#############################################################
#  Cliente de Casa Buckner (Klamath)   ?  ?                  #
#  Traduzido por Ricardo Alvarenga                          #
#############################################################

#{100}{}{You see someone who could be a trapper.}
#{101}{}{You see someone relaxing.}
#{102}{}{You see a townsperson.}
#{103}{}{You see a worker relaxing.}
#{104}{}{You see a person enjoying a drink.}

{100}{}{Você vê alguém que poderia ser um caçador.}
{101}{}{Você vê alguém descansando.}
{102}{}{Você vê um cidadão de Klamath.}
{103}{}{Você vê um trabalhador se descansando.}
{104}{}{Você vê uma pessoa se deliciando com uma bebida.}

#{106}{}{You see a bar patron. They look happy and content.}
#{107}{}{You see a patron. They look well-fed and healthy.}
#{108}{}{You see a patron quietly talking to someone nearby.}
#{109}{}{You see a patron quietly drinking a mug of beer.}
#{110}{}{You see a patron chuckling to themselves over something.}

{106}{}{Você vê os clientes do bar, parecem tão contentes e felizes.}
{107}{}{Você vê um cliente ele parece são e bem alimentado.}
{108}{}{Você vê um cliente bem tranquilo conversando com uma pessoa.}
{109}{}{Você vê um cliente bebendo tranquilamente uma garrafa de cerveja.}
{110}{}{Você vê alguns clientes contando piadas e se sorrindo muito.}

#{120}{}{You?re in the wrong tavern, ain?t ya?}
#{121}{}{We don?t need troublemakers here.}
#{122}{}{Tribals always mean trouble.}
#{123}{}{Jist as long as you don?t get too much firewater in you...}
#{124}{}{(mumble, mumble)?sorry ass outa town...}
#{125}{}{Another one of Dunton?s gang.}
#{126}{}{What are you looking at?}
#{127}{}{Just keep moving.}
#{128}{}{Buy us all a round of drinks, newcomer.}
#{129}{}{Hope you can hold your liquor.}
#{130}{}{You don?t look like a cannibal.}
#{131}{}{No room for the likes of you.}
#{132}{}{Too many strangers lately.}
#{133}{}{Well at least your teeth ain?t filed into points.}
#{134}{}{There goes the neighborhood.}
#{135}{}{Aren?t you supposed to have a bone through your nose?}
#{136}{}{(looks at you and then shakes his head)}
#{137}{}{(makes a subtly rude gesture)}
#{138}{}{You?re probably the one responsible for them brahmin mutilations.}
#{139}{}{Some of our hunters' have gone missing; you?re prob'ly why.}
#{140}{}{There?s been bugmen creeping around town.}
#{141}{}{There?s a spirit in a canyon East of town.}
#{142}{}{Don?t let the Walking Spirit getcha!}
#{143}{}{You better not steal our brahmin.}
#{144}{}{We?re keeping an eye on you.}

{120}{}{Você está no bar errado, não?}
{121}{}{Nós não queremos encrenqueiros por aqui.}
{122}{}{Os tribals sempre trazem problemas.}
{123}{}{Desde que não fique bebado...}
{124}{}{(murmurando, murmurando) ... tenho que sair dessa espelunca.}
{125}{}{Outro da gangue de Dunton.}
{126}{}{O que você está olhando?}
{127}{}{Vaza!}
{128}{}{Pague uma rodada para nós recém chegado.}
{129}{}{Espero que possa aguentar seu licor.}
{130}{}{Você não parece ser um canibal.}
{131}{}{Não há espaço para gente como você.}
{132}{}{Ultimamente anda aparecendo muitos estrangeiros.}
{133}{}{Bem, pelo menos seus dentes não estão afiados.}
{134}{}{Lá se vai a boa vizinhança.} #?
{135}{}{Suponha-se que deveria ter um osso intalado no nariz?}
{136}{}{(Olha para você e depois sacode a cabeça)}
{137}{}{(Faz um gesto grosseiro de forma sutil)}
{138}{}{Estou seguro de que é o responsável pelas multilações dos brahmins}
{139}{}{Alguns de nossos caçadores desapareceram e provavelmente você seja a causa.}
{140}{}{Tem alguns homens-insetos rasteijando nas próximidades da cidade.}
{141}{}{Tem um espirito em um canyon a leste da cidade.}
{142}{}{Não deixe que os espiritos te peguem!}
{143}{}{É melhor que você nem pense em roubar nossos brahmins.}
{144}{}{Ficaremos de olho em você.}

#{150}{}{Nice to see someone new in town.}
#{151}{}{I guess tribals ain?t so bad after all.}
#{152}{}{Buy us a round of drinks!}
#{153}{}{Hello there.}
#{154}{}{You could be Sulik?s twin.}
#{155}{}{You say hello to Sulik yet?}
#{156}{}{Trapping?s good lately.}
#{157}{}{Weather?s getting ready to turn, I guess.}
#{158}{}{Got me a good trapline south of here.}
#{159}{}{If you?re smart, you?ll stay away from the Duntons.}
#{160}{}{If your anxious, try the Bathhouse.}
#{161}{}{Head west to Trapper Town, if you want a place to sack out later.}
#{162}{}{Welcome, friend.}
#{163}{}{Hope you like our city.}
#{164}{}{Klamath is the place to be.}
#{165}{}{Nice to have you here.}
#{166}{}{(raises a mug to you)}
#{167}{}{(winks at you)}
#{168}{}{Don?t go wandering at night.}
#{169}{}{There?s bugmen out in the hills.}
#{170}{}{One of our best trappers is missing.}

{150}{}{Fico feliz em ver alguém novo na cidade.}
{151}{}{Apesar de tudo parece que os tribals não são tão ruins assim.}
{152}{}{Pague-nos uma bebida!}
{153}{}{Olá.}
{154}{}{Você parece ser irmão gemeo de Sulik.}
{155}{}{Você ja disse olá para Sulik?}
{156}{}{Ultimamente o negócio de caçador esta indo bem.}
{157}{}{Me parece que as coisas vão mudar.}
{158}{}{Tenho um bom acampamento de caça ao sul daqui.}
{159}{}{Se você é inteligente, ficará longe dos Dunton.}
{160}{}{Se estiver ancioso vá a Casa de Banho.}
{161}{}{A oeste está o bairro dos caçadores, se procura um lugar para descançar.}
{162}{}{Seja bem vindo, amigo.}
{163}{}{Espero que goste da nossa cidade.}
{164}{}{Klamath é o melhor lugar do mundo.}
{165}{}{Fico feliz em te ver.}
{166}{}{(Levanta uma caneca para você)}
{167}{}{(Pisca pra você)}
{168}{}{Não ande por ai fora a noite.}
{169}{}{Tem homens-insetos nas colinas.}
{170}{}{Um de nossos melhores caçadores esta desaparecido.}

#{201}{}{Well, that sure wet my whistle.}
#{202}{}{Thanks.}
#{203}{}{Mmm-mm, good.}
#{204}{}{Nothing like Buckner?s Best.}
#{205}{}{Thanks for the brew.}
#{206}{}{Huzzah!}
#{207}{}{Tribals know what?s best in life.}
#{208}{}{Thank you.}
#{209}{}{Thanks, friend.}
#{210}{}{I sure needed that. Thanks.}
#{211}{}{Thanks a million!}
#{212}{}{Rather have a bottle in front of me?.}
#{213}{}{Much obliged, friend.}
#{214}{}{Alright!}
#{215}{}{Yes! I was waiting for that.}
#{216}{}{I thought you?d never ask.}
#{217}{}{Thanks, friend.}
#{218}{}{Just like Sulik.}
#{219}{}{Thanks.}
#{220}{}{Yeah!}

{201}{}{Bem, acho que vou molhar o bico.}
{202}{}{Obrigado.}
{203}{}{Mmm-mm, bom.}
{204}{}{Não a nada como Buckner. É a melhor.}
{205}{}{Obrigado pela cerveja.}
{206}{}{Hurraa!}
{207}{}{Os tribals sabem o que é o melhor da vida.}
{208}{}{Muito obrigado.}
{209}{}{Muito obrigado, amigo.}
{210}{}{Tinha certeza que precisava disso, obrigado.}
{211}{}{Um milhão de obrigados!}
{212}{}{Prefiro ter uma garrafa na minha frente?.}
{213}{}{Eu te agradeço, amigo.}
{214}{}{Explendido!}
{215}{}{Yes!, estava esperando por isso.}
{216}{}{Achei que nunca ia perguntar.}
{217}{}{Gracias, colega.}
{218}{}{Assim como Sulik.}
{219}{}{Obrigado.}
{220}{}{Yeah!}