{100}{}{Você vê um monge.}
{101}{}{Esse monge parece ser um comerciante.}

{200}{}{Seja bem-vindo viajante.}
{201}{}{Desejo paz para você.}
{202}{}{O tempo está bom.}
{203}{}{Vá jogar em outro lugar.}

{300}{}{Hi, how can I help you?}
{301}{}{What can you tell me about your order?}
{302}{}{Let's barter.}
{303}{}{Bye.}

{400}{}{Our holy mission is to collect and preserve the sacred relics of the forgotten past. Anyone is welcome here, as long as they don't damage anything.}
{401}{}{Who is your leader?}
{402}{}{What kind of relics?}
{403}{}{He can be found on the third floor. If you wish to learn more about our order, he is the one to talk to.}
{404}{}{All sorts, but most of our Memorabilia consist of ancient tomes. So much information can be obtained from those texts. It is our mission to preserve this knowledge so that a future generation may use it to build a new world of peace and joy.}
{405}{}{Okay.}
{406}{}{Ok.}

{500}{}{Stop that!}
