#{100}{}{You see a Tribal.}
{100}{}{Você vê um Tribal.}
#{101}{}{You see a strong looking man.}
{101}{}{Você vê um homem aparentementeforte.}

#{200}{}{Greetings.}
{200}{}{Saudações.}
#{201}{}{Welcome to the Abbey.}
{201}{}{Bem-vindo à Abadia.}
#{202}{}{Hi.}
{202}{}{Oi.}
#{203}{}{Hello.}
{203}{}{Olá.}
#{204}{}{Are you from the Arroyo tribe?}
{204}{}{Você é da tribo Arroyo?}
#{205}{}{Greetings.}
{205}{}{Saudações.}
#{206}{}{Nice outfit!}
{206}{}{Roupa bonita!}
#{207}{}{Hello, fellow tribal!}
{207}{}{Olá, companheiro tribal!}

#{500}{}{Don't mess with my stuff!}
{500}{}{Não mexa em minhas coisas!}
