XDathz está traduzindo esse arquivo.
{100}{}{Aquela é a Morlis, uma de suas tias... a que nunca gostou de você.}
{101}{}{Por que você fica me encomodando, sobrinho? Não vê que estou ocupada?}
{301}{}{Por que você fica me encomodando, sobrinha? Não vê que estou ocupada?}
{102}{}{Humm, certo. Me desculpe.}
{103}{}{O que é isso? Você sabe que eu tenho muito o que fazer!}
{104}{}{Humm, Mynoc disse...}
{105}{}{Mynoc disse o que? Saia daqui, garoto!}
{106}{}{Isso, humm, você poderia ter uma pedra.}
{107}{}{Eu tenho. Você quer um pouco, não é mesmo?}
{108}{}{Bem, sim.}
{109}{}{Bem... Eu quero três doses de pó curativo. Momentos ruins estão se aproximando, 
 e preciso estar preparada. Traga-os para mim e eu te darei a pedra. Agora, 
 vá pega-los!}
{110}{}{Sim, senhora!}
{111}{}{Não me faça perder tempo. Você tem os pós?}
{112}{}{Sim, estão aqui.}
{113}{}{Humm, eu acho que não.}
{114}{}{Aqui está a pedra. Agora cai fora! Eu não tenho tempo para fofocar.}
{115}{}{Obrigado, Tia Morlis.}
{116}{}{Outra vez me fazendo perder tempo, sobrinho inútil! Como é possível você ser
 o Escolhido?}
{117}{}{Sim, Tia Morlis.}
{118}{}{Ah, Tia Morlis, aqui está os três.}

{150}{}{Tia Morlis, eu estou em uma perigosa missão para salvar nossa vila.
 Minhas chances de sucesso aumentariam se você 
 me desse os pós curativos e a pedra. Não é verdade?}
{151}{}{O que você acha que está fazendo, garoto? Essa não é a forma que o Escolhido deve agir. Agora saia da minha frente!}
{152}{}{Se essa pedra é tão importante assim que você está disposto a desrespeitar o nome do Escolhido, aqui está. Pegue 
 a pedra e saia da minha frente.}
{153}{}{Sim, Tia Morlis.}
{154}{}{Bem... Ah, muito bem. Aqui está a pedra. Tenha uma boa viagem, garoto.}
{155}{}{Não, eu não acredito. Agora pare de desperdiçar meu tempo e dê o fora daqui!}
{156}{}{Sim, Tia Morlis.}


# new add on stuff for time limit
{200}{}{Então você retornou. Encontrou o santo Treze?}
{201}{}{Não, Tia Morlis, Eu...}
{202}{}{Então saia daqui e encontre-o! As pessoas precisam de você!}
{203}{}{Sim, Tia Morlis.}
{204}{}{Bem, você está aqui novamente. Não conseguiu completar sua última missão?}
{205}{}{Sim, Tia Morlis, mas...}
{206}{}{Então dê o fora daqui e não volte até que você tenha completado! Por que perder tempo voltando aqui, quando poderia estar dando continuidade a sua busca!?}
{207}{}{Sim, Tia Morlis.}
{208}{}{O fato de você estar aqui significa que completou a sua missão. Você não perderia seu precioso tempo voltando aqui de mãos vazias, não é mesmo?}
{209}{}{Yes, Aunt Morlis. I mean no, Aunt Morlis. Uh, I've got to go, Aunt Morlis.}
{210}{}{So, child. Once again you stand before me. Are you empty-handed yet again?}
{211}{}{Yes, Aunt Morlis.}
{212}{}{Listen, }
{213}{}{. People are dying, cattle are dying, and crops are failing. Everyone is either hungry, sick, or both. Our time draws near. If you do not find the GECK soon, we are doomed. Do you understand me?}
{214}{}{Yes, Aunt Morlis.}
{215}{}{Then get yourself out of here and find the GECK! People are depending on you!}
{216}{}{Yes, Aunt Morlis.}

#added by killap
{300}{}{Well, I seem to have misplaced the flint. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
{302}{}{Well, I can't seem to find the flint. I'm sure you took it from me when I wasn't looking though. I caught you before. Now off with you! I don't have time to gossip.}
{303}{}{Well... Oh, I'm sorry but I seem to have misplaced the flint. I wish you a safe journey though, child. }

#added by Darek
{304}{}{I already gave you the flint, stupid. Now stop wasting my time and get out of here!}
{305}{}{I already gave you the flint, stupid. Oh well, at least I got my powders. Now off with you! I don't have time to gossip.}
