#You see a regular bookcase.
{100}{}{Você vê uma estante de livros comum.}
#This bookcase has various books on it.
{101}{}{Há vários livros nessa estante.}
#This bookcase has a lot of books from pre-war days. So much information, it's a pity you don't have the time to sit down and read them all.
{102}{}{Há vários livros do pré-guerra nessa estante. Tanta informação, é uma pena você não ter tempo de sentar e ler todos.}
