{100}{}{Você vê Hank.}
{101}{}{Você vê um monge gorducho.} #You see a greasy monk.
{102}{}{Ele está mexendo com um ainda.}

{200}{}{Ei, amigo. Você tem um isqueiro?}
{201}{}{Sim. [Distribua o seu isqueiro para ele.]}
{202}{}{Isto é perfeito. Obrigado!}
{203}{}{Só por curiosidade, o que exatamente você está fazendo aqui?}
{204}{}{Claro. Desde que você me traga um isqueiro, aqui será sua casa.}
{205}{}{[Beba-o.]}
{206}{}{Eu mudei minha mente. Eu não quero qualquer tipo de álcool. Tchau.}
{207}{}{(Você se sente quente e relaxado depois de beber o vinho.)}
{208}{}{Me dê outra, Hank.}
{209}{}{Eu vou agora, tchau.}
{210}{}{(De repente, você se senti como merda, então sua visão começa a ficar confusa. Você cai no chão...)}
{211}{}{[FEITO]}
{212}{}{Não, desculpe.}
{213}{}{Oi, novamente.}
{214}{}{Oi e tchau.}
{215}{}{Este aqui não será de graça. Vai lhe custar $20.}
{216}{}{Claro. Aqui está o dinheiro.}
{217}{}{Nah, eu tive o suficiente. Talvez na próxima.}
{218}{}{(Ele embolsa o dinheiro.) Certo, então, aqui está a bebida.}
{219}{}{Eu vou voltar quando eu tiver mais dinheiro.}

{220}{}{Teve sorte de encontrar um isqueiro?}

{250}{}{Eu gostaria de comprar um pouco do álcool que você tem aqui.}
{251}{}{Basta olhar ao redor. Tome cuidado.}
{252}{}{Claro. $20 por garrafa.}
{253}{}{[Segure-se a ela.]}


{300}{}{Onde eu coloquei meu isqueiro?}
{301}{}{Eu preciso de um isqueiro.}
{302}{}{ALGUÉM PODERIA ME TRAZER UM ISQUEIRO!?}
{303}{}{Uh, oi lá.}
{304}{}{Desculpe, eu não posso conversar com você agora.}

{400}{}{Ooh, olhe todas essas estrelas bonitas!}

{500}{}{Olá. Precisa de alguma coisa?}
{501}{}{Hey, obrigado novamente pelo isqueiro. É melhor do que o meu antigo.}

{600}{}{Vamos nos preparar espiritualmente nesse mosteiro. Você experimentará nesses resíduos, algumas das coisas mais poderosas já vistas.}
{601}{}{Se importa se eu experimentar?}
{602}{}{Parece interessante. Eu preciso ir.}

{700}{}{Isso é muito ruim. Eu perdi o meu recentemente e eu não consigo encontrá-lo em lugar nenhum. Se você algum dia conseguir um, eu ficaria feliz em pegar de suas mãos.}
{701}{}{Claro. Se eu encontrar um te aviso. Tchau.}
{702}{}{Desculpe. Eu sou um pouco colecionador e gosto de manter tudo o que eu encontro. Tchau.}

#dumb dialgoue
{800}{}{Li-ter? Tenho máquina de criar fogo. Ela já me queimou muitas vezes. (Você ergue um isqueiro.)}

{810}{}{Sim, isso é o que eu preciso. Você vai dar para mim?}
{811}{}{Okay. Eu já gosto dele.}
{812}{}{Eu não vou lhe dar}

{820}{}{Agora cuidado para não se queimar também. Tchau!}

