{100}{}{Você vê irmão John.}
{101}{}{Você vê um dos monges mais velhos de Abbey's.}
{102}{}{Você vê um velho monge. Ele parece estar no inicio dos setenta anos.}

{300}{}{Olá, meu jovem.}
{301}{}{Quem é você?}
{302}{}{Você já ouviu falar alguma coisa sobre a GECK ou Vault 13?}
{303}{}{Tchau}

{400}{}{Meu nome é John, eu sou um dos monges mais velhos por aqui.}
{401}{}{Então, qual é o seu trabalho?}
{402}{}{Eu vejo, tchau.}
{403}{}{Bem, eu costumava trabalhar em uma fazenda, mas foi ruim para o meu coração.}
{404}{}{Você tem problemas cardíacos?}
{405}{}{Isso é muito ruim, tchau!}
{406}{}{Sim, eu tenho um coração fraco. Se eu ainda tivesse minhas pílulas para o coração, iria facilitar a minha vida muito mais. É muito difícil encontrar remédios para esse problema no mundo de hoje você sabe.}
{407}{}{Eu poderia ter uma solução para os seus problemas de coração ...}
{408}{}{Lamento ouvir isso, Tchau.}

{410}{}{Thau.}
{411}{}{Você tem? Você está dizendo que você realmente TEM pílulas para o coração?}
{412}{}{Sim, eu tenho. Seria um prazer da-las a você.}
{413}{}{Sim, eu tenho pílulas para o coração. Você pode tê-las por $400.}
{414}{}{Eu só estava brincando. Eu não tenho nenhuma pílula para o coração.}
{415}{}{[Ele toma as pílulas de você.] Obrigado, meu amigo! Aqui, por favor, tome este item como um gesto de gratidão.}
{416}{}{Estou feliz em ajudar, e obrigado pelo item. Tchau!}
{417}{}{(Ele retorna bem bravo, mas depois se acalma) Ok, tudo bem, aqui está o seu dinheiro. Agora me dê as pílulas!}
{418}{}{Eu decidi manter as pílulas para mim. Obrigado pelo dinheiro!}
{419}{}{Foi um prazer negociar com você, Tchau.}
{420}{}{Hmmm, desculpe, eu não tenho. Fale com o Abbot, ele poderia saber de algo.}
{421}{}{Eu vou fazer isso, obrigado. Agora eu tenho algumas outras perguntas.}
{422}{}{Se eu não estivesse tão doente, eu te daria uma surra. AGORA, SAIA DAQUI!}
{423}{}{Tudo bem, ja to indo.}

{500}{}{Obrigado novamente por essas pílulas para o coração, meu amigo. Boa sorte em suas viagens.}

{600}{}{Apenas vá embora, por favor.}

{700}{}{Você mostrou John o quão cruel é o mundo.}
