{100}{}{Você vê um homem baixo e gordo de Shi.}
{101}{}{Você vê o Dr. Wong Yi Tze.}
{102}{}{Você vê um homem baixo e gordo de Shi.}
{103}{}{Posso te ajudar com algo?}
{104}{}{Daghi nu?}
{105}{}{Quem você é?}
{106}{}{Eu ouço que você tem algo diferente.}
{107}{}{Quem é você?}
{108}{}{O que você faz aqui?}
{109}{}{Não, obrigado. Isso é tudo.}
{110}{}{Eu tenho que confessar, Eu não falo sua língua. Talvez você deva falar com o Ken Lee, ele entende muitas línguas diferentes.}
{111}{}{Aagh!}
{112}{}{Eu sou o Dr. Wong. Eu sou o cientista chefe dessa instalação.}
{113}{}{Mais algumas dúvidas, por favor.}
{114}{}{Obrigado. Tchau.}
{115}{}{Eu comando os experimentos científicos que nós criamos e fazemos aqui. Eu sou o encarregado da rede de computadores.}
{116}{}{O que você está planejando?}
{117}{}{Como alguém consegue acesso à rede de computadores?}
{118}{}{Eu tenho outras perguntas.}
{119}{}{Vejo. Tchau.}
{120}{}{Ah, mas se eu te contar sobre os nossos planos, então todo mundo saberá. Eu quero ter certeza que eles são planos secretos, por enquanto.}
{121}{}{Está bem, está bem. Eu tenho outras perguntas.}
{122}{}{Obrigado. Tchau.}
{123}{}{O que você acha se eu enfiar uma arma embaixo do seu nariz e forçar você a me dizer?}
{124}{}{Quem aprender a hackear ele, ou fazer amizade com um de meus homens. Estou brincando, é claro, sobre hackear ele - se você está aqui para fazer isso, eu mandaria alguém atrás de você para te matar. [Ele sorri para mostrar que não existe nenhuma ofensa.]}
{125}{}{Você realmente quer me matar?}
{126}{}{Então você fará objeção se eu acessar o computador?}
{127}{}{Eu tenho algumas outras perguntas.}
{128}{}{Claro que você pode. Tchau.}
{129}{}{Então teria que considerar ele como uma ameaça e te advertir que essa ação talvez seja prejudicial a sua saúde.}
{130}{}{Vamos ver.}
{131}{}{Eu só estava brincando. Eu tenho outras perguntas.}
{132}{}{[Ele sorri] Nós devemos proteger nossa honra, estranho.}
{133}{}{Err, certo. Então você faria objeção se eu acessar o computador?}
{134}{}{Ceeerto. Eu tenho outra pergunta.}
{135}{}{Apostarei. Tchau.}
{136}{}{Se você conseguir convencer meus homens a deixa-lo entrar. Mas tenho certeza que não conseguirá.}
{137}{}{E se eu colocasse uma arma embaixo do seu nariz?}
{138}{}{Ótimo. Bem, eu tenho mais algumas perguntas.}
{139}{}{Hmm. Vejo. Bem, tão longo.}
{140}{}{Ahh, sim! De fato. Eu irei preparar isso com feijões de fava e um bom chianti.}
{141}{}{Você ainda tem isso? Bom. O Chip precisa voltar.}
{142}{}{Isso é um baço humano, você é um doente!}
{143}{}{Você supostamente deve saber que devia servir fígado com esse vinho ao em vez de baço, certo?}
{144}{}{Isso é um baço humano, você sabe.}
{145}{}{Quem é esse Chip? É meu baço agora, e eu o tenho agora para jantar.}
{146}{}{Chip é o verdadeiro dono do baço. Ele estava bêbado e o vendeu para o Lao Chou.}
{147}{}{Ele precisava para sobreviver, você sabe. Isso veio de dentro do corpo dele.}
{148}{}{Então talvez seria melhor eu te matar por ele.}
{149}{}{Um acordo é um acordo. Ele não pode tê-lo. Desculpe, mas nós fizemos um acordo e não é só porque o Chip se arrependeu que ele poderá voltar atrás no acordo.}
{150}{}{-mais-}
{151}{}{Isso é um baço humano? Lao Chou não me disse isso!}
{152}{}{Ainda, por causa da rudeza do mensageiro, eu acredito que manterei todas as partes do acordo. Experimentarei ele em vez disso.}
{153}{}{Diga ao seu amigo para vir aqui amanhã, e eu felizmente o devolverei à ele. Eu só espero que você consiga achar um jeito de recolocar isso dentro dele a tempo.}
{154}{}{Muito bem.}
{155}{}{Ha ha! Sim, eu já vi esse filme antes.
Espere... O que você está dizendo? Você está dizendo que...?}
{156}{}{Sim, é um baço humano.}
{157}{}{Na verdade, eu iria me opor a isso. Você mostrou não ser de bom caráter. De fato, não sei porque ainda estou falando com você . Tenha um bom dia.}
{158}{}{-feito-}
{159}{}{Aiee! Guardas! O intruso está aqui!}
{160}{}{Você com certeza tem um esquema para mim?}
{161}{}{Ken Lee me disse para te dar isso.}
{162}{}{Sim. Agora como que eu pego?}
{163}{}{Não, ainda não.}
{164}{}{Fale com o Ken Lee, e ele te dirá o que vai acontecer no seu futuro. Obrigado. Nós seremos capazes de verificar alguns de nossos testes com esse. Tenho um bom dia.}
{165}{}{Na verdade eu tenho outras perguntas.}
{166}{}{Tão longo.}

#added by killap - expansion pack

#bio specimen begin
{200}{}{I found this corpse stashed over at the Hubologists' base. I believe it might be your missing Xeno Project specimen.}
{201}{}{Yes, it is indeed! My predecessor had much invested in this subject and was quite distressed when it went missing. Although he is now gone, we still may have some use for this specimen. Thank you for retrieving this.}
{202}{}{No problem. See you later.}
{203}{}{Hold on there. No one said I did this for free.}
{204}{}{Correct. Nor did anyone ask you to retrieve the subject. You did that and brought it here of your own volition. Now the stolen subject has been returned to its rightful owners, and we thank you for it.}
{205}{}{That's nice, but I found it, so if you want it back, then it's going to cost you.}
{206}{}{I don't have time for this...Guards!}
{207}{}{[The man looks like he is about to yell, then calms down.] Fine. Here is $500. More than enough for something
 that always belonged to us. Now leave, I'm a busy man.}
{208}{}{Pleasure doing business with you. Bye.}
{209}{}{Oh, shit!}
{210}{}{Let's dance!}
{211}{}{You recover the missing Xeno Program specimen.}
{220}{}{So where is it then? Are you trying to play games with me?}
{221}{}{Sorry, I like to try and hoard as many items as I can. It's kinda my thing.}
{230}{}{I don't have time for this. Come back when you have the specimen.}

{240}{}{[He sniffs the air.] What is that smell? Like rotten meat. [He looks at you and raises an eyebrow.]}
{241}{}{Oh, you must be smelling this body I found. I'm not really sure why I'm carrying it around, to be honest.}
{242}{}{Huh-huh! [You pull out the decomposing corpse] Stinky body! U want?}

{250}{}{Wait a second, that's the subject from the Xeno Project! My predecessor had much invested in this subject and was quite distressed when it went missing. Although he is now gone, we still may have some use for this subject. Thank you.}
{251}{}{No, I do not want— Wait a second, that's the subject from the Xeno Project! My predecessor had much invested in . . . [He notices your blank stare.] Ahem. I mean, thank you for the body. Good job. Don't bring any more though. This is enough. Bye now!}
{252}{}{Bye Bye!}
{253}{}{Me hoard tings. Me hide it.}

#bio specimen end

#dr sheng begin
{300}{}{So what's the deal with this Dr. Sheng?}

{310}{}{How do you know about Dr. Sheng? Eh, I suppose it doesn't matter. Dr. Sheng Ming was a brilliant, but rather unpleasant man who served as my predecessor. He is no longer of any great relevance here.}
{311}{}{Well if he's not relevant to you, then why should *I* care? Let me ask you something else.}
{312}{}{So what happened to him?}

{320}{}{What happened? I'd say he lost his mind. During his experiments he stumbled upon something which I admit was rather remarkable, but it was also extremely dangerous and in no way related to the goals of the Shi. But that did not matter to Dr. Sheng. He became obsessed with his creation and since his experiments were deemed too dangerous to continue here, he decided to take them elsewhere. He left on sabbatical and never returned. That is when I stepped up to fill his position.}
{321}{}{What kind of experiments was Dr. Sheng performing? And what exactly was his big discovery?}
{322}{}{So where is Dr. Sheng now?}

{330}{}{As a man of science, I respect your inquisitive nature. However, I'm afraid I am not willing to share the secrets of the Shi with you, stranger.}
{331}{}{So where is Dr. Sheng now?}
{332}{}{Fine, you keep your fancy secrets. I have secrets of my own, you know. Better secrets than you could ever possibly imagine.}

{340}{}{[He smiles politely.] I'm sure you do. Now if you will excuse me, I have plenty of work that needs doing. Good day.}
{341}{}{[DONE]}

{350}{}{Dr. Sheng was escorted a day or so to the south. He took up residence in some abandoned home, if I'm not mistaken. He was only supposed to be gone for a month, but it's been much longer and we have yet to hear from him. If I were to guess, I would say he was either destroyed by his own creations, or else fell victim to the numerous hazards of the wasteland.}
{351}{}{One of your lead scientists could be dead, and you don't care? You're not even going to go look into it?}
{352}{}{I think I'd like follow up on this Dr. Sheng guy. Could you give me his last known location?}
{353}{}{Well, that's that. Let me ask you something else.}

{360}{}{You'll have to excuse me for seeming so callous about the matter. The truth is, Dr. Sheng was not very popular around here and I do not believe any of us miss him in the slightest.}
{361}{}{I think I'd like follow up on this Dr. Sheng guy. Could you give me his last known location?}
{362}{}{I see. Let me ask you something else.}

{370}{}{I suppose I could... I must admit I am somewhat curious to learn of his fate. Here, I'll mark Dr. Sheng's last known location on your mapping device. But I must warn you that it could prove to be highly dangerous. Of course, it is always dangerous out there in the wastes. Anyway, if you find something of interest, do let me know.}
{371}{}{Thanks, I'll do that. Bye.}
{372}{}{Let me ask you something else.}

{380}{}{Dr. Sheng is still alive and he's created some kind of plant that takes root in and controls human corpses.}

{390}{}{So he has achieved some success with his Xeno Project. How fascinating ... and disturbing. We put an end to his sentient plant experiments here after we lost one our techs. When he left to continue his research, I assumed he'd fall victim to his own creations. Has he managed to assume some form of control over them?}
{391}{}{Yeah, some of them seem to be subservient. They even refer to him as 'master.'}

{400}{}{Hmm… If he were to somehow establish an army of those plant-creatures, that would not bode well for the Shi. I was hoping it wouldn't come to this, but it seems we have no choice but to ensure that Dr. Sheng and his experiments are eliminated. Since he trusts you enough to allow you get close to him, you are the best candidate. Is that something you'd be willing to do? You would be compensated, of course.}
{401}{}{It'd be a pleasure. The guy and his whole operation creeps me out.}
{402}{}{What kind of compensation are we talking here?}
{403}{}{Not interested. Dr. Sheng's your problem—you guys can deal with him.}

{410}{}{The Shi will be most grateful for this service. Once Dr. Sheng and all of his creations have been eliminated, report back to me to receive your reward.}
{411}{}{[DONE]}

{420}{}{I'll leave that up to you. We could grant you weapons, supplies, or money. You may decide once the task is complete.}
{421}{}{All right. I'll do it.}
{422}{}{Not interested. Dr. Sheng's your problem—you guys can deal with him.}
{423}{}{All right. I'll do it. But before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}

{430}{}{Fair enough. We will handle the problem ourselves, but it will have to wait, as we don't have the resources to expend at the moment. Hopefully it won't be too late once we are able to act. In the meantime, if you should change your mind, please let me know.}
{431}{}{Don't count on it. Bye.}
{432}{}{I'll think about it. Bye.}
{433}{}{We'll see. Let me ask you something else.}

{440}{}{I don't suppose you have changed your mind? Will you help us eliminate Dr. Sheng and his creations?}
{441}{}{Nope, I actually wanted to ask you about something else.}
{442}{}{Alright, I'll take him out for you.}
{443}{}{I'll do it, but for a price. You were talking about compensation before?}

{450}{}{Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind… Anyway, you may claim your reward. Are you interested in weapons, supplies, or cash?}
{451}{}{Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind… Anyway, we never asked you to get so involved, but we are grateful. For your troubles, you may claim a reward. Are you interested in weapons, supplies, or cash?}
{452}{}{I'll take weapons.}
{453}{}{I could always use more supplies.}
{454}{}{Just give me money.}
{455}{}{Keep your reward. I only did it because it was the right thing to do.}

{460}{}{Here you go. [He hands various high powered weapons]}
{461}{}{[DONE]}

{470}{}{Here you go. [He hands you various supplies]}
{471}{}{[DONE]}

{480}{}{Here you go. [He hands you $5,000]}
{481}{}{[DONE]}

{490}{}{The Shi appreciates your assistance. Now, I have much work to do. Good day.}
{491}{}{[DONE]}

{500}{}{Before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}
{501}{}{Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}
{502}{}{Dr. Sheng wanted me to give you this plant sample as a gift, but I thought I should warn you that it's infused with his sentience serum. I don't know what it's supposed to do, but I'm pretty sure it won't be good for the Shi.}

{510}{}{Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. Now if there is nothing else, I should be getting back to work.}
{511}{}{Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. But I thought you were going to eliminate Dr. Sheng, not be his courier? In any case, I should be getting back to work.}
{512}{}{Actually, I would like to ask you something else.}
{513}{}{Goodbye.}
{514}{}{Actually, I went through quite a bit of trouble to get that sample for you. I think it's worth a reward.}

{520}{}{Do you, now? The Shi did not solicit this plant sample from you, but if you feel your deeds have earned some compensation, I suppose we could spare this. [He hands you a super stimpak.] Now I really should be getting back to work.}
{521}{}{Actually, I would like to ask you something else.}
{522}{}{Thanks. Bye.}
{523}{}{Really? You call this a reward? I'm gonna knock you around until something more valuable falls out.}

{530}{}{[Takes the seed.] Thank you, I will dispose of this immediately. [He sighs.] I knew Dr. Sheng had lost it, but I didn't think he'd go so far as to try and destroy his own people. He must be dealt with immediately.}
{531}{}{I agree. He's quite the madman.}

{540}{}{*clutches heart* Wahh.}
{541}{}{Urgh.}
{542}{}{Dr. Wong!}

{600}{}{You eliminate Dr. Sheng for the Shi.}
{601}{}{You deliver the plant sample to Dr. Wong.}
{602}{}{You assassinate Dr. Wong.}
#dr sheng end
#end added

