##############################################################################
#John L. Sullivan (Klamath/Broken Hills)
##############################################################################

{100}{}{Você vê um homem alto e grisalho segurando uma caneca de cerveja.}
{101}{}{Você vê John L. Sullivan. O boxeador.}
{102}{}{Você vê um velho alto, com braços musculosos e um bigode perfeitamente preparado cinza.}
{103}{}{Eh, não exagere com álcool.} #Sure now, you've had a wee bit too much already.
{104}{}{Begorah, mas você não é um idiota.} #Begorah, but aren't you a stupid one.
{105}{}{You'd give Torr a good run for his money.} #fiquei em duvida (Você daria Torr uma boa corrida para o seu dinheiro.) e/ou (Você fez suar tinta chinesa em Torr.)
{106}{}{Trilha seu caminho agora, forastero.}
{107}{}{Ugh, outro tribal com cérebro vazio.}
{108}{}{(Ele olha para cima e para baixo de forma avaliadora) Vamos lá, o que temos aqui? Você parece ter alguma idéia da ciência doce , ou o quê?}
{109}{}{Se você fosse um pouco menos arrogante, todos te ajudariam.}
{110}{}{Do que você está falando?}
{111}{}{Uh, sim, que seja, senhor. Vejo você por aí. Talvez.}
{112}{}{Bem, isso é apenas a minha humilde opinião, mas eu posso ver pela maneira como você se move que você poderia melhorar muito com algumas dicas.}
{113}{}{Conselhos? Conselhos de quê?} #Pointers? With what?
{114}{}{Eu não acho que um homem velho como *você* poderia me ensinar alguma coisa. Adeus.}
{115}{}{Sobre a nobre arte, é claro. A 'arte'.}
{116}{}{Uh, a arte? Você está falando de magia!?! Você pode me ensinar feitiços mágicos?} #Uh, the art? Are you talking about magic!?! Can you teach me magic spells?
{117}{}{O que você está falando?} #What are you talking about?
{118}{}{(he grins broadly) Sure and begorah, I could teach you about the wee folk, leprechauns, spriggans, Ban'sidhe and the like. Would you like that?}
{119}{}{That sounds great. Teach away.}
{120}{}{Pugilism, the manly art of hand-to-hand combat. That's what I mean.}
{121}{}{Pugilism, the manly, uh, and womanly art of hand-to-hand combat. That's what I mean.}
{122}{}{Well, I guess I could use some help with that.}
{123}{}{I think I already know more about that than you could possibly teach me.}
{124}{}{(talking to those around you) Did ye hear that? I got myself a live one here. Wants to hear bout the fairies and wee goblins and such. (Hooo, haah, haah-he doubles over in laughter) Here lad, have a drink on me, that's your ticket to the realms of the fay folk.}
{125}{}{(talking to those around you) Did ye hear that? I got myself a live one here. Wants to hear bout the fairies and wee goblins and such. (Hooo, haah, haah-he doubles over in laughter) Here lass, have a drink on me, that's your ticket to the realms of the fay folk.}
{126}{}{All I need is a drink? That's great. Thanks for the tip.}
{127}{}{Somehow, I feel as though you're pulling my leg a bit.}
{128}{}{Well, the drink's just a start. You have to find a fairy mound. (winks at the surrounding patrons)}
{129}{}{What then?}
{130}{}{Well, you sit by the mound and wait until you can see the fairy circle in the dew. If you jump into the fairy ring, you'll be made to dance until dawn with the wee folk. If you survive, they'll steal you away to the land of fairie. (heee, hah, hah, hah)}
{131}{}{Wow, how'd you find this out?}
{132}{}{Somehow, I think you're pulling my leg.}
{133}{}{Oh, it's in me blood, of course. Erin go bragh! (he hefts his tankard aloft)}
{134}{}{Yeah, go brag about Erin. Okay. Thanks for the tips. Hey, let me ask you about something else.}
{135}{}{Somehow, I think you're pulling my leg about this whole thing.}
{136}{}{Uh, well, uh, I can see that you're a busy man. See you later. Goodbye.}
{137}{}{(He looks you over.) Mebbe' so. Mebbe' so. Well then, suit yourself.}
{138}{}{I will. Goodbye.}
{139}{}{Well, mebbe' I am at that. Ne'er-the-less, you were a bonny good sport about it. Here's a beer, on me, for takin' it so well.}
{140}{}{Thanks. Now what were you saying about the sweet science?}
{141}{}{I'm not taking a beer from you. I know more than you could teach me, you old drunk. Goodbye.}
{142}{}{Well, let's go outside and see what I can teach you. You see, it's all about getting your whole wee body to snap just like a whip...}
{143}{}{Uh, huh.}
{144}{}{I don't have time for this right now. Goodbye.}
{145}{}{(Several, sweaty, hours later) So you see what you were doin' wrong then?}
{146}{}{Yes, I do. Thanks for taking the time to help me out, Mr. Sullivan.}
{147}{}{That was great. Let me give you $10 for some brew on me. It's the least I can do.}
{148}{}{Yeah, I guess so. Thanks. Goodbye.}
{149}{}{It was me very own pleasure. You take care o' yourself now. And if anyone asks...you just tell 'em that Fightin' John Sullivan taught you how to fight that way.}
{150}{}{Will do, John. Thanks. Goodbye.}
{151}{}{No, no, no. I could nay take money from ye. It was my very own pleasure to teach what I know. You take darn good care of yourself now. You've got real potential.}
{152}{}{That's great, let me ask you one thing though. Where'd you learn how to fight like that?}
{153}{}{Thanks, John. Goodbye.}
{154}{}{That was a long time ago. When I was a wee young lad, an' dinnay have any sense in me thick head. A place called Reno. You keep your nose clean and stay away from the likes o' that place.}
{155}{}{Where's Reno?}
{156}{}{Oh, okay. Thanks, John. Goodbye.}
{157}{}{I dinnay want to tell ye. You get on now. Just keep out o' harm's way. Goodbye now.}
{158}{}{OK, thanks again. Goodbye, John.}
{159}{}{Keep yourself outa trouble. I've taught you all I know.}
{160}{}{Thanks. You mentioned something about the art before?}
{161}{}{Thanks, John. I sure appreciate it. Goodbye.}
{162}{}{I mean the art of pugilism. I was just pulling your leg about the other stuff. I'd best be getting' back to me cup now. Good luck to ye.}
{163}{}{Oh, okay. Thanks, John. Goodbye.}
{164}{}{John Sullivan has helped you improve your Melee and Unarmed Combat skills.}