#
# 
# Text labels and messages used in OPTIONS.C
#
# (These MUST match "text message" enumeration on the top of OPTIONS.C)
#
# 
# Main option panel
#
# Buttons
{0}{}{SALVAR}
{1}{}{CARREGAR}
{2}{}{OPÇÕES}
{3}{}{SAIR}
{4}{}{OK}
#
# Preferences
#
{100}{}{PREFERÊNCIAS}
{101}{}{DIFICULDADE DO JOGO}
{102}{}{DIFICULDADE DE LUTA}
{103}{}{NÍVEL DE VIOLÊNCIA}
{104}{}{DESTAQUE DO ALVO}
{105}{}{VISÃO DE COMBATE}  # Was: BURNING GUYS
{106}{}{MENSAGENS}
{107}{}{COMBAT TAUNTS}
{108}{}{FILTRO DE TEXTO}
{109}{}{CORRER}
{110}{}{LEGENDAS}
{111}{}{DESTAQUE DO ITEM}
{112}{}{VELOCIDADE DE LUTA}
{113}{}{ATRASO DO TEXTO}
{114}{}{VOLUME DO JOGO}
{115}{}{VOLUME DA MÚSICA}
{116}{}{VOLUME DE EFEITOS}
{117}{}{VOLUME DE FALA}
{118}{}{NÍVEL DO BRILHO}
{119}{}{SENSIBILIDADE}
{120}{}{PADRÃO}
{121}{}{CANCEL}
{122}{}{Afetar a velocidade do jogador}
{123}{}{Discurso Pipboy}
#
# Label text
#
{201}{}{Ligado}             # 1
{202}{}{Desligado}            # 2
{203}{}{Fácil}           #  1
{204}{}{Normal}         #  2
{205}{}{Difício}           #  3
{206}{}{Fácil}          # 1
{207}{}{Normal}         # 2
{208}{}{Brutal}          # 3
{209}{}{Normal}         #  1
{210}{}{Rápido}        #  2
{211}{}{Raro}        # 1
{212}{}{Sempre}          # 2
{213}{}{Apenas alvo}
{214}{}{Nenhum}           # 1
{215}{}{Mínimo}        # 2
{216}{}{Sanguinário}  # 3
{217}{}{Lento}           #  1
{218}{}{Rápido}         #  2
{219}{}{Sempre}
{220}{}{Lots}
{221}{}{Baixo}          # 1
{222}{}{Alto}           # 2
{223}{}{Alto}
{224}{}{Wide}


#
# Pause window
#
{300}{}{OK}
{301}{}{PAUSAR}
#
# Demo versions only
#
{1000}{}{Sorry, the preferences menu is not}  # 1
{1001}{}{available in the demo version.}      # 2