#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used in OPTIONS.C
#
# (These MUST match "text message" enumeration on the top of OPTIONS.C)
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

# ° Main option panel °
#
# Buttons
{0}{}{SALVAR}
{1}{}{CARREGAR}
{2}{}{CONFIG}
{3}{}{SAIR}
{4}{}{OK}
#
# Preferences
#
{100}{}{CONFIG}
{101}{}{DIFICULDADE}
{102}{}{COMBATE}
{103}{}{VIOLÊNCIA}
{104}{}{ALVO EM DESTAQUE}
{105}{}{VISAO DE COMBATE}  # Was: BURNING GUYS
{106}{}{TEXTO COMBATE}
{107}{}{PROVOCAÇÕES NO COMBATE}
{108}{}{FILTRAR LINGUAGEM}
{109}{}{CORRER}
{110}{}{SUBTITULOS}
{111}{}{DESTACAR ITEM}
{112}{}{VEL. COMBATE}
{113}{}{VEL. TEXTO}
{114}{}{VOL. AUDIO GERAL}
{115}{}{VOL. MUSIC/FILME}
{116}{}{VOL. EFEITOS SOM}
{117}{}{VOL. VOZ}
{118}{}{NIVEL DE LUZ}
{119}{}{SENSIBILIDADE MOUSE}
{120}{}{DEFAULT}
{121}{}{CANCEL}
{122}{}{Afetam a velocidade jogador}
{123}{}{Discurso Pipboy}
#
# Label text
#
{201}{}{On}             # 1
{202}{}{Off}            # 2
{203}{}{Facil}           #  1
{204}{}{Normal}         #  2
{205}{}{Dificil}           #  3
{206}{}{Wimpy}          # 1
{207}{}{Normal}         # 2
{208}{}{Áspero}          # 3
{209}{}{Normal}         #  1
{210}{}{Fastest}        #  2
{211}{}{Verbose}        # 1
{212}{}{Brief}          # 2
{213}{}{Targeting Only}
{214}{}{None}           # 1
{215}{}{Minimal}        # 2
{216}{}{Maximum Blood}  # 3
{217}{}{Slow}           #  1
{218}{}{Faster}         #  2
{219}{}{Always}
{220}{}{Lots}
{221}{}{Quiet}          # 1
{222}{}{Loud}           # 2
{223}{}{Brighter}
{224}{}{Wide}


#
# Pause window
#
{300}{}{OK}
{301}{}{PAUSAR}
#
# Demo versions only
#
{1000}{}{Sorry, the preferences menu is not}  # 1
{1001}{}{available in the demo version.}      # 2