#
#   Messages from skilldex.c
#
{100}{}{PERÍCIAS}
{101}{}{CANCEL}
{102}{}{FURTIV.} #SNEAK #SIGILOSO #Furtividade
{103}{}{ARROMB.} #Lockpick #Gazua #Arrombamento
{104}{}{ROUBO} #Steal
{105}{}{ARMAD.} #Traps
{106}{}{P. SOC.} #First aid
{107}{}{MEDICINA} #Doctor #Medicina #médico
{108}{}{CIÊNCIA} #Science
{109}{}{REPARO} #Repair