#You see a grave marker.
{100}{}{Você vê uma lápide.}
#The grave marker reads: 
{101}{}{Está escrito na lápide: }
#"Here lies Brother Gregory. A man who knew no limits."
{102}{}{"Aqui jaz Irmão Gregory. Um homem que não conhecia limites.}
#"Aunt Patty. Good riddance indeed."
{103}{}{"Tia Patty. Certamente já vai tarde."}
#"Here lies Per Joner. Died one rock too short."
{104}{}{Aqui jaz Per Joner. Morreu faltando uma pedra.}
#
{105}{}{"Here lies Father Michael. Founder, Father, Fighter."}
#
{106}{}{"An Atheist. All dressed up and no place to go."}
#
{107}{}{"Here lies Johnny Yeast. Pardon me for not rising."}
#
{108}{}{"Mary Jane. Loving wife and mother."}
#
{109}{}{"'Checkmate!' was the call to dear old Jon, On the chessboard of life, He was just a pawn.}
#
{110}{}{"Sir John Strange, here lies an honest lawyer, and that is Strange."}
#
{111}{}{"Tears cannot restore her -- therefore I weep."}
#
{112}{}{"Every day in every way, I am getting better and better."}

#
{250}{}{There are no markings on this grave marker.}
#
{251}{}{The grave marker is too cracked and broken to be read.}
#
{252}{}{The name on the grave marker reads John Doe.}
#
{253}{}{The name and date on this headstone have been worn off by the weather.}
