#Geovany esta traduzindo....
{100}{}{Você vê Mr. Cheater.}
{101}{}{Ele ainda se parece com um trapaceiro.}
{200}{}{Olá eu sou Mr. Cheater. Como posso ajudá-lo?}
{201}{}{Você vai raptar minha tribo?}
{202}{}{Will you put me on the Shi quest?}
{203}{}{Will you put me on the Elron quest?}
{204}{}{Will you put me on the Brotherhood quest?}
{205}{}{Make it so I've already been to the military base.}
{206}{}{I've kidnapped your tribe.}
{207}{}{I've put you on the Shi quest.}
{208}{}{I've put you on the Elron quest.}
{209}{}{I've put you on the Brotherhood quest.}
{210}{}{Now you have been to the military base.}
{211}{}{Thank you, Mr. Cheater.}