{100}{}{Você está vendo um terminal de computador.}
{101}{}{You see Darion's computer terminal.}
{102}{}{Você está vendo um terminal de computador padrão. Parece ser funcional e pronto para a acessar.}
{103}{}{You access the computer and quickly scan all available files. Among some personal journal
 entries, you find several detailed reports on the NCR. It seems there is a spy on their council.
 You copy the reports to a holodisk.}
{104}{}{Você está tendo dificuldade para acessar os arquivos.}
{105}{}{Concluído.}
{106}{}{Além da informação sobre o espião NCR, o computador não contém mais nenhuma informação útil.}
{107}{}{Concluído.}