{100}{}{Você está vendo um terminal de computador.}
{101}{}{You see the control center computer terminal.}
{102}{}{Você está vendo um terminal de computador padrão. Parece ser funcional e pronto para a acessar.}
{103}{}{O terminal indica que o campo de força de segurança na entrada do vault foi ativada
 com sucesso após a energia ter sido restaurada.}
{104}{}O terminal indica que todos os sistemas de segurança do vault estão offline, devido à falta de 
 energia.}
{105}{}{Gire o campo de força para desligar.}
{106}{}{Gire o campo de força para ligar.}
{107}{}{Concluído.}
{108}{}{Você dará o comando para desativar o campo de força.}
{109}{}{Concluído.}
{110}{}{Você dará o comando para ativar o campo de força.}
{111}{}{Concluído.}

{112}{}{O terminal indica que o campo está desligado por acionamento manual.}
{113}{}{O terminal indica que o sistema de campo tenha sido comprometida.}
{114}{}{O terminal indica que o sistema está fora de campo.}