{100}{}{Você está vendo um terminal de computador.}
{101}{}{You see Darion's computer terminal.}
{102}{}{Você está vendo um terminal de computador padrão. Parece ser funcional e pronto para a acessar.}
#Traduzido por Rsalvarenga na revisão.
#You access the computer and quickly scan all available files. Among some personal journal
#entries, you find several detailed reports on the NCR. It seems there is a spy on their council.
#You copy the reports to a holodisk.
{103}{}{Você acessa rapidamente o computador e verificar todos os arquivos disponíveis. 
Entre alguns diários pessoais, você encontra vários relatórios detalhados sobre a NCR. 
Parece que há um espião em seu conselho. Você copia os relatórios para o holodisk.}
{104}{}{Você está tendo dificuldade para acessar os arquivos.}
{105}{}{Concluído.}
{106}{}{Além da informação sobre o espião NCR, o computador não contém mais nenhuma informação útil.}
{107}{}{Concluído.}