#You see trader Bill.
{100}{}{Você vê o comerciante Bill.}
#You see an older looking merchant.
{101}{}{Você vê um comerciante de aparência envelhecida.}

#Hello there, traveler. Name's Bill. What can I get for you?
{200}{}{Olá, viajante. Meu nome é Bill. O que posso fazer por você?}
#Welcome back. Need something else?
{201}{}{Bem-vindo! Precisa de mais alguma coisa?}
#Let's barter.
{202}{}{Vamos negociar.}
#I hear you're the man to talk to about caravans.
{203}{}{Ouvi dizer que você é o cara com quem falar sobre caravanas.}
#Nevermind. Bye.
{204}{}{Deixa pra lá. Tchau.}

#Say, I've noticed a lot of old equipment and items have been collected here at the Abbey.
#I don't suppose you've found anything...special, during your time here?
{210}{}{Então, eu percebi que vários equipamentos e itens antigos foram recolhidos aqui em Abbey. Talvez você tenha encontrado algo...especial enquanto esteve por aqui?}
#Heh, so you noticed that, huh? Yeah, the Abbey folks have a bit of a fascination with anything pre-war,
#especially if it's tech related. They've formed some kind of kooky religion around it. I don't quite understand it,
#myself, but they're nice people and they pay good money for anything pre-war I manage to get my hands on. But anyway,
#as for something special...hmm, [He glances over at Marcus.] It's funny you should ask, I just might have something that
#would interest your friend here.
{211}{}{Heh, então você percebeu, heim? É, o povo de Abbey tem uma pequena fascinação por qualquer coisa pré-guerra, especialmente tecnologia. Isso se tornou meio que uma religião excêntrica. Não entendo muito bem, mas são boas pessoas e pagam bom dinheiro por qualquer coisa pré-guerra que eu consigo encontrar. Enfim, sobre algo especial...hmm, [Ele encara Marcus.] Engraçado você perguntar, posso ter algo aqui que pode ser interessante para seu amigo.}
#Heh, so you noticed that, huh? Yeah, the Abbey folks have a bit of a fascination with anything pre-war,
 especially if it's tech related. They've formed some kind of kooky religion around it. I don't quite understand it,
 myself, but they're nice people and they pay good money for anything pre-war I manage to get my hands on. But anyway,
 as for something special...hmm, [He glances over your party.] Sorry, I don't think I have anything special you'd find
 useful right now.
{212}{}{Heh, então você percebeu, heim? É, o povo de Abbey tem uma pequena fascinação por qualquer coisa pré-guerra, especialmente tecnologia. Isso se tornou meio que uma religião excêntrica. Não entendo muito bem, mas são boas pessoas e pagam bom dinheiro por qualquer coisa pré-guerra que eu consigo encontrar. Enfim, sobre algo especial...hmm, [Ele olha seu grupo.] Desculpe, acho que não tenho nada de especial agora que você acharia útil.}
#Oh, well. Let's see what you have in stock instead.
{213}{}{Está bem... Então vamos ver o que você tem em estoque.}
#That's alright. Let me ask you something else.
{214}{}{Tudo bem. Quero perguntar outra coisa.}
#Such as?
{215}{}{Como o quê?}
#You see, a caravan came through here not too long ago, claiming to have come up from the deep south. Said they'd
 been attacked by some of them vile mutants (turning to Marcus) no offense, big guy. Anyway, they did a lot of bragging
 about how they'd wasted all the muties. Claimed there'd been nearly a dozen of 'em, and I called bullshit. But it turns
 out they had some proof.
{216}{}{Veja, uma caravana passou por aqui não faz muito tempo, dizendo ter vindo do sul distante. Disseram que foram atacados por alguns desses mutantes cruéis (virando para Marcus), sem ofensa, grandão. De qualquer modo, ficaram se gabando sobre como acabaram com os mutantes. Afirmaram que eram quase uma dúzia, e eu disse que era mentira. Mas eles tinham provas.}

#new for RP 1.3
#Yeah? What was that?
{217}{}{Ah é? O que era?}
#A hulking set of mutant armor they'd managed to salvage off one of the corpses. Of course, for all I know, they
 stole it off the bones of some long dead mutie they'd stumbled upon in the wastes, but who knows? Anyway, they weren't
 eager to keep lugging the heavy thing around, so they offered it to me for dirt cheap. I didn't know what I'd ever do
 with it, but I figured a deals a deal.
{218}{}{Uma gigantesca armadura de mutante que eles conseguiram recuperar de um dos corpos. Claro, pelo que sei, eles podem ter roubado dos ossos de um mutante morto há muito tempo com que eles trombaram no deserto, mas quem sabe? Enfim, eles não estavam muito afim de carregar esse negócio pesado por aí, então me venderam por uma pechincha. Eu não tinham ideia do que fazer com isso, mas acho que negócio é negócio.}
#end new and begin reordering
#Well, I'm sure Marcus here could benefit from this. How much for it?
{219}{}{Tenho certeza de que o Marcus aqui pode se beneficiar disso. Quanto por ela?}
#That's interesting. Well, Marcus here is tough enough. I don't think we'll be needing that item. Let me ask you something else.
{220}{}{Interessante. Bem, o Marcus aqui é resistente o suficiente. Não acho que ele precise disso. Quero perguntar outra coisa.}
#Well, this bad boy could easily be melted down to make three or four sets of metal armor. Let's say $3000.
{221}{}{Bem, essa fera aqui pode facilmente ser derretida para fazer três ou quatro kits de metal armor. Digamos $3000.}
#I've got enough for that.
{222}{}{Tenho o suficiente para isso.}
#I think I'll pass for right now. Let me ask you something else.
{223}{}{Acho que vou passar por enquanto. Quero perguntar outra coisa.}
#Alright then. This is going to take two of us to move this thing, so let me help you fit it to your friend here.
{224}{}{Ok. Vai precisar de nós dois para carregar essa coisa, vou te ajudar a encaixar ela no seu amigo aqui.}
#[Done]
{225}{}{[Feito]}
#Hey, this fits nicely!
{226}{}{Hey, ela coube muito bem!}
#end

#I might know a thing or two. What would you like to know?
{300}{}{Posso saber de uma ou outra coisa. O que você quer saber?}
#How often do you get resupplied?
{301}{}{Com que frequência você é reabastecido?}
#Are the caravans hiring?
{302}{}{As caravanas estão contratando?}
#On second thought, I have to go.
{303}{}{Pensando bem, tenho que ir.}
#I get a new shipment of supplies twice a month. Frankly, I wish they'd come more often, but we're only on a
 minor trade route so I guess this is the best we can get.
{304}{}{Recebo uma nova leva de suprimentos duas vezes por mês. Honestamente, queria que fosse mais frequente, mas somos uma rota de comércio menor, acho que isso é o melhor que podemos ter.}
#I'm not quite sure. Usually, the ones that stop by here are pretty well equipped and not really interested in
 hanging around very long. But if you're looking to hook up with one of em, I'd head over to Redding or even down to NCR.
 They've got pretty active caravans and good help is always wanted.
{305}{}{Não tenho certeza. Geralmente, os que param por aqui são bem equipados e não muito interessados em ficar muito tempo. Mas se você quiser ficar com uma delas, eu iria para Redding ou talvez para NCR. Lá as caravanas são bastante ativas e ajuda é sempre bem-vinda.}
#Interesting. I was curious about something else.
{306}{}{Interessante. Estou curioso sobre outra coisa.}
#Thanks. Let's barter.
{307}{}{Obrigado. Vamos negociar.}
#Well, thanks for the information. See you around.
{308}{}{Bem, obrigado pela informação. Até mais.}

#Found everything you need?
{400}{}{Encontrou tudo de que precisava?}
#Actually, I'd like to take another look at your goods.
{401}{}{Na verdade, quero dar mais uma olhada nos seus produtos.}
#Yes I did. See you around.
{402}{}{Sim. Até mais.}
