#You see a stout nun.
{100}{}{Você uma freira robusta.}
#You see Elaine.
{101}{}{Você vê Elaine.}
#You still see her.
{102}{}{Você ainda a vê.}

#Greetings!
{200}{}{Saudações!}
#Hi, what's your name?
{201}{}{Olá, qual seu nome?}
#What can you tell me about the Abbey?
{202}{}{O que você pode me dizer sobre Abbey?}
#Bye.
{203}{}{Tchau.}

#If you want to know more about our order, talk to the Abbot. You can find him in his quarters on the third floor.
{300}{}{Se você quiser saber mais sobre a ordem, converse com Abbot. Você vai encontrá-lo em seus aposentos no terceiro andar.}
#I see. A few more questions...
{301}{}{Entendo. Mais algumas perguntas...}

#Of course. What would you like to know?
{400}{}{Claro. O que você quer saber?}
#What is your name?
{401}{}{Qual seu nome?}
#Nothing really, bye.
{402}{}{Na verdade nada, tchau.}
#What can you tell me about the Abbey?
{403}{}{O que você pode me dizer sobre Abbey?}

#My name is Elaine.
{500}{}{Meu nome é Elaine.}
#I see. A few more questions...
{501}{}{Entendo. Mais algumas perguntas...}

#Hey! Before you go, perhaps you could do me a favor. I'm supposed to bring this machine part to Max in the
 basement copy room. But you see, my left knee has been acting up lately, and it's a real pain for me to go up and down
 all those stairs. Would it trouble you too much to bring him this part for me?
{600}{}{Ei! Antes de ir, talvez você possa me fazer um favor. Eu tenho que levar essa peça para Max na sala de cópia do porão. Mas, sabe, meu joelho esquerdo está doendo ultimamente, e é doloroso para mim ir para cima e para baixo naquelas escadas. Seria muito incômodo levar a peça para mim?}
#Sure.
{601}{}{Claro.}
#Sorry, I don't have time for this. Bye.
{602}{}{Desculpe, não tenho tempo. Tchau.}
#Do I look like your personal delivery service? Do it yourself, you fat lazy bitch. Bye.
{603}{}{Eu pareço ser seu serviço de entregas pessoal? Vá você mesma, sua gorda folgada. Tchau.}  #new in RP 1.3

#Thanks! Here's the part. The copying room is in the basement. Just use the stairs directly behind Brother Matthew
 in the chapel area.
{604}{}{Obrigado! Aqui está a parte. A sala de cópia fica no porão. É só usar as escadas bem atrás do Irmão Matthew na capela.}
#Not a problem. [You take the part.] I'll bring it down to Max right away.
{605}{}{Sem problemas. [Você pega a peça.] Vou levar para o Max agora mesmo.}

#dumb dialgoue
#Me
{700}{}{Eu }
#. Who you?
{701}{}{. Você ser?}

#Hehe. That pretty name.
{710}{}{Hehe. Esse nome bonito.}
#Bye!
{711}{}{Tchau!}

#You're a special little guy aren't you? Could you do me a BIG favor and be my special helper today?
{720}{}{Você é um carinha especial, não é mesmo? Pode me fazer um GRANDE favor e ser meu ajudante especial hoje?}
#You're a special little gal aren't you? Could you do me a BIG favor and be my special helper today?
{721}{}{Você é uma mocinha especial, não é mesmo? Pode me fazer um GRANDE favor e ser minha ajudante especial hoje?}
#Me special. Me help.
{722}{}{Eu especial. Eu ajudar.}
#Me no wanna help.
{723}{}{Eu não querer ajudar.}

#Really? Great! Please give this machine part to Max in the copying room. He can be found in the BASEMENT. Okay?
{730}{}{Sério? Ótimo! Por favor entregue essa peça para Max na sala de cópia. Ele pode ser encontrado no PORÃO. Ok?}
#I no let you down!
{731}{}{Eu não vou desapontar!}

#You keep on truckin' now.
{740}{}{Continue perseverando.}