# Matheus Reis traduzindo

# You see a Tough Guard.
{100}{}{Você vê um guarda durão.}
# You see an impressively muscled, but aging guard with sun burnt skin. He must have been quite something in his
# prime. His piercing gaze seems to follow you everywhere.
{101}{}{Você vê um guarda velho, mas impressionantemente musculoso com a pele queimada pelo sol. Ele deve ter sido bastante coisa no seu auge. Seu olhar penetrante parece seguí-lo em todos os lugares.} #Pode ser na juventude, ficou meio tenso achar uma tradução legalzinha

 # Hi there, traveler. Welcome to the Abbey. Keep your nose clean and we'll get along just fine.
{200}{}{Olá, viajante. Bem-vindo(a) a Abbey. Mantenha-se longe de confusão e nós vamos conviver muito bem.}
#  I'm watching you, slaver. One wrong move and you'll be tainting our graveyard for the rest of eternity.
# I wouldn't wish that on you, and I'm fairly sure you wouldn't enjoy that either, so don't get any funny ideas in that
# warped brain of yours.
{201}{}{Estou de olho em você, traficante de escravos. Um movimento errado e você irá apodrecer em nosso cemitério por toda a eternidade. Eu não gostaria que isso acontecesse, e tenho quase certeza de que você também não, então não tenha nenhuma idéia engraçadinha nesse seu cérebro deformado.}
 # Who are you?
{202}{}{Quem é você?}
# Where can I barter for some supplies?
{203}{}{Onde posso negociar por suprimentos?}
# Somebody is digging up graves, why don't you do anything about it?
{204}{}{Alguém está cavando túmulos, Por que você não faz nada a respeito?}
# I heard something about animals in the basement. Know anything about that?
{205}{}{Eu ouvi algo sobre animais no porão. Sabe alguma coisa sobre isso?}
# I think it's time I send you to a grave. Let's dance, old man.
{206}{}{Eu acho que é hora de mandá-lo para um túmulo. Vamos dançar, velho.}
# Nevermind. Goodbye.
{207}{}{Deixa pra lá. Adeus.}

# Nobody... Just an old retired caravan guard. A lot of people mistake me for some sort of sheriff because I'm
# the closest thing resembling the law in these parts, but I'm not. I just look out for this community because I think
# it's worth protecting.
{300}{}{Ninguém... Apenas um velho guarda de caravana aposentado. Um monte de gente me confunde com algum tipo de xerife porque sou a coisa mais próxima que se assemelha à lei por estas bandas, mas eu não sou. Eu só cuido desta comunidade pois acho que vale a pena protegê-la.}
# And in return the community looks out for me. I get some complimentary booze from the monks, Peterson makes
# sure I'm fed and Bill makes sure I've got ammo and stims. Not a bad retirement gig, if you ask me.
{301}{}{E em troca a comunidade cuida de mim. Eu recebo algumas bebidas de cortesia dos monges, Peterson certifica-se de que sou alimentado e Bill garante que eu tenha munição e stims. Não é um trabalho ruim de aposentadoria, caso queira saber.}
# I'm the one keeping you in line, and that's all you need to know. Now get on with your business and leave me
 alone.
 {302}{}{Eu sou o que mantém você na linha, e isso é tudo que precisa saber. Agora vá em frente com o seu negócio e me deixe em paz.}
 # That is a nice arrangement. Let me ask you something else.
{303}{}{Este é um ótimo arranjo. Deixe-me perguntar algo mais.}
# Whatever, goodbye.
{304}{}{Tanto faz, adeus.}
# You think you can keep me in line? Let's see you try it, old man. This should be fun.
{305}{}{Você acha que pode me manter na linha? Vamos ver você tentar, velho. Isso será divertido.}

# You can find Bill, our resident trader, in the building across from here. Other than that, you ought to go
# to Percy's Survival Gear Locker at the Junkyard in Gecko or Happy Harry's in the Courtyard at Vault City.
{400}{}{Você pode encontrar Bill, nosso comerciante residente, no prédio em frente. Fora isso, você deve ir ao Percy's Survival Gear Locker no Junkyard em Gecko ou Happy Harry's no Courtyard em Vault City.}
 # Good to know. I have another question.
{401}{}{Bom saber. Eu tenho outra pergunta.}
# Thanks, bye
{402}{}{Obrigado, tchau.}

# If someone is poor or greedy enough to try and dig up graves, that's their business. It's not like the dead can
# use what they're buried with anyway. Not my problem... I'm not losing any sleep over it.
{500}{}{Se alguém é pobre ou ganancioso o suficiente para tenta cavar túmulos, este é o negócio deles. De qualquer modo, não é como se os mortos pudessem usar o que está enterrado com eles. Não é problema meu... Não vou perder nenhum sono por isso.}
 # Let me ask you something else.
{501}{}{Deixe me perguntar algo mais.}
# Bye.
{502}{}{Tchau.}
 
 # Yes, and Brother Thomas is missing. He was a smart man, but a bit foolhardy. I don't know what's down there,
 but I don't think it's just a bunch of rats and radscorpies.
{600}{}{Sim, e o irmão Thomas está desaparecido. Ele era um homem inteligente, mas um pouco audacioso. Eu não sei o que há lá embaixo, mas eu não acho que seja apenas um monte de ratos e radscorpies.}
 # Yes, and Brother Thomas is missing. I don't know what's down there, but I don't think it's just a bunch of rats
 and radscorpies. Why don't you find out, tough guy?
{601}{}{Sim, o irmão Thomas está perdido. Eu não sei o que há ali embaixo, mas eu não acho que seja um monte de ratos e radscorpies. Por que não tente descobrir, valentão?}
# So why don't you go look?
{602}{}{Então por que você não vai lá dar uma olhada?}
# You're the tough guy around here, aren't you? Why don't you drag your ass down there?
{603}{}{Você é o cara durão por aqui, não é? Por que não arrasta essa sua bunda lá pra baixo?}

# It's a bit embarrassing, but after spending so much time outdoors with the caravans, I get very nervous when I
# go underground. The walls just close in on me and I have trouble breathing... Maybe you can find out what happened to
# Brother Thomas?
{610}{}{É um pouco embaraçoso, mas depois de passar tanto tempo ao ar livre com as caravanas, eu fico um pouco nervoso quando vou ao subsolo. As paredes simplesmente fecham-se sobre mim e eu sinto dificuldades pra respirar... Talvez você possa descobrir o que aconteceu com o irmão Thomas?}
# I'll see what I can do. In the meantime, let me ask you something else.
{611}{}{Verei o que posso fazer. Entretanto, Deixe-me te perguntar outra coisa.}
# Bye.
{612}{}{Tchau.}
# I am a tough guy, which is why I'm gonna kick your ass.
{613}{}{Eu sou um cara durão, é por isso que vou chutar seu traseiro.}

# What else do you want to know?
{700}{}{O que mais você quer saber?}

# It's good to see you again.
{800}{}{É bom te ver novamente.}
# I'm keeping my eye on you
{801}{}{Estou de olho em você.}
