# Matheus Reis traduzido.
# You see Jack, the Abbey's medic.
{100}{}{Você vê Jack, o médico de Abbey.}
# He has a red cross on his shoulder.
{101}{}{Ele tem uma cruz vermelha no ombro.}

# If you are injured, talk to me.
{200}{}{Se você for ferido, fale comigo.}

# How can I help you?
{300}{}{Como posso ajudá-lo?}
# I'm injured, can you help me?
{301}{}{Estou ferido, você pode me ajudar?}
# [Drool.]
{302}{}{[Babar.]} # Eu acho que essa é uma das opções de diálogo sugerindo que você babe pro médico saber sua necessidade, então babar deve estar correto (Ao contrário de baba).
# So, what do you do here at the Abbey?
{303}{}{Então, o que você faz aqui em Abbey?}
# Bye.
{304}{}{Tchau.}

# It is done!
{400}{}{Está feito!}
# Thanks.
{401}{}{Obrigado.}
# Stop that!
{402}{}{Pare com isso!}
# [GO ON]
{403}{}{[CONTINUAR]}
# [LEAVE]
{404}{}{[SAIR]}
# STOP IT! STOP IT! STOP IT!
{405}{}{PARE! PARE! PARE!}
# [GO ON]
{406}{}{[CONTINUAR]}
# [STOP]
{407}{}{[PARAR]}
# (Suddenly, Jack starts to melt.) I'M MELTING, I'M MELTING, OH WHAT A WORLD...
{408}{}{(De repente, Jack começa a derreter.) ESTOU DERRETENDO, ESTOU DERRETENDO, OH QUE MUNDO...}
# What the fu...
{409}{}{Que porr...}

# Hey, don't steal my medical supplies!
{500}{}{Hey, não roube meus suprimentos médicos!}
# You gain 200 experience points for making Jack melt. Are you happy now, you sick fuck?
{501}{}{Você ganha 200 pontos de experiência por fazer Jack derreter. Você está feliz agora, seu doente?}

# I'm a doctor. I've been tending to the people of this Abbey for about, oh, fifteen years now, I believe.
{600}{}{Eu sou um médico. Tenho cuidado de pessoas deste Abbey por cerca de, oh, quinze anos, acredito.}
# I see. That's a lot of years to study all the pre-war medical books in the Abbey's library. You must be quite the doctor.
{601}{}{Deu pra ver. Isso é bastante tempo para estudar todos os livros medicinais de antes da guerra na biblioteca de Abbey. Você deve ser absolutamente o médico.}
# Where did you get all your medical equipment?
{602}{}{De onde você tirou todo o seu equipamento médico?}
# Interesting. I think I will be leaving now.
{603}{}{Interessante. Acho que vou saindo agora.}
# [He frowns.] I fancy myself a fine doctor, but I can't credit the books for that since I'm not even allowed to...never mind, I won't get into that. My father was a doctor, and he passed his knowledge down to me.
{604}{}{[Ele franze a testa.] Eu me imagino um bom médico, mas eu não posso creditar os livros por isso desde que eu não estou autorizado a...deixa pra lá, I won't get into that. Meu pai foi um médico, e ele passou seu conhecimento para mim.}
# Ah, I see.
{605}{}{Ah, Deu pra ver.}

# Some of these meds I received from my father. Most of the rest were already here at the Abbey.
{700}{}{Alguns desses remédios recebi do meu pai. O restante já estavam aqui em Abbey.}
# Interesting, bye.
{701}{}{Interessante, tchau.}
# Do you think you could give me some of your meds? You seem to have plenty to spare.
{702}{}{Você acha que poderia me dar alguns de seus remédios? Você parece ter muito de sobra.}
# You want me to just *give* them to you? What makes you think you deserve them more than the people of the Abbey?
{703}{}{Você quer que eu os *dê*? O que faz você pensar que merece mais que o povo de Abbey?}
# Because I tend to get hurt...a lot.
{704}{}{Porque eu tendo a me machucar...bastante.}
# Because I'm on a holy quest to find a Garden Of Eden Creation Kit. You see, my entire village will perish if
# I don't find this device in time. Your people, on the other hand, seem to live a peaceful life without much need for so
# much healing equipment. I'm not asking for a lot, even the smallest amount you could give me would help me greatly.
{705}{}{Porque eu estou em uma missão sagrada para encontrar um Garden Of Eden Creation Kit. Veja, toda a minha aldeia morrerá se eu não achar este dispositivo a tempo. Seu povo, por outro lado, parece viver uma vida tranquila sem muita necessidade de muito equipamento de cura. Não estou pedindo muito, até mesmo a menor quantidade que você poderia me dar ajudaria muito.}
# [He ponders over your words for a moment, then nods.] Alright, I'll give you some of our excess medical supplies.
 It sounds like you're gonna need 'em. Here. [He hands them to you.] Good luck, wanderer.
{706}{}{[Ele pondera sobre suas palavras por um momento, depois balança a cabeça.] Certo, vou lhe dar um pouco do nosso excesso de suprimentos médicos. Parece que você vai precisar deles. Aqui. [Ele entregas ele para você] Boa sorte, viajante.}
# Thanks, Jack. You're a true savior of the wastes. Bye.
{707}{}{Obrigado, Jack. Você é um verdadeiro salvador do mundo. Tchau.}

# Then perhaps you should learn to be more careful. Sorry, I'm not going to just give away the Abbey's medical supplies.
{708}{}{Então talvez você deva aprender a ser mais cuidadoso. Desculpe, Não irei simplesmente dar os suprimentos médicos de Abbey.}
# Fine. GOODBYE
{709}{}{Ótimo. ADEUS.}

# I can't talk right now.
{800}{}{Não posso conversar agora.}
# Sorry, I'm in the middle of something now. Come see me later.
{801}{}{Desculpe, estou meio ocupado agora. Venha me ver mais tarde.}
# Hello again.
{802}{}{Olá novamente.}
