# You see a bespectacled young monk.
{100}{}{Você vê um jovem monge de óculos.}

# You see Brother Jason.
{101}{}{Você vê o Irmão Jason.}

# This monk seems to be brooding.
{102}{}{Este monge parece estar melancólico.}

# [The young monk quickly pockets a deck of "Tragic" cards as you approach.] What do you want?
{200}{}{[O jovem monge esconde rapidamente no bolso um baralho de "Tragic" enquanto você se aproxima.] O que você quer?} 

# Nothing from you. Bye.
{201}{}{De você, nada. Adeus.}

# I want to know why you just hid that card deck from me.
{202}{}{Eu quero saber por que você escondeu esse baralho quando me viu.}

# I don't know what you're talking about. I don't have any card deck.
{210}{}{Eu não sei do que você esta falando. Eu não tenho baralho algum.}

# Don't lie to me. I saw you put it away in your pocket. I just wanted to know why.
{211}{}{Não minta pra mim. Eu vi você guardar em seu bolso. Eu só quero saber por quê.}

# Alright, whatever you say. See ya.
{212}{}{Tudo bem, como quiser. Falou.}

# Look, don't tell anyone, alright? We're not suppose to "use" pre-war relics, just worship them. But these Tragic
 cards are so damn cool. [He seems to get lost in another world as he gazes lovingly at the deck. After a moment,
 he looks up at you.] Oh, sorry. I'm Brother Jason by the way. I, uh, don't suppose you play Tragic?
{220}{}{Olha, não conte pra ninguém, ok? Nós não deveriamos "usar" relíquias de antes da guerra, apenas louvá-las. Mas estas
cartas de Tragic são muito loucas. [Ele parece estar perdido em outro mundo enquanto olha admirado para o baralho. Após um momento,
ele olha para você.] Me desculpe. Eu sou Brother Jason, a propósito. Eu, uh, suponho que não saiba jogar Tragic?}

{221}{}{TRAGA ADIANTE A COLECÃO!!!} #BRING FORTH THE GARNERING!!!

# Hell yeah, I love Tragic the Garnering.
{222}{}{Claro que sei, eu adoro a colecão de Tragic.}

# I've tried it, but it's not for me.
{223}{}{Já tentei jogar, mas não é minha praia.}

# I used to be addicted as hell to that game. I try to stay away from it now.
{224}{}{Eu me viciei nesse jogo por um tempo. Mas agora estou tentando largar.}

# Nope.
{225}{}{Não.}

# Hell no. Do I look like a pathetic loser to you?
{226}{}{Claro que não. Por acaso ta me achando com cara de nerd bundão?}

# Hey, fuck you asshole. Just leave me alone.
{230}{}{Vá se foder seu cuzão. Me deixe em paz.}

# Hey, fuck you whore. Just leave me alone.
{231}{}{Vá se foder sua puta. Me deixe em paz.}

# I'd love to, but I'm overcome with a desire to do you great bodily harm.
{232}{}{Eu adoraria, mas estou transbordando de vontade de arrebentar sua cara.}

# Alright, fine. Bye.
{233}{}{Tá bom então. Adeus.}

# Look, I'm sorry. That was rude of me. I'm just not a fan of Tragic.
{234}{}{Desculpa. Foi grosseria da minha parte. Eu apenas não curto Tragic.}


# Ah man, I'd love to play against you, but it's too risky. I don't want these taken from me. That's what I hate
 about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves
 from indulging in it. It doesn't make any sense. It's fucking moronic.
{240}{}{Cara, eu adoraria jogar contra você, mas é muito arriscado. Eu não quero que os tomem de mim. É isso que eu odeio
neste lugar. Nós estamos sentados em uma mina de ouro de coisas incríveis de antes da guerra, mas nos proibimos de
aproveitá-la. Essa porra não faz sentido. É uma idiotice do caralho.}

# Ah man, I know what you mean. I wish I could play more myself, but it's too risky. I don't want these taken from me.
 That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're
 forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.
{240}{}{To ligado cara. Eu queria poder jogar mais também, mas é muito arriscado. Eu não quero que os tomem de mim. 
É isso que eu odeio neste lugar. Nós estamos sentados em uma mina de ouro de coisas incríveis de antes da guerra, mas nos proibimos de
aproveitá-la. Essa porra não faz sentido. É uma idiotice do caralho.}

# [He chuckles.] We got an addict on our hands here, I see. I wish I could play more myself, but it's too risky.
 I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things
 from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.
{242}{}{[Ele ri.] Parece que não sou o único viciado por aqui. Eu queria poder jogar mais também, mas é muito arriscado.
 Eu não quero que os tomem de mim. É isso que eu odeio neste lugar. Nós estamos sentados em uma mina de ouro de coisas incríveis
 de antes da guerra, mas nos proibimos de aproveitá-la. Essa porra não faz sentido. É uma idiotice do caralho.}
 
# It doesn't matter, we wouldn't be able to play anyway -- it's too risky. I don't want these taken from me. That's what
 I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves
 from indulging in it. It doesn't make any sense. It's fucking moronic.
{243}{}{Não importa, nós não poderiamos jogar mesmo -- é arriscado demais. Eu não quero que os tomem de mim. É isso que eu odeio neste lugar. 
 Nós estamos sentados em uma mina de ouro de coisas incríveis de antes da guerra, mas nos proibimos de aproveitá-la. 
 Essa porra não faz sentido. É uma idiotice do caralho.}
 
# Yeah, that does sound stupid.
{244}{}{É, parece bem idiota.}

# If you don't agree with the ideals of your order, then why are you a monk?
{245}{}{Se você discorda dos ideais da sua ordem, então por que virou um monge?}

# You think I *chose* to be a monk? I was born into this shitty lifestyle. I just wish the others would wake up and
 see how stupid it is to not take advantage of all this sweet stuff we've collected. But no, they're perfectly content to
 worship and catalog the relics, but never actually do anything useful with them. Like I said, it's fucking moronic.
{250}{}{Acha que eu *escolhi* me tornar um monge? Eu nasci nesta merda. Eu só queria que os outros acordassem e vissem o 
quanto é idiota não se aproveitar de todas as maravilhas que pegamos. Mas não, eles ficam felizes em apenas catalogar e 
idolatrar as relíquias, mas nunca fazer nada de útil com elas. Como eu falei, é uma idiotice do caralho.}

# You got a point, that does sound pretty stupid.
{251}{}{Você tem razão, parece bem idiota.}

# About as moronic as me sitting here listening to you bitch about your life. Bye.
{252}{}{Quase tão idiota quanto eu ficar aqui ouvindo voce reclamar da vida. Adeus.}

# If you think it's so stupid, then why don't you do something to try and change things?
{253}{}{Se você acha tão idiota, então por que não faz nada pra mudar as coisas?}

# Finally, someone who agrees with me! Look, I have this idea, and maybe you could help me out. You see, the monks
 here have spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally"
 format the database, they'd lose all that work. I think something like that might shock them back to their senses and we
 might finally give up this stupid way of life. So, what do you say?
{260}{}{Finalmente alguém que me entende! Cara, eu tenho uma ideia, e talvez você possa me ajudar. Sabe, os monges
 daqui gastaram *anos* transcrevendo informações de antes da guerra no banco de dados do nosso computador. Se alguém 
 "acidentalmente" formatar o banco de dados, eles perderão todo o trabalho. Acho que algo assim daria um choque de realidade
 neles e nós finalmente abandonaríamos esse modo de vida idiota. E aí, o que me diz?}
   
# I say that's a terrible idea and that I'm done talking to you.
{261}{}{Digo que é uma péssima ideia e que cansei de falar com você.}

# Erase years of someone else's hard work? Sounds fun. I'll do it.
{262}{}{Apagar anos do trabalho árduo de outra pessoa? Maneiro. Tô dentro.}

# Why don't you format it yourself?
{263}{}{Por que você mesmo não formata?}

# If you hate it here, why don't you just leave?
{264}{}{Se você odeia este lugar, por que não vai embora?}

# Actually, I *do* have an idea of how to change things. Maybe you could help me out. You see, the monks here have
 spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally" format the
 database, they'd lose all that work. I think something like that might shock them back to their senses and we might finally
 give up this stupid way of life. So, what do you say?
{270}{}{Na verdade, eu *tenho* uma ideia de como mudar as coisas. Talvez voce possa me ajudar. Sabe, os monges
 daqui gastaram *anos* transcrevendo informações de antes da guerra no banco de dados do nosso computador. Se alguém 
 "acidentalmente" formatar o banco de dados, eles perderão todo o trabalho. Acho que algo assim daria um choque de realidade
 neles e nós finalmente abandonaríamos esse modo de vida idiota. E aí, o que me diz?}
 
# I say that's a terrible idea and that I'm done talking to you.
{271}{}{Digo que é uma péssima ideia e que cansei de falar com você.}

# Erase hundreds of years of someone else's hard work? Sounds fun. I'll do it.
{272}{}{Apagar anos do trabalho árduo de outra pessoa? Maneiro. Tô dentro.}

# Why don't you format it yourself?
{273}{}{Por que você mesmo não formata?}

# If you hate it here, why don't you just leave?
{274}{}{Se você odeia este lugar, por que não vai embora?}

# Are you kidding me? They'd crucify me if I did that. You however, you're an experienced adventurer. Hell, I bet
 you could massacre everyone here without breaking a sweat. So will you do it, or are you afraid of a bunch of pacifist monks?
{280}{}{Tá me zoando? Eles me crucificariam. Já você é um aventureiro experiente. Porra, aposto que você poderia
massacrar todo mundo aqui sem ao menos suar. E então, vai formatar ou tá com medinho de um bando de monges pacifistas?}  

# I'm not afraid of anyone. I'll do it.
{281}{}{Eu não tenho medo de ninguém. Eu aceito.}

# Alright. I'll do it.
{282}{}{Ok, eu topo.}

# Nah, instead I think I'll test out your massacre theory. Starting with you.
{283}{}{Nah, ao invés disso acho que vou testar aquela sua teoria sobre massacrar todos. Começando com voce.}

# I'll pass. That's just not my style. Bye.
{284}{}{Não. Não faz meu estilo. Adeus.}

# No, I'm not going to do it. If you hate it here, why don't you just leave?
{285}{}{Não farei isso. Se você odeia este lugar, por que não vai embora?}

# Unless you've changed your mind about helping me, fuck off.
{286}{}{A não ser que tenha mudado de ideia, cai fora daqui.}

# Alright. I'll do it.
{287}{}{Ok. Eu topo.}

# No, I'm not going to do it. If you hate it here, why don't you just leave?
{288}{}{Não farei isso. Se você odeia este lugar, por que não vai embora?}

# You will? Seriously? Oh man, that's awesome. But first, you'll need to get access, 'cause they're pretty protective
 of the database. It shouldn't be too hard though, these monks are pretty trusting. They're gonna be pissed as hell when
 you format it, but they're all a bunch of wimps, so don't worry about it. Just try not to kill anyone -- I don't want things
 to get too out of hand, you know?
{290}{}{Você aceita? Sério? Cara, isso é ótimo. Mas primeiro, você precisará obter acesso, porque eles o banco de dados é
fortemente guardado. Apesar disso, não deve ser tão difícil, esses monges são ingênuos. Eles vão ficar putos quando você formatar
o banco, mas são um bando de frouxos, então relaxa. Só tente não matar ninguém -- Eu não quero que as coisas saiam do controle, sabe?} 

# Sure. Anything else?
{291}{}{Claro. Mais alguma coisa?}

# I make no promises. Anything else?
{292}{}{Não posso prometer nada. Mais alguma coisa?}

# Just format it, then take off, cause they're not going to want you around here. Don't even bother to come tell me
 you did it, because I'll have to act just as pissed as everyone else or they'll suspect something's up. Thanks again for
 doing this. It's for their own good.
{300}{}{Só formate tudo e caia fora, porque eles não vão querer te ver por lá. Nem se preocupe de voltar pra me avisar
que conseguiu, eu preciso fingir que estou tão puto quanto os outros, ou vão achar suspeito. Obrigado por ajudar. 
É para o próprio bem deles.}

# Whatever you say. Bye.
{301}{}{Como quiser. Adeus}

# Are you crazy? I've never been out in the wastes, but I've got a pretty damn good idea as to what it's like. I'd
 be lucky to make if fifty yards before a radscorpion shoved a foot-long stinger up my ass. Or even worse, I'd get captured
 and tortured by a gang of maniac raiders *or* I'd be eaten alive by cannibalistic tribals. Whatever. I just know that if
 I left here, I'd be fucked. So no, I'm stuck here.}
{310}{}{Voce bateu a cabeça? Eu nunca botei o pé no deserto, mas tenho uma boa noção de como ele é. Seria
 muita sorte eu andar 50 metros antes de um radscorpion enfiar um baita ferrão no meu cu. Ou pior, eu poderia ser capturado
 e torturado por uma gangue de assaltantes *ou* eu seria devorado por índios canibais. Tanto faz. Eu só sei que se sair daqui me 
 fodo. Então não, estou preso aqui.}
 
# Hey, it's not *that* bad out there... Actually, you're right. You probably wouldn't even make it to Gecko.
 At least, not without help. But what if I said I'd escort you?
 {311}{}{Ei, não é *tão* ruim assim la fora... Na verdade, você tem razão. Você provavelmente não chegaria nem até o Gecko.
  Pelo menos não sem ajuda. Mas e se eu te acompanhar?}
  
# Sucks to be you. Bye.
{312}{}{Que bosta. Adeus.}

# Keep your hopes up. I'm sure there is a town nearby that would be safe to travel to.
{313}{}{Mantenha a esperança. Com certeza tem alguma cidade perto que seja fácil de chegar.}

# Yeah, well if you find one, let me know.
{315}{}{Bom, se você encontrar algo, me avise.}
 
# Will do. Bye.
{316}{}{Pode deixar. Adeus.}

# To Gecko? That's the ghoul town, right? Thanks, but no thanks.
{320}{}{Até Gecko? Essa é a cidade dos ghouls, não é? Valeu, mas não, obrigado.}

# Hey, the ghouls there are actually really friendly. Besides, I know one in particular that loves a good game of Tragic.
{321}{}{Na verdade os ghouls de lá são bem amigáveis. Aliás, eu conheço um em particular que é viciado em um bom jogo de Tragic.}

# Hey, the ghouls there are actually really friendly.
{322}{}{Ei, na verdade os ghouls de lá são bem amigáveis.}

# Hey, I hear the ghouls there are actually really friendly.
{323}{}{Sabe, eu ouvi falar que na verdade os ghouls de lá são bem amigáveis.}

# Alright. Suit yourself. Bye.
{324}{}{Como quiser, a vida é sua. Adeus.}

# No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{330}{}{Puta que pariu, outro jogador de Tragic? Hmm, isso muda tudo... Talvez ele tenha uma Black Dahlia para 
trocar. Ok. Eu vou se você me levar até lá.}

# Lets go.
{331}{}{Então vamos.}

# Alright, but I need to take care of some things first. I'll let you know when I'm ready to go.
{332}{}{Ok, mas tem umas coisas que eu preciso fazer primeiro. Eu te aviso quando estiver pronto pra ir.}

# Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.
{340}{}{Ah é? Isso não muda o fato de que eles parecem merda de brahmin. Não, obrigado.}

# Alright. Suit yourself. Bye.
{341}{}{Como quiser, a vida é sua. Adeus.}

# What do you want?
{350}{}{O que você quer?}

# I just wanted to say hi. See ya.
{351}{}{Só queria te cumprimentar. Falou.}

# I changed my mind. I'll format the computer for you.
{352}{}{Eu mudei de ideia. Vou formatar o computador pra você.}

# Hey, you might want to reconsider my offer to take you to Gecko, because I know
 someone there that loves a good game of Tragic.
{353}{}{Talvez você queira reavaliar minha oferta de te levar até Gecko, porque eu conheço
alguém lá que é viciado em um bom jogo de Tragic.}

# Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.
{354}{}{Ei, eu conheço alguém em Gecko que é viciado em um bom jogo de Tragic. Eu poderia te levar lá.}
 
# Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.
{360}{}{Podemos ir? Eu estou louco pra saber que tipo de cartas de Tragic esse cara tem.}

# Alright, let's go.
{361}{}{Ok, vamos.}

# Not yet. I'll let you know.
{362}{}{Ainda não. Eu te aviso quando puder.}

# [Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their
 Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]
{370}{}{[Ao chegar em Gecko, você apresenta o jovem monge a Wooz. Eles imediatamente começam a comparar suas cartas de
 Tragic. Você está prestes a sair quando Brother Jason consegue esquecer um pouco de Tragic para falar com você.]} 
# [MORE]
{371}{}{MAIS]}

# Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here,
 I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works.
 [He hands you a Stealth Boy.] See ya.
{372}{}{Puta merda, o Wooz *tem* uma Black Dahlia! Só isso já fez a viagem valer a pena. Os ghouls podem ser feios pra diabo,
 mas descobri que se eu tirar os óculos, até que são suportáveis. Obrigado por me trazer até aqui. Aqui, eu, é, "emprestei" isso
 da Memorabilia de Abbey, é uma das poucas relíquias tecnológicas que ainda funciona. [Ele te entrega um Stealth Boy.] Falou.}
 
# Thanks. Bye.
{373}{}{Valeu. Adeus.}

# I'm just happy I won't have to hear you bitch anymore. Bye.
{374}{}{Já estou feliz o bastante de não ter que ouvir mais seu mimimi. Adeus.}

# Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.
{380}{}{Puta merda, o Wooz *tem* uma Black Dahlia! Só isso já fez a viagem valer a pena. Os ghouls podem ser feios pra diabo,
 mas descobri que se eu tirar os óculos, até que são suportáveis. Obrigado por me trazer até aqui. Aqui, [Ele coloca a mão no bolso, depois franziu o cenho.]
 que diabo. Eu podia jurar que estava comigo. Oh, sinto muito, mas parece que eu perdi sua recompensa, então parece que você só vai
 ficar com um simples obrigado. Falou.}
 
# Oh, uh, don't worry about it. Just glad I could help. Bye.
{381}{}{Oh, é, não se preocupe. Eu fico feliz por ajudar. Adeus.}

# I'm just happy I won't have to hear you bitch anymore. Bye.
{382}{}{Já estou feliz o bastante de não ter que ouvir mais seu mimimi. Adeus.}

# Can't talk... must build more powerful deck...
{400}{}{Não posso conversar... preciso construir um deck mais poderoso...}

# Leave me alone.
{500}{}{Me deixe em paz.}

# Go away.
{501}{}{Vá embora.}

# Fuck off.
{502}{}{Cai fora.}

# Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there,
 so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving.
 This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply.]
{600}{}{Oh, é você. Alguém explodiu o reator de Gecko e todos os ghouls foram embora. Não tinha mais porque eu ficar lá,
 então voltei pra cá. Por sorte, os monges daqui não questionaram minha ausência, então não fui punido por sair.
 Que merda, eu pensei que ia ter uma nova vida fazendo o que gosto. [Ele suspira pesarosamente.]}
 
# Sorry to hear that. See you around.
{601}{}{Que pena. A gente se vê.}

# That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.
{602}{}{A vida é assim. Uma hora você está no topo do mundo e na outra cai de cara na lama. Vivendo e aprendendo. Adeus.}

# Guess I just gotta get used to this place.
{610}{}{Acho que vou ter que me acostumar com este lugar.}

# You safely escort Brother Jason to his new home.
{1000}{}{Você tranquilamente acompanha Brother Jason para sua nova casa.}
