#You see pre-war gadgets.
{100}{}{Você vê aparelhos pré-guerra.}
#Displayed on the table, like holy relics, is an impressive array of pre-war gadgets and gizmos.
 Too bad none of it works anymore.
{101}{}{À mostra na mesa, como relíquias sagradas, é uma impressionante coleção de aparelhos e bugigangas pré-guerra. Uma pena nenhum deles funcionar mais.}
#There is nothing of use here.
{102}{}{Não há nada útil aqui.}
