# Matheus Reis Traduzindo...

# You see Max.
{100}{}{Você vê Max.}
# You see a regular Abbey monk.
{101}{}{Você vê um monge comum de Abbey.}
# He looks a little nervous.
{102}{}{Ele parece um pouco nervoso.}

# Hello. What can I do for you?
{200}{}{Olá. O que posso fazer por você?}
# I have something from Elaine...
{201}{}{Eu tenho algo da Elaine...}
# What is this place?
{202}{}{Que lugar é este?}
# Bye.
{203}{}{Tchau.}

# Let me guess. It's that service part I requested, right?
{300}{}{Deixe-me adivinha. É aquela peça do serviço que eu pedi, certo?} #Imagino que aqui esteja errado
# Yes, here it is
{301}{}{Sim, aqui está.}
# No, I was just testing you.
{302}{}{Não, eu só estava te testando.}

# (He takes the part from your hands) Finally! Now we can fix this printing machine. Thanks, take this survival manual for your trouble.
{303}{}{(Ele pega a peça de suas mãos) Finalmente! Agora podemos consertar a máquina de impressão. Obrigado, tome este manuel de sobrevivência pela confusão.}
# Thanks.
{304}{}{Obrigado.}

# Look, I don't have time for this. Do you have the part or not?
{305}{}{Olhe, Eu não tenho tempo para isso. Você tem a peça ou não?}
# Yeah, I have it.
{306}{}{Sim, eu tenho.}
# Whatever, I'm outta here
{307}{}{Seja como for, Vou embora daqui.}

# This is our printing works. We copy our books here.
{400}{}{Este é o nosso trabalho de impressão. Nós copiamos nossos livros aqui.}
# Ok, thanks for the info.
{401}{}{Ok, obrigado pela informação.}

# You gain 100 experience points for delivering the part.
{500}{}{Você ganha 100 pontos de experiência por ter entregue a peça.}

#dumb dialgoue
# I be BIG helper today. I have macheen part from pretty name woman.
{600}{}{Eu ser GRANDE ajudante hoje. Eu tenho a peça da makiinah da mulher de nome bonito.}

# That must be the service part that I requested from Elaine. Thanks for bringing this to me. Here, take this
 survival manual for your trouble...uh if you can read it that is.
{610}{}{Essa deve ser a peça de serviço que eu pedi para a Elaine. Obrigado por trazer para mim. Aqui, leve este manual de sobrevivência pela confusão...uh isto é, se você conseguir lê-lo.}
 # I read ten words. I likie pitcher books more. They fun to look. Tankee!
{611}{}{Eu leio dez palavras. Eu gostu mais de livros de pintar. Eles divertido de olhar. Bigado!}

