# You see a merchant.
{100}{}{Você vê um vendedor.}
# You see a merchant who is trying to fix the waterpump.
{102}{}{Você vê um vendedor tentando consertar o encanamento.}
# I just can't get this thing working!
{103}{}{Essa coisa não funciona de jeito nenhum!}
# This seems to be very hard to fix.
{104}{}{Isso parece bem difícil de consertar.}
# What a piece of shit this is!
{105}{}{Mas que merda!}
# Stubborn little sonnuva bitch are we?
{106}{}{É um filho da puta teimoso mesmo.}
# Could you lend me a hand?
{107}{}{Você poderia me dar uma mão?}
# Maybe you'll have better luck with this.
{108}{}{Talvez você se de melhor nisso.}
# Hey, thanks for fixing the waterpump!
{109}{}{Ei, obrigado por consertar o encanamento!}
# You should notify the headmonk that the waterpump is now fixed.
{110}{}{Você deveria avisar o chefe dos monges que o encanamento foi consertado.}
# Thanks for helping us with this thing.
{200}{}{Valeu por ajudar com essa coisa.}
# Ah, what a piece of shi- umm, I'm a little busy right now. Do you need something or are
 you just wasting my time?
{300}{}{Mas que mer-umm, eu estou um pouco ocupado agora. Você quer alguma coisa ou só esta me 
 fazendo perder tempo?} 
# Actually yes, the Abbot sent me. He said the water pump is having some trouble.
{301}{}{Sim, o Abbot me mandou. Ele disse que o encanamento está com problemas.}
# Heh, "having trouble" is an understatement. This ol' thing is totally busted. There's no way
 it's going to run again.
{302}{}{Hah, "está com problemas" é pouco. Essa velharia já era. Nunca mais vai funcionar direito.}
# I see. Then I guess it wouldn't hurt anything if I took a look at it.
{303}{}{Beleza. Então não tem problema se eu der uma olhada nele.}
# Sure, be my guest. Not like you could break it any more.
{304}{}{Claro, fique à vontade. Não tem como ficar mais quebrado que isso.}
# I don't mean to bother, but what seems to be the trouble here?
{305}{}{Eu não quero incomodar, mas qual é o problema aqui?}
# The main water pump for the Abbey is busted. The damn thing was breathing its last the past few days
 and now it's finally gone out.
{306}{}{A tubulação principal para a Abbey está quebrada. Essa porcaria já estava nas últimas faz tempo, e agora finalmente
 quebrou} 
# I'm a bit of a techie, mind if I take a look?
{307}{}{Eu meio que sou um técnico, posso dar uma olhada?}
# Well, I'm not that great with machines, but perhaps I can see if something can be done.
{308}{}{Não sou muito bom com máquinas, mas talvez eu possa dar uma olhada.}
# Sure, no one's stopping you.
{309}{}{Claro, não custa nada tentar.}
# Uh, sorry. Bye.
{310}{}{Uh, sinto muito. Adeus.}
# I'll see what I can do then.
{311}{}{Vou ver o que posso fazer.}

#added in 1.3
# I thought I might be able to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.
{312}{}{Pensei que eu poderia ajudar, mas já que você é um cuzão, fique à vontade para consertar sozinho.}
# I told the Abbot I'd be willing to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.
{313}{}{Eu disse para o Abbot que queria ajudar, mas já que você é um cuzão, fique à vontade para consertar sozinho.}
# [He squints at you for a moment, then slowly lets out his breath in a sigh.] Sorry friend, this thing's being a
 real bitch, and it's gotten me all worked up. I didn't mean to snap at ya.
{320}{}{[Ele te encara por um momento, mas lentamente solta um suspiro.] Desculpa amigo, essa coisa tem sido um inferno,
 e atacou meus nervos. Eu não queria ter descontado em você.}
# Well, what seems to be the problem then?
{321}{}{Bem, qual é o problema então?}
# Whatever, bye.
{322}{}{Que seja, adeus.}
# Come back and talk to me in the morning.
{330}{}{Volte aqui para falar comigo amanhã.}
#end added

# Oh, it's you again. Any luck?
{400}{}{Oh, você voltou. Conseguiu alguma coisa?}
# No, not yet. I'll get back to you if I do.
{401}{}{Não, ainda não. Eu volto aqui quando conseguir.}
# Actually, yes. I looked inside and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.
{402}{}{Um pouco. Eu olhei lá dentro e parece que o motor está completamente quebrado. As conexões arrebentaram, então nós
 vamos ter que conseguir um novo motor, e também alguns cabos para reconectar tudo de novo, já que os cabos antigos derretaram.} 
# Hmm...the connectors are shot on the main motor, eh? Well, I got some wires here with me that will work, but not
 that specific motor. I am sure Vault City has the part though. Go there and speak with Harry in the main courtyard. Tell him
 Dave sent you. Damn motor is expensive, but he should give you a good deal.
{500}{}{Hmm... Os conectores arrebentaram no motor principal, eh? Bem, eu tenho alguns cabos aqui que servem, mas não 
 tenho outro motor. Mas tenho certeza que em Vault City eles tenham um. Vá até lá e fale com Harry no pátio principal. Diga a 
 ele que Dave lhe enviou. O motor é caro para caramba, mas ele deve te dar um bom desconto.}
# I'll head there now. Be back soon.
{501}{}{Vou para lá agora. Eu volto logo.}

#added in 1.3
# Whoa, hold on a second. I was happy to help you figure out the problem, but who said I'm willing to trek across
 the wastes to go buy you an expensive motor? If you want my help, it's going to cost you.
{502}{}{Opa, espera aí. Eu fico feliz por te ajudar a descobrir qual é o problema, mas quem disse que eu quero 
 perambular pelo deserto só para comprar um motor caro? Se quer minha ajuda, saiba que ela tem um preço.}
# How 'bout *you* tell Harry that when you go fetch it your damn self? I'm not your fucking errand boy. Bye.
{503}{}{E que tal *você* ir buscar o motor com o Harry? Eu não sou um garoto de recados, porra. Adeus.}
# Alright, I wouldn't expect someone to do work for free. The part will cost you bout 500 and I think 100 more for
 your trouble is reasonable. Here's 600.
{510}{}{Ok, eu não esperava que saisse de graça. A peça vai lhe custar uns 500 e acho que 100 a mais pelo seu trabalho
 é justo. Tome 600.}
# That's better. I'll be back with the part.
{511}{}{Assim está melhor. Eu voltarei com a peça.}
#end added

# Any luck on that part? This machine won't fix itself.
{600}{}{Conseguiu a peça? Máquinas não se consertam sozinhas.}
# No, not yet. I'll be back when I get it.
{601}{}{Não, ainda não. Eu volto aqui quando conseguir.}
# Yep, got the part right here.
{602}{}{Opa, aqui está a peça}
# Excellent. Want me to install the damn thing, or do you want the pleasure?
{700}{}{Ótimo. Quer que eu instale essa porra, ou quer fazer as honras?}
# I think I can handle it. Step aside.
{701}{}{Acho que posso cuidar disso. Para trás.}
# Actually, I think I've done enough on this job. Go ahead and install it yourself.
{702}{}{Na verdade, acho que já fiz o bastante. Pode instalar você mesmo.}
# Alright fine, hand it over.
{800}{}{Tudo bem, passa ela para cá.}
# Here you go.
{801}{}{E lá vamos nós.}
# That should do it.
{900}{}{Isso deve resolver o problema.}
# The water pump has been repaired.
{901}{}{O encanamento foi consertado.}
#if head monk gives you the quest
# (Wipes the sweat from his forehead.) Yeah, need something?
{910}{}{(Limpa o suor da testa.) Precisa de alguma coisa?}

# The Abbot said you might need some assistance. What seems to be the trouble?
{911}{}{O Abbot disse que você precisa de ajuda. Qual é o problema?}

# Nevermind. Goodbye.
{912}{}{Esquece. Tchau.}

#already looked at water pump

# I took a look at the water pump and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.
{913}{}{Eu dei uma olhada no encanamento e parece que o motor está completamente quebrado. As conexões arrebentaram, então nós
 vamos ter que conseguir um novo motor, e também alguns cabos para reconectar tudo de novo, já que os cabos antigos derretaram.}
