{100}{}{Você está vendo a Sra. Peterson.}
{101}{}{Você está vendo uma jovem, mulher bonita. Ela sorri quando vê você.}

{200}{}{Bem-vindo ao Abbey, amigo.}
{201}{}{Fale com o meu marido, se você precisar de alguma coisa.}
{202}{}{Lindo dia, não é?}

{300}{}{Bem-vindo ao Abbey, amigo.}
{301}{}{Fale com o meu marido, se você precisar de alguma coisa.}
{302}{}{Adorável à noite, não é?}

{400}{}{Não tenho nada a dizer para você. Por favor, vá embora.}


