{100}{}{Você está vendo um camponês.}
{101}{}{Você está vendo um camponês com aspecto saudável.}
{102}{}{Você está vendo uma pessoa.}
{103}{}{Bebeu muito álcool ultimamente?}
{104}{}{Fique longe do álcool por um tempo.}
{105}{}{Eu vejo que você bebeu um mix "especial" do Hank.}
{106}{}{Bem-vindo, herói!}
{107}{}{Você realmente mostrou à esses canalhas da Enclave!}
{108}{}{Você é realmente um herói!}
{109}{}{Ouvi dizer que você destruiu a Enclave, bem feito!}
{110}{}{Olá.}
{111}{}{Espero que começa a chover em breve, ou minha colheita não vai sobreviver.}
{112}{}{Nós não temos muitos visitantes aqui.}
{113}{}{Bem-vindo!}
{114}{}{Sim, eu sei. É muito chato aqui, mas pelo menos estamos a salvo de invasores e tal ...}
{115}{}{Oi, tribal.}
{116}{}{Com certeza é um dia quente hoje!}
{117}{}{Bons motivos agrícolas aqui...}
{118}{}{Tenha um bom dia.}
{119}{}{Bem-vindo ao Abbey, vagabundo!}
{120}{}{Mosteiro impressionante que temos aqui, hein?}

{200}{}{Tire as mãos de cima de mim maldito!}
