#############################################################
#  Message File: ACBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um brahmin comum domesticado.} # You see a regular domesticated brahmin.
{101}{}{A cabeça extra do brahmin é provavelmente resultado
 de uma vaca comum sendo exposta à radiação cedo de mais.} # The brahmin's extra head is probably the result of a regular cow being exposed too soon to radiation.
{102}{}{Você não percebe nada de estranho no brahmin.} # You dont notice anything unusual about the brahmin.
{103}{}{Brahmins não são muito de conversar.} # Brahmin aren't much for conversations.
{104}{}{Você não tem nada melhor pra fazer do que perder seu
 tempo falando com vacas de duas cabeças?} # Don't you have anything better to do than sit around talking to a two-headed cow?
{105}{}{Brahmins são uma raça de vacas mutantes.} # Brahmin are a mutated breed of cows.