#############################################################
#  Punho de pé (Arroyo)     				    #
#############################################################
{100}{}{Você vê o "Punho de pé".}
{101}{}{"Punho de pé" é o guerreiro chefe de sua tribo.} 
{102}{}{Aí está você, Escolhido. Hm! Como vai sua missão?} 
{103}{}{Muito bem.} 
{104}{}{Não tão bom.}
{105}{}{Uh?!}
{106}{}{Eu devo retornar por isso.}
{107}{}{Talvez você precisa da ajuda de um guerreiro.} 
{108}{}{Você pode me ajudar em que?}
{109}{}{Não. Eu estou bem.}
{110}{}{Boa resposta, seu burro. Agora fique calado enquanto eu treino.} 
{111}{}{O-k}
{112}{}{Eu sei como lutar com minhas próprias mãos e pernas. Você acha que pode aprender isso?} 
{113}{}{Claro.} 
{114}{}{Vá com Deus, Escolhido.} 
{115}{}{Adeus.}
{116}{}{Hmmm -- passe um dia comigo e eu te ensino como dar socos mais fortes.} 
{117}{}{Ok. Vamos fazer.}
{118}{}{Desculpe, eu não tenho tempo agora.} 
{119}{}{Você sabe que posso te ensinar, Escolhido. Boa sorte na sua missão.} 
{120}{}{Oh, ok.}
{121}{}{Ha! Escolhido, você não é bom o suficiente para eu te treinar.} 
{122}{}{Oh, ok.}
{123}{}{Você não é rapido suficiente no combate para meu treinamento de ajudar, Escolhido.} 
{124}{}{Oh, ok.}
{125}{}{Você tem que aprender mais sobre combate antes de eu poder te ajudar, irmãozinho.} 
{126}{}{Oh, ok.}
{127}{}{Eu posso te ensinar a dar um chute poderoso. Vai levar um dia inteiro.} 
{128}{}{Ok.}
{129}{}{Eu posso te ensinar a lutar melhor. Vai levar um dia inteiro.} 
{130}{}{Ok.}
{131}{}{Você aprendeu bem, Escolhido. Que Deus te acompanhe.} 
{132}{}{Obrigado pela sua ajuda.} 
{133}{}{Eu te ensinei tudo que eu podia, Escolhido. Boa sorte na sua missão.}