# Noob-Saibot está traduzindo este arquivo.

#############################################################
#  Message File: ACMynoc.msg                                #
#                                                           #
#       Body Type:  NMPRIM                                  #
#       Combat AI: Berzerker                                #
#       Weapons: Sledgehammer[in hand]                      #
#       HP: 75                                              #
#       Skills to note: 80% Throwing                        #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

{100}{}{Você vê o guarda da ponte.} # You see the bridge guard.
{101}{}{Você vê Mynoc, o guarda da ponte.} # You see Mynoc, the bridge guard.

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Na sua frente está um grande guerreiro da sua vila, segurando uma lança.} # Before you stands a large warrior of your village, holding a spear
{151}{}{[FALAR]} # [TALK]
{152}{}{Olá, Escolhido. Está indo encontrar o GECK?} # Hello, Chosen One. Off to find the GECK?
{153}{}{Sim.} # Yes
{154}{}{Sim. Mas antes de ir, queria te fazer algumas perguntas.} # Yes. But before I go, I would like to ask you some questions.
{155}{}{Ainda não. Eu vou dar mais uma olhada por aí.} # Not just yet. I'm going to look around a little bit more.
{156}{}{Bem, que os deuses te protejam.} # Well, may the gods watch over you.
{157}{}{Obrigado. Adeus.} # Thank you, goodbye.
{158}{}{O que você quer saber?} # What do you want to know?
{159}{}{O que você pode me dizer sobre os homens que negociam com a nossa vila?} # What can you tell me of the men who trade with our village?
{160}{}{O que você pode me dizer sobre esse objeto do vault que eu tenho aqui comigo?} # What can you tell me about this object I have from a vault?
{161}{}{Nada, deixa pra lá.} # Nothing, never mind.
{162}{}{Muito bem, mas não perca muito tempo. Sem o GECK, estamos perdidos.} #Very well, but don't waste too much time. Without the GECK, we're doomed.
{163}{}{Eu sei, não se preocupa -- Tá tudo sobre controle.} # I know, don't worry -- I've got it all under control.
{164}{}{Porquê?} # Why?
{165}{}{Eu vou indo. Até mais.} # I must be going. Goodbye.
{166}{}{Os comerciantes? Eles vem de Klamath, a cada dois meses, mais ou menos. Eles só devem aparecer daqui há um mês ou mais, mas Klamath fica a poucos dias daqui, ao leste.} # The traders? They come from Klamath about every two months. There won't be another here for a month or more, but Klamath's only a few days east of here.
{167}{}{Obrigado. Adeus.} # Thank you. Goodbye.
{168}{}{O que você pode me dizer sobre esse objeto do vault sagrado que trago comigo?} # What can you tell me about this object I have from the sacred vault?
{169}{}{Parece ser um cantil de ferro. Talvez o vault tenha nos enviado isso como um presságio.} # Looks like a metal water gourd. Maybe the vault sent it to us as an omen.
{170}{}{Você saberia me dizer quem trouxe isto para nossa vila?} # Can you tell me who brought this item to our village?
{171}{}{Obrigado. Eu tenho que ir agora. Adeus.} # Thank you. I must be going. Goodbye.
{172}{}{Eu espero que sim.} # I hope you do.
{173}{}{Esse seu excesso de confiança faz com que todos sofram! Adeus!} # Your overconfidence makes all of us suffer! Goodbye!
{174}{}{Adeus.} # Goodbye.
{175}{}{Porque? Olhe a sua volta -- nossa vila está morrendo. Os jardins secam e todos os dias velhos e crianças morrem. Você deve trazer o GECK para nós antes que seja tarde de mais!} # Why? Look around you -- our village dies. The gardens wither and every day children and old ones collapse. You must bring Eden to us before it is too late!
{176}{}{Pode deixar comigo. Adeus.} # And I will take care of it.  Goodbye.
{177}{}{Eu sou o Escolhido -- Eu só "devo" fazer o que eu quiser. Adeus.} # I am the Chosen One -- I "must" do only as I please. Goodbye.
{178}{}{Eu não lembro do nome dele, só que ele era velho e barulhento -- muito barulhento pra ser educado -- mas ele sabia de muitas coisas. Ele era de Klamath, que fica ao leste, como eu disse.} # I don't remember his name, just that he was old and loud -- too loud for proper manners -- but he knew many things. He was from Klamath, east like I said.
{179}{}{Obrigado. Até mais.} # Thank you, goodbye.
{180}{}{Você ainda está aqui? Você precisa encontrar o GECK! Ficar aqui não vai nos ajudar.} # Are you still here? You must go find the GECK. Staying here doesn't help us.
{181}{}{Você tem que se preocupar é com essa ponte, amigo. Eu já sei me virar muito bem.} # This bridge is all you need to worry about, friend. I can take care of myself.
{182}{}{Eu já estava de saida. Até mais, amigo.} # I was just heading out. Goodbye, my friend.
{183}{}{Eu não vou mais falar com você, seu porco indisciplinado!} # I will speak to you no longer, insubordinate pig!
{184}{}{Eu queria te fazer outra pergunta.} # I would like to ask you another question.
{185}{}{Isso foi rápido! Você achou o Santo Vault 13?} # That was quick! Have you found the holy Vault 13?
{186}{}{Sim} # Yes.
{187}{}{Não, ainda não.} # No, not yet.
{188}{}{Mesmo? Incrível! Você trouxe o GECK?} # You have? Wonderful! Did you bring back the GECK?
{189}{}{Não.} # No.
{190}{}{Não. Eu não falei com as pessoas do vault ainda.} # No. I haven't spoken to the people of the vault yet.
{191}{}{Eu não acho que isso seja problema seu, meu amigo.} # I don't believe that's any business of yours, my friend.
{192}{}{Não? Escolhido, três anciões morreram desde que você partiu. Você não deve mais perder tempo.} # No? Chosen One, three old ones have died since you left. You must not waste any more time. 
{193}{}{Eu vou encontrá-lo, não se preocupe.} # I'll find it, don't worry.
{194}{}{Estou ficando de saco cheio dessas suas reclamações.} # I'm getting sick of your constant nagging.
{195}{}{Bem, então porque você está falando comigo? Vá falar com eles, pegue o GECK.} # Well, why are you talking to me? Talk to them, and get the GECK.
{196}{}{Eu vou -- tudo ao seu tempo, meu amigo.} # I will -- all in good time, my friend. 
{197}{}{Estou ficando de saco cheio dessas suas reclamações.} # I'm getting sick of your constant nagging.
{198}{}{Como vai sua busca ao GECK, Escolhido?} # What news of the GECK, Chosen One?
{199}{}{Eu encontrei o vault!} # I have found the vault!
{200}{}{Eu não consegui encontrar o Vault 13.} # I have not been able to find Vault 13.
{201}{}{Olha só... Se não é o "Escolhido"...} # Well, look, it's the Chosen One.
{202}{}{Olá.} # Hello. 
{203}{}{Cale a boca.} # Shut up.
{204}{}{Posso te fazer umas perguntas?} # Can I ask you a question? 
{205}{}{Não. Eu não tenho tempo pra perder com você.} # No, I've no time for you.
{206}{}{Que seja. Adeus.} # Whatever. Good bye.
{207}{}{Ah, ok.. Te vejo por aí.} # Oh well. See you around.
{208}{}{Vê se morre.} # Go die.
{209}{}{Saudações, Tolo. Vê a ponte? Atravesse-a. Tome cuidado. Ponte perigosa. Você não quer cair. Ok?} # Greetings, dull one! See bridge? You cross, you be careful. Bridge dangerous. You not want to fall. Okay?
{210}{}{Umm... Hunh?} # Umm... Hunh? 
{211}{}{Miserável! Você falhou com a aldeia!} # Wretch! You have failed the village!
{212}{}{Você nos traiu. Você vai morrer por isso!} # You betray us. For that you'll die!
{213}{}{Você traiu seu próprio povo!} # You are a traitor to your own people.
{214}{}{Porque você faz isso?} # Why do you do this?
{215}{}{A Anciã estava errada. Você é perverso!} # The Elder was wrong. You are evil.

{300}{}{Meu pai me ensinou a fazer armas mais fortes do que a maioria. Consiga um pedaço de pederneira, que eu faço o mesmo pela sua lança. Você vai precisar disso no Deserto.} # My father taught me how to make stronger blades than most. Get me a piece of flint and I'll fix your spear, too. You'll need it in the wilderness.
{301}{}{Onde eu consigo essa pederneira?} # Where would I get some of this flint?
{302}{}{Eu ouvi dizer que sua tia Morlis tem um pedaço com ela. Ela é tão mau humorada que eu acho que ninguém pediu a pederneira pra ela. É claro, a bruxa vai querer alguma coisa em troca.} # They say your Aunt Morlis has been hoarding a piece. She's so ill-tempered I don't think anyone's asked her. Of course, the witch will want something in return.
{303}{}{Obrigado. Adeus.} # Thanks. Goodbye.
{304}{}{Você conseguiu pegar a pederneira com a sua tia?} # Did you talk your aunt out of her flint?
{305}{}{Sim, está bem aqui.} # Yes, I have some right here.
{306}{}{Ainda não.} # Not yet.
{307}{}{É um bom pedaço. Me dê sua lança.} # It's a good piece. Give me your spear.
{308}{}{Aqui está.} # Here you go.
{309}{}{Eu acho que eu não tenho uma.} # I guess I don't have one. 
{310}{}{Então, é só pegar os pedaços e colocá-los assim, que...} # Now, you put the pieces like so...
{311}{}{O Escolhido sem uma lança? Bem, você pode pegar uma das minhas. Agora, vamos ao trabalho...} # The Chosen One without a spear? Well, you'll have to take one of mine. Now, let's get to work...
{312}{}{Aqui está sua nova lança.} # Here is your new spear.
{313}{}{Obrigado, meu amigo -- isso vai me ajudar bastante.} # Thank you, my friend -- this will help a lot.
{314}{}{Sim, mas eu estava me perguntando sobre a sua lança. Ela parece diferente das outras.} # Yes, but I was wondering about your spear. It looks a little different.

# added in for time limit
{400}{}{Bem-vindo de volta, Escolhido! Você achou o vault? Trouxe o GECK com você?} # Welcome home, Chosen One! Did you find the vault? Have you returned with the GECK?
{401}{}{Eu num achar ainda.} # Me not find yet.
{402}{}{Não, eu ainda não achei.} # No, I haven't found it yet. 
{403}{}{Eu não tô afim de responder essas perguntas agora. Adeus.} # I'm not in the mood for your questions. Goodbye.
{404}{}{As coisas não vão bem, Escolhido. A seca está ficando pior, e nossas plantações não vão nada bem. Nós estamos tentando pegar tudo o que podemos para ter uma reserva de comida.} # Things are not going well, Chosen One. The drought is getting worse and our crops are sure to fail. We are trying to salvage what we can to build up our food reserves.
{405}{}{Porque não negociamos com as outras aldeias?} # Why no trade with other villages?
{406}{}{Mim fazer o melhor. Eu achar o GECK. Eu voltar.} # Me doing best me can. Me find GECK. Me return.
{407}{}{Porque não podemos negociar com as outras aldeias pelos alimentos que precisamos?} # Why can't we trade with other villages for the food we need?
{408}{}{Estou fazendo meu melhor. Quando achar o GECK, vou trazê-lo pra cá.} # I'm doing my best. When I find the GECK I'll return with it.
{409}{}{Nós somos um povo simples, e não temos muito o que oferecer em trocas. As poucas cidades que se comunicaram conosco enquanto você não estava aqui, não mostraram interesse em nos ajudar.} # We are a simple people and have little to offer in trade. The few towns that we have contacted while you were away have shown no interest in helping us.
{410}{}{Eu entende.} # Me see.
{411}{}{Entendo.} # I see.
{412}{}{Você é nossa única esperança, Escolhido. Por favor, não falhe!} # You are our only hope, Chosen One. Please do not fail us!
{413}{}{É bom te ver, Escolhido. Como vai sua jornada?} # It is good to see you, Chosen One. How fares your quest?
{414}{}{Mim procurando.} # Me still look.
{415}{}{Ainda estou procurando.} # I'm still looking.
{416}{}{Eu não quero falar sobre isso.} # I don't want to talk about it. 
{417}{}{Você deve se apressar. As coisas estão cada vez piores aqui na vila. Em breve teremos pouca comida, e a Anciã fala de racionar o que temos. Eu temo pelo futuro de Arroyo.} # You must hurry. Things are getting worse here at home. Soon there will be little food and the Elder speaks of rationing what we have. I fear for the future of Arroyo.
{418}{}{Escolhido! Por favor, diga-me que você completou sua jornada! Nossa vila está morrendo, assim como as pessoas daqui.} # Chosen One! Please tell me that you have completed your quest. Our village is dying, and so are our people.
{419}{}{Não, eu procura ainda.} # No, me still look.
{420}{}{Não, ainda estou procurando.} # No, I'm still looking.
{421}{}{Como vão as coisas?} # How are things?
{422}{}{Me desculpe, Escolhido, mas eu estou começando a peder minha fé em você. As vidas do nosso povo estão nas suas mãos. Por favor, encontre o Santo Treze e retorne para nós com o GECK!} # I am sorry, Chosen One, but I am beginning to question my faith in you. The very lives of our people are in your hands. Please find the holy Thirteen and return to us with the GECK!
{423}{}{Nossas colheitas falham, nosso brahmin morre.. todos estão famintos agora. O choro das crianças a noite não permite que ninguém durma. Estamos ficando desesperados.} # Our crops fail, the brahmin die, everyone goes hungry now. The cries of the children at night allow no one any sleep. We are becoming a desperate people.
{424}{}{Mim procurando.} # Me continue look.
{425}{}{Farei o que posso.} # I'll do what I can.
{426}{}{Mais uma vez você retorna para nós, Escolhido. Não de mãos vazias, espero?} # Once again you return to us, Chosen One. Not empty-handed, I hope?
{427}{}{Mim desculpa. Não achar GECK ainda.} # Me sorry, no find GECK yet.
{428}{}{Desculpe, eu ainda não encotrei o GECK.} # I'm sorry, I still haven't found the GECK.
{429}{}{Estou farto disso.} # I've had enough of this.
{430}{}{Pessoas estão morrendo enquanto você passeia pelas terras. Talvez você devesse procurar em outro lugar, ao invés de voltar aqui.} # People are dying here while you stroll about the lands. Perhaps you should be searching elsewhere instead of returning here.

{500}{}{Você já falou com a Anciã?} # Have you talked to the Elder yet?

#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Anciã} # Elder
{1001}{}{Fundador} # Founder
{1002}{}{Vault Dweller} # 
{1003}{}{Arroyo} # 
{1004}{}{Klamath} # 
{1005}{}{Vault} # 
{1006}{}{Escolhido} # Chosen One
{1007}{}{Xamã} # Shaman
{1008}{}{Hakunin} # 
{1009}{}{Healing Powder} # 
{1010}{}{Ponte} # Bridge 
{1011}{}{Mynoc} # 

{1100}{}{A anciã é a sua mãe e nossa lider.} # The Elder is your mother and our leader
{1101}{}{Nosso grande ancestral, que nos deu conhecimento.} # Our great ancestor who gave us knowledge.
{1102}{}{O primeiro a lutar e vencer o caos.} # The first to fight and win over chaos.
{1103}{}{Essa seria a nossa bela aldeia.} # That would be our beautiful village.
{1104}{}{É um posto avançado de troca que fica a alguns dias a leste daqui.} # That's trading outpost a few days east of here.
{1105}{}{O Vault é o céu.} # The Vault is heaven.
{1106}{}{Você é O Escolhido.} # You are the Chosen One.
{1107}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1108}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1109}{}{É um pó mágico que vai curá-lo, mas vai te deixar sonolento.} # It is a magic powder which will heal you, but will make you sleepy.
{1110}{}{A Grande Ponte fica ao sul de nossa aldeia.} # The Great Bridge exits our village in the south.
{1111}{}{Ele protege a ponte que dá acesso à nossa aldeia.} # He guards the bridge leading into our village.


#added by killap - expansion
{600}{}{Algum conselho final antes de eu partir para o desconhecido?} #Any final advice for me before I head out into the unknown?
#Certainly. Beware the weapons of the Outsiders. The gecko's bite is nothing compared to the destructive power of their boom-sticks.
{601}{}{Certamente. Cuidado com as armas dos Estranhos. Uma mordida do gecko é não é nada comparado com o poder destrutivo de suas patatas.}
{602}{}{Entendi. Mais alguma coisa?} #Got it. Anything else?
#Do not give your trust freely. Honor means very little out in the wastes. Stay alert and always question the motives of others.
{603}{}{Não confie em todos assim tão facil. Honra significa muito pouco no mundo la fora. Fique atento e sempre questione os motivos dos outros.}
{604}{}{Com certeza. Isso é tudo?} #Sure thing. Is that all?

#Never forget your roots. The world outside our village is full of shiny toys and luxuries that might make our life here in Arroyo appear simple and plain. But remember that the lifestyle of the Outsiders produces wicked men ruled by greed and corruption. Be wary not to become like He-Who-Must-Not-Be-Named.
{605}{}{Nunca esqueça suas raízes. O mundo fora da nossa aldeia está cheio de brinquedos brilhantes e luxos que podem tornar nossa vida aqui em Arroyo parecer simples. Mas lembre-se que o estilo de vida dos pessoas de fora produz homens maus governado pela ganância e corrupção. Seja cauteloso para não se tornar como Aquele-Que-Não-Deve-Ser-Nomeado.}
{606}{}{Eu nunca vou esquecer as minhas raízes. Obrigado pelo conselho, Mynoc.} #I'll never forget my roots. Thanks for the advice, Mynoc.
{607}{}{Aquele-Que-Não-Deve-Ser-Nomeado? Uh ... Quem?} #He-Who-Must-Not-Be-Named? Uh... who?
#Are you so drunk with the glory of being the Chosen One that you've forgotten about... [Mynoc quickly glances around to be sure no one is listening in, then leans forward and lowers his voice to a whisper.] ... Kaga?
{608}{}{Você está tão bêbado com a glória de ser O Escolhido que você esqueceu ... [Mynoc rapidamente olha em volta para se certificar de que ninguém está ouvindo, então se inclina para frente e abaixa a voz para um sussurro.] ... Kaga?}
{609}{}{Oh! Sim, aquele cara. Eu vou me certificar de que não vou ficar como ele. Obrigado.}
#Oh, that's who I thought you meant. But, uh, why don't you go ahead and tell me what his deal is again. I really love that story.
{610}{}{Ah, isso é o que eu to pensando. Mas, uh, por que você não vá em frente e me conte. Eu realmente adoro essa história.}
#[Mynoc mumbles something under his breath and shakes his head before beginning his tale.] As you should know, he was once the greatest warrior of our tribe. He led many expeditions into the outside world, and it was there where corruption began to poison his mind.
{611}{}{[Mynoc resmunga algo baixinho e balança a cabeça, antes de iniciar seu conto.] Como você deve saber, ele já foi o maior guerreiro de nossa tribo. Ele conduziu muitas expedições para o mundo exterior, e foi lá onde a corrupção começou a envenenar sua mente.}
#He became infatuated with the ways of the Outsiders, where power could bring anyone great respect and luxury. He began to view himself as superior to his fellow tribesmen who were content to live a more simple life.
{612}{}{Ele ficou encantado com os caminhos das pessoas do mundo exterior, onde o poder pode trazer a qualquer um respeito e luxo. Ele começou a se sentir superior aos seus companheiros de tribo que estavam contentes de viver uma vida mais simples.}
{613}{}{O que, que idiota.}
{614}{}{Continue.}
#When our tribe fell into these hard times, he deemed himself our people's savior and entered the Temple of Trials to prove himself to be the Chosen One.
{615}{}{Quando a nossa tribo caiu nestes tempos difíceis, ele se considerava salvador do nosso povo e entrou no Templo de Provações para provar a si mesmo ser o escolhido.}
{616}{}{Continue.}
{617}{}{Não importa, eu não quero ouvir essa história mais. Tchau.}
{618}{}{Ele fez o seu caminho através do Templo, atingindo rapidamente o teste final: uma batalha corpo-a-corpo com um guerreiro companheiro.}
{619}{}{Continue.}
#Wait, he blew up that door and everything? Do we have it rebuilt every time someone goes through the temple? Speaking of that, who built the temple in the first place?
{620}{}{Espere, ele explodiu a porta e tudo mais? Será que temos que reconstruir toda vez que alguém passa pelo templo? Falando nisso, quem foi o primeiro a construiu o templo?}
{621}{}{Eu não tenho tempo para responder a todas suas perguntas tolas. Você quer que eu terminar o conto, ou não?}
{622}{}{Desculpe. Por favor continue.}
{623}{}{Na verdade, eu acho que estou pronto para ir. Vejo você por aí.}
#During the final trial, He-Who-Must-Not-Be-Named unsheathed a hidden blade and used it to kill his opponent. When the Elder confronted him about his dishonorable use of a hidden weapon, he argued that it was not cheating, but rather proved him to be a cunning warrior.
{624}{}{Durante o julgamento final, Aquele-Que-Não-Deve-Ser-Nomeado desembainhou uma lâmina escondida e usou para matar seu oponente. Quando a Ãnciar confrontou sobre seu uso desonroso de uma arma escondida, ele argumentou que não estava traindo, mas ele provou ser um guerreiro astuto.}
{625}{}{A Ãncia não concordou. Aquele-Que-Não-Deve-Ser-Nomeado foi forçosamente exilado de nossa tribo e seu nome nunca mais pode ser falado entre nós novamente. Como ele foi expulso para longe, ele fez um juramento de vingança. Vingança contra a nossa tribo, e, especialmente, contra você.}
{626}{}{De mim? O que eu fiz?}
{627}{}{Agradeço pela história, mas é melhor eu voltar para meu caminho agora.}
{628}{}{Você é o Escolhido, um título que ele sente ser seu por direito. Seu orgulho não vai permitir que você viva.}
{629}{}{Eu não vou me preocupar com isso. Ele provavelmente já deve estar morto.}
{630}{}{Eu vou estar preparado. Esperamos que ele esteja morto.}
{631}{}{Ouça e entenda. Aquele-Que-Não-Deve-Ser-Nomeado está lá fora. Ele não pode ser enganado. Ele não vai sentir pena ou remorso, ou medo. E ele absolutamente não vai parar, nunca, até que você esteja morto.}
{632}{}{Sabe, eu acho que você esta exagerando um pouco com o melodrama. De qualquer forma, obrigado pelo conselho. Vejo você por aí, Mynoc.}
{633}{}{Eu vou me lembrar disso. Tome cuidado, Mynoc.}

{640}{}{Você poderia me dizer alguma coisa sobre esse tal cara Kaga?}
#[His eyes go wide and he looks around nervously as if expecting to suddenly be struck by lightning.] Have you lost your senses out in the wastes?! You should know better than to speak the name of the outcast! He is to be referred to only as He-Who-Must-Not-Be-Named. Our village suffers enough without inviting the wrath of the Gods upon us. [He raises his eyes nervously to the sky.]
{641}{}{[Seus olhos estão arregalados e olha em volta nervosamente, como se esperasse de repente ser atingido por um raio.] Você perdeu seus sentidos la fora! Você deve saber melhor do que todos que não deve dizer o nome do maldito! Ele deve ser referido apenas como Aquele-Que-Não-Deve-Ser-Nomeado. A nossa aldeia sofre o suficiente sem convidar a ira dos deuses sobre nós. [Ele levanta os olhos nervosamente para o céu.]}
#Sorry about that, Mynoc. But would you mind telling me what Ka... I mean, "He-Who's" deal is again? I really love that story.
{642}{}{Desculpe por isso, Mynoc. Mas você se importaria de me contar sobre Ka... quero dizer, "Aquele-Que-Não-Deve..." de novo? Eu realmente adoro essa história.}
#You know, I'd forgotten how stupidly superstitious you people could be. I'll see you around.
{643}{}{Você sabe, eu tinha esquecido de como estupidamente supersticioso vocês são. Te vejo por aí.}

#I've faced him before, so I'm sure I can handle him if our paths cross again.
{650}{}{Já enfrentei ele antes então tenho certeza que eu posso lidar com ele, se os nossos caminhos se cruzam novamente.}
#Actually, he's already dead. I left his corpse out there to rot in the wastes.
{651}{}{Na verdade, ele já está morto. Deixei seu cadáver apodrecer nos desertos.}
#[Mynoc nods grimly.] He may have strayed from the path, but he was once a great and respected warrior. I hope his troubled soul has found peace in the next world.
{660}{}{[Mynoc acena sombriamente.] Ele pode ter se desviado do caminho, mas ele já foi um grande e respeitado guerreiro. Espero que sua alma perturbada encontre a paz no outro mundo.}

{661}{}{De fato. Te vejo por aí, Mynoc.}
#Whatever. He seemed like an asshole to me. I'll see you around, Mynoc.
{662}{}{Tanto faz. Pra mim ele parecia ser um idiota. Te vejo por aí, Mynoc.}