#############################################################
#  Message File: ACSporPL.msg                               #
#                                                           #
#       Body Type:  Spore Plant(Plant with Dark Soul)       #
#       Combat AI: ?                                        #
#       Weapons: ?                                          #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê uma planta da alma escura.}
{101}{}{Estas plantas não só são prejudiciais para o jardim como também tem a capacidade de atacar os seres humanos e outras criaturas.}
{102}{}{Estas plantas de almas escuras são mutações estranhas. É duvidoso que se transformaram por fenômenos naturais.}
{103}{}{Você percebe que não tem nada de especial nessas plantas - além do fato de que atacam os seres humanos.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################
{150}{}{Você deve se livrar de todas essas plantas do jardim.}
