{100}{}{Você vê Cameron, um irmão da tribo.}
{101}{}{Você está vendo Cameron.}
{102}{}{Você está vendo um homem muito confiante e musculoso.}
{103}{}{Saudações, }
{104}{}{. Tenho a honra de ser seu último desafio. Para terminar seu teste você deve me derrotar em um combate desarmado. Você está pronto?}
{105}{}{Tenho umas perguntas.}
{106}{}{Ok, vamos lutar.}
{107}{}{Não, tenho que me preparar primeiro.}
{108}{}{Antes gostaria de te fazer algumas perguntas.}
{109}{}{Claro! Agora sim começou a diversão!}
{110}{}{Acho que preciso de um momento para me preparar.}
{111}{}{O que você quer saber?}
{112}{}{Por que tem que lutar?}
{113}{}{Nós vamos lutar até a morte?}
{114}{}{Vamos lutar desarmados?}
{115}{}{Ok, agora vamos lutar.}
{116}{}{Tenho que me preparar.}
{117}{}{Por que nós temos que lutar?}
{118}{}{Isso vai ser uma luta até a morte?}
{119}{}{Você está dizendo que vamos lutar desarmado?}
{120}{}{Vamos acabar com isso.}
{121}{}{Espere, ainda preciso de um tempo para me preparar.}
{122}{}{O caminho do escolhido não será fácil, }
{123}{}{. Você vai se deparar com muitos desafios ao logo de sua jornada, cada um mais difícil que o outro. Chegará um momento em que nem a diplomacia nem a sagacidade serão úteis. Este desafio prepara você para lidar com outro ser humano. Para olhar em seus olhos e saber se você vai ter que matá-lo.}
{124}{}{Okay.}
{125}{}{Entendo.}
{126}{}{Não, meu amigo, você só precisa me derrotar. Quando você fizer isso, acabaremos com a batalha.}
{127}{}{Entendo.}
{128}{}{Tudo bem.}
{129}{}{Sim, armas tendem a nos distanciar da batalha e dessensibilizam os efeitos de nossas ações contra os outros. Quando você bate utilizando seu corpo, ambos sentem a dor que você vai causar. A batalha é muito pessoal e real. Esta é uma lição importante para você, }
{130}{}{.}
{131}{}{Entendo.}
{132}{}{Entendo.}
{133}{}{Muito bem. Vamos começar?}
{134}{}{Estou pronto.}
{135}{}{Não, eu tenho que me preparar primeiro.}
{136}{}{Estou pronto.}
{137}{}{Não, eu preciso de algum tempo para me preparar.}
{138}{}{Muito bem. Volte quando você estiver pronto para continuarmos desafio.}
{139}{}{Você está pronto para o seu desafio, }
{140}{}{?}
{141}{}{Estou pronto. }
{142}{}{Ainda não estou pronto.}
{143}{}{Acho que sim.}
{144}{}{Não, me dê um minuto.}
{145}{}{Excelente! Seu equipamento será armazenado na entrada da sala. Você poderá recuperá-lo após o desafio. Que comece o desafio! Boa sorte para você, }
{146}{}{.}
{147}{}{É um prazer vê-lo novamente, Escolhido. Como posso ajudá-lo?}
{148}{}{Eu quero entrar no templo outra vez.}
{149}{}{Quer lutar novamente?}
{150}{}{Apenas vim dizer olá. Saindo agora.}
{151}{}{Eu gostaria de visitar o templo novamente.}
{152}{}{Olá, Cameron. Está se preparando para outro combate?}
{153}{}{Só queria dizer um oi. Até mais.}
{154}{}{Pegue o caminho à minha esquerda, Escolhido. Isso vai te levar ao templo. A entrada da caverna atrás de mim faz voltar para a última câmara.}
{155}{}{Okay, agora tenho que ir.}
{156}{}{Tudo bem.}
{157}{}{Nem pensar, Escolhido. Eu ainda carrego as feridas do nosso último encontro, e vou precisar de tempo para me recuperar!}
{158}{}{Adeus, Cameron.}
{159}{}{Bom dia para você, Cameron.}
{160}{}{Escolhido é o cacete! Eu vou matar você!}
{161}{}{Você me derrotou. Você é digno, Escolhido.}
{165}{}{Eu discordo de você. Eu acho que sempre vai ter uma solução pacífica para qualquer problema.}
{166}{}{Você pode está certo, }
{167}{}{, mas não em nossa situação atual. Você tem que me derrotar para concluir o teste.}
{168}{}{Olha, eu não sei de todos os seus pontos fortes e fracos, e você também não sabe dos meus. Acidentes acontecem. E se um de nós acidentalmente matar o outro? Vamos acabar logo com isso antes que aconteça alguma coisa, ok?}
{169}{}{Hmmm... faz sentido. Eu não gostaria de ser o responsável por sua morte, tudo que eu queria era provar o seu valor. Muito bem - você pode passar, Escolhido.}
{170}{}{Hmm... faz sentindo. No entanto, ainda temos que batalhar. Eu vou simplesmente ter o cuidado para não te machucar... muito.}
{171}{}{Obrigado! Vejo você na aldeia.}
{172}{}{Eu entendo.}
{200}{}{Ainda me lembro da nossa última batalha, Escolhido. Eu sempre estou me perguntando como foi que você me derrotou.}
{201}{}{Você tem uma língua de ouro, Escolhido. Sua habilidade com as palavras vão-lhe abrir muitas portas.}
{300}{}{Para você também, Escolhido. Que os espíritos te guiem em sua busca.}
{301}{}{Obrigado, Cameron.}
{302}{}{Escolhido, não pude deixar de notar que você não tem habilidades em combate fortes. Minha experiência me diz que você não pode sempre confiar em usar sua inteligência ou na sua língua para te proteger. Com sua permissão vou te ensinar algumas técnicas que eu acho que você vai achar muito úteis.}
{303}{}{Sim, você pode me ensinar.}
{304}{}{Não, não quero sua ajuda.}
{305}{}{Sim, por favor me ensine tudo o que você puder.}
{306}{}{Obrigado, mas eu acho que posso me cuidar sozinho.}
{307}{}{Você aprende rápido, Escolhido. Acho que de agora em diante você será capaz de se cuidar sozinho. Mas lembre-se que mesmo o mais forte dos guerreiros as vezes, devem recuar. Não há vergonha em viver para lutar no outro dia.}
{308}{}{Muito obrigado, Cameron.}
{309}{}{Obrigado, Cameron. Eu lembrarei de suas palavras.}
{310}{}{Okay, caso mude de idéia, é só voltar aqui.}
{311}{}{Obrigado, Cameron.}
{312}{}{Obrigado, Cameron. Eu vou me lembrar dessa oferta.}

#added by killap - expansion
#Do you ever think about stepping down from your position as the Temple's final trial? I mean, it can be pretty risky.
{400}{}{Depois que eu passei no teste do Templo você já pensou em largar de mão de toda essa história de "Desafio Final do Templo"? Quero dizer, isso parece ser muito arriscado.}
#Life is a constant series of risks, Chosen One. With each new dawn, every one of us takes a risk simply by stepping from our homes to greet the unknown day. Why do you ask?
{401}{}{A vida é uma série constante de riscos, Escolhido. A cada novo amanhecer, cada um de nós assume um risco simplesmente por pisar em nossas casas para saudar o dia desconhecido. Por que pergunta?}
{402}{}{Nada não. Falo com você mais tarde, Cameron} #No reason. I'll talk with you later, Cameron
#Well, I was just thinking about what happened to your predecessor, you know, during his battle with... uh, "He-Who-Must-Not-Be-Named".
{403}{}{Bem, eu estava pensando sobre o que aconteceu com o seu antecessor, você sabe, durante sua batalha com ... uh, "Aquele-Que-Não-Deve-Ser-Nomeado"..}

#Ah, that was a dark day, indeed, for our tribe lost two good men: one in body, the other in spirit. But the foul deed of that day is no concern of mine. My time will come when the Gods deem it so.
{410}{}{Ah, de fato, isso foi um dia sombrio para a nossa tribo. Perder dois bons homens: um no corpo do outro, em espírito. Mas o acontecido daquele dia não é problema meu. Minha hora vai chegar quando os deuses decidirem.}
{411}{}{E que este dia demore muito a chegar. Tenha um bom dia, Cameron..} #And may that day be a long time coming. Good day, Cameron.
#Are they even going to have other people attempt the Temple? Hasn't it already been determined that I'm the Chosen One?
{412}{}{E por acaso mais alguém vai ser testado no templo? Eu já não provei que sou O Escolhido?}

#There will always be a need to test the might of our people. And I take great honor in doing my part.
{420}{}{Haverá sempre a necessidade de testar a força do nosso povo. E tenho muita honra em fazer minha parte.}
{421}{}{Tudo bem. Te vejo mais tarde, Cameron.} #Alright, I'll see you later, Cameron.