#############################################################
#  Message File: ACVillgr.msg                               #
#                                                           #
#       Body Type:  NAROBE                                  #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você está vendo um homem em sua aldeia.}
{101}{}{Você está vendo uma mulher em sua aldeia.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Um membro gentil de sua aldeia.}
{151}{}{[FALAR]}
{152}{}{Olá! Ouvi dizer que você é o Escolhido. Talvez agora a nossa aldeia possa ser salva.}
{153}{}{Você poderia me dizer onde eu posso encontrar healing powder?}
{154}{}{O que você pode me dizer sobre os comerciantes que negociam com a gente?}
{155}{}{Que bom te ver, mas eu tenho que ir.}
{156}{}{Que os Deuses lhe protejam em sua busca.}
{157}{}{Eu tenho uma pergunta para você.}
{158}{}{Adeus, meu amigo.}
{159}{}{Vá ver Hakunin na parte norte da cidade. Ele pode ajudá-lo.}
{160}{}{Muito obrigado. Adeus.}
{161}{}{Oh, eu não costumo lidar com os comerciantes. Fale com Mynoc, o guardião da grande ponte. Ele lida com todos.}
{162}{}{Muito obrigado. Adeus.}
{163}{}{Você pode me dizer onde se encontra a grande ponte?}
{164}{}{Só mais uma pergunta, se me permite.}
{165}{}{Boa piada, Escolhido! Você sabe onde ele está. Lá - para o sul.}
{166}{}{Muito obrigado. Adeus.}
{167}{}{Só mais uma pergunta, se me permite.}
{168}{}{Claro, o que é?}
{169}{}{Você poderia me dizer onde eu posso encontrar algumas healing herbs?}
{170}{}{O que você pode me dizer sobre os comerciantes que negociam com a gente?}
{171}{}{Nada, não importa.}
{172}{}{Oh Deus - Que os espíritos do Fundador te guiem. Se você for o Escolhido, nós vamos precisar de você.}
{173}{}{Uun Ga.}
{174}{}{Tenha uma boa viagem.}
{175}{}{????}
{176}{}{Estamos condenados! Você falhou em sua missão.}
{177}{}{Você não pode continuar assim.}
{180}{}{Você é um traidor do seu próprio povo.}
{181}{}{Por que você faz isso?}
{182}{}{Você é mal. O Escolhido é muito mal!}
{183}{}{Eles vêm à nossa aldeia do leste, embora muitas vezes trazem poucas coisas.}
{184}{}{Você poderia me dizer onde eu posso encontrar mais healing powder?}
{185}{}{Obrigado. Adeus}
{186}{}{Só mais uma pergunta, se me permite.}

# Starting Dialog after 1st Hakunin Movie
{300}{}{Olá, Escolhido. Fico feliz em vê-lo novamente. Rezo para que esta missão sagrada esteja indo bem. Existe alguma coisa que possa te ajudar?}

# Starting Dialog after 2nd Hakunin Movie
{301}{}{Escolhido, o nosso povo está morrendo. Você deve se apressar para encontrar o GECK. Em que eu posso te ajudar em sua busca?}

# Starting Dialog after 3rd Hakunin Movie
{302}{}{Estamos correndo contra o tempo, Escolhido. Por favor, conclua sua missão logo. Não podemos dar ao luxo de esperar mais. Se há alguma coisa em que eu possa ajudá-lo, deixe-me saber.}

# Starting Dialog after 4th Hakunin Movie
{303}{}{Escolhido, a nossa aldeia está quase morta ... você é a nossa única esperança. Existe algo que eu possa te ajudar para nossa salvação?}


#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Ãncia}
{1001}{}{Fundador} #Founder
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{O Escolhido} #Chosen One
{1007}{}{Xamã}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Ponte} #Bridge
{1011}{}{Mynoc}

{1100}{}{A anciã é a sua mãe e nossa lider.} # The Elder is your mother and our leader
{1101}{}{Nosso grande ancestral, que nos deu conhecimento.} # Our great ancestor who gave us knowledge.
{1102}{}{O primeiro a lutar e vencer o caos.} # The first to fight and win over chaos.
{1103}{}{Essa seria a nossa bela aldeia.} # That would be our beautiful village.
{1104}{}{É um posto avançado de troca que fica a alguns dias a leste daqui.} # That's trading outpost a few days east of here.
{1105}{}{O Vault é o céu.} # The Vault is heaven.
{1106}{}{Você é O Escolhido.} # You are the Chosen One.
{1107}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1108}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1109}{}{É um pó mágico que vai curá-lo, mas vai te deixar sonolento.} # It is a magic powder which will heal you, but will make you sleepy.
{1110}{}{A Grande Ponte fica ao sul de nossa aldeia.} # The Great Bridge exits our village in the south.
{1111}{}{Ele protege a ponte que dá acesso à nossa aldeia.} # He guards the bridge leading into our village.

#added by killap - expansion
{400}{}{Há alguma coisa coisa que você poderia me dizer sobre Kaga?} #Is there anything you could tell me about Kaga?
{401}{}{[O morador olha para você de olhos arregalados, depois, lentamente, se distância de você, olhando a seu redor, nervosamente.]} #[The villager stares at you, wide-eyed, then slowly steps away from you while glancing around nervously.]
{402}{}{Tudo bem, acho que não.} #Alright, I guess not.}