{100}{}{Procure a Anciã de sua aldeia.}
{101}{}{É a Anciã.}
{102}{}{A Anciã é apenas isso - velha, mais velha do que você se lembra. No entanto, ela tem a força e fogo para liderar a aldeia através destes tempos difíceis.}
{103}{aeld1}{Parabéns, Escolhido, você sobreviveu ao Templo de Provações. Você está pronto para a sua missão?}
{104}{}{O que você estava fazendo - tentando me matar no templo?}
{105}{}{É claro}
{106}{}{Eu gostaria de pensar sobre isso.}
{107}{aeld2a}{Estou orgulhosa de você, Escolhido. Você se superou muito. Agora você deve ir e encontrar o Vault 13. Traga o GECK para casa. Aqui uma garrafa brilhante que Vic nos deu. Vic é um comerciante em Klamath. Procure Vic. Encontre o Vault 13. Encontre o GECK. Volte para casa. Faça o seu melhor, jovem.}
{112}{aeld2b}{Você não encontrou o Vault. Encontre o Vault! Vault 13.}
{113}{}{Uh.}
{114}{aeld3}{Escolhido, você quer nos ver todos mortos? Você deve encontrar o Vault!}
{115}{}{Sinto muito, Anciã. Eu não vou falhar.}
{116}{}{Sim, sim. Pare de tagarelar.}
{117}{aeld4}{Escolhido, por que você está aqui?}
{118}{}{Eu sei onde está Vault 13!}
{119}{}{Estou pronto para a missão sagrada.}
{120}{}{Eu preciso de mais informações.}
{121}{}{Eu não vou me matar!}
{122}{}{O que eu deveria fazer agora?}
{123}{}{Estou indo agora.}
{124}{aeld5}{Isso é uma boa notícia, mas não o suficiente para nos salvar. Você deve voltar em breve com o GECK ou o nosso povo morrerá.}
{125}{}{Eu preciso de mais informações.}
{126}{}{Tudo bem, eu estou indo agora.}
{127}{aeld6}{Você sobreviveu. O Escolhido não pode ser fraco ou estaremos todos condenados. Você está preparado para a sua missão?}
{128}{}{Eu passei no teste. Claro que estou pronto.}
{129}{}{Eu vou pensar sobre isso.}
{130}{}{Eu não vou me matar!}
{131}{aeld7}{Preste atenção. Encontre o refúgio Vault 13 e traga de volta o GECK. Vic, o comerciante de Klamath trouxe este frasco do refúgio 13. Comece sua busca por ele. Este disco vai lembrá-lo de sua missão. Que os Deuses do Vault te protejam.}
{133}{}{Antes de eu partir, eu tenho algumas perguntas.}
{134}{}{Goodbye. Eu não vou deixar a tribo}
{135}{aeld8}{Muito bem. Procure por mim quando você se decidir - mas não espere muito tempo.}
{136}{}{Adeus.}
{137}{aeld9}{Eu não posso ajudar muito. Tanta coisa se perdeu ao longo desses anos. O que você quer saber?}
{138}{aeld9b}{O que você precisa?}
{139}{}{Me diga mais informações sobre o GECK.}
{140}{}{Como chego em Klamath?}
{141}{}{Onde é o Vault 13?}
{142}{}{Pensando bem, eu não preciso te ajudar agora. Adeus.}
{143}{aeld10}{O Garden of Eden Creation Kit - é um artefato sagrado. O Disco promete que vai fertilizar nossas terras e nossa aldeia vai prosperar novamente. Ele vai nos salvar. Eu não sei mais do que isso.}
{144}{}{Tem mais coisas que eu quero saber.}
{145}{}{Adeus.}
{146}{aeld11}{Klamath fica ao leste.}
{147}{}{Há outras coisas que você poderia contar.}
{148}{}{Estou pronto. Adeus.}
{149}{aeld12}{Vault 13? Eu não posso te ajudar. Somente o Vault Dweller. Suas histórias tem um som de uma jornada perigosa.}
{150}{}{Eu vejo. Há muito que eu preciso saber.}
{151}{}{Adeus, Anciã}
{152}{aeld13}{Sendo um covarde vai matar todos nós! Inclusive você. Você passou no Templo de Provações. Temos fé em você. Nós precisamos de você.}
{153}{}{Não tão rápido, velha Anciã. Preciso de tempo para pensar sobre isso!}
{154}{}{Como quiser, Anciã.}
{155}{aeld14a}{Você nos traiu. Você vai morrer.}
{156}{aeld14b}{Você é um traidor!}
{157}{aeld14c}{Por que está fazendo isso?}
{158}{aeld14d}{Eu sabia que sua alma estava nas trevas!}
{159}{aeld15}{Então, tome este frasco. É uma parte do refúgio Vault 13. Vic, um comerciante de Klamath, trouxe pra nós. Ele pode saber onde está o refúgio. Você também pode precisar de um pouco do que eles chamam de dinheiro. Pegue!}
{160}{}{Eh? Você pode me dizer mais uma vez sobre a minha missão?}
{161}{}{Há algo mais para contar?}
{162}{}{Deseje-me sorte, Anciã, e eu não falharei com você.}
{163}{aeld16}{Encontre Vic em Klamath. Estamos contando com você.}
{164}{aeld17}{É bom vê-lo novamente, Garoto. Não deve ser abrupta, mas eu vejo que você não completou a sua missão do Vault 13. Por favor, não perca tempo falando. A necessidade de nosso povo é grande. Vá encontrar o Vault!}
{165}{}{Tenho que ir agora.}
{166}{}{Ok, eu vou embora.}
{167}{}{Não vou falhar Anciã}
{168}{}{Eu estou trabalhando nisso, ok?}
{169}{aeld18}{Mais uma vez você volta sem o GECK. Nossas colheitas estão estragando, Escolhido. Nossa necessidade se torna maior ao longo do tempo. Vá encontrar o Vault 13}
{170}{}{Ok, estou indo agora.}
{171}{}{Sim, Anciã}
{172}{}{Não deixarei você ou nosso povo, Anciã}
{173}{}{Olhe. Se você acha que pode fazer melhor...}
{174}{aeld19}{Escolhido, as coisas não estão bem aqui, Precisamos do GECK para nossa aldeia sobreviver. Nosso povo enfraquecidos pela fome e as nossas reservas de alimentos não vão durar muito tempo. Por favor, encontre o Vault 13 e volta aqui. Agora vá.}
{175}{}{Estou indo.}
{176}{}{Muito bem. Eu vou embora.}
{177}{}{Eu farei o meu melhor para encontrar o GECK e salvar nossa aldeia.}
{178}{}{Não me pressione, velha. Eu estou fazendo o melhor que posso.}
{179}{aeld20}{Jovem. A nossa necessidade é maior do que nunca. Nosso povo adoece, o gado está morrendo e a nossa comida está acabando. A ruína desta terra só pode ser curada com o GECK. Vá encontrar o GECK e salvar nosso povo.}
{180}{}{Eu entendo.}
{181}{}{Eu vou embora.}
{182}{}{Perdoe-me Anciã. Eu vou encontrar o GECK sem demorar.}
{183}{}{Sim, sim. Você está começando a parecer como um disco quebrado...}


{200}{eeld1}{Escolhido! Como você chegou aqui?}
{201}{}{Uhh? duh?}
{202}{}{Eu vim para te salvar.}
{203}{}{Que diabos está acontecendo aqui?}
{204}{eeld2}{Seu monstro! Você veio para me matar, também?}
{205}{}{Uhhh?}
{206}{}{Não, sou eu, o Escolhido!}
{207}{}{OOh, cale-se, sua puta velha! Eu sou o Escolhido}
{208}{eeld3}{Oh, Deus... Ouça - veja abaixo. Encontre que faz luz. Matar máquina. Matem todos. Você mata, voltamos para casa. Se você não tem o GECK, procure o GECK aqui. Deve ter o GECK para salvar a aldeia! Liberdade não é nada se não temos uma casa para onde voltar. Você entendeu? Oh, Deus.}
{209}{}{Uh -huh!}
{210}{eeld4}{Cuidado, não toque na parede que brilha. Acho que o que alimenta a máquina está atrás de nós. Destrua para que possamos escapar. Como você chegou aqui?}
{211}{}{Eu tenho um barco. }
{212}{eeld5}{Homens com máquinas voadoras veio a nossa aldeia e nos levou. Havia outros, também - a partir do Vault 13! Pensei que estávamos salvos. Pensei que estámos indo para o céu. (suspiro)}
{213}{}{E depois?}
{214}{eeld5a}{Em seguida, fomos trazidos aqui, para o inferno. Eles mataram a maioria de nós com algo que eles chamam de effeevee. Eles não vão parar até matar todos nós! Você sabe o que fazer, Escolhido?}
{215}{}{Effeevee?}
{216}{}{Sim.}
{217}{}{Não.}
{218}{eeld6}{Se você destruir a máquina, podemos encontrar o navio. Depressa, não restaram muitos de nós. }
{219}{}{O que aconteceu?}
{220}{}{Eu entendo.}
{221}{eeld7}{Você tem que destruir a máquina e matar os demômios deste lugar. Vamos encontrá-lo lá fora! Escolhido, se você ainda não encontrou o GECK, procure-o aqui. A nossa liberdade não é nada se não podemos salvar a nossa aldeia. Agora vá.}
{222}{}{Adeus.}
{223}{eeld8}{Eu ainda sou a Anciã. Lembre-se de seu lugar! Peça desculpas ou não ajudarei em nada.}
{224}{}{Desculpe, você não é uma puta Anciã. Agora, o que está acontecendo aqui?}
{225}{}{Como você poderia me ajudar aqui? Foda-se e morra.}
{226}{eeld9}{Vá embora. Você não é melhor do que esses demônios. Eu lamento o dia em que nomeei você Escolhido.}
{227}{eeld10}{Por que diabos ainda está aqui? Cada minuto que você perde um do nosso povo morre. E não se esqueça do GECK. Temos que obtê-lo.}
{228}{}{Nuh??}
{229}{}{Onde eu deveria ir?}
{230}{}{Só queria te irritar. Eu estou nessa. Não se preocupe.}
{231}{eeld11}{(sigh) Vai logo. Mate. Esmague as máquinas. Agora vá!}
{232}{eeld12}{Ouça uma vez! Vá para os níveis abaixo de nós. Encontre a máquina que dá energia. Pare ela e poderemos escapar. Os homens aqui não são fiéis para o Vault. Eles são maus. Além disso, se você ainda não encontrou o GECK, procure-o aqui. A nossa liberdade não é nada se a nossa aldeia possa ser salva. Agora vá!}
{233}{}{Entendi.}
{234}{eeld13}{Isso é o que eles chamam. Vão enfiar agulhas em nossas peles, como stimpacks, e depois as coisas ainda vão piorar. Então... (engasgando)}
{235}{}{Então o quê?}
{236}{}{Isso vai me fazer mal, não é?}
{237}{eeld13a}{Em seguida, sua pele borbulha como se tivessem vermes nela. Ferve cresce e depois explodi. O seu ouvido sangra, sua língua incha. Aqueles que são que tiveram a sorte de morrer. Aqueles que não são?}
{238}{}{Eles vão pagar por isso.}
{239}{}{Isso com certeza é desagradável. O que eu devo fazer?}


#verificar depois, tem na tradu espanhol mais nao no ingles
#240-Tengo un verti-, eh, una máquina voladora.
#241-Si destruyes la máquina, encontraremos tu máquina voladora. Date prisa, no quedamos muchos de nosotros.
#######
