# Noob-Saibot Traduziu esse arquivo.
{100}{}{Você vê um monge.} # You see a monk.
{101}{}{Você vê uma religiosa.} # You see a holy woman.
{102}{}{Você vê um monge comum de Abbey.} # You see a regular Abbey monk.
{103}{}{Você vê uma freira comum de Abbey.} # You see a regular Abbey nun.

{200}{}{Bem-Vindo, viajante.} # Welcome traveler.
{201}{}{Vá em Paz.} # Peace to you.
{202}{}{Nós somos os guardiões do conhecimento.} # We are the guardians of knowledge.
{203}{}{Olá.} # Hi.
{204}{}{O tempo está bonito.} # Nice weather.
{205}{}{Eu espero que você aproveite sua estadia aqui.} # I hope you enjoy your stay here.

{500}{}{Pare com isso!} # Stop that!

