{100}{}{Você vê um monge.}
{101}{}{Esse monge parece ser um comerciante.}

{200}{}{Seja bem-vindo viajante.}
{201}{}{Desejo paz para você.}
{202}{}{O tempo está bom.}
{203}{}{Vá jogar em outro lugar.}

{300}{}{Olá, como eu posso ajudá-lo?}
{301}{}{O que você pode me dizer sobre o seu pedido?}
{302}{}{Vamos negociar.}
{303}{}{Até logo.}

{400}{}{Nossa missão é coletar e preservar as relíquias sagradas do passado esquecido. 
 Qualquer um é bem-vindo aqui, contanto que ninguém danifique nada.}
{401}{}{Quem é o seu líder?}
{402}{}{Qual o tipo de relíquia?}
{403}{}{Ele pode ser encontrado no terceiro andar. Se você desejar saber mais sobre nós, 
eles é o primeiro a falar com você.}
{404}{}{Todos os tipos, mas a maioria de nossos registros são de coisas antigas. Muitas informações podem ser obtidas nesses arquivos. Nossa missão é preservar esse conhecimento para a geração futura e usá-lo para construir um mundo de paz e alegria.}
{405}{}{Certo.}
{406}{}{Tudo bem.}

{500}{}{Pare ai!}
