#You see a computer monk.
#You see Brother Paul.
{100}{}{Você vê um computador monge.}
{101}{}{Você vê o irmão Paul.}
#This monk looks like a computer geek.
{102}{}{Este monge parece um nerd de computador.}

#Hi!
{200}{}{Oi!}
#Hello.
{201}{}{Olá.}
#Now, did I backup those computer files today...
{202}{}{Agora, eu fiz o backup dos arquivos de hoje do computador...}
#I'm sorry, but I don't have time for someone of your intelligence.
{203}{}{Me desculpe, mas não tenho tempo para alguém de sua inteligência.}

#Yes?
{300}{}{Sim?}
#You guys sure have a lot of computers here.
{301}{}{Vocês com certeza tem um monte de computadores aqui.}
#What can you tell me about the Abbey?
{302}{}{O que você pode me dizer sobre o Abbey?}
#Tell me about your leader.
{303}{}{Me fale sobre seu líder.}
#Do you have any info about a GECK?
{304}{}{Você tem alguma informação sobre o GECK?}
#Do you know where I could find Vault 13?
{305}{}{Você sabe onde eu poderia encontrar Vault 13?}
#Bye.
{306}{}{Tchau.}
#I am in need of some specific information.
{307}{}{Eu estou precisando de algumas informações específicas.}
#Such as?
{308}{}{Tipo?}

#Yes, we have. Too many, in my opinion. I can't express to you the tedium of having to back up all these files
 each and every day. There's just so much information to preserve, but, of course, it must be done.
{400}{}{Sim, nós temos. Muitos, na minha opinião. Não consigo expressar o tédio de ter que fazer backup de todos os arquivos
 a cada dia. Há tanta informação para preservar, mas, claro, isso tem que ser feito.}
#Of course. Anyway, I have some other questions.
{401}{}{Claro. De qualquer forma, eu tenho algumas outras perguntas.}
#We are an independent community. Anyone is welcome as long as they behave themselves.
{402}{}{Somos uma comunidade independente. Qualquer um é bem-vindo, desde que se comportem.}
{403}{}{Ok.}
#The Abbot is a good spiritual leader, but he's been a little cranky since we lost Brother Thomas to the beast.
{404}{}{O Abade é um bom líder espiritual, mas ele tem sido um pouco irritado desde que perdeu o irmão Thomas para à besta.}
#What kind of beast?
{405}{}{Que tipo de besta?}
#I haven't seen it, personally--there's nothing in the world that could get me to go down there and explore those
 caverns--but if I had to guess, I'd say it's probably just some overgrown radscorpion.
{406}{}{Eu não vi pessoalmente - não há nada no mundo que possa me fazer ir lá e explorar
 essas cavernas - mas se eu tivesse que adivinhar, eu diria que provavelmente são apenas alguns radscorpions.}
 #If you haven't seen it, then what makes you think it's a radscorpion?
{407}{}{Se você ainda não viu, então o que faz você pensar que é um radscorpion?}
#Because I've heard sounds echoing up from the caves--the sounds of snapping claws and skittering legs.
{408}{}{Devido aos sons que eu ouvi ecoando das cavernas - os sons de estalar garras e deslizando pernas.}
#Right.
{409}{}{Certo.}
#In fact, we do. Take a look on that computer over there. Here, you can use this card to access our encrypted files. [He hands you an access card.]
{410}{}{Na verdade, o que fazemos. Dê uma olhada no computador lá. Aqui, você pode usar este cartão para acessar nossos arquivos criptografados. [Ele te entrega um cartão de acesso.]}
#Wow, thanks a lot!
{411}{}{Uau, muito obrigado!}
#I don't know anything about Vault 13, but there is Vault City down south. Maybe they have the info you need.
{412}{}{Eu não sei nada sobre o Vault 13, mas Vault City fica sul. Talvez eles têm a informação que você precisa.}
#Thanks
{413}{}{Obrigado}
#That computer near me should have the information you seek, but you'd need an access card to use it.
 #We're very selective with who we give access to, but if you speak to the Abbot, perhaps he'll grant you permission.
{414}{}{Esse computador próximo a mim deve ter a informação que você procura, mas você precisa de um cartão de acesso para usá-lo.
 Estamos muito seletivo para permitir o acesso, mas se você falar com o Abbot, talvez ele vai lhe conceder.}
#Ok, thanks.
{415}{}{Ok, obrigado.}

#I'm guessing you've read a lot of books in your time. So I'm curious, what's the most fascinating thing you could tell me?
{420}{}{Eu suponho que você já leu um monte de livros pela sua idade. Então, como eu sou curioso, qual é a coisa mais fascinante que você poderia me dizer?}

#new in RP 1.3
#Hmm, let's see. Did you know a notch in a tree will remain the same distance from the ground as the tree grows?
{421}{}{Hmm, vamos ver. Você sabia que um entalhe em uma árvore permanecerá a mesma distância do solo mesmo a árvore continuando a crescer?}
#Uh, no, I can't say I knew that. That's...interesting.
{4210}{}{Uh, não, eu não posso dizer que eu sabia disso. Isso é...interessante.}
#And did you know a cucumber is 96% water?
{4211}{}{E você sabia que um pepino tem 96% de água?}
#Wow, 96%, huh? Fascinating. But, um, what's a cucumber?
{4212}{}{Uau, 96%...? Fascinante. Mas, hum, o que é um pepino?}
#I've never seen one, but I've read about them. [He looks around nervously and lowers his voice.] I know we're
 not supposed to actually study these books, but when I was transcribing a book on botany, I just couldn't help but get
 sucked into it. The world of plants is simply captivating. Perhaps, if, during your travels, you happen upon some botany
 information, you could bring it to me? I'd be most grateful. Of course, it'd have to be our secret.
{4213}{}{Eu nunca vi um, mas eu li sobre eles. [Ele olha em volta nervosamente e abaixa a voz.] Eu sei que não
 deveria poder estudar esses livros, mas quando eu estava transcrevendo um livro sobre botânica, Eu simplesmente não podia
 deixar de ser sugado para ele. O mundo das plantas é simplesmente cativante. Talvez, se durante suas viagens você encontrar
 informações sobre botânica, você pode trazê-los para mim? Eu ficaria muito grato. Claro, eu gostaria que fosse o nosso segredo.}
 
 #Sure. If I come across anything like that, I'll be sure to let you know.
{422}{}{Claro. Se eu encontrar algo assim, eu vou concerteza providenciar para que fique sabendo.}
#I don't think I want to contribute to your plant obsession. Sorry.
{4220}{}{Eu não acho que eu quero contribuir para essa sua obsessão sobre as plantas. Desculpe.}
#Oh, well then. Fine, forget I asked.
{4221}{}{Oh, bem, então. Tudo bem, esqueça o que eu disse.}
#Let me ask you something else.
{4222}{}{Deixe-me perguntar-lhe algo mais.}
#end
#Right...Well, I have some other questions.
{423}{}{Certo... Bem, eu tenho algumas outras perguntas.}
#Would you? I'd appreciate that.
{424}{}{Você faria isso? Eu aprecio isso.}
#No problem. I have some other questions.
{425}{}{Sem problemas. Eu tenho algumas outras perguntas.}
#Any time. Well, see you around.
{426}{}{A qualquer hora. Bem, te vejo por aí.}

#I found some information about Botany that might interest you.
{430}{}{Eu encontrei algumas informações sobre Botânica que lhe possam interessar.}
#Really?! That's great. Please, do tell immediately.
{431}{}{Realmente! Isso é ótimo. Por favor, diga imediatamente.}
#Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you
 taking the time to find this for me. Thank you for collecting this for me.
{432}{}{Fascinante! Vou levar o holodisk e adicioná-lo ao banco de dados no computador imediatamente. Eu aprecio
 você tomar o seu tempo para encontrar ele para mim. Obrigado pela coleta.}
 #Well you see...Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...
{433}{}{Bem, você vê ... a destruição do habitat Compreensão e extinção de espécies é dependente de um catálogo preciso e completo da sistemática e taxonomia. E então, isso significa que ...}
#Any time. I have some other questions though.
{434}{}{A qualquer hora. Eu tenho algumas outras perguntas.}
#No problem. See you around.
{435}{}{Sem problemas. Vejo você por aí.}
#Fascinating! I appreciate you taking the time to find this for me. Please go and upload this information to our computers.
{436}{}{Fascinante! Eu aprecio você dedicar o seu tempo para encontrar ele para mim. Por favor, vá e faça o upload dessas informações para os nossos computadores.}
#No problem, I'll do that now. See you around.
{437}{}{Não tem problema, eu vou fazer isso agora. Vejo você por aí.}

#Stop that, moron!
{500}{}{Pare com isso, idiota!}

#That computer near me should have some information about it. You now have access, so take a look for yourself.
{550}{}{Esse computador próximo a mim deve ter algumas informações. Agora você tem acesso, então dê uma olhada por si mesmo.}

#The Abbot gave me permission to access the computers here.
{600}{}{O Abbot me deu permissão para acessar os computadores aqui.}
#Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. (He hands you the key.) Enjoy!
{601}{}{Ah sim, eu ouvi sobre o que você fez. Obrigado por cuidar dessa situação. Aqui está a chave de acesso. (Ele te entrega a chave.) Divirta-se!}
#Thanks. See you around.
{602}{}{Obrigado. Vejo você por aí.}

#Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?
{650}{}{Saudações viajante! Eu sou o irmão Paul e eu sou encarregado da recolha de informações para o Abbey. O que posso fazer por você?}
#Nice to meet you, Paul. I have some questions.
{651}{}{Prazer em conhecê-lo, Paul. Eu tenho algumas perguntas.}
#Nothing. See you around.
{652}{}{Que nada. Vejo você por aí.}
