
# Traduzido por Noob-Saibot
{100}{}{Você vê um monge.} # You see a monk.
{101}{}{Você vê uma freira.} # You see a nun.
{102}{}{Esse monge parece saber uma coisa ou outra sobre computadores.} # This monk looks like he knows a thing or two about computers.
{103}{}{Essa freira parece saber uma coisa ou outra sobre computadores.} # This nun looks like she knows a thing or two about computers.

{200}{}{Não quebre nada.} # Don't break anything.
{201}{}{Desculpe, estou trabalhando agora.} # Sorry, I'm rather busy at the moment.
{202}{}{Saudações.} # Greetings.
{203}{}{Sinta-se livre para olhar ao redor..} # Feel free to look around.
{204}{}{Nós copiamos o conhecimento para as gerações futuras.} # We copy the knowledge for the future generations.
{205}{}{Esse livos antigos são muito frágeis.} # These old books are very fragile.
{206}{}{Copiar livros é um trabalho bem difícil.} # Copying books is pretty hard work.
{207}{}{Olá.} # Hello.
{208}{}{Tem muita coisa pra copiar destes livros.} # There's much to copy down from these books.

{500}{}{Pare com isso!} # Stop that!
