# Traduzido por Noob-Saibot
{100}{}{Você vê um monge.} # You see a monk.
{101}{}{Você vê uma religiosa.} # You see a holy woman.
{102}{}{Você vê um monge comum de Abbey.} # You see a regular Abbey monk.
{103}{}{Você vê uma freira comum de Abbey.} # You see a regular Abbey nun.

{200}{}{Saudações.} # Greetings.
{201}{}{Bem-vindo a Abbey.} # Welcome to the Abbey.
{202}{}{Você deve falar com nosso líder se quiser alguma informação.} # You should talk to our leader if you wish to gain any information.
{203}{}{Bom dia... ou já é boa noite?} # Good day...or is it night already?
{204}{}{Tem tanto trabalho pra fazer...} # There's so much work that must be done.
{205}{}{A vida aqui em Abbey é bem tranquila. Algo raro nessas terras devastadas.} # Life here at the Abbey is a peaceful one. Something rare in these wretched wastes.

{500}{}{Pare com isso!} # Stop that!

