{100}{}{Você vê um posseiro.}
# You see a squatter.
{101}{}{Você vê Bill, o posseiro.}
# You see Bill, the squatter.
{102}{}{Um homem de meia-idade com roupas esfarrapadas.}
# You see a middle aged man wearing worn clothing.
{103}{}{Me desculpe, forasteiro. Mas não tenho tempo pra falar com você.}
# Sorry, stranger. I don't have time to chat with you.
{104}{}{Ei, já disse que não tenho tempo pra conversas. Vá embora, por favor.}
# Hey, I said I don't have time to chat. Please go away.
{105}{}{Obrigado por ajudar Rebecca. Foi lindo o que fez.}
# Thanks for helping Rebecca. That was a fine thing you did.
{106}{}{Me deixe em paz. Não ofereço nenhuma ameaça a você.}
# Leave me alone. I'm no threat to you.
#push messages
{107}{}{Tá bom, tá bom. Já tô saindo.}
# All right, all right. I'm moving.