{100}{}{Você vê uma mulher jovem.}
# You see a young woman.
{101}{}{Você vê Chrissy, a filha de Rebecca.}
# You see Chrissy, Rebecca's daughter.
{102}{}{Você vê uma jovem atraente. Ela parece confiante e capaz de se virar numa luta.}
# You see a pretty young woman. She looks confident and able to handle herself in a fight.
{103}{}{Se veio aqui tentar me estuprar, vai acabar usando suas bolas como gravata borboleta. Sacou?}
# If you're here to try and rape me, you're going to be wearing your balls as a bow tie. Get it?
{104}{}{Deixe-me advinhar. Os caras estão cansados de mim dando chutes onde dói neles, então te enviaram aqui para fazer alguma coisa obscena. Bom, posso te machucar do mesmo jeito. Só preciso chutar mais pra cima. Sacou? }
# Let me guess. The guys are tired of me kicking them where it hurts, so they sent you in here to
 do something obscene. Well, I can hurt you just as bad; I just need to kick higher. Get it?
{105}{}{Gravata borboleta?}
# Bow tie?
{106}{}{}
{107}{}{O qui que tá acontecenu aqui? Quem é cê?}
# What go on here? Who you?
{108}{}{}
{109}{}{Estou afim de saber quem é você e o que está acontecendo aqui.}
# I'd like to know who you are and what is going on here.
{110}{}{Isso! Um pomposo pedaço de pano enrolado ao redor do pescoço usado para enfeite. É como um cachecol, só que para homens. Agora me imagine te dando um chute TÂO forte que você vai terminar usando seu saco ao redor do pescoço. Entendeu?}
# Yeah. A fancy piece of cloth worn around the neck for decoration. It's like a scarf, but for
 men. Now, just imagine me kicking you SO hard that you end up wearing your dangly about your neck. Get
 it?
{111}{}{Eu tendi. Não machuca eu.}
# Me understand. You no hurt me.
{112}{}{Entendi tudinho. Não me machuque, por favor.}
# I got the picture; please don't hurt me.
{113}{}{Tá bom. E então, o que faz aqui?}
# Okay, so why are you here?
{114}{}{}
{115}{}{Tô querenu sabê o que contece? Quem tu é?}
# Me want know what go on here? Who you?
{116}{}{}
{117}{}{Estou afim de saber quem é você e o que está acontecendo aqui.}
# I'd like to know who you are and what is going on here.
{118}{}{Sério? Que bom! Vamos!}
# Really? Awesome! Let's go.
{119}{}{Okay.}
{120}{}{Resumindo, meu nome é Chrissy e sou das posses. Semana passada estava dando uma olhada por aqui quando encontrei aquela entrada estranha. Pensei que poderia ser uma mina abandonada ou alguma outra coisa, então decidi verificar. Bom, não é uma mina. É uma passagem secreta para o Vault 15, que está sendo usado como base por um bando de raiders chamado Khans. Eles me pegaram bisbilhotanto e o seu líder, Darion, mandou me prender aqui.}
# In a nutshell, my name is Chrissy and I'm from the Squat. I was out exploring last week when I
 found that entrance out there. I thought it might be an abandoned mine or something, so I decided to
 check it out. Well, it's not a mine; it's a secret entrance into Vault 15. The vault is being
 used as a base for a band of raiders called the Khans. They caught me snooping around and their leader, Darion, had me locked up in here.
{121}{}{Ta bão. Vô ti levá pra casa.}
# Okay. Me take you home.
{122}{}{Tá bom. Vou te levar pra casa.}
# All right, I'll take you home.
{123}{}{Por deus! Hoje deve ser meu dia de sorte. A que devo o prazer de te ver de novo?}
# Well, I'll be damned. Today must be my lucky day. To what do I owe the pleasure of seeing you
 again?

{124}{}{}
{125}{}{O qui tá contecenu? Cê é quem?}
# What go on here? Who you?
{126}{}{}
{127}{}{Quero saber quem é você e o que tá fazendo aqui.}
{128}{}{Me leve para minha mãe Rebecca, por favor.}
# Please take me to my mother, Rebecca.
{129}{}{Meu príncipe com armadura brilhante voltou. Bem, brilharia se você limpasse de vez em quando. Ah, e você poderia pensar em tomar um banho também. Então, como posso te ajudar?}
# My knight in shining armor returns. Well, it would shine if you'd clean it every once in a
 while. Oh, and you might want to consider bathing yourself as well. So, what can I do for you?
{130}{}{Mim dizer oi. Mim ir agora.}
# Me just say hi. Me go now.
{131}{}{Só passei pra dizer oi. Agora tenho que ir.}
# Just thought I'd say hello. I'll be going now.
{132}{}{Ei, eu sei que tenho a boca grande, mas quero que saiba que sou muito grata por me salvar. Muito obrigada!}
# Hey, I know I have a smart mouth, but I want you to know that I'm very grateful for you saving
 my butt. Thanks very much!
{133}{}{Di nada.}
# You welcome.
{134}{}{De nada!}
# You're welcome.

{135}{}{As pessoas daqui estão protegendo esses caras ajudando a manter o Vault em segredo, mas eles não sabem o que está acontecedo de verdade. Darion nos disse que o vault estava sendo consertado para que pudéssemos ter um lugar seguro para viver, com muita comida e água, mas é tudo mentira. Eu estive lá e vi tudo. O vault está morto, as máquinas de alimento e água não funcionam. Nossa água e comida são das caravanas roubadas por eles.}
# The people of the Squat are protecting these guys by helping them keep the vault a secret, but they
 don't know what's really going on here. Darion told us that the vault was being repaired so we could have
 a safe place to live with lots of food and water, but it's all a lie. I've been in there and looked
 around. The vault is dead, and the food and water machines don't work. Our food and water's been coming
 from the spoils
 of raids against caravans.
{136}{}{Olha só, tenho que ir pra casa e avisar a todos sobre o que está acontecendo aqui de verdade. Não podemos ajudar esses monstros. Vai me levar pra casa?}
# Look, I've got to go home and warn everyone about what's really going on here. We can't help these
 monsters. Will you take me home?