{100}{}{Você vê uma jovem com roupas esfarrapadas.}
# You see a young woman in tattered clothing.
{101}{}{Você vê Dalia.}
# You see Dalia.
{102}{}{Você vê uma jovem com roupas esfarrapadas. Ela parece estar bem alerta e vigia cuidadosamente tudo à sua volta.}
# You see a young woman in tattered clothing. She seems very alert, and watches her surroundings
 carefully
{103}{}{Sou Dalia. Pois não?}
# Hi. I'm Dalia. What can I help you with?
{104}{}{Nada, só passanu pra dá um 'oi'.}
# Nothing, just say hi.
{105}{}{Uh, você sêr a?}
# Uh, who you?
{106}{}{O qui fagi aqui?}
# What you do here?
{107}{}{Cê é ingual a um vigia.}
# You look like guard
{108}{}{Mim ir jájá}
# Me go now.
{109}{}{Só passando pra cumprimentar.}
# Just saying hello.
{110}{}{Quem é você?}
# Who are you?
{111}{}{O que está fazendo?}
# What are you doing?
{112}{}{Parece que você tá vigiando esse caminho.}
# You look like you're guarding that trail.
{113}{}{Tenho que ir.}
# I'll be going now.
{114}{}{Bom, olá. Me desculpe, mas você tem que ir embora.}
# Well, hello to you. Now, I'm sorry, but you should go.
{115}{}{Má eu tá querenu faláá.}
# Me want talk.
{116}{}{Tá bão. Tô inu.}
# Ok, me go.
{117}{}{Quero conversar contigo.}
# I want to talk to you.
{118}{}{Tchau.}
{119}{}{Disse que me chamo Dalia. Olha só, sem querer ser rude, mas não tô afim de conversar com ninguém agora, tá bom?}
# I said I'm Dalia. Look, I don't mean to be rude, but I don't want to talk to anyone right now. Okay?
{120}{}{Tá bão. Tixau.}
# Okay, bye.
{121}{}{Só um porquinho mais, vai!}
# Just little more.
{122}{}{Já que é assim, tô partindo.}
# Then I'll leave.
{123}{}{Só quero te fazer uma pergunta.}
# I just want to ask you a question.
{124}{}{Adoro ar fresco, árvores, e por isso estou aqui de pé. Algum problema?}
# I like the fresh air, I like the trees, so I'm standing here. Do you have a problem with that?
{125}{}{Descupa. Tô inu.}
# Sorry, me go.
{126}{}{Tem pobrema não. Só tô querenu te perguntá umas coisa.}
# No, not problem. Me ask you something.
{127}{}{Problema nenhum, mas estou curioso sobre umas coisas.}
# I don't have a problem, but I am curious about something.
{128}{}{Desculpe, tenho que ir.}
# Sorry, I'll be going then.
{129}{}{Não, não estou vigiando o caminho. Não tem nada aqui neste buraco que valha a pena ser vigiado. Já te disse que adoro ar fresco. Agora vá embora.}
# No, I'm not guarding the trail. There's nothing in this hole worth guarding. I told you, I'm
 enjoying the fresh air. Now go away.
{130}{}{Cê falá bonitu. Eu queru conversá mais.}
# You nice talk to. Me talk more.
{131}{}{Disculpa te aporrinhá. Tô inu.}
# Sorry me bother. Me go.
{132}{}{Mas nosso papo tá ótimo! Por que parar?}
# But we're having such a nice conversation, why stop?
{133}{}{Acho que tá na hora de partir.}
# I guess it's time to leave.
{134}{}{Ah não, esta peste de novo! Não tenho nada pra falar com você. Vá embora!}
# Oh no, it's the pest again. Look, I have nothing to say to you. Go away!
{135}{}{}
{136}{}{}
{137}{}{Não tenho nada contra você. Esquece que eu existo!}
# I have no quarrel with you. Leave me be.
{138}{}{}
{139}{}{}
{140}{}{Oi! Sou Dalia. Pois não?}
# Hi. I'm Dalia. What can I help you with?
{141}{}{Viu uma pessoa passá comu uma frecha porraqui?}
# Person go by here? In hurry?
{142}{}{Nada.}
# Nothing.
{143}{}{Nada.}
# Nothing.
{144}{}{Viu alguém passar correndo por aqui?}
# Did you see someone go by here in a hurry?
{145}{}{Vejo pessoas passando aqui todos os dias. Mas não presto muita atenção nelas.}
# I see people go by here every day. I really don't pay much attention to them.
{146}{}{Eu não ter tempu pra suas merdas.}
# Me not have time for you crap.
{147}{}{Ah, tá bom.}
# Oh, okay.
{148}{}{Vida de garota em pirigo. Menina jovi. Filhota de alguém. Vai ajudar eu?}
# Girl life at stake. Young girl. Someone daughter. You please help?
{149}{}{Não tenho tempo pras suas besteiras.}
# I don't have time for your crap.
{150}{}{Ótimo. Tchau.}
# Fine, bye.
{151}{}{Olha só, a vida de uma jovem está em risco. A filha de uma mãe preocupada. Não tem como você me ajudar? Por favor.}
# Look, a young girl's life is at stake here. The daughter of a worried mother. Can you please
 help me out?
{152}{}{Não dou a mínima... Sinto muito. Sou só uma vigia que foi contratada para ficar aqui guardando o caminho. Fora isso, não sei o que está acontecendo. Eu já tive uma filha, mas, e... é, alguém passou aqui. Deixei que passasse porque ele fez o sinal correto, igual ao que você me fez agora. Pode ir. Vou sair fora daqui.}
# I don't give a radrat's ass... I'm sorry. I'm just a gun who was hired to stand here and guard
 this trail. Other than that, I don't know what's going on around here. I had a daughter once, though,
 and...yeah, some guy went by here. I let him through because he knew the proper sign...just like the
 sign you gave me. Go on. I'm outta here.
{153}{}{Brigadu. Não vô esquecê isso, Dalilia.}
# Thanks. Me no forget this, Dalia.
{154}{}{Valeu. Não vou esquecer essa, Dalia.}
# Thanks. I won't forget this, Dalia.
{155}{}{Então vá pro inferno e me deixe em paz!}
# Then go the hell away and leave me be!
{156}{}{Pronto.}
# Done.
{157}{}{Então vá pro inferno e me deixe em paz!}
# Then go the hell away and leave me be!
{158}{}{Pronto.}