#bcdardog.msg
#You see a dog.
{100}{}{Você vê um cachorro.}
#You see Darion's dog.
{101}{}{Você vê o cachorro de Darion.}
#You see an animal with a lot of fur and four legs. If a dog could grin evilly, you would swear this one is doing it.
{102}{}{Você vê um animal com uma grande quantidade de pêlo e quatro pernas. Se um cachorro pudesse sorrir maldosamente, você juraria que este aqui está fazendo isso.}
