{100}{}{Você vê um velho.}
{101}{}{Você vê Darion, líder dos New Khans.}
{102}{}{Você vê um velho de barba rala e grisalha. Pra sua idade ele até que está em forma.}
{103}{}{Aí está você finalmente. O salvador dos oprimidos, a vara dos injustos, o ícone de esperança para a humanidade. 
 Que coisa idiota! Bom, antes de começar com discursos chatos, gostaria de dizer que não estou interessado em porra nenhuma. 
 Vamos direto pra caça e acabar logo com isso. Baddgog, mata!}
{104}{}{Pronto.}
