{100}{}{Você vê um velho.}
# You see an older man.
{101}{}{Você vê Darion, líder dos New Khans.}
# You see Darion, leader of the New Khans.
{102}{}{Você vê um velho de barba rala e grisalha. Pra sua idade ele até que está em forma.}
# You see an older man with thin, gray hair. He seems to be in good shape for his age.
{103}{}{Aí está você finalmente. O salvador dos oprimidos, a vara dos injustos, o ícone de esperança para a humanidade. Que coisa idiota! Bom, antes de começar com discuros chatos, gostaria de dizer que não estou interessado em porra nenhuma. Vamos direto pra caça e acabar logo com isso. Baddgog, mata! }
# So, here you are at last. The savior of the downtrodden, the righter of wrongs, the icon of
 hope for humanity. What a dumb-ass! Well, before you start any boring speeches, I'd just like to say
 that I'm not fucking interested. Let's just cut to the chase and get this over with.  Baddog, kill!
{104}{}{Pronto.}