#You see a Khan raider.
{100}{}{Você vê um Khan raider.}
{101}{}{Você vê um Khan raider.}
#You see a tough looking person with armor, weapons, and a bad attitude. It must be a Khan.
{102}{}{Você vê uma pessoa resistente de armaduras, armas e uma atitude ruim. Deve ser um Khan.}

#node1
#What the... I don't think I know you. Who the hell are you? 
{103}{}{Mas que ... eu não acho que te conheço. Quem diabos é você?}

#responses 1
#I got my ID right here! Let me show ya.
{104}{}{Eu tenho o meu ID aqui! Deixa eu te mostrar.}
#The name's... umm... Pat, and I'm new here.
{105}{}{O nome é ... umm ... Pat, e eu sou novo por aqui.}
#edit below by killap - was 110
#Die!
{145}{}{Morra!}

#node 2
#All right, wise-ass. Take your best shot.
{106}{}{Tudo bem, espertinho. Dê o seu melhor tiro}

#node 3
#made skill check
#Oh yeah. Sorry. Didn't recognize you at first. Go on about your business.
{107}{}{Ah sim. Desculpe. Não reconhecê-lo à primeira vista. Vá em frente com o seu negócio.}
#Hey, I'm not as stupid as you look.
{108}{}{Hey, eu não sou tão estúpido como você pensa.}

#node 4
#You're not dead yet? Shit.
{109}{}{Você ainda não tá morto? Merda.}

#idle talking messages
#BLOCK 1
#Man, Darion doesn't pay me enough to stand around here and do nothing.
{110}{}{Cara, O Darion não me paga o suficiente para ficar por aqui e não fazer nada.}
#Sometimes I sit and think about absolutely nothing.
{111}{}{Às vezes eu sento e penso sobre absolutamente nada.}
#I generally don't care what anyone else thinks.
{112}{}{Eu geralmente não me importo com o que ninguém pensa.}
#Ignorance is bliss... I think.
{113}{}{A ignorância é a felicidade ... eu acho.}
#When's the next caravan passing through? I could use some action.
{114}{}{Quando é a próxima passagem da caravana? Eu poderia usar um pouco de ação.}
#I could use a break.(Atenção revisor não enendi muito bem o comando da frase)
{115}{}{Eu poderia usar uma pausa.}

#BLOCK 2
#Damn, I still hurt from that bitch Chrissy kicking me.
{116}{}{Porra, ainda sinto a dor daquela puta Chrissy me chutando.}
#Hey, we never get any new blood around here.
{117}{}{Hey, nós nunca vamos obter qualquer sangue novo por aqui.}
#So when are we going to get out of this stupid place?
{118}{}{Então, quando é que a gente vai sair desse lugar estúpido?}
#I don't know about you, but I think this sucks
{119}{}{Eu não sei quanto a você, mas eu acho que isso aqui é uma merda.}
#There ain't nothin' to kill around here.
{120}{}{Não tem nada pra matar por aqui.}
#Where's the damn bathroom?
{121}{}{Cadê a porra do banheiro?}

#BLOCK 3
#Hey, we never get a break around here. Isn't there some law or something?
{122}{}{Hey, nós nunca vamos ter uma pausa por aqui. Não existe nenhuma lei ou algo assim?}
#We should start up a government like in the old days.
{123}{}{Nós devemos começar um governo como nos velhos tempos.}
#Man, I wonder what it was like to be President back then?
{124}{}{Cara, eu me pergunto o que era parecido com o que ser presidente na época?}
#I bet you could do anything you wanted if you were President.
{125}{}{Eu aposto que você poderia fazer o que quisesse, se você fosse o presidente.}
#I think my father would be proud of me today. Too bad I killed him.
{126}{}{Acho que meu pai estaria orgulhoso de mim hoje. Pena que eu o matei.}
#I HATE RATS! HATE HATE HATE!
{127}{}{EU ODEIO RATS! ODEIO ODEIO ODEIO!}

#BLOCK 4
#Hey, is that new armor you have on? How do you rate getting new armor?
{128}{}{Ei, é a nova armadura que você pegou? Como você se classifica recebendo a nova armadura?}
#This damn vault smells. Don't you hate it?
{129}{}{Esse refúgio maldito tem um cheiro ruim. Você não odeia isso?}
#Hey, who is it we're supposed to be keeping an eye open for?
{130}{}{Ei, quem é que esta mantendo um olho aberto?}
#All I do is stand, stand, stand.
{131}{}{Tudo o que eu faço é ficar, ficar, ficar.}
#I think we should just waste everyone upstairs and say to hell with this place.
{132}{}{Eu acho que devemos apenas dizer a todo mundo lá em cima o quanto esse lugar é um inferno.}
#What the hell is your problem with rats?
{133}{}{Que diabos é o seu problema com os rats?}

#BLOCK 5
#Have you ever pulled one of the legs off of a rat?
{134}{}{Você já tirou uma das pernas de um rat?}
#I like guns, yeah! GUNS I LIKE! GUNS: I REALLY, REALLY LIKE THEM!
{135}{}{Eu gosto de armas, yeah! EU GOSTO DE ARMAS! ARMAS: EU REALMENTE, REALMENTE GOSTO DELAS!}
#Hey, is anyone listening to me?
{136}{}{Ei, tem alguém me ouvindo?}
#Oh well, I just talk to keep myself sane anyway.
{137}{}{Oh bem, eu apenas disse para me manter são qualquer maneira.}
#Hey, anyone remember what was in a Long Island Ice Tea?
{138}{}{Ei, alguém se lembra o que estava no Chá Gelado de Long Island?}
#Yeah, vodka, rum, tequila, triple sec, lime, and Nuka.
{139}{}{Sim, vodka, rum, tequila, triple sec, limão, e Nuka.}

#Lights on
#Hey, look -- the lights came on. What the...
{140}{}{Ei, olhe -- as luzes se acenderam. Mas o que ...}
#Darion said he'd get the damn lights fixed. I guess he came through.
{141}{}{Darion disse que ia concertar as malditas luzes.Eu acho que ele veio.}
#I don't think the generator just fixes itself, does it?
{142}{}{Eu não acho que o gerador apenas se concerta, não é?}
#That was kind of weird; now I can see. Jesus, this place looks like shit!
{143}{}{Isso foi um pouco estranho; agora eu posso ver. Jesus, este lugar se parece com nada!}
#Wow, it's bright in here. Where's the dimmer control?
{144}{}{Uau, é claro aqui. Onde está o controlador de luz?}