{100}{}{Você vê um posseiro.}
# You see a squatter.
{101}{}{Você vê John, um posseiro.}
# You see John, the squatter.
{102}{}{Você vê um homem de meia-idade com roupas esfarrapadas.}
# You see a middle-aged man wearing worn clothing.
{103}{}{Me desculpe, forasteiro, mas não tenho tempo pra bater papo com você.}
# Sorry, stranger, I don't have time to chat with you.
{104}{}{Porcauso di que não falar?}
# Why no talk?
{105}{}{Tá bão.}
# Okay, wavy.
{106}{}{Tá bom. Até mais.}
# All right, see ya.
{107}{}{Calma aí. Por que não fala comigo?}
# Wait a minute. Why won't you talk to me?
{108}{}{Nós somos uma comunidade selosa de privacidade e não queremos problemas ou interferência de fontes externas. Nos deixe em paz, por favor.}
# We're a very private community here, and we don't want any trouble or interference from outside
 sources. Please just leave us be.
{109}{}{Tá bom.}
# Okay
{110}{}{Olá... e tchau!}
# Hello... and good bye.
{111}{}{Muito obrigado por tudo o que fez. Peço desculpas por ter sido frio com você antes.}
# Thank you for all that you've done. I apologize for the cold shoulder earlier.
{112}{}{Vá se foder, imbecil!}
# Screw you, asshole!

{113}{}{Maldição! Odeio quando acontece isso.}
# Damn, I hate it when that happens.
{114}{}{Segura essa! Você vai ver!}
# Take that! Yeah, that'll show ya.