{100}{}{Você vê um posseiro.}
{101}{}{Você vê John, um posseiro.}
{102}{}{Você vê um homem de meia-idade com roupas esfarrapadas.}
{103}{}{Me desculpe, forasteiro, mas não tenho tempo pra bater papo com você.}
{104}{}{Porque você não fala?}
{105}{}{Está bem.}
{106}{}{Ta bom. Até mais.}
{107}{}{Calma aí. Por que não fala comigo?}
{108}{}{Nós somos uma comunidade secreta e não queremos problemas ou interferência de fontes externas. 
 Deixe-nos em paz, por favor.}
{109}{}{Ta bom.}
{110}{}{Olá... e tchau!}
{111}{}{Muito obrigado por tudo o que fez. Peço desculpas por ter sido frio com você antes.}
{112}{}{Vá se fuder, imbecil!}
{113}{}{Maldição! Odeio quando acontece isso.}
{114}{}{Tome isso! você vai ver!}
