{100}{}{Você vê uma velha.}
# You see an older woman.
{101}{}{Você vê Rebecca.}
# You see Rebecca.
{102}{}{Uma velha. Embora pareça ter tido uma vida dura, ainda não perdeu nem um pouco da sua beleza natural.}
# You see an older woman. Although she appears to have lived a hard life, she has not lost any of
 her natural beauty.
{103}{}{Oi! Sou a Rebecca. Podemos conversar em particular?}
# Hi, I'm Rebecca. Can we talk privately, please?
{104}{}{Cunversá sob o quê?}
# What talk about?
{105}{}{Porcauso di que em parti cu lá?}
# Why need talk private?
{106}{}{Tá bão.}
# Okay.
{107}{}{Não. Deixa eu.}
# No. Me leave.
{108}{}{Desculpe, mas não me interessa.}
# Sorry, not interested.
{109}{}{Sobre o que quer falar comigo?}
# What do you want to talk to me about?
{110}{}{Tá bom, mas onde vamos conversar?}
# Sure, where can we go for privacy?
{111}{}{Por que a privacidade?}
# Why the need for privacy?
{112}{}{(murmurando) Minha filha desapareceu e preciso de ajuda pra encontrá-la. Mas não posso falar sobre isso aqui. Podemos ir pra um lugar mais particular?}
# (whispering) My daughter is missing and I need help finding her. I can't talk about it here,
 though. Can we go somewhere private?
{113}{}{Tá bão.}
# Okay.
{114}{}{Porcausa di que conversá im particulá?}
# Why need talk private?
{115}{}{Não. Eu ir.}
# No, me go.
{116}{}{Tá bom. Vamos.}
# All right, let's go.
{117}{}{Por que precisamos de privacidade?}
# Why the need for privacy?
{118}{}{Não, valeu. Não quero me involver nisso.}
# No thanks, I don't want to get involved.
{119}{}{(murmurando) Pode pensar que sou louca, mas estou com pressentimento de que estão me vigiando o tempo todo. E isso é perturbador. Estou um pouco nervosa por causa disso.}
# (whispering) You may think I'm crazy but I get the feeling I'm being watched all the time. It's
 rather disturbing, and I'm a bit on edge because of it.
{120}{}{Tá bão. Vamu privado.}
# Okay, we go private.
{121}{}{Não tenhu tempo pra dódói de cabeça.}
# No time for sicky in head.
{122}{}{Tá bom. Aonde vamos conversar?}
# All right; where can we go to talk?
{123}{}{Desculpe. Mas isso não tá me soando legal.}
# Sorry, I don't like the sound of this.
{124}{}{Obrigada. Vamos pra minha tenda.}
# Thanks; we can go to my tent.
{125}{}{Okay.}
{126}{}{Acho que aqui dá pra gente conversar.}
# We should be able to talk here.
{127}{}{Tá bão. Qual é o probrema?}
# Okay, what problem?
{128}{}{Tenhu umas pergunta.}
# Me got questions first.
{129}{}{Tá bom. O que é tão importante?}
# Okay, so what's so important?
{130}{}{Tenho algumas perguntas primeiro.}
# I have some questions for you, first.
{131}{}{Tenho uma filha chamada Chrissy que é um pouco levada. Ela adora rodar por aí, explorar e meter seu nariz nas coisas. Mas é uma ótima jovem. Nunca dá problema, chega sempre em casa na hora certa e se mostra uma dama muito responsável. Deixo sempre ela fazer o que gosta. Semana passada ela não voltou pra casa. Perguntei pelas redondezas, mas ninguém viu ou escutou sobre ela. Tentei encontrá-la eu mesma, mas Zeke, ele... é um tipo de prefeito aqui... disse pra eu não ir. Disse que não é seguro para mim sair por aí atrás dela. Ele mandaria alguns de seus homens fazerem isso. Mas eles não a encontraram e disseram que os traficantes de escravos podem ter pego minha filha. }
# I have a daughter named Chrissy who's a bit of a tomboy. She likes to run around, explore,
 and pretty much stick her nose into things. Chrissy's a good kid, though. She doesn't
 cause trouble, she's always home on time and she's shown herself to be a very responsible young lady.
 I let her do as she pleases most of the time. Last week Chrissy didn't come home. I've asked
 around, and nobody's seen or heard from her. I tried to find her myself, but Zeke, he's... sort of the
 mayor here... stopped me. He said it wasn't safe for me to go out looking on my own; he'd have some of
 his men do it. They couldn't find her, either, and said that maybe the slavers got her.
{132}{}{Não, não me envolver nisso.}
# No, not get involved.
{133}{}{Precisu matutá sobre isso.}
# Need think before decide.
{134}{}{Tá bão, tô tipo herói ultimamenti.}
# Ok, me seem be hero type lately.
{135}{}{Desculpe, mas não me interessa.}
# Sorry, not interested.
{136}{}{Preciso pensar nisso.}
# I need to think about this.
{137}{}{Tá bom, Rebecca. Vou tentar te ajudar.}
# All right, Rebecca. I'll try to help you.
{138}{}{O que ganho se te ajudar?}
# If I help you, what's in it for me?
{139}{}{Sobre o que quer saber?}
# What do you want to know?
{140}{}{O qui tá acontecenu porr aqui?}
# What go on here?
{141}{}{Quem é chefe?}
# Who boss?
{142}{}{Tô tentanu acha o vault 13. Sabe ondi fica?}
# Me try find Vault 13. You know where is?
{143}{}{Conta pra eu do vault.}
# Tell about vault.
{144}{}{Falar sobri Darion.}
# Tell about Darion.
{145}{}{Valeu. Agora pode falá do seu pobrema?}
# Thanks. We talk you problem?
{146}{}{O que está acontecendo por aqui?}
# What's going on around here?
{147}{}{Quem é a autoridade aqui?}
# Who's in charge around here?
{148}{}{Estou em busca do Vault 13. Sabe alguma coisa sobre?}
# I'm looking for Vault 13. Do you know anything about it?
{149}{}{Conte-me sobre o vault.}
# Tell me about the vault.
{150}{}{Então conte-me sobre Darion.}
# So tell me about Darion.
{151}{}{Valeu Rebecca. Agora vamos ao seu problema.}
# Thanks Rebecca. Let's talk about your problem now.
{152}{}{Este lugar pode ser chamado de 'Posse' porque foi invadido por muitos desabrigados de várias cidades. Não é muito, mas é tudo o que temos. A oeste daqui fica uma cidade chamada NRC. Eles sabem da nossa existência há muito tempo e nunca ofereceram nenhum tipo de ajuda ou obstáculo. Agora de repente resolveram reivindicar esta área como a casa dos seus ancestrais, e a querem de volta.}
# We call this place the 'Squat' because it was settled by the homeless of many cities. It's not
 much, but it's all we have. To the west is a city called the NCR. They've known about us for quite some
 time, and never offered us any kind of help or hindrance. Now, they are suddenly claiming this area as their
 ancestral home, and they want it back.
{153}{}{Tá bão.}
# Okay.
{154}{}{O que 'eis' quer?}
# What here they want?
{155}{}{Entendi.}
# I see.
{156}{}{Mas o que tem aqui para eles quererem tanto assim?}
# What is here that they want so badly?
{157}{}{Bem... existe um vault aqui; acho que é o número 15. Eles querem saquear o Vault em busca de alguma velha tecnologia que ainda pode estar lá.}
# Well... there is a vault here; I think it's number 15. They want to loot it for any of the old
 technology that may still be there.
{158}{}{Ah. Intindi.}
# Ah. Me understand.
{159}{}{Sabia que havia algo mais aqui além desses habitantes imprestáveis.}
# I knew there had to be something here other than the waste-of-flesh inhabitants.
{160}{}{Entendi.}
# Got it.
{161}{}{Isso já explica muita coisa. Você foi muito útil. Mas preciso te fazer mais algumas perguntas.}
# That explains a lot. You've been very helpful. I need to ask some more questions, though.
{162}{}{Seria o Zeke. Ele administra tudo aqui. Você pode encontrá-lo naquela construção ali. ::apontando para o nordeste::}
# That would be Zeke. He runs everything up here. You can find him in the building over there.
 ::points north-east::
{163}{}{Brigadu. Mais perguta.}
# Thanks. Ask more.
{164}{}{Valeu. Preciso te perguntar mais algumas coisas.}
# Thank you. I need to ask you some more questions.
{165}{}{Sinto muito, mas não faço idéia. Se eu fosse você, perguntaria lá na NRC. Ultimamente eles tem tido um interesse imenso em vaults.}
# I'm sorry, I have no idea. I would ask about it in NCR. They've taken a great interest in
 vaults lately.
{166}{}{Tá bão. Eu ir.}
# Okay, me do.
{167}{}{Tá bom. Eu irei.}
# All right, I will.
{168}{}{Bom... não podemos falar sobre isso, mas já que preciso de sua ajuda... Darion está consertando o vault. Ele é nosso benfeitor. Quanto o vault estiver com tudo funcional, todos nós nos mudaremos para lá, onde estaremos seguros dos raiders, traficantes de escravos e tudo mais. Assim que ele acabar de consertar o sistema de  alimentos e água.}
# Well... we're not supposed to talk about it, but since I need your help... The vault is being
 repaired by Darion. He's our benefactor. When it's fully functional, we're all supposed to move in
 where we'll be safe from raiders, slavers, and such. So far he has the food and water systems up, but
 that's about it.
{169}{}{Intindi. Preciso sabe um bocadinho mais.}
# Me see. Need know more.
{170}{}{Preciso saber mais coisas.}
# I need to know more.
{171}{}{Não há muito a dizer, na verdade. Darion não fala nada e nunca deixa o vault. Quando ele tem algo a dizer, diz através de Zeke. Só o vi uma única vez, e ele pareceu ser um cara legal.}
# There's not much to say, really. Darion keeps to himself and never leaves the vault. If he has
 anything to say, he says it through Zeke. I've only met him once, and he seemed like a nice guy.
{172}{}{Okay.}
{173}{}{Caras legais morrem virgens. Queria saber o que ele está planejando de verdade.}
# Nice guys finish last. I wonder what he's up to?
{174}{}{Entendo.}
# I see.
{175}{}{Tá bom. Você ajudou bastante.}
# That's okay. You are very helpful.
{176}{}{Não tenho nada pra te dar além da minha eterna gratidão.}
# I have nothing to give you other than my undying gratitude.
{177}{}{Já é o suficiente. Vou te ajudar.}
# That's more than enough. I'll help you.
{178}{}{Minha ajuda custa mais.}
# It'll take more than that to buy my help.
{179}{}{Mas por que não? É claro que vou te ajudar.}
# What the hell, I'll help you.
{180}{}{Muito obrigada. Nunca vou poder te retribuir isso. Vou esperar aqui até você trazer... Ei, tinha alguém ali fora nos escutando. Eu vi a sombra na tenda. Ele correu por ali! ::apontando para o nordeste:: Deve ter escutado tudo!}
# Thank you so much. I'll never be able to repay you for this. I'll wait here until you bring...
 Hey, there was someone outside listening to us! I saw their shadow on the tent wall. They just ran off
 that way! ::points north-east:: They must have heard everything!
{181}{}{Vô pará ele, ele não vai fugi.}
# Me stop, no get away!
{182}{}{Não se preocupá, eu vô achá a garota.}
# You no worry, me find girl.
{183}{}{Ooops.}
{184}{}{Vou tentar pegá-lo!}
# I'll try and stop them.
{185}{}{Eles não vão me impedir de encontrar sua filha.}
# They won't stop me from finding your daughter.
{186}{}{Ah... merdas acontecem.}
# Oh well. Shit happens.
{187}{}{Por favor, vá embora.}
# Please, just go away.
{188}{}{E aí, já pensou a respeito?}
# Have you thought things through?
{189}{}{Tô querenu fazê pergunta.}
# Me ask questions.
{190}{}{Não, ainda pensanu.}
# No, still think.
{191}{}{Não, mas ainda estou pensando no assunto.}
# No, I'm still considering everything.
{192}{}{Queria te fazer algumas perguntas.}
# I want to ask you some questions.
{193}{}{Mudou de idéia? Vai me ajudar?}
# Have you changed your mind? Will you help me?
{194}{}{Desculpe. Não.}
# Sorry, no.
{195}{}{Eu ajudá sim.}
# Me help.
{196}{}{Sim, vou te ajudar.}
# Yes, I'll help you.
{197}{}{Você deve ser a pessoa que salvou minha filha. Nunca vou poder retribuir a sua bondade. Obrigada. Espere aqui, por favor. Preciso conversar com a Chrissy e gostaria de falar com você.}
# You must be the person who saved my daughter. I can never repay you for your kindness.Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.
{198}{}{Você salvou minha filha. Nunca vou poder retribuir a sua bondade. Obrigada. Espere aqui, por favor. Preciso conversar com Chrissy e gostaria de conversar com você também.}
# You saved my daughter. I can never repay you for your kindness. Thank you.
 Please wait here, I need to talk to Chrissy and then I'd like to talk to you.
{199}{}{Tá ok.}
# Okay.
{200}{}{Minha filha me contou tudo. É dificil acreditar que Darion é esse monstro depois de tudo o que tem feito por nós. E pensando bem, estamos ajudando ele a esconder suas operações como raider. Posso te garantir que não vamos permitir isso nem mais um minuto. Já falei com Zeke e ele quer te ver. Acho melhor você ir falar com ele agora.}
# My daughter has told me everything. I find it hard to believe that Darion is such a monster
 after all he's been doing for us. And to think, we've been helping him hide his operations as a raider.
 I can guarantee you we won't stand for it any longer. I've already talked to Zeke, and he wants to see
 you. You should go see him now.
{201}{}{Minha filha me contou tudo. É dificil acreditar que Darion é esse monstro depois de tudo o que tem feito por nós. E pensando bem, estamos ajudando ele a esconder suas operações como raider. Posso te garantir que vamos permitir isso nem mais um minuto. Vou falar com Zeke e explicar tudo. Tenho certeza de que ele vai querer ver você. Você deveria falar com ele depois.}
# I find it hard to believe that Darion is such a monster after all he's been doing for us. And to
 think, we've been helping him hide his operations as a raider. I can guarantee you we won't stand for
 it any longer. I'll talk to Zeke and explain everything. I'm sure he'll want to see you. You should go
 talk to him later.
{202}{}{Valeu.}
# Thank you.
{203}{}{Tomara que encontre Chrissy logo.}
# I hope you find Chrissy soon.
{204}{}{Eu tô procuranu.}
# Me looking.
{205}{}{Vou continuar minha busca por ela.}
# I'll continue to search for her.
{206}{}{Obrigada por tudo que fez por mim.}
# Thanks for everything you've done for me.

{207}{}{Não sei explicar o porquê, mas não acredito que os traficantes de escravos a pegaram. Estou com um desagradável pressentimento de que algo mais está acontecendo. Além da sensação de estar sendo seguida. Comecei a ter isso depois que falei com Zeke sobre Chrissy. Preciso de ajuda para encontrar minha filha. Por favor, você vai me ajudar?}
# I can't explain why, but I don't believe the slavers took her. I've an uneasy feeling that
 something else is going on. And then there's this feeling that I'm being followed. I've had it ever
 since I talked to Zeke about Chrissy. I need someone to help me find my daughter. Will you help me,
 please?
{208}{}{Eles ficam mandando pessoas aqui pra tentar nos convencer a sair da nossa casa, mas eles não entendem que não temos lugar nenhum pra ir. Não temos as habilidades necessárias para sobreviver se sairmos daqui.}
# They keep sending people here to try and talk us out of our home, but they don't understand
 that we have nowhere else to go. We don't have the skills necessary to survive on our own if we leave
 here.
{209}{}{Sabe, é um pouco engraçado eles terem conseguido consertar alguma coisa tão complexa, exceto as luzes. O maldito lugar é iluminado por tochas. De qualquer maneira, Darion não quer que ninguém saiba o que está acontecendo no vault. Ele tem medo que alguém tome tudo da gente se descobrirem. Por isso, foi dito pra gente mandar embora todo mundo que aparecer aqui -- especialmente da NRC.}
# You know, it's kind of funny that they managed to get something that complex fixed, but not the
 lights. The damn place is lit by torches. Anyway, Darion doesn't want anyone to know what's going on
 with the vault. He's afraid that someone will take it all away from us if they find out. So, we're told
 to drive off anyone who shows up here -- especially the NCR.