{100}{}{Você vê uma posseira.}
# You see a squatter.
{101}{}{Você vê Roberta, uma posseira.}
# You see Roberta, a squatter.
{102}{}{Você vê uma mulher de meia-idade vestindo roupas esfarrapadas.}
# You see a middle aged woman wearing worn clothing.
{103}{}{Ah, meu Deus. Peço desculpas, mas não tenho nada pra te falar. Vá embora, por favor.}
# Oh, my. I'm sorry, but I have nothing to say to you. Please go away.
{104}{}{Vá embora, por favor. Não quero ser incomodada.}
# Please go away. I don't want to be bothered.
{105}{}{Obrigada por ajudar a Rebecca. Eu estava errada sobre você.}
# Thanks for helping out Rebecca. I was wrong about you.
{106}{}{Não ofereço nenhuma ameaça a você. Não me mate!}
# I'm no threat to you. Please don't kill me.