{100}{}{Você vê uma posseira.}
# You see a squatter.
{101}{}{Você vê Sara, uma posseira.}
# You see Sara, a squatter.
{102}{}{Você vê uma mulher de meia-idade com vestidos esfarrapados.}
# You see a middle aged woman wearing worn clothing.
{103}{}{Por favor não me incomode. Estou muito ocupada no momento.}
# Please don't bother me; I'm really busy right now.
{104}{}{Vá embora, por favor. Não tem nada aqui pra você.}
# Please go away. There's nothing here for you.
{105}{}{Obrigada por ajudar a Rebecca. Vindo de um forasteiro é uma coisa maravilhosa.}
# Thanks for helping out Rebecca. It was a wonderful thing for you to do for a stranger.
{106}{}{Não sou ameaça a você. Não me mate.}
# I'm no threat to you. Please don't kill me.