{100}{}{Você vê um posseiro bem velho.}
# You see an older squatter.
{101}{}{Você vê, Zeke, um posseiro.}
# You see Zeke, a squatter.
{102}{}{Um velho com parcos cabelos brancos.}
# You see an older man with thinning, white hair.
{103}{}{Meu nome é Zeke, forasteiro. Sinto muito, mas não tenho tempo pra conversar contigo -- e creio que não tem nada aqui no povoado pra você. É melhor seguir seu rumo.}
# My name's Zeke, stranger. I'm sorry, but I don't have time to talk to you -- and I don't think
 there's anything in this town for you, anyway. You should move on.
{104}{}{Ah, tá bom.}
# Uh, okay.
{105}{}{Eu tenhu perguntas.}
# Me got questions.
{106}{}{Tá bom. Tô indo.}
# All right, I'll leave.
{107}{}{Só queria te fazer algumas perguntas.}
# I just wanted to ask a couple of questions.
{108}{}{Acho que vai descobrir que nenhum de nós tem respostas aqui. Por que não volta quando o carregamento chegar?}
# Well, I think you'll find that we're all out of answers here. Why don't you come back when we
 get a shipment in?
{109}{}{Pronto.}
# Done.
{110}{}{Olá novamente. Eu ainda não tenho respostas pra você, estranho. Será que você não se toca e cai fora daqui?}
# Hello, again. I still don't have any answers for you, stranger. Why don't you take a hint and
 get the duck out of fodge?
{111}{}{Pronto!}
{112}{}{Rebecca me contou o que fez por ela. Quero pedir desculpas pelo tratamento que recebeu aqui. Com certeza você não merecia isso. Como posso te ajudar?}
# Rebecca has told me what you did for her. I want to apologize for the treatment you received
 here. You certainly didn't deserve it. What can I help you with?
{113}{}{Eu ter umas pergunta.}
# Me got questions.
{114}{}{Nada. Inté.}
# Nothing. Wavy.
{115}{}{Queria te fazer algumas perguntas.}
# I've got some questions for you.
{116}{}{Por enquanto nada. Valeu.}
# Nothing for now, thanks.
{117}{}{O que quer saber?}
# What do you want to know?
{118}{}{Cê trabalha pro Dario?}
# You work for Darion?
{119}{}{Ô que cê faz com os raiders?}
# What you do about raiders?
{120}{}{Cadê a porca...por... porta do vault.}
# Where vault door?
{121}{}{Alguma coisa magi contecendo aqui?}
# Anything else go on here?
{122}{}{Mim partir.}
# Me leave now.
{123}{}{Você trabalha pro Darion?}
# Do you work for Darion?
{124}{}{E sobre os raiders? O que pretende fazer?}
# What do you intend to do about the raiders?
{125}{}{Onde fica a entrada do vault?}
# Where is the vault entrance?
{126}{}{Tem mais alguma coisa acontencendo por aqui?}
# Is there anything else going on around here?
{127}{}{Acho que isso é tudo. Tenho que ir agora.}
# I guess that's it. I'll be going now.
{128}{}{Sim, trabalho. Sou o intermediário entre ele e as pessoas aqui. Não estou muito feliz com o fato, agora que sei o que ele planeja.}
# Yes, I do. I act as the middle man between him and the people up here. I'm not very happy about
 the fact, now that I know what he's up to.
{129}{}{Okay.}
{130}{}{Saquei.}
# I see.
{131}{}{Nada. Eles têm armas, controlam a água e a comida. Quer dizer, quem manda são eles. Ponto. Não temos conhecimentos nem meio de vida sem o apoio de Darion. Como podemos nos virar contra ele? Estamos nas suas mãos.}
# Nothing. They have the guns, they control the water, and they control the food. That means
 they are in charge. Period. We have no skills and no means of support without the backing of Darion.
 How can we turn against him? We're at his mercy.
{132}{}{Hmm. Acho que intindi.}
# Hmm. Me think me understand.
{133}{}{Hmm. Entendi.}
# I see.
{134}{}{Fica atrás daquela porta alí, mas está trancada pelo outro lado e tem uma armadilha também. Não tenho como abrí-la... Calma aí, encontrei esta chave cartão faz um tempo e não tenho idéia pra que serve isso. Rebecca disse que você descobriu uma porta onde eles mantinham a Chrissy presa. Vai ver este cartão consegue abri-la. Tome aqui.}
# It's behind that door over there, but it's locked from the other side and trapped, too. I don't have
 any means of opening it... Wait a minute. I found this key card some time ago, and I have no idea what
 it is for. Rebecca says that you found some sort of door where they were holding Chrissy. Maybe this
 card will open it. Here, take it.
{135}{}{Eu agradeçu.}
# Me thank you.
{136}{}{Valeu. Vou tentar.}
# Thanks. I'll give it a try.
{137}{}{Existe uma cidade a oeste daqui chamada Nova República da Califórnia. Eles dizem que o Vault 15 é a casa dos seus ancestrais e a querem de volta. Estão sempre enviando pessoas aqui pra tentar nos convencer a sair, mas não vamos sair. Isto aqui é a única casa que conhecemos.}
# There's a city west of here called NCR. They claim Vault 15 is their ancestral home and they want it
 back. They've been sending people here trying to talk us into leaving but we aren't going for it. This is the only home we know.
{138}{}{E porcausa di que não faz a cordo com 'eis'?}
# You maybe make deal NCR?
{139}{}{Já considerou fazer um acordo com a NRC?}
# Would you consider making a deal with NCR?
{140}{}{Depende. O que tem em mente?}
# That all depends. What did you have in mind?
{141}{}{Se unir com a tribo da NRC. Aprender dos ancião. Dar a NRC permissão de entrá no vault. E os dois é feliz.}
# Join NCR tribe. Learn from elders. Give NCR you permission enter vault. Both happy.
{142}{}{Se junte a NRC, deixe que anexem seu território e dêem a eles acesso ao vault. Em troca, eles podem ensinar a vocês as tecnicas necessária para garantir a sobrevicência, além de oferecem proteção.}
# Join NCR, let them annex your territory, and give them access to the vault. In return, they can teach you all the skills you need to survive on your own and offer you their protection.
{143}{}{Nada mal... gostei. Você acaba de conseguir um acordo, desde que a NRC concorde. Mas... olha só, alguém tem que dar um jeito no Darion e seus amigos. Isso deve ser feito antes que ele perceba o que está acontecendo e tenha tempo de se preparar para um ataque. Por que não dá um jeito nisso e acaba com Darion? Você terá o elemento surpresa ao seu lado.}
# Not bad... I like it. You've got yourself a deal if you can get NCR to agree to it as well. But...
 Look, someone has to take care of Darion and his cronies. It should be done now before they realize what has happened
 and have time to prepare for an attack. Why not get this over with and take Darion out now?
 You'll have the element of surprise on your side.
{144}{}{Cê tem ração. Vou dá um jeito 'neis'.}
# You right, me take care of.
{145}{}{Sei não.}
# Me not sure.
{146}{}{É! Acho que isso tem que ser feito.}
# Yeah, I guess it has to be done.
{147}{}{Não sei.}
# I don't know.
{148}{}{Ótimo! Boa sorte e muito obrigado.}
# Excellent. Good luck to you, and thank you.
{149}{}{Pronto.}
{150}{}{Bem, pare pra pensar sobre isso. Mas saiba de uma coisa -- até Darion estar fora de jogada, não tenho outra escolha a não ser manter as coisas como estão. É pra segurança de todos os envolvidos. Isso quer dizer que não existe acordo e que você continua sendo uma persona non grata. Entendeu?}
# Well, take the time to think about it, but know this -- until Darion is out of the picture, I
 have no choice but to maintain things around here as they are. It's for the safety of everyone
 concerned. That means no deal and you are still persona non grata. Understand?
{151}{}{Okay.}
{152}{}{Oi! Ainda estou aguardando a solução final para os nossos problemas. Em outras palavras, mande Darion pro inferno.}
# Hi. I'm still waiting for a final resolution to our troubles. In other words, kick Darion's ass!
{153}{}{Pronto.}
{154}{}{Você conseguiu! Não estamos mais sobre o jugo da Darion. Obrigado! Estamos prontos para aceitar pacto com a NRC. Basta que eles enviem algum dos seus representantes que eu selo o acordo.}
# You've done it, friend! We're no longer under Darion's yoke. Thank you! I'm ready to accept your deal with NCR now.
 Just have them send one of their reps by and I'll seal the deal.
{155}{}{Pronto.}
{156}{}{Obrigado pela chance de ter uma nova vida. Devemos isso a você.}
# Thanks for the chance of a new life. We all owe you.
{157}{}{Vá embora. Não tenho nada pra conversar contigo.}
# Just go away. I have nothing to say to you.
{158}{}{Calma.. antes de ir.  encontrei esta chave cartão faz um tempo e não tenho idéia pra que serve isso. Rebecca disse que você descobriu uma porta onde eles mantinham a Chrissy presa. Vai ver este cartão consegue abrí-la. Tome aqui.}
# Wait, before you go... I found this key card some time ago, and I have no idea what it’s for.
 Rebecca says that you found some sort of entrance where they were holding Chrissy. Maybe this card will
 open it. Here, take it.
{159}{}{Valeu.}
# Thanks.
{160}{}{Como posso te ajudar?}
# What can I help you with?
{161}{}{Só os problemas com a NRC mesmo, mas acho que o acordo que ofereceu vai resolver isso.}
# Just the problems with the NCR, but I think the deal you offered will solve that.
{162}{}{Você conseguiu! Não estamos mais sob o jugo de Darion. Obrigado!}
# You've done it, friend! We're no longer under Darion's yoke. Thank you!
{163}{}{Agora que Darion se foi, não temos mais como conseguir alimento. Com certeza vamos morrer. Muito obrigado, viu.}
# Now that Darion's gone we don't have any way to get food. We will surely perish! Thanks a lot.