{100}{}{Você vê um posseiro bem velho.}
{101}{}{Você vê, Zeke, um posseiro.}
{102}{}{Um velho com parcos cabelos brancos.}
{103}{}{Meu nome é Zeke, forasteiro. Sinto muito, mas não tenho tempo pra conversar contigo --  e creio que não tem nada aqui no povoado pra você. É melhor seguir seu rumo.}
{104}{}{Ah, ta bom.}
{105}{}{Eu tenho perguntas.}

{106}{}{Ta bom. To indo.}
{107}{}{Só queria te fazer algumas perguntas.}
{108}{}{Acho que vai descobrir que nenhum de nós tem respostas aqui. Por que não volta quando o carregamento chegar?}
{109}{}{Pronto.}
{110}{}{Olá novamente. Eu ainda não tenho respostas pra você, estranho. Será que você não se toca e cai fora daqui?}
{111}{}{Pronto!}
{112}{}{Rebecca me contou o que fez por ela. Quero pedir desculpas pelo tratamento que recebeu aqui. Com certeza você não merecia isso. Como posso te ajudar?}
{113}{}{Eu ter umas pergunta.}
{114}{}{Nada. Inté.}
{115}{}{Queria te fazer algumas perguntas.}
{116}{}{Por enquanto nada. Valeu.}
{117}{}{O que quer saber?}
{118}{}{Você trabalha pro Darion?}
{119}{}{Ô que você faz com os raiders?}
{120}{}{Cadê a porca...por... porta do vault.}
{121}{}{Tem alguma coisa mágica acontecendo aqui?}
{122}{}{Mim partir.}
{123}{}{Você trabalha pro Darion?}
{124}{}{E sobre os raiders? O que pretende fazer?}
{125}{}{Onde fica a entrada do vault?}
{126}{}{Tem mais alguma coisa acontecendo por aqui?}
{127}{}{Acho que isso é tudo. Tenho que ir agora.}
{128}{}{Sim, trabalho. Sou o intermediário entre ele e as pessoas aqui. Não estou muito feliz com o fato, agora que sei o que ele planeja.}
{129}{}{Okay.}
{130}{}{Saquei.}
{131}{}{Nada. Eles têm armas, controlam a água e a comida. Quer dizer, quem manda são eles. Ponto. Não temos conhecimentos nem meio de vida sem o apoio de Darion. Como podemos nos virar contra ele? Estamos nas suas mãos.}
{132}{}{Hmm. Acho que entendi.}
{133}{}{Hmm. Entendi.}
{134}{}{Fica atrás daquela porta ali, mas está trancada pelo outro lado e tem uma armadilha também. Não tenho como abri... Calma aí, encontrei esta chave cartão faz um tempo e não tenho idéia pra que serve isso. Rebecca disse que você descobriu uma porta onde eles mantinham a Chrissy presa. Vai ver este cartão consegue abri-la. Tome aqui.}
{135}{}{Eu agradeço.}

{136}{}{Valeu. Vou tentar.}
{137}{}{Existe uma cidade a oeste daqui chamada Nova República da Califórnia. Eles dizem que o Vault 15 é a casa dos seus ancestrais e a querem de volta. Estão sempre enviando pessoas aqui pra tentar nos convencer a sair, mas não vamos sair. Isto aqui é a única casa que conhecemos.}
{138}{}{E porque não faz um acordo com eles?}
{139}{}{Já considerou fazer um acordo com a NRC?}
{140}{}{Depende. O que tem em mente?}
{141}{}{Junte-se a tribo NCR. E aprenda com os mais velhos. NCR da permissão para entrar vault.}
{142}{}{Se junte a NRC, deixe que anexem seu território e dêem a eles acesso ao vault. Em troca, eles podem ensinar a vocês as técnicas necessária para garantir a sobrevivência, além de oferecem proteção.}
{143}{}{Nada mal... gostei. Você acaba de conseguir um acordo, desde que a NRC concorde. Mas... olha só, alguém tem que dar um jeito no Darion e seus amigos. Isso deve ser feito antes que ele perceba o que está acontecendo e tenha tempo de se preparar para um ataque. Por que não dá um jeito nisso e acaba com Darion? Você terá o elemento surpresa ao seu lado.}
{144}{}{Você tem ração. Vou dá um jeito 'neis'.}

{145}{}{Sei não.}
{146}{}{É! Acho que isso tem que ser feito.}
{147}{}{Não sei.}
{148}{}{Ótimo! Boa sorte e muito obrigado.}
{149}{}{Pronto.}
{150}{}{Bem, pare pra pensar sobre isso. Mas saiba de uma coisa -- até Darion estar fora de jogada, não tenho outra escolha a não ser manter as coisas como estão. É pra segurança de todos os envolvidos. Isso quer dizer que não existe acordo e que você continue sendo essa pessoa tão grata. Entendeu?}
{151}{}{Okay.}
{152}{}{Oi! Ainda estou aguardando a solução final para os nossos problemas. Em outras palavras, mande Darion pro inferno.}
{153}{}{Pronto.}
{154}{}{Você conseguiu! Não estamos mais sobre o jugo da Darion. Obrigado! Estamos prontos para aceitar pacto com a NRC. Basta que eles enviem algum dos seus representantes que eu selo o acordo.}
{155}{}{Pronto.}
{156}{}{Obrigado pela chance de ter uma nova vida. Devemos isso a você.}
{157}{}{Vá embora. Não tenho nada pra conversar contigo.}
{158}{}{Calma.. antes de ir.  encontrei esta cartão chave faz um tempo e não tenho idéia pra que serve isso. 
 Rebecca disse que você descobriu uma porta onde eles mantinham a Chrissy presa. Vai ver este cartão consegue abrir. Pegue aqui.}

{159}{}{Valeu.}
{160}{}{Como posso te ajudar?}
{161}{}{Só os problemas com a NRC mesmo, mas acho que o acordo que ofereceu vai resolver isso.}
{162}{}{Você conseguiu! Não estamos mais sob o jugo de Darion. Obrigado!}
{163}{}{Agora que Darion se foi, não temos mais como conseguir alimento. Com certeza vamos morrer. Muito obrigado, viu.}
