{100}{}{Você está vendo um terminal de computador.}
{101}{}{Você está vendo um terminal de computador de segurança.}
{102}{}{Você está vendo um terminal de computador padrão. Parece ser funcional e pronto para a acessar.}
{103}{}{Este terminal monitora os geradores do campo de força. Ele indica que tudo está funcionando
 normalmente.}
{104}{}{Este terminal monitora os geradores do campo de força. Ele indica que a unidade está offline,
 devido à falta de energia.}
{105}{}{Gire o campo de força para desligar.}
{106}{}{Gire o campo de força para ligar.}
{107}{}{Concluído.}
{108}{}{Você dará o comando para desativar o campo de força.}
{109}{}{Você não consegue digitar os códigos de segurança para desativar o campo de força.}
{110}{}{Concluído.}
{111}{}{Você dará o comando para ativar o campo de força.}
{112}{}{Você não consegue digitar os códigos de segurança para ativar o campo de força.}
{113}{}{Concluído.}

{114}{}{Este terminal monitora os geradores do campo de força. Ele indica que o campo de força está desligado.}
{115}{}{Este terminal monitora os geradores de campo de força. Ele indica que o campo de força está
 temporariamente desabilitado.}
{116}{}{Este terminal monitora os geradores de campo de força. Isto indica que o campo de forças foi
 comprometido.}