{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal de computador da central de energia.}
{102}{}{Você vê um terminal de computador padrão. Ele parece funcional e pronto para ser usado.}
{103}{}{Este terminal monitora o gerador de energia. Ele indica que tudo está funcionando normalmente.}
{104}{}{Este terminal monitora o gerador de energia. Ele indica que a unidade está desligada devido a alguma falha.}
{105}{}{Pronto.}
