{100}{}{Você vê um terminal de computador.}
# You see a computer terminal.
{101}{}{Você vê o terminal de computador da central de energia.}
# You see the power center computer terminal.
{102}{}{Você vê um terminal de computador padrão. Ele parece funcional e pronto para ser usado.}
# You see a standard computer terminal. It appears to be functional and ready for input.
{103}{}{Este terminal monitora o gerador de energia. Ele indica que tudo está funcionando normalmente.}
# This terminal monitors the power generator. It indicates that everything is functioning
 normally.
{104}{}{Este terminal monitora o gerador de energia. Ele indica que a unidade está desligada devido a alguma falha.}
# This terminal monitors the power generator. It indicates that the unit is off line due to a
 malfunction of some sort.
{105}{}{Pronto.}