{100}{}{Você está vendo um terminal de computador.}
{101}{}{Você está vendo um terminal de computador da biblioteca.}
{102}{}{Você está vendo um terminal de computador padrão. Parece ser funcional e pronto para a acessar.}
{103}{}{Você acessa o computador e escaneia os arquivos disponíveis. Você encontra a localização do Vault 13
 e copia para seu PIP-BOY.}
{104}{}{Você está tendo dificuldade para acessar os arquivos.}
{106}{}{Além de outra localização do Vault 13, esse computador não contém uma informação útil.}