{100}{}{O gerador está funcionando normalmente. A saída de energia está no máximo.}
# The generator is functioning normally. Power output is optimal.
{101}{}{O gerador parece estar em modo stand-by. A saída de energia está no mínimo.}
# The generator seems to be in an emergency stand-by mode. The power output is minimal.
{102}{}{Tentar diagnosticar o problema.}
# Try to diagnose the problem.
{103}{}{É... tenho que ir.}
# Oh well. Gotta go.
{104}{}{Deve ter acontecido um curto-circuito no sistema alguma vez. Os disjuntores estão funcionando, mas foram mudados para a posição aberta. Você poderá ligá-los e restaurar a energia.}
# There must have been a short in the system at some time. The emergency circuit breakers kicked
 in, but fused in the open position. You may be able to free them up and restore power.
{105}{}{Você não consegue achar nada de errado. Só não funciona.}
# You can't seem to find anything wrong. It just doesn't work.
{106}{}{Tentar consertar.}
# Try to repair it.
{107}{}{Hora de ir embora.}
# Time to leave.
{108}{}{Você consegue quebrar os contatos e restabelecer energia.}
# You manage to break the contacts loose and restore power!
{109}{}{Maldição! Isso está mais duro do que parece.}
# Damn. This is tougher than it looks.
{110}{}{Terminado.}
# Done