
{100}{}{O gerador está funcionando normalmente. A saída de energia está no máximo.}
{101}{}{O gerador parece estar em modo stand-by. A saída de energia está no mínimo.}
{102}{}{Tentar diagnosticar o problema.}
{103}{}{É... tenho que ir.}
{104}{}{Deve ter acontecido um curto-circuito no sistema alguma vez. Os disjuntores estão funcionando, mas foram mudados para a posição aberta. Você poderá ligá-los e restaurar a energia.}
{105}{}{Você não consegue achar nada de errado. Só não funciona.}
{106}{}{Tentar consertar.}
{107}{}{Hora de ir embora.}
{108}{}{Você consegue quebrar os contatos e restabelecer energia.}
{109}{}{Maldição! Isso está mais duro do que parece.}
{110}{}{Terminado.}
