{100}{}{Você vê alguém em uma farda militar.}
{101}{}{Você vê alguém vestindo uma farda militar.}
{102}{}{Você vê alguém vestindo uma farda militar, mas eles parecem ser mais técnicos do que soldados.}

{103}{}{Ei, como vai?}
{104}{}{"Positivo, estou te vendo no monitor" – desculpe, mas estou no meio de uma coisa importante agora.}
{105}{}{Não posso falar agora.}
{106}{}{Sinta-se a vontade para olhar, mas não toque em nada.}

{107}{}{Você está se arriscando em andar por aí sem uniforme. É melhor requisitar algum no depósito.}
{108}{}{Se o sargento te pegar sem uniforme ele te mata.}
{109}{}{Por que está sem uniforme? }

{110}{}{Puta que pariu! Estamos sendo invadidos! Alerta!}
{111}{}{Intrusos! Chamem os guardas!}
{112}{}{Guardas! Intrusos no controle de tráfego aéreo!}

{113}{}{O que houve? Estamos sendo atacados?}
{114}{}{Por que o alerta? O que está acontecendo?}
{115}{}{Que diabos está acontecendo?}