{100}{}{Você vê um técnico.}
{101}{}{Você vê um técnico da Enclave.}
{102}{}{Você vê alguém usando um jaleco de laboratório. Ele parece ser confiante e seguro de si.}

{103}{}{Sim, soldado?}
{104}{}{Mim iniciante. Precisa fazer perguntas.}
{105}{}{Mim só dizer oi. Mim ir agora.}
{106}{}{Eu sou iniciante por aqui e estou tentando me familiarizar com a base. Posso te fazer algumas perguntas?}
{107}{}{Só dando um olá. Até logo.}

{108}{}{Claro. Eu tenho alguns minutos.}
{109}{}{Em que posso ajudar?}
{110}{}{Que lugar é esse?}
{111}{}{Qual o seu trabalho?}
{112}{}{Onde fica a base principal da Enclave?}
{113}{}{Mim procura por vertibird plans. Onde achar?}
{117}{}{Mim ir agora.}
{118}{}{O que é esse lugar?}
{119}{}{Qual é o seu trabalho?}
{120}{}{Onde se localiza a base principal da Enclave?}#Enclave main base> se achar traducao melhor...
{121}{}{Eu preciso dar uma olhada nos vertibird plans. Onde eles ficam guardados?}
{125}{}{Nada. Eu tenho que ir.}

{126}{}{Esse é o controle de tráfego aéreo. Daqui nós podemos monitorar todos os movimentos dos vertbirds.}
{127}{}{Mim entender. Mim pergunta mais.}
{128}{}{Certo. Mais algumas perguntas.}

{129}{}{Eu sou um técnico em computadores, primeira classe. Eu cuido da manutenção do link do mainframe.}
{130}{}{Hã... tá.}
{131}{}{Hum. Mantenha o bom trabalho.}

{132}{}{Você não veio de lá?}
{133}{}{Hã... não, mim veio do norte.}
{134}{}{Na verdade, não. Eu vim do extremo norte.}

{135}{}{Oh... eu não sabia que tínhamos uma base por lá. De qualquer forma, a base principal fica bem depois da costa de San Fran.}
{136}{}{Como ir lá?}
{137}{}{Bem... como fazemos pra chegar lá?}

{138}{}{Com os vertibirds, é claro. Não há outro meio, a não ser que você tenha um navio. Fica longe demais pra ir nadando.}
{139}{}{Valeu.}
{140}{}{Valeu.}

{141}{}{Vertibird plans... eu não vejo por que você iria querer saber disso. Sugiro que converse na manutenção, na porta ao lado.}
{142}{}{Certo.}
{143}{}{Entendi.}

{153}{}{Você enlouqueceu? Andar por aí sem farda? Vista-se logo!}
{154}{}{Se o sargento te pegar sem farda ele te mata.}
{155}{}{Por que está sem farda? }

{156}{}{Puta que pariu! Estamos sendo invadidos! Alerta!}
{157}{}{Intrusos! Chamem os guardas!}
{158}{}{Guardas! Intrusos no centro de comando!}

{159}{}{O que houve? Estamos sendo atacados?}
{160}{}{Por que o alerta? O que está acontecendo?}
{161}{}{Que diabos está acontecendo?}

{162}{}{Eu sou apenas um técnico! Não atire em mim!}
{163}{}{Eu não me alistei para combate, apenas pra treinamento técnico!}
{164}{}{Isso é um jaleco de laboratório, não uma armadura! Eu vou dar o fora daqui!}