{100}{}{Você vê o Sr. Cheater.}
{101}{}{Ele ainda parece um cheater.}
{200}{}{Olá, eu sou o Sr. Cheater. Como posso ajudar?}
{201}{}{Você vai sequestrar minho tribo?}
{202}{}{Você vai me colocar na missão Shi?}#missão x -> do original x quest. ex: Will you put me on Shi quest?
{203}{}{Você vai me colocar na missão Elron?}
{204}{}{Você vai me colocar na missão Brotherhood?}
{205}{}{Faça com que eu já tenha ido até a Military Base.}
{206}{}{Eu sequestrei sua tribo.}
{207}{}{Eu te coloquei na missão Shi.}
{208}{}{Eu te coloquei na missão Elron.}
{209}{}{Eu te coloquei na missão Brotherhood.}
{210}{}{Agora você já esteve na Military Base.}
{211}{}{Valeu, Sr. Cheater.}