{100}{}{Você vê um homem velho.}
{101}{}{Você vê Chris, o frentista do posto.}
{102}{}{Você vê um velho desmazelado vestindo um Robe.}#não sei o que você tá usando pra ROBE..
{103}{}{Olá, estranho. Uau! Olha só pra essas rodas! Não vejo uma
 dessas há anos. O que o velho Chris pode fazer por você?}
{104}{}{Olá, estranho. Nunca te vi por essas bandas antes. O que o velho
 Chris pode fazer por você?}
{105}{}{Que lugar é esse?}
{106}{}{Mim procura por Navarro. Ser aqui?}
{107}{}{Você viu um pássaro de metal passar por aqui?}
{108}{}{'Cê já ouviu falar da Enclave? Eles tão aqui?}
{109}{}{Mim só dando um olhada.}
{110}{}{Que lugar é esse?}
{111}{}{Estou procurando por Navarro. É aqui?}
{112}{}{Você já viu algum vertibird voar por aqui?}
{113}{}{Já ouviu falar sobre a Enclave? Eles estão por aqui?}
{114}{}{Só estou dando uma olhada.}
{115}{}{Isso aqui é o meu comércio, Chris's. É um posto de combustível - você nunca
 viu um desses, em revistas velhas ou algo parecido? É o que eu tenho aqui - um posto
 de combustível.}
{116}{}{Mim procura por Navarro. Ser aqui?}
{117}{}{Você viu um pássaro de metal passar por aqui?}
{118}{}{'Cê já ouviu falar da Enclave? Eles tão aqui?}
{119}{}{Hã... mim tem que ir.}
{120}{}{Estou procurando por Navarro. É aqui?}
{121}{}{Você já viu algum vertibird voar por aqui?}
{122}{}{Já ouviu falar da Enclave? Eles estão por aqui?}
{123}{}{Desculpe, tenho que ir.}
{124}{}{Navarro? Não ouço esse nome há anos. A velha base militar fica a sudeste de
 San Fran, e fica muito ao sul daqui.}
{125}{}{Mim estar lá. Não ser Navarro.}
{126}{}{Certo. Mim agradece. Mim procura lá.}
{127}{}{Você mentir pra mim. Mim sabe que Navarro estar aqui. Você fala a verdade ou mim fazer você lamentar!}
{128}{}{Eu estive lá e não é Navarro.}
{129}{}{Certo. Vou dar uma olhada lá. Obrigado.}
{130}{}{Você está mentindo. Eu sei que navarro fica aqui. Diga a verdade ou vai se
 lametar!}
{131}{}{Hein? Hã... Bem, claro que é. Eu ouvi falar há pouco tempo! Base Militar
 de Navarro, sudeste de San Francisco.}
{132}{}{Você mente. Mim não ter paciência. Você dizer a verdade ou vai se lamentar!}
{133}{}{Você mente. Eu não tenho paciência pra isso. Diga a verdade ou
 irá se lamentar.}
{134}{}{Vai te foder! (pega o rádio do robe) Você que ver lamentaçào? Eu tenho
 alguns garotos que irão te mostrar uma maneira de interpretar essa palavra! (começa a ligar o rádio)}#robe de novo
{135}{}{Mim matar você!}
{136}{}{O você estar fazendo?}
{137}{}{Mim ir embora.}
{138}{}{Péssima escolha, parceiro.}
{139}{}{O que você acha que está fazendo?}
{140}{}{Ei, estou indo embora.}
{141}{}{(falando no rádio) Alerta! Nós temos um intruso no posto! Alerta!}
{142}{}{Feito.}
{143}{}{Bem, foi bom falar com você. Aqui vai uma advertência - não há nada
 nessas bandas além de deserto e radiação. Civilização fica ao sul daqui. Eu iria para essa direção se fosse você.}
{144}{}{Obigado.}
{145}{}{Pássaros de metal? Ah, você quer dizer vertibirds. Agora, por que você
 está perguntando sobre eles aqui?}
{146}{}{Vertibirds? É um assunto interessante. Agora, por que você
 está perguntando sobre eles aqui?}
{147}{}{Shaman diz que pássaro de metal pegou vila, voou Navarro. Mim tentar encontrar.}
{148}{}{Pessoas interessadas. Mim tentar achar.}
{149}{}{Você saber sobre eles? O que saber?}
{150}{}{O shaman da minha tribo me disse que esses vertibirds roubaram as pessoa de lá.
 Estou aqui para encontrá-los.}
{151}{}{Eu conheço algumas pessoas que estão interessadas nos vertibirds. Estou tentando
 localizá-los para elas.}
{152}{}{Então você sabe algo sobre os vertibirds. Fale-me sobre eles.}
{153}{}{Shaman? Olha; se seu shaman disse que vê coisas voando por aí
 e capturando pessoas então ele deve estar cheirando ervas demais. Entendeu?}
{154}{}{Hakunin grande shaman. Se ele diz que viu então ele viu.}
{155}{}{Hakunin foi um grande shaman. Se ele disse que viu vertibirds, então ele
 os viu!}
{156}{}{Bem, isso não quer dizer nada pra mim, mas no caso de eu vir um
 desses vertibirds, pra quem eu devo contar?}
{157}{}{Você contar pra mim. Mim estar por perto.}
{158}{}{Contar pro Shi.}
{159}{}{Contar pra Brotherhood of Steel.}
{160}{}{Contar pros Hubologistas.}
{161}{}{Escolher. Você contar pro Shi ou Brotherhood of Steel ou Hubologistas.
 Todos interessados.}
{162}{}{Você pode me contar. Vou estar por perto.}
{163}{}{Você pode contar aos Shi.}
{164}{}{Você pode contar a Brotherhood of Steel.}
{165}{}{Você pode contar aos Hubologistas.}
{166}{}{Faça sua escola. Conte aos Shiou a  Brotherhood of Steel
 ou aos Hubologistas. Todos eles estão interessados nos vertibirds.}
{167}{}{Aos Shi, hein? Bem, se você diz. Eu vou dar um palavra a eles
 em China town. Por enquanto tenho coisas a fazer.}
{168}{}{Espera. Mim ter amigos fortes. Eles diz que Navarro aqui. Você diz
 onde ou coisas ficarem ruins pra você!}
{169}{}{Espere um minuto, cara. Obviamente, eu tenho amigos poderosos e
 eles dizem que Navarro está aqui. Agora diga onde está ou as coisas vão piorar pro seu lado!}
{170}{}{A Brotherhood... Hã, certo, bem, eu irei fazer isso. Por enquanto
 eu tenho coisas a fazer.}
{171}{}{Espera. Mim ter amigos fortes. Eles diz que Navarro aqui. Você diz
 onde ou coisas ficarem ruins pra você!}
{172}{}{Espere um minuto, cara. Obviamente, eu tenho amigos poderosos e
 eles dizem que Navarro está aqui. Agora diga onde está ou as coisas vão piorar pro seu lado!}
{173}{}{Os Hubs? É, claro, eu vou comunicar se achar alguma coisa.
 Por enquanto tenho coisas pra fazer.}
{174}{}{Espera. Mim ter amigos fortes. Eles diz que Navarro aqui. Você diz
 onde ou coisas ficarem ruins pra você!}
{175}{}{Espere um minuto, cara. Obviamente, eu tenho amigos poderosos e
 eles dizem que Navarro está aqui. Agora diga onde está ou as coisas vão piorar pro seu lado!}
{176}{}{Merda, que desgraça de lista... Hã, bem, se eu vir alguma coisa
 eu vou... É, bem, eu tenho mais o que fazer.}
{177}{}{Espera. Mim ter amigos fortes. Eles diz que Navarro aqui. Você diz
 onde ou coisas ficarem ruins pra você!}
{178}{}{Espere um minuto, cara. Obviamente, eu tenho amigos poderosos e
 eles dizem que Navarro está aqui. Agora diga onde está ou as coisas vão piorar pro seu lado!}
{179}{}{Hã... Ei. eu só recebi ordens de receber os visitantes e tal. Eu não quero
 esse tipo de problema que você está falando.}
{180}{}{Então diz o melhor caminho pra base... agora!}
{181}{}{Então eu sugiro que me diga o melhor caminho para a base... agora!}
{182}{}{Suponho que seja pela porta no chão do meu quarto.
 Vá e me deixe em paz.}
{183}{}{Certo, mim ir.}
{184}{}{Certo. Estou indo.}
{185}{}{Eu sei que eles voam por aqui de tempos em tempos. Geralmente vão
 para o sul rumo a San Fran. Se você está interessado sobre os vertibirds, eu iria pra lá.}
{186}{}{Certo, mim tentar lá.}
{187}{}{Mim ter amigos que quer que mim acha vertibirds. Amigos diz que vertibirds
 vir aqui}
{188}{}{Certo, eu irei pra lá.}
{189}{}{Olha, eu tenho alguns amigos que querem que eu ache os vertibirds. Eles me disseram
 que eles vêm pra cá.}
{190}{}{Enclave? Isso é um grupo ou algo assim? Isso não me soa
 familiar. O que você quer com eles?}
{191}{}{Mim que juntar.}
{192}{}{Eu quero me alistar.}
{193}{}{Alistar? Você é um tribal! O que o faz pensar que eles vão querer um tribal?}
{194}{}{Alistar? Você é um tribal! O que o faz pensar que eles vão querer um tribal
 em seu pelotão?}
{195}{}{Mim sério. Quer juntar com Enclave.}
{196}{}{Mim sério. Quer juntar com Enclave.}
{197}{}{Estou falando sério. Eu quero me alistar na Enclave.}
{198}{}{Estou falando sério. Eu quero me alistar na Enclave.}
{199}{}{Espere um minuto, imbecil. Você está tentando dizer que é um dos substitutos
 da Enclave?}
{200}{}{Espere um minuto. Você está tentando dizer que é um dos substitutos
 da Enclave?}
{201}{}{Hã... é.}
{202}{}{Correto.}
{203}{}{Merda. Desculpe pela complicação. Eu tenho que espantar um bando de novatos
 que vêm pra cá, mas tenho que me livrar do lixo. De qualquer forma, apenas vá para cima até o portão,
 através das árvores alí, e diga a senha pra eles. É 'sheepshead.' Ah, ande na trilha!}#SHEEPSHEAD: large (up to 20 lbs) food fish of the eastern coast of the United States and Mexico. nao sei o nome em portugues.
{204}{}{Obrigado!}
{205}{}{Espere um minuto, imbecil. Você está dizendo que é um do substitutos da
 Enclave? Se é o caso, porque não está sozinho?}
{206}{}{Espere um minuto. Você está dizendo que é um do substitutos da
 Enclave? Se é o caso, porque não está sozinho?}
{207}{}{Hã... escolta?}
{208}{}{Eu contratrei uma escolta!}
{209}{}{Bem, eu não quero ser rude nem nada, mas aqui é um propriedade privada.
 Se você vai sair brigando por aí, não faça isso aqui.}
{210}{}{Certo.}
{211}{}{Você voltou. O que o velho Chris pode fazer por você?}
{212}{}{Você dizer que Navarro sul. Você mentir! Mim aqui pra verdade.}
{213}{}{Você me disse que Navarro estava ao sul, velho. Agora eu quero saber a verdade.}
{214}{}{Você me parece familiar. O velho Chris acha que já te viu antes... Não, não pode ser.}
{215}{}{Intruso no posto! Mande ajuda!}
{216}{}{Soe o alarme!}
{217}{}{Alerta, intruso! Alerta, instruso!}
{218}{}{Morra, lixo!}
{219}{}{A Enclave vai me promover por matar você!}
{220}{}{Morra, forasteiro!}
{221}{}{Mas que p...?!}
{222}{}{Você usar rádio e mim fazer você se lamentar!}
{223}{}{Use esse rádio e eu vou fazer você se lamentar!}
{224}{}{Vai te foder! Você que ver lamentação? Eu tenho alguns garotos que vão te mostrar uma nova
 maneira de interpretar essa palavra! (começa a ligar o rádio)}
{225}{}{Mim matar você!}
{226}{}{What you do now?}
{227}{}{Mim ir embora.}
{228}{}{Péssima escolha, parceiro.}
{229}{}{O que pensa que está fazendo?}
{230}{}{Ei, estou indo embora daqui.}
{231}{}{É, certo.}
{232}{}{Ele está tirando um rádio. Ele vai alertar toda a base! Eu tenho que dar um jeito nele rápido.}

{800}{}{Você enganou Chris e ele te deu a senha.}
{810}{}{Você matou Chris antes que ele alertasse a base.}