{100}{}{Você vê o cozinheiro.}
{101}{}{Você vê Cookie, o cozinheiro.}
{102}{}{Você vê um homem em armadura usando um chapéu do cozinheiro e um avental.}

{103}{}{Ei soldado. Está procurando alguma gororoba ou só alguém pra conversar? }
{104}{}{Eu quero comida.}
{105}{}{Eu quero conversar.}
{106}{}{Eu queria comer algo.}
{107}{}{Vamos conversar um pouco.}

{108}{}{Bem, aqui está. Tem alguma merda na telha. Neve e merda que voa em cima. Algo mais?}
{109}{}{O que você espera que eu coma?}
{110}{}{Merda? Neve? Mas que porra de comida que é essa?}

{111}{}{Me desculpe, você deve ser novo na base. Não se ofenda com o que eu disse, é só o jeito como chamamos as coisas por aqui. Merda na telha é carne assada. Neve e merda. São os outros nomes de sal e pimenta.}
{112}{}{Ah... obrigado. Vamos conversar enquanto eu como.}
{113}{}{Entendi, desculpe. Vamos conversar enquanto eu como.}

{114}{}{Sobre o que quer conversar?}
{115}{}{O que fazem aqui?}
{116}{}{Onde estão as plantas dos vertibirds?}
{118}{}{Onde é a base principal?}
{119}{}{Eu preciso voltar ao trabalho. Obrigado.}
{120}{}{O que acontece nessa base?}
{121}{}{Estou interessado nos vertibirds. Se eu quiser dar uma olhada nas plantas, onde eu posso encontrá-las?}
{123}{}{Onde fica a base principal da Enclave?}
{124}{}{Obrigado. Eu preciso voltar ao trabalho.}

{125}{}{Quer saber de alguma fofoca? Eu posso te contar o que anda acontecendo na sala de manutenção, laboratório médico, ou sobre os soldados.}
{126}{}{O que você quer saber?}
{127}{}{O que sabe sobre a sala de manutenção?}
{128}{}{O que sabe sobre o laboratório médico?}
{129}{}{O que sabe sobre os soldados?}
{130}{}{Algo mais?}
{131}{}{Eu já ouvi o bastante.}
{132}{}{O que ta acontecendo na sala de manutenções?}
{133}{}{O que você pode me dizer sobre o laboratório médico?}
{134}{}{O que você sabe sobre os soldados?}
{135}{}{Ta acontecendo mais alguma coisa?}
{136}{}{Eu já ouvi o bastante, eu acho.}

{137}{}{Raul, o mecânico dos vertibirds, não gosta do Quincy, o chefe da manutenção. Esses dois estão sempre brigando. Eu não acho que seja uma rivalidade profissional qualquer. De qualquer modo, Raul é um arrogante mas o Quincy é um cara legal. Espero que ele ganhe no final.}
{138}{}{Okay.}
{139}{}{Sim, eu entendi.}

{140}{}{O laboratório médico é comandado por um cabeça de ovo da enclave chamado Schreber. Aquele filha da puta; ele não se importa com nada e nem ninguém. Ele está fazendo umas experiências com deathclaws lá embaixo, só que não sei o que é. De qualquer jeito, ele fazia tanto barulho que o comandante mandou colocar isolantes sonoros na sala.}
{141}{}{Entendi.}
{142}{}{Isso é interessante. }

{143}{}{Ha! Nós estamos falando de romance, meu amigo. Parece que um dos super computadores se apaixonou por um dos soldados, a guarda que fica do lado de fora do laboratório médico. Tem até um desses nomes "fofos" para ela. Chama ela de "Snookie" para tudo.}
{144}{}{Que fofo.}

{145}{}{Nah, isso é tudo que eu sei por aqui. Se eu ficar sabendo de mais alguma coisa eu vou te contar. Eu gosto mais de falar do que ouvir!}
{146}{}{Obrigado.}

{147}{}{Porque você ta interessado nisso? Ah bem, não importa. Eu acho que Quincy guarda elas na sala de manutenções. }
{148}{}{Okay.}
{149}{}{Onde fica?}
{150}{}{Sei.}
{151}{}{Onde fica isso?}

{152}{}{No canto nordeste da base, amigo. Não tem como errar.}
{153}{}{Okay. Obrigado.}

{156}{}{Estou surpreso que você não saiba, você deve ser um novato, eu acho. De qualquer maneira, a base principal fica no meio da maldito oceano. Bem, não exatamente no meio, mas é possível que seja. O único jeito de chegar lá é de navio ou de vertibird e é foda ir de navio pra lá. Você precisa de um fob para operar aquela bosta.}
{157}{}{Fob?}

{158}{}{É, uma chave. O Comandante guarda ela no seu escritório. Sem ela você não tem acesso a algumas partes do navio e isso mantém alguns lugares abaixo de San Fran de visitas não desejadas.}
{159}{}{Boa idéia.}
{160}{}{Onde é o escritório do comandante?}
{161}{}{Essa é uma boa idéia.}
{162}{}{Então, onde fica o escritório do comandante?}

{163}{}{Desça pelo elevador da sala ao lado, siga pelo corredor até o cruzamento, e siga reto. }
{164}{}{Obrigado.}

{165}{}{Ei, soldado. Bom ouvir você de novo. Gororoba ou conversa dessa vez?}
{166}{}{Comida.}
{167}{}{Conversa.}
{168}{}{Passei só pra falar um oi.}
{169}{}{Nada, Só to dando uma passada pra falar um oi.}

{170}{}{Aqui está. Ta morto, ta cozido, ta identificável. Sirva-se.}
{171}{}{Uh... Obrigado.}

{172}{}{Filho, eu posso sentir o cheiro de que você está sem sua armadura.
 Se o sargento ver você sem uniforme você tá fudido. E eu não estou falando que o jeito que ele te fuder seja bom. Agora mexa esse seu rabo e desça para a sala de suprimentos e coloque sua armadura.}
{173}{}{Princesinha, eu posso sentir o cheiro de que você está sem sua armadura.
 Se o sargento ver você sem uniforme você ta fudida. E eu não estou falando que o jeito que ele te fode seja bom. Agora desça para a sala de suprimentos e coloque sua armadura.}
{174}{}{Onde fica?}
{175}{}{Okay.}
{176}{}{Onde fica isso?}
{177}{}{Cuidarei disso.}

{178}{}{Desça pelo elevador da sala ao lado, siga pelo corredor até o cruzamento, vire à esquerda, é a primeira porta a sua esquerda. Vai lá.}
{179}{}{Obrigado.}

{180}{}{Puta merda! Eu sou apenas um cozinheiro... e cego por sinal. Eu não vi nenhum intruso por aqui.}
{181}{}{Obrigado.}

{182}{}{Porra de alarme. Sempre toca quando eles estão saindo.}
{183}{}{Que porra que é dessa vez?}
{184}{}{Eu gostaria que eles usassem alarmes silenciosos, essa porra me dá dor de cabeça.}

{185}{}{Eu vou fritar sua bunda e servi-lá num prato.}
{186}{}{Seu peru ta assado. Ha! Eu fiz uma piada!}
{187}{}{Fora da frigideira e dentro do fogo.}
