{100}{}{Você vê um cientista.}
{101}{}{Você vê o Dr. Schreber.}
{102}{}{Você vê um homem careca em um jaleco de laboratório.}

{103}{}{Espero que tenha um bom motivo pra interromper meu trabalho, soldado.}
{104}{}{Mim que fazer perguntas.}
{105}{}{Não, mim voltar depois.}

{106}{}{Muito bem. Eu tenho que conviver com vocês ogros, então eu poderia
 me esforçar pra me entender com vocês.}
{107}{}{O que você quer saber?}
{108}{}{Quem ser você?}
{109}{}{O que você fazer?}
{110}{}{O que ser esse lugar?}
{111}{}{Porque esse sala não fazer barulho?}
{112}{}{Por que ter D'claw na outra sala?}
{113}{}{Por que cachorrinho não move? Não fazer nada?}
{114}{}{Mim tem que ir agora.}
{115}{}{Quem é você?}
{116}{}{O que você faz aqui?}
{117}{}{Que lugar é esse?}
{118}{}{Por que esse cômodo é à prova de som?}
{119}{}{Por que tem um deathclaw no outro cômodo?}
{120}{}{O que há com a estátua de cachorro ali na porta?}
{121}{}{Eu tenho que ir agora.}

{122}{}{Meu nome é Schreber, Dr. Schreber. Eu sou o médico da base entre
 outras coisas. Não se incomode com o seu nome, soldado. Todos os outros ogros parecem
 ser a mesma pessoa com essa armadura de vocês.}
{123}{}{Certo.}
{124}{}{Entendi.}

{125}{}{Eu trabalho como médico da base mas isso é só um bico. Na verdade,
 eu sou um geneticista.}
{126}{}{O que ser isso?}
{127}{}{O que é um geneticista?}

{128}{}{Eu  realmente não acho que você tenha capacidade intelectual para
 entender meu trabalho, soldado. Vamos dizer apenas que eu posso 'modificar' pessoas
 ou animais.}
{129}{}{Ah... claro.}
{130}{}{É... eu preciso fazer mais algumas séries de perguntas.}

{131}{}{Esse era o laboratório médico da base. Entretanto, eu senti que meus experimentos
 tomavam precedentes mínimos em necessidades médicas dos soldados. Então eu
 decidi convertê-lo em um laboratório.}
{132}{}{Que... legal.}
{133}{}{Interessante. Então me conte outra coisa.}

{134}{}{Por que não faz som? Ah, você quer dizer à prova de som! É
 por causa da pesquisa que estou fazendo... experimentos em cobaias.
 Às vezes elas gritam um pouco. O comandante da base achou que
 isso perturbava então ele mandou instalar as paredes à prova de som.}
{135}{}{É por causa da pesquisa que estou fazendo... experimentos em cobaias.
 Às vezes elas gritam um pouco. O comandante da base achou que
 isso perturbava então ele mandou instalar as paredes à prova de som.}
{136}{}{Ah...}
{137}{}{Entendendo.}

{138}{}{Grande, marrom e feio? É um experimento que eu completei
 recentemente. Ele está para ser exterminado.}
{139}{}{O que exteminado que dizer?}
{140}{}{Por que vocês vão matá-lo?}

{141}{}{Oh meu D... Você não é O brilhante, não é? Exterminar. Matar, deitar,
 colocar pra dormir, apagar. Entendeu?}
{142}{}{Mim entendeu. Por que você querer matar D'claw?}

{143}{}{A Enclave está procurando por soldados baratos, prescindíveis.
 Nós estamos interessados em deathclaws porque eles nascem com armadura e
 arma, e eles são muito temidos. Eles só precisam ser mais inteligentes para
 que possam entender os comandos mas não tão inteligentes a ponto de desenvolver
 seu próprio comando. Está me entendendo?}
{144}{}{Ah... claro.}
{145}{}{Sim, prossiga.}

{146}{}{Bem, nós obtivemos sucesso! Na verdade nós conseguimos incrementar sua
 inteligência. Entretanto, eu comecei a suspeitar que nós fomos longe demais.
 Talvez eles fossem muito mais espertos do que estavam se deixando revelar. Então,
 quando eu fui transferido pra cá eu trouxe um deles comigo, assim eu
 poderia colocar minha teoria em teste.}
{147}{}{E?}

{148}{}{Eu estava certo! Os deathclaws estavam aparentemento se passando por
 idiotas, tentando ganhar tempo e tentando aprender o máximo que pudessem
 de nós. Eles podem até imitar a voz humana! Eu inclusive tive
 uma conversa com o companheiro na sala ao lado.}
{149}{}{De qualquer maneira, o fato deles terem sido capazes de conceber
 esse plano mostra o quão perigosos
 eles são.}
{150}{}{Então o que você fazer agora?}
{151}{}{E o que você planeja fazer agora?}

{152}{}{Eu irei emitir um relatório sobre minhas descobertas e
 trasmiti-lo à Enclave. É claro que terei que recomendar a
 exterminação dos deathclaws criados. Eles são uma ameaça muito
 perigosa.}
{153}{}{Mim entender. Mim precisa peguntar mais.}
{154}{}{Hã... você ter certeza que sala à prova de som?}
{155}{}{Mim quer matar D'claw pra você!}
{156}{}{Ei, eu posso matar o deathclaw pra você?}
{157}{}{Interessante. Posso fazer mais algumas perguntas?}
{158}{}{Doutor, você tem certeza que essa sala é à prova de som?}

{159}{}{Claro que eu tenho. O comandante teria um ataque se não fosse. Por quê?}
{160}{}{Nada não.}
{161}{}{Mim não que que ninguém escute seu grito quando mim matar você!}
{162}{}{Só por curiosidade.}
{163}{}{Eu não quero que ninguém ouça seus berros enquanto eu faço meus experimentos com você.}

{164}{}{Voltou? O que eu posso fazer por você dessa vez?}
{165}{}{Você  ter certeza que sala à prova de som?}
{166}{}{Mim quer fazer mais perguntas.}
{167}{}{Nada. Mim apenas dizer oi.}
{168}{}{Você tem certeza que essa sala é à prova de som?}
{169}{}{Eu gostaria de fazer mais algumas perguntas.}
{170}{}{Nada, só passei pra dar um 'oi'.}

{171}{}{Claro que eu tenho. O comandante teria um ataque se não fosse. Por quê?}
{172}{}{Nada não.}
{173}{}{Mim não que que ninguém escute seu grito quando mim matar você!!}
{174}{}{Apenas por curiosidade.}
{175}{}{Eu não quero que ninguém ouça seus berros enquanto eu faço meus experimentos com você.}

{176}{}{Com o maior prazer. Está sala ao lado.}
{177}{}{Valeu!}

{178}{}{Esse é o K-9, meu cachorro. Eu decidi tentar realçar sua
 inteligência cibernética. Funcionou, mas ele desenvolveu um sério caso de
 moral. Ele decidiu que não gosta do meu trabalho nem de mim e me mordeu.}
{179}{}{Como punição eu desativer as pernas dele e o deixe muito mais
 útil. Agora ele tem que ficar sentado aqui e assistir todas as coisas
 desagradáveis que eu faço.}
{180}{}{Oh...}
{181}{}{Ele poder ser consertado?}
{182}{}{Entendo.}
{183}{}{Ele pode ser consertado?}

{184}{}{Ah sim. Eu removi seu circuito de locomoção e o dei pro
 Raul na manutenção. Ele pode ser recolocado a qualquer hora... Talvez
 eu farei isso algum dia apenas pra ver se ele mudou de atitude.}
{185}{}{Certo.}
{186}{}{Tudo bem.}

{187}{}{Você é um civil?}
{188}{}{Esse é o laboratório médico. O depósito de armas fica na entrada, a sua esquerda.}
{189}{}{Por que você está sem uniforme?}

{190}{}{Puta merda! Nós estamos sendo invadidos! Alerta!}
{191}{}{Intrusos! Chamem o guarda!}
{192}{}{Guarda! Intrusos no laboratório médico!}

{193}{}{O que há? Estamos sendo atacados?}
{194}{}{Por que o alerta? O que está acontecendo?}
{195}{}{Que diabos está acontecendo?}

{196}{}{Eu não vou te fazer mal, não atire em mim.}
{197}{}{Eu não me alistei pra lutar, então me deixe em paz.}
{198}{}{Merda! Eu sou um médico, não um soldado!}

{200}{}{[Mais]}
{201}{}{Eu gostaria de te fazer algumas perguntas.}
{202}{}{Não agora. Desculpe por interrompê-lo.}

{800}{}{Você matou o Doutor Schreber.}