{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em uma power armor.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Circulando.}
{104}{}{Estou trabalhando. Não tenho tempo pra falar agora.}
{105}{}{Keep it moving. Gate’s that way.}#que gate? entrada, porta...?

{106}{}{É melhor pegar sua farda.}
{107}{}{Não ande por aí sem farda.}
{108}{}{Você está no exército agora. Não seja pego sem farda.}

{109}{}{Instrusos no portão principal!}
{110}{}{Soem o alarme! Instrusos!}
{111}{}{Deploy backup to the main gate. We’ve got intruders!}

{112}{}{Alerta de segurança no portão principal!}
{113}{}{Matenham todas as áreas seguras! Portão principal sob ataque!}
{114}{}{Código vermelho no portão principal!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave vai dominar o mundo!}
{117}{}{You die so that the Enclave will survive!}