{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda vestindo uma combat armor.}
{102}{}{Você vê alguém vestindo uma combat armor. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Nada a declarar.}
{104}{}{Não vi nada de errado, e você?}
{105}{}{Você não deveria estar no seu posto, soldado? Não é bom andar por aqui.}

{106}{}{Você está sem a farda.}
{107}{}{É melhor você falar com o Sargento e se vestir.}
{108}{}{Você está se arriscando em andar por aí sem farda. Melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Instrusos!}
{110}{}{Nós fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Soem o alarme!}

{112}{}{Alerta de segurança! Fechem todas as saídas!}
{113}{}{Mantenhas todas as áreas seguras! Estamos em alerta!}
{114}{}{Alerta de instrusos! Código vermelho!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave irá dominar o mundo!}
{117}{}{You die so that the Enclave will survive!}