{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda vestindo uma power armor.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Nada a declarar.}
{104}{}{Não vi nada de errado, e você?}
{105}{}{Você não devia estar no seu posto, soldado? Não é bom ficar andando por aqui.}

{106}{}{Você está sem a farda.}
{107}{}{É melhor você falar com o Sargento e se vestir.}
{108}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Nós fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Soem o alarme!}

{112}{}{Alerta de segurança! Fechem todas as saídas!}
{113}{}{Mantenham todas as áreas seguras! Estamos sob alerta!}
{114}{}{Alerta de intrusos! Código vermelho!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave irá dominar o mundo!}
{117}{}{You die so that the Enclave will survive!}

{200}{}{...cusão...}#ou cuZão?
{201}{}{...é, é MELHOR você ir andando...}
{202}{}{...what a brownie hound...}
{203}{}{...sim, senhor! Vai te foder, senhor!...}