{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda vestindo uma power armor.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Nada a declarar.}
{104}{}{Não vi nada de errado, e você?}
{105}{}{Você não devia estar no seu posto, soldado? Não é bom ficar andando por aqui.}

{106}{}{Você está sem a farda.}
{107}{}{É melhor você falar com o Sargento e se vestir.}
{108}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Nós fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Soem o alarme!}

{112}{}{Alerta de segurança! Fechem todas as saídas!}
{113}{}{Mantenham todas as áreas seguras! Estamos sob alerta!}
{114}{}{Alerta de intrusos! Código vermelho!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave irá dominar o mundo!}
{117}{}{You die so that the Enclave will survive!}

{200}{}{...cusão...}
{201}{}{...é, é MELHOR você ir andando...}
{202}{}{...o que um brownie...}
{203}{}{...sim, senhor! Vai se fuder, senhor!...}

#added by killap - RP
{300}{}{Espere aí. O que você acha que está fazendo com esta aeronave? Não há vôos regulares há vários dias.}
{301}{}{Hãn?}
{302}{}{Estou ciente disso.}
{303}{}{Sinto muito. Eu estava apenas olhando. Eu ja estou indo agora.}
{304}{}{Houve uma mudança de planos. Vou levar esta aeronave.}

{310}{}{O quê? Oh isso é só para olhar, não toque. Ok? Se Tocar novamente você morre.}
{311}{}{(Sorria e em seguida os ataques)}
{312}{}{(Vá embora.)}

{315}{}{Oh merda, parece que temos mesmos um intruso. Código vermelho! Repito, o código vermelho!}
{316}{}{Isso parece uma boa idéia. Toque no avião de novo e eu vou meter uma bala em sua cabeça.}

{320}{}{Certo. E, portanto, você é ...}
{321}{}{Ja estou saindo. Desculpe incomodá-lo.}
{322}{}{Vou entregar uma mensagem importante para a base.}
{323}{}{Ah, é mesmo? E o que diz essa mensagem.}
{324}{}{É super top secret. Eu não posso te dizer.}
{325}{}{Eu vou te dizer, mas é absolutamente essencial que você não conte essas informações a ninguém, para não causar um pânico em massa. 
você vai ver, veio ao meu conhecimento que um dos últimos carregamentos de escravos estava infectado com um vírus desconhecido e altamente mortal. 
DEVO chegar à base imediatamente, ou todos nos podemos morrer. 
Agora, pare de desperdiçar meu tempo, porque não há tempo a perder.}
{326}{}{Sim, eu acredito em você. Parece que temos um intruso ...}
{327}{}{Droga! Ah, sei lá. Nunca me contam merda de nada por aqui. Bom. Siga seu caminho.}
{328}{}{Woah, isso é ruim. É melhor você se mexer então, eu não quero essa merda em minhas mãos. Ah, e não se preocupe, não vou contar a ninguém.}
{329}{}{[FEITO]}