{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda vestindo uma power armor.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Nada a declarar.}
{104}{}{Não vi nada de errado, e você?}
{105}{}{Você não devia estar no seu posto, soldado? Não é bom ficar andando por aqui.}

{106}{}{Você está sem a farda.}
{107}{}{É melhor você falar com o Sargento e se vestir.}
{108}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Nós fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Soem o alarme!}

{112}{}{Alerta de segurança! Fechem todas as saídas!}
{113}{}{Mantenham todas as áreas seguras! Estamos sob alerta!}
{114}{}{Alerta de intrusos! Código vermelho!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave irá dominar o mundo!}
{117}{}{Você morre para que a Enclave sobreviva!}

{200}{}{...cusão...}
{201}{}{...é, é MELHOR você ir andando...}
{202}{}{...o que um brownie...}
{203}{}{...sim, senhor! Vai se fuder, senhor!...}

#added by killap - RP
{300}{}{Espere aí. O que você acha que está fazendo com esta aeronave? Não há vôos regulares há vários dias.}
{301}{}{Hãn?}
{302}{}{Estou ciente disso.}
{303}{}{Sinto muito. Eu estava apenas olhando. Eu já estou indo agora.}
{304}{}{Houve uma mudança de planos. Vou levar esta aeronave.}

{310}{}{O quê? Oh isso é só para olhar, não toque. Ok? Se Tocar novamente você morre.}
{311}{}{(Sorria e em seguida os ataques)}
{312}{}{(Vá embora.)}

{315}{}{Oh merda, parece que temos mesmos um intruso. Código vermelho! Repito, o código vermelho!}
{316}{}{Isso parece uma boa idéia. Toque no avião de novo e eu vou meter uma bala em sua cabeça.}

{320}{}{Certo. E, portanto, você é ...}
{321}{}{Ja estou saindo. Desculpe incomodá-lo.}
{322}{}{Vou entregar uma mensagem importante para a base.}
{323}{}{Ah, é mesmo? E o que diz essa mensagem.}
{324}{}{É super top secret. Eu não posso te dizer.}
{325}{}{Eu vou te dizer, mas é absolutamente essencial que você não conte essas informações a ninguém, para não causar um pânico em massa. 
você vai ver, veio ao meu conhecimento que um dos últimos carregamentos de escravos estava infectado com um vírus desconhecido e altamente mortal. 
DEVO chegar à base imediatamente, ou todos nos podemos morrer. 
Agora, pare de desperdiçar meu tempo, porque não há tempo a perder.}
{326}{}{Sim, eu acredito em você. Parece que temos um intruso ...}
{327}{}{Droga! Ah, sei lá. Nunca me contam merda de nada por aqui. Bom. Siga seu caminho.}
{328}{}{Woah, isso é ruim. É melhor você se mexer então, eu não quero essa merda em minhas mãos. Ah, e não se preocupe, não vou contar a ninguém.}
{329}{}{[FEITO]}

# [After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! One of those mutie wastlanders stowed away in the 'bird! ALERT! We got an intruder!
{400}{}{[Após ficar meia hora dentro do escuro compartimento de carga, você sente o veículo tocar o solo novamente. Um minuto
 depois, a porta do compartimento abre e você vê um esquadrão de soldados com power armor. Um deles da uma olhada em
 você e fala com os companheiros.] Puta merda! Um desses mutantes do deserto se escondeu no 'pássaro! ALERTA! Temos um invasor!}
 
# [After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! Some of those mutie wastlanders stowed away in the 'bird! ALERT! We got intruders!
{401}{}{[Após ficar meia hora dentro do escuro compartimento de carga, você sente o veículo tocar o solo novamente. Um minuto 
 depois, a porta do compartimento abre e você vê um esquadrão de soldados com power armor. Um deles da uma olhada em 
 você e fala com os companheiros.] Puta merda! Alguns desses mutantes do deserto se esconderam no 'pássaro! ALERTA! Temos invasores!}

# [Jump out and see how many you can take down before they waste you.]
{402}{}{[Pular para fora e ver quantos você consegue matar antes que eles te eliminem.]}

# [Raise hands in surrender and hope for the best.]
{403}{}{Erguer as mãos se rendendo e esperar pelo melhor.]}

# Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring him to the Commander -- see
 what he wants to do about this.
{410}{}{Awn, parece que o mutante não oferece ameaça. Poderíamos levar ele até o Comandante -- ver o que ele 
 acha disso.}
 
# Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring her to the Commander -- see
 what he wants to do about this.
{411}{}{Awn, parece que a mutante não oferece ameaça. Poderíamos levar ela até o Comandante -- ver o que ele 
 acha disso.}
 
# Aw, it doesn't look like the muties are gonna put up a fight. Maybe we should bring them to the Commander -- see
 what he wants to do about this.
{412}{}{Awn, parece que os mutantes não oferecem ameaça. Poderíamos levá-los até o Comandante -- ver o que ele 
 acha disso.}
 
#player wearing power armor

# [After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of Enclave soldiers. One of them does a double-take at you.] What the hell
 are you doing back here? You weren't authorized to be on that mission. What's your name, soldier?
{420}{}{[Após ficar meia hora dentro do escuro compartimento de carga, você sente o veículo tocar o solo novamente. Um minuto 
 depois, a porta do compartimento abre e você vê um esquadrão de soldados do Enclave. Um deles da uma olhada em você.] 
 Que diabo você está fazendo aqui? Você não está autorizado a participar dessa missão. Qual é o seu nome, soldado?}
 
# It doesn't matter what my name is, 'cause I'm not here to talk. [Jump out and start fighting.]
{421}{}{Não importa qual é meu nome, porque eu não estou aqui para conversar [Pular fora e começar a lutar.]}

# Me? Oh, I'm, uh, *cough*mumble*cough*. Don't mind me, though. In fact, I should probably be going now.
 [Get out and attempt to walk away nonchalantly.]
{422}{}{Meu? Oh, eu, uh *tosse*murmura*tosse*. Não se preocupe comigo. Na verdade, eu já estou de saída. 
 [Cair fora e tentar andar despreocupadamente.]}
 
# My name's 
{423}{}{Meu nome é }

# . Where am I?
{424}{}{. Onde eu estou?}

# No, what's *your* name, soldier? I was put here to test you and I gotta say you FAILED. If I were a wasteland
 suicide assassin you and your whole crew would be dead right now! That is unacceptable! Shape up, soldier!
{425}{}{Não, qual é *seu* nome, soldado? Eu fui colocado aqui para te testar e você FALHOU. Se eu fosse um assassino
 suicida dos desertos, você e toda a tripulação estariam mortos agora! Isso é inaceitável! Em forma, soldado!}
 
# Uh . . . my name 
{426}{}{Uh... meu nome }

# . I take fun ride in metal birdie! Go again! Wanna go again!
{427}{}{. Mim divertir em pássaro de metal! Vamos de novo! Quero ir de novo!}

# You not need know my name. I no like you. I kill. [Jump out and start fighting.]
{428}{}{Você não precisar saber nome. Mim não gostar você. Mim mata. [Pular fora e começar a lutar.]}

# What are you, drunk? You're at Navarro, of course. If you're having memory problems, soldier, you might wanna go get yourself checked out. Maybe some of that radiation out there got to you.
{430}{}{Você esta bêbado, ou o quê? Você está em Navarro, lógico. Se estiver com problemas de memória, soldado, você deveria fazer um check-up. Talvez você tenha sido pego pela radiação.}

# Don't give me that bullshit. You're one of the new recruits, aren't you? Heh. That smart mouth of yours is gonna land you in all sorts of trouble--and I can't wait to see it happen. Now get back to your post, soldier.
{440}{}{Não me venha com esse papo furado. Você é um dos novos recrutas, não é? Heh. Bancar o espertinho aqui vai lhe trazer todo tipo de problema --e eu mal posso esperar por isso. Agora volte ao seu posto, soldado.}
# Sir! Yes sir!
{450}{}{Sim senhor! Senhor!}

# Ma'am! Yes ma'am!
{451}{}{Sim senhora! Senhora!}

#dumb player wearing power armor
# [The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made him retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bastard out of his misery before he contaminates us.
{460}{}{[O soldado olha para um de seus companheiros.] Meu Deus, o contato com tantos mutantes e radiação lá fora o fizeram ficar retardado. Tá vendo? *Por isso* que eu nunca me voluntariei para essas missões no deserto. Enfim, vamos acabar com o sofrimento desse desgraçado antes dele nos contaminar.}

# [The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made her retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bitch out of her misery before she contaminates us.
{461}{}{[O soldado olha para um de seus companheiros.] Meu Deus, o contato com tantos mutantes e radiação lá fora a fizeram ficar retardada. Tá vendo? *Por isso* que eu nunca me voluntariei para essas missões no deserto. Enfim, vamos acabar com o sofrimento dessa vadia idiota antes dela nos contaminar.}