{100}{}{Você vê um homem de lata brilhante.}
{101}{}{Um soldado em uma power armor.}
{102}{}{Um soldado em um novo tipo de power armor, você acha.}

{103}{}{Dá pra acreditar? Fui mandado pra cozinha de novo!}#Can you believe it? I got KP duty again! KP:kitchen police
{104}{}{Word is the old man’s gonna issue leave to SF!}
{105}{}{Esperar uma porra. Por mim a gente explodia todos aqueles primitivos e acabava logo com isso.}
{106}{}{Tem fogo aí? Deixa pra lá. Já achei.}
{107}{}{Craps game behind the hanger tonight. Don’t let the CO know.}#CO=corrections office

{108}{}{Quem diab--? <zzzt> Nós temos um intruso aqui!}
{109}{}{Você aí! Alto!}
{110}{}{Intruso na base!}

{111}{}{Espere, você—ah, deixa pra lá. }
{112}{}{Olha, é melhor você pegar sua identidade. Esses alarmes falsos deixam todo mundo assustado.}
{113}{}{Você deveria estar aqui, certo? Esses alarmes falsos mexem com meus nervos!}

{114}{}{Intruso bem ali! Peguem!}
{115}{}{Aí está o intruso!}
{116}{}{Bem aqui! Não deixem que escapem!}

{117}{}{Nós estamos sob ataque na dianteira. Mandem reforços!}
{118}{}{Não deixem o intruso alcançar o portão!}
{119}{}{Morra, primitivo!}