{100}{}{Você vê um cão-cibernético.}
{101}{}{Você vê K-9.}
{102}{}{Você vê um cão-cibernético. Ele é parte máquina e parte cachorro.}
{103}{}{As funções vitais de meu mestre terminaram. Você é o meu novo mestre?}
{104}{}{Hã... cachorrinho fala?}
{105}{}{Certo. Mim gosta do cachorrinho.}
{106}{}{Não. Não quer cachorrinho.}
{107}{}{Ha! Um cachorro falante.}
{108}{}{Um; Eu sou um cão. Dois; Eu estou me comunicando com você vocalmente usando a
 língua Portuguesa. Portanto é seguro assumir que a resposta para a sua pergunta
 é 'sim, o cachorrinho fala.' Agora, você pretende responder a pergunta que eu lhe fiz
 momentos atrás?}
{109}{}{Um; Eu sou um cão. Dois; Eu estou me comunicando com você vocalmente usando a
 língua Portuguesa. Portanto é seguro assumir que eu sou um cachorro falante. Agora, você
 pretende responder a pergunta que lhe viz momentos atrás?}
{110}{}{Desculpe, mim esqueceu a pergunta.}
{111}{}{Sim.}
{112}{}{Não.}
{113}{}{(suspiro) Preste atenção. Concentre-se. Olhe nos meu olhos. Agora, está preparado?}
{114}{}{Preparado o quê?}
{115}{}{Sim. Mim preparado.}
{116}{}{Eu... se não fosse o fato do seu QI ser menor que a minha altura medida
 em 'pés' eu poderia pensar que você está tentando me irritar. Agora, faça silêncio. Preste
 atenção. Concetre-se. Olhe nos meus olhos. Estou prestes a te fazer um pergunta.}
{117}{}{Então vá em frente. Que impedir você?}
{118}{}{As funções vitais do meu mestre terminaram. Você é meu novo mestre?}
{119}{}{Hã... cachorrinho fala?}
{120}{}{Sim. Mim quer cachorrinho.}
{121}{}{Não, valeu.}
{122}{}{Parece bom.}
{123}{}{Não, valeu.}
{124}{}{Eu... eu me recuso a continuar nisso com você por uma segunda vez! Se eu
 fosse capaz de me movimentar eu morderia sua parte carnosa da sua
 região anterior, comumente chamada de...}
{125}{}{Bum-bum. Mim saber o que ser bum-bum. Mim não ser burro. Mim só brincando com você.}
{126}{}{Ah, uma piada. Rá rá rá. Agora, você é meu novo mestre ou não?}
{127}{}{Certo. Mim gostar cachorrinho.}
{128}{}{Não. Não querer cachorrinho.}
{129}{}{Excelente. Eu preciso de reparos, mestre. Minha unidade de locomoção foi
 removida. Ache-a, recoloque-a e eu me juntarei a você.}
{130}{}{Hã... Onde eu achar?}
{131}{}{Alguma idéia de onde eu poderia achar essa parte?}
{132}{}{Não tenho certeza, mestre. Eu tentaria a manutenção. Subindo as escadas, vá
 ao nordeste da base.}
{133}{}{Certo. Mim ir.}
{134}{}{Vou tentar lá. Se eu não encontrar lá, vou procurar por aí.}
{135}{}{Então me deixe em paz.}
{136}{}{Certo.}
{137}{}{Tudo bem.}
{138}{}{Olá de novo. As funções vitais do meu mestre terminaram. Você
 é meu novo mestre?}
{139}{}{Certo.}
{140}{}{Não.}
{141}{}{Tudo bem.}
{142}{}{Não, valeu.}
{143}{}{Você não é meu mestre. Eu não posso falar com você. Tchau.}
{144}{}{Certo.}
{145}{}{Olá, mestre. Você encontrou minha unidade de locomoção?}
{146}{}{Não, mim procurar mais.}
{147}{}{Sim. Mim encontrou.}
{148}{}{Não, ainda estou procurando por ela.}
{149}{}{Estou com ela bem aqui.}
{150}{}{Eu vou esperar o seu retorno, mestre.}
{151}{}{Certo.}
{152}{}{Então por favor, instale a peça, mestre! Por favor, mestre!}
{153}{}{Certo. Se acalme.}
{154}{}{Parece que estou em funcionnamento total, mestre. Devo me juntar a você?}
{155}{}{Não é aí que a peça vai, mestre. Tem certeza do que está
 fazendo?}
{156}{}{Certo. Cachorrinho vem comigo.}
{157}{}{Mim sabe o que está fazendo! Mim tentar de novo.}
{158}{}{Sim, vamos embora.}
{159}{}{Ei, eu já vonsertei coisas mais complexas do que a sua boca resmunguenta e sarnenta. Fique
 quieto que eu vou tentar de novo.}
{160}{}{Vá embora. Eu não o quero como mestre.}
{161}{}{Deixe-me em paz.}
{162}{}{Eu não gosto de você. Vá embora.}
{163}{}{Eu vou exterminar você.}
{164}{}{Posicionando armas no alvo. Preparar para morder.}
{165}{}{Você vai ser destruído.}

{166}{}{Sim, mestre?}
{167}{}{Você curar você mesmo.}
{168}{}{Esperar aqui. Eu voltar e te pegar depois.}
{169}{}{Hã... guarde sua arma. Certo?}
{170}{}{Ficar por perto.}
{171}{}{Não vai muito longe.}
{172}{}{Você muito perto. Afastar um pouco.}
{173}{}{Nós ir agora.}
{174}{}{Mim terminou.}
{175}{}{Você deve se curar agora.}
{176}{}{Eu preciso que você espere aqui até que eu volte.}
{177}{}{Guarde sua arma, certo?}
{178}{}{Fique perto de mim.}
{179}{}{Não vá muito longe.}
{180}{}{Nós devemos nos dispersar pouco.}
{181}{}{Vamos embora.}
{182}{}{É só isso por enquanto.}
{183}{}{Todos os sistemas estão funcionando na capacidade máxima, mestre.}
{184}{}{Meus sistemas estão funcionando próximos a capacidade máxima, mestre.}
{185}{}{Eu realizei os reparos que pude, mestre, mas vou precisar
 de assistência adicional.}
{186}{}{Eu realizei os reparos que pude, mestre, mas a falha no sistema
 persistirá sem assitência.}
{187}{}{Você esperar aqui. Eu voltar e pegar você.}
{188}{}{Hã... guarde sua arma. Certo?}
{189}{}{Ficar por perto.}
{190}{}{Não vai muito longe.}
{191}{}{Você muito perto. Afastar um pouco.}
{192}{}{Nós ir agora.}
{193}{}{Mim terminou.}
{194}{}{Eu preciso que você espere aqui até que eu volte.}
{195}{}{Guarde sua arma.}
{196}{}{Fique perto de mim.}
{197}{}{Não vá muito longe.}
{198}{}{Nós devemos nos dispersar um pouco.}
{199}{}{Vamos embora.}
{200}{}{É só isso por enquanto.}
{201}{}{Eu esperarei pelo seu retorno, mestre.}
{202}{}{Você curar você mesmo.}
{203}{}{Hã... guarde sua arma. Certo?}
{204}{}{Você ficar por perto.}
{205}{}{Você não ir muito longe.}
{206}{}{Você muito perto. Afastar um pouco.}
{207}{}{Nós ir agora.}
{208}{}{Mim terminou}
{209}{}{Você deve se curar agora.}
{210}{}{Guarde sua arma.}
{211}{}{Fique perto de mim.}
{212}{}{Não vá muito longe.}
{213}{}{Nós devemos nos dispersar um pouco.}
{214}{}{Vamos embora.}
{215}{}{É só isso por enquanto.}
{216}{}{Recolhendo arma, mestre.}
{217}{}{Você curar você mesmo.}
{218}{}{Você esperar aqui. Eu voltar e te pegar.}
{219}{}{Você ficar por perto.}
{220}{}{Você não ir muito longe.}
{221}{}{Você muito perto. Afastar um pouco.}
{222}{}{Nós ir agora.}
{223}{}{Mim terminou.}
{224}{}{Você deve se curar agora.}
{225}{}{Eu preciso que você espere aqui até que eu volte.}
{226}{}{Fique perto de mim.}
{227}{}{Não vá muito longe.}
{228}{}{Nós devemos nos dispersar um pouco.}
{229}{}{Vamos embora.}
{230}{}{É só isso por enquanto.}
{231}{}{Estreitando distância, mestre.}
{232}{}{Você curar você mesmo agora.}
{233}{}{Você esperar aqui. Mim voltar e te pegar.}
{234}{}{Hã... você guardar arma. Certo?}
{235}{}{Você não ir longe.}
{236}{}{Você muito perto. Afastar um pouco.}
{237}{}{Nós ir agora.}
{238}{}{Mim terminou.}
{239}{}{Você deve se curar agora.}
{240}{}{Eu preciso que você espere aqui até que eu volte.}
{241}{}{Guarde sua arma.}
{242}{}{Não vá muito longe.}
{243}{}{Nós devemos nos dispersar um pouco.}
{244}{}{Vamos embora.}
{245}{}{É só isso por enquanto.}
{246}{}{Aumentando distância, mestre.}
{247}{}{Você curar você mesmo agora.}
{248}{}{Você esperar aqui. Mim voltar e te pegar.}
{249}{}{Hã... você guardar arma. Certo?}
{250}{}{Você ficar por perto.}
{251}{}{Você muito perto. Afastar um pouco.}
{252}{}{Nós ir agora.}
{253}{}{Mim terminou.}
{254}{}{Você deve se curar agora.}
{255}{}{Eu preciso que você espere aqui até que eu volte.}
{256}{}{Guarde sua arma.}
{257}{}{Fique perto de mim.}
{258}{}{Nós deveríamos nos dispersar um pouco.}
{259}{}{Vamos embora.}
{260}{}{É só isso por enquanto.}
{261}{}{Aumentando distancia ao máximo, mestre.}
{262}{}{Você curar você mesmo agora.}
{263}{}{Você esperar aqui. Eu voltar e te pegar.}
{264}{}{Hã... você guardar sua arma. Certo?}
{265}{}{Você ficar perto.}
{266}{}{Você não ir longe.}
{267}{}{Nós ir agora.}
{268}{}{Mim terminou.}
{269}{}{Você deve se curar agora.}
{270}{}{Eu preciso que você espere aqui até que eu volte.}
{271}{}{Guarde sua arma.}
{272}{}{Fique perto de mim.}
{273}{}{Não vá muito longe.}
{274}{}{Vamos embora.}
{275}{}{É só isso por enquanto.}
{276}{}{Desculpe, mestre, mas parece que não há mais espaço para mim
 em seu grupo. Eu esperarei aqui até que haja uma vaga livre.}
{277}{}{Como desejar, mestre.}
{278}{}{Você curar você mesmo agora.}
{279}{}{Você esperar aqui. Mim voltar e te pegar.}
{280}{}{Hã... você guardar arma. Certo?}
{281}{}{Você ficar perto.}
{282}{}{Você não ir longe.}
{283}{}{Você muito perto. Afastar um pouco.}
{284}{}{Mim terminou.}
{285}{}{Você deveria se curar agora.}
{286}{}{Eu preciso que você espere aqui até que eu volte.}
{287}{}{Guarde sua arma.}
{288}{}{Fique perto de mim.}
{289}{}{Não vá muito longe.}
{290}{}{Nós devemos nos dispersar um pouco.}
{291}{}{É só isso por enquanto.}
{292}{}{Claro. Você parece ser um cachorro legal.}
{293}{}{Não, valeu.}

{300}{}{Mim triste. Mim não pode concertar.}
{301}{}{Desculpe, não consigo concertá-lo.}

{400}{}{Parece que você está sem um peça.}
{410}{}{Isso não fez nada.}#ESSA FRASE TEM QUE SER A PADRAO: THAT DOES NOTHING. SUBSTITUA PELA QUE VOCÊ ESTÁ USANDO. (that does nothing)
{420}{}{Isso não se encaixa.}#That does not fit.

{800}{}{Você concertou o K9.}

{1000}{}{Sim, mestre?}

{1100}{}{Todos os sistemas estão funcionando em capacidade máxima, mestre.}
{1200}{}{Meus sistemas estão funcionando em capácidade próxima à máxima, mestre.}
{1300}{}{Eu realizei os reparos que pude, mestre, mas vou precisar
 de assistência adicional.}
{1400}{}{Eu realizei os reparos que pude, mestre, mas a falha no sistema
 persistirá sem assistência.}

{1500}{}{Aguardarei o seu retorno, mestre.}

{1600}{}{Você espera que eu engula os meus dentes, mestre?}

{1700}{}{Eu o seguirei próximo aos seus pés, mestre.}
{1800}{}{Eu me movimentarei a uma distância média, mestre.}
{1900}{}{Eu me movimentarei a um boa distânica, mestre.}

{2000}{}{Desculpe-me, mestre, mas não parece que haja espaço para mim
 no seu gupo. Eu esperarei aqui até que haja um vaga livre.}
{2200}{}{Como desejar, mestre.}
{2300}{}{Eu tenho pele, mestre. Eu não posso carregar outro equipamento.}
{2400}{}{Eu não desejo remover minha pele, mestre.}
{2500}{}{Dentes, mestre. As coisa brancas e brilhantes instaladas em minha boca.}

{2700}{}{Você é mais cuzão que o Schreber. Eu não vou me juntar a você.}
{2800}{}{Muito bem, mestre. Estou ao seu comando.}
{2900}{}{Você é um cretino. Não vou a lugar algum com você. Vá embora.}