{100}{}{Você vê um mecânico.}
{101}{}{Você vê Kevin, o mecânico.}
{102}{}{Você vê um homem em uma farda militar. Julgando pelas manchas de graxa você acha que ele é mais
 um mecânico do que um soldado.}

{200}{}{Não posso falar agora. Vá ver o Quincy.}
{201}{}{Quincy é quem manda aqui. Fale com ele.}
{202}{}{Eu sou só um aprendiz de mecânico. Você deve falar com o Quincy.}

{300}{}{Você está sem a farda.}
{301}{}{É melhor você se vestir, soldado.}
{302}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{400}{}{Quem diabos são vocês... Alerta! Intrusos!}
{401}{}{Nós fomos infiltrados! Alerta!}
{402}{}{Múltiplos intrusos! Soem o alarme!}

{500}{}{Merda! Iniciem os backups.}
{501}{}{Desativem todas as operações secretas.}
{502}{}{Mantenham o sistema seguro e ativem todos os códigos de segurança.}

{600}{}{Eu sou um mecânico, não um lutador!}
{601}{}{Mirar a ponta com o diodo do laser no inimigo. Então, puxar o gatilho.}
{602}{}{Socorro! Socorro! Na manutenção!}