# Revisado por Noob-Saibot (1.0b)

{100}{}{Você vê uma pessoa vestindo uma power armor.}
{101}{}{Você vê o comandante de Navarro.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnea no peito que não é familiar pra você.}

{103}{}{Quem diabos são vocês..? Alerta! Intrusos na base!}
{104}{}{Eu não tenho tempo pra bater papo com soldados. Dispensado.}
{105}{}{Hora de morrer.}
{106}{}{Ok.}

{107}{}{Eu já disse que não tenho tempo pra você. Deixe este escritório e não volte a não ser que eu mande alguém te chamar. Dispensado!}
{108}{}{Desobedecer uma ordem direta de um superior é traição. Eu não tenho tempo pra Corte Marcial, então eu mesmo vou cuidar disso. Guardas! Matem esse idiota!}
{109}{}{Ok.}
{110}{}{Vai tomar no cu!}

{111}{}{O Fob está naquele armário bem ali. Diga ao oficial para me contactar assim que ele estiver seguro. Dispensado!}
{112}{}{Sim, senhor!}

{113}{}{Ande logo com isso soldado, eu não tenho o dia todo.}
{114}{}{Sim, senhor!}

{115}{}{Deixe o meu armário em paz ou eu te arrebento.}
{116}{}{Sim, senhor!}

{117}{}{Esta base está em alerta e eu não te reconheço. Mostre-me seus documentos, soldado.}
{118}{}{Que documentos?}
{119}{}{Ah, não fode!}
{120}{}{É que eu não estou com eles aqui...}
{121}{}{Documentos? Eu tenho os seus documentos bem aqui!}

{122}{}{Resposta errada, imbecil. Você deveria andar com seus documentos o tempo todo. Você deveria saber disso!}
{123}{}{Vai se fuder!}

{124}{}{Deixe o meu armário em paz ou eu te arrebento.}
{125}{}{Hora de morrer.}

#added by killap - RP
{200}{}{Ok, vamos acabar logo com isso-- Eu não gosto de mutantes fedorentos no meu escritório, e eu tô cheio de merdas pra resolver. 
Você trabalha pros Salvatores?} #Alright, let's get this over with--I don't like muties stinking up my office, and I got shit to do. Do you work for the Salvatores? 
{201}{}{Não é da tua conta, cuzão.} # None of your business, asshole.
{202}{}{Eu não trabalho pra ninguém.} # I work for no one.
{203}{}{E se eu trabalhar?} # So what if I do?
{204}{}{Sim, eu trabalho pros Salvatores.} # Yeah, I work for the Salvatores.
{205}{}{Antes de responder suas perguntas, eu tenho algumas pra fazer.} # Before I answer any questions, I've got a few of my own.

# None of your business, asshole
{210}{}{Eu não tenho tempo pra essa merda. Guardas! Matem este mutante!} # I don't have time for this bullshit. Guards! Kill this mutie!

#I work for no one
{220}{}{Então você está me dizendo que você não é nada mais que um rato do deserto que 
sem querer entrou em um de nossos vertibirds?} # So you're saying you're nothing more than a stray wasteland rat that happened to wander into one of our vertibirds?
{221}{}{Hm.. É, mais ou menos... Tirando a parte de ser um rato.} # Uh, yeah, pretty much . . . except for that part about me being a rat.
{222}{}{Exatamente isso.} # That's right.
{223}{}{Não, o que eu estou te dizendo é que isso foi tudo apenas um grande engano. Eu não sei quem vocês são
e não me importo. Então, se você não se incomoda, eu já estou indo...} # No, I'm saying that this is all just a big misunderstanding. I don't know who you guys are, and I don't care.  So if you don't mind, I'll be moving along now.
 
{230}{}{Bom, se você não trabalha pra ninguém, então não tenho que perder nem mais
um segundo com você. Guardas! Matem este mutante!} # Good, if you're acting alone, then I don't have to waste another second of my time with you. Guards! Kill this mutie!

{240}{}{Você não vai sair daqui vivo, mutante. Eu não posso arriscar que você conte a localização da base
pra todos os seus amiguinhos do deserto. Guardas! Matem esse mutante!} # You're not leaving here alive, mutant. I couldn't risk you blabbing the location of this base to all your wasteland friends, now could I? Guards! Kill this mutie!
 
# So what if I do?/ Yeah, I work for the Salvatores.
{250}{}{Me diz o que eu quero ouvir, e eu garanto que terá uma morte rápida e... relativamente tranquila. O Salvatore te enviou aqui?} #Tell me what I want to know, and I'll make sure your death is quick and . . . relatively painless. Did Salvatore put you up to this?
{251}{}{Hmmm.... não? Quero dizer, sim. Talvez.} # Uhh . . . no? Wait, yeah. Maybe.
{252}{}{Não. Brincar de pique-e-esconde na sua máquina voadora foi idéia minha mesmo. Genial, eu sei.} # Nope. Playing hide-and-seek in your flying machine was all my own idea. Genius, I know.
{253}{}{É, ele achou que seria bom me enviar junto pra fazer um agrado. Que bom negócio, hein?} # Yeah, he thought he'd sweeten the trade by sending me along. What a deal, huh?
{254}{}{Antes de responder essas perguntas, quero fazer algumas antes.} # Before I answer any questions, I've got a few of my own.

{260}{}{Eu não tenho tempo pra essa merda. Guardas! Matem este mutante!} # I don't have time for this bullshit. Guards! Kill this mutie!

{270}{}{Isso devia ser engraçado, mutante? Eu acho que vai ser muito mais engraçado pra mim
quando você for um corpo sangrando no chão. Guardas! Matem este mutante!} # That supposed to be funny, mutant? I think you'll be a lot funnier to me when you're a bleeding corpse. Guards! Kill this mutie!

{280}{}{Ah, você quer? [Ele ri.] Porra, porque não? Você vai morrer de qualquer jeito. O que você quer saber, mutante?} # Oh, you do? [He chuckles.] Well hell, why not? You're dying anyway. What do you want to know, mutant?
{281}{}{Porque você fica me chamando de mutante?} # Why do you keep calling me a mutant?
{282}{}{Quem diabos são vocês?} # Who the hell are you guys?
{283}{}{Onde eu estou?} # Where am I? 
{284}{}{Como eu posso conseguir uma armadura irada dessas?} # How can I get some of that sweet armor?
{285}{}{Eu já ouvi o bastante.} # I've heard enough.

{290}{}{Porque você É. Claro, você parece meio humano, mas não deixe que isso te engane.
 Você ainda é um mutante. Você e todos os que vivem no deserto. Todos infectados. Mais alguma pergunta?} # Because you ARE. Sure, you might look kinda human, but don't let that fool you. You're still a mutant. You and  everyone else on the mainland. All tainted. Next question?
{300}{}{Nós somos a Enclave - o último reduto de humanidade verdadeira nessa droga de planeta! Nós somos os únicos ainda carregando
a honra do velho vermelho, branco e azul. Isso mesmo, nós somos verdadeiros patriotas. Nós comemos águias e cagamos estrelas e
listras! Nós somos tudo o que restou do magnífico Estados Unidos da America. Mas nós somos o suficiente. Ah sim, nós somos mais que
o suficiente para colocar as coisas em seus devidos lugares. Você pode contar com isso, mutante. Mais alguma pergunta?} # We're the Enclave--the last bastion of true humanity on this damn planet. We're the only ones still upholding the honor of the ol' red, white, and blue. That's right, we're true patriots. We eat bald eagles and shit stars and stripes. We're all that's left of the great United States of America. But we're enough. Oh, yeah, we're enough to set things right. You can count on that, mutie. Next question?
{310}{}{Essa é Navarro, nossa base terrestre secreta. Nós estamos bem na costa da California e do oceano
pacífico. Mais alguma pergunta?} # This here's Navarro, our secret mainland base. We're sitting right on the coast of California and the pacific ocean. Next question?
{320}{}{Tirando do meu cadáver. Boa sorte com isso, mutante. Mais alguma pergunta?} # By prying it off my dead body. Good luck with that, mutie. Next question?
{330}{}{Ah, ótimo! Já estava de saco cheio de gastar minha saliva com a porra de um mutante! Na verdade, toda essa merda foi
uma enorme perda de tempo, porque eu não dou a porra de uma mínima pro que você tem a dizer. Guardas! Matem este mutante!} #Good, 'cause I'm damn tired of wasting my breath on a mutant. In fact, this whole things a waste of my time, because I don't give a flying fuck what you've got to say to me. Guards! Kill this mutie!