{100}{}{Você vê alguém em uma power armor. }
{101}{}{Você vê o comandante de Navarro.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnea no peito que não é familiar pra você.}

{103}{}{Quem diabos são vocês... Alerta! Intrusos na base!}
{104}{}{Eu não tenho tempo pra bater papo com soldados. Dispensado.}
{105}{}{Hora de morrer.}
{106}{}{Certo.}

{107}{}{Eu já disse que não tenho tempo pra você. Deixe este escritório e não volte a não ser que eu mande te chamar. Dispensado!}
{108}{}{Desobedecer uma ordem direta de um superior é traição. Eu não tenho tempo pra Corte Marcial, então eu mesmo vou cuidar disso. Guardas! Matem esse idiota!}
{109}{}{Certo.}
{110}{}{Vai te fuder!}

{111}{}{O Fob está naquele armário bem ali. Diga ao oficial para me contactar assim que ele estiver seguro. Dispensado!}
{112}{}{Sim, senhor!}

{113}{}{Ande logo com isso soldado, eu não tenho o dia todo.}
{114}{}{Sim, senhor!}

{115}{}{Deixe o meu armário em paz ou eu acabo com você.}
{116}{}{Sim, senhor!}

{117}{}{Esta base está em alerta e eu não te reconheço. Mostre-me seus documentos, soldado.}
{118}{}{Que documentos?}
{119}{}{You blow me!}
{120}{}{É que eu não estou com eles aqui...}
{121}{}{Documentos? Eu tenho os seus documentos bem aqui!}

{122}{}{Resposta errada, imbecil. Você deveria andar com seus documentos o tempo todo. Você deveria saber disso!}
{123}{}{Vai te fuder!}

{124}{}{Deixe o meu armário em paz ou eu acabo com você.}
{125}{}{Hora de morrer.}

#added by killap - RP
{200}{}{Alright, let's get this over with--I don't like muties stinking up my office, and I got shit to do. Do you work
 for the Salvatores? }
{201}{}{None of your business, asshole.}
{202}{}{I work for no one.}
{203}{}{So what if I do?}
{204}{}{Yeah, I work for the Salvatores.}
{205}{}{Before I answer any questions, I've got a few of my own.}

# None of your business, asshole
{210}{}{I don't have time for this bullshit. Guards! Kill this mutie!}

#I work for no one
{220}{}{So you're saying you're nothing more than a stray wasteland rat that happened to wander into one of our vertibirds?}
{221}{}{Uh, yeah, pretty much . . . except for that part about me being a rat.}
{222}{}{That's right.}
{223}{}{No, I'm saying that this is all just a big misunderstanding. I don't know who you guys are, and I don't care.
 So if you don't mind, I'll be moving along now.}
 
{230}{}{Good, if you're acting alone, then I don't have to waste another second of my time with you. Guards! Kill this mutie!}

{240}{}{You're not leaving here alive, mutant. I couldn't risk you blabbing the location of this base to all your
 wasteland friends, now could I? Guards! Kill this mutie!}
 
# So what if I do?/ Yeah, I work for the Salvatores.
{250}{}{Tell me what I want to know, and I'll make sure your death is quick and . . . relatively painless.
 Did Salvatore put you up to this?}
{251}{}{Uhh . . . no? Wait, yeah. Maybe.}
{252}{}{Nope. Playing hide-and-seek in your flying machine was all my own idea. Genius, I know.}
{253}{}{Yeah, he thought he'd sweeten the trade by sending me along. What a deal, huh?}
{254}{}{Before I answer any questions, I've got a few of my own.}

{260}{}{I don't have time for this bullshit. Guards! Kill this mutie!}

{270}{}{That supposed to be funny, mutant? I think you'll be a lot funnier to me when you're a bleeding corpse. Guards!
 Kill this mutie!}

{280}{}{Oh, you do? [He chuckles.] Well hell, why not? You're dying anyway. What do you want to know, mutant?}
{281}{}{Why do you keep calling me a mutant?}
{282}{}{Who the hell are you guys?}
{283}{}{Where am I? }
{284}{}{How can I get some of that sweet armor?}
{285}{}{I've heard enough.}

{290}{}{Because you ARE. Sure, you might look kinda human, but don't let that fool you. You're still a mutant. You and
 everyone else on the mainland. All tainted. Next question?}
{300}{}{We're the Enclave--the last bastion of true humanity on this damn planet. We're the only ones still upholding
 the honor of the ol' red, white, and blue. That's right, we're true patriots. We eat bald eagles and shit stars and
 stripes. We're all that's left of the great United States of America. But we're enough. Oh, yeah, we're enough to set
 things right. You can count on that, mutie. Next question?}
{310}{}{This here's Navarro, our secret mainland base. We're sitting right on the coast of California and the pacific
 ocean. Next question?}
{320}{}{By prying it off my dead body. Good luck with that, mutie. Next question?}
{330}{}{Good, 'cause I'm damn tired of wasting my breath on a mutant. In fact, this whole things a waste of my time,
 because I don't give a flying fuck what you've got to say to me. Guards! Kill this mutie!}