{100}{}{Você vê alguém em uma power armor. }
{101}{}{Você vê o comandante de Navarro.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnea no peito que não é familiar pra você.}

{103}{}{Quem diabos são vocês... Alerta! Intrusos na base!}
{104}{}{Eu não tenho tempo pra bater papo com soldados. Dispensado.}
{105}{}{Hora de morrer.}
{106}{}{Certo.}

{107}{}{Eu já disse que não tenho tempo pra você. Deixe este escritório e não volte a não ser que eu mande te chamar. Dispensado!}
{108}{}{Desobedecer uma ordem direta de um superior é traição. Eu não tenho tempo pra Corte Marcial, então eu mesmo vou cuidar disso. Guardas! Matem esse idiota!}
{109}{}{Certo.}
{110}{}{Vai te fuder!}

{111}{}{O Fob está naquele armário bem ali. Diga ao oficial para me contactar assim que ele estiver seguro. Dispensado!}
{112}{}{Sim, senhor!}

{113}{}{Ande logo com isso soldado, eu não tenho o dia todo.}
{114}{}{Sim, senhor!}

{115}{}{Deixe o meu armário em paz ou eu acabo com você.}
{116}{}{Sim, senhor!}

{117}{}{Esta base está em alerta e eu não te reconheço. Mostre-me seus documentos, soldado.}
{118}{}{Que documentos?}
{119}{}{You blow me!}
{120}{}{É que eu não estou com eles aqui...}
{121}{}{Documentos? Eu tenho os seus documentos bem aqui!}

{122}{}{Resposta errada, imbecil. Você deveria andar com seus documentos o tempo todo. Você deveria saber disso!}
{123}{}{Vai te fuder!}

{124}{}{Deixe o meu armário em paz ou eu acabo com você.}
{125}{}{Hora de morrer.}