{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em uma armadura de combate.}
{102}{}{Você vê alguém vestindo uma armadura de combate. Há uma insígnia no peito que não é familiar pra você.}

{103}{}{Nada a declarar.}
{104}{}{Não vi nada de errado, e você?}
{105}{}{Você não deveria estar no seu posto, soldado? Não é bom ficar andando por aqui.}

{106}{}{Você está sem a farda.}
{107}{}{É melhor você falar com o sargento e se vestir.}
{108}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Nós fomos descobertos! Alerta!}
{111}{}{Vários intrusos! Soem o alarme!}

{112}{}{Alerta de segurança! Fechem todas as saídas!}
{113}{}{Mantenham todas as áreas seguras! Estamos sob alerta!}
{114}{}{Alerta de intrusos! Código vermelho!}

{115}{}{Nós vamos acabar com você!}
{116}{}{A Enclave irá dominar o mundo!}
{117}{}{Você vai morrer para que a Enclave sobreviva!}

{118}{}{Desculpe, soldado. Esta área está fora dos limites para o pessoal da base. Tenho que pedir para você se retirar.}
{119}{}{O doutor quer que eu mate o D'claw. Ele não quer vir matar ele. }
{120}{}{Certo, mim vai.}
{121}{}{O doutor quer que eu mate a criatura pra ele. Ele não quer vir.}

{122}{}{Eu sabia que o desgraçado não teria as bolas pra fazer isso. Claro, não tem problema se um de nós se fuder. (suspiro) Tudo bem, entre. E boa sorte, soldado.}
{123}{}{Valeu.}

{124}{}{Por que está olhando pra mim desse jeito, soldado?}
{125}{}{Mim saber que você chamar Snookie. Bonitinho.}
{126}{}{Fiquei sabendo que você é chamada de Snookie. Eu acho muito bonitinho.}

{127}{}{O quê... ele te contou? Quando eu sair daqui eu acabo com ele...
 Andando, soldado. E tire esse sorriso da cara!}
{128}{}{Certo.}
