
{100}{}{Você vê um técnico.}
{101}{}{Você vê um técnico em computadores.}
{102}{}{Você vê alguém vestindo um jaleco de laboratório com o bolso cheio de canetas.}

{103}{}{Bom dia, soldado.}
{104}{}{Por favor, não toque em nada.}
{105}{}{Vocês soldados não deveriam vir aqui.}

{106}{}{Você está sem a farda. }
{107}{}{É melhor você se vestir. O depósito de armaduras fica no andar de baixo à esquerda.}
{108}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Nós fomos descobertos! Alerta!}
# Nós fomos infiltrados! Alerta!
{111}{}{Vários intrusos! Soem o alarme!}
# Múltiplos intrusos! Soem o alarme!

{112}{}{Merda! Iniciem os backups.}
{113}{}{Desativem todas as operações secretas.}
{114}{}{Mantenha o sistema seguro e ative todos os códigos de segurança.}

{115}{}{Eu sou um cientista, não um lutador!}
{116}{}{Mirar no inimigo com a ponto onde fica o diodo do laser. Então apertar o gatilho.}
{117}{}{Socorro! Socorro! Para o laboratório do computador!}