
{100}{}{Você vê alguém em uma power armor.}
{101}{}{Você vê o oficial de suprimentos.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnia no peito que não é familiar pra você.}
{103}{}{Quem diabos são você... Alerta! Intrusos na base!}
{104}{}{O quê... Acho que sei porque está aqui. Obviamente você quer se livrar desse modelo antigo que está vestindo.}
{105}{}{Porque está sem farda, soldado?}
{106}{}{Morra!}
{107}{}{Hã, é...}
{108}{}{Hã...}
{109}{}{Mim novo aqui.}
{110}{}{Mim não ser um dos seus soldados!}
{111}{}{Hã, bem...}
{112}{}{Eu sou novo aqui.}
{113}{}{Eu não sou um dos seus soldados!}

{114}{}{Hã, o quê? Não consegue pensar numa boa desculpa? Estou esperando, soldado!}
{115}{}{Mim ainda não receber farda.}
{116}{}{Eu ainda não recebi minha farda.}

{117}{}{Você é bem devagar, não? (suspiro) Bem, não é  sua culpa. Eu tenho um irmão igualzinho a você. Enfim, você é novo aqui? Eu não me lembro de ter te visto antes.}
{118}{}{Você é novo aqui? Eu não me lembro de ter te visto antes.}
{119}{}{Sim! Mim novo aqui!}
{120}{}{Sim, eu sou novo aqui.}

{121}{}{Bem, então você precisa dos seu equipamento padrão. Vá ao depósito de armas, vista-se e pegue sua arma. Você deve se apresentar ao Sargento depois disso.}
#Well, you'll need your standard issue, then.
{122}{}{Agradeço.}
{123}{}{Tudo bem. Agora saia daqui. Eu tenho trabalho a fazer e não quero ser perturbado.}

{124}{}{Estou ocupado agora. Volte mais tarde.}

{125}{}{Olá, recruta. Eu acabei de receber uma ligação do seu Sargento. Ele disso pra eu te vestir e te mandar de volta pra ele. Está correto?}
{126}{}{Sim.}

{127}{}{Esta base está sob alerta e eu não te reconheço. Mostre-me seus documentos, soldado.}
{128}{}{Mim não ter documentos comigo.}
{129}{}{Mim não precisa de documentos!}
{130}{}{Eu não estou com os meus documentos. Eles estão no meu armário.}
{131}{}{Documentos? Eu tenho os seus documentos bem aqui!}

{132}{}{Resposta errada. Você deveria andar com os seus documentos o tempo todo e deveria saber disso!}
{133}{}{Opa...}