
{100}{}{Um soldado vestindo uma farda militar.}
{101}{}{Alguns Pfc-Tech, tipo X.}

{102}{}{Ele está vestindo uma farda, mas está claro que esse cara é mais um técnico do que um soldado.}

{103}{}{Olha, quantas vezes eu vou ter que dizer pra você, imbecis? Não fiquem no caminho!}
{104}{}{Vocês não têm que atirar em alguma coisa agora?}
{105}{}{Saudações, soldado.}

{106}{}{Quem é você? Guardas!}
{107}{}{Que diabos é isso? Invasor na base!}
{108}{}{Merda! Onde está minha arma?}

{109}{}{Olha, eles já procuraram aqui e não acharam nada.}
{110}{}{Merda, esses alarmes falsos me fazem pular igual uma bichinha.}
{111}{}{Ótimo, outro alarme falso. Agora temos que desativar todo o sistema e colocar tudo no lugar de novo. }

{112}{}{Puta que pariu! Bem aqui! Um espião!}
{113}{}{Merda! É um ataque! Onde estão minhas coisas?}
{114}{}{Tiroteio? Ninguém disse que haveria um tiroteio!}

{115}{}{Quem diabos é você? Guardas!}
{116}{}{Você não é da Enclave! Guardas!}
{117}{}{Invasores! Sabotadores! Bem aqui!}

{118}{}{Ei, não avacalha com os planos. Estou trabalhando aqui.}
{119}{}{Onde diabos está aquela peça do gyrovator?}
{120}{}{Malditos pilotos, sempre quebrando minhas máquinas.}

{121}{}{Positivo, estou te vendo no monitor -— não me atrapalhe, estou trabalhando.}
{122}{}{Olha, chamadas pessoais não são permitidas, soldado.}
{123}{}{Desculpe, não posso ajudar agora.}

{124}{}{Você tem negócios por aqui? Se não, saia do meu caminho.}
{125}{}{Essa é uma área restrita, soldado.}
{126}{}{Cai fora do meu caminho, soldado.}

{127}{}{Puta merda! Que diabos está acontecendo lá em cima?}
{128}{}{Merda! Estão invadindo!}
#Shit! They've broken in!
{129}{}{Aqueles palhaços! Provavelmente é só mais um alarme falso.}