{100}{}{Saudações, humano. Eu sou o guerreiro Xarn. Você será meu executor?}
{101}{}{Sim.}
{102}{}{Não, mim aqui pra salvar você.}
{103}{}{Não sabe. Mim quer saber porque você ta aqui.}
{104}{}{Sim, eu sou.}
{105}{}{Não, eu estou aqui para salvá-lo.}
{106}{}{Eu não sei. Eu gostaria de saber porque você está aqui.}

{107}{}{Que assim seja. Eu não pretendo ficar quieto, humano. Vamos fazer dessa uma batalha a ser lembrada!}
{108}{}{Certo.}
{109}{}{Espera! Mim mudar idéia. Por que você aqui?}
{110}{}{Estou pronto. Vamos nessa.}
{111}{}{Espere um minuto! Por que você está aqui?}

{112}{}{Eu não creio que um soldado da Enclave esteja aqui para me salvar.
 Na verdade, você deve estar aqui para me dar esperanças para que você possa quebrá-las em pedaços mais tarde.}
{113}{}{Não. Mim aqui pra salvar. De verdade.}
{114}{}{Olhe, eu realmente estou aqui para resgatá-lo!}

{115}{}{Você é minha última esperança, então colocarei minha confiança em você. Aquela
 porta bem ali leva para uma tubulação de ar que sai na floresta.
 Eu consigo escalar a tubulação e ganhar minha liberdade. Entretanto,
 a porta está seguramente trancada e requer um cartão de acesso para abrir.
 Ache o cartão, abra a porta, e garanta minha liberdade.}
{116}{}{Certo, mim fazer.}
{117}{}{Mim pensar sobre isso.}
{118}{}{Claro, eu vou fazer isso.}
{119}{}{Vou pensar sobre isso.}

{120}{}{(Xarn te fita intensamente por um momento) Muito bem.
 A Enclave criou meu povo como uma raça de escravos guerreiros. Eles
 aumentaram nossa inteligência esperando que nós pudéssemos entender melhor seus
 comandos sem perceber nossa posição de escravos.
 Eles falharam; somos muito mais inteligentes do que eles suspeitam.}
{121}{}{Nós decidimos bancar os tolos até que pudéssemos ganhar nossa
 liberdade. Nossa chance chegou quando a Enclave decidiu nos testar
 fora de seu controle, aqui no continente. O Doutor Schreber
 quis se opôr a essa decisão, mas ele não foi escutado.}
{122}{}{Não aceitando a decisão da Enclave, ele escolheu o exílio,
 me capturou e vêm realizando experimentos para determinar minha
 verdadeira natureza. Ele obteve sucesso. Quando ele enviar suas descobertas
 para a Enclave meu povo será caçado e eliminado. Eu preciso
 escapar para alertar meu povo.}
{123}{}{(Xarn te fita intencionalmente por um momento) Eu não tenho nada
 a lhe dizer, humano. Eu posso sentir a escuridão da sua alma.}
{124}{}{Se o dotô ser ameaça por que você não mata ele?}
{125}{}{Foda-se você. Mim atirar no seu traseiro.}
{126}{}{Se esse cara é tão ameaçador, então por que você simplesmente não o mata?}
{127}{}{Azar o seu, então. Morra, deathclaw.}

{128}{}{(Suspiro) Recentemente eu comecei a considerar isso,
 mesmo não gostando de matar. Mas estou certo que o doutor
 percebeu, porque ele parou de me ver em pessoa. A escolha não
 é mais minha.}
{129}{}{Você não preocupar. Dotô morto. Ele não enviar relatório.}
{130}{}{Mim agradece você pela história.}
{131}{}{Você não tem com o que se preocupar. O doutor está morto e
 não irá enviar o relatório.}
{132}{}{Agradeço pela história.Foi muito interessante.}

{133}{}{Eu lamento saber da sua morte mas foi
 melhor assim. Eu gostaria de pedir sua ajuda para escapar
 desse lugar. Você me ajuda?}
{134}{}{Sim, mim ajuda.}
{135}{}{Mim pensar sobre isso.}
{136}{}{Não, mim não ajuda.}
{137}{}{Sim, eu vou ajudá-lo.}
{138}{}{Não, mas eu vou pensar sobre isso.}
{139}{}{Não, eu não irei ajudá-lo.}

{140}{}{Muito bem... eu esperarei aqui até que você tome sua decisão.}
{141}{}{Certo.}

{142}{}{Muito bem... eu fico triste com sua decisão mas a escolha
 é sua. Se mudar de idéia, estarei aqui.}
{143}{}{Tchau.}
{144}{}{Tchau.}

{145}{}{Eu gostaria de pedir sua ajuda para escapar
 desse lugar. Você me ajuda?}
{146}{}{Sim, mim ajudar.}
{147}{}{Mim pensar sobre isso.}
{148}{}{Não, mim não ajuda.}
{149}{}{Sim, eu vou ajudá-lo.}
{150}{}{Não, mas eu vou pensar sobre isso.}
{151}{}{Não, eu não irei ajudá-lo.}

{152}{}{Olá de novo. Está pronto pra nossa batalha?}
{153}{}{Não quer lutar, quer escutar sua história.}
{154}{}{Mim não quer lutar. Mim aqui pra ajudar.}
{155}{}{Não. Mim sair.}
{156}{}{Sim. Mim pronto.}
{157}{}{Eu não quero lutar. Posso ouvir sua história, ao invés disso?}
{158}{}{Estou aqui para resgatá-lo, não para lutar.}
{159}{}{Não. Eu saindo agora.}
{160}{}{Certo, vamos acabar logo com isso.}

{161}{}{Olá de novo. Mudou de idéia? Vai me ajudar?}
{162}{}{Sim.}
{163}{}{Não.}

{164}{}{Olá de novo. Mudou de idéia? Vai me ajudar?}
{165}{}{Sim.}
{166}{}{Não. Mim ainda pensar sobre.}
{167}{}{Não. Mim não ajuda.}
{168}{}{Não, ainda estou pensando nisso.}
{169}{}{Eu não quero ajudá-lo.}

{170}{}{Olá de novo. Você achou a chave pra porta?}
{171}{}{Sim, mim abrir pra você.}
{172}{}{Mim ainda procurando.}
{173}{}{Sim, eu achei. Vou abrir a porta pra você.}
{174}{}{Ainda estou procurando.}

{175}{}{Obrigado. Não irei me esquecer disso.}
{176}{}{De nada.}
{177}{}{De nada.}

{178}{}{Obrigado novamente. Tenho um débito com você que não pode ser pago.}

{179}{}{Saudações, humano. A base está em alerta geral. Você tem alguma chance de ser a causa?}
{180}{}{Olá de novo. A base está em alerta geral. Você é a causa?}
{181}{}{Sim, mim causa. Quem ser você, porque quer saber?}
{182}{}{Sim. Por quê?}

{183}{}{Eu sou Xarn, o guerreiro. Permita-me juntar-me a você e lutar do seu lado pela nossa liberdade. Juntos ainda temos uma chance; sozinhos... quem sabe?}
{184}{}{Então deixe-me juntar-me a você e lutar ao seu lado. Juntos
 podemos ser capazes de ganhar nossa liberdade; sozinhos... quem sabe?}
{185}{}{Antes de mim decidir você contar por que estar aqui?}
{186}{}{Hã... certo. Você ir comigo. Nós luta junto.}
{187}{}{Você se virar. Mim sair daqui.}
{188}{}{Antes que eu tome uma decisão gostaria de saber por que você está aqui.}
{189}{}{Certo. Estamos nessa juntos. Prepare suas garras e vamos nessa!}
{190}{}{Você está nessa sozinho, chapa. Eu vou dar o fora daqui.}

{191}{}{Hã... certo. Você ir comigo. Nós luta junto.}
{192}{}{Você se virar. Mim sair daqui}
{193}{}{Certo. Estamos nessa juntos. Prepare suas garras e vamos nessa!}
{194}{}{Você está nessa sozinho, chapa. Eu vou dar o fora daqui.}

{195}{}{Eu o agradeço, humano. Vamos chutar alguns traseiros da Enclave! Pack Gruthar! Grrrrrrrhh!}
{196}{}{Certo.}

{200}{}{[Mais]}
{201}{}{Sim. Quem é você?}
{202}{}{Sim. Por quê?}
{300}{}{Muito bem. A Enclave criou meu povo como uma raça de escravos guerreiros. Eles
 aumentaram nossa inteligência esperando que nós pudéssemos entender melhor seus
 comandos sem perceber nossa posição de escravos.
 Eles falharam; somos muito mais inteligentes do que eles suspeitam.}
{301}{}{Nós decidimos bancar os tolos até que pudéssemos ganhar nossa
 liberdade. Nossa chance chegou quando a Enclave decidiu nos testar
 fora de seu controle, aqui no continente. O Doutor Schreber
 quis se opôr a essa decisão, mas ele não foi escutado.}
{302}{}{Não aceitando a decisão da Enclave, ele escolheu o exílio,
 me capturou e vêm realizando experimentos para determinar minha
 verdadeira natureza. Ele obteve sucesso. Quando ele enviar suas descobertas
 para a Enclave meu povo será caçado e eliminado. Eu preciso
 escapar para alertar meu povo.}

{500}{}{Você é realmente sagaz. Talvez possamos nos encontrar novamente em tempos de paz.
 Eu preciso ir agora para preparar meu povo pra guerra.}#You are a true Pack brother
{501}{}{Vou arrancar os seus membros e então te quebrar com eles.}
{502}{}{Morra, humano traiçoeiro!}
{503}{}{Isso vai doer mais em você do que em mim.}

{600}{}{Juntos iremos esmagar nossos inimigos.}
{601}{}{Você os enfileira e eu os jogo no chão.}
{602}{}{Hora pra uma boa cabeçada.}

{700}{}{Você vê um deathclaw. Ele olha pra você com bastante inteligência nos olhos.}
{701}{}{Você vê o Xarn, um deathclaw.}
{702}{}{Você vê um típico deathclaw. A criatura é enorme, com um corpo poderoso, dentes afiados e longas garras.}

{800}{}{Você matou o Xarn.}
{810}{}{Você libertou o Xarn.}
{820}{}{Você se juntou ao Xarn.}
