# 0. Look
{100}{}{Você vê Lara.}

{150}{}{Ela é a líder desta gangue.}
# She's the leader of this gang.

# 1. Start (From Where to go)
{200}{}{Meu nome é Lara. Sou a líder desta gangue. Espero que não tenha vindo aqui pra causar confusão ou você vai ter bastante prejuízo.}
# The name's Lara; I run this gang. You better not be here to cause trouble or
# you're in for a world of hurt.
## Meu nome é Lara. Sou a líder desta gangue. Espero que não tenha vindo aqui pra causar confusão ou vai se arrepender. << minha tradução
{201}{}{Oi de novo. Precisa de alguma coisa?}
# Hi again. Need something?
## Olá. Precisa de alguma coisa?
{202}{}{Tem algum trabalho aí?}
# Got any work?
## Tem algum trabalho?
{203}{}{Estou só dando uma olhada.}
# Just looking around.
## Só tô dando uma olhada.
{204}{}{Estou a procura de um comerciante chamado Vic.}
# I'm looking for a merchant named Vic.
## Tô procurando um comerciante chamado Vic.
{205}{}{Aruh.}
{206}{}{Rara.}

# 2. Dumb, bye (From 1, 26)
{220}{}{Não temos nenhum médico aqui na cidade e eu não posso te ajudar.}
# We don't have any doctors in town and I can't help you.
{221}{}{Foi mal, mas não consigo te entender.}
# Sorry, I still don't understand.
{222}{}{Ack.}

# 3. Vic (From 1)
{230}{}{Pelo nome não me recordo. Mas também não tenho a lista de quem entra e sai da cidade. Veja com a Becky. Todo mundo acaba indo lá no salão dela. Ela deve saber.}
# The name doesn't ring a bell, but then again I don't keep track of who comes in and out of # #town. Check with Becky. Everyone ends up going through there. She might know.
## Esse nome não me parece familiar. E eu não tenho a lista de quem entra e sai da cidade. Veja com a Becky. Todo mundo acaba indo lá no bar dela. Ela deve saber.
{231}{}{Tem algum trabalho aí?}
# Got any work?
## Tem algum trabalho?
{232}{}{Valeu. tchau.}

# 4. Looking around (From 1)
{240}{}{Se não veio a Den por uma razão específica, é melhor ir embora. Ficar por aqui não é muito seguro.}
# If you didn't come to the Den for a specific reason you should probably leave. It's not #very safe around here.
## Se não veio fazer nada em Den, acho melhor ir embora. Aqui não é muito seguro.
{241}{}{Ah, tá bom.}
# Oh, okay.
{242}{}{Algum trabalho aí pra mim?}
# Got any work?
## Algum trabalho?
{243}{}{Sei cuidar bem do meu nariz.}
# I can handle myself.
## Sei me cuidar muito bem.
{244}{}{Tá bom. Valeu.}
# Okay, thanks.

# 5. Handle (From 4)
{250}{}{Sem dúvida. Senão não teria chegado até aqui vivo.}
# No doubt. Otherwise you probably wouldn't have made it here alive.
## Claro que sabe. Senão não ia ter chegado aqui vivo.
{251}{}{Ah, sim, eu soube. Você já disse.}
# Uh, yes, so I heard. You said that already.
{252}{}{Algum trabalho?}
# Got any work?
{253}{}{Tudo bem, valeu.}

# 6. Got work? (From 1, 3-5)
{260}{}{Depende da sua especialidade. Tem alguma coisa que está me deixando curiosa. Se você descobrir pra mim, te dou uma graninha.}
# Well it depends on what you're good at. There is something I'm curious about. If you # can find out, I'll pay you a bit.
## Isso depende do que você sabe fazer. Tem uma coisa que está me deixando curiosa. Se você descobrir pra mim, te dou uma graninha.
{261}{}{Como eu disse, estou querendo mais informações sobre uma certa coisa... ou lugar. Eu pagarei pela informação, é claro.}
# As I said, I'm looking for more information on a certain something… or someplace. I'll # pay of course.
{262}{}{Está bem. O que é?}
# Sure what's that?
## Tá bom. O que é?
{263}{}{Depois, quem sabe.}
# Maybe later.
## Quem sabe mais tarde.

# 7. Bye, let me know if mind changes (From 6)
{270}{}{Se mudar de idéia, me avise.}
# Let me know if you change your mind.
{271}{}{Pode deixar.}

# 8. Setting Crates (From 6)
{280}{}{Existe uma igreja do outro lado da cidade. Metzger colocou guardas para vigiar alguma coisa que tem lá dentro. Descubra o que é e eu te dou $200.}
# Well, there's a church east of here. Metzger has some people guarding whatever
# is inside. Find out what and I'll pay you $200.
{281}{}{Essa é mole. Eu já sei.}
# That was easy. I already know.
## Isso é fácil. Eu já sei.
{282}{}{Pode deixar.}
# Sure.
{283}{}{Vou ver o que posso fazer.}
# I'll see what I can do.

# 9. Thanks (From 8)
{290}{}{Valeu. Mas não arrume briga... por enquanto. Eu tenho um plano.}
# Thanks. Don't get in a fight… yet. I have a plan.
{291}{}{Sem problemas.}
{292}{}{Volto já.}
# I'll be right back.

# 10. Crates Answered (From 8)
{300}{}{O que é aquilo afinal?}
# What's that?
## O que tem lá na igreja?
{301}{}{Imensas caixas com compostos químicos em estado bruto.}
# Raw chemical compounds in large crates.
{302}{}{Grandes caixas com algum tipo de componente químico.}
# Big containers holding chemicals of some kind.
{303}{}{Vou lá dar uma olhada de novo.}
# Let me check again.

# 11. Crates Answered (From 10, 18)
{310}{}{Hmmm... faz sentido. Obrigada. Aqui tá sua grana.}
# That makes sense actually. Thanks. Here's your money.
{311}{}{Por que faz sentido?}
# Why is that?
{312}{}{Sem problemas. Tchau.}
# No problem. Bye.

# 12. Makes Sense? (From 11)
{320}{}{Tenho visto caravanas de Vault City chegando e algumas sendo compradas por caravanas de Nova Reno. }
# I've seen caravan's from Vault City come in and then some of it gets picked up by 
# caravans from New Reno.
{321}{}{Mesmo? E por que faz sentido?}
# So? Why does that make sense?
{322}{}{Oh.}

# 13. Makes Sense, Bye (From 12)
{340}{}{Nova Reno é a capital das drogas aqui das redondezas. Eles têm que comprar a matéria prima em algum lugar pra fazer as drogas, certo? E pelo visto eles estão comprando uma parte, ou tudo, de Vault City. }
# New Reno is the drug capital around here. They have to get the raw materials to make there # #drugs from somewhere, right? It seems like they're getting some, or all of it, from Vault City.
{341}{}{Onde fica Nova Reno?}
# Where's New Reno?
{342}{}{Tudo bem. Valeu.}

# 14. Located? (From 13)
{350}{}{Não sei ao certo. Acho que fica em algum canto ao sul daqui. Nunca estive lá, só vejo as caravanas por aqui de vez em quando - uma vez há um bom tempo.}
# Not sure exactly. Some where to the south I think. I've never been there, I just see their # # caravans stop buy once in a while - once in a long while.
## Não sei ao certo. Acho que fica em algum canto ao sul daqui. Nunca estive lá, só vejo as caravanas de lá para aqui para comprar algo de vez em quando - de muito em muito tempo.
{351}{}{Ah, tá. Valeu.}
# Oh, okay. Thanks.

# 15. (From 11-14)
{360}{}{Tá querendo ganhar uma grana fácil? $50. Dinheiro fácil.}
# You looking for some more quick and easy cash? $50. Easy money.
{361}{}{Claro que sim!}
# Sure.
{362}{}{Seja breve.}
# Make it quick.

# 16. Set Ask (From 15)
{370}{}{Preciso saber do Metzger se ele concorda do Tyler e eu resolvermos umas velhas pendengas. Ele sabe o que quero dizer.}
# I need you to check with Metzger to see if he'd be okay if Tyler and I settled some old # maters. He'll understand what I mean.
{371}{}{E por que você quer que eu pergunte?}
# Why do you want me to ask?
{372}{}{Se eu tiver oportunidade.}
# If I get a chance
{373}{}{Sem problemas.}
# Okay.

# 17. Why PC ask Metzger (From 16)
{380}{}{Por que não quero que o Tyler veja gente minha entrando e saindo da área do Metzger. Não quero dar bandeira.}
# Because I don't want Tyler to see any of my people going into or out of Metzger's place. # I don't want to tip our hand.
{381}{}{Você não entendeu. Se Tyler de repente me ver conversando com Metzger ele pode perceber alguma coisa.}
# Don't you get it. If Tyler sees me all of a sudden talking to Metzger he might catch wind of something fishy.
{382}{}{Vou ver o que posso fazer.}
# We'll see.
{383}{}{Tudo bem.}

# 18. On Crate Quest (From WTG)
{390}{}{Descobriu o que tem lá?}
# So did you find out what's in there?
{391}{}{Imensas caixas com compostos químicos em estado bruto.}
{392}{}{Grandes caixas com algum tipo de componente químico.}
{393}{}{Ainda não.}

# 19. Ask/Permission (From WTG)
{400}{}{Já falou com ele? O que ele disse?}
# So did you talk to him yet? What did he say?
{401}{}{Ele permitiu. Disse que se você vencer, o trabalho pode ser seu de volta, como antes.}
# He said yes. If you win, you can have their job, like before.
## Ele permitiu. Disse que se você vencer, você pode ter o seu trabalho de volta, como antes.
{402}{}{Na.}

# 20. Permission Done (From 19)
{410}{}{Que ótimo! Estava muito ansiosa por isso. Soube que Metzeger estava reclamando deles ultimamente. Aqui está sua grana.}
# Great. I was hoping as much. I hear he's been complaining about them lately. Here's your # # money.
{411}{}{Mais alguma coisa?}
# I assume there's something else now?
{412}{}{Valeu. Tchau.}

# 21. Wait, need info… (From 20)
{420}{}{Tenho mais um serviço pra você. Não sei como vai fazer isso, mas já que conseguiu entrar lá talvez eles confiem em você.}
# I have one more job for you. I'm not sure how you'll do it, but since you were able to # get inside maybe they trust you.
{421}{}{Eu entro às escondidas.}
# I snuck inside.
## Eu entrei escondido.
{422}{}{O que é?}
# What is it?

# 22. Snuck (From 21)
{430}{}{Tenho certeza que vai pensar em algum jeito.}
# I'm sure you can figure something out.
## Tenho certeza que você consegue pensar em alguma coisa.
{431}{}{Tá bom. Qual é o serviço?}
# Okay, what is it?

# 23. Setting Find (From 20-22)
{440}{}{Não podemos enfrentá-los agora. Eles têm mais grana e são em número um pouco maior. Se você conseguir descobrir algum ponto fraco que a gente possa usar pra equilibrar as vantagens ou alguma coisa que a gente possa aproveitar... }
# We can't take them at their present strength. They have extra funding
# and slightly out number us. If you can find some kind of weakness we could use
# to balance out the odds or something we can exploit...
{441}{}{Hein? Descobrir um ponto fraco? E como vou fazer isso?}
# Huh? Find a weakness? How am I supposed to do that?
{442}{}{Quanto?}
{443}{}{Considere o serviço feito.}
# Consider it done.

# 24. How Much? (From 23)
{450}{}{Vou te dar $150. Não tem como a gente chegar lá perto e descobrir por nós mesmos.}
# We'll give you $150. There's no way we can get close enough to find out by ourselves.
{451}{}{Se eu tiver tempo pra isso...}
# If I get around to it.
{452}{}{Tudo bem.}

# 25. Weakness??? (From 23)
{460}{}{Não sei! E é por isso mesmo que tô te pedindo pra ajudar.}
# I don't know. That's why I'm asking you to help.
{461}{}{Vou ver o que posso fazer.}
# I'll try.
{462}{}{Isso é inútil.}
# This is pointless.

# 26. Find/Weakness report (From WTG)
{470}{}{Descobriu alguma coisa?}
# Did you find anything?
{471}{}{Descobri sim. Vai rolar uma festa hoje a noite.}
# Yes. They're having a party tonight.
{472}{}{Ainda não. Quando souber, te falo.}
# Not yet. I'll let you know.
{473}{}{Gra.}
{474}{}{Na.}

# 27. Skeleton crew(From 4)
{480}{}{Excelente! Eles vão deixar pouca gente lá vigiando. Vai ser uma boa vantagem. Primeiro vamos atacar à igreja, depois damos um jeito nos da festa.}
# Excellent! They're sure to leave a skeleton crew. Those should be good
# odds. We'll take out those at the party after we hit the church.
{481}{}{E minha grana?}
# And my money?

# 28. Money ? (From WTG & 27)
{490}{}{Ainda não. Se quer sua grana, vai ter que vir conosco. Você não vai precisar lutar, mas é só pra termos certeza que não é uma armadilha. Nós te daremos $300 no total.}
# I don't think so. You'll have to come with us if you want your money. You
# won't have to fight but just to be sure it's not a trap. We'll give you $300 total.
{491}{}{Já se preparou?}
# You ready?
{492}{}{Okay, vamos!}
# Okay, let's do it.
{493}{}{Espere um pouco, estou me preparando.}
# Give me a bit to get ready.
{494}{}{De jeito nenhum. Pode ficar com a grana.}
# No way. Keep your money!

# 29. Wait to fight. (From 28, 30)
{500}{}{Tá bom, mas temos que agir rápido. Não demore ou vamos arruinar nossa chance. }
# Okay, but we've got to act soon so don't take to long or we'll ruin our chance.
{501}{}{Tudo bem.}

# 30. Coward (From WTG & 28)
{510}{}{Você não vai precisar lutar. É dinheiro fácil.}
# You don't have to fight. Easy money.
{511}{}{E aí, já mudou de idéia?}
# Well, have you changed your mind?
{512}{}{Vamos! Estou pronto.}
# Let's go. I'm ready.
{513}{}{Tá bom. Volto já.}
# Okay, I'll be right back.
{514}{}{Não.}
{515}{}{Uk}

# 31. CF: No Show (From WTG)
{520}{}{Por culpa sua perdemos nossa chance.}
# Because of you we blew our chance.
{521}{}{Covarde!}
# Coward!
{522}{}{Você não é nada.}
# You get nothing.
{523}{}{Provavelmente devia ser uma armadilha.}
# It was probably a trap anyhow.
{524}{}{Sinto muito, mas você não é confiável.}
# Sorry, you're not reliable.
{525}{}{Não posso confiar em você.}
# I can't trust you.

# 32. CF: 2 Won (From WTG)
{530}{}{Conseguimos!}
# We did it!
{531}{}{Valeu pela ajuda!}
# Thank you for your help.
{532}{}{Muito obrigada!}
# Special thanks to you!
{533}{}{Finalmente devolvi ao Tyler o que ele fez ao meu irmão.}
# I've finally paid Tyler back for what he did to my brother.
{534}{}{Obrigada de novo.}

# 33. CF: Metzger Dead (From WTG)
{540}{}{Com a morte de Metzger, não sei o que vai acontecer.}
# Now that's Metzger's dead, I don't know what'll happen.
{541}{}{Acho melhor a gente arrumar as malas.}
# Maybe we should just pack up.
{542}{}{Soube que o Metzger morreu? Não sei o que fazer agora.}
# Did you hear Metzger died? I don't know what to do now.
{543}{}{O que vai ser de Den agora? Talvez melhore alguma coisa.}
# What's going to happen to the Den now? Maybe something better.
{544}{}{Isso realmente pode ser melhor.}
# This could actually be for the better.

# 34. CF: Hostile (From WTG)
{550}{}{Filho da puta!}
{551}{}{Vai toma no cu!}

# 35. CF:  Reward (From WTG)
{560}{}{Valeu. Aqui está seu dinheiro e um brinde de $100.}
# Thanks. Here's your money and $100 extra.

# 36. Gang Dead (From WTG)
{570}{}{Você matou Tyler e a sua gangue? Como vamos provar nossa força ao Metzger? Agora ele nunca mais vai contratar a gente. Era a nossa única chance.}
# Did you kill Tyler and his guards? How are we supposed to prove ourselves to Metzger? # He'll never hire us now. That was our only chance.
{571}{}{Não temos trabalho aqui. Alguém exterminou os guardas de Metzger e agora ele não vai falar mais com a gente. Ele acha que foi a gente...}
# We don't have any work. Someone killed off Metzger's guards and now he won't talk to us. # He thinks we did it. Oh well.
{572}{}{Sinto muito.}
{573}{}{Que merda.}
# Too bad.
{574}{}{Fui eu, e você é a próxima.}
# That was me, and you're next.
{575}{}{É? Tudo bem, tchau.}
{576}{}{Uhr?}
{577}{}{Ug.}

# 37. Gang Dead Cont. (From 36)
{590}{}{Eu te falei pra irmos juntos. Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
# I told you we would go together. Since no one was there to watch the place, it got # ransacked and now Metzger's madder than hell.
{591}{}{Eu te falei pra achar um ponto fraco, não pra matar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
# I told you to find a weakness, not kill them! Since no one was there to watch the place, # it got ransacked and now Metzger's madder than hell.
{592}{}{Merda! Eu disse pra você falar com Metzger e não pra matar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
# Damn it! I told you to ask Metzger not to kill them! Since no one was there to watch the place, # it got ransacked and now Metzger's madder than hell.
{593}{}{Merda! Eu te disse pra não atacar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
# Damn it! I told you not to attack them! Since no one was there to watch the place, it got # ransacked and now Metzger's madder than hell.
{594}{}{Ah... é.. tenho que ir.}
# Oh, well, I've got to go.
{595}{}{Que vergonha!}
# That's a shame.
{596}{}{Você é a próxima, sua puta.}
# You're next, bitch.
{597}{}{Hmph!}
{598}{}{Você é a próxima.}
# You next.

# 38. CF: Next times Gang Dead (From WTG)
{610}{}{Você realmente sabe como fazer as coisas fracassarem, né?}
# You really know how to screw things up, don't you?
{611}{}{Não precisamos mais da sua ajuda.}
# We don't need any more of your help.
{612}{}{Vá incomodar outra pessoa.}
# Go bother someone else.
{613}{}{É melhor o Metzger não tirar nada da gente.}
# Metzger better not take anything out on us.
# Tomara que o Metzger não faça nada com a gente.
{614}{}{Sinto muito. Não posso te ajudar.}
# I'm sorry. I can't help you.
{615}{}{Não posso conversar. Estou tentando imaginar o que fazer agora.}
# Can't talk. I'm trying to figure out what to do now.
{616}{}{Tomara que Metzger não pense que estamos envolvidos nisso.}
# I hope Metzger doesn't think we were involved.
{617}{}{O que vamos fazer agora?}
# What are we going to do now?
{618}{}{É melhor sairmos fora... se o metzger pensar que matamos seus guardas... }
# We better leave soon in case Metzger thinks we killed his guards.
# É melhor irmos embora, no caso do Metzeger pensar que nós que matamos seus guardas. 
{619}{}{Já foi pra Nova Reno? Acho que vamos pra lá - ou pro norte.}
# You ever been to New Reno? Maybe we'll head there - or north.

# 39. Running to Fight
{650}{}{Vamos! Siguam-me!}
# Alright! Let's go! Everyone follow me!