{100}{}{Você vê Lara.}
{150}{}{Ela é a líder desta gangue.}
{200}{}{Meu nome é Lara. Sou a líder desta gangue. Espero que não tenha vindo aqui pra causar confusão ou vai se arrepender.}
{201}{}{Oi de novo. Precisa de alguma coisa?}
{202}{}{Tem algum trabalho?}
{203}{}{Só tô dando uma olhada.}
{204}{}{Tô procurando um comerciante chamado Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}
# 2. Dumb, bye (From 1, 26)
{220}{}{Não temos nenhum médico aqui na cidade e eu não posso te ajudar.}
{221}{}{Foi mal, mas não consigo te entender.}
{222}{}{Ack.}
# 3. Vic (From 1)
{230}{}{Esse nome não me parece familiar. E eu não tenho a lista de quem entra e sai da cidade. Veja com a Becky. Todo mundo acaba indo lá no bar dela. Ela deve saber.}
{231}{}{Tem algum trabalho?}

{232}{}{Valeu. tchau.}

# 4. Looking around (From 1)
{240}{}{Espero que tenha vindo em Den por um bom motivo, senão acho melhor ir embora. Aqui não é muito seguro.}

{241}{}{Ah, tá bom.}

{242}{}{Algum trabalho?}

{243}{}{Sei me cuidar muito bem.}

{244}{}{Tá bom. Valeu.}
# 5. Handle (From 4)
{250}{}{Sem dúvida. Senão não teria chegado até aqui vivo.}
{251}{}{Ah, sim, eu soube. Você já disse.}
{252}{}{Algum trabalho?}
{253}{}{Tudo bem, valeu.}
# 6. Got work? (From 1, 3-5)
{260}{}{Depende da sua especialidade. Tem alguma coisa que está me deixando curiosa. Se você descobrir pra mim, te dou uma graninha.}
{261}{}{Como eu disse, estou querendo mais informações sobre uma certa coisa... ou lugar. Eu pagarei pela informação, é claro.}
{262}{}{Está bem. O que é?}
{263}{}{Quem sabe mais tarde.}

# 7. Bye, let me know if mind changes (From 6)
{270}{}{Se mudar de idéia, me avise.}
{271}{}{Pode deixar.}

# 8. Setting Crates (From 6)
{280}{}{Existe uma igreja do outro lado da cidade. Metzger colocou guardas para vigiar alguma coisa que tem lá dentro. 
 Descubra o que é e eu te dou $200.}
{281}{}{Isso é fácil. Eu já sei.}
{282}{}{Pode deixar.}
{283}{}{Vou ver o que posso fazer.}
# 9. Thanks (From 8)
{290}{}{Valeu. Mas não arrume briga... por enquanto. Eu tenho um plano.}
{291}{}{Sem problemas.}
{292}{}{Eu voltarei logo.}
# 10. Crates Answered (From 8)
{300}{}{O que é aquilo afinal?}
{301}{}{Imensas caixas com compostos químicos em estado bruto.}
{302}{}{Grandes caixas com algum tipo de componente químico.}
{303}{}{Vou lá dar uma olhada de novo.}

# 11. Crates Answered (From 10, 18)
{310}{}{Hmmm... faz sentido. Obrigada. Aqui tá sua grana.}
{311}{}{Por que faz sentido?}
{312}{}{Sem problemas. Tchau.}

# 12. Makes Sense? (From 11)
{320}{}{Tenho visto caravanas de Vault City chegando e algumas sendo compradas por caravanas de Nova Reno.}
{321}{}{Mesmo? E por que faz sentido?}
{322}{}{Oh.}

# 13. Makes Sense, Bye (From 12)
{340}{}{Nova Reno é a capital das drogas aqui das redondezas. Eles têm que comprar a matéria prima em algum lugar pra fazer as drogas, certo? 
 E pelo visto eles estão comprando uma parte, ou tudo, de Vault City. }

{341}{}{Onde fica Nova Reno?}
{342}{}{Tudo bem. Valeu.}

# 14. Located? (From 13)
{350}{}{Não sei ao certo. Acho que fica em algum canto ao sul daqui. Nunca estive lá, só vejo as caravanas por aqui de vez em quando - de muito em muito tempo.}
{351}{}{Ah, tá. Valeu.}

# 15. (From 11-14)
{360}{}{Tá querendo ganhar uma grana fácil? $50. Dinheiro fácil.}
{361}{}{Claro que sim!}
{362}{}{Seja breve.}

# 16. Set Ask (From 15)
{370}{}{Preciso saber do Metzger se ele concorda do Tyler e eu resolvermos umas velhas pendengas. Ele sabe o que quero dizer.}

{371}{}{E por que você quer que eu pergunte?}
{372}{}{Se eu tiver oportunidade.}
{373}{}{Sem problemas.}

# 17. Why PC ask Metzger (From 16)
{380}{}{Por que não quero que o Tyler veja gente minha entrando e saindo da área do Metzger. Não quero dar bandeira.}
{381}{}{Você não entendeu. Se Tyler de repente me ver conversando com Metzger ele pode perceber alguma coisa.}
{382}{}{Vou ver o que posso fazer.}
{383}{}{Tudo bem.}

# 18. On Crate Quest (From WTG)
{390}{}{Descobriu o que tem lá?}
{391}{}{Grandes caixas com algum tipo de componente químico.}
{392}{}{Grandes caixas com algum tipo de componente químico.}
{393}{}{Ainda não.}

# 19. Ask/Permission (From WTG)
{400}{}{Já falou com ele? O que ele disse?}
{401}{}{Ele permitiu. Disse que se você vencer, você pode ter o seu trabalho de volta, como antes.}
{402}{}{Não.}

# 20. Permission Done (From 19)
{410}{}{Que ótimo! Estava muito ansiosa por isso. Soube que Metzeger estava reclamando deles ultimamente. Aqui está sua grana.}
{411}{}{Mais alguma coisa?}
{412}{}{Valeu. Tchau.}

# 21. Wait, need info… (From 20)
{420}{}{Tenho mais um serviço pra você. Não sei como vai fazer isso, mas já que conseguiu entrar lá talvez eles confiem em você.}

{421}{}{Eu entrei escondido.}
{422}{}{O que é?}

# 22. Snuck (From 21)
{430}{}{Tenho certeza que você consegue pensar em alguma coisa.}

{431}{}{Tá bom. Qual é o serviço?}

# 23. Setting Find (From 20-22)
{440}{}{Não podemos enfrentá-los agora. Eles têm mais grana e são em número um pouco maior. 
 Se você conseguir descobrir algum ponto fraco que a gente possa usar pra equilibrar as vantagens ou alguma coisa que a gente possa aproveitar...}

{441}{}{Hein? Descobrir um ponto fraco? E como vou fazer isso?}
{442}{}{Quanto?}
{443}{}{Considere o serviço feito.}

# 24. How Much? (From 23)
{450}{}{Vou te dar $150. Não tem como a gente chegar lá perto e descobrir por nós mesmos.}
{451}{}{Se eu tiver tempo pra isso...}
{452}{}{Tudo bem.}

# 25. Weakness??? (From 23)
{460}{}{Não sei! E é por isso mesmo que tô te pedindo pra ajudar.}

{461}{}{Vou ver o que posso fazer.}

{462}{}{Isso é inútil.}

# 26. Find/Weakness report (From WTG)
{470}{}{Descobriu alguma coisa?}
{471}{}{Descobri sim. Vai rolar uma festa hoje a noite.}
{472}{}{Ainda não. Quando souber, te falo.}
{473}{}{Gra.}
{474}{}{Na.}

# 27. Skeleton crew(From 4)
{480}{}{Excelente! Eles vão deixar pouca gente lá vigiando. Vai ser uma boa vantagem. 
 Primeiro vamos atacar à igreja, depois damos um jeito nos da festa.}

{481}{}{E minha grana?}

# 28. Money ? (From WTG & 27)
{490}{}{Ainda não. Se quer sua grana, vai ter que vir conosco. Você não vai precisar lutar, 
 mas é só pra termos certeza que não é uma armadilha. Nós te daremos $300 no total.}
{491}{}{Já se preparou?}
{492}{}{Okay, vamos!}
{493}{}{Espere um pouco, estou me preparando.}
{494}{}{De jeito nenhum. Pode ficar com a grana.}
# 29. Wait to fight. (From 28, 30)
{500}{}{Tá bom, mas temos que agir rápido. Não demore ou vamos arruinar nossa chance. }
{501}{}{Tudo bem.}
# 30. Coward (From WTG & 28)
{510}{}{Você não vai precisar lutar. É dinheiro fácil.}
{511}{}{E aí, já mudou de idéia?}
{512}{}{Vamos! Estou pronto.}
{513}{}{Ta bom. Volto já.}
{514}{}{Não.}
{515}{}{Uk}

# 31. CF: No Show (From WTG)
{520}{}{Por culpa sua perdemos nossa chance.}
{521}{}{Covarde!}
{522}{}{Você não é nada.}
{523}{}{Provavelmente devia ser uma armadilha.}
{524}{}{Sinto muito, mas você não é confiável.}
{525}{}{Não posso confiar em você.}

# 32. CF: 2 Won (From WTG)
{530}{}{Conseguimos!}
{531}{}{Valeu pela ajuda!}
{532}{}{Muito obrigada!}
{533}{}{Finalmente devolvi ao Tyler o que ele fez ao meu irmão.}
{534}{}{Obrigada de novo.}

# 33. CF: Metzger Dead (From WTG)
{540}{}{Com a morte de Metzger, não sei o que vai acontecer.}
{541}{}{Acho melhor a gente arrumar as malas.}
{542}{}{Soube que o Metzger morreu? Não sei o que fazer agora.}
{543}{}{O que vai ser de Den agora? Talvez melhore alguma coisa.}
{544}{}{Isso realmente pode ser melhor.}

# 34. CF: Hostile (From WTG)
{550}{}{Filho da puta!}
{551}{}{Vai toma no cu!}

# 35. CF:  Reward (From WTG)
{560}{}{Valeu. Aqui está seu dinheiro e um bônus de $100.}

# 36. Gang Dead (From WTG)
{570}{}{Você matou Tyler e a sua gangue? Como vamos provar nossa força ao Metzger? Agora ele nunca mais vai contratar a gente. Era a nossa única chance.}
{571}{}{Não temos trabalho aqui. Alguém exterminou os guardas de Metzger e agora ele não vai falar mais com a gente. Ele acha que foi a gente...}
{572}{}{Sinto muito.}
{573}{}{Que merda.}
{574}{}{Fui eu, e você é a próxima.}
{575}{}{É? Tudo bem, tchau.}
{576}{}{Uhr?}
{577}{}{Ug.}

# 37. Gang Dead Cont. (From 36)
{590}{}{Eu te falei pra irmos juntos. Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
{591}{}{Eu te falei pra achar um ponto fraco, não pra matar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
{592}{}{Merda! Eu disse pra você falar com Metzger e não pra matar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger tá muito puto.}
{593}{}{Merda! Eu te disse pra não atacar os caras! Como não tinha ninguém lá vigiando, saquearam tudo e agora Metzger ta muito puto.}
{594}{}{Ah... é.. tenho que ir.}
{595}{}{Que vergonha!}
{596}{}{Você é a próxima, sua puta.}
{597}{}{Hmph!}
{598}{}{Você é a próxima.}

# 38. CF: Next times Gang Dead (From WTG)
{610}{}{Você realmente sabe como fazer as coisas fracassarem, né?}
{611}{}{Não precisamos mais da sua ajuda.}
{612}{}{Vá incomodar outra pessoa.}
{613}{}{Tomara que o Metzger não faça nada com a gente.}
{614}{}{Sinto muito. Não posso te ajudar.}
{615}{}{Não posso conversar. Estou tentando imaginar o que fazer agora.}
{616}{}{Tomara que Metzger não pense que estamos envolvidos nisso.}
{617}{}{O que vamos fazer agora?}
{618}{}{É melhor irmos embora, no caso do Metzeger pensar que nós que matamos seus guardas.}
{619}{}{Já foi pra Nova Reno? Acho que vamos pra lá - ou pro norte.}
# 39. Running to Fight
{650}{}{Tudo bem! Vamos lá! Todo mundo me sigam!}
