{100}{}{Você vê um freguês.}
# You see bar patron.
{101}{}{Você vê Leanne.}
# You see Leanne.
{102}{}{Ela é muito bonita, mas parece estar perdida em pensamentos.}
# She's very beautiful, but seems to be lost in thought.
{103}{}{Pare com isso!}
# Stop it!
{104}{}{Por que você está fazendo isso?}
# Why are you doing this?
{105}{}{Me deixe sozinha!}
# Leave me alone!
{106}{}{Pare por favor!}
# Please stop!
{107}{}{Seu assassino!}
# You murderer!
{108}{}{Como você pôde fazer isso com a Beecky!}
# How could you do that to Becky!
{109}{}{O que ela fez para você?}
# What did she do to you?
{110}{}{Você vai apodrecer no inferno.}
# You'll rot in hell.
{111}{}{Desculpe, estou cansada de histórias.}
# Sorry, all out of stories.
{112}{}{Obrigada pela bebida.}
# Thanks for the drink.
{113}{}{É um prazer conversar com você.}
# Pleasure talking to you.
{114}{}{Obrigado por escutar.}
# Thanks for listening.
{115}{}{É bom te ver de novo.}
# Nice to see you again.
{116}{}{Boa viagem.}
# Safe travels.
{117}{}{Olá! Bom ver gente nova por aqui. Meu nome é Leanne. Como você está, quer se sentar?}
# Why hello! Nice to see a new face around here. My name's Leanne. How are you, care to sit down?
{118}{}{Olá de novo. Imagino que esteja bem?}
# Hello again. Doing well, I hope?
{119}{}{Então, me diga o que você sabe sobre o Mestre.}
# So, tell me what you know about the Master.
{120}{}{Ótimo. Como as coisas estão indo com você?}
# Great. How are things with you?
{121}{}{Muito bom.}
# Pretty good.
{122}{}{Não posso conversar no momento. Tchau.}
# Can't talk right now. Bye.
{123}{}{Igsby?}
# Igsby?
{124}{}{Bgy.}
# Bgy.

# Node005 removed.

{131}{}{Me desculpe. Eu não consigo entender. Talvez você não devesse beber tanto.}
# Oh, I'm sorry. I don't understand. Perhaps you shouldn't drink so much.
{132}{}{Ugra.}
# Ugra.
{133}{}{Fegi.}
# Fegi.
{134}{}{Muito bem. Obrigado por perguntar. Becky tem uma história de família interessante. Você tem uma?}
# Oh, very good. Thanks for asking. Becky has such an interesting family history. Do you have one yourself?
{135}{}{Estou bem, obrigado. Onde estávamos? Eu acho que você estava falando da história de sua família?}
# Still doing good, thanks. Now where were we? I think you were talking about your family history?
{136}{}{Sim. Eu sou o Chosen One. Meu ancestral salvou o mundo de um cara conhecido como o Mestre.}
# Yes. I am the Chosen One. My ancestor saved the world from one called the Master.
{137}{}{É. Meu ancestral supostamente salvou o mundo de um cara conhecido como o 'Mestre.'}
# Yeah. My ancestor supposedly saved the world from someone called the 'Master.'
{138}{}{Eu tenho que ir.}
# I've got to go.
{139}{}{Uh, tá bem. Prazer em conhecê-lo Chosen One... Na verdade. Eu já tinha escutado algo sobre um mestre antes...}
# Uh, okay. Nice to meet you Chosen One... Actually. I've heard something about a master before...
{140}{}{Que interessante. Isso me lembra uma história que eu escutei a muito tempo atrás. Algo sobre um mestre.}
# How interesting. That reminds me of a story I heard a long time ago. Something about a master.
{141}{}{Verdade? Como era?}
# Really? What was it?
{142}{}{Me conte.}
# Tell me.
{143}{}{Hum, então tá. Tchau.}
# Oh, okay. Bye.
{144}{}{Bem, isso pode demorar um pouco. Seja um cavalheiro e compre uma bebida pra mim, promete que não vai rir? Whisky não, uma Nuka-Cola por favor.}
# Well this might take a bit. Be a gentleman and buy me a drink, wouldn't you please? Not whiskey though, Nuka-Cola please.
{145}{}{Bem, isso pode demorar um pouco. Seja uma boneca e me compre uma bebida, promete que não vai rir? Whisky não, uma Nuka-Cola por favor.}
# Well this might take a bit. Be a doll and buy me a drink, wouldn't you please? Not whiskey though, Nuka-Cola please.
{146}{}{Nós já começamos? Agora eu tô me lembrando bem.}
# Shall we get started? I remember it quite well now.
{147}{}{Sim.}
# Sure.
{148}{}{Desculpe, eu não posso dispensar $5 no momento.}
# Sorry, I can't spare $5 right now.
{149}{}{Obrigado. Agora vamos ver... Eu lembro que minha mãe me contou sobre essa grande migração que aconteceu 70... ou foi 80 anos atrás...}
# Thanks. Now let's see... I remember my mom telling me about this huge migration that happened 70... or was it 80 years ago...
{150}{}{Por favor, continue.}
# Please, go on.
{151}{}{Mutantes realmente grandes com armas maiores que eu e você vieram do sul. Mamãe disse que parecia uma grande migração de algum tipo.}
# Really big mutants with weapons as tall as you and me came from the south. Mom said it looked like a big migration of some sort.
{152}{}{Tinha quantos mutantes?}
# How many?
{153}{}{Eu não sei, mas haviam muitos grupos deles. Alguns continuarão para o norte, outros foram para o lesta. Ninguém sabe para onde eles estavam indo.}
# Don't know, but there were multiple groups of them. Some would continue north, others headed east. No one knew where they were going.
{154}{}{Continue.}
# Go on.
{155}{}{Parecia que estavam assustado e fugindo de algo.}
# They were quite upset and seemed to be fleeing from something.
{156}{}{Sério?}
# Really?
{157}{}{Sério, tinha mais gente junto, vestidas com mantos roxo... eles não paravam de conversar sobre como o Mestre tinha morrido...}
# Yeah, there were also others in dirty, tattered purple robes... they kept babbling about how the Master was dead...
{158}{}{Interessante.}
# Interesting.
{159}{}{Alguns deles se mataram aqui na cidade!}
# Some of them even committed suicide right here in town!
{160}{}{Então?}
# So?
{161}{}{Bem, você não vê. Eles estavam falando do Mestre, aquele que seu ancestral matou.}
# Well don't you see. They were talking about the Master, the one your ancestor killed.
{162}{}{Obrigado pela história.}
# Thanks for the story.
{163}{}{Bem, está ficando tarde. Tchau.}
# Well, it's getting late. Bye.
{164}{}{Foi um prazer. Tchau.}
# My pleasure. Bye.
{165}{}{Tchau.}
# Bye.
{166}{}{Esquece.}
# Nevermind.
{167}{}{Leanne te contou a história dela sobre o Mestre.}
# Leanne told you her story about the Master.