{100}{}{Você vê um freguês.}
{101}{}{Você vê Leanne.}
{102}{}{Ela é muito bonita, mas parece estar perdida em pensamentos.}
{103}{}{Pare com isso!}
{104}{}{Por que você está fazendo isso?}
{105}{}{Me deixe sozinha!}
{106}{}{Pare por favor!}
{107}{}{Seu assassino!}
{108}{}{Como você pôde fazer isso com a Beecky!}
{109}{}{O que ela fez para você?}
{110}{}{Você vai apodrecer no inferno.}
{111}{}{Desculpe, estou cansada de histórias.}
{112}{}{Obrigada pela bebida.}
{113}{}{É um prazer conversar com você.}
{114}{}{Obrigado por escutar.}
{115}{}{É bom te ver de novo.}
{116}{}{Boa viagem.}
{117}{}{Olá! Bom ver gente nova por aqui. Meu nome é Leanne. Como você está, quer se sentar?}
{118}{}{Olá de novo. Imagino que esteja bem?}
{119}{}{Então, me diga o que você sabe sobre o Mestre.}
{120}{}{Ótimo. Como as coisas estão indo com você?}
{121}{}{Muito bom.}
{122}{}{Não posso conversar no momento. Tchau.}
{123}{}{Igsby?}
{124}{}{Bgy.}

# Node005 removed.

{131}{}{Me desculpe. Eu não consigo entender. Talvez você não devesse beber tanto.}
{132}{}{Ugra.}
{133}{}{Fegi.}
{134}{}{Muito bem. Obrigado por perguntar. Becky tem uma história de família interessante. Você tem uma?}
{135}{}{Estou bem, obrigado. Onde estávamos? Eu acho que você estava falando da história de sua família?}
{136}{}{Sim. Eu sou o Chosen One. Meu ancestral salvou o mundo de um cara conhecido como o Mestre.}
{137}{}{É. Meu ancestral supostamente salvou o mundo de um cara conhecido como o 'Mestre.'}
{138}{}{Eu tenho que ir.}
{139}{}{Uh, tá bem. Prazer em conhecê-lo Chosen One... Na verdade. Eu já tinha escutado algo sobre um mestre antes...}
{140}{}{Que interessante. Isso me lembra uma história que eu escutei a muito tempo atrás. Algo sobre um mestre.}
{141}{}{Verdade? Como era?}
{142}{}{Me conte.}
{143}{}{Hum, então ta. Tchau.}
{144}{}{Bem, isso pode demorar um pouco. Seja um cavalheiro e compre uma bebida pra mim, promete que não vai rir? Whisky não, uma Nuka-Cola por favor.}
{145}{}{Bem, isso pode demorar um pouco. Seja uma boneca e me compre uma bebida, promete que não vai rir? Whisky não, uma Nuka-Cola por favor.}
{146}{}{Nós já começamos? Agora eu tô me lembrando bem.}
{147}{}{Sim.}
{148}{}{Desculpe, eu não posso dispensar $5 no momento.}
{149}{}{Obrigado. Agora vamos ver... Eu lembro que minha mãe me contou sobre essa grande migração que aconteceu 70... ou foi 80 anos atrás...}
{150}{}{Por favor, continue.}
{151}{}{Mutantes realmente grandes com armas maiores que eu e você vieram do sul. Mamãe disse que parecia uma grande migração de algum tipo.}
{152}{}{Tinha quantos mutantes?}
{153}{}{Eu não sei, mas haviam muitos grupos deles. Alguns continuarão para o norte, outros foram para o lesta. Ninguém sabe para onde eles estavam indo.}
{154}{}{Continue.}
{155}{}{Parecia que estavam assustado e fugindo de algo.}
{156}{}{Sério?}
{157}{}{Sério, tinha mais gente junto, vestidas com mantos roxo... eles não paravam de conversar sobre como o Mestre tinha morrido...}
{158}{}{Interessante.}
{159}{}{Alguns deles se mataram aqui na cidade!}
{160}{}{Então?}
{161}{}{Bem, você não vê. Eles estavam falando do Mestre, aquele que seu ancestral matou.}
{162}{}{Obrigado pela história.}
{163}{}{Bem, está ficando tarde. Tchau.}
{164}{}{Foi um prazer. Tchau.}
{165}{}{Tchau.}
{166}{}{Esquece.}
{167}{}{Leanne te contou a história dela sobre o Mestre.}
