{100}{}{Esse é o dono da loja.}
{101}{}{Você vê Tubby.}
{150}{}{Esse é o dono da loja.}
{151}{}{Este é Tubby, o dono da loja.}
{152}{}{[CONVERSAR]}
{153}{}{Preferiria que você fizesse negócios em outro canto.}
{154}{}{Ah, você é um homem de negócios. Vamos negociar.}
{155}{}{Posso te fazer umas perguntas?}
{156}{}{Tchau.}
{157}{}{Estou muito feliz em te ver de novo. Em que posso te ajudar hoje?}
{158}{}{Vamos fazer negócios.}
{159}{}{Posso te fazer umas perguntas?}
{160}{}{Por enquanto nada. Tchau.}
{161}{}{Olá, senhor. Bem-vindo ao Tubby. Sou o dono da Loja. Em que posso ajudar?}
{162}{}{Sério?! Vamos fazer negócios.}
{163}{}{Preciso de informações.}
{164}{}{Até logo.}
{165}{}{Olá, madame. Meus amigos me chamam de Tubby. Bem vindo à minha loja. Pois não?}
{166}{}{Estou afim de comprar algumas coisas.}
{167}{}{Preciso de algumas informações.}
{168}{}{Até logo.}
{169}{}{Em vez disso, eu preferiria que você fosse embora daqui.}
{170}{}{Tchau.}
{171}{}{Sobre o que gostaria de saber?}
{172}{}{Quem está no comando desta cidade?}
{173}{}{Por que todo mundo tá vendendo drogas?}
{174}{}{Sabe onde fica o Vault?}
{175}{}{Queria fazer umas trocas.}
{176}{}{Deixa pra lá. Tchau.}
{177}{}{Meu Deus! Posso afirmar que temos um problema de comunicação. Por favor, balance a cabeça se quiser fazer negócios.}
{178}{}{[balançar a cabeça.]}
{179}{}{Tchauutchau.}
{180}{}{Ninguém, esse é meu medo. A cidade de Den é um lugar anárquico onde um tipo de luta darwiniana acontece. 
 Só os mais fortes, rápidos e inteligentes sobreviverão aqui. Tenho certeza que você vai encontrar seu nicho.}
{181}{}{Um, valeu.}
{182}{}{OK. As drogas são a base do sistema econômico desta cidade, assim como o ouro ou os grãos são para outras cidades. 
 Redding é outro belo exemplo de cidade abastecida de drogas. Aqueles malditos mineiros vivem doidões 
 para arrumar tempo de trabalhar de verdade. Nunca estive lá pessoalmente, mas sei que fica a dois dias daqui 
 seguindo na direção sudeste... se quiser ir lá dar uma olhada.}

{183}{}{Valeu.}
{184}{}{Já ouvi sobre um lugar chamado Vault City. Mas infelizmente não vou poder te apontar direções. 
 Muito poucos da cidade conseguimos bens que podem ser trocados pelos serviços médicos que eles fornecem, então a maioria de nós nunca esteve lá.}
{185}{}{OK. Valeu.}
{186}{}{Esse não é o tipo de informação que eu DOU pra qualquer um.}
{187}{}{$100 moedas te fariam mudar de idéia?}
{188}{}{O que acha de eu te dar $50 e você me contar?}
{189}{}{O que acha de ou me dar a informação ou eu te dou um buraco novinho em folha no meio da sua testa?}
{190}{}{Deixa pra lá.}
{191}{}{Posso te perguntar sobre outras coisas, então?}
{192}{}{Certo. Esse tipo de grana PODERIA me ajudar a mudar de idéia. Mas você não tem tanto dinheiro.}
{193}{}{Devo ter deixado em algum canto. Vou dar uma procurada.}
{194}{}{Acho que isso não vai ser suficiente.}

{500}{}{Certo Petey. Eu estarei aí em um segundo.}
{501}{}{Espere, Petey!}
{502}{}{To indo, tô indo.}
{510}{}{Aqui está, Petey.}
{511}{}{Você sabe, Petey, você deveria chutar essa merda.}
{512}{}{Pega essa merda e dá o fora daqui, Petey.}

#added by killap
{520}{}{Foi um prazer fazer negócio.} #Pleasure doing business.
