{100}{}{Esse é o dono da loja.}
# You see the shop owner.
# Você vê o dono da loja.
{101}{}{Você vê Tubby.}
# You see Tubby.

{150}{}{Esse é o dono da loja.}
# This is the store owner.
{151}{}{Este é Tubby, o dono da loja.}
# This is Tubby, the shop store owner.
{152}{}{[CONVERSAR]}
{153}{}{Preferiria que você fizesse negócios em outro canto.}
# I would prefer that you take your business elsewhere.
# Eu gostaria que você fizesse negócios em outro lugar
{154}{}{Ah, você é um homem de negócios. Vamos negociar.}
# You are a business man. Let's conduct business.
{155}{}{Posso te fazer umas perguntas?}
# Can I ask you something.
{156}{}{Tchau.}
{157}{}{Estou muito feliz em te ver de novo. Em que posso te ajudar hoje?}
# I am so happy to see you again. What can I do for you today?
{158}{}{Vamos fazer negócios.}
# Let's trade.
{159}{}{Posso te fazer umas perguntas?}
{160}{}{Por enquanto nada. Tchau.}
# Nothing for now. Bye.
{161}{}{Olá, senhor. Bem-vindo ao Tubby. Sou o dono da Loja. Em que posso ajudar?}
# Hello, sir, and welcome to Tubby's. I am the proprietor. May I help
 you?
{162}{}{Sério?! Vamos fazer negócios.}
# Yes, let's trade.
# Sim, vamos fazer negócios.
{163}{}{Preciso de informações.}
# I need some information.
{164}{}{Até logo.}
# Goodbye.
{165}{}{Olá, madame. Meus amigos me chamam de Tubby. Bem vindo à minha loja. Pois não?}
# Hello, madam. I am called Tubby by my friends, and I welcome you
 to my store. How may I help you?
# Olá, madame. Meus amigos me chamam de Tubby. Bem vindo à minha loja. Em que posso ajudar?
{166}{}{Estou afim de comprar algumas coisas.}
# I want to buy some things.
{167}{}{Preciso de algumas informações.}
# I need some information.
{168}{}{Até logo.}
{169}{}{Em vez disso, eu preferiria que você fosse embora daqui.}
# I would prefer that you leave, instead.
# Eu gostaria que você saísse daqui agora.
{170}{}{Tchau.}
{171}{}{Sobre o que gostaria de saber?}
# What would you like to know?
{172}{}{Quem está no comando desta cidade?}
# Who's in charge of this town?
{173}{}{Por que todo mundo tá vendendo drogas?}
# Why is everyone selling drugs?
{174}{}{Sabe onde fica o Vault?}
# Do you know where the Vault is located?
{175}{}{Queria fazer umas trocas.}
# I would like to barter after all.
{176}{}{Deixa pra lá. Tchau.}
# Never mind. Bye
{177}{}{Meu Deus! Posso afirmar que temos um problema de comunicação. Por favor, baçance a cabeça se quiser fazer negócios.}
# Oh my. I can tell we will have a communication problem. Please nod
 if you would like to trade any goods.
{178}{}{[balançar a cabeça.]}
# [Nod]
{179}{}{Tchauutchau.}
# Byebye.
# Tchauzinho
{180}{}{Ninguém, esse é meu medo. A cidade de Den é um lugar anárquico onde um tipo de luta darwiniana acontece. Só os mais fortes, rápidos e inteligentes sobreviverão aqui. Tenho certeza que você vai encontrar seu nicho.}
# No one, I'm afraid. The Den is an anarchistic place where a kind of Darwinian struggle is played out. Only the strongest, fastest or smartest will survive here. I’m sure you will find your niche.
# Ninguém, estou com medo. Den é um lugar anárquico onde um tipo de luta darwiniana acontece. Só os mais fortes, rápidos e inteligentes sobreviverem aqui. Tenho certeza que você vai encontrar seu lugar.
{181}{}{Um, valeu.}
# Um, thanks.
{182}{}{OK. As drogas são a base do sistema econômico desta cidade, assim como o ouro ou os grãos são para outras cidades. Redding é outro belo exemplo de cidade abastecida de drogas. Aqueles malditos mineiros vivem doidões para arrumar tempo de trabalhar de verdade. Nunca estive lá pessoalmente, mas sei que fica a dois dias daqui seguindo na direção sudeste... se quiser ir lá dar uma olhada.}
# OK. Drugs are the basis for this town's economic system, just as another town may use grain or gold. Redding is another prime example of a town fueled by drugs. Damn miners are too high all the time to get any real work done. I have never been there myself, but it is a couple days south-east of here if you want to check it out.
{183}{}{Valeu.}
{184}{}{Já ouvi sobre um lugar chamado Vault City. Mas infelizmente não vou poder te apontar direções. Muito poucos da cidade conseguimos bens que podem ser trocados pelos serviços médicos que eles fornecem, então a maioria de nós nunca esteve lá.}
# I have heard of a place called Vault City. But unfortunately, I can't help you with directions. You see, very few of us towns can offer acceptable exchange for the medical services they provide, so most of us have never been there.
{185}{}{OK. Valeu.}
{186}{}{Esse não é o tipo de informação que eu DOU pra qualquer um.}
# That's not the kind of information I would just GIVE away to anyone.
{187}{}{Cem moedas te fariam mudar de idéia?}
# Would a hundred bucks change your mind?
{188}{}{O que acha de eu te dar $50 e você me contar?}
# How about I give you $50 and you tell me.
{189}{}{O que acha de ou me dar a informação ou eu te dar um buraco novinho em folha no meio da sua testa?}
# What do you say you give me the information, or I give you a new hole
 in the head.
{190}{}{Deixa pra lá.}
# nevermind
{191}{}{Posso te perguntar sobre outras coisas, então?}
# Well, can I ask you something else, then?
{192}{}{Certo. Esse tipo de grana PODERIA me ajudar a mudar de idéia. Mas você não tem tanto dinheiro.}
# Sure, that kind of money MIGHT help me change my mind. But you ain't got
 it!
{193}{}{Devo ter deixado em algum canto. Vou dar uma procurada.}
# I must have dropped it somewhere. I'm gonna go look for it.
{194}{}{Acho que isso não vai ser suficiente.}
# I don't think that's going to be enough.

#tell petey to hold on messages
{500}{}{Certo Petey. Eu estarei aí em um segundo.}
# Sure Petey. I'll be there in a second.
{501}{}{Espere, Petey!}
# Hold on, Petey!
{502}{}{Tô indo, tô indo.}
# I'm comin', I'm comin'.

#sell petey drug messages
{510}{}{Aqui está, Petey.}
# Here you go, Petey.
{511}{}{Você sabe, Petey, você deveria chutar essa merda.}
# You know, Petey, you should kick this shit.
{512}{}{Pega essa merda e dá o fora daqui, Petey.}
# Take this and get the hell outta here, Petey.
