{100}{}{Um homem em uma power armor.}
{101}{}{Arthur, filho de Uther Pendragon.}
{102}{}{A braguilha dele está aberta.}
{103}{}{Saudações, viajantes. Meu nome é Arthur, filho de Uther Pendragon, da Brotherhood of Steel. Nós
 estamos em uma expedição em busca da Holy Hand Grenade of Antioch. Vistes a granada?}
{104}{}{Holy o quê de quem?}
{105}{}{Resposta do jogador}
{106}{}{Unga.}
{107}{}{Não há tempo para conversas. Nós estamos em uma expedição.}
{108}{}{Nós procuramos a Hand Grenade of Antioch.}
{109}{}{Para a Brotherhood of Steel!}
{110}{}{Hmm... Andorinha africana ou européia?}
{111}{}{Ei! Isso não é seu, é?}
{112}{}{Estou te alertando. Mantenha tuas mãos contigo.}
{113}{}{É isso. Já chega.}
{114}{}{A Holy Hand Grenade of Antioch? É apenas a mais poderosa granada de mão
 do seu tipo.}
{115}{}{Por que você procura por uma arma tão terrível?}
{116}{}{Nós da Brotherhood of Steel procuramos essa arma mais devastadora dos nossos ancestrais, afim de
 mantê-la segura daqueles que desejam abusar do poder da Holy Hand Grenade of Antioch.}
{117}{}{Por que?}
{118}{}{Bem... porque a Brotherhood of Steel se dedica a proteger os fracos e oprimidos, e
 essa coisa pode machucar alguém de verdade.}
{119}{}{Por que?}
{120}{}{Umm... porque é a única coisa moral a fazer.}
{121}{}{Por que?}
{122}{}{O qu... hum... Olha, nós estamos muito ocupados. Tu irás ajudar ou não? Viste
 a Holy Hand Grenade of Antioch ou não?}
{123}{}{Sim.}
{124}{}{Não.}
{125}{}{Bem, por que não disseste antes? Se disseres onde está, nós iremos e tu poderás
 voltar para seja lá o que estavas fazendo.}
{126}{}{[Você aponta para um direção qualquer]}
{127}{}{Certo, então. Obrigado pela ajuda. Isso é pelo distúrbio causado.}
{128}{}{Espere! Eu também estou em uma busca. Eu procuro pelo sagrado GECK. Você o viu?}
{129}{}{Bem, então não faz sentido continuar com essa conversa. Nós já vamos.}
{130}{}{[FIM]}
{131}{}{Sangrento camponês!}
{132}{}{[FIM]}
{133}{}{GECK, você quis dizer? Oh sim, nós temos dois deles. Não precisamos de mais um. Mas obrigado assim mesmo.}
{134}{}{Já que vocês tem dois dele, talvez pudessem me dar um.}
{135}{}{Não. Não. Não podemos. Não seria correto terminar a sua busca tão facilmente. Há mais deles
 naquela direção. Pega-os por ti mesmo. [Ele aponta para uma direção da mesma maneira que você, quando
 contou para ele onde estava a Holy Hand Grenade of Antioch]}
{136}{}{[FIM]}
{200}{}{Tu falas a língua do rei?}
{201}{}{Oláaaa!.}
{202}{}{Ei, estou bem aqui.}
{203}{}{Se puderes dar um pouco de teu tempo...}
{204}{}{Ahem.}
{205}{}{Ah, o que é isso. Não me ignores.}
{206}{}{Por favoooooor! Eu preciso perguntar algo importante.}
{207}{}{Bem, nós precisamos continuar a nossa busca pela Hand Grenade of Antioch. Vamos, Patsy.}

#added by killap - RP 1.3
{300}{}{Nossa busca foi cumprida!} #Our quest has been fulfilled!
{301}{}{Arthur, ao seu serviço.} #Arthur, at your service.
