{100}{}{Você vê um enorme monumento de pedra que parece estar... murmurando sozinho?}
{101}{}{Você vê um monumento de pedra da cabeça do Vault Dweller. É bem lisonjeante, embora
 você ache que a cabeça do Vault Dweller não seja realmente deste tamanho.}
{102}{}{Você vê um enorme monumento de pedra.}
{103}{}{Você vê um monumento de pedra da cabeça do Vault Dweller. É bem lisonjeante, embora
 você ache que a cabeça do Vault Dweller não seja realmente deste tamanho.}
{104}{}{Malditos turistas...}
{105}{}{"Eu sou o Chosen One." Que retardado.}
{106}{}{Se eu fosse você, "Chosen One", eu cairia o fora daqui.}
{107}{}{Zzzzzz Snzzzzz Zzzzzzzzzz}
{108}{}{ZZZZZZZzzzzzzzz}
{109}{}{Zsnzzz...*ronco*...zzzzsZZZZZ}
{110}{}{Zzssnnnnnzzzzz}
{111}{}{ZZZZzzzzzZZZZZ}
{112}{}{Eu queria poder ver o que está atrás de mim.}
{113}{}{Se pelo menos alguém viesse e cavasse o resto do meu corpo...}
{114}{}{Tenho certeza de que aquelas formigas comedoras de cabeça-de-pedra vão chegar a qualquer momento.}
{115}{}{"Seja uma grande cabeça de pedra! Veja o mundo!" Vá a merda...}
{116}{}{É um mistério pra mim como eu vim parar aqui no deserto.}
{117}{}{Eu ainda não sei por que tenho que ficar aqui no deserto enquanto aquela outra cabeças fica
 na vila.}
{118}{}{Quero dizer, ele recebe oferendas e é limpo e recebe orações... tudo o que eu ganho é ficar olhando pra areia o tempo todo.}
{119}{}{Já ouvi falar que as coisas são melhores na Ilha de Páscoa.}
#I hear those guys at Easter Island have it pretty good.
{120}{}{Aposto que a Stonehenge recebe mais visitantes do que eu.}
{121}{}{Hrnnfff...Hã-hã, mãe... não tem escola hoje... Zsnzzzzz}
{122}{}{Zzzsnnnzzzz... Eu não quero levantar ainda... Zzznnsss}
{123}{}{Zzsssccs... hein?}
{124}{}{O qu--?}
{125}{}{TIRE SUAS MALDITAS MÃOS DE CIMA DE MIM!}
{126}{}{Jogador deve virar, dar alguns passos para trás, em seguida, voltar-se e enfrentar o monumento.}
{127}{}{*Ahem*}
{128}{}{QUEM SE ATREVE A APROXIMAR DA SAGRADA CABEÇA DO VAULT DWELLER?!}
{129}{}{Sou eu, o Escolhido.}
{130}{}{HA HA HA HA HA HA!}
{131}{}{*VOCÊ*?! O ESCOLHIDO?!}
{132}{}{VOCÊ NÃO É MAIOR QUE O MEU DEDO!}
{133}{}{VOCÊ *NÃO* É O ESCOLHIDO.}
{134}{}{Sim, eu sou.}
{135}{}{NÃO, VOCÊ NÃO É.}
{136}{}{Sim, eu sou.}
{137}{}{HÃ-HÃ.}
{138}{}{Hã-ham.}
{139}{}{HÃ-HÃ.}
{140}{}{Hã-ham.}
{141}{}{HÃ... HÃ...}
{142}{}{Hã... ham...}
{143}{}{HÃ... JÁ CHEGA DISSO!}
{144}{}{MUITO BEM! VOCÊ PROVOU SER QUEM É!}
{145}{}{VOCÊ *É* CHOSEN ONE!}#o/a
{146}{}{TOME ISTO!}
{147}{}{AGORA ME DEIXE EM PAZ!}
{148}{}{Ei, valeu!}
{149}{}{É, É... AGORA CAI FORA.}
{150}{}{MALDITOS TURISTAS.}
{151}{}{EU JÁ TE DEI UM PRESENTE.}
{152}{}{SUMA!}
{153}{}{Idiota.}
{154}{}{O QUÊ?! VOCÊ VAI ME ROUBAR?!}
{155}{}{MORRA!}
{156}{}{Desintegrar-se com animação de morte plasma.}# acho que nao entra.
{200}{}{(12 horas depois)}
