{100}{}{Você vê um eremita.} #You see a hermit.
{101}{}{Você vê um eremita.}
{102}{}{É como se ele não toma banho a anos.} #It looks as if he hasn't washed in years.
{103}{}{Consegue adivinhar por que eu sou um eremita? [Parece que ele não fala com ninguém há anos.]} #Can guess you why I hermit? [It seems he hasn't spoken to anyone in years.]
{104}{}{Por quê?}
{105}{}{Estou só de passagem.}
{106}{}{Ug.}
{107}{}{Mim quer ficar sozinho.}
{108}{}{Aproveitando que estou aqui, talvez possamos trocar. Tenho certeza de que tenho algo que você pode querer.}
{109}{}{Então eu vou deixá-lo sozinho.}
{110}{}{Negociar. E em seguida, vou embora.}
{111}{}{OK, aqui está o que eu tenho para negociar.}
{112}{}{É melhor eu ir embora.}
{113}{}{Cai fora.}
{114}{}{Estou indo.}
{115}{}{Hmm ... Eu gostei de você. Nunca ouvi falar de você la fora. Fique, eu e você  podemos negociar.}
{116}{}{Ok}
{117}{}{Estou indo.}
{118}{}{A conversa foi agradável. Mas, estou cansado. Vá agora.}
{119}{}{[FIM]}
{120}{}{Conversar da dor de cabeça. Vá.}
{121}{}{Feito, vou falar com você.}
{122}{}{Sem conversa. Vá.}
{123}{}{Vá embora!}
{124}{}{Saia da casa!}
{125}{}{Como você ousa me atacar!}
{126}{}{Deixe-me sozinho.}
{127}{}{Eu vou.}
