{100}{}{Essa pessoa parece estar cambaleando vagarosamente.}
{101}{}{Você o barman da festa.}#bartender
{102}{}{Parece que ele está experimentando um pouco de sua mercadoria.}
{202}{}{Parece que ela está experimentando um pouco de sua própria mercadoria.}
{103}{}{O qu... o qu... 'que quiô poscho fazser por voschê. [Ic.]}
{104}{}{Nuka Cola [$6]}
{105}{}{Cerveja [$15]}
{106}{}{Booze [$30]}
{107}{}{Nada por hoje. Valeu.}
{108}{}{Ug.}
{109}{}{Ahhhh...voschê non gosxta de beber...that ain't no fun ta drinks. [Ele te entrega a bebida.]}#that ain't no fun ta drinks.??? sinceramente... nao entendi
{110}{}{[Fim]}
{111}{}{Aqui eshtá.  'Tá um poco quentche puquê non deu tempo pá gelá... É issho que dá vender as coisash rápido demaish...
 non gela direito. [está quente, é amarela é....]}
{112}{}{[Fim]}
{113}{}{[Você sente a parede do seu estômago dissolver quando toma um golão.]}
{114}{}{[Fim]}
{115}{}{Uooopa... [Ic] Eu ascho que voschê já bebeu o shufichiente.}
{116}{}{[Fim]}
{117}{}{Ahhh cara! 'chê non tem dinhêro sufsiciente! Volta quando 'schê tivé um poco.}#AHEUAEHUEA "sufsiciente!" foi foda... 
{118}{}{[Fim]}
{119}{}{Tem um pouco de olhar selvagem nele.}
{120}{}{Você vê um viciado.}
{121}{}{Ele parece um pouco nervoso.}
{122}{}{Oquêque'cêquer? Eutenhotudo!}#Whatdoyawant? Igotitall!
{123}{}{Mentats [$560]}
{124}{}{Buffout [$400]}
{125}{}{Psycho [$800]}
{126}{}{Nada por hoje. Obrigado.}
{127}{}{Ug.}
{128}{}{Esseébom! Medáodinheiroecaiforadaqui. Eutenhonegóciosafazer.}
{129}{}{[Fim]}
{130}{}{Écomodizem. Semdinheirosemmel. Ah. Issoéprasexo. Massemdinheironadafeito.
 Voltequandotiverumpoucomaisdegrana.}#Likethesayinggoes. Nomoneynohoney. Oh. Thatsforsex. Howaboutnodoughnoblow.
 Comebackwhenyougotsomecash
{131}{}{[Fim]}
{132}{}{Heheheh! Parecequevocêpodeusarumpoucodementats. Medê$1000.}
{133}{}{[Dar $1000 ao cara]}
{134}{}{Mim ir.}
{135}{}{ISSOAÍ! Issovaitedeixarnasalturas!}#OHYEAH! Thiswillpickyourightup!
{136}{}{[FIM]}

#Drunk: sets the sex flag
{150}{}{Ei, você é uma gracinha. Qual o seu nome?}
{151}{}{A'lil higher. Ohh, yeah.}#?
{152}{}{Você é demais... quer mandar ver?}
{153}{}{Naw..naw..naw..naw nuh naw.}
{154}{}{Watch like this. Yeah.}#?
#Drunk: the sex flag is set and you got some
{155}{}{Non agora, cai fora.}
{156}{}{Dexa eu bebê em paz.}
{157}{}{Vai transar... em outro lugar.}
#prop Drunk
{158}{}{Que tal eu e você sairmos da multidão?}
{159}{}{Hã, vamos nessa!}
{160}{}{Naa, bebi demais.}
{161}{}{[Arroto] ::sorriso::}

#Addict: set the sex flag
{170}{}{Ei, você quer ir pra trás daquele arbusto?}
{171}{}{Você já fez depois de usar drogas?}
{172}{}{Eu poderia te mostrar as estrelas, baby.}
{173}{}{Você sabe que eu quero amor.}
{174}{}{Estava torcendo pra encontrar alguém que queira mandar ver.}
#Addict: the set flag is set and you got some
{175}{}{Foi o suficiente pra mim.}
{176}{}{Ei, você tem um cigarro?}
{177}{}{Ei, não grude demais -- eu gosto da minha liberdade.}
#prop Addict
{178}{}{Você é selvagem como uma pantera e eu quero você.}
{179}{}{Quer ir agora?}
{180}{}{Não agora; eu tenho que "subir" primeiroo.}
{181}{}{Man the hatches. We're goin' in.}#?

{200}{}{Não seja idiota!}
{201}{}{Vai se divertir em outro lugar.}
{202}{}{Quem deixou você entrar?}

{203}{}{Isso não é legal!}
{204}{}{Relaxa, cara.}
{205}{}{Calma, cara!}