{100}{}{Um viajante.}
{101}{}{Saudações! Caro viajante.}
{102}{}{Eu preciso de direções. Você pode me ajudar?}
{103}{}{Pra onde está indo?}
{104}{}{O que você faz?}
{105}{}{Ug.}
{106}{}{Bem... eu não sei. Eu sou novo nessa área e só estive nestes locais.}
{107}{}{New Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{The Den}
{111}{}{San Francisco}
{112}{}{New California Republic}
{113}{}{Uma mina abandonada.}
{114}{}{Não, eu já estive lá. Valeu assim mesmo.}
{115}{}{New Reno -- esse é um ótimo lugar pra ir. Sexo, drogas e jogos. O que mais alguém pode querer?
 Aqui, deixe eu te mostrar onde fica.}
{116}{}{Valeu.}
{117}{}{Vault City -- uma cidade de imbecis. Se te crescer um dedo extra eles te tratam como um
 anormal. Nunca entrei lá, mas sei onde fica.}
{118}{}{Valeu.}
{119}{}{Redding... eu não sei muito sobre ela, a não ser que é uma velha cidade mineira. Se localiza ao norte,
 right smack dab in the middle of some of meanest mountains you've ever seen.}#essa última frase me pegou
{120}{}{Valeu.}
{121}{}{Eu ficaria longe de Den se fosse você. É um imã para as castas baixas da área. Eu vou te mostrar
 onde fica, mas não recomendo que vá pra lá.}
{122}{}{Valeu.}
{123}{}{San Francisco. Hum... tudo o que posso dizer é que as pessoas de lá são... estranhas. Ficava localizada na
 costa.}
{124}{}{Valeu.}
{125}{}{The New California Republic... esse é um bom lugar. Eu gostaria de me aquietar e viver lá
 algum dia. Limpo, boas pessoas, e muito bem estruturada. Fica bem aqui no seu mapa.}
{126}{}{Valeu.}
{127}{}{É, um tempo atrás eu cruzei com um acampamento de uma mina abandonada. Pensei que poderia descansar por lá por um ou dois dias,
 mas lobos começaram a aparecer e achei melhor sair. Uma vergonha, também; parecia que
 os mineiros saíram com pressa. Eles deixaram muita coisa pra trás. Não planejo voltar lá, então acho que
 não faz mal te mostrar onde fica.}
{128}{}{Valeu.}
{129}{}{Ah... não tem muita impotância. Eu só decidi viajar um dia e bem, aqui estou.}
{130}{}{Talvez você possa me ajudar. Eu preciso de direções.}
{131}{}{O que você faz?}
{132}{}{Foi bom falar com você.}
{133}{}{Eu faços bicos aqui e ali pra me sustentar. Mas na maior parte do tempo eu só viajo.}
{134}{}{Talvez você possa me ajudar. Eu preciso de direções.}
{135}{}{Pra onde está indo?}
{136}{}{Foi bom falar com você.}
{137}{}{Eu preciso ir agora. Foi bom falar com você.}
{138}{}{Talvez nos escontremos de novo.}
{139}{}{Quero chegar na próxima cidade ao amanhecer. Melhor partir.}
{140}{}{É melhor eu ir andando.}
{141}{}{Emboscada!}
{142}{}{Não se pode confiar em ninguém hoje em dia.}
{143}{}{Você quebrou o código do viajante.}
{144}{}{Hora de partir.}
{145}{}{I've overstayed my welcome.}#?
{146}{}{Eu preciso partir.}