{100}{}{Um vendedor.}
{101}{}{Willy.}
{102}{}{Um esperto vendedor viajando.}
{103}{}{Saudações, meu nome é Willy e eu tenho uma proposta pra você. [Ele parece estar lendo de uma
 carta, e após algum tempo você cochila.]}
{104}{}{Zzzzzzz...}
{105}{}{[Você abre os olhos groguemente quando percebe que alguém está te chutando.] Bem, você tem
 interesse ou não?}
{106}{}{Interesse em quê?}
{107}{}{Erg?}
{108}{}{Why, it slices it dices and it'll also come in handy against pesky critters. A bargain at any
 price, but for you it's on special for only }#não entendi o SLICES ITS DICES.
{109}{}{É feito da mais fina madeira por aqui. Use para bater em criaturas mantendo-as distantes ou
 se tiver habilidade, você pode lançar! É muito aerodinâmico e não quebra no impacto. O que me diz?
 Sai por apenas }
{110}{}{Essa arma é feita do mais fino aço reciclado. Sinta como ela se encaixa confortavelmente na sua
 mão. E não se preocupe, nossos engenheiros a testaram por segurança e confiança. Nenhum ladrão com mente
 sã ousaria tentar te roubar se você ficar rodando esse bebê por aí. E só vai sair por apenas }
{111}{}{Esse pequena gema é a única de seu tipo. Do mais longínquo... ela funciona apontando
 pra- Olha, eu não sei que merda é essa. Você quer ou não? O preço é  }
{112}{}{This little dandy just screams. "Don't mess with me!" The mere sight of it will send your
 enemies running. A bargain at }#dandy
{113}{}{I can tell you're the type of person that likes to get close up and personal when dealing with
 riff raff. Well this little doohickey is just what you need, and it'll only cost you }#doohickey
{114}{}{Eu vou querer.}
{115}{}{Não, valeu.}
{116}{}{Ah, certamente, você não vai se arrepender. Foi ótimo fazer negócios com você. Te vejo por aí.}
{117}{}{[Fim]}
{118}{}{Merda! Que perda de tempo. Vai, cai fora!}
{119}{}{[Fim]}
{120}{}{Bem, gastei minha fala a toa. $} #continue on 152
{121}{}{Sim.}
{122}{}{Não.}
{123}{}{Ei, é você de novo. Eu tenho material novo - quer ver?}
{124}{}{Claro, vamos ouvir o que você tem.}
{125}{}{Sem chance, Willy.}
{126}{}{Sim.}
{127}{}{Não.}
{128}{}{Cai fora! Tenho trabalho a fazer.}
{129}{}{Volte quando tiver mais dinheiro.}
{130}{}{VAI EMBORA!}
{131}{}{Sem devoluções.}
{132}{}{Nada de trocas.}
{133}{}{Nada de créditos.}#ou 'fiado nem fudendo!'??? ^^
{134}{}{Vai embora, tenho trabalho a fazer.}
{135}{}{Não foi um gesto inteligente.}
{136}{}{Fedaputa!}
{137}{}{Isso é pra me fazer baixar os preços?}
{138}{}{Certo, eu vou abaixar os preços.}
{139}{}{Que tal 20% de desconto?}
{140}{}{Que tal 40% de desconto?}
{141}{}{Que tal 80% de desconto?}
{142}{}{Certo, GRÁTIS; aqui, tome!}
{143}{}{Willy}
{144}{}{George}
{145}{}{Mike}
{146}{}{Walter}
{147}{}{Charlie}
{148}{}{Freddy}
{149}{}{Mick}
{150}{}{Smitty}
{151}{}{Jack}

{152}{}{. Você quer ou não?}
{200}{}{.}