{100}{}{Você vê um homem em uma metal armor.}
{101}{}{Você vê Joshua.}
{102}{}{Você vê um homem vestindo uma metal armor que contém um insígnea em forma de raio.}
{103}{}{Olá,}
{104}{}{. Meu nome é Joshua. O que posso fazer por você?}
{105}{}{Como sabe nome?}
{106}{}{Como você sabe o meu nome?}
{107}{}{Suas recentes atividades atraíram as atenções pra você. As pessoas falam, escutam e os boatos se espalham por aí. Você precisa lembrar que é apenas um pequeno peixe em um oceano de tubarões,}
{108}{}{.}
{109}{}{O que isso que dizer?}
{110}{}{O que você quer dizer com isso?}
{111}{}{Digamos que você acabou de chegar no pedaço e não sabe o que está rolando na vizinhança. Há muito mais coisas acontecendo do que a sua simples expedição...}#new kid on the block: Nem sei se isso é um easter egg... se acha melhor deixar no original: Let's just say that you're the new kid on the block and you don't know what's going on in the neighborhood. There's a lot more going on than your simple quest...
{112}{}{Continue.}
{113}{}{Prossiga, estou ouvindo.}
{114}{}{Já disse o suficiente por enquanto. Acho melhor você voltar a cuidar da sua vida.}
{115}{}{Espera, mim precisa fazer pergunta.}
{116}{}{Espere, eu preciso preciso fazer algumas perguntas.}
{117}{}{Tudo bem, você tem direito a uma pergunta. O que vai ser?}
{118}{}{Você sabe onde mim acha GECK?}
{119}{}{Você sabe onde mim acha Vault 13?}
{120}{}{Mim procura por comerciante chamado Vic. Onde achar?}
{121}{}{Você sabe onde eu posso encontrar um GECK?}
{122}{}{Você sabe onde eu posso encontrar o Vault 13?}
{123}{}{Estou procurando por um comerciante chamado Vic. Você sabe onde posso encontrá-lo?}
{124}{}{Os GECKs eram aparelhos padrões e obrigatórios em todos os vaults. Se não me falha a memória eles deveriam ser usados depois da abertura do vault para reconstruir a civilização. Suponho que você possa encontrar algum em um vault que não foi aberto. Boa sorte,}#reavalie a primera frase: The GECKs were a standard issue item for all vaults.
{125}{}{Valeu.}
{126}{}{Eu ouvi muitas histórias sobre o Vault 13, mas nehuma delas mencionava sua localização. Boa sorte,}
{127}{}{Valeu.}
{128}{}{Vic teve problemas com a slaver's guild. Você pode achá-lo lá. Boa sorte,}
{129}{}{Espera! Onde eu achar guilda?}
{130}{}{Espere, covê pode me dizer onde fica essa guilda?}
{131}{}{Olá novamente. Não tenho mais nada para te dizer.}
{132}{}{. Bem... com certeza você andou um longo caminho desde a tribo. Você deveria visitar nosso posto em New California Republic qualquer dia. Você vai achar recompensante. Agora, se me dá licença...}
{133}{}{Olá novamente. Eu não tenho mais nada para te dizer.}
{134}{}{Espere...}
{135}{}{Este é um posto privado.}#posto=office. não achei outra palavra pra usar.
{136}{}{Não tem nada aí pra você.}
{137}{}{Esta é uma propriedade privada, saia daí.}