{100}{}{Você vê um homem baixo e gordo de Shi.}
{101}{}{Você vê o Dr. Wong Yi Tze.}
{102}{}{Você vê um homem baixo e gordo de Shi.}
{103}{}{Posso te ajudar com algo?}
{104}{}{Daghi nu?}
{105}{}{Quem você é?}
{106}{}{Eu ouço que você tem algo diferente.}
{107}{}{Quem é você?}
{108}{}{O que você faz aqui?}
{109}{}{Não, obrigado. Isso é tudo.}
{110}{}{Eu tenho que confessar, Eu não falo sua língua. Talvez você deva falar com o Ken Lee, ele entende muitas línguas diferentes.}
{111}{}{Aagh!}
{112}{}{Eu sou o Dr. Wong. Eu sou o cientista chefe dessa instalação.}
{113}{}{Mais algumas dúvidas, por favor.}
{114}{}{Obrigado. Tchau.}
{115}{}{Eu comando os experimentos científicos que nós criamos e fazemos aqui. Eu sou o encarregado da rede de computadores.}
{116}{}{O que você está planejando?}
{117}{}{Como alguém consegue acesso à rede de computadores?}
{118}{}{Eu tenho outras perguntas.}
{119}{}{Vejo. Tchau.}
{120}{}{Ah, mas se eu te contar sobre os nossos planos, então todo mundo saberá. Eu quero ter certeza que eles são planos secretos, por enquanto.}
{121}{}{Está bem, está bem. Eu tenho outras perguntas.}
{122}{}{Obrigado. Tchau.}
{123}{}{O que você acha se eu enfiar uma arma embaixo do seu nariz e forçar você a me dizer?}
{124}{}{Quem aprender a hackear ele, ou fazer amizade com um de meus homens. Estou brincando, é claro, sobre hackear ele - se você está aqui para fazer isso, eu mandaria alguém atrás de você para te matar. [Ele sorri para mostrar que não existe nenhuma ofensa.]}
{125}{}{Você realmente quer me matar?}
{126}{}{Então você fará objeção se eu acessar o computador?}
{127}{}{Eu tenho algumas outras perguntas.}
{128}{}{Claro que você pode. Tchau.}
{129}{}{Então teria que considerar ele como uma ameaça e te advertir que essa ação talvez seja prejudicial a sua saúde.}
{130}{}{Vamos ver.}
{131}{}{Eu só estava brincando. Eu tenho outras perguntas.}
{132}{}{[Ele sorri] Nós devemos proteger nossa honra, estranho.}
{133}{}{Err, certo. Então você faria objeção se eu acessar o computador?}
{134}{}{Ceeerto. Eu tenho outra pergunta.}
{135}{}{Apostarei. Tchau.}
{136}{}{Se você conseguir convencer meus homens a deixa-lo entrar. Mas tenho certeza que não conseguirá.}
{137}{}{E se eu colocasse uma arma embaixo do seu nariz?}
{138}{}{Ótimo. Bem, eu tenho mais algumas perguntas.}
{139}{}{Hmm. Vejo. Bem, tão longo.}
{140}{}{Ahh, sim! De fato. Eu irei preparar isso com feijões de fava e um bom chianti.}
{141}{}{Você ainda tem isso? Bom. O Chip precisa voltar.}
{142}{}{Isso é um baço humano, você é um doente!}
{143}{}{Você supostamente deve saber que devia servir fígado com esse vinho ao em vez de baço, certo?}
{144}{}{Isso é um baço humano, você sabe.}
{145}{}{Quem é esse Chip? É meu baço agora, e eu o tenho agora para jantar.}
{146}{}{Chip é o verdadeiro dono do baço. Ele estava bêbado e o vendeu para o Lao Chou.}
{147}{}{Ele precisava para sobreviver, você sabe. Isso veio de dentro do corpo dele.}
{148}{}{Então talvez seria melhor eu te matar por ele.}
{149}{}{Um acordo é um acordo. Ele não pode tê-lo. Desculpe, mas nós fizemos um acordo e não é só porque o Chip se arrependeu que ele poderá voltar atrás no acordo.}
{150}{}{-mais-}
{151}{}{Isso é um baço humano? Lao Chou não me disse isso!}
{152}{}{Ainda, por causa da rudeza do mensageiro, eu acredito que manterei todas as partes do acordo. Experimentarei ele em vez disso.}
{153}{}{Diga ao seu amigo para vir aqui amanhã, e eu felizmente o devolverei à ele. Eu só espero que você consiga achar um jeito de recolocar isso dentro dele a tempo.}
{154}{}{Muito bem.}
{155}{}{Ha ha! Sim, eu já vi esse filme antes.
 Espere... O que você está dizendo? Você está dizendo que...?}
{156}{}{Sim, é um baço humano.}
{157}{}{Na verdade, eu iria me opor a isso. Você mostrou não ser de bom caráter. De fato, não sei porque ainda estou falando com você . Tenha um bom dia.}
{158}{}{-feito-}
{159}{}{Aiee! Guardas! O intruso está aqui!}
{160}{}{Você com certeza tem um esquema para mim?}
{161}{}{Ken Lee me disse para te dar isso.}
{162}{}{Sim. Agora como que eu pego?}
{163}{}{Não, ainda não.}
{164}{}{Fale com o Ken Lee, e ele te dirá o que vai acontecer no seu futuro. Obrigado. Nós seremos capazes de verificar alguns de nossos testes com esse. Tenho um bom dia.}
{165}{}{Na verdade eu tenho outras perguntas.}
{166}{}{Tão longo.}

#added by killap - expansion pack

#bio specimen begin

{200}{}{Eu encontrei este corpo escondido acima da Hubologists' Base. Acredito que pode ser o seu espécime Xeno Project desaparecido.}
{201}{}{Sim, é verdade! Meu antecessor tinha investido muito neste exemplar e ficou desesperado quando desapareceu.Embora ele ja se foi,talvez ainda podemos ter algum uso para este espécime.Obrigado por recupera-lo.}
{202}{}{Sem problemas, até logo.}
{203}{}{Espere aí! Ninguém disse que eu fiz isso de graça.}
{204}{}{Correto. Ninguém lhe pediu para recuperar este exemplar. Você fez isso e trouxe até aqui por sua própria vontade.Agora o exemplar roubado retornou ao seus legítimos proprietários, e nós o agradecemos por isto.}
{205}{}{Legal, mas fui eu que o encontrei, por isto se você quer de volta,vai ter que pagar um preço.}
{206}{}{Eu não tenho tempo pra isto...Guardas!}
{207}{}{[O homem parece estar prestes a gritar, então ele se acalma] Certo. Aqui esta $500. Mais do que suficiente
 por algo que sempre nos pertenceu. Agora saia, eu sou um homem ocupado.}
{208}{}{Foi um prazer fazer negócios com você. Até}
{209}{}{Oh, merda!}
{210}{}{Vamos Dançar!}
{211}{}{Você recuperou o espécime Xeno Porject desaparecido.}
{220}{}{Aonde ele esta então? Você está de brincadeira comigo?}
{221}{}{Desculpe, eu tenho o costume de acumular quantos itens eu puder. É coisa da minha cabeça.}
{230}{}{Eu não tenho tempo pra isto. Volte aqui quando estiver com o espécime.}
{240}{}{[Ele fareja o ar.] O que é este cheiro? Parece carne podre. [Ele olha pra você e ergue a sobrancelha.]}
{241}{}{Oh, você deve estar sentindo o cheiro deste corpo que encontrei. Pra ser sincero, nem tenho certeza porque estou carregando isto.} 
{242}{}{Huh-huh![Você remove o cadáver em decomposição] Corpo fedido! Cê quer?}
{250}{}{Espere um segundo, este é o espécime do Xeno Project!Meu antecessor tinha investido muito neste exemplar e ficou desesperado quando desapareceu.Embora ele ja se foi,talvez ainda podemos ter algum uso para este espécime.Obrigado por recupera-lo.}
{251}{}{Não, eu não quer-Espere um segundo, este é o espécime do Xeno Project! Meu antecessor tinha investido muito neste... [Ele percebeu que você estava o encarando.] Ahem. Digo, obrigado pelo cadaver. Bom trabalho. Não traga nada mais. Isto é suficiente.Até mais!}
{252}{}{Até!}
{253}{}{Mim guardar coisas. Mim esconder isto.}

#bio specimen end

#dr sheng begin

{300}{}{Então, qual é o negocio com esse tal Dr. Sheng?}
{310}{}{Como você sabe sobre Dr. Sheng? Eh, não importa. Dr. Sheng Ming foi um homem brilhante, mas bastante desagradável que serviu como meu antecessor. Ele ja não tem muita importância aqui.}
{311}{}{Bem, se ele não tem importância pra você, porque deveria *eu* me importar? Deixe-me perguntar outra coisa.}
{312}{}{Mas o que aconteceu com ele?}
{320}{}{O que aconteceu? Eu diria que ele perdeu a cabeça. Durante seus experimentos ele se deparou com algo que eu admito foi bastante notável, mas também muito perigoso e de forma alguma ligado aos objetivos de Shi. Mas Dr. Sheng não se importava com isto. Ele se tornou obcecado com sua criação e a partir do momento que seus experimentos ficaram muito perigosos para continuar aqui, decidiu leva-los para outro lugar. Ele tirou um ano sabático e nunca retornou. Foi ai que eu decidi preencher o seu cargo.}
{321}{}{Que tipo de experimentos Dr. Sheng conduzia? E o que exatamente foi a sua grande descoberta?}
{322}{}{E onde esta o Dr. Sheng agora?}
{330}{}{Como um homem da ciência, eu respeito sua natureza inquisitiva. No entanto,receio que eu não tenha permissão para compartilhar os segredos de Shi com você, estranho.}
{331}{}{E onde está Dr. Sheng now?}
{332}{}{Certo, guarde seus segredos fictícios. Eu tenho meus próprios segredos, você sabe. Melhores do que você pode imaginar}

{340}{}{[Ele sorri educadamente] Tenho certeza que você tem. Agora se você me der licença, eu tenho muito trabalho que precisa ser feito.Bom dia!}
{341}{}{[FEITO]}

{350}{}{Dr. Sheng foi escoltado um dia ou mais para o sul.Se não me engano. Ele passou residir em alguma casa abandonada.Ele só tinha que estar fora por um mês, mas ja se passou muito tempo e ainda temos que falar com ele. Se tivesse que adivinhar, diria que foi destruído por suas próprias criações, ou foi vitima dos numerosos perigos do deserto.}
{351}{}{Um dos seus principais cientistas pode estar morto, e você não se importa? Ainda não foi procurar por ele?}
{352}{}{Acho que gostaria de procurar este tal Dr. Sheng. Você poderia me dar sua ultima localização?}
{353}{}{Bem, é isso. Deixe-me perguntar outra coisa.}

{360}{}{Você vai ter que me desculpar por parecer tão insensível sobre o assunto. A verdade é, Dr. Sheng não era muito popular por aqui e eu não acredito que qualquer um de nós sente no minimo falta dele.}
{361}{}{Acho que gostaria de procurar este tal Dr. Sheng. Você poderia me dar sua ultima localização?}
{362}{}{Entendo. Deixe-me perguntar outra coisa.}

#I suppose I could... I must admit I am somewhat curious to learn of his fate. Here, I'll mark Dr. Sheng's last known location on your mapping device. But I must warn you that it could prove to be highly dangerous. Of course, it is always dangerous out there in the wastes. Anyway, if you find something of interest, do let me know.
{370}{}{Suponho que eu poderia... Devo admitir que de alguma forma estou bastante curioso sobre o seu paradeiro. Aqui, vou marcar a ultima localização conhecida de Dr. Sheng no seu dispositivo de mapeamento. Mas devo alerta-lo que ele pode vir a ser bastante perigoso. Claro,é sempre um risco la fora em lugares desertos. No mais, se encontrar algo de interesse, deixe me saber.}
#Thanks, I'll do that. Bye.
{371}{}{Obrigado, eu farei isto. Até mais.}
#Let me ask you something else
{372}{}{Deixe-me perguntar algo a mais.}

#Dr. Sheng is still alive and he's created some kind of plant that takes root in and controls human corpses.
{380}{}{Dr. Sheng ainda esta vivo e ele criou algum tipo de planta que se enraíza e toma controle de cadáveres humanos.}

#So he has achieved some success with his Xeno Project. How fascinating ... and disturbing. We put an end to his sentient plant experiments here after we lost one our techs. When he left to continue his research, I assumed he'd fall victim to his own creations. Has he managed to assume some form of control over them?
{390}{}{Neste caso ele então conseguiu algum sucesso com o seu Xeno Porject. Tão fascinante... e perturbador. Nós demos um fim nos seus experimentos científicos em plantas depois de perder um de nossos técnicos. Quando nos deixou para continuar suas pesquisas, eu pensei que ele seria vitima das próprias criações. Teria ele conseguido assumir algum tipo de controle sobre elas?}  
#Yeah, some of them seem to be subservient. They even refer to him as 'master.'
{391}{}{Sim, algumas delas parecem ser subordinadas. E referem a ele como 'mestre'.}

#Hmm… If he were to somehow establish an army of those plant-creatures, that would not bode well for the Shi. I was hoping it wouldn't come to this, but it seems we have no choice but to ensure that Dr. Sheng and his experiments are eliminated. Since he trusts you enough to allow you get close to him, you are the best candidate. Is that something you'd be willing to do? You would be compensated, of course.
{400}{}{Hmm... Se de alguma forma ele estabelecer um exercito destas criaturas vegetais, não sera nada bom para Shi. Tinha esperanças de que ele não chegaria a isto, mas pela situação não temos nenhuma escolha alem de garantir que Dr. Sheng e seus experimentos sejam eliminados. Parece que ele confia o suficiente em você para permitir que cheque perto dele, você é o melhor candidato. É algo que você estaria disposto a fazer? Obviamente, seria recompensado.}
#It'd be a pleasure. The guy and his whole operation creeps me out.
{401}{}{Seria um prazer, este cara e toda a sua operação me assusta.}
#What kind of compensation are we talking here?
{402}{}{Que tipo de recompensa nós estamos falando aqui?}
#Not interested. Dr. Sheng's your problem—you guys can deal with him.
{403}{}{Não estou interessado. Dr. Sheng é problema seu, é vocês que devem lidar com isto.}

#The Shi will be most grateful for this service. Once Dr. Sheng and all of his creations have been eliminated, report back to me to receive your reward.
{410}{}{Shi ficara muito grato por este serviço. Uma vez que Dr. Sheng e todas as suas criaturas forem eliminadas, reporte a mim e recebera sua recompensa.}
#DONE
{411}{}{FEITO}

#I'll leave that up to you. We could grant you weapons, supplies, or money. You may decide once the task is complete.
{420}{}{Vou deixar isso pra você. Podemos lhe conceder armas, suprimentos ou dinheiro. Você pode decidir uma vez que a tarefa seja concluída.}
#All right. I'll do it.
{421}{}{Tudo certo. Eu faço isso.}
#Not interested. Dr. Sheng's your problem—you guys can deal with him.
{422}{}{Não estou interessado. Dr. Sheng é problema seu, é vocês que devem lidar com isto.}
#All right. I'll do it. But before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.
{423}{}{Tudo certo.Eu faço isso. Mas antes de partir, Dr. Sheng queria que eu entregasse esta amostra de uma planta para você. Ele disse que deveria ajuda-ló a alcançar o objetivo de criar plantas resistentes a radiação.}

#Fair enough. We will handle the problem ourselves, but it will have to wait, as we don't have the resources to expend at the moment. Hopefully it won't be too late once we are able to act. In the meantime, if you should change your mind, please let me know.
{430}{}{Justo, nós vamos lidar com o problema nos mesmos, mas isto vai ter que esperar, pois não podemos desperdiçar nossos recursos no momento. Espero que não seja tarde de mais quando formos capazes de agir. Neste meio tempo, se acaso mudar de ideia, por favo me avise.}
#Don't count on it. Bye.
{431{}{Não conte com isto. Até mais.}
#I'll think about it. Bye.
{432}{}{Vou pensar sobre isto. Até mais.}
#We'll see. Let me ask you something else.
{433}{}{Nos veremos. Deixe-me perguntar algo mais.}

#I don't suppose you have changed your mind? Will you help us eliminate Dr. Sheng and his creations?
{440}{}{Eu não acredito que você mudou de ideia? Vai nos ajudar a eliminar Dr. Sheng e suas criaturas?}
#Nope, I actually wanted to ask you about something else.
{441}{}{Não, na realidade eu queria perguntar sobre algo mais.}
#Alright, I'll take him out for you.
{442}{}{Tudo bem, vou cuidar dele para você.}
#I'll do it, but for a price. You were talking about compensation before?
{443}{}{Eu faço isso, mas por um preço. Vocês estava falando sobre um recompensa antes?}

#Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind… Anyway, you may claim your reward. Are you interested in weapons, supplies, or cash?
{450}{}{Nossas escoltas relataram que Dr. Sheng e seus experimentos foram destruídos. Um desperdício de uma mente brilhante... De qualquer forma, você pode exigir a sua recompensa. Você esta interessado em armas, suprimentos ou dinheiro?}
#Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind… Anyway, we never asked you to get so involved, but we are grateful. For your troubles, you may claim a reward. Are you interested in weapons, supplies, or cash? 
{451}{}{Nossas escoltas relataram que Dr. Sheng e seus experimentos foram destruídos. Um desperdício de uma mente brilhante... De qualquer forma, nos nuncas lhe pedimos para se envolver tanto, mas estamos muito gratos. Pelos seus problemas, você pode exigir uma recompensa. Você esta interessado em armas, suprimentos ou dinheiro?}
#I'll take weapons.
{452}{}{Vou levar as armas.}
#I could always use more supplies.
{453}{}{É sempre bom ter mais suprimentos.}
#Just give me money.
{454}{}{Apenas me dê o dinheiro.}
#Keep your reward. I only did it because it was the right thing to do.
{455}{}{Guarde sua recompensa. Eu so fiz isso pois era a coisa certa a se fazer.}

#Here you go. [He hands various high powered weapons]
{460}{}{Aqui está. [Ele entrega varias armar de alta potencia].}
#DONE
{461}{}{FEITO}

#Here you go. [He hands you various supplies]
{470}{}{Aqui está. [Ele entrega varios suprimentos].}
#DONE
{471}{}{FEITO}

#Here you go. [He hands you $5,000
{480}{}{Aqui está. [Ele entrega $5,000}
#DONE
{481}{}{FEITO}

#The Shi appreciates your assistance. Now, I have much work to do. Good day.
{490}{}{A Shi agradece o seu apoio. Agora, eu tenho muito trabalho a fazer. Bom dia.}

#Before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.
{500}{}{Antes de partir, Dr. Sheng queria que eu entregasse esta amostra de uma planta para você. Ele disse que deveria ajuda-ló a alcançar o objetivo de criar plantas resistentes a radiação.}
#Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.
{501}{}{Dr. Sheng queria que eu entregasse esta amostra de uma planta para você. Ele disse que deveria ajuda-ló a alcançar o objetivo de criar plantas resistentes a radiação.}
#Dr. Sheng wanted me to give you this plant sample as a gift, but I thought I should warn you that it's infused with his sentience serum. I don't know what it's supposed to do, but I'm pretty sure it won't be good for the Shi.
{502}{}{Dr. Sheng queria que eu entregasse esta amostra de uma planta como presente, mas eu acho que deveria alerta-lo que isto foi contaminado com o seu soro orgânico. Não sei exatamente o proposito disto, mas tenho certeza que não será bom para a Shi.} 

#Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. Now if there is nothing else, I should be getting back to work.
{510}{}{Interessante. [Ele pegou a amostra e guardou em outro lugar.] Eu e minha equipe iremos examina-la depois. Não posso dizer  que confio em nenhum presente vindo do Dr. Sheng, mas acredito que exista um minimo de chance disto ser útil.Veremos. Agora, se não há mais nada, eu devo voltar ao trabalho.}
#Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. But I thought you were going to eliminate Dr. Sheng, not be his courier? In any case, I should be getting back to work.
{511}{}{Interessante. [Ele pegou a amostra e guardou em outro lugar.] Eu e minha equipe iremos examina-la depois. Não posso dizer  que confio em nenhum presente vindo do Dr. Sheng, mas acredito que exista um minimo de chance disto ser útil.Veremos. Mas eu pensei que você estava indo para eliminar Dr. Sheng, não para ser o seu mensageiro? De qualquer forma, eu devo voltar ao trabalho.}
#Actually, I would like to ask you something else.
{512}{}{Na realidade, eu gostaria de perguntar sobre algo mais.}
#Goodbye.
{513}{}{Adeus.}
#Actually, I went through quite a bit of trouble to get that sample for you. I think it's worth a reward.
{514}{}{Na verdade, eu passei por muitos problemas para conseguir esta amostra para você. Pensei que isto merecia uma recompensa.}

#Do you, now? The Shi did not solicit this plant sample from you, but if you feel your deeds have earned some compensation, I suppose we could spare this. [He hands you a super stimpak.] Now I really should be getting back to work.
{520}{}{Porque? A Shi não requisitou esta amostra de planta a vocês, mas se vocês acha que merece algum tipo de recompensa, suponho que podemos ceder isto. [Ele entrega um super stimpak.] Agora eu realmente devo voltar ao trabalho.}
#Actually, I would like to ask you something else.
{521}{}{Na realidade eu gostaria de perguntar sobre algo mais.}
#Thanks. Bye.
{522}{}{Obrigado. Até mais.}
#Really? You call this a reward? I'm gonna knock you around until something more valuable falls out.
{523}{}{Serio? Você chama isto de recompensa? Eu vou vou te surrar todo até que algo com mais valor caia de você.}

#[Takes the seed.] Thank you, I will dispose of this immediately. [He sighs.] I knew Dr. Sheng had lost it, but I didn't think he'd go so far as to try and destroy his own people. He must be dealt with immediately.
{530}{}{[Ele pegou a sementes] Obrigado, vou me livrar disto imediatamente. [Ele suspira] I sabia que Dr. Sheng tinha se perdido, mas nunca iria pensar que ele pudesse ir tão longe ao pondo de destruir o seu próprio povo. Ele precisa ser tratado imediatamente.}
#I agree. He's quite the madman.
{531}{}{Concordo. Ele é um homem louco.}

#clutches heart
{540}{}{*Coração Acelerado* Wahh.}
#Urgh
{541}{}{Urgh.}
#Dr,Wong!
{542}{}{Dr. Wong!}

#You eliminate Dr. Sheng for the Shi
{560}{}{Você eliminou Dr. Sheng para a Shi.}
#you deliver the plant sample to Dr. Wong.
{561}{}{Você entregou a amostra de planta para Dr. Wong.}
#You assassinate Dr. Wong.
{562}{}{Você assassinou Dr. Wong}

#dr sheng end
#end added

