{100}{}{Você vê uma punk.}
{101}{}{Você vê uma punk.}
{102}{}{Você vê uma mulher jovem, cínica e claramente bonita.}
{103}{}{Eu aposto que meu namorado ofereceu pra me compartilhar.}
{104}{}{Às vezes eu fico doente de viajar.}
{105}{}{Tenho certeza que é bom morar aqui.}
{106}{}{Aposto que nós podemos fazer um inferno de cena aqui.}
{107}{}{Você foi para o oeste pela água?}
{108}{}{Eu flertaria com você, mas eu só não estou interessado.}
{109}{}{::sarcasmo:: Com certeza tem um monte de mulheres fortes por aqui, né?}
{110}{}{Você espera que eu me vire pra você? Se liga.}
{111}{}{Eu sou único! Só igual a todo mundo!}
{112}{}{As vezes o cinismo do mundo me deixa entediado.}
{113}{}{A próxima vez, eu quero encontrar uma tribo de góticos.}
{114}{}{Me falaram que o Imperador Shi tem uma esperteza de outro mundo.}
{115}{}{Esse Shi me parece engraçado.}
{116}{}{Eu tenho a mente aberta, né?}
{117}{}{Olhe para todos esses novos punks. Só se pagam de punks.}
{118}{}{AHS-9 nos enganou e ele vai enganar você também se você deixá-lo.}
{119}{}{O próximo palhaço que me chamar de "vadia" vai levar um tiro.}
{120}{}{Então como foi isso, pegou de um mutante?}
{121}{}{Foi mutante grande e forte Francis machucou você?}
{122}{}{Estou surpreso que você consiga andar depois do que o Francis fez.}
{123}{}{Eu achei que você ainda estaria sangrando depois do Francis.}
{124}{}{Eu não consigo acreditar que você não conseguiu ajudar o Chip.}
{125}{}{Seu bastardo egoísta. Eu aposto que o Chip teria te ajudado.}
{126}{}{Todo mundo gostava do Chip. Agora ninguém gosta de você.}
{127}{}{Você é bem idiota, né?}
{128}{}{Nunca pensa em ninguém além de você mesmo?}
{129}{}{Oh, vejam, é o "herói".}
{130}{}{Ei, galera! É o egoísta bastardo!}
{131}{}{Oh, você de novo? Parece que ninguém quer falar com você agora.}
{132}{}{Odiador do Chip!}
{133}{}{Muito ruim sobre o baço.}
{134}{}{Aposto que alguém comeu o fígado do Chip.}
{135}{}{Eu adoraria se o Chip ficasse bom de novo.}
{136}{}{Eu acho Chip o melhor!}
{137}{}{Ainda que ele não tenha baço, eu faria o Chip em um segundo!}
{138}{}{Obrigado por você ter tentado pegar o baço do Chip de volta.}
{139}{}{Você fez o seu melhor pelo Chip.}
{140}{}{Aqui está outra coisa sobre o Chip.}
{141}{}{Me pergunto se o baço estava bom?}
{142}{}{Yay! Agora eu posso ter o Chip E o baço dele!}
{143}{}{Estou indo ver o Chip agora!}
{144}{}{Chip é o melhor!}
{145}{}{Eu gosto de você. Você é uma boa pessoa.}
{146}{}{Estou tão feliz pelo Chip.}
{147}{}{Chip é um homem completo agora.}
{148}{}{Você quer se divertir comigo e com o Chip?}
{149}{}{Você fez bem com o baço do Chip.}
{150}{}{Você é muito descolado!}
{151}{}{Suze voltou! Ótimo!}
{152}{}{Suze voltou...Droga!}
{153}{}{Suze sempre foi realmente legal comigo.}
{154}{}{Eu gosto da Suze.}
{155}{}{Obrigado por salvá-la.}
{156}{}{Algumas pessoas precisam aprender a não sair andando por aí.}
{157}{}{Quem sabe?}
{158}{}{Pobre Badger. Talvez ele precise de alguém para consolá-lo.}
{159}{}{É melhor eu ter certeza que o Badger está bem.}
{160}{}{Badger é fofo, mas não é nenhum galã.}
{161}{}{Me pergunto por que o Badger peida e arrota tanto.}
{162}{}{Badger provavelmente peida porque ele fica triste.}
{163}{}{Pobre Badger.}
{164}{}{É o forte e velho mundo em que vivemos.}
{165}{}{Suze devia saber mais.}
{166}{}{Se você for pegar o barco, nós teremos que partir.}
{167}{}{Desculpe pelo estado em que o barco está.}
{168}{}{Então você vai pegar o barco, né?}
{169}{}{O PMV Valdez é um bom navio - era uma boa casa.}
{170}{}{Hora de juntar minha trouxa, eu acho.}
{171}{}{Pegue o barco.}
{172}{}{Boa sorte na procura pelo seu povo.}
{173}{}{Eu irei embora agora.}
{174}{}{Eu espero que a gente consiga encontrar outro lugar para morar.}
{175}{}{Pobre Badger. Ele era realmente fofo.}
{176}{}{Quem iria querer matar o Badger?}
{177}{}{Badger tinha um cheiro engraçado mas eu gostava dele.}
{178}{}{Eu fiquei sabendo que o Badger era gay, mas ele tinha uma namorada.}
{179}{}{Eu sempre achei o Badger abusivo, mas de certa forma fofo.}
{180}{}{Aposto que o Badger está mostrando isso para seus amigos.}
{181}{}{Badger... ::sniff::}
{182}{}{Badger era uma verdadeira príncesa de contos de fadas.}
{183}{}{Seu idiota. Por que você matou ele?}
{184}{}{Você acha que nós iremos nos juntar com os Hubologistas agora?}
{185}{}{Seu estúpido, dívida estúpida.}
{186}{}{Os Hubologists estão te chantageando também.}
{187}{}{Vá para o inferno! Vá para o inferno e morra!}
{188}{}{Eu te odeio.}
{189}{}{Você fede.}
{190}{}{Ovelhinha ovelhinha ovelha!}
{191}{}{Cultista louco!}
{192}{}{Eu acho que algumas pessoas são burras de natureza.}
{193}{}{Ei! É o idiota que não consegue pensar sozinho!}
