{100}{}{Você vê um homem em uma metal armor.}
{101}{}{Voê vê Luke.}
{102}{}{Você vê um homem vestindo uma metal armor que contém uma insígnea em foa de raio.}
{103}{}{Olá,}
{104}{}{. Meu nome é Luke, o que posso fazer por você?}
{105}{}{Como saber meu nome?}
{106}{}{Como você sabe meu nome?}
{107}{}{Joshua mencionou sua passagem em Den. Ele disse que você era um pequeno peixe provocando grandes ondas.}
{108}{}{Os boatos se espalham. Você é um pequeno peixe provocando grandes ondas.}
{109}{}{O que isso quer dizer?}
{110}{}{O que você quer dizer com isso?}
{111}{}{Você está atraindo a atenção de muita gente. Você precisa tomar cuidado.}
{112}{}{Continue.}
{113}{}{Prossiga, estou ouvindo.}
{114}{}{Eu já disse o suficiente por enquanto. Acho melhor você voltar a cuidar da sua vida.}
{115}{}{A mesma lorota que mim receber do Joshua. Mim precisa fazer pergunta.}
{116}{}{Espera, mim precisa fazer pergunta.}
{117}{}{É a mesma lorota que eu recebi do Joshua. Eu posso fazer algumas perguntas?}
{118}{}{Espere, eu preciso fazer algumas perguntas.}
{119}{}{Joshua permitiu um pergunta; eu vou fazer o mesmo. Qual vai ser?}
{120}{}{Tudo bem, você tem direito a uma pegunta. Qual vai ser?}
{121}{}{Você sabe onde eu encontrar GECK?}
{122}{}{Você sabe onde eu encontrar Vault 13?}
{123}{}{Quem ser vocês?}
{124}{}{Você sabe onde eu posso encontrar um GECK?}
{125}{}{Você sabe onde eu posso encontrar o Vault 13?}
{126}{}{Quem diabos são vocês?}
{127}{}{Sim, eu acredito que o Vault 13 nunca usou o deles. É capaz de você conseguir encontrar um por lá. Boa sorte,}
{128}{}{Espera! Onde fica vault?}
{129}{}{Espere um minuto! Onde fica o vault?}
{130}{}{Sua localização está armazenada no sistema dos computadores do Vault 15. Boa sorte,}
{131}{}{.}
{132}{}{Valeu.}
{133}{}{Nós somos a Brotherhood of Steel. Não há mais nada para eu te dizer agora. Boa sorte,}
{134}{}{Espera! Mim precisa saber mais!}
{135}{}{Espere, você não pode deixar as coisas vagas desse jeito!}
{136}{}{Olá novamente, eu não tenho mais nada pra dizer.}
{137}{}{. Bem... com certeza você andou um longo caminho da tribo até aqui. Você deveria visitar nosso posto em San Francisco, você vai achar muito recompensante. Agora, se me dá licença. Eu tenho que ir.}
{138}{}{Olá novamente. Eu não tenho mais nada pra te dizer.}
{139}{}{Espere...}
{140}{}{Este é um posto particular.}#office=posto... trocar
{141}{}{Não há nada pra você aí.}
{142}{}{Esta é uma propriedade privada, saia daí.}