{100}{}{Você vê um humano com cara de abatido.}
# You see a very glum-looking human.
{101}{}{Você vê Lumpy, amigo e assistente do Skeeter.}
# You see Lumpy, Skeeter’s friend and assistant.
{102}{}{Você vê um humano muito magro, de olhos caídos e triste.}
# You see a very thin, saggy-eyed, and unhappy-looking human.

{110}{}{Você tá pior que eu. Pobre coitado.}
# You’re in worse shape than I am. Poor moron.
{111}{}{Eu não tenho tempo para gastar conversando com idiotas.}
# I don’t have time enough to spend talking to morons.
{112}{}{Eu percebi que você não é muito mais esperto que uma brahmin.}
# You ain’t much smarter than the brahmin I watch.
{113}{}{Você não tem um baralho completo aí, tem?}
# You don’t quite have a full deck, do ya?
{114}{}{Por Deus, você é tão idiota quanto parece.}
# By God, you are just as dumb as you look.

{120}{}{Olá. Meu nome é Lumpy.}
# Hello there. My name’s Lumpy.
{121}{}{Esse é um tipo de nome raro. Como você o conseguiu?}
# That’s sort of an unusual name. How did you come by it?
{122}{}{O que você faz aqui?}
# What do you do here?
{123}{}{Que legal, Lumpy. Uh, eu tenho que ir agora.}
# That’s nice, Lumpy. Uh, I’ve got to be going now.

{130}{}{Bem, meu verdadeiro nome é John -- mas todo mundo me chama de Lumpy.}
# Well, my real name’s John -- but everyone here just call me Lumpy.
{131}{}{Por que Lumpy?}
# Why Lumpy?
{132}{}{Bem, quem pode culpá-los. Tchau.}
# Well, who can blame them. Goodbye.

{140}{}{Olá. Ficou sabendo que cada brahmin tem sua própria personalidade? Bem, se você ficar olhando elas por muito tempo, como eu fiquei, você vai perceber.}
# Hello there. Ever notice that each brahmin has its own personality? Well, if you watch them as long as I have, you sure notice.
{141}{}{É. Com certeza é fascinante. Isso é o que elas são.}
# Yup. Downright fascinating. That’s what they are.
{142}{}{Moo moos.}
{143}{}{O que você tá fazendo aqui?}
# What do you do here?
{144}{}{Isso é realmente interessante. Quem é você?}
# That’s really interesting. Who are you?
{145}{}{Eu tava curioso sobre algumas coisas.}
# I’m curious about some things.
{146}{}{Foi um prazer te conhecer, Lumpy. Até mais.}
# Nice to meet you, Lumpy. Goodbye.

{150}{}{Olá. Você provavelmente tá aqui pra ver o Skeeter. eu realmente não me importo com coisas eletrônicas. Eu só tô aqui pra ajudar quando ele precisa de algo.}
# Hello there. You’re probably here to see Skeeter. I don’t really take care of the technical stuff. I’m just here to help out.
{151}{}{Keeter. Heh, heh, heh.}
{152}{}{Quem é você?}
# Who’re you?
{153}{}{O que você faz aqui?}
# What do you do here?
{154}{}{Eu tenho algumas perguntas pra fazer.}
# I have some questions for you.
{155}{}{Ah, tá. Eu vou falar com o Skeeter então. Obrigado.}
# Oh, okay. I’ll talk to Skeeter then. Thanks.

{160}{}{Olá. Já que você se convidou pra entrar -— O que eu posso fazer por você?}
# Hello there. Since you’ve already invited yourself in -— what can I do for you?
{161}{}{Eu faminto.}
# Me hungry.
{162}{}{Ah, eu queria saber onde o Skeeter tá?}
# Uh, I was wondering where Skeeter is?
{163}{}{Eu tenho umas perguntas pra fazer.}
# I have some questions for you.
{164}{}{Ah, desculpe. Eu entrei por engano. Tchau.}
# Oh, sorry. I didn’t mean to barge in. Goodbye.

{170}{}{Eu cuido das brahmins ou ajudo Skeeter na oficina dele.}
# I guard the brahmin or help Skeeter in his workshop.
{171}{}{Quem é o Skeeter?}
# Who’s Skeeter?
{172}{}{Deixa eu pergunta uma coisa.}
# Let me ask you something else.
{173}{}{Eu acho que isso é tudo que eu preciso saber por enquanto. Falô, Lumpy.}
# I think that’s all I need to know for now. Goodbye, Lumpy.

{180}{}{Bem, é um tipo de piada. Veja bem, eles normalmente chamam as pessoas como nós de pele lisa. Mas eu fui tratado tão mal por outros Pele lisa em Vault City que todos aqui perceberam que eu devo ser mais carocento que eles.}
# Well, it’s sort of a joke. You see, they usually call people like you and me smoothskins. But I was treated so poorly by other Smoothskins down in Vault City that everyone here figured that I must be more lumpy than they are.
{181}{}{Por que você foi tratado tão mal em Vault City?}
# Why were you treated poorly in Vault City?
{182}{}{Isso explica tudo. Tchau.}
# That explains a lot. Goodbye.

{190}{}{Bem, Skeeter é tipo um mecânico. Ele vai desmontar a maioria das coisas que você trouxer aqui. Ele devolve a maioria, cedo ou tarde. Ás vezes ele deixa as coisas melhores do que estavam antes dele desmontar.}
# Well, Skeeter’s sort of a mechanic. He’ll take apart almost anything that you bring him. Gets most of them back together too, sooner or later. Sometimes things end up working better than they did before.
{191}{}{Onde eu posso achar o Skeeter?}
# Where can I find Skeeter?
{192}{}{Interessante. Deixa eu te perguntar outra coisa.}
# Interesting. Let me ask you something else.
{193}{}{Eu acho que isso é tudo que eu quero saber por enquanto. Falô.}
# I guess that’s all I need to know for now. Goodbye.

{200}{}{Bem, eles disseram que não sou humano o suficiente para eles. Eu sou muito resistente à radiação -— perfeito pra morar aqui. Mas eles não gostaram disso. Me trataram como lixo.}
# Well, they said I wasn’t human enough for them. I’m sorta radiation resistant -— perfect for here. But they didn’t like it. Treated me like dirt.
{201}{}{Sério?}
# Really?

{210}{}{Um dia eu não aguentei mais. Eu percebi que morrer no deserto era melhor do que viver com aqueles idiotas de Vaul City.}
# One day I just couldn’t take it anymore. I figured that dying out in the Wastes was better than living with those assholes in Vault City.
{211}{}{Então como você chegou aqui?}
# How’d you end up here, then?

{220}{}{Bem, uma caravana de Broken Hills me achou e me trouxe pra cá. Eu tô aqui desde então. Uma coisa dos ghouls daqui, é que eles se preocupam mais com a pessoa que você é por dentro. É como uma grande família.}
# Well, a caravan from Broken Hills found me and brought me here. I’ve been here ever since. One thing about the ghouls here is that they care more about what kind of person you are inside. It’s like a big family.
{221}{}{Broken Hills? Onde é isso?}
# Broken Hills? Where are those?
{222}{}{Interessante. Mesmo assim, deixa eu te perguntar outra coisa.}
# Interesting. Let me ask you something else, though.
{223}{}{Que bom que você tá feliz aqui. Tchau.}
# It’s great that you’re happy here. Goodbye.
{224}{}{Uma família de aberrações. Eu não acho que queira escutar alguma coisa de você. Adeus.}
# A family of freaks. I don’t think I want to hear anything else from you. Goodbye.

{230}{}{Broken Hills é onde nós pegamos todo o urânio que precisamos para o reator nuclear. Pelo que eu sei, o urânio é minerado pelos mutantes de lá. Mas eles usam humanos para vender as coisas por eles.}
# Broken Hills is where we get all the uranium that we need for the atomic reactor from. From what I understand, the uranium is mined by mutants down there. But they have humans trade the stuff for them.
{231}{}{Por que eles usam humanos para vender por eles?}
# Why do they have humans trade the stuff for them?

{240}{}{O que você quer saber?}
# What do you want to know?
{241}{}{Você não é o cara curioso? Tá bom. O que você quer saber?}
# Aren’t you the curious one? Well, okay. What do you want to know?
{242}{}{E agora, o que você quer saber?}
# What do you want to know now?
{243}{}{O que é todo esse lixo no pátio?}
# What’s all that junk in the yard?
{244}{}{O que você faz aqui?}
# What do you do here?
{245}{}{Quem é o Skeeter?}
# Who’s Skeeter?
{246}{}{Alguma coisa estranha tem acontecido aqui por perto?}
# Anything unusual going on around here?

{250}{}{Bem, porque eles vendem o urânio para Vault City também. Vault City trata qualquer um que não seja um humano puro como eles como monstros. Então, Broken Hills usa comerciantes humanos. Um cara chamado Chad, eu acho.}
# Well, because they trade uranium to Vault City, too. Vault City treats anyone that’s not a pure strain human just like lepers. So, Broken Hills uses human traders. Some guy named Chad, I think.
{251}{}{Chad, huh? Vou guardar esse nome. Deixa eu te perguntar outra coisa.}
# Chad, huh? I’ll keep that in mind. Let me ask you something else.
{252}{}{Eu acho que isso é tudo que eu quero saber por enquanto. Tchau.}
# I guess that’s all I need to know for now. Goodbye.

{260}{}{Bem, uma parte desse lixo foi deixado aí quando eles estavam construindo o reator -— antes da guerra. O resto dessas coisas? Eu simplesmente não sei. Skeeter coleciona todo tipo de coisa.}
# Well, some of this junk is left over from when they were building the reactor -— before the war. The rest of this stuff? I just don’t know. Skeeter collects all kinds of stuff.
{261}{}{Quem é o Skeeter?}
# Who’s Skeeter?
{262}{}{Interessante. Eu tenho outra pergunta pra fazer.}
# Interesting. I have another question for you.
{263}{}{Eu acho que é só isso que eu queria saber. Tchau.}
# I guess that’s all I need to know. Goodbye.

{270}{}{Ele tá bem aqui. É só você abrir seus olhos e procurar um pouco. Sheesh.}
# Well he’s right here. Just open your eyes and look around a bit. Sheesh.
{271}{}{Skeeter normalmente fica na oficina dele. É um pouco pra baixo do reator que não terminaram de construir. Quase nada consegue tirar ele de lá.}
# Well, Skeeter’s usually in his workshop. Just south of the unfinished reactor. Can’t almost never drag him out of there.
{272}{}{Ah, valeu. Falô.}
# Oh, thanks. Goodbye.
{273}{}{Ultimamente eu não sei por onde o Skeeter anda.}
# I don't know where Skeeter's been recently.

{280}{}{A maioria das vezes eu só me importo com meu trabalho, mas às vezes eu acho que escuto umas coisas tarde da noite.}
# Well, I mostly stick to my business, but sometimes I think I hear things late at night.
{281}{}{Ouve coisas? Que tipo de coisas?}
# Hear things? Like what?
{282}{}{Ah, qual é. Você pode me contar o que você ouviu. Eu não vou contar pra ninguém.}
# Aw, come on. You can tell me what you heard. I won’t tell anybody.
{283}{}{Eu também, mas eu percebo que são apenas vozes na minha cabeça.}
# Me too, but I figure they’re just voices inside my head.

{290}{}{Eu não tenho certeza, você mente. Mas eu acho que eu escutei pessoas, pelo menos eu acho que são pessoas. Indo e vindo do buraco do reator tarde da noite.}
# Well, I’m not sure, mind you. But I think I’ve heard people, at least I thought it was people. Coming and going from the reactor pit late at night.
{291}{}{Pessoas? Toda noite?}
# People? Every night?
{292}{}{Interessante. Deixa eu pergunta outra coisa.}
# Let me ask you something else

{300}{}{Eu não posso te dizer. As pessoas pensam que sou biruta. De qualquer jeito, provavelmente é só o vento batendo no lixo.}
# I can’t tell you. People would think I’m nuts. Probably just the wind blowing through the junk, anyway.
{301}{}{Eu te disse, eu não escutei nada. Agora para de me enxer o saco.}
# I tell you I didn’t hear anything. Now stop pestering me about it.
{302}{}{Tá bom. Então deixa eu perguntar outra coisa.}
# Okay. Let me ask you something else, then.

{310}{}{(Ele olha bem nos seus olhos) Você escuta vozes dentro da sua cabeça? Elas dizem o quanto você é melhor que todo mundo? Elas te dizem que algum dia as pessoas irão se ajoelhar diante da sua grandeza? (ele sorri e concorda com a cabeça)}
# (Looks closely into your eyes) You hear voices inside your head? Do they tell you how much better you are than everyone else? Do they tell you that someday people will kneel before your greatness? (smiles and nods)
{311}{}{Ah, não. Na verdade não.}
# Uh, no. Not really.
{312}{}{Ah, sim. Claro que escuto. Não é todo mundo que escuta?}
# Uh, yeah. Sure I do. Doesn’t everyone?

{320}{}{Good thing. I was really beginning to worry about you.}
{321}{}{Well, thanks for your concern. Let me ask you some questions.}
{322}{}{Uh, yeah. Well, I think I need to be moving on. Goodbye.}

{330}{}{I kinda had you pegged for that type when I first saw you, but I wasn’t sure. Get out of here, you frigging nutcase!}
{331}{}{Uh, yeah. Whatever. Goodbye.}
{332}{}{Well, one of us is a nutcase -— I just think you’re confused as to which one of us it is.}

{340}{}{Well, I don’t know if they were people or what, but usually it’s just every couple of nights. Noises coming and going from the reactor pit. I don’t know what’s going on, and I don’t want to know, either.}
{341}{}{I guess I can’t blame you. No telling what might be down there.}
{342}{}{Thanks for the information. Goodbye.}
{343}{}{Isn’t the reactor pit too radioactive for anything to live in it?}

{350}{}{No, this part of the reactor wasn’t completed when the war started.}
{351}{}{Oh, I see. Hmm, tell me something else, then.}