{100}{}{Você vê um ghoul maior do que o habitual.}
{101}{}{Você vê Zomak, conhecido por alguns como Destruidor.}
{102}{}{Você vê um ghoul grande e robusto cuja face, sob uma testa serveramente inclinada, reflete uma vasta
 reserva de estupidez suprema.}#reveja essa frase inteira por favor. tentei ao máximo entender o sentido correto, mas acho que não consegui. You see a big, burly ghoul whose face, beneath a sharply sloping forehead, reflects vast reserves of simpleminded superiority.

{110}{}{Renew, camarada! Eu sou Zomak. Alguns me chama de Zomak, o Destruidor. O que você quer aqui?}#renew. não sei como voce esta traduzindo isso nos outros dialogos. eu traduziria como renovação mesmo. vou deixar original
{111}{}{Renew, camarada! O que você quer? Diga para Zomak, o Destruidor, o que você veio fazer aqui.}
{112}{}{Renu!}#fala tribal de renew
{113}{}{Ook?}
{114}{}{Só estou dando uma olhada.}
{115}{}{Eu quero a renewal.}#renewal
{116}{}{Eu peguei o caminho errado.}

{120}{}{É melhor você dar uma olhada em outro lugar, ou Zomak vai te mostrar as estrelas.}

{130}{}{Então você deve ver Ele.}
{131}{}{Ele? Onde está ele?}
{132}{}{Eu não sou digno de vê-lo. Tchau.}

{140}{}{É ele quem concede o esclarecimento. É ele quem promete a renewal para todos os que o seguirem.}#renewal
{141}{}{Bem, eu estou quase pronto pra Renewal. Onde ele está?}#renewal
{142}{}{Parece mais uma estupidez pra mim. Vou dar o fora daqui.}

{150}{}{Bem, ele está atrás... Ei! Quem é você mesmo?}
{151}{}{Só um andarilho.}
{152}{}{Sou o Chosen One.}#chosen one
{153}{}{Só estou aqui pra minha renewal anual.}#renewal
{154}{}{Vai ficar tudo bem. Eu só tenho que fazer algumas perguntas pra ele.}

{160}{}{Bem, ande pra fora daqui, então.}
{161}{}{Hã, certo. Tchau.}

{170}{}{Bem, nesse caso... entre. Ele está na próxima sala. Não o deixe esperando.}
{171}{}{Não mesmo. Já vou entrar. Tchau.}
{172}{}{Eu posso voltar mais tarde. Tchau.}

{180}{}{Bem, você pode escolher ir embora. Saia daqui.}#escolher = chosen one
{181}{}{Certo.}

{200}{}{Sim, você podem todos receber a Renewal lá dentro.}#renewal
{201}{}{Certo.}

{210}{}{Ook? O que você quer dizer com isso? Você é idiota?}
{211}{}{Goop?}

{220}{}{Saia daqui. O Cérebro não tem tempo pra gente do seu tipo.}#traduzi como Cérebro mesmo. Afinal, é um easter egg, e todos que conhecem o desenho conhecem como cérebro.
{221}{}{Certo. Estou indo.}

{230}{}{Aqui em baixo só tem o lar do Cérebro. Cara, você é idiota?}
{231}{}{O Cérebro?}
{232}{}{Eu só estava te testando. Você passou. Agora me deixa entrar.}
{233}{}{Acho que me confundi. Deve ser toda essa radiação. Tchau.}

{240}{}{Opa. Hã, não há nada aqui. Nada mesmo. Agora vá embora.}
{241}{}{Tem certeza de que não há nada aqui?}
{242}{}{Certo. Tchau.}

{250}{}{É. Tenho. Agora saia.}
{251}{}{Bem, se você está dizendo. Tchau.}

{260}{}{Ah, he, he... é. Eu sabia disso. Humm, bem, er, eu passei? }
{261}{}{Claro que sim. Agora me deixe entrar.}
{262}{}{Não, você falhou e agora eu tenho que te denunciar.}

{270}{}{Certo, então. Você pode entrar.}
{271}{}{Certo. Tchau.}

{280}{}{Você tem o sinal. Pode entrar.}
{281}{}{entraaaá.}
{282}{}{Sinal?}
{283}{}{Tema o sinal! Tchau.}

{290}{}{Sim, o talismã sagrado da Renewal. Renew, camarada! Renew!}#renewal
{291}{}{Yes... Reno to you, too. Goodbye.}#reno = tribal: renew

{300}{}{Renew, irmão. Você pode passar.}
{301}{}{Renew, irmã. Você pode passar.}