{100}{}{Você vê um homem desmazelado usando roupas bastante desgastadas.}
#You see a scruffy man in worn-down clothing.
{101}{}{Você vê Manson, membro da milícia rebelde local.}
#You see Manson, one of the local hate militia.
{102}{}{Você vê um homem jovem, barbudo, com as roupas desgastadas e com um insano, mas de alguma maneira
 confiável brilho nos olhos.}
#You see a young man with a scraggly beard, tattered clothing, and an insane yet somehow
 trusting gleam in his eye. 

{103}{}{O quê?!}
{104}{}{Dã... gaba gaba ei?}
#Duhhh… gabba gabba hey?
{105}{}{Eu sab'ocê barras?}
#I knyou bars? (Eu hein... confuso bagarai)
{106}{}{Quem é você?}
{107}{}{Por que você está na prisão?}
{108}{}{Me fale sobre Broken Hills.}
{109}{}{Nada. Deixa pra lá.}

{110}{}{Não entendo essa conversa doida de gente estúpida. Dá o fora daqui antes que 'cê me deixe
 burro também.}
{111}{}{Oh!}

{112}{}{Manson. Rebelde contra a sociedade.}
#Manson. Rebel ‘gainst society.
{113}{}{Contra o que você está se rebelando?}
#What are you rebelling against?
{114}{}{Isso aí! Abaixo os opressores!}
#Yeah! Fight the power! (eu sei que não é a tradução certa, mas acho que soa melhor e o sentido é o mesmo. tem mais 3 frases dessa pra frente, se quiser mudar dá uma olhada.)
{115}{}{Parece mais um fracassado na sociedade.}
#Loser in society, more like.
{116}{}{Manson?}
{117}{}{Eu … entendo. Tchau!}

{118}{}{Eu 'tô aqui porque eu e o Franc 'tava agindo contra o que a sociedade quer que a gente acredite.}
#I’m here cuz me and Franc were working against what society wants us to believe.
{119}{}{E que é...}
#And that is…
{120}{}{Isso aí! Abaixo os opressores!}

{121}{}{Broken Hills? Vivi aqui toda a minha vida. Logo, sei de todas as coisas ruins que rolam por aqui.
 Por isso eu sei o quão maus os mutantes são. É bom ter gente como nós que consegue ver a
 verdade.}
#Broken Hills? Lived here all my life. That’s how I know all the bad stuff that goes on here.
 That’s why I know how evil the mutants all are. It’s a good thing there are some of us who see the
 truth.
{122}{}{É isso mesmo. Abaixo os opressores!}
#Yeah, I’ll say. Fight the power, huh?
{123}{}{Você está vendo as coisas com ódio, essa não é a verdade.}
#You’re seeing hatred, and that’s not the truth.
{124}{}{Talvez você devesse se dar conta de que as únicas mentiras que você sabe são as que você deixa
 outras pessoas colocarem na sua cabeça, e que pregar os princípios da rebeldia só vai te fazer parecer mais estúpido.}
#Perhaps you ought to realize that the only blinders you have are the ones you allow other
 people to put on you, and that preaching the politics of hatred only makes you look more stupid.
(caralho, custei pra interpretar essa merda e nao gostei de como ficou. muda aí.)
{125}{}{É. Tchau.}

{126}{}{A sociedade quer que a gente acredite que humanos e mutantes estão destinados a viver juntos. Mas os mutantes
 querem é nos matar! Pelo menos é o que o Franc diz.}
#Society wants us to believe that humans and mutants are meant to live together. But the mutants
 are out to kill us! At least, that’s what Franc says.
{127}{}{Você realmente gosta do Franc, hein?}
{128}{}{Essa deve ser a coisa mais idiota que eu já ouvi.}
{129}{}{Tudo bem. Tchau.}

{130}{}{É isso mesmo! Nós temos que... hmm... pensar por nós mesmos! É isso que o Franc e o Jacob sempre dizem.}
#That’s right! We gotta… umm… think for ourselves! That’s what Franc and Jacob always say!
{131}{}{Puta merda, você realmente bajula esses dois. Por que não tenta pensar por você ao invés de papaguear
o que as outras pessoas te contam?}
#Wow, you really suck up to those two. Why not try thinking for yourself instead of parroting
 what other people tell you?
{132}{}{Você realmente gosta do Franc, hein?}
{133}{}{Tchau.}

{134}{}{E do que você saberia, seu bosta? Dá o fora daqui antes que se machuque.}
#What would you know, you jerk? Get the hell out of here before you get hurt!

{135}{}{Tempos atrás, havia um cara que disse pra gente que tudo que nós tinha que fazer era pensar por nós mesmos. Minha mãe
 e meu pai disseram que ele falava isso pra mim. Ele morreu na prisão, mas foi muito influente pra mim. As pessoas disseram que
ele era muito esperto. Eu acho que elas estavam certas. Quero dizer, olha pra mim!}
#Back in the olden days, there was a guy who told us all we hadda think fer ourselves. My mom
 and dad said he was related to me. He died in prison, but he was really influential to me. People said
 he was really smart. I think they were right. I mean, look at me!
(ficou uma desgrama essa tradução. tá me fugindo um meio melhor de traduzir aquela parte "my mom..." até "...to me"
{136}{}{Hmm… é. Olha pra você.}
{137}{}{Você? Esperto? Ha!}
{138}{}{Claro. Tchau.}

{139}{}{Que é?}
#Wha’?
{140}{}{Nada.}

{141}{}{É, eu acho que ele é uma das pessoas mais sábias que eu já conheci. O Jacob é esperto, mas ele não é
 astuto como o Franc.}
#Yeah, I think he’s one of the wisest people I ever knew. Jacob’s smart, but he ain’t as
 straight up as Franc.
{142}{}{O Franc é só um bostão virulento. Ele não vai te levar pra lugar nenhum}
#Franc’s just a virulent scumbag. He won’t get you anywhere.
{143}{}{É, eu o conheci. Ele é um cara legal.}
#Yeah, I’ve met him. He’s a good guy.
{144}{}{Eu não conheci o cara. Não tenho opinião sobre ele.}
#Haven’t met the guy. No opinion on him.
{145}{}{Valeu. Tchau.}

{146}{}{O que mais você quer?}
{147}{}{Quem é você?}
{148}{}{Por que você está na prisão?}
{149}{}{Me fale sobre Broken Hills.}
{150}{}{Você gosta do Franc?}
{151}{}{Por que você se chama Manson?}
{152}{}{Por que você é tão estúpido?}
{153}{}{Nada. Deixa pra lá.}

{154}{}{Você está com a gente? Então tira nós daqui!}
{155}{}{Estou trabalhando nisso. Tchau.}

{156}{}{Valeu pela ajuda. Sabia que a gente podia contar com um amigo humano pra ver a luz!}
#Thanks for the help. Knew we could count on a fellow human to see the light!
{157}{}{É. Eu tenho a manha mesmo.}
#Yep. I’m good like that.

{158}{}{Então, o que mais eu posso fazer por você?}
#So what else can I do for ya?
{159}{}{Quero saber dos seus planos agora.}
#I’m curious about your plans now.
{160}{}{O que o seu nome quer dizer?}
#What you name means?
{161}{}{Nada. Só estou dando uma olhada por aqui.}

{162}{}{Agora a gente destrói a mina com os mutantes dentro dela. Os que ficarem de fora, a gente quebra no pau.}
#Now we destroy the mine while the mutants are inside. The ones that’re left, we mop up by hand.
{163}{}{Eu quero ajudar.}
#I want in
{164}{}{Me coloca fora dessa.}
#Count me out.
{165}{}{Legal. Boa sorte.}

{166}{}{Bem, as pessoas acham que ele era um cara de uma banda ou algo do tipo. Mas o Manson do meu nome criou uma
 religião e foi morto por causa dela. Ele foi um mártir. Talvez eu vou ser um, também.}
#Well, people think he was a band guy or something. But the Manson I’m named after started a
 religion and got killed because of it. He was a martyr. Maybe I’ll be one, too.
{167}{}{Parece... fascinante. De qualquer jeito…}
#Sounds… fascinating. Anyway

{168}{}{Você tem que falar com o Jacob sobre isso. Tenho certeza que depois de libertar a gente ele vai te aceitar.}
#You’ll have to talk to Jacob about that. I’m sure that with your jailbreak, he’ll want you.
{169}{}{Legal. Tchau.}

{170}{}{Eu queria trabalhar com você. Bem, te vejo por aí!}
#I wanted to work with ya. Oh well. See ya!

{171}{}{Seu merda! A gente confiou em você pra nos ajudar!}
#You jerk! We trusted you to help us!

{172}{}{Puta merda... você mata pra caralho. E agora a gente 'tá livre dos mutantes. Isso é tããão legal!}
#Wow… you can kill like nobody’s business. And now we’re free of the mutants. That’s soooo cool!

{173}{}{A gente vai dar o fora da cidade. E 'cê devia ir também... os mutantes vão caçar bodes-espiatórios.}
#We’re gettin’ outta town. You probably oughta too… the muties will be looking for scapegoats.

{174}{}{A gente vai te seguir.}
#We'll follow you.

{175}{}{Você pregou a mente-aberta para o Manson.}
#You preached open-mindedness to Manson.

{176}{}{We wuz framed! We wuz framed!}#?

{177}{}{Valeu pela ajuda. Vamo' falar com o Jacob e a Aileen.}

{178}{}{Você realizou a fuga com sucesso.}
#You have successfully performed the jailbreak.

{179}{}{Good luck at the mine, brother.}