{100}{}{Você vê um homem introspectivo, usando um jaleco.}
# You see a bemused man in a lab coat.
{101}{}{Você vê o Professor. Parece que ele esta empenhado em um esquema complexo.}
# You see the Professor. He looks like he's engaged in some madcap scheme.
{102}{}{Um homem introspectivo, usando um jaleco, rodeado por equipamentos de laboratório e com um brilho insano em seu olhar.}
# You see a bemused man in a lab coat surrounded by laboratory equipment. There's an insane gleam in his eye.
{103}{}{Você novamente?}
# You again?
{104}{}{O que você quer? Fala logo, sou um homem ocupado!}
# What is it you want? Out with it! I'm a busy man!
{105}{}{Sem putas?}
# Noo beezy?
{106}{}{Teste!}
#Test!
{107}{}{Quem é você? E qual é a desse escorpião?}
# Who are you? And what's with the scorpion?
{108}{}{Quero fazer um dos seus testes.}
# I'd like to take one of your tests.
{109}{}{Nada não. Tchau.}
# Nothing. Bye.
{110}{}{Ah, uma cobaia! Gostaria de fazer um teste, colega?}
# Ah, a test subject! Would you like to take a test, my friend?
{111}{}{Sim!}
{112}{}{Não!}
{113}{}{Quer fazer um teste, hein? Quer testar suas mãos, seus olhos ou sua cuca?}
# You wish to take a test, eh? Do you want to test your hands, your eyes, or your brains?
{114}{}{É!}
# 'Ands!
{115}{}{Sim!}
{116}{}{Raios!}
{117}{}{Nenhum!}
{118}{}{Então porque está gastando meu tempo? Já disse que estou ocupado, não disse? Tenho muito pra fazer em vez de ficar de conversa fiada... Nem sei por que ainda estou falando com você. Passar bem!}
# Then why are you wasting my time? I told you I'm busy, didn't I? I have too much to do to stand around wasting time talking to people like ... why am I still talking to you? Good day!
{119}{}{Tchau!}
{120}{}{É mesmo. Tchau.}
# Err... yeah. Bye.
{121}{}{Quer fazer um teste, hein? Quer testar sua destreza manual, sua percepção ou sua inteligência?}
# You wish to take a test, eh? Do you want to test your manual dexterity, your perception, or your intelligence?
{122}{}{Quero testar minha agilidade.}
# I'd like to test my agility.
{123}{}{Vamos testar minha visão.}
# Let's test my eyes.
{124}{}{Que tal minha inteligência?}
# How about my smarts?
{125}{}{Hmm. Nenhum desses. Esquece.}
# Hmm. None of them. Forget it.
{126}{}{Muito bem. Vou testar você contra o esporpião. Vocês tentarão destrancar essas caixas. Boa sorte.}
# Very well. I'll be matching you against the scorpion. You will both attempt to unlock those boxes. Good luck.
{127}{}{Vai!}
# Go!
{128}{}{Vamos nessa.}
# Let's do it.
{129}{}{Certo. Fique atrás deste cercado, onde você e escorpião dirão quais as letras vocês lêem, de cima para baixo, da esquerda para direita.}
# Right. You'll stand behind this rail, and you and the scorpion will tell me the letters you read, from top to bottom, left to right.
{130}{}{Vai!}
# Go!
{131}{}{Entendi. Pode começar.}
# Got it. Let's go.
{132}{}{Você e o escorpião vão jogar um jogo de minha concepção, chamado "xadrez". Podemos começar?}
# You and the scorpion will be playing a game of my own devising. I call it "chess". Are you ready?
{133}{}{Isso!}
# 'Es!
{134}{}{Sim. Manda ver.}
# Yep. I'm ready.
{135}{}{Eu sou o Professor. Realizo testes de inteligência aplicada. Produzo componentes químicos que aumentam a inteligência e estou testando nesse escorpião, depois de ter falhando com uma planta.}
# I am the Professor. What I do is applied intelligence testing. I create chemical compounds to increase intelligence. I'm trying some out on this radscorpion here, after my failure with the plant.
{136}{}{Você testou em uma planta?}
# You tried it out on a plant?
{137}{}{Quero fazer um teste.}
# I'd like to take a test.
{138}{}{Conseguiu fazer algo que funciona?}
# Have you made anything that works?
{139}{}{Entendi. Era tudo que queria saber. Tchau.}
# I see. That's all I wanted to know. Bye.
{140}{}{Claro que testei numa planta! Estou tentando criar inteligência do nada!}
# Of course I tried it out on a plant! I'm trying to increase intelligence from the ground up!
{141}{}{Entendi. Conseguiu fazer algo que funciona?}
# I see. Have you made anything that works?
{142}{}{Quero fazer um teste.}
# I'd like to take a test.
{143}{}{Isso é tudo que queria saber.}
# That's all I wanted to know.
{144}{}{Claro que consegui! Já ouviu falar do "Mentats"? Ajudei no desenvolvimento de um método para facilitar a produção em massa dessa droga! E de tantas outras!}
# Yes, I have, thank you very much! You ever hear of "Mentats"? I helped develop a method for easy mass-production of that drug! And others! Lots of others!
{145}{}{Beleza, não estressa. Diz aí, queria testar minhas habilidades contra seu escorpião.}
# All right, all right. Say, I'd like to try out my skills against your scorpion.
{146}{}{Tudo bem, acredito em você. Não está mais aqui quem falou.}
# All right, I believe you. I'll just be leaving.
{147}{}{Como você foi capaz de matar meu escorpião? Eu estava tão perto... tão perto...}
# How... how could you kill my scorpion like that? I was close... so close...
{148}{}{Shamble off}

# Agility Test
{200}{}{Uhuuu! Segura ESSA, Sr. Escorpião.}
# Woo hoo! Beat THAT, Mr. Exoskeleton.
{201}{}{Uhuuuuu!}
# Wooooooo Hoooo!
{202}{}{Desgraça!}
# Damn it!
{203}{}{Aaaargh!}
{204}{}{::click clack::}
{205}{}{Como diabos você conseguiu abrir a tranca com GARRAS?}
# How the hell did you pick a lock with CLAWS?
{206}{}{Como conseguir com GARRAS?}
# How U pik wiff CLAWS?
{207}{}{::chitter::}
{208}{}{Pois bem, foi um empate.}
# Well, that was a tie.
# The following 4 strings are used in the phrase:
# "You lose. Scorpion: [SCORE], [Player Name]: [SCORE]."
{209}{}{Você perdeu. Escorpião: }
{210}{}{, }
{211}{}{: }
{212}{}{.}
{213}{}{Hein?}
# Errr
{214}{}{Você provou ser tão ágil quanto o escorpião.}
# You have proven that you are just as agile as the radscorpion.
{215}{}{Aqui, pegue esses Mentats. Parece que você precisa.}
# Here, take these Mentats. You appear to need them.

# Perception Test
{300}{}{E...Z...W...T...O...D...F...E..R...T...F...P...Y...J...M}
{301}{}{Está certo.}
# Yes, that's correct.
{302}{}{M...O...O...Mu?}
# M...O...O...Moo?
{303}{}{Não, eu lamento. Está incorreto.}
# Uh...no, I'm sorry. That's way off.
{304}{}{::click clack:: ::click clack:: (batidas com a cauda)}
# ::chitter chitter:: ::click clack:: ::chirp
{305}{}{Correto! Bom garoto! Sua habilidade com o código Morse está aumentando muito.}
# Correct! Good boy! Gooooood boy! Your Morse code skills are improving nicely.
{306}{}{Você provou ser tão perceptivo quanto o escorpião.}
# You have proven that you are just as perceptive as the radscorpion.

# Intelligence Test
{400}{}{Xeque-mate ::click::}
{401}{}{O QUÊ? Você trapaceou!}
{402}{}{Xeqmate?}
# Ecmat?
{403}{}{Não seja um mau perdedor.}
# Don't be a sore loser.
{404}{}{e...Xeque-mate!}
{405}{}{Xeque-mate!}
{406}{}{::click:: Matar planta! ::click-clack-click::}
{407}{}{Você provou que pode superar o escorpião, que é mais inteligênte que você.}
# You have proven that you can subvert a radscorpion that is more intelligent than you.