{100}{}{Você vê uma planta carnívora.}
# You see a spore plant.
{101}{}{Você vê Seymour, a planta carnívora.}
# You see Seymour the spore plant.
{102}{}{Uma planta carnívora que de alguma forma irradia uma aura de inteligência.}
# You see a spore plant that somehow radiates an aura of intelligence.
{103}{}{Oi! O clima está agradável, não acha?}
# Hi! Nice weather we've been having, huh?
{104}{}{Você falar?}
# Yoo talk?
{105}{}{Hein?}
# Rrr?
{106}{}{Com licença, mas é esta planta que está falando?}
# Excuse me, but is this the plant that's talking?
{107}{}{Você está ligado de alguma forma ao cientista?}
# Are you connected with that scientist in any way?
{108}{}{Tchau.}
# Bye.
{109}{}{Sim, eu falo. E até melhor que algumas pessoas. Eu sorriria para você agora, mas não tenho uma boca. [risos] Diga, você poderia fazer-me um grande favor?}
# Yes, I do talk. Better than some people, it seems. I'd smile at you right now, but I just don't have a mouth. [it laughs] Say, could you do me a big favor?
{110}{}{Sim.}
# 'Es.
{111}{}{Não.}
# Nuh.
{112}{}{Procuro por um lugar melhor. Aqui é legal e tal, mas sinceramente, essas plantas não são de conversar. Estava pensando em um lugar próximo da casa dos ghouls... Você poderia replantar-me?}
# I'm looking for a better place to be. Right here is nice and all, but frankly, these plants aren't much for conversation.  I was thinking over there, by the building with all the ghouls in it... Would you replant me?
{113}{}{Sim!}
#'Es!
{114}{}{Não!}
# Nuh.
{115}{}{Claro.}
# Sure.
{116}{}{Mim achar que não.}
# I think not.
{117}{}{Ótimo! Tudo que você tem que fazer é achar uma pá, desenterrar-me, e me plantar lá. Quando terminar, contarei-te um segredo.}
# Great! All you have to do is find a shovel, dig me up, and plant me over there. When you do, I'll tell you a secret.
{118}{}{Tá!}
# Okay!
{119}{}{Aham.}
# Nuh uh
{120}{}{Certo. Bem... vou te esperar aqui. Como se eu tivesse outra escolha. Até logo!}
# All right. Well, um... I'll be waiting here for you. Not like I really have a choice, you know. So long!
{121}{}{Tchau!}
# Byeeee!
{122}{}{Se você mudar de idéia sabe onde me achar. Estarei plantado aqui. Ha ha ha! É só uma piada de planta. Oh, não vou mais tomar seu tempo. Até logo!}
# If you should happen to change your mind, you know where to find me. I've put down roots here. Ha ha ha! Just a little plant humor for you. Oh, don't let me keep you. So long!
{123}{}{Tchau.}
{124}{}{Bem dito, bem dito! Quão prazeroso ver um ser humano usar a capacidade máxima de seu cérebro. Colega, você estaria com disposição para fazer-me um favor?
# Well said, well said! How delightful to see a homo sapiens use its brain to its fullest extent. My dear friend, would you be willing to do me a favor?
{125}{}{Sim.}
# 'Es.
{126}{}{Não!}
# Nuh!
{127}{}{Porque, sim! É, sim! Tens muita astúcia. Percebo que não germinastes ontem! Seletíssima companhia, teria a gentileza de fazer-me um favor?}
# Why, yes! Yes, it is! Very astute, friend, very astute. I can see you didn't germinate yesterday! My fine-stemmed companion, would you be so kind as to do me a favor?
{128}{}{Claro.}
# Sure.
{129}{}{Acho que não.}
# I don't think so.
{130}{}{Maravilha! Estou muitíssimo satisfeito. Ache logo uma pá e volte. Quando terminar, contarei-te um segredo. Colega, espero que você continue a florir.}
# Deee-lightful! I'm very, very pleased. Just find yourself a shovel and come on back. When you're done, maybe I can tell you a secret. My friend, I do hope you continue to flower.
{131}{}{Hum, certo. Até logo.}
# Um, right. So long.
{132}{}{Mudei de idéia.}
# I changed my mind.

{133}{}{Ah sim, o Professor. Ele cultivou-me desde que eu era uma semente... Mas desde cedo percebi que se mostrasse toda minha inteligência,
 ele me cortaria em pedaços para me examinar. Então eu fingi ser burro e fui plantado aqui. O que é bom, mas gostaria de expandir meus horizontes.
 Você sabe, talvez for replantado em outro lugar...}

#Oh, yes, the Professor. He grew me from a tiny spore and nurtured me... but I realized from an early age that if I were to act as smart as I truly
# am, he'd cut me into pieces to examine me.  So, I played dumb and got planted out here. It's nice... but I'd like to branch out a little.
# Y'know, maybe get planted someplace else...

{134}{}{"Expandir o horizonte." Realmente.}
# "Branch out." Indeed.
{135}{}{Certo. O que você quer?}
# Right. What do you want?
{136}{}{Aham. Preciso ir. Tchau.}
# Uh... huh. I gotta go. Bye.
{137}{}{Então ele ainda tem o escorpião? Aquele bicho é um jogador de xadrez malicioso... cascudo e disposto a morder,
 se é que você me entende... Mas sei como derrotá-lo. Se você me fizer um favor, te direi como.}

# So does he still have the scorpion? That thing is a mean chess player... it has a lot of bark and plenty of bite,
# if you know what I mean... but I know how to beat him. If you do me a favor, I'll tell you how.

{138}{}{Sério? Como?}
# Really? How?
{139}{}{Que fascinante. Uma planta jogadora de xadrez. Quão trivial. Adeus.}
# That's fascinating. A chess-playing plant. How prosaic. Goodbye.
{140}{}{Colega, se você me replantar próximo a casa dos ghouls logo ali, ficarei feliz em partilhar dos meus profundos conhecimentos de xadrez.}
# My fine friend, if you will replant me near the ghouls' home over there, I will be happy to impart my deep-rooted knowledge of chess.
{141}{}{Estamos de acordo.}
# It's a deal.
{142}{}{Não, obrigado. Cuidarei do escorpião por minha conta.}
# No thanks. I'll handle the scorpion on my own.
{143}{}{Ah, colega, você retornou. Que lugar prazeroso. A sombra é perfeita, e a companhia é simplesmente deslumbrante. E o Typhon, que brincalhão! Ele realmente faz minha seiva intelectual fluir!}
# Ahh, my friend, you have returned. This is quite a delightful place here. The shade is perfect, and the company is simply dazzling. That Typhon, what a kidder! He really makes my intellectual sap flow!
{144}{}{Xadrez?}
{145}{}{O que você havia mencionado sobre xadrez?}
# What was that you mentioned about chess
{146}{}{Tchau.}
{147}{}{Bem, mencionei como derrotar o escorpião do Professor no xadrez. Colega, mais simples impossível.
 A manobra Flying Liver Attack é como um mosquiteiro para aquele inseto - ele cai direto na trama e não consegue sair. Garanto seu sucesso.}

# Well, it was about how to beat the professor's scorpion at chess. My friend, it is simplicity itself.
#  The Flying Liver Attack is like a flytrap to that bug - it walks right into it and then can't extricate itself. I guarantee your success.

{148}{}{Brigado! Tchau!}
# 'Anks! Bye!
{149}{}{Agradeço pela informção! Tchau!}
# I appreciate the information! Bye!
{150}{}{Colega! O sol tem brilhado para você? Seu dia está florido? Está pronto para mudança? Eu certamente estou!}
# My friend! Has the sun been shining upon you? How does your day flower? Are you ready for the move? I certainly am!
{151}{}{Sim!}
{152}{}{Hum hum! Sem mudança!}
# Nuh uh! No move!
{153}{}{Vamos nessa.}
# Let's go.
{154}{}{Mudei de idéia.Não quero te ajudar.}
# I've changed my mind. I don't want to help you.
{155}{}{Estou tão empolgado que poderia soltar uma nuvem de pólen sobre mim! Vamos nessa!}
{156}{}{-feito-}
{157}{}{Uma pena, realmente uma pena. Espero que alguma hora você mude de idéia. Talvez o pólen da sua
 indecisão soprará novamente em meu caminho. Passar bem.}
# That's a pity, that's a pity indeed. I do hope you'll change your mind at some point. Perhaps the pollen of your
#  indecision will blow my way again. Good day.

{158}{}{Hã.}
# Uh.
{159}{}{Certamente. Passar bem.}
# Good day indeed.
{160}{}{Óooo... o solo aqui é tão... diferente. É de alguma forma mais limpo. Provavelmente por não compartilhá-lo com
 outras plantas.  Ahhh. Ah, sim! Se você encontrar o Professor e seu escorpião, lembre-se dessa manobra de xadrez:
 É chamada Flying Liver Attack, e o escorpião não pode resistir contra ela.}

# Oooh... the soil here feels so... different. Cleaner, somehow. Probably because I don't have to share it with
#  those other plants.  Ahhh. Oh! Yes! If you ever run across the Professor and his scorpion, remember this chess
#  maneuver: It's called the Flying Liver Attack, and the scorpion cannot stand against it.

{161}{}{Brigado!}
# 'Anks!
{162}{}{obrigado. Certamente vou usá-la. Tchau!}
# Thanks. I'll try that out. Bye!
{163}{}{Gostaria de informar que felizmente sei que o ghoul Typhon conhece o paradeiro de um tesouro secreto.
 Talvez essa informação seja útil algum dia.}

# I would also like to tell you that I happen to know the ghoul Typhon inside this building knows the whereabouts
# of a treasure trove. Perhaps that might be useful to you someday.

{164}{}{Brigado! Tchauu!}
# 'Anks! Byee!
{165}{}{Teve tempo de reconsiderar? Gostaria de me ajudar?}
# Have you had time to reconsider? Would you like to help me?
{166}{}{Sim!}
# 'Es!
{167}{}{Não!}
# Nuh!
{168}{}{Certo.}
{169}{}{Mim achar que não.}
# I think not.
{170}{}{Aliás, parece que você não tem uma pá. Enquanto você não achar uma, não posso ir. Aguardarei seu retorno com as pétalas .}
# Alas, you do not appear to have a shovel. Until you can find one, I can't go. I await your return with bated pistil.
{171}{}{Tchau.}
{172}{}{Psiu! Ei! Ei, colega! Venha aqui!}
# Psst! Hey! Hey, pal! Over here!
{173}{}{Vem cá! Prometo que não vou te machucar.}
# C'mere! I promise I won't hurt you.
{174}{}{Venha aqui. Está com medo de uma planta?}
# Come on. You scared of a plant
{175}{}{Olha aqui! Venha aqui falar comigo!}
# Over here! Let's get to it!
{176}{}{Sim, sou uma planta falante. Venha aqui e converse comigo.}
# Yes, I'm a talking plant. Get over it and talk to me.}
{177}{}{Opa, colega. Não é só começar a cavar. Primeiro temos que planejar a mudança. Vamos conversar sobre o assunto.}
# Whoa, friend. Don't just start digging. We've got to strategize the move first. Let's talk it over.
{178}{}{Você replantou Seymour próximo a casa do velho ghoul.}
# You replanted Seymour by the old-ghouls home.
{179}{}{Eu cavar! Plantar agora!}
# Haf shuvl! Plant now!
{180}{}{Por coincidência eu tenho uma pá aqui comigo. Vamos nessa.}
