#############################################################
#  Message File: KCaldo.msg                                 #
#                                                           #
#       Body Type:                                          #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 15                                              #
#       Skills to note: Barter 50                           #
#       Inventory: 2 bottles of booze, 1 bottle of beer     #
#                  and 2 molotov cocktails                  #
#  Log:                                                     #
#                                                           #
#  Created: January 14, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

# TRADUÇÃO: STATUS DO ARQUIVO - SEM REVISÃO
# SEM REVISÃO 2006
# SEM REVISÃO 2007
# SEM REVISÃO


{100}{}{Você vê um homem de aspecto doentio vestindo roupas imundas.}
{101}{}{Você vê Aldo, o anfitrião oficial da cidade. Você consegue sentir o cheiro do hálito dele de longe.}
# You see Aldo, the Town Greeter. You think you can see his breath from here.

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{200}{}{Olá! Nunca te vi aqui em Klamath antes. Sou Aldo, o anfitrião oficial da cidade (soluça). Meu trabalho é receber os visitantes e responder qualquer pergunta que eles possam ter sobre a nossa bucólica cidadezinha. Seja bem-vindo a Klamath. (soluça) Você seria...?}
{201}{}{Ah, valeu pelas boas-vindas. Sou só um viajante.}
{202}{}{Me chamo }
{203}{}{Valeu por me receber aqui.}
{204}{}{Sou o Escolhido de Arroyo.}
{205}{}{Não te interessa! Agora sai fora daqui, seu bêbado imundo!}
{206}{}{Não acredito que uma cidade como Klamath tenha um bêbado fedorento como você recebendo os visitantes ou fazendo qualquer outra coisa.}
#I don’t think a town like Klamath would have a drunk like you as a greeter, or anything else.

{300}{}{O Escolhido. Oh poderoso }
{301}{}{, você deve ser uma pessoa muito importante e poderosa entre os seus. Com certeza alguém da sua (soluça) categoria ficaria feliz de dar gorjeta ao anfitrião oficial da cidade, como de costume. (coff)}
{302}{}{Tá bom. Toma uma gorjeta. Mas fique longe da bebida um pouco.}
{303}{}{Uma gorjeta? Tá bom. Acho que vale a pena gastar $5 pra você parar de me encher o saco.}
{304}{}{Tá certo. Não sou eu que vou quebrar o costume de dar gorjetas. 5$ tá de bom tamanho? }
{305}{}{Acho melhor você me dar uma gorjeta, só assim não vou perder meu tempo livrando Klamath da sua pele imunda.}
{306}{}{Foi mal, mas dinheiro para o Escolhido tem pouca utilidade. Não tenho nenhum aqui comigo pra te dar.}

{350}{}{Bem }
{351}{}{, já que você é recente por aqui (soluça), e pelo visto precisa de uns conselhos, tenho que te dizer que em Klamath é costume dar gorjetas ao anfitrião oficial antes de perguntar qualquer coisa e tal.}

{355}{}{Foi mal, mas não posso gastar nenhum centavo com você.}
#Sorry, I can’t spare any money for you.

{400}{}{Bem, Forasteiro, tô vendo que você é (soluça) recente na área e não sabe (soluça) que por aqui é costume (soluça) dar gorjeta ao anfitrião oficial da cidade antes de perguntar qualquer coisa a ele.}

{450}{}{Muito obrigado pela grana, amizade! (coff). Vou usar esse dinheirinho pra comprar alguns remédios (soluça) pra minha garganta seca. Você já pode se considerar oficialmente recebido em Klamath. (coff) Quer saber algo sobre a nossa bela metrópole?}
{451}{}{Não, não se preocupe comigo. Dou meu jeito por aqui.}
{452}{}{Quero sim. Quero saber sobre algumas coisinhas. Uma ou duas.}
{453}{}{Aldo, eu tô procurando um comerciante que vende coisas antigas. Sabe, coisas velhas mesmo.}

{500}{}{Manda ver, meu benfeitor!}
{501}{}{O que as pessoas de Klamath fazem da vida?}
{502}{}{Onde consigo trocar coisas e encontrar medicamentos por aqui?}
{503}{}{Me fale mais sobre os geckos.}
{504}{}{Onde compra sua bebida?}
#Onde você compra bebida?
# Where do you buy your booze?
{505}{}{Valeu. Por enquanto é tudo o que preciso saber.}
{506}{}{Sabe onde posso encontrar um GECK?}

{550}{}{Muito obrigado (irônico)! Tomara que você não fique muito tempo em Klamath. Não precisamos do seu tipinho por aqui. Humph. Esses tribais... são todos iguais.}
# Thanks for nothing. I hope you don’t stay in town too long. We don’t need your kind here.
 Humph. Tribals -- they’re all the same.

{600}{}{Aqui em Klamath alguns são lavradores, enquanto outros criam brahmins, mas o que o povo daqui mais gosta é de caçar geckos.}
{601}{}{Gecko?! Que isso?}
{602}{}{Valeu! Por enquanto chega de papo.}
{603}{}{Interessante. Mas mudando de assunto...}

{650}{}{Gecko é um lagartão imenso que os caçadores adoram por causa da carne e do couro. Mas dá muito trabalho pegar os malditos -- e é perigoso também. Quer um conselho de amigo pra amigo? Evite! É uma trabalheira!}
{651}{}{Ah, valeu. Agora chega de conversa fiada.}
{652}{}{Hmm. Só mais uma coisinha, Aldo.}

{700}{}{Você pode comprar ou trocar coisas na Casa Buckner e no Gecko Dourado. Às vezes eles têm umas ervas medicinais pra vender também. Não que eles me dêem algumas delas pra curar (soluça) minha condição. São uns pães-duros dos infernos! Se atrasar um pouco o pagamento da conta, lá vai você na chuva e no frio.}
{701}{}{Valeu pelas informações. Por enquanto é tudo.}
{702}{}{Ah, sempre achei esse ar fresco revigorante. Hmm, mais uma perguntinha pra você.}

{750}{}{Sei que mais cedo você não podia gastar sua grana com o anfitrião oficial da cidade, mas talvez agora (soluça) você esteja se sentindo mais generoso e disposto a ser "oficialmente" recebido em Klamath.}
# I know that you couldn’t spare any money for the official town greeter earlier, but perhaps
 (hic) this time you are feeling more generous and are ready to be greeted ‘officially’ to Klamath.
{751}{}{Acho que vale a pena gastar $5 pra você parar de me enchar o saco.}
# I guess I could spare $5 to keep you off my back.
{752}{}{Senti que estava esquecendo alguma coisa. Aqui estão $5 pra você. Tô pronto pra receber suas saudações.}
{753}{}{Não, valeu. Acho que não preciso das suas saudações oficiais.}
# No, thanks, I don’t think I need your official greeting.
# Por que não enfia essas suas "saudações oficiais" na bunda?
{754}{}{Prefiro que suas tripas recebam minha lâmina.}
# I think I’d rather have your insides greet my blade

{800}{}{E aí! Que bom te ver! Por acaso não tem uma graninha aí pra eu comprar alguns medicamentos? Minha maldita garganta fica o tempo todo seca e áspera (soluça). Não tô nem podendo saudar (soluça) nossos visitantes.}
# Hey there, friend, good to see you again. Can you spare some money for a bit of medicine? My
 throat is getting dryer and scratchier (hic) all the time. I could even throw in another official
 (urp) greeting.
{801}{}{Claro! É sempre bom poder ajudar um amigo doente. Tome aqui $5.}
{802}{}{Foi mal, Aldo, mas não tô podendo gastar nem um centavo.}
{803}{}{Já chega de medicamentos. Você tem que colocar esse veneno pra fora do seu organismo com um pouco de trabalho pesado.}
# I think you’ve had enough medicine. You should sweat that poison out of your system with some
 hard work.

{810}{}{Muito obrigado (irônico)! Como pode ser tão cruel com um doente quanto eu? Malditos tribais! (Aldo cospe no seu pé e um pouco de baba escorre no queixo imundo dele)}
# Thanks for nothing. How can you be so cruel to someone as unwell as myself? Damn tribals!
 (Aldo spits on the ground at your feet, dribbling a bit on his scruffy chin)

{820}{}{Tenho certeza que a sua generosidade com alguém tão necessitado quanto eu (soluça) vai te dar sorte. Espero te ver de novo em breve. }
{830}{}{Tenho que gastar um pouco de grana com medicamentos. Tô me sentindo muito fraco. Mas se você não puder (coff, coff) me ajudar, eu até entendo (coff). Quem sabe da próxima, se eu ainda estiver (coff) por aqui até lá.}
# I could sure use some money for medicine. I feel pretty weak - but if you can’t (cough, cough)
 spare any (cough), I guess I understand. Maybe next time, if I’m still around (cough) by then.

{850}{}{Você quer dizer meus medicamentos extremamente necessários, né? (soluça) Normalmente eu compro no Gecko Dourado e na casa Buckner (urp), mas aqueles malditos não estão me vendendo nada até eu pagar uma parte da minha conta lá. Pra minha sorte, o Whiskey Bob tá fazendo uns remedinhos pra alguns dos seus amigos.}
# You mean my much needed medicine? (hic) Well, I used to buy it at either the Golden Gecko or
 the Buckner Place (urp), but they won’t sell it to me until I pay some money on my bill. Lucky for
 me, Whiskey Bob's been making a bit of medicine for some of his friends
{851}{}{Fico feliz em saber que você descobriu uma fonte pros seus remédios. Agora chega de jogar conversa fora.}
{852}{}{Interessante. E onde encontro esse Whiskey Bob?}
{853}{}{Valeu, Aldo. Agora mudando de assunto.}

{860}{}{Ele sempre fica aqui do lado, na Buckner. Acho que ultimamente ele não está conseguindo ir lá na cabana pra supervisionar o alambique. Não é uma fonte confiável de remédios pra alguém tão doente (coff, coff) quanto eu.}
# Whiskey Bob is usually (urp) at Buckner’s Place right here in downtown. I don't think he's
 been able to get out to tend his still lately. He's just not a reliable source of medicine for someone
 as (hic) unwell as myself.
{861}{}{Valeu pelas informações, Aldo. Chega de conversa por enquanto.}
{862}{}{Que bom que encontrou outro fornecedor. Ah, tem como você respirar um pouco mais na direção do vento? Tenho outra pergunta pra você.}
# Glad you found another supplier. Uh, could you breathe a bit more downwind? I’ve got another
 question for you.

{870}{}{E aí, amizade! Você tá parece meio confuso. O que precisa é de um amigo aqui na cidade. Sou Aldo, o anfitrião oficial da cidade.}
# Hello there, Friend -- you look a bit perplexed. What you need is an friend here in town. I’m
 Aldo, the town greeter
{871}{}{Mizade? Heh, heh, }
{872}{}{ gostar de amigo.}
{873}{}{Urk, (funga, funga) cheiro ruim. Você cair fora.}

{880}{}{Se me der $20 vou ser seu amigo e tenho certeza que todos aqui também serão. Assim que as coisas funcionam aqui na cidade grande.}
# If you give me $20 I’ll be your friend and I’ll make sure everyone else is, too. That’s how it
 works here in the big city
{881}{}{Viiinteee? Okkááá?}
# Toowa-eee-nty? Ook?  Beeg Cee-tee? Ook?
{882}{}{Dar folha bonita pra homi agora?}
# Give man pretty leaf now?
#estranho

{890}{}{Um Geck? Porra, você quer dizer gecko. Nunca escutei merda nenhuma sobre geck, mas vou te contar algumas coisas sobre gecko.}
# A Geck? Heck, you mean a gecko. Never heard about a geck but I’ll tell you about geckos.

{900}{}{Coisas antigas, heim? (urp) A única pessoa (soluça) que conheço que troca e vende coisas antigas é (soluça) o Vic.}
# Old stuff, huh? (urp) Well the only (hic) trader I know who trades much old stuff is
 (hic) Vic.
{901}{}{Vic? E onde encontro o Vic?}

{910}{}{Bom, faz um certo tempo que não vejo o Vic. Não sei exatamente pra que lugar ele pode ter ido. Se eu fosse você falaria com a Jenny lá na casa de banho. Ela e Vic são bem íntimos. Heh, heh, heh. Sacou? Não perdi meu tato.}
# Well now (hic), I haven’t seen Vic for a while. I don’t rightly (urp) know where he might have
 run off to. You might talk to (urp) Jenny over at the bath house. She and Vic were pretty (hic) thick.
 Heh, heh, heh. Get it? Oh my, I haven’t lost my touch.
{911}{}{É bom saber que não importa se está na parte mais funda do poço, você não pode perder o que nunca teve. Mudando de assunto...}
# It’s nice to know that no matter how low you sink, you can’t lose something you never had. Let
 me risk asking you something else.
{912}{}{Valeu! Você é sem igual, Aldo. Por enquanto é tudo.}
# Thankfully, you’re one-of-a-kind, Aldo. I guess that’s all I need to know