{100}{}{Você vê uma mulher vigorosa, já idosa e com um sorriso cansado no rosto.}
{101}{}{Você vê Ardin Buckner, a proprietária do Buckner house.}
{102}{}{Você vê uma coroa na casa dos cinqüenta, muito bem conservada.}

{110}{}{Você achou meu Smiley -- muito obrigada! Eu já tinha perdido as esperanças. 'Tô muito zangada com ele! Com o Smiley de volta, acho que não precisamos mais do Torr.}
{111}{}{Gecko morder Smiley. Smiley merreu.}
{112}{}{Fico feliz por poder ajudar. Mas vou ficar mais feliz ainda se você deixar o Sulik partir.}
{113}{}{Acho que ele prefere ficar com os geckos do que com você. Mas, mudando de assunto, eu tenho algumas perguntas.}
{114}{}{Não seja muito rígida com ele. Ele não 'tava se divertindo nem um pouco por lá. Tchau.}

{120}{}{Fiquei sabendo que você machucou o meu menino, o Torr. Não sei o que aconteceu ao certo, mas não quero você aqui por perto. Agora se manda.} 

{130}{}{Olá. Meu nome é Ardin Buckner e esta é a Buckner House.} 
{131}{}{Argl. Goop}
{132}{}{ É uma bela casa.}

{140}{}{Você me faz lembrar o meu garoto, Torr. Aposto que os dois se dariam muito bem. Por que não vai lá falar com ele? Tchau.} 

{150}{}{Olá! Meu nome é Ardin Buckner e sou a dona deste lugar. Mas me diga, você não viu um caçador chamado Smiley fora da cidade, viu? (Virando-se de lado) Ele se foi faz bastante tempo.  Eu nunca deveria ter deixado ele ir praquela expedição idiota.} 
{151}{}{Smiley? Não, não vi nenhum caçador com esse nome. Quem é ele, afinal?} 
{152}{}{No momento 'tô precisando de outra coisa.} 
{153}{}{Olá, Ardin. Acho melhor eu partir agora. Tchau.} 

{160}{}{Fale com a minha fílha, Maida. Eu não sei muito bem das coisas que andam
 acontecendo. Já é muito eu manter o olho no trabalho o todo tempo.}
{161}{}{Ah, 'tá bom, vou fazer isso. De qualquer maneira, preciso de algumas informações.} 
{162}{}{Certo, vou falar com ela então. Tchau.} 

{170}{}{É melhor você não estar planejando nenhum travessura por aqui. O que quer?} 
{171}{}{Pois não?}
{172}{}{Quero saber algumas coisas sobre Smiley, o Caçador.} 
{173}{}{Por acaso você é a pessoa certa pra falar sobre notícias e eventos locais?} 
{174}{}{Preciso de um quarto, por favor.} 
{175}{}{Precisamos de um quarto, por favor.} 
{176}{}{Quero comprar algumas coisas.} 
{177}{}{Pelo visto, não 'tô precisando de nada no momento. Tchau.} 

{180}{}{Bem, Smiley e eu estávamos discutindo muito. Pensei que finalmente o convenci a
 ficar e dirigir este lugar. Mas ele disse que precisava sair
 em uma última expedição.}
{181}{}{Uma expedição?}

{190}{}{Eu só cuido dos quartos aqui. Se quiser comprar ou trocar algo, fale com minha filha, Maida.}
{191}{}{Entendo. Fale-me sobre outras coisas.} 
{192}{}{Certo. Tchau.}

{200}{}{Estamos lotados hoje. Desculpe.}
{201}{}{Bem, vejamos. Acho que temos quartos disponíveis. O preço é $25.}
{202}{}{Eu vou ficar. Aqui estão os $25.}
{203}{}{Mudei de idéia. Deixa eu te perguntar algumas coisas.}
{204}{}{Acho que não preciso muito do quarto. Tchau.}

{210}{}{Acho que você não tem dinheiro suficiente.}
{211}{}{Opa. Acho que estou sem grana agora. Deixa eu te perguntar algumas coisas.}
{212}{}{Desculpe. Melhor arrumar um pouco de dinheiro, então. Tchau.}

{220}{}{Obrigada. Estou tão feliz por você ter encontrado meu garoto! Pensei que nunca veria esse bobo de novo.}
{221}{}{Torr amigo..}
{222}{}{Fico feliz por poder ajudar.}
{223}{}{Não havia algo mencionando uma recompensa?}

{230}{}{Bem, obrigada. Acho que você vai precisar de alguém pra te ajudar -
 uma companhia de viajem. Vou pedir pra Maida libertar o Sulik.}
{231}{}{Bem, eu não sei o que podemos fazer pra te agradecer.}
{232}{}{Torr amigo}
{233}{}{Não é preciso agradecer. Precisavam de ajuda e eu estava lá.}
{234}{}{Bem, dinheiro é sempre uma ótima maneira de dizer obrigado.}
{235}{}{Se você puder considerar o débito de Sulik como pago, poderia ser uma forma de recompensa.}
{236}{}{. Sulik amigo?}

{240}{}{Eu vou falar com a Maida e ela toma conta dos negócios com Sulik. Você deve querer falar com ela,
 sobre isso.}
{241}{}{Maida libertar Sulik. Maida }
{242}{}{Tenho certeza que Sulik ficará muito agradecido por você ter perdoado seus débitos. Eu vou falar
 com a Maida agora mesmo. Tchau.}
{243}{}{Fico contente que você não precise mais do Sulik. Tem algo que eu gostaria de pergunta.}
{244}{}{ amigo.}

{250}{}{Eu não tenho muito, mas aqui estão $100. Queria que fosse mais, mas com todas as Brahmins que
 perdemos isso é tudo o que posso dispor. Desculpe.}
{251}{}{Obrigado Sra. Buckner. Tchau.}
{252}{}{Talvez eu possa receber uma recompensa diferente.}

{260}{}{Bem, certamente há alguma coisa que eu possa fazer pra demonstrar o quão grata estou. Hmm... Eu vou
 perdoar a dívida do Sulik. Ele está livre. Acho que nem todos os tribais são arruaceiros.}
{261}{}{Por mim está bom. Tchau.}
{262}{}{Hmm, talvez eu possa receber uma recompensa diferente.}

{270}{}{Eu simplesmente não sei o que pensar. Meu Torr está perdido. Queria muito que alguém me ajudasse a
 achá-lo. Ele nunca demorou tanto pra voltar.}
{271}{}{Torr?}
{272}{}{O que aconteceu?}
{273}{}{Isso é legal, mas eu preciso de uma coisa de você.}
{274}{}{Posso ver que você está ocupada. Eu volto depois. Tchau.}

{280}{}{Ele se foi a noite passada. Eu fiquei com raiva dele depois que perdeu os últimos Brahmins. Nós simplesmente 
 não podemos nos dar ao luxo de perder mais, tudo que ele falava era sobre os homens-insetos leva-los. Aquele garoto idiota.}
{281}{}{Torr se foi?}
{282}{}{Acho que os Duntons tem algo a ver com o sumiço das brahmins. Você não deveria ser tão
 dura com o Torr. Pra onde você acha que ele pode ter ido?}
{283}{}{Pra onde você acha que ele pode ter ido?}

{290}{}{Bem, ele sempre fala que vai pegar os homens-inseto aonde eles vivem. Sabe, tem um
 anyon à leste do campo onde as brahmins pastam. De uns tempos pra cá costuma-se ouvir uns barulhos estranhos
 vindo de lá. }
{291}{}{Barulhos?}

{300}{}{Obrigado por prometer procurar meu garoto. Espero que você o ache. Estou tão preocupada com
 ele. Vá depressa, por favor.}
{301}{}{Ok.}

{310}{}{Você já achou meu garoto Eu não sei por quanto tempo ele vai conseguir se virar sozinho. Por favor, ache-o
 pra mim.}
{311}{}{Torr?}
{312}{}{Eu ainda não desisti, mas eu preciso de algo antes.}
{313}{}{Eu só queria saber se ele tinha voltado. Vou continuar procurando. Tchau.}

{320}{}{Torr afirmava que tinham homens-insetos que estava roubando nossas brahmins. Disse
 algo sobre provar pra nós. Queria tanto que alguém trouxesse meu garoto de volta...}
{321}{}{Torr canyon. }#acho que pode ficar assim mesmo
{322}{}{Não procurarei por Torr.}#?
{323}{}{Parece que aquele canyon parece um bom lugar pra começar a procurar. Vou achar o seu garoto
 Sra. Buckner.}
{324}{}{Eu adoraria ajudar -- se não estivesse tão ocupado. Tenho certeza de que Torr consegue se virar sozinho.
 Tchau.}
{325}{}{ irei procurar Torr.}#? procurar torr?

{330}{}{Bem, ele disse que era uma expedição. Me disse que achava que sabia de onde vêm todos os Golden Geckos
 e que queria achar o local. Pensou que talvez fosse um tipo de fonte mágica ou talvez
 uma caverna escondida ou um tipo de vault.}
{331}{}{Hmmm.}

{340}{}{Bem, eu não sei ao certo tudo o que ele disse, mas ele parecia bem excitado em sair. Eu
 não devia ter deixado ele ir. Ele já está duas semanas atrasado do prazo que deu pra voltar e isso me preocupa muito.}
{341}{}{Eu gostaria de ajudar. Eu poderia procurá-lo pra você.}
{342}{}{Desculpe ouvir isso. Deixa eu te perguntar outra coisa.}
{343}{}{Isso é mau, sra. Buckner. Talvez ele simplesmente volte pra você. Acho que sei porque ele voltaria, também.
 Tchau. }

{350}{}{Oh, obrigada. Deixa eu marcar no seu mapa o local que ele me falou. Eu espero que você consiga
 achá-lo pra mim. Ele não é muito, mas eu ainda o amo e sinto mais falta dele do que achei que pudesse ter. Por favor, ache-o
 pra mim.}
{351}{}{Eu vou achar. Deixe eu te perguntar mais algumas coisas primeiro.}
{352}{}{Vou dar o melhor de mim, sra. Buckner. Tchau.}
{353}{}{Sabe, acho que não posso te ajudar agora. Tchau.}

{360}{}{Você já achou o meu Smiley?}
{361}{}{Desculpe, sra. Buckner. Eu ainda estou procurando por ele. Deixe eu te perguntar algumas coisas.}
{362}{}{Não, eu estou indo agora mesmo procurar por ele. Tchau.}

{370}{}{Eu acho que alguma coisa horrível aconteceu com o meu pobre garoto, Torr. Eu estava contando com você (suspiro)
 pra achá-lo antes que fosse tarde demais. Quele pobre garotinho. Eu não acredito que confiei em você.}
{371}{}{Eu pensei que você pudesse ajudar meu pobre garotinho, Torr. Ele tinha uma alma tão boa e agora
 certamente está morto. Eu sinto tanta falta dele.}
{372}{}{Desculpe, sra. Buckner. Eu dei o melhor de mim para achá-lo. Er, mas tem algo que eu queria saber,
 no entanto.}
{373}{}{Talvez eu possa ajudar a recuperar o que sobrou do corpo dele pra você. Tchau.}
{374}{}{Torr? Quem ser Torr? (você dá de ombros) Tchau.}
{375}{}{Sinto muito -- eu queria ajudar, mas não pude. Er, eu odeio mencionar isso numa hora dessas,
 mas há algo de que eu preciso.}
{376}{}{Acho melhor voltar outra hora. Tchau.}

{380}{}{Bem, de certa forma isso não me surpreende muito. Eu gritei com meu pobre garotinho, mesmo eu sendo
 a culpada. (suspiro) Eu vou pegar aqueles Duntons. Ele foram longe demais dessa vez.}
{381}{}{Sinto muito por isso. Pra onde você acha que o Torr pode ter ido?}

{390}{}{Ok.}

{400}{}{Você já achou o meu Smiley?}
{401}{}{Quem? Ah, hã, não. Eu não sei pra onde ele foi. Mas... deixe eu te pergunta outra coisa.}
{402}{}{Ele está morto. Foi comido por geckos.}
{403}{}{Eu, hã, o vi. Ele disse que estava saindo com outra mulher. Opa! Olha só pras horas. Eu tenho que ir.}
{404}{}{Hã, eu, hã, nós, é que... Hã, não. Eu ainda estou procurando por ele. Tenho certeza de que ele aparecerá qualquer dia. Hã, tchau.}

{410}{}{Comido por geckos? Eu não acredito em você. Geckos nunca iriam capturar meu Smiley, ele é um caçador muito bom pra isso. Você deve ter se enganado.}
{411}{}{É, provavelmente você está certa. Desculpe pelo susto. Deixe eu te pergunta outra coisa.}
{412}{}{Não, eu o vi, ou o que sobrou dele. Não foi uma bela cena. Bem, te vejo mais tarde. Tchau.}
{413}{}{Acho que você me pegou. He, he, eu só estava brincando. É, é isso. Bem, tchau.}

{420}{}{Eu pensei que eles só estavam fazendo suas sacanagens de sempre! Meu pobre Torr. Eu vou dar um jeito naqueles dois palhaços agora mesmo. Eles não vão voltar a fazer isso. Obrigada.}
{421}{}{Fico feliz em ajudar, madame. Deixe eu te perguntar uma coisa.}
{422}{}{Aqueles Duntons me dão nojo. Fico feliz por você dar um jeito neles. Tchau.}

{500}{}{Eu acho que os irmãos Dunton estão roubando suas brahmins. Só achei que você deveria saber, madame.}
{510}{}{Você não viu um caçador chamado Smiley fora da cidade, viu? (virando de lado) Ele se foi há
 muito tempo. Nunca deveria ter deixado ele sair praquela expedição idiota.}
{520}{}{Você foi muito útil por aqui. Obrigada.}#You've been so helpful with things around here. Thanks. - acho que é a mulher mesmo
{530}{}{Só estava pensando no que mais está acontecendo por aqui.}

{600}{}{Você é demais.}
{610}{}{Você é demais. Trouxe meu filho Torr e meu Smiley de volta pra mim. Não há como te agradecer o suficiente.}
{620}{}{Você achou meu filho Torr. Muito obrigada.}
{630}{}{Você achou meu Smiley. Obrigada, muito obrigada.}
{640}{}{Fico feliz por ter ajudado. Seria uma pena perder duas pessoas tão queridas por você.}
{650}{}{Torr só precisa de um pouco da ajuda do tempo. Fico feliz por estar lá pra ajudá-lo.}
{660}{}{Smiley teve sorte dessa vez. Apenas diga pra ele pra tomar mais cuidado.}
{670}{}{Fico feliz por ajudar, sra. Buckner. Deixe eu te perguntar uma coisa.}
{680}{}{Gurrrrg bloop?}
{690}{}{Não há de quer, madame. Tchau.}

{700}{}{Torr está morto.}
{710}{}{Smiley está morto.}
{720}{}{Eu, hã, eu não sei onde eles estão. Posso te fazer uma pergunta?}
{730}{}{Eles estão mortos como pedra.}
{740}{}{Torr saiu? O que você quer dizer com isso?}
{750}{}{Eu não sei onde ele está. Deixe eu te perguntar algumas coisas, talvez eles retornem enquanto conversamos.}
{760}{}{Ainda estou procurando por eles. Acho melhor continuar. Tchau.}
{770}{}{Ainda estou procurando por ele. Acho melhor continuar. Tchau.}
{780}{}{Eu hã, não sei onde ele está. Hmm... Opa, olha só pras horas. Eu tenho que ir.}
{790}{}{Então, deixe eu te fazer algumas perguntas.}
{800}{}{Bem, há muito trabalho a ser feito. Tchau.}
{810}{}{Urrrrrgh.}

{900}{}{Você achou meu filho, Torr? Estou tão preocupada com ele.}
{910}{}{Já encontrou o meu Smiley?}
{920}{}{Já achou meu filho, Torr, ou meu amigo, Smiley o caçador?}
{930}{}{Meu pobre Torr saiu de casa.}

{940}{}{Eu não acredito em você.}
{942}{}{Ah, é verdade. Provavelmente eles são comida de vermes agora - bem, os pedaços que não viraram
 merda de gecko. Bem, te vejo por aí.}
{943}{}{Hã, eu acho que essa foi uma péssima *piada*, desculpe.}

{950}{}{Eu não quero falar com você.}
{951}{}{Cai fora daqui.}
{952}{}{Malditos tribais. Nada além de problemas.}
{953}{}{Saia daqui, selvagem.}
{954}{}{Eu não tolero seu tipo por aqui.}
{955}{}{Você não vai conseguir nada de mim, tribal.}
{956}{}{Você já causou problemas demais por aqui.}
{957}{}{Me deixe em paz.}
{958}{}{Tribal problemático, sai fora do meu estabelecimento.}
{959}{}{Já tive o suficiente de você. Cai fora.}