#############################################################
#  Cliente/caçadores de Golden Gecko (Klamath)      	    #
#  Traduzido por Ricardo Alvarenga                          #
#############################################################

{100}{}{Você vê um caçador mal vestido.}
{101}{}{Você vê um caçador bem forte.}
{102}{}{Você vê um caçador de geckos.}
{200}{}{Será bem servido aqui.}
{201}{}{Porque você não paga uma rodada de bebida pra nós?}
{202}{}{Vaí brigar com os Dunton?}
{203}{}{Parece que veio do norte de Den.}
{204}{}{O que está olhando?}
{205}{}{Você com certeza tem uma pele maravilhosa, amor. Heh, heh, heh.}
{206}{}{Urp, eu não me importaria de tomar mais um copo desse mijo de gecko.}
{207}{}{Se você precisar de dinheiro, os Duntons estão procurando por alguma ajuda.}
{208}{}{Por ser um tribal, até que você não é tão ruim.}
{209}{}{96 garrafas de mijo na parede, 96 garrafas de mijo...}
{210}{}{Eu vou para o sul para o Den, tem muito trabalho lá.}
{211}{}{Mais mijo de gecko, salve!}
{212}{}{A caçada com armadilhas não está indo bem, deve haver uma forma mais fácil de ganhar dinherio.}
{213}{}{Eu não estou tão bebado como pensa que estou.}
{214}{}{Ei amigo, parece que estes dados estão travados? (chocalho, chocalho)}
{215}{}{Fale com os Duntons ou com o barmen se busca trabalho, amigo.}
{216}{}{Você escolheu o bar perfeito para beber, amigo.}
{217}{}{Não, Bishop; com essa faca novamente.}
{218}{}{Alguém quer lançar os dados?}
{219}{}{Que bom que o Aldo não está fedendo novamente.}
{220}{}{Sempre fica com brahmins que não são seus?}
{221}{}{Cuidados com os espíritos que vagam.}
{222}{}{Há um espírito em um canyon leste daqui.}
{223}{}{Caçar é muito perigoso, uns tempos atras perdemos um ótimo caçador.}
{224}{}{Adorei esse truque de Torr.}
{300}{}{Olha quem vem aí.}
{301}{}{(murmuros, murmuros)...otímos pares de sapatos aqui..(murmuros)}
{302}{}{Você não está no lado errado da cidade?}
{303}{}{Não gostamos do seu tipo por aqui, tribal.}
{304}{}{Talvez se nos pagar uma bebida deixaremos você ficar.}
{305}{}{Empurre, tribal.}
{306}{}{O que você está encarando?}
{307}{}{Os Dutons irão dar um jeito em você, tribal.}
{308}{}{Você escolheu o lugar errado para beber.}
{309}{}{Sua mãe não esta aqui jovem, esperimente a casa de banho (Bathhouse).}
{310}{}{Por que você não vai brincar em outro lugar?}
{311}{}{Lá fora, a oeste daqui, têm um canyon onde poderia se perder.}
{312}{}{O que deseja?}
{313}{}{É melhor cuidar da sua vida.}
{314}{}{Seu nome é Torr? (heh, heh, heh)}
{315}{}{Vamos beber com Aldo, você quer?}
{316}{}{Aqui não é lugar pra você, seu merda.}
{317}{}{Você não é do tipo de amigo que eu chamo pra beber.}
{318}{}{Humph. (cospe no chão)}
{319}{}{Pelo jeito você não é muito de olhar.}
{320}{}{Ainda está se sentindo desconfortável?}