#################################################
# Smiley (KLAMATH)                              #
#################################################

# You see a filthy trapper with torn and bloodstained clothing. He appears to be favoring one leg slightly.
{100}{}{Você vê um caçador sujo com a roupa rasgada e manchada de sangue. Parece que está se apoiando sobre uma perna só.}

# You see Smiley, the trapper. He's limping a bit and looks unhappy.
{101}{}{Você vê Smiley, o caçador. Ele está mancando um pouco e parece descontente.}

# You see Smiley, the trapper. He looks a lot better since you rescued him from the caves.
{102}{}{Você vê Smiley, o caçador. Ele parece estar bem melhor desde que você o resgatou das cavernas.}

# You see a middle-aged man wearing the bloody and torn clothes of a trapper. He doesn't look
 very well.
{103}{}{Você vê um homem de meia-idade vestindo as roupas ensanguentadas e rasgadas de um caçador. 
 Ele não parece estar bem.}
 
# You see Smiley, the trapper. He looks as though his health has improved greatly since you
 rescued him from the cave.
{104}{}{Você vê Smiley, o caçador. Parece que sua saúde melhorou muito desde que você o salvou da caverna.}

# Hello there, stranger. People call me Smiley. I'm sure glad to see you. I thought I was going
 to die here for certain! I'm hurt too bad to get past those damn lizards on my own.
{110}{}{Olá, estranho. As pessoas me chamam de Smiley. Fico feliz em te ver. Tinha certeza que iria
 morrer aqui, estou muito machucado para passar por aqueles malditos lagartos.}
 
# Smiley, heh, heh, heh. Ook.
{111}{}{Smiley, heh, heh, heh. Ook.}

# What are you doing here?
{112}{}{O que faz aqui?}

# Nice to meet you, Smiley. I think I'll be going now.
{113}{}{Prazer em conhecê-lo, Smiley. Preciso ir agora.}

# Great. Another Torr. I (points at himself) need you (points at you) to help me get out of here
 (makes walking fingers motion on hand).
{120}{}{Ótimo! Outro Torr. Eu (aponta para si mesmo) preciso de você (aponta para você) para me ajudar a sair 
 daqui (faz um gesto de caminhar com os dedos da mão).}

# Go? Now? Ook 
{121}{}{Ir? Agora? Sim! }

#  go. Bad lizards! Bad!
#{122}{}{ vamos. Lagartos maus! Maus!}

# Yes! That's it. We go (walking fingers again) together (clasps hands together). Right now!
{130}{}{Sim! É isso aí. Nós vamos (andando com os dedos novamente) juntos (fecha as mãos juntas). Agora!}

# Smiley go with 
{131}{}{Smiley ir com }

#  now.
{132}{}{ agora.}

# Smiley no go with 
{133}{}{Smiley não ir com }

# . No like Smiley. Goodbye.
{134}{}{. Não gosta Smiley. Adeus.}

# Hey! Wait! You can't just leave me here.
{140}{}{Ei! Espere! Você não pode me abandonar aqui.}

# Oh, sorry. What was I thinking?
{141}{}{Oh, desculpe. O que eu estava pensando?}

# Well, I guess not.
{142}{}{Bem, suponho que não.}

# I can and I will. I think I'm going to do just that. Goodbye.
{143}{}{Posso e farei. Acho que vou fazer exatamente isso. Tchau.}

# I always caught more golden geckos north and west of Klamath than anywheres else. So I figured
 that all the golden geckos lived someplace up here.
{150}{}{Eu sempre caçava mais geckos dourados no norte e oeste de Klamath do que em qualquer outro lugar. Até que
 percebi que todos os geckos dourados vivem por aqui.}
 
# Looks like you were right.
{151}{}{Parece que você estava certo.}

# I'd love to chat with you, but let's just get out of here now and chat later. Okay?
{160}{}{Eu adoraria ficar e conversar com você, mas vamos sair daqui e conversar depois. Ok?}

# Uh, yeah. I guess that's a good idea.
{161}{}{É, verdade. Boa ideia.}

# Just one question, first. What do you know about these caves?
{162}{}{Mas antes, uma pergunta. O que sabe sobre esta caverna?}

# Looks as though I was a little too right. I got in here okay, but then one of those damn geckos
 got behind me and damn near took my leg off. I just barely made it over here.
{170}{}{Parece que eu estava certo demais. Quando entrei aqui estava bem, mas então um daqueles geckos malditos ficou bem
 atrás de mim e pegou minha perna. Tive sorte de conseguir chegar até aqui.}
 
# I wonder why they didn't finish you off?
{171}{}{Por que será que ele não matou você?}

# Well, I guess they don't like to crawl through the goo too much. I can't say as I blame them.
 It sure burns if gets on your skin. But that doesn't seem to stop 'em from licking up the darn stuff
 like it was Buckner's Best.
{180}{}{É, acho que eles não gostam muito de rastejar por aqui. Não posso culpá-los. Queima quando encosta
 na pele. Mas isso não impede os malditos de lamberem essa coisa como se fosse uma Buckner's Best.}
 
# Interesting.
{181}{}{Interessante.}

# Enough gum flapping. Now let's get out of here. I figure that if I can join you we should both
 be able to make it out of here okay. I sure could use the help.
{190}{}{Chega de conversa fiada. Agora vamos sair daqui. Acho que se nos juntarmos podemos sair daqui tranquilos.
 Eu preciso de uma mão.}
 
# Ok. You can join me. I'll make sure you get out of here and back to Klamath. I think that Ardin
 is going to be glad to see you again.
{191}{}{Ok. Pode vir comigo. Eu vou te tirar daqui e levar de volta para Klamath. Acho que a Ardin ficará feliz 
 em vê-lo de novo.
 
# Well, OK. But I don't want you whining for help all the time.
{192}{}{Ok. Mas não quero ouvir você choramingando no caminho.}

# These caves look like a prewar storage area. I think there must be more down below us but
 there's some kind of fancy teck-no-logical lock on the door. Anyhow, I've had enough. Let's git out of
 here.
{200}{}{Essas cavernas parecem um depósito da época pre-guerra. Deve ter mais no subsolo, mas tem uma bugiganga
tecnologica trancando a porta. De qualquer forma, eu já estou de saco cheio. Vamos cair fora daqui.}

# OK.
{201}{}{OK.}

# Whew. I think I just used up some lives that time around. Why don't you come over to the
 Buckner place a little later on and I'll make sure you get a nice reward for saving me.
{210}{}{Ufa. Dessa vez eu fiquei no bico do corvo. Por que você não passa na Buckner depois para receber 
uma recompensa por me salvar?

# Thanks, Smiley. I was happy to do it. Goodbye.
{211}{}{Valeu, Smiley. Fico feliz em ajudar. Adeus.}

# OK, whatever. Goodbye.
{212}{}{Ok, tanto faz. Adeus.}

# About time you mentioned a reward. It better be a good one. Goodbye.
{213}{}{Finalmente você mencionou uma recompensa. Espero que seja boa. Adeus.}

# Well, if'n it ain't my idjit friend. Thanks a heap. Goodbye to you.
{220}{}{Oh, she num ééé camaradinha idiota. Valeu mesmo. Adeus.}

# Hello there, friend. Thanks again for getting me out of that tight spot. Anything I can help you
 with?
{221}{}{E ae, camarada. Obrigado por me tirar daquela roubada. Posso te ajudar em alguma coisa?}

# Anything else, friend?
{222}{}{Mais alguma coisa, camarada?}

# Well, I had a few questions about hunting geckos.
{223}{}{É que eu preciso de umas dicas para caçar geckos.}

# I have all sorts of questions about this area.
{224}{}{Tenho muitas perguntas sobre essa região.}

# Is Mrs. Buckner happy to see you back?
{225}{}{A senhora Buckner ficou feliz em te ver?}

# No, I guess I just wanted to say hello. Talk to you later, Smiley. Goodbye.
{226}{}{Não, só passei para dar um oi. Conversamos depois, Smiley. Adeus.}

# I sure owe you for saving my hide. Least I can do is to teach you something in return.
{230}{}{Eu te devo uma por salvar minha pele. O mínimo que eu posso te fazer é ensinar alguma coisa.}

# Teach?
{231}{}{Ensinar?}

# Thanks Smiley. I'd sure appreciate any tips you could give me.
{232}{}{Valeu Smiley. Qualquer dica que me der vai ajudar.}

# Since those geckos nearly had my hide let me teach you how to get theirs. Here's how you skin 'em. (Smiley
 demonstrates) ...and when you kill 'em you can get their hides an' sell 'em. OK?
{240}{}{Já que os geckos quase arrancaram meu couro, deixe-me te ensinar como arrancar o deles. É assim que 
 você esfola eles. (Smiley demonstra) ... e quando você matar um deles, pode tirar a pele e vender. OK?}
 
# Urk. Pretty, heh, heh, heh. Sell. Heh, heh, heh. Bye.
{241}{}{Argh. Beleza, heh, heh, heh. Vende. Heh, heh, heh. Até.}

# Thanks, I'm sure that will come in handy. Tell me something else though.
{242}{}{Valeu, isso vai ser muito útil. Mas vamos conversar sobre outra coisa.}

# Thanks for showing me how to do that, Smiley. I think I'll go practice on some geckos. Goodbye.
{243}{}{Obrigado por me mostrar como fazer isso, Smiley. Achou que vou praticar em alguns geckos. Adeus.}

# I think you know enough about geckos now. 
{250}{}{Acho que você já sabe o suficiente sobre geckos agora.}

# Heh, heh. I think maybe you could teach me something about geckos. I don't think I can help you
 out with that.
{251}{}{Heh, heh. Acho que você que deveria me ensinar algo sobre geckos. Eu não posso te ajudar com isso.}

# Well, I guess I know more about geckos than anyone alive. I was raised on gecko milk, you know.
 But it'll take a few hours.
{252}{}{Bom, acho que sou o maior especialista em geckos do mundo. Sabia que eu cresci tomando leite de gecko?
 Mas vai levar umas horas.}
 
# I want to know all you can teach me about geckos.
{253}{}{Eu quero aprender tudo que você sabe sobre geckos.}

# I guess I don't need to know about that right now. Tell me something else though.
{254}{}{Acho que não preciso aprender isso agora. Me fale sobre outra coisa.}

# {Gecko milk? I thought geckos were reptiles.
{255}{Leite de gecko? Eu pensei que eles eram répteis.}

# There's more you need to know than you even know you need.
{260}{}{Existe mais para saber do que você imagina.}

# Teach me, oh great trapper.
{261}{}{Ensine-me, oh grande caçador.}

# Uh, yes. Go ahead. I'm listening.
{262}{}{Uh, claro. Vá em frente. Estou ouvindo.}

# Well, okay. Spin your tall tales. I'll listen.
{263}{}{Claro, ok. Conte seus causos. Estou ouvindo.}

# Maybe I don't need to know about this. Goodbye.
{264}{}{Talvez eu não precise aprender sobre isso. Adeus.}

# Well, you see it's like this - golden geckos and regular geckos are basically the same critter
 except the golden's got a big second helping of sheer cussedness... (time passes as you learn the lore
 of the Gecko)
{270}{}{Olha, você faz assim - golden geckos e geckos comuns são basicamente a mesma coisa, só que os 
 golden são muito mais desgraçados... (o tempo passa enquanto você aprende sobre a cultura Gecko)}
 
# That was great. I think I know a lot more about geckos now. Thanks. Goodbye.
{271}{}{Isso é incrível. Sinto que sei muito mais sobre geckos agora. Valeu. Falou.}

# Maida Buckner, Widow Buckner's daughter, is the one to talk to about all sorts of town gossip.
{280}{}{Maida Buckner, a filha da viúva Buckner, conhece todo tipo de boato da cidade.}

# Let me ask you something else, then.
{281}{}{Deixa eu te perguntar outra coisa, então.}

# Oh, I see. Thanks. Goodbye.
{282}{}{Entendo. Adeus.}

# Widow Buckner's so darn happy to have me back that she may be Mrs. Smiley before too long. She
 was even talking about giving you a little something for finding my hairy butt and returning it to her.
{290}{}{A senhora Buckner esta tão feliz em me ter de volta que é capaz dela se tornar senhora Smiley em breve.
 Ela até estava falando sobre te dar uma recompensa por devolver minha bunda peluda para ela.}
 
# I'm happy for the two of you. Let me ask you something else.
{291}{}{Fico feliz pelo casal. Deixa eu perguntar outra coisa.}

# That's great. I'll have to talk to her. Goodbye.
{292}{}{Que bom. Eu preciso falar com ela. Adeus.}

# Hey, thanks for saving my sorry ass. I better high-tail it back to Klamath. See you there.
{300}{}{Ei, obrigado por salvar meu pescoço. É melhor eu correr de volta para Klamath. Te vejo por aí.}

# Don't worry about me. I can make it back from here on my own.
{310}{}{Não se preocupe comigo. Posso voltar sozinho daqui.}

# You gain 
{320}{}{Você ganhou }

#  experience points for rescuing Smiley.
{330}{}{ pontos de experiência por resgatar Smiley.}

