# You see a scruffy looking person.
{100}{}{Você vê uma pessoa esfarrapada.}
# You see a citizen of Klamath.
{101}{}{Você um cidadão de Klamath.}
# You see a squatter.
{102}{}{Você vê um posseiro.}
# You see a backwoodsman.
{103}{}{Você vê um sertanejo.}
# You see a trapper.
{104}{}{Você vê um caçador.}
# You see a trapper.
{105}{}{Você vê um caçador.}
# Heh, heh - you reckon you're one of us now?
{110}{}{Heh, heh - você sabe que é um de nós agora?}
# We ain't got nothing left to steal here.
{111}{}{Não sobrou nada para ser roubado aqui.}
# Trapper Town's got bigger rats every day. Some even stand erect.
{112}{}{Os ratos do Bairro dos Caçadores ficam maiores a cada dia. Alguns até andam em duas pernas.}
# No room for you here.
{113}{}{Não há lugar para você aqui.}

# No squats left here.
{114}{}{Não sobraram posseiros aqui.}

# What are you looking at?
{115}{}{O que você está olhando?}

# Damn tribals, always stirring up trouble.
{116}{}{Malditos índios, sempre causando problemas.}

# You should go south.
{117}{}{Você deveria ir para o sul.}

# Something smells worse than a gecko pelt.
{118}{}{Alguma coisa esta fedendo mais que pele de gecko.}

# Rats everywhere!
{119}{}{Ratos em toda parte!}

# By the Great Rat Spirit, what's next?
{120}{}{Pelo Grande Rato Espiritual, o que agora?}

# I'd offer a prayer to the Great Rat Spirit if you're in town for long.
{121}{}{Eu faria uma prece para o Grande Rato Espiritual se você estivesse na cidade há mais tempo.}

# Watch out, or you'll end up just like Phil.
{122}{}{Cuidado, ou você vai acabar igual o Phil.}

# You're just like the Duntons.
{123}{}{Você é igual os Duntons.}

# I don't think we want you in this part of town.
{124}{}{Nós não queremos você nesse canto da cidade.}

# What's your problem?
{125}{}{Qual o seu problema?}

# (Mumble, mumble)...only one kind of good tribal, and that's a...(mumble)
{126}{}{(Murmura, murmura)... só há um tipo de índio bom, e é... (murmura)}

# This part of town's for us professionals only.
{130}{}{Essa parte da cidade é apenas para nós, profissionais.}

# Hmm... You don't look as though you could find a gecko if it bit you.
{131}{}{Hmm... Você tem cara de quem não consegue achar um gecko nem que ele te morda.}

# I'm surprised you made it all the way here from your tribe.
{132}{}{Me surpreende que você tenha chegado da sua tribo até aqui.}

# Watch out for the rats here.
{133}{}{Cuidado com os ratos daqui.}

# Golden geckos can grow five times as long as a man is tall.
{134}{}{Golden geckos podem crescer até cinco vezes mais que o tamanho de um homem.}

# Them golden geckos have a deadly poison in their fangs.
{135}{}{Os golden geckos tem um veneno mortal em suas presas.}

# Anyone seen Phil? I think we lost another trapper to the rats last night.
{136}{}{Alguém viu o Phil? Acho que perdemos mais um caçador para os ratos essa noite.}

# Have you seen Phil?
{137}{}{Você viu o Phil?}

# Those rats are so hungry these days.
{138}{}{Esses ratos estão famintos ultimamente.}

# There are supposed to be old mine tunnels underneath here.
{139}{}{Supostamente existem túneis abandonados lá embaixo.}

# Wish I could figure out how to get to that Corvega.
{140}{}{Gostaria de saber como chegar até Corvega.}

# Watch out for slavers. They just love to take tribals.
{141}{}{Cuidado com os escravagistas. Eles gostam de capturar índios.}

# I sure wish I had enough money to get a bath.
{142}{}{Eu bem que gostaria de ter dinheiro suficiente para um banho.}

# I want to go visit my Jenny.
{143}{}{Eu quero visitar minha Jenny.}

# Another few pelts and I'll be able to buy myself a bath.
{144}{}{Mais algumas peles e vou poder pagar um banho pra mim.}

# Mmm, I love that Dunton's Drymeat.
{145}{}{Mmm, eu adoro essa carne seca do Dunton.}

# If the bugmen ever show up here, the rats will eat them. Heh, heh.
{146}{}{Se os homem-inseto aparecem aqui, os ratos vão devorá-los. Heh, heh.}

# Yessir, there are old tunnels underneath Klamath. You better believe it.
{147}{}{Sim senhor, tem alguns túneis abaixo de Klamath. Pode acreditar nisso.}

# Lots of stuff crawling around in those buildings.
{148}{}{Muitas coisas se escondem nesses edifícios.}

# You look as though you know your way around the woods.
{150}{}{Parece que você sabe se virar pelas florestas.}

# Trapping geckos is dangerous -- but it pays well.
{151}{}{Caçar geckos é perigoso -- mas paga bem.}

# I hate all the rats here. They're too dang smart for the traps!
{152}{}{Odeio esses ratos. Eles são espertos demais para cair em armadilhas!}

# Watch out for golden geckos; they're twice as tough as the ordinary ones.
{153}{}{Cuidado com os golden geckos; eles tem o dobro da força dos normais.}

# You're from the Arroyo tribe, ain't you? Can tell by your looks.
{154}{}{Você é da tribo de Arroyo, não é? Posso dizer só de olhar para você.}

# Sometimes I think I've seen a really big rat back in the buildings here.
{155}{}{As vezes acho que vi um rato gigantesco em um dos edifícios aqui.}

# It's cheap to live here, but you have to put up with rats.
{156}{}{É barato viver aqui, mas tem que suportar os ratos.}

# (Chewing noisily) Rat tastes better than most people think. Hungry?
{157}{}{(Mastigando bem alto) Ratos são mais gostosos que muita gente pensa. Tá com fome?}

# You know, geckos taste a lot like something else if you cook them right. Can't rightly
 remember what, though.
{158}{}{Sabe, geckos tem um gosto bem parecido com alguma coisa se você cozinhá-los direito. 
 Não me lembro direito de quê.}
 
# Some animals like drymeat so much that they'll run for it instead of you.
{159}{}{Alguns animais gostam tanto de carne seca que eles atacam ela ao invés de você.}

# Remember, if you ever sell too many gecko hides at once, their price will drop.
{160}{}{Lembre-se, se você vender muitas peles de gecko de uma vez só, o preço vai cair.}

# Someday, I want to get a weapon with some range to it.
{161}{}{Um dia, eu quero conseguir uma arma com alcance maior.}

# I swear I've seen bugmen out near the brahmin grazing area east of town. 
{162}{}{Eu juro que vi uns homens-inseto rondando os brahmin na área de pastagem ao leste da cidade.}

# I hated the rats here. I'm sure glad they're gone.
{170}{}{Eu odiava os ratos daqui. Estou feliz que eles se foram.}

# Trapping geckos is dangerous but it pays well.
{171}{}{Caçar geckos é perigoso mas paga bem.}

# Watch out for golden geckos, they're twice as tough as the ordinary ones.
{172}{}{Cuidado com os golden geckos; eles tem o dobro da força dos normais.}

# You're from the Arroyo tribe ain't you? Can tell by your looks.
{173}{}{Você é da tribo de Arroyo, não é? Posso dizer só de olhar para você.}

# There used to be a lot more rats. Can't say's I miss 'em.
{174}{}{Costumava ter bem mais ratos. Não posso dizer que sinto falta deles.}

# Those rats been deserting this place like it was sinkin'.
{175}{}{Os ratos estão desertando esse lugar como se estivesse afundando.}

# (Chewing noisily) Rat tastes better than most people think. Hungry?
{176}{}{(Mastigando bem alto) Ratos são mais gostosos que muita gente pensa. Tá com fome?}

# You know geckos taste a lot like something else if you cook them right. Can't
 rightly remember what though.
{177}{}{Sabe, geckos tem um gosto bem parecido com alguma coisa se você cozinhá-los direito. 
 Não me lembro direito de quê.}
 
# Some animals like drymeat so much that they'll run for it instead of you.
{178}{}{Alguns animais gostam tanto de carne seca que eles atacam ela ao invés de você.}

# I haven't heard that weird voice comin' from the rat caves lately. Wonder
 where it went?
{179}{}{Faz tempo que não ouço aquela voz estranho que vinha das cavernas dos ratos. O que será que houve?}

# Y'know, don't laugh at me, but I think the Rat God's dead.
{180}{}{Olha, não ria de mim, mas acho que o Deus Rato está morto.}

# I heard that the Rat God's dead. Not that I believe in stuff like that.
{181}{}{Ouvi falar que o Deus Rato está morto. Não que eu acredite nessas coisas.}

# You see a rough-hewn person with leather boots.
{200}{}{Você vê uma pessoa tosca com botas de couro.}

# You see a person who must spend a lot of time outdoors.
{201}{}{Você vê uma pessoa que deve passar muito tempo ao ar livre.}

# You see a person with roughly made and repaired clothing.
{202}{}{Você vê uma pessoa com roupas toscas e remendadas.}

# You see a rough-hewn trapper with gecko-hide boots.
{203}{}{Você vê um caçador tosco com botas de couro de gecko.}

# You see someone who spends a lot of time in the wilderness. They're wearing
 a gecko-pelt shirt.
{204}{}{Você vê alguém que passa muito tempo nos desertos. Eles estão usando camisas de pele de gecko.}
 
# You see a trapper who makes his home in Trapper Town.
{205}{}{Você vê um caçador que mora no Bairro dos Caçadores.}