#############################################################
#  Message File: mcChild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Um garotinho.}
{101}{}{Uma garotinha.}

{120}{}{Um garotinho. Ele parece bem alegre.} 
{121}{}{Uma garotinha. Ela parece bem alegre.} 
#############################################################
#  The following lines are floaters for children            #
#############################################################
{150}{}{Não me coma!}
{151}{}{Eeeee! Um bicho-papão!}
# The boogy-monster!
{152}{}{Papai disse que você é uma pessoa má.} 
{153}{}{Aieeee! Correeee!}
{154}{}{Você tá me assustando.}
{155}{}{Pare de me olhar.}
{156}{}{Não posso falar com tribais.}
# I'm not supposed to talk to tribals.
{157}{}{Cachorro salsicha.} 
# Wiener dog.
{158}{}{Mamãe disse que se eu fizer besteiras você vai me comer.} 
{159}{}{Não tenho medo de você}
{160}{}{Socorroooo!}
{161}{}{Tá trás de mim!}
# It's after me!
# Me segue!
{162}{}{Por favor não me machuque!}
{163}{}{Fique longe de mim!} 
{164}{}{Eeeeeeeee!}
{165}{}{Te odeio!}
{166}{}{Mamãe mamãe mamãe!}
{167}{}{Me deixe só!} 
{168}{}{Seu fedido!}
# You stink!

{170}{}{Olá.}
{171}{}{Quer brincar de casinha?} 
{172}{}{Você enfia mesmo um osso no nariz?} 
# Do you really poke a bone through your nose?
{173}{}{Por que você parece tão engraçado?} 
# How come you're so funny looking?
# Caraca! Por que você parece tão engraçado?
{174}{}{Minha mãe disse que você é um primitivo.} 
# My mom says you're primitive.
{175}{}{Sua tribo já parou de comer pessoas?}
# Has your tribe stopped eating people?
{176}{}{Quem te vestiu desse jeito tão engraçado?}
# Who dressed you so funny?
{177}{}{Aposto que você é mais legal do que aparenta.}
# I'll bet you're nicer than you look.
# Aposto que você é mais legal do que sua aparência.
{178}{}{Vamos brincar de pique-pega. Tá com você!} 
# Let's play tag. You're it.
{179}{}{Você não fede tanto.} 
# You don't smell that bad.
{180}{}{Já viu meu amigo invisível?}
{181}{}{Quero viajar o mundo quando tiver sua idade.}
# I want to travel the world when I'm as old as you.
# Quando eu ficar grande igual a você, quero viajar o mundo.
{182}{}{Você é um tribal legal, nem parece com os outros.}
# You’re a nice tribal, not like the others.
# Você é um bonito tribal, nem parece com os outros.
{183}{}{Aposto que toma banho.} 
# I bet you do bathe.
{184}{}{Tribal!! ururururuuuu - ururur!!}
# É mais inteligente que o Torr. 
{185}{}{Essa lâmina é afiada mesmo?} 
{186}{}{Quando eu crescer quero ser igual a você.}
# I want to be just like you when I grow up.
{187}{}{Meu cachorro adora carne seca.} 
{188}{}{Tenho uma pedrinha brilhante.} 
# I’ve got a shiny pebble.
{189}{}{Já viu meu amigo invisível?}

{190}{}{Posso ser da sua tribo?}
{191}{}{Você é legal.}
{192}{}{Você parece engraçado.}
{193}{}{Tá vestindo o quê?}
# Whatcha wearing?
{194}{}{Quero andar numa brahmin!} 
# I want a brahmin ride!
{195}{}{Veio de muito longe?}
{196}{}{Weeee! Ha, ha, ha!}
{197}{}{Não vá!}
{198}{}{Tem comida aí?}
{199}{}{Tô te incomodando?}
{200}{}{Tá indo aonde?}
# Where ya going
{201}{}{Posso ir com você?}
# Can I come with you?
{202}{}{Quantos anos tem?}
{203}{}{Qual é o seu nome?}
{204}{}{Gosta de crianças?}
{205}{}{Que isso?}
{206}{}{Quer brincar?}
# Do you wanna play a game?
{207}{}{O que tá fazendo?}
# Whatcha doing?
{208}{}{Já viu um besouro?}
# Have you seen any bugs?
{209}{}{Onde conseguiu isso?}
# Where did you get that?
{210}{}{Me dá?}
# Can I have that?
{211}{}{O que faz?}
{212}{}{Eu corro muito rápido. Quer ver?}
# I can run fast. Wanna see?
{213}{}{Olha pra cá! Olha apra cá!}
# Watch me! Watch me!
{214}{}{Mamãe diz que eu falo muito.}
{215}{}{Onde mora?}
{216}{}{Heeee! Heeee!}
{217}{}{Vai ficar por aqui?}
{218}{}{Tem filhos?}
{219}{}{Por que veio aqui?}
{220}{}{Gosto de você.}
{221}{}{Você gosta de mim?}
{222}{}{Você é casado?}
{223}{}{Um, Dois, três... e jááááá!}

{300}{}{Um estranho!}