{100}{}{Um garotinho.} 
{101}{}{Jonny.}
{102}{}{Cabelo louro, olhos azuis; um típico garoto americano da cabeça aos pés.} 
# Blonde hair, blue eyes; your typical all-American looking kid.

{150}{}{Buááa!} 
{151}{}{Quero meu cachorro de volta!} 
{152}{}{Sniiifff... } 
# Whimper…
{153}{}{Um estranho!} 
{154}{}{Laddie! Senti sua falta. Obrigado por devolver meu cão.} 
# Laddie! I’ve missed you, boy. Thank you for bringing my dog back to me.
{155}{}{Olá, nunca te vi por aqui antes.} 
# Hello, I haven’t seen you around here before.
{156}{}{Seu nome é Jonny?} 
{157}{}{Qual é o seu nome, garoto?} 
{158}{}{Me fale seu nome, monstrinho.} 
{159}{}{Quer um doce, garotinho?} 
# Would you like some candy, little kid?
{160}{}{Oi de novo.} 
{166}{}{Seus pais me pediram pra te buscar.} 
# Your mother and father have sent me to find you.
{168}{}{Já falou com Vegeir sobre minha volta pra casa?} 
# Have you talked to Vegeir about me going home?
{169}{}{Falei sim. Ele quer que seus pais desçam aqui pra te buscar.} 
# Yes. He says he wants your parents to come down and get you.
{170}{}{Não, ainda não.} 
{171}{}{Meu pai disse que Laddie foi com você me procurar. Cadê ela? Tô com saudades.} 
# My dad said Laddie went with you to look for me. Where is he? I miss him.
{172}{}{Sinto muito, Jonny. Laddie morreu enquanto estávamos te procurando.} 
# I’m sorry Jonny. Laddie died while we were searching for you.
{173}{}{Rose disse que ia atrás da sua cadela.} 
# Rose said she would look after your dog.
{174}{}{Meu nome é Jonny. E o seu?} 
{175}{}{Me chamo } 
{176}{}{.}
{177}{}{Meu nome não vem ao caso.} 
{178}{}{Meu nome é Jonny e eu não gosto de você.} 
{179}{}{[Ele aponta pra você e começa a berrar.] Um estranho! Um estranho! Um estranho!} 
# [He points to you and starts screaming.] Stranger! Stranger! Stranger!
{180}{}{Muito bom te ver } 
{181}{}{.}
{182}{}{Te vejo por aí, garoto.} 
{183}{}{Que bom! Quero ir pra casa, mas Vegeir disse que seu pessoal não pode andar pela superficie e por isso não podem me levar. Não que eu suspeite de você, mas qual é o nome do meu pai?}
# That’s swell! I wanted to go home, but Vegeir says his people can’t travel that far above
# ground and wouldn'ttake me… Not that I doubt you, but what’s my father’s name?
{184}{}{Farrel.}
{185}{}{Cornelius.}
{186}{}{Balthas.}
{187}{}{Davin.}
{188}{}{Joshua.}
{189}{}{Não confia em mim, Jonny?} 
{190}{}{Hmm.. não. Valeu por devolver meu cão, mas agora tenho que ir. Tchau.} 
{191}{}{Vou bom te ver, mas agora tenho que ir. Tchau.} 
# It was sure nice meeting you, but I have to go now. Bye.
{192}{}{Isso mesmo! Oba! Vou pra casa. Pergunte ao Vegeir se eu posso voltar com você. Ele tem sido tão bom pra mim, não quero ir embora sem a permissão dele. Se apresse, por favor. Tô com saudades da minha casinha.} 
# That’s right! Yipee! I’m going home. Ask Vegeir if it’s all right for you to take me home. He’s # been so nice to me, I don’t want to leave until he says it’s all right. Please hurry; I’m # # homesick.
{193}{}{Tudo bem, senhor, confio em você. Pergunte ao Vegeir se ele deixa você me levar pra casa. Ele tem sido tão legal comigo, não quero ir embora sem a permissão dele.}
# Okay mister, I believe you. Ask Vegeir it’s all right for you to take me home. He’s been so nice to me, I don’t want to leave until he says it’s all right.
{194}{}{Tudo bem, senhorita, confio em você. Pergunte ao Vegeir se você pode me levar pra casa. Ele tem sido tão legal comigo, não quero ir embora sem a permissão dele.}
{195}{}{Não. Agora vou brincar com meus amigos. Tchau.} 
{196}{}{Não posso falar com estranhos. Tchau.} 
# I’m not supposed to talk to strangers. Bye.
{197}{}{E isso mesmo! Como soube? Laddie deve ter te contado. Ela é uma cadela muito inteligente.}
# Yes it is! How did you know? Laddie must have told you. She’s such a smart dog.
{199}{}{Você vem comigo, garoto. Tá rolando uma recompensa pra quem te trazer de volta.}
# You’re coming with me, kid. There’s a reward for bringing you back.
{200}{}{Acho que é melhor assim mesmo. Mesmo que eu confie em você, tenho certeza que Vegeir só quer ter certeza que vou chegar em casa seguro. Obrigado pela sua ajuda.}
# Yes, I think that’s best. Although I trust you, I’m sure Vegeir just wants to make sure I get home safely. Thank you for your help.


{201}{}{Por favor, se apresse. Quero ir pra casa logo.} 
{202}{}{Não, eu não acredito em você! Me dá meu cão de volta! [Buáááá!]} 
# No! I don’t believe you! Give me back my dog! [Waaaaa!]
{203}{}{Ah não! Vai dizer que você não sabia que a Rose usa carne de cachorro nos pratos dela? A essa hora Laddie já virou hamburguer.}
# Oh no! Don’t you know Rose uses dog in her dishes!? Laddie is probably a burger by now.


{300}{}{Laddie!!!}

{400}{}{Valeu por me salvar, Senhor.} 
{401}{}{E muito bom estar em casa!} 
# It's nice to be home!
{402}{}{Wahoo...} Viva!!!!
{403}{}{Não tenho mais medo do escuro.} 
# You know, I'm not afraid of the dark anymore!
{404}{}{Obrigado por me salvar, senhora.} 