{100}{}{Um bêbado. [Ele tem uma placa escrito "Trabalho por comida."]}
# One very drunk person. [He has a sign that says "Will work for food."]
{101}{}{Karl.}
{102}{}{Ele está tão sujo que tem algumas flores silvestres crescendo em sua cabeça.}
# He is so filthy that you notice some wildflowers growing out of his hair.
{150}{}{Toma essa cerveja.}
# Here, have a beer.
{151}{}{Aqui, pegue essa garrafa de cana.}
# Here, have a bottle of booze.
{152}{}{Aqui, pegue essa Nuka-Cola.}
# Here, have a Nuka-Cola.
{153}{}{Ei.}
{154}{}{Ei!}
{155}{}{EI!!}
{156}{}{Os fantasmas não vão me achar aqui… [soluço]}
# The ghosts won’t be able to find me here… [sob]
{157}{}{Bom estar em casa novamente.}
# It’s good to be home again.
{159}{}{É o Karl; ele desmaiou.}
# It’s Karl; he’s passed out.
{160}{}{Ele vai precisar dar uma cochilada.}
# He’s going to have to sleep it off.
{161}{}{Ah! Os fantasmas da fazenda vieram me pegar!}
# Ah! The ghosts from the farm have come to gets me!
{162}{}{Dá uma esmola para (hic) um fazendeiro aposentado?}
# Spare some change for (hic) an out-of-work farmer?
{163}{}{Claro, cara; quanto você precisa?}
# Sure thing, fella; how much do you need?
{164}{}{Que tal um te comprar uma comida quentinha?}
# How about I buy you a hot meal?
{165}{}{Desculpe, tô sem dinheiro.}
# Sorry, I don’t have any money.
{166}{}{Qual é a sua história?}
# What’s your story?
{167}{}{Aqui esmola?}
# Here cha-ange?
{168}{}{Jooky.}
{169}{}{Oh, bondosa e generosa pessoa. (hic) Como posso te ajudar hoje? (hic) [Ele retira seu gorro em um gesto de humildade]}
# Oh, kind and generous person. (hic) How can Karl help you today? (hic) [He takes off his cap and holds out his hand.]
{170}{}{Aqui tem $100.}
{173}{}{Desculpe, não tenho nada para você. Tchau.}
{174}{}{Sabe onde posso achar um GECK?}
# Do you know where I can find a GECK?
{175}{}{Antes você mencinou algo sobre um jardim. Fale mais sobre ele.}
# You mentioned something about a garden earlier. Tell me more.
{178}{}{Mim vai.}
# Me go.
{179}{}{Ei pão-duro! (hic) Vamos, eu sei que você tem grana… (hic) Só uma esmolinha… (hic) alguma coisa, qualquer coisa! Mostre alguma compaixão.}
# Hey cheapskate! (hic) Come on, I know you gots money… (hic) Just some spare change then… (hic) something, anything! Show some compassion.
{180}{}{Pega aí $25.}
# Here. Here's $25.
{184}{}{Toma aí $1.}
# Here. Here's $1.
{185}{}{Aqui o dinheiro.}
# Here money.
{186}{}{Sem grana.}
# No money.
{187}{}{O que você quer?}
# What do you want?
{188}{}{[Diga para o Karl sobre o que Jo disse.]}
# [Tell Karl about what Jo said.]
{189}{}{Fastasmas, Karl… estão em todos lugares. Olha, tem um ali agora!}
# Ghosts, Karl… they’re everywhere. Look, there’s one now!
{190}{}{Uga uga.}
# Gibba gibba.
{191}{}{Você aí (hic) quer se divertir as minhas custas? (hic) Bem, O que tá esperando? (hic) Vamos acabar logo com isso!}
# You here (hic) to have fun with poor Karl again? (hic) Well, what are you waiting for? (hic) Let’s get this over with!
{198}{}{[Com uma voz insultante.] Que grande generosidade… (hic) Uns $1000 são mais que suficientes.}
# [In a slurred voice.] Mighty kind of ya… (hic) A $1000 otta gets me by.
{199}{}{Certo, .}
# Sure, here you go.
{200}{}{Por quanto tempo, um ano? Sem chance; toma aí $25.}
# For how long, a year? No way; here’s $25.
{201}{}{Você deve achar que sou bobo. Tô fora.}
# You must take me for a fool. I’m out of here.
{202}{}{[Karl fica boquiaberto] Obrigado! Você é (hic) uma pessoa muito generosa… (hic) Se precisar de algo (hic) pode pedir. Aliás, (hic) meu nome é Karl.}
# [Karl’s mouth drops open in surprise] Thanks! You’re a (hic) very generous person… (hic) If thars anything ya needs (hic) just come see me. By the way, (hic) me name's Karl.
{203}{}{Certamente, Karl; agora que você mencinou, estou procurando por um item chamado GECK. Alguma dica de onde posso achar um?}
# Sure, Karl; now that you mention it, I’m looking for an item called a GECK. Any clues as to where I might find one?
{204}{}{Eu vou lembrar disso. Se cuida, Karl.}
# I’ll keep that in mind. Take care of yourself, Karl.
{205}{}{Que tipo de pessoa você é? (hic) Sacaneando um fezen-(hic)-deiro pobre e sem lar. Me deixa em paz!}
# What kinds of person are ya? (hic) Playing tricks on a poor homeless farm-(hic)-er. Leave me alone!
{206}{}{Sei… (hic) Me disseram que é um tipo de lagarto (hic). Porém nunca vi um.}
# Yeah… (hic) Some sort of lizard (hic) I hear. Never seen one, though.
{207}{}{Não, procurando um GECK, não um gecko.}
# No, I’m looking for a GECK, not a gecko.
{208}{}{Deixa pra lá. Agradeço a informação.}
# Never mind. Thanks for the info.
{209}{}{Oh! Você quer dizer um gecko… (hic) Sim, é um lagar-(hic)-tão. [Karl gesticula com as mãos para tentar te mostrar o tamanho. Não dá para saber, o lagarto pode ter 20 centímetros ou 2 metros.]}
# Oh! Ya means gecko… (hic) Yeah, it’s a liz-(hic)-ard about so big. [Karl holds his hands out to show the size. You can’t tell, but the lizard is either 3 inches long or 3 feet long.]
{210}{}{Vou tentar explicar. Não estou procurando um lagarto chamado gecko. Estou procurando um objeto chamado GECK.}
# Let me try to explain. I’m not looking for a lizard called a gecko. I’m looking for an object called a GECK.
{212}{}{Porque não disse logo? (hic) Eu sei onde tem um… (hic) GECK… [Karl desmaiou e caiu de cara no chão.]}
# Why didn’t you say so? (hic) I know where to get it… (hic) Garden of… [Karl falls flat on his face and passes out.]
{213}{}{[Talvez quando Karl acordar, você possa falar com ele novamente.]}
# [Maybe when Karl wakes up, you can talk to him again.]
{214}{}{Abençoado seja! (hic) Você salvou minha vida.}
# Bless you! (hic) Ya saved me life.
{215}{}{Estou procurando um GECK; pode me ajudar?}
# I’m looking for a GECK; can you help me?
{216}{}{Não esquenta. BVejo você por aí, Karl.}
# Don’t mention it. I’ll see you around, Karl.
{217}{}{Hum… (hic) Não estou com fome agora… (hic) Que tal me dar a grana agora para eu comer mais tarde? (hic)}
# Um… (hic) I’m not real hungry right now… (hic) How about if you give me the money and I’ll get it later? (hic)
{219}{}{Seu pilantra. Aposto que usa o dinheiro que consegue para comprar drogas, não é?}
# You shyster. I’ll bet you use the money you collect to buy drugs, don’t you?
{220}{}{Meeer… merrr… merda… O que foi que você colocou? (hic) Pegue de volta… (hic) Seja o que for, isso não é bom.}
# Shi… shy… shick… Whatever you just sed? (hic) Take that back… (hic) Whatever it means, it can’t be good.
{221}{}{[Antes que você possa responder, Karl cai para frente e desmaia.]}
# Before you can reply, Karl falls forward and passes out.]
{222}{}{Beeeleza… (hic) Você por acaso não teria alguma garrafa de bebi-(hic)-da. Pode ficar (hic) frio por aqui durante a noite.}
# Thaaaats okay… (hic) I don’t suppose you have any liquid refresh-(hic)-ment. It get’s mighty (hic) cold out here at night.
{224}{}{Você realmente é (hic) meu melhor amigo (hic) nesse mundo de cão. [Karl começa a beber toda garrafa de bebida, até o ponto de desmaiar]}
# You are truly (hic) my bestest friend in this whole (hic) cursed world. [Karl proceeds to drink the liquid refreshment, at which point he then passes out]
{225}{}{Bem, talvez você consiga conversar com o Karl mais tarde.}
# Oh well, maybe you’ll be able to talk to Karl later.
{226}{}{Você realmente é (hic) meu melhor amigo (hic) nesse mundo de cão. [Karl abre a garrafa e começa a beber  -- e então cospe tudo em você.] Eca! Que porra é essa?! Tá tentando me envenenar?! Sai fora daqui!}
# You are truly (hic) my bestest friend in this whole (hic) cursed world. [Karl opens the bottle and proceeds to drink -- and then proceeds to yark all over you.] Ptui! What the?! Are you trying to  poison me or something?! Get out of here!
{227}{}{Pois, muito (hic) obrigado; você é tão (hic) generoso. Porque não deixa te ajudar com essa bolsa pesada? [Karl meche em sua bolsa e pega metade do seu dinheiro.] Muita bondade sua (hic) se precisar de algo, pode falar.}
# Why, thank (hic) you; you’re so (hic) kind. Why don’t I help you with that heavy purse? [Karl reaches into your purse and takes half your money.] Very kind of you (hic) if you needs anything, don’t hesitate to ask.
{228}{}{GECK?}
{229}{}{Mim vai.}
# I go.
{230}{}{Isso aqui… hic… é uma festa enlatada.}
# Jooky… hic… It’s a party in a can.
{231}{}{Então, talvez mais tarde.}
# Maybe later, then.
{232}{}É... (hic) ...obrigado. Talvez eu compre (hic) uma bala para atirar em mim mesmo. (hic) Claro que terei que juntar (hic) para a arma.}
# Gee... (hic) ...thanks. Maybe I can buy a (hic) bullet to shoot myself with. (hic) Course I’d have to save (hic) up for the gun.
{233}{}{Quer dizer… que posso ir pra casa? Sem mais fastanmas? [Karl ajoelha e chora. Cara, não há nada como ver um homem chorando.] Muito obrigado, finalmente posso voltar para casa!}
# You mean… I can go home? No more ghosts? [Karl breaks down and cries. Boy, nothing like seeing a grown man cry.] Thank you, I can finally go home again!
{234}{}{Onde?! Nããããooo! Eles me acharam!}
# Where?! Nooooooooo! They’ve found me!
{235}{}{Porque sim, eu tinha o maior jardim (hic) que uma pessoa poderia querer. Exceto que (hic) de onde eu sou, nós chamamos isso de fazenda…}
# Why yes, I had the biggest garden (hic) a person could want. Except (hic) where I’m from, we calls it a farm…
{236}{}{Você não lembra? Estávamos falando sobre o GECK, e você mencinou algo sobre um jardim.}
# Don’t you remember? We were talking about the GECK, and you mentioned a garden.
{237}{}{Esqueça, isso não vai dar em nada.}
# Forget it, this is going nowhere.
{238}{}{Ei! (hic) Você é uma graça! Vamos ali atrás (hic) para nos conhecer melhor. Eu posso pagar… tenho $1000. [Karl olha sugestivamente para você.]}
# Hey! (hic) You’re kind a cute! Let’s me and you go out back (hic) and gets better acquainted. I can pay… I’ve got a $1000. [Karl leers suggestively to you.]
{239}{}{você sabe que está falando com um homem, não sabe?}
# You do know you’re talking to a man, don’t you?
{240}{}{Calro, mas vai te custar $1000.}
{241}{}{Agradeço a oferta, mas prefiro falar sobre como encontrar um GECK.}
# Thanks for the offer, but I’d rather talk about finding a GECK.
{242}{}{Nem morto!}
# Not on your life!
{243}{}{Você é tão agradável... (hic) Se você não fala alguma coisa, eu também não. (hic)}
# Yer sooo purty... (hic) If you don’t says anything, I won’t. (hic)
{244}{}{[Você quase não segura o vômito.] Preciso ir embora.}
# You can hardly keep from gagging.] I’ve got to go.
{245}{}{OK, $1000.}
{246}{}{[Você e Karl escapam para uma rapidinha. Para sua surpresa, você até que gostou.]}
# You and Karl slip out back for a quickie. To your surprise, you find that you enjoyed it.
{247}{}{[Ele rapidamente recupera a sobriedade e começa a contar sua história] Já fui um cidadão respeitável antes de vir para cá.
 Era um pacífico fazendeiro que trabalhava duro nos campos como qualquer homem – até que eles começaram a aparecer durante a noite.
 Todos brilhando, com uma pele pálida e pastosa... me caguei todo com medo disso. Noite após noite eles apareceram, roubando tanto as
 plantações quando as plantações. Não pude fazer nada para impedir. Eu sei o que você vai dizer – “Porque não pediu ajuda” E te digo que pedi!
 Mas ninguém acreditou em mim, acharam que eu tava louco. Teve uma hora que tudo isso era demais para mim. EU NÃO AGUENTAVA MAIS!
 Simplesmente fui embora e vim para cá – e aqui estou desde então. [Karl começa a chorar incontrolavelmente. Você resolve deixá-lo
 em seu sofrimento.]}
# [He sobers up quickly and begins to tell his tale.] I used to be an upstanding citizen before coming here. I was a peaceful farmer that worked the fields as hard as any man -- until they started
# showing up at night. All glowing, with pasty white skins... Spooked the hell out of me, it did. Night
# after night they showed up and stole crops and cattle alike; I could do nothing to stop them. I know
# what you’re gonna say - "Why didn’t you ask for help?" I tell ya, I did! Nobody would believe me, they
# thought I was crazy. Finally, it just became too much for me. I COULDN’T TAKE IT ANYMORE! I just up
# and left and came here -- and here I’ve been ever since. [Karl starts to weep uncontrollably. You
# decide to leave him with his misery.]

{248}{}{Ó Jesus! Acho que deixei meu dinheiro cair em algum lugar. Pegue $}
# Oh jeez. I must have dropped my money along the way. Here's $
{249}{}{.}

{250}{}{Zzz}
{251}{}{Zzzzzz}
{252}{}{Zzzzzzzzz}
{253}{}{Zzzzzzzzzzzz}
{254}{}{Zzzzzzzzzzzzzzz}
{255}{}{*ronc* *aham* *ronc*}
# *snort* *grunt* *snort*

{260}{}{Ó Jesus! Acho que deixei meu dinheiro cair em algum lugar. Pegue $}
{261}{}{. É tudo que tenho.}
{262}{}{Ó Jesus! Acho que deixei meu dinheiro cair em algum lugar. Desculpe, mas de qualquer forma foi divertido.}
# Oh jeez. I must have dropped my money along the way. Sorry, it was fun anyway.

{300}{}{Vou para casa, graças a você!}
# I'm going home, thanks to you!

{400}{}{Você mandou Karl de volta para Modoc.}
# You have sent Karl on his way back to Modoc.