# QUICK LOOK
{100}{}{Você vê um barman.}

# EXAMINE
{150}{}{Você vê um homem baixo e gordo tomando conta do bar. Ele acena pra você.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ei! }
{201}{}{! Chutou o traseiro da Enclave, hein! Quer uma bebida?}

# 2. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA = SAME CASINO (WTG)
{206}{}{! O que 'cê manda?!}

# 3. FLOAT DIALOGUE: NORMAL (WTG)
{210}{}{Uma dose de rotgut saindo…}
{211}{}{São três pratas…}
{212}{}{Mais uma, fera?}
{213}{}{Aqui tem um torniquete, se precisar.}
{214}{}{Não inale o Jet de uma vez... tome uma dose, respire fundo e deixe
 fazer efeito.}
{215}{}{Você quer em dois malotes ou no inalador?}#dei uma improvisada ruim demais, se quiser traduzir o original: You want two ½ ounce bags, or a canister?
{216}{}{O inalador vai de brinde…}
{217}{}{Deixa eu adivinhar: Coloco na sua conta?}
{218}{}{Um nuke on the rocks, saindo.}
{219}{}{Nós não deixamos clientes tomarem Buffout aqui, chapa.}

# 4. CLICK DIALOGUE: THREAT (WTG)
{225}{}{É melhor 'cê dar o fora daqui antes que seja servido com mais chumbo do que
 'güenta tomar, entendeu?}
{226}{}{Vamos lá... dá o fora. Nós não queremos encrenca.}
{227}{}{Eles vão acabar com você se continuar por aqui. Cai fora.}
{228}{}{Nós estamos com o estoque vazio. Agora cai fora, otário.}

# 5. INTRO (WTG)
{236}{}{! Vai beber o quê}
{237}{}{Eeeeei! Vai beber o quê?}
{238}{}{O que vai beber, chapa?}
{239}{}{O que vai beber, meu bem?}
{240}{}{Be-bê parece bom}
{241}{}{Bebê?! Mim não quer bebê!}
{242}{}{O que você tem aí?}
{243}{}{Que tipo de drogas você tem?}
{244}{}{Quem é o velhote naquele caça-níqueis?}
{245}{}{Quem é o cara com a faca no bar?}
{246}{}{Nada por hoje, valeu.}

# 6. WHAT'S WITH McGEE? (5)
{250}{}{Ah, 'cê tá falando do velho McGee? Ele é inofensivo. Gasta quase uma fortuna naquela
 máquina velha e não ganhou nada há anos. De qualquer forma... posso te trazer alguma coisa,
 chapa?}

# 7.  WHAT'S WITH LIL' JESUS? (5)
{260}{}{Aquele é o Jesus's little boy, Lil' Jesus. Ele e aquela faca são como amigos
 íntimos... eu já vi ele fazer coisas terríveis com ela. De qualquer forma, posso te
 trazer algo, chapa?}