# quick look
{100}{}{Você vê um freguês do cassino.}
*You see a casino patron.*

# examines
{150}{}{Você vê um freguês do cassino. Ele parece cansado.}
*You see one of the casino patrons. He looks tired.*
{151}{}{Você vê um freguês do cassino. Ele tem um brilho dourado em seus olhos.}
*You see one of the casino patrons. He has a golden gleam in his eye.*
{152}{}{Você vê um freguês do cassino. Ele está cobrindo o rosto com as mãos.}
*You see one of the casino patrons. He is cupping his face in his hands.*
{153}{}{Você vê um freguês do cassino. Ele parece estar um pouco bêbado.}
*You see one of the casino patrons. He looks a little tipsy.*
{154}{}{Você vê um freguês do cassino. Ele pisca os olhos demoradamente, e então dá uma cambaleada.}
*You see one of the casino patrons. He gives you a broad wink, then staggers off.*
{155}{}{Você vê um freguês do cassino. Ele está tentando chamar a atenção da garçonete.}
*You see one of the casino patrons. He is trying to get the waitress's attention.*
{156}{}{Você vê uma freguês do cassino. Ela parece cansada.}
*You see one of the casino patrons. She looks tired.*
{157}{}{Você vê uma freguês do cassino. Ela tem um brilho dourado em seus olhos.}
*You see one of the casino patrons. She has a golden gleam in her eye.*
{158}{}{Você vê uma freguês do cassino. Ela está cobrindo o rosto com as mãos.}
*You see one of the casino patrons. She is cupping her face in her hands.*
{159}{}{Você vê uma freguês do cassino. Ela parece estar um pouco bêbado.}
*You see one of the casino patrons. She looks a little tipsy.*
{160}{}{Você vê uma freguês do cassino. Ela pisca os olhos demoradamente, e então dá uma cambaleada.}
*You see one of the casino patrons. She gives you a broad wink, then staggers off.*
{161}{}{Você vê uma freguês do cassino. Ele está tentando chamar a atenção do garçom.}
*You see one of the casino patrons. She is trying to get the waiter's attention.*

# float
{200}{}{::Palmas::}
*Claps*
{201}{}{::Assobios::}
*Cheers*
{202}{}{Você detonou fácil aqueles idiotas da Enclave! Fácil de mais!}
*Way to burn those Enclave bastards! Way to go!*
{203}{}{Você acabou com a Enclave facilmente, }
*Way to crush the Enclave*
{204}{}{Parabéns por destruir a Enclave, }
*Congrats on stomping the Enclave*
{205}{}{Parabéns por destruir a Enclave, }
*Congrats on stomping the Enclave*
{206}{}{Uh-oh. Saia do caminho.}
*Uh-oh. Get out of the way.*
{207}{}{Só de olhar para ele…ela…isso…*o que quer que seja* me dá arrepios.}
*Just looking at him…her…it…*whatever* it is gives me the shivers.*
{208}{}{Você acha que essa coisa quer atirar em alguém?}
*Think that thing's looking to cap anyone?*
{209}{}{Isso é carne da fúria do inferno. Uh, embaixo da armadura, é isso.}
*It's hell's fury given flesh. Uh, underneath the armor, that is.*
{210}{}{Fique fora do caminho dessa coisa.}
*Stay outta that thing's path.*
{211}{}{O que me diz sobre esse olhar-assassino…}
*Talk about dangerous-looking…*
{212}{}{*Glup*}
*Gulp*
{213}{}{Eu acho que esse Sr. Roboto está me scaneando.}
*I think that Mr. Roboto dude was scanning me.*
{214}{}{Eu acho que esse tanque ambulante está me dando o olhar da morte. Vou cair fora daqui.}
*I think that walking tank just gave me the stare of death. I'm outta here.*
{215}{}{Eu ouvi que essa coisa acabou com três assassinos só ontem.}
*I heard that thing fragged three hitmen just yesterday.*
{216}{}{Só de olhar para ele me dá arrepios.}
*Just looking at him gives me the shivers.*
{217}{}{Você acha que essa coisa quer atirar em alguém?}
*Think he's looking to cap anyone?*
{218}{}{Fique fora do caminho desse cara.}
*Stay outta that man's path.*
{219}{}{Eu acho que ele está olhando para mim.}
*I think he was looking at me.*
{220}{}{Eu acho que esse tanque ambulante está me dando o olhar da morte. Vou cair fora daqui.}
*I think he just gave me the stare of death. I'm outta here.*
{221}{}{Fiquei sabendo que ele matou três assassinos só ontem.}
*I heard he shot down three hitmen just yesterday.*
{222}{}{Uh-oh. Saia do caminho.}
*Uh-oh. Get out of the way.*
{223}{}{Isso é carne da fúria do inferno.}
*It's hell's fury given flesh.*
{224}{}{O que me diz desse olhar-assassino…}
*Talk about dangerous-looking…*
{225}{}{*Glup*}
*Gulp*
{226}{}{Então, é uma La Femme Nikita da vida.}
*La Femme Nikita, then some.*
{227}{}{Só de olhar pra ela me da arrepios.}
*Just looking at her gives me the shivers.*
{228}{}{Você acha que ela quer atirar em alguém?}
*Think she's looking to cap anyone?*
{229}{}{Acho que ela está olhando pra mim.}
*I think she was looking at me.*
{230}{}{Eu acho que ela está me dando o olhar da morte. Vou cair fora daqui.}
*I think she just gave me the stare of death. I'm outta here.*
{231}{}{Fiquei sabendo que ela matou três assassinos só ontem.}
*I heard she shot down three hitmen just yesterday.*
{232}{}{Que bunda! Uh, bunda má, é isso.}
*What an ass! Uh, bad ass, that is.*
{233}{}{Você não parece tão forte, Sr. Prizefighter.}
*You don't look so tough, Mr. Prizefighter.*
{234}{}{Eu ganhei 20 conto apostando em você!}
*I got 20 chips riding on ye!*
{235}{}{Ei, campeão! Aquela última luta foi ótima!}
*Hey, champ! That last fight was great!*
{236}{}{Vi você lutando no ringue. Que belo gancho que você deu.}
*Saw you fight in the ring. Damn good right hook you throw.*
{237}{}{Você vai cair? Eu ganhei 30 conto apostando em você.}
*You gonna take the fall? I got 30 chips riding on you.*
{238}{}{Quanto você pesa?}
*How much you bench?*
{239}{}{Onde você trabalha fora do ringue?}
*Where do you work out?*
{240}{}{Cuidado com o Masticator. Ele é louco por orelhas.}
*Watch out for the Masticator. He has a taste for ears.*
{241}{}{Eu te pagaria uma bebida se não tivesse perdido todo meu dinheiro apostando no seu oponente.}
*I'd get you a drink if I hadn't blown all my money betting on your opponent.*
{242}{}{Você não parece ser tão forte, Srta. Gancho de esquerda.}
*You don't look so tough, Ms. Left Hook.*
{243}{}{Posso ver seus músculos abdominais?}
*Can I see your abdominal muscles flex?*
{244}{}{Whoa. Dá uma olhada nisso.}
*Whoa. Check that out.*
{245}{}{Você viu *isso*?}
*Would you look at *that*?*
{246}{}{::As bocas soltam um 'caramba.'::}
*Mouths the word 'damn.'*
{247}{}{Eu SABIA que devia ter me barbeado hoje.}
*I KNEW I should have shaved today.*
{248}{}{Vem conversar comigo um pouco, tetas-de-mel.}
*Come chat with me for a sec, honey-tits.*
{249}{}{Tribais pega suas tetas! Droga!}
*Tribals got them tits! Damn!*
{250}{}{Cheque os peitos dessa tribal.}
*Check out the rack on that tribal.*
{251}{}{Aqui está a melher potranca do meu rebanho.}
*That there's the main filly of my herd.*
{252}{}{Eu tomaria banho por essa mulher.}
*I'd bathe for that woman.*
{253}{}{Eu tenho seu compridinho bem aqui.}
*I got your mother lode right here.*
{254}{}{Mexa isso!}
*Shake it!*
{255}{}{Trabalhe isso!}
*Work it!*
{256}{}{::Assobios::}
*Whistles*
{257}{}{Essas pernas ficam totalmente erguidas?}
*Them legs go all the way up?*
{258}{}{Pooooooorra.}
*Daaaaaamn*
{259}{}{Você pega batatas fritas para acompanhar essa mexida, linda?}
*You got fries to go with that shake, beautiful?*
{260}{}{Talvez ela vai dançar hoje de noite.}
*Maybe she'll dance tonight.*
{261}{}{Você viu o último filme dela? Muito bom, cara, muito BOM.}
*Did you see her latest film? Red hot, man, red HOT.*
{262}{}{me desculpe. Eu tenho que ir ao banheiro e er, ageitar meu cabelo por um segundo.}
*Excuse me. I have to go to the bathroom and er, comb my hair for a sec.*
{263}{}{Eu queria ser a calça dela.}
*I'd like to be her underpants.*
{264}{}{Eu gostaria de ser a calcinha dela.}
*I'd like to be her underwear.*
{265}{}{Eu gostaria de cheirar o short dela.}
*I'd like to smell her shorts.*
{266}{}{Essa é uma biscate bonita.}
*That is one foxy bitch.*
{267}{}{Droga. Todas essas curvas e eu sem freio nenhum.}
*Damn. All them curves and me with no brakes.*
{268}{}{Bem, oláááá garanhão.}
*Well, hellloooo stud.*
{269}{}{Um garanhão como você tá na seca? Eu vou estar livre amanhã à noite.}
*A stallion like you in need of a saddle? I'm free tomorrow night.*
{270}{}{O que você vai fazer mais tarde, marinheiro?}
*What you doing later, sailor?*
{271}{}{Eu posso sentir seus músculos?}
*Can I feel your muscles?*
{272}{}{Como você não fica cansado depois de ficar com o pau duro?}
*How come you don't pass out when you get erect?*
{273}{}{Quer ir na minha casa tomar um drink?}
*Wanna come over to my place for a drink?*
{274}{}{Eu quero comer meu jantar longe do seu peito.}
*I want to eat my dinner off your chest.*
{275}{}{Precisa de uma parceira para o próximo filme?}
*Need a partner for your next film?*
{276}{}{::Olhares no seu bíceps.::}
*Stares at your biceps.*
{277}{}{Isso é um tipo de caça-níquel que está te seguindo por aí?}
*Is that some kind of slot machine that's following you around?*
{278}{}{Isso é um robô caça-níqueis?}
*Is that a robo-slot machine?*
{279}{}{O seu robô faz truques? Uh…truques de mágica, que eu quis dizer.}
*Does your robot do tricks? Uh…magic tricks, I mean.*
{280}{}{Isso parece tão louco quato raposas transando.}
*That sounds crazier than foxes lovin' hens.*
{281}{}{Role os ossos.}
*Roll the bones.*
{282}{}{O bebê precisa de um novo par de sapatos...}
*Baby needs a new pair of shoes...*
{283}{}{Turistas sortudos da porra…}
*Damn lowrolling tourists…*
{284}{}{Caralho! Eu tinha *53* conto, então…}
*Dammit! I was up *53* chips, then…*
{285}{}{Todos podem ter sorte…}
*Of all the rotten luck…*
{286}{}{Por pouco!}
*So close!*
{287}{}{Eu faço banco.}
*I'm making bank.*
{288}{}{Eu? Eu faço banco. Olha eu indo.}
*Me? I'm making bank. Watch me go.*
{289}{}{A Casa tá contra mim.}
*House was against me.*
{290}{}{A fortuna tá contra mim.}
*Fortune's against me.*
{291}{}{Moça Sortuda, não falha comigo agora.}
*Lady Luck, don't fail me now.*
{292}{}{A Casa está a meu favor.}
*The House ha'mercy on me.*
{293}{}{Entre pontas e esses bêbados gastando…}
*Between tips and these drunken spending sprees…*
{294}{}{Continue agindo assim, e você vai chamar Golgotha de casa…}
*Keep betting like that, and you're going to be calling Golgotha home…*
{295}{}{Garçonete, outra bebida!}
*Waitress, another drink!*
{296}{}{Garçom, outra bebida!}
*Waiter, another drink!*
{297}{}{Esses bebidas tem um gosto…único.}
*These drinks taste…odd.*
{298}{}{Eu fiquei com febre!}
*I got the fever!*
{299}{}{Já foi todo o meu dinheiro?}
*Are all my chips gone already?*
{300}{}{A Sorte é uma puta inconstante, e minha sogra também.}
*Luck's a fickle bitch, and so is my mother-in-law.*
{301}{}{Tem mais slavers na cidade ultimamente.}
*More slavers in town recently.*
{302}{}{Queria saber o que acontece nos estábulos fora da cidade.}
*Wonder what goes on in the stables outside of town.*
{303}{}{Outra disputa pode começar daqui a pouco.}
*Another feud may start soon.*
{304}{}{Droga de viajantes estão por toda parte...}
*Damned crossroaders all over the place...*
{305}{}{Ótimo, outro sortudo.}
*Great, another low roller.*
{306}{}{Eu sou MUITO dinheiro.}
*I am SO money.*
{307}{}{Eu estarei dormindo quando eu estiver morto.}
*I'll sleep when I'm dead.*
{308}{}{Cara, eu preciso mijar. Meu dente tá nadando.}
*Man, I gotta piss. My teeth are swimming.*
{309}{}{Cara, eu preciso tirar água do joelho.}
*Man, I gotta drain the snake.*
{310}{}{Porra, eles deixam qualquer um entrar aqui.}
*Damn, they'll let anyone in here.*
{311}{}{Me dá um 7!}
*C'mon 7!*
{312}{}{Você tem bolas, baby.}
*You've got moxy, baby.*
{313}{}{Quem é o grande vencedor essa noite? Mikey!}
*Who's the big winner tonight? Mikey!*
{314}{}{Não caga fora…vai…}
*Don't crap out…c'mon…*
{315}{}{Eu tenho 'jet'…se é que me entende.}
*I've gotta 'jet'…if you know what I mean.*
{316}{}{Isso é PURA mentira.}
*This is SUCH bullshit.*
{317}{}{Eu só perdi 60 conto. Nos primeiros cinco minutos, é isso.}
*I only lost 60 chips. In the first five minutes, that is.*
{318}{}{Vermelho 23! Vermelho 23! Vamos lá…vermelho 23…}
*Red 23! Red 23! C'mon…red 23…*
{319}{}{50 conto no Preto 15…}
*50 chips on Black 15…*
{320}{}{Isso vai rodando…e onde para, ninguém sabe…}
*Round and round it goes…where it stops, nobody knows…*
{321}{}{O jeito é queimar esses idiotas da Enclave! Vai lá!}
*Way to burn those Enclave bastards! Way to go!*
{322}{}{Eu sempre soube que o Presidente queria matar a todos nós.}
*I always knew the President wanted to kill us all.*
{323}{}{O Presidente tá vivo?  Quando foi a última eleição?}
*The President was alive? When was the last election?*
{324}{}{Destrui a Enclave, huh? Bem, deixa eu comprar uma bebida pra você.}
*Destroyed the Enclave, huh? Well, let me buy you a drink.*
{325}{}{A caminho de destruir a Enclave, }
*Way to crush the Enclave, *
{326}{}{Com a destruição da Enclave, você fez esse cassino o melhor lugar para minhas crianças. Como eu posso te agradecer?}
*With the destruction of the Enclave, you've made this casino a better place for my children. How can I ever thank you?*
{327}{}{A Enclave nunca mexeu comigo, mas eu estou feliz que eles se foram.}
*The Enclave never messed with me, but I'm glad they're gone.*
{328}{}{Eu não consigo acreditar que a Enclave continuou lutando a guerra durante todos esses anos. Idiotas.}
*I can't believe the Enclave were still fighting the war after all this time. Idiots.*
{329}{}{Eu estou preocupado…como que centenas de idiotas malvados em uma plataforma de petróleo de repente espalha o terror por aí
 e do nada foram silenciados. Estranho.}
*I felt a great disturbance…as if a hundred evil bastards on an oil derrick suddenly cried out in terror
 and were suddenly silenced. Strange.*
{330}{}{Parabéns por acabar com a Enclave, }
*Congrats on stomping the Enclave, *
{331}{}{Parabéns por acabar com a Enclave, }
*Congrats on stomping the Enclave, *
{332}{}{Você está procurando pelo seu irmão Robby? Você sabe, o Robô? Aw, esquece.}
*You looking for your brother Robby? You know, the Robot? Aw, nevermind.*
{333}{}{Me desculpa, por eu estar no seu caminho? Eu vou deixar a cidade.}
*Sorry, was I in your way? I'll leave town.*
{334}{}{Me desculpa, por eu estar respirando seu ar? Eu vou parar.}
*Sorry, was I breathing your air? I'll stop.*
{335}{}{Eu não sabia que faziam portas do seu tamanho.}
*I wasn't aware they made doorways in your size.*
{336}{}{::Batidas na armadura:: Tem alguém aí?}
*::Knocks on armor:: Anybody in there?*
{337}{}{'Perigo, Will Robinson! Perigo, Will Robinson!' Heh-heh. Uh…e só uma piada.}
*'Danger, Will Robinson! Danger, Will Robinson!' Heh-heh. Uh…just a joke.*
{338}{}{Beeeeela armadura. Tem ar condicionado?}
*Niiiiice armor. Does it have air conditioning?*
{339}{}{Você não fica com calor aí?}
*Don't you get hot in there?*
{340}{}{Posso esfregar estes dados na sua armadura para ter sorte?}
*Can I rub these dice against your armor for luck?*
{341}{}{Perdeu seu coração, homem de lata?}
*Lose your heart, tin man?*
{342}{}{Uh, olá, senhor…ou madame…ou seja lá o que você for.}
*Uh, hello, sir…or ma'am…or whatever you are.*
{343}{}{Eu considero quem quer que tenha te dado essa armadura pra você.}
*Give my regards to whoever gave that armor to you.*
{344}{}{Tem alguma coisa errada, senhor…madame…uh, o que quer que você seja?}
*Anything wrong, sir…ma'am…uh, whatever you are?*
{345}{}{Você é um dos novos patrões? Ou algum novo jogo ambulante?}
*Are you one of the new bouncers? Or some new walking arcade game?*
{346}{}{Não, eu NÃO vou colocar óleo nas suas juntas.}
*No, I'm NOT going to oil your joints.*
{347}{}{Sua armadura se transforma num jet e voa por aí? Apenas curiosidade.}
*Can your armor transform into a jet and fly around? Just curious.*
{348}{}{É, é, 'clank-whirrr-clank' pra você também.}
*Yeah, yeah, 'clank-whirrr-clank' to you, too.*
{349}{}{Se você pensa que essa armadura me intimida, você está certo.}
*If you think that armor intimidates me, you're right.*
{350}{}{Você deve ser um desses video games pré-guerra.}
*You must be one of those pre-war video game consoles.*
{351}{}{Olhe, por favor…Eu não quero arrumar encrenca. Eu estou na cidade só por um dia.}
*Look, please…I don't want any trouble. I'm just in town for the day.*
{352}{}{Olhe, por favor…Eu não quero arrumar encrenca.}
*Look, please…I don't want any trouble.*
{353}{}{Me desculpa, por eu estar no seu caminho? Eu vou deixar a cidade.}
*Sorry, was I in your way? I'll leave town.*
{354}{}{Me desculpa, por eu estar respirando seu ar? Eu vou parar.}
*Sorry, was I breathing your air? I'll stop.*
{355}{}{Dê minhas saudações para o seu chefe.}
*Give my regards to your boss.*
{356}{}{Uh…*glup*…algo errado?}
*Uh…*gulp*…anything wrong?*
{357}{}{Olhe, por favor…Eu não quero arrumar encrenca. Eu estou na cidade só por um dia.}
*Look, please…I don't want any trouble. I'm just in town for the day.*
{358}{}{Olhe, por favor…Eu não quero arrumar encrenca.}
*Look, please…I don't want any trouble.*
{359}{}{Você tá vendendo?}
*You selling?*
{360}{}{Eu posso comprar suas roupas? Eu digo, agora?}
*Can I buy your clothes? I mean, right now?*
{361}{}{Eu SABIA que devia ter me barbeado hoje.}
*I KNEW I should have shaved today.*
{362}{}{Venha conversar comigo por um segundo, peitos-de-mel.}
*Come chat with me for a sec, honey-tits.*
{363}{}{Vamos lá, lábios-de-mel…ande comigo.}
*C'mon, honey-lips…walk with me.*
{364}{}{Pequena ninfa ligeira, não é?}
*Nimble little minx, aincha?*
{365}{}{Eu tomei banho por você.}
*I'd bathe for you.*
{366}{}{Eu tenho o seu filão de mãe bem aqui.}
*I got your mother lode right here.*
{367}{}{Essas pernas vão para o lugar que quiser?}
*Them legs go all the way up?*
{368}{}{Você vai dançar essa noite?}
*You gonna dance tonight?*
{369}{}{Com licensa. Eu tenho que ir ao banheiro e er, ajeitar meu cabelo por um segundo.}
*Excuse me. I have to go to the bathroom and er, comb my hair for a sec.*
{370}{}{Eu queria ser suas roupas de baixo.}
*I'd like to be your underwear.*
{371}{}{Eu gostaria de cheirar seu shorts.}
*I'd like to smell your shorts.*
{372}{}{Você é uma puta gostosa.}
*You are one foxy bitch.*
{373}{}{Me foda se eu estiver errado, querida, mas você não quer me beijar?}
*Screw me if I'm wrong, darling, but don't you want to kiss me?*
{374}{}{Droga. Todas essas curvas e eu sem freios.}
*Damn. All them curves and me with no brakes.*
{375}{}{Sabe o que ficaria bem em você? Eu.}
*Know what would look good on you? Me.*
{376}{}{Suas calças podem não ser a melhor coisa na Terra, mas elas estão perto.}
*Your panties may not be the best thing on earth, but they're damn close to it.*

{503}{}{!}
{504}{}{! Você chuta bundas! Você chuta BUNDAS!}
*! You kick ass! You kick ASS!*
{505}{}{! Você é tanto DINHEIRO!}
*! You are so MONEY!*
{625}{}{!}
{630}{}{! Você chuta bundas! Você chuta BUNDAS!}
{631}{}{! Você é tanto DINHEIRO!}