# examine
{150}{}{Você vê um homem com roupas amassadas. Ele está esfregando o nariz e olhando furtivamente ao redor.}
*You see a man in wrinkled clothes. He is rubbing his nose and glancing around furtively.*
{151}{}{Você vê um vendedor de drogas.}
*You see a drug dealer*
{152}{}{Você vê um vendedor de drogas. Parece estar procurando algum freguês.}
*You see a drug dealer. It looks like he's trolling for a customer.*

# float
{200}{}{Hey, herói! Você quer comemorar com um Jet? Fale comigo!}
*Hey, hero! You lookin' to celebrate with some Jet? Talk to me!*
{201}{}{Chutu a bunda da Enclave fácil herói! Você quer celebrar chapando com um Jet?}
*Way to kick the Enclave's ass, hero! You want to kick back and celebrate with some Jet?*
{202}{}{::Aplausos::}
*Cheers*
{203}{}{::Assobios::}
*Whistles*
{204}{}{Nada melhor que usar um Jet depois de chutar a bunda da Enclave né? Eu estou certo?}
*Nothing better than a shot o' Jet after kicking the Enclave's ass, eh? Am I right?*
{205}{}{Eu tenho a parada que vai te ajudar a beijar o céu, herói.}
*I got shit that'll help you kiss the sky, hero.*
{206}{}{Você já experimentou?}
*Are you experienced?*
{207}{}{Herói, se você quiser doce de cérebro, venha negociar comigo. Eu reservarei TODA minha parada pra você.}
*Hero, you want brain candy, you come deal with me. I mark down ALL my shit for you.*
{208}{}{Eu sei o que você quer amigo, e eu tenho isso bem aqui. Todo o Jet que você PRECISA.}
*I know what you're looking for, friend, and I got it. All the Jet you NEED.*
{209}{}{Por que andar quando você pode VOAR?}
*Why walk when you can FLY?*
{210}{}{Eu tenho o Jet mais puro da cidade. Ele não é barato, mas vale cada centavo.}
*I got the purest Jet in town. It ain't cheap, but it's worth every bit.*
{211}{}{Você quer voar? Você tem dinheiro? Fale COMIGO.}
*You lookin' to fly? You got money? You talk to ME.*
{212}{}{Eu tenho a parade que vai te ajudar a beijar o céu, amigo.}
*I got shit that'll help you kiss the sky, friend.*
{213}{}{Eu tenho Jet e mais Jet. Vamos conversar.}
*I got Jet and more Jet. Let's talk.*

# click dialogue
{214}{}{Deixe-me saber como eu posso ajudar VOCÊ, herói. Me diga o que você precisa, e eu vou te dar o melhor bagulho da cidade.}
*Let me know how I can help YOU, hero. Tell me your needs, and I'll give you the best rate in town.*
{215}{}{Então você está querendo celebrar com um Jet, herói? Você veio ao lugar certo. Para você, TUDO do meu estoque especial.}
*So you lookin' to celebrate with some Jet, hero? You came to the right place. For you, EVERYTHING'S on special.*
{216}{}{O mínimo que eu posso fazer é marcar o meu estoque para você, herói. É o meu jeito de dizer obrigado por nos salvar.}
*Least that I can do is mark down my stock for you, hero. Just my little way of saying thanks for saving our hide.*
{217}{}{Nada melhor que usar um Jet depois de chutar a bunda da Enclave, né? Estou certo? Todo o meu estoque especial pra você.}
*Nothing better than a shot o' Jet after kicking the Enclave's ass, eh? Am I right? All my stock's on special for you.*
{218}{}{Eu tenho a parada que vai ajudar você a beijar o céu, herói.  E para você: um ótimo desconto. O que você acha?}
*I got shit that'll help you kiss the sky, hero.  And for you: a nice discount. How does that sound?*

{219}{}{Você tem doce? }
*U got candy?*
{220}{}{Cai fora}
*Wander off*
{221}{}{O que você tem?}
*What have you got?*
{222}{}{Eu não quero nada, obrigado.}
*I don't want anything, thanks.*

# player great
# male
{230}{}{Hey, hey…Estou na presença do grandioso. Para VOCÊ, amigo, meu estoque especial. Diga a todos os seus amigos sobre mim, tudo
 bem?}
*Hey, hey…I'm in the presence of greatness. For YOU, friend, my stock's on special. Tell all your friends about me, all
 right?*
{231}{}{Então você está procurando fazer uma festa com uns Jet, amigo? Você veio ao lugar certo. Para você, TUDO do estoque especial.}
*So you lookin' to party with some Jet, friend? You came to the right place. For you, EVERYTHING'S on special.*
{232}{}{Eu tenho Jet suficiente pra te colocar em órbita, meu caro amigo. E para você: um desconto. Vamos falar de preços?}
*I got enough Jet to put you in orbit, my fine friend. And for you: a discount. Shall we talk price?*
{233}{}{Eu tenho a parada que vai ajudar você a beijar o céu, amigo.  E para você: um desconto. O que você acha?}
*I got shit that'll help you kiss the sky, friend.  And for you: a discount. That sound all right?*
{234}{}{O mínimo que eu posso fazer é marcar meu estoque para VOCÊ, amigo. É meu jeito de ser amigável.}
*Least I can do is mark down my stock for YOU, friend. Just my way of being friendly.*
# generic
{235}{}{Você tem classe, sabia disso? Classe. E quando alguém com classe negocia comigo, eles ganham um desconto no
 estoque, sabia?}
*You've got class, y'know that? Class. And when someone as classy as you deals with me, they get a discount at
 the store, see?*
{236}{}{Deixe-me saber como posso ajudar VOCÊ, amigo. Me diga o que você precisa, e eu te darei o melhor bagulho da cidade.}
*Let me know how I can help YOU, friend. Tell me your needs, and I'll give you the best rate in town.*
{237}{}{Nada melhor que puxar um Jet depois de um longo dia correndo por aí, né? Estou certo? Para VOCÊ, todo meu estoque especial.}
*Nothing better than a shot o' Jet after a long day of running around, eh? Am I right? For YOU, all my stock's on special.*
# female
{238}{}{Hey, hey…I'm in the presence of greatness. For YOU, miss, my stock's on special. Tell all your friends about me, all right?Hey, hey…Estou na presença do grandioso. Para VOCÊ, amigo, meu estoque especial. Diga a todos os seus amigos sobre mim, tudo bem?}
*Hey, hey…I'm in the presence of greatness. For YOU, miss, my stock's on special. Tell all your friends about me, all right?*
{239}{}{Então você está procurando fazer uma festa com uns Jet, amiga? Você veio ao lugar certo. Para você, TUDO do estoque especial.}
*So you lookin' to party with some Jet, miss? You came to the right place. For you, EVERYTHING'S on special.*
{240}{}{Eu tenho Jet suficiente pra te colocar em órbita, minha cara amiga. E para você: um desconto. Vamos falar de preços?}
*I got enough Jet to put you in orbit, my lady friend. And for you: a discount. Shall we talk price?*
{241}{}{Eu tenho a parada que vai ajudar você a beijar o céu, moça.  E para você: um desconto. O que você acha?}
*I got shit that'll help you kiss the sky, miss. And for you: a discount. That sound all right?*
{242}{}{O mínimo que eu posso fazer é marcar meu estoque para VOCÊ, moça. É meu jeito de ser amigável.}
*Least that I can do is mark down my stock for YOU, miss. Just my way of being friendly.*

{247}{}{Eu sei o que você tá procurando, slaver, e eu tenho bem aqui. Todo o Jet que você PRECISA.}
*I know what you're looking for, slaver, and I got it. All the Jet you NEED.*
{248}{}{Por que andar quando você pode VOAR? Você quer Jet, eu tenho aqui.}
*Why walk when you can FLY? You want Jet, I got it*
{249}{}{Slaver, eu tenho o Jet mais puro da cidade. Não é barato, mas vale cada centavo.}
*Slaver, I got the purest Jet in town. It ain't cheap, but it's worth every bit.*
{250}{}{Você quer voar, slaver? Você tem grana? Fale COMIGO.}
*You lookin' to fly, slaver? You got chips? You talk to ME.*
{251}{}{Eu tenho a parada que vai ajudar você a beijar o céu, slaver.}
*I got shit that'll help you kiss the sky, slaver.*
{252}{}{Eu tenho Jet, Jet, e MAIS Jet. Vamos conversar.}
*I got Jet, Jet, and MORE Jet. Let's talk.*
{253}{}{Eu tenho Jet suficiente pra te colocar em órbita, slaver. Vamos falar de preços?}
*I got enough Jet to put you in orbit, slaver. Shall we talk price?*
{254}{}{Você já experimentou, slaver? Deixa eu te mostrar o melhor Jet da cidade.}
*Are you experienced, slaver? Let me set you up with the best Jet in town.*
{255}{}{Você tá procurando Jet? Vem cá, slaver, vamos negociar.}
*You lookin' for Jet? C'mon, slaver, let's deal.*
{256}{}{Você tá procurando Jet? Vamos, slaver, você e eu: Vamos conversar.}
*You lookin' for Jet? C'mon, slaver, you and me: Let's talk.*

{261}{}{Eu sei o que você tá procurando, amigo, e eu tenho aqui. Todo o Jet que você PRECISA.}
*I know what you're looking for, friend, and I got it. All the Jet you NEED.*
{262}{}{Por que andar quando você pode VOAR?}
*Why walk when you can FLY?*
{263}{}{Eu tenho o Jet mais puro da cidade. Não é barato, mas vale cada centavo.}
*I got the purest Jet in town. It ain't cheap, but it's worth every chip.*
{264}{}{Você quer voar? Você tem grana? Fale COMIGO.}
*You lookin' to fly? You got chips? You talk to ME.*
{265}{}{Eu tenho a parada que vai te ajudar a beijar o céu, amigo.}
*I got shit that'll help you kiss the sky, friend.*
{266}{}{Eu tenho Jet, Jet e MAIS Jet. Vamos conversar.}
*I got Jet, Jet and MORE Jet. Let's talk.*
{267}{}{I got enough Jet to put you in orbit, friend. Shall we talk price?}
*I got enough Jet to put you in orbit, friend. Shall we talk price?*
{268}{}{Você já experimentou? Deixa eu te mostrar o melhor Jet da cidade.}
*Are you experienced? Let me set you up with the best Jet in town.*
{269}{}{Tá procurando Jet? Vamos negociar.}
*You lookin' for Jet? Let's deal.*
{270}{}{Tá procurando Jet? Vamos conversar.}
*You lookin' for Jet? Let's talk.*

{519}{}{ ADORA doce!}
*LIKE candy!*