# 0. QUICK LOOK, BOXES (WTG)
{100}{}{Você vê várias caixas repletas de produtos químicos.}

# 0. LOOK, BOXES (WTG)
{150}{}{Você vê várias caixas repletas de produtos químicos. Você não consegue identificá-los, mas eles foram
 empacotados com *muito* cuidado.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{175}{}{Você vê um Vertibird.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{199}{}{Você vê um Vertibird... uma forma avançada do helicóptero. Infelizmente, você não faz idéia de
 como operá-lo. }

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(Esses caras me dão arrepios...)}
{000}{}{(Cala a boca. Aí vem eles.)}
{000}{}{*Zztttt* Você tem a carga que requisitamos? *Zzzttt**}
{000}{}{Sim, os produtos químicos estão todos aqui. Vocês podem checar se quiserem.}
{000}{}{*Zztttt* Isso não será necessário. *Zzzttt**}
{000}{}{*Zztttt* Você sabe o que vai acontecer se os produtos não correspoderem com as especificações que requisitamos.
 *Zzzttt**}
{000}{}{Sim, é claro. Hã, e vocês trouxeram as lightbringers...?}
{000}{}{*Zztttt* As armas laser estão em nosso cargo bay. *Zzzttt**}#nao me veio a traducao pra cargo bay na cabeca.
{000}{}{*Zztttt* To insure your cooperation, we will transmit the arming sequence for them once the
 chemicals are loaded. *Zzzttt**}#transmit the arming sequence for them = transmitir as armas?
{000}{}{Hã... bem... tudo bem, então. Peguem as caixas, homens --}
{000}{}{*Zztttt* Não. *Zzzttt**}
{000}{}{*Zztttt* Nós iremos fazer o carregamento. *Zzzttt**}
{000}{}{Hã, certo... certo. É claro. Abram caminho pra eles, homens.}
{000}{}{Tudo bem; estamos prontos. O resto de vocês, guardas... você também, novato... voltem pra Reno.
 Nós iremos encontrar vocês lá.}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{Olhem! Tem alguém nos espionando!}
{000}{}{Matem!}
{000}{}{Parece que nós temos um espião...!}
{000}{}{*Zztttt* Missão abortada. Seqüência de falha no carregamento ativada. *Zzzttt**}#Mission aborted. Cargo failsafe sequence engaged. verifique essa ultima frase se a traducao ficou boa. idem no numero 5 abaixo
{000}{}{*Zztttt* Exterminar os hostis e retornar à base. *Zzzttt**}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{Não chegue perto daqueles caras de armadura. Eles podem te partir no meio.}
{000}{}{Em posição.}
{000}{}{Pare de tremer... aqueles caras de armadura não gostam disso.}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{Merda! O que você está fazendo, imbecil?!}
{000}{}{Volte para o seu posto! Que diabos você está fazen --?!}
{000}{}{*Zztttt* Missão abortada. Seqüência de falha no carregamento ativada. *Zzzttt**}
{000}{}{*Zztttt* Exterminar os hostis e retornar à base. *Zzzttt**}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[Parece que tem uma porta. Abrir e embarcar?]}
{000}{}{Isso aí}
{000}{}{Cair fora}
{000}{}{Embarcar no Vertibird.}
{000}{}{Deixar pra lá.}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[A porta se fecha atrás de você e o Vertibird levanta vôo! Você não consegue abrir a porta!]}
{000}{}{Oh-oh}
{000}{}{Oh, merda...}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{Essas caixas estão repletas de pesadas latas de metal. Julgando pelo cuidado do empacotamento,
 você suspeita que elas contenham algum tipo de produto químico perigoso. }