# quick looks
{100}{}{Você vê um boxeador.}
*You see a boxer.*
{101}{}{Você vê Pete "The Hurricaine" McKneely.}
*You see Pete "The Hurricaine" McKneely.*

# examines
{150}{}{Você vê o que parece ser um cara branco realmente forte. Ele parece ser tão fraco que você o derrubaria com um pedaço de pizza.}
*You see what seems to be a heavily-muscled white man. He looks so weak you could knock him out with a slice of pizza.*
{151}{}{A sua dentadura brilha como vidro.}
*His jaw gleams like glass.*
{152}{}{Parece que ele não duraria sete segundos no ringue.}
*He looks as if he wouldn't last seven seconds in the ring.*
{153}{}{Parece que você poderia derrubá-lo com uma fatia de pizza.}
*He looks like you could knock him out with a slice of pizza.*

# FLOAT DIALOGUE
{200}{}{*Hnffff*}
{201}{}{*Hnrggg*}
{202}{}{::Flexes::}
{203}{}{Tô só o pó}
*I'm bushed*
{204}{}{Tô cansado}
*I'm tired*
{205}{}{*Phewwww* Dia difícil}
*Rough day*
{206}{}{Trabalhar fora sempre me deixa cansado}
*Working out always makes me tired*
{207}{}{Lutar me deixa exausto}
*Fighting exhausts me*
{208}{}{Melhor ir polir minha dentatura de vidro}
*Better go polish my glass jaw*

#CLICK DIALOGUE
# (ANY PRIZEFIGHTER)
{300}{}{::O boxeador olha para você e cobre sua mandíbula::}
*The boxer looks at you and covers his jaw*
{301}{}{::O boxeador olha para você e esfrega sua mandíbula::}
*The boxer looks at you and rubs his jaw*
# (NORMAL)
{302}{}{Trabalhar fora sempre me deixa cansado}
*Working out always makes me tired*
{303}{}{Eu estou bem se meu técnico puder vir no ringue e parar a luta}
*I'm okay if my manager can come in the ring and stop the fight*
{304}{}{Eu sou o Pete. Pete "Derrotado" McKneely.}
*I'm Pete. Pete "Defeat" McKneely.*
{305}{}{Eu gosto de pizza, mas tenho que tomar cuidado com a crosta}
*I like pizza, but I have to be careful with the crust*
{306}{}{Eu abri a porta hoje e o vento me derrubou no chão}
*I opened the door this morning and the wind knocked me out*
{307}{}{Lutar me deixa exausto}
*Fighting exhausts me*
{308}{}{Melhor eu ir polir minha dentatura de vidro}
*Better go polish my glass jaw*
{309}{}{Se eu continuar treinando, eu vou conseguir ficar DEZ segundos no ringue}
*If I keep training, I can last TEN seconds in the ring*
# (FEMALE)
{310}{}{Eu só posso durar sete segundos no ringue, mas posso durar DEZ segundos na cama}
*I may only last seven seconds in the ring, but I can last TEN seconds in bed*