# QUICK LOOK
{100}{}{Você vê um homem idoso.}
{101}{}{Você vê o velho McGee.}

# LOOK
{150}{}{Você vê um homem idoso. Ele está com raiva e resmungando.}
{151}{}{Você vê o velho McGee. Ele está com raiva e resmungando.}

# 1. FLOAT [McGEE = JACKPOT, MALE] (WTG)
{200}{}{Fi duma puta! Cê tirou toda minha sorte!}
{201}{}{Eu vou te matar! Toma isso, seu raider!}
{202}{}{Acha que eu não tenho bolas, moleque? Cai dentro!}
{203}{}{Dog and son uva dog!}#?
{204}{}{Eu vou tirar seu ar pra fora, jogar pra dentro de novo e tirar ele de ocê de novo!}
{205}{}{Cê quer um pedaço do velho McGee, moleque?}
{206}{}{I got yer number, seu chupador de pistola.}
{207}{}{Eu vou arrancar seu couro, fidumaégua!}#I'm gonna whale the holy, howling tar outta you.: nem os tradutores de um forum de tradutores profissionais aí souberam traduzir certo. mas a idéia é essa.
{208}{}{Cê quer um pedaço de mim, num é? Eu vou acabar co'cê.}
{209}{}{I'm gonna cut the fig off you, fella.}#?
{210}{}{Eu vou te castrar como se cê fosse um brahmin.}

# 2. FLOAT (McGEE = JACKPOT, FEMALE] (WTG)
{225}{}{Puta de meia tigela! Cê tirou minha sorte!}
{226}{}{I got yer number, sua putinha.}#?
{227}{}{Tá querendo sentir meu punho, piranha?}
{228}{}{Gonna smack you up, girlie.}#nao sei se o smack aí seria uma bofetada ou beijo. qualquer um seria à força. mas sei lá.

# 3. FLOAT (SLOT MACHINE) (WTG)
{235}{}{Máquina mardita, sua merda de brahmin!}
{236}{}{Raider-de-um-braço-só desgraçado! Pague o velho McGee!
{237}{}{Pára de enrolar o velho McGee, querida...}
{238}{}{Casa contra eu de novo!}
{239}{}{Vamo lá, garota, seja boazinha com o McGee agora...}
{240}{}{Me dá um pouco de amor, docinho.}
{241}{}{I done ast you fer the payoff, c'mon now!}#?
{242}{}{Só mais uma jogada...}
{243}{}{Vou conseguir meus mardito dinhero, mesmo que leve o ano todo...}
{244}{}{Pox on yore hide, ye one-armed bandit!}#?
{245}{}{Talvez eu tenha mais sorte hoje...}
{246}{}{Tomorry's got to have a pretter face.}#?
{247}{}{Today's I gonna win. Lady Luck sez it's nigh-on certain.}#?
{248}{}{::Bate na máquina::}

# 4. FLOAT (McGEE WARNING] (WTG)
{255}{}{Toca na minha máquina de novo e eu vou ver seu couro apodrecer em Golgotha.}
{256}{}{É melhor cê sair de perto da minha máquina se sabe o que é bom procê..}

# 5. FLOAT (McGEE BROKE] (WTG)
{260}{}{Merda! Tô duro de novo!}
{261}{}{House's gainst me again!}
{262}{}{Preciso conseguir mais de grana...}
{263}{}{Máquina mardita! Continua pegando toda minha grana...}

# 6. FLOAT (McGEE APOLOGIZES] (WTG)
{270}{}{Você tem minhas descurpa. Que a sorte esteje co'cê.}#eu nao sou burro não! deixei estejE de proposito
{271}{}{Descurpa, perdi o controle. O sol do deserto faz um homem dizer coisas horríveis.}
{272}{}{::Sinaliza com um chapéu imaginário::}

# 7. JACKPOT, ATTACK (WTG)
{275}{}{}
{276}{}{}
{277}{}{Ocê! Foi ocê que tirou toda a grana da MINHA máquina! A que eu tô jogando por *cinco marditos anos*
 e nunca ganhei uma mardita moeda sequer!}
{278}{}{Ernnhh?}
{279}{}{Ei, espere --}

# 8. JACKPOT, CHANCE TO TALK (7)
{285}{}{Eu gastei todas as economia da minha vida nessa putinha de um braço só e ela nunca me deu sequer a
 hora do dia. Então ocê chega e tira tudo! }
{286}{}{I got yer number, seu chupador de pistola!}
{287}{}{I got yer number, sua vagabunda de meia tigela!}
{288}{}{Hunh? Chupador de pistola? Mim GRANDE chupador de pistola}
{289}{}{Hunh? Onde vagabunda? Mim tem tigela}
{290}{}{Mim não chupador de pistola. Mim }
{291}{}{Mim não vagabunda. Mim  }
{292}{}{Calma, Sr. McGee. Podemos conversar sobre isso?}
{293}{}{Acalme-se senhor. Podemos conversar sobre isso?}
{294}{}{Olha, eu ganhei o dinheiro justamente.}
{295}{}{Espere um momento. E se eu te der o dinheiro que ganhei?}
{296}{}{Chupador de pistola? CHUPADOR DE PISTOLA?! Vovô, você vai precisar de cirurgia pra tirar minhas botas da sua bunda.}
{297}{}{Vagabunda? VAGABUNDA? Vovô, você vai precisar de cirurgia pra tirar minhas botas da sua bunda.}
{298}{}{Que seja. Estou indo.}

# 9. JACKPOT, McGEE NEGOTIATING (8)
{305}{}{Conversar?! CONVERSAR?! O que DIABOS nós tem pra conversar, ladrão de uma figa!}
{307}{}{Olha, eu ganhei o dinheiro justamente, vovô. Não gostou? O problema é SEU.}
{309}{}{Ladrão? Vovô, é melhor tomar cuidado com a língua antes que eu a enfie garganta afora.}
{310}{}{Esqueça, então. Estou indo.}

# 10. JACKPOT, McGEE COMBAT (8)
{315}{}{Rapazinho, não vamos conversar sobre MERDA nenhuma. A única coisa que cê vai fazer é levar chumbo.}
{316}{}{Mocinha, não vamos conversar sobre MERDA nenhuma. A única coisa que cê vai fazer é levar chumbo.}
{317}{}{(Tenta alcançar o rifle, mas pega o ar) Hein? Onde diabos tá o meu rifle...?}
{318}{}{Deixa eu te mostrar...}

# 11. JACKPOT, SQUARE AND FAIR (8, 9)
{325}{}{Justamente seu cu! Rapaz, você assinou sua sentença de morte!}
{326}{}{Justamente seu cu! Moça, você assinou sua sentença de morte!}

# 12. RECOMPENSATE McGEE . . .? (8, 9)
{335}{}{O quê? (Pisca) Cê tá falando que vai me devolver toda a minha grana de volta? Todos os 473 chips?}
{336}{}{Hum, que tal 250 chips?}
{337}{}{Claro. Todos os 473 chips. Aqui está.}
{338}{}{Bem, ainda não. Não tenho tudo isso comigo.}
{339}{}{Esqueça. Estou indo.}

# 13. GIVE McGEE BACK ½ (12)
{345}{}{}
{346}{}{}
{347}{}{Hmmmmmm. Bem... não chega perto do que eu perdi pra'quela máquina, mas não parece
 má idéia pra mim. }
{348}{}{Tá certo, então, rapaz. 250 chips e fica tudo certo.}
{349}{}{Tá certo, então, moça. 250 chips e fica tudo certo.}
{350}{}{Tudo certo, então.}

# 14. McGEE SAYS NO DICE (12, 9)
{355}{}{Sem chance, rapaz. Eu vou levar toda minha grana de volta agora mesmo.}
{356}{}{Sem chance, moça. Eu vou levar toda minha grana de volta agora mesmo.}

# 15. PAY McGEE BACK EVERYTHING (12)
{365}{}{}
{366}{}{}
{367}{}{(Pisca quando os chips mudam de mãos) Bem, agora... merda, eu não sei o que dizer. }
{368}{}{Isso foi muita gentileza docê, rapaz... er, senhor. Eu...}
{369}{}{Isso foi muita gentileza docê, moça... er, senhorita. Eu...}
{370}{}{Sim?}

# 16. TURN BACK ON McGEE (8, 12, 9)
{375}{}{Não se ATREVA a dar as costa pra mim, rapaz!}#confirma, por favor: Don't you DARE turn yore back on me, boy!
{376}{}{Não se ATREVA a dar as costa pra mim, moça!}

# 17. McGEE INTRO (WTG)
{385}{}{}
{386}{}{}
{387}{}{Eh? O que ocê quer, rapaz?}
{388}{}{Eh? O que ocê quer, moça?}
{389}{}{Eh? O que diabos cê tá querendo agora, rapaz?}
{390}{}{Eh? O que diabos cê tá querendo agora, moça?}
{391}{}{Quem você}
{392}{}{ quer jogar mánica}
{393}{}{Dar o fora}
{394}{}{Quem é você?}
{395}{}{O que você está fazendo?}
{396}{}{Se importa se eu der uma jogada?}
{397}{}{Nada. Desculpe por atrapalhar.}

# 18. BOTHERING McGEE (17)
{405}{}{(Uma série de símbolos roda no caça-níqueis. A máquina faz um  *bzzzzt*) Meeeerda!
 Máquina teimosa! Eu vou pegar meu dinheiro de volta qualquer dia...}
{407}{}{ ir agora! Tcha-aau}
{409}{}{Hã... a quanto tempo você está fazendo isso?}
{410}{}{Deixa pra lá. Desculpe o incômodo.}

# 19. McGEE's REASON FOR LIVING (18)
{415}{}{}
{416}{}{}
{417}{}{Quase cinco anos... eu calculo que qualquer dia desses a máquina tem que quebrar, e quando acontecer...
 Pagamento! He-he!}
{418}{}{Ham, boa sorte pra você, então.}
{419}{}{Ceeeeerto. Falo com você mais tarde, então.}

# 20. McGEE JEALOUS (17, 18)
{425}{}{}
{426}{}{}
{427}{}{(Risos) Deixar você tocar minha máquina? E foder com a minha sorte?! Diabos, não! Dá o fora daqui!}
{428}{}{Tudo bem, então...}

# 21. RETARDED vs. McGEE (8)
{435}{}{Idiota imbecil! Eu vou pegar esse dinheiro de volta agora mesmo!}

# 22. McGEE LOSES TEMPER, VOL. 56 (9, 12)
{445}{}{Parece que eu vou ter que pegar meu dinheiro do ser cadáver, então, rapaz. Se perpara pra comer chumbo!}
{446}{}{Parece que eu vou ter que pegar meu dinheiro do ser cadáver, então, moça. Se perpara pra comer chumbo!}

# 23. JACKPOT, ATTACK 2 (7)
{455}{}{Eu gastei toda todas as minhas economia nessa puta de um braço só e ela nunca me deu
 nem as hora do dia. Então OCÊ aparece e pega toda a grana!}

# 24. PAY McGEE BACK EVERYTHING (15)
{465}{}{O sol do deserto faz um homem dizer coisas terríveis. Ocê tem minhas descurpa
 aqui e agora. (Sinaliza com um chapéu imaginário respeitosamente.) }
{466}{}{Que a sorte esteje co'cê, senhor.}
{467}{}{Que a sorte esteje co'cê, senhorita.}
{468}{}{Tudo bem. Desculpas aceitas.}

# end lines
{1290}{}{.}