# 0. QUICK LOOK
{100}{}{Você vê Renesco, o Homem-foguete.}

# 0. LOOK (GLASSES = DISCOUNT, FREEBIE, DONE)
{150}{}{Você vê um homem idoso com um par de grandes e deslumbrantes óculos. 
Ele suspira irritado enquanto você o observa.}

# 0. LOOK (GLASSES = NOTHING)
{200}{}{Você vê Renesco, o Homem-foguete. Enquanto você observa, ele tira 
seus óculos quebrados e começa a polir a única lente boa.}
{201}{}{Você vê Renesco, o homem-foguete. Enquanto você o olha, ele tira seus 
óculos quebrados e começa a polir a única lente boa.}

# 1. FLOAT DIALOGUES (WTG)
{210}{}{Só uma lente, isso é tudo que eu peço.}
{211}{}{Malditos óculos!}
{212}{}{Malditos olhos!}
{213}{}{Você vai COMPRAR alguma coisa?}
{214}{}{Isso não é uma cozinha de sopa. Você vai COMPRAR alguma coisa?}

{215}{}{Eu vou ficar cego se eu continuar nesse ramo de trabalho.}
{216}{}{Vou precisar de algum Chemtex novo…}
{217}{}{A demanda tá ascendente…}

# 2. FLOAT DIALOGUES (WTG)
{225}{}{Vá para o inferno.}
{226}{}{Saia daqui, ou atiro em você até você morrer. Duas vezes.}
{227}{}{Dê o FORA daqui!!.}
{228}{}{Fora! Fora! Fora! Fora! Fora!}

# 3. INTRO SPIEL (WTG)
{235}{}{(O velhote enfia os óculos em seu nariz e suspira em exasperação.) 
SIM? O que  você quer?}
{236}{}{Vamos lá homem, desembucha!}
{237}{}{Vamos lá mulher, desembucha!}
{238}{}{Taa legal ta saindo pra fora… Melhor você afastar(Zip.)}
{239}{}{Taa legal. Precisa abrir sutiã primeiro. Esperar.(Zip.)}
{240}{}{U que mim QUER? U que você TER?}
{241}{}{Encará-lo por um tempo, só pra ter certeza que ele é real, e então 
sair fora.}
{242}{}{Quem é você?}
{243}{}{Hey, eu tenho um par de lentes, se você quiser.}
{244}{}{Como vão os óculos?}
{245}{}{Sabe, algumas coisas sem-sal são tão boas quanto as normais.}
{246}{}{Home, eu to no lugar errado. Adeus.}
# 4.  RETARD (3, 5)
{255}{}{(Encara em choque.)}
{256}{}{…Outro idiota abortado desse mundo pós-holocausto repleto de crianções imbecis. (levanta os seus punhos) Fora da minha loja! Dê o fora agora! Não te quero de volta, ta escutando?!}
{257}{}{Mim lamenta pouco.}
{258}{}{Mim não saber como colocar sutiã de volta.}
{259}{}{Não gritar em mim}
{260}{}{Odeio você!}
{261}{}{Eu estou indo, eu estou indo. Por enquanto.}

# 5.  WHO ARE YOU? (3)
{270}{}{Eu? Ah eu sou o alegre São Nicolau, sua besta quadrada.}
{271}{}{Eu? Oh, eu só sou o bom e velho alegre São Nicolau. E VOCÊ deve ser aquele 
estúpido capanga-para-contratar que está andando pela cidade que nem um 
cachorro com fome esfomeado pelo próprio excremento.}
{272}{}{Eu? Oh, eu só sou o bom e velho alegre São Nicolau. E VOCÊ deve ser aquele 
estúpido resto de lixo pornô caçando o próprio rabo que é tão travado quanto um cavalo e estúpido como um.}
{273}{}{Eu? Oh, eu só sou o alegre velho São Nicolau. E VOCÊ deve ser aquele 
estúpido resto de lixo pornô que os velhotes vestidos com casaco de trincheira usam para preencher as suas fantasias masturbatórias.}
{274}{}{Bem, eu estou feliz já que não preciso me apresentar. O que você 
faz aqui, "Nicolau?"}
{275}{}{São Nicolau? Que diabos é isso?}
{276}{}{Olha vovô, mais um comentário igual a esse, e eu vou estar usando 
seus dentes como colar.}
{277}{}{Olha, eu vou deixar esse seu comentário passar… Dessa vez. Agora, 
quem é você?}
{278}{}{Vocabulário impressionante… "Nicolau". Você é das redondezas?}
{279}{}{Esqueça isso. Eu vou dar o fora daqui.}

# 6. WHO ARE YOU? (3, 5)
{290}{}{(Olha para você, e então resmunga) O nome é Renesco. Apenas diga o 
que você quer, seu… Bem, seja lá o que você for.
(Olhar vesgo em você.) Por baixo dessas roupas você parece um daqueles 
primitivos adoradores do sol.}
{291}{}{Eu sou de uma vila ao Noroeste. Arroyo.}
{292}{}{O que você vende aqui?}
{293}{}{O que eu QUERO? Eu realmente não sei. Na maior parte do tempo eu 
ignoro minha jornada e entro na casa dos outros, mexendo nas estantes dos 
outros… oooh, que nem essas aí!}
{294}{}{Você tem um vocabulário interessante… Renesco. Você é das 
redondezas?}
{295}{}{To fora daqui.}

# 7. WHAT DO YOU SELL? (6, 36, 42)
{305}{}{Eu vendo drogas mais recreativas. É por isso que eles me deram esse 
apelido idiota,'O homem-foguete'. Hmmmph. Eu também vendo alguns suprimentos 
de caravanas. Você PRECISA de alguma coisa ou eu posso voltar a fazer algo 
importante?}
{306}{}{Homem-foguete, huh? Conhece aquela parte da música do Elton John, 
"Homem-Foguete, queimando mmmncfnfm aqui em casa?" O que ele está realmente dizendo ali?}
{307}{}{Eu posso ver o que você tem no estoque?}
{308}{}{Você vende drogas aqui na LOJA?}

{309}{}{Você quer dizer que nem vender drogas para o filho do Wright?}
{310}{}{Volte ao que você estava fazendo.}

# 8. ROCKETMAN/IGNORE QUEST (6, 7, 32, 36)
{320}{}{(Renesco te encara. Parece que ele está te despindo mentalmente, e 
depois te despedaçando membro por membro.)}
{321}{}{Esquece então. Eu tenho algumas outras perguntas…}
{322}{}{Esquece então.}

# 9. YOU SELL DRUGS IN THE STORE? (7)
{330}{}{(Renesco olha para você em desgosto.) Sim. Na LOJA. Isso não é o 
século 20 onde drogas são vendidas por baratas de beco que vivem com um 
constante medo das autoridades.}
{331}{}{Bem, então -}
{332}{}{Mas -}
{333}{}{Uh, Eu acho que é melhor eu -}

# 10. YOU SELL DRUGS IN THE STORE? (9)
{350}{}{Aqui é NEW RENO. Não temos policiais, nem lei, e há fregueses em 
abundância que não se importam em comprar veneno na farmácia da esquina. 
Dessa vez ISSO respondeu sua questão, primitivo?}
{351}{}{Todas exceto uma: Foi Richard Wright um de seus fregueses?}
{352}{}{Ta certo, ta certo… O que você tem no estoque?}
{353}{}{Na verdade, eu tenho algumas perguntas a mais…}
{354}{}{Mas, como você disse, as drogas são… venenosas. Elas matam o 
espírito. Não lhe deixa perturbado vendê-las?}
{355}{}{Com certeza. Eu estou indo.}

# 11. DOES IT BOTHER YOU TO SELL DRUGS IN THE STORE? (10)
{365}{}{Se me deixa perturbado vendê-las para idiotas, escravagistas, 
senhores do crime e tribais que o mundo ficaria melhor sem? Primitivo, três 
palavras: Saia fora mais.}
{366}{}{OK… Eu posso ver o que você tem no estoque?}

{367}{}{Ta certo, ta certo. Olha, eu tenho outras perguntas…}
{368}{}{As drogas daqui de New Reno estão encontrando seu caminho direto para 
outros lugares, e ferindo as pessoas lá. Isso não lhe preocupa?}
{369}{}{Eu vou começar saindo daqui agora mesmo.}

# 12. YOU SELL DRUGS IN THE STORE 2? (11)
{375}{}{Como? Por que eu me preocuparia sobre eles?}
{377}{}{A raça humana sofreu uma terrível tragédia. Agora nós estamos 
tentando reconstruir. Vender Jet parece… contra-produtivo a essa 
reconstrução.}
{378}{}{Bem, Seja o que for. Eu preciso ir agora.}

# 13. SOME OF THE PEOPLE BEING HARMED ARE . . . (12)
{385}{}{Assim. De que maneira. Ninguém esta FORÇANDO esses idiotas a inalar 
Jet. Ninguém esta indo por aí e enfiando isso goela abaixo!
{386}{}{Eu posso ver -}
{387}{}{Mas não -}
{388}{}{Esse é seu -}

# 14. SOME OF THE PEOPLE BEING HARMED ARE . . . 2 (13)
{395}{}{Esses quebradores de pedra com cabeça de lâmpada em Redding SABEM o 
que é que estão tomando, assim eu não sinto um milímetro de pena por eles!
Eu estou remotamente preocupado, Jet limpa o lixo humano que deveria ter 
morrido quando as bombas caíram!}
{396}{}{Uh, tá certo. Posso ver seu estoque?}
{397}{}{Onde é essa Redding que você fala? Por que você a menciona?}
{398}{}{Você mencionou Redding especificamente. Por que o Jet é tão 
prevalente em Redding?}
{400}{}{Você tem o direito de se sentir assim. Eu preciso ir agora.}

# 15. REDDING 1 (14)
{410}{}{Bem, Redding é um… caso especial. Veja, existem pessoas em Reno que 
fazem o preciso para que Redding esteja bem suprida. Afinal, você prova Jet uma vez, 
você está viciado. Assim é como eu faço MINHA vida.}
{411}{}{Falando como, eu posso ver seu estoque?}
{412}{}{Quem é que está fazendo com que Redding está bem suprida? E por 
que?}
{413}{}{Assim eu percebi. Olhe, eu tenho algumas outras perguntas…}
{414}{}{Percebi… Eu preciso ir agora.}

# 16. WHO'S SUPPLYING REDDING? (15)
{420}{}{Bem tribal, eu duvido que você tenha a percepção para noticiar isso 
ainda, mas New Reno não produz nada útil. É igual a um grande, bem iluminado 
carrapato da planície sentada no deserto. Agora, Redding, por outro lado…}
{421}{}{Continue.}
{422}{}{…REALMENTE Produz alguma coisa útil.}
{423}{}{Eu escutei o bastante.}

# 17. . . . DOES PRODUCE SOMETHING USEFUL (16)
{430}{}{Primeira e última vez que eu vou te avisar, tribal: Não termine 
minhas malditas frases. Eu não gosto de primitivos espertinhos que falam 
quando eles deveriam escutar. Não é de admirar que todos vocês ainda usam 
lanças…}
{431}{}{Nem todos de nós. Por exemplo, eu uso uma variedade de armas para 
matar pessoas… Deixe-me lhe mostrar.}
{432}{}{Me desculpe. Por favor, continue.}
{433}{}{Queime no inferno. Eu to fora daqui.}

# 18. GO ON ABOUT REDDING (16, 17)
{440}{}{Redding tem uma força de trabalho estável que mineira materiais 
puros, como ouro mesmo. Alguém em New Reno com certeza poderia usar este 
ouro. Alguém compreende que tudo o que temos que fazer é viciar esses 
mineradores, e nós temos para viver. Você compreende agora?}
{441}{}{Sim… exceto por uma coisa: de onde o Jet veio?}
{442}{}{Quem está tentando viciar todos os mineradores?}
{443}{}{Yeah, eu entendi. Olhe, eu tenho algumas outras perguntas…}
{444}{}{Eu não quero escutar mais nada. Eu tenho que me mandar agora.}

# 19. WHERE DID JET COME FROM? (20)
{450}{}{(Aponta para Myron.) Por quê você não pergunta para o seu pequeno 
amigo sapo tarado bem ai? Eu estou certo de que ele vai estar feliz em lhe 
contar. (olha para Myron) Certo, criança?}
{451}{}{Nós temos uma pessoa para agradecer pelo jet. Você ouviu falar do 
pequeno garoto de ouro da família Mordino, Myron? Bem, o pequeno bastardo 
CRIOU o Jet. Big Jesus Mordino apenas deixa todo mundo saber onde eles 
podem pegá-lo.}
{452}{}{Fale-me mais sobre Myron.}
{453}{}{Existe alguma cura para o Jet?}
{454}{}{Eu tenho outras perguntas…}

# 20. WHERE DID JET COME FROM? (18)
{460}{}{O Jet de Big Jesus Mordino está entrando em Redding. Típico jogo de 
poder. Assim que o cano realmente escoar, esses mineiros vão se ferrar.}
{461}{}{De onde vem o Jet?}
{463}{}{Eu vejo. Olhe, eu tenho algumas outras perguntas…}

# 21. TALK ABOUT MYRON (19, 24)
{470}{}{Tarado como um sapo e com toda a moral de um. Mas é um moleque 
esperto. Alto QI. Mas gastando seus miolos para manufaturar drogas, isso é 
certo pra caralho.}
{471}{}{Aonde eu posso encontrá-lo?}
{472}{}{Eu percebi. Tenho algumas perguntas…}

# 22. WHERE CAN I FIND MYRON? (21)
{480}{}{Os Mordinos estão com ele trancado em algum lugar. Provavelmente 
guardado pesadamente. Não sei exatamente onde.}
{481}{}{Obrigado pela informação. Posso ver o que você tem no estoque?}

# 23. ANY CURE FOR JET? (19, 20)
{490}{}{Uma CURA para o vício Metanfetaminal?! Ha! Eu só conheço duas! Uma é 
a morte. A outra é se trancar em uma jaula sem Jet e vomitá-lo para fora do 
seu sistema. Hmmmph. "Cura," minha bunda! Que coisa sem nexo!}
{492}{}{Tem de ter uma cura. Qual é a composição química do Jet?}

# 24. JET COMPOSITON? (23)
{505}{}{Por que você não pergunta para o seu amigo aí? Ele que criou a droga.}
{506}{}{Eu só vendo a coisa. Eu perguntaria a um cientista. Ou Myron. Ele 
criou a droga.}

# 25. TALK ABOUT VILLAGE (6, 42)
{515}{}{(Renesco lhe encara em silêncio.)}
{516}{}{(Renesco lhe encara de novo, dessa vez em silêncio.)}
{517}{}{Eu acho que você gostaria de Arroyo. É uma vila pacata. Exceto 
pelas plantas possuídas por espíritos maus e é claro, o Templo dos Desafios, 
cheio  daquelas mortíferas armadilhas com lanças e aquelas formigas gigantes 
devoradoras de gente.}
{518}{}{Ei, você já ouviu falar do Kit de Criação do Paraíso? Ou do Vault 
13?}
{519}{}{Tá legal então… Vou dar o fora daqui.}

# 26. TALK ABOUT VILLAGE 2 (25)
{525}{}{(Renesco continua com o catarro.)}
{526}{}{E algumas vezes a anciã fica furiosa com pequenas coisas, 
como… heh-heh… Aquela noite em que eu ignorei meu voto de celibato e transei 
com Reyna – Da qual – As pernas – Apertam – Com – Força – De – Milhares – de 
cobras do desfiladeiro de Arroyo…}
{1526}{}{}{}{(Renesco continua a catarro.)}
{526}{}{E algumas vezes a anciã fica furiosa com pequenas coisas, 
como… heh-heh… Aquela noite em que eu ignorei meu voto de castidade e transei 
com Kor – Que – Fulmina – Igual – A – Milhares de – Garanhões do 
desfiladeiro de Arroyo.}


# 27. TALK ABOUT VILLAGE 2 (26)
{535}{}{(Renesco lhe dá um olhar seco.)}
{536}{}{Foi como ontem. O corpo de Reyna brilhava como prata na luz da Lua 
quando ela se ajoelhou e… ei, você quer saber? Você talvez goste da Anciã. 
Ela é quase da sua idade.}
{1536}{}{Foi como ontem. O corpo de Kor agitou-se que nem bronze na luz da 
Lua quando eu me ajoelhei e… Ei, você quer saber? Você talvez goste da anciã. 
Ela tem quase a sua idade.}

# 28. WHO ARE YOU? (27)
{545}{}{(Renesco continua a lhe encarar como se de alguma maneira ele 
pudesse fazer você desaparecer simplesmente imaginando com força o 
bastante.)}
{546}{}{Eu mencionei que Arroyo foi fundada pelo meu ancestral, o sagrado 
Vault Dweller? Ele fez uma lendária jornada do sul depois de derrotar um 
grande mal. (Estufa o peito e começa a olhar o longe orgulhosamente.) Agora, 
*EU* sou o libertador da minha tribo, escolhido para procurar pelo sagrado 
GECK!}
{547}{}{Ta legal, então, chega de histórias… Melhor eu seguir meu caminho. 
Louve o Vault!}

# 29. GECK? (25, 26, 27, 28, 36)
{555}{}{(O olhar de Renesco se despedaça)}
{556}{}{GECK? Como em '"Kit de Criação do Paraíso"? Vem com uma unidade 
replicadora básica, leitor de holodisks com seleções da livraria do 
congresso, e uma pequena caneta de pena com uma lanterna?}

{557}{}{Sim, mas isso não é importante agora mesmo. Eu não acabei de te 
contar sobre Arroyo.}
{558}{}{Sim! Minha vila esta tendo problemas com suas colheitas, e o GECK é 
necessário para restaurá-las. Você sabe onde eu posso encontrar um?}
{559}{}{Dizem que está selado dentro do Vault 13, ou assim as lendas dizem. 
Você conhece algum lugar assim?}
{560}{}{Se você não vai me ESCUTAR quando eu recitar as escrituras sagradas, 
eu dou o fora daqui.}
{561}{}{Pode ser. Olha, eu tenho que ir.}

# 30. I HAVEN'T FINISHED TELLING YOU ABOUT ARROYO (29)
{570}{}{Sua vila caipira fumadora de erva que se dane, e você com ela. Porque um primitivo que nem você está procurando por um GECK?}
{571}{}{Arroyo… Minha vila caipira fumadora de erva, como você disse… está 
tendo problemas com suas colheitas. O GECK é necessário para restaurá-las.}
{572}{}{É dito que tem de estar selado dentro do Vault 13. Você conhece tal 
lugar?}
{573}{}{Nesse momento, eu não sinto que gostaria de compartilhar isso. 
Adeus.}

# 31. GECK NEEDED TO RESTORE VILLAGE (29, 30)
{580}{}{Hmmmmm. Com certeza poderia fazer isso… facilmente. SE você puder 
encontrar um. Não sei nem aonde você poderia começar a olhar. NRC Ou Vault 
City, mais eu duvido que eles ainda tenham um… ainda…}
{581}{}{Ainda…?}

# 32. GECK NEEDED TO RESTORE VILLAGE (31)
{590}{}{Ainda, esses bastardos direitinhos podem lhe apontar uma pista. Se 
eles falaram devagar e usarem palavras pequenas…}
{591}{}{Você disse NRC ou Vault City? Eu vou ir a procura desses lugares e 
perguntar aos seus moradores sobre o GECK. Obrigado.}
{592}{}{Por quê o GECK não estaria no sagrado Vault 13? As escrituras DIZEM 
que o GECK está dentro do sagrado Vault 13.}
{593}{}{Muito engraçado. Eu tenho outras perguntas…}
{594}{}{Tá legal, então… Eu vou lá checar. Obrigado.}

# 33. GECK NEEDED TO RESTORE VILLAGE (X)
{600}{}{Diabos, não, primata. Eu ouvi falar de Vaults, claro, mas não Vault 
13. Coisa mais próxima é Vault City ao Nordeste… E Se esses aristocratas 
impertinentes habitaram um Vault antes, eles com certeza não vivem mais 
lá.}
{601}{}{Você disse Vault City? Eu vou procurar essa Vault City e perguntar 
a seus moradores sobre o GECK. Obrigado Renesco. Louve o Vault!}

{602}{}{"Vaults?" Existe mais que um Vault?}
{603}{}{Hmmm. Eu tenho outras perguntas…}

# 34. THANKS (32, 33, 35)
{610}{}{Se você está indo para Vault City, não me agradeça, primitivo. É 
melhor ficar em New Reno. Pelo menos as pessoas querendo te botar num túmulo 
são honestas sobre isso.}
{611}{}{Tá certo, então… estou indo para Vault City. Louve o vault!}
{612}{}{Entendi. Obrigado pelo aviso.}

# 35. MORE THAN ONE VAULT? (33)
{620}{}{Por que você acha que é chamada Vault TREZE, chupa-lanças? O quê, 
sua tribo tinha poucos miolos ou você celebra rituais de lobotomia para 
limpar a pequena voz de razão que fala na sua cabeça?}
{623}{}{Yeah, aí vai você falando docemente comigo novamente. Obrigado… Pela 
informação, pelo menos.}

# 36. YOUR VOCABULARY IS IMPRESSIVE (6, 42)
{630}{}{O passado de uma pessoa não é um assunto esperto de conversa aqui em 
New Reno. Agora, o que você quer?}
{632}{}{Você parece um homem educado. Você já ouviu falar de um lugar 
chamado Vault 13?}
{634}{}{Nada, esquece.}

# 37. GLASSES (3, 42)
{640}{}{(Renesco pega os óculos de você e coloca-os. Seus olhos arregalam) 
Doce Reno! É ASSIM que essa maldita loja se parece. (faz careta.) Que 
bagunça… E o que é isso nas estantes? Parece merda de Brahmin.}
{641}{}{Você é bem vindo.}
{642}{}{Aproveite.}

# 38. YOU'RE WELCOME (37)
{650}{}{Hmpphh! Eu… hmmm… uh… onde você conseguiu pegar esses?}
{651}{}{Bem, tinha aquele pequeno Radscorpion, vê, e tinha aquele cientista 
que estava treinando-o, e… Você quer saber? Nem eu acreditei nisso. Só 
fique com eles, tá certo?}
{652}{}{Vamos apenas dizer que eu os encontrei. Por aí.}

# 39. YOU'RE WELCOME 2 (37)
{660}{}{Ei! Espera um minuto! Aonde você encontrou esses?}
{661}{}{Bem, tinha aquele pequeno Radscorpion, vê, e tinha aquele cientista 
que estava treinando-o, e… Você quer saber? Nem eu acreditei nisso. Só 
fique com eles, ta certo?}

# 40. I GOT THEM (38, 39)
{670}{}{Bem, eu…hmnnn… Eu estou… er, muito grato. Eu achava que eu teria que 
sofrer com esses vidros quebrados pelo resto da minha vida. Se eu puder 
fazer algo por você, você me avisa… e, uh, eu vou PENSAR sobre isso.}
{671}{}{Que tal um desconto?}
{672}{}{Esquece… Apenas use-os numa boa, ta legal? Eu tenho algumas outras 
questões…}
{673}{}{Algum dia – e que esse dia nunca chegue – eu vou chamá-lo para fazer 
um serviço para mim. Mas até que esse dia chegue, aceite esses óculos como um presente do 
dia de casamento da minha filha.}

# 41. DISCOUNT (40)
{680}{}{Ehhh…}
{681}{}{Errr…}
{682}{}{Bem…}
{683}{}{Okay! Okay! Eu vou te dar um desconto! Hmphhh.}
{684}{}{Vamos lá. Só um pequeno desconto. Vamos lá…}
{687}{}{Grande! Vamos ver o que você tem, "amigo."}
{688}{}{Excelente! Vamos lá, tenho mais perguntas…}
{689}{}{Eu voltar pra loja depois.}

# 42. QUESTIONS? (8, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 32, 33, 41, 
49, 50, 51, 54, 55, 57, 65, 66, 67, 68, 71, 72, 73, 74, 75)
{700}{}{Seja rápido.}
{701}{}{Olha, eu sou um homem ocupado…}
{702}{}{Bem? Desembucha isso!}
{703}{}{Yeah?}
{704}{}{Eu já te falei sobre minha vila Arroyo?}
{706}{}{Foi você que vendeu Jet para Richard Wright?}
{707}{}{Eu vim coletar o imposto do Sr. Salvatore.}
{710}{}{Eu estou procurando algumas peças de mina para Broken Hills…}
{711}{}{Você tem um vocabulário interessante… Você é daqui?}
{712}{}{Esquece.}

# 43.  TOOLS: SO? (3, 42)
{725}{}{(Olhar desconfiado.) Então?}
{726}{}{Bem, eu preciso de peças para concertar o purificador de ar na mina 
deles. Me disseram que você poderia me ajudar.}
{727}{}{Bem, eu preciso das peças para concertar o purificador de ar na mina 
deles. Zaius me enviou. Ele disse uh… disse… uh… merda.}
{728}{}{Bem, eu preciso de peças para concertar o purificador de ar na mina 
deles. Zaius me enviou. Ele disse "O canário bateu as botas".}

# 44.  TOOLS: SURE. HERE'S SOME MONEY (43)
{735}{}{Sim, acontece que eu tenho algumas peças que poderiam concertar o 
purificador de ar. 100 pratas.}
{736}{}{Eu vou pegar. Aí esta.}
{737}{}{Que tal cinqüenta pratas?}
{738}{}{Uh, eu não tenho uma centena comigo… Eu voltarei depois com o 
dinheiro.}

# 45.  200 OR NOTHING (3, 42, 44)
{745}{}{Inflação devido á irritação administrativa com pechinchadores. 200 
ou nada.}
{746}{}{(faz careta.) 200 ou nada.}
{747}{}{Duas centenas? Você disse uma CENTENA a um segundo atrás!}
{748}{}{Uh, eu vou pegar. Aí vai.}
{749}{}{Uh, Eu não tenho duas centenas comigo… eu volto depois com o 
dinheiro.}

# 46.  HE SAID: SHIT (43)
{755}{}{Eu DUVIDO mesmo que ele tenha dito isso. Não seria "O canário 
bateu as botas"?}
{756}{}{Bem, sim.}

# 47.  HE SAID: AND . . . (43, 46)
{760}{}{E…?}
{761}{}{"E?"}

# 48.  SECOND PART? (47)
{765}{}{E a segunda parte era…?}
{766}{}{"Segunda parte?" Ele não disse qualquer coisa sobre uma SEGUNDA 
parte. Aquele ze-mané bast -!}

# 49.  HE DIDN'T?! THAT BASTARD! (44, 45)
{769}{}{Só estou testando você. Não tem segunda parte nenhuma. Bem, se Zaius 
te enviou, eu SUPONHO que eu tenho algumas peças para compartilhar.}
{770}{}{Aí vai. Não deixe-as cair.}
{771}{}{Obrigado. Eu tenho outras perguntas…}
{772}{}{Uh, obrigado.}

# 50. YOU SELL DRUGS TO WRIGHT'S SON? (7, 10, 42)
{780}{}{Melhor você nem tentar enfiar essa acusação em mim. Você quer saber 
quem fez isso, pergunte para som de violino e som de violino agudo se eles 
continuam vendendo Jet junto com arsênico.}
{781}{}{'O som de violino' e 'Som de violino agudo?' Quem são eles?}
{782}{}{Jules disse para perguntar para você. Ele diz que você vende merda 
ruim.}
{783}{}{Jagged Jimmy disse para perguntar para você. Ele diz que você vende 
merda ruim.}
{784}{}{Os dois disseram para perguntar a VOCÊ sobre isso. Eles dizem que 
você vende merda ruim.}
{785}{}{Eu não acho que foi arsênico… EU REALMENTE acho que ele foi 
envenenado, porém}
{786}{}{Poderia você falar-me qualquer coisa sobre essa seringa de Jet 
vazia?}
{788}{}{Irei questioná-los então.}

# 51. WHO ARE THEY? (50)
{795}{}{Esse urubu Jules e esse protegido mentiroso "Jagged Jimmy". Jules 
tá sempre pousado perto da entrada da cidade procurando visitantes 
ignorantes para vitimizar, e Jagged Jimmy negocia na 2nd Street o resto 
do rebanho de Reno.}
{798}{}{Eles dizem para perguntar para você. Eles dizem que você vende 
merda ruim. Merda que mata pessoas.}
{800}{}{Eu vou falar com eles então.}

# 52. THEY SAID ASK YOU. (51)

{805}{}{Olhe, primitivo… você nem SABE do que você está tagarelando.}
{806}{}{Oh, eu acho eu -}
{807}{}{Yeah? Certo então, por que nã -}

{808}{}{Esquece. Eu tenho algumas outras per -}
{809}{}{Olhe melhor -}

# 53. THEY SAID ASK YOU 2. (52)
{815}{}{Abra sua boca de novo e até mesmo que um cochicho, até mesmo que uma dica, chegue ao Sr.Wright de que eu… ou você… talvez tenhamos tido alguma coisa a ver com a overdose do garoto, nossas vidas não valem merda de Brahmim. Se ISSO acontecer --}
{816}{}{Oh? Então você -}
{817}{}{Eu?! Agora pare por um -}

# 54. THEY SAID ASK YOU 3. (53)
{825}{}{Se ISSO acontecer, seu tribal de MERDA, EU JURO que você vai morrer 
antes de mim. Agora… pela última vez, essa criança nunca comprou nenhuma MERDA de 
mim, entendeu? Melhor você nunca mais dizer seu nome de novo, ou então me 
ajude…}
{826}{}{JULES diz que ele não vendeu para o garoto. JYMMY diz que ele não 
vendeu para o garoto. VOCÊ diz que você não vendeu para ele. Um de vocês 
esta mentindo.}
{827}{}{JULES diz que ele não vendeu para o garoto. JYMMY diz que ele não 
vendeu para o garoto. VOCÊ diz que você não vendeu para ele. Ou vocês todos 
estão mentindo, ou… Alguém mais é responsável.}
{828}{}{Você pode me dizer mais alguma coisa sobre Richard Wright? Por acaso 
ele saía com alguém mais que talvez tenha usado drogas?}
{829}{}{Tá certo… Olhe, eu tenho algumas outras perguntas…}
{830}{}{Certo, certo… Eu estou indo agora.}

# 55. THEY SAID THEY DON'T KNOW. (54)
{835}{}{Eu posso responder isso facilmente. Um dos dois idiotas está 
mentindo para salvar o próprio traseiro. Eles vendem 90% do Jet em 
Reno, e esse é o único lugar no qual o 'garoto' poder ter pego.}
{836}{}{Ou alguém que comprou de um dos três. Quais foram seus clientes que 
no mês anterior talvez possam ter tido contato com a vítima?}
{837}{}{Você pode me dizer mais alguma coisa sobre Richard Wright? Por acaso 
ele saía com alguém mais que talvez tenha usado drogas?}
{838}{}{Entendi… Eu tenho algumas outras perguntas…}
{839}{}{Estou indo agora.}

# 56. THEY SAID ASK YOU. (55)
{845}{}{Seu bastardo estúpido.}
{846}{}{Sua puta estúpida.}
{847}{}{Eu DISSE para você não falar o nome dele aqui. Dê o fora! Se eu ver 
você de novo, eu VOU ATIRAR EM VOCÊ! Se o Sr.Wright vier procurando por mim, 
achando que eu matei seu garoto, VOCÊ VAI morrer primeiro.}
{848}{}{Não me ameace, velhote…}
{849}{}{Whoa. Eu to indo agora.}

# 57. KILLER REVEALED! . . . (55)
{855}{}{Eu NÃO tenho idéia. Eu não conhecia o garoto, então eu não conhecia 
seus amigos OU seus hábitos. O único que poderia lhe dizer claramente está muito 
ocupado morto em Golgotha para lhe falar.}
{856}{}{Golgotha?}
{858}{}{Talvez eu faça isso. Adeus.}

# 58. TRIBUTE (3, 42)
{865}{}{Então você perdeu a viagem. EU PAGUEI ao Sr.Salvatore seu 'tributo' 
*duas semanas atrás,* pelo compromisso. Eu não sei quem você é, ou o 
que você acha que está fazendo, mas você não vai pegar uma moedinha vermelha 
de mim. Saia.}
{866}{}{Olhe, grão-de-bico. Pare de me dar dificuldade. Espirre as moedas, 
ou você vai estar tossindo sangue.}
{867}{}{Eu sou o representante do Sr.Salvatore. Você vai me dar o tributo 
que eu pedi, e você fará isso agora.}
{868}{}{Eu vou checar com o Sr.Salvatore sobre o compromisso, e então eu 
voltarei.}

# 59. TRIBUTE 2 (58)
{875}{}{Você perdeu sua audição, garoto?}
{876}{}{Você perdeu sua audição, garota?}
{877}{}{EU DISSE EU-JÁ-PAGUEI-O-IMPOSTO. *Duas semanas atrás.* Se você 
fosse realmente do Salvatore, você saberia isso. Agora rasga!}
{878}{}{Olhe. Última vez: passe-me as moedas.}
{879}{}{Você é que perdeu a sua audição. Eu sou um representante do 
Sr.Salvatore, e você vai pagar o imposto.}
{880}{}{Eu te avisei, grão-de-bico. Parece que nós vamos ter que fazer 
isso da maneira difícil. Hora de morrer.}
{881}{}{Eu vou checar com o Sr.Salvatore sobre o imposto, então eu vou 
voltar.}

# 60. SPEECH SUCCESS (59)
{890}{}{Prove que você representa os Salvatore, e eu IREI CONSIDERAR te dar as moedas. Senão você não levará merda nenhuma.}
{891}{}{Eu não preciso provar nada. Eu sou o representante dele, e 
isso é tudo que você precisa saber.}
{892}{}{O quê, você acha que essa pistola laser é só para mostrar?}
{893}{}{Se você não me dar o imposto em cinco segundos, EU VOU MATAR você.}

# 61. SPEECH FAILURE (59, 60)
{900}{}{Dê o fora daqui, porra, seu ladrão de moedas! É só você mostrar a sua cara aqui de novo, e eu atiro em você eu mesmo!}
{901}{}{Eu te avisei. Hora de morrer.}


# 62. SHOW OFFICIAL, CAN'T PAY (3, 42, 60)
{910}{}{Hmmmph. Não importa, não posso pagar mesmo. A última coleta quase me quebrou.}
{911}{}{Problema seu. Você dará o dinheiro agora. O Sr. Salvatore não está interessado nas suas desculpas.}

# 63. GIVE ME MONEY EVEN THOUGH YOU CAN'T PAY (62)
{920}{}{Me ameaçar não vai ajudar. Sr.Salvatore quer seu dinheiro. Eu não 
tenho. Ele vai ficar puto comigo, mas ele vai ficar puto com você, também. 
Salvatore não GOSTA de pessoas que o decepcionam… Melhor você pensar em algo 
rápido.}
{921}{}{Já pensei. Eu vou pagar sua parte nesse período. Em troca, você 
mais me dar um desconto na sua loja.}
{924}{}{Eu vou tentar pensar em alguma coisa… Eu volto.}

# 64. IN EXCHANGE FOR FREE ACCESS TO YOUR STORE (63)
{930}{}{Agora pare, seu neandertal…}
{931}{}{Eu não quero mais discutir com você. Minha paciência está no fim. 
Esses são os meus termos.}

# 65. THOSE ARE MY TERMS (64)
{940}{}{Eu… Olhe, agora, eu… hmmmm… Tá certo, então. Você vai pegar um… 
"desconto."}
{941}{}{Deixe-me ver seu estoque. Eu vou fazer minhas 'compras' agora.}
{943}{}{Eu não quero nada agora, mas não se preocupe, eu vou voltar.}

# 66. HOW'S THE GLASSES (64)
{950}{}{(cruza os braços.) Adequados. Se você está esperando alguma nota por 
ser um bom samaritano, você está GRAVEMENTE errado. Agora… O que você quer?}
{951}{}{Deus amaldiçoe seja lá o que Deathclaw ou diretor de marketing te deu! Você QUER alguma coisa? Aqui! AQUI! Tome ISTO! Pegue TUDO que eu tenho! Qualquer coisa para fazer você ME DEIXAR SOZINHO!}
{952}{}{Deixe-me ver seu estoque.}
{953}{}{Eu tenho algumas perguntas…}
{955}{}{Que porra É essa…?}

# 67. POISONED (50)
{960}{}{Envenenado? Sobre o que você está tagarelando?}
{961}{}{A condição do corpo era compatível com envenenamento de Radscorpion. 
Eu acho que ele morreu por que seu Jet estava envenenado, NÃO por causa de 
uma overdose.}
{962}{}{Eu encontrei uma seringa de Jet vazia no quarto dele. Tinha traços 
de veneno de Radscorpion dentro.}
{963}{}{Esqueça. Eu tenho outras perguntas…}
{964}{}{Esqueça isso. Eu tenho que ir agora.}

# 68. POISONED 2 (67, 73, 74)
{970}{}{Radscorpion…? (Renesco congela subitamente, como se lembrasse de 
alguma coisa.)}
{971}{}{Seu filho da puta. Você *envenenou* o moleque, não foi?}
{972}{}{Você sabe algo sobre isso, não sabe?}

# 69. POISONED 3 (68)
{980}{}{Whoa! Agora espere só um minuto…!}
{981}{}{Não tente dar uma de espertinho comigo, Renesco! Tente jogar a culpa em cima de mim e você 
vai fazer companhia ao Richard. Entendeu?}
{982}{}{Chega. Eu e o Sr.Wright vamos ter uma pequena conversa. Bom dia, 
Renesco… ou eu deveria dizer,"adeus."}

# 70. POISONED 4 (69)
{990}{}{Espera um minuto! Olhe… Eu nunca VENDI isso para o moleque! Ele 
nunca comprou nada de mim! Eu… fui solicitado para fazer algum Jet banhado 
com veneno de Radscorpion, mas… mas eu NUNCA vendi isso para o moleque!}
{991}{}{Pediram para você fazer um jet envenenado? Para quem?}
{992}{}{Você vendeu isso para QUEM?}

# 71. POISONED 5 (70)
{995}{}{Os Salvadores pediram – Eles disseram que isso era um… "pedido 
especial." Eu não sabia que eles iriam dar isso para a criança Wright. Você 
TEM que acreditar em mim… Eu não enveneno crianças!}
{996}{}{Só adultos, hein, Renesco? Seu filho da puta lamentável…}
{997}{}{PORQUE você envenenou o Jet? Você deveria saber que eles iriam 
matar alguém com aquilo.}
{998}{}{Ta certo, ta certo, eu acredito em você. Eu tenho outras 
perguntas…}
{999}{}{Apenas cale a boca. Olhe, eu tenho algumas outras perguntas…}
{1000}{}{Os Salvadores, hêin? Eu acho que o Sr. Wright vai querer saber 
disso.}

# 72. RESPONSE (71)
{1005}{}{Os Salvadores MANDAM em mim. Eles MANDAM nesse lugar, e quando eles 
querem alguma coisa, eu dou a eles, ou então eles me matam e me 
substituem. Eu nunca quis causar nenhum ferimento a esse garoto.}
{1007}{}{Apenas cale a boca. Olhe, eu tenho algumas outras perguntas…}
{1008}{}{Yeah, estou certo de que você tinha a melhor das intenções 
enquanto você estava misturando esse Jet com veneno. Adeus, Renesco.}
{1009}{}{Até mais tarde, Renesco.}

# 73. JET CANISTER (50)
{1020}{}{Está vazio. É uma seringa de Jet igual a centenas de outras em toda 
New Reno. Mais alguma coisa em que posso lhe ajudar?}
{1021}{}{Por acaso isso é seu?}

{1022}{}{Sabe qualquer coisa sobre os traços de veneno de Radscorpion 
que estão nessa seringa?}
{1023}{}{Yeah, eu tenho algumas outras perguntas…}

# 74. JET CANISTER (73)
{1030}{}{Não. Posso te ajudar com alguma OUTRA coisa?}
{1033}{}{Não. Adeus.}

# 75. GOLGOTHA? (57)
{1040}{}{Golgotha? O cemitério enorme fora da cidade ao sul. Siga o 
fedor… o único ALÉM do seu próprio.}
{1041}{}{Oh. Ei, tenho algumas outras perguntas…}
{1042}{}{Continue falando carinhosamente desse jeito, Renesco, e você vai 
agonizar por muito tempo.}
{1043}{}{OBRIGADO, Renesco.}

{2000}{}{Você expôs o envolvimento de Renesco na morte de Richard Wright.}

# END LINES
{5257}{}{É tão grande. Eu ir agora.}
{5259}{}{Não grite. PORQUE VOCÊ CONTINUA GRITANDO? PARE A GRITARIA!}
{6259}{}{MATAR VOCÊ}
{5260}{}{…*sniff*…vou chamar o irmãozão pra te bater, velhote! Aí então nós 
teremos sorvete e… *sniff* DOCE e uma grande festa com palhaços e…}

