# 0. QUICK LOOK [FEMALE]
{100}{}{Você vê a pesquisadora chefe, Marjorie Reed.}

# 0. LOOK [FEMALE]
{150}{}{Você vê uma mulher cansada. Sua cabeça foi raspada e está vestindo um jaleco branco.}
{151}{}{Você vê Marjorie Reed. Ela está enchendo uma seringa, resmungando baixo.}

# 1. FLOAT (COMPANION = MYRON)
{200}{}{Olá, Myron.}
{201}{}{Myron, você tem um minuto…?}
{202}{}{Sabe quando os novos escravos chegarão, Myron?}
{203}{}{Myron, estes novos resultados são muito promissores…}
{204}{}{Myron, tem um minuto?}

# 2. FLOAT (NORMAL)
{215}{}{Onde diabos está o Myron…}
{216}{}{Traga o Myron aqui. Ele tem que ver isso.}
{217}{}{Bem que esses escravos poderiam calar a boca…}
{218}{}{Onde eu deixei aquela seringa…}
{219}{}{Alguém viu o número 31? Ele estava aqui há um segunda atrás.}
{220}{}{Os escravos tomaram mais do Jet Beta?}
{221}{}{Resultados dos testes com o Jet Beta são muito promissores, mas…}
{222}{}{O estado de êxtase dura de 15 min a uma hora... calculando um dose/hora... hmmmnnn.}
{223}{}{No. 12 ainda está com hemorragia nasal…}
{224}{}{É a quinta vez que o No. 12 tem uma convulsão... aumente a dose, vamos ver o que acontece…}
{225}{}{Bem, que TIPO de alucinações ele estava tendo?}
{226}{}{Cheque o batimento cardíaco deste aqui. Se ainda estiver em limites toleráveis, aumente a dose.}
{227}{}{Por que a escrava no grupo de controle se matou? Nós nem a estávamos testando!}
{228}{}{Damn guards can keep track of their own asses…}#track aqui é marca de agulha devido as injecoes. nao consegui uma boa traducao

# 3. CLICK (COMPANION = MYRON)
{235}{}{Olá, Myron, senhor. Os teste estão prosseguindo como no planejamento.}
{236}{}{Myron, senhor, esse novo tipo de Jet é extremamente viaciante. Os escravos estão quase matando uns aos outros por mais.}
{237}{}{Myron, senhor, o senhor ficará satisfeito ao notar que os escravos estão preferindo Jet a comer!}
{238}{}{Quem são estas pessoas com você, Myron? Novos escravos?}
{239}{}{Myron, senhor, o terceito grupo de teste parece estar ragindo melhor de todos os grupo.}
{240}{}{Myron, senhor, se tiver um momento... eu acho que o próximo grupo de teste deve ter pelo menos três crianças, senhor.}
{241}{}{Myron, senhor, o No. 46 teve um ataque cardíaco; nós estamos restringindo as doses para seis de agora me diante.}
{242}{}{Myron, senhor, por favor... nós precisamos de um novo carregamento de seringas de Vault City. Não podemos continuar reutilizando estas.}
{243}{}{Sabe quando os novos escravos chegarão, Myron, senhor?}
{244}{}{Myron, senhor, nós mudamos três escravos do grupo de controle para o grupo de teste devido àquelas falhas respiratórias que tivemos semana passada.}
{245}{}{Myron, más notícias, senhor. Nós tivemos que atirar em um dos escravos que tentaram escapar. Que desperdício.}
{246}{}{Myron, esse novo alunicinógeno que você desenvolver é muito promissor, mas não é tão viciante quanto o Jet…}

# 4. INTRO (WTG)
{250}{}{(A mulher careca sequer olha por cima da prancheta.) Sim?}
{251}{}{Não!}
{252}{}{Sim!}
{253}{}{Heh-heh. Você careca. Você parecer homem}
{254}{}{Delenn?}#?
{255}{}{Cair fora}
{256}{}{Quem é você?}
{257}{}{Desculpe, eu pensei que você era outro tipo de mulher careca com prancheta. Eu vou sair agora.}

# 5. RETARD (4)
{265}{}{(A mulher levanta a cabeça e olha pra você.) Você é um dos escravos de controle? Como se isso tivesse importância. Guadas! Detenham esse escravo!}
{266}{}{Onde escravo? Mim não ver um}

# 6. WHO ARE YOU? (4)
{275}{}{Olha, eu estou MUITO ocupada, então se você não se importa... [Olha pra você por cima da prancheta, então fecha a cara] QUEM é você? Como chegou aqui?}
{276}{}{Olha, eu estou MUITO ocupada, então se você não se importa... [Olha pra você por cima da prancheta, então fecha a cara] VOCÊ de novo? O que quer agora?}
{278}{}{Sou um dos novos empregados aqui.}
{279}{}{Estou procurando pelo Myron. Ele está por perto?}
{280}{}{São resultados de testes nessa prancheta? Eu posso vê-los?}
{282}{}{Deixe pra lá. Desculpe o incômodo.}

# 7. DOOR WAS OPEN (6)
{295}{}{Essa área não é aberta pra... visitantes. Saia ou eu chamarei os guardas.}
{296}{}{Mas eu tenho algumas perguntas pra te fazer...}
{298}{}{São resultados de testes nessa prancheta? Eu posso vê-los? Eu também sou uma espécie de pesquisador.}
{300}{}{Muito bem. Desculpe o incômodo.}

# 8. BUT HEY. . . (7, 24)
{310}{}{Guardas! Guardas, detenham essa pessoa!}

# 9. I'M ONE OF THE NEW PERSONNEL (6, 7)
{315}{}{MAIS guardas. Ha! Como se ele fizessem algo de útil... olha, você DEVE ter recebido instruções de seja lá quem for que te mandou aqui. Fale
 com os outros guardas para descobrir suas tarefas. Agora vá.}
{316}{}{Eu não sou guarda, eu faço pesquisas. Você tem alguma tarefa para mim?}
{317}{}{Desculpe, mas eu esperava que VOCÊ me mostrasse o lugar. Eu vi você parada bem aqui e
 me senti na OBRIGAÇÃO de falar com você. Talvez depois do "tour" nós poderíamos almoçar...?}
{318}{}{Agradeço. Você foi muito útil.}

# 10. I'M ONE OF THE NEW RESEARCHERS (6, 7, 9)
{325}{}{Um dos PESQUISADORES...? Hmmmm. Eu nunca te vi antes. O que você sabe sobe pesquisa farmaceutica?}
{326}{}{Certo. Sente-se e escute.}
{327}{}{Eu tenho amplo conhecimento sobre composição e manufatura da base de componente neuroquímicos, e acho que
 poderia ajudar nos seus estudos.}
{328}{}{Eu tenho que ir.}

# 11. I'M ONE OF THE NEW RESEARCHERS (10)
{335}{}{Ha! Acho que vou ver você sair agora mesmo. Saia ou eu chamo os guardas.}
{336}{}{Certo.}
{337}{}{Eu vou…::resmungo::…sua puta careca.}

# 12. I KNOW QUITE A BIT ABOUT BASE NEUROCHEMCIAL COMPOUNDS . . . (10)
{345}{}{Hmmmm. Muito bem, então. Deixe-me fazer um resumo do que nós fazemos aqui: nós testamos os efeitos e a potência da metanfetamina
 chamada Jet..}
{346}{}{Entendo. E como anda a pesquisa?}
{347}{}{Acho que entendi. Vou examinar o resto da área de teste por mim memso.}

# 13. I SEE. AND HOW IS THE RESEARCH COMING? (12, 22, 25)
{355}{}{Não muito bem. Nosso prazo é curto e nós precisamos purificar o processo de manufaturo do Jet o quanto antes.}
{356}{}{Por que? O Jet não é viciante o suficiente?}
{357}{}{Por que o prazo curto?}
{358}{}{Parece um trabalho duro. Olha, eu tenho que resolver algo rápido - volto logo.}

# 14. WHY THE TIGHT SCHEDULE? (13)
{365}{}{Ninguém sair por aí dizendo isso, mas provavelmente é devido à distribuição de Jet em Redding. O Jet já potente *o sufuciente*, mas
 há um grande espaço para melhoras, e o chefe quer um aumento do vício de Jet em Redding.}
{366}{}{Qual é o lance com Redding?}
{367}{}{Bem, boa sorte com prazo.}

# 15. WHY? JET SEEMS ADDICTIVE ENOUGH ALREADY . . . (13)
{375}{}{Já é potente o suficiente, mas ainda há espaço para melhoras. O chefe quer aumentar a distribuição de Jet em
 Redding, e eles querem o grau de vício o mais perto possível de 100%. Vai nos custar longas horas de trabalho.}
{377}{}{Ogradeço a informação. Eu volto mais tarde.}

# 16. WHAT'S THE DEAL WITH REDDING? (14, 15)
{385}{}{Viciar os mineradores em Redding com Jet, e seja lá quem controla o Jet, controla Redding. Típico jogo de poder.}
{386}{}{Então... quem controla as drogas?}

# 17. SO WHO DOES CONTROL THE DRUGS? (16)
{395}{}{Quem controla as drogas? Os Mordinos. É claro, Myron lida com todo o trabalho de composição do Jet.
 Nós fazemos o trabalho de limpeza.}
{396}{}{Myron é seu chefe?}

# 18. MYRON'S OUR BOSS? (17)
{405}{}{Pode-se dizer que sim. Ele é cabeça por aqui, mas ele não se importa com o que acontece
 aqui em cima. Ele fica mais na vault subterrânea... sem visitas, exceto pelo trem de prostitutas. Típico projeto de líder.}#except for the train of prostitutes *train=treino ou trem?
{406}{}{Eu posso vê-lo?}
{407}{}{É, negócio de markenting. De qualquer forma, agradeço a informação. Eu volto mais tarde.}

# 19. COULD I SEE HIM? (18)
{415}{}{Eu suponho... vou te dar um crachá temporário; apenas mostre-o aos guardas. Seja rápido, Myron não
 gosta que pessoas fiquem lá por muito tempo.}
{416}{}{Eu suponho... vou te dar um crachá temporário; apenas mostre-o aos guardas. Seja rápido, Myron não
 gostaqude pessoas fiquem lá por muito tempo. Apesar de ele poder fazer uma exceção no seu caso.}
{417}{}{Certo. Te vejo depois.}

# 20. EXCUSE ME FOR BEING FORWARD (FEMALE) (9)
{425}{}{Olha, eu estou MUITO ocupada, se você não se importa…}
{426}{}{Olha, eu... eu estou, hã, muito ocupada, então se você puder me der licença…}
{427}{}{Deixe pra lá, então...}
{428}{}{Certo.}
{429}{}{Certo. ::resmungo:: ...sua puta careca.}

# 21. EXCUSE ME FOR BEING FORWARD (GOOD) (9)
{435}{}{Isso...hmm...eu estou MUITO lisojeada, mas estou muito ocupada no momento... então... hã...}
{436}{}{Bem, você se importa se eu te pegar depois do trabalho? Sem pressão.. só um jantar, alguma
 conversa. Você parece um pessoa necessitada de um pausa no trabalho. As coisas aqui devem te manter muito ocupada.}
{437}{}{Bem, eu tinha que perguntar. Agradeço assim mesmo.}

# 22. DO YOU MIND IF I PICKED YOU UP AFTER WORK . . .? (21)
{445}{}{Bem, não TÃO ocupada... heh... bem, não, muito ocupada. Digo, a maior parte da rotina é testar as drogas e ocasionamente nós temos
 um escravo além da conta...}
{446}{}{Injetar metanfetaminas propositalmente para pesquisa não te faz questionar sua humanidade?}
{447}{}{Uau. Isso parece perigoso. Você nunca se machucou? Já teve fatalidades com pacientes?}
{448}{}{Testar drogas? Sério? Como vão as coisas?}
{449}{}{Parece interessante, mas eu tenho que ir. hã, eu vou mais tarde.}

# 23. DON'T YOU EVER QUESTION YOUR HUMANITY? (22)
{455}{}{Essa foi uma tentativa fraca ou uma piada?}
{456}{}{Só perguntando. Digo, o que você acharia se fosse vendida pela escravidão, trazida até aqui e então te enchessem de drogas?}
{457}{}{Hã, sim. Eu tenho que ir.}

# 24. PUMPED FULL OF DRUGS? (23)
{465}{}{Eu estou DESTE lado, eles estão DAQUELE lado. Desde que estamos fazendo hipóteses, VOCÊ
 gostaria de saber como é estar com eles? Nós temos mais uma vaga ou duas.}
{466}{}{Opa, espera um minuto aí...…}
{467}{}{Hã, não mesmo. Desculpe o incômodo.}

# 25. PATIENT FATALTIES (22)
{475}{}{Morte de escravos? Um pouco. Maioria por overdose - geralmente culpa de um tecnico - ou eles mesmo se machucam.
 Alguns ingerem Jet demais, e ele REALMENTE querem ficar doidões.}
{476}{}{E como anda o teste das drogas?}
{477}{}{Aposto que sim. Bem, agradeço a informação. Você foi muito útil.}

# 26. ACTUALLY, I WAS LOOKING FOR MYRON (6)
{485}{}{Tente as escadas para o laboratório. A porta vigiada. Se você o vir, diga para ele vir aqui pra cima quando tiver
 tempo. SE ele não estiver muito ocupado.}

# GET BADGE MESSAGE
{1000}{}{Você ganhou um crachá temporário da Marjorie.}