# 0. QUICK LOOK (WTG)
{100}{}{Você vê o Coffin Willie.}
*You see Coffin Willie.*

# 0. LOOK (WTG)
{150}{}{Você vê um ghoul velho, fedorendo e ríspido. E cara, ele FEDE.}
*You see an old, stinky, crusty ghoul. And boy, does he SMELL.*

# 1. DIG UP (WTG)
{200}{}{Whoa. Esse túmulo FEDE.}
*Whoa. This grave SMELLS.*
{201}{}{Oh, bem…é melhor continuar cavando.}
*Oh, well…better keep digging.*
{202}{}{Que po-?}
*What th-?*
{203}{}{Sobre a porra do tempo! Você pode cavar mais DEVAGAR, seu idiota?}
*About friggin' time! Could you dig any SLOWER, idjit?*
{204}{}{Sai da minha frente, smoothie.}
*Outta my way, smoothie.*
# lenny in party
{205}{}{P..pai?}
*D'dad?*
{206}{}{Agora não, Lenny, eu não tô disposto pra conversar.}
*Not now, Lenny, I ain't in th' mood to be talkin'.*

# 2. CLICK/FLOAT (WTG)
{300}{}{Tava em Reno tomanu umas quando os malditos smoothies me jogaram nessa merda de túmulo…}
*Jest pop inta Reno fer a lil' drinking n' whoring, n' damned smoothies jam me inna goddamn grave…*
{301}{}{Graças a Deus eu não tenho nariz, ou me sufocaria com o meu próprio cheiro.}
*Good thing I ain't got no nose, or I woulda choked on my own stink.*
{302}{}{Não existe nenhuma porra de respeito com os Ghouls.}
*Ghouls don't get no damn r'spect.*
{303}{}{Só tinha parado pra tomar uma bebida, e esses filhos da puta de Reno me enterraram vivo.}
*Just stopped in the city for a drink, n' those Reno assholes bury me alive.*
{304}{}{Nada mais entediante do que ficar tossindo durante meses.}
*Nothing more boring than bein' in a coffin for months.*
{305}{}{Tire suas mãos de mim, smoothie. Eu tenho que ir para um lugar.}
*Hands off, smoothie. I got places to go.*
{306}{}{Tire suas mãos lisas de mim, smoothie.}
*Get your smoothie mitts offa me, smoothie.*

# HEADSTONE
{500}{}{Na lápide está escrito: "Aqui está o filho da puta mais burro que já pisou em New Reno."}
*The headstone reads: "Here lies the dumbest son of a bitch ever to set foot in New Reno."*

{550}{}{Um cheiro horrível está saindo desse túmulo.}
*There's a horrible odor flowing from the grave.*

{600}{}{Hey!}
{601}{}{Eu tô escutando alguém aí fora!}
*I ken hear someome movin' round out there!*
{602}{}{Não pisa no túmulo! Tá cheio de sujeira aqui!}
*Don't step onna grave! It packs the dirt in!*
{603}{}{Rápido, PEGUE UMA PÁ!}
*Quick, GET A SHOVEL!*
{604}{}{Alguém pode me desenterrar? Eu preciso de uma bebida!}
*Would somebody dig me up already? I need a drink!*
{605}{}{Tô sentindo uma minhoca? Ah...esquece.}
*That a worm I feel? Oh...nevermind.*