# QUICK LOOK

# EXAMINE
{150}{}{Você vê um caça-níqueis feio e enferrujado.}
{151}{}{Você vê um caça-níqueis muito feio. Ele está coberto de ferrujem e está amassado em várias partes, como se tivesse sido
 atingido repetidamente por um objeto pesado.}

# 1. FLOAT DIALOGUE (PLAYER = MALE, DRUNK OR HIGH) (WTG)
{200}{}{*Ei, meu jovem…::tosse:: ::tosse:: ::ofegante:: …vem…::tosse seca::…me jogá por um segundo.*}
{201}{}{*Olá, meu jove- ::tosse:: ::tosse::*}
{202}{}{*Como vai, jovem amig- ::tosse:: ::tosse seca:: ::ofegante:: …por que…::tosse seca::…não vem fazê uma aposta?*}
{203}{}{*Trac-trac-trac*}
{204}{}{*Clink*}
{205}{}{*Thwunk*}
{206}{}{*Ker-chunka-chunka*}
{207}{}{*Zzzztttt*}
{208}{}{*Ka-dink-thunk-snap*}
{209}{}{*Ka-chuuuunk-snap-creeeeeak*}
{210}{}{*Clunk*}
{211}{}{*Tink-tinkety-tink*}
{212}{}{*Efeito de som idiota*}
{213}{}{*Ei, belezin…::tosse:: ::tosse:: ::ofegante:: …vem…::tosse seca::…me jogá por um segundo.*}#a partir daqui acho que é pra feminino. só não está indicado.
{214}{}{*Olá, belezin- ::tosse:: ::tosse:: Disgraça!*}
{215}{}{*Coloca uma moeda e puxa meu braço. Eu prometo que vou ser gentil cocê. He-he.*}
{216}{}{*Mas que gracinha de garot-- ::tosse:: ::tosse seca:: ::ofegante:: Por que…::tosse seca::…num vem me jogá?*}

# 4. RETARD (WTG)
{230}{}{Você vê uma caixa de metal inanimada com três olhos e um braço.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{235}{}{A estranha caixa de metal inanimada com três olhos e um braço não responde.}

# 6.  RETARD PULLS HANDLE (4, 5)
{240}{}{Você segura o braço dela e balança calorosamente. Quando faz isso, ouve um som alto como um chocalho!}

# PLAY. . . ? (WTG, 14, 15)
{245}{}{(Você vê um caça-níqueis. Talvez seja o caça-níqueis mais feio que você já tenha visto em New Reno. A alavanca está torta, duas
 das janelas estão quebradas e está completamente amassado.)}
{246}{}{Sua mão treme quando pega as moedas. (A máquina continua sussurrando pra você com sua voz moribunda.)
 *Vem, agora…::tosse::…isso mermo…*}

# LOOOOOOSER (8)
{250}{}{Você ouve um barulho de doer os ouvidos quando as roletas giram e...}
{251}{}{NADA! (A máquina ri sarcasticamente.) *Mais sorte na próxima, jove -- ::tosse:: ::tosse:: ::ofegante::}

# WIN x1 (8)
{255}{}{(A máquina continua sussurrando pra você.) *Tenta de novo, jovem... mais uma pra - ::tosse:: ::tosse seca:: - aproveitá a sorte.*}

# WIN x2 (8)
{260}{}{Finalmente, as roletas param e revelam… }
{261}{}{(A máquina ri calorosamente.) *Isso mesmo, jovem. Eu sabia que cê cons... ::tosse:: ::tosse:: …eguiria.*}

# WIN x3 (8)
{265}{}{(A máquina dá uma gargalhada.) *Muito bem, é isso mermo. Eu sabia que ainda tinha… ::ofgante:: …mojo sobrano! He-he!*}

# DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{270}{}{(Diante de você talvez esteja o caça-níqueis mais feio que você já viu. Você olha pra ele com uma fascinação mórbida,
 de repente uma voz moribunda masculina sussurra através do compartimento de moedas.) *Nunca vi um jovem como ocê por aqui antes - ::tosse::
 ::tosse:: Cê quer… ::tosse seca:: ::ofegante::… tentá a sorte?*}

# DRUNK CONVERSATION 1 (13)
{275}{}{*Eu ainda tô aqui, jovem.* o caça-níqueis faz barulhos. *Ei, chega mais... cê qué fazê uma aposta? Eu não tenho muito tempo nesse mundo.*}#I ain't long fer this world. seria: não ligo pra esse mundo, mas a máquina morre lá pra frente. Acho que é isso mesmo.

# DRUNK 2 (14)
{280}{}{*Eu sou o bandido maneta mais velho de Reno. Eu tô por aqui desde…::tosse:: ::tosse::…bem, desde sempre. Starting ta
 show, ah'm sorry ta say. Olha, cê vai apostar ou eu vou ficar esperando aqui e enferrujar?*}#Starting ta show, ah'm sorry ta say

# DRUNK 3 (15)
{285}{}{::Tosse:: ::tosse:: *Num tenho TEMPO pra batê papo, jovem. E com certeza cê também tem coisas mais importantes pra fazê do que conversar comigo, eh? Alguma coisa em mente?*}

# DRUNK 4 (16)
{295}{}{*Calma lá, jovem. Pára de chorá. Vai ficá tudo bem, entendeu? Eu vou tomá conta docê, ok?*}

# DRUNK 5 (17)
{300}{}{*Ei, qual é, já chega disso. Vai dá uma volta, limpá a mente…::tosse::…ajuda a relaxá. Cê acha que vai ficá melhor,
 jovem?*}
{301}{}{Eu vô ficá legal... valeu por cunversá cumigo, caça-níqueu véio}

# DRUNK 6 (18)
{305}{}{*Ah! Num precisa agradecê, [X]. Agora, cê vai lá fora e mostra o INFERNO pra eles. Cê é o único herói que nós temo nesse mundo
 de desgramados e ladrãos... ::tosse:: ::ofegante:: ::tosse::… toma cuidado, entendeu??*}
{306}{}{'Tendi -- cê tamém, tá?}

# JACKPOT! (8)
{310}{}{(Assim que você puxa a manivela, você pensa ter ouvido a máquina dar um suspiro de alívio, seguido de um longo silêncio. Quando você
 está prester a desistir, ouve um som de algo fazendo barulho bem no fundo da máquina. Alguns segundos depois, o barulho cresce pra
 um barulho ensurdecedor quando moedas começam a pular pra fora como uma avalanche!!) JACKPOT!}
{311}{}{Coletar os ganhos!}

# AFTER JACKPOT (WTG)
{315}{}{(Essa máquina parece ter finalmente partido. Parece ter pago o jackpot foi o seu anúncio de morte.
 Você não pode ajudar mas sente pena dela.)}

# skill use
{320}{}{Essa máquina é muito antiga. É um milagre que ainda esteja funcionando.}
{321}{}{Você não pode trabalhar na máquina enquanto o velho está jogando.}
{322}{}{Essa máquina é irreparável.}
{323}{}{Não há mais nada que você possa fazer com essa máquina.}
{324}{}{Essa máquina é muito antiga. É um milagre que ainda esteja funcionando. Você mexe nela por um tempo até ouvir um terrível
 som estalando. Você decide deixá-la como está.}
{325}{}{Essa máquina é muito antiga. É um milagre que ainda esteja funcionando. Você mexe nela por um tempo, mas você não consegue consetá-la.}
{326}{}{Essa máquina é muito antiga. É um milagre que ainda esteja funcionando. Você mexe nela por um tempo e limpa algumas das
 engrenagens, mas ainda está em péssimo estado.}