{100}{}{Você vê um homem alto com uma barriga enorme e disforme.}
#You see a tall man with a huge, misshapen belly.
{101}{}{Você vê Hakeswill, um trabalhador da Morningstar Mine.}
#You see Hakeswill, a Morningstar Mine worker.
{102}{}{Você vê um homem de pele amarela, com uma cicatriz no pescoço e uma pança enorme.}
#You see a man with jaundiced skin, a scar ringing his neck, and a huge gut.
{103}{}{Ei,  o que 'cê pensa que 'tá fazendo?}
#Here now. What do you think you're doing
{104}{}{Hakeswill vai te dar uma lição, vai sim.}
#Hakeswill will teach you a lesson, 'e will.
{105}{}{Vão se fuder 'cês tudo!}
#Bloody bugger all of you. (nao achei traducao pra isso nem fudendo. só que é xingamento dos fodas. dei uma improvisada)
{106}{}{Mostre o devido respeito aos seus superiores.}
#Show proper respect for your betters.
{107}{}{Você ama sua mãe?}
#Do you love your mother?
{108}{}{Cai fora.}
#Clear off, you.
{109}{}{Num tem lugar aqui pra gente do seu tipo.}
#No room 'ere for the likes o' you.
{110}{}{A gente sabe como lidar com gente do seu tipo aqui.}
#We know how to handle your kind here.
{111}{}{Tá olhando o quê?}
#Whatcha gawkin' at?
{112}{}{Sai fora, antes que eu perca minha paciência.}
#Move it, you, afore I lose my temper.
{113}{}{Eu ainda te pego, quando 'cê menos esperar.}
#Some day, I'll catch you when you're not lookin' (ficou feia a tradução ao pé da letra, mudei um poco)
{114}{}{'Cê não pode me matar. Já tentaram antes.}
#You can't kill me. It's been tried before.
{115}{}{Eu vou dar o fora daqui. Você vai ver.}
#I'll get out of here. You'll see.
{116}{}{Aquela vadia pediu por isso.}
#That bitch had it coming to 'er. (nao sei se é isso mesmo)
{117}{}{Aquela puta não vai ser nada comparado com o que eu vou fazer com'cê.}
#That whore won't be nothing compared with what I'll do with you.
{118}{}{Eu estou guardando um prego aqui pra você, cara.}
#I'm saving a flat-headed nail for you, guv.
{119}{}{Eu sou fodão, sou invencível, sou sim. Esse lugar não vai me agüentar por muito tempo.}
#I'm bloody, fucking invincible, I am. This place won't hold me long. (Não sei se é aguentar mesmo)
{120}{}{'Cê fez o que era sábio.}
#You did what's smart.
{121}{}{A mãe do Obidiah ama ele.}
#Obidiah's mother loves 'im.
{122}{}{A Lou é a próxima.}
#I'll take care of Lou next.
{123}{}{'Cê é mais inteligente do que parece.}
#You're smarter than you look.
{124}{}{Putas desgraçadas; são todas iguais. Cadê minha navalha?}
#Damn whores; they're all the same. Where's my razor?
{125}{}{Ouvi dizer que alguém gostaria de falar com o velho Hakeswill. Alguém disposto a levar
 o Obidiah à justiça. É 'ocê?}
#I hears that someone might want to talk to old Hakeswill. Someone's volunteered to bring
 Obidiah to justice. Is that you?
{126}{}{Estou procurando um mineiro que cortou a garota da Lou. Me parece que você acabou de cofessar.}
#I'm looking for the miner that cut Lou's gal. Sounds like you just made a confession to me.
{127}{}{Eu estou trazendo a justiça pra você pessoalmente. A justiça 10mm.}
#I'm bringing justice to you in person. 10mm justice, that is.
{128}{}{Pode ser. O que você sabe do assunto?}
#It might be. What do you know about the affair?
{129}{}{Não, senhor, he, he. Eu não faria isso. T'tchau... senhor.}
#No sir, heh, heh. I wouldn't do that. G'goodbye…sir.
{130}{}{Eu cortei a vadia. Ela cometeu um erro, cometeu um erro.}
#I cut the bitch. She made a mistake, she did.
{131}{}{Um erro?}
#A mistake?
{132}{}{Eu não ligo pro que ela fez com você. Você é um cachorro louco e sou eu quem vai te dar uma lição.}
#I don't care what she did to you. You're a mad dog, and I'm just the one to put you down. (Wahahaha porra, eles deviam ter colocado a frase do stallone cobra aqui: "você é a doença, e eu sou a cura...")
{133}{}{Você cometeu o erro, seu louco desgraçado. Eu vou te levar pra prisão até que você seja julgado e enforcado.}
#You made the mistake, you crazy fuck. I'm taking you to jail until you're tried and hung.
{134}{}{Me levar pra prisão? Eu vou pacificamente. Nem faz sentido causar mais problemas. A vadia teve
 o que merecia. 'Cê não pode me matar. Eu sou invencível, mas vai deixar os outros mineiros putos. 'Cê tem
 olhos atrás da cabeça, não tem?}
#aking me to jail? I'll come peaceably. No sense in making more trouble. The bitch still got
 what she deserved. You can't kill me. I'm invincible, but you can sure piss off the other miners. Got
 eyes in the back of your head, do you?
{135}{}{Eu sei tomar conta de mim. Agora eu sou o xerife por essas bandas e vou te levar comigo.}
#I can take care of myself. Right now I'm the Sheriff in these here parts, and I'm taking you in.
{136}{}{Pensando bem, eu tenho uma idéia melhor. Por que eu não economizo tempo e dinheiro das boas pessoas
 de Redding e te mato aqui e agora?}
#On second thought, I have a better idea. Why don't I save the good people of Redding some time
 and trouble by just killing you here and now?
{137}{}{Eu não tenho certeza se quero deixar todos os outros mineiros da Morningstar com raiva. Dessa vez eu vou deixar você ir
 só com uma advertência. Mas se você fizer isso de novo…}
#I'm not sure that I want to upset all the other Morningstar miners. This time I'll let you off
 with a warning. But, if you ever do it again…
{138}{}{Oh, 'brigado, senhor. Sim, senhor. Obidiah vai ser cuidadoso, senhor. 'Brigado.}
#Oh, thank you, sir. Yes, sir. Obidiah'll be careful, sir. Thank you.
{139}{}{'Brigado, madame. Sim, madame, Obidiah vai ser cuidadoso, madame. 'Brigado.}
#Thank you, ma'am. Yes, ma'am, Obidiah'll be careful, ma'am. Thank you.
{140}{}{Prometa que vai tomar cuidado. Eu não quero ouvir nada sobre esse tipo de coisa de novo.
 Tchau.}
#You just make sure that you are careful. I don't want to hear about this sort of thing again.
 Goodbye.
{141}{}{Ela fez piada da minha mamãe. Ninguém faz piada da mamãe do Hakeswill. Ela é a única coisa boa em
 todo esse mundo desgramado.}
#She made fun o' me Mum. Nobody makes fun o' Hakeswill's Mum. She's the only good thing in this
 whole rotting world.
{142}{}{Eu não ligo por que você fez isso. Eu vou te levar pra prisão comigo. Agora.}
#I don't care why you did it. You're coming to jail with me. Right now.
{143}{}{Sua mamãe deveria ter usado métodos contraceptivos mais confiáveis.}
#Your Mum should have used more reliable birth control.
{144}{}{Ela fez piada da sua mãe? Bem, isso realmente não foi correto. Mas você perdeu o controle.}
#She made fun of your mother? Well, that's not right at all. But you overreacted.
{145}{}{Bem, eu perdi mesmo. Mas os caras e eu aqui da Morningstar não achamos que o que ela fez é certo,
 não mesmo. Mas eu prometo não fazer de novo.}
#Well, that I did. But the lads and I here at the Morningstar don't think what she did was right,
 not right at all. But I promise to not do it again.
{146}{}{Bom, eu deveria te levar preso por cortar metade do rosta daquela garota - mas contanto que você não faça
 disso um hábito... eu vou te deixar ir, desta vez.}
#Well, I should take you in for slicing off half that girl's face - but as long as you don't make
 a habit of it... I'll let you go, this time.
{147}{}{Tenho certeza que o juri levará isso em consideração. Ainda assim eu vou te levar preso.}
#I'm sure that the jury will take that into consideration. I'm still taking you in.
{148}{}{Se os outros mineiros têm as mesmas inclinações brutais que você eles vão aprender com
 o exemplo de sofrimento que eu vou te causar.}
#If the other miners have the same brutish inclinations that you do, then they can benefit from
 the painful example that I'm going to make of you.