{100}{}{Você vê um homem com os olhos esbugalhados. Apesar de seu cabelo despenteado e da barba sem-fazer, suas roupas parecem limpas e
bem cuidadas.}
#You see a wild-eyed man. Despite his unkempt hair and scruffy beard, his clothes look clean and
 well-cared for.
{101}{}{Você vê Thomas Moore.}
{102}{}{Você vê Thomas Moore. Apesar de seu cabelo despenteado e da barba sem-fazer, suas roupas parecem limpas e
bem cuidadas.}
{103}{}{Saudações, viajante! Você já ouviu a palavra hoje?}
#Hello and welcome, traveler! Have you heard the word today?
{104}{}{Umpf}
{105}{}{Argh}
{106}{}{Portzebie}#tem poTRzebie na wikipedia, mas não entendi aqui.
{107}{}{Dar o fora}
#Shamble off
{108}{}{Bem, não... não escutei.}
{109}{}{E você é...?}
{110}{}{Hã, não e não quero escutar. Tchau.}
{111}{}{A palavra, camarada... a palavra é EGOÍSMO. Misture com bastante
 arrogância e o que você tem? Vault City... com toda o sua hipócrita glória do
 mercado de escravos.}
#The word, my friend... the word is SELFISHNESS. Mix in a slew
 of arrogance, and what do you have? Vault City... in all its self-righteous,
 slave-trading glory.
{112}{}{Por que você vive aqui se odeia tanto a cidade?}
{113}{}{Amém, irmão!}
{114}{}{Acho que já ouvi o bastante. Tchau.}
{115}{}{Vá vender loucura em outro lugar, nosso estoque está lotado.}
#Go sell crazy somewhere else, pal... we're all stocked up here.
{116}{}{Sim! }
{117}{}{Chegou a HORA de ouvir as lamentações de nossos próximos fora desses muros e deixá-los entrar! Nós temos mais
 do que o suficiente para alimentar e proteger nossos irmãos... não precisamos ser ricos quando VÁRIOS são pobres.}
#It is TIME to hear the wailing of our kin outside these walls and let them in! We have more
 than enough to feed and shelter our brothers... we need not be rich when so MANY are poor.
{118}{}{Amém!}
#I hear you!
{119}{}{Finalmente, alguém com bom senso! Por que os outros devem sofrer quando a ajuda está aqui entre esses muros?}
#At last, someone who speaks sense! Why must others suffer when aid lies within these walls?
{120}{}{Já ouvi o suficiente. Tchau.}
#I've heard enough. Goodbye.
{121}{}{Camarada... quando eu te vi hoje eu vi FORÇA. Eu vi
 FÉ. Os meus olhos me enganam? Ou ele vêem uma alma disposta a ajudar minha causa?}
#Friend... as I look upon you today, I see STRENGTH. I see
 FAITH. Do my eyes deceive me? Or do they see a kindred soul that shares my cause?
{122}{}{Sim! Amém!}
#Damn right!
{123}{}{Sim! Saiba que é a HORA... hora dessa cidade, construída no pecado e na escravidão, abrir suas portas
 para todos! }
#Yes! Know that it is TIME... time for this city, built on sin and slavery, to open its gates
 to everyone! 
{124}{}{Eu tenho que ir. Foi bom conversar... er, escutar você.}
{125}{}{Então deixa eu te perguntar algo, camarada -
 o quão LONGE você iria para espalhar a palavra?}
#Then let me ask you this, my friend -
 to what LENGTHS would you go to spread the word?
{126}{}{Bem, isso depende de quanto dinheiro você tem... "camarada".}
{127}{}{Nenhum caminho é longo demais... nenhuma distância é enorme quando a causa é justa e a palavra é verdadeira.
 O que preciso for, eu o farei!}
#No lengths are too long... no distance too great, when the cause is just, and the word is true.
 Whatever needs be done, I will do it!
{128}{}{Eu não gosto do caminho pra onde esta conversa está indo. Bom dia.}
#I don't like the direction this conversation is going. Good day.
{129}{}{Mesmo que possa significar o seu banimento deste oasis?}
#Even though it may mean banishment from this oasis?
{130}{}{Isto não é um oasis, meu irmão. É uma cidade, construída no egoísmo e na avareza. Ela precisa
 ser salva de si mesma... naquela luz, o banimento é um preço muito alto? Eu não acho.}
#This is no oasis, my brother. It is a city, built on selfishness and greed. It needs to be
 saved from itself... in that light, is banishment too high a price? I think not.
{131}{}{Qualquer coisa pra ajudar meu companheiro em sua causa.}
#Anything to release my fellow man from his bonds! (tá traduzido errado. mas nao achei sentido certo pra frase.)
{132}{}{Eu não sei... o que você quer que eu faça?}
{133}{}{Hmmm. Bem, agora que você colocou dessa forma, não, acho que não. Tchau.}
#Hmmm. Well, since you put it that way, no, I guess not. Good day.
{134}{}{(Inclina-se pra você) Eu tenho uma pasta... com informação vital para nossa causa.
 Você a entregaria em New Reno pra mim? Eu faria isso, mas os Citizens estão me vigiando...}
#(Leans in.) I have a briefcase... with information vital to our cause.
 Will you deliver it to New Reno for me? I would do it, but the Citizens here are watching me...
{135}{}{Então, você admite que tem laços com New Reno, hein? Isso vai te custar... "camarada".}
#So, you admit you have ties to New Reno, eh? That's gonna cost you... "friend."
{136}{}{Claro. Dá ela pra mim.}
{137}{}{Não, valeu... é um pouco arriscado demais pra mim. Não conte comigo.}
{138}{}{Aqui está... entregue
 para um homem, John Bishop, em New Reno. Vá com cuidado, criança, e carregue a palavra com você.}
#Here it is... deliver
 this to a man, John Bishop, in New Reno. Tread carefully, my child, and carry the word with you.
{139}{}{Entregar a pasta pro John Bishop? Sem problemas.}
{140}{}{Meu nome? Eu sou Thomas Moore, pregador da palavra e da verdade. E o que traz você a mim
 hoje, camarada? VOCÊ procura a palavra?}
#My name? I am Thomas Moore, preacher of the word and the truth. And what brings you to me
 today, friend? Do YOU seek the word?
{141}{}{A palavra?}
{142}{}{Hã, não, hoje não, valeu. Tchau.}
{143}{}{Mesmo aqueles que parecem ser os mais inocentes podem enganar um mensageiro da palavra...
 como eu posso saber se você REALMENTE é um crente?}
#Even those who appear the most innocent may deceive a messenger of the word...
 how do I know that you're a TRUE believer?
{144}{}{Você vai ser um verdadeiro crente quando eu enfiar meu pé no seu cu!}
#You'll be a true believer when I shove my foot up your ass! (huaehuaehua enfiar o pé no cu foi muito boa)
{145}{}{Eu SOU um crente, irmão. Como posso provar minha devossão?}
{146}{}{Eu sei que esta cidade foi construída com base no pecado e na escravidão, e que somente a justiça
 pode corrigi-la.}
#I know that this city has built its foundations on sin and slavery, and that only the righteous
 may set it right!
{147}{}{É melhor a gente conversar depois.}
{148}{}{Descrente ignorante! Você tem ouvidos, mas não escuta! Você tem olhos,
 mas não exerga! Saia da minha frente, canalha!}
#Ignorant heathen! You have ears, but you do not listen! You have eyes,
 but you are blind! Get from my sight, filthy swine! (ao inves de descrente era pra ser pagão, mas tem o galho do genero. o mesmo vale pro filthy, deixei só canalha)
{149}{}{Canalha... hã... hm... o quê? Ninguém fala assim comigo! Espero que você não tenha família que vá sentir sua
 falta, seu defunto...}
#Filthy... uh... sw... what? Nobody talks to me like that! Hope you ain't got no family that'll miss
 you, dead man...
{150}{}{Ninguém fala assim comigo, ainda mais um pregador de merda que só quer chamar atenção. Eu acho
 que é hora de te ensinar uma lição, seu defunto.}
#Nobody talks to me like that, least of all some two-bit wanna-be soapbox preacher. I think
 it's time you learned a lesson, dead man.
{151}{}{Calma, eu já vou embora.}
{152}{}{Hmmmmmmm. Deve-se ter cautela com serpentes que dizem palavras sobre a verdade, mas
 que abrigam a falsidade em seus corações.}
#Hmmmmmm. One must beware serpents that echo the words of truth, yet
 shelter falsehood within their heart.
{153}{}{Amém, irmão! }
{154}{}{Se não há confiança entre nós, eu devo partir. Adeus.}
#If there is no trust between us, I shall leave. Goodbye.
{155}{}{Hã... claro. Talvez a gente se fale depois.}
{156}{}{O quê?! Como OUSA me chantagear... (Fecha a cara)... sou todo ouvidos.}
#What?! How DARE you blackmail me, you... you... (Frowns.)... you have my full attention. (you... you... problema do genero)
{157}{}{Podemos discutir o pagamento, então?}
#Let's discuss payment, shall we?
{158}{}{Ora... onde seria melhor para pregar do que para aqueles que mais precisam escutar?}
#Why... where better to preach than to those that need to hear the most?
{159}{}{Acho que você tem razão. Quem é você?}
{160}{}{Testemunhe, irmão! Pregue a palavra!}
#Testify, brother! Speak the word!
{161}{}{Exatamente! Essa cidade foi construída no pecado e na escravidão e precisa da força da justiça para
 se consertar!}
#Exactly! This city is built on sin and slavery and it needs the strength of the righteous to
 set it right!
{162}{}{Hã... certo. Bem, foi bom falar com você. Tchau.}
{163}{}{Aqui... esta pasta tem os números
 da minha conta. Entregue para o John Bishop em New Reno, e ele vai te dar acesso às minhas
 contas.}
#Here... this briefcase has my
 account numbers in it. Deliver it to John Bishop in New Reno, and he will give you access to my
 accounts.
{164}{}{Deixa pra lá. Eu vou te denunciar mesmo.}
#Forget it. I'm turning you in anyway
{165}{}{Esquece o pagamento, então. Eu não vou pra Reno.}
#Screw the payment, then. I'm not going to Reno.
{166}{}{Ótimo! Mas é melhor valer a pena.}
#Great! But it better be worth my while.
{167}{}{Parece que a natureza já te puniu, slaver. Talvez um dia você se redima.}
#It seems nature has already punished you, slaver. Perhaps one day you shall redeem yourself. (slaver, não sei como você vai colocar.)
{168}{}{Eh... that's not it. Walk carefully in the wastes, my simple
 friend.}#fiquei com merdo de traduzir esse 'that's not it' ao pé da letra. Tentei falar com ele no jogo mas não consegui essa frase no diálogo.
{169}{}{Af}
#Urf
{170}{}{Então, camarada, você reconsiderou?}
{171}{}{Eu reconsiderei que pode render muito dinheiro manter seu segredo. Entendeu?}
#I've considered that it might be worth a lot of money for me to keep your secret. Understand?
{172}{}{Eu vi a luz, irmão... o que devo fazer?}
#I've seen the light, brother... what shall I do?
{173}{}{Não, desculpe. Bom dia.}
{174}{}{Hein? O que você está fazendo aqui? Você não entregou...}
#Eh? What are you doing here? Didn't you deliver...
{175}{}{...a pasta pro Bishop? Bem, eu TENTEI, até que ele leu esta pequena nota que você deixou
 nela e tentou me MATAR. Engraçado, não? Espero que esteja pronto pra morrer, Moore.}
#... the case to Bishop? Well, I TRIED, except he read this little note you left in the case
 and tried to KILL me. Pretty funny, huh? Hope you're ready to die, Moore.
{176}{}{Eu entreguei, mas voltei pra te encher de buracos e depois cobrir seu corpo com uma fina camada de poeira.}
#I did, but I came back to fill you full of holes then cover your body with a thin layer of dirt.
{177}{}{Continue com o ótimo trabalho. Tchau.}
#Just keeping you on your toes. Bye. (disgreta! demorei 2 dias pra achar essa merda)
{178}{}{Ah! Saudações novamente, camarada! Como posso ajudar hoje?}
#Ah! Welcome again, fellow seeker of truth! How can I help you this day? (nao achei algo pra substituir 'seeker of truth'. esse negócio do genero quebra.)
{179}{}{O que você sabe sobre NCR?}
{180}{}{Eu tenho uma pergunta: Por que Vault City tem escravos? Eu ouvi dizer que ela era uma cidade livre.}
{181}{}{Eu quero ouvir a palavra, irmão!}
{182}{}{Esta cidade foi construída no pecado e na escravidão, e eu vim para corrigi-la!}
{183}{}{Nada por hoje, valeu.}
{184}{}{Eu sei que eles estão se esforçando para reviver a verdade e a justiça, e nós não vamos
 levantar nem uma mão para ajudar.}
#I know that they are striving to revive truth and justice, and we will not lift
 a hand to help.
{185}{}{O que podemos fazer?}
{186}{}{Isso parece mais uma traição.}
#That sounds a lot like treason.
{187}{}{É uma pena. Bem, tchau.}
#That's a shame. Oh well, goodbye
{188}{}{Nós podemos ampliar nossos portões e recebê-los aqui! Eles precisam da nossa ajuda, mesmo que
 AINDA tenhamos um olho cego!}
#We can throw our gates wide and welcome them in! They need our help, yet
 STILL we turn a blind eye!
{189}{}{Amém! A tecnologia avançada de Vault City precisa ser compartilhada, não restringida.}
#Amen! Vault City's advanced technology should be shared, not horded.
{190}{}{Hmm... eu não sei. Nós estamos muito bem assim. Nós realmente precisamos deles? Afinal, eles
 poderiam prejudicar nosso modo de vida... nos contaminar, até.}
#Hmm... I don't know. We have it pretty good here. Do we really need them? After all, they'd
 bring down our standard of living... contaminate us, even.
{191}{}{Hmmm. Bem, é algo a se pensar. Tchau.}
{192}{}{Eu não posso responder isso, para uma cidade construída na escravidão nunca será verdadeiramente livre.}
#I cannot answer that, for a city built on slavery can never be truly free.
{193}{}{É, mas eles realmente podem ficar ricos, hã?}
{194}{}{Suas palavras... elas soam como música pra mim. Talvez libertar os escravos e recebê-los calorosamente seria
 o melhor pra Vault City.}
#Your words... they strike a chord with me. Perhaps freeing the slaves, welcoming them, is best
 for Vault City.
{195}{}{Nós deveríamos libertar os escravos e abraçá-los como irmãos!}
#We should free the slaves, and embrace them as brothers!
{196}{}{Ah, não vem com merda pro meu lado. Escravidão... e Vault City... vão permanecer assim por muito tempo.}
#Aw, don't give me that brahmin shit. Slavery... and Vault City... is gonna be around a long time.
{197}{}{Palavras interessantes. Talvez a gente se fale de novo.}
{198}{}{Eu vejo que você é um mercador de carne humana. Eu não tenho NADA pra dizer pra alguém
 como você.}
#I see you are a trader in human flesh. I have NOTHING to say to one
 such as yourself.
{199}{}{Umpf}
{200}{}{Argh}
{201}{}{Portzebie}#?
{202}{}{Dar o fora}
{203}{}{Ei, eu só me fiz de slaver pra conseguir informações.}
#Hey, I only acted like a slaver to get information.
{204}{}{Bem, eu tenho algo pra falar com você: Por que Vault City tem escravos? Eu pensei que essa fosse uma
 cidade livre.}
{205}{}{Ei, mesmo os menores atos justificam um nobre fim.}
#Hey, even the lowest means justify a noble end. (rever)
{206}{}{Tudo bem, então. Tchau.}
{207}{}{É bom ver intolerância viva e bem. Bom dia.}
#It's good to see intolerance alive and well. Good day. (rever)
{208}{}{The act is the same as the deed. Begone, slaver.}#não entedi isso. acho que seria tipo um 'quem vê cara VÊ coração'
{209}{}{Mas eu aprendi com o erro dos meus caminhos!}
#But I've learned the error of my ways! #Não sei se ficou bom. Acho que o sentido mesmo é 'me arrependi dos meus erros'.
{210}{}{Agora chega. É hora de te cortar todo e ver do que você é feito...}
#That does it. Time to cut you open and see what you're made of...
{211}{}{Tudo bem, então.}
{212}{}{Eu não tenho nada a dizer para alguém com uma ídole tão tola. Vá embora.}
#I have  nothing to say to one of such foul disposition. Leave.
{213}{}{Você quer ver uma índole tola? Eu vou te MOSTRAR a índole tola...}
#You want foul disposition? I'll SHOW you foul disposition...
{214}{}{Eu enxerguei os meus erros. Eu vim pra me arrepender e escutar a palavra!}
#I've seen the error of my ways. I've come to repent and hear the word!
{215}{}{Meu coração se quebrou por causa da desumanidade com os homens!}
#My heart was torn because of the thought of man's inhumanity to man!
{216}{}{Tudo bem, então. }
{217}{}{Olá novamente, camarada! Você entregou a informação que eu pedi?}
#Hello again, fellow pilgrim! Did you deliver the information as I  asked? (pilgrim, problema do gênero)
{218}{}{Olá novamente, camarada! Como posso ajudar hoje?}
#Hello again, fellow pilgrim! How can I help you on this day?
{219}{}{Vamos pular as besteiras, "gatuno". Eu sei tudo sobre você e seus "amigos" em NCR.}
#Let's cut the crap, "Tomcat." I know everything about you and your "friends" down in NCR.
{220}{}{Como você pôde trabalhar pra NCR? Eu pensei que você fosse um homem honrado.}
#Why would you work for the NCR? I thought you were an honorable man.
{221}{}{Sim... olha, o Bishop falou que você trabalhou pra NCR. Isso é verdade?}
#Yes... look, Bishop said you worked for NCR. Is that true?
{222}{}{Sim, só queria que soubesse que eu já tomei conta disso.}
#Yes, I just wanted to let you know I'd taken care of it.
{223}{}{Me gratifica muito saber que minhas palavras brotaram eu seu coração. Talvez nossos caminhos
 se cruzem novamente.}
#It pleases me to hear that my words have taken seed in your heart. Perhaps our paths
 will cross again.
{224}{}{Talvez. Continue na fé, irmão.}
#Perhaps so. Keep the faith, brother.
{225}{}{Tchau.}
{226}{}{NCR está tentando trazer a honra e o governo pra toda a Califórnia,
 e Vault City tem o poder pra que isso aconteça! Pense no bem que poderíamos fazer com o acesso
 à tecnologia de Vault City!}
#The NCR is trying to bring honor and government to all of California,
 and Vault City has the power to make it happen! Think of the good we could do with access to Vault
 City's technology!
{227}{}{Eu não caio nessa. Eu acho que devia te denunciar - a não ser, é claro, que você queira comprar o meu silêncio.}
#I don't buy it. I think I should turn you in - unless, of course, you want to buy my silence.
{228}{}{Mas é a tecnologia de Vault City. Os outros não têm direito à ela.}
#But it's Vault City's technology. Others have no right to it.
{229}{}{Nada de bom vem da mentira e da traição, Moore. Vault City vem mentindo pra ela mesmo por
 anos... não vá por esse caminho, entendeu?}
#Nothing good comes from lies and treachery, Moore. Vault City has been lying to itself for
 years... don't go down that road, all right?
{230}{}{Hmm.Eu vou ter que pensar nisso.}
# I'll have to think about this.
{231}{}{Você está certo. Desculpe ter duvidado de você.}
#You're right. I'm sorry I doubted you.
{232}{}{TODOS os homens têm o direito aos frutos do mundo antigo. A tecnologia deve ser dividida, não
 restringida.}
#ALL men have the right to the fruits of the old world. Technology is to be shared, not
 hoarded.
{233}{}{Você NÃO ENTENDEU, não é, Moore? Talvez um chute no cu ao estilo antigo traga um pouco de
 senso pra você.}
#You just don't GET it, do you, Moore? Maybe a good old fashioned ass-kicking will knock some
 sense into you.
{234}{}{É, é, pule essa merda de "mais-sagrado-que-tu". Passa um pouco de grana pra cá, ou eu
 te denuncio.}
#Yeah, yeah, cut the "holier-than-thou" crap. Hand over some cash, or I'm
 turning you in.
{235}{}{Eu vou ter que pensar sobre isso. Tchau.}
{236}{}{Por favor, entregue a pasta em New Reno, camarada. O mais rápido possível!}
#Please deliver the case to New Reno, friend. Time is of the essence!
{237}{}{O que fazer? Ora, espalhe a palavra, será o suficiente.
 Ande com cautela e com objetivo pelas wastes, camarada. Com a palavra como sua luz, você não
 irá se desviar.}
#What to do? Why, spread the word, and that shall be enough.
 Walk carefully and with purpose in the wastes, my friend. With the word as your light, you shall not
 go astray.
{238}{}{Eu agradeço, irmão. Farei como disse.}
#Thank you, brother. I shall do as you have said.
{239}{}{Você já ouviu a palavra hoje?}
{240}{}{Ouça a palavra! A palavra irá te libertar!}
{241}{}{A escravidão condenará esta cidade!}
{242}{}{Nós devemos abrir os portões de Vault City e abraçar o mundo exterior!}
{243}{}{Por que não podemos compartilhar nossa riqueza?! }
{244}{}{Vocês não conseguem ouvir os prantos daqueles que sofrem fora desses muros?!}