{100}{}{Você vê Martin.}
# You see Martin.
{101}{}{Você vê um gago que fica piscando os olhos rapidamente.}
# You see a slack-jawed man who keeps blinking rapidly. (não achei uma tradução exata pra slack-jawed aqui)
{102}{}{Você vê Martin.}
# You see Martin.
{103}{}{Você vê um gago que fica piscando os olhos rapidamente.}
## You see a slack-jawed man who keeps blinking rapidly.
{104}{}{Obrigado por s-sa-salvar a gente. Fiquei sabendo da notícia a-a-aqui em baixo.}
# Thanks for suh-suh-saving us. I heard about it even duh-duh-down here.
{105}{}{S-so-socorro! Intruso!}
# Huh-help! Intruder!
{106}{}{Um m-mu-mutante. Socorro!}
# A muh-muh-muhtant! Help!
{107}{}{Um g-gho-ghoul! Socorro!}
#A guh-guh-ghoul! Help!
{108}{}{::Bum-ba-bum-ba::}#não vou traduzir essa música não
{109}{}{2 Segundos}
{110}{}{"Maaaay-beeee..."}
{111}{}{2 Segundos}
{112}{}{"Yoooou'll think of meee...when you are alllll alone..."}
{113}{}{2 Segundos}
{114}{}{"Maaaay-beeee...the one whooo...is waaaaah-ting for yooou..."}
{115}{}{2 Segundos}
{116}{}{"...will prove un-truuuuuue..."}
{117}{}{2 Segundos}
{118}{}{"...then what will yooou dooooo?"}
{119}{}{2 Segundos}
{120}{}{::Simula aplausos e o gritos da multidão::}
#::Pantomimes clapping, roaring of crowd::
{121}{}{2 Segundos}
{122}{}{O-ob-obrigado, o-ob-obrigado... v-vo-vocês são uma ótima platéia.}
#Th-th-thank you, th-th-thank you...yuh-yuh-you're a wonderful audience.
{123}{}{2 Segundos}
{124}{}{Um b-bis? T-tu-tudo bem!}
#An enh-encore? Ouh-okay!
{125}{}{*Snfff*}
{126}{}{O q-?! Ahhh!}
{127}{}{Aaaaaah!}
{128}{}{Opa, calma!}
#Whoa, easy there!
{129}{}{Qual é o seu problema?! Fica calmo!}
# What the hell's your problem?! Calm down!
{130}{}{V-vo-você quase me m-matou de s-su-susto.}
# Yuh-yuh-you nearly sc-scairt the life uh-outta me.
{131}{}{Aaaaah! Aaaaaaaaaaah!}
{132}{}{Desculpe, não quis te assustar.}
# Sorry, didn't mean to startle you.
{133}{}{S-s-SE você prestasse atenção no que estivesse acontecendo a sua volta, talvez não tivesse dado um ataque do coração em NÓS dois.}
#Muh-Muh-MAYBE if you paid attention to what was going on around you, maybe you wouldn't be giving us BOTH heart attacks, pal.
{134}{}{T-tu-tudo bem.}
#Th-that's okay.
{135}{}{D-di-discupa.}
Suh-suh-sorre.
{136}{}{Équi n-num vem m-muta gente'quinu Vault.}
#It's juhst nuh-not muh-many people come inta the Vault.
{137}{}{(Tudo bem. É que não vem muita gente aqui no Vault.)}
#(That's okay. It's just not many people come into the Vault.)
{138}{}{(Desculpe. É que não vem muita gente aqui no Vault.)}
#(Sorry. It's just not many people come into the Vault)
{139}{}{O que você faz aqui?}
#What is it you do here?
{140}{}{Você sabe me dizer onde fica o Computador Central do Vault?}
#Can you tell me where the Vault Central Computer is?
{141}{}{Ah, legal falar com você. Tchau.}
#Oh. Great talking to you. Goodbye.
{142}{}{Fica bem a-ali.... é o c-ca-caputadô f-f-flante.}
#Itz juhst over th-there...itz th' tuh-tuh-talking cuh-cuh-compuhter.
{143}{}{(Fica bem ali. É o computador falante.)}
#(It's just over there. It's the talking computer.)
{144}{}{O que você faz aqui?}
#What is it you do here?
{145}{}{Valeu. Tchau.}
#Thanks. Goodbye.
{146}{}{Só fico de o-oio nas cosa a-ar-amarzenada aqui. T-ter certeza que tudas as portas estão t-t-tanrcadas.}
#Juhst keep an uh-uh-eye on things in stuh-storage down here. Muh-Muh-Make shure all the doors stay luh-luh-locked.
{147}{}{(Só fico de olho nas coisas armazenadas aqui. Just keep an eye on things in storage down here. Make sure all the doors stay locked.)}
#(Just keep an eye on things in storage down here. Make sure all the doors stay locked.)
{148}{}{Você tem uma chave?}
#Do you have a key?
{149}{}{O que vocês armazenam aqui?}
#What do you store down here?
{150}{}{Te vejo por aí. Tchau.}
#See you around. Bye.
{151}{}{Hã-hã. Mas'numporta, purque a m-maroia das portas tão e-empradas mesmo.}
#Uh-uh. Dozn't mattuh, cuz muh-muh-most doors are juh-juh-jammed shu-shut anyway.
{152}{}{(Hã-hão. Mas não importa, porque a maioria das portas está emperrada mesmo.}
#(Uh-uh. Doesn't matter, because most of the doors are jammed shut anyway.)
{153}{}{O que vocês armazenam aqui?}
#What do you store down here?
{154}{}{Te vejo por aí. Tchau.}
#See you around. Bye.
{155}{}{P-peças reservas... s-suprentos... e m-minéro.}
#Spuh-spuh-spare parts...suh-suh-supplies...and uh-uh-ore...
{156}{}{(Peças reservas, suprimentos e minério.)}
#(Spare parts, supplies, and ore.)
{157}{}{Minério?}
#Ore?
{158}{}{Ham. Valeu pela informação.}
#Oh. Thanks for the information.
{159}{}{M-minéro de R-ri-Ridin... n-não m-mu-muto, agora.}
#Uh-uh-ore from Ruh-Ruh-Redding...nuh-nuh-not so muh-muh-much any-more.
{160}{}{(Minério de Redding. Não muito, agora.)}
#(Ore from Redding. Not so much anymore.)
{161}{}{Pouco minério de Redding? Por quê?}
#Not much ore from Redding? Why not?
{162}{}{Ham. Valeu pela informação.}
#Oh. Thanks for the information.
{163}{}{N-n-num sei. Mic-Clure tá muito p-p-peorcupado c'isso.}
#Duh-duh-don't know. Mic-Clure's really wuh-wuh-worried 'bout it.
{164}{}{(Não sei. McClure está muito preocupado com isso.)}
#(Don't know. McClure's really worried about it.)
{165}{}{Você sabe me dizer onde fica o Computador Central?}
#Can you tell me where the Central Computer is?
{166}{}{Talvez eu fale com ele, então. Valeu.}
#Maybe I'll talk to him then. Thanks.
{167}{}{O-olá de novo. V-você p-percisa de alguma cosa?}
#Huh-huh-hi, again. Yuh-yuh-you nuh-nuh-need summthing?
{168}{}{(Olá de novo. Você precisa de alguma coisa?)}
#(Hi, again. You need something?)
{169}{}{Geeechk}
#?
{170}{}{Você poderia parar com essa música infernal?! Está me enlouquecendo.}
#Could you stop that goddamn singing?! It's driving me crazy.
{171}{}{Você tem ótima voz pra música. Deveria continuar praticando.}
#You have a great singing voice. You should keep practicing.
{172}{}{O que você faz aqui mesmo?}
#What was it you do here again?
{173}{}{Deixa pra lá. Desculpe por interromper.}
#Nevermind. Sorry to bother you.
{174}{}{O-o-orbigrado! É muito g-gentil da sua parte.}
#Th-th-thanks! That's n-nice of you to say.
{175}{}{O que você faz aqui mesmo?}
$What was it you do here again?
{176}{}{Só achei que deveria saber. Se cuida.}
#Just thought you should know. Take care.
{177}{}{D-d-descupa. Eu v-vo'prar.}
#Suh-suh-suh-sorreee. I'll stuh-stuh-stop.
{178}{}{(Desculpa. Eu vou parar.)}
#(Sorry. I'll stop.)
{179}{}{Agora... o que você faz aqui mesmo?}
#Now...what was it you do here again?
{180}{}{Bom. Faça um favor ao mundo e fique quieto.}
#Good. Do the world a favor and keep quiet.
{181}{}{V-v-v-v-você tem que f-f-ficá'quieto! Shhhh!}
#Yuh-yuh-yuh-you guh-guh-got to be Kuh-Quiet! Shhhhhh!
{182}{}{Desculpaaaaa}
#Sorreeeee
{183}{}{O-o-o q-q-que v-você tá fazendo aqui em baixo?!}
#Wuh-wuh-wuht are yuh-you doin' down here?!
{184}{}{GEK}
{185}{}{G-g-GECK? Você p-p-pode p-procurar no c-caputador central... a c-caixa f-falante.}
#Guh-guh-GECK? You kuh-can ch-ch-check th' cuh-cuh-computer...the tuh-tuh-talkie buh-buh-box.
{186}{}{Ceeerto. Valeuuu.}
#Okeee. Fanks.
{187}{}{Z-z-z-Zzzzzzzzz}
{188}{}{F-f-f-fique l-longe dessa p-po-porta!}
#S-s-s-tay aw-w-w-ay from-m-m that d-d-oor!
{189}{}{Zzzzzzz.}