#############################################################
#  Message File: ZCBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um brahmin domesticado.}
{101}{}{A razão para o brahmin ter duas cabeças é devido
 exposição precoce de radiação para o que costumava ser chamado 
 de vaca.}
{102}{}{Você não percebe nada de incomum sobre o brahmin.}
{103}{}{brahmin não são muito para conversas.}
{104}{}{Não tem nada melhor para fazer do que ficar falando com
 uma vaca de duas cabeças?}
{105}{}{É um brahmin. Com duas cabeças.}
{201}{}{Mooo...}
{202}{}{Mooo Mooo Mooo...}
{203}{}{Mooo...}
{204}{}{Moooooo...}
{205}{}{Mooooooooo...}
{206}{}{:: GRUNT ::}