# 
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins - So let's get to Work!!!
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Version 2.0 July 29, 1998 Feargus Urquhart - modified for Fallout 2, most text has been rearranged, however some lines were still authored by the above people.
#
#  READ THIS!! READ THIS!! READ THIS!! READ THIS!!
#
#  This new file is different than the old one in that body locations are listed in a generic fashion first and are only listed for particular types of characters.  This is followed by a list of generic characters, which is then followed by the more specific taunts and party member taunts.
#
#
####################################################################################
#
#                    Generic Body Parts
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#
#                     1000 Wimpy Person
#                     1100 Normal Person
#                     1200 Tough Person
#                     1300 Berserk Person
#                     1400 Robot
#                     1500 Primitive
#                     1600 Ghoul
#                     1700 Raider (Khan)
#                     1800 Junkie
#
####################################################################################
#
#
############################################
# 1000 Wimpy Person
############################################
#
# target hit in head
#
{1000}{}{A minha cara! A minha cara!}
{1001}{}{Ai! Isso dói!}
{1002}{}{Ouch! Preciso de um pouco de gelo para a minha cabeça.}


#
# target hit in left arm
#
{1010}{}{Ow, o meu braço!}
{1011}{}{Ai!}
{1012}{}{Você quebrou o meu braço!}

#
# target hit in right arm
#
{1020}{}{Ow, o meu braço!}

{1021}{}{Wahhhh!}
{1022}{}{Meu Deus! Meu braço!}

#
# target hit in torso
#
{1030}{}{Ai! Isso realmente dói!}
{1031}{}{I think I'm gonna faint}


{1032}{}{Ouch!}
{1033}{}{Uuuuf!}

{1034}{}{Isso dói!}
{1035}{}{Me deixe em paz!}

{1036}{}{Ohhh, dor!}
#
# target hit in right leg
#
{1060}{}{Ow, minha perna!}
{1061}{}{Meu joelho!}

{1062}{}{Ai!}
#
# target hit in left leg
#
{1070}{}{Ow, minha perna!}
{1071}{}{Meu joelho!}

{1072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{1080}{}{Ai! Meus olhos!}

{1081}{}{Minha cara! Meus olhos! Arrrrgh!}
{1082}{}{Meus olhos!}

#
# target hit in groin
#
{1090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{1091}{}{Oww ... Queima!}
{1092}{}{Urp!}
{1093}{}{Ooorp! aoooww...}
{1094}{}{Eu. .. não posso ... respirar ...}
{1095}{}{A dor, a dor ...}
#
############################################
# 1100 Normal Person
############################################
#
# target hit in head
#
{1100}{}{Maldição!}
{1101}{}{Meu crânio doendo!}


{1102}{}{A minha cara! A minha cara!}
#
# target hit in left arm
#
{1110}{}{Aggghhh! Meu braço!}
{1111}{}{Meu braço!}
{1112}{}{Oh cara, isso dói!}


#
# target hit in right arm
#
{1120}{}{Aggghhh! Meu braço!}
{1121}{}{Meu braço!}

{1122}{}{}
#
# target hit in torso
#
{1130}{}{}
{1131}{}{Oof!}
{1132}{}{Ouch!}
{1133}{}{Ufa! Minha costela doí}

{1134}{}{Ugh! Isso dói!}
{1135}{}{Maldição! Eu cuspo em você!}

{1136}{}{Argh!}
{1138}{}{Oh, minhas costelas!}
{1139}{}{Ai!!!}
{1140}{}{Oof!}
#
# target hit in right leg
#
{1160}{}{Aggghhh! Minha perna!}
{1161}{}{Minha perna!}
{1162}{}{Lá se vai o meu joelho}


#
# target hit in left leg
#
{1170}{}{Aggghhh! Minha perna!}
{1171}{}{Minha perna!}
{1172}{}{Lá se vai o meu joelho}

#
# target hit in eyes
#
{1180}{}{Aggghhh! I'm blind!}
{1181}{}{Meus olhos! Meus olhos!}
{1182}{}{O meu olho! Você vai pagar por isso!}


#
# target hit in groin
#
{1190}{}{Oooooo, minha virilha!}
{1191}{}{Oooooooooo!}
{1192}{}{Eu. .. não posso ... respirar ...}
{1193}{}{Erg! Direito nas jóias!}

{1194}{}{A dor, a dor ...}
{1195}{}{Maldição, isso dói!}
#
############################################
# 1200 Tough Person
############################################
#
# target hit in head
#
{1200}{}{Ai! Seu filho da ...}

{1201}{}{Você quebrou meu nariz!}
{1202}{}{Eu vou arrancar sua cabeça!}
#
# target hit in left arm
#
{1210}{}{Ow, meu braço.}
{1211}{}{Você acabou de fazer o maior erro de sua vida.}
{1212}{}{Meu braço!}


#
# target hit in right arm
#
{1220}{}{Ow, meu braço.}
{1221}{}{Você acabou de fazer o maior erro de sua vida.}
{1222}{}{Meu braço!}


#
# target hit in torso
#
{1230}{}{Urp!}
{1231}{}{Oof!}
{1232}{}{Ouch!}
{1233}{}{}
{1234}{}{Ugh! Isso dói!}
{1235}{}{Ouch!}
{1236}{}{Argh!}
{1237}{}{Oh, eu acho que você quebrou uma costela!}
{1238}{}{Ai! Meu baço!}


{1239}{}{Oof!}
#
# target hit in right leg
#
{1260}{}{Ow, minha perna.}
{1261}{}{Eu não preciso ficar de pé para te matar!}
{1262}{}{Meu joelho!}


#
# target hit in left leg
#
{1270}{}{Ow, minha perna.}
{1271}{}{Eu não preciso ficar de pé para te matar!}
{1272}{}{Meu joelho!}


#
# target hit in eyes
#
{1280}{}{Eu não posso ver!}
{1281}{}{Esta luta está ficando pior a cada segundo.}
{1282}{}{Isso foi um verdadeiro golpe baixo!}


#
# target hit in groin
#
{1290}{}{Oooooo, minha virilha!}
{1291}{}{Eu vou sentir isso pela manhã.}
{1292}{}{}
{1293}{}{Urp!}
{1294}{}{}
{1295}{}{}
#
############################################
# 1300 Berserk Person
############################################
#
# target hit in head
#
{1300}{}{Isso vai ser uma cicatriz legal!}
{1301}{}{eu estou começando a ficar irritado.}
{1302}{}{Faça isso de novo, porco.}



#
# target hit in left arm
#
{1310}{}{Eu voltei!}
{1311}{}{}
{1312}{}{Você quebrou meu braço, mas eu vou quebrar seu pescoço!}

#
# target hit in right arm
#
{1320}{}{}
{1321}{}{Foi apenas um arranhão ...}
{1322}{}{Você quebrou meu braço, então eu vou quebrar seu pescoço!}

#
# target hit in torso
#
{1330}{}{Um pouco de sangue não é machuca ninguém.}
{1331}{}{Uff! Vou torcer seu pescoço por isso ...}


{1332}{}{Ai!}
{1333}{}{Eu gosto da dor!}
{1334}{}{Eu gosto do som de costelas quebrando!}
{1335}{}{Isso não é nada!}



{1336}{}{Arg!}
#
# target hit in right leg
#
{1360}{}{Eu adoro o som de ossos se quebrando.}

{1361}{}{}
{1362}{}{Você quebrou a minha perna, mas eu vou quebrar seu pescoço!}

#
# target hit in left leg
#
{1370}{}{Eu adoro o som de ossos se quebrando.}

{1371}{}{}
{1372}{}{Você quebrou meu braço, mas eu vou quebrar seu pescoço!}

#
# target hit in eyes
#
{1380}{}{Ei, estou cego.}
{1381}{}{Eu não posso ver. Agora a luta vai ficar de igual pra igual.}
{1382}{}{Meus olhos, cadela!}


#
# target hit in groin
#
{1390}{}{Uff, minha virilha!}
{1391}{}{Esse foi um movimento corajoso.}


{1392}{}{}
{1393}{}{}
{1394}{}{Então é assim que você quer jogar?}

{1395}{}{Ack!}
#
############################################
# 1400 Robot 
############################################
#
# target hit in CPU
#
{1400}{}{Atenção, registrado mau funcionamento CPU!}
{1401}{}{Aviso! Danos na CPU! Processamento prejudicado!}
{1402}{}{Aviso! CPU danificada! Desviando sistema crítico!}



#
# target hit in left manipulator
#
{1410}{}{Danos registrados no manipulador.}
{1411}{}{Unidade atingida no manipulador esquerdo. Avaliando danos.}
{1412}{}{Impacto registrado no manipulador. Tentando compensação.}



#
# target hit in right manipulator
#
{1420}{}{Danos registrados no manipulador.}
{1421}{}{Unidade atingida no manipulador direito. Avaliando danos.}
{1422}{}{Impacto registrado no manipulador. Tentando compensação.}



#
# target hit in frame
#
{1430}{}{Impacto na carcaça. Correção de danos.}
{1431}{}{Impacto na carcaça. Correção internas inicializadas.}
{1432}{}{Estrutura principal sob ataque.}



{1433}{}{Armadura penetrada.}
{1434}{}{Estrutura principal sob ataque. Corrigindo.}
{1435}{}{Unidade sob ataque.}
{1436}{}{Tentando manobras de ataque.}



{1437}{}{Brzzt!}
{1438}{}{Danos menores.}
{1439}{}{Brzzt!}
#
# target hit in right motivator
#
{1460}{}{Danos registrados em unidade matriz.}
{1462}{}{Unidade atingida na matriz direita. Avaliando danos.}
{1463}{}{Impacto registrado na unidade matriz. Tentando compensação.}



#
# target hit in left motivator
#
{1470}{}{Danos registrados em unidade matriz.}
{1471}{}{Unidade atingida na matriz esquerda. Avaliando danos.}
{1472}{}{Impacto registrado na unidade matriz. Tentando compensação.}



#
# target hit in sensors
#
{1480}{}{Sensor atingido! Sensor atingido!}
{1481}{}{Sensores prejudicados! Sensores prejudicados!}
{1482}{}{Mau funcionamento do sistema de sensor, tentando desviar.}



#
# target hit in regulator
#
{1490}{}{Mau funcionamento registrado no regulador}
{1491}{}{Regulador danificado! Regulador danificado!}
{1492}{}{Regulador danificado! Desviando para o sistema crítico!}



#
#
############################################
# 1500 Primitive
############################################
#
# target hit in head
#
{1500}{}{Minha cabeça está cheia de maus espíritos.} 
{1501}{}{Posso escutar meus antepassados me chamando. 


{1502}{}{Isso vai me deixar uma bela cicatriz.}
{1503}{}{Ouuuuch!}
{1504}{}{Minha cabeça esta em chamas!}
{1505}{}{Queima, queima!}


{1506}{}{Que dor.}
{1507}{}{Sua magia é poderosa.}
{1508}{}{Você não pode roubar minha alma dessa maneira.} 


{1509}{}{Sua magia não pode me matar.}
#
# target hit in left arm
#
{1510}{}{Vou usar o meu braço direito para matá-lo.} 
{1511}{}{Eu só preciso de uma mão para te matar.} 
{1512}{}{Sua dor vai ser ainda maior!} 
{1513}{}{Eu não preciso que muitos dedos.} 
{1514}{}{De qualquer maneira esse braço era um pouco grande demais.} 
{1515}{}{Vou arrancar seus dois braços por isso.} 
{1516}{}{Por isso, vou te matar lentamente.} 







{1517}{}{Ouch!}
{1518}{}{Quanto sangue.}
{1519}{}{Algo para mostrar os jovens-queridos.}
 #


# target hit in right arm
#
{1520}{}{Eu vou matá-lo com minha mão esquerda.} 
{1521}{}{Sua mira é tão ruim assim?}
{1522}{}{Eu só preciso de uma mão para te matar.} 
{1523}{}{Eu não preciso que muitos dedos.} 
{1524}{}{Por isso, vou te matar lentamente.}
{1525}{}{Vou arrancar seus dois braços por isso.} 
{1526}{}{Você arrancou meu braço, eu vou levar a sua cabeça!}
{1527}{}{Esta tentando me matar?}
{1528}{}{Vou cortar suas entranhas por isso.} 
{1529}{}{Vou fazer com que morra lentamente.}










#
# target hit in torso
#
{1530}{}{Awwwwwg!}
{1531}{}{Minhas entranhas queimar!}
{1532}{}{Minhas entranhas estão pegando fogo!}
{1533}{}{Meus espíritos de vida se separam de mim.} 
{1534}{}{Fui rasgado!}
{1535}{}{Posso viver o suficiente para acabar com você} 

{1536}{}{Antepassados??, estou chegando.} 
{1537}{}{Eu nunca vou ver a aldeia novamente.} 
{1538}{}{Pelo menos eu vou morrer com honra.} 
{1539}{}{Meus irmãos vão me vingar.} 
{1540}{}{Eu não tenho mais fôlego.} 
{1541}{}{Você tomou minha alma.} 
{1542}{}{Você me mataria?}
{1543}{}{Estou eviscerado como um brahmin.} 
{1544}{}{Eu não me sinto bem.} 
{1545}{}{Eu não posso sentir minhas pernas.} 
{1546}{}{De repente, eu me sinto quente e sonolento.}

{1547}{}{Errrggggg!}
{1548}{}{Gack! cough, cough.}
{1549}{}{Devo continuar, devo matar o inimigo...} 
{1550}{}{A escuridão acena para mim.} 
{1551}{}{A hora da minha morte se aproxima.} 
{1552}{}{O Shaman estava certo, eu não voltar.} 
{1553}{}{O farasteiro me matou.}
{1554}{}{Eu estou morto.}
{1555}{}{Minhas entranhas estão soltas da minha espinha!} 
{1556}{}{Não deixe com vergonha da minha morte.} 
{1557}{}{Maldição esses intestinos fracos.} 
{1558}{}{Ei, olhe aqui, eu posso ver o meu almoço.} 
{1559}{}{Para onde foi todo o ar?}

#
# target hit in right leg
#
{1560}{}{Vou rastejar para matá-lo.} 
{1561}{}{Devo me manter em pé, devo ....} 
{1562}{}{Não me faça correr para pegar você!} 
{1563}{}{Você me aleijou, covarde!}
{1564}{}{Awwwwgg!}
{1565}{}{Osso? Tão branco ....} 
{1566}{}{Por que eu não posso andar?} 
{1567}{}{Arrrrrrgh.} 
{1568}{}{Unnhhh.} 
{1569}{}{Sinto fogo em minhas pernas.}

#
# target hit in left leg
#
{1570}{}{Vou rastejar para matá-lo.}
{1571}{}{Devo me manter em pé, devo...} 
{1572}{}{Não me faça correr para pegar você!} 
{1573}{}{Você me aleijou, covarde!} 


{1574}{}{Awwwwgg!}
{1575}{}{Osso? Tão branco...}
{1576}{}{Não posso andar. Oh que dor...} 
{1577}{}{Vou queimar seu pé por isso.} 

{1578}{}{Ooooo-ouuuuch!}
{1579}{}{Sinto fogo em minha perna.}
#
# target hit in eyes
#
{1580}{}{A escuridão está aqui.}
{1581}{}{Onde você está?}


{1582}{}{Ajuda, me ajuda.}
{1583}{}{Eu ainda posso ouvi-lo.}
{1584}{}{Querendo me cegar? Covarde!} 
{1585}{}{Minha visão foi roubada.}
{1586}{}{Você pode tirar meus olhos, mas não a minha coragem!} 
{1587}{}{Venha aqui para que eu possa matá-lo!} 
{1588}{}{A escuridão, a escuridão, Aaaiiiieee!} 
{1589}{}{Onde está o meu olho, onde está?!}

#
# target hit in groin
#
{1590}{}{Agora eu tenho muitos filhos.} 

{1591}{}{Você luta sem honra.}
{1592}{}{Estou casado, não uso de qualquer maneira.} 
{1593}{}{Espíritos santos, o mundo explodiu.} 


{1594}{}{Gasp ... não consigo respirar ....}
{1595}{}{Ouch! (Em voz alta e estridente)} 

{1596}{}{Unnhhh. Eu preciso sentar um pouco.} 
{1597}{}{Seu filho da puta - eu mato você lentamente por isso.} 

{1598}{}{Você não sabe nada de honra.}
{1599}{}{Eu farei você em pedaços como se fosse um animal pronto para o abáte.}
#
#
############################################
# 1600 Ghoul
############################################ 
#
# target hit in head
#
{1600}{}{Oh, meu rosto bonito}
{1601}{}{O meu cérebro dói.}
{1602}{}{Agora eu Pareço o Van Gogh.}
{1603}{}{Maldição, lá se vai o meu nariz.}
{1604}{}{Ei, esse é o meu último dente.} 
{1605}{}{Ai, Meu couro capeludo!} 
{1606}{}{Gostaria de ficar na frente de uma garrafa ...} 
{1607}{}{Me deixe compartilhar minhas idéias.}
{1608}{}{Ahhh, esse era meu olho bom.} 
{1609}{}{Meu olho bom sai lágrimas.}

#
# target hit in left arm
#
{1610}{}{Você me desarmou!}

{1611}{}{Ooohh, que dor, que dor.}
{1612}{}{Eu ainda tenho alguns dedos da mão esquerda.} 
{1613}{}{Eu só precisa de um dedo para * você *, covarde.} 
{1614}{}{Então acho que vou te dar uma mão.} 
{1615}{}{Isso é pior do que uma unha encravada.} 
{1616}{}{Isso acabou com meu swing.} 
{1617}{}{Vou esfaqueá-lo com meu coto!}
{1618}{}{Ei, para onde foram meus?} 
{1619}{}{Isso vai ser ótimo. Me pareco com Capitão Gancho.} 

#
# target hit in right arm
#
{1620}{}{Deveria ter usado a direita.} 
{1621}{}{Você quebrou o meu braço!}
{1622}{}{Você vai se arrepender disso!}
{1623}{}{Aarrrggg!}
{1624}{}{Acabou o Wimbledon.}
{1625}{}{Maldiç... ah, deixa pra lá.}
{1626}{}{Você me desarmou!}
{1627}{}{Eu só preciso de um dedo para * você *, covarde.} 
{1628}{}{Te chutarei até a morte.} 
{1629}{}{Lá se vai minha grande luva de Michael Jackson!} 
#
# target hit in torso
#
{1630}{}{Isso é * meu * fígado, me devolva!} 
{1631}{}{Só mais um pouquinho para a direita, ahhh, muito melhor.} 
{1632}{}{Gerrk!}
{1633}{}{O que é esse cheiro de mofo? Oh, minha entranhas.} 
{1634}{}{Agora que você já me espedaçou, eu estou tão esbelto! Obrigado!} 
{1635}{}{./~ [Canta] Eu te dei coração....../~}
{1636}{}{Isso fez cócegas nas minhas costelas.}
{1637}{}{De qualquer maneira quem precisa de um apêndice.}
{1638}{}{Acho que você passou um pouco do ponto, doc.}
{1639}{}{Arrggghh, minha coluna!}
{1640}{}{Minhas pernas, eu não consigo sentir minhas pernas.}
{1641}{}{Só uma ferida nas tripas, Sarge.}
{1642}{}{Os pulmões são para maricas.}
{1643}{}{Ei, eu tenho costelas!}
#
# target hit in right leg
#
{1660}{}{Ow, minha perna!}
{1661}{}{Você vai pagar por isso!}
{1662}{}{Argh! Você quebra minha perna, eu vou quebrar seu pescoço!} 
{1663}{}{Maldição, lá se vai o meu Tango.}
{1664}{}{Maldição, lá se vão meus pés.}
{1665}{}{Eu acho que agora preciso de outra perna.}
{1666}{}{Você acabou com meus sapatos de camurça azul!} 
{1667}{}{Você acabou com meus dedos!}
{1668}{}{E eu foi só um de raspão.} 
{1669}{}{Eu vou arrancar seus joelhos fora com meus dentes!} 
#
# target hit in left leg
#
{1670}{}{Minha perna!}
{1671}{}{Você acabou com minhas coisas!}
{1672}{}{Ouch! Hey! Isso é abaixo da cintura!} 
{1673}{}{Sabe levantar vergões como ninguém.} 
{1674}{}{Me castigue mamãe, eu fui mau.} 
{1675}{}{Isso deixará uma boa cicátriz.}
{1676}{}{Todo esse sangue é meu?}
{1677}{}{Xerife Dillon, Xerifel Dillon!} 
{1678}{}{Isso vai me dar bolhas.}
{1679}{}{Kai, yai, yippee, ai, ay!}
#
# target hit in eyes
#
{1680}{}{Maldição sanque em meus olhos!}
{1681}{}{O meu olho! Você vai pagar por isso!} 
{1682}{}{Idióta!}
{1683}{}{Quem apagou as luzes?} 
{1684}{}{Hah, la se foi meu olho de vidro!} 
{1685}{}{Faz um barulho como se estoura uma uva madura, não é assim?}
{1686}{}{Ei você esta com meu olho, uh, você pode me devolver, por favor?} 
{1687}{}{Eu ainda posso rastreá-lo apenas pelo som!}
{1688}{}{Aiyeee! Aiyeee! meus olhos!}
{1689}{}{Me cegou, porque você está com medo, não é?!} 
#
# target hit in groin
#
{1690}{}{Você não é um cavalheiro.}
{1691}{}{Yooooouuuuch!} 
{1692}{}{Unnhhhhh!}
{1693}{}{Talvez se eu simplesmente não se mover por um tempo ....} 
{1694}{}{Essa é a minha carne mortadela!}
{1695}{}{Lá se vai minha vida social.} 
{1696}{}{Eu acho que preciso me sentar um pouco.}
{1697}{}{Pô, Olha! um coquetel de Ostras Prairie.}
{1698}{}{Oohh, isso dói.}
{1699}{}{Será que isso ...? Oh, sim, isso dói.}
{1700}{}{Ei, olha! Ostras Prairie.}
{1701}{}{Alguem quer nozes picadas?}
{1702}{}{Não poderei mais escrever meu nome na neve.}
#
############################################
# 1703 Raider (Khan)
############################################
#
# target hit in head
#
{1703}{}{Na cara! Na cara não!}

{1704}{}{Minha cabeça ... ... ficando tonto ...}
{1705}{}{Ugnnn!}
{1706}{}{Na cara! Na cara não!}

#
# target hit in left arm
#
{1710}{}{Eu posso bater em você com um braço!}
{1711}{}{Médico! Fudeu com meu braço!}
{1712}{}{Ack! Ainda bem que eu sou ambidestro...}



#
# target hit in right arm
#
{1720}{}{Você quebrou o meu braço! Agora a luta é justa!}
{1721}{}{Médico! Fudeu com meu braço!}
{1722}{}{Você precisará remover mais do que o meu braço para se salvar seu burro!}
#
# target hit in torso
#
{1730}{}{Ahhg! Grande tiro!}
{1731}{}{Hnrgggg! Não posso ... respirar ...}
{1732}{}{Minhas costelas estão feridas. Agora vou retirar as suas! É justo!}
{1733}{}{Você... vai ... pagar ... por... isso!}
{1734}{}{* Ooooof * Deus, como odeio isso ...}
{1735}{}{Nggg! No complexo solar!}
#
# target hit in right leg
#
{1760}{}{Maldição! Minha perna!}
{1761}{}{Eu não preciso de duas pernas para chutar sua bunda.}
{1762}{}{Vou precisar de um stimpack para a minha perna ...}
{1763}{}{Urggg ... perna se ... ferrou ...}
#
# target hit in left leg
#
{1770}{}{Maldição! Minha perna!}

{1771}{}{* Ergg * Vai ter troco ...}
{1772}{}{Vou precisar de um stimpack para a minha perna ...}

{1773}{}{Urggg ... perna se ... ferrou ...}
#
# target hit in eyes
#
{1780}{}{Merda! Nos olhos não!}
{1781}{}{Tentando inviabilizar minha percepção de profundidade, não é?}
{1782}{}{Não posso ... ver ... sangue ... dentro ... dos olhos ...}
{1783}{}{Não preciso te ver, posso sentir seu cheiro!}
#
# target hit in groin
#
{1790}{}{O que você acha que é isso? Alguns filme barato de ação?}
{1791}{}{Minhas bolas! Venha aqui e deixe-me fazer isso com você!}
{1792}{}{Bem, lá se vão as minhas bolas de bronze.}
{1793}{}{Me desculpe por vomitar tudo sobre mim mesmo.}
{1794}{}{Grande. Eu começo a lutar com alguém que tem fixação por bolas.}
{1795}{}{Deixe-me descançar um pouco, então depois vou te matar.}
{1796}{}{Nuts! Oh bem, sem filhos para mim.}
#
############################################
# 1800 Junkie
############################################
#
# target hit in head
#
{1800}{}{Whoa. Algo me atingiu no rosto.}
{1801}{}{O que acabou de me bater na cabeça?}
{1802}{}{Ngggg}
{1803}{}{Ainda bem que estou chapádo de Jet, ou teria sido muito dolorozo.}
{1804}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
#
# target hit in left arm
#
{1810}{}{Hey! Alguém acabou de bater no meu braço!}
{1811}{}{Olha, meu braço é apenas para desenhar. Pare de atacá-lo.}
{1812}{}{Nggggg}
{1813}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
#
# target hit in right arm
#
{1820}{}{Hey! Alguém acabou de bater no meu braço!}
{1821}{}{Olha, meu braço é apenas para desenhar. Pare de atacá-lo.}
{1822}{}{Nggggg}
{1823}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}

#
# target hit in torso
#
{1830}{}{Meu baço!}
{1831}{}{Ai! Owwww, meu maldito peito! Ai!}
{1832}{}{Hey! Porque você me bateu no peito?, idiota!}
{1833}{}{Pare de me bater no peito!}
{1834}{}{Whoa. Meu peito. Isso machucou legal.}




{1835}{}{Nrgggg}
{1836}{}{*hfff*}
{1837}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}

#
# target hit in right leg
#
{1860}{}{Hey! Alguém acabou de bater na minha perna!}
{1861}{}{Hey! Eu ando com a perna!}
{1862}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
#
# target hit in left leg
#
{1870}{}{Hey! Alguém acabou de bater na minha perna!}
{1871}{}{Hey! Eu ando com a perna!}
{1872}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
#
# target hit in eyes
#
{1880}{}{Isso é como sentir uma agulha no olho ...}
{1881}{}{Hey! Eu vejo com aquele olho!}
{1882}{}{MEUS Olhos! MEUS Olhos! Meus olhos doem!}
#
# target hit in groin
#
{1890}{}{Estou tão chapádo de Jet, que mal senti isso. Ah ... não, espere.}
{1891}{}{*Hurhkkkk*}
{1892}{}{Chuta minhas partes, anda!}
{1893}{}{Nghhhhh!}
{1894}{}{Na virilha não! Na virilha não!}
{1895}{}{Os meus órgãos genitais! Meus pobres órgãos genitais!}
{1896}{}{Me desculpe por vomitar em todo o lugar.}
{1897}{}{Isso ... dói ... um ... MUITO.}
{1898}{}{Espero que a minhas partes vão para o céu genital.}
#
####################################################################################
#
#                    Generic People
#
####################################################################################
#                     

#                     Notes
#                     

#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed.
#
#                     2000 Wimpy Person
#                     2100 Normal Person
#                     2200 Tough Person
#                     2300 Berserk Person
#                     2400 Guard (Normal)
#                     2500 Guard (Tough)
#                     2600 Primitive
#                     2700 Soldier
#                     2800 Leader
#                     2900 Raider (Khan)
#                     3000 Robot
#                     3100 Ghoul
#                     3200 Junkie
#
####################################################################################
#
#
############################################
# 2000 Wimpy Person
############################################
#
#  running away
#
{2000}{}{Misericórdia!}
{2001}{}{Alguém me ajude!}
{2002}{}{Por favor, pare!}


{2003}{}{Ajuda!}
{2004}{}{Aaaaahhhh!}
{2005}{}{Misericórdia!}
#
# moving in to attack
#
{2020}{}{Hmm, uh, pare!}
{2021}{}{Eu não gosto de seu tipo ...}
{2022}{}{Eu realmente esperava que não chegaria a isso...}
{2023}{}{Eu acho que eu tenho que me defender}
{2024}{}{Eu acho que eu tenho que me defender}
{2025}{}{Eu realmente esperava que não chegaria a isso...}

#
# attacking
#
{2040}{}{Tome isso!}
{2041}{}{Você não deveria ter começado isso!}
{2042}{}{Você pediu por isso!}
{2043}{}{Você gosta disso?}



{2044}{}{}
{2045}{}{Otário!}
{2046}{}{Eu não quero fazer isso!}

{2047}{}{}
{2048}{}{Eu não queria lutar, mas ...}

{2049}{}{Canalha!}
#
# target being missed
#
{2060}{}{}
{2061}{}{Não vou desistir!}
{2062}{}{Uau, poderia ter me ferido!}
{2063}{}{Ufa! Eu ainda estou vivo!}
{2064}{}{Hey! Poderia ter me ferido!}
{2065}{}{Ufa! Eu ainda estou vivo!}

#
############################################
# 2100 Normal Person
############################################
#
#  running away
#
{2100}{}{Ataque mais alguem, por favor!}
{2101}{}{Tenha misericórdia!}
{2102}{}{Alguém me ajude!}
{2103}{}{Por favor, pare!}
{2104}{}{}
{2105}{}{Eu não vou morrer por isso!}

#
# moving in to attack
#
{2120}{}{Espere até que eu te ...}
{2121}{}{}
{2122}{}{Ei, você!}
{2123}{}{Você não é bem vindo aqui}
{2124}{}{Ninguém vai destuir este lugar ...}
{2125}{}{Quem você pensa que é?}

#
# attacking
#
{2140}{}{Você não deveria ter feito isso!}
{2141}{}{Preocupamos uns com os outros.}
{2142}{}{Isto é o que fazemos com vermes!}
{2143}{}{Você é uma aberração mutante!}
{2144}{}{Idióta!}
{2145}{}{Vou te usar como alimentar para os cães!}
{2146}{}{Aprenda com isso!}
{2147}{}{Bem. Você pediu por isso.}
{2148}{}{Animal!}
{2149}{}{Você merece o que está passando!}

#
# target being missed
#
{2160}{}{Não sou tão ruim, sou?}
{2161}{}{Eu vi mais Brahmin mais esperto que você}

{2162}{}{Ufa!}
{2163}{}{Eu não  sou uma presa fácil.}
{2164}{}{Graças a Deus!}
{2165}{}{Perdeu!}

#
############################################
# 2200 Tough Person
############################################
#
#  running away
#
{2200}{}{Não vale a pena!}
{2201}{}{Tenho coisas melhores para fazer.}
{2202}{}{Alguém me ajude!}
{2203}{}{Da próxima vez vou fazer melhor.}
{2204}{}{Vai ter o que merece!}
{2205}{}{Eu não vou morrer por isso!}

#
# moving in to attack
#
{2220}{}{É tarde demais para correr.}
{2221}{}{Quem te deixou entrar aqui?}
{2222}{}{Ei, você!}
{2223}{}{Nós não gostamos de seu tipo por aqui!}
{2224}{}{Ninguém vai destuir este lugar ...}
{2225}{}{Quem você pensa que é?}

#
# attacking
#
{2240}{}{Tome isso!}
{2241}{}{Você gosta disso?}
{2242}{}{Isto é o que fazemos com vermes!}
{2243}{}{Isto é para você!}
{2244}{}{Good-bye!}
{2245}{}{Vamos em frente!}
{2246}{}{Escória problemática!}
{2247}{}{Eu vou bater em você como um filho da puta.}
{2248}{}{Animal!}
{2249}{}{Você vai se arrepender de colocar o pé aqui!}

#
# target being missed
#
{2260}{}{Você não é tão bom quanto pensa.}

{2261}{}{Patético.}
{2262}{}{Você é apenas um bandido comum.}
{2263}{}{Não é nada especial.}
{2264}{}{Eu não vou ser sua vítima.}
{2265}{}{Esse foi seu último erro.}

#
############################################
# 2300 Berserk Person
############################################
#
#  running away
#
{2300}{}{Estou fugindo.}
{2301}{}{Eu voltarei!}
{2302}{}{Mais tarde, seu puto!}
{2303}{}{Isso foi divertido, mas eu vou embora!}
{2304}{}{Pagará por isso... depois!}
{2305}{}{Vamos fazer isso novamente em breve!}

#
# moving in to attack
#
{2320}{}{Vou pregar suas orelhas para trás!}
{2321}{}{Carne fresca!}
{2322}{}{Você só fez alegrar meu dia!}
{2323}{}{Você vai ser minha puta!}
{2324}{}{Vou pregar suas orelhas para trás!}
{2325}{}{Eu vou me por em seu lugar!}

#
# attacking
#
{2340}{}{Eu vou pegar você!}
{2341}{}{Hora de jogar!}
{2342}{}{Por favor, não se humilhe. A morte deve ser digna.}
{2343}{}{Eu espero que você não morrer muito rapidamente.}
{2344}{}{Tem alguma últimas palavras?}
{2345}{}{Tome isso!}
{2346}{}{Morra! Morra! Morra! Morra! Morra!}
{2347}{}{Morra!}
{2348}{}{Vamos abri-lo um pouco ...}
{2349}{}{Vai virar ração de cachorro, amigo.}
#
# target being missed
#
{2360}{}{Não me toque.}
{2361}{}{Você me fez chorar}
{2362}{}{Vamos lá seu merda, lute comigo!}
{2363}{}{Isso é o melhor que pode fazer?}
{2364}{}{Você não presta!}
{2365}{}{Isso vai ser mais fácil do que eu pensava}

#
############################################
# 2400 Guard (Normal)
############################################
#
#  running away
#
{2400}{}{Vou sair daqui!}
{2401}{}{Talvez essa não seja uma boa idéia.}
{2402}{}{Posso atacar mais alguém?}
{2403}{}{Caramba!}
{2404}{}{Eu não vou morrer por isso!}
{2405}{}{Isso é demais para mim!}

#
# moving in to attack
#
{2420}{}{Ei, você!}
{2421}{}{Eu vou te ensinar boas maneiras!}
{2422}{}{Nós não gostamos de seu tipo por aqui!}
{2423}{}{Você precisa aprender um pouco de respeito!}
{2424}{}{Hora de ganhar meu salário ...}
{2425}{}{Espere até que eu te ...}
{2426}{}{Por que você vai fazer isso?}
{2427}{}{Há sempre idiotas como você por perto para atrapalhar um pouco.}


#
# attacking
#
{2440}{}{Tome isso!}
{2441}{}{É bom não é?}
{2442}{}{Deveria ter me deixado sozinho.}
{2443}{}{Você gosta disso?}
{2444}{}{Onde está sua mãe agora?}
{2445}{}{Toma isso!}
{2446}{}{Vamos ver o quão duro você é ...}
{2447}{}{Bastardo!}
{2448}{}{Folgado!}
{2449}{}{Vou te matar para o bem de todos!}

#
# target being missed
#
{2460}{}{Sua mãe te ensionou isso?}
{2461}{}{Simplismente chupa!}
{2462}{}{Não é suficientemente bom.}
{2463}{}{Esse foi seu último erro.}
{2464}{}{Amador.}
{2465}{}{Você aprende a lutar em bares?}

#
############################################
# 2500 Guard (Tough)
############################################
#
#  running away
#
{2500}{}{Tenho que sair daqui!}

{2501}{}{Eu voltarei...}
{2502}{}{Não vai me matar hoje!}
{2503}{}{Mais tarde, seu puto!}
{2504}{}{Não sera a última vez que nos vemos!}
{2505}{}{Vai pagar por isso... mas tarde!}

#
# moving in to attack
#
{2520}{}{Você é história!}

{2521}{}{Toma isso!}
{2522}{}{Eu vou dançar no seu túmulo!}
{2523}{}{Todo mundo! É um alvo em potêncial!}
{2524}{}{Prepare, seu vagabundo!}
{2525}{}{Vou desfrutar disto ...}
#
# attacking
#
{2540}{}{Toma isso!!!}
{2541}{}{Não adianta ficar gritando por Misericórdia ...}
{2542}{}{Esta é a melhor parte ...}
{2543}{}{Você quer mais disso! Huh!}
{2544}{}{Vai vira comida de cachorro}
{2545}{}{Não deve começar o que você não pode terminar}
{2546}{}{Espero que você não morra rápido demais}
{2547}{}{Apenas um de nós vai sair vivo dessa.}
{2548}{}{Morra!}
{2549}{}{Eu como viados como você no café da manhã.}
{2550}{}{Vou usar você como alimento para o meu iguana}
{2551}{}{A última coisa que você verá é o rosto sorridente.}
{2552}{}{Este é meu trabalho favorito.}

#
# target being missed
#
{2560}{}{Você é uma piada.}
{2561}{}{Isso é o melhor que pode fazer?}
{2562}{}{Você está fazendo isso fácil.}
{2563}{}{Simplismente patético...}
{2564}{}{Muito lento!}
{2565}{}{Perdedor!}
#
############################################
# 2600 Primitive
############################################
#
#  running away
#
{2600}{}{Executado Maligno!}
{2601}{}{Os espíritos me dizem para reagir!}
{2602}{}{Nosso inimigo tem usado magia poderosa - Corra! Alguém pode chamar um Shaman!}
{2603}{}{O espírito maligno é mais poderoso agora. A morte caminha sobre a terra!}
{2604}{}{O espírito maligno está aqui!}
{2605}{}{O espírito maligno quer nos castirgar. Corre!}
{2606}{}{Aiiieeeee!!}
#
# moving in to attack
#
{2620}{}{Meus antepassados guiam meu braço!}
{2621}{}{Sua força será minha.}
{2622}{}{Grande será a minha glória.}
{2623}{}{Vou desonrar sua tribo.}
{2624}{}{Ayah! Nabataluk!}
{2625}{}{Que os espíritos me acompanhe!}
{2626}{}{Venha faça nossas espadas dançarem.}
{2627}{}{Pode começar!}
{2628}{}{U-Suthoooo!}
{2629}{}{Os espíritos me acompanham!}
#
# attacking
#
{2640}{}{Seus antepassados abandonaram você.}
{2641}{}{Sua derrota vai me trazer grande honra. Minha magia não conhece derrota!}
{2642}{}{Renda-se agora e não vamos comer seu coração.}
{2643}{}{Você luta bem. Vou acabar com sua coragem. Os espíritos vão gostar da minha vitória.}
{2644}{}{Vou tomar banho em seu sangue!}
{2645}{}{Eu não tenho medo de você!}
{2646}{}{Trago à paz perdida.}
{2647}{}{Glória na batalha compra a vida eterna! Obrigado estrangeiro.}
{2648}{}{The mists beckon to you.}
{2649}{}{Our ancestors thirst for your soul.}
{2650}{}{My blade grows thirsty!}
{2651}{}{Let us drink from the cup of battle!}
#
# target being missed
#
{2660}{}{ Your eyes are clouded with hatred.}
{2661}{}{ Your spirits have abandoned you.}
{2662}{}{ Our magic is working!}
{2663}{}{ My magic makes me invincible!}
{2664}{}{ Your life-force is weakening!}
{2665}{}{ Fear is the mind-killer }
{2666}{}{ My battle-song is working!}
{2667}{}{ Our children know more of battle!}
{2668}{}{ You have known peace too long.}
{2669}{}{ Are all of your tribe so weak?}
#
############################################
# 2700 Soldier
############################################
#
#  running away
#
{2700}{}{Reinforcements!}
{2701}{}{They can court martial me..}


{2702}{}{Medic!}
{2703}{}{Retreat! Retreat!}
{2704}{}{Fall back! Fall back!}
{2705}{}{You may have won the battle...}



#
# moving in to attack
#
{2720}{}{Vamos em frente!}
{2721}{}{Hoo-Yah!}
{2722}{}{Eu vou te ensinar boas maneiras!}
{2723}{}{Você é história!}




{2724}{}{Attack!}
{2725}{}{Let's bury this Perdedor!}
{2726}{}{Lock and Load!}
{2727}{}{We'll let god sort out what's left of ya.}



#
# attacking
#
{2740}{}{Tome isso!}
{2741}{}{Now I have you!}
{2742}{}{Now you Morra!}
{2743}{}{Você gosta disso?}
{2744}{}{This ain't just a job to us}
{2745}{}{Não deve começar o que você não pode terminar.}
{2746}{}{You better pray to the gods!}
{2747}{}{You ain't even gonna make it to 6am!}







{2748}{}{Feel good?}
{2749}{}{See you in Hell!}
#
# target being missed
#
{2760}{}{Try training some.}
{2761}{}{Isso é o melhor que pode fazer?}
{2762}{}{C'mon Perdedor. Gimme a fight!}


{2763}{}{Try aiming next time.}
{2764}{}{Civilian...}
{2765}{}{Leave it to the professionals next time.}

#
############################################
# 2800 Leader
############################################
#
#  running away
#
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
#
# moving in to attack
#
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
#
# attacking
#
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
#
# target being missed
#
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
#
############################################
# 2900 Raider
############################################
#
#  running away
#
{2900}{}{Flee! Flee!}

{2901}{}{Retreat!}
{2902}{}{Regroup!}
{2903}{}{Fall back!}
{2904}{}{Withdraw!}
{2905}{}{Aaaaghhh!}
#
# moving in to attack
#
{2920}{}{Kill this fool!}

{2921}{}{Toma isso!}
{2922}{}{Plunder!}
{2923}{}{This one's mine!}

{2924}{}{Ahhhhhhh!}
{2925}{}{Attack!}
#
# attacking
#
{2940}{}{Enjoy the last few seconds of your life!}
{2941}{}{Blood! Blood! Blood!}
{2942}{}{Your heart is mine!}



{2943}{}{RAAAAAAARRRR!!}
{2944}{}{Your weapons will be my trophies!}

{2945}{}{Death!}
{2946}{}{You are mine to kill!}
{2947}{}{Your bones shall bleach in the wastes!}
{2948}{}{Blood and darkness!}



{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Drill the scraggin' Idióta!}

#
# target being missed
#
{2960}{}{Wasted effort!}
{2961}{}{You have failed!}
{2962}{}{My blood is stronger than yours!}



{2963}{}{I live!!}
{2964}{}{Your body is weak and pitiful!}

#
############################################
# 3000 Robot
############################################
#
#  running away
#
{3000}{}{Retreat option initiated.}

{3001}{}{Tactical plan: retreat.}
{3002}{}{Combat effective minimal. Retreat advised.}
{3003}{}{Tactical analysis complete. Retreat recommended.}
{3004}{}{Downloading escape program.}
{3005}{}{Retreat sequence initiated.}




#
# moving in to attack
#
{3020}{}{Target acquired!}
{3021}{}{Terminate! Terminate!}
{3022}{}{The humanoid must not escape!}
{3023}{}{Terminate the intruder!}
{3024}{}{Combat sequence initiated.}
{3025}{}{Uploading combat program.}






#
# attacking
#
{3040}{}{Combat sequence initiated.}

{3041}{}{Attacking target.}
{3042}{}{Initiating attack sequence.}
{3043}{}{The intruder must be destroyed!}
{3044}{}{Tactical options selection completed.}



{3045}{}{Commencing attack.}
{3046}{}{The target will be destroyed!}
{3047}{}{Enemy termination sequence begun.}
{3048}{}{Target must be eliminated!}
{3049}{}{Offensive selection completed.}




#
# target being missed
#
{3060}{}{Analysis. Defensive program success.}
{3061}{}{Analysis. Target offense negligible.}
{3062}{}{Target attack failed. Calculating response.}
{3063}{}{Unit was unharmed by attack.}
{3064}{}{Recalculating target's offensive abilities.}
{3065}{}{Analysis. Target erred in tactical selection. Unit undamaged.}






#
############################################ 
# 3100 Ghoul
############################################ 
#
#  running away
#
{3100}{}{Gotta get outa here!}

{3101}{}{Eu voltarei...}
{3102}{}{Não vai me matar hoje!} 
{3103}{}{Later, normie!}
{3104}{}{You ain't heard the last of me!} 
{3105}{}{Vai pagar por isso... mas tarde!} 




{3106}{}{I ain't dyin' twice.}
{3107}{}{Feet don't fail me nAi!}
{3108}{}{I'm just executing a retrograde advance.} 
{3109}{}{Uh, time for a tactical withdrawal here.} 



{3110}{}{Exit, stage left.}
{3111}{}{It's later than I thought.} 

{3112}{}{Gotta run. See ya.}
{3113}{}{Run awaaaaay!}
{3114}{}{I've gotta go reattach some parts.} 
{3115}{}{These old bones can't take this anymore.} 
{3116}{}{It's not the years, it's the mileage.} 




{3117}{}{What a world, what a world....}
{3118}{}{I guess, you've learned your lesson, I'm outa here!} 
{3119}{}{Hey, stop backing away from me.}


#
# moving in to attack
#
{3120}{}{Você é história!}

{3121}{}{Toma isso!}
{3122}{}{Beef, beef, beef--beef bologna!} 

{3123}{}{Brains...}
{3124}{}{I'm gonna dig your grave...} 
{3125}{}{Hope I can keep your head intact...} 

{3126}{}{More Brains....}
{3127}{}{Send more cops!}
{3128}{}{Send more paramedics!}
{3129}{}{I could use some fresh parts.} 
{3130}{}{Steak Tartar comin' up.}
{3131}{}{Come an' get it!}
{3132}{}{Is it soup yet?}
{3133}{}{Where's the beef?}
{3134}{}{Mmm, I just love smoothskins.} 
{3135}{}{You crossed my shadow...or sumthin'} 
{3136}{}{I knew I heard the chow-bell.} 
{3137}{}{Guess who's comin' to dinner.} 











{3138}{}{Parts is parts.}
{3139}{}{So, you're my next organ donor huh?} 

#
# attacking
#
{3140}{}{Your number is up!}
{3141}{}{Não adianta ficar gritando por Misericórdia ...} 
{3142}{}{I'm gonna enjoy this}



{3143}{}{Oooo, that's gotta hurt!}
{3144}{}{Slicin' & Dicin' time.}
{3145}{}{I'm gonna eat your liver!}
{3146}{}{Espero que você não morra rápido demais} 
{3147}{}{Dinnertime!}



{3148}{}{Morra!}
{3149}{}{I eat Bastardos like you for breakfast, and lunch} 
{3150}{}{How can anything this messy be bad?} 
{3151}{}{Lemme' just have a taste!}
{3152}{}{Give Daddy some sugar, baby!} 
{3153}{}{I got sumpin' for ya!}
{3154}{}{Stay still! It'll hurt less.}
{3155}{}{Stop your twitchin', the chef's in the kitchen!} 
{3156}{}{I loves to watch 'em squirm.}
{3157}{}{Delicious & nutritious too!}
{3158}{}{You sure bleed a lot. Must be tender & juicy.} 
{3159}{}{I'm guessin' that's more fear than excitement.} 











#
# target being missed
#
{3160}{}{You cannot hurt me!}
{3161}{}{And you think *Ghouls* are slow?} 
{3162}{}{You missed, normie!}
{3163}{}{You missed, normie!}
{3164}{}{You can't kill what you can't hit!} 





{3165}{}{Muito lento!}
{3166}{}{OK, let's try that at full speed now.} 
{3167}{}{Were you actually aiming at me?} 
{3168}{}{What was that?}



{3169}{}{This is not a charade.}
{3170}{}{Combat requires total concentration.}
{3171}{}{Shame that your first time is gonna' be your last too.} 
{3172}{}{Are you lookin' at me?}
{3173}{}{You wanna try this again when you know what you're doin'?} 
{3174}{}{No, no, no, the *pointy-end* goes towards *me.* Got it?} 
{3175}{}{What were you aimin' at, or were you aimin' at all?} 
{3176}{}{What is your major malfunction numb-nuts?}
{3177}{}{You ain't never did this before have ya?} 
{3178}{}{My turn's next!}
{3179}{}{Was that really your *best* shot? Man, are you in trouble.}









#
############################################
# 3200 Junkie
############################################
#
#  running away
#
{3200}{}{Whoa. I am SO outta here.}
{3201}{}{Eu voltarei...after I get another hit.}
{3202}{}{Knew I should have taken more Buffout...}
{3203}{}{I can't shoot up when I'm dead...}
{3204}{}{Aieeeeeee! Don't hurt me! Don't hurt me!}
{3205}{}{This hallucination just became way too real for me...}





#
# moving in to attack
#
{3220}{}{Eat this!}
{3221}{}{You better hope you have some stimpacks...or some Jet.}
{3222}{}{Maybe I can sell your body for some Jet...}


{3223}{}{Gonna...hit...you...when...I...catch...you.}
{3224}{}{Maybe killing you will be the fix I need...}
{3225}{}{I'll kill you! I'll kill you! I'll kill you!}
{3226}{}{Killing you will top off my high nicely...}



#
# attacking
#
{3240}{}{Eat this!}
{3241}{}{I'll kill you! I'll kill you! I'll kill you!}
{3242}{}{You want some of this?!}


{3243}{}{Nrrrg}
{3244}{}{Hiyaaaaaa}
{3245}{}{I'll kill you slow...}
{3246}{}{You're going down like a 2-cap whore...}

#
# target being missed
#
{3260}{}{Close, but no Jet.}
{3261}{}{I'm so high, you'll never touch me!}
{3262}{}{Which one of me are you aiming at?}


{3263}{}{Whoa. Nearly got me.}
{3264}{}{I knew that Jet would make me faster...}
{3265}{}{You fight pretty badly for a drug-induced hallucination.}


#
####################################################################################
#
#                   Area People
#
####################################################################################
#                     
#

#                     4000  Arroyo
#                     6000  The Den
#                     8000  Modoc
#                     10000  Klamath
#                     12000  Vault City / Raiders
#                     14000  Gecko
#                     16000 Broken Hills
#                     18000 New Reno
#                     20000 Sierra Army Depot
#                     22000 Redding
#                     24000 NCR
#                     26000 V13 / V15
#                     28000 Military Base
#                     30000 Navarro
#                     32000 San Francisco
#                     34000 The Enclave
#                     36000 Special (Encounters and Created)
#
#                     Note : Some of these people will just have run away, moving to attack, attacking, and getting
#                                missed.  Others will also have cataloged hit locations.
#
####################################################################################
#
####################################################################################
#
# 4000 Arroyo
#
#                   4000 The Elder
#                   4100 Hakunin
#                   4200 Standing Fist
#
####################################################################################
#
#
####################################################################################
#
# 12000 Vault City / Raiders
#
#                   12000 Raider Mercs
#                   12100 Raider Captain
#                   12200 Gangster
#                   12300 Raider (Hit Locations)
#
####################################################################################
#
############################################
# 12000 Raider Mercs
############################################
#
#  running away
#
{12000}{}{No way am I staying in this clusterfuck...}

{12001}{}{Retreat!}
{12002}{}{Time to get the hell outta Dodge...}

{12003}{}{Scatter!}
{12004}{}{Fall back!}
{12005}{}{I'll wait to get these fuckers when Fallout 3 comes out...}

{12006}{}{Bishop can keep his fucking money...}
#
# moving in to attack
#
{12020}{}{Target acquired!}

{12021}{}{Somebody cover me!}
{12022}{}{Hut hut hut hut hut hut}
{12023}{}{Hut hut hut hut hut hut}
{12024}{}{Hut hut hut hut hut hut}



{12025}{}{Kiss your ass good-bye...}
{12026}{}{Time to dust this mother fucker...}
{12027}{}{Lock and load!}


{12028}{}{Rock and roll!}
{12029}{}{Look who just walked into the free fire zone...}

{12030}{}{Better hope you packed some stimpacks, tribal...}
{12031}{}{Contact!}
{12032}{}{The area's been breached!}
{12033}{}{We got us an intruder, boys!}
{12034}{}{Scramble, boys, we got an intruder!}
{12035}{}{You got some sand comin' in here...}
{12036}{}{By the numbers, people, by the numbers.}
{12037}{}{Attention to detail, people!}
{12038}{}{Lay down some suppressing fire! Keep their heads down!}







#
# attacking
#
{12040}{}{Waste 'em!}
{12041}{}{You're shit out of luck, tribal...}
{12042}{}{I'm going to put my boot so far up your ass, you'll be smelling shoe polish for a week.}

{12043}{}{::I wanna be an airborn ranger...::}
{12044}{}{Get critical!}
{12045}{}{You want some of this?! YOU WANT SOME OF THIS?!}


{12046}{}{Hiyaaaaaa!!!}
{12047}{}{Get some!}
{12048}{}{Better hope you packed some stimpacks, tribal...}
{12049}{}{Kiss your ass good-bye...}
#
# target being missed
#
{12060}{}{You fight like old people fuck!}

{12061}{}{Ha! Missed!}
{12062}{}{Too fast for you...}
{12063}{}{You're gonna be a long time dying...}

{12064}{}{Sloppy...}
{12065}{}{Weak AND slow, I see.}
#
############################################
# 12100 Raider Captain
############################################
#
#  running away
#
{12100}{}{Tenho que sair daqui!}

{12101}{}{Eu voltarei...}
{12102}{}{Não vai me matar hoje!}
{12103}{}{Later, normie!}
{12104}{}{You ain't heard the last of me!}
{12105}{}{Vai pagar por isso... mas tarde!}




#
# moving in to attack
#
{12120}{}{Você é história!}

{12121}{}{Toma isso!}
{12122}{}{Ah, dinner's arrived.}
{12123}{}{Brains...}
{12124}{}{I'm gonna dig your grave...}
{12125}{}{Hope I can keep your head intact...}

#
# attacking
#
{12140}{}{Your number is up!}
{12141}{}{Não adianta ficar gritando por Misericórdia ...}


{12142}{}{I'm gonna enjoy this}
{12143}{}{Oooo, that's gotta hurt!}
{12144}{}{}
{12145}{}{I'm gonna eat your liver!}
{12146}{}{Espero que você não morra rápido demaisly!}


{12147}{}{Dinnertime!}
{12148}{}{Morra!}
{12149}{}{I eat Bastardos like you for breakfast, and lunch.}

#
# target being missed
#
{12160}{}{You cannot hurt me!}

{12161}{}{}
{12162}{}{You missed, normie!}
{12163}{}{You missed, normie!}
{12164}{}{You can't kill what you can't hit!}



{12165}{}{Muito lento!}
#
############################################
# 12200 Gangster (Combat Messages)
############################################
#
#  running away
#
{12200}{}{Whoa, this shit's getting too heavy.}
{12201}{}{Time to go get some of the other boys...}
{12202}{}{I'll get you next time!}
{12203}{}{You're just lucky I ain't got no stimpacks on me...}
{12204}{}{Time to get the hell outta Dodge.}
{12205}{}{Need to find some stimpacks, fast...}






#
# moving in to attack
#
{12220}{}{I'm gonna roll you like dice.}
{12221}{}{And here I was, thinking I wasn't gonna get to kill no one today...}
{12222}{}{Looks like Golgotha just got a new resident...}
{12223}{}{Looks like we'll be doing this the hard way...}
{12224}{}{I'm gonna knock out your teeth and make dice out of them.}
{12225}{}{Looks like someone's gambling with their life...}
{12226}{}{I'm gonna kill you, your family, then your dog.}







{12227}{}{Time to take out the trash...}
{12228}{}{Gonna snap you like a wishbone...}

#
# attacking
#
{12240}{}{I'm going to kick your ass so hard you'll be wearing your ass as a hat.}
{12241}{}{Lady Luck ain't with you today...}
{12242}{}{I'm gonna beat you until you're ugly.}
{12243}{}{Time to put your ass in a grave.}
{12244}{}{I'm gonna kick your heart out and stomp on it.}
{12245}{}{Wish I had time to put your head in a vise...}
{12246}{}{Let me show you what we do with garbage around here...}
{12247}{}{I'm going to hit you so hard you'll think it's an earthquake...}
{12248}{}{I've had enough of this turd...}
{12249}{}{Say hello to the angels for me...}










#
# target being missed
#
{12260}{}{Moves like that'll put you in the hospital...}
{12261}{}{You hit like a bitch...}
{12262}{}{Nice one. I'll show you how it's done in a sec.}


{12263}{}{You blind and stupid?}
{12264}{}{You flying on Jet or something?}
{12265}{}{You couldn't hit the broad side of a casino.}
{12266}{}{If you tried to hit the air, you'd miss.}



#
############################################
# 12300 Raider (Hit Locations)
############################################
#
# target hit in head
#
{12300}{}{Ngggg}
{12301}{}{Minha cabeça ... ... ficando tonto ...}
{12302}{}{Ugnnn!}
{12303}{}{Na cara! Na cara não!}

#
# target hit in left arm
#
{12310}{}{My...arm...my...beautiful...arm.}
{12311}{}{Médico! Fudeu com meu braço!}

{12312}{}{*hffff*}
#
# target hit in right arm
#
{12320}{}{My stroke hand! Have you no shame?!}
{12321}{}{Médico! Fudeu com meu braço!}
{12322}{}{Looks like I can't polish my gun with that hand anymore...}



#
# target hit in torso
#
{12330}{}{Meu baço!}
{12331}{}{Hnrgggg}
{12332}{}{*hff*}
{12333}{}{Você... vai ... pagar ... por... isso!}

{12334}{}{*Ooooof*}
{12335}{}{Nggg! No complexo solar!}
#
# target hit in right leg
#
{12360}{}{Maldição! Minha perna!}

{12361}{}{*Ergg*}
{12362}{}{Vou precisar de um stimpack para a minha perna ...}

{12363}{}{Urggg ... perna se ... ferrou ...}
#
# target hit in left leg
#
{12370}{}{Maldição! Minha perna!}

{12371}{}{*Ergg*}
{12372}{}{Vou precisar de um stimpack para a minha perna ...}

{12373}{}{Urggg ... perna se ... ferrou ...}
#
# target hit in eyes
#
{12380}{}{My eye! My beautiful eye!}
{12381}{}{Tentando inviabilizar minha percepção de profundidade, não é?}


{12382}{}{Não posso ... ver ... sangue ... dentro ... dos olhos ...}
#
# target hit in groin
#
{12390}{}{O que você acha que é isso? Alguns filme barato de ação?}
{12391}{}{Now I can't sound off like a got a pair.}
{12392}{}{Bem, lá se vão as minhas bolas de bronze.}
{12393}{}{Me desculpe por vomitar tudo sobre mim mesmo.}
{12394}{}{Great. A player character with a ball fixation.}
{12395}{}{Deixe-me descançar um pouco, então depois vou te matar.}






{12396}{}{Nuts!}
#
####################################################################################
#
# 26000         V13/V15
#
#                    26000  Normal Khan
#                    26100  Tough Khan
#
####################################################################################
#
############################################
# 26000 Khan - Normal
############################################
#
#  running away
{26000}{}{Flee! Flee!}
{26001}{}{Retreat!}
{26002}{}{Regroup!}
{26003}{}{Fall back!}
{26004}{}{Withdraw!}
{26005}{}{Vou sair daqui!}

#
# moving in to attack
#
{26020}{}{Kill this fool!}

{26021}{}{You're already dead...}
{26022}{}{I'm gonna fuck you up!}
{26023}{}{This one's mine!}


{26024}{}{Take em!}
{26025}{}{Your ears will make a nice trophy!}

#
# attacking
#
{26040}{}{Enjoy the last few seconds of your life!}
{26041}{}{Blood! Blood! Blood!}
{26042}{}{Your heart is mine!}
{26043}{}{I love doing this to you!}
{26044}{}{Your weapons will be my trophies!}
{26045}{}{Death and dismemberment. Just two of my favorite things!}
{26046}{}{You are mine to kill!}
{26047}{}{Your bones shall bleach in the wastes!}
{26048}{}{Blood and darkness!}
{26049}{}{I'm gonna loot your corpse!}
{26050}{}{Drill the scraggin' Idióta!}











#
############################################
# 26100 Khan - Tough
############################################
#
#  running away
#
{26100}{}{Khans! Cover me!}
{26101}{}{Retreat!}
{26102}{}{Regroup!}
{26103}{}{Fall back!}
{26104}{}{Withdraw!}
{26105}{}{Break off and regroup!}

#
# moving in to attack
#
{26106}{}{Let the challenge begin!}
{26107}{}{I'm going to use you for target practice!}


{26108}{}{No Misericórdia for you!}
{26109}{}{This one's mine!}

{26110}{}{Khans attack!}
{26111}{}{It's party time!}
{26112}{}{Would someone please kill this waste of flesh!}


#
# attacking
#
{26113}{}{Khans kill!}
{26114}{}{Khans are the elite of the wastes!}
{26115}{}{I am supreme!}



{26116}{}{Khans will rule!}
{26117}{}{Khans are invincible!}
{26118}{}{No retreat! No surrender!}
{26119}{}{You are mine to kill!}
{26120}{}{I'll make a necklace out of your teeth!}
{26121}{}{Blood and darkness!}
{26122}{}{Khans are the strong!}





#
# target being missed
#
{26123}{}{Nice form but I'm over here!}
{26124}{}{I cannot be touched!}


{26125}{}{I am indestructible!}
{26126}{}{My blood is stronger than yours!}
{26127}{}{Maybe we should stop long enough for you to get some practice shots in!}
{26128}{}{You are not worthy of combat with me!}
{26129}{}{Why am I wasting my time with the likes of you?}




#
####################################################################################
#
# 32000        San Francisco
#
#                    32000  Shi Hit Location Messages
#                    32100  The Dragon
#                    32200  Lo Pan
#                    32300  Chip
#                    32400  Badger
#                    32500  Ryan
#                    32600  Shi Guards
#                    32700  Elron Hit Locations
#                    32800  Elron Guards
#                    32900  Ron Cruz/Nikki Goldman
#                    33000  OZ-9
#                    33100  OZ-7
#                    33200  Bastardo (Hit Locations)
#
####################################################################################
#
############################################
# 32000 Shi Hit Locations
############################################
#
# target hit in head
#
{32000}{}{A minha cara! A minha cara!}
{32001}{}{My scalp!}
{32002}{}{oooh... my ears...}
#
# target hit in left arm
#
{32010}{}{Ow, o meu braço!}

{32011}{}{Ai!}
{32012}{}{Você quebrou o meu braço!}

#
# target hit in right arm
#
{32020}{}{Ow, o meu braço!}

{32021}{}{Wahhhh!}
{32022}{}{Meu Deus! Meu braço!}

#
# target hit in torso
#
{32030}{}{OUCH!}
{32031}{}{I think I'm gonna faint...}
{32032}{}{Hey! Meu baço!}
{32033}{}{Uuuuf!}
{32034}{}{Isso dói!}
{32035}{}{I think you hit my liver!}

{32036}{}{Ohhh, dor!}
#
# target hit in right leg
#
{32060}{}{Ow, my leg}
{32061}{}{Meu joelho!}
{32062}{}{Right in the artery!}

#
# target hit in left leg
#
{32070}{}{Ow, my leg}
{32071}{}{::hop... hop::}
{32072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32080}{}{Eu não posso ver! Idióta!}
{32081}{}{Minha cara! Meus olhos! Arrrrgh!}
{32082}{}{Onde você está? Ajuda!}



#
# target hit in groin
#
{32090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32091}{}{I... I... ouch...}
{32092}{}{::whimper::}
{32093}{}{::vomit::}
{32094}{}{Eu. .. não posso ... respirar ...}
{32095}{}{A dor, a dor ...}
#
############################################
# 32100 The Dragon
############################################
#
#  running away
#
{32100}{}{Your kung fu is better than mine!}
{32101}{}{You are truly mighty. Goodbye.}
{32102}{}{Aieee! Evil triumphs!}



{32103}{}{Oh no...}
{32104}{}{I have failed.}
{32105}{}{I am dishonored.}
#
# moving in to attack
#
{32120}{}{It grieves me to attack you.}

{32121}{}{I advise you to flee.}
{32122}{}{Only a coward uses weapons.}

{32123}{}{Flee while you can.}
{32124}{}{Prepare yourself, wrongdoer.}
{32125}{}{Run and I won't hurt you.}


{32126}{}{If you insist on fighting...}
{32128}{}{Do you think you can defeat me?}

#
# attacking
#
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Chop-socky!}
{32142}{}{rooOOOooo!}
{32143}{}{Hai!}
{32144}{}{Huh!}
{32145}{}{Hai oooOOo!}
{32146}{}{Hai - ah!}
{32147}{}{Show me some!}
{32148}{}{Mongolian BEEF!}
{32149}{}{A kick in the eye!}



#
# target being missed
#
{32160}{}{Only a coward uses weapons.}
{32161}{}{Are you afraid to face a real fighter?}


{32162}{}{Your kung fu is no good here.}
{32163}{}{Surrender!}
{32164}{}{You call that fighting?}

{32165}{}{You move like a pregnant yak.}
#
############################################
# 32200 Lo Pan
############################################
#
#  running away
#
{32200}{}{I'm looking for a green-eyed girl... goodbye!}
{32201}{}{Yes sir... the check is in the mail.}
{32202}{}{I think I have an appointment...}
{32203}{}{Okay, you win!}




{32204}{}{I give up!}
{32205}{}{Your kung-fu is stronger than mine!}

#
# moving in to attack
#
{32220}{}{Lightning! Thunder! Kill them for me!}
{32221}{}{Your powers are weak!}


{32222}{}{Your kung fu cannot hurt me!}
{32223}{}{I'm invincible!}

{32224}{}{Flee, worm!}
{32225}{}{The thunder rolls toward you!}
{32226}{}{Float like a butterfly!}
{32228}{}{Sting like a bee!}



#
# attacking
#
{32240}{}{Who's Jack Burton?}
{32241}{}{Is it too much to ask for you to die?!}
{32242}{}{Have you paid your dues, Jack?}
{32243}{}{There's a problem with your face.}
{32244}{}{The check is in the MAIL!}
{32245}{}{Hell awaits you!}
{32246}{}{Greet your ancestors for me!}
{32247}{}{I am immortal!}







{32248}{}{Chop-suey!}
{32249}{}{Hai-YA!}
#
# target being missed
#
{32260}{}{Feelin' kind of invincible!}

{32261}{}{Give me your best shot.}
{32262}{}{I can take it.}
{32263}{}{You don't really know how to fight, do you?}
{32264}{}{You call that fighting?}


{32265}{}{::yawns::}
#
############################################
# 32300 Chip
############################################
#
#  running away
#
{32300}{}{I have a wife and kids!}

{32301}{}{Noo... it's my birthday!}
{32302}{}{Ow... my spleen...}
{32303}{}{Back to the hospital!}
{32304}{}{Must... protect. .. spleen hole...}
{32305}{}{Oh, my aching liver.}
#
# moving in to attack
#
{32320}{}{Don't make me use the cheat knife.}
{32321}{}{I am going to give you such a beat down...}
{32322}{}{You eat little pieces of shit for breakfast?}
{32323}{}{I'll kick your fucking ass.}
{32324}{}{I'll cut you!}
{32325}{}{I think that's all I have to say.}






#
# attacking
#
{32340}{}{Boom!}
{32341}{}{I railed your ass!}

{32342}{}{YEAH!}
{32343}{}{Yeah, baby, yeah!}
{32344}{}{You want some of this?}
{32345}{}{Don't move that way!}
{32346}{}{Shagadelic, bay-by!}




{32347}{}{Oh, is that your face?}
{32348}{}{You're a face full of ugly, aintcha?}

#
# target being missed
#
{32360}{}{Missed Meu baço! Ha ha!}

{32361}{}{Você não presta!}
{32362}{}{Ha ha! I rule!}

{32363}{}{Give me a kiss, sweetness.}
{32364}{}{Time to row, baby.}
{32365}{}{I'll cut you!}

#
############################################
# 32400 Badger
############################################
#
#  running away
#
{32400}{}{The face! Don't hit the face!}
{32401}{}{My hair's ruined, Otário!}
{32402}{}{Idióta! I'll sodomize you for that!}
{32403}{}{I need a bigger gun!}




{32404}{}{Waaaaaaaaaaa!!!}
{32405}{}{AAGGH!! You shot me in the ass!!}

#
# moving in to attack
#
{32420}{}{I'm gonna make you wish yer daddy pulled out early!}
{32421}{}{Say...you've got a face like an arse!}
{32422}{}{Let's see what you've got, dickcheese.}
{32423}{}{Bend over and grab your ankles, bub!}




{32424}{}{For Shane!!}
{32425}{}{I'll try to make this as painful as possible.}
{32426}{}{Mind if i break your kneecaps first?}
{32428}{}{C'mon, little girl. Show me what you got.}



#
# attacking
#
{32440}{}{Hope you won't need that arm...}
{32441}{}{Maldição, that's gotta hurt, huh?}


{32442}{}{Uf-da!}
{32443}{}{I love the smell of blood in the morning...}
{32444}{}{Boy, you are a bleeder, aren't ya?}


{32445}{}{::::belch!:::::}
{32446}{}{You broke the shirt, man!!!!}
{32447}{}{Hot lead enema coming right up!!} 


{32448}{}{Eat this!!}
#
# target being missed
#
{32460}{}{You shoot worse than my mom!}
{32461}{}{Maldição, Você não presta!}
{32462}{}{Go back to L.A., ya puss!} 
{32463}{}{Want me to stand still for you?} 




{32464}{}{:::brapp:::}
{32465}{}{Oh, good one...} 
#
############################################
# 32500 Ryan
############################################
#
#  running away
#
{32500}{}{Holy gee, I wanted to lick 'em!}

{32501}{}{La la la ... Ajuda!}
{32502}{}{Ha ha Ai!}
{32503}{}{AT! AT! At at at at at!}
{32504}{}{Ay carumba!}
{32505}{}{Heeeelp!}
#
# moving in to attack
#
{32520}{}{You don't want none o' this!}
{32521}{}{Come get some!}
{32522}{}{You want some of this? Huh? Huh?}
{32523}{}{Come on! I'll rape you!}




{32524}{}{You are SO dead.}
{32525}{}{You just opened a whole can of whoopass.}
{32526}{}{I got some for you, oh yeah.}


#
# attacking
#
{32540}{}{You gotta fight through that shit.}

{32541}{}{::sings::}
{32542}{}{Iii... will always love YOOUUUUU}
{32543}{}{Can't we all just get along?}

{32544}{}{You are SO dead.}
{32545}{}{Bend over for a second...}
{32546}{}{I got a present for you.}
{32547}{}{You want a piece of me?}
{32548}{}{He shoots... he scores!}
{32549}{}{How about some lovin'?}



#
# target being missed
#
{32560}{}{That's right!}
{32561}{}{That's RIGHT!}


{32562}{}{Ha ha ha!}
{32563}{}{Do you ever get any better?}
{32564}{}{Can't touch this!}
{32565}{}{Ai! Ha ha... just kidding.}



#
############################################
# 32600 Shi Guards
############################################
#
#  running away
#
{32600}{}{Aiee!}
{32601}{}{Next rank, step in!}

{32602}{}{Fall back!}
{32603}{}{Flee! Flee!}
{32604}{}{Run away!}
#
# moving in to attack
#
{32620}{}{Prepare to be dishonored.}

{32621}{}{The pillars of heaven shake...}
{32622}{}{... the poison arrows fall...}
{32623}{}{Here comes the Porkchop Express.}

{32624}{}{We warned you...}
{32625}{}{One ex-gaijin, coming up!}

{32626}{}{Goodbye, dead one.}
#
# attacking
#
{32640}{}{Something for you...}

{32641}{}{... something for your mother...}
{32642}{}{...something for your father...}
{32643}{}{...something for  your sister....}
{32644}{}{... and something for your ancestors!}

{32645}{}{Get out!}
{32646}{}{Morra!}
{32647}{}{Goodbye!}
{32648}{}{Let me dishonor you!}

{32649}{}{Your presence offends me.}
#
# target being missed
#
{32660}{}{It's all in the reflexes.}

{32661}{}{Gaijin fool!}
{32662}{}{::sighs:: When do we fight someone GOOD?}
{32663}{}{Is this ever going to end?}
{32664}{}{When do you start hitting me?}



{32665}{}{This is getting old...}
#
############################################
# 32700 Elron Hit Locations
############################################
#
# target hit in head
#
{32700}{}{A minha cara! A minha cara!}
{32701}{}{Star Father! Heal me!}
{32702}{}{Ouch! Preciso de um pouco de gelo para a minha cabeça.}


#
# target hit in left arm
#
{32710}{}{Ow, o meu braço!}
{32711}{}{Ai!}
{32712}{}{Você quebrou o meu braço!}

#
# target hit in right arm
#
{32720}{}{Ow, o meu braço!}
{32721}{}{Wahhhh!}
{32722}{}{By Elron! Meu braço!}

#
# target hit in torso
#
{32730}{}{Ai! Isso realmente dói!}
{32731}{}{I think I'm gonna faint}


{32732}{}{Ouch!}
{32733}{}{Star Father! Help me!}

{32734}{}{Isso dói!}
{32735}{}{Me deixe em paz!}

{32736}{}{Ohhh, dor!}
#
# target hit in right leg
#
{32760}{}{Ow, minha perna!}

{32761}{}{Meu joelho!}
{32762}{}{Ai!}
#
# target hit in left leg
#
{32770}{}{Ow, my tibia!}
{32771}{}{Meu joelho!}
{32772}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32780}{}{Ai! Meus olhos!}
{32781}{}{Minha cara! Meus olhos! Arrrrgh!}


{32782}{}{Meus olhos!}
#
# target hit in groin
#
{32790}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32791}{}{Oww ... Queima!}
{32792}{}{Urp!}
{32793}{}{::gasp::}
{32794}{}{Eu. .. não posso ... respirar ...}
{32795}{}{good thing... I'm already... sterile...}
#
############################################
# 32800 Elron Guards
############################################
#
#  running away
#
{32800}{}{Star Father! Help us!}

{32801}{}{My anodynes!}
{32802}{}{I want to live to see Quetzel!}
{32803}{}{Eeek!}
{32804}{}{Save our celebrities!}

{32805}{}{OZ-9! Help us!}
#
# moving in to attack
#
{32820}{}{I'm going to "adjust" you so hard...}
{32821}{}{I'll be so glad when we leave your type behind...}
{32822}{}{Too bad you won't see the future.}
{32823}{}{Never defy the Star Father.}
{32824}{}{Elron will smite you!}
{32825}{}{We are the vengeance of the Star Father!}
{32826}{}{Death to the uninitiated!}
{32828}{}{Think of this as a different zeta-scan.}







#
# attacking
#
{32840}{}{You have dirty energy!}
{32841}{}{For the Star Father!}


{32842}{}{For Elron!}
{32843}{}{For Quetzel!}
{32844}{}{For OZ-9!}
{32845}{}{Die, unwashed one!}
{32846}{}{Sully not our sanctum!}


{32847}{}{This is for OZ-9!}
#
# target being missed
#
{32860}{}{Your energy is misaligned.}
{32861}{}{If you were one of us, you'd've hit me.}


{32862}{}{You have dirty energy.}
{32863}{}{Do not strike a true believer!}
{32864}{}{That will reset your anodynes!}


{32865}{}{Impure one!}
#
############################################
# 32900 Ron Cruz/Nikki Goldman
############################################
#
#  running away
#
{32900}{}{I'm a movie star!}
{32901}{}{Celebrity coming through!}
{32902}{}{This isn't in the script!}
{32903}{}{Star Father! Ajuda!}




{32904}{}{But I'm famous!}
#
############################################
# 33000 OZ-9
############################################
#
#  running away
#
{33000}{}{Star Father! Help me!}

{33001}{}{No! Not me!}
{33002}{}{Please kill someone else!}

{33003}{}{Don't kill me! I'm OZ-9!}
{33004}{}{Guards! Help me!}
{33005}{}{You can't kill me! I'm too important!}


#
# moving in to attack
#
{33020}{}{You could've been one of us.}
{33021}{}{The stupid always turn on their betters.}
{33022}{}{Your impurity shines!}
{33023}{}{If only you had taken the oaths...}
{33024}{}{The Star Father will strike you down.}





{33025}{}{You will never see planet Quetzel.}
{33026}{}{You are a traitor to humanity's evolution.}

{33028}{}{Unworthy and impure.}
#
# attacking
#
{33040}{}{My touch will purify you!}

{33041}{}{I will strike you dead!}
{33042}{}{In the name of Elron!}
{33043}{}{For the glory of Star Father!}
{33044}{}{Feel the wrath of Elron!}
{33045}{}{This will optimize you!}




#
# target being missed
#
{33060}{}{The Star Father saves me!}

{33061}{}{Elron protects me!}
{33062}{}{Your anodynes are clogged!}

{33063}{}{Your energy is no good.}
{33064}{}{Don't you know how to focus?}

#
############################################
# 33100 OZ-7
############################################
#
#  running away
#
{33100}{}{Star Father! Help me!}

{33101}{}{I'd rather be on Quetzel!}
{33102}{}{Not me! Don't kill me!}
{33103}{}{I'm just a lackey!}
{33104}{}{I don't make the decisions!}
{33105}{}{I'm not the one you want!}




#
# moving in to attack
#
{33120}{}{I'd rather not do this...}
{33121}{}{Are you sure you wouldn't rather give up?}
{33122}{}{We can work this out, can't we?}
{33123}{}{If OZ-9 says you're bad, you must be bad.}
{33124}{}{For ... um... the glory of Elron!}
{33125}{}{Fighting is bad for your anodynes...}
{33126}{}{I'm no good at this threatening stuff.}
{33128}{}{My apologies if I'm about to hurt you.}







#
# attacking
#
{33140}{}{Look out!}
{33141}{}{::he squints his eyes shut and attacks::}

{33142}{}{Here comes another attack...}
{33143}{}{If you just run away, I wouldn't have to do this.}
{33144}{}{Go on! Get out of here!}


{33145}{}{Shoo! Shoo!}
{33146}{}{Stop fighting!}
{33147}{}{Hoooooooowdy ho!}


{33148}{}{You smell like flowers.}
{33149}{}{We can work this out!}

#
# target being missed
#
{33160}{}{Why are you trying to hurt me?}
{33161}{}{What have I ever done to you?}
{33162}{}{We don't have to fight, you knAi!}
{33163}{}{I don't want to hurt you!}
{33164}{}{I don't want you to hurt me!}
{33165}{}{Can we settle this like adults?}







############################################
# 33200 Bastardo Hit Locations
############################################
#
# target hit in head
#
{33200}{}{I think you broke my jaw!}
{33201}{}{My cheekbone!}
{33202}{}{That'll leave an unpleasant scar.}



#
# target hit in left arm
#
{33210}{}{My writing hand!}

{33211}{}{My elbAi!}
{33212}{}{Hey! Watch it!}
#
# target hit in right arm
#
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Wahhhh!}
{33222}{}{Ai! My ulna!!}

#
# target hit in torso
#
{33230}{}{I think you got my kidney!}
{33231}{}{My solar plexus!}


{33232}{}{::panting::}
{33233}{}{Uuuuf!}
{33234}{}{You don't have to do this...}
{33235}{}{Okay, that hurt.}
{33236}{}{Ohhh... owwww}
#
# target hit in right leg
#
{33260}{}{My fibia!}
{33261}{}{Meu joelho!}
{33262}{}{Ai!}
#
# target hit in left leg
#
{33270}{}{Oooh, my femur!}

{33271}{}{Meu joelho!}
{33272}{}{That'll be a limper..}
#
# target hit in eyes
#
{33280}{}{I think you detached my retina!}

{33281}{}{My aqueous humor! My vitreous humor!}
{33282}{}{I'm blind! I'm blind!}

#
# target hit in groin
#
{33290}{}{That's... that's... painful...}
{33291}{}{Mother...}
{33292}{}{::whimper::}
{33293}{}{Sweet mother of GOD!}

{33294}{}{Hmmm. Ow. Hmmm.}
{33295}{}{I think I'll go into shock now.}
#
####################################################################################
#
# 36000        Special Encounters (Randoms)
#
#                   36000 Kaga (Hit Locations)
#                   36100 Kaga (Combat Messages - Area 1)
#                   36200 Kaga (Combat Messages - Area 2)
#                   36300 Kaga (Combat Messages - Area 3)
#                   36400 Kaga (Combat Messages - Area 4)
#                   36500 Kaga (Combat Messages - Area 5)
#                   36600 Super Mutant (Master Army) - Hit Locations
#                   36700 Super Mutant (Master Army) - Combat Messages
#                   36800 Bounty Hunters - Combat Messages
#
####################################################################################
#
############################################
# 36000 Kaga (Hit Locations)
############################################
#
# target hit in head
#
{36000}{}{Gawd! That hit me in the head!}

{36001}{}{Ai! My head!}
{36002}{}{Oof! Kaga's head is on fire!}

#
# target hit in left arm
#
{36010}{}{My hand!}
{36011}{}{Ai! Good thing I'm right handed}

{36012}{}{Ai!!}
#
# target hit in right arm
#
{36020}{}{Ow, my arm}
{36021}{}{Você quebrou o meu braço!}
{36022}{}{Você vai se arrepender disso!}


#
# target hit in torso
#
{36030}{}{(Grunt!)}
{36031}{}{It's only a flesh wound!}

{36032}{}{Grrr!}
{36033}{}{Você vai se arrepender disso!}
{36034}{}{You should stop while you're ahead!}


{36035}{}{Good shot. My turn!}
#
# target hit in right leg
#
{36060}{}{Ow, my leg}
{36061}{}{Você vai pagar por isso!}

{36062}{}{Ah! Minha perna!}
#
# target hit in left leg
#
{36070}{}{Minha perna!}
{36071}{}{Unh! Aiming a little low aren't you?}
{36072}{}{You weren't trying to hit my leg were you!?!}


#
# target hit in eyes
#
{36080}{}{Maldição sanque em meus olhos!}
{36081}{}{O meu olho! Você vai pagar por isso!}


{36082}{}{Idióta!}
#
# target hit in groin
#
{36090}{}{Oooooo, time out, I have to pick something up}
{36091}{}{Ooo! Kaga gotta learn that move...}


{36092}{}{Urg! Petey! You OK down there?}
{36093}{}{That...wheeeeze...hurt!}
{36094}{}{Urp!}
{36095}{}{Gasp!}
#
############################################
# 36100 Kaga (Combat Messages) Area 1
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36100}{}{We will meet again!}

{36101}{}{Eu voltarei...}
{36102}{}{I have never been beaten before!}
{36103}{}{I will dedicate myself to hunting you down!}
{36104}{}{You ain't heard the last of me!}
{36105}{}{Vai pagar por isso... mas tarde!}




#
# moving in to attack
#
{36120}{}{I should have been the Chosen One!}

{36121}{}{Arroyo will regret casting me out!}
{36122}{}{I will have my revenge on YOU!}
{36123}{}{Kaga will send you to the next life!}
{36124}{}{Another Chosen One to kill!}



#
# attacking
#
{36140}{}{Your momma's not here to help you!}
{36141}{}{I'm gonna enjoy this!}


{36142}{}{Oooo, that gotta hurt!}
{36143}{}{I'm gonna take your head back to the Elder!}
{36144}{}{I'm gonna eat your liver!}
{36145}{}{Hope you don't die as quickly as the others.}
{36146}{}{Another Chosen One to kill!}




{36147}{}{Morra!}
{36148}{}{Scream for me}
#
# target being missed
#
{36160}{}{You cannot hurt me!}
{36161}{}{The spirits are protecting me.}
{36162}{}{Hope that ain't your best shot.}



{36163}{}{Bwahaha. Kaga didn't even have to duck!}
{36164}{}{You can't kill what you can't hit!}

{36165}{}{Muito lento!}
#
############################################
# 36200 Kaga (Combat Messages) Area 2
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36200}{}{We will meet again!}

{36201}{}{Eu voltarei...}
{36202}{}{You cannot kill the Great Kaga!}
{36203}{}{You are in luck! Kaga has business elsewhere}


{36204}{}{You and Kaga will meet again}
{36205}{}{Vai pagar por isso... mas tarde!}

#
# moving in to attack
#
{36220}{}{After I kill you, I will burn Arroyo to the ground!}
{36221}{}{I am to be feared by all!}
{36222}{}{Kaga will have your head for a trophy!}
{36223}{}{Surrender and I'll make your death quick.}




#
# attacking
#
{36240}{}{Feel the wrath of Kaga!}
{36241}{}{Não adianta ficar gritando por Misericórdia ...}
{36242}{}{I'm gonna enjoy this!}


{36243}{}{Oooo, Kaga felt that one from here,}
{36244}{}{I'm gonna take your head back to the Elder!}
{36245}{}{I'm gonna carve your heart out with a spoon!}
{36246}{}{Hope you don't die as quickly as the others!}
{36247}{}{Another Chosen One to kill!}




{36248}{}{Morra!}
{36249}{}{Scream for me.}
#
# target being missed
#
{36260}{}{You cannot hurt me!}
{36261}{}{The spirits are protecting me.}
{36262}{}{Hope that ain't your best shot.}



{36263}{}{Bwahaha. Kaga didn't even have to duck!}
{36264}{}{You can't kill what you can't hit!}

{36265}{}{Muito lento!}
#
############################################
# 36300 Kaga (Combat Messages) Area 3
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36300}{}{This is getting to be a bad habit.}

{36301}{}{Kaga needs more training.}
{36302}{}{I'll be back. Yada yada yada I'm gonna kill you.}
{36303}{}{You are in luck! Kaga has business elsewhere.}


{36304}{}{You and Kaga will meet again.}
{36305}{}{Vai pagar por isso... mas tarde!}

#
# moving in to attack
#
{36320}{}{Kaga and the Chosen One meet again!}

{36321}{}{Let's end this!}
{36322}{}{You will regret ever hearing the name Kaga!}
{36323}{}{My skills have increased since we last met.}


#
# attacking
#
{36340}{}{Feel the wrath of Kaga!}
{36341}{}{I'm gonna enjoy this!}

{36342}{}{Oooo, Kaga felt that one from here.}
{36343}{}{I'm gonna take your head back to the Elder!}
{36344}{}{I'm gonna carve your heart out with a spoon!}
{36345}{}{Hope you don't die as quickly as the others!}
{36346}{}{Another Chosen One to kill!}




{36347}{}{Morra!}
{36348}{}{Scream for me}
#
# target being missed
#
{36360}{}{You cannot hurt me!}
{36361}{}{The spirits are protecting me.}
{36362}{}{Hope that ain't your best shot.}



{36363}{}{Bwahaha. Kaga didn't even have to duck!}
{36364}{}{You can't kill what you can't hit!}

{36365}{}{Muito lento!}
#
############################################
# 36400 Kaga (Combat Messages) Area 4
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36400}{}{This is getting to be a bad habit.}

{36401}{}{Kaga needs more training.}
{36402}{}{This is not the last you will see of Kaga!}
{36403}{}{You are in luck! Kaga has business elsewhere.}


{36404}{}{You and Kaga will meet again!}
{36405}{}{Vai pagar por isso... mas tarde!}

#
# moving in to attack
#
{36420}{}{The Chosen One will never return to Arroyo!}
{36421}{}{Kaga will crush you!}


{36422}{}{Kaga fears no one!}
{36423}{}{Let Kaga teach you new skills he has learned.}

#
# attacking
#
{36440}{}{Feel the wrath of Kaga!}
{36441}{}{Hold still so Kaga can get a good shot.}
{36442}{}{I'm gonna enjoy this}


{36443}{}{Oooo, Kaga felt that one from here.}
{36444}{}{I'm gonna take your head back to the Elder!}
{36445}{}{I'm gonna carve your heart out with a spoon!}
{36446}{}{Hope you don't die as quickly as the others!}
{36447}{}{Another Chosen One to kill!}




{36448}{}{Morra!}
{36449}{}{Scream for me}
#
# target being missed
#
{36460}{}{You cannot hurt me!}
{36461}{}{The spirits are protecting me.}
{36462}{}{Hope that ain't your best shot.}



{36463}{}{Bwahaha. Kaga didn't even have to duck!}
{36464}{}{You can't kill what you can't hit!}

{36465}{}{Muito lento!}
#
############################################
# 36500 Kaga (Combat Messages) Area 5
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
#
# moving in to attack
#
{36520}{}{Kaga is ready for you now.}
{36521}{}{You are no match for Kaga.}
{36522}{}{Kaga will send you to next life.}
{36523}{}{Kaga gonna miss you.}
#
# attacking
#
{36540}{}{Feel the wrath of Kaga!}
{36541}{}{Kaga will be famous for killing you!}
{36542}{}{I'm gonna enjoy this!}


{36543}{}{Oooo, Kaga felt that one from here.}
{36544}{}{I'm gonna take your head back to the Elder.}
{36545}{}{It ends here Chosen One!}


{36546}{}{Kaga has to kill you now.}
{36547}{}{Morra!}
{36548}{}{Scream for me}
#
# target being missed
#
{36560}{}{You cannot hurt me!}
{36561}{}{The spirits are protecting me.}
{36562}{}{Hope that ain't your best shot.}



{36563}{}{Bwahaha. Kaga didn't even have to duck!}
{36564}{}{You can't kill what you can't hit!}

{36565}{}{Muito lento!}
#
#
############################################
# 36600 Super Mutant (Master Army) - Hit Locations
############################################
#
# target hit in head
#
{36600}{}{Ahhhgh! My face!}
{36601}{}{My face! You shall suffer!}

{36602}{}{Ahhhgh! I rend you into bits!}
#
# target hit in left arm
#
{36610}{}{Ahhhgh!}
{36611}{}{Ai! You almost hurt Chosen!}
{36612}{}{Ahhhgh! I snap your neck for that!}


#
# target hit in right arm
#
{36620}{}{Ahhhgh!}
{36621}{}{Ai! You almost hurt Chosen!}

{36622}{}{Ahhhgh! I snap your neck for that!}
#
# target hit in torso
#
{36630}{}{Oof!}
{36631}{}{Grrr!}
{36632}{}{I kill you for that!}
{36633}{}{You no hurt me when you dead!}
{36634}{}{I laugh at your feeble attack!}



{36635}{}{Oh!}
{36636}{}{I'm gonna dip you!}

{36637}{}{Grrr! You anger me.}
{36638}{}{Agh!}
{36639}{}{I will return this pain to you!}

{36640}{}{Oof!}
{36641}{}{Ouch!}
{36642}{}{Hmm, you might be trouble.}
{36643}{}{Grrr! I look forward to your death.}
{36644}{}{You can hurt me but you cannot win!}
{36645}{}{Ai! That wasn't a good idea to hurt me.}



#
# target hit in right leg
#
{36660}{}{Ahhhgh! Minha perna!}
{36661}{}{You call that pain? I laugh!}
{36662}{}{Ahhhgh! I snap your neck for that!}


#
# target hit in left leg
#
{36670}{}{Ahhhgh! Minha perna!}
{36671}{}{You call that pain? I laugh!}
{36672}{}{Ahhhgh! I shall snap your neck for that!}


#
# target hit in eyes
#
{36680}{}{Ahhhgh! Miserable human! I am blind!}
{36681}{}{Ahhhgh! Pain! What have you done!}
{36682}{}{Ahhhgh! I will torture you many days!}

#
# target hit in groin
#
{36690}{}{That is human weakness!}
{36691}{}{You call that pain? I laugh!}
{36692}{}{You are stupid, human!}
{36693}{}{Why you attack me there?}
{36694}{}{I will hurt you for many hours}
{36695}{}{Why you attack me there?}






#
############################################
# 36600 Super Mutant (Master Army) - Combat Messages
############################################
#
#  running away
#
{36700}{}{Run!}
{36701}{}{You will not kill me!}
{36702}{}{I will be back!}
{36703}{}{My friends get you for me!}
{36704}{}{You pay for this -- later!}
{36705}{}{We are Chosen! You die later!}





#
# moving in to attack
#
{36720}{}{Your death comes!}
{36721}{}{Those who bother Chosen, bother no one again!}
{36722}{}{Human weapons cannot harm me!}
{36723}{}{You will suffer, suffer great!}
{36724}{}{When I fight, I kill!}
{36725}{}{Who is stupid enough to anger us?}
{36726}{}{I see enemies to destroy!}
{36727}{}{You will suffer, suffer great!}








#
# attacking
#
{36740}{}{Now you die}
{36741}{}{Nobody save you nAi!}
{36742}{}{Let me see your pain!}
{36743}{}{Now you die burning death!}
{36744}{}{Die Human Fool!}
{36745}{}{Now you die a screaming death}





{36746}{}{Suffer!}
{36747}{}{Now I crush you!}
{36748}{}{You cannot fight the Chosen!}

{36749}{}{Suffer, human!}
#
# target being missed
#
{36760}{}{Why do you struggle?}
{36761}{}{Is that best humans can do!}
{36762}{}{You have no power!}
{36763}{}{You make me laugh hard!}
{36764}{}{Was that an attack?}
{36765}{}{We are the Chosen!}






#
####################################################################################
#
#                    Party Members
#
####################################################################################
#                     

#                     Notes
#                     

#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed
#
#                     40000 Sulik *
#                     40400 Vic
#                     40800 MacRae *
#                     41200 Lenny *
#                     41600 Marcus *
#                     42000 Myron *
#                     42400 Davin
#                     42800 Miria
#                     43200 Laddie
#                     43600 Cyberdog
#                     44000 Robo-Brain (Idiot/Chimp) *
#                     44400 Robo-Brain (Human/Cybernetic) *
#                     44800 Goris **
#
####################################################################################
#
############################################
# 44800 Goris
############################################
#
# target hit in head
#
{44800}{}{I'm thick skulled but that still hurt.} 
{44801}{}{I've got one hell of a headache.} 


{44802}{}{Umph. Not the head!}
{44803}{}{I can do head shots too you knAi!}

{44804}{}{Arrrgh! Dizzy...}
#
# target hit in left arm
#
{44810}{}{I'll kill you with my other arm.} 
{44811}{}{I don't need both arms to ruin your day!} 
{44812}{}{I don't use that arm anyway.} 
{44813}{}{Ouch! I can use a sling over here.} 
{44814}{}{One arm down, one to go!} 





 #
# target hit in right arm
#
{44820}{}{Hey, that's my fighting arm!} 
{44821}{}{Maldição that arm hurts!}
{44822}{}{I can take the likes of you with only one arm.} 



{44823}{}{Right arm... arrgh!} 
{44824}{}{You hit my arm. I tear off your arm!}

#
# target hit in torso
#
{44830}{}{Umph... can't... breathe.}
{44831}{}{I'm minus a couple of ribs after that one.}

{44832}{}{Ouch! I hate gut shots.}
{44833}{}{Arrgghh! Chest pains!} 
{44834}{}{Solar plexus... eegad that hurts!}
{44835}{}{Is this a fight or are you just trying to get my attention?}
{44836}{}{Let me know if that was supposed to hurt. I'll cry for you.}
{44837}{}{Did your mama teach you how to fight?}
{44838}{}{Oh the pain (yawn). Please don't hurt me any more.}
{44839}{}{You call that a hit. Let me show you how it's done!}
{44840}{}{I'm going to kick your ass for that one.}
{44841}{}{Whoa! That stings a bit.}
{44842}{}{I left the vault for this!?}
{44843}{}{I'm going to need a vacation.}









{44844}{}{Yeeeouch! That hurts!}
{44845}{}{That didn't hurt at all}
{44846}{}{Where's a stimpak when you need one?}
{44847}{}{As soon as I can move again, you've had it}
{44848}{}{I am impervious to pain!}
{44849}{}{I'm going to do the monster mash on your face!}





#
# target hit in right leg
#
{44860}{}{Great. I'll be the only Deathclaw at home with a limp.}

{44861}{}{Ouch! My leg...} 
{44862}{}{You'll pay with your leg for what you did to mine.}
{44863}{}{I'll miss that leg...} 
{44864}{}{I don't need two legs to kill you.}



#
# target hit in left leg
#
{44870}{}{Great. A bum leg.}
{44871}{}{Maldição it! The leg...} 
{44872}{}{Not the leg... can't walk right as it is.} 
{44873}{}{You cripple my leg, I cripple your leg.} 



{44874}{}{Arrggh! That knee hurts!}
#
# target hit in eyes
#
{44880}{}{Can't see!}
{44881}{}{Not the eyes!}

{44882}{}{Blood... in eyes... can't see.}
{44883}{}{I can't see you, but I can smell you.}
{44884}{}{I'm going to need glasses after that one!} 


#
# target hit in groin
#
{44890}{}{The groin is such a cheap shot!} 

{44891}{}{No... hitting... below... the belt!}
{44892}{}{That's fighting dirty. How about if I hit you in the crotch?} 

{44893}{}{I HATE groin shots! Unngh...} 
{44894}{}{Crotch shot... good thing I'm not human!}

#
#  running away
#
{44900}{}{Time to bail!}

{44901}{}{I'm leaving!}
{44902}{}{Retreat!}
{44903}{}{Fall back!}
{44904}{}{I'm out of here!}
{44905}{}{Feet don't fail me nAi!}
{44906}{}{Out of the way, I'm moving out!}
{44907}{}{I'm not retreating, this is a strategic withdrawal.}
{44908}{}{I've had enough of this shit!}
{44909}{}{I've got to get out of here!}






#
# moving in to attack
#
{44920}{}{Come here so I can hit you!}
{44921}{}{You're all mine!}


{44922}{}{It's you or me... and I vote you!}
{44923}{}{It's your funeral!}
{44924}{}{Come and get it!}
{44925}{}{Prepare to meet your doom!}
{44926}{}{Best kiss your ass goodbye while you still can.}
{44927}{}{I'm going to paint you red!}
{44928}{}{It's party time!}
{44929}{}{I'm heading in!}
{44930}{}{I'll see you on the front line!}
{44931}{}{Time to reach out and touch someone!}
{44932}{}{Advance and annihilate!}
{44933}{}{I'm going to fall on you like ugly on a human!}
{44934}{}{Time to get physical!}











{44935}{}{Getting up close and personal.}
{44936}{}{Bad ass moving in!}

{44937}{}{Incoming!}
{44938}{}{Locked on target and homing!}
{44939}{}{There's a storm coming!}


#
# attacking
#
{44940}{}{I'm going to hurt you... bad!}
{44941}{}{This is going to hurt you a lot more than it does me!}
{44942}{}{Do unto others before they do unto you!}
{44943}{}{If there's a part of you that doesn't hurt, it's next!}
{44944}{}{Contact sports. I love it!}
{44945}{}{Tell me your name so I can contact your next of kin.}
{44946}{}{I'm the one who put the 'death' in deathclaw!}
{44947}{}{It's better to give than to receive!}
{44948}{}{I hope you're enjoying this as much as I am!}
{44949}{}{Did that hurt? If not I can do it harder next time.}
{44950}{}{We have a bleeder over here!}
{44951}{}{It'll take more than a stimpak to fix you when I'm done.}
{44952}{}{I hope you have medical insurance. You're going to need it.}
{44953}{}{Here a rip, there a rip, everywhere a rip rip...}
{44954}{}{I don't care who started it, I intend to finish it!}
{44955}{}{I love the sound of tearing flesh, don't you?}
{44956}{}{Just warming up, the best is yet to come.}
{44957}{}{Just sharpening my claws.}
{44958}{}{Ooops! Hope you didn't need that!}
{44959}{}{If you fall over and stay there I'll go away!}




















#
# target being missed
#
{44960}{}{Will you stop moving around so I can hit you?}
{44961}{}{Glasses. Must look into getting some glasses.}
{44962}{}{Don't laugh. When I do hit you, it's going to hurt!}



{44963}{}{Arrg! Grng! Ghrr! Thpt! (Deathclaw four-letter words)}
{44964}{}{I guess I shouldn't make a career out of fighting.}
{44965}{}{How could I possibly miss anything as big as you are!}
{44966}{}{As soon as I get ranged in you're in trouble.}
{44967}{}{You're a nimble little shit aren't you.}
{44968}{}{I'm glad my mother didn't see me do that.}
{44969}{}{Why am I swinging over there when you're over here?}
{44970}{}{How embarrassing. Please don't tell anyone I did that.}
{44971}{}{That really pisses me off!}
{44972}{}{Ok. I missed! It could happen to anyone!}









{44973}{}{I'll get you next time.}
{44974}{}{Way to go, Grace!}
{44975}{}{That was a shining example of missing the target!}
{44976}{}{I'm beginning to think I'm not cut out for this.}
{44977}{}{Arrggh! I can't believe I missed you!}
{44978}{}{I fanned the air on that one I did!}
{44979}{}{Did I just miss you or what!}





#
