{100}{}{Herói}
{101}{}{}
{200}{}{Heroína}
{201}{}{}
{300}{}{Aldeão}
{400}{}{Aldeã}
{500}{}{Radscorpion}
{501}{}{Um pequeno escorpião mutante.}
{600}{}{Radscorpion}
{601}{}{Um escorpião mutado.}
{700}{}{Deathclaw}
{701}{}{Um Deathclaw imaturo.}
{800}{}{Deathclaw}
{801}{}{Um Deathclaw imaturo.}
{900}{}{Dog}
{901}{}{Um canino, provavelmente de uma raça mista.}
{1000}{}{Brahmin}
{1001}{}{Vaca mutante de duas cabeças.}
{1100}{}{Rato}
{1101}{}{Um grande e típico rato.}
{1200}{}{Mantis}
{1201}{}{Um Mantis mutado.}
{1300}{}{Anciã}
{1400}{}{Hakunin}
{1500}{}{Mynoc}
{1600}{}{Planta de esporas} #Spore Plant
{1601}{}{Uma planta carnivora.}
{1700}{}{Escravo charmoso} #Cute Slave
{1800}{}{Escrava charmosa} #handsome Slave
{1900}{}{Escravo saudável}
{2000}{}{Escrava saudável}
{2100}{}{Escravo forte}
{2200}{}{Escrava forte}
{2300}{}{Escravo de combate} #Combat Slave
{2400}{}{Escrava de combate}
{2500}{}{Escravo Inteligente} #Clever Slave
{2600}{}{Escrava Inteligente}
{2700}{}{Escravo genérico} #Generic Slave
{2800}{}{Escrava genérica}
{2900}{}{Anna}
{3000}{}{Bandido resistente} #Tough Thug
{3100}{}{Bandida resistente}
{3200}{}{Bandido desarmado} #Melee Thug
{3300}{}{Bandida desarmado}
{3400}{}{Bandido ágil} #Agile Thug
{3500}{}{Bandida ágil}
{3600}{}{Bandido armado} #Gun Thug
{3700}{}{Bandida armada}
{3800}{}{Bandido muito bem armado} #Big Gun Thug
{3900}{}{Bandida muito bem armada}
{4000}{}{Guarda resistente}
{4100}{}{Guarda resistente} #Tough Guard
{4200}{}{Guarda desarmado} #Melee Guard
{4300}{}{Guarda desarmada}
{4400}{}{Guarda ágil} #Agile Guard
{4500}{}{Guarda ágil}
{4600}{}{Guarda armado} #Gun Guard
{4700}{}{Guarda armada}
{4800}{}{Guarda muito bem armado} #Big Gun Guard
{4900}{}{Guarda muito bem armada}
{5000}{}{Órfão (Masculino)}
{5100}{}{Órfão (Feminino)}
{5200}{}{Criança (Masculino)}
{5300}{}{Criança (Feminino)}
{5400}{}{Perdedor}
{5500}{}{Perdedora}
{5600}{}{Mal comerciante} #Bad Merchant
{5700}{}{Mal comerciante}
{5800}{}{Comerciante}
{5900}{}{Comerciante}
{6000}{}{Mestre Negociante}
{6100}{}{Mestre Negociante} #Master Trader
{6200}{}{Vic}
{6300}{}{Camponês fraco} #Weak Peasant
{6400}{}{Camponêsa fraca}
{6500}{}{Camponês} #Average Peasant
{6600}{}{Camponêsa}
{6700}{}{Camponês forte} #Strong Peasant
{6800}{}{Camponêsa forte}
{6900}{}{Guarda fraco e desarmado} #Weak Melee Guard
{7000}{}{Guarda fraco e desarmada}
{7100}{}{Guarda armado} #Weak Gun Guard
{7200}{}{Guarda armada}
{7300}{}{Robô de Reparação} #Repair Bot
{7400}{}{Robô de Reparação Mark II}
{7500}{}{Robôcerebro} #Robobrain
{7600}{}{Robô olho flutuante} #Floating Eye Bot
{7700}{}{Robô sentinela} #Sentry Bot
{7800}{}{Robô sentinela Mark II}
{7900}{}{Robôcerebro}
{8000}{}{Gecko pequeno} #Little Gecko
{8100}{}{Gecko pequeno e forte}
{8200}{}{Cachorro selvagem} #Wild Dog
{8201}{}{Um cão feroz de raça mista.}
{8300}{}{Gecko dourado} #Golden Gecko
{8400}{}{Deathclaw}
{8500}{}{Ovo de Deathclaw}
{8600}{}{Gecko dourado forte}
{8700}{}{Lynette}
{8800}{}{Dr. Troy}
{8900}{}{John Cassidy}
{9000}{}{Gregory}
{9100}{}{Cidadã}
{9200}{}{Cidadão}
{9300}{}{Cidadã de classe alta}
{9400}{}{Cidadão de classe alta}
{9500}{}{Caçador}
{9600}{}{Caçadora}
{9700}{}{Sulik}
{9800}{}{Maida Buckner}
{9900}{}{Torr}
{10000}{}{Lumpy}
{10100}{}{Reator Incandescente 1} #Reactor Glowing One
{10200}{}{Reator Ghoul} #Reactor Ghoul
{10300}{}{Guarda do Reator}
{10400}{}{Zomak}
{10500}{}{Skeeter}
{10600}{}{O Cérebro} #The Brain
{10700}{}{Lenny}
{10800}{}{Wooz}
{10900}{}{Harold}
{11000}{}{Rato toupeira}
{11100}{}{Rato toupeira grande}
{11200}{}{Rato porco}
{11300}{}{Rato porco forte}
{11400}{}{Brahmin fraco}
{11401}{}{Um vaca mutante de duas cabeças.}
{11500}{}{A.Pwr.Armor (don't use)}
{11600}{}{Rato mutante}
{11601}{}{Um rato mutante.}
{11700}{}{Rato topeira mutante}
{11701}{}{Um rato topeira mutante.}
{11800}{}{Rato porco mutante}
{11801}{}{Um Rato porco mutante.}
{11900}{}{Super Mutante}
{12000}{}{Mutante poderoso}
{12100}{}{Melchoir}
{12200}{}{Hero Andro (não use)}
{12300}{}{Hero Andro (não use)}
{12400}{}{Herói (não use)}
{12500}{}{Heroína (não use)}
{12600}{}{Herói (não use)}
{12700}{}{Heroína (não use)}
{12800}{}{Herói (não use)}
{12900}{}{Heroína (não use)}
{13000}{}{Herói (não use)}
{13100}{}{Heroína (não use)}
{13200}{}{Herói (não use)}
{13300}{}{Heroína (não use)}
{13400}{}{Guarda de Vault City}
{13500}{}{Guarda de Vault City}
{13600}{}{Cyberdog}
{13700}{}{Guarda de NCR}
{13800}{}{Guarda de NCR}
{13900}{}{Guarda desarmado de NCR}
{14000}{}{Guarda de escravos}
{14100}{}{Supervisor de escravos} #Slaver Overseer
{14200}{}{O Grande Mestre Comerciante} #Grand Master Trader
{14300}{}{A Grande Mestre Negociante}
{14400}{}{Tandi}
{14500}{}{Merc}
{14600}{}{Ratch}
{14700}{}{Doofus}
{14800}{}{Mikey}
{14900}{}{Garçom de NCR}
{15000}{}{Dono da loja} #Shop Owner
{15100}{}{Gruthar}
{15200}{}{Goris}
{15300}{}{Rato toupeira de luta}
{15400}{}{Rato toupeira de luta}
{15500}{}{Rato toupeira de luta}
{15600}{}{Rato toupeira de luta}
{15700}{}{Rato toupeira de luta}
{15800}{}{Rato toupeira de luta}
{15900}{}{Ghoul genérico}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Doc Jones}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Laddie}
{16600}{}{Rondo}
{16700}{}{Rancheiro} #Ranch Hand
{16800}{}{Rancheiro}
{16900}{}{Rancheiro}
{17000}{}{Porteiro}
{17100}{}{Porteira} #Bouncer
{17200}{}{Sr. Handy fraco} #Weak Mr. Handy
{17300}{}{Genérico Incandescente 1} #Generic Glowing One
{17400}{}{Dar}
{17500}{}{Dalia}
{17600}{}{Gordon}
{17700}{}{test (não use)}
{17800}{}{Ghoul do reator}
{17900}{}{Genérico Ghoul}
{18000}{}{Matt}
{18100}{}{Líder caçador de recompensas (1-6)} #B. Hunter Lead (1-6)
{18200}{}{Caçador de recompensas (1-6)}
{18300}{}{Líder caçador de recompensas (7-12)}
{18400}{}{Caçador de recompensas (7-12)}
{18500}{}{Caçador de recompensas (7-12)}
{18600}{}{Líder caçador de recompensas (13-18)}
{18700}{}{Caçador de recompensas (13-18)}
{18800}{}{Caçador de recompensas (13-18)}
{18900}{}{Líder caçador de recompensas (19-?)}
{19000}{}{Caçador de recompensas (19-?)}
{19100}{}{Bess}
{19101}{}{Vaca mutante de duas cabeças.}
{19200}{}{Balthas}
{19300}{}{Grisham}
{19400}{}{Phil}
{19500}{}{Galinha}
{19600}{}{Karl}
{19700}{}{Jonny}
{19800}{}{Jo}
{19900}{}{Zeke}
{20000}{}{Butcher}
{20100}{}{Petey}
{20200}{}{Caçador Primitivo} #Primitive Hunter
{20300}{}{Caçador Primitivo}
{20400}{}{Canibal} #Cannibal
{20500}{}{Canibal}
{20600}{}{Homem sagrado} #Holy Man
{20700}{}{Mulher sagrada}
{20800}{}{Nômade-Baixo}
{20900}{}{Nômade-Médio}
{21000}{}{Nômade-Baixo}
{21100}{}{Nômade-Médio}
{21200}{}{Bandido}
{21300}{}{Bandida}
{21400}{}{Fazendeiro}
{21500}{}{Fazendeira}
{21600}{}{Mantis}
{21700}{}{Traficante de escravos} #Slaver
{21800}{}{Traficante de escravos}
{21900}{}{Brahmin selvagem} #Wild Brahmin
{22000}{}{Sobrevivencialista} #Homesteader
{22100}{}{Sobrevivencialista}
{22200}{}{Patrulha de Vault City}
{22300}{}{Patrulha de Vault City}
{22400}{}{Traficante de escravos Forte}
{22500}{}{Traficante de escravos Forte}
{22600}{}{Doidos} #Crazies
{22700}{}{Catadores}
{22800}{}{Glow Doidos}
{22900}{}{Glow Catadores}
{23000}{}{Pescador}
{23100}{}{Pescadora}
{23200}{}{Selvagens}
{23300}{}{Selvagens}
{23400}{}{Contrabandista de bebidas}
{23500}{}{Contrabandista de bebidas}
{23600}{}{Garimpeiro}
{23700}{}{Garimpeira}
{23800}{}{Assaltante}
{23900}{}{Assaltante}
{24000}{}{Gecko de fogo}
{24100}{}{Gecko de fogo duro}
{24200}{}{Alien}
{24300}{}{Alien duro}
{24400}{}{Deathclaw duro}
{24500}{}{Deathclaw dura}
{24600}{}{Nômade} #Floater
{24700}{}{Nômade desagradável}
{24800}{}{Centauro} #Centaur
{24900}{}{Centauro malvado}
{25000}{}{Patrulheiro da Enclave}
{25100}{}{Patrulheira da Enclave}
{25200}{}{Gangue Press} #Press Gang
{25300}{}{Gangue Press}
{25400}{}{Mercenario}
{25500}{}{Mercenaria}
{25600}{}{Noturno} #Nightkin
{25700}{}{Noturno duro}
{25800}{}{Ghoul duro}
{25900}{}{Criminoso} #Mobster
{26000}{}{Yakuza}
{26100}{}{NCR Ranger}
{26200}{}{NCR Ranger}
{26300}{}{Maurader}
{26400}{}{Maurader}
{26500}{}{Lloyd Garoto bonito} #Pretty Boy Lloyd
{26600}{}{Rato Vorpal}
{26700}{}{Homem de Vault 13}
{26800}{}{Mulher de Vault 13}
{26900}{}{Guardião da Ponte} #Bridge Guardian
{27000}{}{Estranho misterioso}
{27100}{}{Estranha misteriosa}
{27200}{}{Hakeswill}
{27300}{}{Grande Jesus Mordino}
{27400}{}{Dumar}
{27500}{}{Deathclaw Mãe}
{27600}{}{O Dragão} #The Dragon
{27700}{}{Lo Pan}
{27800}{}{Hubologista}
{27900}{}{Hubologista}
{28000}{}{Estranho misterioso}
{28100}{}{Estranho misterioso}
{28200}{}{Estranho misterioso}
{28300}{}{Estranho misterioso}
{28400}{}{Estranho misterioso}
{28500}{}{Estranho misterioso}
{28600}{}{Estranho misterioso}
{28700}{}{Estranho misterioso}
{28800}{}{Pres. Bodyguard}
{28900}{}{Ovo de Deathclaw}
{29000}{}{Metzger}
{29100}{}{Pessoa}
{29200}{}{Pessoa em tipo estranho de armadura}
{29300}{}{Presidente}
{29400}{}{Vice Presidente}
{29500}{}{Técnico}
{29600}{}{Badger}
{29700}{}{Dr. Fung}
{29800}{}{Criança}
{29900}{}{Criança}
{30000}{}{Comerciante armado}
{30100}{}{Técnico do laboratório Shi}
{30200}{}{Guarda Shi}
{30300}{}{Camponês Shi}
{30400}{}{Camponêsa Shi}
{30500}{}{Camponês de Lo Pan}
{30600}{}{Camponêsa de Lo Pan}
{30700}{}{Estivador} #Dock Worker
{30800}{}{Comerciante Shi}
{30900}{}{Rei Rato} #Keeng Ra'at
{31000}{}{Sulik - Nível 1}
{31100}{}{Sulik - Nível 2}
{31200}{}{Sulik - Nível 3}
{31300}{}{Sulik - Nível 4}
{31400}{}{Sulik - Nível 5}
{31500}{}{Sulik - Nível 6}
{31600}{}{Lenny - Nível 1}
{31700}{}{Lenny - Nível 2}
{31800}{}{Lenny - Nível 3}
{31900}{}{Goris - Nível 1}
{32000}{}{Goris - Nível 2}
{32100}{}{Goris - Nível 3}
{32200}{}{Goris - Nível 4}
{32300}{}{Goris - Nível 5}
{32400}{}{Goris - Nível 6}
{32500}{}{Myron - Nível 1}
{32600}{}{Myron - Nível 2}
{32700}{}{Myron - Nível 3}
{32800}{}{Myron - Nível 4}
{32900}{}{Marcus - Nível 1}
{33000}{}{Marcus - Nível 2}
{33100}{}{Marcus - Nível 3}
{33200}{}{Marcus - Nível 4}
{33300}{}{Marcus - Nível 5}
{33400}{}{Cyberdog - Nível 1}
{33500}{}{Cyberdog - Nível 2}
{33600}{}{Cyberdog - Nível 3}
{33700}{}{Cyberdog - Nível 4}
{33800}{}{Cassidy - Nível 1}
{33900}{}{Cassidy - Nível 2}
{34000}{}{Cassidy - Nível 3}
{34100}{}{Cassidy - Nível 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Nível 1}
{34400}{}{Dogmeat - Nível 2}
{34500}{}{Dogmeat - Nível 3}
{34600}{}{Dogmeat - Nível 4}
{34700}{}{Dogmeat - Nível 5}
{34800}{}{Dogmeat - Nível 6}
{34900}{}{Robôcerebro - Nível 1}
{35000}{}{Robôcerebro - Nível 2}
{35100}{}{Robôcerebro - Nível 3}
{35200}{}{Robôcerebro - Nível 4}
{35300}{}{Robôcerebro - Nível 5}
{35400}{}{Rainha Alien}
{35500}{}{Radscorpion preto}
{35600}{}{Radscorpion preto}
{35700}{}{Spud}
{35800}{}{Capitão de Mercenários}
{35900}{}{Mercenário}
{36000}{}{Mercenária}
{36100}{}{Sombra-que-Caminha} #Shadow-Who-Walks
{36200}{}{Punk}
{36300}{}{Punk}
{36400}{}{Marc}
{36500}{}{Dave H.}
{36600}{}{Capt. A. Ron Meyers}
{36700}{}{Chip}
{36800}{}{AHS-9}
{36900}{}{Guarda Hubologista}
{37000}{}{Guarda Hubologista}
{37100}{}{Juan}
{37200}{}{Vikki}
{37300}{}{Vic - Nível 1}
{37400}{}{Vic - Nível 2}
{37500}{}{Vic - Nível 3}
{37600}{}{Vic - Nível 4}
{37700}{}{Vic - Nível 5}
{37800}{}{Vic - Nível 6}
{37900}{}{Robôcerebro - Chimpanzé}
{38000}{}{Robôcerebro - Anormal}
{38100}{}{Robôcerebro - Humano}
{38200}{}{Formiga Gigante} #Giant Ant
{38300}{}{Formiga Gigante dura}
{38400}{}{Cachorro Pariah}
{38500}{}{Zurak}
{38600}{}{Imbot}
{38700}{}{Jimmy}
{38800}{}{Wejungh}
{38900}{}{Herb}
{39000}{}{Loopal}
{39100}{}{Jobe}
{39200}{}{Smitty}
{39300}{}{Rube}
{39400}{}{Master Krall}
{39500}{}{Ziggy}
{39600}{}{Master Khung}
{39700}{}{John Bishop}
{39800}{}{Angela Bishop}
{39900}{}{Sra. Bishop}
{40000}{}{Guarda Bishop's 1}
{40100}{}{Guarda Bishop's 2}
{40200}{}{Bandido Bishop's 1}
{40300}{}{Bandido Bishop's 2}
{40400}{}{Brahmin zangado}
{40500}{}{Lil' Jesus}
{40600}{}{Big Jesus}
{40700}{}{Homem de Mordino 1}
{40800}{}{Homem de Mordino 2}
{40900}{}{Homem de Mordino 3}
{41000}{}{Guarda Myron 1}
{41100}{}{Guarda Myron 2}
{41200}{}{Sr. Wright}
{41300}{}{Sra. Wright}
{41400}{}{Chris Wright}
{41500}{}{Keith Wright}
{41600}{}{Filho de Wright 1}
{41700}{}{Filho de Wright 2}
{41800}{}{Filha de Wright 1}
{41900}{}{Filha de Wright 2}
{42000}{}{Sr. Salvatore}
{42100}{}{Mason}
{42200}{}{Bandido de Salvatore 1}
{42300}{}{Bandido de Salvatore 2}
{42400}{}{Garçom genérico 1}
{42500}{}{Garçom genérico 2}
{42600}{}{Garçom genérico 3}
{42700}{}{Boxeador 1}
{42800}{}{Boxeador 2}
{42900}{}{Boxeador 3}
{43000}{}{Boxeador 4}
{43100}{}{Mike o Masticador}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Stuart Little}
{43500}{}{Irmãos Corsican} #Corsican Brothers
{43600}{}{Prostitutas dos Corsican}
{43700}{}{Padre Tully}
{43800}{}{Segurança do Casino 1}
{43900}{}{Segurança do Casino 2}
{44000}{}{Garota do Casino}
{44100}{}{Traficante de Drogas 1} #Drug Dealer/Pimp
{44200}{}{Traficante de Drogas 2}
{44300}{}{Traficante de Drogas 3}
{44400}{}{Traficante de Drogas 4}
{44500}{}{McGee}
{44600}{}{Miss Kitty}
{44700}{}{Prostituta Genérica 1}
{44800}{}{Prostituta Genérica 2}
{44900}{}{Jagged Jimmy J}
{45000}{}{Renesco}
{45100}{}{Cientista}
{45200}{}{Eldridge}
{45300}{}{Algernon}
{45400}{}{Jules}
{45500}{}{Burocrata 1}
{45600}{}{Burocrata 2}
{45700}{}{Comerciante 1}
{45800}{}{Comerciante 2}
{45900}{}{Guarda 1}
{46000}{}{Guarda 2}
{46100}{}{Guarda 3}
{46200}{}{Guarda 4}
{46300}{}{Soldado 1}
{46400}{}{Soldado 2}
{46500}{}{Soldado 3}
{46600}{}{Soldado 4}
{46700}{}{Sgt. Stark}
{46800}{}{"Doc" Andrew}
{46900}{}{Garçom}
{47000}{}{Torre armada} #Gun Turret
{47001}{}{Esta é uma torre de tiro automático equipado com um canhão de plasma duplo.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (Nível 1)}
{47300}{}{K-9 (Nível 2)}
{47400}{}{K-9 (Nível 3)}
{47500}{}{K-9 (Nível 4)}
{47600}{}{Cyberdog genérico}
{47700}{}{Ovo de Wanamingo} #Wanamingo Egg
{47800}{}{Guarda de Lo Pan}
{47900}{}{Marjorie}
{48000}{}{Canhão automático}
{48100}{}{Gecko especial}
{48200}{}{Ceifador} #Grim Reaper
{48300}{}{Frank Horrigan}
{48301}{}{Guarda Costas do Presidente.} #The President's Body Guarda.

{48400}{}{Nessa}
{48401}{}{The ghost of dead Nessa.}
{48500}{}{Shaman}
{48501}{}{Tribal shaman.}
{48600}{}{Warrior 	}
{48601}{}{Tribe warrior.}
{48700}{}{Guard}
{48800}{}{Sulik's sister}
{48900}{}{Kaga}
{49000}{}{Kaga}
{49100}{}{Kaga}
{49200}{}{Kaga}
{49300}{}{Kaga}
{49400}{}{Hologram 00000}
{49401}{}{The hologram for the director of science.}
{49500}{}{Hologram 10001}
{49501}{}{The hologram for the director of security.}
{49600}{}{Hologram 12001}
{49601}{}{The hologram for the director of operations.}
{49700}{}{Hologram 10031}
{49701}{}{Hologram for the director of Ground Maintenance.}
{49800}{}{Hologram 40011}
{49801}{}{Hologram for the Director of Public Relations.}
{49900}{}{Mr. Handy Robot}
{49901}{}{A seriously depressed version of the Mr. Handy Robot.}
{50000}{}{The Doctor}
{50001}{}{The leading, and only, Doctor left in the EPA.}
{50100}{}{EPA Spore Plant}
{50101}{}{A hideously mutated spore plant.}
{50200}{}{Kitsune}
{50300}{}{Dex}
{50400}{}{Cat Jules}
{50500}{}{Doctor's Warrior}
{50501}{}{A warrior for the doctor.}
{50600}{}{Fruit fly}
{50601}{}{A mutated fruit fly.}
{50700}{}{A hologram}
{50701}{}{A hologram.}
{50800}{}{Kitsune - level 1}
{50900}{}{Kitsune - level 2}
{51000}{}{Kitsune - level 3}
{51100}{}{Kitsune - level 4}
{51200}{}{Kitsune - level 5}
{51300}{}{Dex - level 1}
{51400}{}{Dex - level 2}
{51500}{}{Dex - level 3}
{51600}{}{Dex - level 4}
{51700}{}{Dex - level 5}
{51800}{}{Cat Jules - level 1}
{51900}{}{Cat Jules - level 2}
{52000}{}{Cat Jules - level 3}
{52100}{}{Cat Jules - level 4}
{52200}{}{Cat Jules - level 5}
{52300}{}{MIBoba Fe88}
{52400}{}{Hivan Zolo}
{52500}{}{Contie-bacca}
{52600}{}{Darek Vader}
{52700}{}{Jotisz the Hutt}
{52800}{}{R2Qwerty}
{52900}{}{Chris3ParksO}
{53000}{}{Yosan12}
{53100}{}{Obi-Wan-Killap}
{53200}{}{Empress Timeslip}
{53300}{}{Luke Skynet}
{53400}{}{Mon-Morticia}
{53500}{}{Kanhef}
{53600}{}{HawkEyE}
{53700}{}{Dravean}
{53800}{}{Mr. Wolna}
{53900}{}{encinodude}
{54000}{}{Minigun Jim}
{54100}{}{Bofast}
{54200}{}{Krom}
{54300}{}{Mother Spore Plant}
{54400}{}{Mother Alien}
{54500}{}{EPA Spore Plant}
{54501}{}{A hideously mutated spore plant.}
{54600}{}{Wild Dog}
{54601}{}{A mixed breed feral dog.}
{54700}{}{Sentry Bot Mark II}
{54800}{}{Old Joe}
{54900}{}{A plant creature}