{100}{}{Herói}
{101}{}{}
{200}{}{Heroína}
{201}{}{}
{300}{}{Aldeão}
{400}{}{Aldeã}
{500}{}{Radscorpion}
{501}{}{Um pequeno escorpião mutante.}
{600}{}{Radscorpion}
{601}{}{Um escorpião mutado.}
{700}{}{Deathclaw}
{701}{}{Um Deathclaw imaturo.}
{800}{}{Deathclaw}
{801}{}{Um Deathclaw imaturo.}
{900}{}{Dog}
{901}{}{Um canino, provavelmente de uma raça mista.}
{1000}{}{Brahmin}
{1001}{}{Vaca mutante de duas cabeças.}
{1100}{}{Rato}
{1101}{}{Um grande e típico rato.}
{1200}{}{Mantis}
{1201}{}{Um Mantis mutado.}
{1300}{}{Anciã}
{1400}{}{Hakunin}
{1500}{}{Mynoc}
{1600}{}{Planta de esporas} #Spore Plant
{1601}{}{Uma planta carnivora.}
{1700}{}{Escravo charmoso} #Cute Slave
{1800}{}{Escrava charmosa} #handsome Slave
{1900}{}{Escravo saudável}
{2000}{}{Escrava saudável}
{2100}{}{Escravo forte}
{2200}{}{Escrava forte}
{2300}{}{Escravo de combate} #Combat Slave
{2400}{}{Escrava de combate}
{2500}{}{Escravo Inteligente} #Clever Slave
{2600}{}{Escrava Inteligente}
{2700}{}{Escravo genérico} #Generic Slave
{2800}{}{Escrava genérica}
{2900}{}{Anna}
{3000}{}{Bandido resistente} #Tough Thug
{3100}{}{Bandida resistente}
{3200}{}{Bandido desarmado} #Melee Thug
{3300}{}{Bandida desarmado}
{3400}{}{Bandido ágil} #Agile Thug
{3500}{}{Bandida ágil}
{3600}{}{Bandido armado} #Gun Thug
{3700}{}{Bandida armada}
{3800}{}{Bandido muito bem armado} #Big Gun Thug
{3900}{}{Bandida muito bem armada}
{4000}{}{Guarda resistente}
{4100}{}{Guarda resistente} #Tough Guard
{4200}{}{Guarda desarmado} #Melee Guard
{4300}{}{Guarda desarmada}
{4400}{}{Guarda ágil} #Agile Guard
{4500}{}{Guarda ágil}
{4600}{}{Guarda armado} #Gun Guard
{4700}{}{Guarda armada}
{4800}{}{Guarda muito bem armado} #Big Gun Guard
{4900}{}{Guarda muito bem armada}
{5000}{}{Órfão (Masculino)}
{5100}{}{Órfão (Feminino)}
{5200}{}{Criança (Masculino)}
{5300}{}{Criança (Feminino)}
{5400}{}{Perdedor}
{5500}{}{Perdedora}
{5600}{}{Mal comerciante} #Bad Merchant
{5700}{}{Mal comerciante}
{5800}{}{Comerciante}
{5900}{}{Comerciante}
{6000}{}{Mestre Negociante}
{6100}{}{Mestre Negociante} #Master Trader
{6200}{}{Vic}
{6300}{}{Camponês fraco} #Weak Peasant
{6400}{}{Camponêsa fraca}
{6500}{}{Camponês} #Average Peasant
{6600}{}{Camponêsa}
{6700}{}{Camponês forte} #Strong Peasant
{6800}{}{Camponêsa forte}
{6900}{}{Guarda fraco e desarmado} #Weak Melee Guard
{7000}{}{Guarda fraco e desarmada}
{7100}{}{Guarda armado} #Weak Gun Guard
{7200}{}{Guarda armada}
{7300}{}{Robô de Reparação} #Repair Bot
{7400}{}{Robô de Reparação Mark II}
{7500}{}{Robôcerebro} #Robobrain
{7600}{}{Robô olho flutuante} #Floating Eye Bot
{7700}{}{Robô sentinela} #Sentry Bot
{7800}{}{Robô sentinela Mark II}
{7900}{}{Robôcerebro}
{8000}{}{Gecko pequeno} #Little Gecko
{8100}{}{Gecko pequeno e forte}
{8200}{}{Cachorro selvagem} #Wild Dog
{8201}{}{Um cão feroz de raça mista.}
{8300}{}{Gecko dourado} #Golden Gecko
{8400}{}{Deathclaw}
{8500}{}{Ovo de Deathclaw}
{8600}{}{Gecko dourado forte}
{8700}{}{Lynette}
{8800}{}{Dr. Troy}
{8900}{}{John Cassidy}
{9000}{}{Gregory}
{9100}{}{Cidadã}
{9200}{}{Cidadão}
{9300}{}{Cidadã de classe alta}
{9400}{}{Cidadão de classe alta}
{9500}{}{Caçador}
{9600}{}{Caçadora}
{9700}{}{Sulik}
{9800}{}{Maida Buckner}
{9900}{}{Torr}
{10000}{}{Lumpy}
{10100}{}{Reator Incandescente 1} #Reactor Glowing One
{10200}{}{Reator Ghoul} #Reactor Ghoul
{10300}{}{Guarda do Reator}
{10400}{}{Zomak}
{10500}{}{Skeeter}
{10600}{}{O Cérebro} #The Brain
{10700}{}{Lenny}
{10800}{}{Wooz}
{10900}{}{Harold}
{11000}{}{Rato toupeira}
{11100}{}{Rato toupeira grande}
{11200}{}{Rato porco}
{11300}{}{Rato porco forte}
{11400}{}{Brahmin fraco}
{11401}{}{Um vaca mutante de duas cabeças.}
{11500}{}{A.Pwr.Armor (don't use)}
{11600}{}{Rato mutante}
{11601}{}{Um rato mutante.}
{11700}{}{Rato topeira mutante}
{11701}{}{Um rato topeira mutante.}
{11800}{}{Rato porco mutante}
{11801}{}{Um Rato porco mutante.}
{11900}{}{Super Mutante}
{12000}{}{Mutante poderoso}
{12100}{}{Melchoir}
{12200}{}{Hero Andro (não use)}
{12300}{}{Hero Andro (não use)}
{12400}{}{Herói (não use)}
{12500}{}{Heroína (não use)}
{12600}{}{Herói (não use)}
{12700}{}{Heroína (não use)}
{12800}{}{Herói (não use)}
{12900}{}{Heroína (não use)}
{13000}{}{Herói (não use)}
{13100}{}{Heroína (não use)}
{13200}{}{Herói (não use)}
{13300}{}{Heroína (não use)}
{13400}{}{Guarda de Vault City}
{13500}{}{Guarda de Vault City}
{13600}{}{Cyberdog}
{13700}{}{Guarda de NCR}
{13800}{}{Guarda de NCR}
{13900}{}{Guarda desarmado de NCR}
{14000}{}{Guarda de escravos}
{14100}{}{Supervisor de escravos} #Slaver Overseer
{14200}{}{O Grande Mestre Comerciante} #Grand Master Trader
{14300}{}{A Grande Mestre Negociante}
{14400}{}{Tandi}
{14500}{}{Merc}
{14600}{}{Ratch}
{14700}{}{Doofus}
{14800}{}{Mikey}
{14900}{}{Garçom de NCR}
{15000}{}{Dono da loja} #Shop Owner
{15100}{}{Gruthar}
{15200}{}{Goris}
{15300}{}{Rato toupeira de luta}
{15400}{}{Rato toupeira de luta}
{15500}{}{Rato toupeira de luta}
{15600}{}{Rato toupeira de luta}
{15700}{}{Rato toupeira de luta}
{15800}{}{Rato toupeira de luta}
{15900}{}{Ghoul genérico}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Doc Jones}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Laddie}
{16600}{}{Rondo}
{16700}{}{Rancheiro} #Ranch Hand
{16800}{}{Rancheiro}
{16900}{}{Rancheiro}
{17000}{}{Porteiro}
{17100}{}{Porteira} #Bouncer
{17200}{}{Mr. Handy fraco} #Weak Mr. Handy
{17300}{}{Genérico Incandescente 1} #Generic Glowing One
{17400}{}{Dar}
{17500}{}{Dalia}
{17600}{}{Gordon}
{17700}{}{test (não use)}
{17800}{}{Ghoul do reator}
{17900}{}{Genérico Ghoul}
{18000}{}{Matt}
{18100}{}{Caçador de recompensas Líder (1-6)} #B. Hunter Lead (1-6)
{18200}{}{Caçador de recompensas (1-6)}
{18300}{}{B. Hunter Lead (7-12)}
{18400}{}{Bounty Hunter (7-12)}
{18500}{}{Bounty Hunter (7-12)}
{18600}{}{B. Hunter Lead (13-18)}
{18700}{}{Bounty Hunter (13-18)}
{18800}{}{Bounty Hunter (13-18)}
{18900}{}{B. Hunter Lead (19-?)}
{19000}{}{Bounty Hunter (19-?)}
{19100}{}{Bess}
{19101}{}{Vaca mutante de duas cabeças.}
{19200}{}{Balthas}
{19300}{}{Grisham}
{19400}{}{Phil}
{19500}{}{Chicken}
{19600}{}{Karl}
{19700}{}{Jonny}
{19800}{}{Jo}
{19900}{}{Zeke}
{20000}{}{Butcher}
{20100}{}{Petey}
{20200}{}{Primitive Hunter}
{20300}{}{Primitive Hunter}
{20400}{}{Cannibal}
{20500}{}{Cannibal}
{20600}{}{Holy Man}
{20700}{}{Holy Woman}
{20800}{}{Nomad- Low}
{20900}{}{Nomad- Med}
{21000}{}{Nomad- Low}
{21100}{}{Nomad- Med}
{21200}{}{Bandit}
{21300}{}{Bandit}
{21400}{}{Farmer}
{21500}{}{Farmer}
{21600}{}{Mantis}
{21700}{}{Slaver}
{21800}{}{Slaver}
{21900}{}{Wild Brahmin}
{22000}{}{Homesteader}
{22100}{}{Homesteader}
{22200}{}{Vault City Patrol}
{22300}{}{Vault City Patrol}
{22400}{}{Strong Slaver}
{22500}{}{Strong Slaver}
{22600}{}{Crazies}
{22700}{}{Scavengers}
{22800}{}{Glow Crazies}
{22900}{}{Glow Scavengers}
{23000}{}{Fisherman}
{23100}{}{Fisherwoman}
{23200}{}{Wilder}
{23300}{}{Wilder}
{23400}{}{Bootlegger}
{23500}{}{Bootlegger}
{23600}{}{Prospector}
{23700}{}{Prospector}
{23800}{}{Raider}
{23900}{}{Raider}
{24000}{}{Fire Gecko}
{24100}{}{Tough Fire Gecko}
{24200}{}{Alien}
{24300}{}{Tough Alien}
{24400}{}{Sm Tough Deathclaw}
{24500}{}{Tough Deathclaw}
{24600}{}{Floater}
{24700}{}{Nasty Floater}
{24800}{}{Centaur}
{24900}{}{Mean Centaur}
{25000}{}{Enclave Patrol}
{25100}{}{Enclave Patrol}
{25200}{}{Press Gang}
{25300}{}{Press Gang}
{25400}{}{Mercenary}
{25500}{}{Mercenary}
{25600}{}{Nightkin}
{25700}{}{Tough Nightkin}
{25800}{}{Tough Ghoul}
{25900}{}{Mobster}
{26000}{}{Yakuza}
{26100}{}{NCR Ranger}
{26200}{}{NCR Ranger}
{26300}{}{Maurader}
{26400}{}{Maurader}
{26500}{}{Pretty Boy Lloyd}
{26600}{}{Vorpal Rato}
{26700}{}{Vault 13 Man}
{26800}{}{Vault 13 Woman}
{26900}{}{Bridge Guardian}
{27000}{}{Mysterious Stranger}
{27100}{}{Mysterious Stranger}
{27200}{}{Hakeswill}
{27300}{}{Big Jesus Mordino}
{27400}{}{Dumar}
{27500}{}{Mother Deathclaw}
{27600}{}{The Dragon}
{27700}{}{Lo Pan}
{27800}{}{Hubologist}
{27900}{}{Hubologist}
{28000}{}{Mysterious Stranger}
{28100}{}{Mysterious Stranger}
{28200}{}{Mysterious Stranger}
{28300}{}{Mysterious Stranger}
{28400}{}{Mysterious Stranger}
{28500}{}{Mysterious Stranger}
{28600}{}{Mysterious Stranger}
{28700}{}{Mysterious Stranger}
{28800}{}{Pres. Bodyguard}
{28900}{}{Deathclaw Egg}
{29000}{}{Metzger}
{29100}{}{Person}
{29200}{}{Person in strange type of armor}
{29300}{}{President}
{29400}{}{Vice President}
{29500}{}{Technicion}
{29600}{}{Badger}
{29700}{}{Dr. Fung}
{29800}{}{Kid}
{29900}{}{Kid}
{30000}{}{Gun Merchant}
{30100}{}{Shi Lab Tech}
{30200}{}{Shi Guard}
{30300}{}{Shi Peasant}
{30400}{}{Shi Peasant}
{30500}{}{Lo Pan Peasant}
{30600}{}{Lo Pan Peasant}
{30700}{}{Dock Worker}
{30800}{}{Shi Merchant}
{30900}{}{Keeng Ra'at}
{31000}{}{Sulik - Stage 1}
{31100}{}{Sulik - Stage 2}
{31200}{}{Sulik - Stage 3}
{31300}{}{Sulik - Stage 4}
{31400}{}{Sulik - Stage 5}
{31500}{}{Sulik - Stage 6}
{31600}{}{Lenny - Stage 1}
{31700}{}{Lenny - Stage 2}
{31800}{}{Lenny - Stage 3}
{31900}{}{Goris - Stage 1}
{32000}{}{Goris - Stage 2}
{32100}{}{Goris - Stage 3}
{32200}{}{Goris - Stage 4}
{32300}{}{Goris - Stage 5}
{32400}{}{Goris - Stage 6}
{32500}{}{Myron - Stage 1}
{32600}{}{Myron - Stage 2}
{32700}{}{Myron - Stage 3}
{32800}{}{Myron - Stage 4}
{32900}{}{Marcus - Stage 1}
{33000}{}{Marcus - Stage 2}
{33100}{}{Marcus - Stage 3}
{33200}{}{Marcus - Stage 4}
{33300}{}{Marcus - Stage 5}
{33400}{}{Cyberdog - Stage 1}
{33500}{}{Cyberdog - Stage 2}
{33600}{}{Cyberdog - Stage 3}
{33700}{}{Cyberdog - Stage 4}
{33800}{}{Cassidy - Stage 1}
{33900}{}{Cassidy - Stage 2}
{34000}{}{Cassidy - Stage 3}
{34100}{}{Cassidy - Stage 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Stage 1}
{34400}{}{Dogmeat - Stage 2}
{34500}{}{Dogmeat - Stage 3}
{34600}{}{Dogmeat - Stage 4}
{34700}{}{Dogmeat - Stage 5}
{34800}{}{Dogmeat - Stage 6}
{34900}{}{Robôcerebro - Stage 1}
{35000}{}{Robôcerebro - Stage 2}
{35100}{}{Robôcerebro - Stage 3}
{35200}{}{Robôcerebro - Stage 4}
{35300}{}{Robôcerebro - Stage 5}
{35400}{}{Queen Alien}
{35500}{}{Black Radscorpion}
{35600}{}{Black Radscorpion}
{35700}{}{Spud}
{35800}{}{Mercenary Captain}
{35900}{}{Mercenary}
{36000}{}{Mercenary}
{36100}{}{Shadow-Who-Walks}
{36200}{}{Punk}
{36300}{}{Punk}
{36400}{}{Marc}
{36500}{}{Dave H.}
{36600}{}{Capt. A. Ron Meyers}
{36700}{}{Chip}
{36800}{}{AHS-9}
{36900}{}{Hubologist Guard}
{37000}{}{Hubologist Guard}
{37100}{}{Juan}
{37200}{}{Vikki}
{37300}{}{Vic - Stage 1}
{37400}{}{Vic - Stage 2}
{37500}{}{Vic - Stage 3}
{37600}{}{Vic - Stage 4}
{37700}{}{Vic - Stage 5}
{37800}{}{Vic - Stage 6}
{37900}{}{Robôcerebro - Chimp}
{38000}{}{Robôcerebro - Abnormal}
{38100}{}{Robôcerebro - Human}
{38200}{}{Giant Ant}
{38300}{}{Tough Giant Ant}
{38400}{}{Pariah Dog}
{38500}{}{Zurak}
{38600}{}{Imbot}
{38700}{}{Jimmy}
{38800}{}{Wejungh}
{38900}{}{Herb}
{39000}{}{Loopal}
{39100}{}{Jobe}
{39200}{}{Smitty}
{39300}{}{Rube}
{39400}{}{Master Krall}
{39500}{}{Ziggy}
{39600}{}{Master Khung}
{39700}{}{John Bishop}
{39800}{}{Angela Bishop}
{39900}{}{Mrs. Bishop}
{40000}{}{Bishop's Guard 1}
{40100}{}{Bishop's Guard 2}
{40200}{}{Bishop's Thug 1}
{40300}{}{Bishop's Thug 2}
{40400}{}{Angry Brahmin}
{40500}{}{Lil' Jesus}
{40600}{}{Big Jesus}
{40700}{}{Mordino Men 1}
{40800}{}{Mordino Men 2}
{40900}{}{Mordino Men 3}
{41000}{}{Myron's Guard 1}
{41100}{}{Myron's Guard 2}
{41200}{}{Mr. Wright}
{41300}{}{Mrs. Wright}
{41400}{}{Chris Wright}
{41500}{}{Keith Wright}
{41600}{}{Wright Son 1}
{41700}{}{Wright Son 2}
{41800}{}{Wright Daughter 1}
{41900}{}{Wright Daughter 2}
{42000}{}{Mr. Salvatore}
{42100}{}{Mason}
{42200}{}{Salvatore Thug 1}
{42300}{}{Salvatore Thug 2}
{42400}{}{Generic Bartender 1}
{42500}{}{Generic Bartender 2}
{42600}{}{Generic Bartender 3}
{42700}{}{Boxer 1}
{42800}{}{Boxer 2}
{42900}{}{Boxer 3}
{43000}{}{Boxer 4}
{43100}{}{Mike the Masticator}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Stuart Little}
{43500}{}{Corsican Brothers}
{43600}{}{Corsican Bitches}
{43700}{}{Father Tully}
{43800}{}{Casino Bouncer 1}
{43900}{}{Casino Bouncer 2}
{44000}{}{Casino Girl}
{44100}{}{Drug Dealer/Pimp1}
{44200}{}{Drug Dealer/Pimp2}
{44300}{}{Drug Dealer/Pimp3}
{44400}{}{Drug Dealer/Pimp4}
{44500}{}{McGee}
{44600}{}{Miss Kitty}
{44700}{}{Generic Slut 1}
{44800}{}{Generic Slut 2}
{44900}{}{Jagged Jimmy J}
{45000}{}{Renesco}
{45100}{}{Scientist}
{45200}{}{Eldridge}
{45300}{}{Algernon}
{45400}{}{Jules}
{45500}{}{Bureaucrat 1}
{45600}{}{Bureaucrat 2}
{45700}{}{Trader 1}
{45800}{}{Trader 2}
{45900}{}{Guard 1}
{46000}{}{Guard 2}
{46100}{}{Guard 3}
{46200}{}{Guard 4}
{46300}{}{Soldier 1}
{46400}{}{Soldier 2}
{46500}{}{Soldier 3}
{46600}{}{Soldier 4}
{46700}{}{Sgt. Stark}
{46800}{}{"Doc" Andrew}
{46900}{}{Bartender}
{47000}{}{Gun Turret}
{47001}{}{This is an automated gun turret equipped with a Dual Plasma Cannon.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (stage 1)}
{47300}{}{K-9 (stage 2)}
{47400}{}{K-9 (stage 3)}
{47500}{}{K-9 (stage 4)}
{47600}{}{Generic Cyberdog}
{47700}{}{Wanamingo Egg}
{47800}{}{Lo Pan Guard}
{47900}{}{Marjorie}
{48000}{}{Auto-Cannon}
{48100}{}{Special Gecko Critter}
{48200}{}{Grim Reaper}
{48300}{}{Frank Horrigan}
{48301}{}{The President's Body Guard.}