#
#   Messages from skilldex.c
#
{100}{}{HABILIDADES}
{101}{}{CANCELAR}
{102}{}{ESQUIVAR}
{103}{}{TRANCAS}
{104}{}{ROUBAR}
{105}{}{ARMADILHAS}
{106}{}{P. SOC.}
{107}{}{MÉDICO}
{108}{}{CIÊNCIA}
{109}{}{REPARAR}