{100}{}{Você está vendo um jovem, homem forte e bonito.}
{101}{}{Você está vendo o Sr. Peterson.}

{200}{}{Olá, amigo. Ainda não te vi por aqui antes. É a primeira vez aqui em Abbey?}
{201}{}{Que bom te ver de novo. O que posso fazer por você?}
{202}{}{É. O que você pode me dizer sobre esse lugar?}
{203}{}{Eu estou em uma missão para encontrar o GECK. Você sabe alguma coisa a respeito?}
{204}{}{Irmão Samuel disse que você pode saber algo sobre quem está perturbando os túmulos. Ele disse que ouviu alguns
 barulhos estranhos vindos de suas colheitas.}
{205}{}{Não importa, eu preciso ir.}

{300}{}{A minha esposa e eu viemos aqui há alguns anos atrás em uma caravana. Nós gostamos daqui tanto que decidimos
 ficar e começar a nossa pequena fazenda. Deixe-me te dizer, o Abbey pode não ser tão chamativo como New Reno, ou tão avançada como Vault City, mas tanto
 quanto eu sei, este lugar é quase tão bom quanto que ganha em lugares desertos. As pessoas aqui são decentes, e as pessoas olham para
 fora como um outro. Claro, alguns lugares podem oferecer mais segurança, mas à custa da liberdade pessoal. Não, obrigado.}
{301}{}{Você veio em uma caravana? Será que eles vem sempre aqui?}
{302}{}{Not really. The Abbey's too small and isolated for the caravans to pay us much heed. Doesn't matter though, we're
 a pretty self sufficient community -- grow our own food, brew our own booze -- so we get by just fine. Anyway, Bill's the man
 to speak to about caravans, he runs the general store just southwest of here.}
{303}{}{Parece ótimo e tudo mais, mas eu realmente preciso ir.}
{304}{}{Interessante. Eu estava curioso sobre outra coisa.}
{305}{}{Não importa, eu preciso ir.}

{400}{}{O que mais você gostaria de saber?}
{401}{}{O que você pode me dizer sobre a Abbey?}
{402}{}{Você sabe alguma coisa sobre o Garden of Eden Creation Kit?}

{500}{}{Sorry pal, I've never heard of it. But if it has to do with pre-war times, then I bet there's something about it
 in the monastery's computers. Unfortunately for you, those monks are real protective of their information?afraid that it'll
 lead to another war or something if people learn too much. Still, it might be worth asking around there.}
{501}{}{Thanks, I'll go do that. I've got some more questions though.}
{502}{}{Thanks for the tip. I'll go check that out right now.}

{600}{}{Brother Samuel sent you here? What's that drunkard up to now?}
{601}{}{Tending to the graves as usual I suppose. So about what you heard...}
{602}{}{[John sits down in his chair and pours himself a shot of whiskey.] It all began a couple days ago. My wife and
 I were preparing for bed when we heard some rustling out in the field. I grabbed my lantern and rushed outside to see if
 I could find the source of the noise. As soon as I made it to the fields though, the noises had stopped.}
{603}{}{Go on.}
{604}{}{Look, I really must be going.}
{605}{}{Well, the next night we didn't hear a thing. But the night after that, we heard rustling coming from the field
 again. This time I crept to the window and looked out rather than rushing outside. Peering into the darkness, I saw a
 dim light, like from an old lantern or something, moving among the crops. After a couple minutes the light moved toward
 the cemetery.}
{606}{}{I wanted to go out and confront whoever?or whatever?it was, but the wife convinced me to stay inside and check
 on things in the morning. So the next morning, I see some of my crops had been eaten and there's fresh footprints all
 around. Now, I don't mind feeding the poor, but I don't take kindly to thieves.}
{6061}{}{After that, I asked Brother Samuel if anything had happened in the graveyard. That's when he told me someone
 had begun digging up some of the graves. Apparently, whoever's doing this isn't strong enough to dig in one night.
 I'd guess it's an old beggar hoping to dig up some treasure. If you ever find out who's doing this, please tell 'em to
 stop by. There's no need for thievery here in the Abbey and I'd be happy to help this person in any way I can.}
{607}{}{I'll try and catch this individual. Maybe I'll wait around midnight and see if I can find anything out. Well,
 thanks for the information. Take care.}
{608}{}{I'll see what I can do. I have some more questions before I go.}
{609}{}{This story is getting a little too long. Bye.}
{610}{}{Let me get this straight. You'd be happy to help someone that lurks around your house at night, steals your
 crops, and tries to rob your dead? I've met a lot of loonies in my day, but you just might take the cake. It's a marvel
 you've survived this long.}
{611}{}{[He narrows his eyes, but manages to hold his composure.] That's how we do things here at the Abbey. If kindness
 is so offensive to you, then I suggest you get the hell outta my house. I'm not gonna sit here and let some wandering
 tribal insult me in front of my wife.}
{612}{}{Alright, alright, I'm leaving.}
{613}{}{OK tough guy, now this "wandering tribal" is going to kill you in front of your wife. Then maybe I'll kill her too.
 Hell, maybe I'll kill everyone in this pathetic fucking place. You thought you could all hide from the horror of the wasteland?
 Well guess what, my naive friend? Horror has found you, and its name is }

{700}{}{Caia fora daqui.}

#added in RP 2.1
{710}{}{Que bom te ver de novo. Tom tem sido uma grande ajuda por aqui. Obrigado mais uma vez por ordenar tudo isso. Agora, o que eu posso fazer por você?}
 
