#################################################################
# Cachorro (Klamath)                                            #
# Traduzido por Ricardo Alvarenga                               #
#################################################################

#{100}{}{You see a large, mangy, buff colored dog with a feral look to it.}
#{101}{}{You see a dusty, yellowish-buff colored, dog.}

{100}{}{Você vê um grande cão sarnento de cor berge e aspecto selvagem.}
{101}{}{Você vê um empoeirado cão de cor berge.}

#{110}{}{Grrrrrr. Woof! Woof! Grrrrrr?.}
#{111}{}{Woof, Arf, Arf?}
#{112}{}{(Staring into dog's eyes) Grrrr! Arrrrrgh! Grrrrrrrr!}
#{113}{}{Hmm, I bet you sound angry because you want something.}
#{114}{}{You're just hungry, aren't you, boy? Let me see if I have some delicious drymeat to
# give you.}

{110}{}{Grrrrrr. Woof! Woof! Grrrrrr?.}
{111}{}{Woof, Arf, Arf?}
{112}{}{(Olhando nos olhos do cão) Grrrr! Arrrrrgh! Grrrrrrrr!}
{113}{}{Hmm, parece que está com raiva porque quer alguma coisa.}
{114}{}{Você está com fome não é rapaz? Deixe-me ver se eu tenho alguma carne seca para lhe dar.}

#{120}{}{Woof! (Dog leaps forward with teeth bared -? snatches jerky from your outstretched hand -? eats
# jerky noisily)}
#{121}{}{Woof! (The mongrel happily grabs the yummy drymeat, dropping a key that he must have had in his
# mouth -? you pick up the key.)}
#{122}{}{Mmm, jerky.}
#{123}{}{Ah, poor boy, you must have been hungry. (Patting dog on head)}

{120}{}{Woof! (Cão salta para a frente com a boca aberta e arranca a carne seca de sua mão estendida - come ruidosamente).}
{121}{}{Woof! (O vira-lata feliz agarra a deliciosa carne seca, deixando cair uma chave que ele deve ter tido em sua boca - Você pegar a chave.)}
{122}{}{Mmm, carne seca.}
{123}{}{Ah, pobre garotinho, você estava passado fome. (Acariciando o cão na cabeça)}

#{130}{}{Grrr. Woof! Woof!}
#{131}{}{Arf-arf doggy. Heh, heh.}
#{132}{}{Bye, doggy.}
#{133}{}{Sorry, no doggy treats for you today.}
#{134}{}{Shoo! Get out of here, you damn mutt.}

{130}{}{Grrr. Woof! Woof!}
{131}{}{Arf-arf totó. Heh, heh.}
{132}{}{Tchau totó.}
{133}{}{Sinto muito, não tenho tempo para os cachorros.}
{134}{}{Shoo! Saia daqui seu maltido vira-lata!}

#{140}{}{Woof, woof. Woof-woof!}
#{141}{}{Woof, woof? Eru?}
#{142}{}{Good doggy, good boy.}
#{143}{}{You're hungry, aren't you, boy? I bet you'd like some delicious drymeat, wouldn't you?
# Let's see if I have some. }

{140}{}{Woof, woof. Woof-woof!}
{141}{}{Woof, woof? Eru?}
{142}{}{Bom cachorro, bom garto.}
{143}{}{Você está com fome, não é, rapaz? Aposto que você gostaria um pouco de carne seca, não é? Vamos ver se eu tenho alguma aqui comigo.}

#{200}{}{Woof! (pant, pant, pant -- Slurp!)}
#{201}{}{Woof-woof!}
#{202}{}{Arf!}
#{203}{}{Arf, arf, arf!}
#{204}{}{(Stares at you lovingly)}
#{205}{}{Woof!}

{200}{}{Woof! (pant, pant, pant -- Slurp!)}
{201}{}{Woof-woof!}
{202}{}{Arf!}
{203}{}{Arf, arf, arf!}
{204}{}{(Olha pra você com amor)}
{205}{}{Woof!}
