#You see a grave marker.
{100}{}{Você vê uma lápide.}
#The grave marker reads: 
{101}{}{Está escrito na lápide: }
#"Here lies Brother Gregory. A man who knew no limits."
{102}{}{"Aqui jaz Istrupa. Morreu tentanto traduzir este jogo.}
#"Aunt Patty. Good riddance indeed."
{103}{}{"Tia Patty. Certamente já vai tarde."}
#"Here lies Per Joner. Died one rock too short."
{104}{}{"Aqui jaz Per Joner. Morreu faltando uma pedra."}
#"Here lies Father Michael. Founder, Father, Fighter."
{105}{}{"Aqui jaz Padre Michael. Fundador, pai, lutador."}
#"An Atheist. All dressed up and no place to go."
{106}{}{"Um ateu. Tão bem vestido e sem nenhum lugar para ir.}
#"Here lies Johnny Yeast. Pardon me for not rising."
{107}{}{"Aqui jaz Johnny Yeast. Perdoe-me por não me levantar."}
#"Mary Jane. Loving wife and mother."
{108}{}{"Mary Jane. Amada esposa e mãe."}
#"'Checkmate!' was the call to dear old Jon, On the chessboard of life, He was just a pawn.
{109}{}{"'Cheque-mate!' foi o chamado para o velho e querido Jon, no tabuleiro da vida foi apenas o peão."}
#"Sir John Strange, here lies an honest lawyer, and that is Strange."
{110}{}{"Senhor John Strange, aqui jaz um advogado honesto, e isso é estranho."}
#"Tears cannot restore her -- therefore I weep."
{111}{}{"Lágrimas não a trarão de volta -- por isso eu choro."}
#"Every day in every way, I am getting better and better."
{112}{}{"Todo dia de todo modo, eu estou ficando melhor e melhor."}

#There are no markings on this grave marker.
{250}{}{Não há nada escrito nessa lápide.}
#The grave marker is too cracked and broken to be read.
{251}{}{A lápide está muito rachada e quebrada para ler.}
#The name on the grave marker reads John Doe.
{252}{}{O nome na lápide é John Doe.}
#The name and date on this headstone have been worn off by the weather.
{253}{}{O nome e a data nessa pedra tumular foram apagados pelo tempo.}
