#You see a grave marker.
{100}{}{Você vê uma lápide.}
#Here lies the great Per: Author, walkthrough creator, rock hoarder. Alas, he died one rock too short. Last words:
 "Just one more steal check and I'll have all the rocks in th-."
{101}{}{Aqui jaz o grande Noob-Saibot: autor, criador de walkthrough, colecionador de pedras. Morreu faltando uma pedra. Últimas palavras: "Só mais uma checagem de roubo e eu terei todas as pedras do mu-.}
