{100}{}{Você vê um monge de meia idade.}
{101}{}{Você vê o irmão Mathew?.}
{102}{}{Ele está de pé em um palco pregando para os cidadãos de Abbey.}
{200}{}{Boas pessoas de Abbey. Tem um momento para ouvir? Pois tenho muito a dizer.}

#new speech for RP 1.3
{201}{}{Aqui nós coletamos as relíquias sagradas de um longo tempo passado.}
{202}{}{Chamuscada pela Flame Deluge, no escuro, que foram lançados.} #Scorched by the Flame Deluge, into the dark, we were cast.
{203}{}{Faremos a Memorabilia, para preservar a sabedoria da idade.}
{204}{}{Devemos guardar e cuidar dele, embora a chama ficou congelada;}
{205}{}{Poderia acender mais uma vez, a sabedoria deve ser mal utilizada.}
{206}{}{Assim, ninguém pode saber, por medo de outro Flame Deluge.}
{207}{}{Mas um dia, os homens devem subir acima de seu desejo de destruição.}
{208}{}{E a Memorabilia vai estar lá, esperando reintrodução.}
#So we tend to our holy task, lest all that wisdom, we lose.
{209}{}{Então, nós temos a sagrada tarefa, preservar toda a sabedoria que nós perdemos.}
{210}{}{Nós temos que preservar e proteger, mas nunca a usaremos.}
{211}{}{Então vá agora meus amigos, e deixe o seu espírito se levantar;}
{212}{}{Para os guardiões do conhecimento,cada um, foi presenteado.}
{213}{}{Agora, por favor, tome um tempo e reflita sobre o que eu disse.}
{224}{}{Agora, por favor, tome um tempo e reflita sobre o que eu disse.}
{300}{}{Saudações, amigo. Eu não acho que eu já vi por aqui antes.É irmão Matthew e eu ajudo
 espalhar a palavra sobre a importância de preservar o conhecimento dos antigos.}
{301}{}{É bom conhecer você Matt. Meu nome é... }
{302}{}{ e estou em uma missão para o sagrado GECK.}
{303}{}{Desculpe, eu tenho que ir.}

{400}{}{A GECK, hein? Eu me lembro de ler algo sobre isso durante uma das minhas sessões de transcrição. Por isso, deve
 estar em nosso banco de dados, mas estou com medo de acesso de nossos computadores é restrito. No entanto, se você falar com o Abade, é
 possível que ele vai lhe conceder acesso. Ele não poderia machucar para tentar, de qualquer maneira. Ah, e sinta-se livre para navegar através de nossa coleção
 de santas relíquias pré-guerra. Eu lhe pediria para não danificar nada, mas eu tenho medo de tudo já está quebrado além do reparo.}
{401}{}{Acho que só pode.Embora eu tenho algumas perguntas.}
{402}{}{Obrigado. Eu acho que vou fazer isso agora.}

{500}{}{Estou ao seu serviço. O que você gostaria de saber?}
{501}{}{O que você pode dizer sobre esse lugar?}
{502}{}{Você parece ser muito poético em sua pregação. Qual é a razão para isto?}
{503}{}{Não importa, cuide disso.}

{600}{}{A Abbey é a casa de qualquer pessoa, desde que não causem problemas. Nós somos uma comunidade independente e raramente recebem
 visitantes, como a si mesmo. A maioria das pessoas que você vê aqui são descendentes dos fundadores originais que se estabeleceram em
 este antigo mosteiro,não muito tempo depois da grande Flame Deluge.}
{601}{}{Vá em frente.}
{602}{}{O silêncio de qualidade, pacífica deste lugar fez-se uma casa
 atraente para outros viajantes que vagaram aqui ao longo dos anos,
 buscando fugir do caos escuro dos resíduos.
 Naturalmente, o valor real deste lugar reside na sua vasta biblioteca.
 Ela está cheia de velhos tempos, com a estranha sabedoria de uma era perdida.
 Ao longo do tempo, temos vindo a fantasia nos guardiões e guardiãs de que a sabedoria.}
{603}{}{Muito interessante. Outra pergunta?.}
{604}{}{Interessante. Bem, eu preciso ir.}

{700}{}{[O homem ri na sua pergunta] Não, nenhuma razão particular.Eu li muita poesia em toda a minha vida
 e eu gosto de aplicá-lo aos meus ensinamentos. Ele ajuda a deixar um impacto maior sobre os ouvintes.}
{701}{}{Justo. Outra pergunta?.}

{800}{}{É bom te ver novamente }
{801}{}{O que posso fazer para você?}
{802}{}{Eu tenho umas perguntas.}
{803}{}{Nada. Vejo você por aí.}
