#You see a merchant.
{100}{}{Você vê um comerciante.}
#He seems to be assisting the man who is fixing the pump.
{101}{}{Parece que ele está ajudando o homem que está concertando a bomba.}
#This is taking longer than we thought.
{102}{}{Isso está demorando mais do que pensávamos.}
#Check with the boss if you think you can help.
{103}{}{Fale com o chefe se achar que pode ajudar.}
#Great job with fixing the pump.
{104}{}{Bom trabalho concertando a bomba.}
#Thanks again for your help.
{105}{}{Obrigado novamente pela ajuda.}
