{100}{}{Você está vendo um jovem, homem forte e bonito.}
{101}{}{Você está vendo o Sr. Peterson.}

{200}{}{Olá, amigo. Ainda não te vi por aqui antes. É a primeira vez aqui em Abbey?}
{201}{}{Que bom te ver de novo. O que posso fazer por você?}
{202}{}{É. O que você pode me dizer sobre esse lugar?}
{203}{}{Eu estou em uma missão para encontrar o GECK. Você sabe alguma coisa a respeito?}
{204}{}{Irmão Samuel disse que você pode saber algo sobre quem está perturbando os túmulos. Ele disse que ouviu alguns 
barulhos estranhos vindos de suas colheitas.}
{205}{}{Não importa, eu preciso ir.}

{300}{}{A minha esposa e eu viemos aqui há alguns anos atrás em uma caravana. Nós gostamos daqui tanto que decidimos
 ficar e começar a nossa pequena fazenda. Deixa eu te dizer, o Abbey pode não ser tão chamativo como New Reno, ou tão avançada como Vault City, mas tanto
 quanto eu sei, este lugar é quase tão bom quanto que ganha em lugares desertos. As pessoas aqui são decentes, e as pessoas olham para
 fora como um outro. Claro, alguns lugares podem oferecer mais segurança, mas à custa da liberdade pessoal. Não, obrigado.}
{301}{}{Você veio em uma caravana? Será que eles vem sempre aqui?}
{302}{}{Não é verdade. O Abbey é muito pequeno e isolado para as caravanas nos prestarem atenção. Não importa, porém,
 somos uma comunidade bastante auto-suficiente - aumentar a nossa própria comida, preparar a nossa própria bebida - então estamos bem.
 De qualquer forma, Bill é o homem que pode falar sobre as caravanas, ele percorre no armazém geral daqui, a sudoeste.}
{303}{}{Parece ótimo e tudo mais, mas eu realmente preciso ir.}
{304}{}{Interessante. Eu estava curioso sobre outra coisa.}
{305}{}{Não importa, eu preciso ir.}

{400}{}{O que mais você gostaria de saber?}
{401}{}{O que você pode me dizer sobre a Abbey?}
{402}{}{Você sabe alguma coisa sobre o Garden of Eden Creation Kit?}

{500}{}{Desculpe amigo, eu nunca ouvi falar. Mas se isso tem algo a ver com a época da pré-guerra, então aposto que há algo sobre
 eles em computadores no mosteiro. Infelizmente para você, esses monges são proteções reais de suas informações? Com medo de que
 ele vai levar a uma guerra ou algo assim, se as pessoas aprendem muito. Ainda assim, pode valer a pena perguntar lá perto.}
{501}{}{Obrigado, eu vou fazer isso. Eu tenho mais algumas perguntas antes de ir embora.}
{502}{}{Obrigado pela dica. Eu vou verificar isso agora.}

{600}{}{Irmão Samuel te mandou aqui? O que é isso bêbado até agora?}
{601}{}{Cuidando das sepulturas, como sempre, suponho eu. Então sobre o que você ouviu...}
#[John se senta em sua cadeira e derrama-se uma dose de uísque.] It all began a couple days ago. My wife and
# I were preparing for bed when we heard some rustling out in the field. I grabbed my lantern and rushed outside to see if
# I could find the source of the noise. As soon as I made it to the fields though, the noises had stopped.
{602}{}{[John se senta em sua cadeira e derrama-se uma dose de uísque.] Tudo começou alguns dias atrás. Minha esposa e
 eu estávamos nos preparando para dormir quando nós escutamos barulhos no campo. Eu peguei minha lanterna e corri para fora para ver se
 eu conseguia achar a origem do barulho. Entretanto, quando pisei no campo, os barulhos pararam.}
{603}{}{Vá em frente.}
{604}{}{Olha, eu realmente preciso ir.}

#Well, the next night we didn't hear a thing. But the night after that, we heard rustling coming from the field
# again. This time I crept to the window and looked out rather than rushing outside. Peering into the darkness, I saw a
# dim light, like from an old lantern or something, moving among the crops. After a couple minutes the light moved toward
# the cemetery.
{605}{}{Bem, na noite seguinte não ouvimos nada. Mas na noite depois daquela, nós ouvimos barulhos vindos do campo
 novamente. Dessa vez eu rastejei até a janela e olhei para fora ao invés de ir para fora. Espreitando na escuridão, eu vi uma 
 luz sombria, como o de uma velha lanterna ou algo assim, andando no meio da plantação. Depois de alguns minutos a luz foi em direção
 ao cemitério.}
 
#I wanted to go out and confront whoever?or whatever?it was, but the wife convinced me to stay inside and check
# on things in the morning. So the next morning, I see some of my crops had been eaten and there's fresh footprints all
# around. Now, I don't mind feeding the poor, but I don't take kindly to thieves.
{606}{}{Eu quis ir para fora e confrontar seja quem for?ou o que for?, mas minha esposa me convenceu a ficar dentro de casa e checar
 as coisas de manhã. Então na manhã seguinte, eu vi que algumas partes da minha colheita tinham sido comidas e que tinham pegadas frescas
 por perto. Oras, eu não me importo em alimentar os pobres, mas eu não pego leve com ladrões.}
 
#After that, I asked Brother Samuel if anything had happened in the graveyard. That's when he told me someone
# had begun digging up some of the graves. Apparently, whoever's doing this isn't strong enough to dig in one night.
# I'd guess it's an old beggar hoping to dig up some treasure. If you ever find out who's doing this, please tell 'em to
# stop by. There's no need for thievery here in the Abbey and I'd be happy to help this person in any way I can.
{6061}{}{Depois disso, eu perguntei ao Irmão Samuel se alguma coisa aconteceu no cemitério. Foi quando ele me disse que alguém
 começou a cavar algumas covas. Aparentemente, seja quem for que esteja fazendo isso não tem força suficiente para cavar em uma noite.
 Eu acho que é um velho mendigo cavando para achar algum tesouro. Se você achar quem está fazendo isso, fale para ele para
 passar aqui. Não tem necessidade de roubo aqui no Monastério e eu ficaria feliz de ajudar essa pessoa no que eu puder.}
 
#I'll try and catch this individual. Maybe I'll wait around midnight and see if I can find anything out. Well,
# thanks for the information. Take care.
{607}{}{Eu vou tentar capturar esse indivíduo. Talvez eu espere até por volta da meia noite e ver se eu consigo achar alguma coisa. Bem,
 obrigado pela informação. Tome cuidado.}
 
{608}{}{Vou ver o que posso fazer. Tenho mais algumas perguntas antes de eu ir.}
{609}{}{Esta história está ficando chata demais. tchau.}
{610}{}{Deixe-me ver se entendi. Você ficaria feliz em ajudar alguém que se esconde em sua casa à noite, rouba
 suas colheitas, e tenta roubar até os mortos? Eu conheci um monte de malucos no meu dia, mas você só pode levar o bolo.
 É uma maravilha que você tenha sobrevivido tanto tempo.}
{611}{}{[Ele aperta os olhos, mas consegue manter a compostura.] É assim que fazemos as coisas aqui no Abbey. Se a bondade
 é tão ofensiva para você, então eu sugiro que você dar o fora da minha casa. Eu não vou sentar aqui e deixar um pouco de
 insulto tribal vagando me na frente da minha esposa.}
{612}{}{Tudo bem, tudo bem, eu vou embora.}

#OK tough guy, now this "wandering tribal" is going to kill you in front of your wife. Then maybe I'll kill her too.
# Hell, maybe I'll kill everyone in this pathetic fucking place. You thought you could all hide from the horror of the wasteland?
# Well guess what, my naive friend? Horror has found you, and its name is
{613}{}{Tudo bem valentão, agora esse "nômade tribal" vai matar você na frente da sua esposa. Daí talvez mate ela também.
 Diabos, talvez eu mate todo mundo nesse maldito lugar patético. Vocês pensaram que poderiam se esconder do terror do deserto?
 Bem adivinhe, meu amigo ingênuo? O terror te achou, e seu nome é}

{700}{}{Caia fora daqui.}

#added in RP 2.1
{710}{}{Que bom te ver de novo. Tom tem sido uma grande ajuda por aqui. Obrigado mais uma vez por ordenar tudo isso.
 Agora, o que eu posso fazer por você?}