{100}{}{Você está vendo uma bomba d'água.}
{101}{}{Você está vendo uma bomba d'água realmente velha que parece está quebrada.}
{102}{}{A bomba d'água está funcionando bem agora.}
{103}{}{Você vai precisar de mais do que apenas com as suas mãos para corrigir esta máquina. Talvez algumas ferramentas iria ajudar com a parte desta instalação.}
{104}{}{Você reparou a bomba d'água.}
{105}{}{Você falhou em reparar a bomba.}
#You find out what is wrong with the water pump.
{106}{}{Você descobre o que está errado com a bomba de água.}
{200}{}{Você abre a máquina para olhar dentro dela. Você está vendo um monte de engrenagens e motores enferrujados. Um dos motores tem uma rachadura.}
{201}{}{Chame isso de dia.}
{202}{}{Investigue mais.}
{203}{}{Após uma inspeção mais de perto você verá que a rachadura não é a causa do problema, mas sim a conexão por onde os fios vão. Os conectores parecem ter queimado ao longo dos anos. Ele vai demorar ter um motor totalmente novo, bem como um novo conjunto de fios para que esta máquina trabalhe novamente.}
{204}{}{Sair.}