{100}{}{Você vê o guardião do cemitério do mosteiro.}
{101}{}{Você está vendo o irmão Samuel, o guardião do cemitério.}
{102}{}{Ele parece bêbado e um pouco sonolento.}

{200}{}{*soluço* Olá, meu nome é Samuel. O que, uh, *soluço* o traz aqui?}
{201}{}{*soluço* Olá novamente.}
#I'm just looking around. Do you tend to this graveyard?
{202}{}{Só estou dando uma olhada. É você que cuida desse cemitério?}
{203}{}{Você conhece um padre Tully?}
#Yeah...I *hickup* 'member Tully.
 How's that fella doin anyway? I 'aven't seen him since he was kicked out of 'ere long time *hiccup* long time ago.
 [He grins drunkenly as he reflects.] Boy he was a hoot. Him and me together, *hickup* what a combo.
{204}{}{Padre Tully, você diz? [Ele parece estar quebrando seu cérebro tentando lembrar.] É...eu *soluço* lembro do Tully.
 Como que aquele cara tá? Nçao vejo ele desde que foi expulso a um tempão.
 [Ele sorri bêbado enquanto reflete.] Cara, ele era uma piada. Ele e eu juntos, *soluço* que combinação.}
#He lives in New Reno now, preachin' the good word, er, something like that. You know, you two seem a lot alike.
{205}{}{Ele mora em New Reno agora, pregando a boa palavra, ou algo assim. Sabe, vocês dois são bem parecidos.}
#New Reno, huh? [He leans on his shovel, pulls out a small flask and takes a big swig.] I 'member him sayin he'd
 *hickup* be headin that way. I'm glad he made it there safely. I always *hickup* liked that fella. A real hoot. If you
 see him again, tell him Ol' Sammy is still alive an' kickin.
{206}{}{New Reno, huh? [Ele se apoia em sua pá, pega um pequeno frasco e dá um grande gole.] Eu mi lembro dele dizendo que
 *soluço* tava indo para lá. Fico feliz que ele chegou a salvo. Eu sempre *soluço* gostei daquele cara. Uma verdadeira piada. Se você ver
 ele novamente, diga que o velho Sammy ainda está vivo e pronto para ação.}
#I'll do that. I got some other questions though.
{207}{}{Farei isso. No entanto, tenho outras perguntas}
#I'll do that. Take care Sam.
{208}{}{Farei isso. Se cuida, Sam.}
#Nevermind. Sorry to bother you.
{209}{}{Esquece. Desculpa te incomodar.}
#Actually I was just going to say that he sends his greetings. I'll be sure to tell him you say hello as well. I got some other questions though.
{210}{}{Na verdade eu só ia dizer que ele manda saudações. Me certificarei de dizer a ele que você mandou as suas também. No entanto, tenho outras perguntas.}
#Actually I was just going to say that he sends his greetings. I'll be sure to tell him you say hello as well. Take care Sam.
{211}{}{Na verdade eu só ia dizer que ele manda saudações. Me certificarei de dizer a ele que você mandou as suas também. Se cuida, Sam}


#What do you *hickup* wanna know?
{300}{}{O que você *soluço* quer saber}
#Are you the gravekeeper?
{301}{}{Você é o coveiro?} #Você é o coveiro aqui?
#What can you tell me about the Abbey?
{302}{}{O que você pode me dizer sobre Abbey}
#Anything I can help you with?
{303}{}{Algo com que eu possa te ajudar?}


#Yes, *hickup* I tend to these 'ere graves. Nobody else wants to *hickup* do it, so Ol' Sammy got th' job. It's
 not as bad as one might think. It's got its? perks, if you know what I mean. [He grins sloppily and wiggles his bushy
 eyebrows at you.
{400}{}{Sim, *soluço* eu cuido desses túmulos. Não tem mais ninguém que queira *soluço* fazer isso, então o Velho Sammy tem que fazer o trampo.
 Não é tão ruim quanto você pode pensar. Tem suas? vantagens, se é que me entende. [Ele sorri de forma descuidada e levanta suas grossas sombrancelhas pra você.}
 
#new in RP 1.3

#No. I don't know what you mean, and I never want to. Bye.
#No. I don't know what you mean. But I think I'd rather ask you something else. 
#No. I don't know what you mean, but I'm morbidly curious...
#Hell yeah I do. Nothing turns me on like a rotten cadaver.

{401}{}{Não. Eu não te entendo, e nem quero entender. Tchau.}
{402}{}{Não. Eu não te entendo. Mas acho que prefiro te perguntar outra coisa.}
{403}{}{Não. Eu não te entendo, mas estou morbidamente curioso...}
{404}{}{É claro que eu te entendo. Nada me excita mais que um cádaver apodrecendo.}
 
#Why, I get to be outdoors, and no one's 'round to tell Ol' Sammy when he's had enough. I *know* when I've
 'ad enough... when 'ere's none left! [He cackles, which quickly turns into a hideous cough. After coughing up a lung
 or two, he smiles at you.
{410}{}{Por que, eu posso estar ao ar livre, e não tem ninguém por aí pra dizer que já chega para o Velho Sammy. Eu *sei que já chega...
 quando não tem ninguém sobrando! [Ele dá uma gargalhada, que rapidamente se transforma em uma tosse horrível. Depois de tossir um pulmão ou dois,
 ele sorri para você.}
#Oh, of *course* that's what you meant. [Sigh of relief.] Let me ask you something else, though.
{411}{}{Oh, é *claro* que era isso que você queria dizer. [Suspiro de alívio]. Deixe eu te perguntar outra coisa, no entanto.}

#[His eyes go wide with shock and he seems to instantly sober.] That's not what I meant, you...you MONSTER! FIEND!
 Get away from me!
{420}{}{[Seus olhos ficam arregalados por causa do choque ele parece ficar imediatamente.} Não foi isso que eu quis dizer, seu... seu MONSTRO! DEMÔNIO!
#Whatever, you drunk old fuck. You don't know what you're missing
{421}{}{Que seja, seu velho bêbado do caralho. Você não sabe o que está perdendo.}

#Foul demon! Be gone!
{430}{}{Dêmonio imundo! Saía já daqui!}

#Tell me about abbey
#The Abbey, well, this place *hickup* has been my 'ome fer most of my life. Everone 'ere *hickup* is nice, and
 anyone's welcome, long as they *hickup* don't cause trouble. I, myself, don't spend too much time in th'
 mona-*hickup*-monastery, but I know our 'puters have all kinds of info that's been collected over th' years. Maybe
 some of it *hickup* might be of some use to you.
{500}{}{O Abbey, bem, esse lugar tem sido meu lar pela maio parte da minha vida. Todo mundo lá *soluço* é legal, e qualquer um é bem vindo,
 com tanto que *soluço* não causem problemas. Eu mesmo não fico muito tempo no mona-*soluço*-monastário, mas sei que nosso 'putadores tem todos tipos de inforamações que foram coletadas ao longo dos anos. Talvez
 algumas deles *soluço* possam ser tem algum uso pra você.}
#You don't spend much time in the church? You are a monk, aren't you?
{501}{}{Você não passa muito tempo na igreja? Você é um monge, não é?}
#[He grins, revealing a gap filled set of rotten teeth.] Well, *hickup* let's just say that th' other monks don't
 take *hickup* too kindly to my, uh, drinking habits.
{502}{}{[Ele sorri, mostrando uma fileira de dentes podres.] Bem, *soluço* vamos apneas dizer que os outros mongeis não gostam *soluço* muito dos meu, uh, consumo de bebidas.}
#Makes sense I guess. I got some more questions.
{503}{}{Faz sentido eu acho. Tenho mais algumas perguntas.}
#I guess so. See you around Sammy.
{504}{}{Acho que sim. Te vejo por aí Sammy.}
#I see. Look I must be going.
{505}{}{Olha, eu tenho que ir.}

#Need any help
#Hmm... *hickup* lemme...lemme tink a minute. Yeah, I might got somethin, if yer up to it.
{600}{}{Hmm... *soluço* deix...deixa eu pensa um pouco. Sim, posso ter alguma coisa, se você estiver afim.}
#Uh, nevermind Sam. I must be going now.
{601}{}{Uh, deixa pra lá Sam. Eu tenho que ir agora.}
#Sure Sam, what do you need?
{602}{}{Claro Sam, do que você precisa.}
#Well, th' past coupla days I've *hickup* noticed some of these graves are bein dug up. Now, whoever's doin this
 don't appear to be gettin that far, but it's a *hickup* a pain fer me to fill 'em back up.
{603}{}{Bem, há algus dias atrás eu *soluço* percebbi que algum desses túmulos estão sendu cavados. Agora, quem quer que esteja fazendo isso
não parece estar indo muito jongo, mas é *hickup* uma merda para mim encher eles de nov.}
#Hmm, well did you try and figure out who has been doing this?
{604}{}{Hmm, bem, você tentou descobrir quem está fazendo isso?}
#Sure *hickup* I tried. One night I stayed around till midnight or so and no one showed up. I must've fallen asleep
 soon afterwards. Too much drinking I s'pose. [He grins, pulls out his flask and takes a hefty swig.] So, what do you
 *hickup* say? You wanna help out?
{605}{}{Claro *soluço* que eu tentei*. Uma noite eu fiquei de olho até a meia-noite e ninguém apareceu. Eu devo ter dormindo pouco depois disso. Muita bebida euacho. [Ele sorri, pega o seu frasco e da um grande gole.] Então, o que me
 diz? Vai ajudar?}
#Alright, I'll see what I can do. Do you know anything else that might help me?
{606}{}{Certo, vou ver o que posso fazer. Tem mais algo com que eu possa ajudar?}
#Well, now that you mention it, I do *hickup* 'member Mr. Peterson sayin something about hearing some noises comin
 from his field. He might know something about this. He and that pretty little wife a his live right over there.
 [He points to the building south of the graveyard.]
{607}{}{Bom, agora que você mencionou, eu mi lembro *soluço* do Sr. Peterson falando algo sobre ouvir barulhos vindu do campo dele. Ele talvez saiba algo sobre isso.
 Ele e sua linda esposa moram por ali. [Ele aponta para o prédio ao sul do cemitério]}
#I'll see what I can do.
{608}{}{Verei o que posso fazer}
#I think I'll pass. I must be going.
{609}{}{Acho que vou passar. Tenho que ir.}

#I took care of the grave digging situation. You shouldn't have any more problems out here.
{700}{}{[Eu vou cuidar do problema dos túmulos sendo cavados. Você não deve ter outros problemas por aqui.}
#Well, that's *hickup* good news. Glad I won't be falling into any more open *hickup* graves. Thanks fer th' help.
{701}{}{Bom, isso *soluço* é ótimo. Fico feliz que não vou mais cair em mais nenhuma cova *soluço* aberta. Obrigado pela juda}
#Glad to help. I got some questions though.
{702}{}{Fico feliz em ajudar. Tenho algumas perguntas, no entanto.}
#Well, take care then.
{703}{}{Bom, se cuida então.}
#I don't think open graves are the real reason you're falling down Samuel, but you take it easy now.
{704}{}{Eu não acho que as covas abertas são o real motivo de você estar caindo Samuel, é melhor você se cuidar.}

#*Whistle*
{1000}{}{Assobio}
{1001}{}{*Cough* *Cough*}
#*Clears throat*
{1002}{Limpa a garganta}{**}
#Cough
{1003}{}{*Cough*}
#Sigh
{1004}{Suspiro}{*Sigh*}
{1005}{}{*soluço*}

#It's been a *hickup* long day. Come back in th' morning.
{2000}{Tem sido um *soluço* longo dia. Volte pela manhã.}