#You see a hunched over old man
{100}{}{você vê um velho debruçado .}
#The decrepit old man reeks of sweat and possibly urine. He's garbed in tattered, muddy rags, and is carrying a shovel
{101}{}{O velho decrépito cheira a suor e possivelmente urina. Ele está vestindo farrapos, trapos enlameados, e está levando uma pá.}
#You see Tom
{102}{}{Você vê Tom.}

#[The old man jolts with surprise when he sees you approach.] Uh, look, I really must be going...
{200}{}{[O velho se sacode com surpresa quando vê você se aproximando.] Uh, olha, eu realmente tenho que ir...}
#Now you hold on a minute. [You grab the man by the arm as he begins to walk away.] Who are you, and what are you
# doing here at this hour?
{201}{}{Agora espere um minuto. [Você pega o homem pelo braço quando ele começa a se afastar.] quem é você, e o que você está
 fazendo aqui a essa hora?}
#What? Why, uh...the name's Tom and can't an old man enjoy a nightly stroll anymore without getting asked a bunch of
# questions?
{202}{}{Que? porque, uh...o nome é Tom e um homem velho não pode disfrutar de um passeio noturno sem ser feito um monte de perguntas?}
#Not when he's slinking around like a thief and carrying a shovel.
{203}{}{Não quando ele está se esgueirando por aí como um ladrão e carregando uma pá.}
#Alright fine, but why are you carrying a shovel?
{204}{}{tudo bem, mas porque você está carregando uma pá?}
#Whatever, I'm out of here
{205}{}{seja como for, eu já estou caindo fora daqui.}
#Nevermind. Sorry to bother you
{206}{}{Deixa pra lá. Desculpe incomodá-lo.}
#You mean this ol' thing? [He glances down at the rusty shovel in his hands.] Well, uh, you never know when you
# might find something that needs digging up. Always be prepared I say.
{207}{}{O que está fazendo com essa coisa velha? [ele olha para baixo, para a pá enferrujada em sua mãos .] bem, uh, nunca se sabe quando você encontra alguma que precisa desenterrar. sempre esteja preparado digo.}
#Find something, eh? You mean like something in a grave?
{208}{}{Encontra alguma coisa, eh? quer dizer, como algo em uma cova?}
#That's a good motto indeed. Well, take care
{209}{}{Isso é um bom lema de fato. bem, tome cuidado.}
#(Tom's eyes widen) I'm not quite sure what you, uh, mean
{210}{}{(Os olhos de Tom arregalaram) Eu não tenho certeza do que você, uh, quero dizer.}
#Tom, you're in a graveyard, you've got mud all over you, and it's past midnight. Why, even Torr could draw a
# conclusion from this. It's time to start giving me some answers, Tom. Why are you digging up these graves?
{211}{}{Tom, você está em um cemitério, tem lama em cima de você, e já é meia noite. por que, até mesmo Torr poderia tirar uma
 conclusão disso. é hora de começar a me dar algumas respostas. Tom, por que você está desenterrando esses túmulos?}
#[He puts down the shovel and sighs.] Alright, I'll tell you. My body ain't what it used to be. I've got no job,
# and no real means to get food. I know grave diggin ain't something that folks smile upon, but it's been a way for me to
# bring in some money. I'm just trying to survive...I don't mean no harm
{212}{}{[Ele abaixa a pá e suspira.] certo, eu vou te dizer. Meu corpo não é o que costumava ser. Eu não tenho nenhum trabalho,
 e sem meios reais para conseguir comida. eu sei que escavar túmulos não é uma coisa que faça agente sorrir, mas tem sido uma maneira para eu conseguir algum dinheiro. Eu estou apenas tentando sobreviver... Eu não quero causar nenhum mal.}
#I don't think that digging graves is a good thing for a man in your condition. Tell you what. You just mosey on
# out of here and we'll forget that this conversation ever happened. I never want to see your face again though, Okay?
{213}{}{Eu não acho que cavar sepulturas é uma boa coisa para um homem na sua condição. vou lhe dizer. você sai daqui de fininho e vamos esquecer que essa conversa aconteceu. eu nunca mais quero ver seu rosto novamente, ok?}
#[The old man looks like he's about to protest, then stops.] Alright, you win. You've seen the last of poor old Tom.
# [He picks up his shovel and shuffles away.]
{214}{}{[O velho parece que está prestes a protestar, depois pára.] certo, você venceu. é a ultima vez que você vê o pobre Tom.
 [Ele pega a pá e joga longe.]}
#On second thought, maybe it would be better for the world if I kill you
{215}{}{Pensando bem, talvez seja melhor para o mundo se eu matar você.}
#Goodbye Tom
{216}{}{Tchau Tom.}
#I heard you've also been stealing crops from the farmer here.
{217}{}{Ouvi dizer que você também roubou a plantação do agricultor.}
#[The old man fidgets uncomfortably.] I couldn't help it! I was just so hungry and the food looked so good. Please,
# I don't mean any trouble. Look, I'll just go away and you won't see me here again. I promise!
{218}{}{[O velho agita desconfortavelmente.] eu não podia ajuda-lo! eu estava com tanta fome e a comida era tão boa. por favor,
 eu não queria causar nenhum problema. Olha, eu vou embora e você não vai me ver aqui de novo. Eu prometo!}
#Alright, get going then. Before I change my mind.
{219}{}{Tudo bem, vá então, antes que eu mude de idéia.}
#Wait, no need for any of that. The Petersons own the farm here and they're extremely nice people. Mr. Peterson
# even offered to talk with whoever was taking his crops and come to a reasonable agreement. Go talk with him.
# I'm sure he can help you out somehow.
{220}{}{Espere, não há necessidade disso. os Petersons são os donos da fazenda , e são pessoas extremamente agradáveis. Sr. Peterson
 ele até se ofereceu para conversar com quem estava roubando as suas plantações e chegar a um acordo razoável. vá falar com ele.
 Tenho certeza que ele pode ajudá-lo de alguma forma.}
#(The old man's eyes light up.) That doesn't sound like a bad idea at all. Hey, thanks. Maybe this world aint as
# cruel as I thought it was.
{221}{}{(Os olhos do velho brilharam.) Isso não soa como uma má ideia ao todo. ei, obrigado. Talvez este mundo não é tão cruel como eu pensei que era.}
#You take care then, Tom. I'll check with you later and see how things are going.
{222}{}{toma cuidado então, Tom. Vou falar com você mais tarde e ver como as coisas estão indo.}
#I sure hope that Peterson fella is as friendly as you say he is.
{223}{}{eu espero que esse Peterson seja um cara amigável  como você diz.}
#You see Tom. He's wearing new worker's clothing and whistling cheerfully.
{300}{}{você vê Tom. ele está usando sua nova roupa de trabalhador e está assobiando alegremente.}
#Hey there! Wow, you were right. That Mr. Peterson is one kindly fella. He forgave me for what I did and even
# offered me a job helping out in the field. He says once I pay off the food I've taken, then I'll start making a
# weekly salary. Thanks again for your trouble.
{301}{}{EI! uau, você estava certo. esse Mr.Peterson é um cara gentil. ele me perdoou pelo oque eu fiz e me ofereceu um emprego para ajudar no campo.ele disseque que primeiro eu tenho que pagar a comida que eu roubei, então eu vou
 começar a fazer um salário semanal.obrigado novamente pelos seus esforços.}
#You're welcome, Tom. You take care of yourself now
{302}{}{de nada, Tom. cuide-se de si mesmo agora.}
#Alright I wi- Oh, wait a second. I want to give you something for helping an old fella like me out. I found this
# lighter on some lad I dug up a couple weeks ago. I have no use for it and hopefully you might.
{303}{}{certo eu wi- Oh, espere um segundo. eu quero te dar-lhe algo para ajudar um cara velho como eu . Eu encontrei esse
 isqueiro em algum rapaz que desenterrei duas semanas atrás. Eu não tenho nenhum uso para ele e espero que você tenha.} #Correto podem traduzir isqueiro!
#Thanks, Tom. I'm sure this'll come in handy. See you around.
{304}{}{Obrigado, Tom. Eu tenho certeza que eles vão vir a calhar. vejo você por aí.}
#The old man nods and goes back to what he was doing.
{305}{}{(O velho acena e volta a fazer o que estava fazendo.)}
#[END]
{306}{}{[FIM]}

#Hello again. Thanks for everything!
{307}{}{Olá novamente .obrigado por tudo!}
#*Whistle*
{308}{}{*Assobio*}

#You youngins never learn. You aint the boss of me. I think I'll just kill you instead.
{400}{}{Vocês jovens nunca aprendem. você não é meu chefe. Acho que vou matar você.}

#Listen, I've dug up my share of graves too. I'm a bit of a kleptomaniac. What's your reason?
{450}{}{Ouça, Eu desenterrei minha parte das sepulturas também. Eu sou um pouco cleptomaníaco. qual é a sua justificação?}
#I'm not unfamiliar to grave digging, Tom. Every man has his own enjoyment. Now you be on your way.
{451}{}{Tom, eu não estou familiarizado com a escavação de túmulos. Todo homem tem seu próprio divertimento. Agora siga seu caminho.}

#You figure out who is digging up the graves and set Tom towards a new life.
{1000}{}{Você descobriu quem estava escavando os túmulos e definiu uma nova vida para Tom.}
#You figure out who is digging up the graves.
{1001}{}{Você descobriu quem estava escavando os túmulos.}
#I'm going. No need to rush an old man.
{1002}{}{Eu estou indo. Não há necessidade de apressar um velho.}
#You see Tom. He's got a smile on his face and he's wearing new worker's clothing.
{1003}{}{Você vê Tom. Ele tem um sorriso no rosto e está vestindo sua nova roupa de trabalhador.}
#He seems to be in much better condition and he smiles when you approach.
{1004}{}{Ele parece estar em uma condição muito melhor e ele sorri quando você se aproxima.}
