# You see the Abbot, the spiritual leader of the Abbey.
{100}{}{Você vê o Abbot, o líder espiritual da Abbey.}

# There's something about this monk that leads you to believe he's rather important.
{101}{}{Tem alguma coisa nesse monge que o faz acreditar que ele é importante.}

# Welcome traveler.
{200}{}{Seja bem vindo, peregrino.}

# Peace to you.
{201}{}{Esteja em paz.}

# We are the guardians of knowledge.
{202}{}{Nós somos os guardiões da conhecimento.}

# I'm sorry, but knowledge of our books is of no use to you.
{203}{}{Eu sinto muito, mas a conhecimento em nossos livros não tem utilidade para você.}

# How can I help you?
{3000}{}{Em que posso ajudá-lo?}

# Welcome to the Abbey, traveler. How can I help you?
{300}{}{Bem vindo à Abbey, peregrino. Em que posso ajudá-lo?}

# What can you tell me about your order?
{301}{}{O que pode me contar sobre sua ordem?}

# Have you ever heard of a device called a GECK?
{302}{}{Você já ouviu falar de um dispositivo chamado GECK?}

# Do you know where I could find Vault 13?
{303}{}{Você sabe como eu posso chegar na Vault 13?}

# Bye.
{304}{}{Adeus.}

# What do you want to know?
{400}{}{O que você quer saber?}

# Okay. I'd like to know something else.
{401}{}{Ok. Eu gostaria de saber sobre outra coisa.}

# Hmm….that *does* sound familiar. Why, yes, I recall Brother Thomas mentioning something about that recently. I'm sorry, but I don't recall exactly what he said.
{402}{}{Hmm... . Isso me soa familiar. Oh, claro, eu me lembro do Brother Thomas mencionar algo sobre isso recentemente. Me desculpe, mas não lembro exatamente o
 que ele disse.}
 
# That's fine. Just point me to Brother Thomas and I'll go ask him.
{403}{}{Tudo bem. Apenas me leve ao Brother Thomas e eu pergunto para ele.}

# I don't know anything about that.
{404}{}{Não sei nada sobre isso.}

# Well, thanks anyway.
{405}{}{Bem, obrigado mesmo assim.}

# I'm afraid I won't be able to do that. You see, I am under the impression that Brother Thomas is no longer among
 the living. But, fortunately for you, he was one of our most reliable transcribers. I'm sure whatever articles he came
 across concerning the information you seek has been transcribed into our computers.
{406}{}{Temo que não posso fazer isso. Sabe, tenho a impressão de que Brother Thomas não está mais entre os vivos.
 Mas, por sorte, ele era um de nossos mais ávidos transcritores. Tenho certeza que qualquer artigo que ele encontrou 
  sobre a informação que você procura foi transcrita em nossos computadores.}
  
# Wait a second, you're "under the impression" that Brother Thomas is dead? Where I come from, death is a pretty clear cut thing. So, is he dead, or isn't he?
{407}{}{Espera aí, você "tem a impressão" de que Brother Thomas morreu? De onde eu vim, a morte é uma coisa bem clara. Afinal, ele morreu ou não?}

# Brother Thomas has been missing for several days, ever since he went down to the caverns below the Abbey. [He sighs wearily.]
 You see, some of the Abbey's residents claimed to have seen a huge beast lurking down there, and Brother Thomas was quite skeptical.
 He took it upon himself to go dispel these rumors, yet, as it turns out, his disappearance has only further validated them.
{408}{}{Brother Thomas desapareceu há muitos dias, desde que desceu até as cavernas no subsolo da Abbey. [Ele suspira pesarosamente.]
  Sabe, alguns residentes da Abbey disseram ter visto uma fera enorme se escondendo lá embaixo, mas Brother Thomas não acreditou neles.
  Então decidiu ele mesmo acabar com esses boatos, mas, ao que parece, seu desaparecimento serviu para confirmá-los.}

# So no one else has even bothered to go down there and check on him? What if he's simply trapped down there somehow, and he's slowly starving to death?
{4091}{}{E ninguém mais se preocupou de descer lá para procurar por ele? E se ele estiver apenas preso lá embaixo, e está lentamente morrendo de fome?}

# I suppose that's possible, but you must understand. We are a peaceful people. The thought of going up against one of those wasteland monsters is terrifying to us. We're simply not equipped for such confrontations. 
{4092}{}{Suponho que é plausível, mas você precisa entender. Nós somos pacíficos. A ideia de lutar contra um desses monstros do deserto é aterrorizante para nós. Nós não estamos equipados para esse tipo de confronto.}
 
# Hmmm. Maybe I should take a look what's down there. *I AM* the chosen one after all...
{409}{}{Hmmm. Talvez eu possa dar uma olhada lá embaixo. Eu *SOU* o escolhido afinal...}

# I'm adventurous. I can take a look.
{410}{}{Eu sou aventureiro. Vou dar uma olhada.}

# Very interesting. I have to go now.
{1411}{}{Fascinante. Eu tenho que ir agora.}

# You'd really do that? Perhaps while you're down there, you could look for a certain book. You see, it was last
 known to be in Brother Thomas's possession, and it's very important to us, as it was passed down by our founders.
 If you could retrieve that book, I would be most grateful. In fact, I'd grant you full access to our computers, so you
 can look for whatever you desire.
{411}{}{Você realmente faria isso? Talvez, enquanto estiver lá embaixo, poderia procurar um certo livro. Sabe, da última 
 vez que foi visto estava com Brother Thomas, e é muito importante para nós, pois foi passado para nós por nossos fundadores.
 Se puder trazer este livro, eu ficaria muito grato. De fato, eu lhe daria acesso irrestrito aos nossos computadores, então
 você poderia procurar pelo que quisesse.}
 
# It's a deal. I'll be back soon.
{412}{}{Fechou. Eu volto já.}

# Maybe, let me think about this some more...
{413}{}{Talvez, deixe eu pensar um pouco...}

# Thank you. Please let me know if you find the book.
{414}{}{Obrigado. Me avise se encontrar o livro.

# Ok, bye.
{415}{}{Ok, adeus.}

# Hello, my friend.
{416}{}{Olá, meu amigo.}

# I've killed your beast, and I've got your book.
{417}{}{Eu matei sua fera, e achei seu livro.}

# I've killed the beast.
{4177}{}{Eu matei a fera.}

# Excellent! Let me have it!
{418}{}{Excelente! Me dê!}

# Excellent! And how about the book; were you able to recover it?
{4188}{}{Excelente! Mas e o livro; conseguiu recuperá-lo?}

# Here you go.
{419}{}{Aqui está.}

# Not so fast. How much is it worth to you?
{420}{}{Não tão rápido. Quanto isso vale pra você?}

# [He takes the book from you and caresses its cover as if to sooth it.] You have done us a great service. You now
 have full access to our computers in the library. Tell Brother Paul I grant you permission to access our files.
{421}{}{[Ele pega o livro e o acaricia como se estivesse tentando protegê-lo.] Você nos fez um grande serviço. Terá
 agora acesso a todos os computadores da livraria. Diga a Brother Paul que eu dei permissão para acessar nossos arquivos.}
 
# Thank you.
{422}{}{Obrigado.}

# You want money for it? Fine, here's $250. Go see Brother Paul for access to the computers.
{423}{}{Você quer dinheiro por ele? Ótimo, aqui estão $250. Vá até Brother Paul para acessar os computadores.}

# Thanks for the money, bye.
{424}{}{Obrigado pelo dinheiro, adeus.}

# You should look on a second floor computer, now that you have full access there.
{425}{}{Você deveria procurar em um computador no segundo andar, agora que tem acesso.}

# Ok, bye.
{426}{}{Ok, obrigado.}

# What is the purpose of your order?
{430}{}{Qual é o propósito de sua ordem?}

# What is the history behind the Abbey?
{431}{}{Qual é a história por trás da Abbey?}

# Hmm, I don't have any questions at the moment.
{432}{}{Eu não tenho nenhuma pergunta no momento.}

# Our holy mission is to read, copy and take care of our sacred books of knowledge and other relics of the lost age.
 It is our hope that with this knowledge we are able to create a Memorabilia that might one day help humanity emerge from
 its self-imposed Dark Age. Any information that we come across is recorded, lest it be lost like so much was in the
 great Flame Deluge.
{433}{}{Nossa missão sagrada é ler, copiar e cuidar dos livros sagrados de conhecimento e outras relíquias da era perdida.
 Nós esperamos que com esse conhecimento possamos criar a Memorabilia que um dia ajudará a humanidade a emergir da Idade 
 Negra à qual ela mesma se impôs. Toda informação que encontramos é guardada, para que não seja perdida como tudo que 
  foi consumido no grande Flame Deluge.} 
  
# After the Great War, the guiding hands of fate directed our ancestors to this old Abbey in the mountains. Due to
 its remote location, the monastery survived the Flame Deluge mostly unscathed. As our ancestors explored the building,
 they discovered an extensive library of books. And not just religious texts, oh no, this library contained the gamut of
 written works, from literary classics, to scientific encyclopedias.
{434}{}{Depois da Great War, as mãos do destino guiaram nossos ancestrais para essa velha Abbey nas montanhas. Devido
 à sua localização remota, o mosteiro sobreviveu ao grande Flame Deluge ileso. Quando nossos ancestrais exploraram 
 o prédio, eles descobriram uma vasta livraria. E não eram apenas textos religiosos, não, esta livraria continha uma gama 
 imensa de obras arquivadas, de clássicos da literatura, até enciclopédias científicas.}
 
# What happened then?
{435}{}{O que aconteceu depois?}

# I've heard enough.
{436}{}{Já ouvi o suficiente.}

# They soon realized the true treasure trove of wisdom stored within those books—especially the scientific tomes.
 Here were the chronicles of a fallen civilization. A lost age. There were a few who thought it might be best to
 destroy this knowledge, for fear that it would once again guide humanity towards apocalypse. But it was eventually
 decided that they would instead dedicate themselves to ensuring the preservation of the books, to be released when,
 and if, the world was ready for it.
{437}{}{Eles logo perceberam que o verdadeiro tesouro era a sabedoria contida nos livros - especialmente os tomos científicos.
 Aqui estavam as crônicas da civilização caida. A era perdida. Houveram uns poucos que acharam melhor destruir este 
 conhecimento, por medo de que isso levasse a humanidade ao apocalipse. Mas eventualmente foi decidido que ao invés disso
 eles se dedicariam a preservar esses livros, para serem liberados quando, e se, o mundo estivesse pronto para eles.}
 
# (More)
{438}{}{(Mais)}

# And so, utilizing a small printing press, they began making copies of the books, and also transcribing them
 into the Abbey's computers to preserve them digitally, should the physical books ever be destroyed. Over the long years,
 others have come across the Abbey, and some have elected to stay and live out their lives in the tranquil quiet of our mountain home.
{439}{}{E então, usando uma pequena impressora, eles começaram a copiar os livros, e também transcrevê-los nos computadores 
 da Abbey para preservá-los digitalmente, caso os livros físicos fossem destruídos. Ao longo dos anos, outros chegaram até a 
 Abbey, e se voluntariaram para ficar e viver no sossêgo de nossas montanhas.}
 
# Thanks for the story.
{440}{}{Obrigado pela história.}

# Where did your ancestors come from?
{441}{}{De onde vieram seus ancestrais?}

# They never told where they originally came from. We suspect that they came here originally from the east.
{442}{}{Eles nunca me disseram de onde vieram. Nós suspeitamos que eles chegaram do leste.}

# Well, thanks for the story.
{443}{}{Bem, obrigado pela história.}

# Do you need any help here at the monastery?
{444}{}{Você precisa de alguma ajuda aqui no mosteiro?}

# I found out what's wrong with your water pump.
{445}{}{Eu descobri o que há de errado com o encanamento.}

# Do you know anything about the original founders?
{446}{}{Você sabe algo sobre os fundadores?}

# I do not know all the names of our founders, but the most important one I am aware of is Miller.
 Before the Great War he was an electrical engineer working for the United States government. Shortly thereafter,
 he converted to Catholicism and made an oath with himself that we would spend the rest of his life preserving the
 knowledge of the past. His greatest fear was that this knowledge would be lost forever and thus needed to be preserved
 so that future generations may benefit.
{447}{}{ Eu não sei o nome de todos os fundadores, mas o mais importante que eu conheço é Miller.
 Antes da Great War, ele foi um engenheiro elétrico que trabalhava para o governo dos Estados Unidos. Logo após,
 ele se converteu ao Catolicismo e fez um juramento de que passaria o resto de sua vida preservando o conhecimento do
 passado. Seu maior medo era de que o conhecimento seria perdido para sempre, e portanto deveria ser preservado para o 
 bem das gerações futuras.}
 
# You must be quite knowledgeable having read so much.
{448}{}{Você deve ser bem culto, por ter lindo tanto.}

# I have indeed read much in my life. Yet you might be disappointed at the limitations of my knowledge. You see,
 we record and preserve. We are forbidden to act upon the wisdom of these books, therefore our understanding of the text is quite limited.
{449}{}{Eu realmente li muito em minha vida. Ainda assim, você ficaria desapontado com as limitações de meu conhecimento.
 Sabe, nós guardamos e preservamos. Somos proibidos de agir de acordo com a sabedoria contida nos livros, portanto nosso entendimento 
 dos textos é muito limitado.}
 
# Wait, you're telling me that you just blindly transcribe these books without even trying to comprehend them?
{450}{}{Espere, você está me dizendo que apenas transcreve esses livros cegamente, sem ao menos tentar entedê-los?}

# As I've said, it is our job to preserve this knowledge, not to understand it. Before this knowledge can be
 returned to mankind, he must first prove to have risen above his tendency of mass genocide. That's the only way to
 ensure that history does not repeat itself.
{451}{}{Como eu disse, nosso trabalho é preservar o conhecimento, não entendê-lo. Antes do conhecimento poder voltar
 para a humanidade, ele primeiro precisa provar que esta acima da tendência do genocídio.}
 
# Well, I've got news for you: that day's never going to come. And while you're hoarding all this knowledge in your
 little mountain paradise here, people out in the wasteland are struggling every day to survive. In fact, my entire tribe
 is on the brink of destruction. The knowledge contained in these books could help cure diseases, improve crops, and greatly
 increase the chance of humanity's survival.
{452}{}{Bem, eu tenho uma novidade para você: esse dia nunca vai chegar. E enquanto você está aqui acumulando todo esse 
 conhecimento em seu paraíso nas montanhas, pessoas no deserto estão lutando para sobreviver. Na verdade, toda minha tribo
 está à beira da destruição. O conhecimento contido nesses livros poderia ajudar a curar doenças, melhorar as plantações e 
 aumentar as chances de sobrevivência da humanidade.}

#new in RP 1.3

# Ah, well I suppose you make a good point. But it just seems like the information stored here could help out a lot
 of people. Even if you don't think the world's ready for this knowledge, I don't see why *you* can't at least try to learn from it.
 Otherwise, what's the point of keeping it?
{453}{}{Oh, é um bom argumento. Mas me parece que a informação guardada aqui pode ajudar muitas pessoas. Mesmo que você
 ache que o mundo não esta pronto para esse conhecimento, eu não entendo porque *vocês* não podem tentar aprender com os livros.
 Afinal, qual é o propósito de apenas guardar?}
 
# I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years...that would be blasphemous against our faith. No, I feel we must continue
 to live by the rules set by our ancestors.
{454}{}{Eu entendo sua frustação com nossos métodos, mas você precisa entender que é assim que as coisas sempre foram 
 para nós. Mudar essas coisas agora, após tantos anos... seria blasfêmia contra nossa fé. Não, eu sinto que devemos continuar 
 vivendo de acordo com as regras de nossos ancestrais.}

# I understand your frustration with our ways, but you must understand that this is the way things have always been
 for us. To alter things now, after so many years...that would be blasphemous against our faith. Still, I shall consider
 your words. I sense great wisdom in you, wanderer. It is a pity I have met very few like you.
{455}{}{Eu entendo sua frustação com nossos métodos, mas você precisa entender que é assim que as coisas sempre foram 
 para nós. Mudar essas coisas agora, após tantos anos... seria blasfêmia contra nossa fé. Entretanto, eu vou considerar
 suas palavras. Eu sinto uma grande sabedoria em você, andarilho. É uma pena que encontrei tão poucos como você.}
 
# Thanks. I'd like to know something else though.
{456}{}{Valeu. Eu gostaria de saber sobre outra coisa.}

# Very well. I'd like to know something else though.
{457}{}{Bem. Eu gostaria de saber sobre outra coisa.}

# Stop that!
{500}{}{Pare!}

# You gain 200 experience points for bringing back the book.
{501}{}{Você ganhou 200 pontos de experiência por trazer o livro de volta.}

# I fixed your broken waterpump.
{600}{}{Eu consertei seu encanamento.}

# That is great news, indeed. That waterpump had been acting up for quite some time. Those merchants said they
 could take care of it, but they didn't seem to be making much progress. It's a good thing you came along. Thank you again.
{601}{}{Que boas notícias. Esse encanamento estava com problemas faz tempo. Aqueles vendedores disseram que 
 podiam cuidar dele, mas não parecem ter feito muito progresso. Que bom que você veio. Obrigado de novo.}
 
# I expect some money for this you know. Now cough it up!
{602}{}{Eu espero uma grana por isso, tá ligado. Passa pra cá!}

# If you truly want to show your gratitude, how about some money for my trouble?
{6020}{}{Se você realmente quer mostrar sua gratidão, que tal uma grana pelo meu trabalho?}

#new in RP 1.3

# No problem. I have some other questions though.
{603}{}{De nada. Eu tenho outras perguntas.}

# I'm glad to be of assistance. Take care.
{604}{}{Fico feliz por ajudar. Se cuida.}

# [Frowns.] I see. Fine, here, take these coins. Now go, and stop bothering me.
{605}{}{[Franze o cenho] Entendo. Ótimo, aqui, fique com essas moedas. Agora vá, e pare de me perturbar.}

# Thank you, *father*.
{606}{}{Obrigado, *padre*.}

# Uhh...no I seem to have misplaced it.
{700}{}{Uhh...não, acho que perdi.}

# What!? [He sighs deeply.] It is most unfortunate that you were unable to recover that book. But you say you've
 killed the beast? Hm, then it should be safe to send our own people down to continue searching for it. Anyway, for your
 service, I shall grant you access to our computers. Go see Brother Paul for the access key.
{701}{}{Quê!? [Ele suspira profundamente.] É uma pena que não conseguiu recuperar o livro. Mas você disse que matou
 a fera? Hm, deve ser seguro enviar nossa gente para continuar a busca. De qualquer forma, pelo serviço prestado, 
  eu lhe darei acesso aos computadores. Vá ver Brother Paul para pegar a chave de acesso.}
  
# Thank you.
{702}{}{Obrigado.)

# Actually, yes. Our main water pump has been acting up for some time, and now it finally seems to have broken down
 completely. If you know anything about machinery, do you think you could take a look and see if something could be done?
 There are a few merchants already working on it. I fear that little progress has been made though.
{800}{}{Na verdade, sim. Nosso encanamento principal tem dado problema há um tempo, e agora parece que finalmente quebrou
 de vez. Se você souber alguma coisa sobre mecânica, você acha que poderia dar uma olhada para ver se algo pode ser feito?
 Tem uns vendedores que estão trabalhando no conserto. Eu temo que eles não fizeram muito progresso.}
 
# I'm happy to help. I'll report back on the progress.
{801}{}{Fico feliz em ajudar. Trarei notícias sobre o progresso.}
 
# Sure, I'll be glad to help...for a price of course.
{802}{}{Claro, ficarei feliz em ajudar... por um certo preço.}

# Actually on second thought, let me ask you something else.
{803}{}{Pensando bem, deixa eu perguntar outra coisa.}

# What!? Oh, fine. If that's the kind of person you are, then you shall receive payment for your service. Here's
 25 coins to begin with.  Please let me know if something can be done. [The man sighs as he hands you the coins]
{804}{}{Quê!? Ok, certo. Se é esse tipo de pessoa que você é, então receberá pagamento pelos seus serviços. Aqui 
 estão 25 moedas para começar. Por favor, me avise se algo puder ser feito. [O homem suspira quando lhe entrega as moedas]}
 
# Hey, no need for the sighing. You think everything in life comes for free? Now, let me get to work.
{805}{}{Ei, não precisa bufar. Você acha que tudo na vida cai do céu? Agora, me deixe trabalhar.} 

# Really? Please, do tell.
{806}{}{Sério? Por favor, me conte mais.}

# The motor gave out and fried all the connectors. I'm going to Vault City to get a new part.
{807}{}{O motor morreu e queimou todos os conectores. Eu vou na Vault City buscar uma peça nova.}

# Oh thank you. You are indeed a great help. Please report back once you install the new part.
{808}{}{Oh, obrigado. Você realmente nos ajudou muito. Por favor me avise quando instalar a nova peça.}

# I will. Be back soon.
{809}{}{Eu voltarei.}

# You explain to the Abbot that while the information they hold could lead to mankind's annihilation, it could also lead to mankind's salvation.
{900}{}{Você explica para o Abbot que mesmo a informação que eles guardam sendo capaz de aniquilar a humanidade, ela poderia também ser a salvação.}

# You learn about the original founder of the Abbey.
{901}{}{Você leu a respeito do fundador da Abbey.}

#dumb dialgoue

# I killie scary monster down in cave.
{1000}{}{Eu mati monstro assustador na caverna.}

# Really? That's great. That is very brave of you. You're a big boy.
{1010}{}{Sério? Que bom. Foi muita coragem da sua parte. Você é um bom garoto.}

# Really? That's great. That is very brave of you. You're a big girl.
{1011}{}{Sério? Que bom. Foi muita coragem da sua parte. Você é uma boa garota.}

# (smile) I know.
{1012}{}{(sorri) Eu sei.}

# Did you happen to find a book lying there? A friend of mine had it, and he went missing.
{1020}{}{Por acaso você encontrou um livro por lá? Um amigo meu era o dono, mas ele desapareceu.}

# I find book. Here, it heavy and no pitchers inside.
{1021}{}{Eu ter achado livro. Aqui, pesado e sem figuras dentro.}

# I no find book. Sorree. I go look now.
{1022}{}{Eu não achar livro. Dicupa. Eu ir procurar.}

# I find book.
{1030}{}{Eu achar livro.}

# That's great. Thanks. You're one special guy.
{1031}{}{Ótimo. Obrigado. Você é um rapaz especial.}

# That's great. Thanks. You're one special gal.
{1032}{}{Ótimo. Obrigado. Você é uma mocinha especial.}

# YAY.
{1033}{}{EBA.}

#additional dialogue for killing the beast and not having the quest yet

# I was down there earlier. I saw a few dead bodies, so I'm guessing one of them belonged to your missing monk. If
# it makes you feel any better, I killed the thing responsible for his death.
{1100}{}{Eu já estive lá embaixo. Encontrei alguns corpos, então acho que um deles pertencia ao seu monge desaparecido.
 Se isso fizer você se sentir melhor, eu matei a coisa responsável pela morte dele.}

# Ah...so it's as I feared. Brother Thomas shall be dearly missed. You have my thanks for ridding us of whatever
 wasteland beasts lurked down there. However, I... I don't suppose you found a book while you were down there. It's a very
 important book that was last known to be in Brother Thomas's possession.
{1110}{}{Ah... é como eu temia. Brother Thomas fará muita falta. Você tem meu agradecimento por nos livrar de seja 
 lá que tipo de fera se escondia no subsolo. Entretanto, eu... eu suponho que não tenha encontrado um livro enquanto estava lá.
 É um livro muito importante que foi visto pela última vez com Bother Thomas.}
 
# No, but I suppose I could go back and check.
{1111}{}{Não, mas acho que posso voltar lá e procurar.}

# Do you mean this book?
{1112}{}{Você está falando deste livro?}

# Before I go, let me ask you something else.
{1113}{}{Antes de eu ir, me deixe perguntar outra coisa.}
