# You see a short man carrying a book in his hands.
{100}{}{Você vê um homem baixinho segurando um livro.}

# You see Doc Jones, the doctor.
{101}{}{Você vê Doc Jones, o doutor.}

# You see a short man with a book called "So, You Want to be a Doctor."
{102}{}{Você vê um homem baixinho com um livro chamado "Então Você Quer Ser Doutor."}

# Hello, I'm Doc Jones. You can call me Doc. What can I help you with?
{103}{}{Olá, eu sou Doc Jones. Mas pode me chamar de Doc. Em que posso ajudar?}

# Got owie. You fix?
{104}{}{Fiz dodói. Faz sarar?}

# Feel icky. You fix?
{105}{}{Sinto ruim. Faz sarar?}

# Me gimp, you fix?
{106}{}{Mim quebrado. Você conserta?}

# Got questions. Okay?
{107}{}{Mim ter perguntas. Ok?}

# Sorry, me go.
{108}{}{Desculpa, mim ir.}

# I'm injured. Can you help me?
{109}{}{Eu estou ferido. Pode me ajudar?}

# I feel ill. Can you help me?
{110}{}{Me sinto doente. Pode me ajudar?}

# I'm crippled. Can you help me?
{111}{}{Estou coxo. Pode me ajudar?}

# I wanted to ask you some questions.
{112}{}{Eu quero fazer umas perguntas.}

# Just saying hello.
{113}{}{Apenas visitando.}

# Why, certainly. Here, we'll give you a shot of this -- this'll sting a bit -- now a bandage,
 and there, you're all set.
{114}{}{Certamente. Tome um pouco disso -- isso vai doer um pouco -- agora uma atadura, e pronto.}

# Me thank. Bye.
{115}{}{Mim agradece. Tchau.}

# Thanks, Doc. I feel much better.
{116}{}{Obrigado, Doc. Me sinto bem melhor.}

# Why, certainly. Here, you'll need to drink this -- all of it, I know it tastes foul. Now, just
 lie down on the bed over there, and I'll wake you in the morning.
{117}{}{Certamente. Aqui, beba isso -- beba tudo, eu sei que é horrível. Agora deite-se, eu te acordo
 amanhã de manhã.}
 
# Me feel good. Bye.
{118}{}{Mim sentir bem. Tchau.}

# Thanks Doc, that did the trick.
{119}{}{Valeu Doc, me sinto novo em folha.}

# I'm sorry, but I don't have the proper facilities to perform surgery. I'd suggest you go to one
 of the bigger cities and see a surgeon. Try Vault City. It's north of here.
{120}{}{Sinto muito, mas não tenho instalações apropriadas para realizar uma cirurgia. Eu sugiro que 
 você vá para uma das cidades grandes em busca de um cirurgião. Tente Vault City. Fica ao norte daqui.}
 
# Okay. Bye
{121}{}{Ok. Adeus.}

# All right. Thanks anyway.
{122}{}{Entendi. Obrigado pela dica.}

# What would you like to know?
{123}{}{O que você gostaria de saber?}

# You work Darion?
{124}{}{Você trabalhar com Darion?}

# You leave here when want?
{125}{}{Você sair quando querer?}

# What you know about Darion?
{126}{}{O que você sabe sobre o Darion?}

# How you be here?
{127}{}{Como veio parar aqui?}

# You say Darion got doggie?
{128}{}{Você dizer que Darion tem cãozinho?}

# Me go now.
{129}{}{Mim ir agora.}

# Do you work for Darion?
{130}{}{Você trabalha para o Darion?}

# Can you leave here if you want?
{131}{}{Você pode sair daqui quando quiser?}

# What can you tell me about Darion?
{132}{}{O que pode me dizer sobre o Darion?}

# How did you come to be here in the first place?
{133}{}{Como você veio parar aqui?}

# You mentioned Darion has a dog?
{134}{}{Você disse que Darion tem um cachorro?}

# Thanks for the information. I'll be heading out now.
{135}{}{Obrigado pela informação. Eu tenho que ir agora.}

# Well, yes and no. It's not by choice. I'm a prisoner here. Darion is getting up there in years
 and he needs a dedicated physician to look after him. The Khans keep me here for his needs. I'd rather
 be here for the people in the town above. They have no medical help at all, and there is a lot I can
 do to aid them.
{136}{}{Bem, sim e não. Não é por escolha. Sou um prisioneiro aqui. Darion precisa de um médico dedicado
 para cuidar dele. Os Khans me mantém aqui para todas as necessidades dele. Eu preferia cuidar das pessoas
 que vivem na cidade, lá em cima. Eles não tem qualquer ajuda médica, eu poderia fazer muito por eles.}
 
# Okay. Need know more.
{137}{}{Ok. Mim querer saber mais.}

# Thanks. Bye.
{138}{}{Valeu. Flw.}

# That's very commendable of you.
{139}{}{Isso é louvável da sua parte.}

# I see. I'll be going now.
{140}{}{Entendo. Eu preciso ir agora.}

# They're squatters! Let 'em die. Get on with your life.
{141}{}{Eles são um bando de fodidos! Deixe-os morrer. A vida continua.}

# No, I'm pretty much trapped here. I can't even leave to refill my medical supplies. Darion
 sends out for anything I need.
{142}{}{Não, eu estou preso aqui. Eu não posso nem buscar suplimentos medicos. Darion me manda
 tudo que eu preciso.}
 
# Me got it. Go now.
{143}{}{Mim entender. Ir agora.}

# Need ask more.
{144}{}{Precisar perguntar mais.}

# I guess you just aren't a trustworthy enough person to be allowed freedom.
{145}{}{Acho que você não é uma pessoa confiável o bastante para deixarem livre.}

# All right. I'm sorry, but I have to get going.
{146}{}{Ok. Sinto muito, mas tenho que ir.}

# I'm sorry to hear that.
{147}{}{Sinto muito por você.}

# Darion is a mental case, plain and simple. He's got more spooks in his head than his dog has
 fleas. As far as I can figure it, he was a member of another gang called the Khans. They kidnapped
 this girl, Tandi, and held her for ransom. Her father didn't take kindly to that, and hired some merc
 to get her back. Darion was the only one to come out alive.
{148}{}{O Darion é maluco, simples assim. Ele tem menos cabeça que o cachorro pulguento dele. Tudo o que 
 eu sei, é que ele era membro de uma gangue chamada Khans. Eles sequestraram uma garota, Tandi, e pediram 
 resgate. O pai dela não gostou da ideia e contratou um mercenário para resgatá-la. Darion foi o único sobrevivente.}
 
# Uh... what you said.
{149}{}{Uh... o que você disse.}

# Got go now.
{150}{}{Ter que ir agora.}

# Uh-huh. Well, I'll be leaving now.
{151}{}{Uhum. Bem, tenho que ir agora.}

# Wow; I'm impressed with your knowledge.
{152}{}{Uau; Seu conhecimento é impressionante.}

# Sounds like my kind of guy.
{153}{}{Parece meu tipo de cara.}

# I was kidnapped. I was traveling from Vault City to New Reno for a well-deserved vacation. Went
 to bed one night and woke up bound and gagged the next morning. A week or so later, I was here. Been
 here ever since.
{154}{}{Eu fui sequestrado. Eu estava viajando de Vault City até New Reno para umas férias merecidas. Fui
 dormir uma noite e acordei amarrado e amordaçado na manhã seguinte. Mais ou menos uma semana depois, eu 
 vim parar aqui. E nunca mais sai.}
 
# Ugh.
{155}{}{Ugh.}

# Thanks. Me be leave now.
{156}{}{Valeu. Mim estar indo agora.}

# The weak are often the prey of the strong.
{157}{}{Os fracos sempre são presas dos mais fortes.}

# I'm sorry to hear that.
{158}{}{Sinto muito por você.}

# Interesting, but I need to get going.
{159}{}{Interessante, mas eu preciso ir.}

# Yeah, he's got a dog. Personally, I think it's the meanest, most vile creature on the face of
 the earth. It seems to love Darion, though, so I guess it can't be all that bad.
{160}{}{Sim, ele tem um cachorro. Pessoalmente, eu acho que ele é a criatura mais maligna e cruel
 da face da Terra. Apesar disso, ele parece amar o Darion, então não deve ser de todo mal.}
 
# Me ask more.
{161}{}{Mim perguntar mais.}

# Uh, bye.
{162}{}{Uh, adeus.}

# I see. Well, thanks for the warning.
{163}{}{Entendo. Bem, obrigado pelo aviso.}

# Ah. Well, I've got to go.
{164}{}{Ah. Bem, tenho que ir.}

# I'll not help someone like you. Go away.
{165}{}{Eu não vou ajudar alguém como você. Vá embora.}

# Okay, well, you take care, and come back if you need anything.
{166}{}{Okay, se cuida, e volte se precisar de alguma coisa.}

# Done.
{167}{}{Pronto.}

# Now he's paranoid. He believes that Tandi is out to get him. He's obsessed with revenge, and he
 wants Tandi dead. He's riddled with guilt 'cause he hid and lived, rather than dying with his
 gang... and the list goes on and on.
{168}{}{Agora ele esta ficando paranóico. Ele acha que a Tandi está vindo atrás dele. Ele está obcecado
 com vingança, e ele quer matá-la. Ele esta perturbado pela culpa de ter se escondido e sobreviver, 
 ao invés de morrer com o resto da gangue... e não para por aí.}

#added by killap - RP Project 
# Darion is dead.
{200}{}{Darion está morto.}

# Dar-e-on dead.
{201}{}{Dar-e-on morrido.}

# He is!? Oh, this is wonderful news.
{202}{}{Morto? É bom demais para ser verdade.}

# What are you going to do now?
{203}{}{O que você vai fazer agora?}

# What yoo do?
{204}{}{Que cê vai faze?}

# Well, I see no reason to return to my old life. The town above us doesn't have any medical assistance, so I think
 I will go up and help them. Thank you again for freeing me.
{205}{}{Bom, não tenho por que voltar para minha vida antiga. A cidade lá em cima não tem qualquer assistencia médica, 
 então acho que vou subir lá para ajudá-los. Obrigado por me libertar.}
 
# Of course. See you later.
{206}{}{Claro. Te vejo lá.}

# Bye!
{207}{}{Falou!}

# I still need to pack a few things. I'll see you on the outside.
{210}{}{Eu preciso pegar umas coisas. Eu te encontro lá fora.}

# Hey there, good to see you again! Everyone here really appreciates what you have done. I personally am glad
 to be out of there. Working for Darion was a nightmare.
{220}{}{Ei, bom te ver de novo! Todos aqui estão gratos pelo que você fez. Eu pessoalmente estou feliz de 
 poder sair de lá. Trabalhar para o Darion era um inferno.}
 
# Glad I could help. So, tell me a little bit more about yourself.
{221}{}{Fico feliz em ajudar. Então, me conte mais sobre você.}

# Alright, see you around.
{222}{}{Ok, a gente se vê.}

# Well you see, I'm originally from the New California Republic, but I realized I had a gift for medical practices.
 So I trained as much as I could under the NCR medical staff, and once I had learned all I could, I decided to try and
 learn more by making my way to Vault City. I was lucky enough to meet Dr. Troy while he was tending an injured citizen
 outside the vault, and long story short, he agreed to finalize my training in Vault City. I had just finished my training
 and was heading out when Darion captured me.
{230}{}{Eu vim de New California Republic, lá eu percebi que tinha o dom para a medicina. Então treinei o máximo 
 que pude na equipe médica da NCR, e depois que aprendi tudo que podia, eu decidi tentar aprender mais e parti 
 para Vault City. Eu tive sorte de encontrar o Dr. Troy enquanto ele estava tratando um cidadão ferido fora da cidade,
 e para encurtar a história, ele topou me ajudar a terminar meu treinamento em Vault City. Eu tinha cabado de terminar
 meu treinamento e estava saindo da cidade quando Darion me capturou.}
 
# That's terrible. Well, I hope everything works out for you now.
{231}{}{Isso é terrível. Espero que tudo dê certo para você agora.}

# I hope so too. I think I can put my medical skills to good use here.
{240}{}{Eu também. Aqui posso dar um bom uso para minhas habilidades medicinais.}

# Bye.
{241}{}{Adeus}

# Thanks again for everything.
{250}{}{Obrigado de novo por tudo.}

# It feels good to be helping civilized people again.
{251}{}{É tão bom poder voltar a ajudar pessoas civilizadas.}