{100}{}{Você vê Khan um assaltante.}
{101}{}{Você vê Karla, um Khan.}
{102}{}{Você vê uma mulher de aparência resistende com uma armadura de metal. Ela seria bonita, se não fosse pelas marcas de cicatrizes em seu rosto.}
{103}{}{Fale com o Phil, cabeça de merda.}
{104}{}{Fale com o Phil, cadela.}
{105}{}{Ok.}
{106}{}{Essa vadia está morta.}

#You see a Khan raider.
#You see Karla, a Khan.
#You see a tough-looking woman in metal armor. She would be pretty, if it were not for the scars that line her face.
#Talk to Phil, shit head.
#Talk to Phil, bitch.
#Ok.
#That little bitch is dead.