{100}{}{Você vê um bandido Khan.}
{101}{}{Você vê Phil, um guarda Khan.}
{102}{}{Você vê um jovem forte em uma armadura de metal. Ele esta fortemente armado.}
{103}{}{Eu deveria atirar em você até a morte, mas estou curioso sobre o que você tem para me dizer.}
#Me look for spy. Go this way.
{104}{}{Mim procurar espião. Ir por este caminho.}
{105}{}{Estou procurando por uma garota desaparecida. Sabe onde posse encontrá-la?}
{106}{}{Cheguei aqui por acidente. Estou indo agora.}
{107}{}{Foda-se. Eu atiro e você morre.}
{108}{}{Uh, falaremos sobre isso?}
{109}{}{Estou procurando por um intruso que veio por esse caminho.}
{110}{}{Estou procurando por uma garota desaparecida. Você viu ela?}
{111}{}{Desculpe-me, peguei o caminho errado por acidente. Tenho que ir.}
{112}{}{Mais alguma coisa e vai comer bala, seu idiota.}
{113}{}{Eu acho que podemos falar sobre isso como duas pessoas civilizadas.}
{114}{}{Ah, esse seria eu. Agora que você me achou, qual o próximo passo?}
{115}{}{Por que você espiona Rebecca?}
{116}{}{Agora sei que não vou atirar na pessoa errada. Obrigado!}
{117}{}{Nada, estou indo agora.}
{118}{}{Por que você está espionando Rebecca?}
{119}{}{Só queria ter certeza de que estaria atirando na pessoa certa. Obrigado e tenha um bom dia!}
{120}{}{Hm. De nada, acho que estou indo agora.}
{121}{}{Eu não acredito que você acha que pode simplesmente vir aqui e conseguir repostas para suas perguntas! Oh, que diabos, você está prestes a morrer e eu me sinto generoso. Nós temos a filha dela trancando no quarto dos fundos e eu tenho me divertido com ela. Aquela puta, Rebecca, estive tentando achá-la, então estamos de olhos abertos para ter certeza de que ela não se aproxime.}
{122}{}{Vá esfriar a cabeça. Vou segurar as pontas por aqui.}
{123}{}{Você quer dizer, se divertir com a garota?}
{124}{}{Oh, isso explica. Estou indo.}
{125}{}{Você é um cachorro doente. Acho que vou colocá-lo para dormir agora.}
{126}{}{Ok, divirta-se, já estou indo.}
{127}{}{Entreguem a menina e todos nos podemos sair vivos daqui.}
{128}{}{Pense nisso como sua morte, idiota.}
{129}{}{}
{130}{}{}
{131}{}{Por que diabos eu deveria fazer isso?}
{132}{}{Isso é bom para a sua alma imortal.}
{133}{}{Porque eu sou a pior coisa que poderia ter acontecido com você. Entregue-a ou sinta a dor.}
{134}{}{Porque se nós lutarmos um de nós vai morrer. Eu não quero morrer e você também não, então vamos resolver isso pacificamente. Ok?}
{135}{}{Esqueça isso.}
{136}{}{}
{137}{}{}
{138}{}{Isso me parece um desafio. Vou aceitá-lo.}
{139}{}{}
{140}{}{}
{141}{}{Hmm... Eu... Ok, muito bem. Aqui está a chave para a cela dela; ela está no quarto dos fundos da cabana. Pegue-a, saia daqui e nunca mais volte. Se eu te ver novamente, vamos ver quem vive ou quem morre.}
{142}{}{Vamos ver quem sai dessa vivo.}
{143}{}{Obrigado, você fez a coisa certa.}
{144}{}{A única maneira de você sair daqui é escondido, em uma caixa.}
{145}{}{}
{146}{}{}
{147}{}{Você quer dizer aquela trancada lá atrás onde eu estava me divertindo? Não, eu não a vi.}
{148}{}{Vá esfriar a cabeça. Eu seguro as pontas aqui.}
{149}{}{Você quer dizer, me divertir com a garota?}
{150}{}{Oh. Estou indo agora.}
{151}{}{Você é um cachorro doente. Acho que vou colocá-lo para dormir agora.}
{152}{}{Ok, divirta-se, já estou indo.}
{153}{}{Entreguem a menina e todos nos podemos sair vivos daqui.}

{154}{}{Então você voltou. Vamos ver quem leva essa.}
{155}{}{Nós matamos a vadia da Chrissy e agora é a sua vez de morrer!}
