#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#       April 19,1998 nbk: added message line to be used    #
#                          for doors opened with keys.      #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc

# You see a wooden door.
{100}{}{Você vê uma porta de madeira.}

# You see a metal door.
{101}{}{Você vê uma porta de metal.}

# description_proc

# Perception Check Critical Success

# You see a sturdy door with a lock, which can be picked with
# lockpicks, and a highly explosive trap in the doorframe, which
# you may be able to pry open.
{102}{}{Você vê uma porta resistente com uma tranca, que pode ser
 aberta com gazuas. O batente da porta tem uma armadilha com explosivos.
 Talvez você consiga arrombar.}
 
# You see a sturdy door with a lock on it and a highly
# explosive trap in the doorframe, which you may be able to
# pry open.
{103}{}{Você vê uma porta resistente com uma tranca. O batente da 
 porta tem uma armadilha com explosivos. Talvez você consiga arrombar.}
 
# You see a sturdy door with no apparent locking device and
 a highly explosive trap in the doorframe, which you may be able
 to pry open.
{104}{}{Você vê uma porta resistente sem um mecanismo de tranca
 visível. O batente da porta tem uma armadilha com explosivos. Talvez
 você consiga arrombar.}
 
# You see a sturdy door with an old, rusty lock and a highly
 explosive trap in the doorframe, which you may be able to pry
 open.
{105}{}{Você vê uma porta resistente com uma tranca velha e enferrujada.
 O batente da porta tem uma armadilha com explosivos. Talvez você consiga arrombar.}

# You see a sturdy door with a lock (which can be picked with
 lockpicks) and a trap in the doorframe, which you may be able to
 pry open.
{106}{}{Você vê uma porta resistente com uma tranca (que pode ser aberta com
 gazuas) e uma armadilha no batente. Talvez você consiga arrombar.}

# You see a sturdy door with a lock on it and a trap in
 the doorframe, which you may be able to pry open.
{107}{}{Você vê uma porta resistente com uma tranca e uma armadilha no batente.
 Talvez você consiga arrombar.}

# You see a sturdy door with no apparent locking device and
 a trap in the doorframe, which you may be able to pry open.
{108}{}{Você vê uma porta resistente sem um mecanismo de tranca visível e uma
 armadilha no batente. Talvez você consiga arrombar.}
 
# You see a sturdy door with an old, rusty lock and a trap
 in the doorframe, which you may be able to pry open.
{109}{}{Você vê uma porta resistente com uma tranca velha e enferrujada e uma
 armadilha no batente. Talvez você consiga arrombar.}

# You see a sturdy door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe, which you may be
 able to pry open.
{110}{}{Você vê uma porta resistente com uma tranca, que pode ser aberta com
 gazuas. O batente tem um pedaço de arame do lado de fora. Talvez você consiga
 arrombar.}

# You see a sturdy door with a lock on it and a severed wire
 in the doorframe, which you may be able to pry open.
{111}{}{Você vê uma porta resistente com uma tranca e um pedaço de arame do lado
 de fora do batente. Talvez você consiga arrombar.}
 
# You see a sturdy door with no apparent locking device and
 a severed wire in the doorframe, which you may be able to pry
 open.
{112}{}{Você vê uma porta resistente sem um mecanismo de tranca visível e um
 pedaço de arame do lado de fora do batente. Talvez você consiga arrombar.}
 
# You see a sturdy door with an old, rusty lock and a cut
 wire in the doorframe, which you may be able to pry open.
{113}{}{Você vê uma porta resistente com uma tranca velha e enferrujada e um 
 pedaço de arame do lado de fora do batente. Talvez você consiga arrombar.}

# You see a sturdy door with a lock (which can be picked with
 lockpicks), which you may be able to pry open.
{114}{}{Você vê uma porta resistente com uma tranca (que você pode abrir com
 gazuas). Talvez você consiga arrombar.}

# You see a sturdy door with a lock on it, which you may be
 able to pry open.}
{115}{}{Você vê uma porta resistente com uma tranca, que talvez você consiga
 arrombar.}
 
# You see a sturdy door with no apparent locking device,
 which you may be able to pry open.
{116}{}{Você vê uma porta resistente sem um mecanismo de tranca visível, que 
 talvez você consiga arrombar.} 
 
# You see a sturdy door with an old, rusty lock, which
 you may be able to pry open.
{117}{}{Você vê uma porta resistente com uma tranca velha e enferrujada, que
 talvez você consiga arrombar.}

# Perception Check Success

# You see a sturdy door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.
{118}{}{Você vê uma porta resistente com uma tranca, que pode ser aberta com
 gazuas. O batente da porta tem uma armadilha com explosivos.}
 
# You see a sturdy door with a lock on it and a highly
 explosive trap in the doorframe.
{119}{}{Você vê uma porta resistente com uma tranca e uma armadilha com explosivos 
 no batente.}
 
# You see a sturdy door with no apparent locking device and
 a highly explosive trap in the doorframe.
{120}{}{Você vê uma porta resistente sem um mecanismo de tranca visível e uma 
 armadilha com explosivos no batente.}
 
# You see a sturdy door with an old, rusty lock and a highly
 explosive trap in the doorframe.
{121}{}{Você vê uma porta resistente com uma tranca velha e enferrujada e uma
 armadilha com explosivos no batente.}

# You see a sturdy door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.
{122}{}{Você vê uma porta resistente com uma tranca, que pode ser aberta com
 gazuas, e uma armadilha no batente.}
 
# You see a sturdy door with a lock on it and a trap in
 the doorframe.
{123}{}{Você vê uma porta resistente com uma tranca e uma armadilha no batente.}

# You see a sturdy door with no apparent locking device and
 a trap in the doorframe.
{124}{}{Você vê uma porta resistente sem um mecanismo de tranca visível
 e uma armadilha no batente.}
 
# You see a sturdy door with an old, rusty lock and a trap
 in the doorframe.
{125}{}{Você vê uma porta resistente com uma tranca velha e enferrujada
 e uma armadilha no batente.}

# You see a sturdy door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.
{126}{}{Você vê uma porta resistente com uma tranca, que pode ser aberta com 
 gazuas, e um pedaço de arame do lado de fora do batente.}

# You see a sturdy door with a lock on it and a severed wire
 in the doorframe.
{127}{}{Você vê uma porta resistente com uma tranca e um pedaço de arame do
 lado de fora do batente.}
 
# You see a sturdy door with no apparent locking device and
 a severed wire in the doorframe.
{128}{}{Você vê uma porta resiste sem um mecanismo de tranca visível com um 
 pedaço de arame do lado de fora do batente.}
 
# You see a sturdy door with an old, rusty lock and a cut
 wire in the doorframe.
{129}{}{Você vê uma porta resistente com uma tranca velha e enferrujada e 
 um pedaço de arame do lado de fora do batente.}

# You see a sturdy door with a lock, which can be picked with
 lockpicks, on it.
{130}{}{Você vê uma porta resistente com uma tranca, que pode ser aberta com
 gazuas.}
 
# You see a sturdy door with a lock on it.
{131}{}{Você vê uma porta resistente com uma tranca.}

# You see a sturdy door with no apparent locking device.
{132}{}{Você vê uma porta resistente sem um mecanismo de tranca visível.}

# You see a sturdy door with an old, rusty lock.
{133}{}{Você vê uma porta resistente com uma tranca velha e enferrujada.}

# Perception Check Critical Failure

# You see a damaged door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.
{134}{}{Você vê uma porta danificada com uma tranca, que pode ser aberta com
 gazuas. O batente da porta tem uma armadilha com explosivos.}
 
# You see a damaged door with a lock on it and a highly
 explosive trap in the doorframe.
{135}{}{Você vê uma porta danificada com uma tranca e uma armadilha com 
 explosivos no batente.}
 
# You see a damaged door with no apparent locking device and
 a highly explosive trap in the doorframe.
{136}{}{Você vê uma porta danificada sem um mecanismo de tranca visível e uma
 armadilha com explosivos no batente.}
 
# You see a damaged door with an old, rusty lock and a highly
 explosive trap in the doorframe.
{137}{}{Você vê uma porta danificada com uma tranca velha e enferrujada e uma 
 armadilha com explosivos no batente.}

# You see a damaged door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.
{138}{}{Você vê uma porta danificada com uma tranca, que pode ser aberta com 
 gazuas, e uma armadilha no batente.}
 
# You see a damaged door with a lock on it and a trap in
 the doorframe.
{139}{}{Você vê uma porta danificada com uma tranca e uma armadilha no batente.}

# You see a damaged door with no apparent locking device and
 a trap in the doorframe.
{140}{}{Você vê uma porta danificada sem um mecanismo de tranca visível e uma
 armadilha no batente.}
 
# You see a damaged door with an old, rusty lock and a trap
 in the doorframe.
{141}{}{Você vê uma porta danificada com uma tranca velha e enferrujada e uma 
 armadilha no batente.}

# You see a damaged door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.
{142}{}{Você vê uma porta danificada com uma tranca, que pode ser aberta com 
 gazuas, e um pedaço de arame do lado de fora do batente.}
 
# You see a damaged door with a lock on it and a severed wire
 in the doorframe.
{143}{}{Você vê uma porta danificada com uma tranca e um pedaço de arame do lado
 de fora do batente.}
 
# You see a damaged door with no apparent locking device and
 a severed wire in the doorframe.
{144}{}{Você vê uma porta danificada sem um mecanismo de tranca visível e um 
 pedaço de arame do lado de fora do batente.}
 
# You see a damaged door with an old, rusty lock and a cut
 wire in the doorframe.
{145}{}{Você vê uma porta danificada com uma tranca velha e enferrujada com um 
 pedaço de arame do lado de fora do batente.}

# You see a damaged door with a lock, which can be picked with
 lockpicks.
{146}{}{Você vê uma porta danificada com uma tranca, que pode ser aberta com 
 gazuas.}
 
# You see a damaged door with a lock on it.
{147}{}{Você vê uma porta danificada com uma tranca.}

# You see a damaged door with no apparent locking device.
{148}{}{Você vê uma porta danificada sem um mecanismo de tranca visível.

# You see a damaged door with an old, rusty lock.
{149}{}{Você vê uma porta danificada com uma tranca velha e enferrujada.}

# Perception Check Failure

# You see an old door with a lock, which can be picked with
 lockpicks, and a highly explosive trap in the doorframe.
{150}{}{Vocé vê uma porta velha com uma tranca, que pode ser aberta com 
 gazuas. O batente da porta tem uma armadilha com explosivos.}
 
# You see an old door with a lock on it and a highly
 explosive trap in the doorframe.
{151}{}{Você vê uma porta velha com uma tranca e uma armadilha com 
 explosivos no batente.}
 
# You see an old door with no apparent locking device and
 a highly explosive trap in the doorframe.
{152}{}{Você vê uma porta velha sem um mecanismo de tranca visível e uma 
 armadilha com explosivos no batente.}
 
# You see an old door with an old, rusty lock and a highly
 explosive trap in the doorframe.
{153}{}{Você vê uma porta velha com uma tranca enferrujada e uma armadilha
 com explosivos no batente.} 

# You see an old door with a lock, which can be picked with
 lockpicks, and a trap in the doorframe.
{154}{}{Você vê uma porta velha com uma tranca, que pode ser aberta com
 gazuas, e uma armadilha no batente.}

# You see an old door with a lock on it and a trap in
 the doorframe.
{155}{}{Você vê uma porta velha com uma trava e uma armadilha no batente.}

# You see an old door with no apparent locking device and
 a trap in the doorframe.
{156}{}{Você vê uma porta velha sem um mecanismo de tranca visível e uma
 armadilha no batente.}
 
# You see an old door with an old, rusty lock and a trap
 in the doorframe.
{157}{}{Você vê uma porta velha com uma tranca enferrujada e uma 
 armadilha no batente.}

# You see an old door with a lock, which can be picked with
 lockpicks, and a cut wire in the doorframe.
{158}{}{Você vê uma porta velha com uma tranca, que pode ser aberta com
 gazuas, e um pedaço de arame do lado de fora do batente.}
 
# You see an old door with a lock on it and a severed wire
 in the doorframe.
{159}{}{Você vê uma porta velha com uma tranca e um pedaço de arame 
 do lado de fora do batente.}
 
# You see an old door with no apparent locking device and
 a severed wire in the doorframe.
{160}{}{Você vê uma porta velha sem um mecanismo de tranca visível e
 um pedaço de arame do lado de fora do batente.}

# You see an old door with an old, rusty lock and a cut
 wire in the doorframe.
{161}{}{Você vê uma porta velha com uma tranca enferrujada e um 
 pedaço de arame do lado de fora do batente.} 

# You see an old door with a lock, which can be picked with
 lockpicks.
{162}{}{Você vê uma porta velha com uma tranca, que pode ser aberta 
 com gazuas.}
 
# You see an old door with a lock on it.
{163}{}{Você vê uma porta velha com uma tranca.}

# You see an old door with no apparent locking device.
{164}{}{Você vê uma porta velha sem um mecanismo de tranca visível.}

# You see an old door with an old, rusty lock.
{165}{}{Você vê uma porta velha com uma tranca enferrujada.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap

# You set off the trap and were hit for 
{166}{}{Você disparou a armadilha e sofreu }
#  points of damage.
{167}{}{ pontos de dano.}

# NPC sets off the trap

#  sets off the trap and was hit for 
{168}{}{ disparou a armadilha e sofreu }

#  points of damage.
{169}{}{ pontos de dano.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door

# You deftly pick the lock on the door.
{170}{}{Você habilmente arromba a tranca da porta.}

# Your lack of skill has jammed the lock on this door.
{171}{}{Sua falta de habilidade o fez emperrar a tranca da porta.}

# You fail to pick the lock on this door.
{172}{}{Você não conseguiu arrombar a tranca.}

# Lock Door

# You deftly lock the door.
{189}{}{Você habilmente tranca a porta.}

# You fail to lock the door.
{190}{}{Você não conseguiu trancar a porta.}

# Find Trap on the Door

# You find a trap on the door.
{194}{}{Você encontra uma armadilha na porta.}

# You fail to find any traps on the door.
{195}{}{Você não conseguiu encontrar nenhuma armadilha na porta.}

# Disarm the Trap on the Door

# You skillfully disarm the trap.
{196}{}{Você habilmente desativa a armadilha.}

# You fail to disarm the trap.
{198}{}{Você não conseguiu desativar a armadilha.} 

# NPC uses a skill on the door
# The following lines are appended with the NPC's name

# Unlock Door

#  deftly picks the lock on the door.
{173}{}{ habilmente arromba a tranca da porta.}

# 's lack of skill has jammed the lock on this door.
{174}{}{ acabou emperrando a tranca da porta com sua falta de habilidade.}

#  failed to pick the lock on this door.
{175}{}{ não conseguiu arrombar a tranca.}

# Lock Door

#  deftly locks the door.
{191}{}{ habilmente tranca a porta.}

#  failed to lock the door.
{192}{}{ não conseguiu fechar a porta.}    

# Find Trap on the Door

#  finds a trap on the door.
{199}{}{ encontrou uma armadilha na porta.}

#  fails to find any traps on the door.
{200}{}{ não conseguiu encontrar nenhuma armadilha na porta.}

# Disarm the Trap on the Door

#  skillfully disarms the trap.
{201}{}{ habilmente desativa a armadilha.}

#  fails to disarm the trap.
{202}{}{ não conseguiu desativar a armadilha.}

# Using a key on the door.

# You unlock the door.
{400}{}{Você destranca a porta.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door

# You bust the lock off the door.
{176}{}{Você arrebentou a tranca da porta.}

# While trying to bust the lock, you strain your back and
 take a point of damage.
{177}{}{Enquanto tentava arrebentar a tranca, você deu um mau 
 jeito nas costas e sofreu um ponto de dano.}

# The following set of lines is to be translated as:
# While trying to bust the lock, you strain your back and
# take [x] points of damage.

# While trying to bust the lock, you strain your back and
 take 
{178}{}{ Enquanto tentava arrebentar a tranca, você deu um mau 
 jeito nas costas e sofreu }
 
#  points of damage.
{179}{}{ pontos de dano.}

# You are too weak to bust the lock.
{180}{}{Você não tem força para arrebentar a tranca.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name

#  busts the lock off the door.
{181}{}{ arrebenta a tranca da porta.}

#  strains his back while trying to bust the lock and takes
 a point of damage.
{182}{}{ deu um mau jeito nas costas tentando arrebentar a tranca e sofreu
 um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

#  strains his back while trying to bust the lock and takes 
{183}{}{ deu mau jeito nas costas tentando arrebentar a tranca e sofreu }

#  points of damage.
{184}{}{ pontos de dano.}

#  is too weak to bust the lock.
{185}{}{ não tem força para arrebentar a tranca.}

#  strains her back while trying to bust the lock and takes
 a point of damage.
{186}{}{ deu mau jeito nas costas tentando arrebentar a tranca e sofreu
 um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

#  strains her back while trying to bust the lock and takes 
{187}{}{ deu mau jeito nas costas tentando arrebentar a tranca e sofreu }

#  points of damage.
{188}{}{ pontos de dano.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

# The explosives don't even put a scratch on the door.
{193}{}{Os explosivos nem fizeram cocegas na porta.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

# The door appears to be locked. It looks like it takes some kind of thin card as a key.
{203}{}{A porta parece estar trancada. Parece que ela usa um cartão fino como chave.}

# You hear the crackling of electricity running through the door.
{204}{}{Você percebe o crepitar de eletricidade correndo pela porta.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jamb.

#  notices the crackling of electricity running through the door.
{205}{}{ percebe o crepitar de eletricidade correndo pela porta.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door

# You are unable to place a trap on this door because
 the door is open.
{206}{}{Você não conseguiu colocar a armadilha na porta porque ela 
 está aberta.}

# NPC tries to set a trap on an open door

#  is unable to place a trap on this door because the
 door is open.
{207}{}{ não conseguiu colocar a armadilha na porta porque ela está 
 aberta.}

# Player tries to set a trap on a closed door

# You skillfully set a trap in the door frame.
{208}{}{Você habilmente coloca uma armadilha no batente da porta.}

# You fail to set the trap properly in the door frame.
{209}{}{Você não conseguiu colocar a armadilha corretamente no batente da porta.}

# NPC tries to set a trap on a closed door

#  skillfully sets a trap in the door frame.
{210}{}{ habilmente coloca uma armadilha no batente da porta.}

#  fails to set the trap properly in the door frame.
{211}{}{ não conseguiu colocar a armadilha corretamente no batente da porta.}

# You unlock the door.
{300}{}{Você destrancou a porta.}

# You lock the door.
{301}{}{Você trancou a porta.}

# You are unable to lock this door while it is open.
{302}{}{Você não pode trancar uma porta enquanto ela estiver aberta.}

# That key does not fit in this lock.
{303}{}{Essa chave não entra nesta fechadura.}

# for broken doors

# There's no way to lock this door.
{320}{}{Não há como trancar esta porta.}

# There is no way to untrap the door.
{500}{}{Não há como remover a armadilha desta porta.}