{100}{}{Você vê alguém em uma power armor. }
{101}{}{Você vê o comandante de Navarro.}
{102}{}{Você vê alguém vestindo uma power armor com um design diferente. Há uma insígnea no peito que não é familiar pra você.}

{103}{}{Quem diabos são vocês... Alerta! Intrusos na base!}
{104}{}{Eu não tenho tempo pra bater papo com soldados. Dispensado.}
{105}{}{Hora de morrer.}
{106}{}{Certo.}

{107}{}{Eu já disse que não tenho tempo pra você. Deixe este escritório e não volte a não ser que eu mande te chamar. Dispensado!}
{108}{}{Desobedecer uma ordem direta de um superior é traição. Eu não tenho tempo pra Corte Marcial, então eu mesmo vou cuidar disso. Guardas! Matem esse idiota!}
{109}{}{Certo.}
{110}{}{Vai te fuder!}

{111}{}{O Fob está naquele armário bem ali. Diga ao oficial para me contactar assim que ele estiver seguro. Dispensado!}
{112}{}{Sim, senhor!}

{113}{}{Ande logo com isso soldado, eu não tenho o dia todo.}
{114}{}{Sim, senhor!}

{115}{}{Deixe o meu armário em paz ou eu acabo com você.}
{116}{}{Sim, senhor!}

{117}{}{Esta base está em alerta e eu não te reconheço. Mostre-me seus documentos, soldado.}
{118}{}{Que documentos?}
{119}{}{You blow me!}
{120}{}{É que eu não estou com eles aqui...}
{121}{}{Documentos? Eu tenho os seus documentos bem aqui!}

{122}{}{Resposta errada, imbecil. Você deveria andar com seus documentos o tempo todo. Você deveria saber disso!}
{123}{}{Vai te fuder!}

{124}{}{Deixe o meu armário em paz ou eu acabo com você.}
{125}{}{Hora de morrer.}

#added by killap - RP
{200}{}{Alright, let's get this over with--I don't like muties stinking up my office, and I got shit to do. Do you work
 for the Salvatores? }
{201}{}{None of your business, asshole.}
{202}{}{I work for no one.}
{203}{}{So what if I do?}
{204}{}{Yeah, I work for the Salvatores.}
{205}{}{Before I answer any questions, I've got a few of my own.}

# None of your business, asshole
{210}{}{I don't have time for this bullshit. Guards! Kill this mutie!}

#I work for no one
{220}{}{So you're saying you're nothing more than a stray wasteland rat that happened to wander into one of our vertibirds?}
{221}{}{Uh, yeah, pretty much . . . except for that part about me being a rat.}
{222}{}{That's right.}
{223}{}{No, I'm saying that this is all just a big misunderstanding. I don't know who you guys are, and I don't care.
 So if you don't mind, I'll be moving along now.}
 
{230}{}{Good, if you're acting alone, then I don't have to waste another second of my time with you. Guards! Kill this mutie!}

{240}{}{You're not leaving here alive, mutant. I couldn't risk you blabbing the location of this base to all your
 wasteland friends, now could I? Guards! Kill this mutie!}
 
# So what if I do?/ Yeah, I work for the Salvatores.
{250}{}{Tell me what I want to know, and I'll make sure your death is quick and . . . relatively painless.
 Did Salvatore put you up to this?}
{251}{}{Uhh . . . no? Wait, yeah. Maybe.}
{252}{}{Nope. Playing hide-and-seek in your flying machine was all my own idea. Genius, I know.}
{253}{}{Yeah, he thought he'd sweeten the trade by sending me along. What a deal, huh?}
{254}{}{Before I answer any questions, I've got a few of my own.}

{260}{}{I don't have time for this bullshit. Guards! Kill this mutie!}

{270}{}{That supposed to be funny, mutant? I think you'll be a lot funnier to me when you're a bleeding corpse. Guards!
 Kill this mutie!}

{280}{}{Oh, you do? [He chuckles.] Well hell, why not? You're dying anyway. What do you want to know, mutant?}
{281}{}{Why do you keep calling me a mutant?}
{282}{}{Who the hell are you guys?}
{283}{}{Where am I? }
{284}{}{How can I get some of that sweet armor?}
{285}{}{I've heard enough.}

{290}{}{Because you ARE. Sure, you might look kinda human, but don't let that fool you. You're still a mutant. You and
 everyone else on the mainland. All tainted. Next question?}
{300}{}{We're the Enclave--the last bastion of true humanity on this damn planet. We're the only ones still upholding
 the honor of the ol' red, white, and blue. That's right, we're true patriots. We eat bald eagles and shit stars and
 stripes. We're all that's left of the great United States of America. But we're enough. Oh, yeah, we're enough to set
 things right. You can count on that, mutie. Next question?}
{310}{}{This here's Navarro, our secret mainland base. We're sitting right on the coast of California and the pacific
 ocean. Next question?}
{320}{}{By prying it off my dead body. Good luck with that, mutie. Next question?}
{330}{}{Good, 'cause I'm damn tired of wasting my breath on a mutant. In fact, this whole things a waste of my time,
 because I don't give a flying fuck what you've got to say to me. Guards! Kill this mutie!}
 
 #added by killap - RP
#Alright, let's get this over with--I don't like muties stinking up my office, and I got shit to do. Do you work
 for the Salvatores?
{200}{}{Tudo bem, vamos acabar logo com isso--Eu não gosto de muitos fedorentos no meu escritório, e tenho coisas para fazer. Você trabalha
 para os Salvatores?}
 #None of your business, asshole.
{201}{}{Não é da sua conta, idiota.}
#I work for no one.
{202}{}{Eu não trabalho para ninguém.}
#So what if I do?
{203}{}{Então, o que eu faço?}
#Yeah, I work for the Salvatores.
{204}{}{Sim, eu trabalho para os Salvatores.}
#Before I answer any questions, I've got a few of my own.
{205}{}{Antes de responder a todas as perguntas, eu tenho as minhas.}

# None of your business, asshole
#I don't have time for this bullshit. Guards! Kill this mutie!
{210}{}{Eu não tenho tempo para essas besteiras. Guardas! Matem este mudinho!}

#I work for no one
#So you're saying you're nothing more than a stray wasteland rat that happened to wander into one of our vertibirds?
{220}{}{Então você está dizendo que um rato de rua da wasteland passeou em um dos nossos vertibirds?}
#Uh, yeah, pretty much . . . except for that part about me being a rat.
{221}{}{Uh, sim, bastante . . . exceto aquela parte sobre eu ser um rato.}
#That's right.
{222}{}{Está certo.}
#No, I'm saying that this is all just a big misunderstanding. I don't know who you guys are, and I don't care.
 So if you don't mind, I'll be moving along now.
{223}{}{Não, eu estou dizendo que tudo isso é apenas um grande mal entendido. Eu não sei quem vocês são, e eu não me importo.
 Então, se você não se importa, eu vou estar se movendo ao longo agora.}
 
 #Good, if you're acting alone, then I don't have to waste another second of my time with you. Guards! Kill this mutie!
{230}{}{Bom, se você está agindo sozinho, então eu não tenho que perder mais um segundo do meu tempo com você. Guardas! Matem este mudinho!}

#You're not leaving here alive, mutant. I couldn't risk you blabbing the location of this base to all your
 wasteland friends, now could I? Guards! Kill this mutie!
{240}{}{Você não vai sair daqui vivo, mutante. Eu não posso arriscar que você saia tagarelando a localização desta base para todos os seus
 amigos da wasteland, eu posso? Guardas! Matem este mudinho!}
 
# So what if I do?/ Yeah, I work for the Salvatores.
#Tell me what I want to know, and I'll make sure your death is quick and . . . relatively painless.
 Did Salvatore put you up to this?
{250}{}{Me Diga o que eu quero saber, e eu vou ter certeza de sua morte seja rápida e... E sem problemas.
 Será que Salvatore mandou fazer isso?}
 #Uhh . . . no? Wait, yeah. Maybe.
{251}{}{Uhh . . . não? Espere, sim. Talvez.}
#Nope. Playing hide-and-seek in your flying machine was all my own idea. Genius, I know.
{252}{}{Não.. Brincando de esconde-esconde na sua própria máquina voadora foi minha idéia. Genius, eu sei.}
#Yeah, he thought he'd sweeten the trade by sending me along. What a deal, huh?
{253}{}{Sim, ele pensou em adoçar o comércio, enviando-me junto. Que coisa, hein?}
#Before I answer any questions, I've got a few of my own.
{254}{}{Antes de responder a todas as perguntas, eu tenho as minhas.}

#I don't have time for this bullshit. Guards! Kill this mutie!
{260}{}{Eu não tenho tempo para essas besteiras. Guardas! Matem este mudinho!}

#That supposed to be funny, mutant? I think you'll be a lot funnier to me when you're a bleeding corpse. Guards!
 Kill this mutie!
{270}{}Isso deveria ser engraçado, mutante? Acho que você vai ser muito mais engraçado para mim quando seu corpo estiver sangrando. Guardas!
 Matem este mudinho!}

 #Oh, you do? [He chuckles.] Well hell, why not? You're dying anyway. What do you want to know, mutant?
{280}{}{Oh, você faz? [Ele ri.] Bom inferno, por que não? Você está morrendo de qualquer maneira. O que você quer saber, mutante?}
#Why do you keep calling me a mutant?
{281}{}{Por que você continua me chamando de mutante?}
#Who the hell are you guys?
{282}{}{Que diabos são vocês?}
#Where am I? 
{283}{}{Onde eu estou? }
#How can I get some of that sweet armor?
{284}{}{Como posso conseguir uma armadura dessas?}
#I've heard enough.
{285}{}{Já ouvi o bastante.}

#Because you ARE. Sure, you might look kinda human, but don't let that fool you. You're still a mutant. You and
 everyone else on the mainland. All tainted. Next question?
{290}{}{Porque você É. Claro, você pode olhar meio humano, mas não se deixe enganar. Você ainda é um mutante. Você e 
 todos os outros no continente. Todos contaminados. Próxima questão?}
 #We're the Enclave--the last bastion of true humanity on this damn planet. We're the only ones still upholding
 the honor of the ol' red, white, and blue. That's right, we're true patriots. We eat bald eagles and shit stars and
 stripes. We're all that's left of the great United States of America. But we're enough. Oh, yeah, we're enough to set
 things right. You can count on that, mutie. Next question?
{300}{}{Nós somos a Enclave - o último bastião da verdadeira humanidade neste planeta maldito. Nós somos os únicos que defendem 
 ainda a honra do vermelho, branco e azul. É isso mesmo, nós somos os verdadeiros patriotas. Nós comemos águias, estrelas e 
 listras. Nós somos tudo o que resta do grande Estados Unidos da América. Mas nós somos bastante. Ah, sim, nós somos o suficiente para
 acertar as coisas. Você pode contar com isso, mudinho. Próxima questão?}
 #This here's Navarro, our secret mainland base. We're sitting right on the coast of California and the pacific
 ocean. Next question?
{310}{}{Este aqui está Navarro, a nossa base secreta no continente. Estamos sentados na costa da Califórnia e do oceano 
pacífico. Próxima questão?}
#By prying it off my dead body. Good luck with that, mutie. Next question?
{320}{}{Erguendo-a do meu cadáver. Boa sorte com isso, mudinho. Próxima pergunta?}
#Good, 'cause I'm damn tired of wasting my breath on a mutant. In fact, this whole things a waste of my time,
 because I don't give a flying fuck what you've got to say to me. Guards! Kill this mutie!
{330}{}{Bom, porque estou muito cansado de perder o fôlego para um mutante. Na verdade, todas essas coisas foram um desperdício do meu tempo,
 pois eu não dou a mínima no que você tem para me dizer. Guardas! Matem este mudinho!}