#
# This is all of the combat messages used by combat.c
# Note: all %d values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{Você precisa de %d pontos de ação.} #You need %d action points.
{101}{}{Sem munição.} #Out of ammo.
{102}{}{Alvo fora do alcance.} #Target out of range.
{103}{}{Não é possível finalizar o combate com criaturas hostis nas proximidades.} #Combat cannot end with nearby hostile creatures.
{104}{}{Linha de fogo bloqueada.} #Your aim is blocked.
{105}{}{Você não pode usar armas com os dois braços quebrados.} #You cannot use weapons with both arms crippled.
{106}{}{Você não pode usar armas de duas mãos com um braço quebrado.} #You cannot use two-handed weapons with a crippled arm.
{107}{}{Você não é forte o suficiente para usar esta arma corretamente.} #You are not strong enough to use this weapon properly.
{108}{}{ e } #and
#
# Combat Flag Strings (all of these happen to you, the MALE player)
#
{200}{}{te deixou fora de combate} #knocked out
{201}{}{derrubado} #knocked down
{202}{}{perna esquerda quebrada} #crippled your left leg
{203}{}{perna direita quebrada} #crippled your right leg
{204}{}{braço esquerdo quebrado} #crippled your left arm
{205}{}{braço direito quebrado} #crippled your right arm
{206}{}{cego} #blinded
{207}{}{você morreu} #were killed
{208}{}{te deixa ferido} #hit
{209}{}{criticamente}
{210}{}{em chamas} #on fire
{211}{}{perfura sua armadura} #had your armor bypassed
{212}{}{sua arma explodiu} #your weapon exploded
{213}{}{sua arma foi destruída} #destroyed your weapon
{214}{}{sua arma caiu} #dropped your weapon
{215}{}{perdeu seu próximo turno} #lost your next turn
{216}{}{acertou em você mesmo} #hit yourself
{217}{}{perdeu o resto de sua munição} #lost the rest of your ammo
{218}{}{tiro fracassado} #fired a dud shot
{219}{}{você se feriu} #hurt yourself
{220}{}{bater aleatoriamente} #hit randomly
{221}{}{quebrar um membro aleatório} #crippled a random limb
{222}{}{você alcança os fragmentos} #peppered with fragments
#
# Combat Flag Strings (all of these happen to you, the FEMALE player)
#
{250}{}{te deixou fora de combate}
{251}{}{derrubada}
{252}{}{perna esquerda quebrada}
{253}{}{perna direita quebrada}
{254}{}{braço esquerdo quebrado}
{255}{}{braço direito quebrado}
{256}{}{cega}
{257}{}{você morre}
{258}{}{te deixa ferida}
{259}{}{criticamente}
{260}{}{em chamas}
{261}{}{perfura sua armadura}
{262}{}{sua arma explodiu}
{263}{}{sua arma foi destruída}
{264}{}{sua arma caiu}
{265}{}{perdeu seu próximo turno}
{266}{}{acertou em você mesma}
{267}{}{perdeu o resto de sua munição}
{268}{}{tiro fracassado}
{269}{}{você se feriu}
{270}{}{bater aleatoriamente}
{271}{}{quebrar um membro aleatório}
{272}{}{você alcança os fragmentos}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{te deixou fora de combate}
{301}{}{derrubado}
{302}{}{quebrou sua perna esquerda} #crippled his left leg
{303}{}{quebrou sua perna direita} #crippled his right leg
{304}{}{quebrou seu braço esquerdo} #crippled his left arm
{305}{}{quebrou seu braço direito} #crippled his right arm
{306}{}{cego}
{307}{}{morreu} #was killed
{308}{}{te deixa ferido}
{309}{}{criticamente}
{310}{}{em chamas}
{311}{}{perfura sua armadura} #had his armor bypassed
{312}{}{sua arma explodiu} #his weapon exploded
{313}{}{sua arma foi destruída} #destroyed his weapon
{314}{}{deixou cair a arma} #dropped his weapon
{315}{}{perdeu seu próximo turno} #lost his next turn
{316}{}{acertou em você mesmo} #hit himself
{317}{}{perdeu o resto de sua munição} #lost the rest of his ammo
{318}{}{tiro fracassado}
{319}{}{você se feriu} #hurt himself
{320}{}{bater aleatoriamente}
{321}{}{quebrar um membro aleatório}
{322}{}{você alcança os fragmentos}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{te deixou fora de combate}
{401}{}{derrubada}
{402}{}{quebrou sua perna esquerda}
{403}{}{quebrou sua perna direita}
{404}{}{quebrou seu braço esquerdo}
{405}{}{quebrou seu braço direito}
{406}{}{cega}
{407}{}{morreu}
{408}{}{te deixa ferida}
{409}{}{gravemente}
{410}{}{em chamas}
{411}{}{perfura sua armadura}
{412}{}{sua arma explodiu}
{413}{}{sua arma foi destruída}
{414}{}{deixou cair a arma}
{415}{}{perdeu seu próximo turno}
{416}{}{acertou em você mesma}
{417}{}{perdeu o resto de sua munição}
{418}{}{tiro fracassado}
{419}{}{você se feriu}
{420}{}{bater aleatoriamente}
{421}{}{quebrar um membro aleatório}
{422}{}{você alcança os fragmentos}
#
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first %s will be replaced by the value of line 506, which
#          should be the language's equivalent to 2nd person male singular,
#          which is "You" in English. The first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 509
#          where the second %s is the name of another creature
{506}{}{Você}
{509}{}{Oops! %s foi atingido, em vez de %s!} #were hit instead of
{511}{}{%s foi gravemente atingido %s, perdendo %d pontos de vida} #%s were críticoly hit in %s for %d hit points
{512}{}{%s foi atingido %s perdendo %d pontos de vida}
{513}{}{%s foi atingido perdendo %d pontos de vida}
{514}{}{%s errou criticamente} #críticoly missed
{515}{}{%s errou} #missed
{520}{}{%s foi gravemente atingido, perdeu %d pontos de vida} #were críticoly hit for
{521}{}{%s foi gravemente atingido %s perdendo 1 ponto de vida}
{522}{}{%s foi atingido %s e perdeu 1 ponto de vida}
{523}{}{%s foi atingido e perde 1 ponto de vida} #were hit for 1 hit point
{524}{}{%s foi gravemente atingido e perde 1 ponto de vida}
{525}{}{%s foi gravemente atingido %s, sem sofrer nenhum dano} #were críticoly hit in
{526}{}{%s foi atingido %s sem danos}
{527}{}{%s foi atingido sem sofrer nenhum dano} #were hit for no damage
{528}{}{%s foi gravemente atingido sem sofrer nenhum dano}
{533}{}{%s erro critico, perdeu 1 ponto de vida} #and took
{534}{}{%s erro critico, perdeu %d pontos de vida} #and took
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first %s will be replaced by the value of line 556, which
#          should be the language's equivalent to 2nd person female singular,
#          which is "You" in English. The first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 559
#          where the second %s is the name of another creature
{556}{}{Você}
{559}{}{Oops! %s foi atingida, em vez de %s!}
{561}{}{%s foi gravemente atingida %s, perdeu %d pontos de vida}
{562}{}{%s foi atingida %s perdendo %d pontos de vida}
{563}{}{%s foi atingida perdendo %d pontos de vida}
{564}{}{%s errou criticamente}
{565}{}{%s errou}
{570}{}{%s foi gravemente atingida, perdeu %d pontos de vida}
{571}{}{%s foi gravemente atingida %s perdendo 1 ponto de vida}
{572}{}{%s foi atingida %s e perdeu 1 ponto de vida}
{573}{}{%s foi atingida e perde 1 ponto de vida}
{574}{}{%s foi gravemente atingida e perde 1 ponto de vida}
{575}{}{%s foi gravemente atingida %s, sem sofrer nenhum dano}
{576}{}{%s foi atingida %s sem danos}
{577}{}{%s foi atingida sem sofrer nenhum dano}
{578}{}{%s foi gravemente atingida sem sofrer nenhum dano}
{583}{}{%s erro critico, perdeu 1 ponto de vida}
{584}{}{%s erro critico, perdeu %d pontos de vida}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first %s is the name of the male creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 609
#          where the second %s is the name of another creature
#
{608}{}{Oops! %s foi atingido em vez de você!} #was hit instead of you!
{609}{}{Oops! %s foi atingido, em vez de %s!} #was hit instead of
{611}{}{%s é gravemente atingido %s, perdendo %d pontos de vida}
{612}{}{%s é atingido %s, perdendo %d pontos de vida}
{613}{}{%s é atingido, perdendo %d pontos de vida}
{614}{}{%s errou criticamente}
{615}{}{%s errou}
{620}{}{%s é gravemente atingido, perdendo %d pontos de vida}
{621}{}{%s é gravemente atingido %s, perdendo 1 ponto de vida}
{622}{}{%s é atingido %s, perdendo 1 ponto de vida}
{623}{}{%s é atingido, perdendo 1 ponto de vida}
{624}{}{%s é gravemente atingido, perdendo 1 ponto de vida}
{625}{}{%s é gravemente atingido %s, sem sofrer nenhum dano}
{626}{}{%s é atingido %s, sem sofrer nenhum dano}
{627}{}{%s é atingido, sem sofrer nenhum dano}
{628}{}{%s é gravemente atingido, sem sofrer nenhum dano}
{633}{}{%s erro critico, perdeu 1 ponto de vida}
{634}{}{%s erro critico, perdeu %d pontos de vida}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first %s is the name of the female creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 709
#          where the second %s is the name of another creature
#
{708}{}{Oops! %s foi atingida em vez de vocês!}
{709}{}{Oops! %s foi atingida, em vez de %s!}
{711}{}{%s é gravemente atingida %s, perdendo %d pontos de vida}
{712}{}{%s é atingida %s, perdendo %d pontos de vida}
{713}{}{%s é atingida, perdendo %d pontos de vida}
{714}{}{%s erro critico}
{715}{}{%s missed}
{720}{}{%s é gravemente atingida, perdendo %d pontos de vida}
{721}{}{%s é gravemente atingida %s, perdendo 1 ponto de vida}
{722}{}{%s é atingida %s, perdendo 1 ponto de vida}
{723}{}{%s é atingida, perdendo 1 ponto de vida}
{724}{}{%s é gravemente atingida, perdendo 1 ponto de vida}
{725}{}{%s é gravemente atingida em %s, sem sofrer nenhum dano}
{726}{}{%s é atingida %s, sem sofrer nenhum dano}
{727}{}{%s é atingida, sem sofrer nenhum dano}
{728}{}{%s é gravemente atingida, sem sofrer nenhum dano}
{733}{}{%s erro critico, perdeu 1 ponto de vida}
{734}{}{%s erro critico, perdeu %d pontos de vida}
#
# Hit Locations (by art_num alias)
#
# regular humans
#
{1110}{}{na cabeça} #the head
{1111}{}{no braço esquerdo} #the left arm
{1112}{}{no braço direito} #the right arm
{1113}{}{no tronco} #the torso
{1114}{}{na perna direita} #the right leg
{1115}{}{na perna esquerda} #the left leg
{1116}{}{nos olhos} #the eyes
{1117}{}{na virilha} #the groin
{1118}{}{lugar indefinido} #uncalled
#
# Brahmin (Mutant 2-Headed Cows)
#
{1150}{}{na cabeça}
{1151}{}{na pata traseira esquerda} #the left hindleg
{1152}{}{na pata traseira direita} #the right hindleg
{1153}{}{no tronco}
{1154}{}{na pata dianteira direita} #the right foreleg
{1155}{}{na pata dianteira esquerda} #the left foreleg
{1156}{}{nos olhos}
{1157}{}{nas glândulas mamárias} #the udder
{1158}{}{lugar indefinido}
#
# dogs
#
{1160}{}{na cabeça}
{1161}{}{na pata traseira} #the hindleg
{1162}{}{na pata traseira} #the hindleg
{1163}{}{no corpo} #the body
{1164}{}{na pata dianteira} #the foreleg
{1165}{}{na pata dianteira} #the foreleg
{1166}{}{nos olhos}
{1167}{}{na virilha}
{1168}{}{lugar indefinido}
#
# Mr. Handy
#
{1170}{}{no CPU}
{1171}{}{no manipulador} #the manipulator
{1172}{}{no manipulador}
{1173}{}{na estrutura}
{1174}{}{na unidade matriz} #the motivator
{1175}{}{na unidade matriz}
{1176}{}{nos sensores} #the sensors
{1177}{}{no regulador} #the regulator
{1178}{}{lugar indefinido}
#
# Super Mutants             # Fallout 2: Reserved?
#
{1180}{}{na cabeça}
{1181}{}{no braço esquerdo}
{1182}{}{no braço direito}
{1183}{}{no tronco}
{1184}{}{na perna direita}
{1185}{}{na perna esquerda}
{1186}{}{nos olhos}
{1187}{}{na virilha}
{1188}{}{lugar indefinido}
#
# Mole-Rat
#
{1190}{}{na cabeça}
{1191}{}{na pata esquerda} #the left paw
{1192}{}{na pata direita} #the right paw
{1193}{}{no corpo}
{1194}{}{na perna direita}
{1195}{}{na perna esquerda}
{1196}{}{nos olhos}
{1197}{}{na virilha}
{1198}{}{lugar indefinido}
#
# big humans and mutants
#
{1210}{}{na cabeça}
{1211}{}{no braço esquerdo}
{1212}{}{no braço direito}
{1213}{}{no tronco}
{1214}{}{na perna direita}
{1215}{}{na perna esquerda}
{1216}{}{nos olhos}
{1217}{}{na virilha}
{1218}{}{lugar indefinido}
#
# Radscorpion
#
{1220}{}{na cabeça}
{1221}{}{na cauda} #the tail
{1222}{}{na garra} #the claw
{1223}{}{na carapaça} #the carapace
{1224}{}{nas patas dianteiras}
{1225}{}{nas patas traseiras}
{1226}{}{nos olhos}
{1227}{}{no cérebro} #the brain
{1228}{}{lugar indefinido}
#
# Floater
#
{1230}{}{na cabeça}
{1231}{}{na boca} #the mouth
{1232}{}{na boca dianteira} #the fore mouth
{1233}{}{no corpo}
{1234}{}{no saco flutuante} #the float sac
{1235}{}{na cauda}
{1236}{}{no gânglio} #the ganglion
{1237}{}{no ovipositor} #the ovipositor
{1238}{}{lugar indefinido}
#
# masrat? a rat perhaps?
#
{1240}{}{na cabeça}
{1241}{}{na pata esquerda}
{1242}{}{na pata direita}
{1243}{}{no corpo}
{1244}{}{na perna direita}
{1245}{}{na perna esquerda}
{1246}{}{nos olhos}
{1247}{}{na virilha}
{1248}{}{lugar indefinido}
#
# Centaur
#
{1250}{}{na cabeça}
{1251}{}{no braço esquerdo}
{1252}{}{no braço direito}
{1253}{}{no corpo}
{1254}{}{na perna direita}
{1255}{}{na perna esquerda}
{1256}{}{nos olhos}
{1257}{}{na virilha}
{1258}{}{lugar indefinido}
#
# human midgets and children
#
{1270}{}{na cabeça}
{1271}{}{no braço esquerdo}
{1272}{}{no braço direito}
{1273}{}{no tronco}
{1274}{}{na perna direita}
{1275}{}{na perna esquerda}
{1276}{}{nos olhos}
{1277}{}{na virilha}
{1278}{}{lugar indefinido}
#
# Overseer                  # Fallout 2: Reserved?
#
{1460}{}{na cabeça}
{1461}{}{no braço esquerdo}
{1462}{}{no braço direito}
{1463}{}{no tronco}
{1464}{}{na perna direita}
{1465}{}{na perna esquerda}
{1466}{}{nos olhos}
{1467}{}{na virilha}
{1468}{}{lugar indefinido}
#
# Gizmo                     # Fallout 2: Reserved?
#
{1490}{}{na cabeça}
{1491}{}{no braço esquerdo}
{1492}{}{no braço direito}
{1493}{}{no tronco}
{1494}{}{na perna direita}
{1495}{}{na perna esquerda}
{1496}{}{nos olhos}
{1497}{}{na virilha}
{1498}{}{lugar indefinido}
#
# The Master!               # Fallout 2: Reserved?
#
{1500}{}{na cabeça}
{1501}{}{???}
{1502}{}{???}
{1503}{}{na estrutura}
{1504}{}{???}
{1505}{}{???}
{1506}{}{nos olhos}
{1507}{}{no CPU}
{1508}{}{lugar indefinido}
#
# Death Claw
#
{1510}{}{na cabeça}
{1511}{}{no braço esquerdo}
{1512}{}{no braço direito}
{1513}{}{no tronco}
{1514}{}{na perna direita}
{1515}{}{na perna esquerda}
{1516}{}{nos olhos}
{1517}{}{na virilha}
{1518}{}{lugar indefinido}
#
# Mantis
#
{1520}{}{na cabeça}
{1521}{}{na pata raptorial} #the raptorial leg
{1522}{}{na pata raptorial}
{1523}{}{no abdômen} #the abdomen
{1524}{}{nas pernas} #the legs
{1525}{}{nas asas} #the wings
{1526}{}{nos olhos}
{1527}{}{no metatórax} #the metathorax
{1528}{}{lugar indefinido}
#
# Robobrain
#
{1530}{}{no CPU}
{1531}{}{no manipulador}
{1532}{}{no manipulador}
{1533}{}{na estrutura}
{1534}{}{na unidade matriz}
{1535}{}{na unidade matriz}
{1536}{}{nos sensores}
{1537}{}{no regulador}
{1538}{}{lugar indefinido}
#
# Eyeball (Robot)
#
{1540}{}{no CPU}
{1541}{}{no manipulador}
{1542}{}{no manipulador}
{1543}{}{na estrutura}
{1544}{}{na unidade matriz}
{1545}{}{na unidade matriz}
{1546}{}{nos sensores}
{1547}{}{no regulador}
{1548}{}{lugar indefinido}
#
# Mutant Pig Rat (small Mole-Rat)
#
{1550}{}{na cabeça}
{1551}{}{na pata esquerda}
{1552}{}{na pata direita}
{1553}{}{no corpo}
{1554}{}{na perna direita}
{1555}{}{na perna esquerda}
{1556}{}{nos olhos}
{1557}{}{na virilha}
{1558}{}{lugar indefinido}
#
# Deathclaw Egg
#
{1580}{}{na carapaça} #the shell
{1581}{}{na carapaça}
{1582}{}{na carapaça}
{1583}{}{na carapaça}
{1584}{}{na carapaça}
{1585}{}{na carapaça}
{1586}{}{na carapaça}
{1587}{}{na carapaça}
{1588}{}{lugar indefinido}
#
# Lesser Radscorpion
#
{1590}{}{na cabeça}
{1591}{}{na cauda}
{1592}{}{na garra}
{1593}{}{na carapaça}
{1594}{}{nas patas dianteiras}
{1595}{}{nas patas traseiras}
{1596}{}{nos olhos}
{1597}{}{no cérebro}
{1598}{}{lugar indefinido}
#
# Lesser Death Claw
#
{1600}{}{na cabeça}
{1601}{}{no braço esquerdo}
{1602}{}{no braço direito}
{1603}{}{no tronco}
{1604}{}{na perna direita}
{1605}{}{na perna esquerda}
{1606}{}{nos olhos}
{1607}{}{na virilha}
{1608}{}{lugar indefinido}
#
# Giant Plant
#
{1650}{}{na boca}
{1651}{}{no talo} #the stalk
{1652}{}{no talo}
{1653}{}{no talo central} #the central stalk
{1654}{}{nas raízes} #the roots
{1655}{}{nas raízes}
{1656}{}{nas antenas} #the sense-tendrils
{1657}{}{na base} #the base
{1658}{}{lugar indefinido}
#
# Security Robot
#
{1660}{}{na cabeça}
{1661}{}{mísseis de mão} #the missile hand
{1662}{}{pistola de mão} #the gun hand
{1663}{}{no corpo}
{1664}{}{na perna direita}
{1665}{}{na perna esquerda}
{1666}{}{nos sensores}
{1667}{}{na parte inferior do tronco} #the lower torso
{1668}{}{lugar indefinido}
#
# Gecko 2
#
{1670}{}{na cabeça}
{1671}{}{na garra esquerda} #the left claw
{1672}{}{na garra direita} #the right claw
{1673}{}{no corpo}
{1674}{}{na perna direita}
{1675}{}{na perna esquerda}
{1676}{}{nos olhos}
{1677}{}{na virilha}
{1678}{}{lugar indefinido}
#
# Gecko
#
{1680}{}{na cabeça}
{1681}{}{na garra esquerda}
{1682}{}{na garra direita}
{1683}{}{no corpo}
{1684}{}{na perna direita}
{1685}{}{na perna esquerda}
{1686}{}{nos olhos}
{1687}{}{na virilha}
{1688}{}{lugar indefinido}
#
# Alien Thing
#
{1800}{}{na cabeça}
{1801}{}{no tentáculo esquerdo} #the left tentacle
{1802}{}{no tentáculo direito} #the right tentacle
{1803}{}{no corpo}
{1804}{}{no pé direito} #the right foot
{1805}{}{no pé esquerdo} #the left foot 
{1806}{}{nos olhos?}
{1807}{}{na virilha}
{1808}{}{lugar indefinido}
#
# End Boss
#
{1850}{}{na cabeça}
{1851}{}{no braço esquerdo}
{1852}{}{no braço direito}
{1853}{}{no tronco}
{1854}{}{na perna direita}
{1855}{}{na perna esquerda}
{1856}{}{nos olhos}
{1857}{}{na virilha}
{1858}{}{lugar indefinido}
#
# Alien Queen
#
{1860}{}{na cabeça}
{1861}{}{no tentáculo esquerdo}
{1862}{}{no tentáculo direito}
{1863}{}{no corpo}
{1864}{}{no pé direito}
{1865}{}{no pé esquerdo}
{1866}{}{nos olhos?}
{1867}{}{na virilha}
{1868}{}{lugar indefinido}
#
# Gun Turret 2
#
{1900}{}{no CPU}
{1901}{}{no servidor de arma} #the gun servo
{1902}{}{no servidor de arma}
{1903}{}{na estrutura}
{1904}{}{na base do servidor} #the servo base
{1905}{}{na base do servidor}
{1906}{}{nos sensores}
{1907}{}{no regulador}
{1908}{}{lugar indefinido}
#
# Giant Ant
#
{1970}{}{na cabeça}
{1971}{}{na pata dianteira esquerda}
{1972}{}{na pata dianteira direita}
{1973}{}{no abdômen}
{1974}{}{na pata traseira direita}
{1975}{}{na pata traseira esquerda}
{1976}{}{nas antenas} #the feelers
{1977}{}{no metatórax}
{1978}{}{lugar indefinido}
#
# Goris Robed
#
{1990}{}{na cabeça}
{1991}{}{no braço esquerdo}
{1992}{}{no braço direito}
{1993}{}{no tronco}
{1994}{}{na perna direita}
{1995}{}{na perna esquerda}
{1996}{}{nos olhos}
{1997}{}{na virilha}
{1998}{}{lugar indefinido}
#
# Goris UnRobed
#
{2000}{}{na cabeça}
{2001}{}{no braço esquerdo}
{2002}{}{no braço direito}
{2003}{}{no tronco}
{2004}{}{na perna direita}
{2005}{}{na perna esquerda}
{2006}{}{nos olhos}
{2007}{}{na virilha}
{2008}{}{lugar indefinido}
#
# Gun Turret 2
#
{2010}{}{no CPU}
{2011}{}{no servidor de arma}
{2012}{}{no servidor de arma}
{2013}{}{na estrutura}
{2014}{}{na base do servidor}
{2015}{}{na base do servidor}
{2016}{}{nos sensores}
{2017}{}{no regulador}
{2018}{}{lugar indefinido}

#
# Fruit Fly
#
{2030}{}{na cabeça}
{2031}{}{no ferrão} #the stinger
{2032}{}{nas antenas} #the antennae
{2033}{}{no tórax} #the thorax
{2034}{}{nas patas dianteiras}
{2035}{}{nas patas traseiras}
{2036}{}{nos olhos}
{2037}{}{nas asas}
{2038}{}{lugar indefinido}



#
# criticamente Hit Messages
#
# 5000 series - men (including generics)
#
{5000}{}{. Essa doeu} # . That really hurts
{5001}{}{. Um ferimento grave é inflingido} # . A serious wound is inflicted
{5002}{}{ sem a proteção da armadura} #  with no armor defenses
{5003}{}{. Ele foi nocauteado pelo violento ataque} # . The damaging attack knocks him unconscious
{5004}{}{. Ele cai no chão, nocauteado pelo golpe} # . The blow knocks him to the ground
{5005}{}{. O forte ataque na cabeça faz com que ele seja nocauteado} # . The strong blow to na cabeça knocks him out
{5006}{}{. O ataque destrói a têmpora. Boa noite, Bela Adormecida} # . The attack crushes the temple. Good night, Gracie
{5007}{}{. A morte é instantânea} # . Death is instantaneous
{5008}{}{, causando uma severa lesão no cotovelo} # , causing severe tennis elbow
{5009}{}{, tirando o braço da frente} # , pushing the arm out of the way
{5010}{}{, deixando um grande roxo} # , leaving a big bruise
{5011}{}{, danificando o braço esquerdo} # , crippling no braço esquerdo
{5012}{}{, deixando o braço esquerdo pendurado pela pele} # , leaving no braço esquerdo dangling by the skin
{5013}{}{. Esse braço agora é só um cotoco sangrento} # . That arm now looks like a bloody stump
{5014}{}{, danificando o braço direito} # , leaving a crippled right arm
{5015}{}{. Seu braço direito é pulverizado pelo poderoso ataque} # . His right arm is pulverized by this powerful blow
{5016}{}{ em um potente ataque} #  in a forceful blow
{5017}{}{, atravessando a armadura} # , blowing through the armor
{5018}{}{, infligindo um dano extra} # , inflicting an extra helping of damage
{5019}{}{ sem armadura, nocauteando o combatente} #  with no armor, knocking the combatant to the ground
{5020}{}{, expulsando o ar de seus pulmões. Ele cai no chão, fora da luta} # , knocking the air out. He slumps to the ground out of the fight
{5021}{}{. Infelizmente, agora é possível ver claramente sua coluna através do buraco em seu tronco} # . Unfortunately, his spine is now clearly visible from the front
{5022}{}{, ferindo gravemente sua perna} # , putting a major hurt on his leg
{5023}{}{, nocauteando-o como pinos num jogo de boliche depois de um belo strike} # , knocking him to the ground like a bowling pin in a league game
{5024}{}{, atropelando-o, danificando a perna} # , bowling him over and crippling that leg
{5025}{}{, quebrando feio seu joelho. Ele cai} # , smashing the knee into the next town. He falls
{5026}{}{. A intensa dor de perder a perna faz ele desistir} # . The intense pain of having a leg removed causes him to quit
{5027}{}{, inflingindo dor extra} # , inflicting some extra pain
{5028}{}{. Infelizmente, ele perde a visão} # . Unluckily, perdendo him, it causes blindness
{5029}{}{. Sem nenhuma proteção, o golpe causa uma dor severa} # . With no protection there, it causes serious pain
{5030}{}{, cegando-o com um golpe atordoador.} # , and blinding him with a stunning blow
{5031}{}{. a perda de um olho é muito pra ele, e ele desmaia, caindo no chão} # . The loss of an eye is too much, perdendo him, and he falls to the ground
{5032}{}{. Infelizmente, ele está preocupado de mais sentindo a falta de ar no cérebro pra perceber a morte chegando} # . Sadly, he is too busy feeling the rush of air on no cérebro to notice death approaching
{5033}{}{Ai! Essa doeu} # . Ouch! That had to hurt
{5034}{}{, e ele não está usando um protetor de saco.} # , and he's not wearing a cup, either
{5035}{}{. Sem proteção, ele cai no chão gemendo em agonia} # . Without protection, he falls over, groaning in agony
{5036}{}{. A dor é tanta que ele desmaia, caindo no chão feito um saco de merda} # . The pain is too much, perdendo him and he collapses like a rag
{5037}{}{. Ele susurra "Mamãe", enquanto seus olhos giram para trás de sua cabeça} # . He mumbles "Mother", as his eyes roll into the back of his head
#
# series 5100 - women
#
{5100}{}{. Essa doeu} # . That really hurts
{5101}{}{. Um ferimento sério é inflingido} # . A serious wound is inflicted
{5102}{}{ sem a proteção da armadura} #  with no armor
{5103}{}{. Ela foi nocauteada pelo violento ataque} # . The damaging attack knocks her unconscious
{5104}{}{. Ela cai no chão, nocauteada pelo golpe} # . The blow knocks her to the ground
{5105}{}{. O forte golpe na cabeça faz com que ela seja nocauteada.} # . The strong blow to na cabeça knocks her out
{5106}{}{. O ataque destrói sua têmpora. Boa noite, Bela Adormecida.} # . The attack crushes her temple. Good night, Gracie
{5107}{}{. A morte é instantânea} # . Death is instantaneous 
{5108}{}{, causando uma severa lesão no cotovelo} # , causing severe tennis elbow
{5109}{}{, tirando o braço da frente} # , pushing the arm out of the way
{5110}{}{, deixando um grande roxo} # , leaving a big bruise
{5111}{}{, danificando o braço esquerdo} # , crippling no braço esquerdo
{5112}{}{. O braço esquerdo agora está pendurado apenas por um fio de carne} # . o braço esquerdo is barely attached to her shoulder
{5113}{}{. Esse braço agora é só um cotoco sangrento.} # . That arm now looks like a bloody stump
{5114}{}{, danificando o braço direito} # , leaving a crippled right arm
{5115}{}{. O braço direito dela virou carne moida com o golpe} # . Her right arm is turned into hamburger by the blow
{5116}{}{ em um violento ataque} #  in a forceful blow
{5117}{}{, atravessando suas defesas} # , piercing through her defenses
{5118}{}{, inflingindo um dano extra} # , inflicting an extra helping of damage
{5119}{}{ sem armadura, derrubando a combatente nocauteada no chão} #  with no armor, knocking the female fighter to the ground
{5120}{}{, expulsando o ar de seus pulmões. Ela cai no chão, inconsciente} # , knocking the air out. She slumps to the ground
{5121}{}{. Infelizmente, a maioria dos órgãos vitais dela estão agora de fora} # . Unfortunately, her major organs have been exposed to the light
{5122}{}{, ferindo gravemente sua perna} # , putting a major hurt on her leg
{5123}{}{, fazendo ela desmaiar como se tivesse visto a maior barata do mundo} # , knocking her over like a bad blind date
{5124}{}{, derrubando-a e danificando sériamente esta perna} # , knocking her down and crippling that leg
{5125}{}{, quebrando feio seu joelho. Ela vai direto pro chão} # , smashing the knee into the next town. She takes the fast track to the ground
{5126}{}{. Ela grita de dor por causa da perna quebrada} # . She screams in pain from the broken leg
{5127}{}{, inflingindo dor extra} # , inflicting some extra pain
{5128}{}{, causando cegueira. Ela contorce o rosto} # , causing blindness. She grimaces
{5129}{}{. Sem proteção ali, ela sofre uma dor severa} # . With no protection there, it causes serious pain
{5130}{}{. O ferimento causa uma cegueira severa (como se existisse algum outro tipo)} # . The wound causes severe blindness, as if there is any other kind
{5131}{}{. Ela desmaia após perder a visão com o ataque} # . She faints from the blinding attack
{5132}{}{. Ela não tem tempo nem de pedir perdão à Deus antes de ir conhecê-lo pessoalmente} # . Sadly, she doesn't get to pray to her gods before she meets them
{5133}{}{. Ela aguenta que nem macho. Ou seja, doeu muito} # . She takes it like a man. That is to say, it hurts
{5134}{}{, derrubando-a no chão, nocauteada} # , knocking her to the ground
{5135}{}{. As chances dela ter filhos diminuem sériamente enquanto ela cai no chão feito uma boneca de pano} # . Her childbearing days are in trouble as she collapses in a limp heap
#
# series 5200 - children
#
{5200}{}{. A criancinha começa a chorar} #. The little kid starts to cry
{5201}{}{. Inconsciente, a criança cai no chão} #. Unconscious, the small child falls over
{5202}{}{. Ai} #. Ouchie
{5203}{}{. O ataque é forte, e a criança é nocauteada} #. The blow is true, and the child is knocked unconscious
{5204}{}{, esmagando a criança, que parece um boneco de pano quando é atingida} #, smashing the small child around like a limp rag
{5205}{}{. O braço esquerdo da criança agora está com um dodói} #. The left arm of this kid now has an owie
{5206}{}{, fazendo a criança perder o equilíbrio} #, throwing the small child off balance
{5207}{}{, quebrando o braço com um alto estalo. A criança começa a chorar muito} #, breaking that arm with a loud snap. Some serious tears start to flow
{5208}{}{, quebrando o braço facilmente, como se fosse um palitinho} #, easily snapping that arm like a small piece of candy
{5209}{}{. O braço direito começa a inchar, como um balão} #. The right arm starts to swell, like a balloon
{5210}{}{, e ela começa a chorar} #, and starts to cry
{5211}{}{ num lugar sensível} # in a sensitive spot
{5212}{}{. O ataque atinge um órgão vital, derrubando a criança no chão} #. The attack to a vital organ knocks the kid over
{5213}{}{, derrubando a criança como se fosse um brinquedo} #, knocking the little kid over like a toy
{5214}{}{. Agora essa criancinha não vai mais poder desfrutar a vida} #. Now this young child will never really experience life
{5215}{}{, inflingindo um corte profundo} #, inflicting a deep cut
{5216}{}{. O ataque faz com que a criança caia no chão, quebrando a perna} #. The attack bowls the child over, and breaks the leg
{5217}{}{, ferindo sériamente a criancinha} #, inflicting great harm to the small child
{5218}{}{. A criancinha olha pra cima e começa a chorar} #. The young child looks up and starts to cry
{5219}{}{, cegando a criança} #, which blinds the youth
{5220}{}{, esmagando o jovem nariz da criança} #, bashing in the youthful looking nose
{5221}{}{. Um corte aparece em cima dos olhos e o sangue começa a fluir livremente} #. A cut appears above the eyes and the blood starts to flow freely
{5222}{}{, o que faz com que seu olho fique parecendo uma uva explodida. A criança está desnorteada} #, which opens an eye like an exploding grape. The child looks bewildered
{5223}{}{, causando cegueira. A criança cai no chão} #, causing blindness. The young child drops to the ground
{5224}{}{, o golpe continua até atingir o pequeno cérebro} #, the blow continues into the small brain
{5225}{}{. A criança parece confusa e assustada} #. The child looks confused and shaken
{5226}{}{, nocauteando a criancinha, que cai no chão} #, knocking this young target to the ground
# #
# series 5300 - Super Mutants #
# #
{5300}{}{, ferindo o incrível mutante} #, hurting the mighty mutant
{5301}{}{, acertando um órgão vital} #, striking a vital spot
{5302}{}{, acertando um órgão vital e nocauteando o gigante} #, striking a vital spot and knocking the giant to the ground
{5303}{}{. O gigantesco mutante olha pros lados por um segundo, e depois cai no chão} #. The giant mutant looks around for a moment, and then slumps to the ground
{5304}{}{. A cabeça explode feito uma melancia gigante e sangrenta} #. The head explodes like a giant, bloody watermelon
{5305}{}{, ferindo gravemente o terrível mutante} #, severely hurting the mighty mutant
{5306}{}{. O gigante para por um segundo, amaldiçoando o universo} #, causing the giant to spend a moment cursing the universe
{5307}{}{, atingindo um nervo. O gigante é obrigado a segurar seu braço por causa da dor} #, striking a nerve and forcing the giant to grab his arm in pain
{5308}{}{. O ataque quebra o cutuvelo e provavelmente não foi uma sensação agradável} #. The blow breaks the elbow and probably didn't feel too good
{5309}{}{, quebrando o gigantesco braço, o que faz com que o sangue mutante comece a jorrar no chão} #, breaking the thick arm and spewing mutant blood over the ground
{5310}{}{, fazendo o gigante perder o equilíbrio por um momento, e então cair no chão feito uma árvore recém cortada} #, causing the giant to stumble for a moment and then collapse like a felled tree
{5311}{}{, e galões de tripas começam a cair no chão} #, and gallons of viscera spurt to the ground
{5312}{}{, fazendo o gigante cair voando no chão} #, sending the giant flying to the floor
{5313}{}{. O mutante treme e cai, sem conseguir suportar seu peso com a perna} #. The mutant stumbles and falls, his leg barely able to support him
{5314}{}{, acertando um lugar vital. O mutante cai com a perna quebrada} #, striking a vital location. The mutant crumples under a broken leg
{5315}{}{. A dor de uma perna quebrada domina o terrível gigante} #. The pain of a broken leg overwhelms the mighty giant
{5316}{}{, quase cegando o mutante} #, nearly blinding the mutant
{5317}{}{, cegando o agora furioso mutante} #, blinding the now-furious mutant
{5318}{}{, quase cegando o mutante, que perde o equilíbrio} #, nearly blinding the mutant but throwing him off balance
{5319}{}{. O mutante cego tropeça para trás, despreparado para o próximo ataque} #. The blinded mutant stumbles back, unprepared for the next attack
{5320}{}{, cegando o agora inconsciente mutante} #, blinding the now-unconscious mutant
{5321}{}{. Os olhos do mutante brilham por um momento, e depois as luzes se apagam - pra sempre} #. The eyes of the mutant glow for a moment, and then the light fades - permanently
# #
# series 5400 - Ghouls #
# #
{5400}{}{. O ghoul é surpreendido, e não consegue defender o ataque} #. The ghoul is surprised, and fails to defend against this attack
{5401}{}{. O ataque enterra este ghoul} #. The blow buries this ghoul
{5402}{}{. A mão do ghoul desnorteado se escancaram} #. The stunned ghoul's hand flies open
{5403}{}{, atravessando sua armadura e atingindo um ponto crítico} #, sneaking through his armor and striking a critical joint
{5404}{}{, atravessando a armadura e destruindo seu braço} #, sneaking through his armor and lopping the arm off
{5405}{}{. O ghoul vai pro lugar errado, na hora errada, e perde um olho} #. The ghoul moves the wrong way at the wrong moment, and loses an eye
{5406}{}{. O ghoul não está usando nenhuma armadura ai} #. The ghoul is wearing no armor there
{5407}{}{, e sem proteção, o ghoul fica cego} #, and without armor, the ghoul is blinded
{5408}{}{, causando um olhar desnorteado no ghoul em seus últimos momentos} #, causing the ghoul to look bewildered in his final moments
# #
# series 5500 - Brahmin #
# #
{5500}{}{, derrubando a grande besta no chão} #, knocking the big beast to the ground
{5501}{}{, atordoando os dois cérebros e derrubando o gigante animal} #, stunning both brains and felling the giant animal
{5502}{}{. A vaca mutante faz um alto som, claramente assustada} #. The mutant cow gives a loud, startled cry
{5503}{}{, quebrando uma das patas do Brahmin} #, breaking one of the Brahmin's legs
{5504}{}{, ferindo gravemente a vaca mutante} #, seriously hurting the mutant cow
{5505}{}{, penetrando facilmente na grossa carne do animal} #, easily penetrating the thick hide of the giant beast
{5506}{}{, atravessando diretamente os dois corações da vaca mutante} #, penetrating straight through both hearts of the mutant cow
{5507}{}{, cegando todos os olhos com um único ataque} #, blinding both sets of eyes with a single blow
{5508}{}{, cegando as duas cabeças e atordoando a vaca mutante} #, blinding both heads and stunning the mutant cow
{5509}{}{, cegando completamente o Brahmin, que cai nocauteado em seguida} #, completely blinding the Brahmin and knocking it out
{5510}{}{. O gigantesco mutante bovino perde o equilíbrio por um momento} #. The large mutant bovine stumbles for a moment
{5511}{}{. O Brahmin balança com ódio} #. The Brahmin shakes with rage
{5512}{}{. O Brahmin perde o ar com a dor} #. The Brahmin snorts with pain
{5513}{}{. O Brahmin fica bem chateado com esse ataque super devastador} #. The Brahmin is most upset with this udderly devastating attack
# #
# series 5600 - Radscorpions #
# #
{5600}{}{, fazendo o Radscorpion voar longe} #, sending the Radscorpion flying on its back
{5601}{}{, separando o cabeça da carapaça} #, separating the head from the carapace
{5602}{}{, danificando sériamente a cauda} #, seriously damaging the tail
{5603}{}{, ferindo sériamente suas garras} #, putting a major hurt on its claws
{5604}{}{. O ataque passa entre a grossa carapaça do Radscorpion} #. The blow slips between the cracks of the Radscorpion's tough carapace
{5605}{}{, atravessando a carapaça sem perder velocidade} #, striking through the tough carapace without pausing
{5606}{}{, perfurando a armadura natural e nocauteando o Radscorpion} #, passing through the natural armor and knocking the Radscorpion over
{5607}{}{. O Radscorpion não consegue lidar com uma sensação nova, tipo a de perder órgãos internos} #. The Radscorpion cannot cope with a new sensation, like missing internal organs
{5608}{}{, fazendo o escorpião voar longe e quebrando algumas de suas pernas} #, sending the 'scorpion flying and crippling some of its legs
{5609}{}{. O ataque abre um rasgo em uma parte desprotegida da perna, mutilando-a} #. The attack cuts through an unprotected joint on the leg, severing it
{5610}{}{, ferindo gravemente e cegando a criatura mutante} #, seriously wounding and blinding the mutant creature
{5611}{}{, penetrando quase até o cérebro. Isso que eu chamo de esmagar insetos} #, penetrating almost to the brain. Talk about squashing a bug
{5612}{}{, quase chegando até o cérebro, cegando a criatura ao invés disso} #, almost penetrating to the brain, but blinding the creature instead
{5613}{}{. O ataque é forte, e sofisticado de mais para que } #. The attack is fiendish, and far too sophisticated for this simple creature
{5614}{}{. Se fosse um humano, você poderia ter certeza de que ele estaria muito puto} #. If it was human, you would swear it's pretty pissed off
{5615}{}{, fazendo a pobre criatura cair no chão, sem os sentidos} #, knocking the poor creature senseless
{5616}{}{, deixando pedaços de seu cérebro no chão} #, spiking the brain to the floor
# #
# series 5700 - Rats #
# #
{5700}{}{. A cabeça do roedor faz sons nada saudáveis} #. The rodent's skull makes several unhealthy sounds
{5701}{}{, esmagando a cabeça do roedor como se fosse uma bola de papel molhada} #, squashing the rodent's skull like a wet paper bag
{5702}{}{, e a pata da esquerda agora está meio achatada} #, and the left paw now looks a little flat
{5703}{}{. A pata da esquerda do rato está completamente destruida} #. The left paw of the rat is blown off
{5704}{}{. A pata direita está gravemente ferida} #. The right paw is heavily damaged
{5705}{}{, explodindo a pata direita} #, blowing the right paw off
{5706}{}{. O rato é severamente ferido com este ataque} #. The rat is seriously wounded by this attack
{5707}{}{, ferindo gravemente o rato, que é nocauteado} #, seriously wounding the rat and knocking it around
{5708}{}{, espalhando o rato pelo chão} #, splattering the rat across the floor
{5709}{}{, quebrando a perna direita} #, crippling the right leg
{5710}{}{, fazendo um enorme buraco na perna esquerda} #, putting a big hole in the left leg
{5711}{}{, fazendo um dano extra devido a sensibilidade da área atingida} #, doing some extra damage due to the sensitive location
{5712}{}{. Sua alma foi arrebatada para conhecer o maravilhoso (porém pequeno) deus rato} #, summoning this creature to the great ratcatcher in the sky
# #
# series 5800 - Floaters #
# #
{5800}{}{. O floater cai no chão} #. The floater drops to the ground
{5801}{}{. O floater cai no chão, aparentemente morto} #. The floater falls to the ground, seemingly lifeless
{5802}{}{, deixando sérias sequelas que vão prejudicar bastante a vida da criatura} #, with serious consequences to the creature's continued existence
{5803}{}{, atordoando a terrível criatura} #, stunning the foul creature
{5804}{}{, atigindo uma área sensível e atordoando o floater} #, hitting a sensitive spot there and stunning the floater
{5805}{}{. O golpe faz com que a criatura trema violentamente, numa névoa de sangue} #. The blow causes the floater to shudder violently in a spray of crimson
{5806}{}{. O ataque causa algum tipo de reação violenta na criatura} #. The blow causing some sort of violent reaction in the creature
{5807}{}{. O floater de repente explode em chamas} #. The floater suddenly bursts into flames
{5808}{}{. A criatura sacode selvagemente e treme como um pudim surpreso} #. It jerks wildly and quivers like a pudding surprise
{5809}{}{, atingindo uma área sensível} #, with the blow hitting a sensitive spot
{5810}{}{. A criatura está obviamente agitada} #. The creature is obviously agitated
# #
# series 5900 - Centaurs #
# #
{5900}{}{. O centauro cai e fica atordoado} #. Pushed like a bad habit, the centaur falls over and is stunned
{5901}{}{ e o golpe atinge um ponto crítico} # as the blow strikes a critical spot
{5902}{}{, causando uma grande falha neurológica} #, causing massive neurological failure
{5903}{}{, atordoando-o com seu ataque violento} #, stunning it with your violent attack
{5904}{}{, ferindo gravemente o braço} #, crippling the arm
{5905}{}{, atingindo um ponto crítico. O braço está incapacitado} #, striking a critical spot. The arm is crippled
{5906}{}{, derrubando a criatura e ferindo gravemente a perna} #, knocking the creature over and crippling the leg
{5907}{}{, deixando o centauro atordoado enquanto cai com uma perna incapacitada} #, stunning the centaur as it is knocked over with a crippled leg
{5908}{}{, cegando a cabeça} #, blinding a head
{5909}{}{, surpreendendo o centauro. Ele tropeça cegamente por um momento} #, surprising the centaur. It blindly stumbles for a moment
{5910}{}{, surpreendendo o centauro. Ele cai como um monte de merda} #, surprising the centaur. It collapses in a heap
{5911}{}{, surpreendendo o centauro. Ele cai em uma pilha de gosma} #, surprising the centaur. It collapses in a pile of goo
{5912}{}{. O ataque não foi tão eficaz como poderia ter sido} #. The attack was not as effective as it could have been
# #
# series 6000 - Robots #
# #
{6000}{}{, causando alguns danos estruturais} #, inflicting some structural damage
{6001}{}{. Faíscas voam e o robô fica momentaneamente fora de controle} #. Sparks fly and the robot goes momentarily out of control
{6002}{}{, atingindo um componente crítico que deixa o robô fora de controle} #, hitting a critical component and forcing the robot out of control
{6003}{}{, atingindo um componente crítico que causa um gigantesco mau funcionamento} #, hitting a critical component and causing a massive malfunction
{6004}{}{. O robô tenta se manter em pé} #. The robot attempts to compensate
{6005}{}{. As robô luta para não cair} #. The robot strains to compensate
{6006}{}{, atingindo uma parte crítica que causa danos pesados} #, hitting some key part and causing heavy damage
{6007}{}{, causando um gigantesco dano estrutural} #, inflicting heavy structural damage
{6008}{}{, atingindo um componente crítico e causando graves danos} #, hitting a critical component and causing severe damage
{6009}{}{. O robo treme diante desde intenso ataque} #. The robot shudders under this intense attack
{6010}{}{, desmontando o robô} #, dismantling the robot
{6011}{}{. O robô tenta compensar, mas não consegue, caindo no chão} #. The robot attempts to compensate, but fails, falling to the ground
{6012}{}{. O robô cede sobre a pressão, caindo no chão} #. The robot strains under the pressure, falling to the ground
{6013}{}{, Quebrando as lentes do sensor} #, breaking the sensor lenses
# #
# series 6100 - Dogs #
# #
{6100}{}{, derrubando o cão no chão} #, knocking the pooch to the ground
{6101}{}{, bem no meio do focinho} #, right across the snout
{6102}{}{. O cão cai no chão, mas ainda está respirando} #. The dog falls over, but it is still breathing
{6103}{}{. O animal tosse uma nuvem de sangue} #. The animal coughs up a spurt of blood
{6104}{}{, quebrando a perna} #, crippling the leg
{6105}{}{, quebrando a perna. O animal tenta se manter em pé, mas não consegue} #, crippling the leg. The animal tries to remain standing, but fails
{6106}{}{. O animal cego uiva com a dor} #. The blinded animal howls in pain
{6107}{}{, neutralizando o pobre animal} #, neutering the poor animal
# #
# series 6200 - Manti #
# #
{6200}{}{, Derrubando esse inseto mutante} #, knocking down this mutated insect
{6201}{}{. ele cai no chão} #. It collapses
{6202}{}{. O manti se pergunta se deve ou não continuar vivendo} #. The manti ponders whether or not to continue living
{6203}{}{, quebrando o membro} #, crippling the limb
{6204}{}{, fazendo o Manti lamber suas feridas. Ele segura seu membro de forma... curiosa} #, causing the manti to lick its wounds. It holds the limb oddly
{6205}{}{, ignorando a armadura de sua resistente carapaça} #, bypassing the chitinous armor
{6206}{}{. O Manti grita e se contorce de uma maneira nada humana} #. The manti shrieks and shivers most inhuman like
{6207}{}{, o que faz com que o Manti caia. Um membro fica curvado em um ângulo estranho. Isso deve doer} #, which causes the manti to fall over. A limb is bent at an odd angle
{6208}{}{, rasgando as asas} #, shredding the wings
{6209}{}{, ignorando a armadura de carapaça e jogando o Manti pra longe} #, bypassing the chitinous armor and throwing the manti around
{6210}{}{, cegando o inseto com um golpe preciso} #, blinding the insect with an accurate blow
# #
# series 6300 - Deathclaw #
# #
{6300}{}{. Até mesmo essa besta parece desorientada com este ataque brutal} #. Even this beast seems fazed by that stunning attack
{6301}{}{, escorregando pelas enormes garras para atingir o monstro. O Deathclaw se chacoalha e grunhe} #, slipping past the huge claws to strike the monster. The Deathclaw shakes and growls
{6302}{}{. O resultado é um enome estrago nos olhos do Deathclaw} #. The result is massive damage to the Deathclaw's eyes
# #
# series 6400 - Spore Plant  # Was The Master #
# #
{6400}{}{, ignorando as defesas da planta} #, breaking past the plant's defenses
{6401}{}{, arrancando algumas de suas folhas} #, tearing some of its leaves off
{6402}{}{, quebrando alguns de seus galhos} #, breaking some of its fronds
{6403}{}{. Esse ataque violento tiraria todo o fôlego da planta, se ela tivesse pulmões} #, damaging its chlorophyll intake
{6404}{}{, espirrando pólem pra todos os lados} #, knocking the pollen out of it
{6405}{}{, quase a derrubando} #, almost tipping it over
{6406}{}{, danificando alguns de seus galhos} #, damaging some of its branches
#
# series 6500 - The Player
#
{6500}{}{. Você vai ter uma dor de cabeça forte amanhã, se sobreviver até lá} #. You'll have a headache tomorrow, if you live that long
{6501}{}{. Sua armadura não te protege desse ataque certeiro} #. Your armor provides no protection from this well-aimed blow
{6502}{}{. Você sente uma dor forte por um momento, e depois tudo fica preto..} #. You feel the pain for just a moment, and then darkness takes you..
{6503}{}{, ignorando sua armadura. O golpe te derruba no chão} #, bypassing your armor. The blow knocks you off your feet
{6504}{}{. O choque faz você enchergar tudo preto. Depois de uns segundos, você percebe que sua visão não voltou} #. The shock makes your vision go dark. After a moment, you notice that your vision has not returned
{6505}{}{. Você dá uma bela olhada no seu coorpo enquanto sua cabeça viaja pelo ar} #. You get a nice view of your body as your head sails through the air
{6506}{}{. De forma surpreendete, o golpe não é tão pior que o normal} #. Surprisingly, the damage feels no worse than normal
{6507}{}{, te desorientando por um momento} #, stunning you for a moment
{6508}{}{. Sinta a dor} #. Feel the pain
{6509}{}{. O ataque deixa seu braço inutilizado} #. The attack leaves your arm useless
{6510}{}{, atravessando sua armadura. O golpe quebra os ossos de seu braço como se fossem gravetos} #, slipping past your armor. The blow cracks the bones in your arm like deadwood
{6511}{}{, atravessando sua armadura. Seu braço agora está pendurado por um fio no seu ombro} #, bypassing your armor. Your arm now hangs limply at your side
{6512}{}{. Vai ficar um roxo enorme, e talvez as cicatrizes sirvam de assunto nas próximas festas} #. The bruise will look nice, and maybe the scars will make good party talk
{6513}{}{, destruindo seus órgãos internos. Tudo que você pode fazer é gargarejar sangue} #, crushing your internal organs. All you can do is gurgle blood
{6514}{}{, te jogando de cabeça pra baixo. Você dá quase um mortal} #, sending you head over heels
{6515}{}{, você sai voando com a perna quebrada} #, sending you flying and breaking your leg
{6516}{}{, passando por sua armadura como se fosse manteiga. O pancada te derruba no chão, e fere seriamente seu joelho} #, melting through your armor. The blow knocks you over and seriously hurts your knee
{6517}{}{. A dor da sua perna quebrada faz você desmaiar} #. The pain from your broken leg sends you into unconsciousness
{6518}{}{. A pancada faz você se contorcer um pouco, mas nada além disso} #. The painful blow makes you flinch, but does little else
{6519}{}{. Pro seu azar, você fica cego imediatamente} #. Unluckily for you, it also causes immediate vision loss
{6520}{}{. Ai. Você perde um tempinho tentando limpar o sangue dos seus olhos} #. I. It takes you a moment to wipe the blood from your eyest takes you a moment to wipe the blood from your eyes
{6521}{}{, atravessando sua armadura. Você fica sem direção até perceber que você perdeu a visão} #, slipping past your armor. You stand stunned as your realize you cannot see anymore
{6522}{}{. Você sente uma coisa estranha na cabeça. Você percebe que é morte cerebral iminente} #. You feel a strange sensation in your head. You realize it's imminent brain-death
{6523}{}{, fazendo você gritar} #, making you cringe
{6524}{}{. Você segura sua virilha e cai no chão, sentindo uma terrível dor} #. You cup your groin and fall to the floor in pain
{6525}{}{. A dor é tão grande que você desmaia. Eu não queria ser você agora} #. The pain is sufficient to knock you out. Ouch
{6526}{}{. Não existem palavras no universo pra descrever a dor que você está sentindo neste momento} #. There are not enough words in the universe to describe the pain you are feeling at this moment
# Fallout 2:
#
# series 6700 - Gecko
#
{6700}{}{, ultrapassando as defesas do lagarto} #, breaking past the lizard's defenses
{6701}{}{, arrancando um pedaço de sua pele gosmenta} #, tearing some of its slimy skin off
{6702}{}{, quebrando alguns de seus dedos} #, breaking some of its digits
{6703}{}{, prejudicando seriamente a habilidade do Gecko respirar} #, damaging its breathing ability
{6704}{}{. Que pancada} #, knocking the stuffing out of it
{6705}{}{, quase derrubando o Gecko no chão} #, almost tipping it over
{6706}{}{, danificando sériamente alguns de seus membros} #, damaging some of its limbs
#
# series 6800 - Alien
#
{6800}{}{, atravessando as defesas da criatura} #, sliding past the creature's defenses
{6801}{}{, fazendo voar gosma pra todos os lados} #, smearing some of its slime off
{6802}{}{, destruindo seus... o que é isto mesmo? Eca } #, mashing some of its suction-feelers
{6803}{}{, danificando sua habilidade de... respirar (?)} #, damaging its air (?) intake
{6804}{}{, fazendo voar uma coisa nojenta} #, knocking the icky stuff out of it
{6805}{}{. A criatura quase cai no chão} #, almost tipping it over
{6806}{}{, danificando alguns de seus tentáculos} #, damaging some of its tentacles
#
# series 6900 - Giant Ant
#
{6900}{}{, ultrapassando as defesas da formiga} #, breaking past the ant's defenses
{6901}{}{, arrancando uma de suas antenas fora} #, ripping some of its antennae off
{6902}{}{, quebrando algumas de suas pernas} #, breaking some of its feelers
{6903}{}{, ferindo a formiga gravemente} #, damaging its health
{6904}{}{, fazendo com que ela tropece um pouco} #, knocking it around a bit
{6905}{}{, deixando a formiga atordoada} #, almost tipping it over
{6906}{}{, danificando uma parte de seu exoesqueleto} #, damaging some of its exoskeleton
#
# series 7000 - Gun Turret  -- WIP! Won't Work!
#
{7000}{}{, passando pelas defesas da formiga} #, breaking past the ant's defenses
{7001}{}{, arrancando algumas de suas antenas} #, ripping some of its antennae off
{7002}{}{, quebrando alguns de seus sensores} #, breaking some of its feelers
{7003}{}{, danificando sua estrutura} #, damaging its health
{7004}{}{, derrubando-o um pouco pro lado} #, knocking it around a bit
{7005}{}{, quase o derrubando} #, almost tipping it over
{7006}{}{, danificando partes de seu exoesqueleto} #, damaging some of its exoskeleton
#
# Series 7100 - End Boss
#
{7100}{}{, ultrapassando a armadura} #, blowing past the Bodyguard's armor
{7101}{}{, fazendo ele cair de joelhos} #, bringing the Bodyguard to his knees
{7102}{}{, destruindo o mecanismo que controla seu braço} #, destroying his arm control mechanism
{7103}{}{, destruindo o mecanismo que faz sua perna se movimentar} #, destroying his leg rotator mechanism
{7104}{}{, estourando seu olho biônico} #, shattering his bionic eye
{7105}{}{, fazendo ele parar por alguns segundos se recompondo de seu ataque destruidor} #, causing him to pause and shake off your massive attack
{7106}{}{, compactando seu peitoral mecânico} #, compacting his chest plate