# Matheus Reis Traduzido
# Noob-Saibot revisou este arquivo.

# It looks like a generator
{100}{}{Parece ser um gerador.}
# This generator probably powers the elevator.
{101}{}{Este gerador provavelmente alimenta o elevador.}
# The generator needs repairs first.
{200}{}{O gerador precisa de conserto primeiro.}
# The generator is already running.
{201}{}{O gerador já está funcionando.}
# You shutdown the generator.
{202}{}{Você desliga o gerador.}
# That skill is useless on a generator.
{300}{}{Essa habilidade é inútil em um gerador.}
# You repair the generator and start it up.
{400}{}{Você conserta e inicia o gerador.}
# You failed to repair the generator.
{401}{}{Você não conseguiu reparar o gerador.}