# Matheus Reis traduzido.
# Revisado por Noob-Saibot

#############################################################
#  Message File: kcitizen.msg                               #
#                                                           #
#       Body Type:  NAROBE                                  #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
# You see one of Klamath's citizens
{100}{}{Você vê um dos cidadãos de Klamath.}
# You see one of Klamath's citizens
{101}{}{Você vê um dos cidadãos de Klamath.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

# Why don't you go back to your tribe?
{150}{}{Por que você não volta para sua tribo?}
# I'll give you some pretty beads if you leave me alone
{151}{}{Te dou umas miçangas bonitas se você me deixar em paz.}
# Nice tribal, good tribal, don't hurt me
{152}{}{Bom tribal, bom tribal, não me machuque.}
# I sure wish we had a wall around the town.
{153}{}{Eu com certeza gostaria que tivéssemos um muro ao redor da cidade.}
# I don't have anything to steal; go away.
{154}{}{Eu não tenho nada para você roubar; vai embora.}
# Why are you looking at me like that?
{155}{}{Por que você está olhando para mim desse jeito?}
# Great, another tribal.
{156}{}{Ótimo, mais um tribal.}
# Why don't you go back to the golden gecko?
{157}{}{Por que você não volta para o gecko dourado?}
# Just keep away from me.
{158}{}{Fica longe de mim.}
# We don't need you stirring up trouble.
{159}{}{Não precisamos de você causando problemas por aqui.}
# You must have come north from the Den.
{160}{}{Você deve ter vindo do norte de Den.}
# Last thing we need is more like you.
{161}{}{A última coisa que precisamos é de pessoas como você.}

# Hello there, stranger.
{170}{}{Olá, visitante.}
# I sure hope the trapping's good this season.
{171}{}{Espero que a gente tenha uma boa temporada de caça.}
# Lots of brahmin going missing lately.
{172}{}{Muitos brahmin têm sumido ultimamente.}
# (Crunch, crunch) Dunton's Drymeat sure is yummy.
{173}{}{(Mastiga com ruido) A carne seca dos Dunton é com certeza deliciosa.}
# Did you come here to trade hides for firewater?
{174}{}{Você veio aqui para trocar couro por cachaça?}
# I thought all your people put a bone through their noses
{175}{}{Pensei que todos do seu povo colocavam um osso atravessando o nariz.}
# Watch out for the rats in Trapper Town.
{176}{}{Cuidado com os ratos do Bairro dos Caçadores.}
# Now where'd I put those magic beans?
{177}{}{Onde é que eu coloquei aqueles feijões mágicos?}
# Geckos taste just like canned chicken, if you cook them right.
{178}{}{Geckos têm gosto de galinha enlatada, se você cozinhá-los direito.}
# I'm going to relax at the Bathhouse.
{179}{}{Tô indo relaxar na casa de banho.} # Não sei se foi essa a tradução que vocês deram à bathhouse
# Watch out for the Duntons.
{180}{}{Cuidado com os Duntons.}
# Buckner house always gives me a fair price on my goods.
{181}{}{A Buckner House sempre dá um preço justo nos meus bens.}
# Nice day today.
{182}{}{Está um ótimo dia hoje.}
# You look like Sulik
{183}{}{Você se parece com o Sulik.}
# I wonder where that idiot Torr has gone?
{184}{}{Gostaria de saber para onde foi aquele idiota do Torr?}
# The big secret is - hey, what's this in my pocket?!?
{185}{}{O grande segredo é - hey, o que é isso no meu bolso?!?}
# No rest for the poor.
{186}{}{Alegria de pobre dura pouco...}
# My joints ache; weather must be changing.
{187}{}{Minhas juntas estão doendo; o tempo deve estar mudando.}
# Wind's picking up a bit.
{188}{}{O vento está um pouco forte.}

# Nice to see you.
{190}{}{Prazer em vê-lo.}
# Any more like you at home?
{191}{}{Tem mais de você na sua vila?}
# Hope you're enjoying Klamath.
{192}{}{Espero que esteja gostando de Klamath.}
# We could use a few more people of your caliber here.
{193}{}{Nós poderíamos usar mais pessoas do seu caráter aqui.}
# What's up, friend?
{194}{}{Como vai, colega?}
# Good fortune to you.
{195}{}{Que a sorte esteja sempre em seu favor.}
# If you need to buy anything, go to Buckner House.
{196}{}{Se você precisar comprar algo, vá para a Buckner House.}
# You're not like Sulik at all.
{197}{}{Você não parece nada com o Sulik, afinal.}
# You're the most civilized tribal I've ever met.
{198}{}{Você é o tribal mais civilizado que eu já conheci.}
# Watch out for geckos that have changed color.
{199}{}{Cuidado com os geckos de cores diferentes.}
# Hello, traveler.
{200}{}{Olá, viajante.}
# Glad to have you in Klamath.
{201}{}{Fico feliz em tê-lo em Klamath.}
# Howdy, stranger.
{202}{}{Olá, visitante.}
# Watch out for those Duntons; they're dangerous
{203}{}{Cuidado com estes Duntons; eles são perigosos.}
# Trapper Town sure has a lot of rats
{204}{}{O Bairro dos caçadores com certeza tem um monte de ratos.}

#############################################################
#  TELL ME ABOUTS WILL BE REMOVED                           #
#############################################################

{1000}{}{Anciã}
{1001}{}{Fundador}
{1002}{}{Vault Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Escolhido}
{1007}{}{Xamã}
{1008}{}{Hakunin}
{1009}{}{Healing Powder}
{1010}{}{Ponte}
{1011}{}{Mynoc}

{1100}{}{A anciã é a sua mãe e nossa lider.} # The Elder is your mother and our leader
{1101}{}{Nosso grande ancestral, que nos deu conhecimento.} # Our great ancestor who gave us knowledge.
{1102}{}{O primeiro a lutar e vencer o caos.} # The first to fight and win over chaos.
{1103}{}{Essa seria a nossa bela aldeia.} # That would be our beautiful village.
{1104}{}{É um posto avançado de troca que fica a alguns dias a leste daqui.} # That's trading outpost a few days east of here.
{1105}{}{O Vault é o céu.} # The Vault is heaven.
{1106}{}{Você é O Escolhido.} # You are the Chosen One.
{1107}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1108}{}{Ele nos cura com suas ervas e magia. Ele está localizado ao norte da nossa aldeia.} # He heals us with his herbs and magic. He is in the north part of our village.
{1109}{}{É um pó mágico que vai curá-lo, mas vai te deixar sonolento.} # It is a magic powder which will heal you, but will make you sleepy.
{1110}{}{A Grande Ponte fica ao sul de nossa aldeia.} # The Great Bridge exits our village in the south.
{1111}{}{Ele protege a ponte que dá acesso à nossa aldeia.} # He guards the bridge leading into our village.