{100}{}{Você entra em uma série de túneis abaixo do Bairro dos caçadores. O cheiro de bosta de rato é bem forte.}
{101}{}{A explosão faz com que as vigas danificados quebrem e um desmoronamento de rochas aconteça. Quando isso ocorre, você escuta o que parece ser um eco forte por toda a caverna. Conforme você olha ao redor você vê que as outros vigas fracas estão começando a ceder.}
{103}{}{Você encurralou o Rei Rato! Sem possibilidades de fugir, a fome é a única coisa que resta para ele desfrutar.}
{104}{}{Melhor eu sair do caminho dessas vigas antes que seja esmagado até a morte ou fique preso.}
{105}{}{Mais um viga destruída e a caverna vai desmoronar.}


#You enter a series of tunnels beneath Trapper Town. The smell of rat droppings is quite strong.
#The explosion causes the damaged supports to break and an avalanche of rocks comes down from above. As this occurs, you hear what seems to be a loud crack echo throughout the cavern. As you look around you see that the other weak supports are beginning to give way.
#You have trapped Keeng Ra'at! With no means out, starvation is all that is left for him to enjoy.
#I better get out of the way of these supports before I get crushed to death or trapped.
#Another support beam gives way and an avalanche of rocks comes tumbling down.
