#An old, broken down Highwayman.
{100}{}{Um velho, e quebrado Highwayman.} 
#This machine is in much worse shape than it looks -- nothing will make this run again. Looks like there's a box of engine parts on the back seat that's still in pretty good shape, though.
{110}{}{Essa máquina está em um estado pior do que parece -- nada vai fazer isso funcionar de novo. Parece, entretanto, que tem uma caixa com peças de motores no banco de trás que ainda está em bom estado.}
#This machine is in bad shape. There's a package on the back seat, though.
{111}{}{Essa máquina está em mau estado. Entretanto, tem um pacote no banco de trás.}
#This machine looks about the same as the others out front. Looks like there's a package on the back seat.
{112}{}{Essa máquina parece igual as outras da frente. Parece que tem um pacote no banco de trás.}
#This old machine is in great shape! I bet I could fix it up somehow. If only I had the parts...
{113}{}{Essa máquina velha está em um estado ótimo! Aposto que poderia consertá-la de algum jeito. Se eu pelo menos tivesse as peças...}
#The engine looks too badly rusted to fix. While you were looking the car over, you found a bottle of fuel additive that looks as though it would burn really well.
{120}{}{Esse motor parece muito enferrujado para ser consertado. Enquanto você está olhando no carro, você encontra uma garrafa de combustível aditivo que parece queimar muito bem.}
#The engine is nothing but a pile of rust that falls apart as soon as you open the hood.
 {121}{}{O motor não é nada mais do que um monte de ferrugem que desmorona assim que você abre o capô.}
#This is a real fixer-upper. I guess I don't have the skill or parts to get this running yet.
{122}{}{Isso é realmente algo divertido de consertar. Eu acho que não tenho a habilidade ou as peças para arrumar isso ainda.}
#Looks as though this baby's almost ready to rock. Just a few more turns on this nut... (You jump back in surprise as the engine falls out of the car, collapsing into a pile of rust and component parts.)
{123}{}{Embora pareça que esse bebê está quase pronto para rodar. Só mais algumas voltas nesse parafuso... (Você pula para trás surpreso quando o motor cai do carro, desmoronando em uma pilha de ferrugem e peças.)}
#You find a fuel-injection system in the back seat.
 {130}{}{Você encontra um sistema de injeção de combustível no banco traseiro.}