#You see a guard dog.
{100}{}{Você vê um cão de guarda.}
#You see a wild dog.
{101}{}{Você vê um cão selvagem.}

#You see a guard dog.
{120}{}{Você vê um cão de guarda.}
#You see a wild dog.
{121}{}{Você vê um cão selvagem.}

{200}{}{:: GROWL ::}
{201}{}{:: SNARL ::}
{202}{}{:: ROOF ::}

{205}{}{Woof}
{206}{}{Woof woof}

#The dogs seem to be trained to protect what's inside the shed.
{210}{}{Os cães parecem ser treinados para proteger o que esta dentro do galpão.}
#Doggy no like me.
{211}{}{Doggy não gosta de mim.}
#Good doggy!
{212}{}{Bom cãozinho!}

#This dog looks like it could really tear you up if it needed to.
{250}{}{Este cão parece que poderia realmente rasgar-te se ele precisasse.}

#added by killap
#You killed all the dogs attacking the brahmin.
{300}{}{Você matou todos os cães que atacam os brahmin.}
