# Before Jonny Found
{100}{}{Sob-}
{101}{}{Jonny…}
{102}{}{Sniff...}
#I miss my son.
{103}{}{Eu sinto falta do meu filho.}

# Player accepts find Jonny Seed
#Please find Jonny.
{110}{}{Por favor, encontre Jonny.}

# After Jonny Found
#Please bring Jonny back.
{120}{}{Por favor, traga de volta Jonny.}

# Jonny Returned
#Thank you for returning Jonny to me.
{121}{}{Obrigado pelo regresso Jonny para mim.}

# looks
#You see Balthas' wife.
{150}{}{Você vê a esposa Balthas.}
#You see Balthas' wife. She looks pretty upset.
{151}{}{Você vê esposa Balthas '. Ela parece muito chateada.}
#You see Balthas' wife. She appears to be in a pleasant mood now.
{152}{}{Você vê esposa Balthas '. Ela parece estar em um clima agradável agora.}
