#You see a heavy set man wearing a leather apron.
{100}{}{Você vê um homem com o conjunto usando vestindo é um avental de couro.}
#You see Balthas the tanner.
{101}{}{Você vê Balthas o curtidor.}
#You see a tall, muscular man who looks and smells of leather.
{102}{}{Você vê um homem alto e musculoso que parece e tem cheiro de couro.}

#My son was mistakenly killed in the fight.
{151}{}{Meu filho foi morto por engano na luta .}
#I can't bear to live without Jonny.
{152}{}{Eu não posso suportar viver sem Jonny.}
{153}{}{[Sob]}
#Meet us down at the Ghost Farm. We're going to attack the ghosts.
{154}{}{Encontre conosco lá em baixo, para o Santo Farm. Nós vamos atacar os fantasmas.}
#Hello, my name's Balthas. I run the tannery here in Modoc. Can I help you?
{155}{}{Olá, Balthas é meu nome. Eu trabalho com a retirada de couro aqui em Modoc. Posso ajudar?}
#You seem a bit preoccupied; is there something wrong?
{156}{}{Você parece um pouco preocupado; Há algo de errado?}
#I'd like to see your wares.
{157}{}{Eu gostaria de ver seus produtos.}
#Have you seen a gold watch lying around anywhere?
{158}{}{Você já viu um relógio de ouro por aí em algum lugar?}
#I'll be back later.
{159}{}{Volto mais tarde.}
I'm searching for an item called a GECK. Do you by any chance know anything about it, or how I
 might obtain one?
{160}{}{Estou à procura de um item chamado de GECK. Você por acaso sabe alguma coisa sobre isso, ou como eu
  posso obter um?}
{161}{}{GECK?}
#What can I help you with?
{163}{}{O que posso ajudá-lo?}
#Just looking, thanks.
{168}{}{Só estou olhando, obrigado.}
#Any luck finding Jonny?
{171}{}{Sorte para encontrar Jonny?}
#I found this at the bottom of the old dry well. A part of the well had fallen in, and
 this was in the debris. I'm sorry, but I believe Jonny is dead.
{172}{}{Eu encontrei este na parte inferior do poço seco antigo. Uma parte do poço tinha caído, ele foi nos escombros. Sinto muito, mas eu acredito que Jonny está morto.}
#No, nothing yet.
{173}{}{Não, nada ainda.}
#Thank you for returning my boy to me. There's no way I can ever repay you, but please take this
 leather armor as thanks. I've been experimenting with a new curing process; I think you'll find this
 armor very durable, and besides -- you look really good in it.
{175}{}{Obrigado por devolver meu filho para mim. Não há nenhuma maneira que eu posso recompensá-lo, mas por favor, tome este
  armadura de couro, como agradecimento. Estive a experimentar com um novo processo de cura; Acho que você vai encontrar este
  armaduras muito durável, e, além disso - olhar você realmente é bom nisso.}
#Thank you for saving my son!
{176}{}{Obrigado por salvar o meu filho!}
#Please leave me to my grief.
{177}{}{Por favor, me deixe com a minha dor.}
#onny is alive! Some people called Slags have rescued him. If you can wait just a little longer,
 I'm working on a way to get Jonny back home to you.
{178}{}{Jonny is alive! Some people called Slags have rescued him. If you can wait just a little longer,
 I'm working on a way to get Jonny back home to you.}
#Jonny is alive! Some people called Slags have rescued him. If you can wait just a little longer,
 I'm working on a way to get Jonny back home to you.
 {179}{}{Jonny está vivo! Algumas pessoas te chamam de Escória por tê-lo resgatado. Se você puder esperar um pouco mais,
Eu estou trabalhando em uma maneira de obter Jonny de volta a casa para você.}
#I understand; sorry to disturb you.
{180}{}{Entendo; Desculpe incomodá-lo.}
#Huh? Look, I don't discuss my personal life with strangers. Do you have any business with me or
 not?
{181}{}{Hein? Olha, eu não discuto minha vida pessoal com estranhos. Você tem algum negócio comigo ou
  não?}
#Pardon me, my name is
{182}{}{Perdoe-me, meu nome é}
#. Now that we're properly introduced, you seem troubled.
{183}{}{. Agora que estamos devidamente apresentados, você parece incomodado.}
#Yes, I'm interested in some leather goods.
{184}{}{Sim, eu estou interessado em alguns artigos de couro.}
#I guess I don't.
{186}{}{Eu acho que não.}
#Did you say
{187}{}{Será que quis dizer }
#? Yes, I think I've heard of you. One of the guards on a passing caravan mentioned some good
 things about a person with that name. I know we've just met, but I could really use your
 help.
{188}{}{? Sim, eu acho que eu ouvi falar de você. Um dos guardas em uma caravana mencionado algo de bom
  sobre uma pessoa com esse nome. Eu sei que você acabou de conhecer, mas eu poderia realmente usar o seu
  socorro.}
#Why don't you tell me what your problem is, and maybe I'll be able to help.
{189}{}{Por que você não me fala qual é seu problema, que talvez eu vou ser capaz de ajudar.}
#I have problems of my own, sorry.
{190}{}{Eu tenho meus próprios problemas, desculpe .}
#He picks up a metal chisel and starts to wring it anxiously. To your amazement, the chisel begins
 to bend like putty. This guy's strong!] My boy, Jonny, is missing! He went out to play a few days ago and
 never came back. We've searched everywhere, but still haven't found him.
{191}{}{[Ele pega um cinzel de metal e começa a torcer-lo ansiosamente. Para seu espanto, o cinzel começa
a dobrar como massa de vidraceiro. Forte] Meu menino cara!, Jonny, está faltando! Ele saiu para jogar há alguns dias e
nunca mais voltou. Nós temos procurado em todos os lugares, mas ainda não o encontramos.}
#Where does Jonny normally play? Does he usually play with someone else?
{192}{}{Onde é que Johnny jogar normalmente? Será que ele costuma jogar com outra pessoa?}
#I'm sorry about your kid, but what could I possibly do?
{193}{}{Sinto muito pelo seu filho, mas o que eu poderia fazer?}
#That's horrible! But I just stopped in to look at some leather goods. I don't suppose I could
 see some of your merchandise?
{194}{}{Isso é horrível! Mas eu só parei para olhar alguns artigos de couro. Eu não suponho que eu poderia
  ver alguns de suas mercadorias?}
#Oooh! Look at the time. I have to be going.
{195}{}{Oooh! Olhe para o tempo. Eu tenho que ir.}
#Does that mean you'll help me? Thank you! Jonny was last seen playing cowboys and Indians with
 his dog Laddie out front. The two of them are inseparable; in fact, that's how we knew something was
 wrong. One day, Laddie came back without Jonny. We've been searching ever since. Take Laddie with
 you; maybe the two of you will be able to find Jonny.
{196}{}{Isso quer dizer que você vai me ajudar? Obrigado! Jonny foi visto pela última vez brincando com cowboys e índios
  seu cão Laddie em frente. Os dois eram inseparáveis; na verdade, é assim que soube que algo estava
  errado. Um dia, Laddie voltou sem Jonny. Nós temos procurado desde então. Tome Laddie com
  você; talvez os dois de você será capaz de encontrar Jonny.}
#Well, you have the air of an experienced traveler. With your skills, maybe you'll be able to
 track down my son.
{197}{}{Bem, você tem o ar de um viajante experiente. Com suas habilidades, talvez você vai ser capaz de
  rastrear o meu filho.}
#Well, yes! I am quite a skillful tracker, if I do say so myself. Okay, I'll help.
{198}{}{Bem, sim! Eu sou um rastreador bastante hábil, se eu digo assim sou eu. Ok, eu vou ajudar.}
#Flattery will get you nowhere. Look, I need to ask you some questions.
{199}{}{Flattery levarão a lugar nenhum. Olha, eu preciso lhe fazer algumas perguntas.}
#My prayers are answered! Take Laddie with you; maybe he can help. Please
 hurry!
{200}{}{Minhas orações são respondidas! Tome Laddie com você; talvez ele possa ajudar. Por Favor
  apresse-se!}
#Well, maybe you're right. Thanks for listening.
{201}{}{Bem, talvez você tenha razão. Obrigado pela atenção.}
#I've heard of you. Look, I don't want any trouble; we're a peaceful community. Let's just keep
 the subject to business, OK?
{202}{}{Já ouvi falar de você. Olha, eu não quero nenhum problema; Somos uma comunidade pacífica. Vamos apenas manter
  o assunto para negócios, OK?}
#I have some questions for you.
{203}{}{Eu tenho algumas perguntas para você.}
#I don't have any business with you for now. Bye.
{204}{}{Eu não tenho qualquer negócio com você por enquanto. Tchau.}
#Well… I'm worried about my missing son, Jonny. We've searched everywhere, but still can't find
 him. I fear that maybe wild animals got him.
{205}{}{Bem ... Eu estou preocupado com o meu filho desaparecido, Jonny. Nós temos procurado em todos os lugares, mas ainda não conseguiu encontrar
  ele. Temo que os animais selvagens talvez pegou.}
#Maybe I can help. I do a lot of traveling; I'll keep a lookout for your boy.
{206}{}{Talvez eu possa ajudar. Eu faço um monte de viajar; Eu vou manter um vigia para o seu menino.}
#I would really appreciate that. Every little bit helps. In the mean time, did you have some
 business with me?
{208}{}{Eu realmente aprecio isso. Cada pequena ajuda. Nesse meio tempo, você teve algum
  negócio comigo?}
#No, not really. I'll be going now, thanks.
{210}{}{Não, não realmente. Eu estarei indo agora, obrigado.}
#Sorry, I never heard of it.
{211}{}{Desculpe, eu nunca ouvi falar disso.}
#Hehehe. Has Old Cornelius got you looking for his pocket watch, too? No, you won't find it here.
 That old coot probably just left somewhere and forgot about it.
{214}{}{Hehehe. Tem Old Cornelius tenho você olhar para seu relógio de bolso, também? Não, você não vai encontrá-lo aqui.
Aquele velho galego acabou de sair de algum lugar e esqueceu.}
#[He looks at you closely and then smiles.] Why don't you be a good little boy and run outside
 and play?
{216}{}{[Ele olha para você sorri de perto e então.] Por que seja um bom menino e correr para fora
  e jogar?}
#[He looks at you closely and then smiles.] Why don't you be a good little girl and run outside
 and play?
{217}{}{[Ele olha para você sorri de perto e então.] Por que não é uma boa menina e correr para fora
  e jogar?}
#Please keep looking. I know he's still alive, I can feel it!
{218}{}{Por favor, continue procurando. Eu sei que ele ainda está vivo, eu posso sentir isso!}
#That's Jonny's BB gun all right. Noooooooooooooooooooo! [Balthas breaks down and starts to cry
 uncontrollably.]
{219}{}{Isso é arma do BB Jonny tudo certo. Noooooooooooooooooooo! [Balthas rompe e começa a chorar
  incontrolavelmente.]}
#That's Jonny's BB gun all right...I don't believe he is dead. Please keep looking for my boy. I
 am sure he is still out there.
{2199}{}{Isso é arma do BB de Johnny tudo bem ... Eu não acredito que ele está morto. Por favor, continue olhando para o meu menino. Tenho certeza que ele ainda está lá fora.}
#I knew Jonny wasn't dead! You say I have to wait… I don't understand! Is he hurt? My instincts
 tell me to go to my son, but I sense you have my son's best interest at heart. Please hurry, and bring
 my son back to me.
{220}{}{Eu sabia Jonny não estava morto! Você diz que eu tenho que esperar ... Eu não entendo! Ele está ferido? Meus instintos
  dizer-me para ir para o meu filho, mas eu sinto que você tem o melhor interesse do meu filho no coração. Por favor, depressa, e trazê-
  meu filho de volta para mim.}
#Oh no! Not the ghosts! I knew we should've burned that place to the ground. I won't let them
 take my boy... I'm going to get little Jonny back, whatever the cost. I'm sure the residents of Modoc
 will help me get my son back! Meet us at the Ghost Farm. We'll kill them all!
{221}{}{Oh não! Não os fantasmas! Eu sabia que deveria ter queimado aquele lugar até o chão. Eu não vou deixá-los
  levar o meu menino ... Eu estou indo para ajudar o Jonny nas costas, custe o que custar. Tenho certeza que os moradores de Modoc
  iram me ajudar a conseguir o meu filho de volta! Encontre conosco no Santo Farm. Vamos matá-los todos!}

#You have safely returned Jonny back to Modoc.
{230}{}{Você voltou em segurança Jonny volte para Modoc.}

#added by killap - RP
#Please, bring my son back to me safely.
{240}{}{Por favor, traga meu filho de volta para mim de forma segura.}

