# 0. Look
#According to the tag on its collar, its name is Bess.
{100}{}{De acordo com a etiqueta em seu colarinho, seu nome é Bess.}
{101}{}{Você vê Bess.}

#It looks like it's been attacked by some wild animal. It's hurt pretty bad.
{110}{}{Parece que ele foi atacado por algum animal selvagem. Ele está machucado muito ruim.}
#That's a fine brahmin anyone would be proud to own.
{111}{}{Isso é um brâmane bem alguém iria se orgulhar de possuir.}

# 1. Bubble text
{120}{}{Moooooo!}
#[This poor brahmin is injured.]
{121}{}{[Este pobre brahmin esta ferido.]}

# 2. Jerky
{130}{}{Mooooooooo.}
#[Bess lets out a low, mournful moo.]
{131}{}{[Bess solta, um moo triste baixo.]}
#Poor girl - maybe I shouldn't have sold you for jerky. Would you like to get out of here?
{132}{}{Pobre menina - talvez eu não devesse ter vendido por jerky. Você gostaria de sair daqui?}
#Yup! You're going to make some mighty tasty jerky. See ya.
{133}{}{Sim! Você vai ser uma poderosa e saborosa para jerky. Até mais.}

# 3. Escape? (2)
{140}{}{Mooooooo.}
#[That sounded like a much happier moo.]
{141}{}{[Isso soou como um moo muito mais feliz.]}
#OK, then let's get out of here.
{142}{}{OK, então vamos sair daqui.}
#Just kidding. I need the jerky more than I need you.
{143}{}{Só brincando. Preciso do jerky mais do que eu preciso de você.}

# 4. Bubble message
{150}{}{Mooo.}

#First aid skills won't help heal this poor brahmin's broken leg.
{200}{}{Técnicas de primeiros socorros não vai ajudar a curar perna quebrada deste pobre brahmin's.}

#You successfully heal the brahmin's broken leg.
{300}{}{Você curou com sucesso perna quebrada do brahmin's.}

#You fail to heal the brahmin's broken leg.
{310}{}{Você não conseguiu curar perna quebrada do brahmin's.}
