#More scraps for Rose.
{100}{}{Mais recados para Rose.}
#Uh! I never get used to this.
{101}{}{Mais recados para Rose....}
#I love my work.
{102}{}{I Eu amo meu trabalho.}
#Balthas will pay a pretty coin for this hide.
{103}{}{Balthas pagará uma moeda é muito para te esconder.}
#I hear you can make a great dessert from the eyeball squeezin's
{104}{}{Ouvi dizer que você pode fazer uma grande sobremesa dos squeezin's globo ocular}
#I'm about ready for a smoke.
{105}{}{Eu estou pronto para fumar um cigarro.}

#That's a good Bessy.
{120}{}{Essa é uma boa Bessy.}

#Move it, mister; I've got brahmin #to kill.
{200}{}{Mova-se, senhor; Eu tenho brahmin para matar.}
#Get out of the way.
{201}{}{Saia do caminho.}
#Can you please move? I've got work to do.
{202}{}{Você pode por favor andar? Eu tenho trabalho a fazer.}
#Hey lady, do you mind moving? I've got brahmin to kill.
{203}{}{Ei senhora, você se importa de andar? Eu tenho brahmin para matar.}

#You see a butcher.
{250}{}{Você vê um açougueiro.}
#This is the "slaughterhouse technician."
{251}{}{Este é o "técnico de matadouro."}
#This is the slaughterhouse butcher. His clothes are drenched in dead brahmin.
{252}{}{Este é o açougueiro matadouro. Suas roupas estão encharcados de brahmin mortos.}
#You can smell this poor sap from here.
{253}{}{Você pode cheirar esse pobre coitado a partir daqui.}

#Damn, it looks like we're gonna need some more brahmin here.
{275}{}{Porra, parece que vamos precisar de um pouco mais de brahmin aqui.}
#Well, might as well call it a day. We're outta brahmin. Wahoo!!! BEER TIME!!!
{276}{}{Bem, poderia muito bem chamá-lo um dia. Estamos outta brahmin. Wahoo !!! Tempo da cerveja !!!}
#Shucks! No more brahmin to kill! Maybe I should go see Miria.
{277}{}{Nojo! Não há mais brahmin para matar! Talvez eu deva ir ver Miria.}

#Ahhh, time to go home and relax in my own stink.
{280}{}{Ahhh, é hora de ir para casa e relaxar no meu próprio fedor.}
#It's time to head home and have a nice jerky steak.
{281}{}{É hora de ir para casa ter um bom jerky bife.}
#That was a long day. I hope to god someone kills me in my sleep so I don't have to do this
 again.
{282}{}{Esse foi um longo dia. Espero em Deus que alguém me mata no meu sono, então eu não terei que fazer isso
  novamente.}

#Jerky is good for the bones.
{300}{}{Jerky é bom para os ossos.}
#Jerky is good for the hair.
{301}{}{Jerky é bom para o cabelo.}
#Jerky is good for the lungs.
{302}{}{Jerky é bom para os pulmões.}
#Jerky is good for the stomach.
{303}{}{Jerky é bom para o estômago.}
#Jerky is good for the loins.
{304}{}{Jerky é bom para os lombos.}
#Jerky tastes good.
{305}{}{Jerky tem um gosto bom.}
#Christ, did a brahmin shit in here?
{306}{}{Cristo, uma brahmin fez merda aqui?}
#I think I stained my coat. HA! HA! HA!
{307}{}{Eu acho que manchou o meu casaco. HA! HA! HA!}
#Watch your step. This place is full of nasty things on the ground.
{308}{}{Cuidado com o degrau. Este lugar está cheio de coisas desagradáveis no terreno.}
#You like jerky?
{309}{}{Você gosta jerky?}
#I even like jerky for breakfast.
{310}{}{Eu até gosto jerky para o pequeno almoço.}
#Milk, ice-cream, all makes my stomach nuts. But JERKY!!!
{311}{}{Leite, sorvete, tudo faz minhas porcas de estômago. Mas JERKY !!!}
#Hey! Listen here, JERKY!!! HA! HA! HA!
{312}{}{Ei Ouça aqui, JERKY !!! HA! HA! HA!}