#You see an old man.
{100}{}{Você vê um homem velho.}
#You see Cornelius.
{101}{}{Você vê Cornelius.}
#Other than the slightly unsettled look on his face, there appears to be nothing out of the
 ordinary about him.
{102}{}{Diferente o seu olhar um pouco instável em seu rosto, não parece haver nada de
comum sobre ele.}

#Welcome to Rose's Bed and Breakfast. My name is Rose -- I mean, Cornelius -- and I run this bed
 and breakfast. Can I help you?
{150}{}{Bem-vindo ao de Rose Bed and Breakfast. Meu nome é Rose - Quero dizer, Cornelius - e eu sou funcionario temos leito
e pequeno-almoço. Posso ajudar?}
#If you run this place, then how come it's called ROSE'S Bed and Breakfast?
{151}{}{Se você controla este lugar, então como é que ele é chamado de Rose Bed and Breakfast?}
#I'm looking for a gold watch.
{152}{}{Estou à procura de um relógio de ouro.}
#What do you do here?
{153}{}{O que você faz aqui?}
#Who's Rose?
{154}{}{Quem é Rose?}
#I'm interested in getting a room.
{155}{}{Estou interessado em obter um quarto.}
#Questions? Was I asking you something? Hi, my name's Cornelius.
{156}{}{Dúvidas? Será que eu posso pedindo-lhe alguma coisa? Oi, Cornelius é meu nome.}
#You need some serious help, old man.
{162}{}{Você precisa de ajuda é sério, meu velho.}
#Farrel's got your watch in a wall safe. Let's string him up.
{163}{}{Farrel está com o seu relógio em um cofre de parede. Vamos cadeia.}
#I found your watch at Farrel's house. You were right; Farrel is the thief.
{164}{}{Eu encontrei o seu relógio na casa de Farrel. Você estava certo; Farrel é o ladrão.}
#It seems an industrious rat made off with your watch. I recovered this from its nest.
{165}{}{Parece um rato industriosos fugiu com o seu relógio. Eu recuperei esta no seu ninho.}
#Hello thar! Have we met?
{166}{}{Olá Thar! Já nos conhecemos?}
#My God! Somebody killed my best friend, Farrel! The whole town is looking for the murderer.
 We're going to lynch him when we catch him!
{176}{}{Meu Deus! Alguém matou o meu melhor amigo, Farrel! A cidade inteira está procurando o assassino.
  Nós estamos indo para linchá-lo quando pegá-lo!}
#I killed him. What are going to do about it, you crazy old man?
{177}{}{Eu o matei. O que vão fazer sobre isso, você está louco velho?}
#Whoa! Look at the time. I have to be going.
{178}{}{Whoa! Olhe para o tempo. Eu tenho que ir.}
#Rose is my wife; I named this place after her. Did you know I'm married?
{179}{}{Rose é minha esposa; Eu nomeei este lugar por ela. Você sabia que eu sou casado?}
#Can I ask you some more questions?
{180}{}{Posso te fazer mais algumas perguntas?}
#THEN WHY DON'T YOU ASK THAT NO-GOOD FARREL!? MAYBE HE'LL SELL YOU THE WATCH HE STOLE FROM ME!
 Now if you don't mind, I'm quite busy. I got to shave the brahmin.
{181}{}{Então, por que você não pergunta O BOM FARREL!? Talvez ele te venda o relógio que ele roubou de mim!
 Agora, se você não se importa, eu sou muito ocupado. Eu comecei a raspar o brahmin.}
#I run this motel. Yep, this place would fall apart if it weren't for me. Have you been to the
 outhouse? Cleanest outhouse you've ever been to. That's my doing.
{182}{}{Eu controlo este motel. Sim, este lugar iria desmoronar se não fosse por mim. Você já foi para o
outhouse? Cleanest casinha que você já esteve. Isso é obra minha.}
#What does having a clean outhouse have to do with running this place?
{183}{}{O que significa ter uma casinha limpa tem a ver com a execução deste lugar?}
#Rose is my wife. She runs the kitchen. You won't find a better meal anywheres else. Rose, she's
 so beautiful. I'm going to marry her some day.
{184}{}{Rose é minha esposa. Ela vai a cozinha. Você não vai encontrar um melhor anywheres refeição mais. Rose, ela é
  tão bonita. Eu vou casar com ela algum dia.}
#I thought you just said Rose is your wife.
{185}{}{Eu pensei que você disse Rose é sua esposa.}
#I have a room. I sleep over there. Where do you sleep?
{186}{}{Eu tenho um quarto. Eu durmo lá. Onde você dorme?}
#I don't think you understand. I would like to rent a room for the night.
{187}{}{Eu não acho que você entende. Gostaria de alugar um quarto para a noite.}
#A while back, I forget when... my best friend of 30… or was it 40 years? Oh, it doesn't matter,
 what matters is that he stole my precious gold pocket watch. It has been handed down in my family for
 five, no six, err... four generations. Yep, I distinctly remember setting it down on my desk. Then,
 when I looked on the kitchen table, it was gone.
{188}{}{Um tempo atrás, eu me esqueci quando ... meu melhor amigo, de 30 ... ou era 40 anos? Oh, isso não importa,
  o que importa é que ele roubou o meu precioso relógio de bolso de ouro. Ele tem sido repassado na minha família há
  cinco, não seis, err ... quatro gerações. Sim, eu me lembro claramente deixado em baixo da minha mesa. Em seguida,
  quando eu olhei na mesa da cozinha, ele tinha sumido.}
#OK, I'll bring your watch back.
{189}{}{OK, eu vou trazer o seu relógio de volta.}
#Did you try looking for it on your desk?
{190}{}{Você tentou procurá-lo em sua mesa?}
#You'll help me? That's great! Go beat up Farrel and get my watch back. He probably hid it good.
 So tear his house apart and look for it.
{191}{}{Você vai me ajudar? Isso é ótimo! Vai bater Farrel e buscar o meu relógio de volta. Ele provavelmente escondeu-o bem.
Então revista toda a casa dele e olhe para ele.}
#What are you talking about?
{192}{}{O que você está falando?}
#Look, I don't want any part of this.
{193}{}{Olha, eu não quero fazer parte disso.}
#Kill Farrel, get watch back… got it? I'll be right back.
{194}{}{Mate Farrel, consiga relógio volta ... entendeu? Eu já volto.}
#Kill Farrel? Who's going to kill Farrel? He's my best friend! I'll personally string up the
 villain who tries to kill Farrel.
{195}{}{Mate Farrel? Quem vai matar Farrel? Ele é meu melhor amigo! Eu, pessoalmente, vai pra cadeia o
bandido que tenta matá Farrel.}
#I accept the job, and I expect payment upon completion.
{196}{}{Eu aceito o trabalho, e eu espero que o pagamento após a conclusão.}
#I can't take this anymore. I'm leaving.
{197}{}{Eu não aguento mais. Estou indo embora.}
#Of course, I'll pay you. As soon as you finish cleaning out the barn come back and see me.
{198}{}{É claro que eu vou te pagar. Assim que você terminar de limpar o celeiro.}
#I have a watch. It was a gold watch. I wonder where I put it?
{199}{}{Eu tenho um relógio. Era um relógio de ouro. Gostaria de saber onde eu coloquei?}
#Yes, yes, yes. I've looked in my sock drawer. It's not there, either.
{200}{}{Sim, sim, sim. Eu olhei na minha gaveta de meias. Não está lá, também.}
#I'll keep a lookout for your watch while I'm in town.
{201}{}{Eu vou manter um vigia para o seu relógio, enquanto eu estou na cidade.}
#There's no way I'm helping a crazy old man like you. I'm outta here.
{202}{}{Não há nenhuma maneira que eu ajudo um velho louco como você. Eu sou daqui.}
#I knew I couldn't trust him! I'm gonna string him up by the ears until he gives me back my
 watch.
{203}{}{Eu sabia que não podia confiar nele! Vou corda-lo pelas orelhas até que ele me dá de volta o meu
  relogio}
#There's nothing in there. Sheriff Jo and myself looked there already.
{204}{}{Não há nada lá dentro. Sheriff Jo e eu olhei lá já.}
#He did? I knew it! I'll teach him a lesson he'll never forget. You'd better stay here or you
 might get hurt.
{206}{}{Ele fez? Eu sabia! Vou ensinar-lhe uma lição que ele nunca vai esquecer. É melhor você ficar aqui ou você
  pode se machucar.}
#That's my watch! What are you doing with that? Give it back! [He snatches the watch from your
 hands.] I think you better go; we don't take kindly to thieves around here.
{207}{}{Esse é o meu relógio! O que você está fazendo com isso? Dar de volta! [Ele rouba o relógio do
. mãos] Eu acho que é melhor você ir; nós não olhoamos com bons olhos ladrões por aqui.}
#Have you tried Rose's omelets? They're delicious.
{209}{}{Você já tentou omeletes de Rose? Eles são deliciosos.}
#I saw Jonny playing by the well with his dog Laddie. What a nice kid.
{210}{}{Vi Jonny jogando pelo poço com seu cão Laddie. É um garoto legal.}
#Don't go to the Ghost Farm unless you're tired of living.
{211}{}{Não vá para o Santo Farm, a menos que você estiver cansado de viver.}
#Miria is a nice girl. We used to play doctor when she was little.
{212}{}{Miria é uma garota legal. Nós costumávamos brincar de médico quando ela era pequena.}
#Davin is a nice kid. I wonder why he doesn't look anything like his father?
{213}{}{Davin é um bom garoto. Eu me pergunto por que ele não se parece nada com seu pai?}
#I was sitting on the toilet one day and a big dog climbed out of the sewer. Scared me half to
 death.
{214}{}{Eu estava sentado no vaso sanitário de um dia e um grande cão saiu do esgoto. Assustou-me metade 
morto.}
#Grisham is a nice fellow. He sells us scraps to feed the giant chicken.
{215}{}{Grisham é um bom companheiro. Ele nos vende sucatas para alimentar a galinha gigante.}
#Stay away from the chicken coop! I almost lost an arm feeding that thing.
{216}{}{Fique longe do galinheiro! Eu quase perdi um braço alimentando essa coisa.}
#Rose's dogs are vicious, but I just throw them some jerky and they don't pay me no mind.
{217}{}{Cães de Rose são cruéis, mas eu simplesmente jogá-los alguns jerky e eles não pagam-me não mente.}
#Farrel's my best friend in the whole world.
{218}{}{O melhor amigo de Farrel em todo o mundo.}
#Laddie is a smart dog. I talk to him all the time.
{219}{}{Laddie é um cão inteligente. Eu falo com ele o tempo todo.}
#I hear Grisham is trying to marry off his kids. I wonder if Rose wouldn't mind if I got another
 wife.
{220}{}{Ouça Grisham está tentando casar seus filhos. Gostaria de saber se Rose não se importaria se eu ter outra
  esposa.}
#Pog? Whatever happened to that game, anyway? Well, I have to go. Maybe we can play later.
{222}{}{Pog? O que aconteceu com esse jogo, de qualquer maneira? Bem, eu tenho que ir. Talvez possamos jogar mais tarde.}
#I FOUND THE MURDERER! HE ADMITTED TO KILLING FARREL! LET'S GET HIM!
{223}{}{Eu encontrei o assassino! Ele admitiu ter matado FARREL! Vamos levá-lo!}
#I FOUND THE MURDERER! SHE ADMITTED TO KILLING FARREL! LET'S GET HER!
{224}{}{Eu encontrei o assassino! Ela admitiu ter matado FARREL! Vamos levá-la!}
#Me kill Farrel.
{225}{}{Mate Farrel.}

#[Hmmm... Certain words seem to set him off.] Rose... Room... Running...
{300}{}{[Hmmm ... Certas palavras parecem colocá-lo fora.] Rose ... Quarto ... Correr ...}
{301}{}{Ooga.}

#I always knew you were a thief!
{501}{}{Eu sempre soube que você era um ladrão!}
#How could you do this to your best friend!
{502}{}{Como você pôde fazer isso com o seu melhor amigo!}
#I'm gonna kill you!
{503}{}{Eu vou te matar!}
#I'm gonna mount your head on my wall!
{504}{}{Vou colocar sua cabeça em minha parede!}

#He appears to be pre-occupied at the moment.
{550}{}{Ele parece ser pré-ocupada no momento.}

#You have returned the watch to Cornelius.
{600}{}{Você devolveu o relógio para Cornelius.}
#You have resolved the dispute between Cornelius and Farrel.
{650}{}{Você terá resolvido o diferença entre Cornelius e Farrel.}
