#A small boy
{100}{}{Um menino pequeno}
{101}{}{Jonny}
#Blonde hair, blue eyes, your typical all American looking kid.
{102}{}{Cabelo loiro, olhos azuis, o todo típico garoto que olha o americano.}

{150}{}{Waaaaa!}
#I want my dog back!
{151}{}{Eu quero o meu cachorro de volta!}
#Whimper...
{152}{}{choradeira…}
#Stranger!
{153}{}{Estranho!}
#If Laddie went to Jonny Laddie! I’ve missed you girl. Thank you for bringing my dog back to me.
{154}{}{Se Laddie foi para Jonny Laddie! Eu perdi você, garota. Obrigado por trazer o meu cachorro de volta para mim.}
#Hello, I haven’t seen you around here before.
{155}{}{Olá, eu não vi você por aqui antes.}
#Is your name Jonny?
{156}{}{Seu nome é Jonny?}
#What’s your name little boy?
{157}{}{Qual é o seu nome de menino?}
#Tell me your name you little monster.
{158}{}{Diga-me seu nome que monstrinho.}
#Would you like some candy little kid.
{159}{}{Gostaria alguns doces garotinho.}
#Hello again.
{160}{}{Olá novamente.}
#Is your name Jonny?
{161}{}{Seu nome é Jonny?}
#What’s your name little boy?
{162}{}{Qual é o seu nome de menino?}
#Tell me your name you little monster.
{163}{}{Diga-me seu nome que monstrinho.}
#Would you like some candy little kid.
{164}{}{Gostaria alguns doces garotinho.}
#Hello again.
{165}{}{Olá novamente.}
#Your mother and father have sent me to find you.
{166}{}{Sua mãe e seu pai me enviou para te encontrar.}
#Would you like some candy little kid.
{167}{}{Gostaria alguns doces garotinho.}
#Have you talked to Vegeir about me going home?
{168}{}{Você já falou com Vegeir sobre mim indo para casa?}
#Yes. He says he wants your parents to come down and get you.
{169}{}{Sim. Ele diz que quer seus pais venham aqui para baixo e te pegar.}
#No, not yet.
{170}{}{Não, ainda não.}
#My dad said Laddie went with you to look for me. Where is she? I miss her.
{171}{}{Meu pai disse Laddie vai com você ela ira olhar você para mim. Onde ela está? Eu sinto falta dela.}
#I’m sorry Jonny. Laddie died while we were searching for you.
{172}{}{Sinto muito Jonny. Laddie morreu enquanto estávamos procurando por você.}
#Rose said she would look after your dog.
{173}{}{Rose disse que iria cuidar de seu cão.}
#My name is Jonny. What’s yours?
{174}{}{Meu nome é Jonny. Qual é o seu?}
#My name is
{175}{}{Meu nome é }
{176}{}{.}
#My name’s not important.
{177}{}{Meu nome não é importante.}
#My name’s Jonny and I don’t like you.
{178}{}{Jonny é meu nome e eu não gosto de você.}
#[He points to you and starts screaming.] Stranger! Stranger! Stranger!
{179}{}{[Ele aponta para você e começa a gritar.] Estranho! Estranho! Estranho!}
#Very nice to meet you .
{180}{}{Muito prazer em conhecê- .}
#Your mother and father have sent me to find you.
{181}{}{Sua mãe e seu pai me enviou para te encontrar.}
#See you around kid.
{182}{}{Vejo você por aí garoto.}
#That’s swell! I wanted to go home, but Vegeir says his people can’t travel that far above ground and
 couldn’t take me…Not that I doubt you, but what’s my father’s name?
{183}{}{Isso é inchaço! Eu queria ir para casa, mas Vegeir diz seu povo não pode viajar tão longe acima do solo e
não poderia ter me ... Não é que eu duvido de você, mas o qual é o nome do meu pai?}
{184}{}{Farrel}
{185}{}{Cornelius}
{186}{}{Balthas}
{187}{}{Davin}
{188}{}{Joshua}
#Don’t you trust me Jonny?
{189}{}{Você não confia em mim Jonny?}
#Hmm….no. Thank you, for bringing my dog back to me, but I have to go now. Bye.
{190}{}{Hmm ... .não. Obrigado, por trazer o meu cachorro de volta para mim, mas eu tenho que ir agora. Tchau.}
#It was sure nice meeting you, but I have to go now. Bye.
{191}{}{Foi com certeza um prazer conhecê-lo, mas eu tenho que ir agora. Tchau.}
#That’s right! Yipee! I’m going home. Ask Vegeir if it’s all right for you to take me home. He’s been
 so nice to me, I don’t want to leave until he says it’s all right. Please hurry, I’m homesick.
{192}{}{Está certo! Yipee! Eu estou indo para casa. Peça Vegeir se está tudo certo para que você me levar para casa. Ele tem sido
  tão bom para mim, eu não quero sair até que ele diga que está tudo bem. Por favor, depressa, estou com saudades de casa.}
#Okay mister, I believe you. Ask Vegeir it’s all right for you to take me home. He’s been so nice to
 me, I don’t want to leave until he says it’s all right.
{193}{}{Ok senhor, eu acredito em você. Peça Vegeir está tudo certo para que você possa me levar para casa. Ele tem sido tão bom
  mim, eu não quero sair até que ele diz que está tudo bem.}
#Okay miss, I believe you. Ask Vegeir it’s all right for you to take me home. He’s been so nice to me,
 I don’t want to leave until he says it’s all right.
{194}{}{Senhorita Ok, eu acredito em você. Peça Vegeir está tudo certo para que você possa me levar para casa. Ele tem sido tão bom para mim,
Eu não quero sair até que ele diga que está tudo bem.}
#No. I’m going to go play with my friends now. Bye.
{195}{}{Não. Eu estou indo para ir jogar com os meus amigos agora. Tchau.}
#I’m not supposed to talk to strangers. Bye.
{196}{}{Eu não tenho que falar com estranhos. Tchau.}
#Yes it is! How did you know? Laddie must have told you. She’s such a smart dog.
{197}{}{Sim, é! Como você sabia? Laddie deve ter lhe contado. Ela é um cão tão esperto.}
#Your mother and father have sent me to find you.
{198}{}{Sua mãe e seu pai me enviou para te encontrar.}
#You’re coming with me kid. There’s a reward for bringing you back.
{199}{}{Você vem comigo garoto. Há uma recompensa para trazer você de volta.}
#Yes, I think that’s best. Although I trust you, I’m sure Vegeir just wants to make sure I get home
 safely. Thank you for your help.
{200}{}{Sim, eu acho que é melhor. Embora eu confio em você, eu tenho certeza que Vegeir só quer ter certeza que eu chegar em casa
  com segurança. Obrigado pela ajuda.}
#Please hurry. I want to go home.
{201}{}{Por favor, depressa. Eu quero ir para casa.}
#No! I don’t believe you! Give me back my dog! [Waaaaa!]
{202}{}{Não! Eu não acredito em você! Devolva o meu cão! [Waaaaa!]}
#Oh no! Don’t you know Rose uses dog in her dishes! Laddie is probably a burger by now.
{203}{}{Oh não! Você não sabe que Rose utiliza cão em seus pratos! Laddie é provavelmente um hambúrguer agora.}