{100}{}{Oh my! A very shapely and seductive looking woman.}
#You see Miria.
{101}{}{Você vê Miria.}
#You're not sure, but the measurements 36-24-36 come to mind.
{102}{}{Você não tem certeza, mas as medidas 36-24-36 vêm à mente.}

#Bitch!
{150}{}{CADELA!}
#How dare you show your face around here!
{151}{}{Como se atreve a mostrar sua cara por aqui!}

#That's just sick!
{152}{}{Isso é simplesmente doente!}
#I hope you two are happy together.
{153}{}{Espero que vocês dois estão felizes juntos.}

# Node 0
#Why, hello there, stranger. I'm Miria.
{154}{}{Por que, Olá, estranho. Eu sou Miria.}
#I am so pleased you came back. What can I DO for you now?
{155}{}{Estou tão feliz que você voltou. O que posso fazer por você agora?}
#What do you do around here?
{156}{}{O que você faz por aqui?}
#What can you tell me about the slaughterhouse?
{157}{}{O que você pode me dizer sobre o matadouro?}
#Heard any good rumors?
{158}{}{Ouviu alguns bons boatos?}
{159}{}{Hubba! Hubba!}

# Node 2
#If I weren't so bored, I'd say no. So ask away.
{160}{}{Se eu não fosse tão aborrecido, eu diria que não. Então, pergunte a distância.}

# Node 10
#Rumor has it that Farrel stole the watch.
{164}{}{Há rumores de que Farrel roubou o relógio.}
#Why would Farrel steal the watch?
{165}{}{Por que Farrel roubou o relógio?}
#Isn't Farrel Cornelius's best friend?
{166}{}{Não é o melhor amigo do Farrel o Cornelius
#Tell me some more rumors.
{167}{}{Diga-me mais alguns rumores.}

# Node 11
#Because poor people tend to steal to make ends meet. Farrel definitely falls in the poor
 category, and that would explain the new tools he bought soon after Cornelius's watch disappeared.
{168}{}{Porque as pessoas pobres tendem a roubar para sobreviver. Farrel definitivamente cai nos pobres
  categoria, e isso explicaria as novas ferramentas que ele comprou logo após o relógio de Cornelius desapareceu.}
#Can I ask you a few more questions?
{170}{}{Posso perguntar-lhe mais algumas perguntas?}

# Node 12
#Yes, they were thick as thieves, those two. Which is why I think Farrel stole the watch. Who
 else but Farrel would have the access and the opportunity to steal Cornelius's watch?
{171}{}{Sim, eles não se largavam, aqueles dois. É por isso que eu acho que Farrel roubou o relógio. quem
mais seria, mas Farrel teria o acesso e a oportunidade de roubar o relógio de Cornelius?}

# Node 13
#Nothing to tell. My family runs the slaughterhouse. People from all around bring their brahmin
 here for slaughter. After they are slaughtered and the meat treated, it is sold to traders who in turn
 sell it to merchants in various towns. All very boring, if you ask me.
{174}{}{Não há nada a dizer. Minha família dirige o matadouro. Pessoas de todo trazer o seu brahmin
aqui para abate. Depois que eles são abatidos ea carne tratada, ela é vendida a comerciantes que, por sua vez
vendê-lo para os comerciantes em várias cidades. Tudo muito chato, se você me perguntar.}

# Node 14
#Have you come to the right place! This town is so boring, there's nothing else to do but gossip
 and… [She keeps talking for awhile and sometime later you're able to get a word in.]
{176}{}{Você veio ao lugar certo! Esta cidade é tão chata, não há mais nada a fazer, mas e fofoca
  e ... [Ela continua falando por algum tempo e algum tempo depois, você é capaz de obter uma palavra.]}
#What else do you want to know?
{177}{}{O que mais você quer saber?}
#What do you know about the Cornelius's missing watch?
{178}{}{O que você sabe sobre o relógio ausente do Cornelius?}
#You mentioned something about Rose?
{179}{}{Você mencionou algo sobre Rose?}
#What's this about a mutated brahmin?
{180}{}{Que história é essa de um brahmin mutante?}
#Tell me about Davin.
{181}{}{Conte-me sobre Davin.}
#Let's talk about something else.
{182}{}{Vamos falar de outra coisa.}

# Node 15
#Ah, Rose. The proprietor of Rose's Bed and Breakfast. Now, you didn't hear it from
 me, but have you ever wondered why her 'coop' is so well protected? She says it's to
 protect her chickens from predators, but if you look closely it looks as if she's
 trying to keep something in rather than out. Plus, whoever heard of chickens laying twelve pound
 eggs?
{183}{}{Ah, Rose. O titular da Rose Bed and Breakfast. Agora, você não ouviu isso de
  me, mas você já se perguntou por que sua 'gaiola' é tão bem protegida? Ela diz que é a
  proteger os seus pintos de predadores, mas se você olhar de perto, parece que ela tem
  tentado manter algo de fora. Além disso, quem já ouviu falar de frangos, que £ 12 o
  ovos?}
#Tell me more rumors.
{184}{}{Diga-me mais rumores.}

# Node 16
#It's really strange, but I hear some ranchers say that every once in a while a brahmin will
 give birth to a calf with only one head. Talk about weird!
{186}{}{É realmente estranho, mas eu ouço alguns fazendeiros dizem que de vez em quando um brahmin vai
dar à luz a um bezerro com apenas uma cabeça. Fale sobre o estranho!}

# Node 17
#He's family; I don't spread rumors about my own family.
{189}{}{Ele é da família; Eu não espalho boatos sobre a minha própria família.}

# Node 18
#Who, me? I do odd jobs here and there. Surely nothing worth talking about. [She flutters her
 eyes at you.]
{192}{}{Quem, eu? fazer biscates aqui e ali. Certamente nada vale a pena falar. [Ela vibra 
olhos em você.]}
#I really would like to know more about you.
{193}{}{Eu realmente gostaria de saber mais sobre você.}
#You're right, enough talk. Let's get it on! You know you want it.
{194}{}{Você está certa, chega de conversa. Vamos em frente! Você sabe que quer.}

# Node 19
#I'm really touched. Nobody ever tries to get to know me better. All they want is sex, sex, sex!
 I get so tired of having wild sex all the time. I'm so glad you're not like the others.
{196}{}{Eu sou realmente tocada. Ninguém nunca tenta me conhecer melhor. Tudo que eles querem é sexo, sexo, sexo!
  Eu fico tão cansado de ter sexo selvagem o tempo todo. Estou tão feliz que você não é como os outros.}
#You slut! I thought you were special for a moment.
{197}{}{Você é vagabunda! pensei que você era especial por um momento.}
#You know, I'm just a normal guy like everyone else. Why, my friends say, "
{198}{}{Você sabe, eu sou apenas um cara normal como todo mundo. Ora, meus amigos dizem, "}
#you're just so cool because you're normal just like everyone else." Yep, normal that's me.
{199}{}{ Você é tão legal porque você é normal como qualquer outra pessoa. "Sim, normal que sou eu.}
#Well, I've never known anyone as interesting as you are.
{200}{}{Bem, eu nunca conheci ninguém tão interessante como você.}

# Node 20
#Want what? Just what are you implying?
{202}{}{Quer o quê? O que você está insinuando?}
#I think you know what I'm talking about, baby. You know this is what you want. [You smile and
 start to undress.]
{203}{}{Eu acho que você sabe o que eu estou falando, baby. Você sabe que isso é o que você quer. [Você sorri e
  começar a despir-se.]}
#Forget it; I'm sorry. I didn't mean to imply anything.
{204}{}{Esqueça; Sinto muito. Eu não quis dizer nada.}

# Node 21
#How dare you call me a slut! Let me tell you, I am very picky about the people I sleep with.
 Why, I have only slept with 10 or 20 people this month! I think this conversation is over!
{205}{}{Como você ousa me chamar de vagabunda! Deixe-me dizer-lhe, eu sou muito exigente sobre as pessoas com quem tenho relações sexuais.
Por que, eu só dormi com 10 ou 20 pessoas este mês! Eu acho que essa conversa já deu!}

# Node 22
#How disappointing. You are just like everyone else, aren't you?
{206}{}{Como decepcionante. Você é igual a todo mundo, não é?}

# Node 23
#No. I don't think so. I'm tired of this conversation. Good bye.
{208}{}{Não, eu não penso assim. Eu estou cansado dessa conversa. Adeus.}

# Node 24
#[She blushes] Stop, you're embarrassing me. You are just the sweetest thing. Why don't come
 over here and sit by me.
{209}{}{[Ela cora] Pare, você está me envergonhando. Você é apenas a coisa mais doce. Por que não vêm
aqui e sentar-se perto de mim.}
#I think this going too far. Can't we just talk?
{210}{}{Eu acho que esta indo longe demais. Não podemos apenas falar?}
#I thought you'd never ask. Why don't we get a little more comfortable?
{211}{}{Eu pensei que você nunca pediria. Por que não vamos ficar um pouco mais confortável?}
#All right! You know what I want, baby!
{212}{}{Tudo certo! Você sabe o que eu quero, baby!}
#You are a slut, aren't you!
{213}{}{Você é uma vagabunda, não é você!}

# Node 25
#I can't take this anymore! You're perfect. [She rips off her clothes, your clothes, and then…]
{214}{}{Eu não aguento mais! Você é perfeito. [Ela rasga roupas dela, suas roupas e, em seguida ...]}
#[Your world will never be the same again.]
{215}{}{[O seu mundo nunca mais será o mesmo novamente.]}

# Node 26
#That better not mean what I think that means.
{216}{}{Isto melhor não dizer o que eu acho que isso significa.}
{217}{}{Aoooga!}
{218}{}{Urg?}

# Node 27
#Yup! That's what I thought. It's funny how Neanderthal and civilized speech crosses roads on
 this subject. [You don't even see it coming. But you're sure the red hand print on your face will
 disappear someday.]
{219}{}{Sim! Isso é o que eu pensava. É engraçado como Neanderthal e um discurso civilizado cruza estradas esse
   assunto. [Você não vê-lo chegando. Mas você está certo a impressão de mão vermelha no seu rosto vai
  desaparecer algum dia.]}

# rape script dialog
#Help, Daddy! Get him away!
{250}{}{Ajuda, papai! Levá-lo embora!}
#Get away!
{251}{}{Fugir!}
#Help, Daddy! Get her away!
{260}{}{Ajuda, papai! Afastá-la!}

# wedding script dialog
#Daddy!
{400}{}{Papai!}
{401}{}{Uh oh!}
#I surely do!
{402}{}{Eu com certeza vou fazer!}

{410}{}{Uhh...}
#Uhhh... Continue, please...
{411}{}{Uhhh ... Continue, por favor ...}
#I sure the hell…
{412}{}{Tenho certeza que é o inferno ...}
#Um… I do.
{413}{}{Hum ... eu faço.}

#Uhhh, I think daddy's the one you should be talking too
{450}{}{Uhhh, eu acho que o papai é você aquela que deve falar demais}

#Great, I guess this means I have to run this dump now.
{500}{}{Ótimo, eu acho que isso significa que eu tenho que executar o dump agora.}

# in party dialog
#What'll we do now, baby?}
{1000}{}{O que vamos fazer agora, baby?}
#What'll we do now, honey?
{1001}{}{O que vamos fazer agora, querida?}
#What'll we do now, pooky?
{1002}{}{O que vamos fazer agora, pooky?}
#What'll we do now, lover?
{1003}{}{O que vamos fazer agora, amante?}
#What'll we do now, sugar bottom?
{1004}{}{O que vamos fazer agora, de fundo de açúcar?}
#No, no, no... Not that kind of distance! I need you to step back a few when we're walking around.
{1005}{}{Não, não, não ... Não esse tipo de distância! Eu preciso de você dar um passo para atrás quando estamos andando por aí.}
#Relax baby, just give me more space when we're walking around.
{1006}{}{Relaxe bebê, apenas me dar mais espaço quando estamos andando por aí.}
#I'll try harder, butter cakes. It's just hard to get "us" time out here in this wasteland.
{1007}{}{Vou me esforçar mais, bolos de manteiga. É muito difícil de obter "nestes" tempos aqui no deserto.}
#My stuff is your stuff.
{1008}{}{Minhas coisas é Suas Coisas.}
#Okay, muffin, but do we have to stop with just the armor?
{1009}{}{Ok, muffin, mas nós temos que parar com apenas uma armadura?}
#Sharp weapons like knives get me excited although I can use weapons like an SMG in
 a pinch if I need to. Just don't expect me to actually hit anything.
{1010}{}{Armas cortantes, como facas me animado, embora eu possa usar armas como uma SMG em
  uma pitada se eu precisar. Só não espere que eu realmente vá bater em nada.}
#We need to talk about the distance between us.
{1020}{}{Precisamos falar sobre a distância entre nós.}
#I'm completely healed and ready to go.
{1100}{}{Eu estou completamente curado e pronto para ir.}
#Hardly more than a scratch left on me now.
{1200}{}{Pouco mais do que um arranhão deixou em mim agora.}
#Well, I'm mostly healed -- but I could use more healing when we get a chance.
{1300}{}{Bem, eu estou na maior parte curado - mas eu poderia usar mais a cura quando nós tivemos uma chance.}
#I healed myself as much as I could but I'm still pretty badly hurt.
{1400}{}{Eu me curou tanto quanto eu podia, mas eu ainda estou muito machucado.}
#No, baby; I wanna come with you.
{1500}{}{Não, o bebê; Eu quero ir com você.}
#Sure thing, I'll put it away.
{1600}{}{Claro que sim, eu vou guardar.}
{1700}{}{}
#No, no, sweet pea. I need to be close to you.
{1800}{}{Não, não, docinho. Preciso estar perto de você.}
#But then I wouldn't be near to you, sugar lumps.
{1900}{}{Mas, então, eu não estaria perto de você, torrões de açúcar.}

# Seraph's Code: Uncle Biff
#Help! Get him away!
{270}{}{Socorro! Levá-lo embora!}
#Help! Get her away!
{280}{}{Socorro! Afastá-la!}
#Uncle Biff!
{420}{}{Tio Biff!}
#Uhhh, I think Uncle Biff's the one you should be talking too.
{470}{}{Uhhh, eu acho que o tio Biff aquele que você disse que falar demais.}

#added by killap - NPC info
#I think I broke a limb, lover. Better take a look.
{2000}{}{Acho que quebrei um membro, amante. Melhor dar uma olhada.}
#I feel feverish, lover. I think I am radiated.
{2001}{}{Sinto-me febril, amante. Acho que estou irradiado.}
#I feel very sick, lover. I think I am poisoned.	
{2002}{}{Sinto-me muito doente, amante. Acho que estou envenenado.}
