#You see a townsperson.
{100}{}{Você vê alguns cidadãos}


# General
#I sure hope it rains soon.
{200}{}{Espero que chova em breve.}
#Our crops are dying from lack of water.
{201}{}{Nossas colheitas estão morrendo por falta de água.}
#Even the wells have gone dry.
{202}{}{Até as paredes estão secando.}
#Not a cloud in the sky.
{203}{}{Nem uma nuvem no céu.}
#I'm thinking of moving away from here.
{204}{}{Eu estou pensando em mudar para longe daqui.}
#Modoc used to be a prosperous farming community.
{205}{}{Modoc costumava ser uma comunidade agrícola próspera.}
#Life in Modoc is slow. Just the way I like it.
{206}{}{Vida em Modoc é lento. Apenas o jeito que eu gosto.}

# Ghost Farm Seed Active
#I hear that people have seen glowing figures during the night hours at the Ghost Farm.
{220}{}{Ouvi dizer que as pessoas têm visto figuras brilhantes durante a noite na Fazenda Fantasma.}
#Did you hear? They found some idiot to go and investigate the Ghost Farm.
{221}{}{Você ouviu? Eles encontraram algum idiota de ir e investigar a Fazenda Fantasma.}
#I've been to the Ghost Farm. Scary!
{222}{}{Eu fui para a fazenda fantasma. Assustador!}
#Daytime is the best time to go to the Ghost Farm.
{223}{}{Durante o dia é a melhor hora para ir para a fazenda fantasma.}
#Karl used to live at the Ghost Farm. Now he probably haunts it.
{224}{}{Karl costumava viver na fazenda fantasma. Agora, ele, provavelmente,é uma assombração.}
#People shouldn't mess with the supernatural.
{225}{}{Pessoas não deve mexer com o sobrenatural.}
#Why would ghosts grow food?
{226}{}{Por que fantasmas cultivar alimentos?}

# If player delivered message from slags to Jo - Delivered=yes
#They found out the people living at the Ghost Farm call themselves Slags.
{240}{}{Eles descobriram as pessoas que vivem na fazenda fantasma chamar-se Slags.}
#What kind of name is Slag?
{241}{}{Que tipo de nome é Slag?}
#I don't trust the Slags.
{242}{}{Eu não confio nos Slags.}
#Maybe I could trust the Slags if I knew what happened to Karl.
{243}{}{Talvez eu pudesse confiar nos Slags se eu soubesse o que aconteceu com Karl.}

# If Player Agrees to help Modoc to Attack the Ghost Farm
#I'll meet you down at the Ghost Farm.
{260}{}{Vou encontrá-lo a baixo na fazenda Fantasma.}
#We're gonna kill a bunch of murderous Slags.
{261}{}{Nós vamos matar um bando de Slags assassinos.}
#I hope we're doing the right thing.
{262}{}{Espero que estamos fazendo seja a coisa certa.}
#We should attack during the daytime, while they're asleep.
{263}{}{Devemos atacar durante o dia, enquanto eles estão dormindo.}

# If the player and the town wipeout the Slags
#The Slags were just like us...
{280}{}{As escórias foram apenas como nós ...}
#We even killed the women and children of the Slags.
{281}{}{Temos até mortos as mulheres e crianças do Slags.}
#I feel dirty.
{282}{}{Eu me sinto sujo.}
#The blood stains won't come off my hands!
{283}{}{As manchas de sangue não vai sair minhas mãos!}
#I hope no one finds out what we did.
{284}{}{Espero que ninguém descubra o que fizemos.}
#What we did to the Slags was wrong.
{285}{}{O que fizemos para o Slags estava errado.}

# If the player kills the Slags by himself
#Did you hear? A powerful priest exorcised the ghosts from the farm.
{300}{}{Você ouviu? Um padre poderoso exorcizou os fantasmas da fazenda.}
#The harvest from the Ghost Farm should keep us fed for another year.
{301}{}{A colheita da fazenda Fantasma deveriam manter-nos alimentados por mais um ano.}
#There's not a drop of water at the Ghost Farm.
{302}{}{Não há uma gota de água na fazenda Fantasma.}
#Maybe the soil at the Ghost Farm is magic. How else could the crops grow without water?
{303}{}{Talvez o solo na fazenda Fantasma é mágica. De que outra forma poderia culturas crescer sem água?}
#Maybe the ghosts used blood to feed their crops.
{304}{}{Talvez os fantasmas usavam sangue para alimentar as suas culturas.}
#I think the ghosts were stealing our water.
{305}{}{Eu acho que os fantasmas estavam roubando a nossa água.}
#I bet things will return to normal around here, now that the ghosts are gone.
{306}{}{Aposto que as coisas vão voltar ao normal por aqui, agora que os fantasmas se foram.}

# If the player successfully completes the Ghost Farm seed. Best ending.
#We're gonna trade with the Slags.
{320}{}{Nós vamos ao comércio com os Slags.}
#The Slags have offered to supply water to Modoc during the drought.
{321}{}{Os Slags propuseram para fornecer água para Modoc durante a seca.}
#You're the one that helped us, aren't you? You're a hero!
{322}{}{Você é o único que nos ajudou, não é? Você é um herói!}
#You've saved the town of Modoc.
{323}{}{Você salvou a cidade de Modoc.}
#You'll always be welcome at Modoc.
{324}{}{Você sempre será bem-vindo em Modoc.}