#You see a Slag guard.
{100}{}{Você vê um guarda da Escória.}

# renda-se
#Surrender or die!
{150}{}{Renda-se ou morra!}
#I surrender.
{151}{}{Eu me rendo.}
#Die!
{152}{}{Morra!}
#Ug!
{153}{}{Ug!}
If you need to see Vegeir, we can escort you to him.
{154}{}{Se você precisar ver Vegeir, podemos levá-lo até ele.}
#Not now. I'll see Vegeir later.
{155}{}{Agora não. Visitarei Vegeir depois.}
#Yes, I need to see Vegeir immediately.
{156}{}{Sim, eu preciso ver Vegeir imediatamente.}
#You're dumber than dirt, aren't you! If you want to see Vegeir, you can just go find him yourself.
{160}{}{Você é mais idiota do que folgado não é? Se você quer ver o Vegeir, vá até ele por si mesmo.}

# cavernas
# - comum
#I don't trust "surfacers."
{200}{}{Eu não confio nas pessoas da superfície.}
#Vegeir said not to harm you...YET!
{201}{}{Vegeir disse pra você não se preocupar...POR ENQUANTO!}
#We are charged with protecting our people!
{202}{}{Estamos ocupados protegendo nosso povo.}
#I'm watching you.
{203}{}{Estou te observando.}

# - missão completa
#I guess you're OK... for a "surfacer."
{220}{}{Acho que você é bom... para alguém da superfície.}
#Maybe we can get along with the "surfacers."
{221}{}{Talvez possámos trabalhar juntos com estas pessoas da superfície.}
#I'm glad I was wrong about you.
{222}{}{Fico feliz de estar errado sobre você.}