#You see a pleasantly plump woman.
{100}{}{Você vê uma mulher agradavelmente gorda.}
#You see Rose.
{101}{}{Você vê Rose.}
#Her gray hair is done up in a loose bun, and she walks with a slight waddle. You can't help but
 feel relaxed around her.
{102}{}{Seus cabelos grisalhos é feito em um coque frouxo, e ela anda com um leve gingado. Você não pode ajudar, mas
  sentir-se relaxado em torno dela.}

#I'm sorry, we're closed. There's been a death in the family. [sniff]
{150}{}{Sinto muito, estamos fechados. Houve uma morte na família. [fungada]}
#Hey! I'm the only one allowed to go through the lost and found box.
{151}{}{Ei Eu sou a única que tem permissão para atravessar a caixa de achados e perdidos.}
#I'm beginning to think you're a thief!
{152}{}{Estou começando a pensar que você é um ladrão!}
#Thief! Thief! Thief!
{153}{}{Ladrao! Ladrao! Ladrao!}
#Welcome to Rose's Bed and Breakfast. My, aren't you the strapping young man. What can Rose help
 you with today?
{154}{}{Bem-vindo ao de Rose Bed and Breakfast. Meu, não é o jovem cintas. O que Rose pode ajudar
  você hoje?}
#Welcome to Rose's Bed and Breakfast. Oh my, what a pretty young lady you are. What can Rose do
 for you today?	
{155}{}{Bem-vindo ao de Rose Bed and Breakfast. Oh meu, o que é uma senhora muito jovem, você é. O que Rose pode fazer
  para você hoje?	}
#I'm starved! What do you have to eat around here?
{156}{}{Estou morrendo de fome! O que você tem que comer por aqui?}
#I'd like to rent a room for the night.
{157}{}{Eu gostaria de alugar um quarto para a noite.}
#You must hear things working here. Mind if I ask you a few questions?
{158}{}{Você deve ouvir muitas coisas pois trabalha aqui. Se importa se eu lhe fazer algumas perguntas?}
#You smack your lips with a loud POP]
{159}{}{[Você cheira seus lábios com um POP alto]}
#Glad to see you again! What can I do for you?
{160}{}{Fico feliz em vê-lo novamente! O que eu posso fazer por você
#Oh my! It's you. Everyone is talking about how you risked your life for us, and solved the
 mystery of the Ghost Farm. Know that you are always welcome here, and of course all your meals are on
 the house. You may also rummage through the lost and found box and take whatever you wish as a special
 reward.
{165}{}{Oh meu! É você. Todo mundo está falando sobre como você arriscou sua vida por nós, e resolveu o
mistério da fazeenda fantasma . Saiba que você é sempre bem-vindo aqui, e, claro, todas as suas refeições estão em
a casa. Você também pode vasculhar a caixa de achados e perdidos e levar o que quiser como um especial
recompensa.}
#It's the hero of Modoc! Welcome back.
{166}{}{É o herói do Modoc! Bem vindo de volta.}
#I'd really love to have one of your delicious omelets right about now.
{167}{}{Eu realmente adoraria ter uma de suas deliciosas omeletes agora mesmo.}
#That's what I like to hear. A growing young boy needs to eat to keep up his strength, and I can
 tell you haven't been eating properly. You just sit right down and look at the menu.
{168}{}{Isso é o que eu gosto de ouvir. Um menino novo que cresce precisa comer para manter a sua força, e eu posso
  diga que você não está comendo corretamente. Você se senta à direita para baixo e olhar para o menu.}
#And so you should be. When was the last time you had a good meal, young lady? Why, you're as
 thin as a rail. You just look at the menu and tell Rose what you would like to eat.
{169}{}{E assim que deveria ser. Quando foi a última vez que você teve uma boa refeição, mocinha? Por que, você é tão
  fino como um trilho. Você só olhar para o menu e diga Rose o que você gostaria de comer.}

{170}{}{Brahmin fries. [$5]}
{171}{}{Wasteland omelet. [$25]}
#Water. [$1000]
{172}{}{Água. [$ 1000]}
{173}{}{Brahmin dogs. [$5]}
{174}{}{Canis burgers. [$7]}
{175}{}{Shepherd's stew. [$3]}
#No thank you; I'm not hungry right now.
{176}{}{Não obrigado; Eu não estou com fome agora.}
#Oh, I'm sorry, but you don't seem to have enough money. Why don't you come back later?
{177}{}{Oh, me desculpe, mas você não parece ter dinheiro suficiente. Por que você não voltar mais tarde?}
#But I'm starving! Maybe I can order something cheaper.
{178}{}{Mas eu estou morrendo de fome! Talvez eu possa pedir algo mais barato.}
#Wait! Can I ask you a few questions?
{179}{}{Espere! Posso perguntar-lhe algumas perguntas?}
#Back for some more, I see. You must really like brahmin fries. I'm sorry; since you hold the
 record, you can't enter the contest again until somebody else breaks your score.
{180}{}{Voltar para algo mais, eu vejo. Você deve realmente gostar de batatas fritas brahmin. Sinto muito; desde que você mantenha o
  recorde, você não pode entrar no concurso novamente até que alguém quebra a sua pontuação.}
#Brahmin fries it is, then. We have a contest on who can eat the most Brahmin fries; so far, the
 record is 36. If you break the record, you don't have to pay the tab for your meal. You look like
 you'd be able to beat the record with no problem. Are you interested in trying?
{181}{}{Voltar para algo mais, eu vejo. Você deve realmente gostar de batatas fritas brahmin. Sinto muito; desde que você mantenha o
  recorde, você não pode entrar no concurso novamente até que alguém quebra a sua pontuação.}
#That's okay, I'm willing to pay to eat your delicious fried brahmin scrotum.
{182}{}{Tudo bem, eu estou disposto a pagar para comer o delicioso escroto brahmin frito.}
#I'm so hungry I can probably double that score. Bring it on.
{183}{}{Estou com tanta fome que eu provavelmente pode dobrar essa pontuação. Pode vir.}
#No thanks; just one order, please.
{184}{}{Não, obrigado; apenas um pedido, por favor.}
#Oh, that's just grand. Each order consists of 10 pieces. I'll have to ask you for the money up
 front. I'll refund it as soon as you break the record. That'll be $20, please.
{185}{}{Oh, isso é apenas grande. Cada pedido é composto por 10 peças. Eu vou ter que pedir-lhe o dinheiro até a
frente. Vou restituí-la logo que você quebrar o recorde. Isso vai ser US $ 20, por favor.}
#I don't have that much. Why don't I try for the record later? I'll just get one order. Thanks.
{186}{}{Eu não tenho muito. Por que não eu tento para o recorde mais tarde? Vou pegar uma ordem. Obrigado.}
#Sure, I'll get it back when I break the record.
{187}{}{Claro, eu vou buscá-la de volta quando eu quebrar o recorde.}
#[Rose takes the money and comes back with a heaping platter of brahmin fries. They are not
 quite what you expected. They appear to be about the size of golf balls, covered in batter and fried in
 oil to a deep, golden brown. You take a tentative bite of one of the fries. These are delicious! You
 start into the meal with zeal.]
{188}{}{[Rose pega o dinheiro e volta com um prato de batatas fritas amontoamento brahmin. Eles não são
bem o que você esperava. Eles parecem ser do tamanho de bolas de golfe, coberto de massa e frito em
óleo para uma profunda e marrom dourado. Você toma uma mordida tentative de uma das batatas fritas. Estes são deliciosos! você
começar na refeição com zelo.]}
#[At around the 34th fry, you start to feel the effects of overeating. A crowd has gathered to
 witness the historic event of the old record being broken. In an attempt to regain your composure, you
 strike up a conversation with Rose.]
{189}{}{[Por volta da 34ª fry, você começa a sentir os efeitos de excessos. Uma multidão se reuniu para
  testemunhar o acontecimento histórico do antigo recorde a ser quebrado. Em uma tentativa de recuperar a compostura, você
  iniciar uma conversa com Rose.]}
#[You pop a fry into your mouth.] 'Mmff… splt… mnch…' Don't talk with your mouth full, dear. [You
 swallow.]
{190}{}{[Se você estourar uma fritada em sua boca.] 'MMFF ... SPLT ... MNCH ... "Não fale com a boca cheia, querida. [Você engolir.]}
#How do you prepare these? If it's not a secret or anything, I know some people back home who
 would love these.
{191}{}{Como você se prepara estes? Se não tem um segredo ou qualquer coisa, eu sei que algumas pessoas voltariam para cá
  por esses pratos.}
#Oh, it's no secret. You just dip them in batter, add some salt and fry in grease. [You pop
 another one in your mouth.]
{192}{}{Oh, não é nenhum segredo. Você acabou de mergulhá-los em massa, adicione um pouco de sal e frite em gordura. [Você estalar
outro em sua boca.]}
#How do you prepare the brahmin meat? It has such a unique texture. [You pop yet another one in
 your mouth. These are good!]
{193}{}{Como você se prepara a carne brahmin? Tem uma textura única. [Você estalar ainda outro em
sua boca. Estes são bons!]}
#That's 37! You just broke the record! [The crowd cheers!]
{194}{}{Isso é 37! Você só quebrou o recorde! [Os aplausos multidão!]}
#[You feel like you've gotten you're second wind and pop another fry into your mouth.]
{195}{}{[Você se sente como você chegou você é o segundo vento e estala mais frite em sua boca.]}
#[The crowd yells, "38!"] Well, what makes ours taste so special is that you have to harvest it
 while the brahmin is still alive. You just grab the brahmin by the scrotum and 'snip' four with one
 cut. You've got be careful; the brahmin usually gets riled up at that point.
{196}{}{[A multidão grita: "38!"] Bem, o que faz com que o nosso gosto tão especial é que você tem para colhê-lo
enquanto o brahmin ainda está vivo. Você acabou de pegar o brahmin pelo escroto e 'cortar' quatro com uma
cortar. Você tem ter cuidado; o brahmin geralmente se irritam nesse ponto.}
#[The 38th brahmin tidbit must have been going at the speed of light as it is suddenly and
 forcefully propelled from your mouth.]
{197}{}{[[O boato brahmin 38 deve ter ido à velocidade da luz, pois é de repente e
  com força de propulsão de sua boca.]}
#We can't count that last one, but you broke the record at 37! Here's your money back.
 Congratulations!
{198}{}{Nós não podemos contar que o último, mas você quebrou o recorde a 37! Aqui está o seu dinheiro de volta.
  Parabéns!}
#[You feel sick.]
{199}{}{[[Você se sente doente.]}
#Ah, that's my specialty. I hope you're hungry; I guarantee you've never tasted an omelet like
 this one anywhere. [She leaves and returns with the biggest damn omelet you've ever seen.]
{200}{}{Ah, essa é a minha especialidade. Eu espero que você está com fome; Eu garanto que você nunca provou uma omelete como
  este um em qualquer lugar. [Ela sai e volta com a maior maldição omelete que você já viu.]}
#[You feel revitalized after such a big meal.]
{201}{}{[Você se sente revitalizado após uma grande refeição.]}
#[She quickly disappears behind the counter and returns with your order.]
{202}{}{[Ela desaparece rapidamente atrás do balcão e retorna com o seu pedido.]}
#Can I ask you a few questions?
{203}{}{Posso perguntar-lhe algumas perguntas?}
#I'm sorry, sweetie, I'm quite busy serving customers. Maybe if you ordered something I'll have
 time to chat with you between orders.
{204}{}{Sinto muito, querida, estou muito ocupado servindo clientes. Talvez se você pedir algo que vou ter
  tempo para falar com você entre as ordens.}
#In that case, I'm starving. What do you have to eat?
{205}{}{Nesse caso, eu estou morrendo de fome. O que você tem para comer?}
#Sure, but make it quick, dear. I don't want to keep the other customers waiting.
{206}{}{Claro, mas faça isso rápido, querida. Eu não quero que os outros clientes esperando.}
#What can you tell me about Cornelius's missing watch?
{207}{}{O que você pode me dizer sobre relógio sumido de Cornélio?}
#Have you ever heard of a GECK?
{208}{}{Alguma vez você já ouviu falar de um GECK?}
#What do you know about the Ghost Farm?
{209}{}{O que você sabe sobre a Fazenda Fantasma?}
#I've never seen an omelet the size of the one you served me. What kind of animal lays such a
 large egg?
{210}{}{Eu nunca vi uma omelete do tamanho do que você me serviu. Que tipo de animal estabelece tal
  ovo grande?}
#What's a canis burger made of?
{211}{}{O que é um hambúrguer canis é feito?}
#Oh dear! Have you been talking to my husband Cornelius? This whole business with the watch is
 just terrible. Cornelius has got the whole town believing that his best friend, Farrel, took his watch.
 If you've talked to him, I'm sure you've noticed his mind isn't quite functioning properly. I'm pretty
 sure the poor dear just left the watch somewhere and forgot where.
{212}{}{Oh céus! Você foi falar com meu marido Cornelius? Todo esse negócio com o relógio é
  simplesmente terrível. Cornelius tem a cidade inteira acreditando que seu melhor amigo, Farrel, tirou o relógio.
  Se você já conversou com ele, tenho certeza que você notou sua mente não está completamente funcionando corretamente. Sou linda
  certeza de que o pobre coitado apenas deixou o relógio em algum lugar e esqueceu onde.}
#Now, if you don't need anything else, I have other customers to serve.
{213}{}{Agora, se você não precisa de mais nada, eu tenho outros clientes para servir.}
#Can I ask you a few more questions?
{214}{}{Posso lhe fazer mais algumas perguntas?}
#One moment, I'm still hungry.
{215}{}{Um momento, eu ainda estou com fome.}
#Did you say GECK? No, I can't say that I have. I have heard of good soup recipe that requires
 three geckos. But no, I haven't heard of anything about a GECK.
{216}{}{Queria dizer GECK? Não, eu não posso dizer que eu tenho. Tenho ouvido de boa receita de sopa que exige
  três lagartixas. Mas não, eu não ouvi falar de nada sobre um GECK.}
#[She shivers involuntarily.] Stay away from there! I've heard tales from travelers about
 rotting bodies tied to stakes, and glowing shapes moving through the fields at night. I don't know how
 much of this is true, but I do know a while back Karl moved out there and hasn't been seen since.
{217}{}{[Ela treme involuntariamente.] Fique longe de lá! Eu ouvi contos de viajantes sobre
  apodrecendo corpos amarrados a estacas, e as formas que se deslocam através dos campos à noite brilhante. Eu não sei como
  grande parte isso é verdade, mas eu sei que há um tempo atrás Karl se mudou para lá para fora e não foi visto desde então.}
#Ah, you've had the desert omelet. Delicious, wasn't it? Some people say it has healing
 properties. [She looks around nervously.] Oh! Some customers just came in. I'll be right back. [Hmm…
 She never answered your question.]
{218}{}{Ah, você teve a omelete deserto. Delicioso, não foi? Algumas pessoas dizem que tem cura
 propriedades. [Ela olha em volta, nervosamente.] Oh! Alguns clientes apenas entrou. Eu já volto. [Hmm ...
 Ela nunca respondeu a sua pergunta.]}
#Our burgers are made of nothing but the choicest, select, grade-A dog. The meat is ground up and
 made into half-pound patties. And to give it that unique smoky flavor, they are slow grilled over dried
 brahmin dung.
{220}{}{Nossos hambúrgueres são feitos do mais bem escolhido, selecione, categoria-Um cão. A carne é moído e
feito em pequenos pasteis de metade-libra. E para dar aquele sabor smoky exclusivo, eles são grelhado lentamente sobre secas
esterco brahmin.}
#You poor thing. You look half starved. Come sit down and let Rose get you something to eat. [She
 leaves and returns with a large omelet.] Now, you don't move from that spot until you finish every bit
 of that.
{221}{}{Pobrezinho. Você parece faminto. Vamos sentar e deixar Rose pegar algo para comer. [Ela
folhas e retorna com uma grande omelete.] Agora, você não se move a partir desse ponto até que você termine cada pedacinho
daquilo.}
#Sorry, we're full up. A large caravan has all the rooms rented.
{222}{}{Desculpe, Estamos lotados. Uma grande caravana tem todos os quartos alugados}
#Really!? You must be really thirsty. I raised the price to discourage customers from ordering it.
 Drinking water is at a premium out here, with the lack of rain and the well drying up. Do you still want
 some?
{225}{}{Realmente !? Você deve estar com muita sede. Eu elevei o preço para desencorajar os clientes de pedidos.
 A água potável é um prêmio aqui, com a falta de chuva estar bem seco. Você ainda quer
 algo?}
#Yes! I need water desperately.
{226}{}{Sim! Eu preciso desesperadamente de água.}
#Actually, I'm really hungry.
{227}{}{Na verdade, eu estou realmente com fome.}
#I'm sorry, we stopped serving omelets. Some fool broke into our coop and killed our… chicken.
{228}{}{Sinto muito, paramos de servir omeletes. Algum idiota quebrou em nosso galinheiro e matou o nosso ... frango.}
#I'm really hungry, so let's see what else you have.
{229}{}{Estou realmente com fome, então vamos ver o que mais você tem.}
#I was really looking forward to your world-famous omelet. I guess I'll go hungry.
{230}{}{Eu estava realmente ansioso para o seu mundialmente famoso omelete. Acho que vou passar fome.}
{231}{}{Ahh! Oogie!}

#[She quickly returns with a glass of some brownish liquid substance. It appears that there is
 more dirt than water in the glass. However, you are so thirsty that you drink it anyway.] I brought
 a cookie for you to enjoy with that, sweetie.
{300}{}{[Ela retorna rapidamente com um copo de alguma substância líquida acastanhada. Parece que existe
 mais sujeira do que a água no copo. No entanto, você é tão sedento que você bebe de qualquer maneira.] Trouxe
 um cookie para você desfrutar com isso, querida.}