# Description
# Descrição
#You see a scruffy little lad hard at work caring for the brahmin.
{100}{}{Você vê um rapaz imundo de tanto trabalhar cuidando do brahmin.}
#You see the stable boy.
{101}{}{Você vê um vaqueiro.}
# Examine:
# Examinar:
#He seems to be busy.
{150}{}{Ele parece ocupado.}

# General
# Geral
#Sorry, the stables are full. You'll have to look elsewhere.
{200}{}{Sinto muito, mas os estábulos estão cheios. Você terá de procurar em outro lugar.}
#I'm really busy right now.
{201}{}{Estou realmente ocupado agora.}

# If shitter is exploded
# Se a privada explode
#Smell? I guess you get used to it.
{250}{}{Esse cheiro? Acho que você logo se acostuma com isso.}
#It doesn't smell that bad.
{251}{}{Não está fedendendo tanto assim.}
#I guess I don't have to fertilize the fields this year. Thanks.
{252}{}{Acho que não precisarei fertilizar o solo esse ano. Obrigado.}

# Comentários Geral do Estábulo
#This one needs some fresh hay.
{300}{}{Esse aqui precisa de um pouco de feno fresco.}
#Got to get some more water.
{301}{}{Tenho que ir pegar mais água.}
#Whew! Time to get the shovel.
{302}{}{Vish! Hora de trabalhar.}
#Everything seems okay with this one.
{303}{}{Parece tudo tranquilo com esse aqui.}
#Better keep an eye on this one. Looks a little sick.
{304}{}{Acho bom ficar atento com esse aqui. Se parece um pouco doente.}

# trying to sleep
# tentando dormir
#Zzz... I'm sleeping... Zzz...
{350}{}{Zzz... estou dormindo... Zzz...}
#*YAWN* I've gotta be up early.
{351}{}{*YAWN* Tenho que acordar cedo.}
#Hey, I'm still growing. I need my sleep.
{352}{}{Pô, eu ainda estou na fase de crescimento. Preciso dormir.}
#Why don't you go talk to someone else.
{353}{}{Por que você não vai conversar com outro?}
#Boy, I sure am sleepy. If only someone wouldn't keep talking to me.}
{354}{}{Cara, eu estou com muito sono. Se ao menos não tivesse ninguém conversando comigo...}