# 0. Olhar
#Seems to be a guard of some sort.
{100}{}{Parece algum tipo de guarda.}
#You see a Protector.
{101}{}{Você vê um Protetor.}
#Besides the pale skin and enlarged pupils, he looks to be an ordinary person.
{150}{}{Além da pele pálida e pupilas dilatadas, ele parece ser uma pessoa comum.}

# 1. Floats - Quando o jogador cai no buraco pela primeira vez
#Holy shit!
{200}{}{Puta merda!}
#Oooh! Now that's gotta hurt.
{201}{}{Oooh! Essa vai doer.}

# 2. ( ) Floats - Quando o jogador cai no buraco outras vezes.
#You do know you can enter from the back door...
{210}{}{Você sabe que pode entrar pela porta dos fundos.}
#Bwahahahaha!
{211}{}{Bwahahahaha!}
#I'm not going to say a word.
{212}{}{Não vou falar nada.}
#Oh god! You're killing me! Do it again!
{213}{}{Meu Deus! Você está me matando! Faça de novo!}
#What and idiot!
{214}{}{Que idiota!}
#Hahahaha!
{215}{}{Hahahaha!}

# 3. ( ) Primeira vez falando.
#We have been instructed to take all surfacers to Vegeir. You will not be harmed. Please come with us.
{220}{}{Fomos intruídos para levar todos da superfície até Vegeir. Você não vai se machucar. Por favor venha conosco.}
#Go to hell, I'm not going anywhere with you.
{221}{}{Vai pro inferno, não vou a lugar nenhum com você.}
#I'd like to ask you some questions.
{222}{}{Gostaria de fazer alguns perguntas.}
#Duh?
{223}{}{Quê?}

# 4. ( ) Vai pro inferno
#Let me elaborate on my previous statement. You will not be harmed UNLESS you resist. Are you resisting?
{224}{}{Vou repetir. Você não vai se machucar SE você não resistir. Você vai resistir?}
#{Yes, I am absolutely going to resist you.
{225}{}{Sim, eu vou resistir.}
#No, I know resistance is futile. I'll go with you.
{226}{}{Não, eu sei que resistir é inútil. Irei com vocês.}

# 5. ( ) Perguntas
#Vegeir will answer all your questions. Please come with us.
{230}{}{Vegeir vai te fazer algumas perguntas. Por favor venha conosco.}
#Okay, I'll go with you peacefully for now.
{231}{}{Beleza, irei com vocês pacificamente por enquanto.}
#No, I'm not going anywhere with you unless I get some answers.
{232}{}{Não, não irei a lugar nenhum se você não me der algumas respostas.}

# 6. ( ) Você é idiota!
#Hmm…I wonder if this is an exception to the rule. No, no, no. Vegeir said ALL surfacers,
 even the idiots. Come with me.
{240}{}{Hmm… Me pergunto se essa é uma exceção na regra. Não, não e não. Vegeir disse que TODOS da superfície, 
até os idiotas. Venha comigo.}
#[Go with the guards.]
{241}{}{[Ir com os guardas.]}
#[Kill them all and let whatever gods they worship sort them out.]
{242}{}{[Mate todos eles e deixe que os deuses que eles adorem se virem.]}

# 7. ( ) Floats atuais.
#I'm sorry; you can't leave this way.
{250}{}{Sinto muito; você não pode ir por aí.}
#This entrance is for the workers.
{251}{}{Essa entrada é exclusiva para trabalhadores.}
#It takes too much effort set up the ramps for just one person.
{252}{}{Dá muito trabalho levantar as rampas para apenas uma pessoa.}
#If you want to leave, ask Vegeir.
{253}{}{Se você quer ir embora, fale com Vegeir.}

# goes in node 3
# vai no nó 3
{260}{}{Ogey Dogey.}
