# Fugir
#Run
{100}{}{Corra!}
#Help
{101}{}{Ajude!}
#We're being attack by the surfacers.
{102}{}{Estamos sob ataque da superfície.}
#Leave us in peace.
{103}{}{Deixe-nos em paz.}
#Can't we all just get along?
{104}{}{Não podemos simplesmente trabalhar juntos?}

# Atacar
#Go back where you came from.
{150}{}{Volte para onde veio.}
#You're not wanted here.
{151}{}{Você não é bem vindo aqui.}
#All you surfaces are alike.
{152}{}{Todos vocês da superfície são iguais.}
#You will not escape.
{153}{}{Você não vai escapar.}

# Diálogo atual (acima do solo)
#Groan!
{200}{}{Groan!}
#Boo
{201}{}{Boo!}
#Moaaaaaan.
{202}{}{Moaaaaaaan.}
#*Clank*
{203}{}{*Clank*}
#*Clank*
{204}{}{*Clink*}

# Diálogo atual (abaixo do solo)
#We used to live above ground.
{250}{}{Costumávamos viver na superfície.}
#What's it like above ground?
{251}{}{Como é lá na superfície?}
#It's so BIG up there.
{252}{}{Lá em cima é ENORME.}
#What's the sun look like?
{253}{}{Como o sol se parace?}
#Hello, surfacer.
{254}{}{Olá, pessoa da superfície.}

# Diálogo atual quando a Semente está pronta
#I knew we could trust you.
{300}{}{Sabia que poderia confiar em você.}
#Thank you for helping us.
{301}{}{Obrigado por nos ajudar.}
{302}{}{Nice to see you again.}