#You see a trader.
{500}{}{Você vê um comerciante.}

# Comum (Roses B&B)
# Rose makes the best omelets.
{100}{}{A Rose faz os melhores omeletes.}
#Psst… Stay away from the brahmin fries.
{101}{}{Psiu… Fique longe dos Brahmin fritos.}
#I stop by Rose's every chance I get.
{102}{}{Eu venho aqui sempre que posso.}
#Have tou tried Roses's omelets?
{103}{}{Você já experimentou os omeletes que a Rose faz?}

# If player blows up the shitter (Roses B&B)
# Se o jogador entope a privada (Roses B&B)
#Do you smell something?
{110}{}{Você sentiu esse cheiro?}
#Good god! What the hell have you been rolling in!
{111}{}{Puta que pariu! O que você tem comido?}
#Could you please stand downwind? I'm trying to eat.
{112}{}{Você poderia sair da frente do vento por favor? Estou tentando comer.}

# Bedroom (Rose's B&B)
# Banheiro (Rose's B&B)
#Do you mind? I'm trying to get some sleep.
{120}{}{Algum problema? Estou tentando dormir.}
#Hey, what are you doing in my room?!
{121}{}{Ei, o que você está fazendo no meu quarto?!}
#Get out!
{122}{}{Saia!}

# If player let the chicken out of the coop (Roses B&B) overrides above text
# Se o jogador deixar a galinha fugir do galinheiro (Roses B&B) substitui o texto acima
#Rose is out of omelets.
{130}{}{Os omeletes acabaram.}
#I'll kill the person who let her chicken escape.
{131}{}{Vou matar a pessoa que deixou a galinha dela escapar.}
#There's no point in coming here if I can't get an omelet.
{132}{}{Não faz sentido vir aqui se não vou poder comer um omelete.}

# Pre Ghost General
# O Fantasma Comum 
#I don't know why I bother to come here to trade.
{140}{}{Eu nem sei por que me incomodo de vir aqui para negociar.}
#This town is dying.}
{141}{}{Essa cidade está morrendo.}
#This used to be a prosperous farming town.
{142}{}{Essa lugar costumava ser um próspera cidade rural.}

# If player kills Slags by himself
# Se o jogador matar os Escórias sozinhp
#I hear Modoc 'acquired' a prosperous farm northeast of here.}
{150}{}{Ouvi falar que Modoc 'adquiriu' uma próspera fazendo a nordeste daqui.}
#I don't know if I want to trade for food grown at the Ghost Farm.
{151}{}{Eu não sei se quero comprar aliementos produzidos na Fazenda Fantasma.}
#The crops at the Ghost Farm are probably cursed.
{152}{}{As lavouras na Fazenda Fantasma devem estar amaldiçoadas}

# Se a cidade chacina a fazenda fantasma
#I hear they slaughtered innocent women and children.
{160}{}{Ouvi falar que eles mataram mulheres e crianças inocentes.}
#I don't want to trade with savages who kill recklessly.
{161}{}{Não quero negociar com selvagens que matam sem motivos.}
#After I heard what they did, I almost puked.
{162}{}{Depois de ouvir o que eles disseram eu quase vomitei.}
#Whatever their reason, I don't think I'll be coming by Modoc to trade anymore.
{163}{}{Seja quais forem suas razões, acho que não virei mais aqui por Modoc para negociar.}
#The people of Modoc are killers.
{164}{}{As pessoas de Modoc são assassinos.}

# If the player completes ghost farm seed - best ending.
# Se o jogador completa a semente da fazenda fantasma - melhor final.
#Looks like things are looking up around here.
{170}{}{Parece que as coisas estão melhorando por aqui.}
#I'll probably need to hire another team to carry all the food from here.
{171}{}{Parece que vou precisar de contratar mais algumas pessoas para carregar toda comida daqui.}
#It looks as if Modoc is going to be alright after all.
{172}{}Parece que Modoc vai ficar bem afinal.}