#You see the leader of the Slags.
{100}{}{Você vê o líder dos Slags.}
#You see Vegeir.
{101}{}{Você vê Vegeir.}
#A tall, stately man. His movements remind you of a cat stalking its prey.
{102}{}{Um homem alto e imponente. Seus movimentos te lembram um gato espreitando sua presa.}

#You may leave through the trap door located at the rear of this building.
{150}{}{Você pode sair pelo alçapão localizado na parte de trás desse prédio.}
#Please deliver the message to Modoc.
{151}{}{Por favor entregue a mensagem em Modoc.}
#Modoc is south of here.
{152}{}{Modoc é ao sul daqui.}
#South
{153}{}{Sul.}
#No, the other south.
{154}{}{Não, o outro sul.}
#A visitor - how convenient. I've been contemplating on a way to make contact with the surfacers,
 but now I don't have to worry about that -- thanks to your timely arrival. Welcome to the home of the
 Slags.
{155}{}{Um visitante - que conveniente. Estava pensando em um jeito de fazer contato com o povo da superfície,
 mas agora eu não preciso me preocupar com isso -- graças a sua chegada na hora certa. Bem vindo ao lar dos
 Slags.}
#How good of you to return. I take it you have delivered the message to Modoc, then. How was it
 received?
{156}{}{Que bom que você voltou. Então, eu presumo que você entregou a mensagem em Modoc. Como ela foi
 recebida?}
#They need time to think it over.
{157}{}{Eles precisam de tempo para pensar no assunto.}
#They have some reservations.
{158}{}{Eles tem algumas restrições.}
#I want to take Jonny home to his parents.
{159}{}{Eu quero levar Jonny para casa, para seus pais.}
#Have you reconsidered helping us?
{160}{}{Você reconsiderou nos ajudar?}
#I need to ask you some questions, first.
{161}{}{Primeiro, eu preciso fazer algumas perguntas.}
#The answer is still no.
{162}{}{A resposta ainda é não.}
#I have decided to help you.
{163}{}{Eu decidi te ajudar.}
#Thank you for helping us. You will always be welcome here. For your services, I offer this as a
 reward. [Vegeir hands you an assault rifle.]
{165}{}{Obrigado por nos ajudar. Você sempre será bem vindo aqui. Por seus serviços, eu te ofereço isso como
 recompensa. [Vegeir te entrega um assault rifle.]}
#Thank you for helping us. You will always be welcome here.
{166}{}{Obrigado por nos ajudar. Você sempre será bem vindo aqui.}
#Would it be all right to take Jonny home to his parents?
{167}{}{Está tudo bem em levar o Jonny de volta para seus pais?}
#Please let me apologize for the unpleasant circumstances under which we meet. Normally, the
 Protectors would have tried to scare you off. Usually rattling chains and some low moaning is
 enough to scare anybody off, but recently they have been instructed to bring any surfacers they find
 to me.
{168}{}{Por favor deixe me desculpar pelas circunstâncias desagradáveis em que nos conhecemos. Normalmente, os
 Protetores teriam tentado te assustar. Normalmente chacoalhando correntes e alguns gemidos baixos é
 o suficiente para assustar qualquer um, mas recentemente eles receberam ordens para me trazer qualquer pessoa da superfície que eles
 encontrarem.}
#That's all right. I'll just be going now.
{169}{}{Está bem. Estou indo agora.}
#What do you want with me?
{170}{}{O que você quer comigo?}
#Ghosts?
{171}{}{Fantasmas?}
#You will go IF and WHEN I decide you can go. Not before.
{172}{}{Você sairá SE e QUANDO eu decidir que você pode ir. Não antes disso.}
#A simple request. We need to make contact with the town to the southwest; I believe it is called
 "Modoc." Would you do us this favor?
{173}{}{Uma tarefa simples. Nós precisamos fazer contato com a cidade a sudoeste; Eu acredito que se chama
 "Modoc." Você poderia nos fazer esse favor?}
#What do I get out of this?
{174}{}{Como que eu saio disso?}
#I have many questions to ask before I can possibly take this mission.
{175}{}{Eu tenho que fazer muitas perguntas antes de possivelmente aceitar essa missão.}
#Fair enough. I wouldn't expect anyone to blindly accept tasks from strangers without first
 learning a little bit about them. Ask your questions, and I will answer them as best I can.
{176}{}{É justo. Eu não esperava que alguém aceitasse cegamente tarefas de estranhos, sem primeiro aprender
 um pouco sobre eles. Faça suas perguntas, e eu vou responder da melhor forma que eu puder.}
#Why don't you send one of your own people to deliver the message?
{177}{}{Por que você não manda um dos seus homens para entregar a mesnsagem?}
#Tell me about your people.
{178}{}{Me conte sobre o seu povo.}
#What are your defenses?
{179}{}{Quais são suas defesas?}
#I have heard enough. I am ready to make my decision.
{180}{}{Eu já escutei o suficiente. Estou pronto para tomar minha decisão.}
#Ask your questions.
{181}{}{Faça suas perguntas.}
#Why did you come back to the surface?
{190}{}{Por que você voltou para a superfície?}
#Why the big ghost charade on the surface?
{191}{}{Por que a grande charada fantasma na superfície?}
#What is the purpose of your message?
{192}{}{Qual é o propósito da sua mensagem?}
#Since the Sealing, we, as a people, have changed. Few can bear to be on the surface because they
 are not used to having a black sea of nothingness above them. The sensation of falling upward is so
 great for them that they lie frozen, clutching the ground. But that is not the main reason. All of us
 cannot stand the bright light of that which you call the sun; living underground for so long has made
 our eyes too sensitive to light. We cannot travel far from the safety of our homes beneath the ground.
{194}{}{Desde o Selamento, nós, como um povo, mudamos. Poucos conseguem suportar estar na superfície porque eles
 não estão acostumados a ter um mar negro de nada sobre eles. A sensação de estar caindo para cima é tão
 grande para eles, que eles ficam congelados, grudados no chão. Mas essa não é a razão principal. Todos nós
 não suportamos a luz brilhante que vocês chamam de sol; vivendo no subterrâneo por tanto tempo fez nossos
 olhos ficarem sensíveis à luz. Nós não podemos viajar muito longe da segurança de nossos lares embaixo da terra.}
#Can I ask you some more questions?
{195}{}{Posso fazer mais algumas perguntas?}
#Once, long ago, we were once like the surfacers. We too dwelled above ground, until the world
 above caught fire. Our ancestors -- who were part of a secret militia -- sealed themselves and their
 families down here for protection. For generations, down here we've remained, safely hidden within
 the womb of Mother Earth.
{197}{}{Uma vez, há muito tempo, nós erámos parecidos com o povo da superfície. Também morávamos acima do solo, até que o mundo
 da superfície pegou fogo. Nossos ancestrais -- que faziam parte de uma milícia secreta -- selaram eles mesmos e suas
 famílias aqui embaixo para proteção. Por gerações, permanecemos aqui embaixo, escondidos em segurança
 no ventre da Mãe Terra.}
#Our population steadily increased since the Sealing. It soon became apparent that we could
 no longer survive down here without further supplies. So the Seal was broken, and we once again looked
 to the surface for survival.
{200}{}{Nossa população aumentou de forma constante após o Selamento. E logo ficou claro que não poderíamos
 sobreviver por muito tempo aqui embaixo sem suprimentos. Então o Selo foi quebrado, e de novo nós olhamos
 para a superfície em busca de sobrevivência.}
#Years ago, someone tried to take over our farm, harvesting crops and stealing animals
 they had no right to. We are not a violent people by nature, but something had to be done. Our
 survival at the time depended on those crops. That's when we came up with the ghost idea. Smearing
 ourselves with glowing fungus, we were able to scare away this person and any other nosy neighbors.
 Unfortunately, this has been a little too effective. Lately, we've been seeking to make contact with
 the surfacers, but no one comes to the farm anymore for fear of the ghosts. Luckily, you dropped by.
{203}{}{Anos atrás, alguém tentou tomar nossa fazenda, colhendo as plantações e roubando animais
 a que eles não tinham direito. Nós não somos pessoas violentas por natureza, mas alguma coisa tinha de ser feita. Na época
 nossa sobrevivência dependia dessas plantações. Foi quando tivemos a ideia dos fantasmas. Nos cobrindo
 com fúngus brilhantes, fomos capazes de assustar essa pessoa e outros vizinhos curiosos.
 Infelizmente, foi um pouco eficaz demais. Ultimamente, nós temos tentado fazer contato com
 o povo da superfície, porém ninguém mais apareceu na fazenda com medo dos fantasmas. Por sorte, você caiu aqui.}
#Enough! No more questions. Make your decision now!
{206}{}{Chega! Sem mais perguntas. Tome sua decisão agora!}
#I am sorry; I cannot help you.
{207}{}{Me desculpe; Eu não posso te ajudar.}
#Yes, I will gladly carry your message to Modoc.
{208}{}{Sim, eu terei prazer em levar sua mensagem para Modoc.}
#I am sorry to hear that. Please consider yourself a guest of the Slags. When we finally
 establish contact with the surfacers, you will be allowed to leave. Until then, do not try to
 the leave the caves - the consequences would be most unpleasant.
{209}{}{Sinto muito ouvir isso. Por favor se considere um convidado dos Slags. Quando nós finalmente
 estabelecer contato com o povo da superfície, nós permetiremos você sair. Até lá, não tente
 sair das cavernas - as consequências serão desagradáveis.}
#With the completion of the new irrigation systems, our food supply far exceeds our needs. We
 wish to establish trade with the surfacers and exchange surplus foods for much needed medicines.
{210}{}{Com a conclusão do novo sistema de irrigação, nosso suprimento de comida vai exceder em muito as nossas necessidades. Nós
 queremos estabelecer um comércio com o povo da superfície e trocar suprimentos de comida por rémedios necessários.}
#Please enlighten us with your wisdom.
{213}{}{Por favor nos ilumine com sua sabedoria.}
#I knew you would understand. Here is a message relaying our request. Please take it to Modoc
 and give it to the person in charge. Return here when your task is complete. I will tell the Protectors
 to expect your return. We thank you for doing us this service.
{216}{}{Eu sabia que você entenderia. Aqui está a mensagem transmitindo nosso pedido. Por favor leve-a para Modoc
 e entregue para a pessoa no comando. Retorne aqui quando completar a tarefa. Eu irei dizer para os Protetores
 aguardarem seu retorno. Agradecemos por você fazer esse serviço para nós.}
#How typical of surfacers. Never doing anything for anyone unless there is some kind of personal
 gain involved. Obviously, we cannot trust such a person as you. We will find someone else to deliver the
 message. Although we are not a violent people, do not attempt to leave the caves or you will regret it.
{217}{}{Típico do povo da superfície. Nunca fazem nada para alguém se não tiver ganho pessoal
 envolvido. Obviamente, não confiamos em pessoas como você. Iremos encontrar alguma outra pessoa para entregar a
 mensagem. Apesar de não sermos pessoas violentas, não tente sair das cavernas ou irá se arrepender.}
#Hmm… I understand. Such a decision cannot be made lightly. Please keep me informed of their
 progress.
{218}{}{Hmm… Eu entendo. Tal decisão não pode ser tomada assim. Por favor me mantenha informado de seu
 progresso.}
#Then do not bother me any more.
{219}{}{Então não me incomode mais.}
#About what?
{220}{}{Sobre o quê?}
#They don't trust you. After all, they think you kill passersby and stake the bodies out in front of your
 farm.
{221}{}{Eles não confiam em vocês. Afinal, eles pensão que vocês matam quem passa por aqui e empalam os corpos na frente da sua
 fazenda.}
#They want to know what happened to the farmer that was living here.
{222}{}{Eles querem saber o que aconteceu com o fazendeiro que vivia aqui.}
#We are a peaceful people, and have killed no one. Those bodies are merely props we manufactured
 to scare off those who try to steal from us. If you examine the bodies closely, you'll notice that they
 are nothing but brahmin guts and dummies.
{223}{}{Nós somos um povo pacífico, e não matamos ninguém. Esses corpos são meros bonecos que fizemos
 para assustar aqueles que tentam roubar de nós. Se você examinar os corpos de perto, você vai notar que eles não passam de
 de tripas de brahmin e palha.}
#Then what about poor Karl? You know, the farmer that was living on your farm?
{224}{}{E sobre o pobre Karl? Você sabe, o fazendeiro que vivia na sua fazenda?}
#Was that his name, Karl? We scared him off the farm, nothing more. I assume he went back home
 when he discovered the farm was haunted. The Protectors reported him headed west. You might try
 searching for him that way.
{225}{}{Esse era o nome dele, Karl? Nós assustamos ele, nada mais. Eu acredito que ele voltou para casa
 quando descobriu que a fazenda era assombrada. Os Protetores me informaram que ele foi para oeste. Você pode tentar
 procurá-lo nessa direção.}
#I'll keep you informed of my progress.
{226}{}{Vou te manter informado sobre o meu progresso.}
#We scared him off the farm -- nothing more. I assume he went back home when he discovered the
 farm was haunted. The Protectors reported him headed northwest. You might try searching for him that
 way.
{227}{}{Nós o assustamos -- nada mais. Eu acredito que ele voltou para casa quando descobriu que
 a fazenda era assombrada. Os Protetores informaram que ele seguiu para noroeste. Você pode tentar procurá-lo nessa
 direção.}
#I see you've met Jonny. We found him wandering in the darkness of one of our deepest tunnels.
 He said he had fallen down a dry well by his house, and then was trapped in a tunnel by a cave in. We
 have treated him as one of our own and he is loved by all -- so you will understand that I am wary of
 entrusting him to a stranger who has yet to prove himself to me as trustworthy. I will return Jonny
 when I am sure he will make it home safely.
{231}{}{Vi que você conheceu o Jonny. Nós o encontramos vagando na escuridão de um dos nossos túneis mais profundos.
 Ele disse que caiu em um poço seco perto de sua casa, e então ficou preso em um túnel com uma caverna. Nós
 tratamos ele como um de nós e ele é amado por todos -- então você entenderá porque estou com receio de
 entregá-lo a um estranho que ainda tem que provar ser de confiança. Eu irei devolver o Jonny
 quando eu tiver certeza que ele chegará em casa com segurança.}
#You have proven your trustworthiness without doubt. Despite the fact that we'll miss little Jonny
 down here, we have arranged an escort for you and Jonny to go back to Modoc right now.
{232}{}{Você provou ser de confiança sem deixar dúvidas. Tirando o fato de que iremos sentir falta do pequeno Jonny
 , nós iremos arrumar uma escolta para você e o Jonny voltarem para Modoc imediatamente.}
#Oh boy! No wonder you weren't scared away by our little tricks. You're too stupid to be scared.
 I hate to depend on such an intellectually challenged individual, but we have need of your services.
 Take this message to Modoc. Give to leader of Modoc and try not to get lost.
{233}{}{Oh cara! Não acredito que você não se assustou com os nossos pequenos truques. Você é muito idiota para se assustar.
 Eu odeio depender de um indivíduo tão desafiado intelectualmente, mas nós precisamos dos seus serviços.
 Leve essa mensagem para Modoc. Entregue para o líder de Modoc e tente não se perder.}

#I'll just be going now.
{300}{}{Estou indo agora.}
#What do you want with me?
{301}{}{O que você quer de mim?}
#Bye
{302}{}{Tchau.}
#Ghosts?
{303}{}{Fantasmas?}

#The message was received well. The town of Modoc would like to establish trade with your people.
{400}{}{A mensagem foi bem recebida. A cidade de Modoc gostaria de estabelecer comércio com o seu povo.}
