#You see a wall safe.
{100}{}{Você vê um cofre de parede.}

#The safe is locked.
{110}{}{O cofre está trancado.}

#You successfully unlock the wall safe.
{200}{}{Você destrancou o cofre de parede com sucesso.}
#You successfully lock the wall safe.
{201}{}{Você trancou o cofre de parede com sucesso.}

#You fail to lock the wall safe.
{210}{}{Você falhou em trancar o cofre de parede.}
#You fail to unlock the wall safe.
{211}{}{Você falhou em destrancar o cofre de parede.}
