#An old, boarded-up well. It looks as if the boards are loose.
{100}{}{Um velho poço. Parece que as tábuas estão soltas.}
#An old well. The walls of the well are very slick; you would need a rope to climb down safely.
{101}{}{Um velho poço. As paredes estão muito escorregadias, você vai precisar de uma corda pra descer em segurança.}
#An old well with a rope leading down to the bottom.
{102}{}{Um velho poço com uma corda que leva até o fundo.}