#############################################################
#  Message File: ModMain.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

#A small, quaint farming community, surrounded by vast fields of dead or dying crops.
{100}{}{Uma pequena, comunidade agrícola rudimentar, cercada por vários campos de plantações mortas ou morrendo.}

# from the vermin hunter seed
#Looks like I killed them all.
{500}{}{Parece que eu matei todos eles.}
#All meanie biters dead
{501}{}{Todos os roedores malvados morreram.}
#You cleared out Farrel's garden.
{502}{}{Você limpou o jardim do Farrel.}

# Coin Bag Descriptions
#You see a coin bag.
{600}{}{Você vê uma sacola de moedas.}
#You see a coin bag. Someone probably tossed it into the well to make a wish.
{601}{}{Você vê uma sacola de moedas. Provavelmente alguém jogou dentro do poço para fazer algum pedido.}
#This is MY dream, MY wish, and I'm taking it back. I'm taking them all back.
{610}{}{Esse é o MEU sonho, MEU desejo, e eu estou pegando de volta. Estou pegando tudo de volta.}

# KILL THEM ALL
#Kill them all!
{1000}{}{Matem todos!}
#Death to the Slags!
{1001}{}{Morte aos Slags!}
#I wanna watch 'em scream!
{1002}{}{Eu quero ve-los gritar!}
#Let's go get 'em!
{1003}{}{Vamos pegá-los!}

# fall through floor
#You fall some 15 feet into a dimly lit cave. Various farming equipment lays neatly
 stored against the far wall.
{1100}{}{Você cai cerca de 4 metros em uma caverna mal iluminada. Vários equipamentos agrícolas estão organizados
 na parede oposta.}

# blown out of hole
#You made it out of the hole just in time for the explosion to go off behind you,
 sending you flying through the air.
{1200}{}{Você consegue sair do buraco bem na hora da explosão,
 mandando você pelos ares.}
