# You see...another...Vault City official.
{100}{}{Você vê...mais um...funcionário de Vault City.}
# You see Barkus, the Vault City Servant Coordinator.
{101}{}{Você vê Barkus, Coordenador de Servos de Vault City.}
# What th--?! A mutant! In Vault City! Guards! Guards!
{102}{}{Que diabos--?! Um mutante! Em Vault City! Guardas! Guardas!}
# What th--?! A ghoul! In Vault City! Guards! Guard!
{103}{}{Que diabos--?! Um ghoul! Em Vault City! Guardas! Guarda!}
# Umm...hurnhh?
{104}{}{Umm...hurnhh?}
# If it's a fight you want...
{105}{}{Se é briga que você está querendo...}
# The Servant Allocation Center is closed. Please return in the morning.
{106}{}{O Centro de Alocação de Servos está fechado. Por favor, retorne pela manhã.}
# Yes, Captain?
{107}{}{Pois não, Capitão?}
# Yes, Citizen?
{108}{}{Pois não, Cidadão?}
# Yes, what is it? I'm behind in my assignments.
{109}{}{Sim, o que é? Estou atrasado com minhas atribuições.}
# Umm...Me luuwk Valt!
{110}{}{Umm...Mim prucurar Vault!}
# Shamble off
{111}{}{Parar de balbuciar}
# What is this building?
{112}{}{O que é este edifício?}
# I'm looking for the Vault.
{113}{}{Estou a procura da Vault.}
# I'm looking for a particular Servant...Joshua, I believe. Is he here?
{114}{}{Estou procurando por um servo em particular...Joshua, acredito que ele está aqui?}
# You looking to buy any slaves...er, servants?
{115}{}{Você está procurando algum escrav...eeh, servo para comprar?}
# Nothing today, thanks.
{116}{}{Hoje nada, obrigado.}
# This? Why, this is the Servant Assignment Center. Were you in need of a servant?
{117}{}{Este? Porque? Este é o Centro de Designação de Servos. Você está precisando de um servo?}
# This is the Servant Assignment Center.
{118}{}{Este é o Centro de Designação de Servos.}
# Servant Assignment Center? What's that?
{119}{}{Centro de Designação de Servos? O que é isso?}
# I'm looking for a particular Servant...Joshua, I believe. Is he here?
{120}{}{Estou procurando por um servo em particular...Joshua, eu creio. Ele está aqui?}
# Servant Allocation, huh? Do you buy slaves...er, servants here?
{121}{}{Alocação de Servos, hã? Vocês compram escrav...eeh, servos aqui?}
# No, just curious. Thanks.
{122}{}{Não, só curiosidade. Obrigado.}
# Just curious. thanks.
{123}{}{Apenas curiosidade. Obrigado.}
# The Vault? It's that huge hole in the mountain on the east side of the city. Head out the front door, turn left and walk straight ahead. You can't miss it.
{124}{}{A Vault? É aquele enorme buraco na montanha na parte leste da cidade. Saindo a porta da frente, vire a esquerda e siga em frente. Não tem como não encontrar.}
# What is this building?
{125}{}{O que é este edifício?}
# Can anyone get in there?
{126}{}{Qualquer um pode entrar lá?}
# I had another question for you.
{127}{}{Tenho outra questão pra você.}
# Thanks for the directions. Goodbye.
{128}{}{Obrigado pelas direções. Tchau.}
# What th-? Are you one of the new Servants?
{129}{}{Que diabos-? Você é um dos novos servos?}
# Yup
{130}{}{Aham}
# Uh-uh me leave now
{131}{}{Uh-uh mim ir agora}
# You must be new around here. I'll explain it...slowly.
{132}{}{Você deve ser novo por aqui. Eu vou explicar isso...bem devagar.}
# Citizens who need help with menial tasks come here to have a Servant assigned to them for the day.
{133}{}{Cidadãos que necessitam de ajuda com trabalhos degradantes vem aqui para ter um servo designado para eles por um dia.}
# That sounds a lot like slavery.
{134}{}{Isto soa muito como escravidão.}
# Oh, so this is where the slaves are stored? Why didn't you say so?
{135}{}{Ah, então é aqui que os escravos são trancados? Porque você não disse isso?}
# Where do you get all these servants?
{136}{}{Onde você consegue todos estes servos?}
# I am looking for a particular Servant...Joshua, I believe. Is he here?
{137}{}{Estou procurando por um servo em particular...Joshua, eu creio. Ele está aqui?}
# Are you looking to buy slaves...er, servants, right now?
{138}{}{Você está procurando algum escrav...eeh, servo para comprar hoje?}
# All right, just curious, thanks. Good day
{139}{}{Tudo bem, apenas curiosidade, obrigado. Bom dia.}
# I'm tired of Servants being sent over with no clearance... *sigh*... let's see, you said you were looking for the Vault?
# That must be your assignment for the day. Very well. I will have someone escort you there.
{140}{}{Estou cansado dos servos serem enviados sem a devida autorização... *suspiro*... Vamos ver, você disse que está procurando pela Vault?
 Deve ser sua designação do dia. Muito bem. Vou providenciar que alguém te acompanhe até lá.}
# Valt! Valt!
{141}{}{Valt! Valt!}
# I'd watch that kind of talk if I were you. It is NOT slavery. We take care of these refugees,
# and they have a good life...better than they would get in the wastes.
{142}{}{Eu tomaria cuidado com esse tipo de assunto se fosse você. Isto NÃO É escravidão. Nós cuidamos destes refugiados,
 e eles tem uma boa vida...melhor do que que teriam no deserto.}
# Where do you get them?
{143}{}{Onde você os consegue?}
# Oh, I had some other questions...
{144}{}{Hum, eu tenho outras questões...}
# That's all I needed to know then, thanks. Good day.
{145}{}{Era tudo que eu precisava saber então, obrigado. Bom dia.}
# No, you need to be a Citizen in order to be allowed into the Vault. Now, look, I happen to be very busy at the moment, so if you would please excuse me...}
{146}{}{Não, você precisa ser um cidadão para ser permitido dentro da Vault. Agora, veja bem, acontece de eu estar muito ocupado no momento, então se você me der licença...}
# Just one more question...
{147}{}{Só mais uma questão...}
# All right. Goodbye.
{148}{}{Tudo bem. Tchau.}
# Our Servants are usually refugees from raider attacks or contractual prisoners who wish to work off their sentence in a productive manner.
{149}{}{Nossos servos são geralmente refugiados dos ataques dos Raiders, ou prisioneiros contratuais que desejam cumprir suas setenças de forma produtiva.}
# Oh, you mean scripters? I knew this guy named Dan once who...
{150}{}{Ah, você quis dizer scripters? Uma vez conheci um cara chamado Dan que...}
# At the cost of their freedom, eh?
{151}{}{A custo da liberdade deles, hã?}
# Do you have a contractual prisoner named Joshua in custody?
{152}{}{Você possui um prisioneiro contratual chamado Joshua sobre sua custódia?}
# Are you looking to buy any slave...er, servants...right now?
{153}{}{Você está procurando algum escrav...eeh, servo para comprar hoje?}
# Hmmm. I had another question...
{154}{}{Hummm. Eu tenho outra questão...}
# I see. Thanks for the information.
{155}{}{Entendo. Obrigado pela informação.}
# No, not scripters, you moron.
{156}{}{Não, não são scripters, seu idiota.}
# Moron? I had to work hard to get the minimum 9 Intelligence and Perception to find this node. Anyway, you were saying?
{157}{}{Idiota? Eu tive que trabalhar duro para ter no mínimo 9 de Inteligência e Percepção para desbloquear essa opção de diálogo. De qualquer forma, o que estava dizendo?}
# You're a fine one to make moral judgments, slaver. Get out of here
{158}{}{Você é bom em fazer julgamentos morais, seu traficante de escravos. Dá o fora daqui.}
# You sound a lot like that idiot Moore...just what Vault City needs. Look, whoever you are, I have work to do, so if you'll kindly remove yourself...
{159}{}{Você soa muito como aquela idiota do Moore...exatamente o que Vault City precisa. Olhe, quem quer que você seja, eu tenho trabalho a fazer, então se você fizesse a gentileza de se retirar...}
# All right, all right...
{160}{}{tudo bem, tudo bem...}
# Why don't you make me leave?
{161}{}{Porque você não me faz sair?}
# Joshua? Yes, we do have a Servant by that name, but you wouldn't want him assigned to you.
# Training him has been...difficult. I'm not certain he can be trained.
{162}{}{Joshua? Sim, nós temos um servo com este nome, mas você não iria querer ele designado para você.
 Treiná-lo tem sido...difícil. Não estou certo que ele possa ser treinado.}
# Joshua? I think we once had a Servant by that name, but not anymore.
{163}{}{Joshua? Eu acho que uma vez tivemos um servo com este nome, mas não temos mais.}
# I need to question him about a matter of Vault City security. Have him sent to the Courtyard
 at once.
{164}{}{Eu preciso perguntar a ele algo que diz respeito a segurança de Vault City. Envie-o para o pátio
 imediatamente.}
# I would like him assigned to me anyway.
{165}{}{Gostaria que ele fosse designado para mim de qualquer forma}
# Difficult?
{166}{}{Dificil?}
# Oh, I don't want him assigned to me. Far from it. I am concerned that he might be infected.
{167}{}{Ah, mas eu não quero ele designado para mim. Longe disso. Estou preocupado que ele possa estar infectado.}
# Hmmm. Another question then...
{168}{}{Hummm. Outra questão então...}
# All right. Goodbye.
{169}{}{Tudo bem. Tchau.}
# I don't think it's a good idea. Wait until he has undergone some more training first, then I'll consider it.
{170}{}{Eu não acho que seja uma boa ideia. Espere até ele passar por mais algum treinamento primeiro, e então eu irei considerá-lo.}
# You said he's been difficult?
{171}{}{Você disse que ele tem sido difícil, certo?}
# Just one more question...
{172}{}{Só mais uma questão...}
# All right. Goodbye.
{173}{}{Tudo bem. Tchau.}
# Yes, Yes, he's more stubborn than almost any Servant we've ever had here. If I didn't know
# better, I'd assume his father was a brahmin.
{174}{}{Sim, ele é mais teimoso do que quase todos os servos que já tivemos por aqui. Se eu não o conhecesse
 melhor, eu diria que o pai dele era um brahmin.}
# You know, that kind of attitude could prove to be a problem. What if the rest of the
 Servants start following his example?
{175}{}{Sabe, este tipo de atitude pode se mostrar um problema. E se o restante dos
 servos começar a seguir o exemplo dele?}
# I could purchase him and take him off your hands. Does the Center take..."donations?"
{176}{}{Eu poderia comprá-lo e te livrar as mãos dele. O Centro aceita..."doações?"}
# Just one more question...
{177}{}{Só mais uma questão...}
# All right. Goodbye.
{178}{}{Tudo bem. Tchau.}
# That's true. I have had to separate him from some of the others...and just yesterday one of the Servants actually had the audacity to question one of my requests.
{179}{}{Tem razão. Eu tive que separá-lo de alguns dos outros...e justo ontem um dos servos realmente teve a audácia de questionar uma das minhas solicitações.}
# You should release him now before it gets worse.
{180}{}{Você deveria soltá-lo agora, antes que isso fiquei pior.}
# Joshua? Yes, we do have a Servant by that name. He was recently transferred from the Corrections Center. Your interest in him is...?
{181}{}{Joshua? Sim, nós temos um servo com este nome. Ele foi recentemente transferido do Centro de Correções. Seu interesse nele é...?}
# I'd like to negotiate for his release.
{182}{}{Eu gostaria de negociar a sua liberação.}
# I suspect he has a contagious disease. You might want to release him before he infects the other Servants.
{183}{}{Eu suspeito que ele tenha uma doença contagiosa. Você talvez queira soltá-lo antes que ele infecte os outros servos.}
# No reason. I did have some other questions...
{184}{}{Nenhuma razão. Eu tenho algumas outras questões...}
# All right. Goodbye.
{185}{}{Tudo bem. Tchau.}
# Oh, really? And what makes you think I would release him?
{186}{}{Ah, sério? E o que faz você pensar que eu vou soltá-lo?}
# A sizeable donation to the Servant Allocation Center operating fund, perhaps?
{187}{}{Uma doação considerável para o fundo de operação do Centro de Alocação de Servos, talvez?}
# I suspect he has a contagious disease. You might want to release him before he infects the other Servants.
{188}{}{Eu suspeito que ele tenha uma doença contagiosa. Você talvez queira soltá-lo antes que ele infecte os outros servos.}
# No reason. I did have some other questions...
{189}{}{Nenhuma razão. Eu tenho algumas outras questões...}
# All right. Goodbye.
{190}{}{Tudo bem. Tchau.}
# No, I was thinking of a more sizeable donation.
{191}{}{Não, eu estava pensando em uma doação ainda mais considerável.}
# Hmmn. Donations are indeed welcome to insure the smooth operation of the Center, but it would require a sizeable donation before I could release Joshua into your care.
{192}{}{Hummn. Doações são de fato bem vindas para assegurar uma operação eficiente do Centro, mas eu pediria uma doação considerável antes que eu pudesse liberar o Joshua aos seus cuidados.}
# How about $1000?
{193}{}{Que tal $1000?}
# How about $750?
{194}{}{Que tal $750?}
# How about $500?
{195}{}{Que tal $500?}
# How about $250?
{196}{}{Que tal $250?}
# I'll think about it. I did have some other questions...
{197}{}{Vou pensar sobre isso. Eu tenho algumas outras questões...}
# I see. I may return later.
{198}{}{Entendo. Talvez eu volte mais tarde.}
# I see. I may return later when I have enough funds for a donation.
{199}{}{Entendo. Talez eu volte mais tarde, quando tiver dinheiro suficiente para uma doação.}
# Well...that's not as much of a donation as I would like, but it will do. I shall see to it that this Joshua you have
# requested is shipped to the Courtyard for processing. Let me make the necessary arrangements.
{200}{}{Bem... Este não é o tanto de doação que eu gostaria, mas isso deve bastar. Eu devo verificar se este Joshua que você
 solicitou foi despachado para o pátio para processamento. Deixe me tomar as providências necessárias.}
# Okay.
{201}{}{Certo.}
# It is done. Joshua is no longer a servant of Vault City, and he has been moved into the Courtyard with the rest
 of the Outworlders.
{202}{}{Pronto. Joshua não é mais um servo de Vault City, e ele foi movido para o pátio para se juntar com o restante
 dos forasteiros.}
# Thanks. I had some other questions...
{203}{}{Obrigado. Eu tenho algumas outras questões...}
# Very well. I will go pick him up there, then
{204}{}{Muito bem. Eu vou pegá-lo lá, então.}
# Sounds good. Hopefully, he won't make his way back into the city.
{205}{}{Parece bom. Tomara que ele não faça o caminho para esta cidade novamente.}
# Is that so? Are you aware that each Servant is thoroughly checked before being admitted into the Allocation Center?
{206}{}{Só isso? Você está ciente de que cada servo é cuidadosamente examinado antes de ser admitido no Centro de Alocações?}
# Maybe I was wrong. Nevertheless, I'd like to negotiate for his release.
{207}{}{Talvez eu esteja errado. Apesar disso, eu gostaria de negociar sua liberação.}
# Are you aware of
{208}{}{Você ficou sabendo da Síndrome de }
# 's Syndrome? It doesn't show up on most medical scans, and its symptoms can lie dormant for weeks.
{209}{}{? Ela não se mostra na maioria dos exames médicos, e seus sintomas podem não se manifestar por semanas.}
# In the wastes, there is a disease called
{210}{}{No deserto, existe uma doença chamada Síndrome de }
#'s Syndrome. Perhaps you've noticed the lowered energy level of your Servants recently? Their general surliness?
{211}{}{. Talvez você tenha notado um baixo nível de energiados seus servos recentemente? Suas más disposições gerais?}
# That is utter nonsense. Now if you are quite done with wasting my time with your lies...
{212}{}{Isso é um completo absurdo. Agora se você já terminou de me fazer perder meu tempo com suas mentiras...}
# All right, forget "
{213}{}{Tudo bem, esqueça a Síndrome de }
'# s Syndrome." I'd still like to negotiate for Joshua's release.
{214}{}{. Eu ainda gostaria de negociar a liberação de Joshua.}
# Never mind, then. I had some other questions...
{215}{}{Esqueça, então. Eu tenho algumas outras questões...}
# I'm leaving, then. Goodbye.
{216}{}{Estou indo, então. Tchau.}
# Infected? Infected with what?
{217}{}{Infectado? Infectedo com o que?}
# Symptoms? What kind of symptoms
{218}{}{Sintomas? Que tipos de sintomas?}
# Perhaps you've noticed the lowered energy level of your Servants recently? Short attention span? Their inability to hear orders and follow them correctly? Those are only the early stages.
{219}{}{Talvez você tenha notado um baixo nível de energiados seus servos recentemente? Déficit de atenção? Suas incapacidades de escutar ordens e segui-lás corretamente? Isto é apenas no estágios iniciais.}
# Uh...
{220}{}{Hum...}
# 's Syndrome. A lot of Outworlders have it. Its symptoms include, uh, speaking when not being spoken to. And using
# coarse language.
{221}{}{. Muitos forasteiros tem. Seus sintomas incluem, ahm, falar mesmo quando não ninguém mais está falando. E usar
 linguagem vulgar.}
# Hmmmm. It wouldn't do if Citizens began to report problems with the Servants...very well, I shall release Joshua at
 once. If you would give me a moment to make the arrangements...
{222}{}{Hummmm. Não seria agradável se os cidadãos começassem a reportar problemas com os servos...tudo bem, eu devo liberar o Joshua
 imediatamente. Se você me der uns minutos para que eu tome as providências...}
# Yes...I have noticed those symptoms in the Servants of late. Contagious, you say? Hmmm. Well, if this Joshua is a
 carrier, I shall release him at once. Give me a moment to make the arrangements...
{223}{}{Sim...Eu tenho notado estes sintomas em servos últimamente. Contagioso, você falou? Hummm. Bem, Se Joshua é um
 portador, eu devo liberá-lo imediatamente. Me dê um momento para tomar as providências...}
# No problem. Joshua would be better off with the Outworlders anyway.
{224}{}{Sem problemas. Será melhor Joshua ficar com os forasteiros, de qualquer forma.}
# Of course, Captain. I will take care of it right now.
{225}{}{Claro, Capitão. Eu vou cuidado disso imediatamente.}
# Excellent. Thank you, Citizen.
{226}{}{Excelente. Obrigado, Cidadão.}
# Perhaps. Do you have some you wish to sell?
{227}{}{Talvez. Você teria algum que gostaria de vender?}
# Yes, I have one right here with me. Take a look and make me an offer.
{228}{}{Sim, eu tenho um bem aqui comigo. Dê uma olhada e me faça uma oferta.}
# Yes, I have a few right here with me. Take a look and make me an offer.
{229}{}{Sim, eu tenho alguns bem aqui comigo. Dê uma olhada e me faça uma oferta.}
# No, actually. I had some questions for you...
{230}{}{Na verdade não. Eu tenho algumas questões pra você...}
# No, not today, actually. Goodbye.
{231}{}{Não, hoje não, na verdade. Tchau.}
# Hmmm. That woman there, Miria, is it? She has strong arms...and nice hips. I will buy her from you for $250.
{232}{}{Hummm. Aquela mulher ali, Miria, não é? Ela tem braços fortes...e belos quadris. Eu compro ela de você por $250.}
# Hmmm. that boy there, Davin, is it? He looks relatively free from Outworlder contamination. I will buy him from you for $200.
{233}{}{Hummm. Aquele menino ali, Davin, não é? Ele parece relativamente livre da contaminação que outros forasteiros tem. Eu compro ele de você por $200.}
# Hmmm. That tribal you have. He smells...strongly. But he looks healthy. I'll take him for $100.
{234}{}{Hummm. Esse tribal que você tem. Ele tem um cheiro...forte. Mas parece saudável. Eu fico com ele por $100.}
# Hmmm. That man there...Vic, is it? Even though he's old, he looks like a handyman. $100.
{235}{}{Hmmm. Aquele homem ali...Vic, não é? Mesmo achando ele velho, ele parece um "faz-tudo". $100.}
# Perhaps you should return when you have a servant of value to show me. Your current stock...
 is unimpressive.
{236}{}{Talvez você deveria retornar quanto possuir um servo de valor para me mostrar. Seu estoque atual...
 não é impressionante.}
# C'mon, the slave's worth more than that.
{237}{}{Vamos lá, os escravos valem mais do que isso.}
# That is a fair price. The servant's all yours
{238}{}{É um preço justo. O servo é todo seu.}
# Actually, I'm not looking to sell that one just yet. I did have some questions I wanted to ask you...
{239}{}{Na verdade, não estou procurando vender aquele ali ainda. Eu tenho algumas questões que gostaria de te perguntar...}
# Actually, I'm not looking to sell that slave. Let's deal another time.
{240}{}{Na verdade, não estou procurando vender aquele escravo. Vamos negociar em outra oportunidade.}
# Very well. I had some questions for you, though...
{241}{}{Ótimo. Entretanto, eu tenho algumas questões pra você...}
# All right. Some other time when I get better stock, then.
{242}{}{Tudo bem. Alguma outra oportunidade, quando eu tiver um estoque melhor então.}
# No, I don't think so...250 or nothing.
{243}{}{Não, acho que não...250 ou nada.}
# No, the boy looks like he would be difficult to train...200 or nothing.
{244}{}{Não, o menino parece que seria difícil de se treinar...200 ou nada.}
# Look. It'll take a week to wash the smell off that tribal. 100 or nothing.
{245}{}{Veja bem. Eu vou levar uma semana lavando este tribal para tirar o cheiro dele. 100 ou nada.}
# You can't even promise me that he won't have a heart attack once he leaves your care. He's old. 100 or nothing.
{246}{}{Você não tem nem como me prometer que ele não vai ter um ataque cardíaco assim que você deixar ele aqui. Ele é velho. 100 ou nada.}
# All right, that's fair. The servant's all yours.
{247}{}{Tudo bem, é justo. O servo é todo seu.}
# Forget it, then. I did have some questions I wanted to ask you...
{248}{}{Esqueça isso, então. Eu tenho algumas questões que gostaria de te perguntar...}
# Nothing it is, then. I can't afford to let my servant go for that price. Maybe some other time.
{249}{}{Então é nada. Eu não posso me dar ao luxo de deixar meu servo ir por esse preço. Talvez em alguma outra oportunidade.}
# Hmmmm...She does look like a healthy specimen...maybe I could put her to work around here. $500. And that's my final offer.
{250}{}{Hummmm...Ela parece uma espécime saudável...talvez eu possa colocar ela para trabalhar por aqui. $500. E é minha oferta final.}
# Hmmmm. He is a healthy specimen. $400 for him, then.
{251}{}{Hmmmm. Ele é um espécime saudável. $400 por ele, então.}
# Hmmmm. All right. $200, then. And no more haggling.
{252}{}{Hummmm. Tudo bem. $200, então. E sem mais barganhas.}
# Hmmmmmmm. $200. And not a dollar more.
{253}{}{Hummmmmmm. $200. E nenhum dolar a mais.}
# That's fair. The servant's all yours.
{254}{}{É justo. O servo é todo seu.}
# Actually, I'm not looking to sell that one just yet. I did have some questions I wanted to ask you...
{255}{}{Na verdade, não estou procurando vender aquele ali ainda. Eu tenho algumas questões que gostaria de te perguntar...}
# Actually, I'm not looking to sell that slave. Let's deal another time.
{256}{}{Na verdade, não estou procurando vender aquele escravo. Vamos negociar em outra oportunidade.}
# Excellent. Here is your money. I will have her shipped off for medical tests and processing.
{257}{}{Excelente. Aqui está seu dinheiro. Eu vou despacha-la para os testes médicos e processamento. }
# Excellent. Here is your money. I will have him shipped off for medical tests and processing. 
{258}{}{Excelente. Aqui está seu dinheiro. Eu vou despacha-lo para os testes médicos e processamentos. }
# Excellent. Here is your money. I will have the tribal shipped off for medical tests and processing. 
{259}{}{Excelente. Aqui está seu dinheiro. Eu vou despachar o tribal para os testes médicos e processamento. }
# Excellent. Here is your money. I will have the old man shipped off for medical tests and processing. 
{260}{}{Excelente. Aqui está seu dinheiro. Eu vou despachar o velho para os testes médicos e processamento. }
# Give me a moment to take care of the arrangements...
{261}{}{Me de uns minutos para tomar as providências...}
# Sure. I'll just wait here.
{262}{}{Claro. Eu estarei esperando bem aqui}
# Very well. Your Servant has been relocated for medical testing and re-conditioning.
# Curious...the Servant seemed quite surprised by the whole affair. It took a few tranquilizer
# darts to smooth things over. I put everything the Servant was carrying in the box in my office.
{263}{}{Tudo certo. O seu servo foi realocado para os testes médicos e recondicionamento.
 Estranho...o servo parecida bastante supreso com todo o acontecido. Nos custou alguns dardos
 tranquilizantes para acalmar a situação. Eu coloquei tudo que o servo estava carregando em uma caixa no meu escritório.}
# Well, Servants will be Servants. I had some other questions I wanted to ask you...
{264}{}{Bem, servos sempre serão servos. Eu tenho algumas outras questões que eu gostaria de te perguntar...}
# Really? Well, I 'm sure they'll be more docile as time goes on. Are you interested in any other companions?
{265}{}{Sério? Bem, eu tenho certeza que ele ficará mais dócil com o tempo. Você está interessado em alguma outro companheiro?}
# Yeah, they can be a little difficult at first; they'll get accustomed to it. Good day.
{266}{}{Sim, eles podem ser um pouco difícil no começo; eles vão se acostumar com isso. Bom dia.}
# What are you doing back here? I sent you to the Vault! Of all the... very well, I will have someone escort you back there.
{267}{}{O que você está fazendo aqui de volta? Eu enviei você para a Vault! Pelo amor de... tudo bem, vou providenciar que alguém te acompanhe de volta até lá.}
# Oh-keeeee
{268}{}{Tá-booooom}
# You convinced Barkus to release Joshua.
{269}{}{Você convenceu Barkus a liberar o Joshua.}
#added by killap
# I heard you're quite the hero. Good job.
{300}{}{Eu ouvi dizer que você é bastante herói. Bom trabalho.}
