#You see a dusty-looking traveler.
{100}{}{Você vê um viajante empoeirado para o futuro.}
#You see a bar patron.
{101}{}{Você vê um consumidor de bar.}
#You see a dusty-looking traveler.
{102}{}{Você vê um viajante empoeirado para o futuro.}
#Hey! Everybody! It's the one who kicked the Enclave's ass!
{103}{}{Ei Todo mundo! É a única que chutou a bunda do Enclave!}
#Congratulations, hero!
{104}{}{Parabéns, herói!}
#Hey, hero! Lemme buy you a drink, all right?
{105}{}{Ei, herói! Deixa eu comprar uma bebida, certo?}
#Looks like the Captain's slumming...
{106}{}{Parece que é um capitão slumming...}
#Well, if it ain't the First Citizen's favorite toadie...
{107}{}{Bem, se não é toadie favorito do Primeiro Cidadão ...}
#Well, if it ain't th' "Captain..."
{108}{}{Bem, se não é th '"Capitão ..."}
#Everybody watch out. The law just walked in.
{109}{}{Todo mundo esteja atento. A lei acabou de entrar.}
#You slumming, Citizen?
{110}{}{Você slumming, Cidadão?}
#Don't you belong inside the city, "Citizen?"
{111}{}{Você não pertencem dentro da cidade, "Cidadão?"}
#Damn Citizens just stroll on in whenever they feel like it...
{112}{}{Porra Cidadãos apenas passear em no sempre que sentem como ele ...}
#Whoa... that a mutant?!
{113}{}{Uau ... que um mutante ?!}
#Clear out, boys. There's a mutant in the house.
{114}{}{Limpe, rapazes. Há um mutante na casa.}
#There's gonna be trouble if them guards see that mutant...
{115}{}{Vai haver problemas se esses guardas ver os mutante ...}
#They're letting *mutants* in here now?
{116}{}{Eles estão dentro * * mutantes aqui agora?}
#That mutant's gonna find himself in the Detention Center...
{117}{}{Isso vai do mutante encontrar-se no Centro de Detenção ...}
#Tell me that's not a ghoul.
{118}{}{Diga-me que não é um Ghoul.}
#What's that *stink?!* Get that ghoul outta here!
{119}{}{* O que é que fede?! * Tire esse Ghoul outta aqui!}
#Get that filthy ghoul outta the bar!
{120}{}{Tire esse Ghoul imundo outta o bar!}
#If that ghoul sheds any body parts in here, I'll gut him.
{121}{}{Se isso Ghoul lança quaisquer partes do corpo em aqui, eu vou estripar ele.}
#That ghoul's gonna be target practice if the guards see him. 
{122}{}{Isso vai ghoul ser alvo prática se os guardas vê-lo.}
#Can barely afford a Day Pass nowadays..
{123}{}{Mal consegue pagar a passagem do dia hoje em dia ..}
#Brahmin prices keep going up...
{124}{}{Preços brahmin continuar subindo ...}
#Gonna be a bad season if the drought continues...
{125}{}{Vai ser uma temporada ruim se a seca continua ...}
#Slumming, Captain?
{126}{}{Slumming, Capitão?}
#Look, I ain't done nothing, Captain. I'm just minding my own business.
{127}{}{Olha, eu não fiz nada, capitão. Eu só estou cuidando da minha vida.}
#I don't know nothing, Captain. Now leave me alone.
{128}{}{Eu não sei nada, capitão. Agora me deixe em paz.}
#Take a hike, "Captain."
{129}{}{Dê uma caminhada, o "capitão".}
#Looks like Lynette'll make anyone a Citizen nowadays.
{130}{}{Parece que Lynette'll fazer qualquer cidadão hoje em dia.}
#I already paid the guards their protection money. Now leave me alone.
{131}{}{Eu já paguei os guardas o seu dinheiro de protecção. Agora me deixe em paz.}
#Slumming, Citizen?
{132}{}{Slumming, Cidadão?}
#Maybe you better get inside the walls, Citizen.
{133}{}{Talvez seja melhor você ficar dentro das muralhas, Cidadão.}
#Beat it, Citizen.
{134}{}{Bata-o, Cidadão.}
#Take a hike, Citizen.
{135}{}{Dê uma caminhada, Cidadão.}
#Looks like Lynette'll make anyone a Citizen nowadays.
{136}{}{Parece que Lynette'll faz qualquer cidadão hoje em dia.}
#That Smith's a nice fella.
{137}{}{Esse Smith é um cara legal.}
#I don't think I'll ever be able to get a Day Pass.
{138}{}{Eu não acho que eu nunca vou ser capaz de obter uma passagem do dia.}
#Don't drink the water around here. It makes geiger counters tick.
{139}{}{Não beba a água ao redor aqui. Faz contadores Geiger carrapato.}
#Whenever those Citizens walk by, they don't make eye contact or say hello.
{140}{}{Sempre que esses Cidadãos a pé, eles não fazem contato com os olhos ou dizer Olá.}
#Vault City may not love us, but at least they protect us.
{141}{}{Vault City pode não nos amam, mas pelo menos eles nos proteger.}
#Watch out for that Autodoc. It cures you...most of the time. Just don't press your luck.
{142}{}{Atente para que AutoDoc. Ele cura você ... na maioria das vezes. Só não pressione sua sorte.}
#Ed, the brahmin dealer, had to raise his prices again to meet the monthly guard payment.
{143}{}{Ed, o negociante brahmin, tiveram de aumentar seus preços novamente para atender o pagamento mensal de guarda.}
#That Skeev let me slip some hootch into town for a percentage.
{144}{}{Esse Skeev me deixe escapar algumas bebida alcoólica até a cidade para uma porcentagem. }
#Been on the road for the past week. Came from NCR, way down south.
{145}{}{Já esteve na estrada durante a semana passada. Veio da NCR, caminho para baixo sul.}
#Some friends of mine went to Reno...ain't seen 'em since.
{146}{}{Alguns amigos meus foram para Reno ... não é visto ' desde que.}
#I hear Reno's getting tense again. Them families hate each other.
{147}{}{Ouvi dizer Reno está ficando tenso novamente. Aquelas famílias se odeiam.}
#I hear those ghouls up at Gecko are planning to attack the city.
{148}{}{Ouvi dizer esses fantasmas acima em Gecko estão planejando atacar a cidade.}
#Don't cross any of the Citizens or they'll slap you in the Detention Center.
{149}{}{Não cruze qualquer um dos Cidadãos ou eles vão te dar um tapa no Centro de Detenção.}
#That Lynette is a cold one.
{150}{}{Lynette Isso é uma fria.}
#Vault City ain't exactly a "free" city. It ain't bad, though.
{151}{}{Vault City não é exatamente uma cidade "livre". Não é ruim, embora.}
#Vault City's better than the Den. Ain't as much fun, though.
{152}{}{É melhor do que o Den Vault City. Não é tão divertido, porém.}