#You see Charlie.
{100}{}{Você vê Charlie.}
#You see a gaunt man. His hair is plastered to his head in ragged clumps, and his skin is hanging loosely on his body.
{101}{}{Você vê um homem esquelético. Seu cabelo está colado na sua cabeça em tufos esfarrapados, e sua pele está pendurada no seu corpo.}
#You see Charlie.
{102}{}{Você vê Charlie.}
#You see a gaunt man. His hair is plastered to his head in ragged clumps, and his skin is hanging loosely on his body.
{103}{}{Você vê um homem esquelético. Seu cabelo está colado na sua cabeça em tufos esfarrapados, e sua pele está pendurada no seu corpo.}
#You see a gaunt man... it looks like he has symptoms of radiation poisoning.
{104}{}{Você vê um homem esquelético... parece que ele tem sintomas de envenenamento por radiação.}
#You see Charlie.
{105}{}{Você vê Charlie.}
#You see a gaunt man... it looks like he has symptoms of radiation poisoning.
{106}{}{Você vê um homem esquelético... parece que ele tem sintomas de envenenamento por radiação.}
#You see Charlie... he looks like he has put on weight, and is breathing normally.
{107}{}{Você vê Charlie... ele parece que ganhou peso, e está respirando normalmente.}
#You see Charlie.
{108}{}{Você vê Charlie.}
#You see Charlie...he looks like he has put on weight, and is breathing normally.
{109}{}{Você vê Charlie... ele parece que ganhou peso, e está respirando normalmente.}
#This man has radiation poisoning. Your skills can't help him. He needs medication.
{110}{}{Este homem tem envenenamento por radiação. Suas habilidades não podem ajudá-lo. Ele precisa de medicação.}
#This man looks terribly sick. You're not sure what's wrong.
{111}{}{Este homem parece estar terrivelmente doente. Voce não tem certeza do que está errado.}
#Thanks, but I'm fine, really. That Rad-Away stuff did the trick.
{112}{}{Obrigado, mas estou realmente bem. Aquele Rad-Away fez o truque.}
#You find a vein and inject the Rad-Away into Charlie's system.
{113}{}{Você encontra uma veia e injeta o Rad-Away no sistema de Charlie.}
#*Urhkkkk*...
{114}{}{*Urhkkkk*...}
#3 Seconds
{115}{}{3 Segundos}
#Unhhhhh...*cough* *cough*...
{116}{}{Unhhhhh...*cough* *cough*...}
#3 Seconds
{117}{}{3 Segundos}
#Hrnnhhhh...eh...ahhhhh
{118}{}{Hrnnhhhh...eh...ahhhhh}
#3 Seconds
{119}{}{3 Segundos}
#What happened? I feel tons better.
{120}{}{O que aconteceu? Eu me sinto mil vezes melhor.}
#You have cured Charlie.
{121}{}{Você curou Charlie.}
#*Errhhhhhh*
{122}{}{*Errhhhhhh*}
#*Wheeze*
{123}{}{*Wheeze*}
#*Cough-Cough*
{124}{}{*Cough-Cough*}
#*Urhkkkk*
{125}{}{*Urhkkkk*}
#Last time I drink the damned water in this town, that's fer sure.
{126}{}{A última vez que eu bebo esta maldita água nesta cidade, isso é certo.}
#Surprised I still ain't glowing...
{127}{}{Surpreso que ainda não estou brilhando...}
#Damn Rad-Away gives me the runs...
{128}{}{Droga Rad-Away me dá caganeira...}
#Thanks, stranger. I appreciate your help... I couldn't afford the Autodoc.
{129}{}{Obrigado, estranho. Eu aprecio sua ajuda... Eu não podia pagar o Autodoc.}
#Wish I could reward you, but I ain't even got two caps to rub together.
{130}{}{Eu gostaria de poder recompesar você, mas eu não tenho se quer duas moedas para esfregar juntas.}
#Last time I drink the damned water in this town, that's fer sure.
{131}{}{A última vez que eu bebo esta maldita água nesta cidade, isso é certo.}
#Surprised I still ain't glowing...
{132}{}{Surpreso que ainda não estou brilhando...}
#Damn Rad-Away gives me the runs...
{133}{}{Droga Rad-Away me dá caganeira...}