#You see the Illicit Allocations Chief, Chet.
{100}{}{Você vê o Chefe das Locações Ilegais, Chet.}
#You see a shifty-looking man wearing a Vault 13 jumpsuit.
{101}{}{Você vê um homem de aparência desonesta vestindo um macacão do Vault 13.}
#You see the Illicit Allocations Chief, Chet.
{102}{}{Você vê o Chefe das Locações Ilegais, Chet.}
#You see a shifty-looking man wearing a Vault 13 jumpsuit.
{103}{}{Você vê um homem de aparência desonesta vestindo um macacão do Vault 13.}
#Hey, there. I'm the Illicit Allocations Chief... but you can call me Chet. You need something?
{104}{}{Olá. Eu sou o Chefe das Locações Ilegais... mas pode me chamar Chet. Você precisa de algo?}
#Need anything else?
{105}{}{Precisa de algo mais?}
#Set the endgame flag, Chet. I'm all done.
{106}{}{Defina o sinalizador de fim de jogo, Chet. Eu estou totalmente pronto.}
#Make me Captain of the Guard. Now
{107}{}{Me faça o capitão da Guarda. Agora.}
#Make me a real citizen, if you please.
{108}{}{Faça-me um cidadão de verdade, se você quiser.}
#Make me a fake citizen and give me the papers.
{109}{}{Faça-me um falso cidadão e me dê os papéis.}
#Make me a kicked out citizen.
{110}{}{Faça-me um cidadão expulso.}
#Change my reputation.
{111}{}{Mude minha reputação.}
#(Doesn't work) I need a character in my party.
{112}{}{(Não funciona) Eu preciso de um personagem no meu grupo.}
#Nope, nothing.
{113}{}{Não, nada.}
#To what?
{114}{}{Para quê?}
#Make me a slaver.
{115}{}{Faça-me um traficante de escravos.}
#Make me a childkiller.
{116}{}{Faça-me um assassino de crianças.}
#Nothing...just lower my karma by a 100.
{117}{}{Nada...apenas reduzir meu carma em 100.}
#Nevermind. I wanted something else...
{118}{}{Esqueçe. Eu queria outra coisa...}
#Nope, nothing.
{119}{}{Não, nada.}
#Who?
{120}{}{Quem?}
#Marcus.
{121}{}{Marcus.}
#Lenny.
{122}{}{Lenny.}
#Vic.
{123}{}{Vic.}
#Myron.
{124}{}{Myron.}
#Nobody. I have more needs.
{125}{}{Ninguém. Eu tenho mais necessidades.}
#Nevermind. Bye.
{126}{}{Esqueçe. tchau.}