#You see Curtis.
{100}{}{Você vê Curtis.}
#You see a small brown-haired boy. He looks like he has been crying.
{101}{}{Você vê um garotinho de cabelo castanho. Parece que ele estava chorando.}
#You see Curtis.
{102}{}{Você vê Curtis.}
#You see a small brown-haired boy. He looks like he has been crying.
{103}{}{Você vê um garotinho de cabelo castanho. Parece que ele estava chorando..}
#You see a small brown-haired boy. He looks much happier than before.
{104}{}{Você vê um garotinho de cabelo castanho. Ele parace muito mais feliz do que antes.}
#You see Curtis.
{105}{}{Você vê Curtis.}
#You see a small brown-haired boy. He looks much happier than before.
{106}{}{Você vê um garotinho de cabelo castanho. Ele parace muito mais feliz do que antes.}
#*Snfffff*
{107}{}{*Snfffff*}
#Would you like some tea, Mr. Nixon?
{108}{}{Gostaria de um chá, Sr. Nixon?}
#"Why yes I would, Curtis."
{109}{}{"Porquê sim eu gostaria, Curtis."}
#Here you go. Drink up!
{110}{}{Aqui está. Beba!}
#"Thank you, Curtis."
{111}{}{"Obrigado, Curtis."}
#Thank YOU, Mr. Nixon.
{112}{}{Obrigado VOCÊ, Sr. Nixon.}
#"Do you want to go dig up Daddy's wrench?"
{113}{}{"Você quer ir desenterrar a chave do Papai?"}
#No, Mr. Nixon. Daddy will be mad we buried it.
{114}{}{Não, Sr. Nixon. Papai vai ficar bravo se desenterrarmos.}
#"But it's buried under those rocks just behind the bar. We could get it right now."
{115}{}{"Mas está enterrado embaixo daquelas pedras atrás do bar. Nós poderíamos pegá-las agora"}
#No, Daddy'll be mad. It's best to lie, just like you told me, Mr. Nixon.
{116}{}{Não, Papai ficará bravo. É melhor mentir, como você me disse, Sr. Nixon.}
#I lost my friend while playing in the Courtyard. His name is Mr. Nixon.
{117}{}{Eu perdi meu amigo enquanto jogávamos no pátio. Seu nome era Sr. Nixon.}
#Mr. Nixon has a blue shirt and a big nose. He's really, really short.
{118}{}{Sr. Nixon tem um camisa azul e um nariz grande. Ele é muito, muito pequeno.}
#Have you seen Mr. Nixon? I lost him.
{119}{}{Você viu o Sr. Nixon? Eu o perdi.}
#Thanks for finding Mr. Nixon. He says thanks, too.
{120}{}{Obrigado por encontra o Sr. Nixon. Ele diz obrigado, também.}
#Yer mutant is scary.
{121}{}{Aquele mutante é assustador.}
#Yer ghoul is scary.
{122}{}{Aquele ghoul é assustador.}
#Yer metal doggie looks like he wants to eat me.
{123}{}{Aquele cachorrinho de metal parece querer me comer.}
#I lost Mr. Nixon. I don't know where I left him.
{124}{}{Eu perdi o Mr. Nixon. Eu não sei aonde eu o deixei.}
#Thizzz Nixxson?
{125}{}{Estiii Nixxson?}
#Shamble off
{126}{}{Cair fora}
#This him? He was looking around for you, too.
{127}{}{Este é ele? Ele também estava olhando para você.}
#I have Mr. Nixon right here. But you know what? I think Mr. Nixon should be punished for going off on his own. Some ritual dismemberment may be in order. So, first I'm going to pull off his arms, then...
{128}{}{Eu tenho o Sr. Nixon bem aqui. Mas sabe de uma coisa? Acho que o Sr. Nixon deveria ser punido por sair por conta própria. Algum ritual de desmembramento pode servir. Então, primeiro vou arrancar seus braços, então...}
#Neither do I.
{129}{}{Nem eu.}
#You found him! You found Mr. Nixon!
{130}{}{Você encontrou ele! Você encontrou o Mr. Nixon!}
#Byeee Mistuh Nixxson
{131}{}{Tchauuu Senhooor Nixxson}
#Sure I did. He didn't go far. Now keep an eye on him from now on, okay?
{132}{}{Claro que sim. Ele não foi longe. Agora mantenha os olhos nele, tudo bem?}
#NO! NOOOOO! Don't! Stop it! Sto--
{133}{}{Não! Nãoooo! Não faça isso! Pare! Pa--}
#Ooops. Looks like Nixon was a little more fragile than I thought. Too bad, kid.
{134}{}{Ooopa. Parece que o Nixon era um pouco mais frágil do que pensei. Foi mal garoto.}
#Mr. Nixon will come back from the grave and KILL you.
{135}{}{Mr. Nixon retornará da cova e matará você.}
#Mr. Nixon will haunt you for the rest of your days. I mean it.
{136}{}{Mr. Nixon irá assombrá-lo pelo resto dos seus dias. Eu sei.}
#When I grow up, you'll be old, and I'll do to you what you did to Mr. Nixon.
{137}{}{Quando Eu crescer você será velho, e Eu vou fazer com você o que você fez ao Mr. Nixon.}
#You returned Mr. Nixon to Curtis.
{138}{}{Você devolveu Mr. Nixon para Curtis.}
#You taught Curtis that life is cruel and unfair.
{139}{}{Você ensinou a Curtis que a vida é cruel e injusta.}