#You see an Auto-Doc.
{100}{}{Você vê um Auto-Doc.}
#You see an ancient-looking Auto-Doc. Despite its age, you have managed to coax it back into working order.
{101}{}{Você vê um Auto-Doc aparentemente antigo. Apesar de sua idade, você conseguiu convencê-lo voltar a funcionar.}
#You see an Auto-Doc.
{102}{}{Você vê um Auto-Doc.}
#You see an ancient-looking Auto-Doc. Despite its age, you have managed to coax it back into working order.
{103}{}{Você vê um Auto-Doc aparentemente antigo. Apesar de sua idade, você conseguiu convencê-lo voltar a funcionar.}
#You see an ancient-looking Auto-Doc. It is clicking and whirring unhealthily, and a great deal of heat is emanating from it.
{104}{}{Você vê um Auto-Doc aparentemente antigo. Está fazendo barulho de quebrado, e uma grande quantidade de vapor está saindo dele.}
#You see an Auto-Doc.
{105}{}{Você vê um Auto-Doc.}
#You see an ancient-looking Auto-Doc. It is clicking and whirring unhealthily, and a great deal of heat is emanating from it.
{106}{}{Você vê um Auto-Doc aparentemente antigo. Está fazendo barulho de quebrado, e uma grande quantidade de vapor está saindo dele.}
#This ancient Auto-Doc looks badly in need of repair. It looks several decades past its scheduled maintenance.
{107}{}{Esse Auto-Doc antigo parece estar precisando urgente de reparos. Parece que se passaram várias décadas desde a última manutenção.}
#The damage wasn't as bad as it seemed. Some interior cables needed to be replaced and the diagnostic board cleaned. No problem.
{108}{}{O problema não é tão ruim quanto parece. Alguns cabos interiores precisam ser trocados e a placa de diagnóstico precisa ser limpa. Sem problemas.}
#You examine the Auto-Doc, but you can't seem to figure out the problem.
{109}{}{Você examina o Auto-Doc, mas não consegue descobrir qual é o problema.}
#You have already fixed the Auto-Doc. It is running smoothly. You think.
{110}{}{Você já consertou o Auto-Doc. Está funcionando perfeitamente. Você acha.}
