#You see a young woman.
{100}{}{Você vê uma jovem mulher.}
#You see Ann, Connar's wife.
{101}{}{Você vê Ann, esposa de Connar.}
#She appears to be busily cooking
{102}{}{Ela parece ocupada cozinhando.}

#Why hello there, I'm Connar's wife, Ann. You must be the one who helped us out. I can't tell you how much
 we appreciate all you've done. It's hard to believe that we can finally live in peace without fear of Vault City's goons
 coming to take us from our homes.
{200}{}{Ola, eu sou Ann, esposa do Connar. Você deve ser a pessoa que anda ajudando os outros por ai. Eu posso te contar o quando aprecio tudo
o que você tem feito. É difícil acreditar que nós finalmente vivemos em paz sem ter que temer os capangas de Vault City
vindo para nos tirar de casa.}
#Glad to be of assistance. You seem to be quite busy here. Need some help with anything?
{201}{}{Fico feliz por ser útil. Você parece bem ocupado aqui. Precisa de ajuda com alguma coisa?}
#No problem. See you around
{202}{}{Sem problemas, vejo você por ai.}

#Actually, I *could* use some help. Now that we're becoming more organized, we're starting to see our numbers
 grow. The problem is, I'm not sure we'll have enough food to go around. My husband has attempted to get the caravans
 to stop here, but they don't' think we're worth their time. I don't suppose you could get them to reconsider?
{300}{}{Na verdade, eu poderia usar alguma ajuda. Agora que nos estamos mais organizados, e começamos a ver nosso numero crescer.
 O problema é que eu não tenho certesa se temos comida para todo mundo em volta. Meu marido está tentando trazer as caravanas para cá,
 entretanto eles não acham lucrativo perder tempo por aqui. Eu não sei se você poderia convencelos a nos reconsiderar?}
#Sorry lady, but I think I've done enough here. I need to move on now. Bye.
{301}{}{Desculpe madame, eu já fiz demais por aqui. Eu preciso ir embora agora, adeus.}
#Can't you people ever deal with your own fucking problems? Bye.
{302}{}{Seu povo não pode resolver a merda dos seus problemas? Tchau.}
#Sure. I'll see what I can do. Who do I talk to about this?
{303}{}{Claro, eu vou ver o que posso fazer. Falo com quem sobre isso?}

#One of the caravan masters, Mr. Baron, will be passing by here shortly. The caravan trail isn't far from this
 village. If you could go out there and meet with him, we'd all appreciate it greatly.
{310}{}{Com um dos mestres da caravana, Sr. Baron, vai passar por aqui em breve. A caravana não esta longe da vila. Você podeia se encontrar com ele,
nós apreciariamos muito.}
#Alright, I'll give it a shot. Show me where he is.
{311}{}{Está bem, eu vou tentar. Me mostre onde ele está.}
#Alright, but I'm not ready yet. I'll let you know when I am.
{312}{}{Está bem, porem eu não estou pronto ainda. Vou lhe avisar quando eu puder fazer isso.}
#On second thought, you're going to have to handle this on your own. Sorry.
{313}{}{Espera um pouco, você tem que resolver isso com suas próprias mãos. Desculpe.}

#Are you ready to go meet the caravan master yet?
{320}{}{Você está pronto para se reunir com o mestre da caravana?}
#Not yet. Bye.
{321}{}{Não ainda, tchau.}
#Alright. I'm ready.
{322}{}{Ok, estou pronto.}

#Oh, it's you! Thank you for speaking with Mr. Baron. He had just come by to make trade arrangements with my husband.
 You've done so much to help us, we're forever in your debt!
{330}{}{Ó, ai está você. Muito obrigado por conversar com o Sr. Baron. Ele já veio conversar com meu marido e acertar os arranjos das trocas.
Você fez tanto para nos ajudar, nós seremos eternamento gratos e sempre estaremos em débito com você!}
#It's the least I could do. Take care
{331}{}{É o mínimo que eu poderia ter feito. Cuide-se.}
#You think I do all this for free? Let's talk money.
{332}{}{Você acha que fiz tudo isso de graça? Vamos falar de dinheiro.}

#[Ann looks a bit flustered.] Well, yes...alright fine. I had a little something stored away for an emergency, but
 I suppose you can have it. And to think I saw you as a good person.
{340}{}{[Ann fica um pouco frustada.] Bem, sim...está certo. Eu tenho alguma coisa guardada para emergências, porem eu acho que merece ter.
E eu penso que você é uma boa pessoa.}
#Looks are in the eyes of the beholder, lady. Good day.
{341}{}{Bondade está nos olhos de quem vê, moça. Bom dia.}
#Sorry, money makes the world go round. Bye.
{342}{}{Desculpe, dinheiro faz o mundo girar. Adeus.}
#Oh, it's you! I heard what you did to Mr. Baron. I never did care for him, but you didn't have to kill him. We'll
 stifle as a community without proper trade.
{350}{}{Ai está você! Eu ouvi o que você fez com o Sr. Baron. Eu nunca me importei com ele, porem você não deveria ter matado ele.
Nós iremos sufocar sem um comercio decente.}
#Sorry, mistakes happen. Bye.
{351}{}{Foi mal, erros acontecem. Até.}
#Not my problem. Bye.
{352}{}{Não é problema meu. Adeus.}
#You don't need to worry about any damn merchants. Because I plan on killing the whole lot of you.
{353}{}{Você não precisa mais se preocupar com comerciantes mediocres. Pois eu pretendo matar toda a corja deles para você.}

#Did Vault City send you?
{400}{}{Foi Vault City que lhe enviou?}
#We have the right to live here, you know.
{401}{}{Nós temos o direito de vivermos aqui, você sabe.}
#I have nothing more to say to you.
{402}{}{Eu não tenho mais nada pra falar com você.}
#Thanks again for everything!
{403}{}{Obrigado de novo por tudo!}
#Thanks so much!
{404}{}{Muito obrigado!}
#Finally we are safe.
{405}{}{Finalmente estamos salvos.}
#Thanks for everything! Be sure to stop by again once we expand the place. I'll finally have a working kitchen to cook in.
{406}{}{Obrigado por tudo! Tenha certesa de passar aqui novamente, pois vamos ter espandido bastante o lugar. Eu finalmente vou ter uma cozinha para trabalhar.}

#Hello again.
{410}{}{Oi denovo.}
#You seem to be quite busy here. Need some help with anything?
{411}{}{Você parece estar bem ocupado por aqui. Precisa de ajuda com algo?}
#Nevermind. Bye.
{412}{}{Nada não. Até.}

#How did it go?
{420}{}{Como foi lá?}
#How did what go? Oh, the merchant. Actually, I lost interest with him and wandered off.
{421}{}{Como foi? Ah, o mercante. Bem, na verdade eu perdi o interesse nele e sai fora.}

#What!? You realize this was our last chance to make arragements with him. We look like fools now standing him up.
 You've doomed us.
{430}{}{Oque!? Você tem noção que perdeu a ultima chance de fazer um acordo com ele. Nós ficamos parecendo uns patetas plantados aqui. Você condenou a todos nós.}
#Sorry, mistakes happen. Bye
{431}{}{Foi mal, erros acontecem. Até.}
#Not my problem. Bye.
{432}{}{Não é problema meu. Adeus.}
#You don't need to worry about any damn merchants. Because I plan on killing the whole lot of you
{433}{}{Você não precisa mais se preocupar com comerciantes mediocres. Pois eu pretendo matar toda a corja deles para você.}

#You convinced the merchant to add the village to his trade route
{500}{}{Você conseguiu convencer o mercador a adicionar a vila em sua rota de comércio.}
#You killed the merchant, thus ensuring that the village won't be able to trade.
{510}{}{Você matou o comerciante, garantindo que a vila não consiga mais negociar.}
#You fail to convince the merchant to add the village to his trade route.
{511}{}{Você falhou em converser o mercador a adicionar a vila em sua rota de comércio.}
