# You see a small boy
{100}{}{Você vê um garoto pequeno.}
# You see a small girl.
{101}{}{Você vê uma garota pequena.}
# He smiles when he sees you.
{102}{}{Ele sorri quando te vê.}
# She smiles when she sees you.
{103}{}{Ela sorri quando te vê.}
# He looks at you with uncertainty.
{104}{}{Ele olha para você com incerteza.}
# She looks at you with uncertainty.
{105}{}{Ela olha para você com incerteza.}
# He glares at you.
{106}{}{Ele te encara.}
# She glares at you.
{107}{}{Ela te encara.}

# Thanks for helping us mister!
{200}{}{Obrigado por nos ajudar senhor!}
# Yippie we are safe now!
{201}{}{Ebaaa, nós estamos seguros agora!}
# Thanks for helping us ma'am!
{202}{}{Obrigado por nos ajudar madame!}
# Yippie we are safe now!
{203}{}{Ebaaa, nós estamos seguros agora!}
# You're mean!
{204}{}{Você é malvado!}
# Are you here to help us?
{205}{}{Você está aqui para nos ajudar?}
