# You see a Vault City learning terminal.
{100}{}{Você vê um terminal de aprendizado de Vault City.}
# This computer appears to be a teaching system of some sort. A friendly Pip Boy is on the side.
{101}{}{Este computador aparenta ser um sistema de ensino de algum tipo. Um simpático Pip Boy está do lado.}
# You see the Vault City computer teaching system.
{102}{}{Você vê o computador do sistema de ensino de Vault City.}
# You tinker with the computer a bit, but you'll need to use some scientific skill to actually get anything useful out of the terminal.
{103}{}{Você fuçou um pouco no computador, mas você vai precisar de usar algumas habilidades de ciências para realmente conseguir extrair algo de útil do terminal.}
# You spend some time studying the computer archives.
{104}{}{Você passou algum tempo estudando os arquivos do computador.}
# You spend some time studying the archives but learn nothing more of importance.
{105}{}{Você passou algum tempo estudando os arquivos mas não aprendeu nada de importante.}