# You see the courtyard well.
{100}{}{Você vê o poço de água do pátio.}
# You could be wrong, but as you look down the well, you feel heat emanating from the darkness.
{101}{}{Você pode estar enganado, mas enquanto você olha para o fundo do poço, você sente o calor que vem da escuridão.}
# You take a big gulp of the well water. It's unusually warm.
{102}{}{Você toma um grande gole da água do poço. Está atipicamente morna.}
# You take a big gulp of the well water. It tastes much better than it did before.
{103}{}{Você toma um grande gole da água do poço. O gosto está bem melhor do que estava antes.}
