# As you leave the outskirts of the city you skillfully notice a group of armed men being stealthily led through the bushes by a strong
# looking tribal. The tribal glances in your direction and spots you looking at him. He gives a signal and the group of men
# he is leading duck down and disappear.
{100}{}{Assim que você deixa a periferia da cidade, você de forma sagaz percebe um grupo de homens armados sendo furtivamente levados entre os arbustos por um tribal
 musculoso. O tribal lança um olhar em sua direção e percebe você olhando para ele. Ele dá um sinal e o grupo de homens
 que ele está liderando se inclinam para baixo e desaparecem.}
# Follow them at a safe distance.
{101}{}{[Siga-os a uma distancia segura.]}
# Ignore and move on.
{102}{}{[Ignore e continue andando]}
