# 0. Look
#You see an addict.
{100}{}{Você vê um viciado.}
#This person is heavily drugged.
{101}{}{Esta pessoa está fortemente drogada.}
#He looks like he's high on drugs.
{102}{}{Ele parece que está sob efeito de drogas.}
#She looks like she's high on drugs.
{103}{}{Ela parece que está sob efeito de drogas.}
#He's looking pretty bad. You suspect it's withdrawal from some kind of drug.
{104}{}{Ele parece estar muito mal. Suspeita-se ser abstinência de algum tipo de droga.}
#She's seen better days. She looks like she's going through withdrawal.
{105}{}{Ela já esteve bem melhor. Parece que está passando por abstinência.}
#This addict looks like the living dead.
{106}{}{Este viciado parece com morto-vivo.}
#You think this addict just threw up.
{107}{}{É de supor que este viciado acabou de vomitar.}

# 1. CF: Attacked by PC
#The lights are hurting me!
{150}{}{As luzes estão me incomodando!}
#Monsters everywhere!
{151}{}{Vejo monstros por toda parte!}
#That felt weird.
{152}{}{Isso é estranho.}
#Am I bleeding?
{153}{}{Estou sangrando?}
#It doesn't normally seem this real.
{154}{}{Isso normalmente parece tão real.}
#Stop it, man!
{155}{}{Pare com isso, homem!}
#Will no one help me?
{156}{}{Será que ninguém vai me ajudar?}
#Help!
{157}{}{Socorro!}
#Get away!
{158}{}{Fique longe!}
#My head hurts enough as it is!
{159}{}{Minha cabeça está doendo para valer!}
#Leave me alone.
{160}{}{Me deixe em paz.}

# 2. CF: Normal
#Wow, you've got a weird dark glow.
{200}{}{Nossa, você está com um brilho escuro estranho.}
#My, you're a big pup.
{201}{}{Ora, você é um grande cachorrinho.}
#Don't tell them what we know is not there.
{202}{}{Não diga a eles o que sabemos que não está lá.}
#Ahhh…!
{203}{}{Ahhh...!}
#Can you see me?
{204}{}{Está me vendo?}
#Be vewy, vewy quiet. I'm hunting wabbits.
{205}{}{Fiqui bem, bem quieto. Estou caçando coelhis.}
#How did you get way up here?
{206}{}{Como você chegou até aqui em cima?}
#Shhh, I'm hiding.
{207}{}{Shhhíu, estou me escondendo.}
#I'm running faster than a wolf!
{208}{}{Estou correndo mais rápido do que um lobo!}
#I feel so alive!
{209}{}{Me sinto tão vivo!}
#It's coursing through my veins…!
{210}{}{Está correndo em minhas veias...!}
#Right there, baby.
{211}{}{Bem ali, boneca.}
#Oooohhh, can you feel the power?
{212}{}{Oooohhh, consegue sentir o poder?}
#Wow, you're glowing…!
{213}{}{Uau, você está brilhando...!}
#I love you, man!
{214}{}{Te amo, cara!}
#Life's been so good to me. Has it been good to you?
{215}{}{A vida tem sido tão boa para mim. Tem sido boa para você?}
#The little ones fly at night.
{216}{}{Os menores voam à noite.}
#Say hello to my little friend.
{217}{}{Diga olá para meu amiguinho.}
#Boy, I'm sleepy…!
{218}{}{Cara, estou com um sono...!}
#Have you seen my dog?
{219}{}{Você viu meu cachorro?}
#Shhh, they're right behind you…!
{220}{}{Shhhíu, estão bem atrás de você...!}
#Mine!
{221}{}{De mim!}
#Oooh, my head.
{222}{}{Oooh, minha cabeça.}
#I ache all over.
{223}{}{Está doendo tudo em mim.}
#I'm starting to get the shakes.
{224}{}{Está começando me dar tremedeira.}
#Oh, I need some more.
{225}{}{Oh, preciso de um pouco mais.}
#I need a fix.
{226}{}{Preciso tomar uma.}
#I can't wait, I need it now.
{227}{}{Não posso esperar, preciso agora.}
#You take my shit?
{228}{}{Você pegou minha merda?}
#Ah, leave me alone.
{229}{}{Ah, me deixe em paz.}
#I got the shakes bad, man.
{230}{}{Estou tremendo muito, cara.}
#I hate this part.
{231}{}{Odeio essa parte.}
#I just want to die.
{232}{}{Só quero mesmo é morrer.}
#I need some more bad.
{233}{}{Eu preciso de um pouco mais e logo.}
#I can't take this much longer.
{234}{}{Não posso suportar isso muito mais tempo.}
#I think I have a fever.
{235}{}{Acho que estou com febre.}
#I think I'm going to puke.
{236}{}{Acho que vou vomitar.}
#Maybe if I just sleep...
{237}{}{Talvez se eu dormisse...}
#I got the shakes bad, lady.
{238}{}{Estou tremendo muito, senhora.}

# 3. BGF: Hostile
#Is that blood?
{300}{}{Isso é sangue?}
#Whoa! Am I bleeding? I can't feel a thing!
{301}{}{Nossa! Estou sangrando? E não sinto nada!}
#It tingles.
{302}{}{Só formiga.}
#Who did that?
{303}{}{Quem fez isso?}
#What's going on?
{304}{}{O que está acontecendo?}
#I'm bleeding... I think.
{305}{}{Estou sangrando... Eu acho.}
#Oh, the pain.
{306}{}{Oh, chegou a dor.}
#Now I really need a fix.
{307}{}{Agora realmente preciso toma uma.}
#Just let me die.
{308}{}{Apenas deixe-me morrer.}

# 4. BGF: Normal
#Ahhhh...
{350}{}{Ahhhh...}
#I'm floating...
{351}{}{Eu estou flutuando...}
#I have the power!
{352}{}{Eu tenho a força!}
#Hello, Mr. Flower.
{353}{}{Olá, Sra. Flor.}
#All the colors...
{354}{}{De todas as cores...}
#More longer friend see that sky?
{355}{}{Tem mais velhos amigos que vê este céu?}
#They aren't listening...
{356}{}{Não estão ouvindo...}
#Where am I?
{357}{}{Onde estou?}
#There it is!
{358}{}{Aeh está!}
#Whoa, no! Stop! Wait! Okay, go ahead.
{359}{}{Ai, não! Pare! Espere! Ok, continue.}
#There, there... ahh...
{360}{}{Isso, isso... ahh...}
#Yea, baby!
{361}{}{Sim, garota!}
#What was that?
{362}{}{O que foi isso?}
#Sasha? Where are you Sasha?
{363}{}{Sasha? Onde está você Sasha?}
#The colors are fading!
{364}{}{As cores estão desaparecendo!}
#Mom?
{365}{}{Mamãe?}
#Hey! Get away from me! Oh…!
{366}{}{Ei! Se afaste de de mim! Oh...!}
#Don't you do that!
{367}{}{Não faça isso!}
#I can't see... again.
{368}{}{Não posso ver... mais.}
#Need...
{369}{}{Preciso...}
#Get more...
{370}{}{Consiga mais...}
#There? No.
{371}{}{Ali? Não.}
#No. Can't find it.
{372}{}{Não. Não consigo encontrar.}
#Make it stop!
{373}{}{Faça parar!}
#Ug.
{374}{}{Ai.}
#Oh, the pain.
{375}{}{Oh, que dor.}
#<cough> <cough> <cough>!
{376}{}{<tosse> <tosse> <tosse>!}
#Ooh, my head!
{377}{}{Ooh, minha cabeça!}
#Where'd I put my stash?
{378}{}{Onde coloquei meu estoque?}

# 5. Self Initiated: Attacking Player
#A demon!
{400}{}{Um demônio!}
#The enemy is upon us!
{401}{}{O inimigo está sobre nós!}
#You murderer! You killed my son!
{402}{}{Você assassino! Você matou meu filho!}
#A monster! Kill it!
{403}{}{Um monstro! Mate-o!}
#Ah! Pargasraka!
{404}{}{Ah! Pargasraka!}
#Feet fom chin rat going! Ahhh!
{405}{}{Olha o ladrão de queijo fugindo! Ahhh!}
#You won't take it from me!
{406}{}{Você não vai tirar isso de mim!}
#Give it back!
{407}{}{Devolva!}
#No!!!
{408}{}{Não!!!}
#My family!
{409}{}{Minha família!}