#You see a squatter.
{100}{}{Você vê um ocupante.}
#You see a man covered in dirt and filth
{101}{}{Você vê um homem coberto de terra e sujeira.}
#You see a woman covered in dirt and filth.
{102}{}{Você vê uma mulher coberta de terra e sujeira.}

#What do you want?
{103}{}{O que você quer ?}
#I want you and your friends out of this building. It's come to my attention that Mom intends to turn this place
 into an orphanage to get all those homeless children off the streets. And she can't do that with you squatting here.
 {104}{}{Eu quero você e seus amigos fora deste prédio. Veio a minha atenção que a Mãe pretende transformar esse lugar
 em um orfanato para tirar todas aquelas crianças abandonadas fora das ruas. E ela não pode fazer isso com vocês ocupando ele.} 
#He snickers uneasily and glances at his fellow squatters for support.] Mom knows the deal. We're not going anywhere
 until she coughs up the money. So unless you brought us a million coins, fuck off.
{105}{}{[Ele tosse levemente e olha para seus amigos ocupantes por apoio.] A Mãe conhece o negócio. Nós não vamos a lugar nenhum
até ela nos dar o dinheiro. Então a menos que vocês tenham nos trago um milhão de moedas, vão embora.}
#Look, Mom doesn't have that kind of money, and even if she did, she'd never pay you, so just forget it. Why not show
 some decency and go squat someplace else? Those homeless kids need this place a hell of a lot more than you do
{106}{}{Olha, a Mãe não tem esse tipo de dinheiro, e se ela tivesse, ela nunca iria pagar você, então esqueça. Por que não
mostrar um pouco de decência e ir ocupar outro lugar? Aquelas crianças abandonadas precisam deste lugar muito mais do que vocês.}
#Who're you to say who deserves what? We *like* it here. You can't make us leave
{107}{}{E quem é você para dizer quem preciza de quê ? Nós *gostamos* daqui, você não pode nos fazer sair.}
#Listen, you have two choices: You can either walk out of here on your own two feet, or *I* can remove you -- by dragging
 you out, one corpse at a time
{108}{}{Escute, você tem duas escolhas: Você pode andar pra fora daqui nos seus pés, ou *eu* posso tirar você -- arrastando você
pra fora, um corpo de cada vez.}
#([He exchanges a look with his fellow squatters, then looks back at you and shakes his head.] You can't intimidate us.
 No one's kicking us out of here. We'll fight you for our turf
{109}{}{([Ele troca um olhar com seus amigos, então olha denovo para você e balança a cabeça.] Você não nos assusta.
 Ninguém vai nos chutar pra fora daqui. Nós vamos lutar com você pelo nosso lugar.}
#[He exchanges a look with his fellow squatters, then looks back at you and nods.] OK, you made your point. It's not like
 we hate kids or anything, hell, most of us were homeless kids ourselves. We were just trying to make some money, you know? The
 only jobs around here involve peddling drugs or pain, and we're not into that. [He sighs.] We'll leave, but where do you suggest
 we go? This place is our home.
{110}{}{[Ele troca um olhar com seus amigos, então olha denovo para você e acena.] OK, você tem razão. Não é que nós odiamos crianças
 ou outra coisa, inferno, muitos de nós fomos crianças abandonadas também. Nós só estávamos tentando fazer algum dinheiro, sabe? Os
 únicos trabalhos por aí envolvem vender drogas ou dor, e nós não estamos nisso. [Ele suspira.] Nós sairemos, mas onde você sugere
 que nós vamos? Esse lugar é a nossa casa.}
#I don't know. That's not my problem
{111}{}{Eu não sei. Não é meu problema.}
#I may regret saying this, but if you're serious about wanting jobs, I'm sure Mom could use some help fixing this place up. She's a real nice lady,
 so maybe if you apologize, she'd give you a fair chance to prove you're more than a bunch of lazy opportunists. I'll talk to her about it. But if you try to
 fuck her over, I'll hunt you down and make you pay
{112}{}{Eu posso me arrepender de dizer isso, mas se vocês estavão falando sério sobre querer trabalhos, eu tenho certeza que a Mãe poderia usar
alguma ajuda conertando esse lugar. Ela é uma senhora muito boa, então se talvez você se desculpar, ela iria te dar uma boa chance de provar 
que vocês são mais que um monte de oportunistas preguiçosos. Eu vou falar com ela sobre isso. Mas se vocês tentarem ferrar ela, eu vou caçar vocês e fazer
 vocês pagarem.}
#Screw this, I changed my mind. We ain't leaving. We're staying right here and fighting
{113}{}{Que se ferre isso, eu mudei de idéia. Nós não vamos a lugar nenhum. Nós vamos ficar bem aqui e lutar.}
#[He exchanges a look with the other squatters and ponders your words.] You know what? That doesn't sound too bad. In fact, that could work out great,
 if you really think Mom will go for it. While you go talk to her, we'll get started on cleaning this place up. Oh, and thanks for being so cool about things.
{114}{}{[Ele troca um olhar com os outros ocupantes e pesa as palavras.] Sabe oquê ? Isso não parece tão ruim. De fato, isso paderia funcionar muito bem,
 se você acha que a Mãe vai acreditar. enquanto você vai falar com ela, nós vamos começar a limpar esse lugar. Oh, e obrigado por ser tão legal sobre as coisas.}
#Nevermind
{115}{}{De nada.}

#new for RP 1.3
She's not going to pay you. But I'm here to offer you a new deal: You and your friends walk away from here now, and you get to keep your lives.
{116}{}{Ela não vai pagar vocês. Mas eu estou aqui para oferecer um novo acordo: Você e seus amigos andam pra fora daqui, e vocês ficam vivos.}
#Alright, well, I gave it a shot. Bye.
{117}{}{OK, bem, eu tentei. Tchau.}

#This is a great idea. We'll get things ready
{120}{}{Essa é uma ótima idéia. Nós vamos arrumar tudo.}

{200}{}{Huh?}
#This is our turf
{201}{}{Esse é o nosso lugar.}
#You squatting here too?
{202}{}{Vocês estão ocupando aqui também ?}
#Got anything to eat?
{203}{}{Você tem alguma coisa para comer?}

#You see a man in work clothes
{300}{}{Você vê um homem usando roupas de trabalho.}
#You see a woman in work clothes
{301}{}{Você vê uma mulher em roupas de trabalho.}

#Hey, thanks for helping to set this up for us. We'll work hard.
{310}{}{Hey, obrigado por ajudar a arrumar isso para nós. Nós vamos trabalhar duro.}
#You better. Make sure the children stay out of trouble too.
{311}{}{È bom mesmo.Tenha certeza que as crianças fiquem fora de problemas.}
#We'll do our best.
{312}{}{Faremos o nosso melhor.}
#Bye.
{313}{}{Tchau.}

#third way to finish quest -added after initial creation, but before official release
#Anywhere but here. The Den's a big place, I'm sure you can find somewhere else to crash. Come on, do you really want the children to live on the streets?
{350}{}{Em qualquer lugar menos aqui. O Retiro é lugar grende, eu tenho certeza que vocês podem achar outro lugar pra viver. Vamos, você realmente quer que as crianças vivam nas ruas ?}
#Nah, you're right, that ain't cool for the children. Alright, we'll pack our things and move out. This place had a leaky roof anyway.
{351}{}{Nah, você está certo, isso não é bom para as crrianças. OK, nós vamos arrumar nossas coisas e sair. Esse lugar tinha um teto furado também.}
#Thanks. This means a lot to them. Take care.
{352}{}{Obrigado. Isso vai significar muito para eles. Se cuidem.}
#Nah, that ain't our problem. If Mom thinks it's that important to get those kids off the streets, then she should stop being stingy with her cash and share the
 wealth. Yeah, I've changed my mind, we're staying until she pays up. Now this conversation's over, so you better leave if you know what's good for you.
{353}{}{Nah, isso não é nosso problema. se a Mãe acha importante tirar essas crianças das ruas, então ela deveria parar de ser tão mão de vaca com o dinheiro e dividir a 
 riqueza. Yeah, eu mudei de idéia, nós iremos ficar até que ela pague. Agora essa conversa acabou, então é melhor você ir embora se você sabe oque é bom para você.}

 #Alright. No need for this to get out of control. I'll leave you alone.
{360}{}{OK. Sem necessidade para isso sair do controle. Eu vou deixar você em paz.}
#Time to clean this place up then. (Attack)
{361}{}{Hora de limpar esse lugar então. (Ataque)}

#Thanks again!
{400}{}{obrigado denovo!}
#We'll work hard.
{401}{}{Nós vamos trabalhar duro.}
#Thanks for being so cool about things.
{402}{}{Obrigado por ser tão legal sobre as coisas.}
#We won't let you down.
{403}{}{Nós não vamos te desapontar.}

#We'll collect our things and be out of here soon.
{500}{}{Nós vamos pegar nossas coisas e sair daqui a pouco.}
#You've cleared out all the squatters.
{600}{}{Você liberou todos os ocupantes.}

