#You see a short man with a thick mustache.
{100}{}{Você vê um homem baixo, com um bigode espesso.}
#You see the Great Ananias.
{101}{}{Você vê o Grande Ananias.}
#You see a short, mustachioed, man with a somewhat furtive look to him.
{102}{}{Você vê um homem baixo, de bigode, com um olhar de aparência um tanto furtiva.}
#You! What do you want to do to the, formerly, Great Ananias now?
{103}{}{Você! O que você quer fazer agora com o, antigo, Grande Ananias?}
#Get away from me!
{104}{}{Fique longe de mim!}
#Go ruin someone else's business.
{105}{}{Vá arruinar negócios de outra pessoa.}
#Take it out on someone else.
{106}{}{Vá incomodar outra pessoa.}
#You've already done your worst to me.
{107}{}{Você já fez todo mal possível mim.}
#Just go away, you've done enough harm to me.
{108}{}{Apenas vá embora, você fez mal o suficiente para mim.}
#I'm so hungry.
{109}{}{Estou com tanta fome.}
#How will I ever feed my family now?
{110}{}{Como que vou alimentar minha família agora?}
#You were born with a heart 12 sizes too small.
{111}{}{Você nasceu com um coração 12 vezes menor.}
#No, my friend, a MUMMY! Straight from the sands of ancient Egypt to the sands of the Wastes! Exclusively for you to see!
{112}{}{Não, meu amigo, uma MÚMIA! Direto das areias do Egito antigo para as areias dos Lixos! Exclusivamente para você ver!}
#OK, I'll bite. How much to see the wizened corpse?
{113}{}{OK, vou morder. Quanto para ver o cadáver enrugado?}
#(to yourself) Hmm, a mummy would kinda describe the way a ghoul looks. OK, I'd like to take a look -- how much?
{114}{}{(Para si mesmo) Hummm, uma múmia até que descreveria a forma como um fantasma se parece. OK, gostaria de dar uma olhada -- quanto?}
#I've seen enough corpses already. Goodbye.
{115}{}{Já vi cadáveres suficientes. Adeus.}
#Hello, welcome, salutations! I am the Great Ananias (he offers you a slight bow, with a flourish). I bring mysteries from near and far friend. Mysteries from a world beyond our own... of the Netherworld.
{116}{}{Olá, bem-vindo, saudações! Sou o Grande Ananias (ele faz um ligeira reverência, com um movimento). Trago mistérios de amigos próximos e distantes. Mistérios de um mundo além do nosso... do Submundo.}
#Come back to learn of the Great Ananias' mysteries of the Netherworld have you?
{117}{}{Volte para saber dos mistérios que o Grande Ananias tem do Submundo para você?}
#What kind of mysteries?
{118}{}{Que tipo de mistérios?}
#Uh, nice to meet you Mr. Great Anus...something.
{119}{}{Uh, prazer em te conhecer, Sr. Grande Ânus... alguma coisa assim.}
#Hmm, mysteries make me sleep uneasily, I better go. Goodbye.
{120}{}{Humm, mistérios me faz dormir inquieto, é melhor eu ir. Adeus.}
#Step right up!
{121}{}{Venham até aqui!?}

#Today, in the room within, I have, for your eyes exclusively...A Jan-u-wine Egyptian Mummy!
{127}{}{Hoje, lá dentro da sala, tenho, exclusivamente para seus olhos... Uma Múmia Egípcia Genuína!}
#A mummy?
{128}{}{Uma múmia?}
#A mummy? Hmm, I wonder if it could be.... No, nobody could be that stupid.
{129}{}{Uma múmia? Humm, fico imaginando se poderia ser.... Não, ninguém poderia ser tão estúpido.}
#I don't have any interest in that sort of thing. Corpses scare me.
{130}{}{Não tenho nenhum interesse nesse tipo de coisa. Cadáveres me assustam.}
#Out of the way, you're blocking paying customers.
{131}{}{Fora do caminho, você está bloqueando clientes pagantes.}
#I don't think this is for you.
{132}{}{Não acho que isso é para vocês.}
#Why don't you take your little tribal self elsewhere.
{133}{}{Queira levar seus pequenos selvagens para outro lugar.}
#This isn't really for you.
{134}{}{Isto realmente não é para vocês.}
#I see, hmmm, how about GO (he points) AWAY!
{135}{}{Entendo, hummm, que tal SOMEM (apontando) DAQUÍ!}
#For a person of your obvious class I would be happy to show this unique, and historic, specimen to you for a mere $25.
{136}{}{Para uma pessoa de sua classe, ficaria feliz em mostrar estes espécimes únicos e históricos, para você pela bagatela de $ 25.}
#OK, I'll cough up the dough. Now...Show Me The Mummy!
{137}{}{OK, vou coçar o bolso e pegar o dinheiro. Agora... Me Mostre A Múmia!}
#I don't want to spend that much. I think I'll survive without seeing the thing. Goodbye.
{138}{}{Não quero gastar isso tudo. Acho que vou sobreviver sem ver essa coisa. Adeus.}
#Simply open the sarcophagus lid and the marvelous Mummy will be revealed, in all its ancient glory, to you. But please, no touching, and, uh, no flash photography.
{139}{}{Basta abrir a tampa do sarcófago e a maravilhosa Múmia será exibida, em toda sua glória antiga, para você. Mas, por favor, não toque, e, uh, sem fotografia flash.}
#Great.
{140}{}{Ótimo.}
#There you go! The MUMMY! (the door to the sarcophagus swings open to reveal a desiccated corpse, that looks very much like an ordinary ghoul, standing in a poorly painted, chipped and cracked paper-mache sarcophagus.)!
{141}{}{Aqui está! A MÚMIA! (a porta para o sarcófago abre para exibir um cadáver dissecado, que se parece muito com um fantasma comum, que está em um sarcófago de papel-machê mal pintado, quebrado e rompido.)!}
#There you go! Presenting, the MUMMY! (a crypt-like door swings open to reveal a jan-u-wine Egyptian mummy standing in an open sarcophagus that looks as though it's made out of pure gold!)!
{142}{}{Aqui está! Apresentando, a MÚMIA! (uma cripta tipo porta se abre para exibir uma múmia Egípcia genuína em um sarcófago aberto que parece que foi feito de ouro puro!)!}
#Hey, wait a minute. That's not a Mummy. That's a ghoul. WOODY! Hey WOODY! Is that you?
{143}{}{Ei, espere um minuto. Isso não é uma MÚMIA. Isso é um vampiro. WOODY! Ei WOODY! É você?}
#That sure looks like a ghoul to me.
{144}{}{Isso com certeza se parece com um vampiro para mim.}
#That's a mummy? I can't believe I just paid $25 to see a six-foot hunk of jerky. Goodbye.
{145}{}{Isso é uma múmia? Não acredito que acabei pagando $25 para ver um pedaço de seis metros de carne-seca. Adeus.}
#Wow, that's fantastic...I guess. (you look at the Mummy very intently for a while). Uh, thanks, Goodbye.
{146}{}{Uau, isso é fantástico... eu acho. (você olha para a Múmia bem atentamente por um tempo). Uh, obrigado, Adeus.}
#(the Mummy, snorts, stretches languidly, and then looks at you with a sleepy blink to its eyes) Hello. (he says, sleepily)!
{147}{}{(a Múmia, ronca, estica-se fracamente e, em seguida, olha para você com um piscar de olhos sonolento em seus olhos) Olá. (diz, sonolenta)!}
#Holy shit! That *is* Woody! Run Woody, run for it! Well, uh, gimp for it then! Go Woody go!
{148}{}{Puta merda! Esse *is* é Woody! Fuja Woody, correr sem parar! Bem, uh, olhe para ele, então! Vái Woody, vai!}
#I assure you that the Mummy is, in fact, quite jan-u-wine.
{149}{}{Te garanto que a Múmia é, de fato, bastante genuína.}
#I don't think I believe you. Let me try something. WOODY! Hey WOODY! Is that you?
{150}{}{Não acho que acredito em você. Deixe-me tentar algo. WOODY! Ei WOODY! É você?}
#Well, if you say so. But I sure think it looks like an ordinary ghoul. Goodbye.
{151}{}{Bem, se diz que sim. Mas tenho certeza que se parece com um vampiro comum. Adeus.}
#(Woody--for it is in fact Woody, not a Mummy, that stands somewhat drowsily before you--grabs the sides of the paper-mache sarcophagus, lets out a shriek and runs for the door, leaving a trail of toilet-paper 'mummy-wrappings' and a hasty "Thankee kindly, Stranger!" behind him.
{152}{}{(Woody--pois na verdade é Woody, e não uma Múmia, que fica um pouco sonolenta na sua frente--agarra os lados de do sarcófago de papel machê, deixa escapar um grito e corre até a porta, deixando um rastro de 'trapos de panos de enrolar múmias' tipo papel higiênico e um apressado "Muito Obrigado, Estranho!" atrás dela.)}
#Hah! I knew it! You're finished in this town. You're not the Great Ananias anymore, you're just another ass.
{153}{}{Ah! Eu sabia! Você está acabado nesta cidade. Você não é mais o Grande Ananias, você é apenas mais um idiota qualquer.}
#Go Woody go! Ahah! I knew it!
{154}{}{Vái Woody vai! Aháh! Eu sabia!}
#(The Great Ananias shrugs) I knew I should have picked up that mono-headed Brahmin instead. Oh well, back to the drawing board.
{155}{}{(O Grande Ananias dá de ombros) Eu sabia que deveria ter escolhido aquele Brahmim de uma cabeça no lugar. Oh bem, de volta ao roteiro.}
#Mono-headed brahmin? Sure, who would ever believe that! Goodbye, you Charlatan.
{156}{}{Brahin de uma cabeça só? Claro, quem iria acreditar nisso! Adeus, seu Charlatão.}
#You woke up Woody the ghoul and freed him from indentured mummy-tude.
{157}{}{Você acordou Woody, o vampiro, e libertou-o daquela mumificação temporária.}
#I think I'd rather hear the ghost story.
{158}{}{Acho que prefiro ouvir história de fantasmas.}

#I know things that mere mortal man is not meant to know. Aiiieeee! Nyarloth...Oh, sorry (heh, heh). Got a little carried away there for a moment. I have tales of a Ghost that haunts these very grounds, as well as a Jan-u-wine Egypt-ee-an Mummy that you can see, right here in this marvelous sarcophagus.
{200}{}{Sei de coisas que simples mortais não são para conhecerem. Aiiieeee! Nyarloth... Oh, desculpe (heh, heh). Me entusiasmei um pouco nessa. Sei de histórias de um Fantasma que assombra essas mesma terras, assim um Múmia Egípcia Genuína que pode ver, bem aqui neste maravilhoso sarcófago.}
#Tell me about the mummy. I'm just dying to hear more about that.
{201}{}{Conte-me sobre a múmia. Estou morrendo de vontade de ouvir mais sobre isso.}
#I've just got to hear that ghost story. Uh, do I get a nice hot cup of cocoa to go with it?
{202}{}{Só quero ouvir essa história de fantasma. Uh, consigo por aqui um belo copo de nescau quente para acompanhar?}
#I don't think I have any more time to waste on whatever it is that you're hawking.
{203}{}{Não acho que tenho mais tempo para perder com seja o que for que estiver vendendo.}

#Well, you see, (he motions you closer) there was once a great queen that ruled all of the surrounding town. She kept her throne by virtue of a special amulet that she kept around her neck at all times. Great stuff, huh?
{300}{}{Bem, ouça bem, (ele chega mais perto), houve uma vez uma grande rainha que governava toda a cidade ao redor. Ela mantinha seu trono por virtude e um amuleto especial que ela mantinha em volta de seu pescoço o tempo todo. Ótima história, não é?}
#Uh, yeah. You bet. So this princess had a *magic* amulet. Oh, do go on. I just can't stand this level of suspense much longer (yawn).
{301}{}{Uh, sim. Pode apostar. Portanto esta princesa tinha um amuleto *mágico*. Oh, continue logo. Não aguento este suspense todo muito mais tempo (bocejo).}
#OK. I think I've heard just about enough. Goodbye.
{302}{}{Tudo bem. Acho que já ouvi o bastante. Adeus.}

#Well, I'll cut to the chase then. So, the evil wizard poisoned the young princess and took her amulet. She's been wandering around the room next door ever since. Well, uh, that is, just at the witching hour, anyway. That's why I keep the door locked. Pretty darn scary, huh?}
{400}{}{Bem, vou direto ao assunto então. No entanto, o feiticeiro malvado envenenou a jovem princesa e pegou seu amuleto. Ela vaga pela sala ao lado desde então. Bem, hã, isso é, somente nas horas das bruxas, mesmo. Isso é o porquê mantenho a porta trancada. É muito amedrontador, não é?}
#The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story. I'd rather hear about this stupid Mummy you're supposed to have here.
{401}{}{O fantasma de uma princesa sem amuleto na sala destruída ao lado? É isso? Não acredito que está vendendo *isso* como uma história. Prefiro ouvir sobre essa Múmia estúpida que você diz ter aqui.}
#OK. I think I've heard just about enough. Goodbye.
{402}{}{Está bem. Acho que já ouvi o suficiente. Adeus.}
