#You see a ghost!
{100}{}{Você vê um fantasma!}
#You see Anna the ghost.
{101}{}{Você vê o fantasma de Anna.}

#This a ghost. That's not something you see every day.
{150}{}{Isto é um fantasma. Isso não é algo que se vê todos dias.}
#She seems quite tormented.
{151}{}{Ela parece bastante atormentada.}
#[TALK]!
{152}{}{[CONVERSAR]!}
#Oh, the pain! It burns so!
{153}{}{Oh, que dor! Queima tanto!}
#What's the matter?
{154}{}{Qual é o problema?}
#Who are you?
{155}{}{Quem é você?}
#Begone, foul spirit!
{156}{}{Sai fora, espírito imundo!}
#I stop and knock at every door, but no one comes, no one hears.
{157}{}{Paro e bato em todas portas, mas ninguém aparece, ninguém ouve.}
#I can hear you. What's the matter?
{158}{}{Posso ouvir você. Qual o problema?}
#I think you need to turn off your Stealth Boy, ma'am.
{159}{}{Acho que precisa desligar seu Disfarce de Garoto, senhora.}
#Where is it? I cannot find it! I am lost! Oh....
{160}{}{Cadê? Não consigo encontrar! Estou perdida! Oh....}
#What are you looking for? Maybe I can help.
{161}{}{O que está procurando? Talvez possa ajudar.}
#You really need to stop moaning and groaning and start making sense.
{162}{}{Você realmente precisa parar de se lamentar rosnando para começar a fazer sentido.}
#My locket! It is gone. Thief! Thief!
{163}{}{Meu medalhão! Sumiu. Ladrão! Ladrão!}
#Whoa, I just got here. I didn't do it.
{164}{}{Puxa, estava bem aqui. Não te disse.}
#Can I help you find it?
{165}{}{Posso te ajudar a encontrá-lo?}
#Oh, cruel fate.
{166}{}{Oh, destino cruel.}
#You can't hear me, can you?
{167}{}{Pode me ouvir, não pode?}
#Later, ghost girl.
{168}{}{Mais tarde, menina fantasma.}
#Bye. I'll try to help.
{169}{}{Tchau. Vou tentar ajudar.}
#My locket! Give it to me!!! Oh!!!!
{170}{}{Meu medalhão! Me dê ele!!! Oh!!!!}
#No way! Go to hell. I found this fair and square.
{171}{}{De jeito nenhum! Vá para o inferno. Achado não é roubado.}
#OK. Here you go.
{172}{}{Ok. Pegue ele.}
#Here. May you rest in peace.
{173}{}{Tome. Que você descanse em paz.}
#OK.
{174}{}{Está bem.}
#No.
{175}{}{Não.}
#My locket, my locket! I'm coming, Daddy! I'm coming!
{176}{}{Meu medalhão, meu medalhão! Estou chegando, Papai! Estou chegando!}
#Goodbye.
{177}{}{Adeus.}
#Wait! Don't go!
{178}{}{Espere! Não se vá!}
#Go into the light.
{179}{}{Vá para a luz.}

#Where could it be?
{200}{}{Onde poderia estar?}
#Ohhh.
{201}{}{Ohhh.}
#Mommy? Daddy? Where are you?
{202}{}{Mamãe? Papai? Onde vocês estão?}
#I can't find it!
{203}{}{Não consigo encontrá-lo!}

#Mommy... Daddy... I'm coming...
{500}{}{Mamãe... papai... Estou chegando...}
#It's so bright...
{501}{}{É tão brilhante...}
#Grammy, I can see you...
{502}{}{Vovô, Estou te vendo...}
#Oh, it's the kind Mr. Cain. It's good to see you again...
{503}{}{Oh, é o gentil Sr. Cain. É bom vê-lo de novo...}

#This house is clear.
{550}{}{Esta casa está limpa.}
#Oog, pretti bones.
{551}{}{Ooh, Ossos brronitos.}
  
#GHOST BUSTER!
{560}{}{CAÇA FANTASMA!}
{561}{}{Ug.}
#Ug.
