# 8. BF: Hostile Primitive
#Quiet! They near.
{245}{}{Quieto! Eles estão próximo.}
#Kill bad men.
{246}{}{Matem os homens maus.}
#No take family from me.
{247}{}{Não vão tirar minha família de mim.}
#I protect family.
{248}{}{Vou protejer minha família.}
#Must not find us.
{249}{}{Não podem nos encontrar.}
#They bad people.
{250}{}{São pessoas más.}

# 9. BF: Hostile Nomad
#Slavers are coming. Everyone quiet.
{260}{}{Escravistas estão chegando. Todo mundo quieto.}
#Get ready; I think they're close now.
{261}{}{Prepare-se; Acho que estão perto agora}.
#I'm not going down without a fight.
{262}{}{Não vou ser derrotado sem lutar.}
#They'll never enslave us.
{263}{}{Nunca vão nos escravizar.}
#Those slavers will pay for this.
{264}{}{Esses escravistas vão pagar por isso.}
#No slaver's going to take my family.
{265}{}{Nenhum escravista vai levar minha família.}
# looks
# primitive
#This man looks fairly strong and alert.
{100}{}{Este homem parece bastante forte e alerta.}
#She seems strong despite her size.
{101}{}{Ela parece forte, apesar de seu tamanho.}

# nomads
#He seems to be awfully thin but angry.
{200}{}{Ele parece ser muito magro, mas também furioso.}
#This one looks fairly strong.
{201}{}{Este parece bastante forte.}
#He moves with great speed.
{202}{}{Ele se move com grande velocidade.}

#She doesn't seem to have ever bathed.
{210}{}{Ela não parece nem ter tomado banho.}
#She looks like strong fighter.
{211}{}{Ela parece ser uma lutadora forte.}
#This one doesn't seem like much trouble.
{212}{}{Este não parece ser de muito problema.}

# 12. Combat Float: Hostile Primitive
#You die now!
{300}{}{Você vai morrer agora!}
#Me kill!
{301}{}{Eu vou matar!}
#You no hurt family!
{302}{}{Você não vai ferir minha família!}
#You no take family!
{303}{}{Você não vai levar minha família!}
#I protect!
{304}{}{Vou protejê-la!}
#I hurt you!
{305}{}{Vou atacar você!}
#You pay!
{306}{}{Você vai pagar por isso!}
#Die!
{307}{}{Morra!}
#I'm gonna hurt you.
{308}{}{Vou acabar com você.}

# 13. Combat Float: Hostile Nomad
#You're not going to take my family, slaver!
{350}{}{Você não vai levar minha família, escravista!}
#Die, slaving scum!
{351}{}{Morra, escória escravista!}
#You'll pay, you bastard!
{352}{}{Você vai pagar por isso, seu bastardo!}
#I'll fight to the death for my family!
{353}{}{Vou lutar até a morte por minha família!}
#You won't get away with this!
{354}{}{Você não vai conseguir seu objetivo!}
#You're not leaving here with my friends!
{355}{}{Você não vai sair daqui com meus amigos!}
#I'm going to get you for this!
{356}{}{Vou acabar com você por isso!}
#God damn slavers!
{357}{}{Maldito escravistas!}
#You'll pay for this!
{358}{}{Irão pagar por isso!}
