#You see a patron of the Hole.
{100}{}{Você vê um freguês do Buraco.}

#This fellow sure isn't very attractive.
{150}{}{Este indivíduo certamente não é muito atraente.}
#This guy's only got one tooth.
{151}{}{Esse cara só tem um dente.}
#[TALK]!
{152}{}{[CONVERSAR]!}
#Your wife sure is pretty!
{153}{}{Sua esposa certamente é bonita!}
#Get away from us.
{154}{}{Afaste-se de nós.}
#You like her, huh?
{155}{}{Gostou dela, eh?}
#Yes, she is.
{156}{}{Sim, ela é.}
#Yup.
{157}{}{Sim.}
#I sure would like to do her.
{158}{}{Com certeza gostaria de transar com ela.}
#Go right ahead.
{159}{}{Siga em frente.}
#OK. That'll be $50.
{160}{}{Está bem. Isso vai custar $ 50.}
#Sure, but it'll cost you $200.
{161}{}{Claro, mas vai te custar $200.}
#No way! Get away from us!
{162}{}{De jeito nenhum! Afaste-se de nós!}
#OK.
{163}{}{Está bem.}
#No.
{164}{}{Não.}
#Alright! Now come with Billy, sweetie.
{165}{}{Tudo bem! Agora vêm com o Billy, docinho.}
#Now go away.
{166}{}{Agora vá embora.}
#Thanks. Bye.
{167}{}{Obrigado. Tchau.}
#Bye.
{168}{}{Tchau.}
#Aw, shucks.
{169}{}{Argh, que nojo!}
#[DONE]!
{170}{}{[FEITO]!}
#I am plumb tuckered out.
{171}{}{Estou completamente esgotado.}
#I'll come back.
{172}{}{Vou voltar.}
#OK.
{173}{}{Está bem.}
#You sure are a pretty thing.
{174}{}{Você com certeza é uma coisinha e tanto.}
#Get away from me.
{175}{}{Afaste-se de mim.}
#Give me $200 and you can spend some time with me.
{176}{}{Dê-me $200 e poderá passar algum tempo comigo.}
#I cost $50, Mac.
{177}{}{Cobro $50, Amigo.}
#Hee hee. Thanks.
{178}{}{Oba, oba. Obrigado.}
#I don't have enough money.
{179}{}{Não tenho dinheiro suficiente.}
#Ok, $50 then.
{180}{}{Ok, $50, então.}
#Too bad for you.
{181}{}{Azar seu.}
#See you around.
{182}{}{Te vejo por aí.}
#Don't bother me. I'm scoping for nice-looking chicks.
{183}{}{Não me perturbe. Estou procurando por garotinhas de boa aparência.}
#Good luck. You'll need it.
{184}{}{Boa sorte. Vai precisar.}
#What am I, chopped liver?
{185}{}{O que sou eu, um fígado moído?}
#Bye.
{186}{}{Tchau.}
#Oooh. OK. Bye.
{187}{}{Oooh. Está bem. Tchau.}
#[looks you up and down] No. I like chopped liver.
{188}{}{[Te olha de cima em baixo] Não. Eu gosto de fígado moído.}
#I don't need this from you!
{189}{}{Não preciso disso de você!}
#Excuse me, I have to go.
{190}{}{Desculpe-me, Tenho que ir.}
#Too bad. I thought you were cute.
{191}{}{Que pena. Pensei que você fosse esperto.}


#I want my money back.
{203}{}{Quero meu dinheiro de volta.}
#I ain't giving you anything but a hole in the head.
{204}{}{Não vou te dar nada, a não ser te fazer um buraco na cabeça.}
#OK, here you go.
{205}{}{Tudo, aqui está.}
#I don't have it.
{225}{}{Não tenho.}

#Hey.
{206}{}{Ei.}
# Oh come on, give (player_name) another chance here.
{207}{}{Ah, qual é, dê para (player name)}
# another chance here.
{208}{}{ outra chance.}
#I can see you don't want to talk to me. I'm leaving.
{209}{}{Percebo que não quer falar comigo. Estou indo.}

#I gave you your chance and you blew it.
{210}{}{Te dei uma chance e você desperdiçou.}
#OK, but just one more chance.
{211}{}{OK, mas apenas mais uma chance.}
#That's my boy.
{212}{}{Esse é o meu garoto.}
#I'm just gonna have to kill you, then.
{213}{}{Só me resta ter que te matar, então.}

#Hey!, Frankie, I'm gonna just borrow the back room for a little while.
{220}{}{Ei!, Frankie, Vou tomar emprestado o quartinho dos fundos só por um tempinho.}
#Hey!, Frankie, look what I snagged.
{221}{}{Ei, Frankie, olha só que peguei.}
#Uh, Frankie, if anyone's... uh... looking for me, I'll be in back.
{222}{}{Uh, Frankie, se alguém... ah ... procurar por mim, diga que volto logo.}

#Follow me.
{223}{}{Me acompanhe.}
#It's gonna have to wait. I'll talk to you later.
{224}{}{Vai ter que esperar. Falo com você mais tarde.}


# 10.}
#Damn, I'm fucked flat.
{300}{}{Porra, Estou completamente fodido.}
#Wahoo.
{301}{}{Írrraah.}
#That was... was... WOW!!!
{302}{}{Isso é igual a ... LEGAL!!!}
#You could set her ass on fire.
{303}{}{Você pode deixá-lo fodido.}
#Damn that parted my hair - well, what little I have.
{304}{}{Foda-se que estragou meus cabelos - bem, o pouco que tenho.}
#Sure beats a roll with Dave.
{305}{}{Com certeza que isso é melhor do que arrumar confusão com Dave.}

# 11.}
#Not bad... Not bad...
{320}{}{Nada mal ... Nada mal ...}
#I might even pay for that again.
{321}{}{Poderia até pagar para fazer isso de novo.}
#Mmmm...
{322}{}{Mmmm ...}
#Not bad, not bad.
{323}{}{Nada mal, nada mal.}
#We'll have to do that again and work on our... flexibility.
{324}{}{Vamos ter que fazer isso de novo e trabalhar em nossa ... flexibilidade.}

# 12.}
#Looks like I'm going to be getting Handy again.
{350}{}{Parece que ter que ficar DE BOA de novo.}
#Don't let the door hit your DRY ASS on the way out!
{351}{}{Cuidado com a porta bater na sua BUNDA SECA ao sair!}
#Time to finish what you couldn't even start!
{352}{}{Hora de terminar o que você nem poderia ter começado!}

# 13.}
#Oh, that's nice.
{370}{}{Oh, isso é bom.}
#Billy likes that.
{371}{}{Billy gosta disso.}
#Ohhhh yeah.
{372}{}{Ohhhh sim.}
#Nice.
{373}{}{Ótimo.}
#Jeezus and ramona.
{374}{}{Jeezus e Ramona.}
#Good Gracious.
{375}{}{Ótima Generosidade.}
#I shoulda packed a box of tissue.
{376}{}{Deveria ter embalado uma caixa de lenços de papel.}
#Hmmm, who should I imagine now.
{377}{}{Hmmm, quem deveria imaginar agora.}

# 14.}
#Hey!, can't you see I'm busy in here?
{390}{}{Ei, será que não vê que estou ocupado aqui?}
#Hey!, Ei!, get the hell out.
{391}{}{Ei!, Ei!, dê o fora.}
#Hey!, you couldn't finish the job, so get out.
{392}{}{Ei, não pode terminar o trabalho, então sai fora.}
#Can you get me a mop and come back in 5?
{393}{}{Poderia me conseguir uma vassoura e voltar em 5 minutos?}

#Billy, you better not have made a mess on that mattress again!
{400}{}{Billy, é melhor que você não ter feito bagunça naquele colchão de novo!}
#Hey Billy, you need a mop?
{401}{}{Ei Billy, precisa de uma vassoura?}
#Billy, your fly's down. AGAIN!
{402}{}{Billy, seu zipper está abaixado. DE NOVO!}
#Yo Billy, don't forget to change your pants later.
{403}{}{Você Billy, não se esqueça de trocar suas calças mais tarde.}
#Billy, you been eating doughnuts?
{404}{}{Billy, está comendo rosquinhas?}

#Uhhh.
{410}{}{Uhhh.}
#Shucks!
{411}{}{Que nojo!}
#Jeesh!
{412}{}{Ééca!}
#He, he, heee...
{413}{}{Ha, ha, ha ha...}
#Huh?
{414}{}{Hein?}

#*SPIT, SPIT* Eccchhhh...
{500}{}{*ESCARRADEIRA, ESCARRADEIRA* Eccchhhh ...}

#Hey buddy, care to "rent" that fine ho of yours?
{510}{}{Ei amigo, se importaria de "alugar" essa tesãozinha de putinha sua?}
#Can't this wait? I've got to get a drink.
{511}{}{Isso não pode esperar? Tenho que pegar uma bebida.}
#Yeah, if you want to talk to me, I'll be at The Hole.
{512}{}{Sim, se quiser falar comigo, Vou estar no Buraco.}
#How about you meet me at The Hole and I buy you a drink?
{513}{}{Que tal me encontrar no Buraco e te pagar uma bebida?}

#Sorry, I'm a hurry to get home. I just got some new porn in.
{520}{}{Desculpe, estou com pressa de chegar em casa. Acabei de receber algumas novas revistas pornô.}
#I'm uhhh, tired, please let me go home and uhhh, sleep...
{521}{}{Estou uhhh, cansado, por favor, deixe-me ir para casa e uhhh, dormir...}
#I'm going over to Dave's. He's got a whole porn wing!
{522}{}{Estou indo no Dave. Ele tem uma série pornô completa!}

#Uhhh, no thanks. I don't have money to piss away on that again.
{530}{}{Uhhh, não, obrigado. Não tenho dinheiro para jogar fora nisso de novo.}

#Alright, I'll give your ass a try again.
{540}{}{Tudo bem, Vou tentar mais uma vez com você.}
