# You see a member of the Slaver's Guild.
{100}{}{Você vê um membro da Associação dos Escravistas.}

# You see Metzger, head of the Slaver's Guild.
{150}{}{Você vê Metzger, líder da Associação dos Escravistas.}

# [TALK]
{151}{}{[FALAR]}

# Guards! Attack!
{152}{}{Guardas! Atacar!}

# [done]
{153}{}{[pronto]}

# Come back in the morning damn it! I do my business during the day.
{154}{}{Volte amanhã de manhã, porra! Eu só trabalho durante o dia.}

# [done]
{155}{}{[pronto]}

# What is it now? You're really starting to piss me off.
{156}{}{O que foi agora? Você está começando a dar nos meus nervos.}

# I would like to apologize.
{157}{}{Eu queria pedir desculpas.}

# Sorry, I was drugged earlier. I didn't mean anything.
{158}{}{Desculpe, eu tinha me drogado daquela vez. Eu não sabia o que estava fazendo.}

# Whoa, what's your problem?
{159}{}{Ei, qual é o seu problema?}

# I wanted to ask you a question.
{160}{}{Eu quero te fazer uma pergunta.}

# Apparently I have. Good bye.
{161}{}{Aparentemente eu tenho. Adeus.}

# Wah.
{162}{}{Uhh.}

# Well, it's too late for that. Get out.
{163}{}{Bom, tarde demais pra isso. Vá embora.}

# Please, please, please; I'm sorry.
{164}{}{Por favor, por favor, por favor; Desculpa.}

# Oh well, I tried.
{165}{}{Bom, pelo menos eu tentei.}

# Screw you, then!
{166}{}{Então vai se foder!}

# Alright, alright. Apology accepted.
{167}{}{Tá bom, tá bom. Desculpas aceitas.}

# Whew. Can I ask you some questions?
{168}{}{Ufa. Posso fazer algumas perguntas?}

# I'm glad we straightened that out. See you later.
{169}{}{Fico feliz de termos resolvido isso. A gente se vê.}

# Hello. It's good to see you.
{170}{}{Oi. É bom te ver.} 

# Hi Metzger. We need to talk.
{171}{}{Oi, Metzger. Precisamos conversar.}

# You too. Bye.
{172}{}{Você também. Adeus.}

# Blurp.
{173}{}{Burp.}

# I am Metzger, Head of the Slaver's Guild. Whatcha need?
{174}{}{Eu sou Metzger, líder da Associação dos Escravistas. O que você precisa?}

# Yes, I have some questions.
{175}{}{Sim, eu tenho algumas perguntas.}

# No thanks. I'll just go now.
{176}{}{Não obrigado. Eu já estou de saída.}

# Swavuh???
{177}{}{Sóóó???}

# Please leave. Now.
{178}{}{Por favor, saia. Agora.}

# Or what?
{179}{}{Ou o quê?}

# Alright. But I'll be back!
{180}{}{Tá bom. Mas eu voltarei!}

# OK. Bye.
{181}{}{OK. Adeus.}

# What would you like to know?
{182}{}{O que você quer saber?}

# About Trader Vic...
{183}{}{Sobre o Mercador Vic...}

# Can I join the Slaver's Guild?
{184}{}{Posso entrar para a Associação dos Escravistas?}

# I'd like to sell my husband into slavery.
{185}{}{Eu gostaria de vender meu marido.}

# I'd like to sell my wife. How much?
{186}{}{Eu gostaria de vender minha esposa. Quanto dá por ela?}

# I'd like to sell one of my friends here.
{187}{}{Eu gostaria de vender um dos meus amigos aqui.}

# Tell me about the guild.
{188}{}{Me fale sobre a associação.}

# What cities buy your slaves?
{189}{}{Que cidades compram seus escravos?}

# I'd like to buy a slave.
{190}{}{Eu gostaria de comprar um escravo.}

# I'm looking for Vault 13. Have you heard of it?
{191}{}{Eu estou procurando a Vault 13. Já ouviu falar de lá?}

# Metzger? That's a strange name.
{192}{}{Metzger? Que nome engraçado.}

# Nothing. I have to go.
{193}{}{Nada. Eu tenho que ir.}

# It's from an old language, prewar or something.
{195}{}{É de uma linguagem antiga, de antes da guerra por aí.}

# Metzger means butcher. Fitting, don't you think?
{196}{}{Metzger significa açougueiro. Apropriado, não acha?}

# That was my great grandfather's name. He can from somewhere far to
 the east. Across a large body of water.
{197}{}{Era o nome do meu bisavô. Ele veio de algum lugar distante do oriente.
 Atravessando a vastidão das águas costeiras.}
 
# I read some book about a Metzger. He was a president, or something.
{198}{}{Eu li um livro sobre um Metzger. Ele era um presidente, ou algo assim.}

# Look who's talking tribal.
{199}{}{Olha só quem fala, índio.}

# It's Germen, German, Garmen, or something. Ancient language, from a
 long time ago.
{200}{}{É alimão, alemão, alemau, por aí. Uma língua antiga, de muito tempo atrás.}

# Et tu, Brutus?
{201}{}{Até tu, brutus?}

# I see. I still have a question, though.
{202}{}{Entendo. Eu tenho outra pergunta.}

# That is the dumbest thing I have ever heard.
{203}{}{Essa é a coisa mais estúpida que já ouvi.}

# Fascinating. Gotta go.
{204}{}{Fascinante. Tenho que ir.}

# Our mission is provide a steady and high-quality labor force to
 handle the ever-growing demands of the larger cities. Would you like to join?
{205}{}{Nossão missão é prover uma força de trabalho consistente e de alta qualidade 
 para atender a crescente demanda das cidades grandes. Quer se juntar a nós?}
 
# Sure. Sounds great.
{206}{}{Claro. Parece ótimo.}

# No way.
{207}{}{De jeito nenhum.}

# I'll get back to you on that. What cities buy your slaves?
{208}{}{Eu vou tentar de novo. Quais cidades compram seus escravos?}

# Sorry, that's private guild information.
{209}{}{Desculpe, isso é informação confidencial da associação.}

# OK. Sign me up!
{210}{}{OK. Estou dentro!}

# No! You guys are sick people!
{211}{}{Não! Vocês são doentes!}

# I'll consider that. I have more questions.
{212}{}{Vou pensar. Eu tenho mais perguntas.}

# Hmm, I'll come back later.
{213}{}{Hmm, Eu volto depois.}

# We will need to brand a small marking on your forehead to show to all
 your allegiance with the slavers guild. Are you ready?
{214}{}{Nós vamos precisar fazer uma pequena marca na sua testa para mostrar a todos
 que você se filiou à associação dos escravistas. Podemos começar?}
 
# Sounds great! Do it!
{215}{}{Parece ótimo! Manda ver!}

# I've changed my mind. Can I ask another question?
{216}{}{Mudei de ideia. Posso fazer outra pergunta?}

# I don't have time right now. I have to go.
{217}{}{Eu não tenho tempo agora. Tenho que ir.}

# Welcome to the guild!
{218}{}{Receba as boas vindas da associação!}

# Great, I have questions!
{219}{}{Legal, eu tenho perguntas!}

# OK, thanks. I'll be back.
{220}{}{OK, valeu. Eu voltarei.}

# Vault 13? No. Wait... I think Vic's from Vault City. Maybe that's it.
{221}{}{Vault 13? Não. Espera... Acho que Vic é de uma Vault City. Deve ser isso.}

# Yes, where is it?
{222}{}{Sim, onde fica?}

# No. I have another question though.
{223}{}{Não. Mas eu tenho outra pergunta.}

# No, never mind.
{224}{}{Não, deixa quieto.}

# We sell most of our slaves to Vault City and New Reno. New Reno is
 south east of here and most of the Den trades with it.
{225}{}{Nós vendemos a maioria dos escravos para Vault City e New Reno. New Reno fica 
 ao sudeste daqui e a maioria de Den tem negócios por lá.}
 
# Where is Vault City?
{226}{}{Onde fica Vault City?}

# I have more questions.
{227}{}{Eu tenho mais perguntas.}

# Thanks, gotta go.
{228}{}{Valeu, preciso ir.}

# Vault City is east of here, and a little south. Vic's from there.
{229}{}{Vault City fica para o leste daqui e um pouco para o sul. Vic veio de lá.}

# I have more questions.
{230}{}{Eu tenho mais perguntas.}

# Thanks; gotta go.
{231}{}{Valeu; tenho que ir.}

# Hmm, looks like a healthy slave. I'll give you [x] coins.

# Hmm, looks like a healthy slave. I'll give you 
{232}{}{Hmm, parece um escravo saudável. Vou te dar }

#  coins.
{233}{}{ moedas.}

# OK! It's a deal.
{234}{}{OK! Negócio fechado.}

# Uh, never mind.
{235}{}{Ah, deixa quieto.}

# No way! I want double!
{236}{}{De jeito nenhum! Eu quero o dobro!}

# You drive a hard bargain. Here is your money!
{237}{}{Você é bom de barganha. Aqui está seu dinheiro!}

# Thanks. I have some more questions.
{238}{}{Valeu. Eu tenho mais algumas perguntas.}

# Thanks. Bye.
{239}{}{Valeu. Adeus.}

# Anything else?
{240}{}{Mais alguma coisa?}

# Yes, I have a question.
{241}{}{Sim, eu tenho uma pergunta.}

# Nope. Bye.
{242}{}{Não. Adeus.}

# Which "friend" are you selling?
{243}{}{Qual "amigo" você está vendendo?}

# Um, never mind.
{244}{}{Ah, deixa quieto.}

# Interesting. I'll give you [x] coins.

# Interesting. I'll give you 
{245}{}{Interessante. Vou te dar }

#  coins.
{246}{}{ moedas.}

# Sold!
{247}{}{Vendido!}

# No, thanks.
{248}{}{Não, obrigado.}

# I want more money than that!
{249}{}{Eu quero mais dinheiro que isso!}

# Alright, I'll give you [x] but no more!

# Alright, I'll give you 
{250}{}{Tá bom, eu vou te dar }

#  but no more!
{251}{}{ e nada mais!}

# Sold!
{252}{}{Vendido!}

# Not good enough.
{253}{}{Não é bom o bastante.}

# That's way too little. I'm leaving.
{254}{}{Isso é muito pouco. Eu vou embora.}

# What do you want with Vic? He's my property now. He shouldn't have fucked with me.
{255}{}{O que você quer com o Vic? Ele é minha propriedade agora. Ele não devia ter mexido comigo.}

# I'd like to buy him.
{256}{}{Eu quero comprá-lo.}

# Why are you keeping him here?
{257}{}{Por que você está o mantendo aqui?}

# Nothing. Never mind.
{258}{}{Nada. Esquece.}

# He is not for sale, yet.
{259}{}{Ele ainda não está a venda.}

# Why not?
{260}{}{Por que não?}

# Oh, okay.
{261}{}{Ah, ok.}

# He will cost $2000.
{262}{}{Ele vai lhe custar $2000.}

# Here is your money.
{263}{}{Aqui está seu dinheiro.}

# That's a lot. Maybe later.
{264}{}{Isso é muito. Talvez depois.}

# The cost is $1000.
{265}{}{Faço por #1000.}

# Here is your money.
{266}{}{Aqui está seu dinheiro.}

# Don't have that much yet. Bye.
{267}{}{Ainda não tenho tudo isso. Adeus.}

# Our radio is broken and he's in charge of fixing it.
{268}{}{Nosso rádio quebrou e ele esta encarregado de consertar.}

# I see.
{269}{}{Entendi.}

# You haven't got the money!
{270}{}{Você não tem o dinheiro!}

# Too bad for me. Can I ask you a question?
{271}{}{Que pena. Posso fazer uma pergunta?}

# Sorry, I'll come back.
{272}{}{Desculpe, eu volto depois.}

# How dare you return after abandoning your brothers during a Slave Run! Guards! Attack!
{307}{}{Como ousa voltar aqui depois de abandonar seus irmãos durante uma Caça aos Escravos! Guardas! Atacar!}

# [done]
{308}{}{[pronto]}

# Excellent! It may take a few days for you to travel there and back. Are you ready to leave now?
{309}{}{Excelente! Deve levar alguns dias até você fazer a viagem de ida e volta. Pode ir agora?}

# No. I'll come back.
{310}{}{Não. Eu volto depois.}

# Yes, I'm ready. Let's go.
{311}{}{Sim, já me preparei. Vamos.}

# Ah, you are back from the Slave run. Let's see how you did...
{312}{}{Oh, você voltou de uma caça aos escravos. Vamos ver como se saiu...}

# [more]
{313}{}{[mais]}

# [more]
{314}{}{[mais]}

# You killed potential slaves! A dead man brings us no income! Only kill the ones that are a threat,
 the others are of no threat.
{315}{}{Você matou escravos em potencial! Um homem morto não nos da lucro! Mate apenas os que forem uma ameaça,
 os outros não oferecem perigo.}
 
# [more]
{316}{}{[mais]}

# You returned no slaves at all! What the hell is wrong with you? We're trying to make money here,
 not lose it.
{317}{}{Você não pegou nenhum escravo! O que diabos há de errado com você? Estamos tentando ganhar dinheiro aqui,
 não perder.}
 
# [more]
{318}{}{[mais]}

# Overall, you did well this Run. Keep up the good work and I might keep you around a while.
{319}{}{No geral, você foi bem nessa caçada. Continue com o bom trabalho e eu vou te manter por aqui.}

# Thank you. I will.
{320}{}{Obrigado. Eu irei.}

# I don't know if I like this too much.
{321}{}{Eu não tenho certeza se gosto disso.}

# You need to improve your enslavement technique.
{322}{}{Você precisa melhorar sua técnica em escravatura.}

# I will try.
{323}{}{Vou tentar.}

# I apologize for my poor performance.
{324}{}{Me desculpe pelo fraco desempenho.}

# I think I'm good enough.
{325}{}{Acho que mandei bem o bastante.}

# Damn it! You did terribly in this Run. Are you trying to ruin me? Be more careful next time.
 You don't need to kill them all! Just kill off the hostile ones. Leave the unarmed ones for collection.
{326}{}{Merda! Você foi horrível nessa caçada. Está tentando me arruinar? Tenha mais cuidado da próxima vez.
 Não precisa matar todos eles! Apenas mate os hostis. Traga os desarmados para nossa coleção.}
 
# I'm sorry, Metzger.
{327}{}{Me desculpe, Metzger.}

# Hey, it's tough work to be a Slaver!
{328}{}{Ei, é difícil ser um traficante de escravos!}

# I'd like to see you do better.
{329}{}{Quero ver fazer melhor que isso.}

# I'd like to go on a slave run.
{330}{}{Eu gostaria de ir em uma caçada aos escravos.}

# Damn it! I hate losing any guild member on a Run. Try to watch each other's back!
{331}{}{Merda! Eu odeio perder um membro da associação em uma caçada. Tente cuidar de seus companheiros!}

# Overall, you did well this Run. Here is $
{332}{}{No geral, você foi bem nessa caçada. Aqui estão seus $}

#  as an incentive for you to keep up the good work.
{333}{}{ como incentivo para continuar com o bom trabalho.}