#You see a guard.
{100}{}{Você vê um guarda.}

#The guard is guarding the old church.
{150}{}{O guarda está vigiando a antiga igreja.}
#[TALK]!
{151}{}{[CONVERSE]!}
#How dare you show your face again!
{152}{}{Como se atreve a dar as caras de novo!}
#[Done]!
{153}{}{[Feito]!}
#Ho! No one enters the Family Wright warehouse at night!
{154}{}{Opa! Ninguém entra no armazém da Família Wright à noite!}
#Well, Mr. Wright himself sent me on an errand. If you don’t know about it, too bad.
{155}{}{Bem, o próprio Sr. Wright me enviou para um afazer. Se você não sabe sobre isso, problema seu.}
#I’ll come back tomorrow.
{156}{}{Volto amanhã.}
#I need to get in there now.
{157}{}{Preciso entrar lá agora.}
#[Looking nervous] Sorry...I didn’t know. Do you have any papers?
{158}{}{[Parecendo nervoso] Desculpe...não sabia. Você tem algum documento de autorização?}
#Please! Can you even read?
{159}{}{Por favor! Você pelo menos sabe ler?}
#No, he didn’t give me any.
{160}{}{Não, ele não me deu nenhuma.}
#I left them back with my guard. I’ll go fetch them.
{161}{}{Deixei com meu guarda. Vou buscá-lo.}
#You cannot get in without papers.
{162}{}{Você não pode entrar sem documentos.}
#Here’s my authorization! Attack!
{163}{}{Aqui está minha autorização! Atacar!}
#I’ll come back.
{164}{}{Eu voltarei.}
#[Embarrassed] No...um...alright, just go on in...
{165}{}{[Embaraçado] Não...hã...tudo bem, pode entrar...}
#Thank you.
{166}{}{Obrigado.}
#That’s more like it.
{167}{}{Assim que se fala.}
#What do you people want?
{168}{}{O que vocês querem?}
#We need to go inside.
{169}{}{Temos de entrar aeh.}
#We were sent here by the boss.
{170}{}{Fomos enviados aqui pelo chefe.}
#I would have heard if a group was sent here. Be off!
{171}{}{Eu estaria sabendo se um grupo fosse enviado para cá. Cai fora!}
#Off with your head!
{172}{}{Fora com sua cabeça!}
#OK, OK; we’re going.
{173}{}{OK, OK; estamos indo.}
#What is your business here?
{174}{}{Qual seu negócio aqui?}
#I need to go inside.
{175}{}{Preciso entrar aeh.}
#I’ve been sent on official business by the boss. Stand aside!
{176}{}{Fui enviado em missão oficial pelo patrão. Afaste-se!}
#Removing your head from your shoulders.
{177}{}{Separando sua cabeça dos ombros.}
#Sorry, wrong place.
{178}{}{Sinto muito, se enganou de lugar.}
#Hello again. You can go on in.
{179}{}{Olá de novo. Você pode entrar.}
#Thanks.
{180}{}{Obrigado.}
#Hey, get the hell away from the door!
{181}{}{Ei, se afaste já dessa porta!}
#Don't touch the door again unless you want trouble.
{182}{}{Não toque nesta porta de novo, a menos que queira ter problemas.}
#I see you touch that door again, you're gonna get a bullet in the head.
{183}{}{Se eu ver você tocar nesta porta de novo, vai levar uma bala na cabeça.}
#Hey, what do you think you're doing?
{184}{}{Ei, o que pensa que está fazendo?}
#I've had enough of you.
{185}{}{Você já me encheu.}
#Sorry; I can let you in, but your friends are gonna have to wait outside.
{186}{}{Sinto; Posso te deixar entrar, mas seus amigos vão ter que esperar lá fora.}
#Only one of you are allowed in at a time.
{187}{}{Apenas um de cada vez de vocês está autorizado entrar.}

#Good evening.
{200}{}{Boa noite.}
#Good afternoon.
{201}{}{Boa tarde.}
#Good morning.
{202}{}{Bom dia.}
#Just finish up your business, thank you.
{203}{}{Apenas termine seu serviço, obrigado.}

#You know, pal, I've had enough of your shit!
{250}{}{Sabe, colega, já me enchi de sua babozeira!}
#You know, bitch, I've had enough of your shit!
{251}{}{Sabe, puta, já me enchi da sua babozeira!}
#[END]!
{252}{}{[Fim]!}
