#You see a drug dealer.
{100}{}{Você vê um traficante de drogas.}
#You see a drug dealer.
{101}{}{Você vê um traficante de drogas.}
#If you are looking to deal, I got the stuff.
{102}{}{Se você está procurando, eu tenho o material.}
#Sure, show me.
{103}{}{Claro, me mostra.}
#Maybe some other time.
{104}{}{Talvez em outro momento.}
#Find what you need?
{105}{}{Encontrou o que você precisa?}
#Thanks. Goodbye.
{106}{}{Obrigado. Adeus}


#You see a thug.
{200}{}{Você vê um bandido.}
#You see a thug.
{201}{}{Você vê um bandido.}
#I'm here for protection. Talk to the dealer if you wanna buy.
{202}{}{Estou aqui para proteção. Fale com o vendedor, se você quer comprar.}
