# 0. Look
#You see a citizen of the Den.
{100}{}{Você vê um cidadão de Den.}
#You see Derek.
{101}{}{Você vê Derek.}

#He looks quite agile.
{150}{}{Ele parece bem agitado.}

# 1.  Night (From Where to go)
#Beat it.
{200}{}{Cai fora.}
#I'm too tired to talk.
{201}{}{Estou muito cansado para conversar.}
#Get out of my place.
{202}{}{Saia do meu lugar.}
#Get your own place to sleep.
{203}{}{Consiga seu próprio lugar para dormir.}
#Stop bothering me.
{204}{}{Pare de me incomodar.}
#I'm bushed.
{205}{}{Estou exausto.}
#Doh!
{206}{}{Doh!}
#Hey!, what are you doing here?
{207}{}{Ei, o que está fazendo aqui?}

# 2. Floats before Quest 2 (From Where to go)
#Stay away from Metzger, tribal.
{220}{}{Fique longe de Metzger, tribal.}
#Why is it always so damn hot?
{221}{}{Por que é sempre tão quente?}
#Why do we live in the desert?
{222}{}{Por que vivemos no deserto?}
#I'm a good cook.
{223}{}{Sou um bom cozinheiro.}
#I'm going to open my own restaurant someday.
{224}{}{Vou abrir meu próprio restaurante um dia.}
#I wish I had a real kitchen.
{225}{}{Gostaria de ter uma cozinha de verdade.}
#Why am I always getting the short end of life?
{226}{}{Por que sempre fico com a parte ruim de tudo?}
#People are always screwing me.
{227}{}{As pessoas sempre me prejudicam.}
#Fred's a dreamer - master plan, my ass.
{228}{}{Fred é um sonhador - plano mestre, como sempre uma bosta.}

# 3. Floats after Job 2, and having talk to him (From Where to go)
#Shhhh! They're everywhere.
{240}{}{Shhhh! Estão por toda parte.}
#Make them stop!
{241}{}{Faça-os parar!}
#So you found that damn book?
{242}{}{Então, você achou esse livro maldito?}
#I don't know why Becky won't hire me.
{243}{}{Não sei por que Becky não me contrata.}
#I will not go insane!
{244}{}{Não vou enlouquecer!}
#I got my quarters!
{245}{}{Tenho minha grana!}
#They come out at night, mostly.
{246}{}{Eles saem à noite, principalmente.}
#I like potatoes!
{247}{}{Gosto de batatas!}
#Don't walk on the green stuff without boots!
{248}{}{Não pise na coisa verde sem botas!}
#Just turn it inside out.
{249}{}{Basta virá-lo do avesso.}
#Oh, my head hurts really bad now.
{250}{}{Oh, estou mesmo com muita dor de cabeça agora.}
#I'm a grandmaster cook!
{251}{}{Sou um grande mestre cozinheiro!}
#I would never poison a newbie's food.
{252}{}{Nunca iria envenenar a comida de um novato.}

# 4. 1st Time, On Job (From Where to go)
#Hey you looking for some freshly baked bread?
{260}{}{Ei está procurando um pouco de pão recém-assado?}
#Yes.
{261}{}{Sim.}
#I'm looking for Becky's book.
{262}{}{Estou procurando o livro de Becky.}
#No, bye.
{263}{}{Não, tchau.}

# 5. Next Times (From Where to go)
#Oh, hi again.
{270}{}{Oh, oi de novo.}
#So where's Becky's book?
{271}{}{Então, onde está o livro de Becky?}
#Hey!, how about some of that bread?
{272}{}{Ei, que tal um pouco desse pão?}
#Bye.
{273}{}{Tchau.}

# 6. Bread (From 4)
#Ha! So am I. Have I told you what a great cook I am? Becky wont' hire me for some reason. She says I'm unstable.
{280}{}{Hã! Eu também. Já te disse que grande cozinheiro sou? Becky não vai me contratar por algum motivo. Ela diz que sou instável.}
#She's probably right.
{281}{}{Provavelmente ela tenha razão.}
#I'm looking for Becky's book.
{282}{}{Estou procurando o livro de Becky.}
#That's great. I've uh… got to go.
{283}{}{Isso é ótimo. Eu hã... tenho que ir.}

# 7. She's right (From 6)
#What? You! Screw you buddy! I'm not… Ow! Fuck.
{290}{}{O quê? Você! Foda-se amigo! Não sou... Ah! Foda-se.}
#What? You! Screw you lady! I'm not… Ow! Fuck.
{291}{}{O quê? Você! Foda-se senhora! Não sou... Ah! Foda-se.}
#Damn.
{292}{}{Droga.}
#Nuf Said.
{293}{}{Nada mais a dizer.}

# 8. Looking for Book (From 4-6)
#Oh yeah. I didn't like it. Too much kissing. I threw it in the corner of that building... no that building... no... was it a building? Maybe I dropped it somewhere else... or did I throw it? Ow! My head!
{300}{}{Oh sim. Não gostei disso. Muita beijação. Joguei no canto daquele prédio... não desse prédio... não... será que era um edifício? Talvez derrubei em outro lugar... ou joguei por aeh? Ai! Minha cabeça!}
#Book? Oh, that book. Who sent you? I'm not sure if that's the proper side. Don't forget the tissue.
{301}{}{Livro? Oh, esse livro. Quem te enviou? Não tenho certeza se esse é o lado certo. Não se esqueça do papel higiênico.}
#I can't! They're… oh crap… Do you have the cheese? Hide!
{302}{}{Não posso! Eles... oh merda... Você tem queijo? Escondam-se!}
#Hey! Not my problem. What was I supposed to do? Fight them? Little green men, big pointy teeth! Fuck! Ouch! Stop that!
{303}{}{Ei! Não é problema meu. O que deveria fazer? Combatê-los? Homenzinhos verdes, com grandes dentes afiados! Porra! Ai! Pare com isso!}
#My head hurts! What... who said that?
{304}{}{Estou com dor de cabeça! O quê... quem disse isso?}
#That helps a lot.
{305}{}{Isso ajuda muito.}
#Uh.
{306}{}{Uh.}

# 9. More bread (From 5)
#What? Are you mocking me! Screw you! I'm not unstable! I can cook! I don't have voices in my head!
{310}{}{O quê? Está caçoando de mim! Vai se fuder! Não sou instável! Sei cozinhar! Não ouço vozes na minha cabeça!}
#I'm gonna- shit! Fuck! Damn it! Stop that. Be quiet! What?... Okay.
{311}{}{Vou te- merda! Porra! Caramba! Pare com isso. Fique quieto! O quê?... Tah bom.}
#Hey! Sto- do... fuck.
{312}{}{Ei! Pare- de fazer... filha da p.}
#Bye.
{313}{}{Tchau.}
#Nothing.
{314}{}{Nada.}

# 10. Dumb Floats (From Where to go)
#Hey! Get away from me!
{320}{}{Ei! Fique longe de mim!}
#Don't touch me!
{321}{}{Não me toque!}
