# 0. Look

# You see a thin, greasy looking, man.
{100}{}{Você avista um homem magro e seboso.}

# You see Flick, giving his groin a thorough scratching.
{150}{}{Você vê Flick, dando uma bela coçada no saco.}

# You see an unclean fellow with a nasty facial-twitch.
{151}{}{Você vê um indivíduo sujo, com um rosto asqueroso.}

# 1. Low Intelligence (WtG)

# Get outta heeya, you dumb-ass.
{200}{}{Mah cai fora, culo.}

# Hey meatball! Yeah, you. Get outta heeya.
{201}{}{Ei, grasso! É, tu. Cai fora daqui, capisci?}

# You dumb or sumpin'?
{202}{}{Tu é culo ou o quê?}

# Whatchur problem, eh?
{203}{}{Mah qual tu pobrema, ein?}

# Get the hell outta heeya.
{204}{}{Dá o fora daqui, capisci!}

# 2. Hello (WtG, 3,4,6,7,911,12,13)

# Hey der, I'm Flick. What the fuck do you want, huh?
{220}{}{Oi, it's a me! Flick! O que caralho tu quer, ein?}

# Now what? You wastin' my time heeya.
{221}{}{Que foi agora? Tu está tomando meu tempo, capisci.}

# What's with the wacky accent, Flick?
{222}{}{Que sotaque bizarro é esse, Flick?}

# What the hell do you do here?
{223}{}{O quê diabos você faz aqui?}

# I'm looking for a Vault - oh yeah, and some trader named Vic, too. Know where they might be?
{224}{}{Estou procurando por uma Vault - ah é, e um comerciando chamado Vic, também. Sabe onde posso encontrá-los?}

# I'd like to trade with you.
{225}{}{Eu gostaria de negociar com você.}

# 3. After Barter (2,3,9)

# That 'bout do it for ya, pal?
{240}{}{Negócio fechado, amico?} 

# Actually I'd like to take another look at your goods if I may.
{241}{}{Na verdade, eu quero dar mais uma olhada na sua mercadoria.}

# Actually, I'd like to ask you a question.
{242}{}{Na verdade, eu quero te fazer uma pergunta.}

# That did it. See you around Flick.
{243}{}{É só isso. A gente se vê, Flick.}

# 4. What do you do here (2)

# I'm a fuckin' provider, waddya think? I'm like a good Samurai-itan guy.
{260}{}{Eu sou um provedor, cazzo. Que tu acha? Sou praticamente um bom samuraitano.} 

# Say what?
{261}{}{Um o quê?}

# Yeah, uh, well…let me ask you something else.
{262}{}{É, hã, bem... Deixa eu perguntar outra coisa.}

# Uh, oh. OK. Goodbye, Flick.
{263}{}{Oh não. OK. Adeus, Flick.}

# 5. You do what? (4)

# I provide fer them little paisanos.
{280}{}{Eu trago providencias para os pequenos bambinos.}

# You provide little pianos?
{281}{}{Você é um provedor de bombinhas?}

# 6. Pianos?(5)

# Pai-san-o, you know, the kids. My kids.
{290}{}{Bam-bi-nos, crianças, capisci? Minhas crianças.}

# Your kids?
{291}{}{Suas crianças?}

# Well, I'm not really interested in music lessons for children. Let me ask you about something else.
{292}{}{Bem, não estou muito interessado em crianças explosivas. Deixa eu perguntar outra coisa.}

# 7. Your kids? (6)

# Yeah, well they work for me. They bring me things. Little things. You know.
{300}{}{Eco, bem, eles trabalham para mim. Me trazem coisas. Pequenas coisas. Tu capisca.}

# Uh, no.
{301}{}{É... não.}

# Oh, OK. Let me ask you something else then.
{302}{}{Ah, ok. Deixa eu perguntar outra coisa então.}

# Ah, I see. Well, I don't want to cramp your, uh, style. Goodbye.
{303}{}{Ah, entendi. Bom, eu não quero meter o bedelho no seu, hm, estilo de vida. Adeus.}

# 8. They bring you things? (7)

# They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.
{315}{}{Eles me trazem as coisas que encontram. Coisas bem pequenas. Coisas que ninguém está usando. Em troca, eu cuido deles.}

# Sounds like a nice arrangement.
{316}{}{Parece uma boa parceria.}

# 9. Nice arrangement (8)

# (Flick shrugs) I get by OK.
{325}{}{(Flick dá de ombros) Dá pra viver.}

# Let me ask you about something else then.
{326}{}{Deixa eu perguntar outra coisa então.}

# They must have brought you some real bargains. Let's see what you've got.
{327}{}{Eles devem ter trazido uma boa mercadoria. Deixe me ver o que você tem.}

# Just checking. Well, goodbye Flick
{328}{}{Só estava olhando. Até mais, Flick.}

# 10. Wacky accent? (2)

# What you talkin' about? You think I'm a fucking stupid pirla? Some dumb filio di puttana? You think I'm some kinda clown? Am I here to amuse you, is that it?
{340}{}{Mah quê tu quer dizer? Tu acha que sou um estúpido? Um filio di puttana burro? Acha que sou um maledetto palhaço? Quê sou uma piada, é vero?} 

# Uh, no. Sorry, I was just curious. Let me ask you about something else.
{341}{}{Oh, nada disso. Desculpa, só tive curiosidade. Deixa eu perguntar outra coisa.}

# Yeah, that's right, shithead. And nothing's going to amuse me more than your death-throes.
{342}{}{É isso aí, seu bosta. E nada vai me divertir mais que ouvir você gritar enquanto morre.}

# Well, if you're going to get all huffy about it, I'm leaving.
{343}{}{Bom, se você vai fazer um escândalo por causa disso, eu vou embora.}

# 11. Vic & Vault (2)

# Vault huh? Maybe Momma knows about that, 'cause I don't. But that Vic guy - him I know. Metzger's got that porca pistola.
{360}{}{Vaul eh? Talvez a Mama saiba algo sobre isso. porque io no sei. Mas esse Vic - eu conheço. Metzger pegou esse porca pistola.}

# Vic? Ain't that him with you? You biota. But Momma, her I know.
{361}{}{Vic? Não é ele que está com tu? Culo. Mas Mama, ela io conheço.}

# Who's Metzger?
{362}{}{Quem é Metzger?}

# Who's Momma?
{363}{}{Quem é Mama?}

# Thanks. Let me ask you something else.
{364}{}{Obrigado. Deixa eu perguntar outra coisa.}

# Thanks, that's all I need to know. Goodbye.
{365}{}{Obrigado, é tudo que eu precisava saber. Adeus.}

# 12. Who's Momma? (11,13)

# Momma runs a food place over in da East side a town. Just past the graveyard. Nice place, she got good pasta, Mama mia.
{380}{}{Mama é dona de um restaurante no lado direito da cidade. Logo após o cemitério. Lugar bom, ela tem um ótimo macarrone, Mama mia.}

# Thanks, What about that Metzger fellow that's got Vic?
{381}{}{Obrigado. E esse sujeito chamado Metzger que pegou o Vic?}

# Thanks. Let me ask you something else.
{382}{}{Obrigado. Deixa eu perguntar outra coisa.}

# Thanks, that's all I need to know. Goodbye.
{383}{}{Obrigado, é tudo que eu precisava saber. Adeus.}

# 13. Who's Metzger? (11,12)

# That's right. Metzger, that stronzo, he's dead. I don't know what happen to Vic.
{400}{}{Eco. Metzger, quelo stronzo, morreu. Não sei o que aconteceu com o Vic.}

# That Metzger, he's a real rompiballe, that one. Runs the Slaver's Guild. East side of town, just north of Momma's. Anyhow, he got Vic, I know.
{401}{}{Questo Metzger, ele é um rompiballe, maledetto. Dono da Associação de Escravistas. Lado direito da cidade, logo acima da Mama. Ele pegou o Vic, pelo que sei.}

# Thanks, now what about Momma?
{402}{}{Obrigado, mas quem é Mama?}

# Thanks. Let me ask you something else.
{403}{}{Obrigado. Deixa eu perguntar outra coisa.}

# Thanks, that's all I need to know. Goodbye.
{404}{}{Obrigado, é tudo que eu precisava saber. Adeus.}


#killap - expansion

# Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with his presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.
{410}{}{Mah puttana merda, olha quem voltou. O bom samaritano "salvador das criancinhas" decidiu me agraciar com sua presença.
 Sabe, eu sou um bom samuraitano também -- sendo o provedor dos bambinos e tudo. Ou era, até tu aparecer e transformar a ideia do orfanato em 
 realidade, cazzo.}
 
# Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with her presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.
{411}{}{Mah puttana merda, olha quem voltou. A boa samaritana "salvadora das criancinhas" decidiu me agraciar com sua presença.
 Sabe, eu sou um bom samuraitano também -- sendo o provedor dos bambinos e tudo. Ou era, até tu aparecer e transformar a ideia do orfanato em 
 realidade, cazzo.}
 
# You provide little pianos?
{412}{}{Você é um provedor de bombinhas?}

# You sound like you don't like the fact that the children are no longer roaming the streets.
{413}{}{Isso soa como se você não gostasse do fato das crianças não viverem mais nas ruas.}

# Hey, don't get me wrong. Life on the street is tough fer them kids, but it's the end of our little arrangement that gets me down.
{420}{}{Ei, não me entenda errado. A vida nas ruas é difícil para os bambinos, mas é o fim de nossa pareceria que io lamento.}

# What arrangement?
{421}{}{Que parceria?}

# You mean them pickpocketing from people and bringing the items to you to sell.
{422}{}{Você está falando das coisas que eles roubam das pessoas para você vender.}

# Don't you get smart with me asshole. The kids bring me items they *find.* I don't know where they get them and frankly, I don't give a fuck.
{430}{}{Não dê uma de anjinho, seu monte de estrume. As crianças me davam coisas que *achavam*. Eu não sei onde elas conseguiam, e não ligo para essa porra.}

# Right.
{431}{}{Tá certo.}

# You're full of it. I'm sick of skum like you who use people for their own benefit. Time to die!
{432}{}{Você é cheio de si. Eu já cansei de gente como você que usa outras pessoas para o próprio benefício. Morra!}

# Pai-san-o, you know, the kids. My kids.
{440}{}{Bam-bi-nos, crianças, capisci? Minhas crianças.}

# And you have an arrangement with them?
{441}{}{E você tem uma parceria com elas?}

# They bring me stuff that they find. Little, little things. Stuff no one ain't usin' no more. In return, I takes care of 'em.
{450}{}{Eles me trazem as coisas que encontram. Coisas bem pequenas. Coisas que ninguém está usando. Em troca, eu cuido deles.}

# Sounds like a nice arrangement.
{451}{}{Parece uma boa parceria.}

# Yeah...business was good 'til you came along. See, yer little stunt's gonna cost me. My business is gonna suffer thanks to you.
 Because of this, I don't really like you too much. In fact, I fuckin' hate you. But, I'm a business man, so if you need to barter,
 get to it. If not, fuck off.
{460}{}{Eco... os negócios estavam indo bem antes de tu chegar. Suas intromissões vão me custar caro. Meu negócio vai sofrer muito graças a tu.
 Por isso, eu não gosto muito de tu. Na verdade, eu te odeio, cazzo. Mas eu sou um empreendedor, então se quiser negociar, ande com isso.
 Se não for, some daqui fili di puttana.}
 
# Alright, let's see what you have in stock then.
{461}{}{Ok, deixa eu ver sua mercadoria então.}

# I think I have all I need. Goodbye.
{462}{}{Acho que não preciso de mais nada. Adeus.}

# I think I'll stay...and kick your ass.
{463}{}{Acho que vou ficar... e chutar seu cu.}

# You again? You better be here to make some good trades, 'cause I'm getting real fuckin' sick of looking at you.
 In fact, I vomit in my mouth a little every time I see yer face. That's how much you disgust me. And if yer not here to
 trade, then I suggest you turn around and walk the fuck outta here.
{470}{}{Tu de novo? É melhor ter voltado aqui para comprar algo, porque io estou ficando puto só de olhar para tu.
 Na verdade, eu engulo um pouco de vomito na minha garganta toda vez que olho para sua cara. Eu tenho nojo de tu. E se não estiver
 aqui para negociar, então sugiro que de meia volta e de o fora daqui, capisci.}
 
# Let's trade.
{471}{}{Vamos negociar.}

# Just checking. Well, goodbye Flick.
{472}{}{Só olhando. Bom, até mais, Flick.}

# You done wastin' my time?
{480}{}{Já terminou de desperdiçar meu tempo?}

# Let me take another look.
{481}{}{Vou dar mais uma olhada.}

# That should do it. Goodbye Flick.
{482}{}{Acho que é o bastante. Até mais, Flick}
