#You see the owner of The Hole.
{100}{}{Você vê o dono da Caverna.}
#You see Frankie, owner of The Hole.
{101}{}{Você vê Frankie, proprietário da Caverna.}

#This appears to be the owner of this place.
{150}{}{Este parece ser o dono desse lugar.}
#This is Frankie. He owns this joint.
{151}{}{Este é Frankie. Ele é dono dessa taberna.}
#[TALK]!
{152}{}{[FALAR]!}
#I'm Frankie and yer standing in 'The Hole.' Best damn bar for
a hundred miles! Everyone crawls into The Hole when it's time to let loose. 
Now don't you be causing too much trouble, y'hear?}
153}{}{Sou Frankie e estou estabelecido na 'Caverna'. O melhor bar no raio de
cento e cinquenta km! Todos se reúnem na Caverna quando é hora de relaxar. 
E vê se não cause muitos problemas, entendeu?}
#I hear ya.
{154}{}{Entendi.}
#Yeah, okay. Whatever.
{155}{}{Sim, tudo bem. Que assim seja.}
#I see why you call this place "The Hole."!
{156}{}{Estou vendo por que chamam este lugar de "A Caverna".!}
#Huh?
{157}{}{Hein?}
#What's yer pleasure?
{158}{}{Em que posso te servir?}
#Whiskey.
{159}{}{Uísque.}
#Women.
{160}{}{Mulheres.}
#Men.
{161}{}{Homens.}
#Info.
{162}{}{Informações.}
#Nothing today. Bye.
{163}{}{Nada hoje. Tchau.}
#Wee wee.
{164}{}{Oba, oba.}
#Hey! You better shut your hole!
{165}{}{Ei! É melhor fechar sua boca!}
#Or what?
{166}{}{Ou o quê?}
#Just do your job and get me a drink.
{167}{}{Só faça seu trabalho e pegue uma bebida para mim.}
#I'll just leave instead.
{168}{}{Vou sair fora então.}
#Whiskey is $!
{169}{}{O uísque é $!}
# a shot.
{170}{}{ a dose.}
#Here's your money.
{171}{}{Aqui está seu dinheiro.}
#No way! That's too much!
{172}{}{De jeito nenhum! Está muito caro!}
#Why does your whiskey cost so much more than Becky's?
{173}{}{Por que o custo de seu Uísque é muito mais do que o de Becky?}
#No thanks.
{174}{}{Não, obrigado.}
#Anything else?
{175}{}{Algo mais?}
#Yes.
{176}{}{Sim.}
#Nope, thanks.
{177}{}{Nada, obrigado.}
#You don't have enough money! This ain't no charity!
{178}{}{Você não tem dinheiro suficiente! Isto aqui não é nenhuma caridade!}
#Oh, sorry. I'm low on funds.
{179}{}{Oh, desculpe. Estou com pouco dinheiro.}
#I'll come back.
{180}{}{Voltarei.}
#What do you want?
{181}{}{O que você quer?}
#Whiskey.
{182}{}{Uísque.}
#Nothing. I'm leaving.
{183}{}{Nada. Estou saindo.}
#Wahdo a peedee!
{184}{}{Hehehehe!}
#And stay out!
{185}{}{E fique por lá!}
#[EXIT]!
{186}{}{[Sair!}
#I don't want people like you in my place. Get out!
{187}{}{Não quero pessoas como você no meu recinto. Sai fora!}
#Alright, I'm going.
{188}{}{Tudo bem, estou indo.}
#Wah.
{189}{}{Wah.}
#Those New Reno families charge an arm and a leg for their booze. I don't know how she does it!
{190}{}{Essas famílias de Novo Reno cobram um braço e uma perna pelo seu álcool. Não sei como ela faz isso!}
#Well, you should try to find out.
{191}{}{Bem, você deve tentar descobrir.}
#I could find out.
{192}{}{Posso descobrir.}
#I know how she does it.
{193}{}{Eu sei como ela faz isso.}
#I'll just go buy whiskey from her.
{194}{}{Vou mesmo comprar uísque dela.}
#If you find out where she gets her booze, I'll pay you $100.
{195}{}{Se você descobrir onde ela consegue a bebida, Te pago $100.}
#OK, I'll find out.
{196}{}{Tudo bem, Vou descobrir.}
#Nope, not interested.
{197}{}{Não, não estou interessado.}
#So, how does Becky do it? How does she sell her booze so cheap?
{198}{}{Então, como Becky faz? Como ela vende sua bebida tão barata?}
#She has a still.
{199}{}{Ela tem uma destilaria.}
#I don't know yet. I'lld come back.
{200}{}{Não sei ainda. Vou voltar para investigar.}
#What? A still! Damn. Ei!, here's the $100, and I'll pay you $500 to destroy it. You can use my crowbar, in the back room over there. That'll do a number on her stupid little still!
{201}{}{O quê? Uma destilaria! Caramba. Ei!, aqui está os $100, e te pago $500 para destruí-lo. Você pode usar meu pé de cabra, que está na sala logo ali. Isso vai fazer um estrago em sua pequena destilaria estúpida!}
#I already did.
{202}{}{Eu já fiz.}
#OK, I'll destroy it.
{203}{}{Tudo bem, Vou destruí-la.}
#No way. That's too much. I got the information. You handle it.
{204}{}{De jeito nenhum. Está muito caro. Fiquei sabendo. Você é quem faz isso.}
#No, I have a better idea.
{205}{}{Não, Tenho uma idéia melhor.}
#So, is the still destroyed? Like I said, just use my crowbar on it. That'll really fuck it up fast.
{206}{}{Então, a destilaria foi destruída? Como eu disse, é só usar meu pé de cabra nela. Isso realmente vai acabar com tudo rápido.}
#Yes, it is.
{207}{}{Sim, vai.}
#I have a better idea.
{208}{}{Tenho uma idéia melhor.}
#Nope. I'll let you know when it is.
{209}{}{Não. Te aviso quando acontecer.}
#Then here's the $500. Thanks.
{210}{}{Então aqui estão os $500. Obrigado.}
#Nice doing business with you.
{211}{}{Foi bom fazer negócios com você.}
#You know, Frankie, she's just going to build another one.
{212}{}{Sabe, Frankie, ela vai simplesmente construir outra.}
#Thanks, bye.
{213}{}{Obrigado, adeus.}
#Damn! Well, in the mean time she'll have no booze.
{214}{}{Droga! Bem, nesse meio tempo, ela não vai ter nenhuma bebida.}
#Why fight her, Frankie? Join her.
{215}{}{Por que lutar contra ela, Frankie? Junte-se a ela.}
#Think. Where else can you get liquor?
{216}{}{Pense bem. Onde mais conseguir licor?}
#What do you mean?
{217}{}{O que quer dizer?}
#Buy liquor from her. It's cheaper than New Reno's, so you'll make more money, too.
{218}{}{Compre licor dela. É mais barato do que os de Novo Reno, assim vai ganhar mais dinheiro, também.}
#I don't want to do this.
{219}{}{Não quero fazer isso.}
#Never mind.
{220}{}{Não importa.}
#Look, I just want her still destroyed. Will you do it?
{221}{}{Olha, só quero a destilaria dela destruída. Vai fazer isso?}
#Alright, I will.
{222}{}{Tudo bem, vou.}
#No, I won't. Good bye.
{223}{}{Não, Não vou. Adeus.}
#Maybe you're right. I'll talk to her. Thanks.
{224}{}{Talvez tenha razão. Vou falar com ela. Obrigado.}
#Hey!, what are friends for?
{225}{}{Ei!, para que servem os amigos, néh?}
#Bye.
{226}{}{Tchau.}
#Information I do not have.
{227}{}{Informações, não tenho.}
#Really? How about why Becky's drinks are so much cheaper than yours?
{228}{}{Sério mesmo? Que tal o porquê das bebidas de Becky serem muito mais barata do que as suas?}
#I thought bartenders knew everything.
{229}{}{Pensei que butequeiros sabiam de tudo.}
#Then I'm in the wrong place. Bye.
{230}{}{Então, estou no lugar errado. Tchau.}
#Go talk to Sheila. Ei!, Sheila, you got a customer!
{231}{}{Vá falar com Sheila. Ei!, Sheila, você tem um cliente!}
#Wait, that's not what I want!
{232}{}{Espere, não é isso que quero!}
#Thanks. Bye.
{233}{}{Obrigado. Tchau.}
#Yeah, I bet. You must have the damnedest time getting men. Try your luck somewhere else, sister. I ain't into no charities.
{234}{}{Sim, aposto que sim. Você deve ter muito tempo para receber homens. Tente a sorte em outro lugar, irmã. Não estou em nenhuma instituição de caridade.}
#Fine! Something else then.
{235}{}{Tudo bem! Alguma outra coisa então?}
#Why, you little...
{236}{}{Mas, seu maldito...}
#I don't need this from you!
{237}{}{Não tenho porque suportar isso de você!}
#I have a room over there. You and I can use it.
{238}{}{Tenho um quarto logo ali. Podemos usá-lo.}
#OK.
{239}{}{Tudo bem.}
#No, I didn't mean that!
{240}{}{Não, Não quis dizer isso!}

#Neither were you.
{242}{}{Um homem, mas nem se fosse você.}
#I might have tried if you knew how to please a woman.
{243}{}{Poderia ter tentado se você soubesse como agradar uma mulher.}
#You were the best I ever had. Really. I mean that.
{244}{}{Você foi o melhor que já tive. Sério mesmo. Pode acreditar.}
#I hate to eat and run, but...
{245}{}{Odeio comer e sair correndo, mas...}
#Well, see you later.
{246}{}{Bem, te vejo mais tarde.}
#Bye.
{247}{}{Tchau.}

#Yeah, whatever. Just clean up after yourself this time, will ya?
{248}{}{Sim, seja lá o que for. Só limpe sua bagunça, desta vez, sim?}
#Hey!, everyone! Let's hear it for Billy. He's actually getting some!
{249}{}{Ei, pessoal! Vejam só o Billy. Conseguiu uma garota!}
#You need a mop?
{250}{}{Quer uma vassoura?}
#See ya in five.
{251}{}{Te vejo em cinco minutos.}
#Sheila! Watch the bar!
{252}{}{Sheila! Dê uma assistência no bar!}
#Hey!, Billy, get outta here!
{253}{}{Ei!, Billy, saia daqui!}
#Now where were we?
{254}{}{Agora, onde estávamos?}
#Where are you, woman?
{255}{}{Onde está você, mulher?}
#Would you get in here?
{256}{}{Poderia vir aqui?}
#Come on, baby.
{257}{}{Vamos lá, amor.}
#Follow me.
{258}{}{Me acompanhe.}
#No woman stands me up. Get the hell out!
{259}{}{Nenhuma me faz esperar. Caia fora!}
#Fine.
{260}{}{Tudo bem.}
#I forgot; I had something else I had to attend to right away. Please forgive me, baby.
{261}{}{Esqueci; que tinha outra coisa que precisava atender de imediato. Por favor, me perdoe, amor.}
#I decided I didn't want to sleep with your ugly ass after all.
{262}{}{Decidi que não queria dormir com sua bunda feia, afinal de contas.}
#Lucky for you, I'm a nice guy. Just don't pull that crap with me again.
{263}{}{Sorte sua, Sou um cara legal. Só não me apronte uma dessas de novo.}
#I won't, baby, I promise.
{264}{}{Não vou, amor, te prometo.}
#I'm gonna put my foot in your ass, woman!
{265}{}{Vou meter o pé na sua bunda, mulher!}
#No one talks to me like that! Die!
{266}{}{Ninguém fala assim comigo! Morra!}
#I've given you all the chances I'm gonna give ya. Now get out.
{267}{}{Eu te dei todas as chances que tinha para te dar. Agora sai fora.}
#You're not going in my back room with that trash!
{268}{}{Você não vai no meu quarto dos fundos com este lixo!}

#Hey!, I didn't fucking say I'd pay you to kill the bitch. Get the fuck out!
{300}{}{Ei!, Não te disse nada que te pagaria para matar a cadela. Cai fora!}

#Wow! Holy fuck. That was amazing.
{350}{}{Uau! Puta merda. Isso foi incrível.}
#Damn, you were pretty good baby.
{351}{}{Porra, você foi muito bem amor.}
#Thanks, it was fun. Now get out.
{352}{}{Obrigado, foi divertido. Agora saia.}
#You were, uhhh... Never mind, get out.
{353}{}{Você foi, uhhh... Não importa, saia.}
#Well, I've never had worse than that.
{354}{}{Bem, nunca tive pior do que isso.}

#You know baby, you might be hot and all, but you've got lots and lots to learn.
{400}{}{Sabe amor, você pode ser quente e tudo mais, mas você tem muitas e muitas coisas para aprender.}
#Baby, I do have work to do you know. I don't just stand around in this spot all day and do nothing.
 Well, okay, so what if I do? That's what I'm here to do.}
{410}{}{Amor, Tenho trabalho para fazer, sabe. Não tenho tempo para ficar neste lugar o dia todo e não fazer nada. 
Bem, tudo bem, então, e se eu fizer? Estou aqui para fazer isso.}

#Look, I just wanted her still destroyed and you do it. Now beat it.
{420}{}{Olha, eu só queria que a destilaria dela fosse destruída, e você fez isso. Agora, se manda.}
