# 0. Look
#You see a guard.
{100}{}{Você vê um guarda.}

#He's one of Tyler's guards.
{150}{}{Ele é um dos guardas de Tyler.}
# Seraph: Part of Haenlomal's gang fixes.
#She's one of Tyler's guards.
{151}{}{Ela é uma dos guardas de Tyler.}

# 1. Hostile
#You still alive?
{200}{}{Você ainda está vivo?}

# 2. CF: Gang 2 Defeated
#We showed them, didn't we?
{210}{}{Mostramos a eles, não é?}
#No one messes with us.
{211}{}{Ninguém mexe com a gente.}
#We kicked ass.
{212}{}{Nós arrebentamos.}
#About time we finished them off.
{213}{}{Já era hora de acabarmos com eles.}
#I can't forget the look on his face. It was great.
{214}{}{Não consigo esquecer o olhar em seu rosto. Foi ótimo.}
#I'm surprised Metzger didn't get pissed.
{215}{}{Estou surpreso de Metzger não ter ficado furioso.}
#I wonder why Metzger didn't step in.
{216}{}{Me pergunto por que Metzger não interferiu.}

# 3. ELSE
#I don't know why Metzger has us guard this shit.
{225}{}{Não sei por que Metzger quer que protegemos esta merda.}
#Who's going to try and steal this crap?
{226}{}{Quem vai tentar roubar essa porcaria?}
#This job is a cakewalk.
{227}{}{Este trabalho é uma moleza.}
#No one ever messes with us.
{228}{}{Ninguém se mete com a gente.}
#I think this stuff came from a Vault or something.
{229}{}{Acho que esta coisa veio de uma Caverna ou algo assim.}
#What are you looking for anyway?
{230}{}{O que você está procurando afinal?}
#There's nothing in here but us mice.
{231}{}{Não há nada aqui, mas nós ratos.}
#Don't waste your time, we've checked this stuff over a million times.
{232}{}{Não perca tempo, verificamos essa coisa mais de um milhão de vezes.}

# 4. SET
#Tonight's the night.
{233}{}{Hoje à noite é a noite.}
#I hate waiting.
{234}{}{Odeio esperar.}
#I'll pass up drinks for this anytime.
{235}{}{Vou passar as bebidas para isto a qualquer momento.}
#Is it time yet? I can hardly wait.
{236}{}{Não é hora ainda? Mal posso esperar.}
#I hope I get the first kill.
{237}{}{Espero ser o primeiro a matar.}
#Why did they wait until now to mess with us?
{238}{}{Por esperaram até agora para se meter com a gente?}
#This is going to be interesting.
{239}{}{Isso vai ser interessante.}

# 5. NOSHOW
#Too bad we didn't get any action after all.
{240}{}{Que pena que não recebemos nenhuma ação depois de tudo.}
#I wonder why they changed their minds.
{241}{}{Me pergunto por que mudaram de idéia.}
#All that waiting and nothing.
{242}{}{Esperamos tanto e nada.}
#So what ever happened to that trap you were going to help us set?
{243}{}{Então, o que aconteceu com essa emboscada que você ia nos ajudar a preparar?}
#What happened the other night?
{244}{}{O que aconteceu na noite passada?}
#Too bad those cowards chickened out. It would have been nice to finish them off.
{245}{}{Que pena que aqueles covardes se acovardaram. Teria sido legal acabar com eles.}
#Can't believe those bastards were going to try and ambush us.
{246}{}{Não posso acreditar que esses bastardos estavam tentando nos emboscar.}
