#You see a thug.
{100}{}{Você vê um bandido.}
#He's Tyler's friend.
{101}{}{Ele é amigo de Tyler.}

#You here to party?
{110}{}{Venho se divertir?}
#*hickup* Brews on me!
{111}{}{*hickup* Cervejas para mim!}
#Hooker's in the back if you want a ride.
{112}{}{Hooker está nos fundos se quiser dar um passeio.}

#Nobody fucks up a party when I am around.
{120}{}{Ninguém estraga a festa enquanto eu estiver por aqui.}

#We showed those fuckers...Ruining *hickup* a good party and all.
{130}{}{Descobrimos os bagunceiros...Estragando *hickup* uma boa festa e tudo mais.}
