# 0. Look
#You see a gangster.
{100}{}{Você vê um gangster.}

#He seems to be a member of Lara's gang.
{150}{}{Ele parece ser um membro da gangue de Lara.}
#She seems to be a member of Lara's gang.
{151}{}{Ela parece ser um membro da gangue de Lara.}

# 1. Hostile
#Wise guy.
{200}{}{Cara esperto.}
#There you are.
{201}{}{Aí está você.}
#Pay back.
{202}{}{Vai me pagar por isso.}
#Come here.
{203}{}{Venha aqui.}
#I'm not through with you.
{204}{}{Ainda não acabei com você.}
#Bitch.
{205}{}{Cadela.}

# 2. Metzger's Dead
#Wonder how long things will last around here with Metzger gone?
{225}{}{Fico imaginando quanto tempo as coisas vão durar por aqui com Metzger morto?
#So, Metzger's finally dead?
{226}{}{Então, Metzger finalmente está morto?}
#Was that your handiwork?
{227}{}{Foi obra sua?
#The Den'll never be the same again.
{228}{}{A Caverna nunca mais vai ser a mesma.}

# 3. 2Won
#I can't believe it, we actually beat them!
{240}{}{Não posso acreditar nisso, nós realmente vencemos eles!}
#Metzger's got to show us respect now.
{241}{}{Metzger tem que nos mostrar respeito agora.}
#We sure showed them.
{242}{}{Certeza que demos uma boa lição neles.}
#We gave 'em our own brand of justice.
{243}{}{Mostramos a eles nossa própria marca de justiça.}
#We couldn't have done it without you!
{244}{}{Não poderíamos ter feito isso sem você!}
#Thank you for your help!
{245}{}{Obrigado pela ajuda!}
#We did it!
{246}{}{Vencemos!}

# 4. NO SHOW
#You screwing around with us?
{247}{}{Está tentando nos prejudicar?}
#Better watch your step.
{248}{}{Melhor ver onde pisa.}
#Lara's the only reason we don't string you up right now.
{249}{}{Lara é a única razão por não te esfatiarmos agora mesmo.}
#What were you trying to pull?
{250}{}{O que você estava tentando fazer?}

# 5. COWARD
#Coward.
{251}{}{Covarde.}
#You make me sick.
{252}{}{Você me dá nojo.}
#Get lost.
{253}{}{Suma daqui.}
#Beat it.
{254}{}{Cai fora.}

# 6. FIGHT
#We're ready when you are.
{255}{}{Estamos prontos para quando quiser.}
#It's about time we pay them back.
{256}{}{Chegou a hora de darmos o troco neles.}
#I hate waiting.
{257}{}{Odeio esperar.}
#Let's go already.
{258}{}{Vamos já.}
#You ready yet?
{259}{}{Já está pronto?}
#Just let Lara know when it's time.
{260}{}{Assim que Lara saber do momento.}

# 7. NO
#You looking to join up?
{270}{}{Está querendo juntar-se a nós?}
#You must be here to see Lara.
{271}{}{Você deve estar aqui para falar com Lara.}
#How's it going?
{272}{}{Como tá indo?}
#Lara's the person you should be talking to.
{273}{}{É com Lara que deve falar.}
#Hi.
{274}{}{Oi.}
#You here to see Lara?
{275}{}{Está aqui para falar com Lara?}

# 8. Else
#Hi.
{300}{}{Oi.}
#How's it going?
{301}{}{Como tá indo?}
#Hope things are going good.
{302}{}{Espero que as coisas estejam indo bem.}
#So you might be able to help us out?
{303}{}{Então pode conseguir nos ajudar?}
#Good to see you.
{304}{}{Bom te ver.}
#We'll pay back Tyler soon…!
{305}{}{Faremos Tyler pagar por isso em breve...!}
#Any new developments?
{306}{}{Algumas novidades?}

# 9. Lara Dead
#Thanks for the help. Too bad about Lara.
{310}{}{Obrigado pela ajuda. Que pena sobre Lara.}
#We finally got em!
{311}{}{Finalmente derrotamos eles!}
#We couldn't have done this without you.
{312}{}{Não poderíamos ter feito isso sem você.}
#At least Lara went out in fight.
{313}{}{Pelo menos Lara morreu na luta.}
#I can't believe Lara didn't make it.
{314}{}{Não posso acreditar que Lara não conseguiu.}
#We sure showed Metzger who's best.
{315}{}{Com certeza mostramos a Metzger quem é o melhor.}
#Metzger's better off with us.
{316}{}{É melhor Metzger não se meter com a gente.}

# 10. Running to fight
#You said it!
{350}{}{Falou tudo!}
#They're dead meat!
{351}{}{São carne morta!}
#We're going to kick some serious ass!
{352}{}{Vamos fuder com a bunda de alguns figurões!}