# 0. Look
#You see a gambler.
{100}{}{Você vê um jogador.}
#This gambler seems to be doing extremely well.
{101}{}{Este jogador parece estar se dando muito bem.}
#He seems to be winning, but all his money is on the table.
{102}{}{Ele parece estar ganhando, mas todo seu dinheiro está sobre a mesa.}
#She seems to be winning, but all her money is on the table.
{103}{}{Ela parece estar a ganhar, mas todo seu dinheiro está sobre a mesa.}
#This person doesn't seem to be winning or losing.
{104}{}{Esta pessoa não parece estar ganhando ou perdendo.}
#This person hasn't won in a while.
{105}{}{Esta pessoa não ganha faz um bom tempo.}
#She looks like she's about to cry and seems to almost be out of money.
{106}{}{Parece que ela está prestes a chorar e parece estar quase sem dinheiro.}
#He looks very angry and seems to be losing big.
{107}{}{Ele parece muito irritado e parece estar perdendo muito.}

# 1. PC Killed Becky, NPC are still around (From Where to go)
#Don't hurt me!
{200}{}{Não me machuque!}
#Don't shoot!
{201}{}{Não atire!}
#I don't have any money!
{202}{}{Não tenho dinheiro!}
#Why did you have to kill poor Becky?
{203}{}{Por que tinha que matar a pobre Becky?}
#What did she ever do to you?
{204}{}{O que ela fez para você?}
#I didn't do anything!
{205}{}{Não fiz nada!}
#Please go, I won't tell.
{206}{}{Por favor, vái embora, não vou te contar.}

# 2. CF: Gambling (From Where to go)
#Yes! The dice love me!
{300}{}{Sim! Os dados me amam!}
#Oh, that was close.
{301}{}{Oh, essa passou perto.}
#Don't interrupt me. You'll ruin my winning streak.
{302}{}{Não me interrompa. Vai estragar minha maré de sorte.}
#I'm hot!
{303}{}{Estou com sorte!}
#Money, money, money!
{304}{}{Dinheiro, dinheiro, dinheiro!}
#I love this game!
{305}{}{Adoro este jogo!}
#You see that! Yes!
{306}{}{Viu só esta! Sim!}
#Roulette is the game to play!
{307}{}{Roleta é o jogo certo!}
#I'm doing pretty good, how about you?
{308}{}{Estou me dando muito bem, e você?}
#I'm doing better than normal.
{309}{}{Estou me saindo melhor que o normal.}
#Great place don't you think?
{310}{}{Ótimo lugar, não acha?}
#Becky's tables are better than New Reno.
{311}{}{A mesas de Becky são melhores do que as de New Reno.}
#You like this game? It's a lot of fun.
{312}{}{Gosta deste jogo? É muito divertido.}
#I haven't had a good roll in a while.
{313}{}{Não tenho uma boa rodada há algum tempo.}
#I need a good roll.
{314}{}{Preciso de uma boa rodada.}
#Well, at least I'm not losing.
{315}{}{Bem, pelo menos não estou perdendo.}
#I'm not going anywhere.
{316}{}{Não vou a lugar nenhum.}
#I'm just breaking even.
{317}{}{Estou apenas empatando.}
#You've got to play the numbers.
{318}{}{Você tem que jogar os números.}
#Just betting on the red or black is bad odds.
{319}{}{Apostar só no vermelho ou preto são péssimas chances.}
#The dice aren't behaving.
{320}{}{Os dados não estão se comportando.}
#I'm down and it's not looking good.
{321}{}{Estou quebrado e a coisa não parece que vai melhorar.}
#I hope you do better than I.
{322}{}{Espero que se dê melhor do que eu
#I've seen better days.
{323}{}{Já tive dias melhores.}
#I know how to play, honest.
{324}{}{Sei como jogar, honestamente.}
#The ball's not bouncing my way today.
{325}{}{A sorte não está para mim hoje.}
#Another payday lost for good.
{326}{}{Outro salário perdido para nada.}
#I'm almost broke!
{327}{}{Estou quase quebrado!}
#Damn it. This sucks.
{328}{}{Droga. Isso é péssimo.}
#Why does this always happen to me?
{329}{}{Por que isso sempre acontece comigo?}
#I can't win.
{330}{}{Não consigo vencer.}
#I hate this game.
{331}{}{Odeio este jogo.}

# 3. BGF: Becky Dead (From Where to go)
#Damn, Becky's was the only place to gamble around here!
{400}{}{Droga, Becky era o único lugar para apostar por aqui!}
#Stay away.
{401}{}{Fique longe.}
#Don't shoot!
{402}{}{Não atire!}
#Please leave us alone.
{403}{}{Por favor, deixe-nos em paz.}

# 4. BGF: Gambling (From Where to go)
#Don't stop there.
{500}{}{Não pára aí.}
#Keep moving.
{501}{}{Continue andando.}
#COME ON 7!
{502}{}{VAMOS LÁ 7!}
#Yes!
{503}{}{Sim!}
#Keep it coming!
{504}{}{Continue assim!}
#Becky! I'm going to take all your money today!
{505}{}{Becky! Vou tirar todo seu dinheiro hoje!}
#Woohoo! Winner!
{506}{}{Oba-oba! Vencedor!}
#Give me another good bounce!
{507}{}{Dê-me um outra boa sorte!}
#Yes!
{508}{}{Sim!}
#All right!
{509}{}{Tudo certo!}
#Again, let's see that again.
{510}{}{Mais uma vez, vamos ver isso de novo.}
#Come on.
{511}{}{Vamos.}
#That's what I wanted.
{512}{}{Isso que eu queria.}
#Almost.
{513}{}{Quase.}
#Not bad.
{514}{}{Nada mal.}
#How did that happen?
{515}{}{Como isso aconteceu?}
#Oops.
{516}{}{Ups.}
#No wammies, no wammies. Stop!
{517}{}{Continue, continue. Pare!}
#Well, the game lives up to its name.
{518}{}{Bem, o jogo faz jus ao seu nome.}
#I just need one big win.
{519}{}{Só preciso de uma grande vitória.}
#Figures!
{520}{}{Cifras!}
#Again?
{521}{}{De novo?}
#This isn't looking good.
{522}{}{Isso não está me parecendo boa coisa.}
#Roulette sucks!
{523}{}{Roulette é uma merda!}
#Becky! You're tables are killing me!
{524}{}{Becky! Suas mesas estão me matando!}
#Are those loaded dice or what?
{525}{}{Estes estão falsificados ou o quê?}
#Not again!
{526}{}{De novo não!}
#Why me?
{527}{}{Por que eu?}
#Damn it! So close!
{528}{}{Caramba! Tão perto!}
#Oh sweet sweet Jesus, KILL ME NOW!
{529}{}{Oh doce, doce Jesus, me mate agora!}
#I hate this game!
{530}{}{Odeio este jogo!}
#Damn! That was my number on the last spin!
{531}{}{Droga! Esse era meu número na última rodada!}
#Black again!?!?
{532}{}{Preto de novo!?!?}

# 5. CF: Hostile (From Where to go)
#Get away!
{600}{}{Sai fora!}
#Why did you do that?
{601}{}{Por que fez isso?}
#Get away!
{602}{}{Cai fora!}
#Stop it, I'm fragile.
{603}{}{Pare com isso, Sou frágil.}
#I wouldn't do that do you.
{604}{}{Não faria isso para você.}
