#You see a thug.
{100}{}{Você vê um bandido.}
#You see Joey.
{101}{}{Você vê Joey.}

#This guy doesn't look too friendly.
{150}{}{Esse cara não parece muito amigável.}
#[TALK]!
{151}{}{[FALAR]!}

# 1.
#I’m gonna cut you up, fucker!
{152}{}{Vou te cortar todo, filho da puta!}
#Yeah? Come on and try.
{153}{}{Ah vai, éh? Venha tentar.}
#Hey!, wait just one minute!
{154}{}{Ei, espere um minuto!}
#I’d think twice if I were you.
{155}{}{Pensaria duas vezes se fosse você.}

# 2.
#What do you want? Why shouldn’t I just kill you rather than listen to your bullshit after what you've done?
{156}{}{O que quer? Por que apenas não te mato, depois do que fez, em vez de ouvir sua babozeira?}
#I want to talk to you about a ghost that comes around here at night.
{157}{}{Gostaria de falar com você sobre um fantasma que vem por aqui à noite.}
#Did you take a locket from the haunted house?
{158}{}{Roubou um medalhão da casa mal-assombrada?}
#Never mind. I'll just kick your ass instead.
{159}{}{Não importa. Vou acabar com você, em vez disso.}
#Nothing. Just passing through.
{160}{}{Nada. Apenas de passagem.}

# 3.
#What the hell are you talking about?
{161}{}{De que diabos está falando?}
#Did you steal a locket from that haunted house?
{162}{}{Você roubou um medalhão daquela casa assombrada?}
#Nothing. Never mind.
{163}{}{Nada. Não importa.}
#Forget it. I’ll kill you now and sort out the pieces later.
{164}{}{Esqueça. Vou te matar agora e junto os pedacinhos mais tarde.}

# 4.
#I-I don’t know what you’re talking about.
{165}{}{N-não sei do que está falando.}
#Oh, I think you do! You stole a dead girl’s locket, and now her spirit can't rest.
{166}{}{Ah, eu acho que sabe! Você roubou o medalhão de uma menina morta, e agora o espírito dela não consegue descansar.}
#Then I’ll take it by force.
{167}{}{Então, vou pegar à força.}

# 5.
#T-That's f-fucking crazy! Y-you must h-have been r-really fucked up on some of Tubby's shit. I-I n-never s-saw no g-ghost w-when I stayed t-there- just a bad trip, wasn't f-fucking real.
{168}{}{I-isso é uma loucura! V-você deve t-ter realmente fodido com alguma porcaria de Tubby. N- nunca v-vi nenhum f-fantasma q-quando fiquei l-lá- apenas imaginação, que não era n-nada real.}
#Look, I’ll buy it from you.
{169}{}{Olha, Eu compro isso de você.}
#Give it to me or you can join her.
{170}{}{Dê isso para mim ou vai se juntar a ela.}
#If you don’t return it now, she’ll come after you. And she can’t be stopped.
{171}{}{Se você não devolver agora, ela vai vir atrás de você. E nada consegue detê-la.}

# 6.
#Huh? Oh yeah. Yeah. T-That's for damn sure. You're gonna have to fork over some bucks for sure. You ain't gettin' this for free! $50 or beat it!
{172}{}{Hein? Oh sim. Sim. I-Isso está bem claro. Você vai ter que clarear uma grana a mais, com certeza. Você não vai ficar com isso de graça! $50 ou some daqui!}
#Okay, here’s the money.
{173}{}{Ok, aqui está o dinheiro.}
#Take $20 and be happy I don’t just take it from you.
{174}{}{Tome $20 e fique grato, assim não tomei de você por nada.}
#Nah, I changed my mind. See ya.
{175}{}{Nah, mudei de idéia. Te vejo mais tarde.}
#Give it to me or I kill you for it.
{176}{}{Me dê isso ou te mato por isso.}

# 7.
#Here. Now just leave me alone.
{177}{}{Pegue. Agora só me deixe em paz.}
#Gladly.
{178}{}{Encantado.}
#Don’t let me catch you doing this again!
{179}{}{Não me deixe te pegar fazendo isso de novo!}

# 8.
#H-Ei! You don’t have the money! Get the hell out of here!
{180}{}{E-ei! Você não tem o dinheiro! Dê o fora daqui!}
#Oops. I’ll come back.
{181}{}{Oops. Eu voltarei.}
#Then I guess I have to kill you.
{182}{}{Então, acho que tenho que te matar.}

# 9.
#Hey. How's it goin'?
{183}{}{Ei. Como está indo?}
#OK, and you?
{184}{}{Tudo bem, e você?}
#Not so good.
{185}{}{Não tão bom.}
#Did you take a locket from that haunted house?
{186}{}{Você roubou um medalhão daquela casa assombrada?}
#What do you know about that ghost that comes around here at night?
{187}{}{O que você sabe sobre o fantasma que vem por aqui à noite?}

# 10.
#Hey!, man, I’m Joey. What're you doin' on my turf?
{188}{}{Ei, cara, Sou Joey. O que está fazendo no meu território?}
#Your turf? I don’t think so.
{189}{}{Seu território? Acho que não.}
#Maybe I’m looking for you.
{190}{}{Talvez esteja te procurando.}
#Just leaving. Bye.
{191}{}{Apenas saindo. Tchau.}
#Looking for some information.
{192}{}{Procurando alguma informação.}

# 11.
#Hey!, baby cakes. You looking for Joey? Here I am.
{193}{}{Ei!, boneco de fantoche. Está procurando Joey? Aqui estou.}
#No. Go away.
{194}{}{Não. Vá embora.}
#Maybe. What are you offering me?
{195}{}{Talvez. O que tem para me oferecer?}
#I want some information.
{196}{}{Gostaria de alguma informação.}
#No, sorry. I have to go now.
{197}{}{Não, desculpe. Tenho que ir agora.}

# 12.
#Hey!, I got some jet. It’s great stuff and brand new from Reno. Want some?
{198}{}{Ei, Tenho algo de Jet. É boa mercadoria e recém chegada de Reno. Quer um pouco?}
#No way!
{199}{}{De jeito nenhum!}
#How much?
{200}{}{Quanto?}
#No, I want information.
{201}{}{Não, quero informações.}
#I have to go. Bye.
{202}{}{Tenho que ir. Tchau.}

# 13.
#How about you and I get it on?
{203}{}{Que tal você e transarmos?}
#Okay.
{204}{}{Tudo bem.}
#Not if you were the last nonmutated man on the planet.
{205}{}{Nem se você fosse o último homem sem mutação do planeta.}
#Er, no... I don’t think so. I need something else.
{206}{}{Er, não... Acho que não. Preciso de algo mais.}

# 14.
#You’ll be coming back.
{207}{}{Você vai voltar.}
#Maybe.
{208}{}{Talvez.}
#Don’t count on it.
{209}{}{Não conte com isso.}
#Wait! Can I ask you something?
{210}{}{Espere! Posso te perguntar uma coisa?}

# 15.
#Nobody talks to me like that!
{211}{}{Ninguém fala assim comigo!}
#I just did. You do anything more than talk?
{212}{}{Eu fiz. Você faz algo mais do que falar?}
#Whatever. Are you selling anything or just making small talk?
{213}{}{Seja o que for. Está vendendo alguma coisa ou é apenas conversa fiada?}
#My apologies. I’m actually looking around and don’t know the area.
{214}{}{Minhas desculpas. Na verdade, estou olhando a região para conhecer a área.}

# 16.
#What do you want?
{215}{}{O que você quer?}
#I’m looking for a locket.
{216}{}{Estou procurando um medalhão.}
#I need to know more about that haunted house.
{217}{}{Preciso saber mais sobre aquela casa mal-assombrada.}
#What’s the deal with the old church and those guards?
{218}{}{Qual é o problema com a antiga igreja e aqueles guardas?}
#Nothing you can provide.
{219}{}{Nada que você pode oferecer.}
#Have you heard of Vault 13?
{220}{}{Você já ouviu falar do Refúgio 13?}
#Hum, never mind. See you around.
{221}{}{Hum, não importa. Vejo você por aí.}

# 17. The Church
#Oh, you mean Tyler and his gang? They guard some shit that comes in from Vault City. Big fucking crates. Once in a while you see them get picked up by caravans heading to New Reno.
{222}{}{Oh, você quer dizer Tyler e sua gangue? Eles guardam alguma merda que vem da Cidade Refúgio. Caixas bem grandes. De vez em quando se vê elas sendo apanhadas por caravanas e indo em direção a Novo Reno.}
#Can I ask you more about them?
{223}{}{Posso te perguntar mais sobre eles?}
#Can I ask you something else?
{224}{}{Posso te perguntar mais uma coisa?}
#OK, thanks. Bye.
{225}{}{OK, obrigado. Tchau.}

# 18.
#What else you wanna know?
{226}{}{O que mais você quer saber?}
#Who’s Tyler?
{227}{}{Quem é Tyler?}
#Where’s New Reno?
{228}{}{Onde fica Novo Reno?}
#So, what are they guarding?
{229}{}{Então, o que eles estão guardando?}
#I want to ask you about something else.
{230}{}{Eu quero te perguntar sobre outra coisa.}
#That’s it. Bye.
{231}{}{É isso aí. Tchau.}

# 19 Who's Tyler?
#Tyler's just some weasel who screwed all the rest of us out of a sweet deal with  Metzger, but fuck that shit! I don't fucking care anymore. I could kick his fucking ass though. Lara and him still have some really bad blood. Something about Tyler and her brother.
{232}{}{Tyler é apenas uma doninha que ferrou todo o resto de nós com um belo negócio com Mezger, mas que se foda essa merda! Não vou me preocupar mais. Vou mais é ferrar a bunda dele também. Lara e ele ainda mantém uma boa relação. Algo sobre Tyler e o irmão dela.}
#That could be useful. Can I ask you more about them?
{233}{}{Isso pode ser útil. Posso te perguntar mais sobre eles?}
#Can I ask you something else?
{234}{}{Posso te perguntar outra coisa?}
#OK, thanks. Bye.
{235}{}{OK, obrigado. Tchau.}

# 20. New Reno?
#New Reno is down to the south a long ways, then east some. There's a lot  of action to be made there, but it's pretty fucking dangerous too. I might head back  some day. Here, I can show you where it's at on that fancy screen thing of yours.
{236}{}{Novo Reno é direto para sul, bem longe, e depois um pouco para a direita. Tem muita ação a ser feita lá, mas é bem perigoso também. Tenho que voltar lá qualquer dia desse. Aqui, posso te mostrar onde fica nessa coisa de tela engraçada sua.}
#I think I can find it now. Can I ask you more about them?
{237}{}{Acho que posso encontrar agora. Posso te perguntar mais sobre eles?}
#Can I ask you something else?
{238}{}{Posso te perguntar outra coisa?}
#OK, thanks. Bye.
{239}{}{OK, obrigado. Tchau.}

# 21. Contents?
#Hell if I know.
{240}{}{Sei lá.}
#Interesting. Can I ask you more about them?
{241}{}{Interessante. Posso te perguntar mais sobre eles?}
#Can I ask you something else?
{242}{}{Posso te perguntar outra coisa?}
#OK, thanks. Bye.
{243}{}{OK, obrigado. Tchau.}

# 22.
#For you, I will sell jet for $500.
{244}{}{Para você, vendo Jet por $500.}
#No, thanks. Bye.
{245}{}{Não, obrigado. Tchau.}
#No, thanks, but I would like to ask you something.
{246}{}{Não, obrigado, mas gostaria de te perguntar uma coisa.}
#That’s too much!
{247}{}{Isso é muito caro!}
#OK, I’ll buy it.
{248}{}{Tudo bem, Vou comprar.}

# 23.
#If you don’t have the money, come back when you can afford it. Don't let me see  you buying from anyone else or I'll kick your fucking ass. I'm the only one with the pure uncut shit, shipped directly from New Reno.
{249}{}{Se você não tem dinheiro, volte quando pode pagar. Não deixe-me ver comprando de alguém mais ou vou te foder. Sou o único aqui com o material puro sem batismo, vinda diretamente de Novo Reno.}
#Wait, I’ll buy it.
{250}{}{Espere, vou comprar.}
#Well, can I ask you something?
{251}{}{Bem, posso te perguntar uma coisa?}
#Bye.
{252}{}{Tchau.}

# 24.
#Tudo bem, baixo o preço para $350, mas nada menos! Esta é minha oferta final. You got to pay top dollar for the good shit. Don't buy from Tubby or any of those losers. They cut their shit. I'm the only one for miles that can get a hold of the best stuff.
{253}{}{OK, Vou baixar o preço para $350, mas não menos! Essa é a minha oferta final. Você tem que pagar bem pelo bom material. Não compre de Tubby ou de qualquer um de seus perdedores. Eles misturam o material deles. Sou o único em quilômetros que pode conseguir material de primeira qualidade.}
#Forget it. Can I ask you something?
{254}{}{Esqueça. Posso te perguntar uma coisa?}
#OK, I’ll buy it.
{255}{}{OK, Vou comprar.}
#Never mind. Bye.
{256}{}{Não importa. Tchau.}

# 25.
#Vault... Vault... Vault 13? Nope, never heard of it. Don't tell me they've come up with another new drug! Nothing can beat jet!}
{257}{}{Refúgio... Refúgio... Refúgio 13? Não, nunca ouvi falar disso. Não me diga que eles apareceram com uma nova droga! Nada é melhor do que o Jet!}
#No, you moron.
{258}{}{Não, seu idiota.}
#No, it’s a place. Can I ask something else?
{259}{}{Não, não é um lugar. Posso te perguntar algo mais?}
#Yes, a wonderful drug.
{260}{}{Sim, uma droga maravilhosa.}
#No, bye.
{261}{}{Não, tchau.}

# ??Don't know what this is for.}
#Joey here isn't much of a conversationalist.
{262}{}{O Joey aqui não é muito de conversa.}

# 4. extra
#Probably not. Bye.
{300}{}{Provavelmente não. Tchau.}

# Addition for Node 17
#You been sleeping? Turns out that Lara's a mean little bitch after all. She gunned Tyler down. I hear Metzger was in on it. Well, I better get back to… work.
{350}{}{Você estava dormindo? Aconteceu que Lara era uma tremenda de uma puta, afinal. Ela atirou e matou Tyler. Ouvi algo que Metzger está envolvido nisso. Bem, é melhor voltar para... o trabalho.}
#You been sleeping? Turns out that Lara was a mean little bitch after all- too bad she's dead. Whipped out Tyler's group. Her gang's running things over there now, last I heard.
{351}{}{Você estava dormindo? Aconteceu que Lara era uma tremenda puta, afinal- que pena que está morta. Acabou com a gangue de Tyler. A gangue dela está gerenciando as coisas por lá agora, da última vez que ouvi.}
