#You see a middle aged man.
{100}{}{Você vê um homem de meia idade.}
#He is unshaven and reeks of alcohol.
{101}{}{Ele está sem barbear e fede a álcool.}
#*hickup* Do I know you?
{102}{}{*Hickup* Eu te conheço?}
#It's 11 O'clock. Do you know where your children are?
{103}{}{São 11:00 hrs. Você sabe onde seus filhos estão?}
#(Looks at you sleepily) What? *hickup* It's 11 already?
{104}{}{(Olha para você sonolento) O quê? *Hickup* Já são 11 horas?}
#Actually no it isn't, I just wanted to say that. But seriously, do you know where your children are?
{105}{}{Na verdade não, não é, Eu só queria dizer isso. Mas, falando sério agora, sabe onde seus filhos estão?}
#Actually yeah it is, but that's not important right now. Seriously though, do you know where your children are?
{106}{}{Na verdade sim, são, mas isso não é importante agora. Falando sério, você sabe onde seus filhos estão?}
#*hickup* I have children? *hickup* Oh yeah, I do. He..or is it she..*hickup* should be around here somewhere.
{107}{}{*Hickup* Eu tenho filhos? *Hickup* Ah, sim, eu tenho. Ele..ou é ela..*hickup* deve estar por aqui em algum lugar.}
#Wow, you're such a drunk. Well, good thing I am working on a way to get your child out of here.
{108}{}{Uau! como você é bêbado. Bem, coisa boa de eu estar trabalhando em uma maneira de tirar seu filho daqui.}
#(Ignores what you just said.) Yeah that's great. *hickup* Now let me get back to this drink.
{109}{}{(Ignora o que você acabou de dizer.) Sim, isso é ótimo. *Hickup* Agora deixe-me voltar a esta bebida.}
#You are a hero to all fathers out there. Keep it up!
{110}{}{Você é um herói para todos por aí. Continue assim!}
#zzzZZZZzzz...
{111}{}{zzzZZZZzzz...}
#zZZZZzzZZzzz...
{112}{}{zZZZzzZZZzzzz...}
#*mumbles*!
{113}{}{*mumbles*!}
#Can't you see I'm drinking here? *hickup*!
{114}{}{Será que não vê que estou bebendo aqui? *Hickup*!}
#Don't bother me. *hickup*!
{115}{}{Não me incomode. *Hickup*!}

#Actually it is a little before 11 O'clock, but that's not important right now. Seriously though, do you know where your children are?
{116}{}{Na verdade, é um pouco antes das 11:00 hrs, mas isso não é importante agora. Falando sério agora, você sabe onde seus filhos estão?}
#Actually it is a little past 11 O'clock, but that's not important right now. Seriously though, do you know where your children are?
{117}{}{Na verdade, é um pouco depois das 11:00 hrs, mas isso não é importante agora. Falando sério agora, você sabe onde seus filhos estão?}

