#You see a small boy.
{100}{}{Você vê um garotinho.}
#You see Little Bobby.
{101}{}{Você vê o Pequeno Bobby.}
#He is wearing dirty clothing and has bruises on his neck and face.
{102}{}{Ele está vestindo roupa suja e tem hematomas no pescoço e face.}
#He is wearing new clothing and has a smile on his face.
{103}{}{Ele está vestindo roupa nova e tem um sorriso no rosto.}
#Hi mister! My name's Bobby and I live here with my Dad.
{104}{}{Oi senhor! Meu nome é Bobby e moro aqui com meu pai.}
#Hi miss! My name's Bobby and I live here with my Dad.
{105}{}{Oi senhorita! Meu nome é Bobby e moro aqui com meu pai.}
#I see. Well tha-!
{106}{}{Entendo. Bem obrig-!}
#Are you here 'cause my dad owes you money? I don't know if he's here or not. But if I knew where he was,
 I'd tell you, 'cause maybe you'd beat him up so bad he wouldn't ever come home again.
{107}{}{Está aqui porque meu pai te deve dinheiro? Não sei se ele está aqui ou não. Mas se soubesse onde ele estava,
 Eu te diria, porque talvez batesse tanto nele que ele jamais voltaria para casa.}
#This sounds horrible, Bobby. Your father has no right to treat you that way -- no parent does.
{108}{}{Isso parece horrível, Bobby. Seu pai não tem direito de tratá-lo dessa forma -- nenhum pai faz.}
#Hah! I'd beat my son too if he didn't listen to me. Your father sounds like a good man.
{109}{}{Hah! Eu bateria no meu filho também se ele não me escutasse. Seu pai parece se um bom homem.}
#[His eyes light up.] You aren't like the others that come through here. I like you. [He sighs heavily.]
 I wish my dad was more like you. Sometimes I think about running away. Some of my friends don't have homes, and they say
 it's not so bad. As long as they bring Mr. Flick enough things, they get to eat once a day. But Mr. Flick doesn't sound very
 nice either -- actually, he sounds a lot like my dad.}
{110}{}{[Seus olhos se iluminam.] Você não é como os outros que passam por aqui. Eu gosto de você. [Ele suspira pesadamente.]
 Gostaria que meu pai fosse como você. As vezes penso em fugir de casa. Alguns de meus amigos não tem casa, e dizem
 que não é tão ruim. Desde que tragam bastante coisas para o Sr. Flick, conseguem comer uma vez por dia. Mas o Sr. Flick não parece
 ser muito bom também -- na verdade, ele se parece muito com meu pai.}
#You're a meanie! Go away. I don't like you.
{111}{}{Você é um meanie! Vá embora. Não gosto de você.}
#There's gotta be something that can be done about this. Can you think of any adults in this town that'd be willing to
 look after you -- or any of these homeless kids?
{112}{}{Tem que haver algo que pode fazer sobre isso. Consegue imaginar em quaisquer adultos nesta cidade que estariam dispostos a
 cuidar de você -- ou quaisquer dessas crianças de rua.}
#[Bobby shrugs.] Maybe Mom? I don't mean *my* mom -- my mom's dead -- but there's a lady that people call Mom. I dunno why.
 Maybe 'cause she's really nice? She's got a diner on the other side of town. [He points to the Northeast.] My homeless friends go
 there and she sneaks them free food. I wish Dad would take me there, 'cause she knows how to make rat taste really yummy!
{113}{}{[Bobby dá de ombros.] Talvez mamãe? Não quero dizer *minha* verdadeira mãe -- minha mãe está morta -- mas tem uma senhora que todos chamam de Mãe. Não sei por quê.
 Será que talvez seja porque ela é realmente muito boa? Ela tem um pequeno restaurante do outro lado da cidade. [Ele aponta para o Nordeste.] Meus amigos de rua vão
 lá e ela desvia comida de graça para eles. Gostaria que Papai me levasse lá, porque ela sabe como fazer um rato realmente delicioso!}
#Hmm, I *am* feeling a bit hungry. Perhaps I'll go pay Mom a visit. You take care of yourself, Bobby.
{114}{}{Hmm, *Estou* com um pouco de fome. Talvez faça uma visitinha na Mamãe. Cuide-se, Bobby.}
#You're such a little brat. I better leave now before I kick the shit outta you. Bye.
{115}{}{Você é um pirralho chato. É melhor eu ir embora agora antes que perca a cabeça e te desça o pau. Tchau.}
#Guess what, Bobby? I spoke with Mom, and she's going to be opening up a nice big new home where you and all your
 homeless friends are welcome to go live together. It's going to be in the big building that's right across the street from here.
 She said she'll have it all set up in a couple days.
{116}{}{Adivinhar o quê, Bobby? Falei com Mamãe, e ela vai abrir uma nova casa grande e agradável, onde você e todos seus
 amigos de rua serão bem vindos para morar juntos. Vai ser um grande edifício que vai ficar bem do outro lado dessa rua.
 Ela disse que tudo estará pronto em dois dias.}
#[A huge smile lights up the boy's face.] Really? That's great! [He hugs you.] I can't wait to live there with all my
 friends! I'm so excited! Thanks again mister, you're the best!
{117}{}{[Um enorme sorriso ilumina o rosto do menino.] Sério mesmo? Isso é ótimo! [Ele abraça-o.] Não posso esperar para morar lá com todos meus
 amigos! Estou tão comovido! Obrigado de novo senhor, me deu a melhor notícia para minha vida!}
#[A huge smile lights up the boy's face.] Really? That's great! [He hugs you.] I can't wait to live there with all my
 friends! I'm so excited! Thanks again miss, you're the best!
{118}{}{[Um enorme sorriso ilumina o rosto do menino.] Sério mesmo? Isso é ótimo! [Ele abraça-o.] Não posso esperar para morar lá com todos meus
 amigos! Estou tão comovido! Obrigado de novo senhorita, me deu a melhor notícia para minha vida!}
#You're welcome kid. See you around.
{119}{}{Você é bem-vindo garoto. Te vejo por aí.}
#Hi again! Did you talk to the Mom lady?
{120}{}{Oi de novo! Falou com a tal Senhora Mamãe?}
#Don't worry Bobby, I'm working on it.
{121}{}{Não se preocupe Bobby, Estou trabalhando nisso.}
#You help Bobby find a better life.
{122}{}{Você ajudou Bobby encontrar uma vida melhor.}
#Hi again! Thanks for everything. I love this new place. Mom is such a great lady!
{123}{}{Oi de novo! Obrigado por tudo. Amo este novo lugar. Mamãe é uma Senhora muito boa!}
#I love this new place. Mom is such a great lady!
{124}{}{Amo este novo lugar. Mamãe é uma Senhora muito boa!}

#I'm so excited! Time to pack my stuff.
{125}{}{Estou tão animado! Hora de arrumar minhas coisas.}
#I wonder if dad will notice I am gone.
{126}{}{Fico imaginando se papai vai notar que fui embora de casa.}
#This is going to be so much better.
{127}{}{Isto vai ser muito melhor.}

#I don't like you. Go away!
{200}{}{Não gosto de você. Vá embora!}

#It sounds like you're not too fond of your dad. Mind if I ask why?
{210}{}{Parece que você não gosta muito seu pai. Se importa se perguntar por quê?}
#You little brat, what gives you the right to talk about your dad like that?
{211}{}{Seu pirralho arrogante, o que te dá o direito de falar sobre seu pai assim?}
#Cause my dad's not very nice. He leaves me home alone all the time, and when he *is* home, he's always drunk or
 he says he's flying on jet, which is a lie 'cause I never see him fly anywhere. Sometimes, he brings a
 girlfriend home -- he's got lots of girlfriends -- and he makes me go outside for awhile, even if its the middle of the night
 and it's cold or raining.
{220}{}{Porque meu pai não é muito legal. Ele me deixa sozinho em casa o tempo todo, e quando ele *está* em casa, ele está sempre bêbado ou
 diz que está viajando, o que é mentira porque nunca soube dele viajar para lugar algum. Às vezes, ele traz uma
 namorada para casa -- ele tem um monte de namoradas -- e me faz ficar fora de casa por um tempo, mesmo que seja de madrugada
 e frio ou chovendo.}
 #That's-!
{221}{}{É por isso que-!}
#Oh! And sometimes he tells me to take things from people in secret. He says it's a game and that he gives it back later,
 but I don't' believe him. But if I don't do it, then he gets real mad and his eyes get all scary looking, and he hurts me.
 See? [He lifts up his shirt sleeve, revealing a nasty bruise on his arm.]
{230}{}{Ah! E às vezes ele me diz para roubar as coisas das pessoas em segredo. Ele diz que é uma brincadeira e que vai devolver mais tarde,
 mas não acredito nele. Mas se eu não fizer, ele fica muito louco e seus olhos fica com aparência amedrontadora, e ele me bate.
 Entende? [Ele levanta a manga de camisa, mostrando um hematoma horrível em seu braço.]}
 