#You see the owner of the saloon.
{100}{}{Você vê a dona da taberna.}
#You see Becky.
{101}{}{Você vê Becky.}

#This looks like the owner.
{150}{}{Esta parece ser a proprietário.}
#This is Becky, owner of this place.
{151}{}{Esta é Becky, proprietária deste lugar.}
#[TALK]!
{152}{}{[FALAR]!}
#Hello, stranger, and welcome to my saloon. I’m Becky.
{153}{}{Olá, forasteiro, e seja bem-vindo à minha taberna. Eu sou Becky.}
#Hello, I am !
{154}{}{Olá, eu sou!}
#. What’s there to do around here?
{155}{}{O que tem para fazer por aqui?}
#Hi, I’m !
{156}{}{Oi, eu sou!}
#. Can I ask some questions?
{157}{}{Posso fazer algumas perguntas?}
#Mom?
{158}{}{Mamãe?}
#Mag gah.
{159}{}{Mag gah.}
#Run along. I don’t need your kind here.
{160}{}{Sai fora já. Não quero tipo como vocês aqui.}
#Mmmm...
{161}{}{Mmmm...}
#Screw you.
{162}{}{Vai se fuder.}
#I’m going.
{163}{}{Estou indo.}
#Sorry, no offense was meant. Can I ask something?
{164}{}{Desculpe, foi sem ofensa. Posso perguntar uma coisa?}
#Drink of whiskey is $5 and the gambling tables are right over there. Have a good one.
{165}{}{A dose de uísque é de $5 e as apostas nas mesas de jogo são bem ali. Que tenham uma boa sorte.}
#Can I ask a question?
{166}{}{Posso fazer uma pergunta?}
#I want a drink!
{167}{}{Quero uma dose de bebida!}
#Hmm, those are some cheap drinks. Let’s see one.
{168}{}{Hmm, essas são algumas bebidas baratas. Vamos tomar uma.}
#Thanks. Bye.
{169}{}{Obrigado. Tchau.}
#Vault 13? Nope, never heard of it.
{170}{}{Refúgio 13? Não, nunca ouvi falar dele.}
#Hmm, can I ask something else?
{171}{}{Hmm, posso te perguntar algo mais?}
#Damn, I need to find it. Bye.
{172}{}{Droga, preciso encontrá-lo. Tchau.}
#What would you like to know?
{173}{}{O que gostaria de saber?}
#Where’s a good place to eat?
{174}{}{Onde tem um bom lugar para comer?}
#Do you know where Vault 13 is?
{175}{}{Sabe onde fica o Refúgio 13?}
#Why are your drinks so cheap?
{176}{}{Por suas bebidas são tão baratas?}
#Nothing. Bye.
{177}{}{De nada. Tchau.}
#Mom runs a little restaurant across town.
{178}{}{Mamãe toca um pequeno restaurante do outro lado da cidade.}
#Mommy! Mommy!
{179}{}{Mamãe! Mamãe!}
#One more question.
{180}{}{Mais uma pergunta.}
#Thanks. Bye.
{181}{}{Obrigado. Tchau.}
#Beat it.
{182}{}{Cai fora.}
#Gwah.
{183}{}{Gwah.}
#I’ll give you something to beat.
{184}{}{Vou te arrumar algo para fazer.}
#Quick question first?
{185}{}{Um pergunta rápida primeiro?}
#Bye.
{186}{}{Tchau.}
#A shot of whiskey is $5. Pay first.
{187}{}{Uma dose de uísque é $5. Pague primeiro.}
#Huh?
{188}{}{Sério?}
#Here’s the money.
{189}{}{Aqui o dinheiro.}
#Changed my mind.
{190}{}{Mudei de idéia.}
#I’m a little short of cash. Can I have a tab?
{191}{}{Estou meio sem grana. Posso abrir um fiado?}
#Can I ask a question?
{192}{}{Posso fazer uma pergunta?}
#Gotta go.
{193}{}{Tenho que ir.}
#Here’s the drink. Anything else?
{194}{}{Aqui a bebida. Algo mais?}
#Question?
{195}{}{Perguntas?}
#Yeha, how about you and I...
{196}{}{Sim, sim, que tal você e eu...}
#Nope.
{197}{}{Não.}
#Hey!, you don’t enough cash for this drink. You’re poorer than even these sops!
{198}{}{Ei, não tem dinheiro suficiente para esta bebida. Você está mais pobre do que estes idiótas!}
#Sorry.
{199}{}{Desculpe.}
#Hmm, I’ll come back.
{200}{}{Hmm, Vou voltar.}
#Hmm. Let me get someone to watch the bar. You and I can go into the back room and play a little game I call "First Strike." If you’re good, well, there’s "Ground Zero."
{201}{}{Hmm. Deixe-me arranjar alguém para cuidar do bar. Então, poderemos ir para os quartos dos fundos e fazer um joguinho que chamo de "Primeiro Ataque." Se se sair bem, bem, passaremos ao "Terreno Neutro."}
#OK!
{202}{}{Está bem!}
#Er...uh...I have to go.
{203}{}{Er... uh... Tenho que ir.}
#You were OK.
{205}{}{Você foi maravilhoso.}
#Next time, let’s play "Into the Glow." But for now...
{206}{}{Da próxima vez, vamos brincar "Dentro da Paixão." Mas, por enquanto...}
#Can you do something for me?
{207}{}{Pode fazer algo por mim?}
#I have to go, but I’ll come back.
{208}{}{Tenho que ir, mas vou voltar.}
#What can I do for you, sweet cheeks?
{209}{}{O que posso fazer por você, docinho?}
#I need some more lovin’.
{210}{}{Preciso transar mais um pouco.}
#I got some questions.
{211}{}{Tenho algumas perguntas.}
#How can you sell your drinks so cheaply?
{212}{}{Como pode vender suas bebidas tão baratas?}
#How about a drink?
{213}{}{Que tal uma bebida?}
#Gotta run. See ya.
{214}{}{Tenho que me apressar. A gente se vê.}
#Not now. Maybe later. Yes, definitely later.
{215}{}{Agora não. Talvez mais tarde. Sim, com certeza mais tarde.}
#Can I ask a question?
{216}{}{Posso fazer uma pergunta?}
#Later then.
{217}{}{Até mais tarde, então.}
#I have a still in the basement. I made it myself. Beats paying triple to those New Reno
{218}{}{Tenho uma destilaria no porão. Eu mesma montei. Sai melhor do pagar o triplo para esses gangster de New Reno.}
#Smart girl! I like that!
{219}{}{Garota esperta! Fosto disso!}
#Hmm, I have to go. I’ll see you later.
{220}{}{Hmm, Tenho que ir. Te vejo mais tarde.}
#Why? Why did you destroy my still? You bastard!
{221}{}{Por quê? Por que você destruiu minha destilaria? Seu filho da puta!}
#Nothing personal. I got paid to do it.
{222}{}{Nada pessoal. Fui pago para fazer.}
#I’m sorry.
{223}{}{Sinto muito.}
#Bye.
{224}{}{Tchau.}
#I’ll just make another one, you know.
{225}{}{Vou montar outra, sabe disso.}
#I know.
{226}{}{Eu sei.}
#Well, that’s good.
{227}{}{Bem, isso é bom.}
#Bye.
{228}{}{Tchau.}
#Why? Why did you destroy my still? You bitch!
{232}{}{Por quê? Por que você destruiu minha destilaria? Sua cadela!}

#Where are you, baby?
{233}{}{Onde você está, tesãozinha?}
#Are you coming?
{234}{}{Você já está vindo?}
#I'm waiting.
{235}{}{Estou esperando.}
#I'm in here, lover.
{236}{}{Estou aqui, amor.}

#I've got a bar to run.
{237}{}{Tenho um bar para gerenciar.}
#Follow me, sugar.
{238}{}{Me acompanhe, docinho.}

#How did you... Do that... Uhhh...
{240}{}{Como você... Faz bem isso... Uhhh...}
#It's O.K., size doesn't really matter.
{241}{}{Está tudo bem, o tamanho realmente não importa.}
#That was, ummm, nice -- I guess.
{242}{}{Isso foi, hummm, uma delícia - eu acho.}
#Thanks, sweety; that was fun.
{243}{}{Obrigado, docinho; foi divertido.}
