# 0. Look
#You see a guard.
{100}{}{Você vê um guarda.}
#You see Marc, a guard.
{101}{}{Você vê Marc, um guarda.}
#You see Marc, one of Tyler's guards.
{102}{}{Você vê Marc, um dos guardas de Tyler.}

# 1. Door opened
#Yo, Tyler!
{150}{}{Você, Tyler!}

# 2. Hostile
#What the…?
{200}{}{Mas que...?}

# 3. Gang 1 Won War
#Thanks for the tip. That was some fun stuff.
{225}{}{Obrigado pela dica. Isso até que foi divertido.}
#I knew we could take those pussies.
{226}{}{Sabia que daríamos conta dessas bichanas.}
#Too bad we killed them all. Now what are we to do?
{227}{}{Que pena que matamos todos. Agora, o que vamos fazer?}
#Are we hot or what?
{228}{}{Somos bons ou o quê?}
#We're too good.
{229}{}{Somos muito bons.}
#We fucking kicked some ass! Fuck yeah!
{230}{}{Nós fudemos com alguns deles! Foda-se, É isso aí!}

# 4. TRAP NO
#Tyler's the one to talk to, not me, lady.
{250}{}{É com Tyler com quem tem que conversar, não comigo, senhora.}
#What's up. You need something; you gotta talk to Tyler here.
{251}{}{Que acontece?. Precisa de algo? Precisa falar com o Tyler aqui?}
#What you looking at?
{252}{}{Que está olhando?}
#Tyler's the one to talk to, not me, man.
{253}{}{É com Tyler com quem tem que conversar, não comigo, cara.}

# 5. TRAP SET
#We're going to kick some ass tonight!
{255}{}{Vamos azarar com alguns esta noite!}
#Tonight's the night!
{256}{}{Esta noite vai ser a noite!}
#I'm going to remember this night for sure.
{257}{}{Sempre vou me lembrar desta noite, com certeza.}
#Don't even tell me they chickened out.
{258}{}{Nem me diga que se acovardaram.}
#Oh, I sure hope those fuckers show.
{259}{}{Oh, Com certeza espero que esses canalhas aparecem.}

# 6. TRAP NOSHOW
#I knew those pussies wouldn't show.
{260}{}{Sabia que essas bichanas não iria aparecer.}
#We should just go kick their asses just for thinking about fighting us.
{261}{}{Deveríamos ir lá provocá-los só para pensarem em nos enfrentar.
#We would have ripped through them if they had showed.
{262}{}{Teríamos acabados com eles se tivessem aparecidos}.}
#I could have taken them on by myself.
{263}{}{Eu deveria ter acabado com eles sozinho}
#Tyler and I would have kicked some serious ass.
{264}{}{Tyler e eu teríamos arrebentado com alguns idiotas bem seriamente.}
