# 0. Look

# You see a mean looking man.
{100}{}{Você vê um homem de aparência maligna.}

# You see Metzger, the slaver master.
{101}{}{Você vê Metzger, o mestre dos escravos.}

# Metzger's the head of the Slaver's Guild.
{150}{}{Metzger, o líder dos traficantes de escravos.}

# 1. CF: Hostile (From WTG)

# You'll pay for that.
{200}{}{Você vai pagar por isso.}

# 2. 1st Time, Self Initiated (From 2-WTG)

# What the fuck do you want? This is the Slaver's Guild, not some safe
 house for you fucking jet heads.
{210}{}{O que caralho você quer? Isso é uma Guilda de Escravistas, não um abrigo para viciados em jet.}

# What the hell do you want, you ugly bitch? This is the Slaver's
 Guild, not some fucking whorehouse.
{211}{}{O que caralho você quer, sua vadia escrota? Isso é uma Guilda de Escravistas, não um puteiro.}

# What the hell do you want, bitch? This is the Slaver's Guild, not some
 fucking whorehouse.
{212}{}{O que caralho você quer, vadia? Isso é uma Guilda de Escravistas, não uma porra de um puteiro.}

# You're starting to piss me off. What the hell do you want now?
{213}{}{Você está começando a me irritar. O que diabo você quer agora?}

# Now what, damn it?
{214}{}{O que foi agora, caralho?}

# What?
{215}{}{Quê?}

# Oh, you better make it quick.
{216}{}{Ah, é melhor você andar logo com isso.}

# You here to work for a fucking change?
{217}{}{Que tal um pouco de trabalho, para variar?}

# I'm starting to get used to your ugly mug. So... are you here for a reason or what?
{218}{}{Estou começando a me acostumar com sua cara feia. Então... você está aqui por algum motivo ou o que?}

# Do I look like your fucking dad or something? I sure as hell hope not. Now spit it
 out, what do you want?
{219}{}{Eu tenho cara de ser o viado do seu pai por acaso? Espero que não. Agora desembucha, o que você quer?}

# Oh, look who's here. You think you're special or something? Speak up or get the
 fuck out.
{220}{}{Oh, olha quem voltou. Você se acha, não? Fala o que você quer ou vai se foder.}

# What do you want now, slaver?
{221}{}{O que você quer agora, escravista?}

# You just going to stand there or are you going to say something?
{222}{}{Vai ficar aí de boca aberta ou vai falar alguma coisa?}

# Speak up. I don't have all day for this crap.
{223}{}{Fala. Eu não tenho tempo para essa merda.}

# 3. Selling NPC (From 5, 13)

# Oh, and 'who' would that be? I hope you don't plan on seeing this person again...
{230}{}{Oh, e 'quem' é essa pessoa? Eu espero que queira ver ela de novo...}

# You don't have anyone that I'm interested in. I'm only interested in people -
 normal ones, that is.
{231}{}{Não estou interessado em nenhum deles. Só me interesso por pessoas - normais, pelo menos.}

# You fucking moron, what do you think I am, a fucking store or something? If you get
 a slave you'd like to sell, let me know. If you want to sell something else, go to a fucking store.
{232}{}{Vai tomar no seu cu, caralho, eu tenho cara de loja por acaso? Se você achar um escravo para vender, venha
 até mim. Se quiser vender qualquer outra coisa, procure uma loja, porra.}
 
# Miria
{233}{}{Miria}

# Davin
{234}{}{Davin}

# Vic
{235}{}{Vic}

# Myron
{236}{}{Myron}

# Cassidy
{237}{}{Cassidy}

# Sulik
{238}{}{Sulik}

# Can I ask you another question instead?
{239}{}{Posso te fazer outra pergunta então?}

# I changed my mind. Bye.
{240}{}{Mudei de ideia. Adeus.}

# Dex
{241}{}{Dex}

# Cat Jules
{242}{}{Cat Jules}

# Kitsune
{243}{}{Kitsune}

# 4. Before PC responses (From ?Everywhere?)

# Go ahead.
{245}{}{Vá em frente.}

# Yeah?
{246}{}{Sim?}

# I'm not your fucking servant, so hurry it up.
{247}{}{Eu não sou seu empregado, caralho, anda logo.}

# What is it? I don't have all day.
{248}{}{O que foi? Eu não tenho o dia todo.}

# Não me lembro exatamente do diálogo, esse Shoot pode ser no sentido de xingar, tipo "merda", ou no sentido de pressionar o protagonista "vai logo"
# Shoot.
{249}{}{Vai logo.}

# Maybe.
{250}{}{Talvez.}

# 5. Main body, yes? (From 3)

# I have someone I'd like to sell.
{255}{}{Eu queria vender alguém.}

# About Vic...
{256}{}{Sobre Vic...}

# I'm looking for a merchant.
{257}{}{Estou procurando um comerciante.}

# Lara wanted me to ask you for permission to fight Tyler.
{258}{}{A Lara quer a sua permissão para lutar contra o Tyler.}

# Can I join the guild?
{259}{}{Posso entrar para a guilda?} 

# What can you tell me about your guild?
{260}{}{O que pode me dizer sobre a guilda?}

# I'd like to go on a slave run.
{261}{}{Eu gostaria de participar de uma caça aos escravos.} 

# Never mind. Bye.
{262}{}{Deixa quieto. Adeus.}

#  want to ill.
{263}{}{ quer maldade.}

# Na.
{264}{}{Nah.}

#killap - expansion (Actually part of Node007)

# I was looking over the slaves you got back there, but you see, I have very, uh...*selective* tastes, and none of
 them are quite what I'm looking for. Are these all the slaves you have to offer?
{265}{}{Eu estava dando uma olhada nos escravos que você me trouxe, só que, eu sou muito errr... *seletivo*, e 
 nenhum deles me agradou. Esses são os únicos escravos que tem a me oferecer?} 

# 6. Want to join slaver's guild? (From 5, 7, 8)

# You think you can cut it? I don't take in just anyone... What the hell. If
 you fuck up, I'll sell you off. You'll have to get a tattoo on your forehead
 identifying you as a slaver to everyone. It's permanent, so no second thoughts.
{270}{}{Acha que dá conta? Eu não aceito qualquer um... que diabo. Se você fizer cagada, eu vou te vender.
 Você vai precisar de uma tatuagem na testa, para todo mundo ver, te identificando como escravista. É permanente, 
 então nem pense em se arrepender depois.} 
 
# So, our delicate little flower girl returns... You changed your mind then?
 Going to get that tat after all?
{271}{}{Então nossa florzinha voltou... Mudou de ideia? Vai fazer a tatu?}
 
# Yeah, you might do... You don't need much in the way of brains to go on a run.
 If you fuck up, I'll just sell you off. If you think you can cut it you'll have
 to get a tattoo on your forehead identifying you to everyone as slaver.
{272}{}{É, talvez você sirva... Não precisa ter muito miolo para ir em uma caçada. e você fizer cagada, eu vou te vender.
 Se acha que aguenta o tranco, vai precisar de uma tatuagem na sua testa, para todo mundo ver, te identificando como escravista.}
 
# Let's do it.
{273}{}{Vamos lá.}

# I have to think about it. I'll get back to you.
{274}{}{Vou pensar. Depois volto.}

# Maybe not. Bye.
{275}{}{Acho que não. Adeus.}

# Uya! [nod]
{276}{}{Óia! [acena com a cabeça afirmativamente]}

# No no no no no!
{277}{}{Nãããããããããããããão!}

# 7. Tell me about Guild (From 4)

# What do you fucking think? This is a slaving guild. I buy and sell slaves.
{285}{}{O que você acha, porra? É uma guilda de escravistas. Eu compro e vendo escravos.}

# Where do you get the slaves?
{286}{}{Onde você consegue os escravos?}

# I'd like to join.
{287}{}{Eu gostaria de entrar.}

# Another question please.
{288}{}{Outra pergunta, por favor.}

# Oh, okay. Bye.
{289}{}{Ah, ok. Adeus.}

# 8. Slaves from? (From 7)

# Oh, here and there. We mainly collect primitives and nomads when we run across them.
{300}{}{Ah, aqui e ali. Nós capturamos principalmente primitivos e nômades quando achamos eles.}

# Sounds like fun. How can I get in on that?
{301}{}{Parece divertido. Como posso entrar?}

# I have another question.
{302}{}{Eu tenho outra pergunta.}

# Oh, okay. Bye.
{303}{}{Ah, ok. Adeus.}

# 9. Self Initiated, Just got Tattoo (From WTG)

# What do you know, you didn't even cry. I'm so proud of you... actually, that tat
 looks pretty good on you. Just give a holler when you're ready for your first slave run.
{310}{}{Caramba, você nem chorou. Estou orgulhoso de você... essa tatu lhe caiu bem. Me chame quando quiser
 participar de sua primeira caçada aos escravos.} 
 
# Thanks. Bye.
{311}{}{Valeu. Adeus.}

# I'm ready right now.
{312}{}{Eu quero ir agora mesmo.}

# Me Kill NOW!
{313}{}{Mim Matar AGORA!}

# Okey-Dokey.
{314}{}{Combinado.}

# 10. Slave Run (From 9)

# Two of my men will get you fairly close to your targets. Your pay will be based
 on the number of the slaves you return, but watch each other's backs. If anyone
 gets killed, your pay will be severely cut.
{320}{}{Dois dos meus homens vão te levar até os alvos. Seu pagamento depende da quantidade de escravos que você
 trouxer de volta, mas se cuidem. Se algum de vocês morrer, descontarei de seus salários.} 
 
# Damn, we're all farmed out. Have to wait for some primitives to move back into the
 area. Maybe we should start breeding them.
{321}{}{Merda, não achamos escravos. Temos que esperar até alguns primitivos chegarem na área. Deveríamos
 começar a criar eles igual gado.}
 
# Sorry, you're just not working out. Too many losses and this is a business. I need
 to make money, not lose it.
{322}{}{Desculpa, mas não está funcionando com você. Muitas perdas, e isso é um negócio. Eu preciso ganhar
 dinheiro, e não perder.}
 
# All right. They're ready.
{323}{}{OK, Eles estão prontos.}

# Good, you can leave now.
{324}{}{Bom, você pode ir agora.}

# Get a move on it then.
{325}{}{Vai logo então.}

# Good. See me when you're done.
{326}{}{Ótimo. Volte aqui quando terminar.}

# Okay.
{327}{}{Ok.}

# Uh.
{328}{}{Uh.}

# 11. Slave Run Description (From 10)

# Just kill all the hostile ones. If they attack you, kill them. I don't
 want to deal with them anymore, too big of a fucking hassle. Once you're done,
 the other slavers will round up and tag the rest.
{340}{}{Mate todos os hostis. Se eles te atacarem, mate-os. Eu não quero mais lidar com esses filhos da puta, dão muito trabalho.
 Quando terminar, os outros escravistas vão te ajudar a juntar o resto.}
 
# Okay.
{341}{}{Ok.}

# Oh.
{342}{}{Oh.}

# 12. Slave Run Description 2 (From 11)

# Once they start tagging the slaves, you can head back if you like. It takes
 special training, so don't try to subdue the others yourself. You can do whatever
 you want just as long as you don't damage the goods.
{350}{}{Quando eles começarem a etiquetar os escravos, pode voltar se quiser. É preciso treinamento especial para
 isso, então não tente capturá-los sozinho. Você pode fazer o que quiser, contanto que não danifique a mercadoria.}
 
# All right.
{351}{}{Beleza.}

# Uh huh.
{352}{}{Uhum.}

# 13. Selling other NPCs (From 3)

# Ah, yeah. She's pretty nice. I'll give you $
{360}{}{Oh, yeah. Ela é muito boa. Vou te dar $ }

#  for her. How about it?
{1360}{}{ por ela. Que tal?}

# He's okay. I could probably take him off your hands for, oh, say $
{361}{}{Ele serve. Acho que posso tirá-lo de suas por, digamos $ }

# ?
{1361}{}{?}

# You fucking idiot. What the hell makes you think I want that moron back? It took
 him forever to fix a damn radio! A radio! You're stuck with him. I don't want him
 breaking anything else around here.
{362}{}{Não seja idiota. Por que caralho você acha que quero esse retardado de volta? Levou uma eternidade para 
 ele consertar um maldito rádio! Um rádio! Fique com ele. Eu não quero ele quebrando mais nada por aqui.}
 
# I don't know, this one's pretty skinny... but a smart one? That might be worth something. I'll give you $
{363}{}{Não sei, é quase só osso... é inteligente? Isso deve valer alguma coisa. Vou te dar $ }

# .
{1363}{}{.}

# This one looks like he could really put up a fight. Hmm... $
{364}{}{Esse dai parece bom de briga. Hmm... $ }

# .
{1364}{}{.}

# Another primitive. This one's a freak show. Still, he looks strong and that look might fetch something extra. $
{365}{}{Outro primitivo. É um show de horrores. Apesar disso, ele parece forte e esse visual pode valer algo. $ }

# ?
{1365}{}{?}

# How about someone else?
{366}{}{Que tal outro?}

# Well, let me ask you another question then.
{367}{}{Bom, deixa eu perguntar outra coisa então.}

# Okay.
{368}{}{Ok.}

# Fine.
{369}{}{Ótimo.}

# Okay.
{370}{}{Ok.}

# Not worth it.
{371}{}{Não vale a pena.}

# No.
{372}{}{Não.}

# 14. NPC Sold SPECIAL DIALOG (From 13)

# All right, boys, put him in the pens.
{380}{}{Muito bem, garotos, coloquem-no na gaiola.}

# All right, boys, put her in the pens.
{381}{}{Muito bem, garotos, coloquem-na na gaiola.}

# Right, boss.
{382}{}{Certo, chefe.}

# 15. Turned down Selling NPC (From 13)

# Well don't waste my fucking time then. If you ever get someone you're
 looking to part with, come see me.
{390}{}{Porra, não me faça perder meu tempo então. Se tiver alguém que queira se livrar, venha me ver.}

# I've got another question for you.
{391}{}{Eu tenho outra pergunta.}

# Okay. Bye.
{392}{}{Ok. Adeus.}

# 16. Permission (From 5)

# What the hell crawled up her ass all of a sudden? I gave that bitch a chance
 a while back. Didn't think she had the balls to try this.
 {400}{}{O que deu na cabeça dela? Eu dei mais uma chance para essa puta. Não achei que ela teria a ousadia de tentar de novo.}
 
# What are you talking about?
{401}{}{Do que você está falando?}

# So it's okay?
{402}{}{Então tá liberado?}

# 17. What kind of outfit… (From 16)

# Oh, don't play coy with me. I know exactly what she's planning to do. I
 gave her a chance a while back and she couldn't cut it, but if she
 thinks she's up to it...
{410}{}{Ah, não tente me comover. Eu sei qual é a dessa puta. Eu já dei uma chance para ela e ela não aproveitou,
 mas se estiver disposta...}
 
# So, it's okay?
{411}{}{Então tá liberado?}

# 18. So it's okay? (From 17)

# Well, I did say the offer would remain open. If she finally thinks she can kick his ass and
 is better able to guard my shit...
{420}{}{Bom, eu disse que a oferta continua de pé. Se ela finalmente acha que pode chutar o cu daquele viado e 
 pode vigiar minhas coisas...}
 
# Well?
{421}{}{Bem?}

# So, that's a yes?
{422}{}{Isso é um sim?}

# 19. Permission Granted (From 18)

# Look, I don't give a shit which of them guards it. Just as long as none of my goods are
 damaged, I don't care.
{430}{}{Olha, eu estou me fodendo para quem fica na vigia. Se a minha mercadoria não for danificada, eu não ligo.}

# Another question, please.
{431}{}{Por favor, mais uma pergunta.}

# Okay, thanks.
{432}{}{Ok, valeu.}

# 20. I'm looking for a Merchant (From 5, 20)

# What the fuck are you asking me for? Do I look like some kind of fucking... oh,
 wait. You're probably looking for Vic?
{440}{}{E por que caralho está perguntando pra mim? Eu tenho cara de... ah, espera. Você está procurando pelo Vic?}

# He's the one that 'specializes' in vault technology, or so he says. He's my
 property now. He's not going anywhere.
{441}{}{Ele é o 'especialista' em tecnologia das cúpulas, pelo menos é o que ele diz. Ele é minha propriedade agora. 
 Não vai a lugar nenhum.}
 
# What about him?
{442}{}{E ele?}

# Yeah, that's him.
{443}{}{Sim, ele mesmo.}

# Can I see him?
{444}{}{Posso vê-lo?}

# Why are you keeping him here?
{445}{}{Por que você o mantém aqui?}

# Okay, thanks. Bye.
{446}{}{Ok, valeu. Falou.}

# 21. Radio Fix/Not Fixed (From 20)

# That little fuck - he sold me a radio that he said would be able to pick up
 some transmissions. It didn't. I caught his ass trying to sneak out of town before
 I found out. Bad mistake. No one fucks with me. He's lucky to be alive.
{455}{}{Esse viado - ele me vendeu um rádio que supostamente interceptaria algumas transmissões. Não funcionou. 
 Eu peguei esse merda tentando fugir da cidade antes que eu descobrisse. Péssima ideia. Ninguém mexe comigo. Ele tem sorte de estar vivo.}
 
# Like I said. He needs to fix something first. After that we'll see.
{456}{}{Como eu disse. Ele precisa consertar algo primeiro. Depois disso, veremos.}

# Well he's finally gotten that damn radio to work, but it doesn't mean I'm going to let
 him off that easy.
{457}{}{Bom, ele finalmente fez o maldito rádio funcionar, mas isso não significa que vou deixá-lo ir tão fácil.}

# He still tried to screw me over.
{458}{}{Esse bosta tentou me enganar.} 

# Can I see him?
{459}{}{Posso vê-lo?}

# What kind of transmissions are you talking about?
{460}{}{Que tipo de transmissões você está falando?}

# Okay, thanks.
{461}{}{Ok, valeu.}

# Maybe some money might help clear things up?
{462}{}{Talvez um pouco de dinheiro resolva o problema?}

# What kind transmissions were you talking about before?
{463}{}{De que tipo de transmissões você estava falando?}

# 22. Set See Vic is Okay (From 20-21)

# What for? Ah, fuck, never mind. Just don't keep him from fixing that damn
 radio - and he better fix it soon. I'm sick of feeding his lazy ass.
{475}{}{Pra que? Ah, porra, esquece. Só não o impeça de consertar o maldito rádio - e é melhor ele consertar logo. 
 Estou de saco cheio desse bunda mole.}
 
# Why are you keeping him here?
{476}{}{Por que você o mantém aqui?}

# Thanks.
{477}{}{Valeu.}

# 23. Transmissions (From 21)

# The Enclave and New... Hey, what the hell you care for? It's business. I need to be sure no one's trying to fuck me over. That's all you need to know.
{485}{}{O Enclave e Nova... Ei, essa porra é da sua conta? São negócios. Eu preciso ter certeza de que ninguém está tentando me foder.
 É só isso que preciso.}
 
# Mind your own business.
{486}{}{Cuide da sua vida.}

# Okay.
{487}{}{Ok.}

# 24. Pay for Vic (From 21, 23)

# Sure, but it'll cost you $
{495}{}{Certo, mas isso vai lhe custar $ }

# $
{496}{}{$ }

# .
{1496}{}{.}

# Can't we work something out?
{497}{}{Não podemos resolver de outra forma?}

# Okay. Here.
{498}{}{Ok. Aqui.}

# Can I ask you some more questions first.
{499}{}{Posso te fazer umas perguntas primeiro?}

# Sorry, can't afford that yet.
{500}{}{Desculpe, não posso pagar por isso.}

# 25. Bought Vic (From 24)

# Okay, he's yours, but get his ass out of here before I change my mind
 and put a bullet in that stupid fucking head of his.
{510}{}{Ok, ele é seu, mas tire esse trazeiro gordo dele daqui antes que eu mude de ideia e estoure os miolos 
 dessa porra de cabeça feia dele.}
 
# Can I ask you some more questions first?
{511}{}{Posso te fazer umas perguntas primeiro?}

# Thank you.
{512}{}{Obrigado.}

# 26. Female Sex (From 24)

# Oh, yes. We can work everything out nice and smooth... I'll give you
 half off if you make it worth my while...
{520}{}{Ah, sim. Podemos negociar... Eu faço pela metade do preço se você fizer valer a pena...}

# You had best stop teasing me, girly. I'm not much with patience.
{521}{}{É melhor parar de me provocar, menininha. Não me tire a paciência.}

# Only if you're good to me.
{522}{}{Só se for boazinha comigo.}

# Sure, why not.
{523}{}{Topo, por que não.}

# Maybe later.
{524}{}{Talvez depois.}

# 27. Good to me (From 26)

# Oh, you better believe it.
{530}{}{Ah, pode acreditar nisso.}

# Good.
{531}{}{Ótimo.}

# 28. Paying for Run (From WTG)

# Here's $
{540}{}{Aqui estão $ }

# . Pretty fucking good job.
{1540}{}{ . Trabalho bem feito da porra.}

# . Pretty fucking good job, 
{15401}{}{ . Trabalho bem feito da porra, }

# .
{2540}{}{.}

# Here's your $
{541}{}{Aqui estão seus $ }

# . You kicked some serious ass. Keep it up.
{1541}{}{ . Você é foda mesmo. Continue assim.}

# Good job out there. Here's $
{542}{}{Bom trabalho. Aqui estão $ }

# .
{1542}{}{.}

# Here's your money, 
{543}{}{Aqui estão seu dinheiro, }

# . $
{1543}{}{. $ }

# .
{2543}{}{.}

# $
{544}{}{$}

#  isn't something to laugh at, but you can't make a lot more than that.
{1544}{}{ não é pouca bosta, mas você pode conseguir muito mais que isso.}

# Well it's $
{545}{}{Bem, são $ }

#  this time. Pretty good job.
{1545}{}{ Dessa vez. Bom trabalho.}

# It wasn't that tough, now was it? Next time no mistakes. Here's $
{546}{}{Não foi tão difícil, foi? Da próxima vez, não quero erros. Aqui estão $ }

# .
{1546}{}{.}

# $
{547}{}{$}

# ? Not bad.
{1547}{}{ ? Nada mal.}

# Come on! $
{548}{}{Vamos! $}

# ? You can do better than that.
{1548}{}{ ? Você pode fazer melhor que isso.} 

# Remember, watch each other's backs and only kill the hostile slaves. Here's $
{549}{}{Lembre-se de cuidar dos seus companheiros e de matar apenas escravos hostis. Aqui estão $ }

# .
{1549}{}{.}

# Only $
{550}{}{Apenas $}

# ! That's fucking pitiful! Shape up or I'll kick your ass out.
{1550}{}{ ! Mas que merda! Ou você aprende a fazer direito ou vou te chutar daqui.}

# You want to make any money or not? You're pissing me off. How fucking
 hard can it be? Now take your $
{551}{}{Você quer ganhar dinheiro ou não? Você está me irritando. É tão difícil assim, porra? Toma aqui seus $}

#  and get out.
{1551}{}{ e some daqui.}

# What the hell was your problem? You don't earn shit this time. We're
 in this to make money, not dick around.
{552}{}{Qual é a porra do seu problema? Não vou te dar bosta nenhuma. Nós fazemos isso para ganhar dinheiro, porra.}

# I'll do better next time.
{553}{}{Eu farei melhor da próxima vez.}

# Thanks for nothing.
{554}{}{É muita generosidade da sua parte.}

# Thanks.
{555}{}{Valeu.}

# Ug.
{556}{}{Ugh.}

# 29. (From WTG)

# Damn bitch, was that your first time? There's no way that was not your first time.
{570}{}{Puta que pariu, essa foi a sua primeira vez? Tem que ter sido sua primeira vez.}

# Damn girl, was that your first time?
{571}{}{Porra menina, essa foi sua primeira vez?}

# Pretty good, I guess.
{572}{}{Muito bem, eu acho.}

# Very nice, maybe we can do it again sometime.
{573}{}{Muito bem, podemos fazer de novo outra hora.}

# Damn! That was... very well spent money.
{574}{}{Porra! Isso foi... dinheiro muito bem gasto.}

# Damn! You were the best piece of ass I've ever had, and I've had a lot.
{575}{}{Porra! Essa foi a melhor bunda que eu já comi, e eu já comi uma porrada.}

# 43. Abandon Slave Run

# YOU STUPID FUCK! How dare you abandon your fellow slavers out there? [Spits in your face] KILL HIM!
{600}{}{SEU RETARDADO! Como pôde abandonar seus companheiros escravistas lá? [Cospe na sua cara] MATEM-NO!}

# But I...
{601}{}{Mas mas...}

# Alright, let's do this.
{602}{}{Beleza, vem pro pau.}

# 30. Returned from run, attacked slaver and lived to tell about it. (From WTG)

# Well, nice to see you could make it back.
{620}{}{Que bom que você conseguiu voltar com vida.}

# Yeah, it was a tough run.
{621}{}{É, foi uma caçada e tanto.}

# Thanks. Things got a little hairy out there.
{622}{}{Obrigado. As coisas ficaram meio tensas por lá.}

# Agra Moo ne!
{623}{}{Agra Moo ne!}

# 31. Dumb hostile run (From 30)

# Oh, you want money? You want to be paid?
{630}{}{Oh, você quer dinheiro? Quer receber um pagamento?}

# Yah.
{631}{}{Ehe.}

# Ugh.
{632}{}{Ugh.}

# 32. Dumb 2 (From 31)

# Of course I'd LOVE to help you out but... there's this slight problem I have... something about attacking one of my men.
{640}{}{Claro que eu ADORARIA te ajudar, mas... tem um certo problema... algo como você ter atacado um dos meus homens.}

# Sorry! I didn't mean to- I mean... Ug?
{641}{}{Desculpa! Eu não queria - quer dizer... Ugh?}

# Uh, oh.
{642}{}{Oh, oh.}

# 33. Dumb 3 (From 32)

# Oh, don't worry. I'm sure I can find it in my heart to pay- I mean repay you. Men, it's payday.
{650}{}{Ah, não se preocupe. Meu coração diz que eu devo te recompensar - ou melhor, te pagar. Homens, paguem-no.}

# Oh, don't worry. I'm sure I can find it in my heart to pay- I mean repay you. Men,
 take this bitch down.
{651}{}{Ah, não se preocupe. Meu coração diz que devo te recompensar - ou melhor, te pagar. Homens, acabem com essa puta.}

# Oops.
{652}{}{Ops.}

# Garaka!
{653}{}{Caraca!} 

# Uh... Tank?
{654}{}{Uh... brigadu?}

# 34. Tough run, hostile (From 30)

# Oh, I'm sure. This line of work isn't to be taken lightly. It takes trust and loyalty. We watch each other's backs. Good policy don't you think?
{670}{}{Ah, eu sei. Esse trabalho não é mole. Ele requer confiança e lealdade. Nós cuidamos uns dos outros. É como uma família, não acha?}

# I guess.
{671}{}{Acho que sim.}

# Uh, what's going on?
{672}{}{Uhm, o que foi?}

# Definitely.
{673}{}{Com certeza.}

# 35. I guess (From 34)

# You guess? I didn't think you were that smart. You really are a stupid fuck.
 [Metzger glares at you then looks to his guards and motions in your direction.]
{680}{}{Você acha? Não achei que fosse tão inteligente. Você é idiota pra caralho. [Metzger te encara e então olha para os guardas e aponta em sua direção.]}

# Actions?
{681}{}{Ações?}

# What?
{682}{}{Quê?}

# 36. What's going on? (From 34)

# Oh, so you aren't as dumb as you act. Well, that's a shame. You see, I'm having a bit of a dilemma. Someone had the nerve to attack my men.
{690}{}{Ah, então você é tão idiota quanto parece. Que pena. Sabe, estou com um problema. Alguém teve a coragem de atacar um dos meus homens.}

# Really?
{691}{}{Sério?}

# It was an accident!
{692}{}{Foi um acidente!}

# 37. Definitely (From 34)

# Really? I'm so glad you agree. Now what would you do if someone betrayed this trust?
{700}{}{Sério? Que bom que você concorda. Agora me diga, o que você faria se alguém traísse sua confiança?}

# Uh, give them a warning?
{701}{}{Uhm, dar um susto neles?}
 
# Here. Let me show you. [attack]
{702}{}{Claro. Deixe eu te mostrar. [atacar]}

# Make them pay.
{703}{}{Faria pagarem por isso.}

# 38. Trust, warn? (From 37)

# You think so? Honestly? I don't know. I was thinking of something a little more... permanent. [With an evil grin, Metzger looks to his guards and nods.]
{710}{}{Você acha? Sinceramente? Não sei. Eu estava pensando em algo um pouco mais... permanente. [Com um sorriso maligno, Metzger olha para os guardas e acena.]}

# What?
{711}{}{Quê?}

# Oh boy...
{712}{}{Ah não...}

# 39. Trust Pay? (From 37)

# I'm glad we're in agreement. [Metzger looks to his guards.] Men, it's payday.
{720}{}{Que bom que concordamos. [Metzger olha para seus guardas.] Homens, hora do pagamento.}

# Uh...
{721}{}{Er...}

# 40. Really? (From 36)

# Yes. It's a shame really. This person just doesn't seem to get it, but
 I think they are about to. [You see Metzger making a small hand gesture to his
 men.] Play time.
{730}{}{Sim. É uma pena mesmo. Essa pessoa parece que não entende, mas eu acredito que logo ela vai sacar. 
 [Você vê Metzger fazendo um pequeno gesto para seus homens.] Porrada!}
 
# Oh really?
{731}{}{É mesmo, é?}

# Uh oh.
{732}{}{Oh oh.}

# 41. Accident? (From 36)

# Yes, I'm afraid accidents happen around here quite often. In fact, I'm afraid we're about to have another one. [Metzger smiles pleasantly and then nods towards his men.]
{740}{}{Sim, infelizmente acidentes acontecem direto por aqui. Na verdade, temo que outro está para acontecer. [Metzger sorri alegremente e acena para seus homens.]

# Bring it on!
{741}{}{Manda bala!}

# I'm not getting out of this am I?
{742}{}{Não posso escapar dessa, posso?}

# 42. Getting out? (From 41)

# Oh, but this will be fun. Trust me.
{750}{}{Ah, mas isso será divertido. Pode apostar.}

# Fuck you.
{751}{}{Vá se foder.}

# Uh, okay.
{752}{}{Uh, ok.}

# You've killed the leader of the Slave Guild.
{800}{}{Você matou o líder dos traficantes de escravos.}

#killap - expansion

# What you see is what you get. If you don't like my merchandise, then get the fuck out of my face and stop wasting my time.
{900}{}{Isso é tudo que eu tenho. Se não gosta da minha mercadoria, cai fora dessa porra e não me encha o saco.} 

# Uh, sorry. Let me ask you something else then.
{901}{}{Oh, desculpa. Deixa eu perguntar outra coisa.}

# Right. I think I'll go then.
{902}{}{Beleza. Acho que vou indo então.}

# Actually, I think I'm going to waste *you* and your whole sick fucking operation.
{903}{}{Sabe, eu vou é arregaçar *você* e todo seu esquema podre.}

# This is all I've got in stock here, you picky fuck, but I've always got new merchandise coming in from my other slave camp.
 Maybe if you check back later, I'll have something that tickles your fancy -- but they're mostly ignorant tribals that all look the
 fucking same, so if that's not your thing, you might be shit outta luck.
{910}{}{Isso é tudo que eu tenho, implicante do caralho, mas sempre recebo mercadoria nova do outro campo de escravos. 
 Talvez outro dia eu tenha algo que você se interesse -- mas a maioria são umas porras de índios ignorantes com a mesma maldita cara,
 então se você não curte isso, não vai ter muita sorte.}
 
# Look, this might be an unusual request, but I'd really like to get first dibs on any new merchandise you got. Is there some
 way I could go check out the stock at your other camp? Of course, I'd be willing to pay a premium price.
{911}{}{Olha, pode ser um pedido meio estranho, mas eu gostaria de receber notícias em primeira mão de qualquer mercadoria nova que você 
 conseguir. Tem como eu dar uma olhada no estoque do seu outro campo? Obviamente, me disponho a pagar um bônus pelo serviço.}
 
# Alright, I'll keep checking back then.
{912}{}{Entendi, eu volto outra hora então.} 

# Good, but next time do me a favor and don't waste my time unless you've got actual business to discuss.
{913}{}{Ok, mas da próxima vez me faça o favor de não desperdiçar a porra do meu tempo a não ser que queira discutir negócios de verdade.}

# Premium price, huh? Now you're talking my kinda language. We usually handle sales here, but I suppose an exception could be made,
 as long as you're serious. I'll tell you how to get there, but you better keep it to your fucking self. I swear, if you turn out to be a
 spy for them fucking Rangers, I'll hunt you down and skin you alive. [You listen to his directions, and note the Slaver Camp's location in your Pipboy.]
{914}{}{Pagar um bônus, hã? Agora você falou na minha língua. Nós costumamos fazer as vendas aqui, mas acho que posso abrir uma exceção, 
 se estiver falando sério. Vou te dizer como chegar lá, mas é melhor guardar segredo, porra. Eu juro que se você estiver nos espionando para os viados dos Rangers,
 eu vou te esfolar. [Você ouve ele lhe dando o caminho e anota a localização do Slaver Camp no seu Pipboy.]}
 
# Got it. Let me ask you something else.
{915}{}{Saquei. Deixa eu perguntar outra coisa.}

# Thanks. I'll be on my way now. Bye.
{916}{}{Obrigado. Eu tenho que ir agora. Adeus.}
