# 0. Look
#You see a tough middle-aged slaver.
{100}{}{Você vê um escravista de meia-idade agressivo.}
#You see a rather large slaver.
{101}{}{Você vê um escravista grande.}

#There's a slaver who seems to enjoy his work.
{150}{}{Existe escravista que parece gostar de seu trabalho.}
#This slaver seems to be very strong but not too bright.
{151}{}{Este escravista parece ser muito forte, mas não muito convincente.}

# 1. Metzger's Bedroom Guard (2nd Time = Hostile)
#Get the hell away from the door.
{200}{}{Se afaste logo desta porta caralho!}
#What the fuck do you think your doing?
{201}{}{Que porra é essa que acha que está fazendo?}
#Metzger'll have your head. Back off man.
{202}{}{Metzger arranca sua cabeça. Se afaste, cara.}
#Hey, bitch, get away from that door.
{203}{}{Ei, puta, se afaste dessa porta.}
#No bitch is going in Metzger's room. Back off.
{204}{}{Nenhuma puta vai entrar no quarto de Metzger. Se afaste.}
#Back off, bitch. Slaver or not, Metzger's room is off limits.
{205}{}{Cai fora, cadela. Escravo ou não, é proibido entrar no quarto de Metzger.}

# 2. CF: Generic
#Talk to Metzger, not me, buddy.
{250}{}{Fale com Metzger, não comigo, colega.}
#You going to join the guild?
{251}{}{Vai se associar ao grêmio?}
#There's good money if you're in the guild.
{252}{}{Ganha-se um bom dinheiro se associando ao grêmio.}
#You'll get a lot of action if you're in the guild.
{253}{}{Você vai ter muita ação, se for associado ao grêmio.}
#Talk to Metzger, not me, lady.
{254}{}{Fale com Metzger, não comigo, senhora.}
#Metzger's not going to hire a bitch so beat it.
{255}{}{Metzger não vai contratar uma biscate, portanto cai fora.}
#Beat it.
{256}{}{Cai fora.}
#Hey, man.
{257}{}{Ei, cara.}
#You're lucky you only have to go on the runs.
{258}{}{Você tem sorte de ter que ir só nas ações.}
#Being a door guard's a boring life.
{259}{}{Ser um porteiro é uma vida chata.}
#How's it going?
{260}{}{Como tá indo?}
#You're the first woman Metzger's ever hired.
{261}{}{Você é a primeira mulher que Metzger já contratou.}
#Metzger must have a soft spot for you.
{262}{}{Metzger deve ter uma queda por você.}
#You're all alone little lady.
{263}{}{Você está totalmente só, mocinha.}
#A woman slaver… Never thought I would see it.
{264}{}{Uma mulher escravista. Nunca pensei que veria isso.}
