# 0. Look
# Eu cometi um erro na tradução do arquivo dcVic, onde eu usei o nome da personagem como "Mom". 
#Porém, fica bem claro que é um apelido, e apelidos devem ser traduzidos, se for possível, então a partir desta tradução vou chamá-la de "Mãe" que é mais apropriado. Peço perdão pelo vacilo... =/
#Resposta: ok. Ja foi corrigido!  Att: rsalvarenga;

# You see a kindly-looking older woman.
{100}{}{Você vê uma senhora de aparência bondosa.}

# You see Mom, busily cooking and cleaning.
{150}{}{Você vê Mãe, ela está ocupada com os afazeres caseiros.}

# You see a robust older woman, with a cheerful smile on her face.
{151}{}{Você vê uma senhora robusta, com um sorriso animado no rosto.}

# 1. Low Intelligence (WtG)

# Hello there, I'm Mom. I haven't seen you around here before.
{200}{}{Olá, eu sou a Mãe. Eu nunca te vi por aqui.}

# Hello again. What can Mom do for you?
{201}{}{Olá de novo. O que a Mãe pode fazer por você?}

# Me 
{202}{}{Mim }

# Mmmm. Ook? Bye bye Mommy.
{203}{}{Mmmm. Ook? Tchauzinho Mamãe.}

# 2. Low IQ more (1)

# You already half-ate me out of house and home. Why dontcha find someplace else to hang out for a while? You've eaten here enough today.
{220}{}{Você já comeu quase todo meu estoque. Por que não procura outro lugar para variar um pouco? Já comeu o suficiente aqui por hoje.}

# Well 
{221}{}{Bem }

#  you sure do look as though you're a mite confused. I hate to see a critter suffer. Want something to eat?
{222}{}{ você se perdeu? Odeio ver uma criatura sofrendo. Quer algo para comer?}

# Me full. Mom food good. Bye Mom.
{223}{}{Mim cheio. Comida da Mãe boa. Adeus Mãe.}

# Me pay?
{224}{}{Mim pagar?}

# Me go. Bye Mom.
{225}{}{Mim ir. Adeus Mãe.}

# 3. Pay? (2)

# Well, OK. Whatcha got? (Mom reaches for your purse)
{240}{}{OK. O que você tem? (Mãe tenta pegar sua carteira)}

# Mom? (you hold out your purse)
{241}{}{Mãe? (você segura sua carteira)}

# No! Me go. Bye Mommy.
{242}{}{Não! Mim ir. Adeus Mãe.}

# 4. No, not really (7,9)

# No, not really. I'm sorry. We just have rat-pie, rat-loaf, and spaghetti.
{250}{}{Na verdade, não. Sinto muito. Temos apenas empada de rato, sanduíche de rato, e espaguete.}
 
# What'll it be this time around?
{251}{}{O que vai ser dessa vez?}

# Uh, could I get something without so much rat in it?
{252}{}{Err, você teria alguma coisa com um pouco menos de rato?}

# I guess I'll have the rat-loaf.
{253}{}{Eu quero um sanduíche de rato.}

# I guess I'll have the rat-pie.
{254}{}{Eu quero uma empada de rato.}

# 5. Not so much rat in it (4)

# You could have the spaghetti. It doesn't have too much rat in it - just the sauce, that's all.
{270}{}{Você pode pedir um espaguete. Não tem muito rato nele - só no molho.}

# Well, OK, I guess I'll have the spaghetti with rat-sauce.
{271}{}{Ah, tá bom, acho que vou querer um espaguete ao molho rato.}

# 6. Here's your food (4,5)

# I'll get you a nice helping right away. That'll be $10.
{280}{}{Vou trazer uma ótima porção para você. São $10.}

# I don't have enough money right now. Let me ask you a question instead.
{281}{}{Eu não tenho dinheiro agora. Deixa eu fazer uma pergunta ao invés disso.}

# $10 for rat? You've got to be crazy. Heck, around the village we charge much more for a nice juicy one. That's a deal.
{282}{}{$10 por ratos? Você deve estar louca. Caramba, no meu vilarejo nós cobramos muito mais que isso pelos mais suculentos. Isso que é negócio.}

# Well, OK. Here's your money.
{283}{}{OK. Aqui está o dinheiro.}

# I think I've changed my mind. Let me ask you a question instead.
{284}{}{Acho que mudei de ideia. Deixa eu te fazer uma pergunta.}

# I think I'll come back later. Goodbye.
{285}{}{Eu volto depois. Tchau.}

# 7.  Thanks Mom (6,20)

# You have quite an appetite there. I love to see a healthy eater. Will that do it for you?
{300}{}{Você tem bastante apetite. Eu adoro ver gente com apetite saudável. Isso é o bastante para você?}

# Not a chance, Mom. I want seconds.
{301}{}{Sem chance, Mãe. Eu quero repetir!}

# Sure will. Let me ask you something, Mom.
{302}{}{Claro que sim. Deixa eu perguntar uma coisa, Mãe.}

# That's it for now. Goodbye, Mom.
{303}{}{É o bastante por enquanto. Tchau, Mãe.}

# 8. What's there to do here? (13)

# Well, I sure need someone to deliver a meal to Smitty. He's just west of here at the junkyard. Will you do it for me? I'll give you a free meal if you do.
{303}{}{Bem, eu preciso entregar uma marmita para o Smitty. Ele fica para o oeste daqui, no lixão. Você entrega para mim? Eu te dou um almoço grátis se aceitar.}

# Sure, I don't mind.
{321}{}{Claro, sem problema.}

# Let me think about it. In the meantime, let me ask you about something else.
{322}{}{Me deixe pensar no assunto. Enquanto isso, deixa eu te perguntar uma coisa.}

# Uh, sorry, Mom. I can't. Goodbye.
{323}{}{Oh, desculpa, Mãe. Eu não posso. Adeus.}

# 9. Random Food item list (13)

# You're in luck. We're having radscorpion stew.
{340}{}{Você está com sorte. Nós temos guisado de radscorpion.}

# We're having braised pig-rat.
{341}{}{Temos rato-porco assado.}

# We're serving steamed radscorpion tails in drawn butter.
{342}{}{Estamos servindo rabo de radscorpion cozido com manteiga.}
 
# Cabbage soup is all I've got right now.
{343}{}{A única coisa que temos é sopa de repolho.}

# Fresh brahmin fries!
{344}{}{Brahmin assado!}

# Pipin' hot gecko pie, comin' up.
{345}{}{Tá saindo uma empada de gecko quentinha.}

# Flank steak.
{346}{}{Bife.}

# Well-marbled molerat.
{347}{}{Molerat bem passado.}

# Fricasseed floater.
{348}{}{Fricassé de floater.}

# Filet mignon.
{349}{}{Filé mignon.}

# Medallions of grilled gecko.
{350}{}{Medalhão de gecko grelhado.}

# Mantis marsala.
{351}{}{Pastel de mantis.}

# Molerat manicotti.
{352}{}{Lasanha de molerat.}

# Brahmin en brochette.
{353}{}{Espeto de brahmin.}

# Radscorpion en croute.
{354}{}{Empanado de radscorpion.}

# It's Smeat!
{355}{}{Temos carne!}

# Uh, I'm not sure, but it tastes like chicken.
{356}{}{Err, não sei, mas tem gosto de frango.}

# Centaur chops, my specialty.
{357}{}{Costeleta de centauros, minha especialidade.}

# It's a surprise.
{358}{}{É uma surpresa.}

# I can't give away my secret recipes!
{359}{}{Eu não posso te dar minhas receitas secretas!}

# Really?
{360}{}{Sério?}

# 10. Low IQ hand food (3)

# Here you go. You look half-starved. (Mom hands you a big steaming plate of delicious smelling food.)
{375}{}{Lá vamos nós. Você parece estar morrendo de fome. (Mãe lhe entrega um prato grande cheio de comida com um cheiro delicioso.}

# Tank-u, Mom.
{376}{}{Bigadu, Mãe.}

# 11. Low IQ fed (10)

# There you go. I knew you'd enjoy that.
{385}{}{Aqui está. Sabia que você ia gostar.}
 
# Mmm, yum yum. Bye, Mom.
{386}{}{Mmm, yum umm. Adeus, Mãe}

# 12. Sure I'll deliver it (8)

# Thanks so much. I'd do it myself but there's nobody to watch the place while I'm gone. Here's Smitty's meal. If I didn't have it brought to him I'm sure he'd forget to eat.
{395}{}{Muito obrigado. Eu mesma entregaria mas não tem ninguém para cuidar daqui se eu estiver fora. Aqui está a marmita do Smitty. Se eu não mandasse entregar para ele, tenho certeza que ele esqueceria de comer.}

# I'll bring it right over to him.
{396}{}{Vou levar para ele.}

# 13. Hello (WtG, 6,7,8,15,18)

# I'm so disappointed in you. Poor Smitty had to come get his own meal. Now what do you want?
{405}{}{Estou tão decepcionada. O pobre Smitty teve que vir até aqui buscar a comida. O que você quer agora?}

# Hello there, my name's Mom and I run this place. Got the best food north of New Reno, too.
{406}{}{Oi, meu nome é Mãe e eu sou dona desse lugar. E preparo a melhor comida ao norte de New Reno.}

# What did you want to talk to Mom about?
{407}{}{Sobre o que você quer conversar com a Mãe?}

# Well if it isn't my hero. What can Mom do you for today?
{417}{}{Ah, se não é meu ídolo. O que a Mãe pode fazer por você?}

# You're not my mom.
{408}{}{Você não é minha mãe.}

# Have you heard of a Vault or anyone named Vic?
{409}{}{Você já ouviu falar de alguma Vault ou de alguém chamado Vic?}

# What's there to do here in town?
{410}{}{O que tem para fazer aqui nesta cidade?}

# What do you have to eat here?
{411}{}{O que tem pro rango?}

# 14. I'm not your mom (13)

# I know that. But everyone calls me that. Heck, I even treat people like they're my kin - long as you obey my rules that is.
{425}{}{Eu sei disso. Mas todos me chamam assim. Caramba, eu até trato as pessoas como se fossem da minha família - desde que obedeçam minhas regras, claro.}

# Rules?
{426}{}{Regras?}

# 15. Rules? (14)

# That's right. No stealing, no cursing, and no fighting - not in my shop you don't. 'Cause if'n you do, out you'll go. I like things peaceful here.
{435}{}{Exatamente. Não roubar, não xingar, e não brigar - não no meu estabelecimento. E quem desobedecer, cai fora. Eu gosto de manter a paz aqui.}

# I see. Let me ask you something else.
{436}{}{Entendi. Deixa eu perguntar outra coisa.}

# That makes sense. See you later, Mom.
{437}{}{Faz sentido. Até mais, Mãe.}

# 16. Vic or Vault? (13)

# Well now, there's a Vault City a ways east of here and a little north. And Vic, hmm, lemme think.
{445}{}{Bom, tem uma Vault City para o leste daqui e um pouco para o norte. E Vic, hmm, deixa eu pensar.}

# I sure hope you know where Vic is. He's a trader.
{446}{}{Eu espero que você saiba onde o Vic está. Ele é um comerciante.}

# Thanks but that's all I need to know. Bye, Mom.
{447}{}{Obrigado, mas isso é tudo que preciso saber. Adeus, Mãe.}

# 17. Trader Vic (16)

# Trader Vic? Now that rings a bell. Yes, I think he's being held by Metzger for some reason.
{455}{}{Comerciante Vic? Isso me é familiar. Sim, acho que ele foi capturado pelo Metzger por algum motivo.}

# Who's Metzger and where do I find him?
{456}{}{Quem é Metzger e onde eu posso encontrá-lo?}

# That's great, Mom. Thanks.
{457}{}{Isso é ótimo, Mãe. Obrigado.}

# 18. Who's Metzger (17)

# Metzger's the head of the local Slaver's Guild. He's got all kinds of people locked up in his place. It's right up the street, just north of here.
{465}{}{Metzger é o chefe da Guilda de Escravistas local. Ele tem todo tipo de gente trancafiada lá. É logo no fim da rua, ao norte daqui.}

# Metzger used to be the head of the local Slaver's Guild. He had all kinds of people locked up in his place. But I don't know now - I heard he's been killed.
{466}{}{Metzger era o chefe da Guilda de Escravistas local. Ele tinha todo tipo de gente trancafiada por lá. Mas eu não sei agora - ouvi falar que ele morreu.}

# Thanks for the information. Let me ask you something else, Mom.
{467}{}{Obrigado pela informação. Deixa eu perguntar outra coisa, Mãe.}

# I need to go take care of some business. Thanks, Mom.
{468}{}{Eu preciso resolver uns negócios. Obrigado, Mãe.}

# 19. Smitty's meal in progress (WtG)

# Go on and get that meal to Smitty now.
{475}{}{Vá e entregue a marmita do Smitty.}

# I won't help you out until you keep your word.
{476}{}{Eu não vou te ajudar enquanto não cumprir com sua palavra.}

# Hurry up now.
{477}{}{Vai logo.}

# Go give Smitty his meal. Hurry up.
{478}{}{Vai entregar a marmita do Smitty. Vai logo.}

# Stop your lollygagging and get that meal to Smitty.
{479}{}{Pare de ensebar e leve a marmita do Smitty.} 

# 20. Reward (WtG)

# That was good work. You must have worked up quite an appetite.
I have a real treat for you as a reward. A combination plate of the best
 darn food I have here, just for you.
 
{485}{}{Bom trabalho. Aposto que isso abriu seu apetite. Eu tenho uma refeição para você como recompensa. Uma mistura de tudo que tenho de melhor aqui, especialmente para você.}
 
# That sounds great! Let me at it!
{486}{}{Parece ótimo! Manda pra cá!}

# Gee, Mom. I don't think I can eat just now, but thanks anyhow. Goodbye.
{487}{}{Poxa, Mãe. Acho que não consigo comer agora, mas obrigado mesmo assim. Tchau.}

# 21. What do you know about that haunted house? (13)

# Hmm, don't know much about that. Someone's probably just having
 a little fun, that's all.
{500}{}{Hmm, não sei muito sobre isso. Alguém deve estar fazendo uma pegadinha, acho que é só isso.}

# Has it always been haunted?
{501}{}{Ela sempre foi assombrada?}

# Does anyone use that house?
{502}{}{Alguém usa essa casa?}

# I agree. Bye.
{503}{}{Também acho. Adeus.}

# 22. Started 2 years back… (21)

# Started about 2 years back. I heard about the moaning and the spirits and all.
 Don't believe it myself.
{520}{}{Começou a uns 2 anos atrás. Eu ouvi falar dos grunhidos, dos espíritos e tudo mais. Mas não acredito nessas coisas.}

# Two years, huh? Anybody use the place back then?
{521}{}{Dois anos, ein? Alguém usava a casa antes disso?}

# Me neither. Thanks.
{522}{}{Eu também não. Obrigado.}

# 23. Anyone used it then? (21-22)

# One of the boys used to sleep there a few years back. Maybe he knows something.
{540}{}{Um rapaz costumava dormir lá a alguns anos atrás. Talvez ele saiba de algo.}

# Who?
{541}{}{Quem?}

# Probably not. Bye.
{542}{}{Acho que não. Adeus.}

# 24. Who? (23)

# He used to come by and try to pawn stuff. Jewelry mostly. I remember
 a little gold locket he kept for himself.
{560}{}{Ele sempre vinha aqui para tentar penhorar coisas. Principalmente Jóias. Eu lembro que ele usava um medalhão de ouro.}

# Do you remember his name?
{561}{}{Você lembra o nome dele?}

# Locket? Strange. Who was it?
{562}{}{Medalhão? Estranho. Quem era ele?}

# Let me ask you something else.
{563}{}{Deixa eu perguntar outra coisa.}

# Thanks, bye.
{564}{}{Obrigado, adeus.}

# 25. Name? (24)

# Not sure. Think it was Joseph, Joel or something like that. He's almost 19
 now.... A shame, really. I believe he's joined up with some local thugs.
 {580}{}{Não lembro. Acho que era Joseph, Joel ou algo assim. Ele deve ter uns 19 anos agora... uma pena. Ouvi falar que ele entrou para uma gangue local.}
 
# Thanks. I have another question for you.
{581}{}{Obrigado. Eu tenho outra pergunta.}

# Thanks, bye.
{582}{}{Obrigado, adeus.}

# 13b. PC Response line added to node 13

{600}{}{What do you know about that haunted house?}

# I noticed there seems to be a lot of orphans around town.
{800}{}{Eu percebi que tem um monte de orfãos pela cidade.}
 
It's a shame, isn't it? Those poor children living on the streets like that… A lot of them steal to get by -- from
 outsiders mostly -- so if you catch one trying to relieve you of something, please take pity on 'em. I'm not saying it's
 right, but it's a harsh world we live in, and we all do what we have to in order to make it through the day.
{801}{}{É muito triste, não? Essas pobres crianças vivendo nas ruas desse jeito... muitos deles roubam para sobreviver --
 de forasteiros principalmente - então se pegar algum tentando bater sua carteira ou algo do tipo, tenha piedade. Eu não estou
 dizendo que acho certo, mas vivemos num mundo cruel, e todos precisamos fazer o que for preciso para vermos a luz do dia seguinte.}
 
# There's gotta be something we can do about this. From what I hear, you seem to be the only person around that
 actually gives a damn about those kids.
{802}{}{Deve ter algo que possa ser feito sobre isso. Pelo que ouvi, você parece ser a única pessoa daqui que dá a mínima para as crianças.}

# Why of course I do. Children are our future. They don't *have* to grow up to be jet heads, thugs, and whores like
 most of their deadbeat parents. Why, with an education and some love and care, these kids could grow into the kind of
 decent folk that we so desperately need in this world. I've tried establishing an orphanage for them, but sadly, that
 didn't pan out.
{803}{}{Mas é claro que sim. Crianças são o futuro. Elas não *precisam* crescer para ser viciados em jet, bandidos, ou putas como a maioria de seus pais foram.
 Pois, com educação e um pouco de amor e carinho, essas crianças podem crescer e se tornar pessoas decentes, que estão em falta neste mundo. Eu tentei montar um orfanato para elas,
 mas infelizmente, não deu certo.}
  
# Maybe it's time to give it another try. I'm not going to be in town for too much longer, but I'll do what I can to help while I'm here.
{804}{}{Talvez seja hora de tentar de novo. Eu não vou ficar na cidade por muito tempo, mas farei o que for preciso para ajudar enquanto estiver aqui.}

# That's too bad. Well, nice talking with you. Bye.
{805}{}{Isso é terrível. Foi bom falar com você. Adeus.}

# Yes, perhaps you *could* help. You see, I procured a large building over on the south-west side that, with a little work, would make an excellent
 orphanage. But a bunch of lowlifes are squatting there and refuse to leave unless I pay an absurd fee. Even if I *had* the money, I wouldn't give
 it to them bullies -- they'd just use it to further poison themselves. I'd go to the authorities, but unfortunately, there's no such thing in the Den.
 Perhaps you'd have better luck at convincing them to leave?
{806}{}{Sim, talvez você *pudesse* ajudar. Sabe, eu achei uma casa no lado sudoeste que, com um pouco de trabalho, daria um excelente
 orfanato. Mas um bando de vagabundos tomaram o lugar e se recusam a sair a não ser que eu os pague uma quantia absurda. Mesmo que eu *tivesse* o dinheiro, eu não daria 
 para esses folgados. -- eles gastariam tudo em tóxico. Eu levaria o caso para as autoridades, mas infelizmente, aqui em Den não existe nada isso.
 Quem sabe você se sai melhor tentando convencê-los a sair?}
 
# I'm sure I could get them out of there. One way, or another. I'll let you know once they're gone.
{807}{}{Tenho certeza que eu posso tirá-los de lá. De um jeito, ou de outro. Eu te aviso quando eles forem embora.}

# Never was a fan of evicting people. Perhaps someone else is better suited for this.
{807}{}{Não sou muito fã de expulsar gente de suas casas. Talvez você encontre alguém mais adequado para essa tarefa.}

# Oh... I see. That's really too bad. Thanks for trying though. Would you like anything before you go?
{809}{}{Ah... eu entendo. Que pena. Mas obrigado por tentar. Você gostaria de mais alguma coisa antes de ir?}

# Nope. Bye Mom.
{810}{}{Não. Adeus Mãe.}

#added by killap - RP 1.3

# If I catch one of them little bastards stealing from me, it'll be the last thing they ever do. I don't care what
 their excuse is, a thief is a thief. Bye.
{811}{}{Se eu pegar um desses merdinhas roubando de mim, mando direto pro inferno. Eu não ligo para qual desculpa eles 
 usam, ladrão é ladrão. Adeus.}

# Good news, Mom. The building's all yours. I ran into a little snag, but those squatters won't be bothering you again.
{820}{}{Tenho boas notícias, Mãe. A casa é toda sua. Eu tive um pouco de trabalho, mas aqueles vagabundos não vão mais te perturbar.}

# The squatters said they'd leave and that they're sorry for causing trouble. They're currently cleaning the place up to try and make it up to you. I was thinking maybe, if they do well enough, you could offer some of them jobs.
{821}{}{Os vagabundos disseram que vão embora e que sentem muito pelos problemas que eles causaram. Eles estão limpando o lugar para entregar para você. Eu acho que talvez, se eles forem bem o bastante, você poderia oferecer empregos para alguns deles.}

# Good news, Mom. The building's all yours. It took a little convincing, but I got the squatters to agree to pack up and move on.
 I don't think they'll be bothering you again.
{1821}{}{Tenho boas notícias, Mãe. A casa é toda sua. Foi difícil convencê-los, mas os vagabundos concordaram em ir embora.}

# Oh, that's great news! Thank you so much! I just hope no one was hurt in the process. I'll get in touch with some friends and we'll get
 started right away. If you're still in town a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh,
 I'm so excited! Thanks again. Here, this meal's on me.
{822}{}{Ah, mas que boa notícia! Muito obrigada! Eu espero que ninguém tenha se machucado. Vou avisar uns amigos e vamos começar os preparos imediatamente.
 Se você ainda estiver na cidade nos próximos dias, passe lá. Com sorte, até lá as coisas já estarão prontas. Ah, estou tão empolgada! Obrigada de novo.
 Aqui, essa refeição é por minha conta.}
 
# Oh, that's great news! Thank you so much! I'll get in touch with some friends and we'll get started right away. If you're still in town
 a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh, I'm so excited! Thanks again. Here, this meal's on me.
{1822}{}{Ah, mas que boa notícia! Muito obrigada! Vou avisar uns amigos e vamos começar os preparos imediatamente.
 Se você ainda estiver na cidade nos próximos dias, passe lá. Com sorte, até lá as coisas já estarão prontas. Ah, estou tão empolgada! Obrigada de novo.
 Aqui, essa refeição é por minha conta.}
 
# Hmm... I suppose everyone deserves a second chance. I'll stop over there with some friends and we'll talk things over with 'em. Thank you so much
 for helping me with this. If you're still in town a few days from now, you should stop by. Hopefully, we'll have things up and running by then. Oh, I'm so
 excited! Thanks again. Here, this meal's on me.
{823}{}{Hmm... Acho que todo mundo merece uma segunda chance. Vou levar uns amigos para lá e conversaremos com eles. Muito obrigada por me ajudar com isso.
 Se você ainda estiver na cidade nos próximos dias, passe lá. Com sorte, até lá as coisas já estarão prontas. Ah, estou tão empolgada! Obrigada de novo.
 Aqui, essa refeição é por minha conta.}
 
# Thanks Mom. See you around.
{824}{}{Obrigado Mãe. Eu te vejo por aí.}

# You help establish an orphanage for the children of The Den.
{850}{}{Você ajudou a estabelecer um orfanato para as crianças de Den.}