You see a child.
{100}{}{Você vê uma criança.}
You see a child. He seems happy.
{101}{}{Você vê uma criança. Ele parece feliz.}
You see a child. She seems happy.
{102}{}{Você vê uma criança. Ela parece feliz.}

#Hi mister!
{200}{}{Oi senhor!}
#Sorry for trying to steal from you.
{201}{}{Desculpe por tentarem roubar de você.}
#I really like it here.
{202}{}{Eu realmente gosto daqui.}
#Thanks for helping Mom start this place!
{203}{}{Obrigado por ajudar a Mãe começar a este lugar!}

#Hi ma'am!
{300}{}{Oi senhora!}
#Sorry for trying to steal from you.
{301}{}{Desculpe por tentarem roubar de você.}
##I really like it here.
{302}{}{Eu realmente gosto daqui.}
##Thanks for helping Mom start this place!
{303}{}{Obrigado por ajudar a Mãe começar a este lugar!}

