#############################################################
#                                                           #
#  Message File: dcPetey.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 12, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and examined.                                    #
#############################################################
#You see a drug addict.
{100}{}{Você vê um viciado em drogas.}
#You see Petey.
{101}{}{Você vê Petey.}

#This here is a poor drug addict.
{150}{}{Isse aqui é um viciado em drogas pobres.}
#Petey here looks like he could use some help.
{151}{}{Parece que Petey quer uma ajuda.}
#talk
{152}{}{[conversa]}
#[cough, cough] Any spare change for Petey?
{155}{}{[cof, cof] Qualquer trocado para Petey?}
#Sure, here ya go.
{156}{}{Claro, aqui vamos nós.}
#No, get away from me.
{157}{}{Não, ficar longe de mim.}
{158}{}{Peewee?}
#You're worse off than me. [cough] Thanks anyway.
{159}{}{Você é pior do que eu. [tosse] Obrigado mesmo..}
#Sorry; bye.
{160}{}{Desculpe; tchau.}
#Duh, you are welcome, uh-huh, yeah.
{161}{}{Duh, você é bem-vindo, uh-huh, sim.}
#Maybe next time. Thank you anyway. [cough]
{162}{}{Talvez na próxima vez. Obrigado de qualquer maneira. [tosse]}
#[done]
{163}{}{[feito]}
#Thank you so much. [cough] So, so, so very much.
{164}{}{Muito obrigado. [tosse] Por isso então}
#You're welcome.
{165}{}{De nada}
{166}{}{Yeah, yeah.}
#Sir, [cough] can you help a poor man down on his luck?
{167}{}{Sr, [tosse] você pode ajudar um pobre homem sem sorte?}
#Here's $5.
{168}{}{Tome $5.}
#Not today
{169}{}{Hoje não}
#Get a job.
{170}{}{Arranje um emprego.}
#Kind lady, please help [cough] a poor, starving man who is [cough] too sick to work.
{171}{}{Amável senhora, por favor me ajude [tosse] um pobre faminto homem que está [tosse] muito doente para trabalhar.}
#You poor thing, here's $5.
{172}{}{Você é um coitadinho, aqui está US $ 5..}
#I make a point of not giving money to panhandlers.
{173}{}{Eu faço questão de não dar dinheiro para mendigos.}
#No.
{174}{}{Não.}
#Sorry, I don't have any money on me.
{175}{}{Desculpe, eu não tenho nenhum dinheiro comigo.}

#Hey, man; give me some money?
{200}{}{Ei, cara; me dar algum dinheiro?}
#Spare some change, kind sir?
{201}{}{Spare alguma mudança, gentil senhor?}
#Hey, can you help me with a few bucks?
{202}{}{Ei, você pode me ajudar com alguns dólares?}
#Do you think you can help me out with coupla bucks?
{203}{}{Você acha que você pode me ajudar com dinheiro?}
#Do you think you could lend me a few bucks?
{204}{}{Você acha que você poderia me emprestar algum dinheiro?}
#Spare some change, kind lady? 
{205}{}{Spare alguma mudança, amável senhora?}
#Hey, lady; spare some money?
{206}{}{HEi, senhora; sobrou algum dinheiro?}

#Please help me, sir.
{220}{}{Por favor, ajude-me, senhor.}
#Ahhh, it hurts.
{221}{}{Ahh, que dó.}
#I need help. It hurts bad.
{222}{}{Eu preciso de ajuda. Isso é ruim.}
#Lady, can you get me some help?
{223}{}{Senhora, você pode me ajudar a obter algum?}
#I greatly appreciate that.
{225}{}{Eu aprecio muito isso.}
#Hey, what do you think you're doing?
{226}{}{Ei, o que você acha que está fazendo?}

#Feels so good.
{230}{}{Sinto tão bem.}
{231}{}{Uhhh...}
#giggle
{232}{}{[risadinha]}
{233}{}{Hey...}
#Niiicceee...
{234}{}{Bom ....}
#Oh yeah...
{235}{}{Oh sim ...}

#dealer dead messages
#tubby dead

#I can't believe someone fucking killed Tubby...
{300}{}{Eu não posso acreditar que alguém matou Tubby porra ...}
#What the fuck happened to Tubby?
{301}{}{Que diabos aconteceu com Tubby?}
#Ah, why did Tubby have to die.
{302}{}{Ah, por que Tubby tem que morrer.}
#generic
{303}{}{Ahhh...}
#Didn't like that asshole anyway.
{304}{}{Não gostou de babaca de nenhuma maneira .}
#flick dead
#Flick's dead...Crap.
{305}{}{Morto ... Crap Flick.}
#What happened to Flick?
{306}{}{O que aconteceu com Flick?}
#I miss Flick...
{307}{}{Eu sinto falta do Flick ...}

#dealer far, ask for assistance
#ask tubby
#Hey Tubby, I..uhhh.. need some help here.
{310}{}{Ei Tubby, I..uhhh .. preciso de alguma ajuda aqui.}
#HEY TUBBY
{311}{}{EI TUBBY!}
#ask any
#Hello.
{312}{}{Ola.}
#HEY!
{313}{}{EI!}
#ask flick
#Hey Flick, I..uhhh..need some help here.
{314}{}{Ei Flick, Eu..uhhh .. preciso de uma ajuda aqui.}
#HEY FLICK
{315}{}{EI FLICK!}

#ask dealer for drug messages
#from tubby
#Hey Tubby, can you hook me up? I've got cash.
{320}{}{Ei Tubby, você pode me deixar doidão? Eu tenho dinheiro.}
#Ummm, Tubby, I've got some money
{321}{}{Ummm, Tubby, eu tenho algum dinheiro}
#from any
{322}{}{Uhhh...}
#I need a fix man.
{323}{}{Preciso de um homem honesto.}
#from flick
#Hey, Flick; can you hook me up? I've got cash.
{324}{}{Ei, Flick; você pode me deixa doidão? Eu tenho dinheiro.}
#Ummm, Flick, I've got some money
{325}{}{Ummm, Flick, eu tenho algum dinheiro}
#thank dealer for drugs messages
#thank tubby
#Uhhh... Thanks again, Tubby.
{330}{}{Uhhh ... Obrigado novamente, Tubby.}
#You're a pal, Tubby.
{331}{}{Você é um amigão, Tubby.}
#thank generic
#I promise. I'm gonna kick tomorrow.
{332}{}{Eu prometo. Eu vou me divertir amanhã.}
#You're a pal.
{333}{}{Você é um amigão..}
#thank flick
#Uhhh... Thanks again, Flick
{334}{}{Uhhh ... Obrigado novamente, Flick}
#You're a pal, Flick.
{335}{}{Você é um amigão, Flick.}
#response from Tubby/Flick
#Here. Now beat, you druggie.
{340}{}{Aqui, drogado pode usar.}
#Take it and get the hell out.
{341}{}{Pode usar e de o fora.}
