#You see a resident of The Den.
{100}{}{Você vê um morador de Den.}
#You see a resident of The Den.
{101}{}{Você vê um morador de Den.}
#Hello.
{102}{}{Olá.}
#Nice to see you.
{103}{}{Prazer te conhecer.}
#Not from around here, are you?
{104}{}{Não é daqui, não é?}
#Mom is a great lady, isn't she?
{105}{}{Mamãe é uma grande mulher, não é?}
#I'm glad the orphans of The Den have a place to live now.
{106}{}{Estou contente que os órfãos do Esconderijo tem um lugar para viver agora.}

#You see a small boy.
{400}{}{Você vê um menino pequeno.}
#You see a small girl.
{401}{}{Você vê uma menina pequena.}

#Hi mister!
{200}{}{Oi senhor!}
#I'm glad the other kids aren't stealing anymore.
{201}{}{Fico feliz que as outras crianças não estão roubando mais.}

#Hi miss!
{300}{}{Oi senhorita!}
{301}{}{Fico feliz que as outras crianças não estão roubando mais.}
