# 0. Look
#You see a slaver.
{100}{}{Você vê um escravista.}

#He seems to be very alert.
{150}{}{Ele parece estar bem atento.}

# 1. Messed with Door 2nd Time
#Touch that again and you'll lose a limb.
{200}{}{Toque nisso de novo e vai perder um dedo.}
#That's it!
{201}{}{É isso aí!}

# 2. CF: Not Slaver
#Nothing but the slaves are back there.
{210}{}{Somente os escravos estão lá.}
#The slaves don't get visitors.
{211}{}{Escravos não recebem visitas.}
#Only guild members through this door.
{212}{}{Somente membros do grêmio passam por esta porta.}
#You lookin' for a slave? Talk to Metzger.
{213}{}{Está procurando por um escravo? Fale com Metzger.}
#Talk to Metzger. Slave pens are off limits.
{214}{}{Fale com Metzger. Não é permitido entrar nos currais de escravos.}
#What are you wandering around here for? Beat it.
{215}{}{Por que está andando por aqui? Cai fora.}
#Beat it, bitch. Slaves get no visitors.
{216}{}{Cai fora, cadela. Escravos não recebem visitas.}

# 3. CF: Slaver
#How's it going, buddy?
{230}{}{Como está indo, colega?}
#Little slow today.
{231}{}{Um pouco calmo hoje.}
#Hope you're liking the guild.
{232}{}{Espero que você esteja gostando da associação.}
#Your tat came out well.
{233}{}{Com sua malícia foi muito bem.}
#Did you go on that last run?
{234}{}{Você foi na última rodada?}
#Hi.
{235}{}{Oi.}
#You're my kind of lady.
{236}{}{Você é meu tipo de mulher.}
#A female slaver - got to respect that.
{237}{}{Uma traficante de escravos feminina - tem que se respeitar isso.}
#Hi there.
{238}{}{Olá, olá.}
#Looking good.
{239}{}{De boa aparência.}
