#You see a resident of The Den.
{100}{}{Você vê um residente de Den.}
#You see a resident of The Den.
{101}{}{Você vê um residente de Den.}

#Hello and welcome to- Hey! You're the one who helped make this place possible. The people of the Den really appreciate what you have done.
{200}{}{Olá e bem-vindo à... Ei! Você é o que ajudou tornar este lugar possível. As pessoas do Esconderijo realmente agradece o que fez.}
#It was my pleasure. How are the children?
{201}{}{O prazer foi meu. Como estão as crianças?}
#They're doing fine. Thanks to you, they're off the streets and now have a place to live. The squatters you negotiated with are also a big help around here. Thanks again for everything!
{202}{}{Eles estão indo bem. Graças a você, eles estão fora das ruas e agora têm um lugar para viver. Os posseiros com quem você fez negociações, são também de grande ajuda por aqui. Obrigado de novo por tudo.}
#They're doing fine. Thanks to you, they're off the streets and now have a place to live. Thanks again for everything!
{203}{}{Eles estão indo bem. Graças a você, eles estão fora das ruas e agora têm um lugar para viver. Mais uma vez obrigado por tudo!}
#Glad to hear it. Take care.
{204}{}{Fico feliz em ouvir isso. Se cuidem.}
#Hello again! Help you with something?
{205}{}{Olá de novo! Posso ajudar com alguma coisa?}
#Nope, just looking around.
{206}{}{Nada não, apenas olhando ao redor.}
