#0. Look
#You see a guard.
{100}{}{Você vê um guarda.}
#You see a guard for Becky's Casino Bar.
{101}{}{Você vê um guarda do Bar Cassino de Becky.}
#He seems to be eyeing the crowd for thieves.
{150}{}{Ele parece estar de olho na multidão por ladrões.}
#She seems to be keeping a close eye on everyone in the room.
{151}{}{Ela parece estar de olhar atento em todos na sala.}

#1. Hostile
#Now you'll get it.
{200}{}{Agora você vai ganhar.}
#You're not getting away this time.
{201}{}{Você não vai muito longe dessa vez.}

#2. CF: Generic
#Sorry, Becky doesn't want us disturbing the customers.
{210}{}{Desculpe, mas Becky não quer que incomodamos os clientes.}
#Hope you're enjoying yourself.
{211}{}{Espero que estejam se divertindo.}
#Rest assured, we have a zero tolerance policy for thievery.
{212}{}{Fique bem certo que, temos uma política de tolerância zero para roubo.}
#You're safe inside these walls.
{213}{}{Você está seguro dentro destas paredes.}
#Rebecca has the best drinks.
{214}{}{Rebecca tem as melhores bebidas.}
#Rebecca's the best boss I've ever had.
{215}{}{Rebecca é a melhor chefe que já tive.}
#You feeling lucky tonight? Blackjack's my game.
{216}{}{Está se sentindo com sorte esta noite? Meu jogo favorito é o Blackjack.}
#Becky's right over there, if you need anything.
{217}{}{Becky está bem ali, se precisar de alguma coisa.}
#Rebecca's tables are honest, so try your luck.
{218}{}{A mesas de Rebecca são honesta, portanto tente sua sorte.}

#3. Self: Caught Stealing
#We don't tolerate that here.
{230}{}{Não toleramos isso aqui.}
