# 0. Look
#You see a very attractive young lady.
{100}{}{Você vê uma jovem mulher muito atraente.}
#You see Rebecca.
{101}{}{Você vê Rebecca.}

{150}{}{You see Rebecca, the owner of Becky's Casino Bar.}

# 1. Greetings (From WTG)
#Hi there, I'm Rebecca. Can I get you something to drink? I'm sure you're thirsty
 after your trip through the wastes.
{200}{}{Oi lá, eu sou Rebecca. Posso arranjar-lhe algo para beber? Tenho certeza que você está com sede
após a sua viagem pelos resíduos.}
#Hey! You want a drink or did you just come back to say hi?
{201}{}{Ei Você quer uma bebida ou você simplesmente voltou para dizer oi?}
#Hi! Glad you came back. Any questions or are you here for some fine whiskey?
{202}{}{Oi! Que bom que você voltou. Todas as perguntas ou você está aqui para bebe bom whiskey?}
#Really glad to see you. What's up? Need something?
{203}{}{Realmente fico feliz em vê-lo. O que está acontecendo? Precisa de alguma coisa?}
#Hope everything's going well for my favorite customer! What can we do for you today?
{204}{}{Espero que tudo esteja indo bem para o meu cliente favorito! O que podemos fazer por você hoje?}
#Hello!
{205}{}{Olá!}
#Always nice to see you again.
{206}{}{É sempre bom vê-lo novamente.}
#Hi! You care for a drink? Finest whiskey in the land!
{207}{}{Oi! Você se importa com bebida? Finest whískey da terra!}
#Hi there!
{208}{}{Oi!}
#It's you! I thought so. How about a drink, my honey?
{209}{}{É você! Eu pensei assim. Que tal uma bebida, minha querida?}
#You back for some of Rebecca's great entertainment or the world famous whiskey?
{210}{}{Você de volta para o grande entretenimento de Rebecca ou para bebe o famoso whiskey do mundo?}
#Welcome back to Rebecca's Bar and Casino. How can I help you?
{211}{}{Bem-vindo de volta ao bar e casino de Rebecca. Como posso ajudá-lo?}
#Hello. How can we help you?
{212}{}{Olá. Como podemos ajudá-lo?}
#Something for you today? How about a drink?
{213}{}{Algo para você hoje? Que tal uma bebida?}
#Would you care for a drink today, or perhaps something else?
{214}{}{Gostaria de tomar uma bebida hoje, ou talvez algo mais?}
#How can I be of service?
{215}{}{Como posso ser útil?}
#Greetings. What can we get you?
{216}{}{Saudações. O que podemos fazer por você?}
#Need something?
{217}{}{Precisa de alguma coisa?}
#Nice to see you again. How can I help you today?
{218}{}{Prazer em vê-lo novamente. Como posso ajudá-lo hoje}
#What?
{219}{}{O Quê?}
#Yes?
{220}{}{Sim?}
#Now what?
{221}{}{E agora?}
#Please keep it short. It's a busy day. What do you need?
{222}{}{Por favor, mantenha a calma. É um dia agitado. O que você precisa?}
#What can I do for you? I'm really busy.
{223}{}{O que posso fazer para você? Estou muito ocupado.}
#You here for a drink? The tables are over there.
{224}{}{Você aqui quer uma bebida? As mesas estão lá.}
#I'm really not in the mood. What now?
{225}{}{Eu realmente não estou no clima. E agora?}
#You're back already? I guess you want a drink then?
{226}{}{Você está de volta já? Eu acho que você quer beber, então?}

# 2. Prelude to questions (From ?)
#Sure, handsome.
{240}{}{Claro, bonito.}
#What would you like to know?
{241}{}{O que você gostaria de saber?}
#I'd be happy to.
{242}{}{Eu ficaria feliz.}
#But of course.
{243}{}{Mas, é claro.}
#Sure.
{244}{}{Claro.}
#I don't mind.
{245}{}{Eu não me importo.}
#I'll help if I can.
{246}{}{Eu vou te ajudar se eu puder.}
#Of course, don't be silly.
{247}{}{É claro, não seja bobo.}
#Anything. Now what was it?
{248}{}{Qualquer coisa. Agora, o que era?}
#I'll do my best to help you out. What did you need to know?
{249}{}{Eu vou fazer o meu melhor para ajudá-lo. O que você precisa saber?}
#Ask away.
{250}{}{Peça a distância.}
#If you insist.
{251}{}{Se você insistir.}
#I guess so.
{252}{}{Eu acho que sim.}
#Let's keep it short. I have a business to run.
{253}{}{Vamos mantê-lo calma. Eu tenho um negócio para ser executado.}
#Well, okay. What is it?
{254}{}{ok, tudo bem. O que é isso?}
#I suppose.
{255}{}{Eu suponho.}
#What?
{256}{}{O quê?}
#No, sorry.
{257}{}{Não, desculpe.}
#Not right now.
{258}{}{Agora não.}

# 3. Questions (From 1-2)
#I need a drink.
{270}{}{Preciso de uma bebida.}
#I'm looking for a merchant who sells Vault equipment. 
{271}{}{Estou à procura de um comerciante que vende equipamentos do Vault.}
#I'm looking for a merchant named Vic.
{272}{}{Estou à procura de um mercador chamado Vic.}
#Do you have any work?
{273}{}{Você tem alguma trabalho?}
#About that job...
{274}{}{Sobre esse trabalho ...}
#Any more work for me?
{275}{}{Tem mais trabalho para mim?}
#Nothing. Bye.
{276}{}{Não há nada. Tchau.}
{277}{}{Wekee.}
{278}{}{Ruh ruh?}
{279}{}{Iho shasha.}
{280}{}{dy.}
{281}{}{Ruh ruh?}

# 4. Whiskey (From 3)
#Whiskey is my specialty. It's almost a tradition in the Dyer family. I charge the
 low, low price of only $5.
{300}{}{O whiskey é a minha especialidade. É quase uma tradição na família Dyer. Eu vendo a preço baixo por apenas US $ 5.}
#Drinks are still $5, and the Dyer family makes the best darn drinks in the whole world.
{301}{}{As bebidas ainda estão a US $ 5, e da família Dyer fazem as melhores bebidas de todo o mundo.}
#You okay? You want whiskey? Only $5.
{302}{}{Você está bem? Você quer whiskey? Por apenas US $ 5.}
#I'll take a drink.
{303}{}{Eu vou tomar uma bebida.}
#Why are your drinks so cheap?
{304}{}{Por que suas bebidas são tão baratas?}
{305}{}{Dyer?}
#Can I ask a question?
{306}{}{Posso fazer uma pergunta?}
#Bye.
{307}{}{Tchau.}
{308}{}{Wekee}
{309}{}{Urka.}

# 5. Dyer (From 4)
#Oh, that's the family name. The name Dyer has been in the bar business for a
 long time - prewar times, of course.
{320}{}{Oh, este é o nome da família. O nome Dyer tem sido no negócio de bar por muito tempo - antes da guerra, é claro.}
#As I said, it's my family name. There used to be Dyer pubs, saloons or something,
 all over the world.
{321}{}{Como eu disse, esse é o nome da minha família. Existiam muitos bares Dyer ou algo assim,
  em todo o mundo.}
#I'll take a drink.
{322}{}{Eu vou tomar uma bebida.}
#Can I ask another question?
{323}{}{Posso te fazer outra pergunta?}
#Bye.
{324}{}{Tchau.}

# 6. Why drinks are so cheap (From 5)
#Well, since you're such a good customer, I'll let you in on a little secret.
 It's simple really - I have a still. A friend from a nearby town taught me how to
 make one. So, would you like another one?
{330}{}{Bem, já que você é um bom cliente, eu vou te contar um pequeno segredo.
É muito simples - Eu tenho um amigo de uma cidade vizinha que me ensinou a
fazer um. Então, você gostaria de um outro?}
#Sorry, it's a trade secret. Plus, I don't really know you that well. I wouldn't
 want Frankie finding out. He's enough trouble as it is. Did you still want one? They
 really hit the spot.
{331}{}{Desculpe, é um segredo comercial. Além disso, eu realmente não te conheço bem pra te contar o segredo. Não te contaria pois
Frankie quer descobrir. Ele já é um problema pra mim. Será que você ainda quer um? eles
fazem sucesso na região.}
#Sure. I'll have one.
{332}{}{Claro. Eu vou querer um.}
#Can I ask another question?
{333}{}{Posso fazer outra pergunta?}
#Okay, thanks.
{334}{}{Ok, obrigado.}

# 7. Drinking (From 4-6)
#There you are. Thank you very much.
{340}{}{Aí está você. Muito obrigado.}
#Thanks. Can I ask you a question?
{341}{}{Obrigado. Posso te fazer uma pergunta?}
#Okay, thanks.
{342}{}{Ok, obrigado.}
{343}{}{Thankey youey.}
{344}{}{Asky?}

# 8. (From )
#Sorry. I don't think so.
{350}{}{Desculpe. Eu não penso assim.}
#Fred owes me $200. If you can collect it somehow, we'll work something out.
{351}{}{Fred me deve US $ 200. Se você pode cobrá-lo de alguma forma, poderiamos dar um jeito.}
#I still have that debt I need collected.
{352}{}{Eu ainda tenho essa dívida Preciso ter pequenos negocios.}
#Derek borrowed a book of mine a while back. I'll pay $80 if you can get it
 back for me.
{353}{}{Derek pegou emprestado um livro meu há um tempo atrás. Eu vou pagar 80 dólares se você conseguir cópia para mim.}
#I'm still looking for that book of mine.
{354}{}{Eu ainda estou procurando esse livro.}
#What's the catch?
{355}{}{Qual é o truque?}
#Tell me more.
{356}{}{Conte-me mais.}
#Can I ask you a question?
{357}{}{Posso te fazer uma pergunta?}
#Bye.
{358}{}{Tchau.}

# 9. Job 1 & 2 Introductions (From 8)
#Catch? Oh, well, if you knew Fred you'd understand. He's owed me the money
 for quite a long time. I'd written it off as a loss, but if you can get it back, I'd be
 amazed... and grateful. He's somewhere in town, I'm sure.
{370}{}{Catch? Oh, bem, se você soubesse o que o Fred fez você entenderia. Ele me devia dinheiro
  por muito tempo. Eu tinha escrito como uma perda, mas se você pode traze-lo de volta, eu ficaria
  espantada ... e grata. Ele está em algum lugar na cidade, tenho certeza.}
#The book was The Lavender Flower. Derek s hould be over around Mom's on the east side.
{371}{}{O livro era a flor Lavanda. Derek deve estar ao redor da mamãe no lado leste.}
#I'll see what I can do.
{372}{}{Vou ver o que posso fazer.}
#Sure sounds easy.}
{373}{}{Claro que parece fácil.}
#I already found it.
{374}{}{Eu já encontrei.}
#I'll have to get back to you.
{375}{}{Vou ter que voltar para você.}

# 10. (From 3, )
#You didn't really get it did you? I'd   ,be amazed.
{385}{}{Você realmente não entendeu não é? Eu, me surpreendir..}
#Oh, did you find my book? Derek better not have messed it up.
{386}{}{Oh, você achou meu livro? É melhor que o Derek não estraguei tudo.}
#Yes, I did.
{387}{}{Sim, eu fiz.}
#I'm sorry. He's dead.
{388}{}{Sinto muito. Ele está morto.}
#Sorry, but Derek's also dead.}
{389}{}{Desculpe, mas de Derek também morto.}
#I'm sorry, but he's dead.
{390}{}{Sinto muito, mas ele está morto.}
#Yes. Here it is.
{391}{}{Sim. Aqui está.}
#No, sorry.
{392}{}{Não, desculpe.}

# 11. Finished Job 1 or 2 (From 10)
#I can't believe it. How did you do it? Oh, never mind. I'm just stunned,
 that's all. To show my appreciation, I'll split it with you, right down the
 middle. Thank you again, that was very honest of you.
{400}{}{Eu não posso acreditar nisso. Como você fez isso? Oh, não importa. Eu sou apenas atordoada,
  com isso tudo. Para mostrar o meu apreço, vou dividi-lo com você, até o
  meio. Obrigado mais uma vez, por você ser uma pessoa honesta.}
#Oh, I'm so glad you were able to find it… Thank you very much. Here's your money.
{401}{}{Oh, eu estou tão feliz que você conseguiu encontrá-lo ... Muito obrigado. Aqui está o seu dinheiro.}
#You're welcome.
{402}{}{De nada.}

# 12. Deaths (From 10)
#I can't believe they are both dead. I'm sorry. Thank you for finding out for
 me. If you'll excuse me...
{410}{}{Eu não posso acreditar que eles estão mortos. Sinto muito. Obrigado por descobrir por
  me. Se você me dá licença ...}
#I can't believe he's dead... after all these years.
{411}{}{Eu não posso acreditar que ele está morto ... depois de todos esses anos.}
#Sure.
{412}{}{Claro.}
{413}{}{...}

# 13. Vic (From 3)
#Yeah, I know who that is. That's Vic - the guy Metzger has locked up.
{420}{}{Sim, eu sei quem é. É Vic - o cara Metzger aprisionou.}
#Yeah, I know Vic. Metzger's got him locked up. I'm not sure why though.
{421}{}{Sim, eu sei Vic. Metzger está com ele preso. Eu não sei o por que.}
#Who's Metzger?
{422}{}{Quem é Metzger?}
#I have another question.
{423}{}{Tenho outra pergunta.}
#Great! Bye.
{424}{}{Otimo! tchau.}

# 14. Who's Metzger (From 13)
#You came to the Den and you don't know who Metzger is? He's the slave master.
 He's on the east side of town. Hard to miss.
{430}{}{Você veio para o Den e você não sabe quem é Metzger? Ele é o senhor de escravos.
  Ele está no lado leste da cidade. Difícil de ser perder.}
#I have another question.
{431}{}{Tenho outra pergunta.}
#Thanks.
{432}{}{Obrigado.}

# 15. CF: Hostile & Childkiller (From WTG)
#Murderer!
{440}{}{Assassino!}
#Childkiller!
{441}{}{Assassino de crianças!}
#Please leave.
{442}{}{Por favor, deixe.}
#I won't deal with the likes of you.
{443}{}{Eu não vou tratar com tipo gente como você.}
#I'm not going down without a fight!
{444}{}{Eu não estou indo sem uma luta!}

# 16. Buffy 1 (From WTG)
#Buffy! It's you! How are you? It's been a long time!
{450}{}{Buffy! É você! Como você está? Faz um longo tempo!}
{451}{}{Huh?}
{452}{}{Huh?}

# 17. Buffy 2 (From 16)
#Dave sends his best and wishes he could be here to say hi, but he had to run off.
{460}{}{Dave faria seu melhor e gostaria de poder estar aqui para dizer oi, mas ele teve que fugir.}
#Where to?
{461}{}{Onde?}

# 18. Buffy 3 (From 17)
#Something about a commando... or that he was going after a commando. Not sure
 exactly. Something like that.
{470}{}{Algo sobre um comando ... ou que ele estava indo atrás de um comando. não tenho certeza
  exatamente. Algo assim.}
{471}{}{Oh.}

# 19. Buffy 4 (From 18)
#Oh, he said to give you this. It's a present from the Hendee family. It should
 help you out some.
{480}{}{Oh, ele disse para lhe dar isso. É um presente da família Hendee. deveria
ajudá-la em algum.}
#What is it?
{481}{}{O que é isso?}

# 20. Buffy 5 (From 19)
#Oh, just a few trinkets. Here you go. [Becky hands you $1000, 5 Stimpaks,
 Metal Armor, an Uzi, 5 clips of ammo, a Plasma Grenade, and a flower]
{490}{}{Oh, apenas algumas bugigangas. Aqui você vai. [Becky entrega-lhe US $ 1000, 5 Stimpaks,
  Metal Armor, uma Uzi, 5 pete de munição, uma granada de plasma, e uma flor]}
#Thanks!
{491}{}{Obrigado!}

# 21. Buffy 6 (From 20)
#No problem. I was just holding them for you. Well, I better get back to work.
{500}{}{Sem problemas. Eu estava apenas segurando-os para você. Bem, é melhor eu voltar ao trabalho.}
#Thanks, bye.
{501}{}{Obrigado, Tchau.}

# 22. Metzger's Dead! (From WTG)
#Didn't you hear! He's dead! Oh, I know I shouldn't be happy, but he was a very
 evil man.
{510}{}{Você não ouviu! Ele está morto! Oh, eu sei que não deveria estar feliz, mas ele era homem muito
  mau.}
#He sure put up a good fight.
{511}{}{Ele com certeza fez uma boa luta.}
#I have a question.
{512}{}{Eu tenho uma pergunta.}
#Yes, he was. Goodbye.
{513}{}{Sim, ele estava. Adeus.}
#kill!
{514}{}{ matem!}

# 23. Metzger's dead 2 (From 22)
#What? You? I... don't know what to say. He was such an evil man...
{520}{}{O Quê? Você? Eu ... não sei o que dizer. Ele era como um homem mau ...}
#A thank you would be enough.
{521}{}{Um agradecimento você para seria o suficiente.}
#Humph
{522}{}{Hum.}

# 24. Metzger Reward (From 23)
#Oh, a thank you would be enough. I know this isn't right but... here, take this
 money. [Becky gives you 1000 dollars]
{530}{}{Oh, um agradecimento seria suficiente. Eu sei que isso não é certo, mas ... aqui,esta aproveite o
  dinheiro. [Becky dá-lhe 1000 dólares]}
#Keep your money, Rebecca.
{531}{}{Guarde seu dinheiro, Rebecca.}
#Thank you very much.
{532}{}{Muito obrigado.}
{533}{}{Tank!}
#Ug! Perdy lady.
{534}{}{Muito obrigado.}

# 25. Metzger's Dead No reward, Gain Karma (From 24)
#You are wonderful man. Even though I don't condone your actions. You did the
 world a great service.
{540}{}{Você é homem maravilhoso. Mesmo que eu não desculpo suas ações. Mas você fez a
  pro mundo um grande serviço.}
#You are wonderful woman. Even though I don't condone your actions. You did the
 world a great service.
{541}{}{Você é mulher maravilhosa. Mesmo que eu não desculpo suas ações. Você fez ao
  mundo um grande serviço.}
#Thanks.
{542}{}{Obrigado.}

# 26. Still destroyed, after talk (From WTG)
#You are not welcome here. Please leave.
{550}{}{Você não é bem-vindo aqui. Por favor, saia.}
#Please leave.
{551}{}{Por favor, saia.}

# 27. Still destroyed (From WTG)
#Why did you destroy my still? What did I ever do to you?
{560}{}{Por que você destruir o meu imóvel? O que foi que eu fiz para você?}
#I was paid to do it.
{561}{}{Me pagaram para fazer isso.}
#I don't have to answer to anyone.
{562}{}{Eu não tenho que responder a ninguém.}
# I don't know what you're talking about.
{563}{}{Eu não sei o que você está falando.}
#Whatever.
{564}{}{Tanto Faz.}
{565}{}{Ooba gooba.}

# 28. Still 2 (From 27)
#Oh really? That sleaze Frankie put you up to it, I'm sure of it. I'll just
 make another one, you know.
{570}{}{Sério? Isso sleaze Frankie coloca até ele, eu tenho certeza disso. Eu vou apenas
  fazer outro, você sabe.}
#Doesn't matter. I got paid.
{571}{}{Não importa. Eu tenho pago.}
#So.
{572}{}{Assim.}
#I wouldn't be surprised
{573}{}{Eu não ficaria surpreso}

# 29. Still 3(From 28)
#So, you're a coward too? Figures.
{580}{}{Então, você é um covarde também? Figuras.}
{581}{}{...}
