#0. Look
#You see a guard.
{100}{}{Você vê um guarda.}
#You see a guard for Becky's Casino Bar.
{101}{}{Você vê um guarda do Bar Cassino de Becky.}
#He seems to be keeping a close eye on this door.
{150}{}{Ele parece estar de olho atento nesta porta.}

#1. CF: Hostile
#You're not getting off that easy.
{200}{}{Você não vai sair dessa tão fácil assim.}

#2. CF: Generic
#This is to Rebecca's room. No one's allowed in.
{210}{}{Este é o quarto de Rebecca. Ninguém é permitido entrar.}
#Hope you're enjoying yourself.
{211}{}{Espero que esteja se divertindo.}
#You looking for Becky? She's right there.
{212}{}{Está procurando Becky? Ela está bem ali.}
#Hi.
{213}{}{Oi.}
#Enjoy the tables.
{214}{}{Aproveite as mesas.}
#Becky's got the cheapest drinks in town.
{215}{}{Becky tem as bebidas mais baratas da cidade.}

#3. Self Initiated: Door tampered with
#Get away from that right now.
{230}{}{Se afaste-se dessa porta agora.}
#Don't touch that again.
{231}{}{Não toque nisso de novo.}
#Back off!
{232}{}{Se afaste!}
#Leave that alone.
{233}{}{Não mexa nisso.}
#What do you think you're doing?
{234}{}{O que pensa estar fazendo?}

#4. Self Initiated: Door opened
#Thief!
{240}{}{Ladrão!}

#5. Self Initiated: Caught Stealing.
#We don't tolerate that here.
{250}{}{Não toleramos isso aqui.}

# left post message
#Baby, you up for something after work?
{300}{}{Garota, tem algum coisa para depois do trabalho?}
#You're looking fine, as always.
{301}{}{Você está muito bem, como sempre.}
#You really know how to run the table, baby.
{302}{}{Você realmente sabe como fazer a mesa, garota.}
#Hey honey, can you pick up those dice again? I love the way you move.
{303}{}{Ei querida, poderia jogar os dados de novo? Adoro o jeito que você se mexe.}
#Hey. How's it going, sweetness?
{304}{}{Ei. Como tem passado, doçura?}
{#So... you and me... after work?
{305}{}{E então... você e eu... depois do trabalho?}
#Becky might give me tomorrow off if you're... available.
{306}{}{Becky deve me dar folga amanhã, se você estiver... disponível.}
#I ever tell you what beautiful eyes you have?
{307}{}{Já te disse que você tem olhos lindos?}

# leaving message
#You ignoring me again. Two can play that game.
{350}{}{Você está me ignorando de novo. Dois podem jogar esse jogo.}
#What? You still pissed at me?
{351}{}{O quê? Ainda está chateado comigo?}
#You're, uh, doing a good job... continue with your work...
{352}{}{Você está, uh, fazendo um bom trabalho... continue com seu trabalho...}
#What? You ignoring me again?
{353}{}{O quê? Você está me ignorando de novo?}
#You're busy... I understand. We'll chat later.
{354}{}{Você está ocupada... Entendo. Conversaremos mais outra hora.}
#Man, you sure know how to play hard to get.
{355}{}{Cara, você sabe mesmo como se fazer de difícil.}
#I'll... uh, talk to you later then.
{356}{}{Eu vou... uh, falar com você outra hora então.}
#Nice talking to you too... I'll just be heading back over there then.
{357}{}{Foi bom falar com você também... vou voltar para lá então.}

# door open
#Oh, shit...
{375}{}{Oh, merda...}
