# examines
#You see a tough, middle aged slaver.
{100}{}{Você vê um escravista de meia idade violento.}
#You see slaver with a large scar on his face.
{101}{}{Você vê um escravista com uma grande cicatriz no rosto.}
#You see a rather large slaver.
{102}{}{Você vê um escravista bem grande.}

#There's a slaver who seems to enjoy his work.
{150}{}{Aeh está um escravista que parece gostar de seu trabalho.}
#This slaver seems to be very strong but not to bright.
{151}{}{Este escravista parece ser muito forte, mas não tão inteligente.}
#This slaver seems to be well-armed, like the others.
{152}{}{Este escravista parece estar bem armado, assim como os outros.}

# 1. CF: Hostile Not Done - no kills
#Let's get em.
{225}{}{Vamos pegá-los.}
#Only kill the hostile ones.
{226}{}{Só mate os hostis.}
#Lead the way; we're right behind you.
{227}{}{Mostre o caminho; te acompanhamos bem de perto.}
#Only take out the hostile ones- the others are our pay.
{228}{}{Só acabem com os hostis - os outros estão na nossa folha de pagamento.}
#I'm ready to split some heads.
{229}{}{Estou pronto para dividir algumas cabeças.}
#Where they at? You see em?
{230}{}{Onde estão? Está vendo eles?}

# 2. CF: Hostile Not Done - have kills
#It's not time to leave yet.
{235}{}{Não é hora de sair ainda.}
#Get the last of the hostile ones.
{236}{}{Acabe com o último dos hostis.}
#Leave the unarmed ones alone. Get the others.
{237}{}{Poupem os desarmados. Acabe com os outros.}
#There's still some more bloodshed waiting for us.
{238}{}{Ainda tem um pouco mais de derramamento de sangue esperando por nós.}

# 3. CF: Done with run - Poor
#That was a horrible run.
{245}{}{Isso foi um péssimo serviço.}
#This was hardly worth it. We didn't get shit.
{246}{}{Quase valeu a pena. Não conseguimos merda alguma.}
#Next time, only take out the hostile ones. This isn't all fun and games.
{247}{}{Da próxima vez, só acabe com os hostis. Isso não é tudo diversão e brincadeiras.}
#Metzger's going to be pissed.
{248}{}{Metzger vai ficar puto da vida.}

# 4. CF: Done with run - Average
#Not bad -- but next time, leave the unarmed ones alone if you want us to get paid.
{255}{}{Nada mal - mas da próxima vez, poupe os desarmados se quiser que recebamos o pagamento.}
#That wasn't that bad. We got some decent slaves out of this.
{256}{}{Até que não foi tão mal assim. Mas acabamos com alguns escravos decentes nessa ação.}
#I've seen better, but at least we'll get paid.
{257}{}{Já vi melhor que isso, mas pelo menos vamos receber o pagamento.}

# 5. CF: Done with run - Good
#Hey!, we did pretty good. We almost got them all.
{265}{}{Ei!, mandamos muito bem. Quase acabamos com todos eles.}
#Thanks for your help.
{266}{}{Obrigado pela ajuda.}
#Good job. The pay for this run should be nice.
{267}{}{Bom trabalho. O pagamento por este serviço deve ser bom.}
#That was fun and we should get a good cash out.
{268}{}{Isso foi divertido e devemos ganhar uma boa grana com isso.}

# 6. CF: Done with run - Perfect
#We kicked some serious ass. Metzger better give us a big bonus.
{275}{}{Fizemos um bom trabalho. É melhor que Metzger nos dê uma boa recompensa.}
#That was perfect! I'm going to get so shit-faced tonight.
{276}{}{Isso foi perfeito! Vou pegar uma bem bonita hoje à noite.}
#Fuck'n A. We kicked ass.
{277}{}{Detonação classe A. Detonamos alguns.}
#That's the way to do it!
{278}{}{E assim que se faz!}

# 7. BF: Hostile Not Done - no kills
#Where they at?
{285}{}{Onde estão?}
#I'm gonna get me some lovin'.
{286}{}{Vou dar uma trapadas.}
#I bet I'll get more kills than you this time.
{287}{}{Aposto que vou matar mais do que você desta vez.}
#Here, kitty, kitty, kitty.}
{288}{}{Vem aqui gatinho, bichano, bichano.}

# 8. BF: Hostile Not Done - have kills
#The rest of you are dead; you just don't know it yet.
{295}{}{O outros de vocês estão mortos; vocês só não sabe disso ainda.}
#You can't hide from us!
{296}{}{Não pode se esconder de nós!}
#Come out, or I'll blow your fucking head off.
{297}{}{Vem para fora, ou vou explodir a porra da sua cabeça.}
#Ah, that was good! Where are the rest of them?
{298}{}{Ah, essa foi boa! Onde estão o resto deles?}

# 9. BF: Done with run - Poor
#Shit.
{305}{}{Merda.}
#That sucked.
{306}{}{Isso fudeu.}
#Damn it.
{307}{}{Droga.}
#We better not do that again.
{308}{}{É melhor não fazermos mais assim.}
#Fuck... and I was going to drink up tonight.
{309}{}{Caralho... e eu que estava pensando em tomar todas hoje à noite.}
#Let's just get out of here. This fucking sucks.
{310}{}{Vamos sair fora daqui logo. Esta merda está começando a feder.}

# 10. BF: Done with run - Average
#Not bad.
{320}{}{Nada mal.}
#Hope we got enough. I need to replenish my jet supply.
{321}{}{Espero que pegamos o suficiente. Preciso repor meu estoque jet.}
#Let's go.
{322}{}{Vamos nessa.}
#I've seen better, but money's money.
{323}{}{Já vi melhor, mas dinheiro é dinheiro.}
#Metzger should be fine with these.
{324}{}{Metzger deve se contentar com estes.}

# 11. BF: Done with run - Good
#Pretty good.
{325}{}{Muito bom.}
#Hurry up. Let's beat it.
{326}{}{Anda logo. Vamos acabar com isso.}
#This should do just fine.
{327}{}{Isso já deve servir muito bem.}
#Nice haul.
{328}{}{Bota bonita.}
#Let's go. I want my money.
{329}{}{Vamos. Quero minha grana.}

# 12. BF: Done with run - Perfect
#Bonus time!
{335}{}{Tempo bônus!}
#Kickass.
{336}{}{Detonar.}
#Round them up and let's get going.
{337}{}{Cerquem eles e vamos descer o pau.}
#Stop fuck'n around. Let's go.
{338}{}{Pare de vacilar. Vamos nessa.}
#Damn, this run looks sweet.
{339}{}{Que legal, esse serviço foi moleza.}
