# looks
# primitive
#You see a big, primitive-looking man.
{100}{}{Você vê um homem grande, de aparência primitiva.}
#You see a slender primitive woman.
{101}{}{Você vê uma mulher primitiva magra.}

# nomads
#You see a strange-looking man.
{200}{}{Você vê um homem de aparência estranha.}
#You see a ragged-looking man.
{201}{}{Você vê um homem de aparência carrancuda.}
#You see a man in tattered clothing.
{202}{}{Você vê um homem vestido com roupas esfarrapadas.}

#You see a very grimy woman.
{210}{}{Você vê uma mulher muito encardida.}
#You see a rather dirty woman.
{211}{}{Você vê uma mulher bastante suja.}
#You see a scrawny looking woman.
{212}{}{Você vê uma mulher de aparência esquelética.}

# 10. BF: Fleeing Primitive
#They no find me.
{270}{}{Eles não irão me encontrar.}
#Must hide. Must hide.
{271}{}{Tenho que me esconder. Tenho que me esconder.}
#Why they want hurt?
{272}{}{Por que eles querem me machucar?}
#Me scared.
{273}{}{Estou assustado.}
#Me no fight.
{274}{}{Não sei lutar.}
#Me want live.
{275}{}{Eu quero viver.}
#No hurt family.
{276}{}{Não magoei ninguém da família.}

# 11. BF: Fleeing Nomad
#Oh, shit!
{280}{}{Oh, merda!}
#Why are they doing this?
{281}{}{Por que estão fazendo isso?}
#What about my family?
{282}{}{E minha família?}
#I don't want to die.
{283}{}{Eu não quero morrer.}
#I don't want to be a slave.
{284}{}{Eu não quero ser um escravo.}
#I deserve better than this.
{285}{}{Eu mereço melhor do que isso.}

# 14. Fleeing Primitive
#Ahhh!
{300}{}{Ahhh!}
#No kill! No kill!
{301}{}{Não me mate! Não me mate!}
#Stop!
{302}{}{Pare!}
#Heeeelp!
{303}{}{Socoooro!}
#Run!
{304}{}{Fugir!}
#Leave alone!
{305}{}{Me deixe em paz!}
#Don't hurt!
{306}{}{Não me machuque!}
#No hurt you!
{307}{}{Não te magoei!}
#I don't fight!
{308}{}{Não sei lutar!}

# 15. Fleeing Nomad
#Run for your lives!
{350}{}{Salve-se quem puder!}
#Don't let them catch you!}
{351}{}{Não deixem te pegarem!}
#Slavers! Run for it!
{352}{}{Escravistas! Fujam!}
#Help, someone! Please!
{353}{}{Socorro, alguém! Por favor!}
#Run for it, Marty!
{354}{}{Fuja, Marty!}
#Ahhh!
{355}{}{Ahhh!}
#Stop the insanity!
{356}{}{Parem com essa loucura!}
#We didn't do anything! Leave us alone!
{357}{}{Não fizemos nada! Deixe-nos em paz!}
#I recognize that tattoo!
{358}{}{Reconheço esta tatuagem!}
#No, please!
{359}{}{Não, por favor!}
#Please don't kill me!
{360}{}{Por favor, não me mate!}
#I won't fight; don't kill me!
{361}{}{Eu não vou lutar; não me mate!}
#Please, I don't want to die!
{362}{}{Por favor, eu não quero morrer!}
#You're slavers aren't you? Oh god.
{363}{}{Vocês são escravistas, não são? Oh deus.}
