#You see a prostitute.
{100}{}{Você vê uma prostituta.}

#This is your usual, run of the mill, prostitute.
{150}{}{Este é o seu jeito comum de ser, prostituta.}

#[TALK]!
{152}{}{[CONVERSE]!}
#Hey, I don’t do chicks!
{153}{}{Ei!, não sou galinha!}
#Whatever.
{154}{}{Seja o que for.}
#Sorry.
{155}{}{Desculpe.}
#Mom?
{156}{}{Mãe?}
#Hey!, it’ll cost more if you've got an audience with ya.
{157}{}{Ei!, vai ficar mais caro se você pensar muito.}
#Hey!, they go where I go.
{158}{}{Ei!, eles vão para onde eu vou.}
#I want them with me.
{159}{}{Eu quero eles comigo.}
#I’ll be back.
{160}{}{Eu voltarei.}
#Mom?
{161}{}{Mãe?}
#Oh, baby. Where you been all my life?
{162}{}{Oh, querido. Onde esteve a vida toda?}
#Right here, baby.
{163}{}{Bem aqui, querida.}
#How much, sister?
{164}{}{Quanto, irmã?}
#Um, I need to go. Bye.
{165}{}{Hã, Preciso ir. Tchau.}
#Whee!
{166}{}{Obaah!}
#I like em big and dumb.
{167}{}{Eu gosto dos grandes e bobinhos.}
#That’s me!
{168}{}{Esse sou eu!}
#Yay!
{169}{}{Yay!}
#Oh. No. Bye.
{170}{}{Oh. Não. Tchau.}
#What a big boy you are!
{171}{}{Que menino grande que você está!}
#The way you like it.
{172}{}{Do jeito que você gosta.}
#Yes, ma'am.
{173}{}{Sim, senhora.}
#I have to go.
{174}{}{Tenho que ir.}
#OK!
{176}{}{Está bem!}
#No. Bye.
{177}{}{Não. Tchau.}
#You’ll be back.
{178}{}{Você vai voltar.}
#We’ll see.
{179}{}{Veremos.}
#Um, no.
{180}{}{Hã, não.}
#[drool]!
{181}{}{[Babar]!}
#You don’t have enough bucks. Get lost, honey.
{182}{}{Você não tem dinheiro suficiente. Some daqui, queridinha.}
#I’ll come back.
{183}{}{Eu voltarei.}
#You’re not worth it, toots.
{184}{}{Você não vale isso, querida.}
#Wah!
{185}{}{Wah!}
#You were incredible!
{186}{}{Você foi incrível!}
#Always, baby.
{187}{}{Sempre fui, querida.}
#Whatever.
{188}{}{Seja o que for.}
#You were, too.
{189}{}{Você foi, também.}
#Me edible!
{190}{}{Tô com fome!}
#You were great!
{191}{}{Você foi genial!}
#Thanks. You too.
{192}{}{Obrigado. Você também.}
#Hmm.
{193}{}{Humm.}
#Yeah.
{194}{}{Sim.}
#Great!
{195}{}{Ótimo!}
#OK, we’re done. Bye.
{196}{}{OK, terminamos. Tchau.}
#That’s it?
{197}{}{Só isso?}
#OK. Bye!
{198}{}{Sim. Tchau!}
#It was good.
{199}{}{Foi ótimo.}
#Bye bye.
{200}{}{Tchau, tchau.}
#I don't get paid enough for this.
{201}{}{Não recebi o suficiente por isso.}
#It's not like you were worth the money anyhow.
{202}{}{Não que você mereceu o dinheiro de qualquer maneira.}
#You’ll miss me.
{203}{}{Você vai sentir minha falta.}
#Bye.
{204}{}{Tchau.}
#Lost?
{205}{}{Perdeu?}
#Come back anytime.
{206}{}{Volte a qualquer hora.}
#OK. Bye.
{207}{}{Está bem. Tchau.}
#Yeah, right.
{208}{}{Sim, certo.}
#Whoo!
{209}{}{Oba!}
#See ya.
{210}{}{A gente se vê.}
#Bye.
{211}{}{Tchau.}
#Bye bye.
{212}{}{Tchau, tchau.}
# It will cost $(amount) for a session. Pay first.
#It will cost $.
{213}{}{Vai custar $}
# for a session. Pay first.
{214}{}{ por uma sessão. Pague primeiro.}
#Follow me.
{215}{}{Siga-me.}
#I'm waiting.
{216}{}{Estou esperando.}
#I'm not gonna stand here in this cold room all day.
{217}{}{Não vou ficar aqui nesta sala fria o dia todo.}
#Would you hurry up?
{218}{}{Poderia se apressar?}
#Last chance.
{219}{}{Última chance.}
#Fine; I'm not waiting around any longer.
{220}{}{Bem; Não vou ficar esperando aqui por mais tempo.}
#Come on, come on.
{221}{}{Vamos lá, vamos lá.}
#Getting excited or something?
{222}{}{Ficando animado ou algo assim?}
#Follow me.
{223}{}{Siga-me.}
#Hey!, pal, keep your hands off of the merchandise.
{224}{}{Ei, fulano, mantenha as mãos fora da mercadoria.}
#Knock it off! I'm not just some toy to use.
{225}{}{Parem com isso! Não sou apenas um brinquedo para usar.}

#Uhhh...? Was this your first time?
{230}{}{Uhhh...? Foi sua primeira vez?}
