#Look Primitive
# 0. Parece Primitivo
#You see a big, primitive-looking man.
{100}{}{Você vê um homem de grande estatura aparentemente primitivo.}
#He has cuts and bruises all over his body.
{125}{}{Ele tem cortes e marcas por todo seu corpo.}

#You see a slender, primitive woman.
{150}{}{Você vê uma mulher primitiva de média estatura. }
#She looks like she's been beaten.
{175}{}{Ela aparenta ter sido mordida.}

#Look Nomad
# 1.Parece um nômade
#You see a ragged-looking man.
{200}{}{Você vê um homem aparentemente fodido.}
#He doesn't look very healthy.
{225}{}{Ele não parece muito saudável.}

#You see a woman captive.
{250}{}{Você vê uma mulher prisioneira .}
#She's filthy and seems to be malnourished.
{275}{}{Ela parece dopada e desnutrida.}

#CF: Freed
# 2. CF: Freed
#No hurt, please!
{300}{}{Sem machucar, por favor!}
#We leave now?
{301}{}{Nós saimos agora?}
#No talk. Must run.
{302}{}{Sem conversa fiada, nós devemos correr.}
#Thank you for help.
{303}{}{Obrigado pela ajuda.}
#Thank you very much!
{304}{}{Muito obrigado mesmo!}
#You are a saint.
{305}{}{Você é um santo.}
#What are you doing? We should go.
{306}{}{O que você está fazendo? Nós devemos ir.}
#Please help us escape.
{307}{}{Por favor, nos ajude a escapar.}

#CF: PC is slaver
# 3. CF: PC é traficante de escravos
#You bad!
{320}{}{Seu malvado!}
#We no talk you.
{321}{}{Nós não falamos com você.}
#We get free.
{322}{}{Nós estamos livres.}
#You no keep us.
{323}{}{Você não nos prende.}
#You slaver!
{324}{}{Seu traficante de escravos!}
#Why you slavers do this?
{325}{}{Por que vocês traficantes fazem isso?}
#How could you work for these people?
{326}{}{Como você pode trabalhar para essas pessoas?}
#We're not primitives!
{327}{}{Nós não somos primitivos!}
#Don't you have any morals?
{328}{}{Você não tem nenhuma moral?}
#What's going to happen to us?
{329}{}{O que vai acontencer conosco?}
#What did we do wrong?
{330}{}{O que nós fizemos de errado?}
#Leave us alone, slaver!
{331}{}{Deixe-nos sozinhos, traficante de escravos!}
#Don't hurt me!
{332}{}{Não me machuque!}
#Get away from me!
{333}{}{Fique longe de mim!}

#CF: PC is Not Slaver
# 4. CF: PC não é traficante de escravos.
#Who you?
{350}{}{Quem você?}
#You no slaver.
{351}{}{Você não é traficante.}
#You no hurt?
{352}{}{Você não machuca?}
#Friend?
{353}{}{Amigo?}
#You help?
{354}{}{Você ajuda?}
#What's going to happen to us?
{355}{}{O que vai nos acontecer?}
#Were you captured too?
{356}{}{Você foi capturado também?}
#We're not primitives!
{357}{}{Nós não somos primitivos!}
#Who do these people think they are?
{358}{}{Quem essas pessoas pensam que são?}
#Please help us!
{359}{}{Por favor nos ajude!}
#Get me out of here.
{360}{}{Me tire daqui.}

#BGF: Not Free
# 5. BGF: Sem liberdade
#You no keep us here!
{380}{}{Você não vai nos manter aqui!}
#No right!
{381}{}{Sem jeito!}
#We no bad!
{382}{}{Nós não somos malvados!}
#We help?
{383}{}{Ajuda nois?}
#Free us!
{384}{}{Nos liberte!}
#No like.
{385}{}{Gostei não.}
#Bad place.
{386}{}{Lugar ruim.}
#Why bad people do this?
{387}{}{Por que pessoas ruins fazem isso?}
#We no slave!
{388}{}{Não somos escravos!}
#We do nothing wrong.
{389}{}{Não fizemos nada de errado.}
#Let go!
{390}{}{Vamu!}
#What go on?
{391}{}{Que que ta acontecenu?}
#Big noise?
{392}{}{Barulho grande?}
#Who fight?
{393}{}{Quem briga?}
#What happen?
{394}{}{O que acontece?}
#Something happen?
{395}{}{Algo aconteceu?}
#Someone help us!
{396}{}{Alguém nos ajude!}
#Hey! Can't anyone hear me?
{397}{}{Hey! Ninguém consegue me ouvir?}
#This is wrong!
{398}{}{Isso é errado!}
#We didn't do anything!
{399}{}{Nós não fizemos nada!}
#Let us out of here!
{400}{}{Nos deixe sair!}
#Someone get us out!
{401}{}{Alguém nos deixe sair!}
#What did we do?
{402}{}{O que nós fizemos?}
#We didn't do anything.
{403}{}{Nós não fizemos nada.}
#We don't deserve this.
{404}{}{Nós não merecemos isso.}
#Those bastards!
{405}{}{Aqueles bastardos!}
#Help us!
{406}{}{Ajude-nos!}
#Let me out!
{407}{}{Me deixe sair!}
#We're not slaves!
{408}{}{Nós não somos escravos!}
#We're not primitives! Let us out of here!
{409}{}{Nós não somos primitivos! Deixe-nos sair!}
#What's happening?
{410}{}{O que passa?}
#Is someone here to save us?
{411}{}{Tem alguém aqui para nos salvar?}
#Over here!
{412}{}{Bem aqui!}
#Help! Don't leave us!
{413}{}{Ajude! Não nos deixe!}
#What was all that shooting?
{414}{}{O que era todos aqueles tiros?}
#What's going on?
{415}{}{O que está acontecendo?}

#BGF: Fleeing
# 7. BGF: Fugindo
#Ahhh!
{420}{}{Ahhh!}
#Ug!
{421}{}{Ug!}
#Don't stop!
{422}{}{Não pare!}
#Yes!
{423}{}{Sim!}
#I'm heading as far away from this place as possible.
{424}{}{Estou indo o mais longe possível desse lugar.}
#Keep moving!
{425}{}{Continua!}
#Freedom! Freedom at last!
{426}{}{Liberdade! Pelo menos liberdade!}

#Metzger is Dead (From Where to go)
# 8. Metzger esta morto (De onde ir)
#What loud gun noise? What you want?
{440}{}{Que barulho alto de armas? O que você quer?}
#Hey! What was all that gunfire? Are the slavers dead?
{441}{}{Hey! O que é todos esses disparos? Os traficantes de escravos mortos?}
#Hey! What was all that gunfire? What's going on?
{442}{}{Hey! O que era todos aqueles disparos? O que passa?}
#That was Metzger's nightcap.
{443}{}{Isso era o último tiroteio do Metzger.}
#Oh, nothing. Just checking up on you. Bye.
{444}{}{Ah, nada. Apenas checando vocês. Tchau.}
#You are free to go. Metzger's dead.
{445}{}{Você pode ir. Metzger esta morto.}
#You free.
{446}{}{Você está livre.}
# friend. He kill Mezgur. You go now.
{447}{}{ Amigo. Ele matou Mezgur. Você vai agora.}
# friend. She kill Mezgur. You go now.
{448}{}{ Amigo. Ela matou Mezgur. Você vai agora.}

#Metzger is Dead (From 8)
# 9. Metzger está morto (Por 8)
#He dead? Me thank you! We leave fast. Bye. You friend.
{460}{}{Ele morto? Eu lhe agradeço! Nós vamos rapido.}
#What? Metzger's dead? Oh, thank you so much! We better leave before others show up. Thank you again.
{461}{}{O que? Metzger está morto? Oh, muito obrigado mesmo! É melhor nós sairmos antes dos outros derem a cara. Obrigado denovo.}
#You're welcome. Now get out of here.
{462}{}{De nada. Agora da o fora daqui.}
#Take care.
{463}{}{Ti Cuida.}
#You're welcome.
{464}{}{De nada.}

#Wait, one more thing. I'm looking for someone specific and I don't see her here. Do you know where other slaves might be held?
{470}{}{Pera, mais uma coisa. Estou procurando por uma pessoa especifica e não vi ela aqui. Você sabe onde os outros escravos são mantidos?}
#Big camp near here. (The tribal points south west) Two moons from here.
{471}{}{Grande campo aqui perto. (O ponto tribal sudoeste} Duas luas daqui.
#There's a camp about two days travel south west from here. That's where I was first at.
{472}{}{Tem um acampamento a uns dois dias de viagem ao sudoeste daqui. Foi o primeiro que eu fiquei.}
#Thank you. Now get out of here.
{473}{}{Valeu. Agora sai daqui.}
#Thank you. Take care then.
{474}{}{Obrigado. Tome conta dele.}

#dumb dialogue added by killap
#Dialogo inútil  adicionado por killap
#Wait. I look for someone. Where more slaves?
{475}{}{Pera. Eu estou procurando alguem. Onde tem mais escravos?}
#Thankee. Go now!
{476}{}{Valeu. Vá agora!}

#Metzger Dead, Next Times (From Where to go)
# 10. Metzger Morto, Tempos próximos (De onde ir)
#What you want?
{480}{}{O que você quer?}
#What do you want?
{481}{}{O que você quer?}
#Oh, nothing.
{482}{}{Ah, nada.}

#Bullet (From 8)
# 11. Bala (Por 8)
{500}{}{Huh?}
#Never mind. You're free to go. Metzger's dead.
{501}{}{Não esquenta. Você está livre. Metzger está morto.}

#You free (From 8)
# 12. Você Livra (Por 8)
#Wha? Free? Bad men gone? We go now! Thank you. You friend! Bye!
{510}{}{Que? Livri? Homi mau foice? Nos vamos agora! Obrigado. Você amigo! tchau!}
#Free? What? You killed them all? Thank you so much! We'd better leave while we still can. Thank you again, you're a saint!
{511}{}{Livre? Que? Você matou todos eles? Obrigado mesmo! Nós vamos o mais rápido que pudermos. Obrigado denovo, você é um santo!}

#NPC Sold to Slavery (From WTG)
# 13. NPC Vendido para o escravismo (Por WTG)
#Damn you!
{520}{}{Ahh vá si fuder!}
#Rot in hell!
{521}{}{Queime no inferno!}
#You'll pay for this.
{522}{}{Você vai pagar por isso.}
#Why are you even talking to me?
{523}{}{Por que você sempre fala comigo?}
#Leave me alone.
{524}{}{Me deixe em paz.}
#I don't want to talk to you.
{525}{}{Eu não quero falar com você.}
#How could you?!
{526}{}{Como você pôde?!}
#I don't ever want to see you again.
{527}{}{Eu nunca mais quero te ver.}
#This isn't going to change things
{528}{}{Isso não vai mudar as coisas.}
#I'll be on my way, if you don't mind.
{529}{}{Eu vou estar no meu caminho, se você não liga.}
#Please, just let me leave.
{530}{}{Por favor, apenas me deixe sair.}
#Just let me be on my way.
{531}{}{Apenas me deixe no meu caminho.}
#I still don't want to talk to you.
{532}{}{Eu continuo não querendo falar com você.}
#Leave me alone.
{533}{}{Me deixe sozinho.}
#No chance.
{534}{}{Sem chance.}
#You think this makes things better?
{535}{}{Você acha que isso vai fazer as coisas ficarem melhores?}

#BGF: Just Freed
# 6. BGF: Apenas livre
#We go?
{600}{}{Nós vamos?}
#No hurt?
{601}{}{Sem machucar?}
#Go!
{602}{}{Vá!}
#Home!
{603}{}{Casa!}
#Free?
{604}{}{Livre?}
{605}{}{Huh?}
#What?
{606}{}{O que?}
#Did you say free?
{607}{}{Você disse livre?}
#I'm out of here!
{608}{}{Eu estou fora daqui!}
#Let's go!
{609}{}{Vamos!}
#Everyone! We're free!
{610}{}{Todo mundo! Estamos livres!}
{611}{}{Yaaahooo!}

#You free the slaves from their pens.
{700}{}{Você liberta os escravos de suas celas.}
