# 0. Look

# You see a slaver.
{100}{}{Você vê um escravista.}

# You see a slaver named Aidan.
{000}{}{Você vê um escravista chamado Aidan.}

# He looks like he could easily take care of himself in a fight.
{150}{}{Ele parece o tipo que sabe se virar sozinho em um combate.}

# 1. First Time - Self Initiated (From Where to go)

# Ah, fresh meat.... Welcome ta the slaver's guild. The name's Aidan. Ya here on
 business? Ya better be.
{200}{}{Ahh, carne fresca... Receba minhas boas vindas em nome da Associação de Escravistas. O nome é Aidan. Está aqui a negócio? É melhor estar.}
 
# What exactly does your guild do?
{201}{}{O que exatamente a associação faz?}

# Slaver's guild?
{202}{}{Associação dos Escravistas?}

# Save guld?
{203}{}{Socião dos Escavistas?}

# Aruk kun sung?
{204}{}{Aruk kun sung?}

# 2. Yes, join (From 4)

# Aidan looks you up and down.] Well, ya look like you'd fit right in, buddy, but you'll
 have ta talk ta Metzger, of course. Right though that back door.
{215}{}{[Aidan te olha da cabeça aos pés.] Bom, parece que você vai se encaixar, colega, mas precisa falar com o Metzger primeiro. Você pode chegar até ele pela porta dos fundos.}
 
# Aidan looks you up and down.] You don't look like ya could stomach it, pal, but who
 am I ta judge? Ya gotta talk ta Metzger. He's through the back door.
{216}{}{[Aidan te olha da cabeça aos pés.] Você não parece ter estomago para isso, colega, mas quem sou eu para julgar? Fale com o Metzger. Entre pela porta dos fundos.}

# I said ta talk ta Metzger. You fucking deaf and dumb or just dumb?
{217}{}{Eu disse para falar com o Metzger. Você tem surdes e é idiota ou só é idiota, porra?}

# Who's Metzger?
{218}{}{Quem é Metzger?}

# Another question for you then.
{219}{}{Outra pergunta para você então.}

# Thanks, I will.
{220}{}{Obrigado, eu irei.}

# Medger
{221}{}{Medger}

# Uh… kay.
{222}{}{Uh... okay.}

# 3. Hostile, Start Combat. (From Where to go)

# Now you die.
{230}{}{Agora você vai morrer.}

# 4. (From Where to go, 1-2, 6, 10-11, 16-18)

# Ya gotta be shittin' me! We capture and sell slaves. That's what yer here for, right?
 Ya looking for some action?
{240}{}{Você tá me zoando! Nós capturamos e vendemos escravos. É pra isso que você está aqui, certo? Quer um pouco de ação?}

# Ya gotta be shittin' me! We capture and sell slaves. If ya ain't here for that, whatta
 want? # Intentional errors, please do not change.
{241}{}{Você tá me zoando! Nós capturamos e vendemos escravos. Se não está aqui pra isso, o que você quer então?} 

# So, ya joined up. This should be interesting. If you like action, yer in the right line of work. If ya don't, ya won't last long.
{242}{}{Então você entrou. Isso vai ser interessante. Se gosta de ação, está no trabalho certo. Se não gosta, não vai durar muito.}

# I never thought I would see that tat on a woman. It looks good though. Surprised Metzger... fuck it. So what do ya need?
{243}{}{Eu nunca pensei que veria essa atitude em uma mulher. Mas tô gostando. Metzger ficou surpreso... foda-se. E então, o que você quer?}

# What do ya want? Ya lost or somethin'?
{244}{}{O que você quer? Se perdeu ou algo assim?}

# Hello again. li'l lady. Whatcha need?
{245}{}{Olá de novo, mocinha. Precisa de alguma coisa?}

# What?
{246}{}{Quê?}

# I'm looking to join.
{247}{}{Eu quero entrar.}

# Where do you get your slaves?
{248}{}{Onde você consegue seus escravos?}

# I'd like to buy some slaves.
{249}{}{Eu quero comprar uns escravos.}

# Do you know a man named Vic?
{250}{}{Você conhece um homem chamado Vic?}

# I'm looking for a Merchant.
{251}{}{Eu estou procurando por um comerciante.}

# You ever heard of Vault 13?
{252}{}{Você já ouviu falar da Vault 13?}

# Bye.
{253}{}{Adeus.}

# Work.
{254}{}{Trabalho.}

# Food.
{255}{}{Comida.}

# Kill.
{256}{}{Matar.}

# Ug.
{257}{}{Ugh.}

# 5. Dumb Kill (From 4)

# Ah, a bloodthirsty one. Well... Talk to the boss. We might have a place for ya. Go through the back door.
{270}{}{Ah, com sede de sangue, hein? Bem... Fale com o chefe. Ele pode ter trabalho para você. Entre pela porta dos fundos.}

# Metzger's never had a bitch slaver, but if you're really that bloodthirsty, check with him. He's right through that door.
{271}{}{Metzger nunca teve uma putinha escravista, mas se você for bem sanguinária, fale com ele. Ele está logo atrás daquela porta.}

# Okke.
{272}{}{Okei.}

# Uh.
{273}{}{Uh.}

# Krook
{274}{}{Krook.}

# 6. Buy slaves (From 4)

# Talk ta Metzger about that. He doesn't normally sell to the public. Has his hands full with... bigger customers.
{280}{}{Fale com o Metzger sobre isso. Ele não costuma vender para o publico. A mercadoria é reservada para... clientes maiores.}

# Who's Metzger?
{281}{}{Quem é Metzger?}

# Can I ask something else then?
{282}{}{Posso perguntar outra coisa então?}

# Okay, bye.
{283}{}{Ok, adeus.}

# What about Vic?
{284}{}{E o Vic?}

# 7. Dumb Exit (From 1, 4)

# Ya don't say. Beat it!
{290}{}{Não me diga. Cai fora!}

# Dumb bitch.
{291}{}{Vadia burra.}

# Oook?
{292}{}{Oook?}

# Hmph.
{293}{}{Hmph.}

# 8. What about buying Vic (From 6, 19)

# Not likely. That dumbass Vic pissed Metzger off about some radio or something. I doubt that he'd sell'm. You'll have to talk ta him yourself.
{300}{}{Acho difícil. Aquele retardado do Vic irritou o Metzger com o negócio do rádio. Eu duvido que esteja a venda. Você vai ter que falar com ele em pessoa.}

# Well, I hear he finally fixed the radio. You should ask Metzger. He's not much use now, not very good trade quality.
{301}{}{Bom, ouvi falar que ele finalmente consertou o rádio. Você devia perguntar para o Metzger. Ele não é muito útil agora, não é mercadoria de qualidade.}

# Who's Metzger?
{302}{}{Quem é Metzger?}

# Where's Metzger at?
{303}{}{Onde o Metzger está?}

# Okay, thanks. Bye.
{304}{}{Ok, valeu. Adeus.}

# 9. Where's Metzger (From 8)

# He's in the back room right through the door over there.
{310}{}{Ele está no quarto dos fundos, atrás daquela porta ali.}

# You playing with me? He's right back there. Just go through that door.
{311}{}{Tá me tirando? Ele está ali atrás. Do outro lado da porta.}

# Okay.
{312}{}{Ok.}

# Thanks.
{313}{}{Valeu.}

# 10. Who's Metzger? (From 2, 8, 16)

# Damn, you don't know Metzger? What're ya doin' in this town, if not ta see him? He's the head of the Slaver's Guild.
{320}{}{Caralho, você não conhece o Metzger? O que você está fazendo nessa cidade, se não for para vê-lo? Ele é o líder da Associação de Escravistas.}

# How many times do I have to tell ya? He's the slave master. He runs things in this town.
{321}{}{Quantas vezes tenho que lhe dizer? Ele é o mestre dos escravos. Ele controla a cidade.}

# Can I ask you something else?
{322}{}{Posso perguntar outra coisa?}

# Okay, thanks.
{323}{}{Ok, valeu.}

# 11. Where do you get slaves from? (From 4)

# I ain't talkin' about that. Metzger'll string me up. Plus, we wouldn't want any outside competition.
{330}{}{Eu não falo sobre isso. Metzger iria me enforcar. Além disso, não queremos nenhuma concorrência.}

# I already said. I ain't gonna talk about that.
{331}{}{Eu já disse. Não vou falar sobre isso.}

# Tell me before I blow a hole through your head.
{332}{}{Me diga antes que eu bote um buraco na sua cabeça.}

# I understand. Another question?
{333}{}{Eu entendo. Mais alguma pergunta?}

# Okay, bye.
{334}{}{Ok, adeus.}

# 12. Threatened life (From 11)

# Listen here, ya li'le shit head, don't you dare threaten me or anyone else in our guild, or you're dead. Get that? Dead.
{340}{}{Escuta aqui, seu merdinha, não ouse me ameaçar ou a qualquer outro da associação, ou você é um homem morto. Entendeu? Morto.}

# Listen here, ya li'l cunt. Don't you dare threaten me or anyone else in our guild, or your dead. Get that? Dead.
{341}{}{Escuta aqui, sua putinha, não ouse ameaçar ou a qualquer outro da associação, ou você será uma bucetinha morta. Entendeu? Morta.}

# Now, young jet eye, you will die.
{342}{}{Agora, viciado em jet, você vai morrer.}

# Screw you.
{343}{}{Vai se foder.}

# Sorry, please don't hurt me.
{344}{}{Me desculpe, por favor não me machuque.}

# Yeah, whatever. I'll let you live this time.
{345}{}{É, foda-se. Vou deixar passar dessa vez.}

# 13. Threaten back (From 12)

# Oh, really? Maybe I should just blow a hole through your head right here 'n now. What do you think, hot shot?
{350}{}{Ah, é mesmo? Talvez eu devesse abrir um buraco na sua cabeça aqui e agora. O que acha, bonzão?}

# Take your best shot.
{351}{}{Manda bala.}

# Don't make me laugh.
{352}{}{Não me faça rir.}

# I was just joking, man.
{353}{}{Eu só estava brincando, cara.}

# I'm sorry. I was just trying to impress you.
{354}{}{Desculpa. Eu estava tentando te impressionar.}

# 14. Run along (From 12, 13)

# Run along, before I change m'mind.
{360}{}{Agora some daqui, antes que eu mude de ideia.}

# Okay.
{361}{}{Ok.}

# 15. Food? (From 4)

# What? Oh, you must be looking for Mom's. You're one building off. She's in the building directly south. S-o-u-t-h. That way. [Aidan points out the door.]
{370}{}{Quê? Ah, você deve estar procurando a Mama. Ela está logo ali. No prédio diretamente abaixo. A-b-a-i-x-o. Naquela direção. [Aidan aponta para a porta.]}

# Huh? Uh… Oh.
{371}{}{Huh? Uh... Oh.}

# 16. Yes, join - Female (From 4)

# Ya look like ya might fit in, but Metzger's never hired a woman. Not sure why, but I doubt he's gonna start now.
{380}{}{Parece você se encaixaria, mas o Metzger nunca contratou uma mulher. Não sei por que, mas duvido que ele vá começar agora.}

# Ya don't look the type. Hell, Metzger's never hired a woman before. Not sure why, but I doubt he's starting now. # Error intentional, please do not remove.
{381}{}{Você não parece desse tipo. Porra, o Metzger nunca contratou uma mulher antes. Não sei por que, mas duvido que ele vá começar agora.}

# I said ta talk ta Metzger.
{382}{}{Eu disse pra falar com o Metzger.}

# Who's Metzger?
{383}{}{Quem é Metzger?}

# Another question.
{384}{}{{384}{}{Outra pergunta.}

# Thanks, I will.
{385}{}{Obrigado, eu irei.}

# Medger
{386}{}{Medger.}

# Uh… kay.
{387}{}{Uh... ok.}

# 17. Vault 13? (From 4)

# Nope, but I'd check with the boss. He's probably been all over the fuckin' place.
{400}{}{Não, eu tentaria perguntar pro chefe. Ele provavelmente já andou por toda parte.}

# Another question.
{401}{}{Outra pergunta.}

# Okay, thanks. Bye.
{402}{}{Ok, valeu. Falou.}

# 18. Vic/Merchant? (From 4)

# Merchant? Oh, you must mean Vic, that guy that sells the old Vault stuff. He's fucked. Metzger pretty pissed with'm.
{410}{}{Comerciante? Ah, você tá falando do Vic, aquele cara que vende tranqueiras das Vaults. Ele se fodeu. Metzger está puto com ele.}

{411}{}{Yeah, Vic… that Merchant guy, right? The one that sells the old Vault stuff. He's fucked. Metzger pretty pissed with'm.}

# How many times you gonna ask me that? Metzger's got'm.
{412}{}{Quantas vezes você vai me perguntar isso? Ele está com o Metzger.}

# Who's Metzger?
{413}{}{Quem é Metzger?}

# Can I ask another question?
{414}{}{Posso fazer outra pergunta?}

# Is he for sale?
{415}{}{Ele está à venda?}

# Okay, thanks.
{416}{}{Ok, valeu.}

# 19. Float Greeting (From WTG)

# Hey, boys, look who's back.
{430}{}{Ei, rapazes, olha só quem voltou.}

# Run, it's a slaver! Ah, I crack m'self up.
{431}{}{Corram, é um escravista! Ah, eu racho de rir.}

# Back for some action?
{432}{}{Voltou para um pouco de ação?}

# You know the way.
{433}{}{Você sabe o caminho.}

# Go on in.
{434}{}{Pode entrar.}

# He's wait'n for ya.
{435}{}{Ele está te esperando.}

# Now what?
{436}{}{O que foi agora?}

# I know that ugly face.
{437}{}{Eu conheço essa cara feia.}

# How's it goin'?
{438}{}{Como vai?}

# Yer back. Ya gonna join up?
{438}{}{Você voltou. Vai se juntar a nós?}
