# 0. Look
#You see a slaver.
{100}{}{Você vê um escravista.}

#He seems to be one of Metzger's personal guards.
{150}{}{Ele parece ser um dos guardas pessoais de Metzger.}

# 1. CF: Hostile
#There you are.
{200}{}{Aí está você.}
#Now you die.
{201}{}{Agora você morre.}

# 2. CF: Normal
#You want to see the boss? Go right in.
{300}{}{Você deseja ver o chefe? Pode entrar.}
#Metzger's the man to talk to, not me.
{301}{}{Metzger é o homem com quem conversar, não eu.}
#Go on in.
{302}{}{Vá entrando.}
#Behave yourself.
{303}{}{Comporte-se.}
#Metzger's right through this door.
{304}{}{Metzger está logo depois desta porta.}
#Don't piss Metzger off.
{305}{}{Não irrite Metzger.}
#We're not selling if that's what you're here for.
{306}{}{Não estamos vendendo se é para isso que está aqui.}
#Still can't get used to a woman slaver.
{307}{}{Ainda não me acostumei com uma mulher escravista.}
#Nice to have you with us.
{308}{}{É bom ter você conosco.}
#Hi. How's it going?
{309}{}{Oi. Como tá indo?}
#You club any slaves yet?
{310}{}{Ainda não bateu em nenhum escravo?}
#Hi again.
{311}{}{Oi de novo.}
#Going to go on another run?
{312}{}{Esta indo para outro turno?}
#Things are pretty calm.
{313}{}{As coisas estão bastante calmas.}
#When am I going to see some action?
{314}{}{Quando vou ver alguma ação?}
#I miss going on slave runs. Guarding sucks.
{315}{}{Sinto falta de estar capturando escravos. Ficar de guarda é uma merda.}
#Slave runs are a blast.
{316}{}{Capturar escravos é super legal.}
#Hey, man, glad to have you with us.
{317}{}{Ei, cara, fico contente por estar conosco.}
