# 0. Male Look - Primitive
#You see a big, primitive looking man.
{100}{}{Você vê um grande homem primitivo te olhando.}
#This man looks fairly strong and alert.
{101}{}{Este homem parece bastante forte e esperto.}

# 1. Female Look - Primitive
#You see a slender primitive woman.
{110}{}{Você vê uma delgada mulher primitiva.}
#She seems strong despite her size.
{111}{}{Ela parece forte, apesar de seu tamanho.}

# 2. Male Look - Nomad
#You see a strange looking man.
{120}{}{Você vê um homem de aparência estranha.}
#He seems to be awfully thin.
{121}{}{Ele parece ser muito fino.}

#You see a ragged looking man.
{130}{}{You see a ragged looking man.}
#This one looks fairly strong.
{131}{}{Este parece ser bastante forte.}

#You see a man in tattered clothing.
{140}{}{Você vê um homem com roupas rasgadas.}
#He movements suggest on with speed
{141}{}{He movements suggest on with speed.}

# 3. Female Look - Nomad
#You see a very grimy woman.
{150}{}{Você vê uma mulher muito suja.}
#She doesn't seem to have ever bathed.
{151}{}{Ela não parece que já se banhou.}

#You see a rather large woman.
{160}{}{Você vê um pouco da grande mulher.}
#She looks like strong fighter.
{161}{}{Ela se parece com um lutador forte.}

#You see a scrawny looking woman.
{170}{}{You see a scrawny looking woman.}
#This one doesn't seem like much trouble.
{171}{}{Este não parece ser um problema.}

# 4. CF: Hostile Primitive
#Die!
{200}{}{Morra!}
#Where you at?
{201}{}{Onde você está?}
#I'm gunna hurt you.
{202}{}{Sou gunna vou te machucar.}

# 5. CF: Hostile Nomad
#I'm going to get your for this!
{210}{}{Eu estou indo para obter o seu para isso!}
#God damn slavers!
{211}{}{Deus escravistas malditos!}
#You'll pay for this!
{212}{}{Você vai pagar por isso!}

# 6. CF: Fleeing Primitive
#Leave alone!
{220}{}{Deixe em paz!}
#Don't hurt!
{221}{}{Não machuque!}
#No hurt you!
{222}{}{Não vou te machucar!}
#I don't fight!
{223}{}{Eu não luto!}

# 7. CF: Fleeing Nomad
#I recognize that tattoo!
{230}{}{Eu reconheço a tatuagem!}
#No, please!
{231}{}{Não, por favor!}
#Please don't kill me!
{232}{}{Por favor, não me mate!}
#I won't fight; don't kill me!
{233}{}{Eu não vou lutar; não me mate!}
#Please, I don't want to die!
{234}{}{Por favor, eu não quero morrer!}
#You're slavers aren't you? Oh, god.
{235}{}{Você é escravista não é? Oh, Deus.}

# 8. BF: Hostile Primitive
#Quiet! They near.
{245}{}{Quieto! Eles estão próximos.}
#Kill bad men.
{246}{}{Matar os homens maus.}
#No take family from me.
{247}{}{Não pegue a família de mim.}
#I protect family.
{248}{}{Eu protejo família.}
#Must not find us.
{249}{}{Não deve encontrar-nos.}
#They bad people.
{250}{}{Eles pessoas más.}

# 9. BF: Hostile Nomad
#Slavers are coming. Everyone quiet.
{260}{}{Escravistas estão chegando. Todo mundo quieto.}
#Get ready; I think they're close now.
{261}{}{Prepare-se; Eu acho que eles agora estão perto.}
#I'm not going down without a fight.
{262}{}{Eu não vou desistir sem lutar.}
#They'll never enslave us.
{263}{}{Eles nunca vão nos escravizar.}
#Those slavers will pay for this.
{264}{}{Estes escravistas vão pagar por isso.}
#No slaver's going to take my family.
{265}{}{Nenhum escravista vai levar a minha família.}

# 10. BF: Fleeing Primitive
#They no find me.
{270}{}{Eles não me encontrarão.}
#Must hide. Must hide
{271}{}{Tem que esconder. Deve esconder.}
#Why they want hurt.
{272}{}{Por que eles querem mal.}
#Me scared.
{273}{}{Mim assustado.}
{274}{}{Mim não luta.}
{275}{}{Mim quer viver}
{276}{}{Não machucar família.}

# 11. BF: Fleeing Nomad
#Oh, shit!
{280}{}{Oh, merda!}
#Why are they doing this?
{281}{}{Por que eles estão fazendo isso?}
#What about my family?
{282}{}{E a minha família?}
#I don't want to die.
{283}{}{Eu não quero morrer.}
#I don't want to be a slave.
{284}{}{Eu não quero ser um escravo.}
#I deserve better than this.
{285}{}{Eu mereço melhor do que isto.}

# 12. Combat Float: Hostile Primitive
#You die now!
{290}{}{Você vai morrer agora!}
#Me kill!
{291}{}{Mim matar!}
#You no hurt family!
{292}{}{Você não tem família ferida!}
#You no take family!
{293}{}{Você não pegar família!}
#I protect!
{294}{}{Eu protejo!}
#I hurt you!
{295}{}{Eu machucar você!}
#You pay!
{296}{}{Você pagar!}

# 13. Combat Float: Hostile Nomad
#You're not going to take my family, slaver!
{300}{}{Você não vai pegar minha família, escravistas}
#Die, slaving scum!
{301}{}{Morra, escória de escravo!}
#You'll pay, you bastard!
{302}{}{Você vai pagar, seu bastardo!}
#I'll fight to the death for my family!
{303}{}{Eu vou lutar até a morte por minha família!}
#You won't get away with this!
{304}{}{Você não vai conseguir acabar com isso!}
#You're not leaving here with my friends!
{305}{}{Você não vai sair daqui com os meus amigos!}

# 14. Combat Float: Fleeing Primitive
{310}{}{Ahhh!}
#No kill! No kill!
{311}{}{Não mate! Não mate!}
#Stop!
{312}{}{Pare!}
#Heeeelp!
{313}{}{Ajuuuuda!}
#Run!
{314}{}{Corre!}
#No do that!
{315}{}{Não faça isso!}

# 15. Combat Float: Fleeing Nomad
#Run for your lives!
{320}{}{Corram por suas vidas!}
#Don't let them catch you!
{321}{}{Não deixe eles te pegarem!}
#Slavers! Run for it!
{322}{}{Escravistas! Run for it!}
#Help someone! Please!
{323}{}{Alguém ajude! Por Favor!}
#Run for it, Marty!
{324}{}{Corra para ele, Marty!}
{325}{}{Ahhh!}
#Stop is insanity!
{326}{}{Pare é loucura!}
#We didn't do anything! Leave us alone!
{327}{}{Nós não fizemos nada! Deixe-nos em paz!}