# 0. Look
#You see a greasy old coot.
{100}{}{Você vê um homem loiro velho e gordo.}

#You see Smitty the mechanic and junkyard owner.
{150}{}{Você vê Smitty o proprietário mecânico do ferro-velho.}
#You see a greasy old coot with dirty work-clothes on.
{151}{}{Você vê um homem loiro velho gordo com roupa-suja do trabalho.}

# 1. Get out floats (WtG)
#You varmint! Git outta here before I hafta learn ya!
{200}{}{Você VARMINT! Saia daqui antes que eu faça você aprender boas maneiras!}
#Git outta my place!
{201}{}{Saia do meu lugar!}
#Git off my land!
{202}{}{Saia das minhas terras}
#Dang varmint, git outta here.
{203}{}{Varmint Dang, sair daqui.}
#Go the hell away from me.
{204}{}{Fique bem longe de mim.}

# 2. Low Intelligence (WtG)
#Hey, git off my land.
{220}{}{Ei, saia da minha terra.}
#You there, dumbass, git outta here.
{221}{}{Você aí, idiota, saia daqui.}
#Git, go on, git!
{222}{}{Saia, vá em frente, saia!}
#I ain't got time for your type.
{223}{}{Eu não tenho tempo para pessoa com o seu tipo.}
#Sorry, I guess I don't speak idjit.
{224}{}{Desculpe, eu não falo com idiotas.}

# 3. Hello (WtG, 4,5,11, 17,20,25)
#Hello there, young feller. What can old Smitty do ya for?
{240}{}{Olá, meu jovem. O que pode o velho Smitty fazer por você?}
#Hello there, cute-stuff. What can old Smitty do ya for?
{241}{}{Olá, cute-stuff. O que pode velho Smitty fazer por você?}
#Jumpin' jiminy, what can I do for ya now?
{242}{}{Jiminy Jumpin ', o que posso fazer por você agora?}
#Hey there, I really enjoyed my meal from Mom's. Thanks. Now what can old Smitty do for ya?
{243}{}{Ei, eu realmente gostei da minha refeição feita pela mãe. Obrigado. Agora, o que você pode fazer para o Smitty de idade?}
#I was just wondering what you do here?
{244}{}{Eu só queria saber o que você faz aqui?}

#Say, old timer, I have this thingy here that I picked up in Gecko….
{245}{}{Sobre o, temporizador velho, eu tenho essa coisa peguei de um Gecko ....}
#Hey Smitty, I was wondering about that car you had for sale.
{246}{}{Ei Smitty, eu estava me perguntando sobre aquele carro que você tem ele esta a venda ..}
#I brought your meal from Mom's.
{247}{}{Eu trouxe a refeição da mãe.}
#Say, old timer, I have this thingy here that I picked up in Klamath….
{248}{}{Sobre o, temporizador velho, eu tenho esta coisa comigo eu peguei em Klamath ....}
#I was just looking around a bit. See you later, Smitty.
{249}{}{Eu só estava procurando algo. Vejo você mais tarde, Smitty.}

# 4. Thing from Gecko (3)
#Let old Smitty here take a look at it.
{260}{}{Vamos velho Smitty de uma olhada nisso.}
#Sure, here it is.
{261}{}{Claro, aqui está..}
#On second thought, let me ask you about something else.
{262}{}{Pensando bem, deixe-me perguntar sobre outra coisa.}
#Maybe another time. Goodbye, Smitty.
{263}{}{Talvez outra hora. Adeus, Smitty.}

# 5. Thing from Klamath (3)
#Let old Smitty here take a look at it.
{280}{}{Vamos velho Smitty de uma olhada nisso.}
#Sure, here it is. 
{281}{}{Claro, aqui está.}
#On second thought, let me ask you about something else.
{282}{}{Pensando bem, deixe-me perguntar sobre outra coisa.}
#Maybe another time. Goodbye, Smitty.
{283}{}{Talvez outra hora. Adeus, Smitty.}

# 6. Use Controller? (4)
#Well now, that looks to me like it's an old fuel cell controller. Hmm, I bet if I used that with the old Highwayman I could get her purring like a kitten.
{300}{}{Bem, agora, que parece-me que é um controlador de célula de combustível de idade. Hmm, eu aposto que se eu usasse com um o velho Highwayman eu poderia funincionar como um ronronar de um gatinho.}
{301}{}{Huh?}

# 7. Use Regulator? (5)
#Hmm, that looks jist like a fuel cell regulator. If I had a car that ran, it'd sure improve the mileage on it.
{310}{}{Hmm, parece com um regulador de célula de combustível. Se eu tivesse um carro que corre, ele iria melhorar a quilometragem com certeza.}
{311}{}{Huh?}

# 8. Meal from Mom's delivered (3,18)
#That was mighty darn kind of you. Thanks mucho, compadre. Here's a little something for your trouble. It'll come in handy 'round these parts. (He hands you a Stimpack.)
{320}{}{Você é uma especie de pessoa poderosa. Graças, compadre. Aqui está um pouco de tudo para o seu problema. Ele vai vir a calhar em volta destas peças. (Ele entrega-lhe um Stimpack.)}
#Thanks, Smitty. No problem. See you around.
{321}{}{Obrigado, Smitty. Sem problemas. Vejo você por aí.}
#Well, uhhh... Thanks, but I already headed over to Mom's and got some eats myself, so I won't be needin' that anymore.
{322}{}{Bem, uhh ... Obrigado, mas eu já fui para mãe e comi bastante, então eu não vou mais precisar '}
#Oops, I'm not the usual delivery person. He called in sick today. Can I get some experience points anyway?
{323}{}{Opa, eu não sou um fornecedor a habitual. Ele ficou doente hoje. Posso obter alguns pontos de experiência de qualquer maneira?}
#OK, sorry about the mix-up. I hope Mom doesn't fire me! I really need this job.
{324}{}{OK, sorry about the mix-up. I hope Mom doesn't fire me! I really need this job.}
#OK, desculpe sobre o mix-up. Espero que mãe não me demita! Eu realmente preciso deste emprego.
{325}{}{You know we're not doing the free meal after 24 hours thing anymore, right?}
#Well, maybe I'll just eat it myself then.
{326}{}{Bem, talvez eu só vou come mesmo.}
#Mom's not gonna be too happy with this.
{327}{}{Mãe não vai ficar muito feliz com isso.}

# 9. Tell about car (6,7)
#Well, you see, I've got this car, a Chrysalis Motors Highwayman. She's a beaut, too. They used to say "Nothing can stop a Highwayman." Built tough, that's what they were.
{330}{}{Bem, como você vê, eu tenho este carro, uma crisálida Motors Highwayman. Ela é uma beleza. Eles costumavam dizer: "Nada pode parar um Highwayman." Construído para ser resistente, e eles são.}
#Yeah, so what's that got to do with me?
{331}{}{Sim, o que isso tem a ver comigo?}

# 10. Car-Controller (9)
#Well, you see, I thought I needed a battery for the thing but all I really need is a fuel cell controller. Them things was always going bad on 'em.
{340}{}{Veja bem, eu pensei que precisava de uma bateria para o carro, mas tudo que eu preciso é um controlador de célula de combustível. Este sempre foi dificil de encontrar.}
#Well, I've got one of those.
{341}{}{Bem, eu tenho um desse.}

# 11. I've got one of those (10)
#That right? Here's the deal. You give me $2,000 and I'll sell you the car. Heck I'll even install the fuel cell controller for you. Should run good as new. I'll even charge it up with some extra micro fusion power cells I got.
{350}{}{Qual o negocio? Aqui está o negócio. Você me dá US $ 2.000 e eu vou vender o carro pra você. Heck Vou até mesmo instalar o controlador de célula de combustível para você. Deve funcionar bem como novo. Vou até carregá-lo com algumas células de energia micro fusão extras que eu tenho.}
#That sounds good to me. Here's the money and the part.
{351}{}{Isso soa bem para mim. Aqui está o dinheiro e a parte.}
#I don't think I want to do that right now. Let me ask you about something else, Smitty.
{352}{}{Eu não acho que eu quero fazer isso agora. Deixe-me perguntar-lhe sobre outra coisa, Smitty.}
#Let me think about it. I'll see you around, Smitty.
{353}{}{Deixe-me pensar sobre isso. Vejo você por aí, Smitty.}

# 12. Here's the car (12)
#Jist take it easy with her 'til she warms up, now.
{370}{}{Basta ter calma com ela até aquece, agora.}
#OK, I will. Thanks, Smitty.
{371}{}{OK, eu vou. Obrigado, Smitty.}

# 13. Car-Regulator (9)
#Well, a lot an' not so much at the same time.
{380}{}{Bem, a tempo existe um lote.}
{381}{}{Huh?}

# 14. What? (13)
#What I'm saying is that havin' a regulator is nice but you need to find a fuel cell controller.
{390}{}{O que estou dizendo é que Havin um regulador bom, mas você precisa encontrar um controlador de célula de combustível.}
#Why's that?
{391}{}{Por que isso?}

# 15. Why? (14)
#'Cause if'n you had a controller, and $2,000, I could fix this here Chrysalis Motors Highwayman that I got here and you could drive around in style.
{400}{}{Porque se você tivesse um controlador, e US $ 2.000, eu poderia consertar Chrysalis Motors Highwayman e você poderia dirigir ao redor em grande estilo.}
#Really? Where can I find a fuel cell controller?
{401}{}{Realmente? Onde posso encontrar um controlador de célula de combustível?}

# 16. Where do I find one of those? (15)
#Now that's a silly question. Don't you think if I knew that then I'd be driving around in the car?
{410}{}{Agora é uma pergunta boba. Você acha que se eu soubesse aonde esta o controlador, eu não estaria dirigindo por aí no carro?}
#Wow. I'll have to look for one of those.
{411}{}{Uau. Vou ter que procurar um desse.}

# 17. Look for one (16)
#Be a good idea. If you find one jist come on back here with it. Oh, and don' forget the $2,000, neither.
{420}{}{Vejo uma boa idéia. Se você encontrar um traga para mim. Ah, e não "esquecer a 2.000 dólares.}
#Sounds like a plan, Smitty. Hey, let me ask you about something else.
{421}{}{Soa como um plano, Smitty. Ei, deixe-me perguntar-lhe sobre outra coisa.}
#I'm going to go look for one right now. Goodbye.
{422}{}{Eu estou indo procura-lo agora. Adeus.}

# 18. Player bought car (WtG)
#Hey there, how's that car runnin' for ya?
{430}{}{Ei, o carro correr bem?}
#Pretty good, Smitty, but I found this part for the car and I don't know what to do with it.
{431}{}{Muito bem, Smitty, mas eu achei essa parte para o carro mas eu não sei o que fazer com ela.}
#Great, Smitty, just great. Hey, I brought you a meal. Compliments of Mom.
{432}{}{Ótimo, Smitty, simplesmente ótimo. Ei, eu trouxe-lhe uma refeição. Cumprimentos de mãe.}
#Real good, Smitty, real good. Thanks. See you around. Goodbye.
{433}{}{Realmente bom, Smitty, muito bom. Obrigado. Te vejo você por aí. Adeus.}

# 19. Have regulator (18)
#Well now, that's a fuel cell regulator. That'll give you better mileage per energy cell. I could put that in for you, if you had say $750 for my trouble.
{450}{}{Bem, agora, isso é um regulador de célula de combustível. Isso vai lhe dar uma melhor quilometragem por célula de energia. Eu poderia colocar isso em para você, se você tivesse $ 750 para resolver o problema.}
#That sounds like a deal, Smitty. Here's the part and the money.
{451}{}{sso soa como um negócio, Smitty. Aqui está a parte e o dinheiro.}
#I'll have to think about it, Smitty. Goodbye for now.
{452}{}{Vou ter que pensar sobre isso, Smitty. Adeus por enquanto.}

# 20. What do you do here? (3)
#Mostly I just keep watch over all this old junk. Only got one thing worth doodly-squat.
{460}{}{Principalmente eu só vigio toda essa sucata velha. Só tem uma coisa que vale a pena doodly-squat.}
#What's that?
{461}{}{O que é isso?}
#I figured that. Let me ask you something else.
{462}{}{Eu percebi isso. Deixe-me perguntar-lhe algo mais.}

# 21. What's worth anything? (20)
#Why, it's none other than this Chrysalis Motors Highwayman. They used ta say that "Nothing can stop a Highwayman." They shore built 'em tough, I'll say that for 'em.
{470}{}{Ora, é outro senão este Chrysalis Motors Highwayman. Eles usaram para dizer que "Nada pode parar a Highwayman." Eles foram construída para serem resistentes.}
#Wow, does it run?
{471}{}{Nossa, ele correu?}

# 22. Does it run? (21)
#If'n it ran, do you think I'd still be in this shithole of a town?
{480}{}{Se ele correu, você acha que eu ainda estaria nessa merda nesta cidade?}
#Uh, yes.
{481}{}{Uh, sim.}
#I guess not.
{482}{}{Eu não acho.}

# 23. Yes (22)
#Well, you're probably right. I got kinda settled in here.
{490}{}{Bem, provavelmente você está certo. Eu fiquei meio que resolvido aqui.}
#I see.
{491}{}{Eu vejo.}

# 24. No (22)
#Well, then again, mebbe' I would too. I got all comfortable here.
{500}{}{Bem, então, novamente, talvez 'eu faria também. Eu tenho tudo confortável aqui.}
#I understand.
{501}{}{Entendo.}

# 25. Got car (23,24 )
#I wouldn't mind selling the car though. If someone brought me the battery - no strike that, uh, I guess I'd need a fuel cell controller. Yeah, if'n I had one of them, I'd sell the car for $2,000. Even install the controller so it'd run right.
{510}{}{Eu não me importaria de vender o carro embora. Se alguém quem me trouxesse a bateria - , uh, eu acho que eu preciso de um controlador de célula de combustível. Sim, ou Tive um deles, eu venderia o carro por US $ 2.000. É instalaria o controlador para ele correr bem.}
#That sounds interesting. I'll have to come back if I ever find a fuel cell controller. Let me ask you something else right now.
{511}{}{Isso soa interessante. Vou ter que voltar se eu encontrar um controlador de célula de combustível. Deixe-me perguntar-lhe outra coisa agora.}
#When I find one, I'll be back. Goodbye, Smitty.
{512}{}{Quando eu encontrar um, eu vou estar de volta. Adeus, Smitty.}

# 26. Regulator installed  (19)
#There you go. Better'n new. Take it easy with her now.
{520}{}{Lá vai você. Better'n de novo. Acalme-se com ela agora.}
#I will. Thanks, Smitty. Goodbye.
{521}{}{Eu vou. Obrigado, Smitty. Adeus.}

#YOU GET THE HELL AWAY FROM MY CAR!
{600}{}{VOCÊ COMEÇA bem longe do meu carro!}

#Don't let me catch you sneaking around my car like that again.
{650}{}{Não me deixe pegar você esgueirando no meu carro novamente.}
#You won't.
{651}{}{Você não vai.}
{652}{}{Uggg-K}
