#You see bar patron. 
{100}{}{Você vê uma freguês do bar.}
#You see Stacy.
{101}{}{Você vê Stacy.}
#She seems to be a little sad.
{102}{}{Ela parece estar um pouco triste.}
#Stop it!
{103}{}{Pare com isso!}
#How could you?
{104}{}{Como se atreve?}
#Get away from me!
{105}{}{Fique longe de mim!}
#Why?
{106}{}{Por quê?}
#Please stop!
{107}{}{Por favor, pare!}
#You murderer!
{108}{}{Seu assassino!}
#Poor Mom! You'll pay for that!
{109}{}{Pobre Mãezinha! Você vai pagar por isso!}
#Mom...
{110}{}{Mãezinha...}
#But she was so nice to everyone...
{111}{}{Mas ela era tão legal com todos...}
#Sorry, can't think of anything else interesting.
{112}{}{Desculpe, não consigo pensar em nada mais interessante.}
#My brains all dried up.
{113}{}{Deu um branco no meu cérebro.}
#That's it.
{114}{}{É isso aí.}
#Hi.
{115}{}{Oi.}
#Have you said hi to Mom yet?
{116}{}{Ainda não disse oi para Mamãe?}
#Oh, hi.
{117}{}{Ah, oi.}
#Oh, you again.
{118}{}{Ah! você de novo.}
#Tell me about your cat.
{119}{}{Me conte sobre seu gato.}
#Why the glum face?
{120}{}{Por que essa cara mal-humorada?}
#You come here often?
{121}{}{Você vem sempre aqui?}
#I'll have to catch you later. Bye.
{122}{}{Falo como você mais tarde. Tchau.}
#Okah?
{123}{}{Tudo bem?}
#Ug.
{124}{}{Ug.}

# Node 005 removed

#Please don't bother me. I'm really not in the mood right now.
{131}{}{Por favor, não me incomode. Não estou de bom humor agora.}
#Ugra.
{132}{}{Ugra.}
#Fegi.
{133}{}{Fegi.}
#Oh, nothing really. Just sometimes I get thinking about my mom and cat. I miss them so very much.
{134}{}{Oh, nada demais. Só que às vezes fico pensando na minha mãe e gato. Sinto muito a falta deles.}
#Cat?
{135}{}{Gata?}
#Sorry to hear that. Bye.
{136}{}{Lamento ouvir isso. Tchau.}
#Yeah, Cuddles. She was such a sweet cat. I really don't feel like talking about it... Well, unless you'd like to buy me a drink. That might help.
{137}{}{Sim, Mimosa. Ela era uma gata tão doce. Realmente não gostaria de falar sobre isso... Bem, pelo menos se não se importar de me pagar uma bebida. Isso pode ajudar.}
#As I said, I would prefer not to talk about it right now. If you'd like to buy me a drink, it might loosen my tongue.
{138}{}{Como eu disse, prefiro não falar sobre isso agora. Se me pagar uma bebida, pode ser que destravo minha língua.}
#Of course I will. I'd love to hear about it.
{139}{}{Claro que vou. Adoraria ouvir sobre isso.}
#Sure.
{140}{}{Claro.}
#Sorry, I can't spare $10 right now.
{141}{}{Desculpe, não tenho $10 no momento.}
#Obviously.
{142}{}{Obviamente.}
#Do you think you're funny or something? Get a better line.
{143}{}{Acha que é engraçado ou algo assim? Ache um assunto melhor.}
#So why the glum face?
{144}{}{Então, por que a cara triste?}
#Whatever, bye.
{145}{}{Seja o que for, tchau.}
#I hear there used to be ones that were as big as you and me. They used to eat animals as big as a brahmin. Now that's scary stuff.
{146}{}{Ouvi dizer que costumava ter alguns tão grandes como você e eu. Que costumavam comer animais tão grandes como um brâmane. Isso sim é uma coisa assustadora.}
#That's nothing.
{147}{}{Isso não é nada.}
#Yeah, it is.
{148}{}{Sim, é sim.}
#The kind I'm talking about is a small cute animal, bigger than a rat but smaller than a dog. Some are fluffy, like my Cuddles, but others have short hair.
{149}{}{O tipo de que estou falando é um pequeno animal bonito, maior do que um rato, mas menor do que um cão. Alguns são pelosos, assim como minha Mimosa, mas outros têm pelos curto.}
#Really?
{150}{}{Sério?}
#They like to be pet like a dog does, but cats make this wonderful relaxing sound when you pet them.
{151}{}{Eles gostam de serem acariciados assim como os cachorros, mas os gatos fazem esse maravilhoso som relaxante quando se acaricia eles.}
#Strange.
{152}{}{Estranho.}
#Cuddles always used to help me go to sleep at night. I think of her every night when I try to go to sleep.
{153}{}{A Mimosa sempre me ajudava a dormir à noite. Penso nela todas noites quando tento dormir.}
#Sounds nice.
{154}{}{Parece legal.}
#Go on.
{155}{}{Continue.}
#I had her when I was a kid, but she disappeared. I didn't know then what happened to her, I was too young.
{156}{}{Ganhei ela quando era criança, mas ela desapareceu. Não sabia na época o que tinha acontecido com ela, eu era muito jovem.}
#Why?
{157}{}{Por quê?}
#Well, food was awfully scarce back then and people had to eat. It's quite sad really...
{158}{}{Bem, a comida estava muito escassa na época e as pessoas tinham que se alimentar. É realmente muito triste...}
#What?
{159}{}{O quê?}
#People would hunt them because they were such easy prey. None of them are around anymore because of it.
{160}{}{As pessoas caçavam eles porque eram uma presa fácil. Não se vê mais nenhum ao redor por causa disso.}
#Sick!
{161}{}{Isso é doentio!}
#I can understand that.
{162}{}{Posso compreender isso.}
#Those were the wild ones, but I'm sure that's what happened to mine. Now I know why Mom always kept a close eye on her.
{163}{}{Caçavam a princípio os selvagens, mas tenho certeza que foi o que aconteceu com a minha. Agora sei por que Mamãe sempre ficava de olho atento nela.}
#How sad.
{164}{}{Como é triste.}
#I'm sorry.
{165}{}{Sinto muito.}
#Oh...
{166}{}{Ah...}
#It makes me sad to think about it...
{167}{}{Me deixa triste pensar sobre isso...}
#Bye.
{168}{}{Tchau.}
#Stacy told you a sweet story about her darling cat Cuddles.
{169}{}{Stacy te contou uma doce história sobre sua querida gata Mimosa.}
