#You see a thug.
{100}{}{Você vê um bandido.}

#The thug looks pretty ruthless.
{150}{}{O bandido parece muito cruel.}
#Get out of my face.
{151}{}{Saia da minha frente.}
#You lookin' for trouble?
{152}{}{Você esta procurando problema?}
#Keep right on walking.
{153}{}{Mantenha a direita.}
#Not interested.
{154}{}{Não estou interessado.}
#Go away.
{155}{}{Vá embora.}

#Hey punk.
{200}{}{Hey punk.}
#You want some trouble?
{201}{}{Você quer um pouco de dificuldade?}
#Come here, sissy.
{202}{}{Venha aqui, mocinha.}
#Don't make me come over there and beat your ass.
{203}{}{Não me faça ir até lá e bater no seu rabo.}
#You talking to me?
{204}{}{Você está falando comigo?}
#You want some of this?
{205}{}{Você quer um pouco disso?}
#Hey baby, come here.
{206}{}{Hey baby, venha aqui.}
#Hey, you like what you see?
{207}{}{Hey, você gosta do que vê?}