# LOOKS
#You see a druggie.
{100}{}{Você vê um drogado.}

#You see a jet whore.
{110}{}{Você vê uma puta da alta sociedade.}
#You see one of Tubby's jet whores.
{111}{}{Você vê uma das putas da alta sociedade do Tubby.}

# EXAMINES
#He seems to be a friend of Tubby's.
{150}{}{Ele parece ser amigo de Tubby.}

#She seems to be extremely doped up.
{160}{}{Ela parece estar extremamente dopada.}
#She seems to be suffering from massive withdrawals.
{161}{}{Ela parece estar com muita síndrome de abstinência.}

# 1. CF: Tubby's Dead
#Oh, man. Where we going to get our shit now?
{200}{}{Oh, cara. Onde vamos conseguir nosso material agora?}
#What'd ya kill Tubby for?
{201}{}{Por que razão matou Tubby?}
#Oh man, that sucks.
{202}{}{Porra cara! que bosta.}
#Now what're we supposed to do?
{203}{}{E agora, o que devemos fazer?}
#Oh, man…!
{204}{}{Putz, cara...!}
#Hey!, that's not fair.
{205}{}{Ei, isso não é justo.}
#Don't hurt us, we won't tell.
{206}{}{Não nos machuquem, não vamos contar.}

# 2. CF: Standard
# LOW KARMA
#Wow, you look pretty mean.
{220}{}{Uau, você parece muito mau.}
# HIGH KARMA
#Hey!, you're a real nice guy. Anyone ever tell you that?
{221}{}{Ei!, você é um cara muito legal. Alguém já te disse isso?}
#Hey!, you're a real nice gal. Anyone ever tell you that?
{222}{}{Ei, você é uma garota muito legal. Alguém já te disse isso?}
# GENERIC
#We're Tubby's guards.
{223}{}{Somos os guardas do Tubby.}
#Don't mess with Tubby. This is his place.
{224}{}{Não se meta com Tubby. Este lugar é dele.}
#Damn, I'm feeling good.
{225}{}{Legal, estou me sentindo bem.}
#Can you believe we're guards? Cool, isn't it.
{226}{}{Consegue acreditar que somos guardas? Maneirol, néh?}
#This shit is great.
{227}{}{Esta merda é genial.}
#Oh, man I can't feel my legs.
{228}{}{Putz, cara. Não consigo sentir minhas pernas.}
#Tubby's our buddy.
{229}{}{Tubby é nosso amigo.}
#Tubby keeps us happy.
{230}{}{Tubby nos mantém felizes.}
#Oh boy, oh boy oh boy… Damn my eyes.
{231}{}{Oh cara, oh cara, oh cara... Porra, meus olhos.}
# SLAVER
#Hey!, man, you a slaver? Wow…!
{232}{}{Ei, cara, você um escravista? Caralho...!}
#Did that tattoo hurt?
{233}{}{Doeu fazer essa tatuagem?}
#You slavers sure are tough.
{234}{}{Vocês esclavistas com certeza são barra pesada.}
#Isn't it dangerous being a slaver?
{235}{}{Não é perigoso ser um escravista?}
# METZGER DEAD
#Hey!, I heard your boss got shot or something. Tough luck.
{236}{}{Ei!, ouvi que seu chefe foi baleado ou algo assim. Que azar.}
#Hey!, you hear? Metzger's dead or something.
{237}{}{Ei!, ficou sabendo de algo? Metzger está morto ou algo assim?}
#Wow, someone diced the Metzger the Butcher.
{238}{}{Caralho, alguém em picotou Metzger o Carniceiro.}
#Hope Tubby can stay in business with Metz gone.
{239}{}{Espero que Tubby continue com os negócios com Metz fora.}

# 3. BGF: Tubby Dead (From Where to go)
#Wow, man. He killed Tubby.
{250}{}{Caralho, cara. Ele matou Tubby.}
#I think my shit went bad.
{251}{}{Acho que minha droga estava estragada.}
#Woh, what's going on?
{252}{}{Oh, que está acontecendo?}
#What was all that noise?
{253}{}{O que foi esse barulho todo?}
#Dang, that was nasty shit.
{254}{}{Maldição, isso foi algo horrível.}
#Wow, man. She killed Tubby.
{255}{}{Caralho, cara. Ela matou Tubby.}

# 4. BGF: Standard
#Ooooohhyaaa… Good stuff.
{260}{}{Ooooohh putz...Boa merda.}
#What's that?
{261}{}{O que é isso?}
#Oh, yeah, I'm flying now.
{262}{}{Oh, sim, Estou voando agora.}
#Oh so warm.
{263}{}{Oh!, tão quente.}
#She's so pretty.
{264}{}{Ela é tão bonita.}
#Oh, blackout… Shit, I can't see.
{265}{}{Oh, apagão... Merda, Não consigo enxergar.}

# 5. Conversation
# CONVERSATION 1
#Wow, you see that?
{270}{}{Caralho, viu isso?}
#Yeah, you know what it was?
{271}{}{Se sim, sabe o que era?}
#I think it was a bird.
{272}{}{Acho que era um pássaro.}
#No, a dog.
{273}{}{Não, um cachorro.}
#But it was flying man.
{274}{}{Mas estava voando cara.}
#No way - it zoomed across the ground.
{275}{}{De jeito nenhum - passou bem grandão pelo chão.}
#Yeah, you seeing things, man.
{276}{}{Sim, está vendo coisas, cara.}
#No way. That was real.
{277}{}{Não, não. Foi real.}
#Whatever.
{278}{}{Seja o que for.}
#Ohhhh it's kicking in again. Ahh.
{279}{}{Ohhhh, o barato está pegando de novo. Ahh.}

# CONVERSATION 2
#Pretty lights.
{290}{}{Luzes bonitas.}
#Lots of lights.
{291}{}{Muitas luzes.}
#They're so warm.
{292}{}{Elas são tão quente.}
#And the trees.
{293}{}{E as árvores.}
#Where are the women?
{294}{}{Onde estão as mulheres?}
#So green and pretty.
{295}{}{Tão verdes e bonitas.}
#I like potatoes.
{296}{}{Eu gosto de batatas.}
#Trees are made of wood.
{297}{}{As árvores são feitas de madeira.}
#I like women and potatoes.
{298}{}{Eu gosto de mulheres e batatas.}
#They make smoke when they burn.
{299}{}{Fazem fumaça quando queimam.}
#But not together.
{300}{}{Mas não juntas.}
#Animals live in trees.
{301}{}{Os animais vivem nas árvores.}
#No, not women and trees, women and potatoes.
{302}{}{Não, mulheres e árvores não, mulheres e batatas.}
#I can climb a tree.
{303}{}{Consigo subir em árvores.}
#A woman climbing a tree eating potatoes? You're dumb.
{304}{}{Uma mulher subindo em uma árvore comendo batatas? Só pode ser idiota.}
#Where do trees come from?
{305}{}{De onde vem as árvores?}
#You can't climb a tree and eat potatoes.
{306}{}{Não se pode subir em árvores comendo batatas.}
#I like bushes, too.
{307}{}{Eu gosto do matagal, também.}
#Well, not very easily.
{308}{}{Bem, não é muito fácil.}
#Because they're green.
{309}{}{Porque eles são verdes.}
#Potatoes aren't green.
{310}{}{As batatas não são verdes.}
#Ohhh, the pretty lights.
{311}{}{Ohhh, as luzes bonitas.}
#Oh, my head hurts…!
{312}{}{Oh, estou com dor de cabeça...!}

# 6. CF: Hostile
#Don't talk to me, man. My head hurts.
{320}{}{Não fale comigo, cara. Estou com dor de cabeça.}
#I won't tell anyone.
{321}{}{Não vou contar a ninguém.}
#Don't hurt me.
{322}{}{Não me machuque.}
#I didn't do anything.
{323}{}{Não fiz nada.}
#I didn't see anything.
{324}{}{Não vi nada.}
#I didn't hear anything.
{325}{}{Não ouvi nada.}
#Please, just leave.
{326}{}{Por favor, vai embora vai.}
#Lady, I don't feel much like talking. My fucking head is killing me.
{327}{}{Senhora, Não sinto muita vontade de falar. A droga de minha dor de cabeça está me matando.}

# 7. BGF: Hostile
#Oh man, you suck.
{340}{}{Oh, cara, você é um merda.}
#What did you go and ruin a perfect high for?
{341}{}{Por foi estragar a festa?}
#Man, that hurt!
{342}{}{Cara, isso machuca!}
#What the hell?
{343}{}{Por que diabos?}
#How's that going to happen?
{344}{}{Como isso foi acontecer?}

# CRACH WHORES
#8. Click Floats
#Tubby's so wonderful.
{400}{}{Tubby é tão maravilhoso.}
#Jet makes me so horny.
{401}{}{A alta sociedade me deixa tão excitada.}
#Tubby knows how to take care of his women!
{402}{}{Tubby sabe como cuidar de suas mulheres!}
#Isn't Tubby wonderful?
{403}{}{Tubby não é maravilhoso?}
#Oh, baby- Wait! You ain't Tubby.
{404}{}{Oh, garota-Espere! Você não é do Tubby.}
#Where's our big man at?
{405}{}{Onde está o nosso grande homem?}
#Doesn't it just make your skin tingle?
{406}{}{Isso não fazer a sua pele formigar?}
#Tubby has the best supply in town.
{407}{}{Tubby tem o melhor fornecimento da cidade.}
#I feel so alive!
{408}{}{Me sinto tão viva!}

#Did you hear a load bang?
{420}{}{Ouviu um estrondo forte?}
#Haven't seen Tubby in a while.
{421}{}{Não vejo Tubby a algum tempo.}
#Where's Tubby?
{422}{}{Onde está Tubby?}
#You seen Tubby?
{423}{}{Você viu Tubby?}

#Oh, my head!
{440}{}{Oh, minha cabeça!}
#Where's Tubby! I think I'm going to die!
{441}{}{Onde está Tubby! Acho que vou morrer!}
#I can't take this much longer.
{442}{}{Não posso suportar isso muito tempo.}
#Oh, the pain is getting really bad.
{443}{}{Oh, a dor está ficando muito ruim.}
#Tubby hasn't given us any in a while. Where he at?
{444}{}{Tubby não tem nos dado por algum tempo. Onde ele está?}
#My lips are numb.
{445}{}{Meus lábios estão dormentes.}
#I can't feel my fingers.
{446}{}{Não posso sentir meus dedos.}

#9. Hostile
#Don't hurt me!
{460}{}{Não me machuque!}
#Please, don't!
{461}{}{Por favor, não!}
#I didn't take it!
{462}{}{Não tomei!}
#It wasn't me!
{463}{}{Não fui eu!}
#Leave me alone!
{464}{}{Me deixe em paz!}
#I didn't know it was yours!
{465}{}{Não sabia que era seu!}
