# 0. Look

# You see Tyler.
{100}{}{Você vê Tyler.}

# You see Tyler, the leader of this gang.
{101}{}{Você vê Tyler, o líder desta gangue.}

# He seems fairly strong.
{150}{}{Ele parece bem forte.}

# 1. Messed with door.

# Hey, don't touch the fucking door.
{200}{}{Ei, não toque na porta, porra.}

# Moron.
{201}{}{Débil mental.}

# 2. Hostile

# Now we finish it.
{210}{}{Vamos acabar logo com isso.}

# 3. CF: Gang 1 Won.

# Told you it would be a piece of cake.
{220}{}{Eu não disse que ia ser moleza?}

# That was like leading lambs to the slaughter.
{221}{}{Foi como levar ovelhas para um matadouro.}

# That fucking bitch is finally dead!
{222}{}{Essa puta do caralho finalmente morreu!}

# Thanks for the tip, that was sweet.
{223}{}{Valeu pela dica, acertou em cheio.}

# 4. CF: No Show

# Where the hell were you?
{230}{}{Onde diabos você estava?}

# Trap my ass! Fucking liar.
{231}{}{Armadilha é o caralho! Mentira do caralho.}

# I should gut you right now.
{232}{}{Eu devia te estripar agora mesmo.}

# So much for the plan, asshole.
{233}{}{Belo plano, cuzão.}

# You better not have been jerking me around.
{234}{}{É melhor você não estar me enrolando.}

# How'd you fuck this one up?
{235}{}{Como você conseguiu foder tudo?}

# 5. CF: Trap Set

# You just lead those dumb bastards here and we'll nail them to the wall.
{240}{}{É só levar esses idiotas pra cá e prensamos eles na parede.}

# We're waiting.
{241}{}{Estamos esperando.}

# We can't wait all night.
{242}{}{Não podemos esperar a noite toda.}

# What are you waiting for? I'm ready for blood.
{243}{}{O que está esperando? Eu quero derramar sangue.}

# Do it already! Don't let them get suspicious.
{244}{}{Vai logo! Antes que eles suspeitem de algo.}

# Hurry the hell up.
{245}{}{Anda logo, diabo.}

# 6. Trap = No (From WTG)

# Who the hell are you and what do you want?
{250}{}{Quem diabos é você e o que você quer?}

# So, what do you want this time?
{251}{}{Então, o que você quer agora?}

# Metzger sent me.
{252}{}{Metzger me mandou.}

# I'm here to inspect the church.
{253}{}{Eu vim examinar a igreja.}

# Nevermind. Goodbye.
{254}{}{Esquece. Adeus.}

# Me 
{255}{}{Mim }

# !
{1255}{}{!}

# Aruwa?
{256}{}{Aruwa?}

# 7. Metzger sent me (From 6)

# What the hell for? His stuff's not going anywhere.
{260}{}{Pra quê? A mercadoria dele não vai a lugar algum.}

# His crap still hasn't moved an inch.
{261}{}{As porcarias dele não se moveram um centímetro.}

# Oh, yeah. You're a slaver now, eh? So what did he want? It's not going anywhere - not like it could.
{262}{}{Ah, sim. Você é um escravista agora, né? O que ele quer? A mercadoria não vai sair daqui - não é como se pudesse.}

# He wanted me to check it for him.
{263}{}{Ele quer que eu de uma olhada pra ele.}

# Well, he wants to be sure.
{264}{}{Digamos que ele quer ter certeza.}

# Never mind.
{265}{}{Deixa quieto.}

# 8. Failed 1st speech roll for entrance (From 7)

# Sure he did. I've never seen you around here before. Now, beat it.
{270}{}{Claro que mandou. Eu nunca te vi por aqui. Vaza.}

# Let me in there now, before I have to get angry on your face!
{271}{}{Deixe-me entrar agora, antes que eu fique irritado!}

# Look, he had me come into town just to inspect his damn stuff. I could care less.
{272}{}{Olha, ele me disse para vir nessa cidade para examinar a maldita mercadoria. Eu não dou a mínima.}

# Okay.
{273}{}{Ok.}

# 9. Whatever, go in (From 7, 8)

#Whatever, slaver. Just go on in. Does he think it's just going to up and leave?
# Who the hell would want that shit?
{280}{}{Tanto faz, escravista. Entra aê. Por acaso ele acha que a mercadoria vai embora?
 Quem iria querer essa merda?}

# Fuck it. Just go in. Does he think it's just going to up and leave? Who the
 hell would want that shit anyhow?
{281}{}{Foda-se. Entra aê. Por acaso ele acha que a mercadoria vai embora? Quem iria querer essa merda?}

# Bye.
{282}{}{Falou.}

# 10. Don't care. (From 8)

# Okay, fuck. It's not like I really care. Like you would know what to do with any of that shit anyway.
{290}{}{Ok, porra. Nem ligo. Não é como se você soubesse o que fazer com essa merda mesmo.}

# Grrrr.
{291}{}{Grrrr.}

# Thanks.
{292}{}{Valeu.}

# 11. Threaten, failed (From 8)

# Beat it, tough guy, before I get angry on Your face.
{300}{}{Cai fora, machão, antes que eu arrebente a sua cara.}

# Beat it, bitch. Metzger wouldn't have sent a woman anyhow, so take a hike.
{301}{}{Cai fora, vadia. Metzger nunca mandaria uma mulher, vai girar bolsinha.}

# Bitch? I'll show you what this bitch can do.
{302}{}{Vadia? Eu vou te mostrar o que essa vadia sabe fazer.}

# Fuck you.
{303}{}{Vai se foder.}

# [Leave]
{304}{}{[Sair])}

# 12. Door = Never (From WTG)

# Beat it.
{310}{}{Cai fora.}

# 13. Me Name (From 6)

# That's nice. Me Tyler. Me go bye bye.
{320}{}{Ótimo. Mim Tyler. Mim dizer tchau tchau.}

# Ur.
{321}{}{Durr.}

# Uh…
{322}{}{Uh...}

# 14. Dumb (From 6, 18)

# Beat it, freak.
{330}{}{Some daqui, aberração.}

# Sukyu!
{331}{}{Sifude!}

# Arug!
{332}{}{Argh!}

# 15. Enter, no. (From 8, 16)

# I don't think so. Now beat it.
{340}{}{Acho que não. Vaza.}

# Okay.
{341}{}{Ok.}

# But!
{342}{}{Mas!}

# Fine.
{343}{}{Ótimo.}

# 16. Metzger Not Known, Search Church (From 6)

# Yeah, I bet you are. Who sent you?
{350}{}{Sim, claro que é. Quem te mandou?}

# Yeah, you said that already, fuck head. Who sent you?
{351}{}{Sim, você já me disse isso, porra. Quem te mandou?}

# Who do you think, moron? Now stop dicking around and let me in.
{352}{}{Quem você acha, debilóide? Agora pare de embaçar e me deixe entrar.}

# The pink panther.
{353}{}{A pantera cor de rosa.}

# Okay, you'll regret that.
{354}{}{Ah, vai se arrepender disso.}

# 17. Pink panther (From 16)

# The what? Get outta here!
{360}{}{A o quê? Some daqui!}

# But...
{361}{}{Mas...}

# Fine.
{362}{}{Ótimo.}

# 18. Find (From WTG)

# Now what the hell does the boss want? Another stupid fucking inspection?
{370}{}{O que diabos o chefe quer agora? Outra inspeção de merda?}

# Yes?
{371}{}{Sim?}

# What now?
{372}{}{Que foi agora?}

# How's it going?
{373}{}{Como vai?}

# Sorry, gotta go.
{374}{}{Desculpa, estou de saída.}

# Uk.
{375}{}{Ugh.}

# Lub?
{376}{}{Durr.}

# 19. Charisma Good (From 18)

# Actually, great! Almost forgot - a buddy of mine won it big at the tables and he's sharing the wealth, if you know what I mean.
{380}{}{Estou ótimo! Quase me esqueci - um amigo meu ganhou uma nota no jogo e está compartilhando sua fortuna, se é que me entende.}

# Pretty fucking bored. I hate guarding - but, hey, things can't be that bad. A buddy of mine won it big at the tables and he's sharing the wealth, if you know what I mean.
{381}{}{Ando entediado. Eu odeio ficar de vigia - mas, ei, não é tão ruim assim. Um amigo meu ganhou uma nota no jogo e ele esta compartilhando sua fortuna, se é que me entende.}

# Big plans, then?
{382}{}{Altos planos, hein?}

# Sounds like fun.
{383}{}{Parece divertido.}

# 20. (From 18)

# Yeah, he's throwing a party tonight at his place. Should be a blast.
{390}{}{É, ele vai dar uma festa na casa dele. Vai ser um estouro.}

# Yeah, he's throwing a party tonight at his place. Should be a blast. I'd invite you, honey, but it's only for his closest friends.
{391}{}{É, ele vai dar uma festa na casa dele. Vai ser um estouro. Eu te convidaria, gracinha, mas é só para os amigos mais chegados.}

# Down a few brews for me.
{392}{}{Eu quero tomar uns goles.}

# I understand, thanks. Have fun.
{393}{}{Entendi, valeu. Divirta-se.}

# See ya.
{394}{}{Falou.}

# 21. Have fun. (From 20)

# You better believe it! We're going to drink until we drop!
{400}{}{Pode apostar! Nós vamos beber até cair!}

# Bye.
{401}{}{Adeus.}

# 22. Failed, how are you (From 18)

# What the fuck do you care. Beat it.
{410}{}{Não interessa pra você. Vaza.}

# Yeah, so-so.
{411}{}{Ééé, mais ou menos, mais ou menos...}

# You trying to annoy me?
{412}{}{Você esta querendo me irritar?}

# Not bad.
{413}{}{Nada mal.}

# Tired.
{414}{}{Cansado.}

# Okay.
{415}{}{Ok.}

# Beat it.
{416}{}{Vaza.}

# Been better.
{417}{}{Já estive melhor.}

# Oh.
{418}{}{Oh.}

# 23. CF: Weakness is still set (From WTG)

# Can't wait for that party. Hope he has a few whores there again.
{430}{}{Mal posso esperar por essa festa. Espero que tenha algumas vadias lá de novo.}

# My buddy really knows how to throw a party.
{431}{}{Meu amigo realmente sabe como dar uma festa.}

# Almost party time.
{432}{}{Quase hora da festa.}

# Party! Wish I was there now.
{433}{}{Festa! Queria estar lá agora.}

# 24. Gang War = Fight (From WTG)

# Hey, what's up? Almost time for that party.
{440}{}{Ei, e aí? A festa já está para começar.}

# What's up?
{441}{}{E aí?}

# I have some information you might be interested in.
{442}{}{Eu tenho informações que podem ser do seu interesse.}

# Nothing.
{443}{}{Nada.}

# Uhg.
{444}{}{Ugh.}

# Urseco?
{445}{}{Urrr.}

# 25. Dumb, Gang War = Fight (From 24)

# Damn, what the hell's wrong with you today? Lay off the drugs.
{450}{}{Merda, o que há de errado com você? Largue as drogas.}

# Drugs are bad for you, man.
{451}{}{Verdadeiros campeões não usam drogas, amigo.}

# Drugs are bad for you, lady.
{452}{}{Drogas fazem mal para você, senhorita.}

# [Grunt]
{453}{}{[Grunhido]}

# 26. Information (From 24)

# Oh, yeah? What's that?
{460}{}{Ah, é? O que é isso?}

# It'll cost you.
{461}{}{Tem um preço.}

# Lara's planning on hitting this place tonight.
{462}{}{planejamento de Lara em bater este lugar esta noite.}

# Wait a minute.
{463}{}{Espera aí.}

# 27. Float reward (From WTG)

# You fucking earned this. Here's your money. I've been wanting to finish them off
 for a while.
{470}{}{Você mereceu, caralho. Aqui está sua grana. Eu estava esperando para acabar com eles há um bom tempo.}

# 28. It'll cost you (From 26)

# Yeah, fuck you. It depends on what it is. You tell me, then I'll decide
 if I pay you anything for it.
{480}{}{É, foda-se. Depende do que for. Você me conta, e eu decido se vale meu dinheiro ou não.}

# Lara's planning on hitting this place tonight.
{481}{}{Lara está planejando atacar esse lugar essa noite.}

# No, sorry.
{482}{}{Não, sinto muito.}

# 29. Lara's plan (From 26, 28)

# Oh really? So that bitch has got some balls after all? Well, that's worth a $100.
{490}{}{É mesmo? Então aquela vadia tem culhões afinal? Bem, isso vale uns $100.}

# Thanks.
{491}{}{Obrigado.}

# 30. Plan 2 (From 29)

# Not so fast, slick. Just to be sure, we'll wait until after they show.
 You could be lying to me for all I know. You just be sure they show, and I'll pay you after.
{500}{}{Calma aí. Só pra ter certeza, vamos esperar até eles aparecerem.
 Você poderia estar inventando, até onde eu sei. É bom que eles apareçam, então eu pago você depois.}
 
# But I'm a lover, not a fighter.
{501}{}{Sou da paz, não da guerra.}

# Sounds good.
{502}{}{Parece bom.}

# 31. Lover (From 30)

# Look, I don't give a rat's ass what you are. I'm not giving you a dollar
 until after they show. We'll do the fighting, but you better be sure they show.
{510}{}{Escuta aqui, eu não dou a mínima foda para o que você é. Não vou te dar um centavo até eles aparecerem.
 Nós cuidamos da luta, mas é bom você garantir que eles vão aparecer.}
 
# Okay.
{511}{}{Ok.}

# 32. CF: Can go through door (From WTG)

# So, you're the boss's new whipping boy?
{600}{}{Então você virou o novo assistente do chefe?}

# What do ya want?
{601}{}{O que você quer?}

# What's up with Metzger? Doesn't he trust us anymore?
{602}{}{O que deu no Metzger? Ele não confia mais em nós?}

# You done checking that shit yet?
{603}{}{Já terminou de conferir essa merda?}

# Told you Metzger's shit wasn't going anywhere.
{604}{}{Eu disse que as merdas do Metzger não iam a lugar algum.}

# So, you finished in there or what?
{605}{}{Já terminou ou não?}

# I'm sure Metzger needs you for something. Why don't you run along and check?
{606}{}{Tenho certeza que Metzger precisa de você pra alguma coisa. Por que não confere logo?}

# What the fuck's wrong with Metzger? Thinking we're not guarding his shit...
{607}{}{O que caralho deu no Metzger? Achando que não estamos vigiando a mercadoria...}

# You still here? Don't you have another little errand to run for Metzger?
{608}{}{Ainda está aqui? Você não tem nada para fazer para o Metzger?}

# So, you're the boss's new whipping girl?
{609}{}{Então você é a nova putinha do chefe?} 

# 12. Additional Never Floats

# I'm not in the mood.
{700}{}{Eu não estou a fim.}

# Not now.
{701}{}{Agora não.}

# I'm busy.
{702}{}{Tenho trabalho a fazer.} 

# New Node 33

# The smart ass is back! So you really want in this church? Why? There's nothing in here you'd be interested in.
{710}{}{Já de volta, sagaz! Você realmente quer entrar nessa igreja? Por quê? Não tem nada que você se interessaria lá dentro.}

# Now what the fuck do you want?
{711}{}{O que caralho você quer agora?}

# You see this mark on my forehead? Let me in. Now!
{712}{}{Está vendo essa tatuagem na minha testa? Deixe-me entrar. Agora!}

# I'm his new bitch, that's why! If you don't let me in right now, I'll be sure you find yourself at the top of his shit list.
{713}{}{Porque eu sou a nova vadia dele! Se não me deixar entrar agora, eu vou fazer você ficar no topo da lista negra dele, seu bosta.}

# Look, buddy. Metzger's going to have my hide if I don't inspect everything soon. You know how he gets.
{714}{}{Olha, amigo. Metzger vai arrancar meu couro se eu não examinar tudo logo. Você sabe como ele é.}

# None of your fucking business. If the Boss wants his shit checked out, that's what I do. I don't ask questions.
{715}{}{Não é da porra da sua conta. Se o chefe quiser que eu examine a merda dele, é isso que vou fazer. Eu não faço perguntas.}

# Never mind.
{716}{}{Deixa quieto.}

# Shaka?
{717}{}{Shaka?}


# Who the- Hey! It's you. You came to *hickup* party with us. I knew you would. (Tyler stumbles over to you and grabs your shoulder)
 Did I ever tell you how much I-(He spies Lara's gang) What the fuck! No fuckin way! This party ain't endin *hickup* cause of some fuckin bitch
 and her cronies. Time to lock and load guys!
{800}{}{Quem foi- Ei! É você. Você veio para *hic* festejar conosco. Sabia que viria. (Tyler tropeça até você e segura seu ombro)
 Eu já te disse o quanto eu- (Ele vê a gangue da Lara) Que porra! Não pode ser! Essa festa não vai acabar *hic* por causa de uma vadia do caralho
 e seus lacaios. Tá na hora do pau, cambada!}
 
# [END]
{801}{}{[END]}
