# 0. Look
#You see a slaver.
{100}{}{Você vê um traficante de escravos.}

#He seems to be paying close attention to the door next to him.
{150}{}{Ele parece estar prestando muita atenção para a porta próximo dele.}

# 1. Self Initiated Floats
#Hey! Hands off
{200}{}{Ei! Não toque}
#That's it!
{201}{}{É isso aí!}

# 2. Open Door 1 - Self Initiated Floats
#Problems?
{210}{}{Problemas?}
#Practicing?
{211}{}{Praticando?}
{212}{}{Hmmm.}

# 3. Open Door 2 - Self Initiated Floats (From 9, 16)
#There you go.
{220}{}{Lá vai você.}

# 4. Starting Node (From Where to go)
#Hey, how's it going?
{230}{}{Ei, como vai?}
#Hey, you joined up, huh? Cool. Hope we go on some runs together.
{231}{}{Ei, você juntou-se, hein? Com estilo. Espero que nós corramos juntos..}
#So, what is it you want to talk about?
{232}{}{Então, o que é que você quer falar?}
#So, who's in there?
{233}{}{Então, quem está lá dentro?}
#About Vic…
{234}{}{Fale sobre o Vic…}
#Good, thanks.
{235}{}{Bom, obrigado.}
#Got to go.
{236}{}{Tenho que ir.}
{237}{}{Wuk?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}

# 5. Who's that? & About Vic… (From 4)
#His name's Vic - some merchant that broke something of my boss's, or something like that. Not too sure.
{250}{}{O nome dele é Vic - algum comerciante que quebrou alguma coisa do meu chefe de, ou algo parecido. Não tenho certeza.}
#His name's Vic - some merchant that broke something of my boss's, or something like that. Not too sure.
{251}{}{O nome dele é Vic - algum comerciante que quebrou alguma coisa do meu chefe de, ou algo parecido. Não tenho certeza..}
#Oh, him? Yeah, some merchant. I think he broke something, but I'm not sure. Why? You know him?
{252}{}{Oh, ele? Sim, algum comerciante. Eu acho que ele quebrou alguma coisa, mas eu não tenho certeza. Por quê? Você o conhece?}
#Oh, him? Yeah, some merchant. I think he broke something, but I'm not sure. Why? You know him?
{253}{}{Oh, ele? Sim, algum comerciante. Eu acho que ele quebrou alguma coisa, mas eu não tenho certeza. Por quê? Você o conhece?}
#Yeah?
{254}{Sim?}
#Why are you guarding him?
{255}{}{Por que você está guardando-o?}
#Who's your boss?
{256}{}{Quem é o seu chefe?}
#Can I see him?
{257}{}{Posso vê-lo}
#Well, I'm fairly skilled in repairing things. Maybe I could help?
{258}{}{Bem, eu estou bastante habilidoso em reparar coisas. Talvez eu possa ajudar?}
#Well, I'm fairly skilled in the sciences, maybe I could help?
{259}{}{Bem, eu estou bastante habilidoso nas ciências, talvez eu possa ajudar?}
#The door's locked. Could you open it?
{260}{}{A porta está trancada. Você poderia abri-la?}
#thanks
{261}{}{Obrigado.}

# 6. Guard Will let PC see Vic. (From 18)
#Thanks for cash. I'm just letting you talk to him. No funny stuff. He can't leave that room without Metzger's okay.
{275}{}{Obrigado pelo dinheiro. Eu estou apenas deixando você falar com ele. Não é nada engraçado. Ele não pode sair daquele quarto sem Metzger ter autorizado..}
#Now, I'm just letting you talk to him, okay? No funny stuff. He can't leave that room without Metzger's okay.
{276}{}{Agora, eu estou apenas deixando você falar com ele, ok? Não é nada engraçado. Ele não pode sair daquele quarto sem Metzger ter autorizado.}
#okay
{277}{}{Ok.}

# 7. Why guarding Vic (From 5)
#To be sure no one bugs him while he works on something for the boss, but mainly to be sure he doesn't run off.
{285}{}{Para ter certeza de não aconteça nenhum erro enquanto ele trabalha em algo para o chefe, mas, principalmente, para se certificar de que ele não vai fugir.}
#Just to be sure he doesn't run off, I guess. He fixed that radio somehow.
{286}{}{Só para ter certeza que ele não vai fugir, eu acho. Ele consertou o rádio de alguma forma.}
#Who's your boss?
{287}{}{Quem é o seu chefe?}
#Can I see him?
{288}{}{Posso vê-lo?}
#Can I see him?
{289}{}{Posso vê-lo?}
#Okay thanks.
{290}{}{Tudo bem obrigado.}

# 8. Can I see him - Slaver (From 7)
#Oh, sure. I didn't mean you could see him, now that you're a slaver and all.
{295}{}{Oh, com certeza. Eu não quis dizer que você podia vê-lo, agora que você é um traficante de escravos e um de nós.}
#Oh, sure. I guess so. He's not busy and he's not going anywhere, so no harm I guess.
{296}{}{Oh, com certeza. Eu acho que sim. Ele não está ocupado e que ele não vai a num lugar, então acho que não há nenhum mal.}
#Well, could you open the door then?
{297}{}{Bem, então você poderia abrir a porta?}
#Okay, thanks.
{298}{}{Ok, obrigado.}

# 9. Unlock door, Okay to see (From 5, 8)
#Of course. I didn't know you wanted to talk to him right now, sorry. I just thought you were curious or something.
{305}{}{Claro. Eu não sabia que você queria falar com ele agora mesmo, me desculpe. Eu apenas pensei que você estava curioso ou algo assim.}
#thanks.
{306}{}{Obrigado.}

# 10. Who's your boss? (From 5, 7, 18)
#Huh? You just in the habit of walking around into places you don't know? This is the Slaver's Guild.
{310}{}{Hein? Você apenas tem o hábito de andar por aí em lugares que você não conhece? Esta é a Aliança dos Escravos..}
#Oh, so that would make your boss's name…
{311}{}{Ah, que faria então em nome do seu chefe ....}
#Oh, that's where I am? I thought I was in Kansas.
{312}{}{Oh, é onde eu estou isso? Eu pensei que estava no Kansas.}
#Okay, thanks.
{313}{}{Ok, obrigado.}

# 11. Kansas (From 10)
#Where? No, never heard of it. This is the Den. Not sure about that place, but I don't get out much. Sorry
{320}{}{Onde? Não, nunca ouvi falar disso. Este é o Den. Não tenho certeza sobre esse lugar, mas eu não saio muito. desculpe}
#Moron.
{321}{}{Idiota.}
#Uh, okay. Thanks.
{322}{}{Uh, ok. Obrigado.}

# 12. Don't know Boss? (From 10)
#Damn, man. Metzger's the slaver master. He runs things around here.
{330}{}{Porra, cara. Metzger é o mestre traficante de escravos. Ele dirige as coisas por aqui.}
#Damn, lady. This is the last place a lady like you would want to be. Metzger's the slaver master
{331}{}{Porra, senhora. Este é o último lugar que uma dama como você gostaria de estar. O mestre do traficante de escravos é o Metzger.}
#Oh, where's his office?
{332}{}{Oh, onde está seu escritório?}
#Okay, bye.
{333}{}{Ok, tchau.}

# 13. Where's his office? (From 12)
#Right through the back door there.
{340}{}{Direito pela porta dos fundos.}
#Thanks
{341}{}{Obrigado.}

# 14. Dumb Exit (From 4, 15, 20)
#Sorry, I don't understand.
{350}{}{Desculpe, eu não entendo.}
{351}{}{Hmph.}

# 15. Dumb Vic ? (From 4)
#Sorry, Vic doesn't get visitors.
{360}{}{Desculpe, Vic não receber visita}
#Yeah, that's Vic
{361}{}{Sim, esse é o Vic}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gaw.}

# 16. Dumb Can See Vic (From 15)
#Sure, you can see him.
{370}{}{Claro, você pode vê-lo.}
#Sure, you can see him. Let me unlock that for you
{371}{}{Claro, você pode vê-lo. Deixe-me abrir isso para você}
{372}{}{Tank.}

# 17. Repair or Science skills (From 5)
#Oh really? I'm sure the boss would appreciate it. Just as long as he stays put. We don't want him running off again.
{380}{}{Sério? Tenho certeza de que o patrão iria apreciá-lo. Contanto que ele fique de fora. Nós não queremos que ele fuja novamente.}
#Thanks.
{381}{}{Obrigado.}

# 18. Can I see Vic? (From 5, 7)
#No, sorry. He's busy working on something for the boss.
{390}{}{Não, desculpe. Ele está ocupado trabalhando em algo para o chefe..}
#Sorry, can't do that. Direct orders from the boss.
{391}{}{Desculpe, não posso fazer isso. Ordens diretas do chefe.}
#Well, you got my money?
{392}{}{Bem, você tem o meu dinheiro?}
#I just need to ask him a few questions.
{393}{}{Eu só preciso lhe fazer algumas perguntas.}
#Oh, come on. Just let me talk to him real quick.
{394}{}{Oh, vamos lá. Apenas deixe-me falar com ele rapidinho.}
#Yes. Here
{395}{}{Sim. Está aqui}
#No. I'll come back
{396}{}{Não. Eu voltarei}
#Who's your boss?
{397}{}{Quem é o seu chefe?}
#Nevermind. Bye	
{398}{}{Não Importa. tchau}

# 19. See Vic is Never (From )
#Stop bothering me. Go talk to Metzger. He's the boss
{410}{}{Pare de me incomodar. Vá falar com Metzger. Ele é o chefe}
#Leave me alone! What's your problem?
{411}{}{Me deixe em paz! Qual é o seu problema?}
#I said talk to Metzger!
{412}{}{Eu disse para falar com Metzger!}
#Okay, fine! You can talk to him, but that's it! He's not stepping a foot outside that room. Got it? Now beat it!
{413}{}{Ok, tudo bem! Você pode falar com ele, mas é só isso! Ele não pode botar um pé fora desse ambiente. Entendeu? Agora va visita-lo!}
#Okay
{414}{}{Ok.}
#Thanks
{415}{}{obrigado!}

# 20. Wuk? (From 4)
#Yeah, talk to Metzger. I'm sure he has some work available. I think he said he needed another man.
{430}{}{Sim, falar com Metzger. Tenho certeza que ele tem algum trabalho disponível. Acho que ele disse que precisava de um outro homem.}
#Yeah, talk to Metzger. I'm sure he has some work available. He said he needed another man… but I'm sure you'll do.
{431}{}{Sim, fale com Metzger. Tenho certeza que ele tem algum trabalho disponível. Ele disse que precisava de um outro homem ... mas eu tenho certeza que você vai querer.}
#Talk to Metzger.
{432}{}{Fale com Metzger.}
{433}{}{Ruru?}
{434}{}{Uh?}
{435}{}{Oh.}

# 21. Hostile (From Where to go) hostil
#Get him, guys.
{450}{}{Pegue-o, pessoal.}
#Get her, guys.
{451}{}{Levá-la, pessoal.}

# 22. Just a few questions. (From 18) Apenas algumas perguntas
#He's busy.
{460}{}{Ele está ocupado.}
#Please, he won't leave the room. I promise.
{461}{}{Por favor, ele não vai sair da sala. Eu prometo.}
#Can't we work something out - financially maybe?
{462}{}{Não podemos trabalhar em algo - talvez financeiramente ?.}
#Okay, bye.
{463}{}{Ok, tchau.}

# 23. Bribe 1 (From 22)
#Well, uh… I don't know. I guess it wouldn't hurt just for you to talk to him. $300 and I'll let you in
{470}{}{Bem, uh ... eu não sei. Eu acho que não faria mal apenas você falar com ele. US $ 300 e eu vou deixarei.}
#You're nuts. That's too much!
{471}{}{Você está louco. Isso é demais!}
#Screw you, buddy!
{472}{}{Foda-se, amigo!}
#Sure.
{473}{}{Claro.}
#Sorry, can't afford that.
{474}{}{Desculpe, não se pode dar a esse luxo.}

# 24. Fine. (From 22)
#Fine, see if I care.
{480}{}{Tudo bem, ver se eu me importo.}
#Okay.
{481}{}{Ok.}
#Fine.
{482}{}{Bem.}

# 25. No. (From 23)
#No, sorry.
{490}{}{Não, desculpe.}
#I said no. Now beat it. You've got to talk to Metzger
{491}{}{Eu disse que não. Agora va. Você tem que falar com Metzger}
#Okay
{492}{}{Ok.}

# 26. Vic Free (From Where to go)
#To bad you didn't join us.
{500}{}{Pena que você não quer se juntar a nós.}

#You should join the guild.
{501}{}{Você deve se juntar à aliança.}
#Just doing that guard thing.
{502}{}{Basta fazer aquela coisa de guarda.}
#Hope Vic works out for you.
{503}{}{Espero Vic trabalhe para você.}
#Vic better be working hard for ya.
{504}{}{É melhor Vic estar trabalhando duro para ya.}
#Maybe I'll catch you on a run
{505}{}{Talvez eu vou pegar você em uma corrida}
#How's it going?
{506}{}{Como tá indo?}
#Hi, again.
{507}{}{Oi, novamente.}
