# You see a slave.
{100}{}{Você vê um escravo.}

# You see Vic.
{101}{}{Você vê Vic.}

# This slave seems to be kept under tight surveillance.
{150}{}{Esse escravo parece estar sob forte vigilância.}
 
# This is Vic.
{151}{}{Este é Vic.}

# [TALK]
{152}{}{[Conversar]}

# Node 1

# Would you tell him I can't... wait. Who are you? You're not a
 slaver. What are you doing here?
{153}{}{Você pode dizer para ele que não posso... esperar. Quem é você? Você não é um escravista. O que
 está fazendo aqui?}
 
# My name is 
{154}{}{Meu nome é }

# . I'm here to get you out.
{155}{}{. Eu vim lhe tirar daqui.}

# I'm 
{156}{}{Eu sou }

# , but why have you been locked in this room?
{157}{}{, mas por que o trancaram nesse cômodo?}

# Can you tell me where Vault 13 is?
{158}{}{Pode me dizer onde fica a Vault 13?}

# I'm 
{159}{}{Eu sou }

# . I'll be right back.
{160}{}{. Eu já volto.}

# Dubba iba 
{161}{}{Dubba iba }

# .
{162}{}{.}

# Node 2

# Metzger's still quite upset with me, even though we fixed his darn radio.
 He's threatening to sell me off! I'll do anything you ask if you can get me out
 of this mess.
{163}{}{Metzger ainda está puto comigo, mesmo tendo consertado seu maldito rádio. Ele está ameaçando me vender!
 Eu faço qualquer coisa se conseguir me tirar daqui.}
 
# OK, I will.
{164}{}{OK, eu irei.}

# Sorry, I can't. Bye.
{165}{}{Desculpe, eu não posso. Adeus.}

# Whoo.
{166}{}{Duuh.}

# Node 3

# Oh, hi again. This darn radio isn't going to repair itself. How does
 he expect me to fix it?
{167}{}{Oh, olá de novo. Esse maldito rádio não vai se consertar sozinho. Como ele espera que eu consiga?}

# Where can I get the parts?
{168}{}{Onde eu posso conseguir as peças?}

# Maybe I can repair it.
{169}{}{Talvez eu possa consertar.}

# Can you use this radio I found?
{170}{}{Você pode usar este rádio que eu achei?}

# I'll see what I can do.
{171}{}{Verei o que posso fazer.}

# Spa pa?
{172}{}{Spa pa?}

# Node 4

# I know I can do it, I just need some spare parts. There is an old radio in
 my shack back in Klamath that has exactly what I need. You been to the Dunton's?
 My shack's... well, it was just east of their place.
{173}{}{Eu sei que consigo, mas preciso de umas peças. Tem um rádio velho na minha cabana em Klamath que
 tem exatamente o que preciso. Você conhece os Duntons? Minha cabana é... bem, fica logo ao leste deles.}
 
# Do you mean this radio?
{174}{}{Você quis dizer, este rádio?}

# I'll go look for it.
{175}{}{Eu vou procurá-lo.}

# Hmmm... I'll be back.
{176}{}{Hmmm... Eu voltarei.}

# Node 4b

# It's right here. [pointing to a map]
{206}{}{Está bem aqui. [aponta para um mapa]}

# Node 5

# That's great! I'll have the radio fixed in no time.
{177}{}{Ótimo! O rádio ficará pronto em breve.}

# Okay, I'll talk to Metzger.
{178}{}{Ok, eu vou falar com o Metzger.}

# Node 6

# Thanks.
{179}{}{Obrigado.}

# Bye.
{180}{}{Adeus.}

# Node 7

# Pardon? I'm sorry but I don't understand.
{181}{}{Quê? Desculpa mas eu não entendo.}
 
# hurm.
{182}{}{hurm.}

# Node 8

# Thank you! I'm forever in your debt. What can I do to repay you?
{183}{}{Obrigado! Serei eternamente grato. Como posso recompensá-lo?}

# Tell me where Vault 13 is.
{184}{}{Me diga como chegar à Vault 13.}

# Come with me, I could use a hand.
{186}{}{Venha comigo, eu preciso de uma mão.}

# It was nothing. Good bye.
{187}{}{De nada. Adeus.}

# Candy?
{188}{}{Doce?}

# Node 9

# Vault 13? There's a Vault City east of here. I trade there,
 sometimes.
{189}{}{Vault 13? Tem uma Vault City ao leste daqui. Eu tenho alguns negócios por lá.}

# Want to go there with me?
{190}{}{Quer ir lá comigo?}

# Thanks. Bye.
{191}{}{Obrigado. Adeus.}

# Node 10

# Sure, I'll join up with you! This old fart has one big adventure left
 in him. I'm sure of it! I'm pretty good at repairing things too, despite what
 Metzger says.
{192}{}{Claro, vou me juntar a você! Este velho ainda tem uma grande aventura pela frente. Tenho certeza! Eu
 também sou muito bom consertando coisas, a despeito do que o Metzger disse.}
 
# Great, let's go.
{193}{}{Ótimo, vamos.}

# Welcome aboard.
{194}{}{Bem vindo a bordo.}

# Whatever.
{195}{}{Que seja.}

# Vic me bess frend.
{196}{}{Vic mim meióres migos.}

# Node 11

# Want to join me on my search?
{197}{}{Quer participar da minha pesquisa?}

# Great! Thanks.
{198}{}{Ótimo! Obrigado.}

# Node 12 OLD IF IN PARTY. REMOVED NODE. Lines 199, 200, 202 (Don't know where 201 is)

# Node 13

# Vault City is east of here. I'll point it out on that map of yours.
{203}{}{Vault City é ao leste daqui. Eu vou marcar no seu mapa.}

# Thanks.
{204}{}{Obrigado.}

# Node 14

# Darn it. That's close, but I need the radio from my shack in Klamath. I know that one has the parts I need.
{220}{}{Merda. É quase isso, mas eu preciso do rádio da minha cabana em Klamath. Eu sei que ele tem as peças que preciso.}

# used in node 12 REMOVED 230 that was here. Node 12, removed. was What else do you need to know?

# Node 15

# Yeah, I can probably help you, but you've got to get me out of here first.
{300}{}{Sim, eu posso te ajudar, mas você precisa me tirar daqui primeiro.}

# I told you. If you can get me out of here, I'll help you with anything you want.
{301}{}{Eu falei para você. Se me tirar daqui, eu te ajudarei com o que quiser.}

# How do we do that?
{302}{}{Como faremos isso?}

# You're on you own then.
{303}{}{Se vire sozinho.}

# Okay, I'll see what I can do.
{304}{}{Ok, eu vou ver o que posso fazer.}

# Node 2b

# You think you can help me out?
{350}{}{Você acha que pode me ajudar?}

# Metzger still won't let me leave.
{351}{}{O Metzger não vai me deixar ir embora.}

# I can't take much more of this.
{352}{}{Eu não aguento mais isso.}

# I'll do anything for you if you help me.
{353}{}{Eu faço qualquer coisa se você me ajudar.}

# I'll earn back any expenses you may incur!
{354}{}{Eu vou reaver todas as despesas que você me causar.}

# 3b

# You haven't been by my place yet have you? I really need that radio,
 Metzger's getting angrier with me by the day.
{400}{}{Você ainda não foi até minha casa, não? Eu preciso muito daquele rádio, o Metzger fica mais puto
 comigo a cada dia.}

# water flask question, Question used in Node 9 and Node 1010

# Where did you get this water flask?
{450}{}{Onde você conseguiu esse cantil?}

# I had a water flask that had a big yellow 13 on it. Do you remember where you got it?
{451}{}{Eu tinha um cantil com um 13 amarelo no meio. Você lembra onde encontrou esse?}

# Additions to Node 11

# Oh, yeah. I remember that. I bought that from Ed. He's a brahmin dealer over in Vault City.
{500}{}{Ah, sim. Eu lembro. Eu comprei do Ed. Ele é um vendedor de brahmin de Vault City.}

# Water Flask? Oh, wait. Yea, I had a few dozen of'm. Sold pretty well. I got'm from Ed, a
 brahmin dealer over in Vault City.
{501}{}{Cantil? Espera. É, eu tinha uma porrada deles. Vendiam bem. Eu consegui com o Ed, um vendedor de 
 brahmin de Vault City.}
 
# Vault City?
{502}{}{Vault City?}

# Node 1000, if said Boss many times.

# Would you stop calling me Boss?
{550}{}{Pode parar de me chamar de Chefe?}

# Node 16

# Sure thing, Chief!
{600}{}{Claro, Patrão!}

# I mean it! STOP IT!
{601}{}{To falando sério! PARA COM ESSA PORRA!}

# I guess that'll have to do.
{602}{}{Acho que é o suficiente.}

# Node 17

# You got it, Sport!
{650}{}{Isso aí, Sport!}

# Uggg!
{651}{}{Uggh!}

# Bee my friend.
{700}{}{Seja meu amigo.}

# Node 1b - Added a line to node 1 for Vic

# Would you tell him I can't fix this without the parts. I don't know... wait.
 Who are you? Some new recruit? He didn't send you here to rough me up again did
 he? It's not going to make any difference. I can't fix it here.
{710}{}{Você poderia dizer para ele que eu não posso consertar sem peças. Eu não sei... espera. Quem é você?
 Um novo recruta? Ele não te mandou aqui para me torturar de novo, mandou? Não faz diferença. Eu não posso
 consertar aqui.}

# 20. Here to get you out. (From 1)

# Wow! You'd do that for me? I'd do anything if you could get me out this mess.
 Only problem is that Metzger's got me locked up here until I fix this radio and
 I don't have the parts I need.
{750}{}{Uau! Faria isso por mim? Eu faço qualquer coisa para você me tirar daqui. O único problema é que 
 o Metzger me trancou aqui até eu consertar o rádio e eu não tenho as peças necessárias.}
 
# Where can I get the parts you need?
{753}{}{Onde eu posso conseguir as peças que você precisa?}

# I'll see what I can do.
{754}{}{Verei o que posso fazer.}

# 21. Why in this room? (From 1)

# It's a long story. I guess you could say that Metzger's keeping me here until
 I fix this darn radio. The crystal's shot and I don't have any spare parts. How does
 he expect me to fix it?
{760}{}{É uma longa história. Acho que posso dizer que o Metzger vai me deixar aqui até eu consertar o maldito
 rádio. O cristal quebrou e não tenho um sobressalente. Como ele espera que eu conserte?}
 
# Well, I'm here to get you out.
{761}{}{Bem, eu vim te tirar daqui.}

# Don't know. See ya.
{764}{}{Não sei. Falou.}

# 22. How do we do that?

# I've got to get this radio fixed. If you can help me do that, then maybe we can reason with him.
{800}{}{Eu preciso consertar esse rádio. Se você me ajudar, acho que podemos conversar.}

# How can I help?
{801}{}{Como posso ajudar?}

# I doubt it. Good luck.
{803}{}{Duvido. Boa sorte.}

# 23. In Mom's, never joined party. (From WTG)

# Why'd you kill poor Mom… I guess you had your reasons… I'm sorry, Boss. It's not my place to question you. This is a pretty bad town. I'm sure she did something pretty bad.
{810}{}{Por que você matou a coitada da Mom... Acho que teve seus motivos... desculpa, Chefe. Não estou em 
 posição de questioná-lo. Esta cidade é bem ruim. Tenho certeza que ela fez algo muito errado.}
 
# Hey, Boss. Thanks for getting me out of that mess with Metzger. You need anything? Mom's been kind enough to feed me while you've been gone. I help her around the place….
{811}{}{Fala, Chefe. Obrigado por me tirar das mãos do Metzger. Precisa de alguma coisa? A Mom teve a bondade de me alimentar enquanto você estava longe. Eu ajudo ela a cuidar do lugar... .}

# Bye.
{812}{}{Adeus}

# Oooh.
{813}{}{Oooh.}

# Beiye
{814}{}{Tiau.}

# Additions to Node 9

# Where is your friend Ed, again?
{823}{}{Por onde anda seu amigo Ed, mesmo?}

# Additions to Node 10

# I would if I could, but you're just not looking good. I'd only be a burden. Now that Mom's gone, I think I'll just head out. Don't know where… maybe we'll see each other again. Thank you for everything you've done for me.
{830}{}{Eu iria se pudesse, mas você não parece bem. Seria um fardo para você carregar. Agora que Mom se foi, acho que vou embora. Não sei para onde... talvez nos veremos de novo. Obrigado por tudo que fez por mim.}

# I would if I could, but you're just not looking good. Looks like you can barely take care of yourself. I'd only be a burden. I'll just wait here, Mom's cooking reminds me of my ex-wife….
{831}{}{Eu iria se pudesse, mas você não parece bem. Parece que mal pode cuidar de si mesmo. Eu seria um fardo para você carregar. Eu vou esperar aqui, a comida da Mom me lembra de minha ex-esposa... .}

# I would, honest. I'd do almost anything for you. It's just that you don't look like you're in any shape to lead anyone. I'd only be a burden. I'll just head over to Mom's, in a bit… until you can work things out. I haven't had her home cooking for a long time.
{832}{}{Eu iria, sério. Eu faria quase qualquer coisa por você. Só que parece que você não está em forma para liderar ninguém. Eu seria apenas um fardo. Eu vou ficar lá na Mom, um pouco... até você resolver seus problemas. Faz tempo que não como a comida caseira dela.}
 
# Sorry, Boss. Looks like you're pretty crowded. Now that Mom's gone, I think I'll just head out. Don't know where… maybe we'll see each other again. Thank you for everything you've done for me.
{833}{}{Desculpa, Chefe. Parece que seu grupo está lotado. Agora que a Mom se foi, acho que vou embora. Não sei para onde... talvez nos veremos de novo. Obrigado por tudo que fez por mim.}

# You're looking a bit crowded, Boss. I'll just wait here for you until you've worked things out. Mom's cooking reminds me of my ex-wife… not sure if that's a good thing or bad thing….
{834}{}{Seu grupo parece meio lotado, Chefe. Vou esperar aqui até você resolver suas coisas. A comida da Mom me lembra de minha ex-esposa... não sei se isso é uma coisa boa ou ruim.}

# I would love to, Boss. It's just that you don't look like you have any more room. I'll just head over to Mom's. I haven't been there in a while. Just come get me if you find some room for me.
{835}{}{Eu adoraria, Chefe. Mas parece que não tem mais espaço no grupo. Vou esperar na Mom. Faz tempo que não fui lá. Venha me buscar quando tiver espaço no grupo.}

# Additions to Node 11

# Ed's over at Vault City. He's a Brahmin Dealer. He was just one of my many suppliers. Vault City's not too far from here.
{840}{}{Ed foi para Vault City. Ele é um vendedor de brahmin. Ele era um dos meus fornecedores. Vault City não é muito longe daqui.}

# Additions to Node 13

# I told you, it's over here. [Vic points to a location on your PIPBoy2000.]
{845}{}{Eu já disse, é bem aqui. [Vic aponta para um lugar em seu PIPBoy2000.]}

# You learned about Vic being a trader.
{900}{}{Você descobriu que Vic era um comerciante.}

# 1000 in party dialog

# I need to ask you something.
{1000}{}{Preciso te perguntar uma coisa.}

# 1001 After healing

# Fully healed, Boss. Anything else?
{1100}{}{Totalmente saudável, Chefe. Mais alguma coisa?}

# Almost perfect condition, Boss.
{1200}{}{Praticamente novo, Chefe.}

# I'm mostly healed up, Boss, but I've been better.
{1300}{}{Estou bem, Chefe, mas já estive melhor.}

# I tried, Boss, but I'm not doing so hot. I'll do what I can though.
{1400}{}{Estou indo, Chefe, mas não estou tão bem. Mesmo assim farei o que puder.}

# 1002 I need you to wait here until I come back

# Whatever you say, Boss.
{1500}{}{Como quiser, Chefe.}

# Here? Right here? Okay, you're the Boss.
{1501}{}{Aqui? Bem aqui? Ok, você é o Chefe.}

# Right. I'll stay here until you come back, Boss. You will come back, right?
{1502}{}{Certo. Vou ficar aqui até você voltar, Chefe. Você vai voltar, certo?}

# As long as you want. I'm not going anywhere.
{1503}{}{Espero o quanto quiser. Não sairei daqui.}

# Of course, Boss.
{1504}{}{Claro, Chefe.}

# 1003 Put your weapon away.

# If you say so.
{1600}{}{Você que manda.}

# Good call Boss.
{1601}{}{Boa ideia, Chefe.}

# Great thinking, Boss.
{1602}{}{Genial, Chefe.}

# Sure, Boss. Anything else?
{1603}{}{Claro, Chefe. Mais alguma coisa?}

# Away it is, Boss.
{1604}{}{Já guardei, Chefe.}

# No problem, Boss.
{1605}{}{Sem problema, Chefe.}

# Done, Boss.
{1606}{}{Pronto, Chefe.}

# 1004 Stay close to me

# Sure, Boss.
{1700}{}{Claro, Chefe.}

# Close it is, Boss.
{1701}{}{Estou na cobertura, Chefe.}

# You know best, Boss.
{1702}{}{Você que sabe, Chefe.}

# I'm right behind ya, Boss.
{1703}{}{Estou bem atrás de você, Chefe.}

# Like glue, Boss.
{1704}{}{Igual unha e carne, Chefe.}

# If you say so, Boss.
{1705}{}{Você que manda, Chefe.}

# Oh. Okay, Boss.
{1706}{}{Oh. Ok, Chefe.}

# 1005 Don't get too far away.

# OK, I'll keep my distance, but not too far, Boss.
{1800}{}{OK, vou manter distância, mas não muita, Chefe.}

# Okay, I won't, Boss.
{1801}{}{Ok, Chefe.}

# I'll just stay back a little then, Boss.
{1802}{}{Vou ficar um pouco para trás então, Chefe.}

# Sure, Boss.
{1803}{}{Claro, Chefe.}

# 1006 We should spread out a bit

# Right Boss. I'll hang way back.
{1900}{}{Certo Chefe. Vou ficar aqui atrás.}

# What ever you say, Boss.
{1901}{}{Como quiser, Chefe.}

# There you go, Boss.
{1902}{}{Estou indo, Chefe.}

# Standing back, Boss.
{1903}{}{Aqui atrás, Chefe.}

# Backing away, Boss.
{1904}{}{Estou voltando, Chefe.}

# Spreading out, Boss.
{1905}{}{Espalhando, Chefe.}

# Okay, Boss.
{1906}{}{Ok, Chefe.}

# 1100a Rejoin: Crowded

# Uh, Boss? You seem a bit crowded. I'll just keep waiting here for ya.
{2000}{}{Uh, Chefe? O grupo parece lotado. Vou ficar esperando você voltar.}

# 1100b Rejoin: Additional NPC response, PC Charisma 1

# You're scaring me, Boss. What's happened to you? You look... well,
 scary. I think I'll just hang out here for a while...
{2100}{}{Você está me assustando, Chefe. O que houve com você? Você parece... bem, assustador. Acho que vou 
 ficar por aqui mais um pouco...}

# 1100c Rejoin:

# You bet, Boss!
{2200}{}{Pode apostar, Chefe!}

# Darn right I will, Boss.
{2201}{}{Claro que quero, Chefe.}

# Sure thing, Boss.
{2202}{}{Claro, Chefe.}

# Ready to go when you are, Boss.
{2203}{}{Estou pronto para ir, Chefe.}

# Great! Let's go.
{2204}{}{Ótimo! Vamos.}

# Great!
{2205}{}{Ótimo!}

# You're the best, Boss!
{2206}{}{Você é o melhor, Chefe!}

# You won't be disappointed. No more mistakes!
{2207}{}{Você não vai se arrepender. Nada de erros!}

# I'll be careful this time, don't you worry!
{2208}{}{Vou ser mais cuidadoso dessa vez, não se preocupe!}

# I knew you would forgive me for that… um. So, uh, Boss. What's the plan?
{2209}{}{Sabia que ia me perdoar por aquilo... um. Então, eh, Chefe. Qual é o plano?}

# I won't let you down, Boss!
{2210}{}{Não vou te decepcionar, Chefe!}

# You're super, Boss!
{2211}{}{Você é foda, Chefe!}

# I knew I wasn't too old for this. Those were just bad odds! Right, Boss?
{2212}{}{Eu sabia que não estava velho demais para isso. Aquilo foi só azar! Certo, Chefe?}

# 1007 Vault 13 Flask?

# From Ed. He's a brahmin dealer over in Vault City. You been there before?
 Let me show you on that map thing of yours.
{2300}{}{Do Ed. Ele é um vendedor de brahmin de Vault City. Já esteve lá? Deixe-me mostrar no seu mapa.}

# 1008 Where's Ed again? Not Marked

# Vault City. Here. Let me show you on that fancy map thing of yours.
{2305}{}{Vault City. Aqui. Deixe-me mostrar nesse seu mapa maneiro.}

# 1009 Where's Ed again?

# He should be around here somewhere.
{2310}{}{Ele deveria estar por aqui.}

# Vault City. Check that fancy map thing of yours.
{2311}{}{Vault City. Dê uma olhada no seu mapa.}

# 1010 Other Questions

# Where did you get the Vault 13 water flask?
{2403}{}{Onde conseguiu o cantil de Vault 13?}

# Never mind.
{2404}{}{Esquece.}

# 1011 Other questions greeting (From 1000)

# Sure, Boss.
{2500}{}{Claro, Chefe.}

# Ask anything, Boss.
{2501}{}{Pode perguntar, Chefe.}

# I'll help you if I can, Boss.
{2502}{}{Vou ajudar no que puder, Chefe.}

# I'm not in trouble am I, Boss?
{2503}{}{Não estou ferrado, não é Chefe?}

# Did I do something wrong, Boss?
{2504}{}{Eu fiz algo errado, Chefe?}

# Of course.
{2505}{}{Com certeza.}

# 1012 Standard Greeting, (WTG) Moved From Node 1000

# What'll we do now, Boss?
{2600}{}{O que faremos agora, Chefe?}

# What's the plan, Boss?
{2601}{}{Qual é o plano, Chefe?}

# Doing my best, Boss.
{2602}{}{Estou fazendo o melhor, Chefe.}

# What can I do for you, Boss?
{2603}{}{O que posso fazer por você, Chefe?}

# Change of plans, Boss?
{2604}{}{Mudança de planos, Chefe?}

# Different strategy, Boss?
{2605}{}{Tem outra estratégia, Chefe?}

# 1013 Crippled

# Boss, they got me good. You've got to get me to a doctor. I don't know if I can
 back you up anymore.
{2700}{}{Chefe, dessa vez me pegaram. Me leva para o médico. Não sei se ainda consigo te dar suporte.}
 
# I need a doctor, Boss. I'm really messed up. I don't know if I can fight
 with you anymore.
{2701}{}{Preciso de um médico, Chefe. Estou muito ferido. Acho que não posso mais lutar ao seu lado.}

# Boss, I'm really messed up. You got to get Lenny to check me out.
{2702}{}{Chefe, estou muito ferido. Você precisa me levar para o Lenny.} 

# 1014 Waiting

# Hey, Boss. You want me to join up with you now?
{2800}{}{Ei, Chefe. Quer que eu me junte ao grupo?}

# Hey, Boss. I don't mind waiting for you. I'm a real patient man.
{2801}{}{Ei, Chefe. Eu não ligo de te esperar. Eu sou bem paciente.}

# We joining up again, Boss? I'll try harder.
{2802}{}{Vamos nos juntar de novo, Chefe? Vou dar o melhor.}

# I was afraid you might not come back. It sure is nice to see you again, Boss.
{2803}{}{Achei que não ia mais voltar. É bom te ver de novo, Chefe.}

# You looking for company again?
{2804}{}{Precisando de companhia?}

# I'm ready to go, Boss.
{2805}{}{Pronto para ir, Chefe.}

# I knew you wouldn't leave me.
{2806}{}{Sabia que você não me abandonaria.}

# Need some back up?
{2807}{}{Precisa de ajuda?}

# Need something repaired, don't you? I'm your man, Boss!
{2808}{}{Precisa que eu conserte alguma coisa, não? Veio ao cara certo, Chefe!}

# Don't worry, Boss. Sulik and I'll get along, honest.
{2809}{}{Não se preocupe, Chefe. Sulik e eu vamos nos dar bem, sério.}

# Let's go.
{2810}{}{Vamos.}

# Stay here. I'll be right back.
{2811}{}{Fique aqui. Eu já volto.}

# Me go.
{2812}{}{Mim ir.}

# 1017 Remove armor: Yes

# What? Uh… okay, Boss. If you say so.
{3100}{}{Quê? Uh... ok, Chefe. Já que insiste.}

# Can I put something else on, Boss? I'm a little worried.
{3101}{}{Posso colocar outra no lugar, Chefe? Estou um pouco preocupado.}

# Okay… you're not going to leave me here… Are you, Boss?
{3102}{}{Ok... você não vai me deixar aqui... Vai, Chefe?}

# But… I mean… Of course, Boss. Coming right off.
{3103}{}{Mas... Eu... Claro, Chefe. Já estou tirando.}

# 1018 Best Weapon

# Well, Boss…. I'm pretty good with small arms. I can handle almost any rifle, shotgun, and most small-medium pistols. I 'can' use knives. I've also got a pretty good throwing arm, but my aim's not the best in the world… actually, it's pretty horrible. Sorry, Boss. I'm really trying to get better.
{3200}{}{Bem, Chefe... . Eu sou bom com armas leves. Posso usar quase qualquer tipo de rifle, shotgun, e a maioria das pistolas pequenas e médias. Eu 'posso' usar facas. Eu também sou bom arremessando, mas minha mira não é das melhores... na verdade, é horrível. Desculpa, Chefe. Estou me esforçando o máximo para melhorar.}

# Like I said, Boss, I prefer small arms. I can handle almost any rifle, shotgun, and most of those small-medium pistols. If we're really in a pinch I can try using a knife or even thrown weapons.
{3201}{}{Como eu disse, Chefe, eu prefiro armas leves. Posso usar quase qualquer tipo de rifle, shotgun, e a maioria das pistolas pequenas e médias. Se estivermos desesperados, posso tentar usar uma faca ou até armas de arremesso.}

# 1019 Other weapons he can use.

# I 'can' use knives and I've got a pretty good throwing arm, but… my aim's not the best in the world. Actually it's pretty horrible. Sorry, Boss. I'm really trying to get better.
{3300}{}{Eu 'posso' usar facas. Eu também sou bom arremessando, mas minha mira não é das melhores... na verdade, é horrível. Desculpa, Chefe. Estou me esforçando o máximo para melhorar.}

# Like I said, Boss. Knives and I've got pretty good throwing arm… I just miss a lot.
{3301}{}{Como eu disse, Chefe. Uso facas e tenho um braço bom para arremessos... O problema é que eu erro bastante.}

# 1020 Hostile

# I've had it up to here!
{3400}{}{Já chega!}

# I'm going to rip your darn head off! No one hurts my family!
{3401}{}{Vou arrancar sua cabeça! Ninguém machuca minha família!} 

# 1101 Vic's being Pushed

# Over here?
{4000}{}{Pra cá?}

# This better Boss?
{4001}{}{Aqui é melhor, Chefe?}

# How 'bout here?
{4002}{}{Que tal aqui?}

# Yes Boss.
{4003}{}{Sim Chefe.}

# What?
{4004}{}{Quê?}

# Where we going?
{4005}{}{Para onde vamos?}

# We leaving Boss?
{4006}{}{Estamos saindo, Chefe?}

# I'm moving.
{4007}{}{Saindo.}

# Sorry Boss.
{4008}{}{Desculpa Chefe.}

# Better?
{4009}{}{Melhor?}

# Ooof.
{4010}{}{Ooof.}

# How's this Boss?
{4011}{}{Assim, Chefe?}

# I'll stand over here.
{4012}{}{Vou ficar aqui.}

# I'll just move over here now.
{4013}{}{Vou para lá.}

# 1102 BGF: Crippled

# Boss! I'm not doing so well here.
{4100}{}{Chefe! Não estou me sentindo bem.}

# I need a doctor.
{4101}{}{Preciso de um médico.}

# Oh, boy. This really hurts.
{4102}{}{Puta merda. Que dor.}

# Ow!
{4103}{}{Ow!}

# Ouch.
{4104}{}{Ai.}

# Dang it.
{4105}{}{Porra.}

# Medic?
{4106}{}{Doutor?}

# I'm hanging in there… barely.
{4107}{}{Eu vou aguentar... acho.}

# 1103 Removed

# 1104 BGF: Random on Specific Map

# I never liked this place.
{4200}{}{Eu nunca gostei desse lugar.}

# Why is this place so clean?
{4201}{}{Por que esse lugar é tão limpo?}

# Do you smell something, Boss?
{4202}{}{Algo errado, Chefe?}

# You know, Boss. I don't think I'll be coming back here when we're through. I can no longer call it home.
{4203}{}{Sabe, Chefe. Acho que nunca mais vou voltar para cá depois que terminarmos. Não posso mais chamar aqui de lar.}

# It sure is a lot dirtier than I remember.
{4204}{}{Com certeza é bem mais sujo do que me lembro.}

# We're not staying here long, are we Boss?
{4205}{}{Não vamos ficar aqui muito tempo, vamos Chefe?}

# This place'll never change.
{4206}{}{Esse lugar parou no tempo.}

# Boss, I'm not going to miss this place.
{4207}{}{Chefe, eu não vou sentir falta daqui.}

# Thanks again for getting me out of this place, Boss.
{4208}{}{Obrigado de novo por me tirar daqui, Chefe.}

# I really owe you one, Boss.
{4209}{}{Eu te devo uma, Chefe.}

# Wow, this place sure has changed.
{4210}{}{Uau, esse lugar mudou completamente.}

# I haven't been here in ages.
{4211}{}{Faz tempo que não vim aqui.}

# I'm going to retire here.
{4212}{}{Vou me aposentar aqui.}

# I could open a repair shop around here.
{4213}{}{Eu posso montar uma oficina de consertos por aqui.}

# 1105 BGF: for specific area on a map

# Ah, a sight for sore eyes. This is… was my place, but I guess you knew that. Right, Boss?
{4300}{}{Ah, de brilhar os olhos. Aqui é... foi meu lar, mas acho que já sabe disso. Certo, Chefe?}

# 1106 Removed

# 1107 BGF: with Specific NPC

# Sulik, don't you be looking at me like that.
{4400}{}{Sulik, não olhe assim para mim.}

# Boss, Sulik's glaring at me again.
{4401}{}{Chefe, o Sulik está me encarando de novo.}

# Nice pooch.
{4402}{}{Bom vira-lata.}

# 1108. BGF: Level Up, Not to be Placed in MSG file

# 1109. BGF: Waiting

# La de da…
{4500}{}{La ra ra...}

# Ho hum.
{4501}{}{Hu hum.}

# Waiting for the Boss…
{4502}{}{Esperando pelo Chefe...}

# I'm waiting for the Boss.
{4503}{}{Estou esperando o Chefe.}

# Just waiting.
{4504}{}{Só esperando.}

# The Boss sure wouldn't leave me behind…
{4505}{}{O Chefe nunca me deixaria para trás...}

# Knock Knock… who's there… wait. How'd that go…
{4506}{}{Toc Toc... quem é... espera. Como era mesmo...}

# Still waiting.
{4507}{}{Ainda esperando.}

# What's that smell?
{4508}{}{Que cheiro é esse?}

# Anything to repair around here?
{4509}{}{Será que tem algo para consertar aqui?}

# Here I am… waiting for the Boss.
{4510}{}{Aqui estou... esperando pelo Chefe.}

# An old man like me, wasting away his talents, just standing here.
{4511}{}{Um velho como eu, desperdiçando seu talento, plantado aqui.} 

# I sure wish I had a stick of gum… it's been decades.
{4512}{}{Eu bem que queria uma goma de mascar... já fazem décadas.}

# I need to get out of the relic business… nothing but trouble.
{4513}{}{Preciso sair do negócio de relíquias... só dá dor de cabeça.}

# Why is waiting so tiring…
{4514}{}{Por que esperar cansa tanto...}

# 1110. PC used Healing on PC

# Uh, thanks, Boss.
{4600}{}{Uh, valeu, Chefe.}

# Thanks.
{4601}{}{Obrigado.}

# You sure you know what you're doing?
{4602}{}{Você sabe o que está fazendo?}

# Can't we just rest instead?
{4603}{}{Não podemos descansar um pouco?}

# Should we make camp?
{4604}{}{Podemos acampar aqui?}

# Am I that bad off?
{4605}{}{Estou tão errado assim?}

# 1111. PC used Drugs on NPC

# Not too much, Boss.
{4700}{}{Nada de mais, Chefe.}

# If you insist, Boss.
{4701}{}{Já que insiste, Chefe.}

# Boss, my head's not going to explode, is it?
{4702}{}{Chefe, minha cabeça não vai explodir, vai?}

# Boss, I think I'm starting to like that stuff.
{4703}{}{Chefe, esse barato é muito louco.}

# I'm feeling a bit funny, Boss.
{4704}{}{Tá tudo girando, Chefe.}

# You sure you have enough of that to spare.
{4705}{}{Você tem mais desses?}

# Sure, Boss. I'll take some.
{4706}{}{Claro, Chefe. Só um pouco.}

# Thanks, Boss.
{4707}{}{Obrigado, Chefe.}

# Not bad.
{4708}{}{Nada mal.}

# I'm a bit hungry at the moment. We'll talk again at Mom's.
{5000}{}{Estou morrendo de fome. Nos falamos lá na Mom.}

#added by killap - NPC info

# I feel like I broke a limb, Boss. You better have a look.
{5500}{}{Acho que quebrei alguma coisa, Chefe. Melhor você dar uma olhada.}

# I feel like I am burning up, Boss. You better have a look.
{5501}{}{Sinto algo queimando, Chefe. Melhor você dar uma olhada.}

# I feel like I have been poisoned, Boss. You better have a look.
{5502}{}{Acho que fui envenenado, Chefe. Melhor você dar uma olhada.}
