# 0. Look
#
#You see a bulletin board.
{100}{}{Você vê um quadro de mensagens.}

#There seem to be a few messages posted on it.
{150}{}{Parece haver algumas mensagens escritas nele.}

# 1. Main Page
#Den Bulletin: Maintained by Rebecca's Casino Bar, best drinks in the Den!
{200}{}{Boletim da Caverna: Mantido pelo Bar Cassino de Rebecca, melhores bebidas da Caverna!}
#Den Bulletin: Maintained by Rebecca's Casino Bar...
{201}{}{Boletim da Caverna: Mantido pelo Bar Cassino de Rebecca...}
#[Someone has scribbled something on the side of this post.]!
{202}{}{[Alguém já escreveu algo ao lado desta mensagem.]!}
#[You notice that a part of this post has been torn off.]!
{203}{}{[Dá para perceber que uma parte desta postagem foi arrancada.]!}
#Slaver's Guild!
{204}{}{Associação dos Escravistas!}
#Bars & Gambling!
{205}{}{Bares e Apostas!}
#Dining!
{206}{}{Restaurantes!}
#Shops!
{207}{}{Lojas!}

# 2. Slaver's Guild
#The Slaver's Guild is the best and only supplier of slaves in the wastes.
{225}{}{A Associação dos Escravistas é a melhor e única fornecedora de escravos disponíveis.}

# 3. Slaver's - Continue
#For employment opportunities, buying or selling of slaves, see Slave Master Metzger.
{250}{}{Para oportunidades de emprego, compra ou venda de escravos, fale com o Senhor de Escravos Metzger.}

# 4. Slaver's - Directions
#The Slaver's Guild is located on the east side of town, past Becky's and Frankie's.
{275}{}{A Associação dos Escravistas está localizada no lado leste da cidade, logo que passar pelos locais Becky e Frankie.}

# 5. Slaver's - Not selling
#They are currently not selling slaves to the general public, due to increased demand.
{300}{}{Atualmente, não estão vendendo escravos para o público em geral, devido ao aumento da demanda.}

# 6. Bars and Gambling
#[Two are listed.]!
{325}{}{[Tem dois na lista.]!}

# 7. Becky's Casino Bar
#Rebecca's Casino Bar has both gambling and great affordable drinks.
{350}{}{O Bar Cassino de Rebecca tem tanto jogos de apostas como excelentes bebidas econômicas.}

# 8. Becky's Directions.
#We are located just east of here. We are the first building on the left as you enter town. Be sure to come by and say hello!
{375}{}{Estamos localizados bem a leste daqui. Estamos no primeiro edifício à esquerda assim que se entra na cidade. Não deixe de passar por aqui e dar um Olá!}

# 9. Frankie's Message
#Becky's a hore and her drinks is watered down! She's a krook and a lier! [The writing is barely legible.]!
{400}{}{Becky é uma puta e suas bebidas são aguadas! Ela é uma Desonesta e mentirosa! [A escrita está quase ilegível.]!}
#[The message that was here is neatly torn off.]!
{401}{}{[A mensagem que estava aqui foi claramente arrancada.]!}

# 10. Dumb Board
#Words words... by... words... Bar... words... in the Den.
{425}{}{Papo furado e papo furado... mais... bláblabláh...... Bar... e bláblabla... na Caverna.}
#You find it all very confusing and your head starts to hurt.
{426}{}{Percebe-se que tudo é muito confuso e sua cabeça começa a doer.}

# 11. Frankie's
#Frankie runs a bar, inn, and 'pleasure' business on the east side of town.
{450}{}{Frankie toca um bar, uma pensão, e um negócio de 'prazer' no lado leste da cidade.}

# 12. Dining
#Mom's is the only restaurant in the Den. She's located on the east side of town just south of the Slaver's Guild.
{475}{}{O da Mama é o único restaurante na Caverna. Está localizado no lado leste da cidade logo atrás da Associação dos Escravistas.}

# 13. Becky Dead
#[It looks like someone tried to set it on fire. You can't make out any of the posts.]!
{500}{}{[Parece que alguém tentou tacar fogo nele. Não se consegue entender nenhuma das mensagens.]!}

# 14. Shops
#[There are three posts.]!
{525}{}{[Tem três mensagens.]!}

# 15. Tubby's
#Tubby sells all sorts of items, but primarily drugs and ammo.
{550}{}{Tubby vende todos tipos de coisas, mas principalmente drogas e munições.}

# 16. Tubby's Directions
#Tubby's is located west of this bulletin board. It's the first building on the right as you enter town.
{575}{}{Tubby se localiza a oeste deste mural de avisos. É o primeiro prédio à direita ao entrar na cidade.}

# 17. Flick
#Flick sells various items out of his 'office' in the residential building directly south from here and right below Rebecca's Casino Bar.
{600}{}{Flick vende vários itens em seu 'escritório' no edifício residencial indo direto para o sul daqui e logo abaixo do Bar Cassino de Rebecca.}

# 18. Smitty
#Smitty is the local mechanic. He sometimes has things for sale.
{625}{}{Smitty é o mecânico local. Ele às vezes tem coisas para vender.}

# 19. Smitty Directions
#Smitty's located in the junkyard on the southwest corner of town.
{650}{}{Smitty está localizado no ferro-velho no canto sudoeste da cidade.}

# MENU OPTIONS
#Continue!
{1000}{}{Continuar!}
#Directions:!
{1010}{}{Direções:!}
#Exit!
{1020}{}{Saída!}
#Flick's!
{1030}{}{Local Flick!}
#Frankie's!
{1040}{}{Local Frankie!}
#Rebecca's Casino Bar!
{1050}{}{Bar Cassino da Rebecca!}
#Return to Main Page!
{1060}{}{Retornar a Página principal!}
#Smitty!
{1070}{}{Local Smitty!}
#Special Note:!
{1080}{}{Nota especial:!}
#Tubby's!
{1090}{}{Local Tubby!}
