#############################################################
#  Message File: diDiary.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 13,1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

#You see an old diary.
{100}{}{Você vê um diário velho.}
#It appears to be a diary which belonged to a young girl. The writing on the inside cover says: "Property of Anna"
 Most of the pages are either torn or faded, but one is still readable. "Day 271: Today my mother gave me a gold locket.
 It is the most beautiful thing I have ever owned. I will never part with it."
{101}{}{Parece ser um diário que pertencia a uma jovem. A escrita na parte interna da capa diz: "Propriedade de Anna"
 A maioria das páginas estão rasgadas ou desbotadas, mas uma delas ainda está legível. "Dia 271: Hoje minha mãe me deu um medalhão de ouro.
 É a coisa mais linda que já tive. Nunca irei me separar dele."}
#The old diary is too frail to keep handling.
{102}{}{O antigo diário está muito frágil para ficar manuseando.}
