#I feel so strange... but was that her gardener or her best friend's second cousin's brother-in-law? My head hurts.
{100}{}{Me sinto tão estranho... mas aquele era o jardineiro dela ou o segundo cunhado do primo de seu melhor amigo? Chega doer minha cabeça.}
#That was beautiful... but he didn't deserve her.
{101}{}{Isso foi lindo... mas ele não a merecia.}
#<sniff, sniff>!
{102}{}{<sniff, sniff>!}
#Why do I keep reading this crap?
{103}{}{Por que continuo lendo esta porcaria?}

#You feel all warm and fuzzy after finishing the book, but gain nothing useful out of it.
{200}{}{Você sente todo entusiasmado e confuso depois de terminar de ler o livro, mas não ganhou nada de útil com isso.}
