#############################################################
#  Message File: ACBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um brahmin comum domesticado.}
{101}{}{A cabeça extra do brahmin é provavelmente resultado
  de uma vaca comum sendo exposta à radiação cedo de mais.}
{102}{}{Você não percebe nada de estranho no brahmin.}
{103}{}{Brahmins não são muito de conversar.}
{104}{}{Você não tem nada melhor pra fazer do que perder seu
  tempo falando com vacas de duas cabeças?}
{105}{}{Brahmins são uma raça de vacas mutantes.}
