{100}{}{Você vê um posseiro.}.
{101}{}{Você vê Bill, o posseiro.}
{102}{}{Um homem de meia-idade com roupas esfarrapadas.}
{103}{}{Me desculpe, forasteiro. Mas não tenho tempo pra falar com você.}
{104}{}{Ei, já disse que não tenho tempo pra conversas. Vá embora, por favor.}
{105}{}{Obrigado por ajudar Rebecca. Isso foi uma coisa boa que você fez.}
{106}{}{Me deixe em paz. Não ofereço nenhuma ameaça a você.}
{107}{}{Ta bom, ta bom. Já to saindo.}
