{100}{}{Você vê uma mulher jovem.}
{101}{}{Você vê Chrissy, a filha de Rebecca.}
{102}{}{Você vê uma jovem atraente. Ela parece confiante e capaz de se virar numa luta.}
{103}{}{Se veio aqui tentar me estrupar, vai acabar usando suas bolas como gravata borboleta. Sacou?}
{104}{}{Deixe-me adivinhar. Os caras estão cansados de tanto eu dar chutes onde dói neles, 
 então te enviaram aqui para fazer alguma coisa obscena. Bom, posso te machucar do mesmo jeito. 
 Só preciso chutar mais pra cima. Sacou?}
{105}{}{Gravata borboleta?}
{106}{}{}
{107}{}{O que está acontecendo aqui? Quem é você?}
{108}{}{}
{109}{}{Estou gostaria de saber quem é você e o que está acontecendo aqui.}
{110}{}{Isso! Um pomposo pedaço de pano enrolado ao redor do pescoço usado para enfeite. É como um cachecol, 
 só que para homens. Agora me imagine te dando um chute TÂO forte que você vai terminar usando seu saco ao redor do pescoço. Entendeu?}
{111}{}{Eu entendi. Não me machuque.}
{112}{}{Entendi tudinho. Não me machuque, por favor.}
{113}{}{Ta bom. E então, o que faz aqui?}
{114}{}{}
{115}{}{O que esta acontecendo? Quem é você?}
{116}{}{}
{117}{}{Estou gostaria de saber quem é você e o que está acontecendo aqui.}
{118}{}{Sério? Que bom! Vamos!}
{119}{}{Ok.}
{120}{}{Resumindo, meu nome é Chrissy e sou do acampamento. Semana passada estava dando uma olhada 
 por aqui quando encontrei aquela entrada estranha. Pensei que poderia ser uma mina abandonada ou alguma outra coisa, 
 então decidi verificar. Bom, não é uma mina. É uma passagem secreta para o Vault 15, que está sendo usado como base 
 por um bando de raiders chamado Khans. Eles me pegaram bisbilhotando e o seu líder, Darion, mandou me prender aqui.}
{121}{}{Ok, vou te levar pra casa.}
{122}{}{Ok. Vou te levar pra casa.}
{123}{}{Por deus! Hoje deve ser meu dia de sorte. A que devo o prazer de te ver de novo?}
{124}{}{}
{125}{}{O que está acontecendo aqui? Quem é você?}
{126}{}{}
{127}{}{Quero saber quem é você e o que ta fazendo aqui.}
{128}{}{Me leve para minha mãe Rebecca, por favor.}
{129}{}{Meu príncipe com armadura brilhante voltou. Bem, brilharia se você limpasse de vez enquanto. 
 Ah, e você poderia pensar em tomar um banho também. Então, como posso te ajudar?}
{130}{}{Só passei pra dizer oi. Agora tenho que ir.}
{131}{}{Só passei pra dizer oi. Agora tenho que ir.}
{132}{}{Ei, eu sei que tenho a boca grande, mas quero que saiba que sou muito grata por me salvar. Muito obrigada!}
{133}{}{De nada.}
{134}{}{Você é bem-vindo!}
{135}{}{As pessoas daqui estão protegendo esses caras ajudando a manter o Vault em segredo, 
 mas eles não sabem o que está acontecendo de verdade. Darion nos disse que o vault estava sendo consertado 
 para que pudéssemos ter um lugar seguro para viver, com muita comida e água, mas é tudo mentira. 
 Eu estive lá e vi tudo. O vault está morto, as máquinas de alimento e água não funcionam. 
 Nossa água e comida são das caravanas roubadas por eles.}
{136}{}{Olha só, tenho que ir pra casa e avisar a todos sobre o que está acontecendo aqui de verdade.
 Não podemos ajudar esses monstros. Vai me levar pra casa?}
