{100}{}{Você vê uma jovem com roupas esfarrapadas.}
{101}{}{Você vê Dalia.}
{102}{}{Você vê uma jovem com roupas esfarrapadas. Ela parece estar bem alerta e vigia cuidadosamente tudo à sua volta.}
{103}{}{Sou Dalia. Pois não?}
{104}{}{Nada, só passando pra dá um 'oi'.}
{105}{}{Uh, quem é você?}
{106}{}{O que faz aqui?}
{107}{}{Você se parece com um guarda.}
{108}{}{Tenho que ir agora.}
{109}{}{Só passando pra cumprimentar.}
{110}{}{Quem é você?}
{111}{}{O que você está fazendo?}
{112}{}{Parece que você ta vigiando esse caminho.}
{113}{}{Tenho que ir.}
{114}{}{Bom, olá. Me desculpe, mas você tem que ir embora.}
{115}{}{Eu preciso conversar.}
{116}{}{Ok, tenho que ir.}
{117}{}{Quero conversar contigo.}
{118}{}{Tchau.}
{119}{}{Disse que me chamo Dalia. Olha só, sem querer ser rude, mas não to afim de conversar com ninguém agora, ta bom?}
{120}{}{Ta bom. Tchau.}
{121}{}{Só um porquinho mais, vai!}
{122}{}{Já que é assim, to partindo.}
{123}{}{Só quero te fazer uma pergunta.}
{124}{}{Adoro ar fresco, árvores, e por isso estou aqui de pé. Algum problema?}
{125}{}{Desculpa. To indo.}
{126}{}{Tem problema não. Só quero te fazer uma pergunta.}
{127}{}{Problema nenhum, mas estou curioso sobre umas coisas.}
{128}{}{Desculpe, tenho que ir.}
{129}{}{Não, não estou vigiando o caminho. Não tem nada aqui neste buraco que vale a pena ser vigiado. 
 Já te disse que adoro ar fresco. Agora vá embora.}
{130}{}{Você é boa de conversa. Me fale mais..}
{131}{}{Desculpa te incomodar. Estou indo.}
{132}{}{Mas nosso papo ta ótimo! Por que parar?}
{133}{}{Acho que ta na hora de partir.}
{134}{}{Oh não, é a praga novamente. Olha, eu não tenho nada para lhe dizer. Vai embora!}
{135}{}{}
{136}{}{}
{137}{}{Não tenho nada contra você. Esquece que eu existo!}
{138}{}{}
{139}{}{}
{140}{}{Oi! Sou Dalia. Pois não?}
{141}{}{Viu alguém passar correndo por aqui?}
{142}{}{Nada.}
{143}{}{Nada.}
{144}{}{Viu alguém passar correndo por aqui?}
{145}{}{Vejo pessoas passando aqui todos os dias. Mas não presto muita atenção nelas.}
{146}{}{Eu não tenho tempo pra essas suas besteiras.}
{147}{}{Ah, ta bom.}
{148}{}{Olha só, a vida de uma jovem está em perigo. Filha de uma mãe preocupada. Não tem como você me ajudar?}
{149}{}{Não tenho tempo para suas besteiras.}
{150}{}{Ótimo. Tchau.}
{151}{}{Olha só, a vida de uma jovem está em perigo. Filha de uma mãe preocupada. Não tem como você me ajudar? Por favor.}
{152}{}{Não dou a mínima... Sinto muito. Sou só uma vigia que foi contratada para ficar aqui guardando o caminho. 
 Fora isso, não sei o que está acontecendo. Eu já tive uma filha, mas, e... é, alguém passou aqui. 
 Deixei que passasse porque ele fez o sinal correto, igual ao que você me fez agora. Pode ir. Vou sair fora daqui.}
{153}{}{Obrigado. Não vou esquecer disso, Dalilia.}
{154}{}{Obrigado. Não vou esquecer disso, Dalilia.}
{155}{}{Então vá pro inferno e me deixe em paz!}
{156}{}{Pronto.}
{157}{}{Então vá pro inferno e me deixe em paz!}
{158}{}{Pronto.}
