{101}{}{Você vê Rebecca.}
{102}{}{Uma velha. Embora pareça ter tido uma vida dura, ainda não perdeu nem um pouco
 da sua beleza natural.}
{103}{}{Oi! Sou a Rebecca. Podemos conversar em particular?}
{104}{}{Sobre o que você quer conversar?}
{105}{}{Por que precisamos de privacidade?}
{106}{}{Ok.}
{107}{}{Não. Preciso ir.}
{108}{}{Desculpe, mas não me interessa.}
{109}{}{Sobre o que quer falar comigo?}
{110}{}{Ta bom, mas onde vamos conversar?}
{111}{}{Por que precisamos de privacidade?}
{112}{}{(murmurando) Minha filha desapareceu e preciso de ajuda pra encontrá-la.
 Mas não posso falar sobre isso aqui. Podemos ir pra um lugar mais particular?}
{113}{}{Ok.}
{114}{}{Por que precisamos de privacidade?}
{115}{}{Não. Preciso ir.}
{116}{}{Tudo bem, vamos lá.}
{117}{}{Por que precisamos de privacidade?}
{118}{}{Não, valeu. Não quero me envolve nisso.}
{119}{}{(murmurando) Pode pensar que sou louca, mas tenho a sensação de que estou sendo vigiado o tempo todo.
 E isso é perturbador. Estou um pouco nervosa por causa disso.}
{120}{}{Ok. Vamos conversar em particular.}
{121}{}{Não há tempo para dores de cabeça.}
{122}{}{Tudo bem, onde podemos ir para conversar?}
{123}{}{Desculpe. Mas isso não está me soando bem.}
{124}{}{Obrigada. Vamos pra minha tenda.}
{125}{}{Ok.}
{126}{}{Acho que aqui dá pra gente conversar.}
{127}{}{Ok. Qual é o problema?}
{128}{}{Tenho algumas perguntas primeiro.}
{129}{}{Ok, então o que é tão importante?}
{130}{}{Tenho algumas perguntas primeiro.}
{131}{}{Tenho uma filha chamada Chrissy que é um pouco levada. Ela adora rodar por aí, 
 explorar e meter seu nariz nas coisas. Mas é uma ótima jovem. Nunca dá problema, 
 chega sempre em casa na hora certa e se mostra uma jovem muito responsável. Deixo sempre ela fazer o que gosta. 
 Semana passada ela não voltou pra casa. Perguntei pelas redondezas, mas ninguém viu ou ouviu falar dela. Tentei encontrá-la eu mesma, mas Zeke, ele... é um tipo de prefeito aqui... Disse pra eu não ir. 
 Disse que não é seguro para eu sair por aí atrás dela. Ele mandaria alguns de seus homens fazerem isso. 
Mas eles não a encontraram e disseram que os traficantes de escravos podem ter pegado minha filha.}
{132}{}{Não, não vou me envolver nisso.}
{133}{}{Preciso pensar antes de decidir.}
{134}{}{Ok, parece que sou o único herói por aqui.}
{135}{}{Desculpe, mas isso não me interessa.}
{136}{}{Eu preciso pensar sobre isso.}
{137}{}{Tudo bem, Rebecca. Vou tentar te ajudar}
{138}{}{Se eu te ajudar, o que eu ganho?}
{139}{}{O que você quer saber?}
{140}{}{Porque ainda está aqui?}
{141}{}{Quem é o chefe?}
{142}{}{Estou tentando encontrar Vault 13. Você sabe onde fica?}
{143}{}{Conte-me sobre vault.}
{144}{}{Conte-me sobre Darion.}
{145}{}{Obrigado. Agora conte me do seu problema?}
{146}{}{O que está acontecendo por aqui?}
{147}{}{Quem é a autoridade aqui?}
{148}{}{Eu estou procurando Vault 13. Você sabe alguma coisa sobre isso?}
{149}{}{Conte-me sobre o vault.}
{150}{}{Então conte-me sobre Darion.}
{151}{}{Obrigado Rebecca. Agora vamos ao seu problema.}
{152}{}{Este lugar pode ser chamado de 'Acampamento' porque foi invadido por muitos desabrigados de várias cidades.
 Não é muito, mas é tudo o que temos. A oeste daqui fica uma cidade chamada NRC. Eles sabem da nossa existência há muito 
 tempo e nunca ofereceram nenhum tipo de ajuda ou obstáculo. Agora de repente resolveram reivindicar 
 esta área como a casa dos seus ancestrais, e a querem de volta.}
{153}{}{Ok.}
{154}{}{O que eles querem aqui?}
{155}{}{Entendi.}
{156}{}{Mas o que tem aqui para eles quererem tanto assim?}
{157}{}{Bem... existe um vault aqui; Acho que é o número 15. Eles querem saquear o Vault em busca de alguma velha 
 tecnologia que ainda pode estar lá.}
{158}{}{Ah. entendi.}
{159}{}{Eu sabia que tinha que haver alguma coisa aqui além desses habitantes imprestáveis.}
{160}{}{Entendi.}
{161}{}{Isso já explica muita coisa. Você foi muito útil. Mas preciso te fazer mais algumas perguntas.}
{162}{}{Seria o Zeke. Ele administra tudo aqui. Você pode encontrá-lo naquela construção ali. ::apontando para o nordeste::}
{163}{}{Obrigado. Mais perguntas.}
{164}{}{Obrigado. Preciso te perguntar mais algumas coisas.}
{165}{}{Sinto muito, mas não faço idéia. Se eu fosse você, perguntaria lá na NRC. Ultimamente eles tem tido um interesse imenso em refúgios.}
{166}{}{Ok, tenho que ir.}
{167}{}{Tudo bem, Eu vou.}
{168}{}{Bom... não podemos falar sobre isso, mas já que preciso de sua ajuda... Darion está consertando o vault.
 Ele é nosso benfeitor. Quando o vault estiver com tudo funcionando, todos nós nos mudaremos para lá, 
 onde estaremos seguros dos raiders, traficantes de escravos e tudo mais. Assim que ele acabar de consertar
 o sistema de alimentos e água.}
{169}{}{Entendi. Preciso saber de mais algumas coisas.}
{170}{}{Preciso saber de mais coisas.}
{171}{}{Não há muito a dizer, na verdade. Darion não fala nada e nunca deixa o vault. Quando ele tem algo a dizer, 
diz através de Zeke. Só o vi uma única vez, e ele pareceu ser um cara legal.}
{172}{}{Ok.}
{173}{}{Caras legais morrem virgens. Queria saber o que ele está planejando de verdade.}
{174}{}{Entendo.}
{175}{}{Tudo bem. Você foi muito útil.}
{176}{}{Não tenho nada pra te dar além da minha eterna gratidão.}
{177}{}{É o suficiente. Vou te ajudar.}
{178}{}{Minha ajuda custa mais.}
{179}{}{Que diabos, eu vou ajudá-lo.}
{180}{}{Muito obrigada. Nunca vou poder te retribuir isso. Vou esperar aqui até você trazer... Ei, 
tinha alguém ali fora nos escutando. Eu vi a sombra na tenda. Ele correu por ali! ::apontando para o nordeste:: 
 Deve ter escutado tudo!}
{181}{}{Vou tentar pegá-lo!}
{182}{}{Não se preocupa, eu vou achar a garota.}
{183}{}{Ooops.}
{184}{}{Vou tentar pegá-lo!}
{185}{}{Eles não vão me impedir de encontrar sua filha.}
{186}{}{Ah... merdas acontecem.}
{187}{}{Por favor, vá embora.}
{188}{}{E aí, já pensou a respeito?}
{189}{}{Queria te fazer algumas perguntas.}
{190}{}{Não, ainda estou pensando.}
{191}{}{Não, mas ainda estou pensando no assunto.}
{192}{}{Queria te fazer algumas perguntas.}
{193}{}{Mudou de idéia? Vai me ajudar?}
{194}{}{Desculpe. Não.}
{195}{}{Vou ajudar.}
{196}{}{Sim, vou te ajudar.}
{197}{}{Você deve ser a pessoa que salvou minha filha. Nunca vou poder retribuir a sua bondade. Obrigada. 
Espere aqui, por favor. Preciso conversar com a Chrissy e gostaria de falar com você também.}
{198}{}{Você salvou minha filha. Nunca vou poder retribuir a sua bondade. Obrigada. Espere aqui, 
por favor. Preciso conversar com Chrissy e gostaria de conversar com você também.}
{199}{}{Ok.}
{200}{}{Minha filha me contou tudo. É difícil acreditar que Darion é esse monstro depois de tudo o que tem feito por nós. 
 E pensando bem, estamos ajudando ele a esconder suas operações como raider. Posso te garantir que não vamos permitir isso 
nem mais um minuto. Já falei com Zeke e ele quer te ver. Acho melhor você ir falar com ele agora.}
{201}{}{Minha filha me contou tudo. É difícil acreditar que Darion é esse monstro depois de tudo o que tem feito por nós. 
 E pensando bem, estamos ajudando ele a esconder suas operações como raider. Posso te garantir que não vamos 
permitir isso nem mais um minuto. Vou falar com Zeke e explicar tudo. Tenho certeza de que ele vai querer ver você. 
 Você deveria falar com ele depois.}
{202}{}{Obrigado.}
{203}{}{Tomara que encontre Chrissy logo.}
{204}{}{Eu to procurando.}
{205}{}{Vou continuar minha busca por ela.}
{206}{}{Obrigada por tudo que fez por mim.}
{207}{}{Não sei explicar o porquê, mas não acredito que os traficantes de escravos a pegaram. Estou com um mau pressentimento
 de que algo ruim está para acontecer. Além da sensação de estar sendo seguida. Comecei a ter isso depois que falei com Zeke sobre Chrissy. 
 Preciso de ajuda para encontrar minha filha. Por favor, você vai me ajudar?}
{208}{}{Eles ficam mandando pessoas aqui pra tentar nos convencer a sair da nossa casa, mas eles não entendem 
 que não temos lugar nenhum pra ir. Não temos as habilidades necessárias para sobreviver se sairmos daqui.}
{209}{}{Sabe, é um pouco engraçado eles terem conseguido consertar alguma coisa tão complexa, exceto as luzes. 
 O maldito lugar é iluminado por tochas. De qualquer maneira, Darion não quer que ninguém saiba o que está acontecendo no vault. 
 Ele tem medo que alguém tome tudo da gente se descobrir. Por isso, foi dito pra gente mandar embora todo mundo que aparecer aqui 
 -- especialmente da NRC.}
