{100}{}{Você vê uma posseira.}
{101}{}{Você vê Roberta, uma posseira.}
{102}{}{Você vê uma mulher de meia-idade vestindo roupas esfarrapadas.}
{103}{}{Ah, meu Deus. Peço desculpas, mas não tenho nada pra te falar. Vá embora, por favor.}
{104}{}{Vá embora, por favor. Não quero ser incomodada.}
{105}{}{Obrigada por ajudar a Rebecca. Eu estava errada sobre você.}
{106}{}{Não ofereço nenhuma ameaça a você. Não me mate!}
