{100}{}{Você vê uma posseira.}
{101}{}{Você vê Sara, uma posseira.}
{102}{}{Você vê uma mulher de meia-idade com vestidos esfarrapados.}
{103}{}{Por favor não me incomode. Estou muito ocupada no momento.}
{104}{}{Vá embora, por favor. Não tem nada aqui pra você.}
{105}{}{Obrigada por ajudar a Rebecca. Vindo de um forasteiro é uma coisa maravilhosa.}
{106}{}{Não sou ameaça a você. Não me mate.}
