{100}{}{Você vê um técnico.}
{101}{}{Você vê um técnico da Enclave.}
{102}{}{Você vê alguém vestindo um jaleco de laboratório. Ele parece confiante e seguro de si.}

{103}{}{Sim, soldado?}
{104}{}{Que lugar é esse?}
{105}{}{Mim só passar pra dizer oi. Mim ir agora.}
{106}{}{Que lugar é esse?}
{107}{}{Só dando um olá. Até logo.}

{108}{}{Essa é a sala do computador. Bem ali está o mainframe, o terminal de interface próximo a ele e aquelas são as unidades de armazenamento de informação dos holotapes. É o último modelo. E o melhor.}
{109}{}{Hã... o que você fazer?}
{110}{}{Então... o que você faz aqui?}

{111}{}{Eu sou o analista dos computadores. Eu cuido da manutenção de todos os equipamentos aqui.}
{112}{}{Hum. Mim pode usar computador?}
{113}{}{Mim não entender nada. Mim ir.}
{114}{}{Então, posso usar o sistema por um minuto? Você sabe, dar uma checada?}
{115}{}{Ei, foi legal falar com você. Te vejo mais tarde.}

{116}{}{Bem... eu não tenho permissão pra deixar pessoal não treinado usar o equipamento. É tudo muito complexo e delicado, entende?}
{117}{}{Por favor? Mim não quebra.}
{118}{}{Eu prometo que não quebro nada.}

{119}{}{Tudo bem. Você pode acessar o sistema por aquele terminal bem ali. Só tome cuidado, por favor. Eles atiram em nós dois se você danificar aquela máquina. Ah, a senha para visitantes é 'Snookie'.}
{120}{}{Sinto muito, mas está fora de questão. Eu nem poderia deixar os alistados ficarem na sala, muito menos permitir que usem o equipamento.}
{121}{}{Snookie? O que é snookie?}
{122}{}{Certo. Eu entendi.}
{123}{}{Snookie? Que diabos é snookie?}
{124}{}{Tudo bem. Eu entendo.}

{125}{}{‘Snookie’ é o apelido da minha namorada. Eu acho bonitinho. Aliás, ela é aquela lá na entrada. Ela é um dos guardas.}
{126}{}{Certo, legal. Valeu.}
{127}{}{É... bonitinho. Valeu.}

{128}{}{Você está sem a farda. }
{129}{}{É melhor você se vestir. O depósito de armaduras fica no andar de baixo à esquerda.}
{130}{}{Você está se arriscando em andar por aí sem farda. É melhor requisitar alguma no depósito.}

{131}{}{Quem diabos são vocês... Alerta! Intrusos!}
{132}{}{Nós fomos descobertos! Alerta!}
{133}{}{Vários intrusos! Soem o alarme!}

{134}{}{Merda! Inicie os backups.}
{135}{}{Desative todas as operações secretas.}
{136}{}{Mantenham o sistema seguro e ativem os códigos de segurança.}

{137}{}{Eu sou um cientista, não um lutador!}
{138}{}{Mirar no inimigo com a ponta onde está o diodo do laser. Então puxar o gatilho.}
{139}{}{Socorro! Socorro! No laboratório do computador!}
