# 0. Look
{100}{}{Você vê um cidadão do Den.}
{101}{}{Você vê Fred.}
{102}{}{Você vê Fred, usando roupas muito finas.}

{150}{}{Ele parece estar ocupado pensando em algo.}
{151}{}{Ele parece estar muito feliz com as suas novas roupas.}

# 1.  Fred B4 Becky's Job (From Where to go)
{200}{}{Eu irei conseguir a sorte grande algum dia.}
{201}{}{Oh, me deixe em paz. Estou ocupado.}
{202}{}{O plano chefe…}
{203}{}{Ainda irei entender direitinho isso um dia…}
{204}{}{Porque eu sempre perco?}
{205}{}{As mesas devem estar viciadas.}
{206}{}{...eu irei ganhar o meu próprio espaço algum dia.}
{207}{}{Indo ganhar belas roupas.}

# 2. Night (From Where to go)
{220}{}{Ei, cara! Já ta tarde. Me deixa em paz.}
{221}{}{Não, eu não preciso de nenhuma companhia.}
{222}{}{Você sabe que horas são?}
{223}{}{Eu não tenho nada.}
{224}{}{Me incomode pela manhã. Estou exausto.}
{225}{}{Cai fora.}
{226}{}{Ninguém em casa.}
{227}{}{Não posso falar. To indo pra cama.}
{228}{}{Ei, moça! Está tarde. Me deixe em paz.}

# 3. Paid, Broke Floats (From Where to go)
{240}{}{Sem mais dinheiro! Me deixe em paz.}
{241}{}{Não há trabalho. O que vou fazer?}
{242}{}{Não me diga que eu te devo algo! Ahh!}
{243}{}{Eu nunca mais estarei tirando a sorte grande agora.}
{244}{}{Estou tão quebrado.}
{245}{}{Oh cara, eu preciso de um pouco de dinheiro.}
{246}{}{Nunca mais irei conseguir comprar novas roupas agora.}
{247}{}{Preciso conseguir um novo plano chefe agora…}

# 4. Covered, Floats (From Where to go)
{260}{}{Obrigado por ter me ajudado!}
{261}{}{Você é realmente um salvador de vidas.}
{262}{}{Terei o dinheiro para você rapidinho.}
{263}{}{Ganharei isso bem a qualquer momento agora!}
{264}{}{Você é a primeira pessoa que eu irei ver quando ganhar isso vem.}

# 5. Covered and Loaned, Floats (From Where to go)
{275}{}{O plano chefe está em ação!}
{276}{}{Obrigado pelo empréstimo! O seu dinheiro está em boas mãos!}
{277}{}{Com certeza essas mesas são duras, mas não precisa se preocupar.}
{278}{}{Irei ganhar bem em algum dia, muito obrigado a você.}
{279}{}{Serei recompensado a qualquer dia! Posso sentir isso.}
{280}{}{Estarei lhe pagando de volta, eu juro!}
{281}{}{Estarei logo ganhando isso bem. Sinto o cheiro disso.}

# 6. 1st Time on Job 1 (From Where to go)
{295}{}{Ahn? Eu te conheço? O que você quer?}
{296}{}{Porque você continua me incomodando? Eu nem mesmo conheço você. Vá encher outra pessoa.}
{297}{}{Estou aqui pra coletar algum dinheiro que Você deve pra alguém.}
{298}{}{Não importa.}
{299}{}{Uk!}
{300}{}{Tchau.}

# 7. Won It BIG! (From Where to go)
{310}{}{Ei! Aí está você! Eu estive procurando em todo lugar por você! Olha só essas roupas!}
{311}{}{Obrigado de novo.}
{312}{}{Está parecendo muito legal.}
{313}{}{Você parece um lixo!}
{314}{}{Credo!}
{315}{}{Urgh.}

# 8. Look nice (From 7)
{320}{}{Muito obrigado. Muito obrigado mesmo! Meus agradecimentos a você, eu tenho 4 conjuntos exatamente como esse!}
{321}{}{Então você ganhou isso depois de tudo?}
{322}{}{Então, cadê meu dinheiro?}

# 9. Look bad (From 7)
{330}{}{Você não gostou das minhas roupas? Sabe, eu acho que você ta certo. Eu também não gosto delas. Hora de roupas novas - eu posso bancar isso!}
{331}{}{Então você tirou a sorte grande depois de tudo?}
{332}{}{Cadê meu dinheiro?}
{333}{}{Hmph.}

# 10. Give me money 1 (From 8, 9)
{340}{}{Eu estava chegando lá! Não vai nem ao menos deixar eu me deliciar da minha glória? Eu batalhei duro por isso, você sabe.}
{341}{}{Eu sei, me desculpe.}
{342}{}{Foda-se isso. Onde está o dinheiro que eu emprestei a você?}
{343}{}{To cagando e andando. Cadê meu dinheiro?}

# 11. Give me money 2 (From 10)
{350}{}{Perfeitamente. Aqui. [Fred te dá $500] Aqui vai um extra por ter acreditado em mim. Bem, nos vemos por aí. Obrigado novamente.}
{351}{}{Obrigado!}
{352}{}{Que seja.}

# 12. Covered 1 (From 8-10)
{360}{}{Muito obrigado por ter coberto minhas dívidas. Isso realmente significou bastante para mim, ser acreditado por um completo estranho. Deixe-me dar-lhe isso.}
{361}{}{Ok.}
{362}{}{Você não precisa.}
{363}{}{Uh.}

# 13. Loaned 1 (From 8-10)
{370}{}{Eu te devo demais. Você acreditou em mim quando eu estava na minha maré de azar. Como um pequeno gesto de gratidão eu tenho isso pra lhe dar.}
{371}{}{Ok.}
{372}{}{Você não precisa.}
{373}{}{Uh.}

# 14. Covered 2 (From 12)
{380}{}{Aqui. [Fred te dá $1000.] Espero que isso ajude. Tenho certeza de que você irá encontrar algum lugar pra gastar isso.}
{381}{}{Me desculpe, mas eu não posso aceitar isso.}
{382}{}{Obrigado.}
{383}{}{Na verdade não, mas eu irei aceitar isso.}
{384}{}{Hum.}

# 15. Loan 2 (From 13)
{390}{}{Aqui. [Fred te dá $2000, 5 Fusion Cells, 5 Energy Cells, e uma Plasma Grenade.] Espero que isso ajude, pelo menos um pouco.}
{391}{}{Me desculpe, mas eu não posso aceitar isso.}
{392}{}{Muito obrigado.}
{393}{}{Na verdade não, mas eu irei aceitar isso.}
{394}{}{Hum.}

# 16. Refused reward (From 15)
{400}{}{O quê? Ah, tudo bem, se você insiste. Muito obrigado mesmo. Tome bastante cuidado por aí.}
{401}{}{Tchau.}

# 17. Dumb, beat it (From 6)
{410}{}{O quê? Você fazendo alguma droga estranha? Você não parece um viciado em jet. Sai de perto de mim seu drogado.}
{411}{}{Sai pra lá!}
{412}{}{Ug.}

# 18. Here to collect (From 6)
{420}{}{Do que você tá dizendo? Eu não te devo nada. Sobre o que diabos você está falando?}
{421}{}{Certo, você me disse da última vez. Eu não sei sobre o que você está falando? Quem é essa pessoa imaginária agora?}
{422}{}{Becky diz que você deve a ela $500}
{423}{}{Becky me enviou.}
{424}{}{Rebecca diz que ela te emprestou $200.}

# 19. Sure she lent me $200 (From 18)
{430}{}{Ah sim, claro. Rebecca me emprestou $200… Ah, espera. Talvez- hummm…}
{431}{}{Ela me disse pra quebrar o seu pescoço se você não pagar.}
{432}{}{Passe isso logo.}

# 20. Owe $500 (From 18)
{440}{}{Ok, certo. Eu nunca vi tanto dinheiro na minha vida.}
{441}{}{Hmmm.}
{442}{}{Oh.}

# 21. Becky Swear or Pissed (From 19)
{450}{}{Certo! Este vai ser o dia. Becky não conseguiria machucar uma mosca. Ela é uma beleza de qualquer forma.}
{451}{}{Bem, você ta errado, cuzão.}
{452}{}{Talvez tenha sido outra pessoa.}

# 22. Remembers money (From 19, 33-35)
{460}{}{Maldição. Eu acho que você está certo, mas - eu to quase quebrado. Eu não posso bancar essa quantia! Eu tenho de comer, você sabe.}
{461}{}{Desculpe.}
{462}{}{Má sorte.}

# 23. Tuff Luck (From 22)
{470}{}{Ah, diabo. eu mal posso bancar $100. Você poderia me cobrir metade? Eu prometo que vou te pagar de volta!}
{471}{}{Não, sinto muito.}
{472}{}{Vamos lá. Pague agora toda a quantia!}
{473}{}{Ok, muito bem.}

# 24. Will pay 200 (From 23, 37)
{480}{}{Diabos. Você está me arruinando! Bem, ok, aqui. Agora eu to completamente quebrado.}
{481}{}{Oh, certo. Eu cobrirei você.}
{482}{}{Obrigado. Gerencie melhor o seu dinheiro na próxima vez.}
{483}{}{Obrigado pelos negócios.}

# 25. Failed Speech for Full amount (From 23, 37)
{490}{}{Eu te disse! Eu não posso! Irei morrer de fome se fizer isso. Oh, vamos lá, você não poderia me ajudar?}
{491}{}{Está certo. Eu cobrirei metade disso.}
{492}{}{Não, sinto muito. Eu também não tenho o dinheiro.}
{493}{}{Eu voltarei.}

# 26. PC will Cover (From 23-25, 29, 37)
{500}{}{O que? Sério? Uau! Muito obrigado, cara! Aqui está os $100. Eu vou te trazer os outros $100 assim que possível!}
{501}{}{O que? Sério? Uau! Muito obrigado, moça! Aqui está os $100. Eu vou te trazer os outros $100 assim que possível!}
{502}{}{Sem problema.}
{503}{}{É melhor você me pagar de volta.}

# 27. Better pay PC back! (From 26)
{510}{}{Ah, não se preocupe. Eu irei! Você tem a minha palavra que eu não me esquecerei dessa vez!}
{511}{}{Ok.}

# 28. Fred asks for Loan (From 26-27)
{520}{}{Diga, você sabe o que? Estes 100 realmente estará ahn... atrasando as coisas. Você acha que eu poderia estar emprestando um pouquinho de volta?}
{521}{}{Quanto?}
{522}{}{Sem chance.}

# 29. Wait I know… (From 25)
{530}{}{Espera! Eu sei. Te digo isso, eu te dou os $100 e você me cobre pelos outros $100 que eu devo à Becky. Eu irei te pagar de volta logo com certeza.}
{531}{}{Ok, certo.}
{532}{}{Sem chance.}

# 30. Amount of Loan (From 28)
{540}{}{Só $50. Por favor! Isto é tudo parte do plano chefe!}
{541}{}{Está certo.}
{542}{}{Mas isto irá me deixar com apenas $50 para pagar a sua dívida de $200.}
{543}{}{Não.}

# 31. PC gave Loan (From 30)
{550}{}{O qu- uh… droga! Você não vai se arrepender por isso! Eu sou bom nisso!}
{551}{}{Sem problema.}

# 32. Clarification of amount of loan (From 30)
{560}{}{Ahn, sim. Estou vendo as suas habilidades matemáticas- quero dizer, por favor! Não é muito pra você, tenho certeza, mas é um montão pra mim.}
{561}{}{Ok.}
{562}{}{Não.}

# 33. Becky sent PC (From 18)
{570}{}{Ahan, claro que ela mandou. Todo mundo sabe que ela odeia esse nome. Você não está zombando de mim!}
{571}{}{Eu não devo nada a ela.}
{572}{}{Ela disse que você era esquecido.}
{573}{}{Olha, Eu não tenho tempo pra isso. Pague agora, diabos!}
{574}{}{Rebecca disse que ela te emprestou isso a um tempo atrás.}

# 34. Forgetful (From 33)
{580}{}{Eu não sou! Eu… espera. Teve aquela vez. Eu não paguei ela de volta? Eu achava que tinha pago…}
{581}{}{Não, você não pagou. E é por isso que ela me mandou.}
{582}{}{Apenas pague agora para que eu possa cair fora daqui.}

# 35. Don't quite remember (From 33)
{590}{}{Eu não me lembro… Mas a Becky com certeza ajudou a mim e aos meus amigos no passado.}
{591}{}{Entregue os $200.}
{592}{}{Apenas me dê o dinheiro.}

# 36. Get out of here (From 33)
{600}{}{Me deixa em paz.}
{601}{}{Que seja.}
{602}{}{Ok.}

# 37. Remembers (From Where to go)
{610}{}{Uh. Oi de novo. Então, ahn, Eu suponho que você quer o dinheiro. Você acha que poderia me cobrir metade?}
{611}{}{Não, sinto muito.}
{612}{}{Se ela te emprestou $200, Você irá pagar isso.}
{613}{}{Ok, certo.}
