{100}{}{Você vê um mestre de caravana.}
{101}{}{Graças ao Criador por você ter aparecido. Está ficando cada vez mais difícil de ir
 de um lugar pra outro sem ser atacado por alguém ou por alguma coisa.}
{102}{}{O que eu posso fazer por você?}
{103}{}{Pra onde você está indo?}
{104}{}{O que está transportando?}
{105}{}{Tchau.}
{106}{}{Ug.}
{107}{}{Eu acabei de pegar um carregamento de  }
{108}{}{ e agora estou indo para }
{109}{}{.}

# Town Names
{198}{}{New Reno}
{199}{}{The Den}
{200}{}{Arroyo}
{201}{}{Redding}
{202}{}{Vault City}
{203}{}{NCR}
{204}{}{Broken Hills}
{205}{}{Gecko}
{206}{}{San Francisco}
{207}{}{Modoc}
{208}{}{Klamath}
{209}{}{Vault 15}

{110}{}{O que está transportando?}
{111}{}{Tchau.}
{112}{}{Nós estamos transportando }

# Cargo for the Caravan
{150}{}{produtos medicinais.}
{151}{}{minério de ouro.}
{152}{}{minério de urânio.}
{153}{}{produtos agrícolas/fazenda.}
{154}{}{drogas.}
{155}{}{escravos.}
{156}{}{coisas.}

{113}{}{Será que eu poderia trocar algo com você?}
{114}{}{Pra onde você está indo?}
{115}{}{Tchau.}
{116}{}{Bem, eu não vejo por que não, considerando que você nos ajudou. Claro, por que não? Aqui está o que eu tenho.}
{117}{}{[Trocar]}
{118}{}{Eu mudei de idéia}
{119}{}{Eu sei que já te vi em algum lugar... Puta merda! É você em todos aqueles pôsteres! Olha, nós
 não queremos problemas. Você segue o seu caminho que nós seguimos o nosso. Eu não vou sequer contar pra alguém que te vi.
 Vá agora!}
{120}{}{Ei! É você em todos aqueles pôsteres! Não se preocupe, eu não vou te fazer mal; se não me falha a memória,
 eu também sou procurado em vários lugares. Agora, você queria trocar...}
{121}{}{[Trocar]}
{122}{}{Certo, então. Nós temos que ir. Não se preocupe, não vou dizer pra lei que te vi.}
{123}{}{Espere um minuto! Eu ouvi falar de você. Você é aquele bem feitor que anda por aí salvando e ajudando
 as pessoas. Nós não gostamos do seu tipo, então se manda!}
{124}{}{Eu ouvi falar de muitas coisas boas sobre uma pessoa bem parecida com você. Acho não há problemas
 e trocar um pouco de nossa carga com você. Aqui está o que eu tenho.}
{125}{}{[Trocar]}
{126}{}{Tchau.}
{127}{}{Eu ouvi falar de você. Você é aquele malfeitor que vem causando problemas em vários lugares. Eu
 estava mesmo querendo te encontrar pra poder apertar a sua mão. Só de pensar em todos os rumores rudes e cruéis sobre você
 me dá vontade de chorar. Seria uma honra negociar com você.}
{128}{}{[Trocar]}
{129}{}{Tchau}
{130}{}{A questão é que é você ou alguém que parece você está causando problemas ultimamente. Eu não faço negócios
 com o seu tipo. Desculpe.}
{131}{}{Eu não sei pelo que está sendo procurado e sequer me importo. Nós não fazemos negócios com o seu
 tipo.}
{132}{}{Por que você não vai... 'fazer coisas boas' em outro lugar. }
{133}{}{Tenho certeza de que alguém com a sua reputação pode conseguir fazer negócio em outro lugar.}
{134}{}{O que você quer?}
#State your business.
{135}{}{Pra onde está indo?}
{136}{}{O que está transportando?}
{137}{}{Tchau.}
{138}{}{Ug.}
{139}{}{Isso é... legal. Tenha um bom dia. }

{300}{}{Agradeço pelo serviço.}
