{100}{}{Você vê um punk careca.}
{101}{}{Você vê Chip. Ele parece melhor.}
{102}{}{Você vê um punk careca. Ele parece muito melhor.}
{103}{}{Ooh, minhas tripas... ow, ow, ow.}
{104}{}{Bolas?}
{105}{}{Ai?}
{106}{}{Qual o problema com você?}
{107}{}{Está doendo? Ha ha ha.}
{108}{}{Quem é você?}
{109}{}{Você tem alguma informação sobre o meu povo?}
{110}{}{Aaii, minhas tripas. Que dor. Me deixe quieto, por favor.}
{111}{}{Tuuuuudo bem.}
{112}{}{Qual o problema comigo? Vou te dizer: é que eu fiquei bêbado semana passada, comecei a jogar com o Lao Chou, e perdi. Eu tava tão bêbado que apostei o meu próprio baço. Agora isso é dele, e eu preciso de volta.}
{113}{}{Você VENDEU o seu baço?}
{114}{}{Isso é péssimo.}
{115}{}{Cara, você é uma anta.}
{116}{}{Pois é, então, eu preciso que você me dê algumas informações ao invés de ficar choramingando.}
{117}{}{::ele dá uma respirada forte:: Vá se fuder.}
{118}{}{::ele dá uma respirada forte:: Sai daqui.}
{119}{}{Ta bom, que seja.}
{120}{}{Ei, mudei de idéia. Eu quero ajudar.}
{121}{}{Sim, eu vendi. Eu tava bêbado! E tem outra, eu acho que o Lao Chou jogou algum jet na minha bebida. Eu preciso do meu baço de volta porque eu to começando a ficar com algumas infecções agora.}
{122}{}{Ei, você perdeu isso. O problema é seu. Você resolva isso.}
{123}{}{Bem, droga, vou tentar resolver isso.}
{124}{}{Sim, isso mesmo. Eu preciso do meu baço de volta porque eu to começando a ficar com algumas infecções.}
{125}{}{Ei, você perdeu isso. O problema é seu. Você resolva isso.}
{126}{}{Bem, droga, vou tentar resolver isso.}
{127}{}{Eu realmente ficaria feliz com isso. Converse com Lao Chou, o comerciante, e diga a ele que eu preciso de meu baço de volta.}
{128}{}{Eu volto.}
{129}{}{Sou Chip. E to sentindo muitas dores.}
{130}{}{Qual o problema com você?}
{131}{}{Ta sentindo dores? Ha ha ha.}
{132}{}{Isso é péssimo. Até mais.}
{133}{}{Informação? Eu morrendo de dores e você quer informação?}
{134}{}{Qual o problema com você?}
{135}{}{Ta sentindo dores? Ha ha ha.}
{136}{}{Esqueça.}
{137}{}{Você já encontrou o meu baço?}
{138}{}{Sim. Está com o Dr. Wong Yi Tze, e ele te dará de volta. Vá falar com ele sobre isso.}
{139}{}{Sim. Dê uma olhada no cadáver do Dr. Wong.}
{140}{}{Meio que ta com o Dr. Wong Yi Tze. Ele não quer dar isso pra mim.}
{141}{}{Eu descobri onde que ta, mas acho que o Dr. Wong acabou de comê-lo.}
{142}{}{Não, ainda não. Mas irei.}
{143}{}{Não. Na verdade nem to procurando.}
{144}{}{Está certo. ::ofegante:: Antes que eu o faça, talvez nós devêssemos dar um jeito de colocar isso de volta em mim. Fale com o Dr. Fung sobre isso, ok? Obrigado.}
{145}{}{Tudo bem.}
{146}{}{Não.}
{147}{}{Eu realmente estou feliz pelo que você está fazendo por mim. Não vou me esquecer disso.}
{148}{}{Sem problema.}
{149}{}{Cara, eu não consigo mesmo sair daqui sem fazer esforço demais. Se você não puder me ajudar, eu to ferrado.}
{150}{}{Beleza. Vou falar com o Fung.}
{151}{}{Beleza. To pouco me fudendo pra você mesmo.}
{152}{}{Se você puder fazer alguma coisa sobre isso... mate ele, ou dê um pouco de juízo a ele, ou o que for... eu vou morrer se ficar sem isso.}
{153}{}{Verei o que posso fazer.}
{154}{}{Desculpa, cara... acho que você ta fudido. Não posso te ajudar.}
{155}{}{Sem o baço, vou morrer de qualquer jeito. Mas obrigado pela sua ajuda de qualquer jeito.}
{156}{}{Encontrei. Vá procurar na sala do Dr. Wong.}
{157}{}{Oh, eu te cubro. Vá até a sala do Fung.}
{158}{}{Sem problema. Boa sorte.}
{159}{}{Você falou com o Fung?}
{160}{}{Falei, ele disse que vai colocar isso em você de graça.}
{161}{}{Sim, ele ta me devendo $1,000.}
{162}{}{}
{163}{}{Caramba. Você tem alguns contatos sérios. Volte aqui amanhã e eu verei o que posso fazer por você.}
{164}{}{Você entendeu.}
{165}{}{Você pode me cobrir?}
{166}{}{Sim, eu acho.}
{167}{}{Não.}
{168}{}{Eu realmente apreciaria isso. Volte aqui em um dia e verei o que posso fazer por você.}
{169}{}{É melhor.}
{170}{}{Eu não posso pagar isso sozinho. Eu acho que vou acabar morrendo.}
{171}{}{Oh, tudo bem, eu cubro você.}
{172}{}{É duro. To quebrado.}
{173}{}{Não consigo te dizer como estou melhor. Então, o que é que você precisava de mim?}
{174}{}{Como eu consigo fazer esse barco navegar?}
{175}{}{Onde está o meu povo? Você sabe?}
{176}{}{Eu preciso que seja feita um trabalho no computador.}
{177}{}{Por ora nada, obrigado. Tchau.}
{178}{}{Pergunte ao Capitão. Ele fica no gabinete do capitão lá em cima.}
{179}{}{Obrigado. Outras perguntas...}
{180}{}{Obrigado. Tchau.}
{181}{}{O que dizem é que eles foram levados para o oeste, através do oceano. O melhor que você pode fazer é botar essa banheira pra funcionar.}
{182}{}{Obrigado. Outras perguntas...}
{183}{}{Obrigado. Tchau.}
{184}{}{Trabalho no computador? Se você não conseguir isso com os Shi ou os Hubologistas, você deve falar com o Badger. Ele é foda.}
{185}{}{Obrigado. Outras perguntas...}
{186}{}{Obrigado. Tchau.}
{187}{}{Merda. Fale com os Hubologistas ou com os Shi. Com o Badger, eu não faço idéia.}
{188}{}{Obrigado. Outras perguntas...}
{189}{}{Obrigado. Tchau.}
{190}{}{Desprezível.}
{191}{}{Você vai precisar de alguns analgésicos.}
{192}{}{Imprestável. Vou acabar com você.}
{193}{}{Você vê um punk careca.}
{194}{}{Você vê Chip. Ele parece melhor.}
{195}{}{Você vê um punk careca. Ele está parado no seu canto, e arfando dolorosamente.}

{196}{}{Tudo bem. Vou falar com o Fung.}
{197}{}{Alguma sorte com o meu baço?}
{198}{}{Sim, e ele quer $1000 - mas eu paguei isso.}
{199}{}{Obrigado pela ajuda, amigão.}
{200}{}{Cara, fiquei sabendo que você encontrou o meu baço. Você falou com o Dr. Fung para colocar isso de volta em mim?}
