{100}{}{Você vê um homem baixo e gordo de Shi.}
{101}{}{Você vê o Dr. Wong Yi Tze.}
{102}{}{Você vê um homem baixo e gordo de Shi.}
{103}{}{Posso te ajudar com algo?}
{104}{}{Daghi nu?}
{105}{}{Quem você é?}
{106}{}{Eu ouço que você tem algo diferente.}
{107}{}{Quem é você?}
{108}{}{O que você faz aqui?}
{109}{}{Não, obrigado. Isso é tudo.}
{110}{}{Eu tenho que confessar, Eu não falo sua língua. Talvez você deva falar com o Ken Lee, ele entende muitas línguas diferentes.}
{111}{}{Aagh!}
{112}{}{Eu sou o Dr. Wong. Eu sou o cientista chefe dessa instalação.}
{113}{}{Mais algumas dúvidas, por favor.}
{114}{}{Obrigado. Tchau.}
{115}{}{Eu comando os experimentos científicos que nós criamos e fazemos aqui. Eu sou o encarregado da rede de computadores.}
{116}{}{O que você está planejando?}
{117}{}{Como alguém consegue acesso à rede de computadores?}
{118}{}{Eu tenho outras perguntas.}
{119}{}{Vejo. Tchau.}
{120}{}{Ah, mas se eu te contar sobre os nossos planos, então todo mundo saberá. Eu quero ter certeza que eles são planos secretos, por enquanto.}
{121}{}{Está bem, está bem. Eu tenho outras perguntas.}
{122}{}{Obrigado. Tchau.}
{123}{}{O que você acha se eu enfiar uma arma embaixo do seu nariz e forçar você a me dizer?}
{124}{}{Quem aprender a hackear ele, ou fazer amizade com um de meus homens. Estou brincando, é claro, sobre hackear ele - se você está aqui para fazer isso, eu mandaria alguém atrás de você para te matar. [Ele sorri para mostrar que não existe nenhuma ofensa.]}
{125}{}{Você realmente quer me matar?}
{126}{}{Então você fará objeção se eu acessar o computador?}
{127}{}{Eu tenho algumas outras perguntas.}
{128}{}{Claro que você pode. Tchau.}
{129}{}{Então teria que considerar ele como uma ameaça e te advertir que essa ação talvez seja prejudicial a sua saúde.}
{130}{}{Vamos ver.}
{131}{}{Eu só estava brincando. Eu tenho outras perguntas.}
{132}{}{[Ele sorri] Nós devemos proteger nossa honra, estranho.}
{133}{}{Err, certo. Então você faria objeção se eu acessar o computador?}
{134}{}{Ceeerto. Eu tenho outra pergunta.}
{135}{}{Apostarei. Tchau.}
{136}{}{Se você conseguir convencer meus homens a deixa-lo entrar. Mas tenho certeza que não conseguirá.}
{137}{}{E se eu colocasse uma arma embaixo do seu nariz?}
{138}{}{Ótimo. Bem, eu tenho mais algumas perguntas.}
{139}{}{Hmm. Vejo. Bem, tão longo.}
{140}{}{Ahh, sim! De fato. Eu irei preparar isso com feijões de fava e um bom chianti.}
{141}{}{Você ainda tem isso? Bom. O Chip precisa voltar.}
{142}{}{Isso é um baço humano, você é um doente!}
{143}{}{Você supostamente deve saber que devia servir fígado com esse vinho ao em vez de baço, certo?}
{144}{}{Isso é um baço humano, você sabe.}
{145}{}{Quem é esse Chip? É meu baço agora, e eu o tenho agora para jantar.}
{146}{}{Chip é o verdadeiro dono do baço. Ele estava bêbado e o vendeu para o Lao Chou.}
{147}{}{Ele precisava para sobreviver, você sabe. Isso veio de dentro do corpo dele.}
{148}{}{Então talvez seria melhor eu te matar por ele.}
{149}{}{Um acordo é um acordo. Ele não pode tê-lo. Desculpe, mas nós fizemos um acordo e não é só porque o Chip se arrependeu que ele poderá voltar atrás no acordo.}
{150}{}{-mais-}
{151}{}{Isso é um baço humano? Lao Chou não me disse isso!}
{152}{}{Ainda, por causa da rudeza do mensageiro, eu acredito que manterei todas as partes do acordo. Experimentarei ele em vez disso.}
{153}{}{Diga ao seu amigo para vir aqui amanhã, e eu felizmente o devolverei à ele. Eu só espero que você consiga achar um jeito de recolocar isso dentro dele a tempo.}
{154}{}{Muito bem.}
{155}{}{Ha ha! Sim, eu já vi esse filme antes.
Espere... O que você está dizendo? Você está dizendo que...?}
{156}{}{Sim, é um baço humano.}
{157}{}{Na verdade, eu iria me opor a isso. Você mostrou não ser de bom caráter. De fato, não sei porque ainda estou falando com você . Tenha um bom dia.}
{158}{}{-feito-}
{159}{}{Aiee! Guardas! O intruso está aqui!}
{160}{}{Você com certeza tem um esquema para mim?}
{161}{}{Ken Lee me disse para te dar isso.}
{162}{}{Sim. Agora como que eu pego?}
{163}{}{Não, ainda não.}
{164}{}{Fale com o Ken Lee, e ele te dirá o que vai acontecer no seu futuro. Obrigado. Nós seremos capazes de verificar alguns de nossos testes com esse. Tenho um bom dia.}
{165}{}{Na verdade eu tenho outras perguntas.}
{166}{}{Tão longo.}
