{100}{}{Um garotinho.} 
{101}{}{Jonny.}
{102}{}{Cabelo louro, olhos azuis; um típico garoto americano da cabeça aos pés.} 

{150}{}{Buááa!} 
{151}{}{Quero meu cachorro de volta!} 
{152}{}{Sniiifff... } 
{153}{}{Um estranho!} 
{154}{}{Laddie! Senti sua falta. Obrigado por devolver meu cão.} 
{155}{}{Olá, nunca te vi por aqui antes.} 
{156}{}{Seu nome é Jonny?} 
{157}{}{Qual é o seu nome, garoto?} 
{158}{}{Me fale seu nome, monstrinho.} 
{159}{}{Quer um doce, garotinho?} 
{160}{}{Oi de novo.} 
{166}{}{Seus pais me pediram pra te buscar.} 
{168}{}{Já falou com Vegeir sobre minha volta pra casa?} 
{169}{}{Falei sim. Ele quer que seus pais desçam aqui pra te buscar.} 
{170}{}{Não, ainda não.} 
{171}{}{Meu pai disse que Laddie foi com você me procurar. Cadê ela? To com saudades.} 
{172}{}{Sinto muito, Jonny. Laddie morreu enquanto estávamos te procurando.} 
{173}{}{Rose disse que ia atrás da sua cadela.} 
{174}{}{Meu nome é Jonny. E o seu?} 
{175}{}{Me chamo } 
{176}{}{.}
{177}{}{Meu nome não vem ao caso.} 
{178}{}{Meu nome é Jonny e eu não gosto de você.} 
{179}{}{[Ele aponta pra você e começa a berrar.] Um estranho! Um estranho! Um estranho!} 
{180}{}{Muito bom te ver } 
{181}{}{.}
{182}{}{Te vejo por aí, garoto.} 
{183}{}{Que bom! Quero ir pra casa, mas Vegeir disse que seu pessoal não pode andar pela superfície 
 e por isso não podem me levar. Não que eu suspeite de você, mas qual é o nome do meu pai?}
{184}{}{Farrel.}
{185}{}{Cornelius.}
{186}{}{Balthas.}
{187}{}{Davin.}
{188}{}{Joshua.}
{189}{}{Não confia em mim, Jonny?} 
{190}{}{Hmm.. não. Valeu por devolver meu cão, mas agora tenho que ir. Tchau.} 
{191}{}{Vou bom te ver, mas agora tenho que ir. Tchau.} 
{192}{}{Isso mesmo! Oba! Vou pra casa. Pergunte ao Vegeir se eu posso voltar com você. Ele tem sido tão bom pra mim, 
 não quero ir embora sem a permissão dele. Se apresse, por favor. Tô com saudades da minha casinha.} 
{193}{}{Tudo bem, senhor, confio em você. Pergunte ao Vegeir se ele deixa você me levar pra casa. 
 Ele tem sido tão legal comigo, não quero ir embora sem a permissão dele.}
{194}{}{Tudo bem, senhorita, confio em você. Pergunte ao Vegeir se você pode me levar pra casa. 
 Ele tem sido tão legal comigo, não quero ir embora sem a permissão dele.}
{195}{}{Não. Agora vou brincar com meus amigos. Tchau.} 
{196}{}{Não posso falar com estranhos. Tchau.} 
{197}{}{E isso mesmo! Como soube? Laddie deve ter te contado. Ela é uma cadela muito inteligente.}
{199}{}{Você vem comigo, garoto. Tá rolando uma recompensa pra quem te trazer de volta.}
{200}{}{Acho que é melhor assim mesmo. Mesmo que eu confie em você, tenho certeza que Vegeir só 
 quer ter certeza que vou chegar em casa seguro. Obrigado pela sua ajuda.}

{201}{}{Por favor, se apresse. Quero ir pra casa logo.} 
{202}{}{Não, eu não acredito em você! Me dá meu cão de volta! [Buáááá!]} 
{203}{}{Ah não! Vai dizer que você não sabia que a Rose usa carne de cachorro nos pratos dela? A essa hora Laddie já virou hamburguer.}

{300}{}{Laddie!!!}

{400}{}{Valeu por me salvar, Senhor.} 
{401}{}{E muito bom estar em casa!} 
{402}{}{Wahoo...} Viva!!!!
{403}{}{Não tenho mais medo do escuro.} 
{404}{}{Obrigado por me salvar, senhora.}
